### ISSUE TITLE
Texture problem?

### ISSUE THREAD

**Issue by MakeLord95** [mekanism/Mekanism#1048]
I'm using Mekanism v6.0.1.13, and I have an error with few of the textures!

This is the list of items that have no texture in-game, but in the Mekanism .jar file they still exist...

Iron Clump, 
Gold Clump, 
Osmium Clump, 
Copper Clump, 
Tin Clump, 
Silver Clump, 
Obsidian Clump, 
Lead Clump, 
Dirty Iron Dust, 
Dirty Gold Dust, 
Dirty Osmium Dust, 
Dirty Copper Dust, 
Dirty Tin Dust, 
Dirty Silver Dust, 
Dirty Obsidian Dust, 
Dirty Lead Dust, 
Electric Bow (Charged and un-charged)

I'm not using any texturepacks so that shouldn't be the broblem...

Any help? :/

**Comment by lichkingman** [comment]
Thank you very much silentgimp!
that fixed it :)
