### ISSUE TITLE
Electric pumps stopped working in my world

### ISSUE THREAD

**Issue by EzerArch** [mekanism/Mekanism#1119]
Minecraft Version: 1.6.4
Forge Version: 9.11.1.965-MCPatcher
Mekanism Version: 6.0.2.19

My electric pumps stopped working in my world without apparent reason after some Mekanism updates. I tried to rebuild the pump and the pipes, no fix.

I created a new world, with and without the other mods installed, pumps were working. It seems the other mods don't affect anything, the problem occurs only in my world.

**Files:**
- Forge log: https://db.tt/9GJNKs32
- World file: https://db.tt/DECeobPS (9.3MB)

**Mods installed (not necessary to install them):**
CloneCraft v2.0 MC1.6.4.zip
GravityGun2.0.0.zip
[1.6.4]FurnitureModv3.2.6.zip
BiblioCraft[v1.5.5].zip
CustomNPCs_1.6.2-1.6.4.zip
ModularPowersuits-1.6.4-0.10.0-92.jar
powersuitaddons-1.6.4-884.jar
Galacticraft-1.6.4-2.0.10.972.jar

**Comment by EricBuist** [comment]
Seems I am having the same issue. The pump was creating heavy water and then stopped without me doing any update at all. I cannot spend my time checking this and shift-rightclicking with a wrench on the pump periodically.

**Comment by EricBuist** [comment]
Even shift-clicking with the configurator doesn't change anything. The electric pump is just bugged, stopped producing heavy water for no reason. It gets power, there is a source block of water underneat and there is a Filter upgrade in it. So my Fusion Reactor setup is pretty much a waste, cannot create Deuterium unless I cheat it. I'm really pissed off.

**Comment by pupnewfster** [comment]
If this is in 1.15 that you are having this issue please open a new issue and state what mek version you are using. If this is for 1.6.4 which is all that can be assumed by commenting on this ancient issue, I hate to break it to you but we are only actively developing 1.15 so even if there is a bug in the 1.6.4 version it is not going to get fixed.
