### ISSUE TITLE
[Feature] Ore processing should handle nether quartz etc as well

### ISSUE THREAD

**Issue by christate** [mekanism/Mekanism#1208]
Possibly on your list for v7 already, but...

Right now IIRC the only nether quartz handling is to put it in a Crusher and get 1:1 dust output, and probably similarly for AE's certus quartz and other such materials.  The Mekanism ore processing toolchains really ought to be able to multiply these as well; cf TE's pulverizer that gives you 1:2 nether quartz -> dust very cheaply.

Personally I think it would be good if some of these other materials (especially certus quartz which tends to be a significant supply bottleneck for heavy AE use) _could_ be multiplied, but only with the more sophisticated Mekanism ore toolchains; say, tier 3 and up.

**Comment by Normal69** [comment]
It would be nice if could process nether ores.

My pack is set up that only machines could process nether ores, making nether a later game better mining world, when you have machines.

So the config solution of smelting nether ores to two normal ores is out of question. :)
