### ISSUE TITLE
EnergyNet.removeTileEntity console spam, possibly also causing lag

### ISSUE THREAD

**Issue by hayleox** [mekanism/Mekanism#1280]
I'm having some issues with Mekanism. Every once in a while (tends to be every ~5-20 minutes), it'll dump [a sudden burst of console spam](https://gist.github.com/oxguy3/9987433). Sometimes a restart will make it temporarily stop happening, but after a while it'll come back -- there's one person who has a lot of hydrogen generators and electrolytic separators and god knows what else, and I think the console spam might start when anyone gets close enough to his base to load the chunks.

More importantly though, lag spikes will start periodically hitting the server at the same time when the Mekanism console spam comes back. I'm guessing that Mekanism is failing to remove old tile entities or something and that's causing the lag, as Opis is telling me I have 1485 tile entities when I remember having 980 or 1000 an hour or two ago. Can you look into resolving this?

**Comment by kulflame** [comment]
This is back happening in ATM3 v 4.3 minecraft 1.12.2,  https://pastebin.com/2UKuSYTn

**Comment by zashra00** [comment]
Oh this... just throwing this out there  that's totes not Meks fault, it's chunkloadings fault. Use chicken chunks if it's available

**Comment by zashra00** [comment]
It mostly happens with ftbu, icu2 chunkloaders and, the chunkloading ward from exu2

**Comment by sativania** [comment]
This happens to me too. Same error, though in my case its the NuclearCraft Fission Controller thats referenced. Im not using any chunkloading though...So i dont think this has anything to do with mekanism

**Comment by thiakil** [comment]
Please dont necro-post. There is a recent issue about it.
