### ISSUE TITLE
Logistical sorter/pipes loses ore into smeltery

### ISSUE THREAD

**Issue by dukinatir1001** [mekanism/Mekanism#1338]
Hey there, 
When you use a logistical sorter to pipe ore through logistical pipes into a smelter, it turns stacks of ore into single ore.
e.g.
10 stacks iron-->chest-->logistic sorter--->logistic pipe--->smeltery controller = 10 individual ore
lost several thousand ore to this, please fix

thanks for your time,

**Comment by predakanga** [comment]
This seems to have snuck back in at some point.

Version 8.1.7 I'm seeing the same issue, with:
Chest --> Logistic Pipe --> Smeltery Controller
and
JABBA Barrel --> Logistic Pipe --> Smeltery Controller
