### ISSUE TITLE
Electric bow won't switch mode.

### ISSUE THREAD

**Issue by Benguin** [mekanism/Mekanism#1431]
I've tried both shift+M (after disabling all other hotkeys that were using M, just to make sure) and that didn't work, nor did shift+rightclick or shift+ rebindable-mekanism-key. 

Mekanism 6.0.5 on MC 1.6.4 (yogscraft complete pack.) Linux 64bit.

**Comment by AwesomeMaster** [comment]
Definitely a issue, I have this problem too.
