### ISSUE TITLE
BuildCraft machines not connecting

### ISSUE THREAD

**Issue by ghost** [mekanism/Mekanism#1585]
BuildCraft machines don't connect to Universal Cable, Forestry machines do. 
Forestry build 30, Mekanism build 75, BuildCraft 6.0.17

**Comment by PGhostCZ** [comment]
Cable still doesn't connect to BuildCraft machines.

Minecraft: 1.7.10
Mekanism: 8.1.5 (All addons have the same version)
BuildCraft: 7.0.1.3
Forge: 10.13.4.1472-1.7.10
