### ISSUE TITLE
Rotary Condensentrator

### ISSUE THREAD

**Issue by AdamJohnCool** [mekanism/Mekanism#1787]
There is no way to remove gases/ liquids from a rotary condensentrator when you want to use them for something else, am I missing something!?

**Comment by CarlSmotricz** [comment]
Not sure if this is a "reopen" or a new issue:

When the amount of gas or liquid is 0, there is no way to get rid of it. It can't be pulled out with a pipe as suggested here, or scooped out with a gauge dropper. It can't be consumed. And so long as there is a non-empty but 0 volume ingredient in the machine, that ingredient can't be replaced by a different one; neither by production nor by piping in nor by use of a tank or gauge.

I'm suffering this problem in 1.12.2-9.4.13.349 . I'm guessing that "0" is actually some fractional amount, maybe due to rounding errors. My only solution was to craft a new condensentrator.

**Comment by recon88** [comment]
Having the exact same issue as @CarlSmotricz 
I'm unable to put anything in as soon as another fluid/gas was in there. It says 0 but it's actually not empty.
Running on Mekanism-1.12.2-9.4.13.349 as well

**Comment by thiakil** [comment]
I'd need to see it in an otherwise empty world, with just Mekanism in the mods list. Alternatively, find the Condensentrator tile entity in NBTEditor and send the data

**Comment by DWX12** [comment]
I can confirm this error. Just got this bug playing on the most recent version of the Devcraft server hosted by EpicSquid. I'll try using a configurator to see if that actually does anything, but for now the machine is stuck at 0 mb.

**Comment by thiakil** [comment]
As mentioned, I need to be able to see the actual data in the tile to work out what it is. RFTools' debug tool might help, I think it has an NBT mode

**Comment by sonmica** [comment]
Here is the NBT data for a newly placed empty Rotary Condensentrator:
![javaw_2019-05-25_02-14-13](https://user-images.githubusercontent.com/4745644/58334460-b1cff900-7e93-11e9-818b-39f4fcb32009.png)
![javaw_2019-05-25_02-18-39](https://user-images.githubusercontent.com/4745644/58334362-7f260080-7e93-11e9-9fce-b1c0c2b9f419.png)

And here it is after processing Chlorine (or any other gas to liquid process):
![javaw_2019-05-25_01-52-59](https://user-images.githubusercontent.com/4745644/58334475-bbf1f780-7e93-11e9-91c2-202b8078af36.png)
![javaw_2019-05-25_02-18-51](https://user-images.githubusercontent.com/4745644/58334383-89e09580-7e93-11e9-94fe-d5d79153c51b.png)

This is on Mekanism 1.12.2-9.7.2.373

As per other comments before this, the liquid can't be drained or piped out, and it retains its state even after breaking and placing the machine. The only solution seems to be to create a new machine to process different liquids.

**Comment by thiakil** [comment]
Awesome, thanks for that, it confirms my suspicion. What are you using to drain the tank?

**Comment by sonmica** [comment]
In the above example, I was just trying to drain it using a Mechanical Pipe into a tank, but I've also tried attaching the tank to the bottom and configurating it, and also using a tank in the GUI to pick up the liquid. 

Toggling machine modes (to decondensentrate) also does not work, the machine hums as if it's processing something but there is nothing to process (though I didn't check to see if energy was being consumed).

**Comment by maid450** [comment]
I was having the same iddue and just read (not tested yet) that you can clear it using a [Gauge Dropper](https://wiki.aidancbrady.com/wiki/Gauge_Dropper)

**Comment by j2olill** [comment]
I was having this issue, and fixed it. My Condensentrator was saying I had 0mb of Lithium in it when I was trying to input another liquid.
To fix it I took my Condensentrator back to the line I was using for Lithium production and hooked it up. I then used a gauge dropper to put lithium back into the system and the change the mode to change Lithium back into liquid Lithium. This completely emptied all the Lithium out, all I had to do then was to remove the liquid Lithium with my gauge dropper and both slots were "empty" and ready to use.

**Comment by Danekjovax** [comment]
Issue still outstanding with DDSS 7.2b.

**Comment by pupnewfster** [comment]
This should no longer be an issue/even possible to have occur in 1.15 due to the massive internal rewrites we have performed. So I am going to go ahead and assume that whatever that acronym is for is not for 1.15, in which case it is not really relevant as we are no longer actively developing the 1.12 version of Mekanism.

**Comment by Danekjovax** [comment]
> This should no longer be an issue/even possible to have occur in 1.15 due to the massive internal rewrites we have performed. So I am going to go ahead and assume that whatever that acronym is for is not for 1.15, in which case it is not really relevant as we are no longer actively developing the 1.12 version of Mekanism.

OK, looks like the Gauge Dropper can clear the internal tanks by entering the machine's GUI and Shift-clicking the tanks while you have the dropper held by the cursor.  It will void any liquids/gasses present in the tanks, so make sure you do what you can to save them before doing this.
