### ISSUE TITLE
Metallurgic Infuser stops working randomly

### ISSUE THREAD

**Issue by Llamadmiral** [mekanism/Mekanism#1804]
The Metallurgic Infuser stopped working somewhy, and I can't figure out why. After some hardcore digging, I found out that other people had the same issue.
I tried powering it with redstone, it failed me.
Before it stopped working, I managed to create a wind turbine, which is working fine, and connected it to the infuser, which also worked for 2 iron ignots, then it would not process the 3rd one.
I replaced it, I reloaded the world, I also placed an entirely new one, I also powered it with redstone, and electricity at the same time, and still nothing.
I downloaded the latest version today, and I am playing under 1.7.10

**Comment by Peffity** [comment]
> The Metallurgic Infuser stopped working somewhy, and I can't figure out why. After some hardcore digging, I found out that other people had the same issue.
> I tried powering it with redstone, it failed me.
> Before it stopped working, I managed to create a wind turbine, which is working fine, and connected it to the infuser, which also worked for 2 iron ignots, then it would not process the 3rd one.
> I replaced it, I reloaded the world, I also placed an entirely new one, I also powered it with redstone, and electricity at the same time, and still nothing.
> I downloaded the latest version today, and I am playing under 1.7.10
There is a way to fix it, you have different fuels apart from energy. There is coal, redstone, diamond and i think there's more. Different fuels works for some ingredients for example, carbon aka coal fuel can infuse iron into enriched iron. Sometimes you have to have multiple infusers in order to make the process work. Hope this helps!
