### ISSUE TITLE
Walkie Talkie

### ISSUE THREAD

**Issue by Nosamthor** [mekanism/Mekanism#1825]
Will someone please upload a video or text tutorial on how to set up walkie talkies on servers! Do I need a voice server like team speak? How to I work these wonderful contraptions!? I have searched for hours looking for set up instructions! Yes, I know all about the controls: M = change frequency, shift right click to turn on, U/V to use voice chat etc. Please help!

**Comment by Peekofwar** [comment]
Would've loved to see an option to use Simple Voice Chat if its installed for the voice system.
