### ISSUE TITLE
Huge client memory leak in latest green and dev builds

### ISSUE THREAD

**Issue by GibbousWaximus** [mekanism/Mekanism#187]
I think you have a client side memory leak.  I recently updated to the latest recommended UE mod builds.  I started seeing garbage collection pauses within 30 minutes of playing.  I used VisualVM to profile minecraft and found the following:

With Mekanism installed, instances of various classes, but primarily 'net.minecraft.client.model.PositionTextureVertex' rapidly increase over time.

WITHOUT Mekanism installed, instances of that class start and stayed around 308,000 over the course of around 10 minutes play time.  
WITH Mekanism installed, instances started at around 308,000, then within 5 minutes ballooned to over 2 million, and just kept climbing, using more and more ram until Minecraft ground to a halt after about 45 minutes because it was doing GC so often.  

I've tested this on two pc's and seen the same behavior.
Tested on Mekanism 121, and 123.

**Comment by DarrenBellew** [comment]
This is still happening
