### ISSUE TITLE
Mekanism Crash on Startup (7.1.0.91 — 1.7.10)

### ISSUE THREAD

**Issue by irkedIsaac** [mekanism/Mekanism#1880]
I'm trying to put together a pack for me to play on my own, and since I do love Mekanism and it's ability to get pretty high-end tools relatively early on, I figured I could add it to my menagerie of various tech, magic, and aesthetic mods. However, upon startup with Mekanism, I get a crash report that mentions the Mekanism electric bow (a crash I've never recieved with other packs with Mekanism, not even in 1.7.10). Knowing me, I just overlooked some config setting or something ridiculous and this means nothing at all, but here (http://pastebin.com/998XV7rM) is the crash report for anyone willing to look it over. Thanks, and keep up the good work!

**Comment by 5hmu3l** [comment]
Just wanted to stop by and say a big thank you, I just spent the whole day putting my pack together, and after hours of browsing the net, going through dozens of adfly links, and version compatibility mishaps, I was having this same crash. You're the best!
