### ISSUE TITLE
All Mekanism machines playing music from WMP

### ISSUE THREAD

**Issue by Apocryphai** [mekanism/Mekanism#2058]
Not sure if this is a Mekanism bug, a Java bug or a Windows Media Player bug.

Had WMP playing music while testing a local Minecraft server when I noticed the music sounded odd. Closed WMP and discovered that all the Mekanism machines I had built (Metallurgic Infuser, Enrichment Chamber, Osmium Compressor, Energized Smelter) were each playing a separate 10-16 second loop of Brahms when active.

Any new Mekanism machine I build does the same. Removing the machines then replacing them doesn't affect it. Have restarted the client, the client PC and the server PC. 

Using Mekanism build 7.1.1.127

It's very strange, but also quite entertaining :)

**Comment by AlphaSierra216** [comment]
Looks like the Easter egg is still there in 2k25 😄

**Comment by Suitov** [comment]
Sure is. I don't even know where it's getting the music it's playing. It's a repeating choppy classical clip I don't recognise.
