### ISSUE TITLE
(CRASH @ Startup) Mekanism v220-241

### ISSUE THREAD

**Issue by Vaygrim** [mekanism/Mekanism#295]
Every version of Mekanism higher than v211 is STILL crashing at startup.
Minecraft 1.6.2
Forge 871

Just tried 240 and 241, and it is still occuring. With 241, it looks like your "walkie talkie" code is causing it. (Shrug)

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/15/13 10:15 AM
Description: There was a severe problem during mod loading that has caused the game to fail

cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: mekanism/common/item/ItemWalkieTalkie
    at cpw.mods.fml.common.LoadController.transition(LoadController.java:149)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:697)
    at cpw.mods.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:231)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:507)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:806)
    at net.minecraft.client.main.Main.main(SourceFile:101)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:57)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:18)
Caused by: java.lang.NoClassDefFoundError: mekanism/common/item/ItemWalkieTalkie
    at mekanism.common.Mekanism.addItems(Mekanism.java:545)
    at mekanism.common.Mekanism.init(Mekanism.java:1120)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:540)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:194)
    at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:174)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at com.google.common.eventbus.EventHandler.handleEvent(EventHandler.java:74)
    at com.google.common.eventbus.SynchronizedEventHandler.handleEvent(SynchronizedEventHandler.java:45)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:313)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:296)
    at com.google.common.eventbus.EventBus.post(EventBus.java:267)
    at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:105)
    at cpw.mods.fml.common.Loader.initializeMods(Loader.java:696)
    ... 10 more
Caused by: java.lang.ClassNotFoundException: mekanism.common.item.ItemWalkieTalkie
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:179)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 38 more
Caused by: java.lang.VerifyError: class mekanism.common.item.ItemWalkieTalkie overrides final method func_77650_f.(Lnet/minecraft/item/ItemStack;)Lnet/minecraft/util/Icon;
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:171)
    ... 40 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.6.2
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.7.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1610037096 bytes (1535 MB) / 2093809664 bytes (1996 MB) up to 2093809664 bytes (1996 MB)
    JVM Flags: 17 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms2048m -Xmx2048m -Xmn512m -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=31 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=40 -XX:GCPauseIntervalMillis=150 -XX:+AggressiveOpts -XX:PermSize=1024m -XX:+TieredCompilation -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:CompileThreshold=1000
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Suspicious classes: FML and Forge are installed
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v8.04 FML v6.2.62.871 Minecraft Forge 9.10.1.871 Optifine OptiFine_1.6.2_HD_C4 96 mods loaded, 96 mods active
    mcp{8.04} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    FML{6.2.62.871} [Forge Mod Loader](minecraftforge-9.10.1.871.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forge{9.10.1.871} [Minecraft Forge](minecraftforge-9.10.1.871.jar) Unloaded->Constructed->Pre-initialized->Initialized
    AppliedEnergistics-Core{rv13.c} [AppliedEnergistics Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    CodeChickenCore{0.9.0.5} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    InfiniBows{1.1.0 build 12} [Infinity Bow Fix](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NotEnoughItems{1.6.1.4} [Not Enough Items](NotEnoughItems 1.6.1.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PowerCrystalsCore{1.1.7} [PowerCrystals Core](PowerCrystalsCore-1.1.7-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DamageIndicatorsMod{2.9.0.9} [Damage Indicators](1.6.4 DamageIndicators v2.9.0.9.zip) Unloaded->Constructed->Pre-initialized->Initialized
    AppliedEnergistics{rv13.c} [Applied Energistics](appeng-rv13-c-mc162.jar) Unloaded->Constructed->Pre-initialized->Initialized
    arsmagica2{1.0.5-rc} [Ars Magica 2](ArsMagica_1.0.0-release.zip) Unloaded->Constructed->Pre-initialized->Initialized
    barrels{3.2} [The Barrels Mod](Barrels 3.2-1.6.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Natura{2.1.8} [Natura](Natura_1.6.2_2.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BiomesOPlenty{1.1.2} [Biomes O' Plenty](BiomesOPlenty-universal-1.6.4-1.1.2.51.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IC2{2.0.264-experimental} [IndustrialCraft 2](industrialcraft-2_2.0.264-experimental.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatForestryPre{1.6.2R2.7.0RC1} [MFR Compat: Forestry (part 2)](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Forestry{2.3.0.5} [Forestry for Minecraft](forestry-A-2.3.0.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BinnieCore{1.8-dev2} [Binnie Core](binnie-mods-1.8-dev2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraBees{1.8-dev2} [Extra Bees](binnie-mods-1.8-dev2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraTrees{1.8-dev2} [Extra Trees](binnie-mods-1.8-dev2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Core{4.1.0} [BuildCraft](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Builders{4.1.0} [BC Builders](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Energy{4.1.0} [BC Energy](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Factory{4.1.0} [BC Factory](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Transport{4.1.0} [BC Transport](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    BuildCraft|Silicon{4.1.0} [BC Silicon](buildcraft-A-1.6.2-4.1.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ChickenChunks{1.3.3.2} [ChickenChunks](ChickenChunks 1.3.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ComputerCraft{1.56} [ComputerCraft](ComputerCraft1.56.zip) Unloaded->Constructed->Pre-initialized->Initialized
    CCTurtle{1.56} [ComputerCraft Turtles](ComputerCraft1.56.zip) Unloaded->Constructed->Pre-initialized->Initialized
    EnderStorage{1.4.3.3} [EnderStorage](EnderStorage 1.4.3.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization{0.8.04beta17} [Factorization](Factorization-0.8.04beta17.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Railcraft{8.1.0.0} [Railcraft](Railcraft_1.6.2-8.1.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Thaumcraft{4.0.2} [Thaumcraft](Thaumcraft4.0.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    TwilightForest{1.19.3} [The Twilight Forest](twilightforest-1.19.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DartCraft{Beta 0.2.10} [DartCraft](DartCraft Beta 0.2.10.jar) Unloaded->Constructed->Pre-initialized->Initialized
    DungeonPack{1.6.2 FINAL} [DungeonPack](DungeonPack 1.6.2 FINAL.zip) Unloaded->Constructed->Pre-initialized->Initialized
    dyeablebeds{1.0} [Dyeable Beds](DyeableBeds-Universal-1.6.2-Build12.jar) Unloaded->Constructed->Pre-initialized->Initialized
    emashercore{1.2.1.4} [Emasher Resource](EmasherResource-1.2.1.4.zip) Unloaded->Constructed->Pre-initialized->Initialized
    eplus{1.16.4} [Enchanting Plus](EnchantingPlus-1.16.4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    EnderIO{0.3.2} [Ender IO](EnderIO-1.6.2-0.3.2.81.jar) Unloaded->Constructed->Pre-initialized->Initialized
    eng_toolbox{1.1.5.0} [Engineer's Toolbox](EngineersToolbox-1.1.5.0.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ExtraUtilities{0.3 prerelease 3a} [Extra Utilities](extrautils - 0.3 Prerelease 3a.zip) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.misc{0.8.04beta17} [Factorization Miscellaneous Nonsense](Factorization-0.8.04beta17.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.notify{0.8.04beta17} [Factorization Notification System](Factorization-0.8.04beta17.jar) Unloaded->Constructed->Pre-initialized->Initialized
    factorization.dimensionalSlice{0.8.04beta17} [Factorization Dimensional Slices](Factorization-0.8.04beta17.jar) Unloaded->Constructed->Pre-initialized->Initialized
    iChunUtil{2.2.0} [iChunUtil](iChunUtil2.2.0.zip) Unloaded->Constructed->Pre-initialized->Initialized
    GraviGun{2.0.0} [GraviGun](GravityGun2.0.0.zip) Unloaded->Constructed->Pre-initialized->Initialized
    inventorytweaks{1.57-dev} [Inventory Tweaks](InventoryTweaks-MC1.6.2-1.57-dev-b78.jar) Unloaded->Constructed->Pre-initialized->Initialized
    IronChest{5.4.1.573} [Iron Chest](ironchest-universal-1.6.2-5.4.1.573.zip) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct{1.6.2_1.4.5} [Tinkers' Construct](TConstruct_1.6.2_1.4.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ThaumicTinkerer{2.0} [Thaumic Tinkerer](ThaumicTinkerer 2.0-20.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MagicBees{2.1.5} [Magic Bees](magicbees-2.1.5.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mekanism{5.5.7} [Mekanism](Mekanism-v5.5.7.241.jar) Unloaded->Constructed->Pre-initialized->Errored
    MekanismGenerators{5.5.7} [MekanismGenerators](MekanismGenerators-v5.5.7.241.jar) Unloaded->Constructed->Pre-initialized->Errored
    MekanismTools{5.5.7} [MekanismTools](MekanismTools-v5.5.7.241.jar) Unloaded->Constructed->Pre-initialized->Errored
    minechem{@VERSION@} [MineChem](Minechem4-413.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded{1.6.2R2.7.0RC1} [MineFactory Reloaded](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatAppliedEnergistics{1.6.2R2.7.0RC1} [MFR Compat: Applied Energistics](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatAtum{1.6.2R2.7.0RC1} [MFR Compat: Atum](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatBackTools{1.6.2R2.7.0RC1} [MFR Compat: BackTools](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatChococraft{1.6.2R2.7.0RC1} [MFR Compat: Chococraft](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatExtraBiomes{1.6.2R2.7.0RC1} [MFR Compat: ExtraBiomes](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatForestry{1.6.2R2.7.0RC1} [MFR Compat: Forestry](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatIC2{1.6.2R2.7.0RC1} [MFR Compat: IC2](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatMagicalCrops{1.6.2R2.7.0RC1} [MFR Compat: Magical Crops](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Mystcraft{0.10.6.00} [Mystcraft](mystcraft-uni-1.6.2-0.10.6.00.zip) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatMystcraft{1.6.2R2.7.0RC1} [MFR Compat: Mystcraft](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatPams{1.6.2R2.7.0RC1} [MFR Compat: Pam's Mods](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatRailcraft{1.6.2R2.7.0RC1} [MFR Compat: Railcraft](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatRP2{1.6.2R2.7.0RC1} [MFR Compat: RP2](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatSufficientBiomes{1.6.2R2.7.0RC1} [MFR Compat: Sufficient Biomes](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatThaumcraft{1.6.2R2.7.0RC1} [MFR Compat: Thaumcraft](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatTwilightForest{1.6.2R2.7.0RC1} [MFR Compat: TwilightForest](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatVanilla{1.6.2R2.7.0RC1} [MFR Compat: Vanilla](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    MineFactoryReloaded|CompatXyCraft{1.6.2R2.7.0RC1} [MFR Compat: XyCraft](MineFactoryReloaded-2.7.0RC1-7.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Morph{0.3.0} [Morph](Morph-Beta-0.3.0.zip) Unloaded->Constructed->Pre-initialized->Initialized
    Natura|CompatMineFactoryReloaded{0.1} [Natura compat: MFR](Natura_1.6.2_2.1.9.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons{1.9.1.r43} [NEI Addons](neiaddons-1.6.2-1.9.1.r43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|AE{1.9.1.r43} [NEI Addons: Applied Energistics](neiaddons-1.6.2-1.9.1.r43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|CraftingTables{1.9.1.r43} [NEI Addons: Crafting Tables](neiaddons-1.6.2-1.9.1.r43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|ExtraBees{1.9.1.r43} [NEI Addons: Extra Bees](neiaddons-1.6.2-1.9.1.r43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|Forestry{1.9.1.r43} [NEI Addons: Forestry](neiaddons-1.6.2-1.9.1.r43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIAddons|MiscPeripherals{1.9.1.r43} [NEI Addons: Misc Peripherals](neiaddons-1.6.2-1.9.1.r43.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NEIPlugins{1.1.0.0} [NEI Plugins](NEIPlugins-1.1.0.0pre1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    NetherOres{1.6.2R2.2.0} [Nether Ores](NetherOres-2.2.0-4.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ObsidiPlates{2.0.0} [Obsidian Pressure Plates](obsidiplates-1.6.2-universal-2.0.0.15.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenBlocks{1.1.0} [OpenBlocks](OpenBlocks-1.1.0-forge9.11.0.883-snapshot-254.jar) Unloaded->Constructed->Pre-initialized->Initialized
    OpenPeripheral{0.2.1} [OpenPeripheral](OpenPeripheral-0.2.1-preview8.jar) Unloaded->Constructed->Pre-initialized->Initialized
    PortalGun{2.0.1} [PortalGun](PortalGun2.0.1.zip) Unloaded->Constructed->Pre-initialized->Initialized
    resonantinduction{0.2.2} [Resonant Induction](Resonant_Induction_v0.2.2.204.jar) Unloaded->Constructed->Pre-initialized->Initialized
    TConstruct|CompatMineFactoryReloaded{0.1} [TConstruct Compat: MFR](TConstruct_1.6.2_1.4.5.1.jar) Unloaded->Constructed->Pre-initialized->Initialized
    Waila{1.3.10} [Waila](Waila_1.3.10_1.6.x.zip) Unloaded->Constructed->Pre-initialized->Initialized
    mod_ZanMinimap{0.9.4} [Zan's Minimap](ZansMinimap1.6.2.zip) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMultipart{1.0.0.171} [Forge Multipart](ForgeMultipart-universal-1.6.2-1.0.0.171.jar) Unloaded->Constructed->Pre-initialized->Initialized
    McMultipart{1.0.0.171} [Minecraft Multipart Plugin](ForgeMultipart-universal-1.6.2-1.0.0.171.jar) Unloaded->Constructed->Pre-initialized->Initialized
    ForgeMicroblock{1.0.0.171} [Forge Microblocks](ForgeMultipart-universal-1.6.2-1.0.0.171.jar) Unloaded->Constructed->Pre-initialized->Initialized

**Comment by minecraft789** [comment]
it does not work on 1.7.10

**Comment by HanatakeYurii** [comment]
Erm, @minecraft789, what are you talking about?

Is there REALLY a reason to respond to this more-than-1-year-old issue?
