### ISSUE TITLE
[9.1.0.281] Mekanism and high power

### ISSUE THREAD

**Issue by ben569** [mekanism/Mekanism#3624]
Hello, I am running Mekanism 9.1.0.281 on 1.7.10 (the latest version I found on the website) on the DNS Techpack.

When I upgraded my induction matrix from 4 ultimate providers and 4 ultimate cells to 32 of each, I was unable to switch (with shift + right click using a crescent hammer) any port to output. I was able to before.

After upgrading my turbines from 11 \* 11 \* 18 to 17 \* 17 \* 18, the cryo-stabilized fluxducts I was using were not able to extract the power of the turbine. Mekanism's universal cables were able to but the turbines were outputting too much juice for them to be sufficient. Editing the config file to change the UltimateCableCapacity to either 3.2MJ or 32MJ made the cables unable to transfer any power. Please note that as soon as the turbines' tanks becomes full enough, the GUI's steam tank's content disappears.

When manually editing the reactor's injection rate above 198, similar bugs start to appear.

![2016-08-10_23 15 12](https://cloud.githubusercontent.com/assets/12788482/17571490/a727c308-5f50-11e6-951b-64cfd99975e6.png)
![2016-08-10_23 15 47](https://cloud.githubusercontent.com/assets/12788482/17571492/a72baa36-5f50-11e6-9945-e13b724723c9.png)
![2016-08-10_23 16 42](https://cloud.githubusercontent.com/assets/12788482/17571491/a729347c-5f50-11e6-9a00-d323b73187c2.png)

Please note that in both cases, WAILA printed rubbish values when I clicked on the machines, which, in my humble opinion, makes me think of a too small variable type.

Don't hesitate to ask for more details, I will remain available.

**Comment by ben569** [comment]
Just a picture of the buggy reactor interface. Please note that the reactor does not output any steam in such an occurrence.

![2016-08-10_23 21 16](https://cloud.githubusercontent.com/assets/12788482/17571621/46a0b674-5f51-11e6-86c5-e8769ce9cb9a.png)

**Comment by ben569** [comment]
The induction matrix bug was my bad. The stored energy still displayed as negative, though (according to waila, at least).

**Comment by ben569** [comment]
While the reactor problem does not occur in the usual injection range and the induction cell problem was just a derp on my part, the turbine bug IS problematic as I have no other way than making a universal cable carpet to tranfer the energy of my turbines.

Not to mention the visual bugs: the tank appears empty while it is full and the energy tab displays no energy production, even when hooked up...

**Comment by ben569** [comment]
I still am ready to provide as much help as you want.

**Comment by TitaniumSapphire** [comment]
I looked through the source, and there is a maximum steam amount, but you are surpassing it. That seems to be the most likely issue. If this is not the problem, then you probably generated over 2^23 mB of steam in one tick, causing the integer to overflow.
