### ISSUE TITLE
Fusion reactor bugg

### ISSUE THREAD

**Issue by bastiaansiemen** [mekanism/Mekanism#4665]
#### Issue description:
I have a weird issue.
Ive build a fusion reactor and got it working just fine.
Running at injection rate 12 producing 1.19 Mrf/t.
But when i returned this morning the reactor wasnt running, after some trial and error i got it running again. But Injection rate 12 only gives me 276830 rf/t now and it wont run at all at injection rates 2 or 4 (didnt try the others i went from 4 to 12 in my tests)

Currently im running Mekanism-1.12.1-9.4.0.318.
But i've had this problem before in a pre 1.0 forge version.

Ps. Both Deutirium and Trtium supplys are running stable so i dont have a lack of fuel.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-1.12.1-14.22.0.2456
**Mekanism: 1.12.1-9.4.0.318
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

Game didn't crash only weird rector behaviour.

**Comment by thommy101** [comment]
Do you have by any chance the region where the fusion reactor is chunkloaded? It sounds like a familiar bug caused by multiblock structures on chunkborders and not loading correctly (and displaying information wrong).

You can see chunk borders with (out of my head) F3+B.

If that's the case (chunk loaded/reactor on chunk borders) it might be related to #3837.

**Comment by thiakil** [comment]
`F3+G` I think

**Comment by thommy101** [comment]
You're right ;) I thought B(order)..

**Comment by bastiaansiemen** [comment]
I checked the positioning of the reactor in relation to my chuncks.
1 of the reactors is in fact positioned in 2 chunks but my other 2 are not.

So i tryed starting them with D-T fuel (running a chemical infuser with 4 speed upgrades) instead of injecting the Deuterium and Tritium seperatly.
With this setup i am able to get 1.2 Mrf/t out of one reactor . The other one runs on Deterium and Tritium speratly  at injection rate 12 and still only gives me 276830 rf/t.
(both metioned reactors are in 1 chunk).


![image](https://user-images.githubusercontent.com/31539223/30006149-45a80cc6-90f2-11e7-834a-0ba0ead60662.png)
(left reactor is the one in 2 chunks middle and right in 1 chunk (left reactor isnt running)).

**Comment by Mementh** [comment]
once started you should not need to use a infuser to combine.. it does it "automatically" inside the reactor.
getting different #'s for different ways at same fuel level sounds wrong

**Comment by aidancbrady** [comment]
I’ve made many internal changes to the Fusion Reactor in v9.9.19 that should hopefully fix this issue. Will leave #5246 open until I do some further testing.
