### ISSUE TITLE
Mekanism not using domain in localization files.

### ISSUE THREAD

**Issue by halvors** [mekanism/Mekanism#4698]
#### Issue description:
Mekanism not using domain in localization files. This causes translations to clash with other mods, as well as other mods to clash with mekanism.

One example is "fluid.tritium" which is translated to "Tritium" by other mods, and to "Liquid Tritium" by mekanism. The result is that the translation that is loaded first, wins.

**Comment by thiakil** [comment]
Additional conflict key `gui.delete` (see linked issue)

**Comment by thommy101** [comment]
Started a branch for this issue, trying to make all localisation key Mekanism specific.

**Comment by thiakil** [comment]
from #5111 

`gui.delete`
- customnpcs `Are you sure you want to delete this?`
- mekanism `Delete`

`gui.volume`
in other language there are different words
- extraambiance `Volume` <- sound
- mekanism `Volume` <- cubage

`gui.active`
- ftblib `Active`
- mekanism `Water-Cooled`

**Comment by pupnewfster** [comment]
All lang strings properly include mekanism (or the submodules name, such as mekanismgenerators), in their entries as of the 1.15 versions.
