### ISSUE TITLE
Private Teleporter allows anyone to go through it

### ISSUE THREAD

**Issue by tgstyle** [mekanism/Mekanism#4704]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Setting a teleporter to private does not restrict it to the player that created it.

#### Steps to reproduce:
1. Create a linked private teleporter with one account
2. Log in with another account and walk through it
3. Player is teleported when they should not be

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.22.1.2485
**Mekanism:** 9.4.1.326
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Private/Public on teleporters refers to the *Frequency*, not the ability for a player to use it.

**Comment by tgstyle** [comment]
Um why would the wiki state otherwise ? http://wiki.aidancbrady.com/wiki/Teleporter_Portal
Please re-open and investigate.

**Comment by tgstyle** [comment]
"Their security can be configured as "Public" (any player can teleport between Teleporters on this frequency) or "Private" (only the player who created/belonging to that frequency may use or add Teleporter Portals to it). They can be used to travel between dimensions."

**Comment by tgstyle** [comment]
Or if the wiki is mis-worded, could the feature be added then?


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Xander <notifications@github.com> Date: 9/22/17  10:22 PM  (GMT-07:00) To: aidancbrady/Mekanism <Mekanism@noreply.github.com> Cc: tgstyle <tg.style@gmail.com>, Author <author@noreply.github.com> Subject: Re: [aidancbrady/Mekanism] Private Teleporter allows anyone to go through it (#4704) 
Closed #4704.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/aidancbrady/Mekanism","title":"aidancbrady/Mekanism","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/aidancbrady/Mekanism"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #4704."}],"action":{"name":"View Issue","url":"https://github.com/aidancbrady/Mekanism/issues/4704#event-1262216662"}}}

**Comment by thiakil** [comment]
I *think* it's just a wording issue - only the owner can add teleporters to it, or use the *portable* teleporter with it.

I did not write it initially though so I could be wrong. @aidancbrady

**Comment by thommy101** [comment]
I do somehow remember the functionality @tgstyle describes (and the wiki). But at the same time, the code doesn't show any sign of blocking it, not now, and not in the commit history for the past months.

**Comment by aidancbrady** [comment]
Teleporters don't discriminate teleporting functionality, just access to the interface.
