### ISSUE TITLE
[1.10.2] Logistical transporters allow items through "none" connections in specific circumstances

### ISSUE THREAD

**Issue by L-Clouds** [mekanism/Mekanism#4895]
#### Issue description:
Logistical Transporters can route items through "none"/disconnected connections.  This is both a visual bug and also affects color routing.

#### Steps to reproduce:
1. Place Logistical Transporters such that they would have at least 2 connections to an inventory.  Set the one with least path-length to disconnect/"none".  Pipe in items from somewhere else; they will fly through the side of the "none" pipe across the "none" connection.  This only happens if there is also a "normal" or "push" connection to that inventory; if the only connections are "none", there isn't a problem.
2. Do the same as above, but color some of the pipe between the "none" connection and the "normal" or "push" connection (or color the normal/push pipe itself).  Then, color the extraction pipe or use a Logistical Sorter with a different color so that normally it would not be able to enter the inventory.  However, the items will be sent along the pipe and will fly across the "none" connection into the inventory.

Imgur album: [https://imgur.com/a/QTFvW](https://imgur.com/a/QTFvW)

#### Version (make sure you are on the latest version before reporting):
**Forge:** MC 1.10.2 Forge 12.18.3.2511
**Mekanism:** 9.2.4.103 (Mekanism, Generators, and Tools)
**Other relevant version:** MCMultiPart 1.4.0

**Comment by pupnewfster** [comment]
Closing this in favor of #5843 which is for 1.15.1 which also is fixed by #5846
