### ISSUE TITLE
Some of our texture sizes don't work well with mipmapping

### ISSUE THREAD

**Issue by josephcsible** [mekanism/Mekanism#4920]
A lot of our textures are odd sizes that look ugly when you're using mipmapping. Forge gives this warning about each of them at startup:

Texture mekanism:textures/X with size X will have visual artifacts at mip level 4, it can only support level X. Please report to the mod author that the texture should be some multiple of 16x16.

**Comment by pupnewfster** [comment]
While #5834 is a duplicate of this I am closing this in favor of that one as it is a more detailed report.
