### ISSUE TITLE
Can't get a laser to consistently point up or down

### ISSUE THREAD

**Issue by MalcolmAnderson** [mekanism/Mekanism#4942]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*
I could not find evidence that this bug has ever been reported.

#### Issue description:

Getting the laser beam to point up is not consistent.

#### Steps to reproduce:
1. Place an energy cell on the ground
2. Place a laser on top of the energy cell
3. using the configurator try to get the laser to point up.

I have sometimes (about 3% of the time) gotten the laser to point up, but not light up
Other times (about 2% of the time) I have gotten the laser beam to shoot into the sky *while* the laser was pointed west.

The rest of the time, the laser insists on pointing horizontally.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.1.2559
**Mekanism: 1.12.2-9.4.3.330
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by MalcolmAnderson** [comment]
It looks like I can point the lasers down.
If I stand below something and click underneath something, the laser will point down.
However, if I stand above something and click on top of something, the laser *will* point horizontal.

**Comment by MalcolmAnderson** [comment]
Updated comment with version number (1.12.2-9.4.3.330)

**Comment by thommy101** [comment]
Hi @MalcolmAnderson,

For a block from mekanism to turn up/down you need to look atleast at an angle of 65 (rounded, so > 64.5) degree. You can see the value when you press F3 on the line saying Facing. The last value is the pitch. At > 65 it is placed facing down, at < -65 it's placed facing up.

Hope this helps with the placement of the blocks. If not, please let us know

**Comment by MalcolmAnderson** [comment]
Hi @thommy101, hi @thiakil  it's a year later, but I now have steps to reproduce.
Turns out it's not what I thought it was. 
(And I'm looking for guidance as to whether I should resubmit this, or just leave this comment.  Thoughts?)

Step 1, place a laser, facing any horizontal direction
Step 2, get above the laser (greater than 65 degrees - thanks again)
Step 3, click with configurator in rotate mode, right click the laser

The image (model, block on the ground) will not change location, but if you have it powered up, the laser will fire in the new rotated direction.

The model will catch up with the orientation, in 2 - 30 seconds (I haven't figured out the trigger yet)

![2019-04-11_23 25 13](https://user-images.githubusercontent.com/1200043/56016521-59f97c00-5cb1-11e9-9408-f6f80bb1e2d8.png)
![2019-04-11_23 25 20](https://user-images.githubusercontent.com/1200043/56016522-59f97c00-5cb1-11e9-9bc1-a78fa66d3a6f.png)
![2019-04-11_23 25 32](https://user-images.githubusercontent.com/1200043/56016523-59f97c00-5cb1-11e9-9474-89d4e4a2f080.png)

**Comment by thiakil** [comment]
Thanks for the follow up, I think I might have come across this in my dev env once or twice but didn't think anything of it

**Comment by pupnewfster** [comment]
Hi @MalcolmAnderson could you please double check this still happening for you with Mekanism 9.7.0. It seems to work properly for me with 9.7.0 (Though I can reproduce it as instructed against the 9.6.x versions).

**Comment by MalcolmAnderson** [comment]
@pupnewfster - I will check that tonight.

**Comment by pupnewfster** [comment]
I think I found the issue, I thought it was fixed as the re connection to the energy cables was causing a block update making the laser reorient itself. However, without it being next to the cables it still happens. I think I just need to make sure that when rotating a block with the configurator it gets notified of an update.

**Comment by MalcolmAnderson** [comment]
Confirmed, image updates immediately in 9.7.0.

**Comment by MalcolmAnderson** [comment]
Confirmed, image updates immediately in 9.7.0.
