### ISSUE TITLE
Voice server not transmitting data

### ISSUE THREAD

**Issue by Dalethium** [mekanism/Mekanism#4992]
#### Issue description:
I have tried next to everything I can think of, but the walkie talkies simply do not work. The socket is created and connected but not a single byte of data is sent or received from it.

Ports are forwarded, voice server is enabled, multiple clients connected, same channel, ptt key bound, etc etc..
Is there anything I am missing?
#### Version
**Forge:** 14.23.2.2611
**Mekanism:** 1.12.2-9.4.3.330

**Comment by aidancbrady** [comment]
Are you using the correctly-bound voice key? Walkie talkies on and on the same channel?

**Comment by lightningblaze** [comment]
I am having the exact same issue including notes from last comment

Mod details
=======================
Forge: 14.23.3.2655
Mekanism: 1.12.2-9.4.10.345

Computer Details (if it matters)
Server Host: Windows 10
Client1: Windows 10 (same machine as host)
Client2: Arch Linux (In another country, tried both with and without pulseaudio)

**Comment by BertTheAvenger** [comment]
I'm also having this issue. Mekanism reports that players from both the local network and from outside it successfully connect to the voice server, but no sound is actually transmitted. I have made sure that all walkie talkies are on the same channel, and have tried transmitting with both the default push-to-talk key (U (conflicting)) and rebinding it to an unused key. Even two players on the local network can't use the voice chat. Voice server has been enabled on all clients and the server.

### Install Details:
Forge 14.23.5.2838
Mod List: 
`enderiointegrationforestry@5.0.46,universalmodifiers@1.12.2-1.0.16.1,openmods@0.12.2,rftools@7.71,jei@4.15.0.287,mekanism@1.12.2-9.7.9.380,tickprofiler@1.12-0.0.7,opencomputers@1.7.4.153,endercore@1.12.2-0.5.59,redstonepaste@1.7.5,mcp@9.42,reborncore@3.13.12.447,journeymap@1.12.2-5.5.4,enderiointegrationticlate@5.0.46,compactmachines3@3.0.18,forgelin@1.8.3,foamfixcore@7.7.4,omlib@3.1.3-246,icbmclassic@1.12.2-3.3.0.63,mts@14.3.1,waila@1.8.26,mekanismgenerators@1.12.2-9.7.9.380,enderioconduitsrefinedstorage@5.0.46,mcjtylib_ng@3.5.3,forge@14.23.5.2838,openmodularturrets@3.1.3-355,enderioconduits@5.0.46,refinedstorage@1.6.14,immersivetech@1.3.10,ironchest@1.12.2-7.0.67.844,openblocks@1.8.1,minecraft@1.12.2,tconstruct@1.12.2-2.12.0.157,industrialforegoing@1.12.2-1.12.2,mtsofficialpack@11.0.0,rebornstorage@1.0.0,unidict@1.12.2-2.9.2,actuallycomputers@2.1.0,powersuits@1.12.2-1.0.44,enderiomachines@5.0.46,immersiveengineering@0.12-89,biomesoplenty@7.0.1.2439,valkyrielib@1.12.2-2.0.20.1,openmodscore@0.12.2,numina@1.12.2-1.0.38,enderiopowertools@5.0.46,atomicscience@1.12.2-3.2.0.2,enderio@5.0.46,teslacorelib_registries@1.0.15,extrautils2@1.0,actuallyadditions@1.12.2-r149,mantle@1.12-1.3.3.55,teslacorelib@1.0.15,backpacks16840@3.5.6,FML@8.0.99.99,gasconduits@1.12.2-1.2.1,enderiobase@5.0.46,enderiointegrationtic@5.0.46,enderioconduitsappliedenergistics@5.0.46,mekanismtools@1.12.2-9.7.9.380,wanionlib@1.12.2-2.2,environmentaltech@1.12.2-2.0.20.1,enderioconduitsopencomputers@5.0.46,foamfix@0.10.5-1.12.2,opencomputers|core@1.7.4.153,refinedstorageaddons@0.4.4,chiselsandbits@14.33`

### Computer/Server Details:
Server: Ubuntu Server 18.04.2
Clients: Windows 10 1809

Server Log (Voice Server Enabled):
[latest.log](https://github.com/mekanism/Mekanism/files/3398586/latest.log)

**Comment by LordMZTE** [comment]
im having the exact same issue as well

**Comment by aidancbrady** [comment]
Walkie Talkies are currently unimplemented in 1.15. We'll use this issue to make sure we get around to porting them.

**Comment by aidancbrady** [comment]
Fixed in 820151a.

**Comment by M3veronMast3r** [comment]
Can you please Fix it for 1.12.2?
Mfg. M3veronMast3r
