### ISSUE TITLE
Question (or bug) Industrial Turbines.

### ISSUE THREAD

**Issue by Karmacopper** [mekanism/Mekanism#5039]
I've been testing turbines, literally to breaking and I have a question.

Why do 7x7 turbines not form above 13 blocks tall? If this one could form at 17 tall it could potentially be none- vent/disperser limiting.
Same question for 9x9x18. If this one could form it would be slightly less limiting.

Versions:

Mek 1.12.2 9.4.6.341 (Also happened with previous build)
Forge 14.23.2.2654

Tested in creative default superflat.

**Comment by thiakil** [comment]
Can you show the layout?

**Comment by Karmacopper** [comment]
Sure, when I get home from work. In the mean time, the turbine would be 6 turbine rotors (12 blades) 3 coils above the Rotational complex. Correctly placed Dispersers. Vents place at and above the dispersers. At 13 high it forms fine, however it will not form if made 14-18 tall. I worked out that if it would form at 17 tall it could be vent/disperser balance (ratios calculated from source code)

**Comment by Karmacopper** [comment]
![2018-05-04_23 04 46](https://user-images.githubusercontent.com/7628623/39655073-ab2c3f10-4fef-11e8-8fc9-1780dd790597.png)
 As requested the only diffference here is the turbine on the left is 1 block taller.

**Comment by Karmacopper** [comment]
![2018-05-04_23 07 42](https://user-images.githubusercontent.com/7628623/39655354-0bde7d5e-4ff1-11e8-8820-c6a54d96ada0.png)

**Comment by Karmacopper** [comment]
Do you need more information here?

**Comment by thiakil** [comment]
Haven't had time to investigate yet sorry

**Comment by Karmacopper** [comment]
No worries, I await your investigation. I have a reddit post about turbine/reactor stuff waiting in the wings. Would be useful to have an answer on this to let me post accurate info.

**Comment by Karmacopper** [comment]
Still no response on this?

**Comment by Karmacopper** [comment]
Been 12 months on this...

Any word on a fix?

**Comment by thiakil** [comment]
https://wiki.aidancbrady.com/wiki/Industrial_Turbine
> Maximum shaft height = min(2xLENGTH-5,14) [so blades don't touch sides]
> Maximum total height = min(2xLENGTH-1,18)

Looks like you need to make its length/with larger

**Comment by Karmacopper** [comment]
No, this cannot be correct. Look at the screen shot. The issue is all in the vent section, the shaft height isn't changing.

**Comment by thiakil** [comment]
shaft height is only one of the equations I posted.

**Comment by Karmacopper** [comment]
If this is the case, can the max total height formula be "improved" to account for all cases where max shaft height is adhered to? The number of viable turbines is not as big as it could be...
