### ISSUE TITLE
Wrong texture stitching on cables

### ISSUE THREAD

**Issue by raspopov** [mekanism/Mekanism#5046]
When I tried to fix a #4920 issue (using Paint.NET :wink: ) I found a small problem:

All cables has a rotaded on 180 degrees textures in the center of block which helps for correct texture stitching (I assumed it's a hack by design) **except** upper and down sides of east-west cables. I added a small arrow to \src\main\resources\assets\mekanism\textures\blocks\models\multipart\universalcableverticalbasic.png texture for better understanding.

Red arrows on screenshot shows a texture stitching error - a doubled green pixels.

![Mekanism Cables](https://i.imgur.com/8UBIwUc.jpg)

Used texture:

![universalcableverticalbasic](https://user-images.githubusercontent.com/228064/39774929-0394058a-5305-11e8-8943-66d2554dbef5.png)

#### Version:
**Forge:** 14.23.3.2678 
**Mekanism:** 1.12.2-9.4.10.345

**Comment by thiakil** [comment]
Cables are rendered in 3 sections; the centre and the two ends. Can you show a screenshot with the centre selection box showing?

**Comment by raspopov** [comment]
Here it is:

![Central section](https://i.imgur.com/dUdoRKb.jpg)

Also I added a red-yellow line and dots to test texture:

![universalcableverticalbasic](https://user-images.githubusercontent.com/228064/39796023-d2969e36-535c-11e8-8731-7f23a2b5fe66.png)

Looks like end sections cut by 4 pixels on 48x48 texture or 1 pixel on original 12x12. So rotated central section helps in masking of green-dot pattern.

**Comment by thiakil** [comment]
hmm the edge green dots look stretched :|

**Comment by raspopov** [comment]
In fact dots are not "stretched", its are two overlapped dots - dot from side section overlapped by another from central section.

**Comment by thiakil** [comment]
ahh, of course, didn't notice your red/yellow lines were on the edge of the texture

**Comment by aidancbrady** [comment]
I've fixed the rotation issue mentioned above. The texture overlapping issue is a bit more deep-rooted, and given the minor importance of this issue I'm going to call this fixed.

**Comment by aidancbrady** [comment]
For reference, this was fixed in 92eb2eb.
