### ISSUE TITLE
Mekanism Mechanical Pipe disconnect from Refined Storage Reader/Writer

### ISSUE THREAD

**Issue by tehMorag** [mekanism/Mekanism#5059]
Also reported on [SevTech ages](https://github.com/DarkPacks/SevTech-Ages/issues/2529) and [Refined Storage](https://github.com/raoulvdberge/refinedstorage/issues/1797) trackers

#### Issue description:
Rebooting the game causes the majority of "Mekanism" item "xxx Mechanical Pipe" and "xxx Universal Cable" to Disconnect from "Refined Storage" item "Reader" & "Writer".

[Liquid example](https://puu.sh/Ap7uB/1cd3c8ba07.png)
[Energy example](http://puu.sh/ArEKw/bd760fb2bf.png)

Had a person in chat also say the item and gas pipes disconnect from other Mekanism machines as well(?)

#### Steps to reproduce:
1. Set up a Reader and Writer with the same channel
2. Connect a "Mekanism" item "xxx Mechanical Pipe" to a source into the Reader
3. Set up a tank to pump the liquid out of the Writer
4. Reboot game
5. Pipes(s) would have disconnected from the Reader and Writer

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.3.2679
**Mekanism:** 1.12.2-9.4.10.345
**Other relevant version:** SevTech: Ages 3.0.7

**Comment by thiakil** [comment]
While I have no idea what the reader/writer do, the pipes check for the capability and will connect if it is found in a usable mode. The check will happen again when a neighbour block update is received.
