### ISSUE TITLE
[Suggestion]: Support for Underground Biomes faced vanilla ores

### ISSUE THREAD

**Issue by PearlCanopus** [mekanism/Mekanism#5082]
I suggest to implement a compatibility for (the new) Underground Biomes.
Underground Biomes allows to generate vanilla ores with UB stone textures (faces). I mine Coal-, Lapislazuli-, Redstone- and Diamond-Ore with silk touch. So I can process these ores with TE Pulverizer.
In some cases it would be useful to do that with the Enrichement Chamber in order to realize a higher yield.

Unfortunately right now this does'nt work. But I would appreciate this a lot.
Maybe you can make this possible, as far as the UB ores are registered well in OreDict.

**Comment by thiakil** [comment]
Are you sure they are registered with oredict correctly and in the right phase? Our system would automatically pick them up if they were.

**Comment by PearlCanopus** [comment]
Sorry, no I'm not 100% sure. I thought so, because TE machines process them now, what they did'nt in 1.11.2, when the oredict registration still was completely wrong. So anything changed... :)
I would really like to see UB Lapislazuli ore processed to 12 Lapis instead of 10... ;) (I know I could tweak recipes by myself.)

**Comment by PearlCanopus** [comment]
I built up the Digital Miner now. The miner shows up all UB faced ore versions as there correct counterpart. if I enter i.e. 'oreLapis*', it cycles between plain Thermal, IE, and all UB faced versions in filter screen.
The Digital Miner catch'em all to my storage. :)
So it would be great to be able to process these ores further. It's no hot topic but only a wish.
With default ores from another dimension, where UB does'nt work, all works well.

**Comment by thiakil** [comment]
That is indeed the point about it being in *the right phase*. It needs to be done before we iterate the OreDict for our recipes. It would appear they do not do it before that.
