### ISSUE TITLE
Mekanism Transport Pipes downgrading "randomly", and logistical sorter breaking

### ISSUE THREAD

**Issue by zeryl** [mekanism/Mekanism#5117]
#### Issue description:
I have a chest, that I have items inserting to (I've tried with normal minecraft chest, iron chest, ender chest, and storage crate), with an advanced logistical pipe connected in pull mode, going to additional storage crates.  At random points, the pipe will downgrade from Advanced to Basic, with no setting set (push/pull/none).  

#### Steps to reproduce:
1.  Unfortunately I don't have anything but a world that I can provide, to reproduce.  It doesn't happen always, just on this setup.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  Forge 14.23.4.2705
**Mekanism:** Mekanism-1.12.2-9.4.13.349.jar

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/SNZm2KSe

Image: https://i.imgur.com/VltydO6.jpg

If you need the world, I can certainly provide it as well somehow.

**Comment by thiakil** [comment]
You've posted a crashlog, though I'm not sure *how* it relates to the downgrade issue?

Does the downgrade only happen after the crash?

**Comment by zeryl** [comment]
On the other end of the pipes, I have a drawer controller, storage crates, and an anti-barrel (from YABBA).  I'm not sure which, if any, would be doing it, unless it's the anti-barrel causing it (which I can try and test).

**Comment by thiakil** [comment]
unlikely, the error is when it checks if the insert would succeed

**Comment by zeryl** [comment]
Yep, looks like further testing reveals the anti-barrel is to blame.  As soon as I put it on the line of items returning to storage, it happens.

**Comment by thiakil** [comment]
Hmm things like slot sizes changing in the same tick shouldn't be a thing :|

**Comment by pupnewfster** [comment]
My guess is this had to do at least in part with determining the subtype via NBT for which item was which, but as that no longer is a thing after the flattening I am going ahead and closing this.
