### ISSUE TITLE
Changing energy generation doesn't change generator real energy output

### ISSUE THREAD

**Issue by danikk14g** [mekanism/Mekanism#5123]
#### Issue description:
Hello i am creating a modpack in which solar and wind generators are more expensive to make but they also output more energy. i changed these lines in the mekanism.cfg file:

D:AdvancedSolarGeneration=500.0
D:SolarGeneration=100.0
D:WindGenerationMax=1200.0
D:WindGenerationMin=120.0

(maxy and miny remain the same)

However when i restart the game i see they still output the default amount of energy

One more request, can you provide a config option to set the max energy capacity of these generators, or at least change them so they have the same energy capacity than the energy tablet, which is used to craft them so it makes sense they both have the same amount of energy.

Thanks. 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.4.2739
**Mekanism:** Mekanism-1.12.2-9.4.13.349
**Other relevant version:**

**Comment by danikk14g** [comment]
Hello again, its been one month, i released my modpack (Craftologia) a week ago, the issue had no reply in this time, [here](https://i.imgur.com/JCIAnjN.png) i add a pic with the output rate of the two generators despite the config change i made that you can see in the previous comment.

Thanks.

**Comment by BlueAgent** [comment]
In the screenshot the values shown on the capacitors are RF not Mekanism Joules, that might be the source of confusion.

Wind Generator (~398 RF/t @ y = 207 + 4 = 211)
Output = (211 - 24)/(255 - 24) * (1200 - 120) + 120 = 0.8095 * 1080 + 120 = 994.3 J/t
Ouput in RF = 994.3 * 2 / 5 = 397.7 RF/t

Advanced Solar Generator (200 RF/t)
Output in RF = 500 * 2 / 5 = 200 RF/t

The config changes check out just fine.
