### ISSUE TITLE
Personal chest slot change crashes

### ISSUE THREAD

**Issue by prokopiy** [mekanism/Mekanism#5135]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
crash

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2705
**Mekanism:** Mekanism-1.12.2-9.4.13.349
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/prokopiy/9d8d810d744fd340e6fadd63ed66d63d

**Comment by pupnewfster** [comment]
I believe 9.7.3 fixed this issue being possible, if you want to check you can find that version here: https://minecraft.curseforge.com/projects/mekanism/files/2706361
