### ISSUE TITLE
Multiple Entangloporters on One Channel Dropping Items

### ISSUE THREAD

**Issue by Malkierian** [mekanism/Mekanism#5147]
#### Issue description:
Just ran into an issue where I have multiple entangloporters taking items on a single channel, and when more than one of them are actively taking these items, the entangloporter keeps dropping item stacks.  Everything is hooked up with ultimate transporters.  The other problem I'm finding is that another one hooked up in that series is rejecting some items back into the transporters.  The exit point entangloporter is merely exporting into a chest.  I thought it might have something to do with the fact that the input EPs were set to auto-eject, but no, when I went around and disabled that on any that were taking in items for that channel, they would still eject.  Had to put some vacuum blocks down to grab the rejects and feed them back into the channel.  Uploaded a few videos to show what was happening with some hoppers and a chest.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.4.2730
**Mekanism:** 9.4.13.349
**Other relevant version:** MC 1.12.2

https://www.dropbox.com/s/9et1biz5s0ovpz8/2018-08-26_15-06-45.mp4?dl=0
https://www.dropbox.com/s/shb015hqh6coi0q/2018-08-26_15-07-33.mp4?dl=0
https://www.dropbox.com/s/fr733k55cc5telu/2018-08-26_15-17-30.mp4?dl=0

**Comment by thiakil** [comment]
@Malkierian is it possible for you to set up a small demo world to send?

**Comment by Malkierian** [comment]
I'll see what I can do, though I'm a bit busy at the moment.  I'll grab the latest versions of stuff, too.
