### ISSUE TITLE
Ultimate Universal Cable not connecting to IC2 Nuclear Reactor

### ISSUE THREAD

**Issue by muniategui** [mekanism/Mekanism#5151]
#### Issue description:
Using a 6 chamber nuclear reactor of IC2 Ultimate Universal Cable (did not try elit or basic) are unable to be atached to it. It is like if they won't detect the reactor as a machine nor a generator making no connection to it.

#### Steps to reproduce:
1. Create a IC2 nuclear reactor
2. Try to put a universal wire adjacent to any nuclear chamber
3. Check that no connection is done and unable to put it in pull or push because no connection to it was done

#### Version:
**Forge: 14.23.4.2756
**Mekanism: 1.12.2-9.4.13.349
**Other relevant version: Using modpack Engimatica 2 Expert 1.34

# Maintainer edit:
- [ ] Check cables connect to reactor
- [ ] Check requirement for pull mode
- [ ] Investigate energy dupe (https://github.com/mekanism-mod/Mekanism/issues/5151#issuecomment-451759625)

**Comment by thiakil** [comment]
Did you check IC2 compat was not disabled in the pack?

**Comment by muniategui** [comment]
Universal wires seems working with other generators like kinetic generator (the universal wire have to be put in pull in order to get the energy but it worked) and they did the conexion automatically when the wire was placed adjecent to it so it seems like it is. The only line in config which contains IC2 is 
    B:BlacklistIC2Power=false
so if that is the compat line teorically is not black listed so it should be working

**Comment by themechman** [comment]
I have this as well. UniCables have to be put in "Pull" mode on all generator types of IC2 for me.
This or I put a piece of IC2 cable off reactor into cube, then to UniCable.

**Comment by thiakil** [comment]
It's likely something to do with IC2 Enet being fundamentally different in how it works (iirc the network handles the movement of power, not the individual tiles)

**Comment by Towdium** [comment]
Another issue here, might be related. When I connect multiple universal cables to one nuclear reactor, it multiples power output of the reactor. For example, if I connect 3 cables to a 20eu/t reactor, it provides 240rf/t in total indicated by ender io capacitor bank.

**Comment by aidancbrady** [comment]
#5682
