### ISSUE TITLE
Is running a sustainable fusion reactor not possible with an injection rate of 2?

### ISSUE THREAD

**Issue by UntouchedWagons** [mekanism/Mekanism#5155]
According to the official Mekanism wiki, the temperature of the reactor must not drop below the ignition temperature of 100MK but that seems inevitable if you use the lowest injection rate for an air cooled reactor. Is that right? If I want to run the reactor 24/7 do I have to set the injection rate to 4?

Love Mekanism, it's my favourite tech mod.

**Comment by themechman** [comment]
I have not had this problem in the past, but my last map seemed a bit off when I tried to run a rate of 2 on the reactor. Like it couldnt keep up. I'll check with creative fuel sources and see.

**Comment by themechman** [comment]
I've checked a few builds. If ANY water gets into the reactor it will drop the temp down.

I bucked mine with a 420M RF jolt which cold started at 110M Kelvin.
The plasma should hold about 149M Kelvin.

Also, make sure you are chunk loaded!

**Comment by aidancbrady** [comment]
#4665
