### ISSUE TITLE
[Suggestion/Question] Atomic Disassembler Vein mine config

### ISSUE THREAD

**Issue by ReiDaTecnologia** [mekanism/Mekanism#5173]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I'm playing currently in the modpack "All The Mods 3 Remix" and in this modpack sadly have OreExcavation Integration (That disable the vein mining from the mod OreExcavation and to use it you need a enchantment or a modifier in the case of TiC tools) to bypass this limitation i use the mode "Vein" of AD to vein mine ores for exemple but i noticed that some blocks is not vein mined like Quartz Blocks (He spawn in the nether around a infernal hive). Have a config that allow me to add blocks to the "WhiteList" of AD? if don't have a config file that allow me to do it currently, you can add one? will be very useful 😃

#### Steps to reproduce:
1. Select the mode "vein" of Atomic Disassembler
2. Try to vein mine a block that isn't currently in the whitelist (Like Quartz Block)
3. And you will notice that it didn't worked.

#### Version (make sure you are on the latest version before reporting):
**Forge:**
14.23.4.2760
**Mekanism:** 
9.4.13.349
**Other relevant version:** 
All The Mods 3 Remix Beta 0.0.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
I think it's really don't needed.

**Comment by thiakil** [comment]
It currently mines blocks that have an ore dictionary name starting with `ore` & wood logs

**Comment by pupnewfster** [comment]
Closing this as it is fixed in 9.9.9 (MC 1.15), which is now released and on curseforge. There is a block tag `mekanism:atomic_disassembler_ore` that can have blocks/other tags added to it.
