### ISSUE TITLE
Cobblestone dupe in pipes

### ISSUE THREAD

**Issue by YOKOGAMA** [mekanism/Mekanism#5177]
I have a big problem with pipes on my server.  Cobblestone dupe in pipes connected to crucible from exnihilocreatio. And this happens when the chunk is not loaded.
![pipes](https://user-images.githubusercontent.com/40151801/46805341-7867d480-cd6d-11e8-8ed8-da2e0b5e88bc.jpg)

**Forge:** 2705
**Mekanism:** Mekanism-1.12.2-9.4.13.349.jar
**Other relevant version:** exnihilocreatio-1.12-0.2.2.jar

**Comment by YOKOGAMA** [comment]
![unknown](https://user-images.githubusercontent.com/40151801/46818613-56c91600-cd8a-11e8-851f-e1441fc1bc1d.png)

**Comment by aidancbrady** [comment]
Gonna call this an interaction issue, and with the latest changes it's likely fixed. Will re-open if this proves to remain a problem.
