### ISSUE TITLE
Tessellator IllegalStateException: Not Building

### ISSUE THREAD

**Issue by Ilandria** [mekanism/Mekanism#5179]
#### Issue description:
A few blocks from Mek are throwing this error, mostly (but not exclusively) various transmitter blocks (mechanical pipes, universal cables, etc.). It seems to be a random chance to occur every rendering tick, as the error happens eventually with only a few cables/blocks placed, but will occur almost immediately after loading an area that has a few hundred Mek cables/blocks in use.

Errors always seem to be thrown by a tessellator.draw() call in the source code. Does there need to be some kind of safety check around that before calling draw()?

#### Steps to reproduce:
1. Set up any large-scale Mek system to increase the probability of the error occurring.
2. Wait a while while looking at said system.

#### Version:
**Forge:** 14.23.4.2715
**Mekanism:** 1.12.2-9.4.13.349

#### Crash report examples:
https://pastebin.com/F8Q6S09X
https://pastebin.com/uyfVcin9

**Comment by thiakil** [comment]
Please try to reproduce with just Mekanism, or start eliminating mods until it doesn't happen. 

The crash shouldn't really be possible, as the methods called check if the buffer has been initialised (startDrawing called) and start it if not
