### ISSUE TITLE
Suggestion: factories in auto-sort mode should move new items to blank slots

### ISSUE THREAD

**Issue by Ricket** [mekanism/Mekanism#5187]
Factories in auto-sort mode with some outputs filled, should move a new input item of different type to an empty slot.

Here's what I mean: I shift-clicked the diamond into the interface. It should have automatically moved it to the second slot and started processing it.

![image](https://user-images.githubusercontent.com/196978/47599960-cc360880-d97e-11e8-87db-708506297468.png)

**Comment by pupnewfster** [comment]
Didn't notice this issue, but this got implemented in 9.7.0, and as well as not being able to even have them be in the same slot if it can't turn into the output. Everything should be working properly though in the latest released version though ([9.7.4](https://minecraft.curseforge.com/projects/mekanism/files/2707235))
