### ISSUE TITLE
Energy Tablet was not correcly found for Autocraft

### ISSUE THREAD

**Issue by Kratzwurst** [mekanism/Mekanism#5190]
hello

Recipes with the energy tablet from your mod can't be craftable automatically.
On the cafting preview locks the tablet at as full storage with energy.
I figured out with oredict and without, same problem.

And you now my last hope to fix it 

https://imgur.com/a/cgUnvF4

##What happens:
The Tablet was not found correctly

##Steps to reproduce:
I ceate a recipe with JEI and no work
I create a recipe manually don't work
I create a recipe with oredict that's be also don't work.

Notice: i turned all wireless charging blocks off and capacitors

##Info
Modpack StoneBlock 1.0.25 (Dev was informed https://github.com/Sunekaer/stoneBlock/issues/494)
Minecraft:1.12.2
Forge:14.2.5.2768
Refined Storage: 1.6.8 (dev was confirmed https://github.com/raoulvdberge/refinedstorage/issues/2064)
Mekanism: 9.4.13.349
Generators: 9.4.13.349
Tools: 9.4.13.349

Does this issue occur on a server? [yes/no] yes

**Comment by totyaxy** [comment]
I confirmed it...

**Comment by Gamertech** [comment]
JEI strips the NBT data from items, so if you shift click the recipe in, the recipe wont match the actual item. Make the recipe manually by using the actual items instead of JEI and it should work fine.

You say you've tried manually making the recipe, if the energy bar is showing as full, then likely you've got wireless charging active and it's changing the NBT data again as the tablets charge while you're holding them, so the recipe is looking for fully/partly charged energy tablets instead of empty ones you'd get from a fresh craft.

Disable any wireless charging then make the recipes manually using fresh, empty energy tablets.

**Comment by Kratzwurst** [comment]
On my Post i'm writing: Notice: i turned all wireless charging blocks off and capacitors

**Comment by Gamertech** [comment]
I did read it, and there's no reason to be rude to people trying to help you.

Following the instructions I posted above in any pack with RS and Mekanism, including StoneBlock, I can easily create working RS patterns without any problem at all.

If the patterns you're making show energy tablets with anything other than an empty energy bar, then you're using charged tablets and it will break autocrafting as the patterns wont match the fresh tablets the crafting produces.

**Comment by totyaxy** [comment]
...you're using charged tablets and it will break autocrafting as the patterns wont match the fresh tablets the crafting produces.

Please avoid the unnecessary comments. This issue happen with uncharged (newly created!) energy tablets too, and with other items... This isn't a big problem, but problem :)

**Comment by thiakil** [comment]
This is a classic case where developers will point fingers at each other.

Our recipe *doesn't care* about the NBT to determine if its a valid item. It *uses* it in the output however.

RS seems to need an *exact match* in it's autocrafting.

I've got some code planned that will craft them without any NBT, but **in the meantime**, create your patterns with an actual, crafted item (that doesn't pick up any charge from a wireless charger for example) and it *should* work.

**Comment by Kratzwurst** [comment]
> This is a classic case where developers will point fingers at each other.

That's so true ^^

>I've got some code planned that will craft them without any NBT

Great plan i like it  ^^

so i figured out with your tipps.

So second way,  once again, i turned all off my items to charged the things
I delete all the Tablet in my own system incl. the recipes.
i double checked............

Doesn't Work

what i see, all chargeing items will don't work with Autocrafting. I can't be autocrafting a simple Display from Actually Addtions :P

**Comment by thiakil** [comment]
If a freshly crafted (uncharged) one by you doesn't work, and you're sure you didn't auto fill the recipe with JEI, try crafting one from RS, and click that into the recipe. If *that* doesn't work, its probably an RS issue with NBT.

**Comment by Redd56** [comment]
Confirmed, also for some reason my upgrades didnt work.... Made mekanism upgrades and the autocrafter just took the recources

**Comment by thiakil** [comment]
@Redd56 which autocrafter?

Both AE2 & RS don't like the NBT that Mekanism charged or tiered items use, so for the time being they will be a little dodgy.

**Comment by Redd56** [comment]
rs just the default one in 1.12

**Comment by pupnewfster** [comment]
I don't believe this is an issue anymore in 1.15, with the fact none of mekanism's stuff requires NBT to exist to determine item types in recipes anymore.
