### ISSUE TITLE
[BUG] Energy loss in non Basic Universal Cable

### ISSUE THREAD

**Issue by OrionSincoat** [mekanism/Mekanism#5195]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The non Basic Universal cables are loosing energy
I noticed that my energy cells don't recharge (even with big reactors) then i started to disconect everything and i found that was only the elite cable connect to the power grid, i switched to every other cable and the same problem happens in the non Basic cables.
I created a creative world and it's working normal (with only and the pipes and the cell).
Finally, i come to my friends world (he opened the server) with only IC2 and Mekanism and the problem with the cables was ocurring.

I think that when have a lot of pipes and machines working together this problem happens

#### Version (make sure you are on the latest version before reporting):
1.12.2-forge1.12.2-14.23.5.2772
Mekanism-1.12.2-9.4.10.345
MekanismGenerators-1.12.2-9.4.10.345
MekanismTools-1.12.2-9.4.10.345

[gist/pastebin/etc link here]

**Comment by blazeb75** [comment]
I have observed this in mekanism 1.12.2-9.4.13.349, forge 14.23.5.2781 (Enigmatica 2 Expert 1.54).

After I place down a couple of cables, power starts draining from my induction matrix at max speed. It doesn't happen for just one cable, and it also depends on where i place down the cables. Power stops draining only when _all_ cables are disconnected. Furthermore, WAILA reports that the cables are full of power when the cables are behaving normally, and empty when they are causing the draining.

**Comment by thiakil** [comment]
Strange, possibly a ghost network fail related to all the transmitter issues cross chunk borders.

You should be able to determine if this is the case with a network tool

**Comment by pupnewfster** [comment]
[9.7.3](https://minecraft.curseforge.com/projects/mekanism/files/2706361) had some work done with how energy is sent/emitted so if this is still happening (or is now fixed) it would be good to know.
