### ISSUE TITLE
[Suggestion] Seismic Reader - Add scrolling bar or mouse wheel scrolling

### ISSUE THREAD

**Issue by KAfable** [mekanism/Mekanism#5202]
#### Issue description:
Seismic Reader is current underutilized and I wanted to make it an easier way to prospect for ores in my pack, which has large vein like generation with GregTech. However using the Seismic Reader you still have to click to get to the bottom, which is a bit tedious.

![image](https://user-images.githubusercontent.com/26587049/48920548-795d4d00-ee67-11e8-92c3-4ea578b18686.png)
My suggestion is to take the arrow down key and move it all the way down to the bottom of the GUI, and adding a scrolling bar between that and the up arrow, so players can have the option to drag the scrolling bar or to use the buttons.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2772
**Mekanism:** 9.4.13.349

**Comment by pupnewfster** [comment]
Re-opening this issue for now to make it more clear this is on the tracker but this will be implemented in the next 1.15.2 alpha.

**Comment by pupnewfster** [comment]
Closing as 9.9.11 is now released and on curseforge.
