### ISSUE TITLE
Heat Generator produces very little power in passive mode

### ISSUE THREAD

**Issue by eccentricbob** [mekanism/Mekanism#5217]
#### Issue description:
The Heat Generator when surrounded by lava should (according to the wiki, and the discussion in Issue #4697) produce 5J/t per side (assuming the default config). However it is producing considerably less than this. In a test world with just Mekanism and MekanismGenerators, I got the following results

Lava Blocks | Generated Power
-----|----
1 | 161.06 mJ/t
2 | 624.15 mJ/t
3 | 1.36 J/t
4 | 2.34 J/t
5 | 3.56 J/t

Looking through the code for the Heat Generator, what seems to be happening is that it is creating 5 heat per tick per side (in the getBoost() method), then the heat dissipation simulation run, a chunk of the heat is dissipated and the remaining amount is used to generate electricity. This seems to explain the non-linear numbers I'm seeing as less heat is lost to the surrounding blocks when the surrounding blocks are lava, at least I think so.

This might be what's intended but it's resulting in very low outputs for passive generation.

Actually, I've just tested active generation, and there's similar behaviour. A generator is only producing 74.92 J/t, not the 150 I was expecting.

#### Steps to reproduce:
1. Create new world
2. Place heat generator surrounded by lava
3. Check energy output

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2796
**Mekanism:** 9.4.13.249
**Other relevant version:**

**Comment by thiakil** [comment]
The wiki is not well maintained, so treat its numbers as dubious at best

It does look to be intended, as the heat loss is part of the energy calculation
