### ISSUE TITLE
[Spongeforge] robit damage handled wrong

### ISSUE THREAD

**Issue by bluelightning32** [mekanism/Mekanism#5231]
#### Issue description:
In single player, the robit has half a heart. When I hit the robit, its energy goes down, but it still has half a heart and continues to follow me.

On a spongeforge server, the robit still has half a heart. However, if I hit the robit, it goes to zero hearts without affecting the energy level. The robit then just sits there and no longer follows me.

#### Steps to reproduce:
1. Install SpongeForge
2. The robit in follow mode
3. Hit the robit

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2781       
**SpongeForge:** 1.12.2-2768-7.1.5-RC3512                                                                                          
**Mekanism:** 1.12.2-9.4.13.349
**Modpack:** Enigmatica 2: Expert 1.47

**Comment by thiakil** [comment]
Report it to sponge. If they can tell us there's something wrong I'll look at it

**Comment by LemADEC** [comment]
Sponge fixed it on their side, so I guess this one can be fixed here
