### ISSUE TITLE
Crusher animation plays while being charged

### ISSUE THREAD

**Issue by Lazarix** [mekanism/Mekanism#5234]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When the crusher is not crushing anything but is charging, the front machine animation still plays, as if it were crushing something.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2781** 
**Mekanism: Mekanism-1.12.2-9.4.13.349** 
**Other relevant version:**

**Comment by pupnewfster** [comment]
I am not sure when this was fixed (maybe just by 9.7.0 or more recently) but I am unable to reproduce this in [9.7.3](https://minecraft.curseforge.com/projects/mekanism/files/2706361), if you could confirm that is the case that would be great.

**Comment by Lazarix** [comment]
Tested it on Mekanism-1.12.2-9.7.4.375 and it appears to have been resolved.
