### ISSUE TITLE
Unable to unify sawdust in Sawmill

### ISSUE THREAD

**Issue by EngineerXL** [mekanism/Mekanism#5244]
#### Issue description:
I can't unify Sawdust in Sawmill using UniDict
![image](https://user-images.githubusercontent.com/37447286/50828466-87e9c000-1352-11e9-8fd8-431ab976733a.png)
Others work properly
![image](https://user-images.githubusercontent.com/37447286/50828509-9e901700-1352-11e9-9099-02b61d2bf4c9.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2768 (MC 1.12.2)
**Mekanism:** 13.349

**Comment by thiakil** [comment]
Mekanism sawdust is registered under `pulpWood` & `dustWood`, your target must be also registered under one of those.

What oredict names are the target dust registered under?

**Comment by EngineerXL** [comment]
I've changed OreDict values via CraftTweaker. Final values: 
![Screenshot_1](https://user-images.githubusercontent.com/37447286/54506747-082e3200-494f-11e9-854e-8a31c6147c0d.png)
![Screenshot_2](https://user-images.githubusercontent.com/37447286/54506750-0b292280-494f-11e9-8e4a-720caa5bf73b.png)
Finally, my UniDict cfg: https://pastebin.com/LsFkfPVK

**Comment by thiakil** [comment]
I'm not quite understanding what the original problem is.

* is Mek sawdust missing a common oreDict entry? (need to know exactly which one it is missing)
* is the Sawmill only outputting Mek sawdust and you want it to use the first one in the oredict?
* both?
