### ISSUE TITLE
Fusion reactor requires to be reignited after a server restart

### ISSUE THREAD

**Issue by c0mical** [mekanism/Mekanism#5246]
Hi

the Fusion reactor requires to be reignited after a server restart, is there anything that can be done to keep it ignited throughout? the injection rate also sets itself to 0

all of the production and reactor are within the same chunk

#### Steps to reproduce:
1. ignite fusion reactor
2. restart MP server
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.52796
**Mekanism:** Mekanism-1.12.2-9.4.13.349, MekanismGenerators-1.12.2-9.4.13.349

**Comment by sgtkwol** [comment]
Same issue. I can check version numbers when I get home. Enigmatica 2: Expert Skyblock 1.18.

**Comment by dizzyd** [comment]
What chunkloader are you using?

**Comment by DarkGuardsman** [comment]
A few of the users on our servers are having this issue as well. We found its especially an issue when the reactor is on a chunk boarder.

**Comment by Frikkle** [comment]
We've had other reports of this as well; here's a reference to the original issue I came across in the Enigmatica 2 Issue tracker: https://github.com/NillerMedDild/Enigmatica2Expert/issues/1282

**Comment by DarkGuardsman** [comment]
Forgot to update this and note it is due to how the multi-blocks work. Its on mine or another one of the devs lists to fix in the near future.

**Comment by aidancbrady** [comment]
After the mass amount of changes we've made to multiblocks (and Mekanism in general with the 1.15 overhaul) and some testing, I don't think this is occurring anymore. Will re-open if anyone can reproduce.

**Comment by Shados** [comment]
I'm still seeing this issue on Mekanism-1.15.2-9.10.9.422, although not consistently. The reactor keeps running across some restarts, but after others it is powered off and the injection rate has reset itself to 0.

**Comment by AidenAviators** [comment]
I have the same issue occurring in Project Ozone 3, except I'm on singleplayer and it randomly resets injection rate to 0, sometimes even when I haven't traveled across dimensions or closed the game. The reactor and production are all chunkloaded.

**Comment by memepolicedogo** [comment]
I'm having the same issue in All The Mods 9 version 2.5.1, the reactor is not on a chunk boarder and the chunk is loaded by FTB Chunks

**Comment by Epicycle23** [comment]
Still experiencing the same issue with ATM10 (Mekanism-1.21.1-10.7.8.70).

**Comment by GABRlEL** [comment]
Also occuring in ATM9TTS 1.1.3 - on 10.4.10.
Any chance we could reopen this? @aidancbrady
