### ISSUE TITLE
Rendering crash

### ISSUE THREAD

**Issue by DemonfangArun** [mekanism/Mekanism#5261]
Forge: 2800
Mekanism: 9.4.13.349
Mekanism Generators: ^
Mekanism Tools ^

https://paste.dimdev.org/zibagekewi.mccrash

This happens more often than not when using the jei function to put stuff into a crafting station for an advanced solar generator. Upon relogging, the solar generators are not rendered on top (eventhough they're in the table) , and I can finish crafting it.

Placing the ingredients manually seems to not trigger the crash.

**Comment by dizzyd** [comment]
Hi @DemonfangArun - I fixed a related item rendering bug in my 9.4.16 of my fork (https://minecraft.curseforge.com/projects/mekanism-tools-dz-edition). Do you want to try it with that version?

**Comment by DemonfangArun** [comment]
> 
> 
> Hi @DemonfangArun - I fixed a related item rendering bug in my 9.4.16 of my fork (https://minecraft.curseforge.com/projects/mekanism-tools-dz-edition). Do you want to try it with that version?

I'll pass, though the fixes are appreciated.

**Comment by thiakil** [comment]
Hard to nail this one down unfortunately but still likely related to the hack item rendering that needs to be fixed.
