### ISSUE TITLE
rendering sillyness with cubic chunks

### ISSUE THREAD

**Issue by Redd56** [mekanism/Mekanism#5262]
version of forge: 2768
mekanism: latest i think unless theres been an update
cc: prettymuch any version

this is a very wierd issue but for some reason updates to rendering is broken below y0... 
https://cdn.discordapp.com/attachments/322363883698520065/537992153184469010/2019-01-24_05.48.04.png
the laser is on, the pipes are connected and the logistical transporters are purple.... or atleast thats how they should be rendering but as we can see... it aint happening client side :p
hopefully it isnt too big of an issue and can be fixed fairly quickly, also everything else seems to work with cc so far so yay

**Comment by thiakil** [comment]
Cubic Chunks issues like that are largely low priority, given the amount of things CC changes about general assumptions

**Comment by Redd56** [comment]
Yeah i know. Hence why i call it sillyness. And it updates to be proper with block updates or chunk regrabs

**Comment by thiakil** [comment]
Cant say i can see anything specific to Y levels in that render code. Is this tested with just Mek & CC?

**Comment by Redd56** [comment]
the first time no, but i have since tested it with just cc and mek and it does still happen. ima look at the code and try to find out where this wonk is happening
im thinking in the update render area as thats whats bugging out

**Comment by pupnewfster** [comment]
Looked into this briefly and I *believe* the issue has to do with the fact that the packet sync does not happen as we do actually have bounds in place for [Range4D](https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/api/Range4D.java#L28) which is used to see if a player is close enough to receive an update packet.

**Comment by pupnewfster** [comment]
Fix available in [9.7.8](https://minecraft.curseforge.com/projects/mekanism/files/2724543)
