### ISSUE TITLE
[Suggestion?] overpowered laser damage

### ISSUE THREAD

**Issue by desmfn** [mekanism/Mekanism#5273]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Not sure if it's intended to be or not, when i focus a laser beam into two laser amplifier (or tractor beam) which are focusing each other, the beam between them seems to deal crazy damage. Apparently it kills a mod mob with around 500 health instantly upon contacting the beam and seems to deal over 100 health damage to player with resistance 4 with diamond chestplate and helmet with single contact. The original beam was 6 laser combined and seems to deal 20 damage to mob each contact.

#### Steps to reproduce:
1. place two laser amplifier or tractor beam, each focusing the other
2. focus a laser beam into one of the amplifier or tractor beam

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.4.2765
**Mekanism:** Mekanism-1.12.2-9.4.13.349
**Other relevant version:** 1.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
This is the damaging code
```
if(!e.isImmuneToFire()) 
{
	e.setFire((int)(energy / 1000));
}
if(energy > 256)
{
	e.attackEntityFrom(DamageSource.GENERIC, (float)energy/1000F);
}
```

So, it will set you on fire for that many seconds (if not immune to fire), and damage you that much in an armor bypassing manner. This appears to be every tick, the same as the block breaking stuff.

Do you have any suggestions? It is planned to make the entity damaging part optional. (I could also just add these to the config too)

**Comment by aidancbrady** [comment]
Lasers are supposed to be brutally damaging. Don't walk into them :)
