### ISSUE TITLE
AE2/Mekanism crafting error wants to be reported

### ISSUE THREAD

**Issue by syndran** [mekanism/Mekanism#5287]
Attempting to AE2 craft induction recipes (provider and cell) from mekanism that use the tier below, cause these errors to occur in server console. attempting to complete the craft on higher tiers will result in overtick and server shutdown.

with Ore dictionary/substitution on or off. (off will result in total recipe failure for some). attempt the craft an advanced, elite or ultimate induction cell or provider from mekanism with stored AE2 recipes

expected. substitution picks up the basic/advanced/elite item and includes in recipe without error

EDIT - narrows it down to a single recipe that appears to cause the issues. "advanced induction cell". just viewing a craft plan for this recipe causes the console error.

Error Log
https://pastebin.com/QLKgnw7N

Pack - ATM3
Applied Energistics 2 rv6-stable-3
Mekanism 1.12.2-9.4.13.349
Forge Mod loader 8.0.99.99

**Comment by thiakil** [comment]
This is most likely an AE2 issue. There are some quirks with the items in recipes, as they use NBT to differentiate the tiers.

**Comment by syndran** [comment]
yeh left same on ae2. their response...

Mekanism was the issue we added the logging as their recipes and items are inherently designed to be extremely ambiguous, therefore causing these problems. But as long as they don't fix it, there is nothing we can do about it besides warning about i

**Comment by pupnewfster** [comment]
Closing this as it has to do with how AE2 handles recipes that rely on NBT, and that in 1.15 due to the flattening we don't use NBT to determine all our different variants so if/when AE2 updates this should no longer be an issue.

**Comment by Karl-Markkus** [comment]
I may have found a potential temporary fix for this sort of a crafting issue - when you start making the energy cubes, after having made them first time, look at their NBT data, some might have {mekData:security:0}.
Now if you take that into consideration, you can re-make the energy cube and induction cell recipes according to that NBT tag. also any other machine requiring those cubes!

**Comment by Karl-Markkus** [comment]
I may have found a potential, yet annoying way to fix this CraftingManager issue - Simply put, you look at the energy cube's NBT tags - specifically {mekData:security:0}. If you start making the recipes for automated crafting you need to input the correct energy cubes - for me, I replaced the regular cubes with said NBT tag for Elite and Ultimate energy cube/induction cell.
I also use crafters from RFTools to do the crafting and input them back into the AE system. Works like a charm!

**If any screenshots are needed for clarification, will provide**
**I am using the latest Mekanism version**
