### ISSUE TITLE
[enhancement] Resistive heater particles

### ISSUE THREAD

**Issue by DemonfangArun** [mekanism/Mekanism#5323]
The heater gives off smoke particles, yet it already has a glowing texture on the side when working. Smoke coming off of electrical devices is generally a bad thing.

**Comment by thiakil** [comment]
would redstone particles be an adequate substitute?

**Comment by DemonfangArun** [comment]
That would be a bit less alarming, but I think no particles would be more appropriate. In essence it's an electric coil heating up a metal rod/heat pipe. It already has a texture color shift on the side indicating it's active/working.

**Comment by DemonfangArun** [comment]
Upon troubleshooting an issue from another mod I have discovered that the particles in question are due to a (poor) default configuration of another mod, and not this one. Since this report has been misfiled, it will be closed! Sorry for any troubles.
