### ISSUE TITLE
Crash when certain player logs in

### ISSUE THREAD

**Issue by tenten8401** [mekanism/Mekanism#5341]
#### Issue description:
Whenever a certain player logs onto the server and loads their base, the entire server crashes.

#### Steps to reproduce:
1. Have my world on a SpongeForge server (I can get a link if you want)
2. Load the player's base

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2823
**Mekanism:** Mekanica 1.2.0 (with patch for #5334)
**SpongeForge**: 1.12.2-2768-7.1.6-RC3639

#### If a (crash)log is relevant for this issue, link it here:
I have 2 crash logs in 1 gist, they were 5 minutes apart and triggered from the same player joining:
https://gist.github.com/tenten8401/beb1085517e8a464cd43330305ddc764
The FoamFix coremod is disabled.

**Could be related to #5334 as that's the issue we were facing yesterday, before I applied that patch to the jar**

**Comment by thiakil** [comment]
Looks like a sponge issue, there's nothing abnormal about the mekanism parts of that stacktrace (its literally just trying to check if the block is loaded).

**Comment by tenten8401** [comment]
Well, the first crash log looks like it could be sponge, but the second looks more like Mekanism. Are they both sponge-related or just the first?

**Comment by thiakil** [comment]
Sorry, didn't notice the 2nd one (it is preferred that separate issues are posted on separate Github issues)

The 2nd one isn't something that should normally even be possible. The only way I can even *think* it might happen is if Sponge is actually loading the chunk when all we're doing is checking if it is loaded.

Are you able to reproduce it without Sponge?
