### ISSUE TITLE
Mechanical pipe bug with IC2 reactor fluid port

### ISSUE THREAD

**Issue by MeowWoem** [mekanism/Mekanism#5368]
#### Issue description:
When i restart my world in SP, all connections between mechanical pipe and IC2 Reactor Fluid Port are "broken" and i need to update a neighboor block to restore them (my reactor don't like that lol).
I have a temporary solution, put some pistons below the pipe and send a redstone signal to them to update the pipe. But we need a fix.

It seem happens because the reactor is initialized after the pipes. If a reactor is not complete, the pipes dont connect to fluid port. Other mods like buildcraft connect the pipe to the reactor even when the reactor is not complete

#### Steps to reproduce:
1. Build an IC2 fluid reactor with one (or more) fluid port
2. Connect a pipe to the fluid port
3. Quit and restart the world
4. The connexion with the pipe is broken and need an update to be restored.

#### Version :
**Forge:** 1.12.2-14.23.5.2814
**Mekanism:**  9.6.9.367
**IC2** 2.8.112 (i've installed the last version but the bug is still here)

**Comment by thiakil** [comment]
Generally we expect them to send a neighbour update when their extractability changes, but we will investigate once we've tidied up the big Mekanica based integration

**Comment by pupnewfster** [comment]
Mods are supposed to fire a neighbor update when their capabilities change. I am going ahead and closing this as IC2 isn't updated to 1.15 yet so there is no way to attempt to reproduce it, if it still is an issue when IC2 eventually updates to 1.15 we can look into this more.
