### ISSUE TITLE
Induction smelter progress lost – gone from world

### ISSUE THREAD

**Issue by Dimentive** [mekanism/Mekanism#5393]
#### Issue description
Yesterday, I finished up my induction smelter by adding a few new induction cells into it and closing it to activate the multiblock. I saved the game, and today, I entered my world again. All my progress of the day before was still there _except_ the induction smelter. My induction smelter was missing the cells I placed yesterday, and it was also missing the induction casing that I had placed to close it. They were nowhere to be found in my inventory, AE2 ME system, or anywhere else.

#### Versions

* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579))
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **Mekanica:** [1.1.2](https://minecraft.curseforge.com/projects/mekanica/files/2691355)

Even though I’m using [Mekanica](https://minecraft.curseforge.com/projects/mekanica), I’m reporting this here because Mekanica’s issue tracker no longer exists.

**Comment by thiakil** [comment]
There's not really enough info to go on here, you'd need to check your logs for any errors that occurred during saving.

And you should probably update to Mekanism 9.7 if not on a server, there have been plenty of changes though not sure any that would help your issue

**Comment by Dimentive** [comment]
Is it 100% safe to switch from Mekanica to Mekanism in an existing world?

**Comment by pupnewfster** [comment]
Yes, though it never hurts to make backups of your worlds before changing mods/updating mods.

**Comment by Dimentive** [comment]
True. In fact, I make far too many backups. 🙃
