### ISSUE TITLE
[1.12.2]Dynamic Tank cannot store liquids

### ISSUE THREAD

**Issue by pupfcom** [mekanism/Mekanism#5395]
When the Dynamic Tank is connected to the Immersive Engineering pipeline, reload the chunk will empty the tank, but the MEK pipeline and the Thermal Dynamic pipeline will not have problems.

#### Steps to reproduce:
1.Connect the Immersive Engineering pipe to the Dynamic Tank
2.Pump liquid(water, lava or oil, etc.) into the Dynamic Tank
3.Reload the chunk and the liquid is emptied by the Dynamic Tank

#### Version (make sure you are on the latest version before reporting):
Forge:14.23.5.2779
Mekanism:1.12.2-9.7.0.369
Minecraft:1.12.2

**Comment by kohlth** [comment]
so fluid already in the dynamic tank is being deleted when you reload the chunk because it was pumped in by a immersive engineering fluid pipe?

**Comment by thiakil** [comment]
please provide some more details: 

- Single player or Server?
- Is it crossing chunk boundaries?
- How big?
- How are you "reloading the chunk"?
- Is chunkloading involved (full or nearby)?

**Comment by pupfcom** [comment]
> so fluid already in the dynamic tank is being deleted when you reload the chunk because it was pumped in by a immersive engineering fluid pipe?

There is a problem as long as the tank is connected to the Immersive Engineering pipeline. The liquid is not necessarily pumped through the Immersive Engineering pipeline

**Comment by pupfcom** [comment]
> please provide some more details:
> 
> Single player or Server?
> Is it crossing chunk boundaries?
> How big?
> How are you "reloading the chunk"?
> Is chunkloading involved (full or nearby)?

Single Player
No
3x3x5
By changing dimensions or restarting the game
Nearby

**Comment by pupfcom** [comment]
@kohlth There is a problem as long as the tank is connected to the Immersive Engineering pipeline. The liquid is not necessarily pumped through the Immersive Engineering pipeline

**Comment by pupfcom** [comment]
@thiakil 
Single Player
No
3x3x5
By changing dimensions or restarting the game
Nearby

**Comment by thiakil** [comment]
What other mods do you have installed?

**Comment by pupfcom** [comment]
@thiakil 

These are all mods
industrialcraft-2-2.8.109-ex112.jar
Mantle-1.12-1.3.3.42.jar
natura-1.12.2-4.3.2.66.jar
jei_1.12.2-4.14.4.264.jar
forestry_1.12.2-5.8.1.322.jar
railcraft-12.0.0.jar
coroutil-1.12.1-1.2.27.jar                       
zombieawareness-1.12.1-1.11.16.jar               
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar
millenaire-1.12.2-7.1.1.jar
CodeChickenLib-1.12.2-3.2.2.353-universal.jar    
ForgeMultipart-1.12.2-2.6.1.81-universal.jar     
Aroma1997Core-1.12.2-2.0.0.0.jar 
AromaBackup-1.12.2-2.1.1.4.jar                   
RedstoneFlux-1.12-2.1.0.6-universal.jar          
MCMultiPart-2.5.3.jar
CoFHCore-1.12.2-4.6.1.22-universal.jar           
Mekanism-1.12.2-9.7.0.369.jar                    
sonarcore-1.12.2-5.0.19-20.jar                 
practicallogistics2-1.12.2-3.0.8-11.jar        
architecturecraft-1.12-3.80.jar                
OpenModsLib-1.12.2-0.12.1.jar               
OpenBlocks-1.12.2-1.8.jar                      
CoFHWorld-1.12.2-1.3.0.6-universal.jar         
ThermalFoundation-1.12.2-2.6.1.22-universal.jar
ThermalExpansion-1.12.2-5.5.2.39-universal.jar 
OpenComputers-MC1.12.2-1.7.4.153.jar    
omlib-1.12.2-3.0.1-162.jar              
openmodularturrets-1.12.2-3.0.1-264.jar 
Chameleon-1.12-4.1.3.jar                
StorageDrawers-1.12.2-5.3.8.jar         
SlashBlade-mc1.12-r16.jar               
infinitefluids-1.11-1.2.0.jar           
GalacticraftCore-1.12.2-4.0.1.181.jar   
Galacticraft-Planets-1.12.2-4.0.1.181.jar        
AsmodeusCore-1.12.2-0.0.5.jar                
GalaxySpace-1.12.2-2.0.3 STABLE.jar              
twilightforest-1.12.2-3.8.689-universal.jar      
Forgelin-1.8.2.jar                     
BetterFoliage-MC1.12-2.2.0.jar             
TLS_V1.2.3_MC1.12.2.jar                
NuclearCraft-2.15-1.12.2.jar                 
bdlib-1.14.3.12-mc1.12.2.jar             
generators-0.9.20.12-mc1.12.2.jar        
i18nupdatemod-1.12.2-1.0.8.jar                 
TrackAPI-1.1_1.12.jar                        
theoneprobe-1.12-1.4.28.jar                  
ImmersiveEngineering-0.12-89.jar             
immersivepetroleum-1.12.2-1.1.9.jar          
immersivetech-1.12-1.3.10.jar                
ImmersiveRailroading-1.5.0_1.12-402.jar      
foamfix-0.10.3-1.12.2.jar                  
Pam's+HarvestCraft+1.12.2zb.jar            
ThermalDynamics-1.12.2-2.5.3.16-universal.jar
InfernalMobs-1.12.jar                          
mw-1.11.7.7_mc1.12.2.jar                       
CustomOreGen-1.12-1.8.1.jar              
MekanismGenerators-1.12.2-9.7.0.369.jar    
Advanced+Solar+Panels-4.3.0.jar          
journeymap-1.12.2-5.5.2.jar                          
NotEnoughItems-1.12.2-2.4.2.244-universal.jar        
IndustrialWires-1.7-35.jar                           
OreLib-1.12.2-3.5.2.2.jar              
DynamicSurroundings-1.12.2-3.5.4.3.jar  

I have tested it, although I only installed Immersive Engineering and Mekanism, the same problem still occurs. I noticed that the Dynamic Tank connected to the Immersive Engineering pipeline will be recognized when the chunks are reloaded.

**Comment by pupfcom** [comment]
@thiakil 
The game crashed...
[crash-2019-04-14_18.08.25-client.txt](https://github.com/mekanism-mod/Mekanism/files/3077253/crash-2019-04-14_18.08.25-client.txt)

**Comment by thiakil** [comment]
thats the same as #5388 but mostly unrelated to this original issue

**Comment by pupfcom** [comment]
@thiakil emmm...this problem still appears,and Induction Matrix cannot receive energy from the Wire Connector (Immersive Engineering) when reloading chunks.But I have not seen these two problems before in version 1.7.10....
