### ISSUE TITLE
[Suggestion]  gas combustion cannon/pneumatic cannon

### ISSUE THREAD

**Issue by kohlth** [mekanism/Mekanism#5396]
**Describe the the feature you'd like**
A clear and concise description of what you want.

**gas combustion cannon**

launch vegetables and other items at your enemy's and friends

**Firing:** 
hold right click to load, right click to fire, auto reload can be disabled/enabled
holding shift will steady the cannon and remove recoil knock back
firing with oxygen will give you a 2 block recoil 
firing with ethylene will give a 4 block recoil

**Propellant:**

oxygen or ethylene gas, ethylene will give a longer range/power but will not allow you to shoot potatoes due to their softness

**Can shoot:**

potatoes (deals some damage, gives blindness and slowness)

poisonous potatoes (deals some damage, gives poison, blindness, slowness) (can be made by droping potatoes under open sky for one min

pumpkins (deals more damage then a potato, give blindness and slowness)

pumpkin pie: deals no damage, gives slowness and blindness for a longer length than the others

**canister:**
a special projectile type that can hold most items and carry them 
(deals no damage (unless contents deal damage) can give items to other players by loading a canister with a item that has no effect and shooting it at the player, doing so will input item directly into players inventory if the player is hit directly, other wise if it hits the ground it will drop the item at impact 

can apply potion effects if a potion is loaded in a canister

gunpowder (up to 8 per canister), TNT, obsidian TNT (low range if you use obsidian TNT) and some gases will explode upon hitting something, the explosion strength and size depends on the payload 

liquids can be carried and some have effects

gasses can be carried and some have effects

 

**Describe alternatives you've considered**

Instead of combustion, it would use pressurised gas (oxygen probably)? 
lower power/range if firing with less gas in the cannon?
upgrade to auto refill the cannon with rf or maybe base cannon is such?

**Additional context**

why am i typing this at 11pm.... at least its not 2 am

https://en.wikipedia.org/wiki/Potato_cannon#Combustion_launchers

more context on pressure/combustion cannons that fire starchy roots

**Comment by aidancbrady** [comment]
Merging with #5075
