### ISSUE TITLE
Digital Miner radius bug when mining Thermal Foundation Tin

### ISSUE THREAD

**Issue by metnavman** [mekanism/Mekanism#5398]
Currently utilizing Mekanica in the Enigmatica 2: Expert pack, version 1.59a. When setting the Digital Miner to work in the Deep Dark, it will NOT mine Tin from the Thermal Expansion mod when set to a Radius over "25". Anything lower than 25, and it sees the ore and begins to work. Anything over that, to the max of "32", and it refuses to recognize any of the Tin ore in the area. This does not happen with other ores (Copper from Thermal Expansion, Silver, etc).

**Comment by thiakil** [comment]
Sounds like some sort of interaction with another mod; there's nothing in our code that would do that

**Comment by NillerMedDild** [comment]
I can only confirm this issue with oreCopper, not oreTin, so there's something really odd going on. Same modpack, version `1.12.2-9.7.4.375` of Mekanism.

**Comment by pupnewfster** [comment]
With those specific ranges? Or more in general where it just doesn't want to mine copper.

**Comment by NillerMedDild** [comment]
I used 32 radius, min to max Y, I forgot all about that part of this issue while testing ^^'

**Comment by thiakil** [comment]
Closing due to Enigmatica issue being closed. Let us know if it happens again with specific circumstances
