### ISSUE TITLE
Bug with rotary condensentrator and enrichment chamber

### ISSUE THREAD

**Issue by Furibon** [mekanism/Mekanism#5401]
In current version of mekanism, rotary condensentrator doesn't extract liquid ethylene even when mechanical pipe is set to pull. So, that's impossible to create HDPE.
Enrichment chamber have a problem with insert and extract item from other mods (like ae2) in an automatic system.

**Comment by pupnewfster** [comment]
It works just fine for me. Please make sure that you are using the correct sides and that you have your machines configured to accept/eject items from the sides you are trying to automate them with. (Machines that can be configured have a button in the top left of the gui)

**Comment by Furibon** [comment]
For me not :/ I'm sure that i use the correct sides and my mechine is correctly configured but the rotary condensentrator don't went to extract liquid ethylene. The liquid don't passed in the mechanical pipe

**Comment by pupnewfster** [comment]
Can you please post a picture of your setup. Your mechanical pipe should be on the side opposite that which you are inserting the gas into. Like such: 
![2019-04-14_18 10 37](https://user-images.githubusercontent.com/1203288/56099848-a1198400-5ee0-11e9-84ab-0a2a63632af2.png)

**Comment by Furibon** [comment]
I just turn off my pc but that almost the same setup. My gas source is a PRC and my pipe is connected on the opposite, on pull just like you.

**Comment by Furibon** [comment]
![2019-04-15_08 24 22](https://user-images.githubusercontent.com/49623331/56111642-fe511c00-5f58-11e9-92d3-e4b270401a10.png)
![2019-04-15_08 25 45](https://user-images.githubusercontent.com/49623331/56111644-027d3980-5f59-11e9-84f4-c38c5214d3c1.png)

**Comment by thiakil** [comment]
Try rotating the Condensentrator maybe? I'm not sure, but it looks like you have the gas side facing the mechanical pipe (it's possible the gas insertion doesn't check side properly)

**Comment by Furibon** [comment]
I try it but the other side can't be connect to a mechanical pipe so i think that's on the right side

**Comment by thiakil** [comment]
Alright, please provide the information you refused to provide in you original post:

### Versions:
**Forge:** 
**Mekanism:** 
**Other mods installed (versions not required):**

**Comment by Pythonic-Rainbow** [comment]
To add on , this is from SkyFactory 4.

Forge: 2831
Mekanism: 9.7.2.273

**Comment by Teapoi** [comment]
> To add on , this is from SkyFactory 4.
> 
> Forge: 2831
> Mekanism: 9.7.2.273

FYI, I got it works with Thermal Foundation's Fluid pipe and servo.

This Rotary Condensentrator and HDPE works very odd or may be it's just working odd in this pack.
Besides the fluid extracting issue, if you add more than one speed upgrade to the PRC which producing HDPE it could stop working.

**Comment by pupnewfster** [comment]
A lot of these systems have been rewritten and given I still cannot reproduce this in 1.15 (including how fluid and gas works for if there is none left), so I believe this issue should no longer be possible. If anyone is able to reproduce this in 1.15 feel free to comment and I will reopen this issue.

**Comment by jerdm** [comment]
Hi everyone. could you help me I can't get water vapor with the rotary. I put the water and energy, but it doesn't turn into water vapor.
forge version 1.15.2.31.1.16
Mekanism-1.15.2-9.9.15.407
MekanismAdditions-1.15.2-9.9.15.407
MekanismGenerators-1.15.2-9.9.15.407
MekanismTools-1.15.2-9.9.15.407
![rotary](https://user-images.githubusercontent.com/16820864/76343542-40e8b900-62ce-11ea-8786-70783eef63dc.png)

**Comment by pupnewfster** [comment]
@jerdm if you would look at open issues first.. you would see this is a known bug and is fixed in dev #5940
