### ISSUE TITLE
Machines again stuck at 0 while dumping

### ISSUE THREAD

**Issue by TheRealDadbeard** [mekanism/Mekanism#5408]
Forge: 2816
Mekanism-1.12.2-9.7.1.371
MekanismGenerators-1.12.2-9.7.1.371

Have a Metallurgic Infuser with Obsidian that I can't empty completely. It stays at zero. I had this issue before but it seems to be back. Have to break it and put it back seem to fix it.

Edit: Says 0 then but still can't put stuff in.

Edit: I'm dumb. Works after breaking the machine

**Comment by thiakil** [comment]
being stuck at 0 shouldn't happen though, I'll see if I can reproduce

**Comment by TheRealDadbeard** [comment]
I closed this because I'm dumb sorry  forgot to comment, it stays at 0 but then after putting the RIGHT ingredient in it works fine all the time.

**Comment by thiakil** [comment]
But are you saying it was showing you 'Obsidian: 0' ?

**Comment by TheRealDadbeard** [comment]
Yeah it sometime stays at 0. Don't know if it's only obsidian or other stuff too. But after putting something other in it just takes it.
