### ISSUE TITLE
Fluxducts from Thermal are not outputting power

### ISSUE THREAD

**Issue by CritFlaw** [mekanism/Mekanism#5409]
#### Issue description:
Fluxducts connected to the gas burning generator with ethylene, are not outputting any power using Thermal Dynamics leadstone fluxduct. 

#### Steps to reproduce:
1. Set up an ethylene gas setup
2. Connect a TD leadstone fluxduct to the energy port of a gas burning generator
3. Connect to some kind of capacitor (I used a basic capacitor bank from Ender IO)

https://imgur.com/a/tNPeKrM

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
2816

**Mekanism:** 
9.7.0.369

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
N/A

**Comment by pupnewfster** [comment]
It works fine, it just seems that TD fluxducts are unable to insert power into Ender IO's capacitor banks without having the capacitor bank set to input from the spot it is connected to.
