### ISSUE TITLE
Armor and weapon values not changeable

### ISSUE THREAD

**Issue by ToserBan** [mekanism/Mekanism#5412]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
For my modpack i needed to change some values for the armor and weapons in mekanismtools. But tweaking the config doesn't seem to effect them at all.

#### Steps to reproduce:
1. Opened mekanism.cfg and changed some values for armor and weapons
2. Started game
3. armor and weapon values still at default, while other changes worked(like bin storage capacity)

#### Version (make sure you are on the latest version before reporting):
**Forge:14.23.5.2824** 
**Mekanism: 1.12.2-9.7.1.371** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by kohlth** [comment]
Could be that you did not save the mek tools config?

**Comment by ToserBan** [comment]
I saved it and there is no special config for mekanismtools, only for mekanism.

**Comment by thiakil** [comment]
Looks like the config isn't loaded (in Tools only) until after the tool materials are already created - and its been that way for almost five years :|

**Comment by ToserBan** [comment]
But some weeks ago i was able to chance all armor and weapon values. I think it was in the 360 version.
