### ISSUE TITLE
Oxygen into PRC?

### ISSUE THREAD

**Issue by geong1** [mekanism/Mekanism#5421]
#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.5.2831
**Mekanism:** 1.12.2-9.6.9.367
**Other relevant version:** SkyFactory 4.0.2

**Comment by pupnewfster** [comment]
I just want to confirm the configuration for gas of the PRC is set to allow inputting gas from the side you are attempting to input it? Right click the PRC at the top left click side config, then on the right click gases to get to the gas config. (By default it is only enabled on the left side of the PRC.
Secondly (I believe this is true from what you said but once again just want to confirm), you do have the gas tank set to output from the side that is touching the PRC? By default gas tanks ares set to input from the majority of the sides. Right click the gas tank and on the top left click side config. You should be able then set the sides to do what you want.

**Comment by geong1** [comment]
Yes, I set all of the gas tanks to output (and made sure it said auto-eject on), and made sure the PRC had every gas and liquid (just in case) port set to input. Recreating to verify.

**Comment by geong1** [comment]
Upon recreation, it worked as intended.. I'm closing the issue, and will re-open if it occurs again. Thanks for your time :)
