### ISSUE TITLE
Make personal chest compatible with other mods?

### ISSUE THREAD

**Issue by ghost** [mekanism/Mekanism#5428]
**Describe the the feature you'd like**
I would like the personal chest to be able to interact with something like an me storage bus named a password and have the security desk be able to add a name special to machines.

**Describe alternatives you've considered**
N/A

**Additional context**
Example:
You have a personal chest with the "trusted" setting. You have a security desk which adds a trusted MACHINE list, and you could add a password* which corresponds to something like a ME storage bus which is named a password*.
Thanks.

**Comment by thiakil** [comment]
I don't think this is really worth it given all the special casing that would be required, probably on both mods' sides

**Comment by Testo0987** [comment]
Yeah, it might not be worth the time but it sure would be helpful.

**Comment by aidancbrady** [comment]
Yeah, for in-depth interaction like this I'd rather leave it up to another mod to handle.
