### ISSUE TITLE
Biome Bonuses Calculated Incorrectly

### ISSUE THREAD

**Issue by kencinder** [mekanism/Mekanism#5432]
#### Issue description:

Biome bonuses for at least the Advanced Solar Generator seem to be calculated backwards, or at least incorrectly. The Solar Evap plant appears to take biome temp into account correctly, as the opposite is seen in reproduction steps for Temp.
Noticed on a server, tested also in single player to confirm.

#### Steps to reproduce:
1. Place an Advanced Solar Generator in the Desert, note an avg output around 192J/t. Place one in a colder biome such as Extreme Hills and notice an increase in output to around 337J/t

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.5.2768
**Mekanism:** 9.7.2.373
**Other relevant version:**

**Comment by Zajozor** [comment]
From https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/generators/common/tile/TileEntitySolarGenerator.java :
```
// Consider the best temperature to be 0.8; biomes that are higher than that
// will suffer an efficiency loss (semiconductors don't like heat); biomes that are cooler
// get a boost. We scale the efficiency to around 30% so that it doesn't totally dominate
float tempEff = 0.3f * (0.8f - b.getTemperature(getPos()));
```
Isn't the behavior you observe only the expected direct result of this? 
The solar generators produce more power in cold places in mekanism:
`peakOutput = getConfiguredMax() * (1.0f + tempEff + humidityEff);`
but they also do so in the real world
(on Earth though, there is a pretty huge correlation  cold = low sunshine, thats why this seems counter-intuitive).
https://stardustsolar.com/2018/02/solar-panels-work-better-cold-temperatures/

**Comment by thommy101** [comment]
@zajozor explained it correctly. Solar panels convert light into energy, not heat. Heat is only making it less efficient.

Some numers: https://docs.google.com/spreadsheets/d/1hkx1R6KtNmyPf8_Xih1TnM5A3M_hqEyBYm8HHYzut2s/edit?usp=drivesdk

**Comment by kencinder** [comment]
Makes sense, appears the wiki needs updated, states 50% bonus when in desert. Not the only thing outdated on the wiki though it seems.
