### ISSUE TITLE
Machines no longer accepting power from Cyclic Energy Transfer Nodes.

### ISSUE THREAD

**Issue by LezChap** [mekanism/Mekanism#5433]
#### Issue description:
I'm playing on Sky Factory 4.  Today's update came with Mekanism-1.12.2-9.7.2.373 (previously running Mekanism-1.12.2-9.6.9.367).  Before, the Crusher would accept power from the Energy Transfer Node from Cyclic.  Now they won't.  Below is a list of machines I tested in a test world:

# Tested machines that work:
Metallurgic Infuser
Teleporter
Rotary Condensentrator
Chemical Oxidizer
Chemical Infuser
Electrolytic Separator
Chemical Washer
Chemical Crystalizer
Formulaic Assemblicator

# Tested machines that don't:
Crusher
Osmium Compressor
Combiner
Enrichment Chamber
Purification Chamber
Energized Smelter
Electric Pump
Chargepad (not 100%, never used it before)
Chemical Injection Chamber
Precision Sawmill
Seismic Vibrator
Pressurized Reaction Chamber
Fluidic Plenisher
Laser Amplifier (not sure if this takes power directly, just going through JEI and trying everything that has an RF bar)
Resistive Heater
Energy Cubes (all tiers)
Factories (all tiers and types)

Cyclic also updated from Cyclic-1.12.2-1.19.4 to Cyclic-1.12.2-1.19.6, but none of their commits appear to impact energy, whereas your mod's did, so I'm reporting it here first.

**Comment by thiakil** [comment]
Unless you can reproduce this with a standard cable this is expected, Mekanism is strongly sided, and will not accept power from a `null` facing.

**Comment by pupnewfster** [comment]
Well actually... @thiakil the energy stuff happened to be strongly faced from a null side when I was fixing some stuff up. There is the chance that #5427 actually will allow them to accept energy from a null side again.
