### ISSUE TITLE
Duplication of items using a logical sorter

### ISSUE THREAD

**Issue by bigenergy** [mekanism/Mekanism#5435]
#### Issue description:
Duplication of items using a logical sorter and cells AE2

#### Steps to reproduce:
1. Take any two EQUAL cells of the same size (this is important)
2. Put in them the items you want to duplicate
3. Put two chests and between them a logical conveyor
4. Configure the cell filter
5. Put two cells in the chest

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2814
**Mekanism:** 9.7.2.373

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

Video (russian) https://www.youtube.com/watch?v=mEowd8Dpru8

**Comment by thiakil** [comment]
Cant reproduce with #5451
