### ISSUE TITLE
Digital Miner not emptying inventory

### ISSUE THREAD

**Issue by GhostZero91** [mekanism/Mekanism#5437]
#### Issue description:
watch unlimited items flow without emptying the inventory, i dont like it because its a bug and i see it as cheating.

#### Steps to reproduce:
1. Place digital miner and connect energy
2. Connect Logistical Transporter pipes on the back square to a chest
3. add a universal ore in filters then set the digital miner on auto-eject then press start

#### Version:
**Forge: forge-1.12.2-14.23.5.2815-universal.jar
**Mekanism: Mekanism-1.12.2-9.6.6.358.jar
**Other relevant version: Atlauncher 3.2.4.0, Minecraft 1.12.2

#### If a (crash)log is relevant for this issue, link it here:

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Update mekanism
