### ISSUE TITLE
Config Card paste to multiple machines

### ISSUE THREAD

**Issue by FlexibleGames** [mekanism/Mekanism#5442]
While I like that configuration cards are in the mod, the fact you have to re-copy after every single paste negates the benefit of the card. I'd like to see this card behave similar to a 'Redprint' from Thermal, copy once, paste many times with those copied settings.

I have to configure a bank of 96 Elite smelters, all in stacks of 8. Half the smelters need one set of configurations, the other half another set, but copying these over is horrifically tedious. Almost as tedious as setting them manually. I'd like to copy once, paste 47 times.

This command path would be excellent:
1. Holding the config card in your hand, shift right click to clear and/or copy a machines settings
2. Right click any number of other machines to paste the same settings.

That's it. This would be so fantastic.

**Comment by pupnewfster** [comment]
Going to implement this into 9.7.5, and make it so to clear the card you have to shift click the air instead of it clearing automatically after use.
