### ISSUE TITLE
Items are not changed or not displayed

### ISSUE THREAD

**Issue by Prasodym** [mekanism/Mekanism#5443]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Starts Normal, but the items are not displayed.

#### Version (make sure you are on the latest version before reporting):
**Forge:2768

** 
**Mekanism: Mekanism-1.12.2-9.7.2.373** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[latest.log](https://github.com/mekanism/Mekanism/files/3124875/latest.log)

**Modlist: [https://pastebin.com/AmUULepp](url)**

[gist/pastebin/etc link here]
![2019-04-28_12 52 18](https://user-images.githubusercontent.com/38152214/56863272-bbf5f900-69b4-11e9-96bc-8f6da8af451c.png)
![2019-04-28_12 52 28](https://user-images.githubusercontent.com/38152214/56863292-f069b500-69b4-11e9-964e-5d5d10db4292.png)

**Comment by thiakil** [comment]
You have a bunch of coremods that mess with rendering, try removing them one by one until it stops. I'd start with Optifine & Hammer Core.

Mekanism uses standard enough rendering to render those items so it's likely another mod causing issues.

**Comment by Prasodym** [comment]
I'm surprised about the version 'Mekanism-1.12.2-9.4.13.349' everything worked fine?

**Comment by thiakil** [comment]
and a lot has changed since then. Forge changes since that version meant the item rendering *didn't* work for normal set ups. You have rendering mods, you're on your own imo

**Comment by Prasodym** [comment]
It was actually Optifine again.

**Comment by pupnewfster** [comment]
My guess then is Optifine may not have support for TEISRs then. Given in 9.7.x the rendering system for some items was switched from using a hack to being less hacky by using TEISRs.

**Comment by Prasodym** [comment]
This may be possible, but I have a tough problem not coming to the server anymore and just can't find the error except for the `produces unregistered item minecraft:wooden_door (net.minecraft.item.ItemDoor@61c42e54)`. ^^

**Comment by pupnewfster** [comment]
From a user on our discord who was also having the same problem with items being invisible with optifine:
```
Good evening, following a complaint from a bawl I made to you yesterday, I have been looking for a solution all day. I have found it and I would like you to share it with me. 

step 1: Uninstall optifine from your modpack.
step 2: Start the game and go to your map to load the machines.
step 3: Exit the game and re-install optifine making sure it is the latest version.

Then you can go quietly to your world and everything will be visible, this technique to work for me so I hope it will work for you.
```

**Comment by Prasodym** [comment]
Tomorrow, I'll blue right here.
What's with this message? 
The console is so too spammed.

`[08:51:10] [ic2-poolthread-3/WARN] [ic2.EnergyNet]: Tile mekanism.generators.common.tile.reactor.TileEntityReactorFrame@2e9ab18d (dim 0: -334/63/380), sub tile mekanism.generators.common.tile.reactor.TileEntityReactorFrame@2e9ab18d (dim 0: -334/63/380) addition is conflicting with a previous registration at the same location: TileEntityReactorFrame{tileType=SpongeTileEntityType{id=mekanismgenerators:mekanismgenerators:reactor_frame, name=mekanismgenerators:reactor_frame, TileEntityClass=class mekanism.generators.common.tile.reactor.TileEntityReactorFrame}, world=WorldServer{Name=world, DimensionId=0, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=-334, y=63, z=380}, blockMetadata=1}.`

**Comment by thiakil** [comment]
1. Wrong issue to post that
2. You probably need to update Mekanism to the latest version
