### ISSUE TITLE
Gas Generator + Gas Tank = FREEZE

### ISSUE THREAD

**Issue by DevTimur** [mekanism/Mekanism#5448]
Issue description:
**If you insert Ethylene tank into Gas Generator game just FREEZE to death.**

Version (make sure you are on the latest version before reporting):
**Forge: **2784**
**Mekanism: **Mekanism-1.12.2-9.7.2.373**

**Comment by thiakil** [comment]
Doesn't happen to me in my dev environment. Is this in single player or on a server?

and which type of gas tank?

**Comment by DevTimur** [comment]
Single player
Ethylene creative tank

**Comment by pupnewfster** [comment]
Will look into fixing this when I get a chance, but I was able to reproduce. (The key thing about the issue is putting it INSIDE the inventory, rather than putting it in the world next to the generator)
