### ISSUE TITLE
Digital Miner dupe bug

### ISSUE THREAD

**Issue by Focamacho** [mekanism/Mekanism#5449]
**Issue description:**
You can duplicate items using a Digital Miner

**Steps to reproduce:**
1. Place a Digital Miner in the ground
2. Put items inside a stackable block that holds items in after being broken(Like RFTools Crafter)
3. Put more "RFTools Crafters" in the ground
5. Set a filter in the Digital Miner to mine the Crafters(Fuzzy Mode:ON)
6. Turn on the digital miner
7. All the collected crafters by the miner will be the same as the first (See the video for more info)

**Version (make sure you are on the latest version before reporting):**
**Forge:** 1.12.2 - 14.23.5.2836
**Mekanism:** Mekanism-1.12.2-9.7.3.374

**If a (crash)log is relevant for this issue, link it here:**

https://www.youtube.com/watch?v=IKg_pf44QBo

**Comment by Zajozor** [comment]
Seems related to the same problem as #5435

**Comment by thiakil** [comment]
confirmed fixed in #5451
