### ISSUE TITLE
Mekanism universal cables don't give enough energy to IC2 machines

### ISSUE THREAD

**Issue by djpadbit** [mekanism/Mekanism#5450]
#### Issue description:
In the latest release of Mekanism, the universal cables don't give enough energy to IC2 machines.

#### Steps to reproduce:
1. Grab any IC2 machine (I use the electric furnace but anything works)
2. Plop in some overclockers to make it consume a bit of energy (something like 20 is enough)
3. Connect a Mekanism universal cable to power it
4. And the machine shouldn't have enough power to run continuously (like it did before 9.7.3.374)

#### Versions:
**Forge:** 14.23.5.2836
**Mekanism:** 9.7.3.374
**IC2:** 2.8.145-ex112

From my understanding, the problem comes from this commit https://github.com/mekanism/Mekanism/commit/b3663a37a958328156eba8b08ec4e7e19e04ebee, and this line of code
https://github.com/mekanism/Mekanism/blob/faef15691ca71472a1e3732e554ea64bf30d478b/src/main/java/mekanism/common/base/EnergyAcceptorWrapper.java#L145
The simulated energy transfer isn't converted back to the proper unit and is returned as EU, changing the line to ```return fromEU(toTransfer);``` seems to fix the issue.

**Comment by pupnewfster** [comment]
I will look into it a bit more today, but I believe you are right. I failed to catch it because when testing I had everything set to a 1:1 conversion ratio so I could quicker tell if there was any total loss of power.
