### ISSUE TITLE
Robit Duplication Bug

### ISSUE THREAD

**Issue by Focamacho** [mekanism/Mekanism#5454]
**Issue description:**
You can duplicate items using a Robit

**Steps to reproduce:**
1. Place a Chargepad in the ground
2. Put a Robit in the chargepad
3. Turn on the Follow mode & Drop Pickup mode
5. Place a stackable block that holds items in after being broken(Like Immersive Engineering Wooden Storage Crate)
6. Put some items into the Wooden Storage Crate
7. Break the Crate and let the Robit pickup it
8. Drop more empty crates for Robit
9. All the collected crates by the Robit will be the same as the first (See the video for more info)

**Version (make sure you are on the latest version before reporting):**
**Forge:** 1.12.2 - 14.23.5.2836
**Mekanism:** Mekanism-1.12.2-9.7.3.374

**If a (crash)log is relevant for this issue, link it here:**

https://www.youtube.com/watch?v=3y5bt98in9Y

**Comment by thiakil** [comment]
Confirmed fixed on  #5451
