### ISSUE TITLE
[1.7.10] Issue connecting to 'http://aidancbrady.com/data/versions/Mekanism.txt.'

### ISSUE THREAD

**Issue by Rulenine** [mekanism/Mekanism#5457]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I know I'm using an older version, but some mods I run require 1.7.10. So forgive me if this just isn't supported anymore, but we really want to use this mod!

I'm getting server restarts and occasional crashes, all of which log the following error:

```
2:45:10 PM CONSOLE: [ERROR] An error occured while connecting to URL 'http://aidancbrady.com/data/versions/Mekanism.txt.'
2:45:10 PM CONSOLE: [ERROR] An error occured while connecting to URL 'http://aidancbrady.com/data/capes/Mekanism.txt.'
```

I can't find where this URL is being referenced in any of the config or jar files. I'm happy to just disable any feature or item that might be causing this if it means the mod will work. Any suggestions?

#### Steps to reproduce:
1. Install Jar files
2. Start server and play. Issue occurs often, restarting server. Sometimes crashes server/
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.7.10-Forge10.13.4.1558-1.7.10
**Mekanism:** MC version 1.7.10, Mekanism 9.1.1
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Your Mekanism version number is missing the build number, but I *think* the latest build on Curse fixed this: https://minecraft.curseforge.com/projects/mekanism/files/2475797
