### ISSUE TITLE
Glitched digi miner cause console spam and server crash

### ISSUE THREAD

**Issue by Trnrr** [mekanism/Mekanism#5458]
#### Issue description:
The digi miner glitched somehow and was not destroyable. When it was in view it sent a massive list of errors to the console. It just spammed over and over till the  server crashed. The log file was over 800mb long and only displayed the same error.

When it glitched it was not able to be destroyed. When you would left click it, the model would disappear but the blocks where it took up would still show highlighted. I had to use world edit to remove it. After I removed it, the errors stopped.

The error it displayed. It showed the coords of where the digi miner is. I just removed them.
`[Server thread/ERROR] [Mekanism]: Found tile TileEntityReactorPart{tileType=SpongeTileEntityType{id=bigreactors:bigreactors:tileentityreactorpart, name=bigreactors:tileentityreactorpart, TileEntityClass=class erogenousbeef.bigreactors.common.multiblock.tileentity.TileEntityReactorPart}, world=WorldServer{Name=factions, DimensionId=2, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=XCORD, y=YCORD, z=ZCORD}, blockMetadata=-1} instead of an IAdvancedBoundingBlock, at BlockPos{x=XCORD, y=YCORD, z=ZCORD}. Multiblock cannot function`

#### Steps to reproduce:
1. get digi miner glitched
2. go next to it
3. see console spam

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2807
**Mekanism:** Mekanism-1.12.2-9.6.7.360
**Other relevant version:** 
**ExtremeReactors(big reactors port)**: ExtremeReactors-1.12.2-0.4.5.65
SpongeForge: 1.12.2-2768-7.1.6-RC3616

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
The only thing the log showed was this error `[16:36:45] [Server thread/ERROR] [Mekanism]: Found tile TileEntityReactorPart{tileType=SpongeTileEntityType{id=bigreactors:bigreactors:tileentityreactorpart, name=bigreactors:tileentityreactorpart, TileEntityClass=class erogenousbeef.bigreactors.common.multiblock.tileentity.TileEntityReactorPart}, world=WorldServer{Name=factions, DimensionId=2, DimensionType=minecraft:overworld, DimensionTypeId=0}, pos=BlockPos{x=XCORD, y=YCORD, z=ZCORD}, blockMetadata=-1} instead of an IAdvancedBoundingBlock, at BlockPos{x=XCORD, y=YCORD, z=ZCORD}. Multiblock cannot function`
[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment]
Please try to reproduce with the latest version of mekanism [9.7.4.375](https://minecraft.curseforge.com/projects/mekanism/files/2707235) There have been a large number of internal changes since the 9.6.x version of Mekanism.

**Comment by Trnrr** [comment]
Ok I will try it on our test server and if it seems fine Ill put it on our live server. I'll let you guys know if it happens again.

**Comment by thiakil** [comment]
Looking at the error it's another sponge failure. Nothing much we can do if they're putting the wrong tile entity there
