### ISSUE TITLE
Crash on PreInit

### ISSUE THREAD

**Issue by Testo0987** [mekanism/Mekanism#5459]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism crashing on startup
Running Intellij Minecraft Client

#### Steps to reproduce:
1. Run intellij Minecraft Client
2. Have Draconic evolution, Modular Machinery installed as a source
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:*1.12.2 v2800* 
**Mekanism: 9.7.4.375** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/Qpd7Nmux

**Comment by thiakil** [comment]
I don't really know why you've got all those mods as modules in your project, but it looks like your mappings versions don't match.

The supported way of using Mekanism as a dependency is to have the api jar as a compile only dependency, and the mods in the mods folder

**Comment by Testo0987** [comment]
Thank you!
