### ISSUE TITLE
Is a bedrock version port possible with the new scripting api?

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5461]
I was just wondering if it would be possible to port this mod to bedrock with the new scripting API available. I am not very experienced in java programming but do have some experience with c and c++. The first things I would like to try making in it would be the energized smelter, solar panel, and basic universal cable. Not sure how difficult it would be to program these 3 things. Am I over my head in this?

**Comment by thiakil** [comment]
You are welcome to try (given the mods licence), however I know not about how achievable it is.
