### ISSUE TITLE
server crash loop due to tier installers

### ISSUE THREAD

**Issue by MasterSloth1** [mekanism/Mekanism#5464]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
went to use the basic tier installer on a enrichment chamber

#### Steps to reproduce:
1. right click enrichment chamber with a basic tier installer
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2831
**Mekanism:** 	Mekanism-1.12.2-9.7.2.373.jar
**Other relevant version:** on a server, no sponge installed

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
https://paste.fedoraproject.org/paste/H~-289DBztYo97xkpYlqqQ/

**Comment by thiakil** [comment]
You're using an old version of the mod, please re-test with the latest; I can't reproduce in dev

**Comment by MasterSloth1** [comment]
seems to have fixed itself we updated the server to use
