### ISSUE TITLE
Artificial Sun Machine

### ISSUE THREAD

**Issue by jwhite8559** [mekanism/Mekanism#5469]
**Describe the the feature you'd like**
A clear and concise description of what you want.
The feature I am requesting is a new machine that would create artificial sunlight. This would be used to be able to create artificial sunlight for solar powered machines. It would of course require energy to run. You could make it a multiblock machine that you could build in the air and it would look like a sun when it is complete and powered with energy. This "Artificial Sun" would only provide sunlight to machines that are in a 32 x 32 radius so as to not be too powerful. 

**Describe alternatives you've considered**
I have thought about looking up for other mods that provide artificial sunlight but don't know if they would be able to work in conjunction with mekanism or not. As well I have asked about the server I play on be set to always day but they are not willing to do so.

**Additional context**
None that I can think of at this time.

**Comment by aidancbrady** [comment]
Kinda defeats the purpose of solar power when you create an artificial sun using energy. It's an interesting idea but I don't see this getting implemented in Mekanism.
