### ISSUE TITLE
Keep crashing on log in with Mekanism issue

### ISSUE THREAD

**Issue by Pabsb** [mekanism/Mekanism#5473]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I constantly crash on joining my multiplayer server and all the logs show due to some error rendering mekanism. I am able to log on when I kill myself but when I get my items it crashes me again

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.25.5.2781** 
**Mekanism: 1.12.2-9.7.1.371** 
**Other relevant version: Enigmatica Expert pack version 1.62** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://paste.ee/p/lOZNW

**Comment by pupnewfster** [comment]
It seems that there is some invalid meta transmitter that you have and it is trying to render. I think we should be able to add some form of safety check to it though I will need to talk with @thiakil what we should default it to.

In the meantime however, you should be able to use an editor such as NBTExplorer to edit your player.dat file and remove the faulty item. The item you are looking for would look like `mekanism:transmitter:31`

**Comment by pupnewfster** [comment]
Actually there is more work that needs to be done so this will probably end up being pushed to version *after* the next one (so version 9.7.6 should fix this) as there should be no legit way to get the items with the data that break it.

**Comment by pupnewfster** [comment]
Closing this as in 1.15 it is not possible to get items with invalid meta (as meta no longer exists), and we have also added extra enum bound safety checking anyways.
