### ISSUE TITLE
[Bug] Creative Gas Tank emptying by Ultimate Pressurized Tube

### ISSUE THREAD

**Issue by andrelec1** [mekanism/Mekanism#5476]
#### Issue description:

Build x5 factorie
Use creative gas tank, didn't change setting.
Use ultimate pressurized tube in extract mod.
creative gas tank isn't infinit/infinit anymore ....
 decrease over time  ( and stuck a 0 / infinit )

change the setting to auto pull on all face,
change the tube to normal state,
creative gas tank not decrease anymore 

![image](https://user-images.githubusercontent.com/3273204/57733883-df04f600-76a0-11e9-82f3-3b520537fc17.png)

![image](https://user-images.githubusercontent.com/3273204/57733891-e3311380-76a0-11e9-8100-875e51205c3d.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-14.23.5.2772
**Mekanism:** Mekanism-1.12.2-9.4.13.349.jar
**Other relevant version:** mod pack automaton 1.5 ( with extra mod )

**Comment by pupnewfster** [comment]
Seems to happen when auto eject is manually turned off for the creative gas tank and then the tube is set to pull.

**Comment by pupnewfster** [comment]
Forgot to link it from the commit but this is fixed by https://github.com/mekanism/Mekanism/commit/99df6a3926862690dd3ad643fdd4c75b60b86c9b
