### ISSUE TITLE
[1.12.2] [suggestion] Plastic Barrier Gate

### ISSUE THREAD

**Issue by ToMe25** [mekanism/Mekanism#5483]
**Describe the the feature you'd like**
I would suggest to add a Fence Gate type of Plastic Block as i think it's realy annoying to have all this colored Fences but no Gates.

**Comment by pupnewfster** [comment]
Didn't even realize there was an issue for this but this is included in 1.15 as part of Mekanism Additions (which is where the plastic blocks have been moved)
