### ISSUE TITLE
Game crash and world broken upon creating steam turbine multiblock

### ISSUE THREAD

**Issue by BjornPijnacker** [mekanism/Mekanism#5487]
Upon creating the multiblock structure of the turbine multiblock the game crashed and the world is now unable to load. [This is the error](https://pastebin.com/6ZKyRwQP)

[List of installed mods](https://pastebin.com/VadJ6BYL)

More info can be delivered upon request

**Comment by AfterRebelion** [comment]
This happened to me as well when updating from 9.7.4 to 9.7.5.
Reverting to 9.7.4 fixed this for me. So the world doesn't seem to be corrupt.

**Comment by pupnewfster** [comment]
I believe this is the same issue as #5485 which will be fixed in 9.7.6 @thiakil could you confirm that your changes should fix this as well

**Comment by thiakil** [comment]
yup, thats the exact same trace
