### ISSUE TITLE
(1.7.10) Client multipart @(Coords) not found

### ISSUE THREAD

**Issue by NothingTheta** [mekanism/Mekanism#5489]
#### Issue description:
When removing multiblock machines via Worldedit or another mass removal method it will cause any players to load it to get disconnected with this issue.
![unknown](https://user-images.githubusercontent.com/47882675/58299290-5bd05800-7da4-11e9-8a03-07c96cabff65.png)

#### Steps to reproduce:
1. Build a Mekanism multiblock. (I find the Thermal Evaporation Plant to work well)
2. Use something that mass removes. (Draconic Tools or Worldedit)
3. Unload and reload said chunks.

#### Version:
**Forge:** 1.7.10-Forge10.13.4.1614-1.7.10
**Mekanism:** 1.7.10 9.1.1.1031
**Other relevant version:** N/A

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

Doesn't Crash

My first ish GitHub post so I hope I did well.

**Comment by thiakil** [comment]
Using something like world edit is not really supported, there's not much we can do since it would go outside our safety measures anyway

**Comment by NothingTheta** [comment]
Do you know of any ways to fix it? I believe putting the blocks exactly back fixes it but that's slightly out of the question in most cases.

**Comment by NothingTheta** [comment]
I tried to find the said machine in the world file but was unsuccessful, If there is a good way to remove the "multipart" please let me know Cheers

**Comment by thiakil** [comment]
Unfortunately I don't know how multipart worked in 1.7
