### ISSUE TITLE
Industrial Turbine Crash 

### ISSUE THREAD

**Issue by fiieryx** [mekanism/Mekanism#5499]
I was finishing my turbine, and when i put the last block to finish the multi-block structure... my game crashed, and now i simply can't load my world

Minecraft 1.12.2
Forge: 14.23.5.2838
Mekanism: 9.7.5.376 for 1.12.2

Crash report:
https://pastebin.com/pUp1zF1t

**Comment by sromi** [comment]
The exact same thing just happened to me.

Minecraft 1.12.2
Forge: 14.23.5.2838
Mekanism: 9.7.5.376 for 1.12.2

Crash report:
https://pastebin.com/M1et0ike

**Comment by skuIIs** [comment]
Minecraft 1.12.2
Forge: 14.23.5.2838
Mekanism: 9.7.5.376 for 1.12.2

[https://pastebin.com/LJUwWtdF](https://pastebin.com/LJUwWtdF)

**Comment by skuIIs** [comment]
Duplicate of #5485. Please close.
