### ISSUE TITLE
Bug report. after the start crash (transport)

### ISSUE THREAD

**Issue by MysteryLP** [mekanism/Mekanism#5500]
Every time the server starts it crashes after about 2-5 minutes
Its on a Sever for FTB Stoneblock 2

#### Version (make sure you are on the latest version before reporting):
FTBserver-1.12.2-14.23.5.2836-universal
Mekanism-1.12.2-9.7.5.3765 and Mekanism-1.12.2-9.7.5.376
MekanismGenerators-1.12.2-9.7.5.375 and MekanismGenerators-1.12.2-9.7.5.376
MekanismTools-1.12.2-9.7.5.375 and MekanismTools-1.12.2-9.7.5.376

https://pastebin.com/64PE17wh

I need help, I have no idea what is.

regards Tim

**Comment by pupnewfster** [comment]
Closing this as I believe you mentioned on discord you are no longer having any issues with 9.7.6
