### ISSUE TITLE
FIXME: Packet handling error

### ISSUE THREAD

**Issue by mistek131995** [mekanism/Mekanism#5501]
Sponge: spongeforge-1.12.2-2825-7.1.6-RC3755
Forge: 1.12.2 - 14.23.5.2838
Mekanism: Mekanism-1.12.2-9.7.5.376 + MekanismGenerators-1.12.2-9.7.5.376 + MekanismTools-1.12.2-9.7.5.376

[LOG.txt](https://github.com/mekanism/Mekanism/files/3248492/LOG.txt)

**Comment by pupnewfster** [comment]
This should be fixed in [9.7.6](https://minecraft.curseforge.com/projects/mekanism/files/2719846)
