### ISSUE TITLE
Purification chamber accepts hydrogen as an input

### ISSUE THREAD

**Issue by Murdermancer** [mekanism/Mekanism#5502]
Hello!

Just ran into an issue where I accidentally put a hydrogen tank into the Purification Chamber, and it accepted this as an input material. The Hydrogen gas is now filling the Infusion Buffer, and there's no way (that I can find, at least), to remove it.

**Comment by pupnewfster** [comment]
That seems to be a bug, iirc it is not supposed to be able to accept gases it does not have a recipe for.

**Comment by pupnewfster** [comment]
The purification chamber accepting hydrogen is fixed and will be included in 9.7.8; however, there still isn't really a way to remove it from the buffer. Not sure what @thiakil 's thoughts on what we should do about that are.

**Comment by thiakil** [comment]
I don't believe there's ever a way to get it out of there once its it? So voiding on load would be fine

**Comment by pupnewfster** [comment]
That would work, when it is loading the gas if it isn't a valid type then it just voids it.

**Comment by Murdermancer** [comment]
That's a clever solution. Thanks for addressing this so quickly!

**Comment by pupnewfster** [comment]
Fix available in [9.7.8](https://minecraft.curseforge.com/projects/mekanism/files/2724543)
