### ISSUE TITLE
How to Integrate with Mekanism?

### ISSUE THREAD

**Issue by skizlit** [mekanism/Mekanism#5503]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Can some one please provide advice as to how mod developers are able to integrate with Mekanism? There is not much information online and I cant find anything useful.
Tried the API cant get it working
Tried "FMLInterModComms.sendMessage" also cant get that working

There is also no Maven to depend on.
Please if anyone is willing to help me that would be great.

Kind regards,

**Comment by pupnewfster** [comment]
If you tell us what you are looking to do, we might better be able to help you figure out which route to go (IMC or API). Also I believe you are correct that there is currently no maven (@thiakil if you could verify), but you can always use the CF Maven to access the jar/api jar.

**Comment by skizlit** [comment]
Hi pupnewfster

All I would like to do is get the Ores, Ingots Dust, Clumps etc, to work with the Mekanism Machines. Basically add my ores to the ore duplication mechanics of Mekanism.

Kind regards

**Comment by pupnewfster** [comment]
Personally I haven't used IMC that much so maybe @thiakil can give better information, but I believe in this case it would be the better solution. A rough tutorial on IMC: https://tutorials.darkhax.net/tutorials/imc/
A mod that I know uses IMC to register ore multiplication recipes with Mekanism: https://github.com/phantamanta44/MekanismOres

Maybe looking through those two will help you figure it out.

**Comment by thiakil** [comment]
The easiest way is to use
```java
MekanismRecipeHelper recipeHelper = mekanism.api.MekanismAPI.recipeHelper();
recipeHelper.addEnrichmentChamberRecipe(new Itemstack(INPUT_ITEM), new ItemStack(OUTPUT_ITEM));
```
Or one of the other methods on the interface of course. You must do this before PostInit phase IIRC.

Indeed there is no official maven, there are some old ones on mine, but as mentioned you can try Curseforge's maven (the api jar is uploaded as an additional file on the main jar), or download the api jar and place it in `<project folder>/libs` and Gradle _should_ automatically pick it up

**Comment by skizlit** [comment]
Thanks for the advice ill have a look at it this evening.
My issue might have been that i was calling it during the PostInit ill try changing were its called and see what happens and provide feedback.

Kind regards,
