### ISSUE TITLE
Ticking player/ 

### ISSUE THREAD

**Issue by bontavi** [mekanism/Mekanism#5506]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
After latest update on the mekanism, it started to crash whenever you place electric pump to the world. And it is impossible to get back to that world.

#### Steps to reproduce:
1. Place electric pump from the mekanism.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 1.12.2-9.7.6.377
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
crashlog, when you have placed electric pump in the world - https://pastebin.com/mcKtPgYc
crashlog, when you try to join the world - https://pastebin.com/JVtwEMXy

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Same as #5504
