### ISSUE TITLE
Crafttweaker removeAllRecipes method of metallurgic infuser targets Chemical Crystallizer instead.

### ISSUE THREAD

**Issue by SiliconEnt** [mekanism/Mekanism#5507]
#### Issue description:
The removeAllRecipes Crafttweaker method added for the Metallurgic Infuser seems to target the Chemical Crystallizer instead.

#### Steps to reproduce:
1. Create a blank instance with Mekanism and Crafttweaker
2. Create a crafttweaker script with one line: mods.mekanism.infuser.removeAllRecipes();
3. Launch the game
4. The Metallurgic Infuser still has its recipes; they still show in JEI and still work. The Chemical Crystallizer, however, does not. JEI shows no Crystallizer recipes and the Crystallizer accepts no gas input.

#### Version (make sure you are on the latest version before reporting):
Minecraft 1.12.2
Forge 12.23.5.2838
JEI 4.15.0.278
Mekanism 9.7.7.378
Mekanism Generators 9.7.7.378
Crafttweaker 4.1.18
Instance is otherwise blank.

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
I've never used gist before, so I hope I'm using it correctly...

Debug.log: https://gist.github.com/SiliconEnt/e1ad101e306ec66287c80faf346bc3db
Latest.log: https://gist.github.com/SiliconEnt/442e43c01e467680366217ccefe86a13
Crafttweaker.log: https://gist.github.com/SiliconEnt/958b592c231106dc14deda52e3406350

**Comment by pupnewfster** [comment]
I see the issue, I think it was due to a copy paste error when I was adding the methods, I will also double check to see if any of the other ones are using the wrong recipe list as well.

**Comment by pupnewfster** [comment]
Fix available in [9.7.8](https://minecraft.curseforge.com/projects/mekanism/files/2724543)
