### ISSUE TITLE
Incompatible mod interaction with Extra Utilities 2

### ISSUE THREAD

**Issue by NLBlacky** [mekanism/Mekanism#5509]
#### Issue description: 
We updated to Stoneblock 1.14.0 an hour ago. Server was crashing as soon as it came online. It seems that Mekanism was causing it. It looks like it has some kind of incompatible mod interaction with Extra Utilities 2. Extra Utilities 2 was not changed in this modpack update which means it should be Mekanism that is causing it.

I'm aware that the modpack is running an older version of Mekanism (since it was updated only a few hours ago) but I'm afraid the same issue might happen in the newer version as I've not seen anyone else reporting this yet. 

I also reported this on the Stoneblock 2 github. Link can be found below:
https://github.com/FTBTeam/FTB-Presents-Stoneblock-2/issues/539

#### Steps to reproduce:
1. Start the server and it will crash after it is done starting

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2836-universal.jar
**Mekanism:** Mekanism-1.12.2-9.7.6.377.jar
**Other relevant version:** extrautils2-1.12-1.9.9.jar

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://paste.feed-the-beast.com/view/a11b1295
https://paste.feed-the-beast.com/view/96706a76
https://paste.feed-the-beast.com/view/bfafdd11

**Comment by pupnewfster** [comment]
I believe this is the same as #5504 so updating mekanism to 9.7.7 *should* fix it.

**Comment by NLBlacky** [comment]
Could be, I'm not sure. I see they used the recommended build which I've done as well, but I also used an older Sponge version in one of the crash logs listed above which had the same result.

**Comment by pupnewfster** [comment]
I am not sure if the issue is as much to do with sponge, as it is the same stack trace if you go down to their lower comment. The `EnumMap.typeCheck` from `CapabilityWrapperManager.getWrapper`, so I believe they are the same though they might have been caused by two different things calling that part of the code. But 9.7.7 should fix that part of the code so when it gets called it doesn't cause a crash.

**Comment by thiakil** [comment]
Yes looking at the first crash it is the exact same (and no it wasn't sponge specific, I just didn't un tag it)
