### ISSUE TITLE
Metallurgic Infuser isn't using oreDict to accept Diamond Dust for infusions

### ISSUE THREAD

**Issue by galaxy119** [mekanism/Mekanism#5510]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The metallurgic infuser doesn't use oreDict for accepting Diamond Dust.

#### Steps to reproduce:
1. Put Diamond Dust from another mod (IC2 for instance) in the metallurgic infuser.
2. It will not accept it as infusion medium.
3. ???
4. Profit?

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.5.2838-universal
**Mekanism:** 9.7.6.377
**Other relevant version:**

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

Both dusts have the oreDict name "dustDiamond" but only the Mekanism dust works.

**Comment by thiakil** [comment]
Unfortunately none of the machines support Oredict, has been on the list for a while, #4646

**Comment by thiakil** [comment]
I've been reminded by another Mek dev that we *do* check for registered dusts (https://github.com/mekanism/Mekanism/blob/33cc2033ff6b13f4dda45e1b455d29472926a143/src/main/java/mekanism/common/integration/OreDictManager.java#L374)

The specific dust not working implies the other mod is registering it to the Oredict too late, i.e. after we've done the check. Oredict entries should be registered when the item gets registered whenever possible. We'll attempt to run this at the end of the recipe event to try to capture more cases, but we can't solve every bad mod.

**Comment by galaxy119** [comment]
Indeed, I'll report it to IC2 devs and tell them to stop being tinybrain with their object registrations :+1:
