### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by bigenergy** [mekanism/Mekanism#5511]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Start server
2. Get crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2814
**Mekanism:** Mekanism-1.12.2-9.7.7.378

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://hastebin.com/arulovaxil.sql

**Comment by thiakil** [comment]
Looks like Spigot or whatever you're running is modifying vanilla class behaviour, not too surprising.

**Comment by thiakil** [comment]
Should be fixed by 55e8980b4a137cf52184d7e2b418a963b8a0cd9b

**Comment by pupnewfster** [comment]
Fix available in [9.7.8](https://minecraft.curseforge.com/projects/mekanism/files/2724543)
