### ISSUE TITLE
Mekanism Universal Cables and Mechanical Pipes Transmitt more power at longer distances.

### ISSUE THREAD

**Issue by ToMe25** [mekanism/Mekanism#5514]
#### Issue description:
Mekanism Universal Cables, Mechanical Pipes and most likely Pressurized Tubes transfer more Stuff on longer distances. for Example one Ultimate Universal Cable Transfers 12.8krf/t but with two of them between the Power Source and Drain it transfers 25.6krf/t.

This is a very old(even Exists in all 1.7.10 versions i know) and commonly known Bug(many YouTubers and Streamers talked about it Years ago) so i think there might already be a Bug Report about this but as i wasn't able to find it i report it anyways, so if you find another Bug Report about this comment it and i will close this Issue.

#### Steps to reproduce:
1. Build a Power Storage that tells you how much Energy it receives(for example an Induction Matrix)
2. get a Strong Power Source and place it one block away from the Input of the Storage
3. Place a Universal Cable in between them
4. look at the Input of the Storage and remember it
5. move the Power Source one Block further away and place another Universal Cable at its old position
6. look at the Input of the Storage and see its now twice as much as last time

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838 and many older
**Mekanism:** 9.7.7.378 and many older

**Comment by thiakil** [comment]
I'm pretty sure this is intended, not a bug
