### ISSUE TITLE
server crash when loading chunk after #5505 fix, Fixed TE flooded console

### ISSUE THREAD

**Issue by ROMVoid95** [mekanism/Mekanism#5516]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
after fixing the issue in #5505 the server was able to boot into world. After tp to base with known Mekanism builds the server crashes on chunk load and console is flooded with 
[Chunk I/O Executor Thread-1/INFO] [Mekanism]: Fixed TE from ....

This server is running sponge and can confirm non-sponge resulted in identical error. my apologies if this is not mekanism related just wanted to be sure  

#### Steps to reproduce:
1. Same to reproduce form #5505 
2
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2838
**Mekanism:** 1.12.2-9.7.7.378
**Other relevant version:** 
**Sponge:**  spongeforge-1.12.2-2825-7.1.6

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
Crashlog -> https://pastebin.com/z6eZMYS8
Lastest.log -> https://gist.github.com/ROMVoid95/9d91b152ef0ec160d6db8058424bbb04

**Comment by thiakil** [comment]
Show me the crashlog from without sponge. There is nothing in that stacktrace pointing (directly) to Mekanism

**Comment by thiakil** [comment]
The `fixed TE from` is a one time log when your saved data is being fixed to the new IDs

**Comment by artdude543** [comment]
Heyo!

We had a few reports with users of our modpack having crashes when porting their worlds from a version to a newer version which seems to have added the TE data fixer. But... something somewhere is causing the worlds to be non-usable. 

Report: https://pastebin.com/pEUUPx0m
<details>
  <summary>Converted Classes</summary>

![image](https://user-images.githubusercontent.com/1885466/63284450-83539580-c2ab-11e9-9244-05cca3257ed4.png)
</details>

We are using `1.12.2-9.7.9.380` in our beta release of the pack (yes it's old) but I have tested myself with `1.12.2-9.8.1.383` and the same issue is about. Removing Mekanism allows the world to load w/o any issues, I also went back and downgraded all our mods to versions in our `3.0.8` of the pack and only updated Mekanism to `1.12.2-9.7.9.380` and the issue still occurs so I narrowed it down to here.

I don't have any actual logs of the mod causing the issue, but as it's always constantly firing when then data-fixer is running. It would suggest either a party mod or this mod is not liking a change happening in the world. Could this be looked into somewhat, please?

I can supply a world download if you wish to help with the debugging.

Thanks,
SevTech Developer

**Comment by thiakil** [comment]
Hiya Kieron,

From the stacktrace this looks related to recent(ish) changes that were made around getting transmitters (cables/pipes/etc) to correctly load/refresh their connections when they're added to the world.

I have some ideas, and will try to get to it this weekend

**Comment by Trnrr** [comment]
Hey I'm getting the same crash report as above and am wondering if there is a fix or if you could point me in the right direction on how to fix it. When ever a player goes to the coords in the crashreport it instant crashes the server. This happens with or without sponge. I included the log when the player joins, thats when it crashes.

Log with sponge: https://gist.github.com/Trnrr/a016bb029a66679511ce7c9d762e8958
Crash Report with sponge: https://gist.github.com/Trnrr/1c8761146b972ceacba757eb8e2570f0

Log **without** sponge: https://gist.github.com/Trnrr/d2678d29f578367e68855dca666fc496
Crash report **without** sponge: https://gist.github.com/Trnrr/ab742526edd50d554bf59c514a529434

**Comment by Trnrr** [comment]
@thiakil Is there anything I can do to help you try and solve this? I've been racking my head around this for the last few days and nothing Im doing is working. The only solution I've found is wiping the players chunks, which is pretty shitty.

- I've tested downgrading to mek version 389, 387 & 381 and all of them instant crash when you connect still
- Some weird stuff happened while testing. Sometimes after certain restarts/version changes the chunk magically became unglitched. Not sure what causes this. Wasn't able to pin point it.
- All of the crashes on the various versions show the same crash report

Is there anything I can do or any version of mek I could downgrade to until this is fixed? I would really appreciate a reply.

**Comment by thiakil** [comment]
Either wait until I look at it code wise, keep downgrading, or try remove all Mekanism pipes/tubes/cables from their chunks

**Comment by Trnrr** [comment]
Ok thank you for the reply. I really appreciate it. I will keep downgrading versions and see if anything changes. If that doesn't change anything I'll try to mcedit the pipes/tubes/cables out of the base. Thank you

**Comment by ROMVoid95** [comment]
sorry about that, didnt mean to close this

**Comment by Trnrr** [comment]
I wasn't able to get it fixed. Even after removing the items from the chunk and downgrading the mod I am still getting crashes. I could have missed some pipes but I don't think I did since I was wiping the chunk and that players base was in 1 chunk.

Are the pipes/tubes/cables  whats affected? I'm planning on banning them until this gets fixed (if ever). Also do by chance know in what version of mek did you start changing the:
> From the stacktrace this looks related to recent(ish) changes that were made around getting transmitters (cables/pipes/etc) to correctly load/refresh their connections when they're added to the world.
I want to downgrade, but since none of my downgrading fixed I'm unsure of what version to do. I went back probably 8-10+ files. @thiakil

**Comment by thiakil** [comment]
It could be anything really, the crash reports offer no useful information unfortunately

**Comment by pupnewfster** [comment]
No idea what is going on, but given we are not actively developing 1.12 anymore, I am going to go ahead and close this, as my best guess is that it had to do with some weird race condition/halt in data fixers, and data fixers are not even available yet to mods in 1.15.
