### ISSUE TITLE
Mekanism crash

### ISSUE THREAD

**Issue by Pabsb** [mekanism/Mekanism#5517]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Game crash

#### Steps to reproduce:
N/A

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2781** 
**Mekanism: 1.12.2-9.7.1.371** 
**Other relevant version: Engimatica Expert Pack 1.62** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://paste.ee/p/4XzKD
[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment]
Update mekanism.
