### ISSUE TITLE
Digital Miner doesnt mine and then turns off

### ISSUE THREAD

**Issue by christoph19900** [mekanism/Mekanism#5518]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Digital Miner going into Search Mode, finding a seemingly random number of ores and then turning himself off.

#### Steps to reproduce:
1. Place Digi Miner down and connect power
2. Select Ore in the Config of the Digi Miner and Press Start
3. Digiminer produces seemingly random number of ores to mine, doenst count up and then stops completly.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2
**Mekanism:** 1.12.2
**Other relevant version:** Minecraft Modpack IndustrialBox Version 1.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No crash Log

**Comment by thiakil** [comment]
There's probably some kind of protection mod that doesn't allow fake players installed

**Comment by christoph19900** [comment]
well we also thought so, we enabled fake players, also we have a protection plugin so we moved the miner outside of the boundaries and set the radius not interfering with protected areas

is there any way to make "fake players" op / owner on the server to let them run freely if theres anything blocking from that side

**Comment by christoph19900** [comment]
also adding to the problem is that, on one occasion i left it searching, then a server restart happened and as i joined i pressed start and it indeed was mining. then i wanted to reconfigure and it went back to searching, displaying a random number of ore and then stopping

**Comment by thiakil** [comment]
> is there any way to make "fake players" op / owner on the server to let them run freely if theres anything blocking from that side

Yes, the uuid is logged by Mekanism on start up. I think there might be an option under the `/mek` command to do it automatically too.
