### ISSUE TITLE
PRC not accepting Biofuel

### ISSUE THREAD

**Issue by game4lols** [mekanism/Mekanism#5521]
#### Issue description:
PRC will not accept biofuel from logistic pipes, but will accept substrate.
Sides are configured correctly, and pipe is pulling from chest with biofuel, but no biofuel is moved into pipes and into PRC. Substrate WILL be pulled into PRC however, which is odd, but means my setup is definably working.

This is becoming a problem as I'd like to begin making Ethelene but have to manually put in biofuel to get ethylene, a stack at a time. Hoppers also do not work, nor do other mods transport pipe options, and because substrate IS being inserted, the pipes and the PRC are set up properly. The PRC DOES make ethylene, but I can't automatically insert biofuel.

I really feel as if this is due to some other mod I added recently, because I had it working before. Since, I have added and removed a few mods, along with updating everything and started a new world. I have no idea what mod could even affect this.

#### Steps to reproduce:
1. Hook up a pipe that should pump biofuel into the PRC (PRC can be completely empty of have water/hydrogen in already)
2. Notice the lack of biofuel in PRC
3. Put substrate into chest with biofuel. Watch it go through pipes and into PRC

#### Version (make sure you are on the latest version before reporting):
**Forge:**   forge-14.23.5.2836
**Mekanism:** 	Mekanism-1.12.2-9.7.7.378
**Other relevant version:**

**Comment by thiakil** [comment]
Is there any NBT getting added to the Biofuel items? (by another mod)

**Comment by game4lols** [comment]
Nope, though it does have an ore dictionary name, itemBioFuel, if that's supposed to be there or not,

**Comment by thiakil** [comment]
Hmm there's definitely something weird here, i can insert with pipes when machine is empty, but shift clicking with one when a stack of 63 is in via the GUI doesn't (the code that does the shift click and can-pipe-insert is the same/very similar)

**Comment by Graphicscore** [comment]
Hi, I can reproduce this, for me it only works if a machine is actively pushing items into the pipes (for example using a Logistical Sorter works) but using the pipes by themself will not work. Had to setup a chest with a logistical supporter attached to it.

**Comment by game4lols** [comment]
Just tried that now, and it works for me too. I'll do that for now I guess. Thanks :)
