### ISSUE TITLE
[01:12:04] [Client thread/INFO] [STDOUT]: [net.minecraft.init.Bootstrap:func_179870_a:553]: #@!@# Game crashed!

### ISSUE THREAD

**Issue by RealCltdj** [mekanism/Mekanism#5522]
im trying to make a modpack and im new. my modpack keeps crashing on startup but i dont know why

[latest.log](https://github.com/mekanism/Mekanism/files/3289510/latest.log)

can someone tell me what i need to do to fiix it.

(has nothing to do with mekanism i dont think im just new to github)

**Comment by CraftalotReloaded** [comment]
It's a crash from the WirelessRedstone mod, please report it here https://github.com/TheCBProject/WirelessRedstone
