### ISSUE TITLE
Not register silver and lead items

### ISSUE THREAD

**Issue by AssB0ys** [mekanism/Mekanism#5524]
**Describe the the feature you'd like**
Please add an option to not register Silver and Lead items - dusts, shards, clumps, crystals. These materials are not obtainable in survival mode, not used by Mekanism mod either.

**Describe alternatives you've considered**
An alternative is to use crafttweaker mod. Is this really necessary? These materials are unobtainable nor they are used in any Mekanism mod crafts.

**Additional context**
Additionally since salt is added by every other cooking/food mod, mekanism recipes that use salt could be configured to use any oredictionaried salt and mekanism salt have the opt-out option as those mentioned above. Although the existence of this particular ingridient(salt) in mekanism mod is not as redundant.

**Comment by thiakil** [comment]
Not registering items based on config is discouraged by Forge, so it's a no from me

**Comment by pupnewfster** [comment]
Eventually (probably for v10) I am sort of planning on reworking how the dust, shard, clump etc stuff works so that if there isn't anything loaded of that type it does not bother registering it. (Along with registering it for other types of ores than just the ones it supports now). Though that may be a while off. For now them existing doesn't really harm anything though.

**Comment by AssB0ys** [comment]
> Not registering items based on config is discouraged by Forge, so it's a no from me

Well, this definitely is new for me. This explains why so many mods don't take approach similar to quarks to mod configuration, although frankly Quark doesn't have any problems with that... Could you link me this part of forges documentation, I read it briefly and this part is not really obvious, maybe I could stop bothering mod authors with pretty much a similar request every time...

@pupnewfster maybe this could be done with a single prototype and just let the user add any ore through json configuration where you can set the color to the base texture, since different metals only have a slight difference in color as of now. And let the crafttweaker handle the recipes other than mekanism and basic furnace processing recipes.

**Comment by AssB0ys** [comment]
Can the corresponding ingots be added? Now I have the following problem: https://github.com/T145/metalchests/issues/78
Mekansim apparently registers `ingotSilver` to the oreDict, while it doesn't add the actual ingot. These should really be removed though as a more proper approach.

**Comment by thiakil** [comment]
Well, no it doesn't actually register it to the oredict, it's a quirk of Forge that the method we use to get a list of ores creates an *empty* list entry in the dictionary.

That's a bug in Metal Chests for not ensuring it is empty. We will change ours, but other mods do use that same method.

**Comment by KokSaker** [comment]
Could you reopen the issue? I use the Mekanism-1.12.2-9.8.1.383.jar and there are still silver and lead dusts(shards, crystals) although there are no mods in my pack that add corresponding ores or ingots. I wonder why keep these items when mekanism doesn't even use these materials internally(by default) and there are other mods(mekanismOres, jaopca etc) that could add such items **if required**.

**Comment by thiakil** [comment]
No, Forge does not recommend conditionally registering items. They will always be registered.
