### ISSUE TITLE
A priority system for the Quantum Entangloporter

### ISSUE THREAD

**Issue by ghost** [mekanism/Mekanism#5525]
**Describe the the feature you'd like**
I would like a priority system for the Quantum Entangloporter.

**Describe alternatives you've considered**
Maybe a system to limit the RF flow into it, or set the buffer size.

**Additional context**
What would happen is there could be a button that allows you to set the priority, and the highest priority will get the energy/items first.

**Comment by thiakil** [comment]
That's not really something we can control without a huge rework - each Entangoloporter frequency is a single buffer shared by all Entangoloporters configured to use it. Which one gets to pull from it first is completely down to the order in which Minecraft ticks the blocks

**Comment by aidancbrady** [comment]
This is achievable using multiple entangloporters with different custom frequencies. Agree with @thiakil that allowing this in a single entangloporter frequency would require a full rewrite of our current system.
