### ISSUE TITLE
Ticking Player

### ISSUE THREAD

**Issue by tenten8401** [mekanism/Mekanism#5535]
Not sure what's up with this one but I have a player on my server and when you go to their base, you just get kicked off for Internal Server Error, with the log below being outputted to the console. I have to assume it's a bounding block somewhere causing issues, but it won't tell me where so I can't remove it.

#### Version:
**Forge:** 14.23.5.2823 (little old I believe, can update if it's probably the issue)
**Mekanism:** 1.12.2-9.7.8.379
**Sponge**: 1.12.2-7.1.6-SNAPSHOT
**SpongeForge**: 1.12.2-2825-7.1.6-RC3716

#### If a (crash)log is relevant for this issue, link it here:
https://gist.github.com/tenten8401/3b07031bcf0646a51948906d5ad8e1c3

**Comment by pupnewfster** [comment]
I think it believes one of our bounding blocks is for some reason a thermal dynamics duct. But I would try updating to forge 2825 (given the version of spongeforge you have is for that version of forge so weird things may happen if they miss-match. Or at least I have heard of various crashes enderio had when people had a different version of forge than the version of spongeforge expected.)

**Comment by tenten8401** [comment]
Just updated to 2825, still seeing the issue.

**Comment by thiakil** [comment]
Your World save data is corrupted/messed-up (as pup mentioned), you'll need to fix it or nuke the chunk

**Comment by tenten8401** [comment]
Is there any way to find out what it's having an issue with? I'd prefer not to nuke the entire base since I'm not even really sure what chunk it is.

**Comment by thiakil** [comment]
Unfortunately not with the info provided by the log. Since it doesn't generate a full crashlog there's no easy way to find the position.

I'd say you could probably use WorldEdit or similar (the external to MC variants) to load the world and find blocks in the area of the TD Duct variety and check their TileEntity data for a mismatch - though I don't have any real experience in this area
