### ISSUE TITLE
Biogenerator and Heatgenerator don't accept items from left side

### ISSUE THREAD

**Issue by Paspartout** [mekanism/Mekanism#5538]
## Issue description:

When trying to input biofuel into the biogen(or e.g. coal to heat gen) it seems
that all sides except the left side work.

Here is a screenshot of the setup:

![2019-06-25_21 54 20](https://user-images.githubusercontent.com/2720369/60129138-a292e280-9794-11e9-96f9-1d266d40a81b.png)

After changing the `getSlotsForFace()` method in TileEntityBioGenerator.java it works fine, but I am not sure if that has any side effects:

```java
    @Nonnull
    @Override
    public int[] getSlotsForFace(@Nonnull EnumFacing side) {
        return new int[]{0};
    }
```

#### Steps to reproduce:
1. Place down a biogen
2. Connect a transporter to it on right side
3. Try to extract biofuel from chest

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2825
**Mekanism:** Latest 1.12 commit on github

**Comment by CraftalotReloaded** [comment]
Seems like the block rotation may also be off inverted when you place them, the other side works fine though

**Comment by thiakil** [comment]
The functionality seems intended - that side only allows access to the Charge Slot

**Comment by Paspartout** [comment]
> The functionality seems intended - that side only allows access to the Charge Slot. Remember that Mekanism is strongly sided in most cases

I wasn't aware of the charge slot and I agree that this seems intended.
Maybe making the sides configurable would be a nice feature in the future since I never used the charge
slot of the generators.
In the meantime maybe making it more obvious which side belongs to which slot would be nice.

**Comment by aidancbrady** [comment]
Recent Mekanism builds for 1.15 have all sides but the right side accessible for the fuel slot in the Heat Generator and Bio Generator.
