### ISSUE TITLE
Turbine Valve Game Crash

### ISSUE THREAD

**Issue by Redorigin28** [mekanism/Mekanism#5540]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Tried to create Multi block Structure With turbine valves and it crashed the server flat out

#### Steps to reproduce:
1.5*5*7 Structure
2.Add valves in anywhere
3.BOOM! crash lol

#### Version (make sure you are on the latest version before reporting):
Skyfactory 4
Forge 14.23.5.2838
#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/k1PzCune

**Comment by pupnewfster** [comment]
Update mekanism
