### ISSUE TITLE
[suggestion] add more speed upgrade in a machine

### ISSUE THREAD

**Issue by rickyhoho** [mekanism/Mekanism#5543]
Can mekanism increase the amount speed upgrade that can put into a machine?

Like industrial craft 2 , it can add a huge number of upgrades into the machine.

If you worry about the cost of making a upgrade ,then i suggest you to add the higher level of upgrades such as advanced upgrade and elite upgrade.

It is because that i am difficult to manage a huge number of machine, so i hope that mekanism can add more speed upgrade into a machine so i can use a machine quickly and use less machine to process my product.

**Comment by rickyhoho** [comment]
also you can add the amount of the electricity use.

**Comment by thiakil** [comment]
You can adjust how much of a boost the upgrades give in the config

**Comment by rickyhoho** [comment]
> You can adjust how much of a boost the upgrades give in the config

how about add it in V10 of mekanism , because not everyone know to change the config

**Comment by pupnewfster** [comment]
While I do sort of like the idea of there being more tiers of upgrades, I think it does not make sense to have it go all that much past the current point it can get to. As in the real world you can only speed things up so much before things just stop really working. (Though it may be interesting to instead of having 8 speed upgrades have either 2 or 3 of each tier and allow for them to be installed together.)

**Comment by rickyhoho** [comment]
> While I do sort of like the idea of there being more tiers of upgrades, I think it does not make sense to have it go all that much past the current point it can get to. As in the real world you can only speed things up so much before things just stop really working. (Though it may be interesting to instead of having 8 speed upgrades have either 2 or 3 of each tier and allow for them to be installed together.)

**Comment by rickyhoho** [comment]
> While I do sort of like the idea of there being more tiers of upgrades, I think it does not make sense to have it go all that much past the current point it can get to. As in the real world you can only speed things up so much before things just stop really working. (Though it may be interesting to instead of having 8 speed upgrades have either 2 or 3 of each tier and allow for them to be installed together.)

However, i think that the speed is not enough for massive production while a large reactor is actually used industrially the increase yield and efficiency.

Therefore, i think modifications to increase production speed is vital and should be added.

**Comment by rickyhoho** [comment]
oh i wrongly closed this issue

**Comment by aidancbrady** [comment]
With the new Ultimate Factories, I'm comfortable with the production power of a single Mekanism machine. As previously mentioned, it is trivial to modify the upgrade boost in the configuration.
