### ISSUE TITLE
Cardboard box does not blacklist pneumaticcraft:security_station

### ISSUE THREAD

**Issue by wideblaze** [mekanism/Mekanism#5548]
#### Issue description:

Cardboard box does not blacklist pneumaticcraft:security_station
I am able to blacklist vanilla spawner but not security station. 
cardboard box removes security station protection

#### Steps to reproduce:
1. place security station
2. use box on security station
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
MCVER=1.12.2
FORGEVER=14.23.5.2823
**Mekanism:** 
Mekanism-1.12.2-9.7.8.379

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

# Use this file to tell Mekanism which blocks should not be picked up by a cardboard box.
# Proper syntax is "NAME META". Example (for stone):
# minecraft:stone 0
minecraft:mob_spawner 0
pneumaticcraft:security_station 0

from lastest.log:
[10:28:43] [Client thread/INFO] [Mekanism]: Hooked into AE2 successfully.
[10:28:43] [Client thread/INFO] [Mekanism]: Finished loading Cardboard Box blacklist (loaded 2 entries)
[10:28:43] [Client thread/INFO] [Mekanism]: Hooking complete.
[10:28:43] [Client thread/INFO] [sonarcore]: Adding Discharge Values
[10:28:43] [Client thread/INFO] [sonarcore]: Added 4 Discharge Values

**Comment by pupnewfster** [comment]
Not sure if it is that we are using the wrong meta data or not (we are using the meta data of the block not of the item), so going to leave this open for now until we get a chance to look into it more. But if you use the wildcard meta `32767` it should block all meta variations of the security station. Which at least for this case should work for your purposes.

```
pneumaticcraft:security_station 32767
```

**Comment by wideblaze** [comment]
tested and works (pneumaticcraft:security_station 32767) thanks for the quick response!

forgot to add: pneumaticcraft-repressurized-1.12.2-0.11.3-366

**Comment by pupnewfster** [comment]
Closing this as it was more or less resolved and in 1.15 I moved cardboard box blacklisting to use the vanilla tag system which will have better built in support for error logging of invalid registry names.
