### ISSUE TITLE
Precision sawmill does not accept torches or ladders via automated input

### ISSUE THREAD

**Issue by The--Captain** [mekanism/Mekanism#5549]
#### Issue description:
Precision sawmill does not accept torches or ladders via automated input.  It work manually, but not via hoppers, etc.  All other materials work using automated methods

#### Steps to reproduce:
1.  Put hopper on top of precision sawmill. 
2.  Put torches in hopper
3.  Headdesk

It looks like you didn't add any custom recipe handlers for itemstacks > 1, so it only accepts automated input of itemstacks of 1, which of course breaks the torches and ladders input when automated, or such is my guess when looking at the code.

**Comment by pupnewfster** [comment]
Sort of the same issue as #5521 (at least in terms of cause), and will be fixed when 9.7.9 gets released. At some point the recipe comparison accidentally gained a check for comparing stack sizes.

**Comment by The--Captain** [comment]
Thanks.  Glad to know I'm not crazy.

**Comment by thiakil** [comment]
Should be fixed in 9.7.9 release
