### ISSUE TITLE
Mechanical pipe not pulling from quantum entangloporter

### ISSUE THREAD

**Issue by rux616** [mekanism/Mekanism#5550]
I have the same issue as a previously closed one, #5100 

![mek_entanglo_no_pull](https://user-images.githubusercontent.com/5643061/60569197-f620a580-9d2b-11e9-9501-0d628ac07378.PNG)

As you can see, I have ult mech pipes pulling from a creative tank going into a quantum entangloporter (all sides set as input), then another quantum entangloporter on the same channel (all sides set as output) where ult mech pipes _should_ be pulling and sending water to a fluid trash can. This is not happening.

Mods:
Mekanism 9.7.8.379
Mekanism: Generators 9.7.8.379
Just Enough Items 4.15.0.268
Extra Utilities 2 1.9.9
Forge 14.23.5.2838

**Comment by thiakil** [comment]
Please show your side config for fluids

**Comment by rux616** [comment]
Visual confirmation of what I stated in my original post, as requested.

Input QE (the one on the right):
![mek_qe_input_fluid_config](https://user-images.githubusercontent.com/5643061/60602836-d0b68a80-9d71-11e9-9178-864cea7ddbe0.PNG)

Output QE (the one on the left):
![mek_qe_output_fluid_config](https://user-images.githubusercontent.com/5643061/60602851-da3ff280-9d71-11e9-8f5c-ffaec9fe7771.PNG)

**Comment by pupnewfster** [comment]
Couple questions:
1. Does it pull without and fill up the pipes if you remove the fluid trash can? One guess of mine is it could be that it just is ejecting it all same tick it pulls so doesn't render as having any fluid in it.
2. Does anything change both for how you have it setup and without the trash can if you set it to auto eject.

**Comment by rux616** [comment]
So to eliminate the question of whether the trash can is at fault, I have removed it and replaced it with an ultimate fluid tank with the result of still nothing.

![mek_qe_output_ult_tank](https://user-images.githubusercontent.com/5643061/60605502-e24e6100-9d76-11e9-8cd3-8dc6eaa304a6.PNG)

I have also turned eject on in the output QE with also no effect.

![mek_qe_output_eject_on](https://user-images.githubusercontent.com/5643061/60605692-36f1dc00-9d77-11e9-9e36-05388f8a7efe.PNG)

And as a final verification, I used the network reader on both the top and bottom branches (this is with eject on).

![mek_qe_output_network_reader_top_branch](https://user-images.githubusercontent.com/5643061/60605971-b54e7e00-9d77-11e9-8a58-578fd943cca0.PNG)
![mek_qe_output_network_reader_bottom_branch](https://user-images.githubusercontent.com/5643061/60605977-b7b0d800-9d77-11e9-9a14-cfeda9a42d5a.PNG)

And with eject off.

![mek_qe_output_network_reader_top_branch_eject_off](https://user-images.githubusercontent.com/5643061/60606005-c5fef400-9d77-11e9-86b4-0be7d068f281.PNG)
![mek_qe_output_network_reader_bottom_branch_eject_off](https://user-images.githubusercontent.com/5643061/60606009-c8614e00-9d77-11e9-99b5-e5f388ce4b6c.PNG)

**Comment by pupnewfster** [comment]
Turns out that some things weren't fully implemented correctly (probably from when we were adding more null safety), so I went through and fixed it for the quantum entangloporter and all the other fluid handlers we have that were broken (some worked some did not). So once 9.7.9 gets released at some point this should be fixed.

**Comment by rux616** [comment]
Thanks for the prompt fix. Here's hoping 9.7.9 gets released soon. (Kinda hard to build a QE-powered chemical plant with only 256mb/t throughput!)

**Comment by thiakil** [comment]
@rux616 in the meantime, does it succeed with pulling when the pipe already has water in it?

**Comment by thiakil** [comment]
Merged for next release

**Comment by rux616** [comment]
> 
> 
> @rux616 in the meantime, does it succeed with pulling when the pipe already has water in it?

No, I just tried attaching a basic mechanical pipe set to pull from a creative tank full of water and linked it with the receiving end of the QE chain, and the tank I had there was only filling at 100mb/t as would happen with a basic.

**Comment by pupnewfster** [comment]
That is on 9.7.8 right? Given 9.7.9 has been released since which *should* fix pulling from it.

**Comment by rux616** [comment]
Oh whoops, I didn't see that. However, it looks like it's not pulling as fast as it should be with ultimate mechanical pipes. I'll open a new issue about that.
