### ISSUE TITLE
Limited fluid throughput for quantum entangloporter

### ISSUE THREAD

**Issue by rux616** [mekanism/Mekanism#5558]
#### Issue description:
When transporting fluids through a quantum entangloporter, throughput is limited to 3200mB/t max.

#### Steps to reproduce:
1. Place creative tank
2. Fill creative tank with water
3. Attach ultimate mechanical pipes to all faces
4. Set all ultimate pipes to 'pull'
5. Place QE
6. Give it a proper channel and set all sides for fluid input
7. Place second QE some distance from the first
8. Give second QE the same channel and set all sides for fluid output
9. Attach ultimate mechanical pipes to all faces
10. Set all ultimate pipes to 'pull'
11. Have pipes go into a fluid trashcan or something
12. Note that the transfer rate should go up by 6400mB/t for each ultimate mechanical pipe attached to the different faces, resulting in an aggregate max transfer rate of 38400mB/t
13. If you right click the pipes with a network reader, you will notice that 'throughput' is listed at 3200mB/t
14. This can also be reproduced when using elite mechanical pipes as 6x of them totals more than 3200mB/t

Pictures:
Control showing that 6 ultimate mechanical pipes connecting a water-holding creative tank and a fluid trashcan from Extra Utilities 2 has a throughput of 38400mB/t:
![control](https://user-images.githubusercontent.com/5643061/60786145-9f8fde80-a112-11e9-8f18-a76921dd20b0.png)

Overall setup
![set_up](https://user-images.githubusercontent.com/5643061/60786150-a3bbfc00-a112-11e9-9670-293f8918f029.png)

Input side
![input_side](https://user-images.githubusercontent.com/5643061/60786158-adddfa80-a112-11e9-92b9-4a88beb38ca1.png)

Input side throughput
![input_side_throughput](https://user-images.githubusercontent.com/5643061/60786161-b1718180-a112-11e9-83e9-10e6874cc23d.png)

Output side
![output_side](https://user-images.githubusercontent.com/5643061/60786171-b59d9f00-a112-11e9-8747-e5b6cd6aabef.png)

Output side throughput
![output_side_throughput](https://user-images.githubusercontent.com/5643061/60786175-b8988f80-a112-11e9-9e55-6905910e3c3a.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 9.7.9.380

**Extra Utilities:** 1.9.9
**Hwyla:** 1.8.26-B41
**Just Enough Items (JEI):** 4.15.0.268
**Mekanism Generators:** 9.7.9.380
**Waila Harvestability:** 1.1.12
**Wawla - What Are We Looking At:** 2.5.273

#### If a (crash)log is relevant for this issue, link it here: _n/a_

**Comment by thiakil** [comment]
If that test world only contains that setup, any chance you could zip it up and post here for us?

**Comment by rux616** [comment]
Sure thing, let me do that right now.

**Comment by rux616** [comment]
Here it is: [mek-test-2.zip](https://github.com/mekanism/Mekanism/files/3367089/mek-test-2.zip)

**Comment by thiakil** [comment]
It appears the buffer of the Entangloporter is only `3200` by default, as it uses the `UltimateFluidTankOutput` setting.

I'm giving it its own setting which defaults to the ultimate tank's capacity

**Comment by rux616** [comment]
You guys are crazy responsive, thanks so much!

**Comment by thiakil** [comment]
This one was relatively easy, and having the test setup provided is also super helpful 👍

**Comment by pupnewfster** [comment]
Version [9.8.0](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2746197) was just released and should sync to the twitch client within the next couple hours.
