### ISSUE TITLE
Formulaic Assemblicator Bucket Duplication

### ISSUE THREAD

**Issue by Ryxcode** [mekanism/Mekanism#5559]
#### Issue description:
There is a bug with the Formulaic Assemblicator : All filled bucket in a craft are duplicated

#### Steps to reproduce:
1. Make the Crusher craft in the Formulaic Assemblicator
2. Put the Auto-Craft Mode
3. Place all needed items
4. See in the result : 4 empty bucket but you have placed 2 :/

#### Version (make sure you are on the latest version before reporting):
**Forge:1.12.2-14.23.5.2838** 
**Mekanism:1.12.2-9.7.9.380** 

Video Links : 
https://www.youtube.com/watch?v=Zf5xDJTo4wQ&feature=youtu.be
https://www.youtube.com/watch?v=_A4K3aZTTHI&feature=youtu.be

**Comment by pupnewfster** [comment]
Version [9.8.0](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2746197) was just released and should sync to the twitch client within the next couple hours.
