### ISSUE TITLE
Mekanism causing crash because of sound handler

### ISSUE THREAD

**Issue by Moistnugger** [mekanism/Mekanism#5560]
o guys.. I've been expierencing random crashes and it tells me that the cause is "Mekanism" and "Random things" anyone know what I could do?
https://paste.dimdev.org/heqasinoni.mccrash

err one "workaround/fix" would be in the config for the client section turn enablePlayerSounds to false and I believe that will stop it (as that should stop the sound events that are crashing from ever being fired). From the looks of it, my guess is that sometimes somehow the player it is trying to play the sounds for is null (might happen if a mob has a jetpack unsure, also unsure how the mob would get the jetpack)

**Comment by SnaveSutit** [comment]
I've been having a similar issue, but conflicting with Immersive Vehicles (MTS). I've been unable to obtain a crash report as it completely freezes my game to the point where task manager has to get involved. I'm going to look though the logs tonight to see if I can find anything that might point towards the exact cause

**Comment by pupnewfster** [comment]
Not sure as this issue only has to do with the player sounds:
- Jetpack
- Gas Mask
- Flamethrower (doesn't work at all so isn't even a possible cause of the problem)

Later today there will be a release of 9.8.0 which will fix this (as well as the flamethrower). So I recommend also trying it against this version when you experiment later.

**Comment by pupnewfster** [comment]
Speaking of which version [9.8.0](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2746197) was just released and should sync to the twitch client within the next couple hours.
