### ISSUE TITLE
I do not see the jetpack on my back.

### ISSUE THREAD

**Issue by imReq** [mekanism/Mekanism#5562]
I do not see the jetpack on my back.
**Forge:** 1.12.2 - 14.23.5.2838
**Mekanism:** 1.12.2-9.7.9.380
![image](https://user-images.githubusercontent.com/36240924/61069262-2c38e600-a40c-11e9-8017-783906dec36e.png)

**Comment by pupnewfster** [comment]
Could you provide us with a mod list, as it is likely that something else is causing the jetpack to not render.

**Comment by imReq** [comment]
all my mods:
![image](https://user-images.githubusercontent.com/36240924/61080663-da04be80-a425-11e9-8b35-f10ea3808db8.png)
![image](https://user-images.githubusercontent.com/36240924/61080736-03bde580-a426-11e9-9553-66ecb7a4bbd0.png)
![image](https://user-images.githubusercontent.com/36240924/61080767-11736b00-a426-11e9-8713-1199db49e6bb.png)

**Comment by imReq** [comment]
The reason for this was the Mo-Bends mod
