### ISSUE TITLE
Oxygen tanks not filling

### ISSUE THREAD

**Issue by Rulenine** [mekanism/Mekanism#5564]
Hi all,

I am having issues with losing all my oxygen. Here is what is happening:

I have an electrolytic separator generating hydrogen and oxygen, with elite pressurized tubes running to 3 gas tanks for each gas. The hydrogen then goes from the 3 hydrogen tanks to a chemical infuser. This creates a gas buffer. Everything works fine here.

The problem is with the oxygen tanks. I have tubes leading to 3 oxygen tanks and then tubes leading to an elite purifying factory. But even when the factory is NOT running, and is completely full of oxygen, the tanks won't fill up. I've set everything up the same way I did my hydrogen and chlorine, and it just won't work. Pipes lead directly to chamber, only output side enabled on the tank is the one with the tubes, and auto eject is on. If I turn auto eject off and fill up my oxygen tanks, then turn it back on, I lose all the oxygen in seconds. Even when the purifying chamber factory is NOT running.

Can anyone help me with this? Everything works from the electrolytic separator up through to the gas tanks (they will fill, separator runs fine, etc) but the moment I try to connect anything up to the gas tanks it never works. I've left it for hours on end with nothing running and still never get a buffer built up. I get the tanks flashing from showing "gas: oxygen" to "gas: none" so obviously its getting dumped somewhere.

Please help!

My MC version is 1.7.10, mekanism 9.1.1

**Comment by pupnewfster** [comment]
Closing this because if memory serves you also joined the discord when you opened it and it turned out to be you were attempting to use hydrogen instead of oxygen by accident. If this wasn't the case feel free to reopen it and we can try to help you trouble shoot, but given we are not releasing updates for the 1.7.10 version anymore if there is an actual bug it unfortunately is unlikely to receive a fix that you can download.

**Comment by Rulenine** [comment]
Hi there,

This was not me in the discord. I definitely do not have them mixed up as I have two separate locations for both hydrogen and oxygen, with tubes headed to each section. I realize this is an older version with no updates, but if anyone has an idea of what causes the glitch I can try to manage.

So far, it appears rendering in affects it. So once I disable eject and fill, I can enable and use normally provided I do not render away. If I log back on 2 hours later, it will be back to an infinite cycle of emptying even when not operational. At least I can reset this, but it still prohibits me from making my systems further automated.

**Comment by pupnewfster** [comment]
Out of curiosity are any of the pipes going across chunks? I didn't work on Mekanism in 1.7.10 but I would not be fully surprised if https://github.com/mekanism/Mekanism/issues/4676 was also an issue then. (If so one thing you *could* try is having gas tanks at the borders of the chunks to pass it on between the sections, no idea if that would even work as a workaround or not, or if you have something like extra cells you *could* theoretically transfer the gas using that.
