### ISSUE TITLE
Mekanism Steel Kompatibilität

### ISSUE THREAD

**Issue by ZeroReaktionLP** [mekanism/Mekanism#5570]
please make possible in melter of mekanism also let steel dust melt to steel bars

**Comment by pupnewfster** [comment]
Not even sure what you are asking here as you deleted the majority of the format. Especially since steel dust can be smelted into steel ingots. You can also use the CraftTweaker integration to add custom recipes if you wish.

**Comment by ZeroReaktionLP** [comment]
i am concerned about that if others e.g. just install the mod and otherwise no other and do not know in it so well that the steel can still with electricity without putting it in the coal oven or so
