### ISSUE TITLE
No config for stats of atomic destabilize

### ISSUE THREAD

**Issue by LordApplesause** [mekanism/Mekanism#5571]
Hello!

I would like a more detailed config option of the atomic destabilizer.

Ex:
- Damage Per Hit
- Enable/Disable modes
- Edit mode stats 

and possibly more that im not thinking of. Thank you!

**Comment by pupnewfster** [comment]
Version [9.8.0](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2746197) was just released and should sync to the twitch client within the next couple hours.
