### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by user38898892** [mekanism/Mekanism#5572]
#### Issue description:
maybe incompatible with some xnet stuffs ?

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2838-universal
**Mekanism:** Mekanism-1.12.2-9.7.4.375
**Other relevant version:** xnet-1.12-1.8.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://paste.ubuntu.com/p/rQFc4ZgJhz/
[gist/pastebin/etc link here]

**Comment by user38898892** [comment]
https://github.com/McJtyMods/XNet/issues/357

**Comment by thiakil** [comment]
Something is likely wrong with your save data - your server thinks the Block is a Mekanism one, but the TileEntity is not.
