### ISSUE TITLE
Mekanism Turbine Valve Crash

### ISSUE THREAD

**Issue by KuroBunny** [mekanism/Mekanism#5574]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Server keeps crashing after I placed a Turbine Valve, and I have confirmed it is because of the Turbine Valve. -- Others have said to upgrade to latest version, 9.2.4.103 is the latest version for Forge version 1.10.2.

#### Steps to reproduce:
1. Place a Turbine Valve.
2. --
3. -- 

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.10.2** 
**Mekanism: 9.2.4.103** 
**Other relevant version: what**

**Comment by thiakil** [comment]
We don't really support < 1.12 at the moment. Also a crashlog would help, like the template asks you for.
