### ISSUE TITLE
Render Bug For New Version (Mekanism-1.12.2-9.8.0.381)

### ISSUE THREAD

**Issue by LordApplesause** [mekanism/Mekanism#5579]
Whenever you move your cursor, it will turn into a static color, you cannot exit to menu nor interact with the world until you get back to your original curser point when logged in. This was right after I installed the new versions for mekanism, mekanism generators and mekanism tools 

- Confirmed not Codechickenlib
- Confirmed Not Sponge
- Confirmed not multiplayer-only (the same issue in singleplayer)

below is the twitch modpack as well as the world: 
https://mega.nz/#!mbRRTCSJ!7f4tIp1tAXZWTxEutZxi_j_pb2oMaQ7V1v6xUsbIhnA
and, the logs are here as well :) 
[2019-07-23-7.log.gz](https://github.com/mekanism/Mekanism/files/3424830/2019-07-23-7.log.gz)
and... the video of the example 
[Minecraft 1.12.2 2019-07-23 21-46-52.zip](https://github.com/mekanism/Mekanism/files/3424836/Minecraft.1.12.2.2019-07-23.21-46-52.zip)

**Comment by pupnewfster** [comment]
Will look into this more tomorrow, but removing buildcraft seems to fix this issue.

**Comment by pupnewfster** [comment]
Still need to try and track down why it is happening and which end it is on, but in BetterFPS changing Fog from `Fast` to `Fancy` seems to make it work properly.

**Comment by pupnewfster** [comment]
I think this may have to do with us "enabling fog" on this line https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/client/render/RenderResizableCuboid.java#L179 (this gets called by the dynamic tank rendering). I am not quite sure what is the *point* of our call to enabling fog there, so I will talk with @thiakil and see if he knows why the method enables fog.

**Comment by pupnewfster** [comment]
Fix included in [9.8.1](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2755008)
