### ISSUE TITLE
Agricraft TileEntityCrop / Heat Vent Issue

### ISSUE THREAD

**Issue by Yann151924** [mekanism/Mekanism#5580]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Don't know when it happen but i think it's when a monster want to spawn on a vent but agricraft have only villager if i remember quite well

#### Steps to reproduce:
1.Don't know the step

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 1.12.2-9.7.9.380
**Other relevant version:** SpongeForge 1.12.2-2825-7.1.6

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/pNrHt5AW

The error is trigger by this line of your code : https://github.com/mekanism/Mekanism/blob/master/src/main/java/mekanism/generators/common/block/BlockGenerator.java#L552

**Comment by thiakil** [comment]
Same as #5572

Likely a Sponge bug

**Comment by Yann151924** [comment]
It's the same as #5572 but i don't think it's related to the save, my team and me investigate on our server and the bug happens when the server try to spawn an entities on the block. To make sure of this we change the biome directly on the chunk (to mushroom) and the crash not appear anymore. We did the same test with completly deactivate the spawn of the mob and the crash not appear too.

Could be a sponge problem but i don't think it is because on the line i mention you cast whatever tileentities to your type. So i think the problem come from the cast like the crash report say and it's not a sponge problem.

**Comment by thiakil** [comment]
Happening once (i.e the other issue), probably a save file issue (not enough info to blame on mods).

Happening twice is enough for me to blame it on sponge. That method is retrieving the TileEntity for _the position its being told its in_. If that doesn't match, that is not on us. Please don't try to explain how things work when you don't know the full picture.

That method has been there for quite some time now, and only now are there suddenly problems.
