### ISSUE TITLE
Digital Miner

### ISSUE THREAD

**Issue by Shadowninja397** [mekanism/Mekanism#5588]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Power Digital miner through Quantum Entagloporter
2. set to max radius and one block under where the surface level is in area
3. chunkload through FTB utilities and anchor upgrade on teleporter nearby

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** v9
**Other relevant version:** latest update

playing on a server we use mekanism. whenever you set up the miner it can say anywhere above 2000 and it won't mine it all after a while ores stop coming through the Entagloporter network and you check on the miner and it says its mined all 10,000 in the most recent case. when you reset and restart it most of the ores will still be there and will have to keep doing this for about 20-30 times before it finally finishes.

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by Shadowninja397** [comment]
after doing more testing it seems to reset sometimes when you travel through the teleporter

**Comment by thiakil** [comment]
You likely aren't chunkloading the necessary area.

Put the anchor upgrade in the _miner_ and you should be right
