### ISSUE TITLE
Nether portals can be broken by hand

### ISSUE THREAD

**Issue by Bomb787** [mekanism/Mekanism#5590]
I'm using the latest update for 1.12.2 and it seems that nether portals can be broken by hand in survival mode and have the stone breaking sound instead of the glass sound you normally get if your break it in creative. Portals also don't give off light anymore.

**Comment by pupnewfster** [comment]
Fix included in [9.8.1](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2755008)
