### ISSUE TITLE
Security desk bypassing the global disable on security

### ISSUE THREAD

**Issue by LemADEC** [mekanism/Mekanism#5591]
#### Issue description:
When disabling protection in the configuration, security desk can still be used to actually set protection on blocks.
Either disable completely or update the comment to clarify what that configuration option do.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 1.12.2-9.8.0.381
**Other relevant version:** n/a

**Comment by pupnewfster** [comment]
Unable to reproduce in 1.15
