### ISSUE TITLE
[Bug report] Mekanism Dumping and Dumping excess ui has been switched around

### ISSUE THREAD

**Issue by BackRowB** [mekanism/Mekanism#5594]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism machines have the wrong ui atacked to Dumping and Dump excess. If Dump excess is selected the machine will dump all, when Dumping is selected the machine with Dump excess.

#### Steps to reproduce:
1. Right click on a mekanism machine such as the Electrolytic Separator
2. Add water (if Electrolytic separator) and energy
3. Play with the Dump options to confirm that this is a problem on other devices

#### Version (make sure you are on the latest version before reporting):
**Mekanism:** 1.12.2-9.8.0.381.jar
**Other relevant version:** All The Mods Remix Version: 1.4.9

[gist/pastebin/etc link here]
Picture of UI posted to reddit :https://www.reddit.com/r/allthemods/comments/ck7e5f/bug_report_mekanism_dumping_and_dumping_excess_ui/

**Comment by pupnewfster** [comment]
Fix included in [9.8.1](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2755008)
