### ISSUE TITLE
[1.12.2] Incompatibility with VanillaFix

### ISSUE THREAD

**Issue by ChlorineX** [mekanism/Mekanism#5595]
#### Issue description:
With VanillaFix installed, rendering would fail (as the picture shows, the whole view becomes blue and I can't see anything) if there is an energy cube existing in my sight. If turn around so that I can't see the energy cube, the rendering would become normal again. 
<img width="1280" alt="Screen Shot 2019-08-01 at 7 12 05 PM" src="https://user-images.githubusercontent.com/34786330/62289789-3ccfff80-b492-11e9-9a10-ba83b9460269.png">

#### Steps to reproduce:
1. Install Mekanism and VanillaFix
2. Place any energy cube

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2838
**Mekanism: 9.8.0.381
**VanillaFix version: 1.0.10-99

No crash report, and nothing valuable is found in the log.

**Comment by thiakil** [comment]
Have you reported to Vanilla Fix? There's not a lot we can do as we don't know what changes they make

**Comment by ChlorineX** [comment]
VanillaFix is currently inactive.

**Comment by ChlorineX** [comment]
> Have you reported to Vanilla Fix? There's not a lot we can do as we don't know what changes they make

But however, 9.7.9.380 works fine, the incompatibility just exist in 9.8.0.381.

**Comment by thiakil** [comment]
In 9.8.0 we removed a whole bunch of direct opengl calls in favour of the normal minecraft state tracker. Something that perhaps VF makes changes to

**Comment by ChlorineX** [comment]
Could you add a option to switch back to gl11? VanillaFix is quite popular and it truly boosts fps a lot.

**Comment by ChlorineX** [comment]
The incompatibility probably occurs here. 
[](https://github.com/DimensionalDevelopment/VanillaFix/blob/master/src/main/java/org/dimdev/utils/GlUtil.java)

**Comment by thiakil** [comment]
No, there's no going back to raw gl

**Comment by pupnewfster** [comment]
I think this is similar to https://github.com/mekanism/Mekanism/issues/5579 so it *may* be fixed in 9.8.1

**Comment by pupnewfster** [comment]
I was going to test to see if it is fixed with the changes coming in 9.8.1, but I am unable to reproduce it with just vanilla fix and 9.8.0. Do you have any other rendering mods installed/is it the default VanillaFix config?

**Comment by HydrogenC** [comment]
I have Phosphor, BetterFPS, VanillaFix, Optifine and FoamFix installed. It's indeed the same as what #5579 describes.

**Comment by pupnewfster** [comment]
Check your BetterFPS settings as #5579 happens when BetterFPS has fog set to "fast". (Optifine has a similar option if I remember but I don't know if it behave the same).

**Comment by ChlorineX** [comment]
I enabled fog in Optifine and it fixes! It's indeed a fog-related problem.

**Comment by pupnewfster** [comment]
My guess is that this will be fixed in 9.8.1 then.

**Comment by ChlorineX** [comment]
Thanks a lot!

**Comment by pupnewfster** [comment]
[9.8.1](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2755008) has been released, if this does not fix the issue please let us know.
