### ISSUE TITLE
Ossmium Compressor ratio.

### ISSUE THREAD

**Issue by neoprofin** [mekanism/Mekanism#5596]
All Mekanism machines are based on a 1:8 ratio except the Osmium Compressor which is based on a a 1:8000000000001 ratio which means that every single time you use the machine it ends at 99.99% and jammed up. I have have played with this mod for near a decade (and I love it, I think Aiden made a mod for people who just love to have fun) but this specific issue is not new. I don't even care, I only need a few ingots for high level tech, but it just seems stupid to break your own mechanics and not have machines work correctly. Minecraft has infinite ore, if you decide to make anything more arbitrarily shitty...

Bro, why?

**Comment by pupnewfster** [comment]
I don't remember exactly how this worked in the old system (though I do remember the issue you are talking about). I just tested this in 1.15, and had to make a small fix to if the exact amount was supplied it not working properly, but in the next alpha of Mekanism this should be properly fixed.

**Comment by neoprofin** [comment]
Awesome! I think Mekanism coming on the scene is as big a game changer as
the TE and IC mods. I love it, just trying to make it work as intended.

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.

**Comment by fw4hre0xxq** [comment]
Is there a plan to backport this to MC 1.12.2 or not really? Thanks for your time and the great mod!

**Comment by pupnewfster** [comment]
No 1.12 is no longer receiving development, also the main reason it was as easy as it was to fix in 1.15 was due to how we rewrote our entire recipe system in 1.15.
