### ISSUE TITLE
Game crashes when clicking "New Filter" on the Oredictionificator

### ISSUE THREAD

**Issue by thakyZ** [mekanism/Mekanism#5597]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The game seems to crash when opening the oredictotionificator and choosing the option "New Filter"

#### Steps to reproduce:
1. Place Oredictionificator down
2. Open the block's menu
3. Click "New Filter"
4. Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 9.8.0.381
**Other relevant version:** Bundled Java

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/thakyZ/779a24d1cec7143f33750a4509ef5fd1

**Comment by pupnewfster** [comment]
Fix included in [9.8.1](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2755008)
