### ISSUE TITLE
Purification chamber makes no sound.

### ISSUE THREAD

**Issue by SiliconEnt** [mekanism/Mekanism#5599]
#### Issue description:
The purification chamber doesn't make any sound when running. I presume this is not intended, as its factory equivalents are not affected and play purificationchamber.ogg.

#### Steps to reproduce:
1. Place a purification chamber. Only the base machine is affected; purification factories are not affected by this issue.
2. Feed it energy, oxygen, and any valid recipe input.
3. Make sure it is running and producing output.
4. Purification chamber is dead silent.

#### Version (make sure you are on the latest version before reporting):
Minecraft 1.12.2
Forge 14.23.5.2838
Mekanism 9.8.1.383
MekanismGenerators 9.8.1.383

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

latest.log: https://gist.github.com/SiliconEnt/7de5551d62109652b6beb47a6ec59dd9
debug.log: https://gist.github.com/SiliconEnt/e7f9297fa6c7c17a84f7fbe4bbeac16c

**Comment by pupnewfster** [comment]
Should be fixed in the latest release [9.8.2](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2794015)
