### ISSUE TITLE
Precision Sawmill does not accept torches via input 

### ISSUE THREAD

**Issue by Vapervop** [mekanism/Mekanism#5601]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The Precision Sawmill does not accept torches as input. It works manually but not automatically. 

#### Steps to reproduce:
1.Take a Precision Sawmill 
2.Put a hopper in the input side
3.Put the torches in the hopper and watch the issue 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
14.23.5.2838
**Mekanism:** 
1.12.2-9.8.1.383
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by The--Captain** [comment]
This had already been marked to be fixed in the next version (I already reported it, and traced the flaw in the code)

In the meanwhile, use the Electric Sorting Machine from IC2 to get your torches into the Precision Sawmill and build your infinite diamond factory.

**Comment by pupnewfster** [comment]
I am pretty sure this has been fixed already and this issue just had been forgotten to be closed, but either way with the new recipe system in 1.15 this is no longer and issue and I tested and it works properly.
