### ISSUE TITLE
Obsidian Paxel can't break Thermal Machines, Hoppers, Livingwood

### ISSUE THREAD

**Issue by PanSzelescik** [mekanism/Mekanism#5604]
#### Issue description:
![image](https://user-images.githubusercontent.com/26679785/62651304-f29ac280-b958-11e9-9bbf-f939e5961eb7.png)
Can't break machine from Thermal and Hoppers

#### Steps to reproduce:
1. Make Obsidian Paxel
2. Try break Thermal Machine, Hopper or Livingwood (Botania)
In 9.8.0.381 I could destroy them normally

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2838
**Mekanism:** 9.8.1.383

**Comment by pupnewfster** [comment]
Should be fixed in the latest release [9.8.2](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools/files/2794018)
