### ISSUE TITLE
Trouble with the Walkie Talkie

### ISSUE THREAD

**Issue by simobambino401** [mekanism/Mekanism#5605]
I am having trouble with the walkie talkie. I have the Voice server enabled and such on my server (a server that i rent a host for) and i have my walkie talkie on and such and on the same channel. However the voice part doesn't actually work. No one can hear anyone. We have another voice mod that works just fine so I am not sure what the issue could be. Do walkie Talkies require something in game?

Meaknism Ver: 9.8.0.381

(Also using Merkanism Tools and Generators)

**Comment by aidancbrady** [comment]
#4992
