### ISSUE TITLE
Paxels don't act like any tools in multiplayer

### ISSUE THREAD

**Issue by Alphakip** [mekanism/Mekanism#5606]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

In multiplayer, Paxels do not function as any tool.

#### Steps to reproduce:
1. Start a multiplayer server (any will do)
2. Use a Paxel
3. 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2815
**Mekanism:** MekanismTools-1.12.2-9.8.1.383
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: n/a

**Comment by pupnewfster** [comment]
Should be fixed in the latest release [9.8.2](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools/files/2794018)
