### ISSUE TITLE
Mekanism Generators/Tools not mentioned in main CurseForge page

### ISSUE THREAD

**Issue by thecodewarrior** [mekanism/Mekanism#5607]
The fact that Mekanism Generators and Mekanism Tools are entirely separate mods is not made clear on the main Mekanism CurseForge page, which may be confusing to players who download the mod themselves and find that it is missing all the power generation blocks (it certainly was for me and my brother). I think it would be helpful to people downloading Mekanism if you provided links to the tools and generators mods on the main mod's CurseForge page.

**Comment by pupnewfster** [comment]
Mekanism and all the submodules now have updated descriptions including links to the other pages.
