### ISSUE TITLE
Configurator is not working

### ISSUE THREAD

**Issue by Solverbolt** [mekanism/Mekanism#5608]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Configurator is not actually allowing for anything to be configured, it only is selecting redstone sensitivity settings, which are doing nothing to interact with any object with mekanism. 

#### Steps to reproduce:
1. Built Configurator
2. Left click and Right click any mekanism object
3. Changes settings of redstone sensitivity off and on. thats all it does

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.23.5.2836
**Mekanism:**1.12.2-9.7.2.373.jar
**Other relevant version:** modpack "A bit of Everything"

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]
![image](https://user-images.githubusercontent.com/38087746/62744753-e23c2380-b9fc-11e9-8881-dae295d78465.png)

**Comment by thiakil** [comment]
Are you sure you're using it correctly? https://wiki.aidancbrady.com/wiki/Configurator

**Comment by aidancbrady** [comment]
You can 'configure' sides of transmitters, what you're showing is intended functionality.
