### ISSUE TITLE
Induction cell values when displayed in RF is wrong

### ISSUE THREAD

**Issue by Pipaul620** [mekanism/Mekanism#5609]
Hello guys !

When I set the energy in "RF", the induction cell capacity display is wrong :
Basic one is 400 MRF, ok.
Advanced one is 2.14GRF, ok.
But the elite and ultimate one are still at 2.14GRF so that's a big problem, when i put those in induction matrix (elite or ultimate ones), the green charging bar does not display (if we consider that the maximum capacity is 2.14GRF), and the displayed maximum energy is 2.14GRF, even if i have 4 ultimate induction cell.

When i set the energy in "Joules", all is OK, it works well.
That's very disapointing :/

Tell me if you want some screenshot

**Comment by pupnewfster** [comment]
My guess is that when I was cleaning up how we convert the numbers, that I made the RF display stop it at MAX_INT by accident.

**Comment by Pipaul620** [comment]
it must be a thing like that (it's not a big deal since it works well and no energy is loss)

**Comment by pupnewfster** [comment]
Should be fixed in the latest release [9.8.2](https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2794015)
