### ISSUE TITLE
Evaporation plant causes render bug

### ISSUE THREAD

**Issue by FractalNumbers** [mekanism/Mekanism#5610]
#### Issue description:
When the evaporation plant is constructed and liquid (water) is inserted, the screen goes blank and takes on the current color of the sky. When Optifine is installed, only the UI goes blank and takes on said color.

#### Steps to reproduce:
1. Construct an evaporation plant.
2. Insert a liquid. In my case it's water, I haven't tested brine.

#### Version
**Forge:** 1.12.2-14.23.5.2838
**Mekanism:** 9.8.0.381

I can provide a mod list if it would help.

**Comment by pupnewfster** [comment]
I believe this is the same as as #5579 which should be fixed by either enabling fog in optifine or updating mekanism to 9.8.1.
