### ISSUE TITLE
Server/Client is crashing when finishing the turbine

### ISSUE THREAD

**Issue by snaex95** [mekanism/Mekanism#5611]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

[crash-2019-08-11_15.01.20-server.txt](https://github.com/mekanism/Mekanism/files/3490006/crash-2019-08-11_15.01.20-server.txt)

#### Steps to reproduce:
1.Build turbine
2.crahes when last block is placed (with valve) and red mist appears [NO CRASH WITHOUT VALVE]
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** Forge 14.23.5.2838
**Mekanism:** Mekanism-1.12.2-9.7.5.376.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment]
Update Mekanism
