### ISSUE TITLE
Mod Id digital miner  Busted

### ISSUE THREAD

**Issue by tyler489** [mekanism/Mekanism#5612]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Attempting to use mod id on the digital miner will always return 0 blocks
Tested with enderio Minecraft twilightforest and nuclearcraft mod ids in the skyfactory 4 modpack

#### Steps to reproduce:
1. Make and place digital miner
2. Mod id anything
3. Click start 0 blocks found

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5 2838
**Mekanism:** 1.12.2-9.7.5.376

**Comment by thiakil** [comment]
Can you please show your configuration settings for the Miner's filter(s)?

**Comment by tyler489** [comment]
just went into my test world and now its working correctly with Minecraft Enderio and NuclearCraft
