### ISSUE TITLE
Tech Reborn Machines dosen't accept Mekanism EnergyCables/Energy Cubes

### ISSUE THREAD

**Issue by Freebi85** [mekanism/Mekanism#5613]
#### Issue description:
Hello =)
Since latest Mekanism update it's not possible to charge Tech Reborn machines via Mekanism Cables. It's still possible when using for example an Energy Cube and cables from other mods.

#### Steps to reproduce:
1. Put an Energy Cube or any source of RF/FE via mekanism cables next to any tech reborn machine

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2836
**Mekanism:** 9.8.1.383
**Tech Reborn:** 1.12.2-2.24.1.1017
**Reborn Core:** 1.12.2-3.15.5.467

**Comment by pupnewfster** [comment]
Not sure what was going on here, but as tech reborn for 1.15 is for fabric not forge I am going ahead and closing it as there is no way that this can be reproduced in 1.15
