### ISSUE TITLE
NullPointerException after respawning

### ISSUE THREAD

**Issue by xJon** [mekanism/Mekanism#5614]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Client crashing, happened after dying and respawning in an environment with Mekanism blocks, but didn't continue to happen.

#### Steps to reproduce:
1. Have Mekanism blocks around
2. ???
3. Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:**  1.12.2-14.23.5.2838
**Mekanism:** 1.12.2-9.8.1.383

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://paste.dimdev.org/dulotozazi.mccrash

**Comment by thiakil** [comment]
Unfortunately that's crashing inside vanilla code, so there's not much we can do there directly.

It's a possible race condition to investigate anyway - but as far as Minecraft is telling us, the chunk is loaded (when it seems it's actually _being_ loaded)

**Comment by xJon** [comment]
Right, huh. If there's nothing that can be done feel free to close the issue.

**Comment by thiakil** [comment]
I have some ideas, it's OK. I'll throw some code at the problem at some point :)

**Comment by xJon** [comment]
Sure, thanks :)

**Comment by aidancbrady** [comment]
Should be fixed in 1.15.
