### ISSUE TITLE
Thermal Evaporation Plant Half Filled

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5615]
![2019-08-13_18 56 43](https://user-images.githubusercontent.com/41069911/62983261-bfdf4700-bdfc-11e9-9992-246329f850e9.png)

I am not sure what is going on here, It appears that the thermal evaporation plants are glitching and causing a visual glitch with the fluid inside.

running 9.8.0.381

**Comment by term2112** [comment]
Im wondering if this could also be connected to #5610 since I also have optifine installed.
![image](https://user-images.githubusercontent.com/41069911/63042346-cb338080-be97-11e9-9c79-aa93b9d11d3d.png)

**Comment by thiakil** [comment]
Could you please test without Optifine? Better to rule it out to start with

**Comment by term2112** [comment]
Tested without optifine, same issue
![2019-08-21_08 58 28](https://user-images.githubusercontent.com/41069911/63433907-0848c700-c3f2-11e9-85d4-ab570ef5cc30.png)

**Comment by term2112** [comment]
sorry for the late response, busy with school

**Comment by pupnewfster** [comment]
Turns out when I updated the rendering of the evaporation plant I accidentally broke the location calculation. AKA depending on what side of the plant the controller is it renders in a different spot, and it just so happens that the orientation my test evaporation plant was in, made it so that it rendered in the correct spot.

**Comment by term2112** [comment]
I have actually noticed another visual glitch with the power cubes too, it used to be that when they filled up, they became less and less transparent, the issue with this is that it just goes to fully visible when partly filled rather than being semi-transparent

**Comment by pupnewfster** [comment]
Thanks for that I didn't actually notice that was a thing before so I guess I accidentally removed it.

**Comment by pupnewfster** [comment]
Turns out I didn't close this by accident when we released 9.8.2 because I forgot to add it to the milestone, but this is fixed in the latest version of mekanism.
