### ISSUE TITLE
Mining ice with the Digital Miner without Silk Touch does not produce water

### ISSUE THREAD

**Issue by Markelius** [mekanism/Mekanism#5616]
**Issue description:**
Mining ice without silk touch is supposed to replace the ice block with water, this is vanilla behaviour. Mining ice using the Digital Miner however does not produce water, it simply breaks the ice.

**Steps to reproduce:**
Mine ice with a Digital Miner without using Silk Touch.

**Version**
Forge: 1.12.2- 14.23.5.2768
Mekanism: 1.12.2-9.4.13.349

**Comment by pupnewfster** [comment]
We will look into it when it gets the chance, though one question. Does it produce water if there is a block below the ice? Vanilla behavior iirc is to turn ice into water iff there is a block under the ice when it breaks (I don't happen to remember if it allows for turning ice into water if there is water underneath the ice or if it just gets replaced by water in that case due to infinite water sources.

**Comment by Markelius** [comment]
It doesn't ever produce water. Not even on ice blocks which will produce water when mined by hand.

**Comment by thiakil** [comment]
The digital miner mines via teleportation. It's not really the same as mining by hand...

IMO this is functioning how it should.

**Comment by Markelius** [comment]
I would agree with you but there are many instances of the digital miner behaving similarly to mining by hand. For instance, you can get saplings by mining leaves.

Being able to turn ice into water via the digital miner also allows for filling in areas with water in new and creative ways where the fluidic plenisher isn't the best option (irregular areas, creating waterfalls, etc.

All in all I'm aware this isn't a "bug" but I would appreciate if my suggested behaviour was implemented.

**Comment by thiakil** [comment]
But saplings makes sense (what do you think the leaves would be attached to?)

Water staying around after the block it would have come from has been teleported away seems illogical

**Comment by Markelius** [comment]
I agree on this for mining ice with silk touch, but mining ice without silk touch using the digital miner does not give anything, it just breaks the ice.
