### ISSUE TITLE
Visual bug with bunch of mekanism blocks

### ISSUE THREAD

**Issue by GuGuISH** [mekanism/Mekanism#5618]
When ever I look at mekanism blocks with the wrench or when I build a mekanism multiblock the screen turn light blue and wont turn to normal before I look away form the block or destroy the multiblock structure. I am playing the All The Mods 3 Remix. I have tried with a few other texture packs and vanilla texture pack but it doesnt seem to be the problem.

![before](https://user-images.githubusercontent.com/10479600/63197928-d0ecba00-c081-11e9-8dd6-ed2d35a5cb17.png)
before I form the multiblock structure

![after](https://user-images.githubusercontent.com/10479600/63197932-d2b67d80-c081-11e9-9d7c-1640e38dfa00.png)
right after

![before2](https://user-images.githubusercontent.com/10479600/63198051-33de5100-c082-11e9-993b-73dd634dfab7.png)
before I look at the energy cube

![after2](https://user-images.githubusercontent.com/10479600/63198057-35a81480-c082-11e9-9052-d515b9f2e233.png)
after

**Comment by pupnewfster** [comment]
Not 100% sure what version of mekanism is being used given you didn't specify it... but I believe this is #5579 which was fixed in mekanism 9.8.1. So either update to that or enable fog in better fps/optifine/whatever rendering mod you have it set to fast/disabled for.

**Comment by GuGuISH** [comment]
Oh yeah totally forgot to add the version. But youre right its 9.8.0, I'm going to update it.
Thanks a lot.
