### ISSUE TITLE
electromagnetic coils

### ISSUE THREAD

**Issue by rexx890** [mekanism/Mekanism#5620]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### IAidan, 
     Hi my name is josh. I am trying to make the steam turbine and cannot get it to form. I have triple checked to make sure pressure dispersers and turbine vents are right but it just will not form. The only difference from the one I made is that the coils on top of the rotational complex won't connect like yours in the video. Help please! Thanks
 Btw I'm computer smart enough to download mods but not to familiar with code to find issues. Running minecraft 1.12.2 with mekanism 1.12.2-9.7.9.380 through twitch launcher.ssue description:

#### Steps to reproduce:
1.place coils on rotational complex
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
![coils mine](https://user-images.githubusercontent.com/54245500/63228156-215c3880-c1a4-11e9-962a-bf35f41079f8.jpg)
![coils his](https://user-images.githubusercontent.com/54245500/63228157-25885600-c1a4-11e9-8c4c-701d029e0575.jpg)

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Visually connecting relies on CTM being installed - https://www.curseforge.com/minecraft/mc-mods/ctm

Not enough information to diagnose any formation issues

**Comment by aidancbrady** [comment]
#5633
