### ISSUE TITLE
Mekanism tools: Osmium paxel

### ISSUE THREAD

**Issue by Robball14** [mekanism/Mekanism#5621]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The osmium paxel doesn't mine mekanism's ores (issues reported by my friend) 

#### Version:
**Forge: 1.12.2 14.23.5.2838
**Mekanism: 1.12.2-9.8.1.383
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by ToserBan** [comment]
I can confirm this new bug. All Paxels seem to not mine non standart blocks(dirt, stone,gravel,sand).
I tried to rise the value for the efficiency of one paxel in the config from 25 to 250, but this only affected the standart blocks like dirt, stone etc. The paxel still didnt mine any other block.
**Forge: 1.12.2 14.23.5.2838
**Mekanism: 1.12.2-9.8.1.383

**Comment by pupnewfster** [comment]
Should be fixed in the latest release [9.8.2](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools/files/2794018)
