### ISSUE TITLE
Server crashes when running an Elite Smelting Factory

### ISSUE THREAD

**Issue by frenzy167** [mekanism/Mekanism#5622]
[crash-2019-08-21_07.05.16-server.txt](https://github.com/mekanism/Mekanism/files/3525042/crash-2019-08-21_07.05.16-server.txt)

**Comment by pupnewfster** [comment]
Update mekanism, you are using version 9.7.0, and the latest is 9.8.1. Also in the future please do not delete the format, it is there to make us helping you easier.
