### ISSUE TITLE
Mekanism use receiveEnergy(1, true) instead of calling canReceive()

### ISSUE THREAD

**Issue by DBotThePony** [mekanism/Mekanism#5624]
#### Issue description:
https://github.com/mekanism/Mekanism/blob/bebcee022c47c70795df7b1e459c63ce7d606c45/src/main/java/mekanism/common/util/ChargeUtils.java#L181
https://github.com/mekanism/Mekanism/blob/bebcee022c47c70795df7b1e459c63ce7d606c45/src/main/java/mekanism/common/base/EnergyAcceptorWrapper.java#L115

This cause my GTCE <-> FE bridge to fail with Mekanism since machines (for balance) accept only certain minimal amount of FE at once, below that point they won't accept anything

**Comment by thiakil** [comment]
While unfortunate for your case, it is technically correct. Have a look at the reference implementation at `net.minecraftforge.energy.EnergyStorage#canReceive` - it only checks if it allows _any_ receiving.

I don't see a reason why we can't simulate `Integer.MAX_VALUE` though, which in theory should solve your implementation quirk

**Comment by aidancbrady** [comment]
Honestly I feel that there could be implementation quirks for any value we simulate. I'd rather leave our implementation as-is.
