### ISSUE TITLE
Question regarding Enrichment Chamber & Pure Certus Quartz Crystal

### ISSUE THREAD

**Issue by xJon** [mekanism/Mekanism#5626]
Is there a way to disable the Enrichment Chamber making Pure Certus Quartz Crystals?
Example: 
![Screenshot_5](https://user-images.githubusercontent.com/8945347/63638476-d8d4db80-c6cb-11e9-9255-6c60e40f449c.png)

**Mod versions:**
Mekanism: 1.12.2-9.8.1.383
AE2: rv6-stable-7

**Comment by thiakil** [comment]
Via settings, no. You should be able to do it with CraftTweaker though

**Comment by xJon** [comment]
Okay. Thank you!
