### ISSUE TITLE
Digital Miner Not Outputting Items

### ISSUE THREAD

**Issue by chris52695** [mekanism/Mekanism#5629]
Issue description: 
     I have tried to find an answer to this proble, but most seem to be old issues and currently irrelavent. I am currently having troulbe getting the Digital Miner to output to any form of inventory in the All The Mods 3 modpack. I have tried connecting all the chests i can think of as well as different forms of cables/conduits. The machine IS set to auto eject, but still nothing happens. The Digital Miner is my favorite form of Quarry system in modded Minecraft and I would hate to have to stray from it just because of a silly issue like this...

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 1.12.2-9.8.0.381.jar
All The Mods 3 Modpack From Twitch: Version - v5.12.2

**Comment by chris52695** [comment]
Update:
     Okay, so my issue seems to only be with the output at the top of the Digital Miner. I am able to get the back output of the miner to output, but just not the top output.

**Comment by pupnewfster** [comment]
The top is not an output port, it is an input port.

**Comment by thiakil** [comment]
I believe you can use active extraction from the top port?

But indeed auto eject only works with the back one
