### ISSUE TITLE
[1.12] Turbines refusing to form?

### ISSUE THREAD

**Issue by Paul17041993** [mekanism/Mekanism#5633]
Something appears to have changed, and turbines now outright refuse to form, even the simplest 5x5x5 or 5x8x5 setups...
![image](https://user-images.githubusercontent.com/3912867/64029866-c3a6f380-cb88-11e9-966a-09a0f6fcaa33.png)
![image](https://user-images.githubusercontent.com/3912867/64030019-18e30500-cb89-11e9-8fbf-1bb959b98495.png)

- coils in place above the rotational complex
- condensers around the complex
- outer frame made completely of turbine casing, along with top and bottom surfaces
- all other faces either structural glass or casing, no difference
- vent and valve presence has no effect
- no difference between sizes up to max, nor chunk location

- boiler structure completely unaffected, builds normally along side everything else
- filling air blocks with glass and removing has no effect, nor does leaving open space in the boiler prevent it from working

- thermal evap towers, while they form, will only show water/brine on the NW corner, which could be a correlated structure code issue?

**Forge:** 14.23.5, build 2838
**Mekanism:** 9.8.1, build 383

[modlist.txt](https://github.com/mekanism/Mekanism/files/3560414/modlist.txt)
(note that betterfps is disabled)

**Comment by term2112** [comment]
I have noticed something weird about this too, if you do manage to form one and break one of the blocks, it would say industrial turbine instead of turbine casing, same thing with valves

**Comment by doctor-something5000** [comment]
I too have the problem. It just won't form even when everything is right. I have looked upon many tutorials on it.

**Comment by ZMHING** [comment]
Me Too.

**Comment by crapStone** [comment]
The `Saturation Condensers` do not work, you need `Pressure Dispersers`.

**Comment by Laykota** [comment]
I'm having an issue with the 17x18x17 not forming. Made a 5x7x5 to test and it worked just fine but the max size refuses to form no matter how I build it.

**Comment by Karmacopper** [comment]
Might be related to this one, which at the time was brushed of as "that's how it's coded":

https://github.com/mekanism/Mekanism/issues/5039

**Comment by aidancbrady** [comment]
#5633

**Comment by aidancbrady** [comment]
Definitely broken. Will look into soon.

**Comment by Laykota** [comment]
Thank you

**Comment by aidancbrady** [comment]
Did some more testing, turns out I was making them wrong myself (forgetting the rotational complex lol). Using your same setups in the images I think this is actually fixed in 1.15. If there are still problems I'll be happy to re-open and look into again.
