### ISSUE TITLE
Have problem when installed Simple Ore Generation 

### ISSUE THREAD

**Issue by Hogor1** [mekanism/Mekanism#5635]
My minecraft crushes on phase 3 of lodaing mods beacuse of mekanism.

Logs:
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Simple Ore Generation (simpleoregen)
Caused by: java.lang.NoSuchMethodError: mekanism.common.config.MekanismConfig.local()Lmekanism/common/config/MekanismConfig;
	at com.gmail.rohzek.compatibility.MKCompat.fixConfig(MKCompat.java:25)
	at com.gmail.rohzek.compatibility.MKCompat.load(MKCompat.java:12)
	at com.gmail.rohzek.compatibility.CheckForMods.checkForMK(CheckForMods.java:94)
	at com.gmail.rohzek.main.Main.PostLoad(Main.java:188)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at crystallauncher.MinecraftConstructor.run(MinecraftConstructor.java:30)
	at crystallauncher.MineClient.start(MineClient.java:64)
	at crystallauncher.MineClient.main(MineClient.java:14)

A detailed walkthrough of the error:

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 588270648 bytes (561 MB) / 1577058304 bytes (1504 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072M -Xms1500M -Xss1M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2772 106 mods loaded, 106 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                   | Version                  | Source                                            | Signature                                |
	|:------ |:-------------------- |:------------------------ |:------------------------------------------------- |:---------------------------------------- |
	| UCHIJ  | minecraft            | 1.12.2                   | minecraft.jar                                     | None                                     |
	| UCHIJ  | mcp                  | 9.42                     | minecraft.jar                                     | None                                     |
	| UCHIJ  | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2772.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | forge                | 14.23.5.2772             | forge-1.12.2-14.23.5.2772.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ  | ivtoolkit            | 1.3.3-1.12               | minecraft.jar                                     | None                                     |
	| UCHIJ  | foamfixcore          | 7.7.4                    | minecraft.jar                                     | None                                     |
	| UCHIJ  | elucore              | 1.0                      | minecraft.jar                                     | None                                     |
	| UCHIJ  | movillages           | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                        | None                                     |
	| UCHIJ  | appliedenergistics2  | rv6-stable-3             | appliedenergistics2-rv6-stable-3.jar              | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| UCHIJ  | bdlib                | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                      | None                                     |
	| UCHIJ  | ae2stuff             | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                     | None                                     |
	| UCHIJ  | aroma1997core        | 2.0.0.0                  | Aroma1997Core-1.12.2-2.0.0.0.jar                  | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJ  | aroma1997sdimension  | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar | None                                     |
	| UCHIJ  | aromabackup          | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                    | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJ  | aromabackuprecovery  | 2.1.1.4                  | AromaBackup-1.12.2-2.1.1.4.jar                    | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| UCHIJ  | quark                | r1.5-130                 | Quark-r1.5-130.jar                                | None                                     |
	| UCHIJ  | autoreglib           | 1.3-20                   | AutoRegLib-1.3-20.jar                             | None                                     |
	| UCHIJ  | crafttweaker         | 4.1.11                   | CraftTweaker2-1.12-4.1.11.jar                     | None                                     |
	| UCHIJ  | mtlib                | 3.0.5                    | MTLib-3.0.5.jar                                   | None                                     |
	| UCHIJ  | modtweaker           | 4.0.15                   | modtweaker-4.0.15.jar                             | None                                     |
	| UCHIJ  | jei                  | 4.12.1.217               | jei_1.12.2-4.12.1.217.jar                         | None                                     |
	| UCHIJ  | base                 | 3.10.0                   | base-1.12.2-3.10.0.jar                            | None                                     |
	| UCHIJ  | betterbedrockgen     | 6.0.2                    | BetterBedrockGenerator-1.12-6.1.1.jar             | None                                     |
	| UCHIJ  | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar   | None                                     |
	| UCHIJ  | betterquesting       | 3.5.271                  | BetterQuesting-3.5.271.jar                        | None                                     |
	| UCHIJ  | bqt                  | 1.0                      | BetterQuestingTriggerer-1.0.jar                   | None                                     |
	| UCHIJ  | blockcraftery        | 0.1.3                    | blockcraftery-0.1.3.jar                           | None                                     |
	| UCHIJ  | bonsaitrees          | 1.1.1                    | bonsaitrees-1.1.1-b138.jar                        | None                                     |
	| UCHIJ  | ceramics             | 1.12-1.3.4               | Ceramics-1.12-1.3.4.jar                           | None                                     |
	| UCHIJ  | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                          | None                                     |
	| UCHIJ  | ctm                  | MC1.12.2-0.3.2.20        | CTM-MC1.12.2-0.3.2.20.jar                         | None                                     |
	| UCHIJ  | chisel               | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                      | None                                     |
	| UCHIJ  | chiselsandbits       | 14.26                    | chiselsandbits-14.26.jar                          | None                                     |
	| UCHIJ  | clumps               | 3.1.1                    | Clumps-3.1.1.jar                                  | None                                     |
	| UCHIJ  | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ  | colytra              | 1.1.0                    | colytra-1.12.2-1.1.0.jar                          | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| UCHIJ  | ctgui                | 1.0.0                    | CraftTweaker2-1.12-4.1.11.jar                     | None                                     |
	| UCHIJ  | crafttweakerjei      | 2.0.2                    | CraftTweaker2-1.12-4.1.11.jar                     | None                                     |
	| UCHIJ  | custommainmenu       | 2.0.8                    | CustomMainMenu-MC1.12.2-2.0.8.jar                 | None                                     |
	| UCHIJ  | diethopper           | 1.1                      | diethopper-1.1.jar                                | None                                     |
	| UCHIJ  | enderstorage         | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ  | theoneprobe          | 1.4.25                   | theoneprobe-1.12-1.4.25.jar                       | None                                     |
	| UCHIJ  | immersiveengineering | 0.12-86                  | ImmersiveEngineering-0.12-86.jar                  | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| UCHIJ  | engineersdoors       | 0.8.0                    | engineers_doors-1.12.2-0.8.0.jar                  | None                                     |
	| UCHIJ  | reborncore           | 3.10.2.337               | RebornCore-1.12.2-3.10.2.337-universal.jar        | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJ  | engineersworkshop    | 1.0.8.37                 | EngineersWorkshopReborn-1.12.2-1.0.8.37.jar       | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| UCHIJ  | valkyrielib          | 1.12.2-2.0.17.2          | valkyrielib-1.12.2-2.0.17.3.jar                   | None                                     |
	| UCHIJ  | environmentaltech    | 1.12.2-2.0.17.1          | environmentaltech-1.12.2-2.0.17.1.jar             | None                                     |
	| UCHIJ  | mcmultipart          | 2.5.3                    | MCMultiPart-2.5.3.jar                             | None                                     |
	| UCHIJ  | redstoneflux         | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar           | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| UCHIJ  | mekanism             | 1.12.2-9.4.13.349        | Mekanism-1.12.2-9.4.13.349.jar                    | None                                     |
	| UCHIJ  | exchangers           | 1.12.2-2.8               | Exchangers-1.12.2-2.8.jar                         | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| UCHIJ  | extracells           | 2.6.1                    | ExtraCells-1.12.2-2.6.1a.jar                      | None                                     |
	| UCHIJ  | fastfurnace          | 1.1.1                    | FastFurnace-1.12.2-1.1.1.jar                      | None                                     |
	| UCHIJ  | fastbench            | 1.5.3                    | FastWorkbench-1.12.2-1.5.3.jar                    | None                                     |
	| UCHIJ  | faufil               | 1.0.2                    | Faucets and Filters-1.0.2.jar                     | None                                     |
	| UCHIJ  | foamfix              | 0.10.2-1.12.2            | foamfix-0.10.2-1.12.2.jar                         | None                                     |
	| UCHIJ  | limelib              | 1.7.12                   | limelib-1.12.2-1.7.12.jar                         | None                                     |
	| UCHIJ  | furnus               | 2.1.8                    | furnus-1.12.2-2.1.8.jar                           | None                                     |
	| UCHIJ  | guideapi             | 1.12-2.1.6-61            | Guide-API-1.12-2.1.6-61.jar                       | None                                     |
	| UCHIJ  | harvest              | 1.12-1.2.6-18            | Harvest-1.12-1.2.6-18.jar                         | None                                     |
	| UCHIJ  | igwmod               | 1.4.4-15                 | IGW-Mod-1.12.2-1.4.4-15-universal.jar             | None                                     |
	| UCHIJ  | immersivecables      | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar                  | None                                     |
	| UCHIJ  | immersivepetroleum   | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar               | None                                     |
	| UCHIJ  | immersivetech        | 1.3.10                   | immersivetech-1.12-1.3.10.jar                     | None                                     |
	| UCHIJ  | lunatriuscore        | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar       | None                                     |
	| UCHIJ  | ingameinfoxml        | 2.8.2.94                 | InGameInfoXML-1.12.2-2.8.2.94-universal.jar       | None                                     |
	| UCHIJ  | mantle               | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                          | None                                     |
	| UCHIJ  | inspirations         | 1.12.2-0.2.3             | Inspirations-1.12.2-0.2.3.jar                     | None                                     |
	| UCHIJ  | inventorytweaks      | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                          | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJ  | ironchest            | 1.12.2-7.0.40.824        | ironchest-1.12.2-7.0.40.824.jar                   | None                                     |
	| UCHIJ  | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                       | None                                     |
	| UCHIJ  | loottweaker          | 0.0.8                    | LootTweaker-1.12.2-0.0.8.jar                      | None                                     |
	| UCHIJ  | jeresources          | 0.8.5.27                 | JustEnoughResources-1.12.2-0.8.5.27.jar           | None                                     |
	| UCHIJ  | kc                   | 1.12                     | knobcontrol-1.12-4.0.20.jar                       | None                                     |
	| UCHIJ  | mekanismgenerators   | 9.4.11                   | MekanismGenerators-1.12.2-9.4.13.349.jar          | None                                     |
	| UCHIJ  | mekanismtools        | 9.4.11                   | MekanismTools-1.12.2-9.4.13.349.jar               | None                                     |
	| UCHIJ  | modlister            | 1.12.2-3.2.4             | ModLister-1.12.2-3.2.4.jar                        | None                                     |
	| UCHIJ  | moreoverlays         | 1.14                     | moreoverlays-1.14-mc1.12.2.jar                    | None                                     |
	| UCHIJ  | morpheus             | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                           | None                                     |
	| UCHIJ  | mousetweaks          | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                      | None                                     |
	| UCHIJ  | netherportalfix      | 5.3.17                   | NetherPortalFix_1.12.1-5.3.17.jar                 | None                                     |
	| UCHIJ  | oreexcavation        | 1.4.129                  | OreExcavation-1.4.129.jar                         | None                                     |
	| UCHIJ  | p455w0rdslib         | 2.0.35                   | p455w0rdslib-1.12-2.0.35.jar                      | None                                     |
	| UCHIJ  | shetiphiancore       | 3.5.8                    | shetiphiancore-1.12.0-3.5.8.jar                   | None                                     |
	| UCHIJ  | platforms            | 1.4.6                    | platforms-1.12.0-1.4.6.jar                        | None                                     |
	| UCHIJ  | reccomplex           | 1.4.7                    | RecurrentComplex-1.4.7.jar                        | None                                     |
	| UCHIJ  | resourceloader       | 1.5.3                    | ResourceLoader-MC1.12.1-1.5.3.jar                 | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| UCHIJ  | roguelike            | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar                | None                                     |
	| UCHIJ  | simplecorn           | 2.4.1                    | SimpleCorn1.12-1.12-2.4.1.jar                     | None                                     |
	| UCHIEE | simpleoregen         | 4.3.4                    | SimpleOreGeneration-4.3.4+mc+1.12.2.jar           | None                                     |
	| UCHI   | bq_standard          | 3.4.145                  | StandardExpansion-3.4.145.jar                     | None                                     |
	| UCHI   | stg                  | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                              | None                                     |
	| UCHI   | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                   | None                                     |
	| UCHI   | tp                   | 3.2.31                   | tinyprogressions-1.12.2-3.3.31-Release.jar        | None                                     |
	| UCHI   | tombmanygraves2api   | 1.12.2-1.0.0             | tombmanygraves2api-1.12.2-1.0.0.jar               | None                                     |
	| UCHI   | usefulnullifiers     | 1.5.0                    | usefulnullifiers-1.5.0.jar                        | None                                     |
	| UCHI   | universalmodifiers   | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.17.3.jar                   | None                                     |
	| UCHI   | vc                   | 5.9.13                   | ViesCraft-1.12.2-5.9.13.jar                       | None                                     |
	| UCHI   | waystones            | 4.0.67                   | Waystones_1.12.2-4.0.67.jar                       | None                                     |
	| UCHI   | wearablebackpacks    | 3.1.3                    | WearableBackpacks-1.12.2-3.1.3.jar                | None                                     |
	| UCHI   | weirdinggadget       | 1.0                      | weirdinggadget-1.12.2-2.0.5-universal.jar         | None                                     |
	| UCHI   | wct                  | 3.9.68                   | WirelessCraftingTerminal-1.12.2-3.9.68.jar        | None                                     |
	| UCHI   | woot                 | 1.12.2-1.4.6             | woot-1.12.2-1.4.6.jar                             | None                                     |
	| UCHI   | xtones               | 1.12-1.0.8-11            | Xtones-1.12-1.0.8-11.jar                          | None                                     |
	| UCHI   | elulib               | 0.1.12                   | elulib-0.1.12.jar                                 | None                                     |

P.S I'm playing on modpack called "Automaton" and i've must download simple ore generator beacuse the furnus mod wasn't spawning one ore that was crushing my game.

**Comment by pupnewfster** [comment]
I believe this is due to the fact you are using an ancient version of Mekanism (9.4.1) the current latest version is (9.8.1). At some point between the two versions (I think sometime during 9.6.x), our config system changed which simple ores seems to have updated to support. It does not seem that they have bothered to put a "minimum" supported Mekanism version, so you are getting this crash instead of just being told to update Mekanism.

cc: @Rohzek (The next time you are working on Simple Ores you may want to include `[9.6.3, )` as the version for where you declare the optional Mekanism dependency; given at a glance I think that is the version the new config system internals were done. No reason to bother releasing an update *just* to include this change though.)

**Comment by thiakil** [comment]
But also why are you using our internal classes @Rohzek?

**Comment by Rohzek** [comment]
> But also why are you using our internal classes @Rohzek?

Rather than messing with the files on the disk, config is interacted with through code.

**Comment by thiakil** [comment]
Clearly, but what are you doing to the config?
