### ISSUE TITLE
[Serious Bug]Using crusher and combiner to infinite gain coal!!

### ISSUE THREAD

**Issue by cuifuyani** [mekanism/Mekanism#5636]
Mek version: Mekanism-1.12.2-9.8.1.383
![image](https://user-images.githubusercontent.com/35100768/64428883-66122a00-d0e7-11e9-8dd9-b0c18d5b8176.png)
![image](https://user-images.githubusercontent.com/35100768/64428922-74604600-d0e7-11e9-8069-4ab75c73883c.png)
So... Thats easy to fix..
Coals are crucial but we cannot gain it by some mix of energy and void hahah

**Comment by thiakil** [comment]
Our recipe only gives 2 coal from ore: https://github.com/mekanism/Mekanism/blob/bbc0f862da8e8f1ae092fea9b57313d919865c4b/src/main/java/mekanism/common/integration/OreDictManager.java#L249-L250

We can't really balance against every mod out there, only between ourselves and vanilla. Crafttweaker is there for *pack makers* to balance their pack.
