### ISSUE TITLE
Power Compatibility Issue with Progressive Automation

### ISSUE THREAD

**Issue by StoneyMahoney420** [mekanism/Mekanism#5643]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Hard crashes caused when attempting to improperly attach an RF cable to a PA Miner

#### Steps to reproduce:
1. Place the Miner
2. Place any tier of universal cable adjacent to it

OR

1. Place the Miner
2. Install an RF Engine in the Miner
3. Place any tier of universal cable adjacent to it
4. Remove the RF Engine from the Miner

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2816 (also confirmed on previous versions)
**Mekanism:** 9.8.1.383 (tested multiple previous versions, found version 9.6.9.367 and earlier appears to work perfectly)
**Other relevant version:** Progressive Automation: 1.7.8, 1.7.7 both tested

NB: Disabling FE integration in the Mekanism config file prevents connection to PA machines and the crashes go away.

NB: Crash log linked is from mod pack build in progress, issue confirmed to occur on clean instance of Minecraft with no other mods.

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://paste.ee/p/tdsy3

**Comment by pupnewfster** [comment]
The crash log points to their code as having the bug. My guess is that they are reporting they support the FE capability, but actually don't. Interestingly it isn't even they are returning a null capability, but are crashing in their own code trying to get the capability in the first place.
