### ISSUE TITLE
Sophos reports old Mekanism is listening to the microphone

### ISSUE THREAD

**Issue by scribbler957** [mekanism/Mekanism#5646]
FYI The AstroBlock modpack is using Mekanism 1.12.2-9.6.8.366 (about 13 releases ago). Sophos AV is reporting that the mod is listening to the microphone. I don't know why it's reporting it, or whether other old versions have this error (the newest ones don't trigger). I'm sure it's a weird dependency mixup causing some third-party library to include something stupid, but you might consider pulling that release to avoid problems. (DW20 and Soaryn mentioned AstroBlock on YT so others may take a peek.)
https://github.com/NFINIT-Development/AstroBlock/issues/82

**Comment by pupnewfster** [comment]
Turning off the voice server in the config probably will stop this?

**Comment by thiakil** [comment]
Pretty sure your AV is just being super paranoid. Yes, if you have the voice server turned on the device is _opened_, but it's not actually _recording_

**Comment by scribbler957** [comment]
It's not paranoid if it's true. AV is reporting that software was accessing the mic and that's all. Personally, I think it's bad coding to open channels you're not using and be lax about security, but I was just giving you a heads up about a potential problem.
