### ISSUE TITLE
Sponge server stall Illegal PhaseTracker access

### ISSUE THREAD

**Issue by OblivionNW** [mekanism/Mekanism#5647]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The server is stalling running on a Sponge with what seems to be something related to Mekanism.

#### Steps to reproduce:
1. I'm not sure how or why this is happening.

#### Version (make sure you are on the latest version before reporting):
**SpongeForge:** 1.12.2-2838-7.1.7-RC3924
**Minecraft Forge:** 14.23.5.2838
**Mekanism:** Manual build from commit 02afcd7 since it fixed a variety of other bugs

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/g2NPatVj

**Comment by OblivionNW** [comment]
And another casued by an Illegal async chunk load: https://pastebin.com/wK6R6Qph

**Comment by thiakil** [comment]
Please post a log that doesnt expire, I can no longer see where this was occurring from

**Comment by pupnewfster** [comment]
Closing this due to lack of feedback, and it seeming likely that this is due to the sponge async prevention checks which we should no longer be tripping, due to changes we have made in the 1.15 branch.
