### ISSUE TITLE
Digital miners mining down from top to bottom.

### ISSUE THREAD

**Issue by Gliese-832-c** [mekanism/Mekanism#5648]
I would like to see this, because not only does it make more sense to mine from top to bottom¹, it also looks much better, I also can visually track the process more easily.

There are Buildcraft quarries, but I don't like to use them, since buildcraft uses their own strange power system and stubbornly decide against having compatibility with RF/FE.

¹the digital miner, having the ability to just remove the ores which are buried below tens of meters of rock doesn't make sense anyway, I know, but I still would like to see this feature

**Additional context**
I don't really know what to add here. Maybe I can say that I searched all the menus in the digital miner and didn't find anything.

**Comment by TripTripy** [comment]
I know this isn't helpful to the issue, but for solving the buildcraft power issue, try using https://www.curseforge.com/minecraft/mc-mods/energy-converters Not only can you convert from FE/RF to MJ, but other mods energy generators produce a lot more energy than buildcraft's do, allowing the quarry to go faster than ever.

**Comment by aidancbrady** [comment]
The Digital Miner mines in this way due to the low-overhead data structure we use to maintain references to blocks that are needed to mine. Unfortunately, changing this wouldn't allow us to have the same kind of performance/overhead we currently have in the Miner.
