### ISSUE TITLE
Making the Quantum Entangloporter more like the Tesseract from Thermal Expansion

### ISSUE THREAD

**Issue by Nocty1501** [mekanism/Mekanism#5649]
**Describe the the feature you'd like**
The Quantum Entangloporter appears to have an invisible item slot inside it and cannot accept any more item input until it is cleared. This is creating massive problems for me, as I am using a BuildCraft quarry for my mining and the Quantum Entangloporter is literally _too slow_. The receiving Entangloporter is auto-ejecting directly into a chest and this is still not quick enough, meaning my quarry chest gets backed up almost immediately. The Thermal Expansion Tesseract has none of these issues, and can funnel as many items through as are put into it.

**Describe alternatives you've considered**
The Thermal Expansion Tesseract.

**Additional context**
For a demonstration of what I'm talking about, set up a BuildCraft quarry and put a Quantum Entangloporter over it to collect the items it outputs. The quarry will immediately begin spewing the items all over the place because the Entangloporter can't move them quickly enough to the destination. Attempt the same with a Thermal Expansion Tesseract and all the items will end up at the destination Tesseract's attached inventory as quickly as they come in.

**Comment by thiakil** [comment]
No plans to do this at this stage. Note that you'd be best to use an active extraction at the other end instead of relying on auto eject. 
This will still limit you to one stack per tick though
