### ISSUE TITLE
arbitary form for the teleporter

### ISSUE THREAD

**Issue by bobodoustaud** [mekanism/Mekanism#5652]
It could be a good feature to be able to build a bigger teleporter, like a horizontal one or a larger size like the nether portal

**Comment by thiakil** [comment]
I'm not sure this is worth the effort, but do note that for a receive only Teleporter, only the receiver block is needed, not the whole frame

**Comment by aidancbrady** [comment]
Thanks for the suggestion, but I think we'll be leaving the Teleporters be for now.
