### ISSUE TITLE
Turbine multiblock refusing to form

### ISSUE THREAD

**Issue by doctor-something5000** [mekanism/Mekanism#5653]
For some reason or another, the steam turbine multiblock is refusing to form itself. I also looked upon many tutorials on it but it just does not work. 
This problem happened in the Aug 8th update of mekanism.
Please look into the problem and make a quick fix maybe in the next update.
Thanks in advance.

**Comment by TepperPepper** [comment]
Got any screenshots? Those would be helpful.

**Comment by doctor-something5000** [comment]
here are some screenshots:
https://m.imgur.com/a/hpWVJmt

**Comment by thommy101** [comment]
Are you sure it's not working? Perhaps you're refering to the texture not changing, then you might miss an optional dependency ConnectedTexturesMod.

**Comment by doctor-something5000** [comment]
Yes I am certain that it does not work because when I was right-clicking it no GUI pops out.(If there is really no GUI then forgive me for my stupidity)

**Comment by crapStone** [comment]
You need to use `Pressure Dispersers` and not `Turbine Vents` around the `Rotational Complex`.

**Comment by doctor-something5000** [comment]
oh makes good sense.... BTW what is the use of saturation condensers?
