### ISSUE TITLE
Ore Processing: Silver & Aluminum support

### ISSUE THREAD

**Issue by IchHabeHunger54** [mekanism/Mekanism#5663]
When playing in modpacks with Mekanism, two ores in particular seem to be missing in the ore processing chain: Silver and Aluminum. Currently, I'm only able to get two ingots out of a silver/aluminum ore (due to Thermal Foundation's pulverized ores), and I'd love to get more output, as this is quite necessary in many bigger modpacks (I do especially struggle with aluminum in Galacticraft).

**Comment by trpg1** [comment]
You could use JAOPCA to automaticly add support for most ores to the mekanism ore processing including Silver, Aluminum, and many others (almost all ores with correct oredict.)

**Comment by term2112** [comment]
it does, JEI shows the crystals, shards, clumps, etc for it.

**Comment by IchHabeHunger54** [comment]
Yes, I did see silver in Mekanism (sorry for that one), but aluminum is still missing.

**Comment by aidancbrady** [comment]
We will not personally be adding support for any external ores while JAOPCA is still around. However, I've just made some serious improvements to our ore processing framework that will make it easy for us to make additions in the future. Marking this as closed.
