### ISSUE TITLE
[1.12.2] Some error is spam in my server

### ISSUE THREAD

**Issue by SamLam140330** [mekanism/Mekanism#5665]
#### Issue description:
When no player is in the specific world (In this time is DIM-6), some error will generate and spam in the server console every second.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.5.2847
**Mekanism:** 1.12.2-9.8.2.389
**Other relevant version:** Sponge: 1.12.2-2838-7.1.7-RC3927

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/e0Ct5m6B

**Comment by SamLam140330** [comment]
Does anyone know how to fix it? It is very annoying :(

**Comment by aidancbrady** [comment]
This is likely fixed in our 1.15 releases. If the issue persists, we will reopen.
