### ISSUE TITLE
"java.lang.IllegalStateException: Not building!" My minecraft keeps crashing!

### ISSUE THREAD

**Issue by Colypoly12345** [mekanism/Mekanism#5666]
My Vics Modern Warefare mod keeps crashing in the inventory.

Here is my crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 10/9/19 2:11 AM
Description: Rendering item

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.func_188616_a(CompatibleWeaponRenderer.java:137)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:356)
	at codechicken.lib.render.item.CCRenderItem.func_180450_b(CCRenderItem.java:323)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.func_188616_a(CompatibleWeaponRenderer.java:137)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)

-- Item being rendered --
Details:
	Item Type: com.vicmatskiv.weaponlib.Weapon@4e6eb11d
	Registry Name: mw:m16a4
	Item Aux: 0
	Item NBT: null
	Item Foil: false

-- Item being rendered --
Details:
	Item Type: com.vicmatskiv.weaponlib.Weapon@4e6eb11d
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at codechicken.lib.render.item.CCRenderItem.handleCaughtException(CCRenderItem.java:188)
	at codechicken.lib.render.item.CCRenderItem.func_184391_a(CCRenderItem.java:359)
	at codechicken.lib.render.item.CCRenderItem.func_180450_b(CCRenderItem.java:323)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (323, 25). Absolute: (1293, 943)
	Screen size: Scaled: (480, 262). Absolute: (1920, 1046). Scale factor of 4

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['colypoly12345'/466, l='MpServer', x=-372.01, y=86.00, z=978.16]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-252,64,240), Chunk: (at 4,4,0 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 53902 game time, 53902 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 125 total; [EntityMinecartChest['Minecart with Chest'/772, l='MpServer', x=-344.50, y=20.06, z=1037.50], EntitySkeleton['Skeleton'/1796, l='MpServer', x=-437.50, y=63.00, z=1043.50], EntityItem['item.tile.sapling.oak'/773, l='MpServer', x=-324.13, y=76.00, z=1011.88], EntityItem['item.tile.sapling.oak'/774, l='MpServer', x=-321.67, y=76.00, z=1012.13], EntityPig['Pig'/1034, l='MpServer', x=-405.87, y=80.00, z=899.78], EntityPig['Pig'/1035, l='MpServer', x=-430.56, y=72.00, z=908.79], EntityPig['Pig'/1036, l='MpServer', x=-315.71, y=70.00, z=899.19], EntityZombie['Zombie'/2062, l='MpServer', x=-426.50, y=32.00, z=941.50], EntityPig['Pig'/1038, l='MpServer', x=-334.30, y=69.00, z=910.50], EntityBat['Bat'/1558, l='MpServer', x=-361.33, y=14.03, z=983.61], EntityBat['Bat'/1559, l='MpServer', x=-358.17, y=13.05, z=981.29], EntityBat['Bat'/1815, l='MpServer', x=-418.44, y=54.60, z=990.32], EntityBat['Bat'/1560, l='MpServer', x=-356.48, y=13.05, z=982.24], EntityBat['Bat'/1856, l='MpServer', x=-421.25, y=25.53, z=1050.13], EntityBat['Bat'/1858, l='MpServer', x=-423.55, y=26.00, z=1050.13], EntityBat['Bat'/1862, l='MpServer', x=-309.25, y=25.77, z=1018.49], EntitySpider['Spider'/1354, l='MpServer', x=-312.53, y=33.10, z=1054.70], EntitySkeleton['Skeleton'/1355, l='MpServer', x=-312.50, y=31.00, z=1056.50], EntityCreeper['Creeper'/1617, l='MpServer', x=-356.50, y=8.00, z=973.50], EntityZombie['Zombie'/2389, l='MpServer', x=-307.50, y=40.00, z=1028.50], EntityZombie['Zombie'/2390, l='MpServer', x=-306.50, y=40.00, z=1028.50], EntityPlayerSP['colypoly12345'/466, l='MpServer', x=-372.01, y=86.00, z=978.16], EntityZombie['Zombie'/1637, l='MpServer', x=-413.50, y=25.00, z=1040.50], EntityPig['Pig'/613, l='MpServer', x=-451.50, y=69.00, z=919.56], EntityCreeper['Creeper'/1129, l='MpServer', x=-395.14, y=8.00, z=983.54], EntityPig['Pig'/618, l='MpServer', x=-432.73, y=69.00, z=934.64], EntityZombie['Zombie'/1131, l='MpServer', x=-386.50, y=8.00, z=975.50], EntityPig['Pig'/619, l='MpServer', x=-439.50, y=70.00, z=930.67], EntitySpider['Spider'/1645, l='MpServer', x=-364.50, y=13.00, z=982.50], EntitySkeleton['Skeleton'/1135, l='MpServer', x=-435.27, y=19.00, z=1027.50], EntityZombie['Zombie'/1904, l='MpServer', x=-390.50, y=19.00, z=1025.50], EntitySkeleton['Skeleton'/1136, l='MpServer', x=-435.27, y=19.00, z=1028.52], EntityZombie['Zombie'/1905, l='MpServer', x=-392.50, y=19.00, z=1025.50], EntitySkeleton['Skeleton'/1137, l='MpServer', x=-433.50, y=18.00, z=1025.50], EntityPig['Pig'/625, l='MpServer', x=-448.75, y=67.00, z=928.61], EntityCreeper['Creeper'/1906, l='MpServer', x=-394.50, y=19.00, z=1025.50], EntityCustomMob10001['entity.gassy.name'/2418, l='MpServer', x=-392.50, y=8.00, z=985.50], EntitySkeleton['Skeleton'/1138, l='MpServer', x=-431.50, y=18.00, z=1025.50], EntityPig['Pig'/626, l='MpServer', x=-437.52, y=71.00, z=922.30], EntityCreeper['Creeper'/1907, l='MpServer', x=-395.50, y=19.00, z=1024.50], EntityZombie['Zombie'/2419, l='MpServer', x=-396.50, y=8.00, z=983.50], EntityCreeper['Creeper'/2675, l='MpServer', x=-361.50, y=43.00, z=929.50], EntityPig['Pig'/629, l='MpServer', x=-450.61, y=68.00, z=965.29], EntityCreeper['Creeper'/2166, l='MpServer', x=-401.50, y=31.00, z=995.50], EntityPig['Pig'/630, l='MpServer', x=-449.36, y=68.00, z=972.41], EntityPig['Pig'/631, l='MpServer', x=-442.52, y=66.59, z=954.73], EntityCreeper['Creeper'/632, l='MpServer', x=-443.53, y=21.00, z=998.80], EntityChicken['Chicken'/633, l='MpServer', x=-447.50, y=72.00, z=992.82], EntitySquid['Squid'/634, l='MpServer', x=-417.59, y=54.04, z=990.21], EntityPig['Pig'/635, l='MpServer', x=-427.25, y=70.00, z=981.52], EntityChicken['Chicken'/640, l='MpServer', x=-448.77, y=72.00, z=1032.12], EntityCreeper['Creeper'/1666, l='MpServer', x=-308.50, y=49.00, z=1025.50], EntityZombie['Zombie'/642, l='MpServer', x=-440.50, y=22.00, z=1019.50], EntitySkeleton['Skeleton'/643, l='MpServer', x=-443.50, y=22.00, z=1014.50], EntitySkeleton['Skeleton'/644, l='MpServer', x=-443.50, y=22.00, z=1013.50], EntityCustomMob10000['entity.bandit1.name'/2693, l='MpServer', x=-353.50, y=68.00, z=1009.50], EntitySkeleton['Skeleton'/645, l='MpServer', x=-449.21, y=22.00, z=1013.51], EntityXPOrb['Experience Orb'/656, l='MpServer', x=-432.98, y=71.00, z=1042.06], EntitySkeleton['Skeleton'/657, l='MpServer', x=-429.50, y=23.00, z=1027.50], EntityEnderman['Enderman'/658, l='MpServer', x=-429.50, y=23.00, z=1028.50], EntityItem['item.item.porkchopRaw'/659, l='MpServer', x=-423.07, y=68.00, z=1034.95], EntityXPOrb['Experience Orb'/660, l='MpServer', x=-424.75, y=67.00, z=1034.75], EntitySkeleton['Skeleton'/2452, l='MpServer', x=-397.50, y=36.00, z=999.50], EntityXPOrb['Experience Orb'/661, l='MpServer', x=-422.56, y=68.00, z=1033.68], EntitySkeleton['Skeleton'/2453, l='MpServer', x=-396.50, y=36.00, z=999.50], EntityItem['item.item.porkchopRaw'/662, l='MpServer', x=-428.95, y=70.00, z=1032.61], EntityXPOrb['Experience Orb'/663, l='MpServer', x=-431.85, y=71.00, z=1036.37], EntitySquid['Squid'/664, l='MpServer', x=-419.60, y=54.00, z=992.15], EntityBat['Bat'/665, l='MpServer', x=-437.44, y=19.05, z=1035.40], EntityXPOrb['Experience Orb'/667, l='MpServer', x=-445.66, y=72.00, z=1033.16], EntitySkeleton['Skeleton'/668, l='MpServer', x=-421.27, y=59.00, z=1008.51], EntityEnderman['Enderman'/669, l='MpServer', x=-419.50, y=60.00, z=1012.41], EntityZombie['Zombie'/2205, l='MpServer', x=-334.50, y=24.00, z=1035.50], EntityZombie['Zombie'/670, l='MpServer', x=-423.50, y=63.00, z=1014.81], EntitySkeleton['Skeleton'/671, l='MpServer', x=-421.27, y=59.00, z=1010.50], EntityZombie['Zombie'/673, l='MpServer', x=-422.50, y=25.00, z=1050.74], EntityBat['Bat'/2733, l='MpServer', x=-393.27, y=8.18, z=979.13], EntitySpider['Spider'/1977, l='MpServer', x=-427.50, y=22.00, z=1029.50], EntityZombie['Zombie'/2492, l='MpServer', x=-366.08, y=20.00, z=1027.50], EntityZombie['Zombie'/2494, l='MpServer', x=-367.50, y=20.00, z=1028.50], EntitySkeleton['Skeleton'/2495, l='MpServer', x=-363.50, y=20.00, z=1027.50], EntitySkeleton['Skeleton'/2496, l='MpServer', x=-366.83, y=20.00, z=1027.50], EntityPig['Pig'/711, l='MpServer', x=-408.70, y=74.00, z=925.78], EntityItem['item.item.porkchopRaw'/712, l='MpServer', x=-407.80, y=71.00, z=972.60], EntityXPOrb['Experience Orb'/713, l='MpServer', x=-410.16, y=71.00, z=970.32], EntityXPOrb['Experience Orb'/714, l='MpServer', x=-408.49, y=71.00, z=969.61], EntityItem['item.item.rottenFlesh'/716, l='MpServer', x=-384.55, y=72.00, z=931.33], EntityBat['Bat'/717, l='MpServer', x=-408.45, y=60.10, z=1007.75], EntitySquid['Squid'/718, l='MpServer', x=-413.91, y=53.89, z=991.19], EntityZombie['Zombie'/719, l='MpServer', x=-398.51, y=58.00, z=1004.48], EntityZombie['Zombie'/720, l='MpServer', x=-407.50, y=56.00, z=1007.50], EntityCreeper['Creeper'/721, l='MpServer', x=-412.82, y=56.00, z=1007.49], EntityZombie['Zombie'/2001, l='MpServer', x=-402.70, y=57.00, z=930.80], EntitySquid['Squid'/722, l='MpServer', x=-413.40, y=53.00, z=988.40], EntityCreeper['Creeper'/2002, l='MpServer', x=-405.14, y=60.00, z=930.54], EntityPig['Pig'/723, l='MpServer', x=-405.62, y=70.00, z=1004.73], EntityPig['Pig'/724, l='MpServer', x=-404.22, y=70.00, z=987.48], EntitySpider['Spider'/725, l='MpServer', x=-405.68, y=23.00, z=1016.69], EntitySkeleton['Skeleton'/726, l='MpServer', x=-410.50, y=23.00, z=1012.50], EntityBat['Bat'/727, l='MpServer', x=-407.75, y=28.15, z=1017.26], EntityCreeper['Creeper'/728, l='MpServer', x=-414.19, y=58.00, z=1012.46], EntityItem['item.item.rottenFlesh'/729, l='MpServer', x=-407.57, y=70.00, z=1022.69], EntityItem['item.tile.cloth.black'/730, l='MpServer', x=-412.23, y=70.00, z=990.05], EntityXPOrb['Experience Orb'/731, l='MpServer', x=-409.53, y=70.00, z=987.85], EntityItem['item.tile.cloth.white'/732, l='MpServer', x=-404.29, y=70.00, z=985.93], EntityItem['item.item.muttonRaw'/733, l='MpServer', x=-402.73, y=70.00, z=986.62], EntityXPOrb['Experience Orb'/734, l='MpServer', x=-403.68, y=70.00, z=989.99], EntitySheep['Sheep'/737, l='MpServer', x=-392.78, y=71.00, z=973.64], EntityPig['Pig'/741, l='MpServer', x=-382.67, y=70.00, z=970.24], EntityMinecartChest['Minecart with Chest'/743, l='MpServer', x=-366.50, y=13.06, z=986.50], EntityPig['Pig'/744, l='MpServer', x=-389.81, y=70.00, z=1024.73], EntityZombieVillager['Zombie Villager'/745, l='MpServer', x=-373.50, y=20.00, z=1019.50], EntityEnderman['Enderman'/747, l='MpServer', x=-409.48, y=24.00, z=1024.44], EntityCreeper['Creeper'/751, l='MpServer', x=-354.50, y=29.00, z=1029.50], EntityCreeper['Creeper'/752, l='MpServer', x=-354.50, y=29.00, z=1028.50], EntityMinecartChest['Minecart with Chest'/753, l='MpServer', x=-341.50, y=20.06, z=1023.50], EntityBat['Bat'/755, l='MpServer', x=-385.43, y=24.10, z=1051.53], EntityPig['Pig'/757, l='MpServer', x=-408.21, y=70.00, z=1037.57], EntitySkeleton['Skeleton'/758, l='MpServer', x=-365.24, y=20.00, z=1023.50], EntityBat['Bat'/759, l='MpServer', x=-356.58, y=57.10, z=1011.50], EntityBat['Bat'/2551, l='MpServer', x=-347.18, y=38.87, z=944.54], EntitySheep['Sheep'/760, l='MpServer', x=-355.76, y=68.00, z=1011.34], EntityCreeper['Creeper'/2296, l='MpServer', x=-355.50, y=24.00, z=1019.50], EntityZombie['Zombie'/2299, l='MpServer', x=-368.50, y=31.00, z=929.50], EntityZombie['Zombie'/766, l='MpServer', x=-341.23, y=59.00, z=1044.48]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 742405952 bytes (708 MB) / 1342177280 bytes (1280 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID             | Version      | Source                        | Signature                                |
	|:------ |:-------------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft      | 1.12.2       | minecraft.jar                 | None                                     |
	| LCHIJA | mcp            | 9.42         | minecraft.jar                 | None                                     |
	| LCHIJA | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None                                     |
	| LCHIJA | forge          | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None                                     |
	| LCHIJA | codechickenlib | 3.2.2.353    | CodeChickenLib-1.12.2.jar     | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | mw             | 1.11.7.7     | mw-1.11.7.7_mc1.12.2.jar      | None                                     |

	Loaded coremods (and transformers): 
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.24' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.24, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
Wrong issue tracker, doesn't look like Mekanism is even installed

**Comment by Colypoly12345** [comment]
This has nothing to do with Mekanism. It is Vics Modern Warfare.

**Comment by pupnewfster** [comment]
Which is exactly why you were told you are in the wrong issue tracker.

**Comment by Colypoly12345** [comment]
Sorry if I sound dumb but wdym?

**Comment by pupnewfster** [comment]
This is the issue tracker for Mekanism, your issue is with Vics Modern Warfare as you yourself has said, it has nothing to do with Mekanism so belongs on their issue tracker there is no way posting it here will get it fixed.

**Comment by Colypoly12345** [comment]
oh sorry
