### ISSUE TITLE
"java.lang.IllegalStateException: Not building!" My minecraft keeps crashing!

### ISSUE THREAD

**Issue by Colypoly12345** [mekanism/Mekanism#5667]
Whenever I try to use Vics modern Warfare it crashes whenever I open my inventory.

Here is my crash log:
---- Minecraft Crash Report ----

WARNING: coremods are present:
  weaponlib (mw-1.11.7.7_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 10/9/19 9:13 PM
Description: Rendering item

java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.func_188616_a(CompatibleWeaponRenderer.java:137)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.renderer.RenderItem.func_180450_b(RenderItem.java:336)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleWeaponRenderer.func_188616_a(CompatibleWeaponRenderer.java:137)
	at net.minecraftforge.client.ForgeHooksClient.renderLitItem(ForgeHooksClient.java:653)
	at net.minecraft.client.renderer.RenderItem.func_191967_a(RenderItem.java:118)
	at net.minecraft.client.renderer.RenderItem.func_191961_a(RenderItem.java:106)
	at net.minecraft.client.renderer.RenderItem.func_180454_a(RenderItem.java:149)
	at net.minecraft.client.renderer.RenderItem.func_191962_a(RenderItem.java:308)

-- Item being rendered --
Details:
	Item Type: com.vicmatskiv.weaponlib.Weapon@6ffbae2e
	Registry Name: mw:m16a4
	Item Aux: 0
	Item NBT: null
	Item Foil: false
Stacktrace:
	at net.minecraft.client.renderer.RenderItem.func_184391_a(RenderItem.java:347)
	at net.minecraft.client.renderer.RenderItem.func_180450_b(RenderItem.java:336)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:922)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:758)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:75)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:51)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:643)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (301, 16). Absolute: (602, 447)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['colypoly12345'/463, l='MpServer', x=-429.42, y=74.42, z=985.00]]
	Chunk stats: MultiplayerChunkCache: 625, 625
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-252,64,240), Chunk: (at 4,4,0 in -16,15; contains blocks -256,0,240 to -241,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 58171 game time, 58171 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 127 total; [EntityPig['Pig'/536, l='MpServer', x=-500.84, y=70.00, z=908.45], EntityPig['Pig'/543, l='MpServer', x=-487.83, y=71.00, z=910.21], EntityCreeper['Creeper'/802, l='MpServer', x=-374.50, y=8.00, z=977.50], EntitySkeleton['Skeleton'/804, l='MpServer', x=-367.73, y=8.00, z=996.47], EntityMinecartChest['Minecart with Chest'/809, l='MpServer', x=-366.50, y=13.06, z=986.50], EntityBat['Bat'/810, l='MpServer', x=-362.88, y=14.10, z=981.53], EntityPig['Pig'/811, l='MpServer', x=-349.71, y=71.00, z=967.59], EntityPig['Pig'/556, l='MpServer', x=-488.23, y=70.00, z=970.34], EntitySpider['Spider'/812, l='MpServer', x=-362.50, y=28.00, z=1011.50], EntityPig['Pig'/557, l='MpServer', x=-492.31, y=70.00, z=973.58], EntityBat['Bat'/813, l='MpServer', x=-356.58, y=57.10, z=1011.50], EntityPig['Pig'/558, l='MpServer', x=-468.46, y=68.00, z=955.22], EntityPig['Pig'/559, l='MpServer', x=-469.50, y=68.00, z=950.50], EntityPig['Pig'/560, l='MpServer', x=-474.54, y=67.00, z=944.51], EntityPig['Pig'/561, l='MpServer', x=-462.39, y=67.00, z=941.77], EntityPig['Pig'/562, l='MpServer', x=-449.32, y=67.00, z=930.15], EntityPig['Pig'/563, l='MpServer', x=-488.24, y=70.00, z=976.90], EntityCreeper['Creeper'/819, l='MpServer', x=-354.50, y=29.00, z=1028.50], EntityPig['Pig'/564, l='MpServer', x=-495.66, y=69.00, z=987.28], EntitySkeleton['Skeleton'/820, l='MpServer', x=-362.30, y=20.00, z=1026.30], EntityChicken['Chicken'/565, l='MpServer', x=-471.85, y=69.00, z=970.51], EntityPig['Pig'/566, l='MpServer', x=-456.32, y=68.00, z=957.74], EntitySkeleton['Skeleton'/567, l='MpServer', x=-449.50, y=14.00, z=974.50], EntityPig['Pig'/568, l='MpServer', x=-453.23, y=69.00, z=973.50], EntityPig['Pig'/569, l='MpServer', x=-479.54, y=71.00, z=984.30], EntityChicken['Chicken'/570, l='MpServer', x=-488.29, y=68.00, z=1028.16], EntityBat['Bat'/571, l='MpServer', x=-489.66, y=12.81, z=1016.42], EntityChicken['Chicken'/572, l='MpServer', x=-459.52, y=70.00, z=973.70], EntityChicken['Chicken'/573, l='MpServer', x=-452.52, y=73.00, z=988.16], EntityItem['item.item.egg'/574, l='MpServer', x=-459.45, y=71.00, z=976.41], EntityChicken['Chicken'/575, l='MpServer', x=-453.09, y=73.00, z=986.52], EntityItem['item.item.egg'/576, l='MpServer', x=-479.21, y=68.00, z=1016.47], EntityCreeper['Creeper'/577, l='MpServer', x=-458.61, y=15.00, z=1005.82], EntitySpider['Spider'/578, l='MpServer', x=-451.57, y=21.00, z=993.83], EntityCreeper['Creeper'/579, l='MpServer', x=-452.23, y=21.00, z=992.52], EntityChicken['Chicken'/580, l='MpServer', x=-458.42, y=71.00, z=1001.16], EntityChicken['Chicken'/581, l='MpServer', x=-457.06, y=71.00, z=1004.93], EntityItem['item.item.egg'/582, l='MpServer', x=-458.67, y=72.00, z=992.25], EntityItem['item.item.egg'/583, l='MpServer', x=-457.67, y=71.00, z=1005.51], EntityChicken['Chicken'/584, l='MpServer', x=-480.21, y=68.00, z=1060.48], EntityChicken['Chicken'/587, l='MpServer', x=-473.44, y=66.00, z=1051.81], EntityChicken['Chicken'/588, l='MpServer', x=-472.44, y=66.00, z=1051.50], EntitySkeleton['Skeleton'/589, l='MpServer', x=-462.25, y=22.00, z=1039.46], EntityBat['Bat'/590, l='MpServer', x=-453.68, y=19.88, z=1035.20], EntityItem['item.item.egg'/591, l='MpServer', x=-453.51, y=72.00, z=1025.97], EntityChicken['Chicken'/592, l='MpServer', x=-454.26, y=72.00, z=1023.90], EntityItem['item.item.egg'/595, l='MpServer', x=-463.51, y=64.00, z=1046.88], EntityEnderman['Enderman'/603, l='MpServer', x=-464.62, y=55.00, z=908.62], EntityPig['Pig'/606, l='MpServer', x=-466.50, y=69.00, z=925.47], EntityPig['Pig'/607, l='MpServer', x=-476.56, y=71.00, z=916.25], EntityPig['Pig'/608, l='MpServer', x=-475.26, y=71.00, z=915.56], EntityEnderman['Enderman'/609, l='MpServer', x=-464.04, y=55.00, z=908.29], EntityPig['Pig'/610, l='MpServer', x=-463.81, y=72.00, z=911.70], EntityPig['Pig'/611, l='MpServer', x=-455.38, y=72.00, z=906.45], EntityPig['Pig'/612, l='MpServer', x=-460.27, y=72.00, z=909.64], EntityPig['Pig'/614, l='MpServer', x=-472.49, y=67.02, z=931.36], EntityZombie['Zombie'/615, l='MpServer', x=-448.20, y=43.00, z=925.51], EntityPig['Pig'/616, l='MpServer', x=-451.50, y=69.00, z=919.56], EntityPig['Pig'/617, l='MpServer', x=-451.49, y=66.00, z=925.31], EntityBat['Bat'/619, l='MpServer', x=-442.24, y=56.27, z=910.91], EntityPig['Pig'/620, l='MpServer', x=-434.28, y=72.00, z=907.58], EntityCreeper['Creeper'/632, l='MpServer', x=-411.50, y=24.00, z=1037.50], EntityCreeper['Creeper'/633, l='MpServer', x=-411.50, y=24.00, z=1032.78], EntityZombie['Zombie'/637, l='MpServer', x=-395.25, y=19.00, z=1025.49], EntityCreeper['Creeper'/638, l='MpServer', x=-399.15, y=19.00, z=1029.40], EntitySkeleton['Skeleton'/639, l='MpServer', x=-393.50, y=19.00, z=1025.50], EntityCustomMob10000['entity.bandit1.name'/640, l='MpServer', x=-391.98, y=19.00, z=1024.56], EntitySpider['Spider'/641, l='MpServer', x=-371.50, y=21.00, z=1017.50], EntityBat['Bat'/642, l='MpServer', x=-368.55, y=22.10, z=1015.75], EntityPig['Pig'/643, l='MpServer', x=-371.74, y=70.00, z=1022.64], EntityBat['Bat'/648, l='MpServer', x=-413.92, y=27.10, z=1064.36], EntityCreeper['Creeper'/652, l='MpServer', x=-396.50, y=13.00, z=1057.50], EntitySkeleton['Skeleton'/653, l='MpServer', x=-375.50, y=22.00, z=1054.50], EntitySkeleton['Skeleton'/654, l='MpServer', x=-379.50, y=22.00, z=1055.50], EntitySkeleton['Skeleton'/655, l='MpServer', x=-378.50, y=22.00, z=1055.50], EntitySquid['Squid'/656, l='MpServer', x=-382.66, y=48.00, z=1047.22], EntitySkeleton['Skeleton'/682, l='MpServer', x=-447.50, y=44.00, z=922.50], EntityPig['Pig'/683, l='MpServer', x=-439.24, y=71.00, z=919.61], EntitySpider['Spider'/685, l='MpServer', x=-428.50, y=36.00, z=907.50], EntityCreeper['Creeper'/687, l='MpServer', x=-427.50, y=36.00, z=907.50], EntityCreeper['Creeper'/688, l='MpServer', x=-427.50, y=36.00, z=908.50], EntityBat['Bat'/692, l='MpServer', x=-425.55, y=43.10, z=922.70], EntityPig['Pig'/693, l='MpServer', x=-440.31, y=67.00, z=936.56], EntityWitch['Witch'/696, l='MpServer', x=-443.81, y=31.00, z=953.51], EntityZombie['Zombie'/697, l='MpServer', x=-443.50, y=29.00, z=949.50], EntityZombie['Zombie'/698, l='MpServer', x=-437.67, y=25.00, z=951.77], EntityPig['Pig'/699, l='MpServer', x=-442.52, y=66.16, z=954.73], EntityPig['Pig'/700, l='MpServer', x=-408.70, y=74.00, z=925.78], EntityCreeper['Creeper'/701, l='MpServer', x=-378.57, y=34.00, z=906.16], EntitySpider['Spider'/705, l='MpServer', x=-444.50, y=22.00, z=973.50], EntityBat['Bat'/706, l='MpServer', x=-384.98, y=31.05, z=917.35], EntitySpider['Spider'/707, l='MpServer', x=-373.50, y=35.00, z=923.50], EntityCreeper['Creeper'/708, l='MpServer', x=-378.83, y=46.00, z=916.53], EntityItem['item.item.egg'/709, l='MpServer', x=-447.66, y=72.00, z=991.98], EntityPig['Pig'/710, l='MpServer', x=-434.50, y=71.00, z=980.72], EntitySkeleton['Skeleton'/711, l='MpServer', x=-445.08, y=22.00, z=1010.15], EntitySkeleton['Skeleton'/712, l='MpServer', x=-443.50, y=22.00, z=1009.50], EntityCreeper['Creeper'/713, l='MpServer', x=-396.50, y=23.00, z=954.50], EntitySkeleton['Skeleton'/714, l='MpServer', x=-376.50, y=32.00, z=937.50], EntitySpider['Spider'/715, l='MpServer', x=-362.66, y=42.00, z=926.73], EntityEnderman['Enderman'/717, l='MpServer', x=-440.50, y=21.00, z=1004.50], EntityCreeper['Creeper'/718, l='MpServer', x=-447.86, y=21.00, z=992.43], EntityPig['Pig'/719, l='MpServer', x=-402.74, y=71.00, z=975.32], EntityZombie['Zombie'/720, l='MpServer', x=-367.48, y=41.00, z=935.78], EntityZombie['Zombie'/721, l='MpServer', x=-355.25, y=39.00, z=942.50], EntitySkeleton['Skeleton'/722, l='MpServer', x=-358.50, y=40.00, z=937.50], EntitySpider['Spider'/724, l='MpServer', x=-406.85, y=29.00, z=985.64], EntityPlayerSP['colypoly12345'/463, l='MpServer', x=-429.42, y=74.42, z=985.00], EntityEnderman['Enderman'/726, l='MpServer', x=-428.50, y=22.00, z=1030.50], EntityPig['Pig'/727, l='MpServer', x=-416.22, y=70.00, z=1039.43], EntityEnderman['Enderman'/728, l='MpServer', x=-410.43, y=23.00, z=1010.68], EntityEnderman['Enderman'/729, l='MpServer', x=-412.50, y=23.00, z=1016.50], EntityZombie['Zombie'/730, l='MpServer', x=-406.50, y=23.00, z=1008.50], EntityZombie['Zombie'/731, l='MpServer', x=-408.50, y=23.00, z=1012.50], EntityZombie['Zombie'/732, l='MpServer', x=-411.33, y=58.00, z=1010.25], EntityCreeper['Creeper'/733, l='MpServer', x=-391.82, y=60.00, z=1002.52], EntityZombie['Zombie'/734, l='MpServer', x=-394.51, y=59.00, z=1001.78], EntityPig['Pig'/735, l='MpServer', x=-390.97, y=70.00, z=1004.45], EntitySheep['Sheep'/736, l='MpServer', x=-396.58, y=71.00, z=991.23], EntitySkeleton['Skeleton'/737, l='MpServer', x=-376.70, y=8.00, z=973.30], EntitySkeleton['Skeleton'/738, l='MpServer', x=-379.70, y=8.00, z=972.70], EntitySkeleton['Skeleton'/739, l='MpServer', x=-379.50, y=8.00, z=971.50], EntityBat['Bat'/995, l='MpServer', x=-400.35, y=8.34, z=984.54], EntityBat['Bat'/740, l='MpServer', x=-351.43, y=38.52, z=946.09], EntityWitch['Witch'/750, l='MpServer', x=-452.50, y=23.00, z=1008.50], EntityWitch['Witch'/751, l='MpServer', x=-452.50, y=23.00, z=1007.50], EntityCreeper['Creeper'/753, l='MpServer', x=-451.50, y=23.00, z=1012.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 690220128 bytes (658 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version      | Source                        | Signature |
	|:------ |:--------- |:------------ |:----------------------------- |:--------- |
	| LCHIJA | minecraft | 1.12.2       | minecraft.jar                 | None      |
	| LCHIJA | mcp       | 9.42         | minecraft.jar                 | None      |
	| LCHIJA | FML       | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | forge     | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar | None      |
	| LCHIJA | mw        | 1.11.7.7     | mw-1.11.7.7_mc1.12.2.jar      | None      |

	Loaded coremods (and transformers): 
weaponlib (mw-1.11.7.7_mc1.12.2.jar)
  com.vicmatskiv.weaponlib.core.WeaponlibClassTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 399.24' Renderer: 'GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 399.24, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8600 CPU @ 3.10GHz

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Vics Modern Warfare:** 
**Other relevant version:**

**Comment by pupnewfster** [comment]
As we told you in #5666 this is not the correct place to report issues with Vics Modern Warefare, go report it on their discord https://discordapp.com/invite/XA7HBSF
