### ISSUE TITLE
Digital Miner

### ISSUE THREAD

**Issue by BriannaCrow** [mekanism/Mekanism#5668]
*Please use the search functionality before reporting an issue. Also, take a look at the closed issues!*

#### Issue description:

The digital miner can see all ore's available to mine, however, are unable to mine do to the items having custom ID names. Example: Iron, gold, Redstone etc
Example: Vanilla Iron ore ID: 15 however they are labelled as # 0015(No space) which the miner is unable to fully register and mine these ores.

#### Steps to reproduce:
1. Install RL Craft
2. Install Mekanism
3. Placed down miner

#### Version (make sure you are on the latest version before reporting):
**Forge:**  Newest for 1.12.2
**Mekanism:** Newest
**Other relevant version:** Newest RL craft mod pack download.

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

No crash logs available.

[gist/pastebin/etc link here]

**Comment by thiakil** [comment]
What filter are you trying to use? The miner doesn't care about a numeric id (or event the localised name)

**Comment by aidancbrady** [comment]
Closing due to lack of feedback. Not running into any issues mining these ores using ItemStack filters.
