### ISSUE TITLE
[BUG] Factory fuction swap not working

### ISSUE THREAD

**Issue by DevTimur** [mekanism/Mekanism#5669]
#5547 ## Issue description:
Ok, when you make factory block, you can swap machines inside to change how this factory function. You put machine IN, and get previous machine back OUT.
![image](https://user-images.githubusercontent.com/22171136/66646017-993b6200-ec2d-11e9-82f3-49b7df22a01c.png)
But when you recieve this machine back it adds empty tag, like this:
![image](https://user-images.githubusercontent.com/22171136/66646091-d99ae000-ec2d-11e9-80d2-36739b256316.png)
And this is preventing machine from been placed back in swap slot.
![image](https://user-images.githubusercontent.com/22171136/66646155-0a7b1500-ec2e-11e9-96ae-7ab18ac33b4e.png)

Forge: **2826**
Mekanism: **Mekanism-1.12.2-9.8.2.389**

**Comment by thiakil** [comment]
This should be resolved in 9.8.3.390
