### ISSUE TITLE
Multiple wind generator items multiply rotation rate

### ISSUE THREAD

**Issue by thecodewarrior** [mekanism/Mekanism#5670]
#### Issue description:
Multiple wind generators items multiply the rotation rate

#### Steps to reproduce:
Have multiple wind generator items rendered at once

The issue appears to be [this line](https://github.com/mekanism/Mekanism/blob/3e8d73fe6da0f073610363dbe6e250c0b9eeef37/src/main/java/mekanism/generators/client/render/item/RenderWindGeneratorItem.java#L48), which updates the angle every time the item is rendered.

**Comment by thiakil** [comment]
Fixed in 9.8.3.390
