### ISSUE TITLE
Universal Cable power lost

### ISSUE THREAD

**Issue by ExDomino** [mekanism/Mekanism#5671]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Power lost when converting RF to EU with Basic Universal Cable.

#### Steps to reproduce:
1. Place an Energy Cell from ThermalExpansion.
2. Place a IndustrialCraft Batbox.
3. Place an Basic Universal Cable between.

Energy Cell power lows but IndustrialCraft Batbox power doesn't raise.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2847
**Mekanism:** 9.8.1.383
**IC2 Classic:** 1.5.4.4

**Comment by doctor-something5000** [comment]
Make sure you are on the latest version then report back.

**Comment by aidancbrady** [comment]
#5682
