### ISSUE TITLE
[1.12.2] Transmitter performance

### ISSUE THREAD

**Issue by bigenergy** [mekanism/Mekanism#5673]
#### Issue description:
The mekanism transmitters cause high loads on my server, is it possible to do something about this?

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.5.2847
**Mekanism:** 1.12.2-9.8.2.389
**Other relevant version:** spongeforge-1.12.2-2838-7.1.7-RC3928

https://sparkprofiler.github.io/#6B8Bb8YhCe

![image](https://user-images.githubusercontent.com/17977139/67622200-b0c73d00-f820-11e9-9a7c-99889d9b8fcc.png)
![image](https://user-images.githubusercontent.com/17977139/67622203-bd4b9580-f820-11e9-92fd-3b46f680609e.png)

**Comment by pupnewfster** [comment]
Unsure, I know over the past ~year we have made a lot of performance improvements to transmitters so I am somewhat unsure of what is causing this. If you could reproduce it without sponge that definitely would be helpful given it might be some weird thing sponge is doing in terms of how TileEntities get tracked. 

The only thing that strikes me as particularly odd I see from looking at the profiling results, is that it is spending a pretty good chunk of time from marking the tiles as dirty on updating comparator outputs. And given I don't remember adding support to transmitters for comparators I believe I *might* be able to somehow make that extra checking code not run. Which might help a decent amount. Not sure when I will get a chance to look at this in more depth given I have mainly been focusing more on various mods in 1.14 lately, but I will add it to the next milestone for purposes of reminding myself I wanted to look into it.
