### ISSUE TITLE
[1.12.2] Error when using OpenComputers with Logistical Sorter with the "addFilter" method

### ISSUE THREAD

**Issue by iKlem** [mekanism/Mekanism#5676]
#### Issue description:
I want to make a program with OpenComputers to automate ore processing and other things with all the machines. I wanted to use the available methods to add filters to the Logistical Sorter but it seems there's an error when I want to use other colors.

I've done some research and found the invoked methods [here](https://github.com/mekanism/Mekanism/blob/95d0fb98b828b815020c31f875b7dd8683f05645/src/main/java/mekanism/common/tile/TileEntityLogisticalSorter.java#L525) (TileEntityLogisticalSorter.java - line 525) and found the colors [here](https://github.com/mekanism/Mekanism/blob/95d0fb98b828b815020c31f875b7dd8683f05645/src/main/java/mekanism/api/EnumColor.java#L15) (EnumColor.java - line 15).

The method i've used is `addFilter` ([this one](https://github.com/mekanism/Mekanism/blob/95d0fb98b828b815020c31f875b7dd8683f05645/src/main/java/mekanism/common/tile/TileEntityLogisticalSorter.java#L548)) for now and the third parameter is a string representing a name from `EnumColor` but for some colors we can't acces to them and I can't put more than 3 colors : 
blue, green & cyan.

I haven't tried to change back version since i'm using the current version below on a private server.

#### Steps to reproduce:
Go ingame, run a computer from OpenComputer, connect an Adapter to the Logistical Sorter and to the computer and typed into lua interpretor these lines :

![image](https://user-images.githubusercontent.com/1726412/68548843-9cbf3600-03f1-11ea-9155-17b0d2546214.png)

#### Version :
**Forge: 14.23.5.2847** 
**Mekanism: 1.12.2-9.8.2.389** 
Other relevant version:
- Minecraft 1.12.2
- OpenComputers 1.12.2-1.7.4.153
- I've a lot of others mods but don't know if it's a good idea to put them all in here.

This is the result of all the commands above :
![image](https://user-images.githubusercontent.com/1726412/68548763-cb88dc80-03f0-11ea-8a3f-34d7c6803928.png)

**Comment by aidancbrady** [comment]
Mekanism development is now entirely focused on Minecraft 1.15, and we plan on rewriting our OpenComputers integration once (if) they update.
