### ISSUE TITLE
Forge Multipart CBE - Covering Cables

### ISSUE THREAD

**Issue by GenoGamer** [mekanism/Mekanism#5680]
Simple request to allow Mekanisms 1.12.2 cables to either be compatible with Chisel and Bits or Forge Multipart CBE in order for them to be covered.

**Comment by pupnewfster** [comment]
They should be compatible with Chisel and Bits if you install MCMultipart.

**Comment by GenoGamer** [comment]
My apologizes, saw that MCMultipart has not been updated in a while and decided to steer clear of it until I found out if it was still stable.

**Comment by MRuth** [comment]
@pupnewfster 

Just tested this out in MC 1.12.2 with Mekanism 9.8.3.390 and MCMultipart 2.5.3 and it seems like cables are no longer working with MultiPart covers:

Any suggestions or something I might be missing?

![2020-01-13_22 42 28](https://user-images.githubusercontent.com/3927478/72314858-2986aa00-3656-11ea-8d9f-277cc08fa279.png)

![2020-01-13_22 42 32](https://user-images.githubusercontent.com/3927478/72314867-2f7c8b00-3656-11ea-826e-cff32b3da671.png)

**Comment by thiakil** [comment]
![2020-01-14_15 34 25](https://user-images.githubusercontent.com/1788847/72323379-88decb80-36e3-11ea-8c36-27c288ab444c.png)

Seems to work fine with Chisels & Bits, probably a problem with the covers mod
