### ISSUE TITLE
Block glitched on explosion and caused constant server spam

### ISSUE THREAD

**Issue by Trnrr** [mekanism/Mekanism#5681]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I'm not sure if this is the cause, but this is what was reported to me. While someone was raiding another members faction they used tnt and a block got stuck in some sort of weird state. It kept playing the explosion effects and sounds and constantly spammed the server. Restarting the server didnt fix it, the only thing that fixed it was removing that block that thankfully someone showed me where it was. The block that was glitched was a basic energy cell from thermal expansion.

I asked on the sponge discord and they said to make a ticket here.

#### Steps to reproduce:
Still trying to find a way to reproduce it but haven't yet.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2846
**Mekanism:** Mekanism-1.12.2-9.8.2.389
**Other relevant version:** 
**SpongeForge:** 1.12.2-2838-7.1.7

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
This is what shows in console over and over: https://gist.githubusercontent.com/Trnrr/2516f1734cef2b2a838bc96d6c0e4e75/raw/debde3cb68e5ebf3fc364c48064a2fa53ed27a9a/gistfile1.txt

**Comment by thiakil** [comment]
Yeah that's a sponge bug, nothing we can do about it
