### ISSUE TITLE
[WIKI] Spam pages on the Mekanism wiki

### ISSUE THREAD

**Issue by jammehcow** [mekanism/Mekanism#5684]
Unrelated to the mod code itself, the wiki seems to have been riddled with spam pages.
Below is a pastebin of the obvious ones I found.

Also a suggestion for wiki content: GitBooks could be a better solution as it means your docs are in a git repo, stored in markdown and could potentially be parsed to produce some kind of in-game documentation book (hint hint). Would be happy to help with that, the docs are looking pretty sparse in some areas.

https://pastebin.com/w8UdUuPw

**Comment by thiakil** [comment]
@Mastergalen I think this one's for you - also account creation is borked, looks like you blocked an AWS internal ip (or similar)

**Comment by pupnewfster** [comment]
I think the *most* likely one we would end up using for being able to also support showing multiblock structures would be [Patchouli](https://www.curseforge.com/minecraft/mc-mods/patchouli), so if you want to figure start figuring out how to get it in the json format (or even just work on getting the docs into a more up to date state), it certainly would be helpful.

**Comment by jammehcow** [comment]
Yeah I was thinking about making some changes to the wiki page but I'd be happy to help look at some options and/or working on a solution.

**Comment by aidancbrady** [comment]
I spoke with my webmaster about this and he just recently flushed the wiki of spam. It’s my intention to eventually move all documentation in-game, however.
