### ISSUE TITLE
Pressure Pipes, Input connecting but not Output

### ISSUE THREAD

**Issue by ConnorTron110** [mekanism/Mekanism#5686]
#### Issue description:
Not too sure if this is Pressure's Fault since last time it was updated was back in in 2017

#### Steps to reproduce:
1. Place input and Output Blocks
2. Place Pipes

#### Versions:
**Forge:** 14.23.5.2847
**Mekanism:** 9.8.3.390
**Pressure Pipes:** 1.3.1.6

#### Image

![image](https://user-images.githubusercontent.com/39780128/69989386-67fb5600-153b-11ea-87d6-c3698ec2e7f5.png)

**Comment by pupnewfster** [comment]
My guess it is a bug on their end due to an issue having been reported to them for the same issue with other mods. https://github.com/bdew/pressure/issues/111

**Comment by ConnorTron110** [comment]
What would have changed in Mechanism that made it incompatible?

**Comment by pupnewfster** [comment]
Are you saying that it used to work and no longer works after you updated mekanism?

**Comment by ConnorTron110** [comment]
I mean i know its an old version but it used to work back in 1.7.10
I can test older versions, ill get back to you on that

**Comment by pupnewfster** [comment]
I meant on an older version of mekanism 1.12. As it is likely that it has never worked in the 1.12 version due to the fact it seems to be a bug in the pressure pipes mod according to the issue I linked.
