### ISSUE TITLE
Mekanism ingots causing crash

### ISSUE THREAD

**Issue by olandraselac** [mekanism/Mekanism#5687]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Started using Mekanism with no issues. Upon making my first round of mod-specific ingots I got a client crash which now repeats as soon as I rejoin the server. 

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** Forge version 14.23.5.2847
**Mekanism:**  Mekanism version 1.12.2-9.8.3.390
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 7
	at mekanism.common.item.ItemIngot.func_77667_c(ItemIngot.java:41)
	at net.minecraft.item.Item.func_77657_g(Item.java:292)
	at net.minecraft.item.Item.func_77653_i(Item.java:362)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:662)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:79)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mekanism.common.item.ItemIngot.func_77667_c(ItemIngot.java:41)
	at net.minecraft.item.Item.func_77657_g(Item.java:292)
	at net.minecraft.item.Item.func_77653_i(Item.java:362)
	at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:617)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:662)
	at net.minecraft.client.gui.GuiScreen.func_191927_a(GuiScreen.java:143)
	at net.minecraft.client.gui.GuiScreen.func_146285_a(GuiScreen.java:137)
	at net.minecraft.client.gui.inventory.GuiContainer.func_191948_b(GuiContainer.java:175)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73863_a(SourceFile:79)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory
	Mouse location: Scaled: (261, 193). Absolute: (523, 92)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['BlocktimussPrime'/2140, l='MpServer', x=-166.69, y=69.00, z=-61.46]]
	Chunk stats: MultiplayerChunkCache: 400, 400
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-212,64,68), Chunk: (at 12,4,4 in -14,4; contains blocks -224,0,64 to -209,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 13840 game time, 2788 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 76 total; [EntityBat['Bat'/12801, l='MpServer', x=-121.67, y=27.10, z=-127.03], EntityPlayerSP['BlocktimussPrime'/2140, l='MpServer', x=-166.69, y=69.00, z=-61.46], EntityCreeper['Creeper'/11783, l='MpServer', x=-220.50, y=25.00, z=-50.50], EntityBat['Bat'/13074, l='MpServer', x=-203.43, y=15.81, z=-102.33], EntityBat['Bat'/13075, l='MpServer', x=-181.40, y=16.81, z=-90.95], EntityZombie['Zombie'/11803, l='MpServer', x=-126.50, y=30.00, z=-87.50], EntityCreeper['Creeper'/12571, l='MpServer', x=-176.58, y=43.00, z=-78.19], EntitySquid['Squid'/7721, l='MpServer', x=-182.57, y=60.20, z=-40.50], EntitySquid['Squid'/7722, l='MpServer', x=-162.72, y=60.68, z=-26.48], EntitySkeleton['Skeleton'/12591, l='MpServer', x=-143.50, y=36.00, z=-116.50], EntityRabbit['Rabbit'/8241, l='MpServer', x=-119.50, y=63.00, z=-134.50], EntitySkeleton['Skeleton'/12850, l='MpServer', x=-157.50, y=31.00, z=-109.50], EntityZombie['Zombie'/12852, l='MpServer', x=-165.50, y=16.00, z=-64.50], EntitySquid['Squid'/13111, l='MpServer', x=-146.30, y=62.36, z=-24.50], EntitySquid['Squid'/13112, l='MpServer', x=-138.02, y=60.99, z=-23.96], EntitySkeleton['Skeleton'/12610, l='MpServer', x=-170.50, y=16.00, z=-66.50], EntityChicken['Chicken'/76, l='MpServer', x=-240.48, y=84.00, z=11.84], EntityZombie['Zombie'/10576, l='MpServer', x=-126.50, y=44.00, z=2.50], EntityBat['Bat'/12881, l='MpServer', x=-176.25, y=27.05, z=-74.25], EntityChicken['Chicken'/82, l='MpServer', x=-205.49, y=65.00, z=-48.23], EntityChicken['Chicken'/83, l='MpServer', x=-224.47, y=67.00, z=-54.51], EntityChicken['Chicken'/84, l='MpServer', x=-195.10, y=64.00, z=-54.92], EntityChicken['Chicken'/85, l='MpServer', x=-201.80, y=66.00, z=-57.44], EntityChicken['Chicken'/86, l='MpServer', x=-207.51, y=66.00, z=-42.16], EntityBabySkeleton['Baby Skeleton'/11606, l='MpServer', x=-177.50, y=17.00, z=-58.50], EntityChicken['Chicken'/87, l='MpServer', x=-226.19, y=70.00, z=-40.61], EntityItem['item.item.egg'/11607, l='MpServer', x=-227.12, y=70.00, z=-41.34], EntityBat['Bat'/12889, l='MpServer', x=-87.91, y=26.47, z=5.23], EntityChicken['Chicken'/96, l='MpServer', x=-180.50, y=69.00, z=-22.50], EntityChicken['Chicken'/97, l='MpServer', x=-179.50, y=69.00, z=-22.50], EntityChicken['Chicken'/98, l='MpServer', x=-180.50, y=69.00, z=-23.50], EntityChicken['Chicken'/99, l='MpServer', x=-182.50, y=69.00, z=-22.50], EntitySkeleton['Skeleton'/12643, l='MpServer', x=-134.50, y=19.00, z=-65.50], EntityPig['Pig'/100, l='MpServer', x=-171.50, y=64.00, z=-11.50], EntityPig['Pig'/101, l='MpServer', x=-174.50, y=64.00, z=-11.50], EntityCreeper['Creeper'/12645, l='MpServer', x=-133.50, y=19.00, z=-66.50], EntityPig['Pig'/102, l='MpServer', x=-175.50, y=65.00, z=-12.50], EntityCreeper['Creeper'/12646, l='MpServer', x=-135.50, y=19.00, z=-66.50], EntityPig['Pig'/103, l='MpServer', x=-173.50, y=64.00, z=-12.50], EntitySpider['Spider'/13160, l='MpServer', x=-180.50, y=43.00, z=-74.50], EntityChicken['Chicken'/108, l='MpServer', x=-143.88, y=64.00, z=-9.66], EntityChicken['Chicken'/109, l='MpServer', x=-148.50, y=64.00, z=-11.50], EntityBat['Bat'/12912, l='MpServer', x=-159.33, y=25.40, z=-25.48], EntityBat['Bat'/12913, l='MpServer', x=-190.25, y=44.10, z=-68.09], EntityRabbit['Rabbit'/133, l='MpServer', x=-92.50, y=63.00, z=-43.50], EntityRabbit['Rabbit'/134, l='MpServer', x=-94.91, y=63.00, z=-40.50], EntityZombie['Zombie'/12680, l='MpServer', x=-162.50, y=15.00, z=-62.50], EntityItem['item.item.egg'/11403, l='MpServer', x=-188.43, y=64.00, z=-60.81], EntityZombie['Zombie'/12944, l='MpServer', x=-228.50, y=26.00, z=-17.50], EntitySkeleton['Skeleton'/11932, l='MpServer', x=-134.46, y=28.00, z=-124.27], EntityCreeper['Creeper'/11933, l='MpServer', x=-137.50, y=26.00, z=-118.50], EntitySkeleton['Skeleton'/12957, l='MpServer', x=-234.70, y=14.00, z=-113.70], EntityRabbit['Rabbit'/2210, l='MpServer', x=-121.53, y=69.00, z=-100.28], EntityCreeper['Creeper'/12706, l='MpServer', x=-243.50, y=35.00, z=-27.50], EntityRabbit['Rabbit'/2211, l='MpServer', x=-119.98, y=70.00, z=-88.50], EntitySpider['Spider'/11181, l='MpServer', x=-149.30, y=30.10, z=-115.70], EntitySkeleton['Skeleton'/12461, l='MpServer', x=-163.50, y=35.00, z=-79.50], EntityWitch['Witch'/12465, l='MpServer', x=-129.50, y=17.00, z=-116.50], EntityItem['item.item.egg'/11955, l='MpServer', x=-180.38, y=69.00, z=-23.42], EntitySkeleton['Skeleton'/12727, l='MpServer', x=-244.50, y=29.00, z=-19.50], EntityCreeper['Creeper'/12475, l='MpServer', x=-140.50, y=22.00, z=-136.50], EntityItem['item.item.egg'/12478, l='MpServer', x=-201.54, y=66.00, z=-57.34], EntityZombie['Zombie'/11973, l='MpServer', x=-185.50, y=20.00, z=-26.50], EntityItem['item.item.egg'/10953, l='MpServer', x=-225.07, y=67.00, z=-54.84], EntityCreeper['Creeper'/12489, l='MpServer', x=-180.50, y=43.00, z=-75.50], EntityCreeper['Creeper'/12491, l='MpServer', x=-120.50, y=26.00, z=-133.45], EntityZombie['Zombie'/13003, l='MpServer', x=-182.91, y=30.00, z=-54.57], EntityCreeper['Creeper'/12492, l='MpServer', x=-115.50, y=27.00, z=-140.50], EntityBabySkeleton['Baby Skeleton'/13004, l='MpServer', x=-182.02, y=30.00, z=-54.30], EntityItem['item.item.egg'/8397, l='MpServer', x=-181.70, y=69.00, z=-22.37], EntityCreeper['Creeper'/12493, l='MpServer', x=-118.50, y=27.00, z=-140.50], EntityRabbit['Rabbit'/8398, l='MpServer', x=-114.44, y=68.00, z=-127.09], EntityCreeper['Creeper'/12494, l='MpServer', x=-120.50, y=27.00, z=-137.50], EntityZombie['Zombie'/12504, l='MpServer', x=-125.19, y=16.00, z=-113.50], EntityItem['item.item.egg'/10978, l='MpServer', x=-148.81, y=64.00, z=-11.04], EntitySkeleton['Skeleton'/12515, l='MpServer', x=-157.50, y=24.00, z=-25.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 713131504 bytes (680 MB) / 1308622848 bytes (1248 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version          | Source                                  | Signature |
	|:------ |:------------------ |:---------------- |:--------------------------------------- |:--------- |
	| LCHIJA | minecraft          | 1.12.2           | minecraft.jar                           | None      |
	| LCHIJA | mcp                | 9.42             | minecraft.jar                           | None      |
	| LCHIJA | FML                | 8.0.99.99        | forge-1.12.2-14.23.5.2847.jar           | None      |
	| LCHIJA | forge              | 14.23.5.2847     | forge-1.12.2-14.23.5.2847.jar           | None      |
	| LCHIJA | baubles            | 1.5.2            | Baubles-1.12-1.5.2.jar                  | None      |
	| LCHIJA | biomesoplenty      | 7.0.1.2443       | Biomes-O-Plenty-Mod-1.12.2.jar          | None      |
	| LCHIJA | elevatorid         | 1.3.12           | ElevatorMod-1.12.2-1.3.12.jar           | None      |
	| LCHIJA | journeymap         | 1.12.2-5.5.5     | journeymap-1.12.2-5.5.5.jar             | None      |
	| LCHIJA | mekanism           | 1.12.2-9.8.3.390 | Mekanism-1.12.2-9.8.3.390.jar           | None      |
	| LCHIJA | mekanismgenerators | 1.12.2-9.8.3.390 | MekanismGenerators-1.12.2-9.8.3.390.jar | None      |
	| LCHIJA | mekanismtools      | 1.12.2-9.8.3.390 | MekanismTools-1.12.2-9.8.3.390.jar      | None      |
	| LCHIJA | roguelike          | 1.8.0            | RoguelikeDungeons-1.12.2-1.8.0.jar      | None      |
	| LCHIJA | thaumcraft         | 6.1.BETA26       | Thaumcraft-1.12.2-6.1.BETA26.jar        | None      |
	| LCHIJA | thutcore           | 5.21.0           | thutcore-1.12.2-5.21.0.jar              | None      |
	| LCHIJA | thutcore_compat    | 1.0              | thutcore-1.12.2-5.21.0.jar              | None      |
	| LCHIJA | thuttech           | 6.1.6            | thuttech-1.12.2-6.1.6.jar               | None      |
	| LCHIJA | bspkrscore         | at_0.9           | TreeCapitator-Mod-1.12.jar              | None      |
	| LCHIJA | treecapitator      | at_0.9           | TreeCapitator-Mod-1.12.jar              | None      |

	Loaded coremods (and transformers): 
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13559 Compatibility Profile Context 26.20.12028.2' Renderer: 'AMD Radeon (TM) R9 380 Series'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R9 380 Series GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment]
You somehow seem to have an ingot with invalid meta data, did you manually spawn in an ingot or something?

**Comment by olandraselac** [comment]
Ahh, ok. Yeah, the first time I'd used /give to replace some lost items, and then again after a clean install to test this issue.

**Comment by pupnewfster** [comment]
Closing this as it was caused due to manually spawning in an invalid item, and not being possible in 1.15 due to meta no longer even existing
