### ISSUE TITLE
FrequencyManager ConcurrentModificationException

### ISSUE THREAD

**Issue by clienthax** [mekanism/Mekanism#5690]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crash / ConcurrentModificationException

#### Steps to reproduce:
1. Unknown

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2847-universal.jar
**Mekanism:** Mekanism-1.12.2-9.8.2.389.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/clienthax/71bbd305aa686fdb8a7424af9b837d6e

**Comment by clienthax** [comment]
I have a feeling this was linked to the miner thread, as I havn't seen this again since patching that.

**Comment by thiakil** [comment]
FrequencyManager is completely separate though

**Comment by clienthax** [comment]
> FrequencyManager is completely separate though

If the chunk with the TE calling the manager is loaded async it would explain the CME, i havn't hit this error once since the PR i submitted was setup on my server.
