### ISSUE TITLE
Server crash on Chunk load

### ISSUE THREAD

**Issue by CommanderLouiz** [mekanism/Mekanism#5691]
[crash-2019-12-05_21.35.49-server.txt](https://github.com/OpenModularTurretsTeam/OpenModularPassiveDefense/files/3933736/crash-2019-12-05_21.35.49-server.txt)

On a server with 1.12.2 and 139 mods
The conflict is between this mod (Mekanism) and OMPD (Open Modular Passive Defense)
It appears to happen on chunk load, though because it is a check for creature spawn I am not 100% sure.
It doesn't matter what Dimension the players base is in, because they have moved it multiple times, and this error keeps appearing randomly.
I have submitted this bug to the OMPD github as well, which I will link [here](https://github.com/OpenModularTurretsTeam/OpenModularPassiveDefense/issues/28).

**Comment by thiakil** [comment]
This is a Sponge bug (I have only ever seen it when Sponge is involved) - there should be a 1:1 relationship between the block at a position and the tile entity at that position.

In cases such as this that relationship is broken. This has also been reported before; **please follow the issue template when reporting issues, which includes searching prior issues**

**Comment by CommanderLouiz** [comment]
I had searched for this issue before, and I found [this issue](https://github.com/mekanism/Mekanism/issues/3663) from 3 years ago, which also involves a cast to a Mek multiblock in the CreatureSpawning. It was fixed then, but since it seems to have resurfaced I figured I would make a new post.

**Comment by pupnewfster** [comment]
The most recent repost of the issue was #5685
