### ISSUE TITLE
Rotary Condenser Automation Broken

### ISSUE THREAD

**Issue by TheCowMooooo** [mekanism/Mekanism#5693]
#### Issue description:
Rotary Condenser Will not accept input or output at least from Mekanism pipes

#### Steps to reproduce:
just put one down and try to connect a pipe to it.

#### Version (make sure you are on the latest version before reporting):
**Forge:1.12.2** 
**Mekanism:Latest at time of writing** 
**Other relevant version: Funcraft - FC: 1.0**

**Comment by thiakil** [comment]
Are you connecting to the correct side? the gas and fluid sides are different
