### ISSUE TITLE
Crash with OpenComputers

### ISSUE THREAD

**Issue by TheFirstMinecrafter** [mekanism/Mekanism#5694]
#### Steps to reproduce:
1. Download all my mods. (Mainly Mekanism and OpenComputers [used VanillaFix])
2. Open Minecraft
3. Get crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 9.8.2.389
**Other relevant version:** OpenComputers: 1.7.5.192

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[https://paste.dimdev.org/qitomodebu.mccrash](https://paste.dimdev.org/qitomodebu.mccrash)

**Comment by aidancbrady** [comment]
Mekanism development is now entirely focused on Minecraft 1.15, and we plan on rewriting our OpenComputers integration once (if) they update.
