### ISSUE TITLE
Chemical Injection Factory Struggles to Run Directly on Salt

### ISSUE THREAD

**Issue by cyberdragon442** [mekanism/Mekanism#5695]
#### Issue description:
The chemical injector can't convert salt directly to HCL fast enough to sustain itself and stutters making it super slow. Appears related to #2601 (either a bug with the factory or with the speed and gas upgrades conflicting with salt conversion)

#### Steps to reproduce:
1.Feed a basic chemical injection factory with ores or crystals and salt as fast as you can (even multiple sides of salt input)
2. Add max gas efficiency and some speed upgrades
3. Watch it stutter on and off and not use up all the salt

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2847
**Mekanism:** 1.12.2-9.3.390
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment]
It is not a bug that factories are not able to be run fully directly on salt as there are multiple inputs trying to all use the salt at once and it is just not able to process it that quickly.
