### ISSUE TITLE
[1.12.2] Personal Chest Dupe Bug 2

### ISSUE THREAD

**Issue by bigenergy** [mekanism/Mekanism#5696]
#### Issue description:
This also applies a little to #5557 
See a video: https://www.youtube.com/watch?v=pICkwXaDny8&feature=youtu.be

#### Steps to reproduce:
First dupe:
1. take a personal chest in 2 hand
2. open the chest which is in the first hand
3. shift the personal chest to another slot (through the numbers on the keyboard)
4. throw the chest that is in the inventory
5. pick up items

Second dupe:
1. open a personal chest
2. swap chests (through the numbers on the keyboard)
3. throw the chest or just shift it through the mouse (be sure to throw it or shift it through the mouse)
4. and pick up items

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2847
**Mekanism:** 9.8.3.390
**Other relevant version:** spongeforge-1.12.2-2838-7.1.8-RC3963

**Comment by bigenergy** [comment]
any ideas?

**Comment by bigenergy** [comment]
@aidancbrady Are you not going to fix this in 1.12.2?  This error has been more than six months old ...

**Comment by aidancbrady** [comment]
We're focused entirely on 1.15.2 development now. We sadly don't have the manpower to back port these changes.
