### ISSUE TITLE
1.12.2 server crash when player goes to his home

### ISSUE THREAD

**Issue by Trnrr** [mekanism/Mekanism#5697]
I have an issue where our server crashes once a player loads his base. This is an issue with mekanism. I loaded the world up on our test server (same as live server) but I removed mekanism from the test client and test server and logged in and I was able to load the world and see the base. Removing mekanism fixed the crash issue.

#### Steps to reproduce:
1. Log into that chunk
2. Crash

#### Version (make sure you are on the latest version before reporting):
**Forge Version:** forge-1.12.2-14.23.5.2847-universal.jar
**Mekanism Versions:**
Mekanism-1.12.2-9.8.3.390.jar
MekanismGenerators-1.12.2-9.8.3.390.jar
MekanismTools-1.12.2-9.8.3.390.jar
**Sponge version:** spongeforge-1.12.2-2838-7.1.8-RC3963.jar

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Log with sponge: https://gist.github.com/Trnrr/a016bb029a66679511ce7c9d762e8958
Crash Report with sponge: https://gist.github.com/Trnrr/1c8761146b972ceacba757eb8e2570f0

Log **without** sponge: https://gist.github.com/Trnrr/d2678d29f578367e68855dca666fc496
Crash report **without** sponge: https://gist.github.com/Trnrr/ab742526edd50d554bf59c514a529434

Im not sure how github handles old tickets so I decided to make one because Im not sure if it was the same issue as https://github.com/mekanism/Mekanism/issues/5516

**Comment by Trnrr** [comment]
Closed because it's the same issue as 5516 or some other reason?

**Comment by thiakil** [comment]
Looks like the same stack trace to me

**Comment by Trnrr** [comment]
Ok np. I will check the other issue to see if a solution is ever found or if there is anything I could do to help try and solve it. Right now I either have to remove the chunk or the mod :(
