### ISSUE TITLE
Logistical Sorter does not sort by Mod ID

### ISSUE THREAD

**Issue by Zobody** [mekanism/Mekanism#5699]
#### Issue description:

Simply speaking, Mod ID filters on Logistical Sorter does not work.

#### Steps to reproduce:
1. Place two inventories, at least 2 blocks apart
2. Place a Logistical Sorter on one of the inventories, and connect it with Logistical Transporters to the another inventory
3. Using the Configurator, change the color of the Logistical Transporters in the path towards the second inventory
4. Add some items from a mod with mod id X to the first inventory (e. g. `mekanism`)
5. Right click the Logistical Sorter, add a `Mod ID` filter, filtering on X (again, `mekanism`), with the previous color set in the step 3

Expectations: Logistical Sorter should pull out X mod's items from the first inventory and send them towards the second inventory.

Result: Nothing happens

![image](https://user-images.githubusercontent.com/16544117/71533157-f88d4200-28ff-11ea-8cdb-c203ea108796.png)
![image](https://user-images.githubusercontent.com/16544117/71533172-0e9b0280-2900-11ea-8733-81e92b98e215.png)
![image](https://user-images.githubusercontent.com/16544117/71533184-1b1f5b00-2900-11ea-9c5b-94f1da5d82bd.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-forge1.12.2-14.23.5.2847
**Mekanism:** 1.12.2-9.8.3.390

**Comment by thiakil** [comment]
Please follow the issue template.

**Comment by Zobody** [comment]
> Please follow the issue template.

I've edited the original issue to follow the issue template

**Comment by aidancbrady** [comment]
#5863
