### ISSUE TITLE
Heat Generator flashing Glitch - lead to Server crash

### ISSUE THREAD

**Issue by mcpedro99** [mekanism/Mekanism#5705]
#### Issue description: Building a line of Heat Generators cause then to get into a glitchy state were they start flashing and don't produce power constantly anymore (playing on server)
ModPack: MC.Eternal

#### Steps to reproduce:
1. 4 lines of heat generators (10 generators each)
2. connect all of then with pipes with lava, and hook'em up with power cables
3. after a short while all generators will start flashing as if turning on and off, instead of producing 40RF/t it produces nearly nothing

Took video, might help understanding my situation
https://streamable.com/jtq8q
Also, after finding this weird, I decided to replace all of it, but even after I broke all of it, the sound remained, so I decided to rejoin, by rejoining this happened and crashed the hole server
https://streamable.com/4d234

#### Version: 1.12.2
**Forge:*8.0.99.99
**Mekanism: 9.8.3.390
**Other relevant version: Mekanism Generators and Tools same version

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

since it is a server, I can't get hold of the crash log

**Comment by thiakil** [comment]
In the first video, you're simply not providing a constant amount of lava to the generators on the top row.

For the 2nd, that's a bit odd, but placing a block next to one of them should fix them.

> since it is a server, I can't get hold of the crash log

We can't do anything without it, please ask the server owner
