### ISSUE TITLE
Mekanism Thermal Evaporator Blindness

### ISSUE THREAD

**Issue by ProfessorFuzz** [mekanism/Mekanism#5708]
#### Issue description:
The thermal evaporator multiblock containment visuals cause ui glitch that completely blinds the player.  Only occurs when multiblock is complete and contains a liquid.  Blindness prevents access to all menus (inventory, escape menu, etc.)

#### Steps to reproduce:
1.  Make thermal evaporator multiblock,
2. Pump in liquid, 
3.  be close to multiblock or looking at multiblock.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2838
**Mekanism:** 1.12.2-9.8.0.381.jar
**Other relevant version:**  All The Mods Modpack v5.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment]
Update mekanism.
