### ISSUE TITLE
{Compatibility Testing} Mekanism & Ender IO / Results POSITIVE

### ISSUE THREAD

**Issue by Vaygrim** [mekanism/Mekanism#571]
TEST ENVIRONMENT:
- Minecraft 1.6.4
- Forge 953
- Buildcraft 4.1.2 & 4.2.0
- Mekanism 5.6.0.547
- EnderIO 1.6.4-0.5.0.98

Testing the compatibility of the power systems between Ender IO and Mekanism resulted in positive functionality. Power transmits at appropriate speeds and proportions to all machines connected, using both Ender IO power conduits and Mekanism universal cables.

![2013-12-01_12 04 06](https://f.cloud.github.com/assets/4295188/1650880/9860118a-5ab3-11e3-85b7-3eb72f12b620.png)

In the above screenshot, all machines function and receive power. The only difference noticed in behavior is that of SPEED of power delivery: universal cables deliver power near-instantaneously while the different tiers of Ender IO power conduit deliver power at an expected difference in speed as it related to their 'quality tier'. Higher tiers of cable delivers power faster, lower tiers of cable deliver power slower, etc.

![2013-12-01_12 05 09](https://f.cloud.github.com/assets/4295188/1650886/dfac2d9e-5ab3-11e3-841b-ad01ca800521.png)

Power transmission between energy storage mediums also functions appropriately. I was able to charge an Ender IO Capacitor Bank using an Ultimate Energy Cube, and vice versa. Not issues discovered here either.

![2013-11-26_23 08 50](https://f.cloud.github.com/assets/4295188/1650887/086e90be-5ab4-11e3-8675-00e5a3fb3885.png)

Testing of the Ender IO Item Conduits even resulted in the pleasant surprise of full compatibility, with the item conduits capable of pulling machine output and appropriately routing it to other desired targets.

====> TESTING RESULTS <====
Ender IO and Mekanism, as of the mod versions used in this testing, show no limitations or incompatibilities beyond the usual slight loss of power through energy conversion between power systems. Ender IO conduits will power Mekanism machines, and can pull items from machines, even route liquids from Mekanism's Dynamic Tanks. All functionality also works in reverse, with Mekanism's Mechanical Pipes working just fine with the likes of an Ender IO Reservoir and more.

No issues regarding mod incompatibility or limited functionality was discovered.

**Comment by tomasdev** [comment]
Is it me or this is no longer working as of 1.10?
