### ISSUE TITLE
Atomic Disassembler and Bins

### ISSUE THREAD

**Issue by OlRusty** [mekanism/Mekanism#5710]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
using extended mining mode with the atomic disassembler on the bins crashes the client

#### Steps to reproduce:
1. change mode on the disassembler to extended mining
2. mine bins of any kind - empty or filled or mix of both
3.causes crash and log appears

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2847
**Mekanism:** Mekanism-1.12.2-9.8.3.390
**Other relevant version:** Absolute Mekanism 1.4 (modpack)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
can view log after this is reproduced (i dont know how to do pastebin sorry)
[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment]
Closing this as it is fixed in 9.9.9 (MC 1.15), which is now released and on curseforge.
