### ISSUE TITLE
NullpointerException on "Updating screen events": Enrichment factory

### ISSUE THREAD

**Issue by SeseMueller** [mekanism/Mekanism#5711]
### Issue description:
My Game crashed twice (I tried it again) when I tried to extract a energy upgrade in an Elite Enrichment Factory. 

#### Steps to reproduce:
1. Place Elite Enrichment Factory
2. Try extracting upgrades
3. -> Crash

#### Version 
**Forge:** 14.23.5.2838
**Mekanism:** (Mekanism-1.12.2-9.8.0.381.jar)
**Other relevant version:** Modpack: Skyfactory 4 latest version, launched via Twitch.

Pastebin: https://pastebin.com/y9PG9k1W
Note that this didn't happen on every upgrade-extraction.

**Comment by pupnewfster** [comment]
Update Mekanism I am pretty sure this was fixed in either back in 9.8.1 or 9.8.2

**Comment by SeseMueller** [comment]
Yes. It is resolved now. I am always a bit scared about compatibility issues when updating modpacks by hand, but it worked quite well. Thanks.
