### ISSUE TITLE
Factory Upgrades

### ISSUE THREAD

**Issue by KidBrine** [mekanism/Mekanism#5712]
**Describe the the feature you'd like**
IIRC there used to be an item you could right click on to a factory to upgrade it rather than picking it up and crafting the new factory, essentially I want a feature like that.

**Describe alternatives you've considered**
I have tried making a ComputerCraft turtle that upgrades things, but realized that a lot of my factories are covered on all sides

**Comment by pupnewfster** [comment]
Right clicking on a factory with a tier installer should do what you want. You still have to go in the order of the tiers, you can't skip any.
