### ISSUE TITLE
[1.15]Servercrash when placing induction matrix

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#5713]
#### Issue description:
Created an induction matrix

#### Version (make sure you are on the latest version before reporting):
**Forge:**  forge-30.0.30
**Mekanism:** Mekanism-1.15.1-9.9.0.391

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://s.yoosk.pl/VfK90

**Comment by pupnewfster** [comment]
While this is duplicated by #5714 I am going to close this and keep that one open as it is slightly more detailed.
