### ISSUE TITLE
Crash when placing induction

### ISSUE THREAD

**Issue by Yoosk** [mekanism/Mekanism#5714]
#### Issue description:
server crashed and entered crash loop after placing induction casing

#### Steps to reproduce:
1. try to build induction casing
2. crash
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.1-30.0.30
**Mekanism:** 1.15.1-9.9.0.391
**Other relevant version:** [ram 0.0.6 dev  ](https://github.com/Team-RAM/RAM/releases/download/0.0.6/RAM-dev-0.0.6.zip)

[crash log](http://s.yoosk.pl/VfK90)

**Comment by pupnewfster** [comment]
Fixed in 9.9.1

**Comment by Canz2** [comment]
Hi I'm getting this crash with the version 10.1.2.457 of Mekanism with the Ragnamod VI modpack
and my friend are getting the crash too
