### ISSUE TITLE
Config is not being respected

### ISSUE THREAD

**Issue by Yoosk** [mekanism/Mekanism#5715]
#### Issue description:
When trying to disable world generation for in and copper ores, its not being respected, ores spawn no matter of config changes.

#### Steps to reproduce:
1. Disable copper ore generation in config
2. Generate new world
3. Ore will be still generated in world

#### Version:
Forge: 1.15.1-30.0.30
Mekanism: 1.15.1-9.9.0.391
Other relevant version: [ram 0.0.6 dev ](https://github.com/Team-RAM/RAM/releases/download/0.0.6/RAM-dev-0.0.6.zip)

**Comment by pupnewfster** [comment]
Fixed in 9.9.1
