### ISSUE TITLE
Ore generation on server not working while using BIOMESOP

### ISSUE THREAD

**Issue by Yoosk** [mekanism/Mekanism#5716]
![2020-01-06_22-10-44-javaw](https://user-images.githubusercontent.com/4502802/71849746-b5368e80-30ca-11ea-9008-d9e878459c61.png)
#### Issue description:
Ore generation in world, while using [Biomes O' Plenty](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty) as default world type, does not work. No ores from mekanism spawn at all. 
At the same time generation of ores from [janoeo](https://www.curseforge.com/minecraft/mc-mods/janoeo) works fine both with and without BoP.

#### Steps to reproduce:
1. Add BoP next to mekanism on server
2. Enable BoP as default world type
3. Start the server, no ores from mekanism

#### Version:
Forge: 1.15.1-30.0.30
Mekanism: 1.15.1-9.9.0.391
Other relevant version: [ram 0.0.6 dev ](https://github.com/Team-RAM/RAM/releases/download/0.0.6/RAM-dev-0.0.6.zip)

**Comment by pupnewfster** [comment]
Fixed in 9.9.1
