### ISSUE TITLE
Osmium armor stats

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5717]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Osmium armor stats are nor properly adjusted.

#### Version (make sure you are on the latest version before reporting):
**Forge: 30.0.30
**Mekanism: Mekanism-1.15.1-9.9.0.391

**Comment by pupnewfster** [comment]
Fixed in 9.9.1, though a config regeneration is needed to make it not have to be manually fixed.
