### ISSUE TITLE
Solar generator gui broken

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#5718]
#### Issue description:
Gui Text goes over the borders 
always says it is producing 0 RF/FE/EU

seems to work fine otherwise

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.30
**Mekanism:** 1.15.1-9.9.0.391

**Comment by pupnewfster** [comment]
This is partially intended that the text goes over the border, and will be fixed once I finish working on the gui rewrite to make gui's be more dynamic. I decided to merge the two lines into one from a lang key standpoint. Though I will fix the fact that it claims it is producing no power.

**Comment by pupnewfster** [comment]
Closing as 9.9.11 is now released and on curseforge.
