### ISSUE TITLE
[Mekanism:Generators] Gas burning generator doesn't accept gas

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5719]
#### Issue description:
Gas Burning generator doesn't accept any gas (tested with Hydrogen and Ethylene). I have tried to pump it in with the tube and also with the gas tank in the GUI and both didn't accept.

#### Steps to reproduce:
1. Pumping gas in with the gas tube
2. Placing gas tank in the generator GUI also doesn't work 

#### Version (make sure you are on the latest version before reporting):
**Forge: 30.0.30
**Mekanism: 1.15.1-9.9.0.391

**Comment by pupnewfster** [comment]
Fixed in 9.9.1
