### ISSUE TITLE
Gas Tank Gui not quite right

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#5720]
![image](https://user-images.githubusercontent.com/4283717/71852061-30527180-30d8-11ea-943e-8b690f8384c7.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.30
**Mekanism:** Mekanism-1.15.1-9.9.0.391

**Comment by pupnewfster** [comment]
Fixed in 9.9.1
