### ISSUE TITLE
Electrolytic Separator doesn't work

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#5721]
#### Issue description:
Has water and power. does nothing :(

#### Steps to reproduce:
1.Fill Separator with power and water
2.watch...
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.30
**Mekanism:** Mekanism-1.15.1-9.9.0.391

**Comment by pupnewfster** [comment]
Fixed in 9.9.1
