### ISSUE TITLE
Digital miner speed upgrades does not incerase power requirement

### ISSUE THREAD

**Issue by Yoosk** [mekanism/Mekanism#5722]
#### Issue description:
When adding speed upgrades to digital miner, its speed increase but power consumption stays the same and/or is not showing/updating properly.

#### Steps to reproduce:
1. place an digital miner
2. add speed upgrades
3. notice that FE/T stays the same

#### Version:
Forge: 1.15.1-30.0.30
Mekanism: 1.15.1-9.9.0.391
Other relevant version: [ram 0.0.6 dev ](https://github.com/Team-RAM/RAM/releases/download/0.0.6/RAM-dev-0.0.6.zip)

**Comment by pupnewfster** [comment]
Fixed in 9.9.1
