### ISSUE TITLE
Seismic reader/vibrator crash on server

### ISSUE THREAD

**Issue by Yoosk** [mekanism/Mekanism#5723]
#### Issue description:
Tried to use seismic reader while near powered seismic vibrator, crashed out from server.

#### Steps to reproduce:
1. Place and power seismic vibrator
2. use seismic reader
3. crash

#### Version:
Forge: 1.15.1-30.0.30
Mekanism: 1.15.1-9.9.0.391
Other relevant version: [ram 0.0.6 dev ](https://github.com/Team-RAM/RAM/releases/download/0.0.6/RAM-dev-0.0.6.zip)

[Crashlog](http://s.yoosk.pl/Q7pJe)

**Comment by pupnewfster** [comment]
Fixed in 9.9.1
