### ISSUE TITLE
Crash when trying to change jetpack mode

### ISSUE THREAD

**Issue by Yoosk** [mekanism/Mekanism#5724]
#### Issue description:
Tried to change mode on jetpack, crashed.

#### Steps to reproduce:
1. get a jetpack
2. try to change mode
3. crash

#### Version:
Forge: 1.15.1-30.0.30
Mekanism: 1.15.1-9.9.0.391
Other relevant version: [ram 0.0.6 dev ](https://github.com/Team-RAM/RAM/releases/download/0.0.6/RAM-dev-0.0.6.zip)

[Crashlog](http://s.yoosk.pl/MD0Xb)

**Comment by pupnewfster** [comment]
Fixed in 9.9.1
