### ISSUE TITLE
[1.7.10] v9.1 download missing!

### ISSUE THREAD

**Issue by GlitchSabre** [mekanism/Mekanism#5728]
I know that v9.1 for 1.7.10 is much outdated and updaed versions are recommended. However I have an old computer and it can handle only being a 1.7.10 mekanism server. So I was wondering where I could find the download for v9.1 for 1.7.10. Please include Mekanism Generators and Mekanism Tools along with Mekanism Core when you provide links.

A sidenote: I feel like you should have a  organised download page containing all versions of your 
                   work. It would be helpful for people wanting to move to a specific version for reasons.

Thanks in advance!

**Comment by thiakil** [comment]
Where _did_ you look?

https://www.curseforge.com/minecraft/mc-mods/mekanism-generators/files/all?filter-game-version=2020709689%3A4449
https://aidancbrady.com/mekanism/download/

Both have the 1.7.10 versions
