### ISSUE TITLE
Digital Miner Filter issue

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5729]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!* Checked

#### Issue description:
The Tag and ID mod filters don't work
ItemStack works

#### Steps to reproduce:
1. Place a digital miner next to my home
2. plug elec cable on its left
3. go to config
4. New Filter > Tag > ore* > check > save > start
5. Or New Filter > Mod ID > 15 (iron_ore) >check > save > start

#### Version (make sure you are on the latest version before reporting):
**Forge: 30.30
**Mekanism: 9.9.0.391 
**Other relevant version: MC 1.15.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Fixed in 9.9.1
