### ISSUE TITLE
Digital miner replace button not working

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5730]
#### Issue description:
Using "Require replace" button is not working also using : and / characters in filters can't be typed.

#### Steps to reproduce:
After pressing "Require replace" button still says it's not active

#### Version (make sure you are on the latest version before reporting):
**Forge: 30.0.30
**Mekanism: 1.15.1-9.9.0.391

**Comment by pupnewfster** [comment]
Fixed in 9.9.1
