### ISSUE TITLE
Crusher cannot turn Melon Slices into Bio Fuel

### ISSUE THREAD

**Issue by TepperPepper** [mekanism/Mekanism#5731]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Pretty much what the title says. Most organic items can be turned into Bio Fuel via the Crusher (wheat seeds, carrots, rotten flesh, ect.) but Melon Slices cannot.

#### Steps to reproduce:
1. Place down a crusher
2. Hook it up with power
3. Attempt to insert Melon Slices into the crusher.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.35
**Mekanism:** 9.9.0.391
**Other relevant version:** Minecraft 1.15.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Added in 9.9.1
