### ISSUE TITLE
Silk touch on digital miner not working

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5732]
#### Issue description:
Using silk touch button says it enables silk touch but digital miner still mines ores without silk touch.

#### Steps to reproduce:
1. Press silk touch button
2. Start mining
3. Digital miner still doesn't silk touch

#### Version (make sure you are on the latest version before reporting):
**Forge: 30.0.30
**Mekanism: 1.15.1-9.9.0.391

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
