### ISSUE TITLE
jetpack impossible to fill

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5734]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!* Checked

#### Issue description:
jetpack is impossible to fill

#### Steps to reproduce:
1.Craft a jetpack (armoured or not)
2.Place into electrolic sperator
3.Or in gaz tank with hydrogen
4.No gaz is going into the jetpack :'(

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.35
**Mekanism:** 9.9.1
**Other relevant version:** mc 1.15.1

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
