### ISSUE TITLE
Gas tanks lose their containers when they're broken.

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5735]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!* Checked

#### Issue description:
Gas tanks lose their containers when they're broken.

#### Steps to reproduce:
1.Fill a gas tank (with electrolytic separator for example) (no matter wich level of tank)
2.Take back in your inventory the gas tank (with atomic disassembler for ex.)
3.Place the gas tank
4.The gas tank is emptied :'(

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.35
**Mekanism:** 9.9.1
**Other relevant version:** mc 1.15.1

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2

**Comment by SimonLyke** [comment]
not fixed in all the mods 8 version 1.0.13 ( not sure what mod version it is ) i broke using tertium pickaxe that has the AOE augment on it, but held shift to break only the 1 block. i believe when the augment is present the contents of the mekanism chemical tank loses its contents.

**Comment by pupnewfster** [comment]
Does it happen with other picks? If not best guess by far is that that pickaxe is doing something weird for how it breaks blocks and not calling all the methods it is supposed to.

**Comment by SimonLyke** [comment]
no, doesnt happen when i take the augment off.  so its 100% the use of the augment, not sure if theres anything to do about it on your side. probably something i should raise on mystical agriculture side instead. just thought id let you know.

**Comment by pupnewfster** [comment]
Yeah thanks for letting us know, but if it doesn't happen with it off then it definitely isn't something on our side and most likely is them not calling all the proper methods when breaking a block for their "aoe" breaking (as I am guessing even with the single block target thing they probably are just using their "aoe" logic in general)
