### ISSUE TITLE
Sawmill factory GUI bug

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5736]
#### Issue description:
Sawmill factory hotbar slots are out of the GUI

#### Version (make sure you are on the latest version before reporting):
**Forge: 30.0.35
**Mekanism: 9.9.1.392

![image](https://user-images.githubusercontent.com/25459732/72075608-08d3f280-32ec-11ea-9d26-ae4fed01de6d.png)

**Comment by pupnewfster** [comment]
Closing as 9.9.11 is now released and on curseforge.
