### ISSUE TITLE
Placing energy cube in the formulaic assemblicator crashes the game

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5738]
#### Issue description:
Placing charged energy cube in the slot for charging formulaic assemblicator to charge it crashes the game. (only happens if Formulaic Assemblicator needs to be charged)

#### Steps to reproduce:
1. Place charged energy cube in the slot for charging
2. Game crashes

#### Version (make sure you are on the latest version before reporting):
**Forge: 30.0.35
**Mekanism: 9.9.1.392

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/YZNy6h7a

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
