### ISSUE TITLE
Formulaic Assemblicator items dissapearing 

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5740]
#### Issue description:
Placing items in the Formulaic Assemblicator makes item dissapear

#### Steps to reproduce:
1. Place items in the Assemblicator
2. Try to remove items from the Assemblicator
3. Items Dissapear

#### Version (make sure you are on the latest version before reporting):
**Forge: ** 30.0.35
**Mekanism:** 9.9.1.392

![ezgif com-gif-maker](https://user-images.githubusercontent.com/25459732/72083748-3aec5100-32fa-11ea-8162-86cb4147e5ba.gif)

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
