### ISSUE TITLE
Electric pump doesn't remove source block

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5742]
#### Issue description:
Electric pump pumps liquid (water/lava) but it doesn't remove the source block.

#### Steps to reproduce:
1. Placing pump above source blocks
2. Start pumping 
3. Source blocks still in the world

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.35
**Mekanism:** 9.9.1.392

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2

**Comment by Radon-212** [comment]
why
:(
