### ISSUE TITLE
Recipes do not transfer data about stored contents

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5743]
#### Issue description:
Losing the items insisde the factory when you upgrade the factory

#### Steps to reproduce:
1.Place items into a factory
2.Take the factory into your inventory (without take back the items)
3.Use this factory to upgrade it (like base to advanced)
4.Place the advanced factory
5.The factory is empty... Items are lost into the nebulus :o

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.35
**Mekanism:** 9.9.1
**Other relevant version:** mc 1.15.1

**Comment by pupnewfster** [comment]
Moving this to 9.9.4, as before I can do this I still need to finish transferring the main modules recipes to data generators, and am not going to delay the release of 9.9.3 until I feel like working on that.

**Comment by term2112** [comment]
So I believe something about upgrading it in this way is causing the contents to be lost similar to how the power cube lost its energy contents before it was patched. Not sure how the process of upgrading the factory causes the contents to be lost, the code needs to find a way to transfer the contents of the previous form into the new form. The new factory counts as a new lock separate from the previous.

**Comment by pupnewfster** [comment]
...? Not sure what you are talking about given the code for transferring the stored contents etc via recipes isn't even complete yet, I got it mostly working (excluding the inventory contents) yesterday (but that isn't even in a released build yet). In the meantime if you don't want to empty your factories etc I would just recommend using the tier installers on the block that is placed, as that does properly keep everything intact.

**Comment by term2112** [comment]
Do you actually have to rewrite the entire mod? I thought you guys were able to recycle some of the old code from the 1.12.2 version in this. I do understand that all the block ids were changed when transitioning to version 1.13+.

**Comment by pupnewfster** [comment]
There are various parts of the mod that are not fully ported yet (the recipe data transferring being one of them), but there are also a lot of things that I am working on rewriting/cleaning up so that they are more efficient and easier to maintain, as there is a lot of legacy code in Mekanism that has been around for a very long time just being ported from one version to the next when there may be better ways to use newer things in forge/vanilla to perform the same task.

**Comment by pupnewfster** [comment]
Moved the milestone to 9.9.8 but may end up just removing a specified milestone from this at some point. 9.9.7 is up and on curseforge now and it should have recipe data mostly transferring (except for inventories themselves, energy and fluids and the like do work properly)

**Comment by Darkere** [comment]
Factories, in comparison to other recipes with stored contents, still have a tag even if the factory does not have a configuration. 
![image](https://user-images.githubusercontent.com/4283717/76869260-5595f580-6868-11ea-8859-03f2627eee51.png)

For purposes of auto crafting this should also not have a tag.
