### ISSUE TITLE
Ethylene recipe bug

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5745]
#### Issue description:
Recipe for ethylene requires 2 substrate to make 1 substrate instead of 2 bio fuel to make 1 substrate. 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.35
**Mekanism:** 9.9.1.392

![image](https://user-images.githubusercontent.com/25459732/72158888-24ee9700-33b3-11ea-845c-23928e3d98fb.png)

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
