### ISSUE TITLE
Can't shift-click upgrades into the Digital Miner

### ISSUE THREAD

**Issue by Discomanco** [mekanism/Mekanism#5746]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
You can't shift-right click upgrades into the Digital Miner, apart from the "brain" block (mid-bottom)

#### Steps to reproduce:
1. Place Digital Miner
2. Try to Shift-Right Click upgrades on it (yes works on the Brain block)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.35
**Mekanism:** 9.9.1.392
**Other relevant version:**

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
