### ISSUE TITLE
[1.15.1] Bounding box of Digital Miner cuts FPS in ~half

### ISSUE THREAD

**Issue by Discomanco** [mekanism/Mekanism#5747]
#### Issue description:
When the bounding/target box is up on the Digital Miner, FPS seems to be cut in half. Yes in half, and not just down by a lot. Experiment done in clean client
FPS, VSync off, targeting other block: 112-118
![2020-01-10_19 09 03](https://user-images.githubusercontent.com/4707702/72175703-0ef5cc00-33dd-11ea-9278-4cbee7ff3d18.png)

FPS, VSync off, targeting the DM: 49-59
![2020-01-10_19 12 43](https://user-images.githubusercontent.com/4707702/72175761-32b91200-33dd-11ea-83cb-4748010c4408.png)

FPS, VSync on, targeting other block: stable 60 ( pleb monitor ;) )
![2020-01-10_19 07 07](https://user-images.githubusercontent.com/4707702/72175799-567c5800-33dd-11ea-874a-23c255701bbc.png)

FPS, VSync on, targeting the DM: 29-39
![2020-01-10_19 15 33](https://user-images.githubusercontent.com/4707702/72175912-980d0300-33dd-11ea-8dd0-386f7cd67b8b.png)

#### Steps to reproduce:
1. Put down Digital Miner
2. Look at it, take note of FPS
3. Look away from it, take note of FPS

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** 9.9.1.392
**Other relevant version:** JEI 6.0.0.1

**Comment by Redstylt** [comment]
I got the same :/
I'm around 80-90 FPS usually but when i'm looking the digital miner i'm more around 60FPS

**Comment by aidancbrady** [comment]
@pupnewfster probably because we're rendering ~70 voxels lol
