### ISSUE TITLE
Digital Miner not dropping when breaking with Atomic Disassembler in extended vein mining mode

### ISSUE THREAD

**Issue by PanSzelescik** [mekanism/Mekanism#5752]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Digital Miner not dropping when breaking with Atomic Disassembler in extended vein mining mode

#### Steps to reproduce:
1. Place Digital Miner
2. Change mode in Atomic Disassembler to extended vein mining
3. Break Digital Miner

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2847 
**Mekanism:** 9.8.3.390
**Pack:** The 1.12.2 Pack v. 1.0.2

**Comment by pupnewfster** [comment]
Closing this as it is fixed in 9.9.9 (MC 1.15), which is now released and on curseforge.
