### ISSUE TITLE
Personal Chest when used as a bag has bad UI

### ISSUE THREAD

**Issue by Discomanco** [mekanism/Mekanism#5753]
#### Issue description:
Something's not quite right
![image](https://user-images.githubusercontent.com/4707702/72192106-bafedd80-3404-11ea-9341-eb664bc52651.png)
Also tested in dedicated client, with same result

#### Steps to reproduce:
1. Open a Personal Chest as a bag

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** 9.9.1
**Other relevant version:**

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
