### ISSUE TITLE
Render Issue

### ISSUE THREAD

**Issue by ppoozl** [mekanism/Mekanism#5754]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Render error
![image](https://user-images.githubusercontent.com/7188938/72199185-6ba3c600-3473-11ea-905e-76adedc324b4.png)
![image](https://user-images.githubusercontent.com/7188938/72199186-70687a00-3473-11ea-9258-da90780351c6.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:30.0.36 
**Mekanism:9.9.1.392
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by ppoozl** [comment]
Machines are actually working

**Comment by pupnewfster** [comment]
Please give the proper mekanism version, 392 isn't all that helpful as it requires us to lookup what 9.x.x it actually goes with, and is not a version we set. Also does it get fixed if you place and break the cables again, and do you have any other mods that mess with rendering such as optifine?

**Comment by ppoozl** [comment]
updated.
And client log reported 
[Render thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Client
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by pupnewfster** [comment]
Can you give more of the client log such as uploading it to pastebin/gist so that we can see the full error?

**Comment by ppoozl** [comment]
https://paste.ee/p/m5vu9

**Comment by ppoozl** [comment]
Server side Error log:
12.01 11:18:51 [Server] INFO java.lang.ArrayIndexOutOfBoundsException: 174063615
12.01 11:18:51 [Server] net.minecraft.network.PacketBuffer.func_179257_a(PacketBuffer.java:161) ~[?:? {re:classloading,pl:runtimedistcleaner:A}
12.01 11:18:51 [Server] mekanism.common.network.PacketSecurityMode.decode(PacketSecurityMode.java:73) ~[?:? {re:classloading}
12.01 11:18:51 [Server] net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$0(IndexedMessageCodec.java:116) ~[?:? {re:classloading}
12.01 11:18:51 [Server] java.util.Optional.map(Unknown Source) ~[?:1.8.0_231 {}
12.01 11:18:51 [Server] net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:116) ~[?:? {re:classloading}
12.01 11:18:51 [Server] net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:157) ~[?:? {re:classloading}
12.01 11:18:51 [Server] net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:79) ~[?:? {re:classloading}
12.01 11:18:51 [Server] net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:? {}
12.01 11:18:51 [Server] net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:? {}
12.01 11:18:51 [Server] net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:? {}
12.01 11:18:51 [Server] net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:84) ~[?:? {re:classloading}
12.01 11:18:51 [Server] net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$0(NetworkHooks.java:74) ~[?:? {re:classloading}
12.01 11:18:51 [Server] java.util.Optional.map(Unknown Source) ~[?:1.8.0_231 {}
12.01 11:18:51 [Server] net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:74) ~[?:? {re:classloading}
12.01 11:18:51 [Server] net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:1279) ~[?:? {re:classloading,pl:accesstransformer:B}
12.01 11:18:51 [Server] net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:42) ~[?:? {re:classloading,pl:runtimedistcleaner:A}
12.01 11:18:51 [Server] net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:12) ~[?:? {re:classloading,pl:runtimedistcleaner:A}
12.01 11:18:51 [Server] net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:? {re:classloading}
12.01 11:18:51 [Server] net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:? {re:classloading}
12.01 11:18:51 [Server] net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:? {re:classloading,pl:accesstransformer:B}
12.01 11:18:51 [Server] net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:? {re:classloading}
12.01 11:18:51 [Server] net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:? {re:classloading,pl:accesstransformer:B}
12.01 11:18:51 [Server] net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:711) [?:? {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
12.01 11:18:51 [Server] net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:705) [?:? {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
12.01 11:18:51 [Server] net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:? {re:classloading,pl:accesstransformer:B}

**Comment by pupnewfster** [comment]
I released 9.9.2 and I believe it fixes this issue, so once you update you should verify if this is fixed, and either close this issue/say if it is fixed or not.

**Comment by ppoozl** [comment]
I will continue testing. If It's not working, I will reopen this issue
