### ISSUE TITLE
Baby Skeletons nerf

### ISSUE THREAD

**Issue by Robball14** [mekanism/Mekanism#5755]
**Describe the the feature you'd like**
Baby Skeletons nerf
**Describe alternatives you've considered**
Need a Speed Nerf and a Spawn Rate Nerf

**Additional context**
Baby skeletons shoot as they were 2 blocks tall

**Comment by Redstylt** [comment]
Please could you fix it for 9.9.3 ? it's so buffed !

**Comment by pupnewfster** [comment]
No idea when I will fix/look into it, and given they can be disabled from spawning it is not super high priority to me currently. The main thing that needs to be fixed is that they are shooting as if they are two blocks tall, in regards to the speed/spawn rate, that requires looking more into how it was in 1.12 to see if something actually changed.

**Comment by Amcro** [comment]
They also spawn in the nether. Maybe adding spawn rate in the config file might help solving part of the issue

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge. The spawn config stuff I moved to its own issue #5779
