### ISSUE TITLE
Mekanism not working on server - 1.15.1 -no block tick updates 

### ISSUE THREAD

**Issue by Aperson95** [mekanism/Mekanism#5756]
mod versions 
http://prntscr.com/qmfqq4

for example if i put a bucket of lava in a tank if does not update live. if i break and replace the tank it show lava in it. if a add a lava bucket to the generator it dose not gen any power. if u break a replace it show some power in it.

could not get past making steel to test more. 

Sorry if this is bad

**Comment by Discomanco** [comment]
Been testing it.
Enigmatica 5, as a local host has this bug.
A dedicated server/client with only JEI+Mek does not have this issue

**Comment by Discomanco** [comment]
Replication steps has been found, for Enig5 and ATM5. Has to be some mod conflict, which I will look for later. For now, the steps:

- Close client and server
- Delete usercache.json and usernamecache.json from the server folder
- Start server and client
- Test if you can put lava in a tank (answer should be No). The 2 json files should be recreated now
- Close server and client
- Restart server and client
- Test if you can put lava in a new tank (answer should be Yes)

**Comment by pupnewfster** [comment]
I released 9.9.2 and I believe it fixes this issue, so once you update you should verify if this is fixed, and either close this issue/say if it is fixed or not.
