### ISSUE TITLE
Personal Chest contents erased when placed/picked up

### ISSUE THREAD

**Issue by Discomanco** [mekanism/Mekanism#5757]
#### Issue description:
If you place, or pick up the Personal Chest, it will lose all its contents

#### Steps to reproduce:
1. Put stuff in the Personal Chest
2. Place it or Pick it up
3. Everything you placed is gone

Tested in dedicated client

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** 9.9.1
**Other relevant version:**

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
