### ISSUE TITLE
Right clicking with an empty bucket on a tank doesn't take from tank

### ISSUE THREAD

**Issue by Discomanco** [mekanism/Mekanism#5759]
#### Issue description:
Rightclicking a tank with a full bucket, will insert the fluid as expected.
Rightclicking a tank with an empty bucket, opens the GUI, instead of taking the fluid, as expected.

#### Steps to reproduce:
1. Put liquid in a tank
2. Try to take it out with an empty bucket
3. Do it through the GUI instead, cuz meh?

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** 9.9.1
**Other relevant version:**

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
