### ISSUE TITLE
Be able to choose the output of the product for the electrolytic separator

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5760]
**Describe the the feature you'd like**
It would be nice if for the electrolytic separator you could choose which product goes out on the left and which product goes out on the right.
This will allow for much better arrangement in the plants
Here is an example of a very bad arrangement because I have no choice :
https://imgur.com/a/7vFVeB0

**Comment by pupnewfster** [comment]
You could always rotate the electrolytic separator by 180 degrees given I think it actually lets you put in liquid on any side. (Unless I fixed it so it properly only accepts liquid from the front)

**Comment by Discomanco** [comment]
but the aesthetics!

**Comment by aidancbrady** [comment]
Chemical machines (including Rotary Condensentrator + Chemical Infuser) are intended to have physically-bounded gas/fluid slots. I think we'll be leaving this the same.
