### ISSUE TITLE
Purification factory losing the progress of recipe when the gas is missing

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5764]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
purification factory losing the progress of recipe when the gas is missing

#### Steps to reproduce:
1.Start a recipe like ore process with oxygen
2.Stop to provide the machine with oxygen
3.When it's out of oxygen, the recipe will lost its progression
4.Put back the oxygen
5.Recipe takes more oxygen than the provide
6.Missing oxygen -> losing recipe -> Back to step 3
7. Infinite loop 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.35
**Mekanism:** 9.9.1
**Other relevant version:**

**Comment by pupnewfster** [comment]
Fixed with the release of 9.9.2
