### ISSUE TITLE
Ultimate Tank doesn't show liquid in it with just 1 bucket

### ISSUE THREAD

**Issue by Discomanco** [mekanism/Mekanism#5766]
#### Issue description:
If the Ultimate Tank only has 1 bucket of liquid in it, it wont show in the tank.
It does show once you have 2 buckets in though, and will keep showing if you drain it back down to 1 button. Empty it, and put 1 bucket back in, it will show the liquid. So only applies for newly placed tanks.

#### Steps to reproduce:
1. Place Ultimate Tank
2. Put 1 bucket of liquid in it, no visual indication
3. Put a 2nd bucket in, it now shows its contents

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** 9.9.1
**Other relevant version:**

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
