### ISSUE TITLE
Energy cubes empty after breaking

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5768]
#### Issue description:
Energy cubes don't keep energy after breaking.

#### Steps to reproduce:
1. Place and charge energy cube
2. Break energy cube
3. Place it back down

#### Version (make sure you are on the latest version before reporting):
**Forge:**  30.0.36
**Mekanism:** 9.9.2

**Comment by pupnewfster** [comment]
Turns out the item and block have a different NBT tag name wise for keeping track of energy. At some point I probably will unify the tag they use, but for now I am just going to make sure it copies it to the correct tag.

**Comment by term2112** [comment]
I couldn't wait for 9.9.3 so I replaced the files in the .jar, and it actually worked. Never really have thing like this work for me. I used winrar to open the .jar file.

**Comment by pupnewfster** [comment]
> I couldn't wait for 9.9.3 so I replaced the files in the .jar, and it actually worked. Never really have thing like this work for me. I used winrar to open the .jar file.

You don't even have to replace the files in the jar you can just make a new [data pack](https://minecraft.gamepedia.com/Data_pack) that overrides those specific files.

**Comment by term2112** [comment]
I guess I can try this out, im a little new to how these file systems work

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
