### ISSUE TITLE
Formulaic Assemblicator crashing game when crafting

### ISSUE THREAD

**Issue by Amcro** [mekanism/Mekanism#5769]
#### Issue description:
Formulaic Assemblicator crashes game when it is crafting recipe

#### Steps to reproduce:
1. Add recipe in Assemblicator
2. Encode formula
3. Turn Auto Mode on

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** 9.9.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/Mi4Rs3dE

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
