### ISSUE TITLE
Free runners doesn't prevent fall damage

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5770]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Free runners doesn't prevent fall damage but they do ascend 1-block inclines automatically (wich is useless now because minecraft does it

#### Steps to reproduce:
1.wear
2.turn on
3.jump from your roof and die

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** 9.9.2
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
