### ISSUE TITLE
Impossible to turn on the fire on the electric bow & no animation

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5771]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
~~Impossible to turn on the fire~~ on the electric bow by press N by default

#### Steps to reproduce:
1. Make an electric bow
2. Charge it
3. Take arrow in your inventory
4. Press n  = "item mode switch key" **(Update : to turn on : crouch + n)**
5. Nothing happened
6. And when you shoot the arrow isn't loading on the bow

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** 9.9.2
**Other relevant version:**

**Comment by Redstylt** [comment]
My bad to turn on the fire mode it was crouch+N
But the animation still not working ;)

**Comment by pupnewfster** [comment]
Closing this as the fire mode is working, and the animation request is covered by #5523
