### ISSUE TITLE
[1.15.1] Cardboard Box doesn't store the block it was placed on

### ISSUE THREAD

**Issue by Revvilo** [mekanism/Mekanism#5772]
#### Issue description:
Placing a cardboard box on a block simply replaces the block and doesn't store it.

#### Steps to reproduce:
1. Place cardboard box on a block
2. Attempt to pull off the box again (doesn't work)
3. Break the box
3. Box contains no data

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.36
**Mekanism:** 9.9.2.393

(Log not relevant)

**Comment by pupnewfster** [comment]
Thank you for making an issue, given it is good to have it be more known about this, but personally this is low on my priority list. To be honest I was initially unsure if placing a cardboard box would just straight up cause a crash given I never bothered testing it, but I did know that it would not work.

**Comment by Revvilo** [comment]
Absolutely. I understand the entire mod is in the process of updating and there are many more significant features that need attention. Just chucking this here to keep track of it :)

**Comment by pupnewfster** [comment]
Closing this as 9.9.8 is now released and on curseforge, I believe it should work properly now, though I would use some caution when initially testing it as I only did minor testing. The blacklist also has now been moved to a config option for blacklisted mods, and to a block tag `mekanism:cardboard_blacklist` for blacklisting blocks from the cardboard box.
