### ISSUE TITLE
Server try to load clientside class

### ISSUE THREAD

**Issue by ppoozl** [mekanism/Mekanism#5774]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
server try to load clientclass and crashed

#### Steps to reproduce:
do not know

#### Version (make sure you are on the latest version before reporting):
**Forge:30.0.36
**Mekanism:9.9.2.393
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]
[crash-2020-01-14_20.52.43-server.txt](https://github.com/mekanism/Mekanism/files/4059215/crash-2020-01-14_20.52.43-server.txt)

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
