### ISSUE TITLE
[1.15.1] digital miner filters "tag" and "mod id" not working

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5775]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. create a digital miner with a power source
2. use tag filters "oreIron" or *ore
3. image does not appear after check, saving the filter is still possible
4. starting miner does not mine the ores.

#### Version (make sure you are on the latest version before reporting):
**Forge:30.0.36** 
**Mekanism:9.9.2** 

Another thing that I have noticed is that the miner loses its energy buffer similar to the energy cube issue in #5768. Strangely enough, standing on a charge pad with the empty buffer will actually recharge the miner.
![image](https://user-images.githubusercontent.com/41069911/72379552-ae6ad580-36e1-11ea-970a-eeb01e2ea015.png)
![image](https://user-images.githubusercontent.com/41069911/72379622-cb070d80-36e1-11ea-9210-292499895808.png)
![image](https://user-images.githubusercontent.com/41069911/72379680-e70aaf00-36e1-11ea-8931-d52cdb976879.png)

**Comment by Yoosk** [comment]
Those are not even valid tags for 1.15 what you tried.

**Comment by term2112** [comment]
Im an idiot, I did not realize they were changed, I used to be able to use oreIron in an older version, thanks for the help.

**Comment by Discomanco** [comment]
You are correct that you used to do `oreIron` :)
OreDicts changed into Tags with 1.14

**Comment by Redstylt** [comment]
How do you do to see the tag in your JEI ?

**Comment by Yoosk** [comment]
f3+h but i have kiwi installed

**Comment by Korach** [comment]
kiwi? What's that?

**Comment by Cyinthia** [comment]
You cant see tags via JEI atm its broken, wandering if anyone has an external lookup for this stuff.

> How do you do to see the tag in your JEI ?

**Comment by Kithid** [comment]
In terms of tag for a specific material, this seems to work.

http://prntscr.com/y5nyta
http://prntscr.com/y5o21f
