### ISSUE TITLE
1.15 Electrolytic Separatorsound not fading out in distance

### ISSUE THREAD

**Issue by mhoppi** [mekanism/Mekanism#5776]
### Issue description:
When the Electrolytic Separator is running the sound stay audible even in distance and does NOT get quieter.

#### Steps to reproduce:
1. Place Electrolytic Separator
2. Give it Water to run
3. Move away from block and notice that volume stays constant

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.1-forge-30.0.39
**Mekanism:** Mekanism-1.15.1-9.9.2.393

**Comment by term2112** [comment]
I have noticed this too when I go underground to mine at level 11

**Comment by pupnewfster** [comment]
Is it just the electrolytic separator or does it happen with all machines?

**Comment by mhoppi** [comment]
Thanks pupnewfster for your quick fix.
I dont know where to write this but I am extremely grateful for your mod.
Its a lot of fun and to have something like this for free is incredible. Many many thanks for maintaining this project!

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
