### ISSUE TITLE
Alloys upgrading cables glitch at 3-way intersections

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5780]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
![image](https://user-images.githubusercontent.com/41069911/72571914-f2e7a400-388e-11ea-9c79-5c0cb0c07ebb.png)
#### Steps to reproduce:
1. Build a cable system with a 3-way intersection
2. attempt to upgrade with alloys
3. the upgrades will only go in one direction and consumes all your alloys without upgrading anything

#### Version (make sure you are on the latest version before reporting):
**Forge:30.0.36** 
**Mekanism:9.9.2** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Are you sure it did not upgrade them? Looking at your image it seems to have gone down and to the right. I do agree the code for figuring out which pieces to upgrade is not the best when lots of cables are nearby but each alloy only upgrades 8 cables, so is it possible it upgraded all it could?

**Comment by term2112** [comment]
Yes, I the cable did not run that far underground and it did end up reaching the machine it was connected too, I believe the code was seeing that there were non upgraded cables in the system and did not know how to upgrade them, it consumed 15 alloys trying to upgrade those last 2 sections.

**Comment by pupnewfster** [comment]
I briefly tried to replicate this but was unable to. Is this on a server/are you able to reproduce it with another set of cables or is it potentially some fluke occurrence?

**Comment by term2112** [comment]
![image](https://user-images.githubusercontent.com/41069911/72683278-eb4d1880-3aa3-11ea-8b33-3ad65525d6b0.png)
![image](https://user-images.githubusercontent.com/41069911/72683289-091a7d80-3aa4-11ea-8a5e-19aecd62c90c.png)
![image](https://user-images.githubusercontent.com/41069911/72683301-23ecf200-3aa4-11ea-9309-32a240eee691.png)
![image](https://user-images.githubusercontent.com/41069911/72683316-57c81780-3aa4-11ea-8105-eb6bdde1c3f8.png)
![image](https://user-images.githubusercontent.com/41069911/72683334-80e8a800-3aa4-11ea-92b0-137124b7b7f8.png)

As I keep upgrading from the piece connected to the power cube, they get stuck at those points

I can however go to those un-upgraded sections and upgrade them
![image](https://user-images.githubusercontent.com/41069911/72683399-079d8500-3aa5-11ea-8d25-3ebb6d8227f3.png)

**Comment by pupnewfster** [comment]
So you keep on right clicking the same cable and that makes the upgrades keep disappearing?

**Comment by term2112** [comment]
yes

**Comment by pupnewfster** [comment]
Ok, so there are a few things going on then. The bug is that you *can* use an alloy on a transmitter when it won't directly upgrade it. Which I actually am now able to reproduce. The other thing is the enhancement request of being able to just click the same transmitter and have it propagate the entire network, which I will look into as well as that isn't something that should be that hard to do.

**Comment by pupnewfster** [comment]
Managed to figure it out, and get it so they propagate down the line.

**Comment by term2112** [comment]
Thanks for the fix, It looks like all that needs to be done now if to upload version 9.9.3 on the website from what it looks like to me.

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
