### ISSUE TITLE
Teleporter not working in 1.15.1

### ISSUE THREAD

**Issue by mhoppi** [mekanism/Mekanism#5783]
### Issue description:
No teleport frequencies are shown in the portable teleporter. Thus making it unusable.

#### Steps to reproduce:
1. Place Teleport Block and power it, give it a name for example "Test1"
2. Give player a portable teleporter and charge it. 
3. List in portable teleporter stays empty so you can not use it to teleport anywhere :(

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.1-forge-30.0.39
**Mekanism:** Mekanism-1.15.1-9.9.2.393

**Comment by thiakil** [comment]
This was fixed, ready for next alpha :)
https://github.com/mekanism/Mekanism/commit/acb8905cf65ab71f1fefb5e45920cba601965355

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
