### ISSUE TITLE
Inductin Matrix - Negative Power - Wireless Crafting Terminal

### ISSUE THREAD

**Issue by Defman** [mekanism/Mekanism#5785]
Help wanted and sorry if this is the wrong place to ask.

Hello, I have found a bug between **WirlessCraftingTerminal** and **Mekanism** and I don't know how to proceed. The best thing would for me to find the source of the bug and come up with a solution and submit a pull request. However I have no idea how different mods communicate and coordinate power transfers, my first thought was some common NBT tags that were agreed upon for the different kinds of power, I have been unable to find any source that supports that theory. So here it goes.

The **wireless crafting terminal** from *WirelessCraftingTerminal* works as an infinite source of power when inserted into an **Induction Matrix** from *Mekanism*. I have been trying to locate the root of the problem and narrowed it down to either the **AE2BasePoweredItem** or Mekanism Induction Matrix. For what I can gather the **[ItemWCT](https://github.com/p455w0rd/WirelessCraftingTerminal/blob/master/src/main/java/p455w0rd/wct/items/ItemWCT.java)** from **WirelessCraftingTerminal** which is the wireless crafting terminal itself extends from **[ItemWT](https://github.com/p455w0rd/AE2WirelessTerminalLibrary/blob/master/src/main/java/p455w0rd/ae2wtlib/api/item/ItemWT.java)** from **ae2wtlib** which extends from **[AEBasePoweredItem](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/items/tools/powered/powersink/AEBasePoweredItem.java)** from **AppliedEnergistics**.
The **[AEBasePoweredItem](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/items/tools/powered/powersink/AEBasePoweredItem.java)** stores the current internal power at nbt: *internalCurrentPower* and internal max power at nbt: *internalMaxPower* on the item itself as two doubles. The weird thing is that the terminal itself displays the power as being Int.MIN_VALUE (-2^31) and which is not the same as Double.MIN_VALUE. Furthermore the **[AEBasePoweredItem](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/items/tools/powered/powersink/AEBasePoweredItem.java)** contains a [safety guard](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/d5fc7a5b21b5318e6cd9d42cf20afa0890a544bc/src/main/java/appeng/items/tools/powered/powersink/AEBasePoweredItem.java#L138) for negative power.

I would love a pointer in the right direction to find the source of the problem and being able to fix it and submit a pull request. I have no clue whether its a bug in Mekanism, AppliedEnergistics or WirelessCraftingTerminals and so far

**Comment by pupnewfster** [comment]
Unsure, I looked briefly to partially refresh myself on how the code worked in 1.12 for charging items and I believe that it is charging the AE2 item [via forge energy.](https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/common/util/ChargeUtils.java#L96-L100) Which we [clamp](https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/common/integration/forgeenergy/ForgeEnergyIntegration.java#L25) to not send more than an int as that is all ForgeEnergy supports. So my guess is somehow in AE2 (or one of the addons that the item is in/uses), it is getting thrown off.

**Comment by pupnewfster** [comment]
Closing this, as it seems to be a multimod interaction, and we are only working on developing for the 1.15 version of MC currently, and we have rewritten various systems such as energy transfer in 1.15, and until the other mods update it is impossible to tell if this bug/interaction even still exists.
