### ISSUE TITLE
Crash placing configured Entangloporter

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#5787]
#### Issue description:
Client crashes. (server is fine) when placing an entangloporter with a configured frequency

#### Steps to reproduce:
1. Configure entangloporter to frequency
2. place it down.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-30.0.39
**Mekanism:** Mekanism-1.15.1-9.9.2.393.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/bd6B1FLq

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
