### ISSUE TITLE
Purification Factory does not accept gas upgrades

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5788]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description: In this example, the advanced purification factory will not accept gas upgrades.
![image](https://user-images.githubusercontent.com/41069911/72683095-48e06580-3aa2-11ea-90af-ae6c01342cfe.png)

#### Steps to reproduce:
1. Build a purification factory
2. Try to install some gas upgrades
3. They do not install

#### Version (make sure you are on the latest version before reporting):
**Forge:30.0.36** 
**Mekanism:9.9.2** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Fixed by https://github.com/mekanism/Mekanism/commit/3bf4854cb58237b14f1d7318614ee8cd51ed29ea

**Comment by pupnewfster** [comment]
Closing as 9.9.3 is now released and approved on curseforge.
