### ISSUE TITLE
Bio generator production showed broke

### ISSUE THREAD

**Issue by Redstylt** [mekanism/Mekanism#5791]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The bio generator doesn't show its production while is working

#### Steps to reproduce:
1.put a bio-generator
2.fill up with biomass
3.Look production
4. Show 0 J/T

#### Version (make sure you are on the latest version before reporting):
**Forge:** 30.0.41
**Mekanism:** 9.9.3
**Other relevant version:** 1.15.1

https://imgur.com/a/00lFr4I

**Comment by pupnewfster** [comment]
Closing as 9.9.4 is now released.
