### ISSUE TITLE
Configuration is not accessible through the forge mod menu

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5794]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I am not sure if this is an issue with forge itself still being in beta but all the mod configurations in the mod menu are grayed out. I do know how to change these configurations through the files themselves though although I find this to be kind of inconvenient at times. I believe that the mod creators are supposed to point forge to where the mod configuration files are to allow it to access them.

#### Steps to reproduce:
1. open mods menu at startup
2. open mechanism or any of its sub-mods
3. the configuration option is unavailable

#### Version (make sure you are on the latest version before reporting):
**Forge: 30.0.41** 
**Mekanism: 9.9.3** 

![image](https://user-images.githubusercontent.com/41069911/72756965-c092bb00-3b9c-11ea-8129-1331ac155bb3.png)

**Comment by pupnewfster** [comment]
The config gui has not been re-implemented in forge yet after forge was rewritten in 1.13/1.14. While it is possible to manually create all the GUI code and stuff and hook that up to the config button, I am not planning on dealing with it/trying to get the config gui working until after https://github.com/MinecraftForge/MinecraftForge/pull/6421 gets merged. At which time I will test to make sure our configs show/behave properly using it and that if anything needs a localization string + key that it has one.

**Comment by term2112** [comment]
I am not sure if this was recently re-implemented but I have noticed that a couple of my other mods re-implemented there settings in the mod menu. The 2 mods are xaeros minimap and worldmap.

**Comment by pupnewfster** [comment]
It hasn't been (https://github.com/MinecraftForge/MinecraftForge/pull/7395) and I still see no need to deal with creating our own set of GUIs when the config files work just fine, if not better in my opinion than a GUI based system.

**Comment by term2112** [comment]
I did not even realize that a mod even had an option to create its own GUI. It was my mistake thinking that this was fixed when noticing that this mod had the option available.
