### ISSUE TITLE
Lithium Dust (Mekanism-1.15.1-9.9.3.394.jar) 1.15.1

### ISSUE THREAD

**Issue by Millificent** [mekanism/Mekanism#5796]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Lithium dust is unable to be created in the above version for 1.15.1 server.
Method: "crystallizing the lithium(fluid) makes sulfur"

#### Steps to reproduce:
1. Tested in SSP
2. Tested in server

#### Version (make sure you are on the latest version before reporting):
**Forge:forge-30.0.41** 
**Mekanism:Mekanism-1.15.1-9.9.3.394.** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Seems I miss counted which dust it went with when I was flattening things, and didn't see it when I briefly double checked some of the recipes.

**Comment by Millificent** [comment]
Happens to the best of us :P - can i be safe to assume it will be fixed in the next update?

**Comment by pupnewfster** [comment]
Ya, was a rather simple fix, especially since I have been working on converting recipes to data generators, so given I already moved over the crystallizing recipes, it made it very easy to fix it. Though I wouldn't be surprised if there were other misc recipe bugs of things creating the wrong items or using the wrong inputs.

**Comment by Millificent** [comment]
We will keep an eye out and report as usual :)

**Comment by pupnewfster** [comment]
Closing as 9.9.4 is now released.
