### ISSUE TITLE
dynamic tank is not keeping it's contents saved

### ISSUE THREAD

**Issue by nukemen2012** [mekanism/Mekanism#5799]
when I save and quit and reopen the world my two dynamic tanks would be empty.

**Comment by pupnewfster** [comment]
Please don't just delete the format, especially when you aren't going to even bother providing all the information it asks for. What version of mekanism is this with and what version of minecraft

**Comment by xXDarkNovaXx** [comment]
You must to remove a Block from the Tank and place it then the Fluid is back
But you must to do this again and again when you restart the world


sry for Error i have use a translator

**Comment by aidancbrady** [comment]
Is this occurring in the 1.15 dev builds?

**Comment by xXDarkNovaXx** [comment]
i dont know
I do not have 1.15 installed
But what I forgot to say is that for me it does not concern both tanks but only one tank

My deuterium tank in my base is not affected by this problem only my tritium tank in the desert is affected
