### ISSUE TITLE
Digital Miner Range not accurate

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#5801]
### Issue description:
Digital miner only mines part of the area that is specified. 

![image](https://user-images.githubusercontent.com/4283717/73002924-0f428e00-3e05-11ea-931b-4c1f648bedf8.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:**  30.0.43
**Mekanism:** 9.9.3.394.

**Comment by Darkere** [comment]
![image](https://user-images.githubusercontent.com/4283717/73005186-d1dfff80-3e08-11ea-8207-952d5f950431.png)
![image](https://user-images.githubusercontent.com/4283717/73005191-d5738680-3e08-11ea-8de3-cb49d6f1858c.png)
Before and after starting the digital miner. One redstone block in each chunk

**Comment by Darkere** [comment]
Started by setting just inverse on and height to the level of the surface. 
Changing minheight to 0 and maxheight to 100 and changing the filter to ItemStack Redstone Block (and disabling inverted) did not yield any different results

**Comment by pupnewfster** [comment]
Closing as 9.9.5 is now approved and on curseforge.
