### ISSUE TITLE
Jetpack and Flamethrower sounds mute after a while

### ISSUE THREAD

**Issue by shouxd** [mekanism/Mekanism#5803]
#### Issue description:

Whenever I play, sounds on jetpack and flamethrower mute after some minutes

#### Steps to reproduce:
1. Join world, verify that jetpack and ft are making noises
2. Stop hearing noises from them
3. Realize they are not making noises 

#### Version (make sure you are on the latest version before reporting):
**forge-1.12.2-14.23.5.2847-universal:** 
**Mekanism-1.12.2-9.8.3.390** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/shouxd/395321175828fe865b41fc81a276fb1d ---- latest.log

**Comment by aidancbrady** [comment]
Tested for ~8 minutes straight using latest version, didn't notice the sounds stopping. Calling this fixed for 1.15.
