### ISSUE TITLE
Smelting Factory Issue

### ISSUE THREAD

**Issue by OrionSincoat** [mekanism/Mekanism#5806]
Copper Dust not been smelted by Advanced Smelting Factory (Elite OK)
Smelting Factory isn't showm in JEI (dunno if its here this one)

![Captura de tela 2020-01-23 23 25 20](https://user-images.githubusercontent.com/44932464/73040430-5e55e680-3e38-11ea-9829-b265998ec14c.png)
![Captura de tela 2020-01-23 23 25 21](https://user-images.githubusercontent.com/44932464/73040431-5e55e680-3e38-11ea-9e09-887e17fff721.png)
![Captura de tela 2020-01-23 23 25 24](https://user-images.githubusercontent.com/44932464/73040432-5eee7d00-3e38-11ea-9a45-871f879520c6.png)

**Comment by aidancbrady** [comment]
Can't reproduce in 1.15.
