### ISSUE TITLE
Digital Miner not mining all matching ores found

### ISSUE THREAD

**Issue by davo97** [mekanism/Mekanism#5807]
Scanning for ironOre, i press start and a number comes up (say 5000). 
After a couple of mines that number will drop to say 400, 
then 0. The digital miner says its finished but when i reset, run it i can see how many it was supposed to mine. It then updates back to 0 and finishes again.

**Comment by Yoosk** [comment]
Offtopic but have you heard about issue template?

**Comment by davo97** [comment]
ahh, sorry, i have not.. i can close and reopen with the template.. 

Sorry!

**Comment by davo97** [comment]
> Offtopic but have you heard about issue template?

Can you elaborate, issue template?

**Comment by pupnewfster** [comment]
No idea what version this is for but if it is for 1.15, this is probably the same as #5801

**Comment by davo97** [comment]
> No idea what version this is for but if it is for 1.15, this is probably the same as #5801

Mc version 1.12.2 
Pack: All the mods 3 remix version 1.5.3
