### ISSUE TITLE
1.15.2 crash on loading 

### ISSUE THREAD

**Issue by 5kedone** [mekanism/Mekanism#5808]
game goes into a boot loop red progress bar just reloads and reloads cant even tab out have to alt-f5 to quit the game i have attached the latest.log

this is with forge 31.0.1 and mekanism .395

https://pastebin.com/A0g3j0YS

**Comment by pupnewfster** [comment]
For now just use 31.0.0, this is fixed by this commit https://github.com/mekanism/Mekanism/commit/78354fb62979ad572815676f617b5dbba2226cd9 which I plan on making a 9.9.5 build later today that will include this fix.

**Comment by Dedriod** [comment]
I got the same problem, 
I'll put the log file in attatchment, I think it could be useful in some way...

[latest.log](https://github.com/mekanism/Mekanism/files/4110019/latest.log)

**Comment by Dedriod** [comment]
By the way, I'm not a programer, don't relly know much about it.... Could some one pass me the file that can solve the problem? 

Thanks a lot 😄

**Comment by pupnewfster** [comment]
Closing as 9.9.5 is now approved and on curseforge.
