### ISSUE TITLE
Pipe/cable recipies prodeces 1x instead of 8x pipes/tubed

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5811]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
as seen above

#### Steps to reproduce:
1. create any pipe or tube
2. only 1 is produced from material

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.0.1** 
**Mekanism: 9.9.5** 
**Other relevant version:** 

I am not sure if this is intentional or not but the recipes now only produce one of each pipe.

**Comment by term2112** [comment]
It also appears that the enrichment table is doubleing the dirty dust for whatever reason

**Comment by pupnewfster** [comment]
This is accidental, I have been working on cleaning up the maintaining of recipes, and obviously made some errors when converting them. If you find any other issues do let me know.

**Comment by DysonFabienSun** [comment]
What's more, ore doubling is screwed...
for the enrichment chamber, i think that dirty dusts and ores' recipes are swapped

**Comment by pupnewfster** [comment]
Yes I know that is what they already reported in the second comment of their post... Either overwrite the recipes using a datapack or wait until I release an update tomorrow

**Comment by pupnewfster** [comment]
Closing this as 9.9.6 is now release and on curseforge and fixes these recipes.
