### ISSUE TITLE
Cables texture missing

### ISSUE THREAD

**Issue by Robball14** [mekanism/Mekanism#5814]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Cables, tubes, conductors, pipes and transporters' textures sometimes disappear.

#### Steps to reproduce:
1. create a world and put any cable, tube, conductor, pipe or transporter
2. restart the game and join the world
3. texture has a chance to be missing

#### Version (make sure you are on the latest version before reporting):
**Forge:*31.0.0* 
**Mekanism:*9.9.4* 
**Other relevant version:*Minecraft 1.15.2* 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Could you please post your latest log I am wondering if it says something about the cause.
