### ISSUE TITLE
Enhancements to the electrolytic seperator

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5815]
This is an idea of how I would handle the electrolytic separator

*speed upgrades would remain the same and would equate the production speed being multiplied by (2^(speed upgrades)) so 8 speed upgrades would multiply the overall production 256 times.

*energy upgrades will work differently on the other hand, each upgrade will slightly increase the efficiency of the machine to near 100% and the energy capacity increase would remain the same

(energy used by separator: energy recovered from gas generator)
stock: 20% efficient
1 energy upgrade: 30% efficient
2 energy upgrades: 40% efficient
3 energy upgrades: 50% efficient
4 energy upgrades: 60% efficient
5 energy upgrades: 70% efficient
6 energy upgrades: 80% efficient
7 energy upgrades: 90% efficient
8 energy upgrades: 100% efficient

*if the gas being used by a machine is lower than the seperator's production rate, the separator would be able to slow down its own production and not stay on mainly to reduce stuttering on and off

**Comment by thiakil** [comment]
The separator is designed to prevent creating energy from nothing. 

It is intended to use as much energy to produce hydrogen as would be gained by burning it in a gas burning generator

**Comment by term2112** [comment]
I do know that this is the way it was originally designed but recently on one of my survival and testing, I recently installed all of the energy and speed upgrades and noticed it was producing massive amounts of power from nothing. I was not sure what was happening here. I had set to drain excess oxygen just to see what would happen.

**Comment by pupnewfster** [comment]
That issue was also fixed after you reported it.

**Comment by term2112** [comment]
Ok, I think I know what is going on here, the separator inst using power at all, I disconnected it from its power source and it is still running without losing anything in its buffer. It is also displaying that it isnt using any power.

**Comment by pupnewfster** [comment]
What version of mekanism are you on? That is the bug you had reported and I fixed in 9.9.4

**Comment by term2112** [comment]
9.9.6
forge 31.0.1

**Comment by term2112** [comment]
![image](https://user-images.githubusercontent.com/41069911/73129617-3d1b0480-3fb6-11ea-95c0-b8732a3d7c2b.png)

**Comment by pupnewfster** [comment]
I will look at it again tomorrow I guess, what upgrades do you have installed?

**Comment by term2112** [comment]
right now, nothing, but it doesn't matter what upgrades I have in it, I just noticed that when I had it hooked up to the gas gen with all the speed upgrades, the power production shot through the roof.

**Comment by pupnewfster** [comment]
Next version (not quite sure when the release will be yet), will have the electrolytic separator's energy usages working properly again.

Also one question about your suggestion for the energy usage of the separator, is your suggestion to make it so that you *only* get the energy back 1:1 iff you have max energy upgrades in it, and otherwise you end up losing some energy?

**Comment by term2112** [comment]
Yes, I know that this type of machine in real life isn't really efficient to begin with. That is why hydrogen fuel cell cars haven't really caught on and why we are seeing more battery powered varients such as Tesla.

I also thought that the initial efficiency may be too inneficiant for the starting tiers so the upgrades could actually upgrade at 5% increments. It could even end at 90% or 95% efficiency if you really want to be realistic.

**Comment by term2112** [comment]
The way I believe it is supposed to work is that the energy used by the separator is always proportional to the energy recovered by burning the hydrogen in a gas burning generator regardless of energy and speed upgrades.

**Comment by aidancbrady** [comment]
While I'd rather not add an efficiency aspect to the separator, I would consider adding such a mechanic to the Gas-Burning Generator. Efficiency upgrades would be an interesting way to add the upgrade mechanic to Mekanism's generators.
