### ISSUE TITLE
Chemical Dissolution Chamber only produce 1mB slurry per ore block

### ISSUE THREAD

**Issue by Apot98** [mekanism/Mekanism#5816]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Using Chemical Dissolution Chamber to process ore only produce 1mB slurry of corresponding ore type; also the name of slurry is abnormal: only have ore type as its name without "slurry" in it

#### Steps to reproduce:
1.Grab a Chemical Dissolution Chamber and any ore that it can process;
2.Process the ore into the slurry
3.Check the output slot

#### Version (make sure you are on the latest version before reporting):
**Forge:1.15.2-forge-31.0.1** 
**Mekanism:1.15.2-9.9.6.397** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

![2020-01-27_17 36 00](https://user-images.githubusercontent.com/20492252/73168311-8c873f00-4134-11ea-9f65-5009f16ea1a6.png)

**Comment by Apot98** [comment]
Had a check in source code and found the problem:
src/datagen/generated/mekanism/data/mekanism/recipes/processing/(type of ore)/slurry/dirty.json
e.g. copper slurry
{
  "type": "mekanism:dissolution",
  "itemInput": {
    "ingredient": {
      "tag": "forge:ores/copper"
    }
  },
  "gasInput": {
    "amount": 1,
    "gas": "mekanism:sulfuric_acid"
  },
  **"output": {
    "gas": "mekanism:dirty_copper_slurry",
    "amount": 1**
  }
}

**Comment by pupnewfster** [comment]
Closing this as it is fixed in 9.9.7 which is approved and on curseforge.
