### ISSUE TITLE
Flamethrower fire entity still don't hurt mobs

### ISSUE THREAD

**Issue by Apot98** [mekanism/Mekanism#5817]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
In version 1.15.2-9.9.6.397 flamethrower's fire entity properly smelt block in heat/inferno mode, and set fires in inferno mode, but still deals no damage to mobs.
![2020-01-27_21 29 58](https://user-images.githubusercontent.com/20492252/73179778-09bfad80-414f-11ea-9ca2-4a7904c9ce42.png)

#### Steps to reproduce:
1.Grab a flamethrower filled with hydrogen;
2.Set the flamethrower at combat mode;
3.Spit the flame at some innocent creature.

#### Version (make sure you are on the latest version before reporting):
**Forge:1.15.2-forge-31.0.1** 
**Mekanism:1.15.2-9.9.6.397** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Closing this as it is fixed in 9.9.7 which is approved and on curseforge.
