### ISSUE TITLE
1.15.1 Crashes on Load

### ISSUE THREAD

**Issue by krelios** [mekanism/Mekanism#5818]
## Issue description: 
Minecraft crashes on launch after the Forge startup but before the main menu 

#### Steps to reproduce:
1. Launch Minecraft 1.15.1 with the latest Forge and Mekanism 1.15.1 versions.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  30.0.51
**Mekanism:** 9.9.3.394
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/xhFArJSG

**Comment by Discomanco** [comment]
Mek for 1.15.1 only works with Forge 30.0.43.
If you want the newer versions of Mekanism, you need to move to 1.15.2
