### ISSUE TITLE
Question about block IDS

### ISSUE THREAD

**Issue by Pultex** [mekanism/Mekanism#5820]
Question really

#### Issue description:

I wanted to have a ultimate Induction Provider spawn in though another mod I can't get the item id to work

I thought it was 
mekanism:basicblock2@4
that does not work

I just am not sure as 
mekanism:basicblock2
does spawn in thermal casing

**Comment by pupnewfster** [comment]
Based on the ids you are given I am going to assume this is for 1.12, and if memory serves a lot of things in 1.12 (especially for tiered things), use NBT to determine which tier the block represents instead of just metadata.

**Comment by Yoosk** [comment]
I would suggest to use mod crafttweaker and command `/ct hand`.

**Comment by Pultex** [comment]
Sorry Did not really think about that things have changes so much for the newer versions
Thank you for responding did not think anyone would really 
Yes it is 1.12.2
I did not know if there was a format for questions.
Also @Yoosk thanks I knew there was a command to find what item was in your hand, will try.

**Comment by pupnewfster** [comment]
Closing this as it seems you have figured out the answer.
