### ISSUE TITLE
Gauge Dropper does not work in many machines.

### ISSUE THREAD

**Issue by Varntex** [mekanism/Mekanism#5821]
#### Issue description:
the Gauge Dropper does not work with gases in the chemical infuser and other machinery, one can't remove or completely dump the tanks. So far the Gauge Dropper only works in the Electric Pumps.

#### Steps to reproduce:
1. Fill a tank of the chemical infuser with for example oxygen.
2. Try to use the Gauge Dropper on the oxygen.

**Forge: 31.0.1** 
**Mekanism: 9.9.6.397**

**Comment by Apot98** [comment]
Gauge Dropper only works on liquids like water, lava, etc.
However the problem of unable to dump gas in machine needs to be solved so I think we can add a vaccum tool, similar to gauge dropper but for gases.

**Comment by Varntex** [comment]
Alright. Then the tip on the chemical infuser on the official mekanism wiki is wrong.
"Should you get the wrong gas into either of the tanks, you can use the Gauge Dropper to empty or transfer it."

**Comment by pupnewfster** [comment]
Firstly the gauge dropper does work on gases. The issue is that for some reason most of the GUIs don't seem to actually properly support it (which imo they should).

**Comment by icebolt9000** [comment]
is there way to remove gas or do i need wait for update?

**Comment by Varntex** [comment]
What I do is go into creative, (if you have the option to) and break the block. then grab a new fresh one from the creative inventory. Or you just make a new one and make very sure you don't make any mistakes. But i hope it gets fixed in .8

**Comment by pupnewfster** [comment]
Don't think there is any simple way to do it other than making a new block/using creative. Though this is relatively low priority, as before implementing this, I believe our system for networking (packets to and from the client), should be rewritten, and maybe the internal GUI rewrite finished/further progressed. Given while it technically would be possible to implement this currently it is just not worth the effort with how much of a mess some of those systems are. Also version `.398` means nothing as it is an arbitrary number added by the build system. The first three numbers are the actual version number (which if you look in game are the only ones that will actually even show)

**Comment by winsrp** [comment]
well in survival this is quite a problem, I've put sodium by mistake on a machine and now I cannot remove it... Actually it would be best for me if breaking the machine with something other than the wrench mode from the configurator, would give me a totally brand new machine instead of keeping its contents, or just make it so that it has a dump/reset button on the gui... using 9.9.8
