### ISSUE TITLE
NullPointerException: Registry Object not present

### ISSUE THREAD

**Issue by auddie2015** [mekanism/Mekanism#5822]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

The game crashes during mod loading with the issue in the title. All that is installed for this report is Mekanism, Mekanism Generators, and Forge.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: 30.0.51
**Mekanism: 9.9.3.394
**Other relevant version: Mekanism Generators 9.9.3.394
[crash-2020-01-28_10.43.06-client.txt](https://github.com/mekanism/Mekanism/files/4123222/crash-2020-01-28_10.43.06-client.txt)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Either update to 1.15.2, or downgrade forge to 30.0.43. Just before 1.15.2 some breaking changes got merged into forge, and I just directly updated to 1.15.2 instead of bothering to make a release on 1.15.1 and then 10 minutes later make another release for 1.15.2.

**Comment by auddie2015** [comment]
Did it through the lancher. Twitch is not showing 1.15.2. Thanks!
