### ISSUE TITLE
9.9.6.397 client crash on startup

### ISSUE THREAD

**Issue by kreezxil** [mekanism/Mekanism#5824]
https://gist.github.com/kreezxil/3a063754bfb5e8366318b0297e3e5fa9

1. installed mod
1. booted client
1. got the crash
1. reliable for me

mc: 1.15.2
forge: 31.0.1

**Comment by pupnewfster** [comment]
Please provide your latest log file, as the crash report in this case does not actually contain the source of the issue due to https://github.com/MinecraftForge/MinecraftForge/issues/6374

**Comment by term2112** [comment]
Were you able to run all the other mods before installing mekanism?

**Comment by kreezxil** [comment]
took your mods out and I was able to start my pack.

putting your mods back in to generate the report files again.

and I can't get it to do it again.

it is either a one off, or one of the other mods I removed was conflicting with your mods.

So I'll close this now.
