### ISSUE TITLE
[1.15.2] cannot extract gas from PRC

### ISSUE THREAD

**Issue by Zoratan** [mekanism/Mekanism#5825]
#### Issue description:
Gas from Pressurized Reaction Chamber cannot be extracted. every side connects with the pressurized tube but there is no transfer. Tried in singleplayer and dedicated server.
push/pull setup with configurator doesnt help aswell.

#### Steps to reproduce:
1.build prc
2.make sulfur dust out of coal (water & oxygen input)
3.gas product fills up with hydrogen that cannot be extracted (tubes, gauge dropper)

#### Version:
Forge: forge-1.15.2-31.0.1
Mekanism: 9.9.5

**Comment by pupnewfster** [comment]
Do you have auto eject enabled in the gas subtab of the side configuration tab?

**Comment by Zoratan** [comment]
Yes, i tried everything. even placed the output pipe on each side separately

**Comment by pupnewfster** [comment]
I take it you have it working now and this issue can be closed?

**Comment by Zoratan** [comment]
yes everything is fine
