### ISSUE TITLE
Quantum Entangloporter

### ISSUE THREAD

**Issue by Quu1337** [mekanism/Mekanism#5827]
Quantum Entagloporter not transporting items.
Energy and Fluid moves without problems, didnt try gases but those probably work too.

Using All The Mods 5 -modpack.

**Forge:** 30.0.42
**Mekanism:** 9.9.3.394

**Comment by SeraphMcLight** [comment]
So far it wouldn't transfer across dimensions for me. Within the same area it would however.

Same version.

**Comment by pupnewfster** [comment]
Quantum entangloporters and multiblocks don't have a backing inventory for items yet in 1.15.

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.
