### ISSUE TITLE
chemical infuser bugged afther server crash

### ISSUE THREAD

**Issue by icebolt9000** [mekanism/Mekanism#5828]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
chemical infuser bugged

#### Steps to reproduce:
1. Server crashed
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-30.0.42
**Mekanism:Mekanism-1.15.1-9.9.3.394
**Other relevant version:

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]
https://i.imgur.com/Z6zsx5s.png
can't empty it even with bukkit or gauge dropper

**Comment by pupnewfster** [comment]
Not sure what the issue is? If it is the fact you can't empty it with a bucket is intended, if it is that you can't empty it with a gauge dropper that is due to #5821
