### ISSUE TITLE
1.15.2 Chemical infuser outputting gas when there is no receiver or receiver is already full

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#5829]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Chemical infuser keep producing and outputting gas when the receiving machine is already full, or the other end of the pressure tube is not connected to anything.

#### Steps to reproduce:
1. Setup the last stage of the 5x ore production as the following diagram

![image](https://user-images.githubusercontent.com/13665046/73421667-496fcc00-42ec-11ea-9fac-f571ec2f5ecf.png)

You have from left to right 

-Creative Hydrogen chlorine tank
-Chemical injector chamber w/hopper on top for gunpowder
-Chemical oxidizer
-Chemical Infuser 1 -on right: creative oxygen tank
-Chemical infuser 2 -on right: creative Water vapor tank
-Chemical Dissolution Chamber
-Creative empty gas tank

-Creative energy under all machines (not pictured)
-Full power, speed, gas and muffling upgrades on all machines.

2. Drop some gunpowder on hopper (a couple of stacks)
3. Drop a stack of gold on Chemical Dissolution Chamber
4. Monitor Chemical infuser 2 for sulfuric acid production
5. Even when the Chemical dissolution chamber has finished processing gold, and filled his tank with sulfuric acid the chemical infuser 2 will still run and send sulfuric acid out of the machine.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.5.2 - 31.0.2
**Mekanism:** Mekanism-1.15.2-9.9.7.399.jar
**Other relevant version:** 

No crash just log, as there is no crash

**Comment by winsrp** [comment]
I think I finally know what is going on... the machines are eating all the resources trying to fill tubes... which seem to get a lot bigger on the ultimate versions, I understand the "realism" of tubes having content (it stumbled me because its the first mod I've tried that does this), but couldn't it be always the same small content regardless of rate it transfers? so that when we move tubes a little is lost instead of a lot, also there is no way to measure how much is on tubes, or is it?

**Comment by pupnewfster** [comment]
If you right click on a tube with a "network reader" it should say some stats about the contents. Alternatively given the one probe updated and I re-added back support for it in 9.9.7, you could install the one probe and hold a probe and shift (to go into extended mode), and that will also show how much is in the tube.

**Comment by winsrp** [comment]
oh I see.. there was something for that.. thanks.

**Comment by winsrp** [comment]
I found that on the config files you can change the capacity of tubes and pipes, set all those to 1, and works like a charm. Thanks!
