### ISSUE TITLE
Download link for mekanism additions on curseforge is broken

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#5830]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Attempt to download mekanism additions on curseforge
2. You are redirected to an error page

![image](https://user-images.githubusercontent.com/41069911/73445294-5d392380-4328-11ea-8756-e8f32ea7cccb.png)

**Comment by Yoosk** [comment]
Link you visited is not a valid one, it wont work. It should look like that [https://www.curseforge.com/minecraft/mc-mods/mekanism-additions/download/2871479](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions/download/2871479)

**Comment by term2112** [comment]
Thank you, that one worked

**Comment by thiakil** [comment]
Looks like a dumb CF bug. when not logged in it shows the broken button, but when i log in it doesnt appear (only the manage project stuff)
