### ISSUE TITLE
Power calculation is weird

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#5831]
#### Issue description:

Adding more cables to a network will increase both input and output of the network

#### Steps to reproduce:
1. Do the following setup for an induction matrix 4x4x4, 1 ultimate induction cell, 1 ultimate induction provider. On the left a creative power cell full, on the right a creative power cell empty.

![image](https://user-images.githubusercontent.com/13665046/73471833-a0f35380-434f-11ea-904e-5e121ccb71f6.png)

2. Each cable added to the input or output network will increase either the input or output respectively by 320.

3.So doing the following will actually increase the input rate of the creative block. This will input to1.6MJ/t, adding more cables increased the input rate... same thing for output.

![image](https://user-images.githubusercontent.com/13665046/73472065-1101d980-4350-11ea-9b8b-ad813bc4423a.png)

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.5.2 31.0.1
**Mekanism: MekanismTools-1.15.2-9.9.7.399.jar
**Other relevant version:**

**Comment by Yoosk** [comment]
That is intended feature of the mod afaik.

**Comment by pupnewfster** [comment]
I am pretty sure this is intended, the part that is "weird"/confusing in my opinion is the names things have for rates/etc as it makes people tend to get confused.

**Comment by winsrp** [comment]
well.. if I hook the induction matrix on the first setup, it will be always at 0 because it fills and empties at the same rate, but if I do the other setup the induction cell will actually fill more than what is taken out... so it is not only the wording to be honest.

**Comment by winsrp** [comment]
the question would be... what difference would it make for the input rate to add more cables, if I have a single provider?

**Comment by pupnewfster** [comment]
Wait is this issue saying the power rates that the induction matrix shows seem to be calculated strangely or is this issue about the mechanics of how the cables increase their rate/capacity?

**Comment by winsrp** [comment]
uhh... the more cables you add the higher the transfer rate on the network mainly... 

I would think
1. provider has an output rate
2. cable has a transfer rate

and there a 3 scenarios

1. provider outputs more than cable can handle, so rate is limited by cable
2. provider output is the same as cable can handle so rate is the same on both
3. provider output is less then cable can handle so rate is limited by provider

or so would I think...

**Comment by pupnewfster** [comment]
Max input/max output rate for the induction matrix is handled by the induction providers.

The part that both yoosk and me mentioned is that the cable's "transfer rate" is poor/misleading phrasing as transmitter networks in Mekanism are done as networks, so the capacity/throughput of the cable network goes up the more cables are in it. So it really is how much it contributes to the entire network rather than how much it individually can handle if there are multiple cables.

**Comment by winsrp** [comment]
removing the induction matrix from the question, this seems to happen for normal energy transfer between energy cubes as well

what's strange is why is it filling faster with more cables attached to the network? shouldn't it fill at the same rate regardless of how many cables it has? If I add 20 more cables to the input side it fills almost right away, vs just 2 tables which takes quite some while to fill.

**Comment by winsrp** [comment]
Take this for example, it fills the cube in 10 secs with an advanced induction cell inside

![image](https://user-images.githubusercontent.com/13665046/73474121-87eca180-4353-11ea-8988-aebebfbcae11.png)

![image](https://user-images.githubusercontent.com/13665046/73474147-976bea80-4353-11ea-904f-ec66903ff1de.png)

vs like 5 minutes with the first setup... on the first post.

**Comment by aidancbrady** [comment]
This has always been the behavior of Universal Cables, since they were introduced >4 years ago. Steering clear of 'not a bug, feature!'-ism, this doesn't violate gameplay in anyway and I don't think it necessitates a fix.

**Comment by winsrp** [comment]
the fact that something is old, doesn't mean it is right... just saying... but ok..
