### ISSUE TITLE
[1.15.2] Texture with size 12x12 limits mip level

### ISSUE THREAD

**Issue by realTIMematrix** [mekanism/Mekanism#5834]
#### Issue description:

I know we are in Alpha but during startup the logfile shows a warning message about a wrong texture size

#### Steps to reproduce:
1. Start Minecraft 1.15.2 with Forge and your mods.
2. Check the game output file

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.0.14
**Mekanism:** 1.15.2-9.9.7.399
**MekanismGenerators:** 1.15.2-9.9.7.399
**MekanismTools:** 1.15.2-9.9.7.399

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

`21:09:51.512 game [21:09:51] [Server-Worker-7/WARN] [minecraft/AtlasTexture]: Texture mekanism:block/models/multipart/opaque/elite_pressurized_tube_vertical with size 12x12 limits mip level from 4 to 2`

**Comment by realTIMematrix** [comment]
Additional Information:

I tested the new mod version under following conditions:

**Minecraft:** 1.15.2
**Forge:** 31.1.0
**Mekanism:** 1.15.2-9.9.8.400
**MekanismAdditions:** 1.15.2-9.9.8.400
**MekanismGenerators:** 1.15.2-9.9.8.400
**MekanismTools:** 1.15.2-9.9.8.400
**JEI:** 1.15.2-6.0.0.2

Now the following line appear:

`[05Feb2020 22:10:16.755] [Server-Worker-1/WARN] [net.minecraft.client.renderer.texture.AtlasTexture/]: Texture mekanism:block/models/multipart/basic_thermodynamic_conductor_vertical with size 12x12 limits mip level from 4 to 2`

**Comment by pupnewfster** [comment]
This is a known issue that most of the transmitter textures do not properly support mipmapping due to their unusual dimensions. Though it is also relatively low priority to fix.
