### ISSUE TITLE
Is the seismic vibrator/reader combo working on 1.5.2?

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#5835]
Just as a general query, I cannot get it to get any reading on this version, the reader always comes empty?

**Comment by pupnewfster** [comment]
No idea

**Comment by term2112** [comment]
I don't know about this either but tested it in 9.9.5, no readout is given on the reader.

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.
