### ISSUE TITLE
Configuration Card does not work for various configurable blocks/machines

### ISSUE THREAD

**Issue by Apot98** [mekanism/Mekanism#5836]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.Place a digital miner;
2.Do some configuration, then copy with configuration card;
3.Try to paste the configuration to another digital miner.

#### Version (make sure you are on the latest version before reporting):
**Forge:1.15.2-forge-31.0.1** 
**Mekanism:1.15.2-9.9.7.399** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Marking this an enhancement as it does seem like something that may be useful, but I don't believe the configuration card ever worked on the digital miner (and in fact I think there are various things it does not work on that it maybe should be able to).

**Comment by aidancbrady** [comment]
@pupnewfster the Configuration Card did used to work on the DM/all other configurable machines. Changing the tag to bug, maintaining minor importance.

**Comment by aidancbrady** [comment]
Fixed in 4eb9c14.
