### ISSUE TITLE
Was connecting Elite Mechanical Pipe and everything crashed

### ISSUE THREAD

**Issue by leofgiam** [mekanism/Mekanism#5837]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.0.14** 
**Mekanism: 1.15.2-9.9.7.399** 
**Other relevant version: 
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/GDf4Bt1s) / etc link here. Please make sure that it isn't set to expire.]

Also the crash report I provided mentions other mods present. Once I got the error I tried opening the world only with the four Mekanism files loaded and it persisted yet.

**Comment by pupnewfster** [comment]
Closing this as 9.9.8 is now released and on curseforge.

**Comment by leofgiam** [comment]
Thanks a lot you guys!
