### ISSUE TITLE
Using Extended Vein Mining Mode on Machines Erases Owners and Contents

### ISSUE THREAD

**Issue by Apot98** [mekanism/Mekanism#5838]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.Place some identical machines, closely one by one, and put something various in different machine;
2.Break one machine using atomic disassembler at extended vein mining mode;
3.watch the details of these machines in your inventory.

#### Version (make sure you are on the latest version before reporting):
**Forge:1.15.2-forge-31.0.1** 
**Mekanism:1.15.2-9.9.7.399** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
That is somewhat odd especially if it actually causes the blocks to be dropped, but either way for now I am not going to look into this (though thank you for the issue report), as I plan on rewriting/overhauling some of the internals of the atomic disassembler at some point so will look into it then.

**Comment by pupnewfster** [comment]
Closing this as it is fixed in 9.9.9, which is now released and on curseforge.
