### ISSUE TITLE
[1.12.2] When sign near the any pipe text backgound will change to black

### ISSUE THREAD

**Issue by kebufu** [mekanism/Mekanism#5839]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When sign near the any pipe text backgound will change to black
![mek1](https://user-images.githubusercontent.com/31839741/73592724-2174a880-4538-11ea-87fc-c985cbf76ba8.png)
![mek2](https://user-images.githubusercontent.com/31839741/73592727-2174a880-4538-11ea-8ce4-53e178672e2a.png)

#### Steps to reproduce:
1.Place a sign
2.Place a pipe near sign
3.Let' this pipe run.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2 14.23.5.2768
**Mekanism:** 1.12.2-9.8.13.83
**Other relevant version:** idk

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
First off neither of your images show any of our pipes nearby, so the best I can guess is this is an issue with smoothfont (assuming I am recognizing the mod you are using properly)

**Comment by kebufu** [comment]
Pipe is under the server rack.

**Comment by aidancbrady** [comment]
No longer reproducible in 1.5.
