### ISSUE TITLE
Improve Transparent Blocks' Underwater Render to Vanilla Glasses

### ISSUE THREAD

**Issue by Apot98** [mekanism/Mekanism#5840]
**Describe the the feature you'd like**
When our server decides to make an underwater base I suggested structural glass for walls, however we found the structural glass will have flowing water texture underwater, making the scenery unacceptable. So I suggest making Structural Glass, Reactor Glass and Laser Focus Matrix render the same as vanilla Glass, which has been updated to have a clear look underwater.

**Describe alternatives you've considered**

**Additional context**
![2020-02-01_21 03 28](https://user-images.githubusercontent.com/20492252/73592719-1ae63100-4538-11ea-9e5d-f72b74d45593.png)

**Comment by Apot98** [comment]
Also, is it intentional that Structural Glass blocks skylight? If it should not block skylight I wish it fixed when you are making the former enhancement.
![2020-02-01_21 32 11](https://user-images.githubusercontent.com/20492252/73593157-ae6d3100-453b-11ea-88ab-ad4b97b789de.png)

**Comment by pupnewfster** [comment]
The next alpha should have the light be fixed, I am currently working on a PR to forge that will then allow for us to make our glass not render the flowing water as it currently is being rendered.

**Comment by pupnewfster** [comment]
This will be fixed in 9.9.10 given the needed changes to forge have been merged. Not sure when 9.9.10 will be released as earlier today is when we released 9.9.9 and this change is by no means critical.

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.
