### ISSUE TITLE
Baby skeletons spawning all over the place

### ISSUE THREAD

**Issue by Zoratan** [mekanism/Mekanism#5841]
## Issue description:
Since the latest update baby skeletons spawn in my base all the time. (at day, outside and inside illuminated rooms)
I didnt even know they exist until today.

the only mod i updated aside from the required forge update was mekanism.
Maybe someone can confirm this issue?..

#### Version (make sure you are on the latest version before reporting):
**Forge 1.15.2-31.0.14
**Mekanism: 1.15.2-9.9.8.400

**Comment by pupnewfster** [comment]
From what little I played of MC a couple weeks ago it did seem that baby skeletons could spawn ignoring the light level. So this is something I will look into at some point. Though one thing to note is *nothing* between 9.9.7 and 9.9.8 actually changed in regards to how we have them spawn.

**Comment by Zoratan** [comment]
is there an option to disable them until there is a fix? they are so annoying that i rather downgrade to the last version than having to chase these speeders every 2-3 minutes..

**Comment by pupnewfster** [comment]
I believe you can disable them in the additions-common config (as well as adjust their spawn rates). Though once again I don't believe downgrading would actually change their spawn rates.

**Comment by seanimusprime** [comment]
I'm just commenting to say that the baby skeletons are annoying enough that I wanted to remove the mod. Thankfully we can get rid of them via config.

**Comment by aidancbrady** [comment]
Fixed in ed6c4c2
