### ISSUE TITLE
filled pressure pipe not connecting

### ISSUE THREAD

**Issue by Zoratan** [mekanism/Mekanism#5842]
#### Issue description:
pressure pipes dont connect to new ones when they are already filled.
i can connect and disconnect empty pipes with the configurator.
two pipes filled with the same gas are also (re)connectable. 
but new pipes refuse to join 

#### Steps to reproduce:
1. place a creative filled gas tank (or a factory that produces a gas) and connect a pressure pipe with it
2.once it is filled no additional pipe can be connected to the first one

#### Version (make sure you are on the latest version before reporting):
**Forge 1.15.2-31.0.14
**Mekanism: 1.15.2-9.9.8.400

**Comment by pupnewfster** [comment]
Closing this as it is fixed in 9.9.9, which is now released and on curseforge.
