### ISSUE TITLE
"None" Connection Type of Logistical Transporter malfunctions with container

### ISSUE THREAD

**Issue by Apot98** [mekanism/Mekanism#5843]
#### Issue description:
During modification over pigman mill I found a bug about a certain layout of logistical transporter and item container will cause some problem:
![2020-02-02_12 03 32_m](https://user-images.githubusercontent.com/20492252/73609269-03c24480-4607-11ea-9440-33b9cfb1e5f6.png)
![2020-02-02_12 03 24_m](https://user-images.githubusercontent.com/20492252/73609280-13418d80-4607-11ea-8678-b1c4bf4e3c98.png)
This layout can't sort correctly: the middle bin can recieve, but the other two bin recieve nothing - they end in the chest in right.

To verify the cause of the issue, I tried another layout, which result is that neither of the three bins recieve correctly, the items all gone to the chest. Now I can conclude that **something is wrong between the chest and the logistical transporter that have a "none" type connection with it.**
![2020-02-02_12 08 21_m](https://user-images.githubusercontent.com/20492252/73609309-46841c80-4607-11ea-93e5-90298e9b0467.png)

I also tried logistical sorter & colored transporter combo, it seems like there's also problem here - all item gone to the blue chest.
![2020-02-02_12 12 22_m](https://user-images.githubusercontent.com/20492252/73609323-69163580-4607-11ea-8bb9-963d76f0379e.png)

#### Steps to reproduce:
Set a transporter layout as the pictures, and try their sorting function.

#### Version (make sure you are on the latest version before reporting):
**Forge:1.15.2-forge-31.0.1** 
**Mekanism:1.15.2-9.9.7.399** 
**Other relevant version:**

**Comment by pupnewfster** [comment]
Hmm this is odd, there is definitely something going on here. I tested (the final images setup) with basic pipes initially and it worked fine, however when I switched to ultimate pipes they all went in the green chest.

**Comment by pupnewfster** [comment]
Closing this as it is fixed in 9.9.9, which is now released and on curseforge.
