### ISSUE TITLE
crash after placing Digital Miner

### ISSUE THREAD

**Issue by Zoratan** [mekanism/Mekanism#5844]
#### Issue description:
moved my digital miner to new location with mekanism ore.
game crashed as son as i placed it and i cannot rejoin as it will always crash when logging in.
other players get disconnected too as soon as they get near (through portal)

#### Steps to reproduce:
1.had to restore a backup of my world and couldnt reproduce so far

#### Version (make sure you are on the latest version before reporting):
**Forge 1.15.2-31.0.14
**Mekanism: 1.15.2-9.9.8.400
** Biomes-O-Plenty-Mod-1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/Zoratan/e84effcfa939d75064967b637190e91a

**Comment by pupnewfster** [comment]
Hmph seems my attempted patch for #5792 (which I wasn't ever able to reproduce), did not work properly. The best I can tell the issue has to do with if the miner is at the edge of where a chunk cache is then it fails to properly get information about the neighboring blocks. I will try to look into this more when I get the chance.

**Comment by pupnewfster** [comment]
Closing this as it is fixed in 9.9.9, which is now released and on curseforge.
