### ISSUE TITLE
The pipeline module is recommended

### ISSUE THREAD

**Issue by EnterFor** [mekanism/Mekanism#5847]
**Describe the feature you'd like**
Suggestions for various pipelines

* * the Describe alternatives you 've considered * *
Hello, can you separate the various pipes? Or is there a switch profile?
Because I didn't want my players to use the MEK pipeline because it would cause serious delays.
Sorry, I'm Chinese and my English is not good.

**Comment by Apot98** [comment]
You may describe in Chinese for me and I can translate it
你用中文发 然后我翻译

**Comment by EnterFor** [comment]
> 您可以用中文描述我，我可以翻译它
> 用中文发然后我翻译

好的，我想请问以后会把MEK的管道系统分离出来吗？
或者说现在有没有配置文件来关闭管道模块？
因为我不希望玩家使用MEK的管道系统，因为这会导致严重的卡顿。
（类似EnderIO那样，可以模块化安装Mod）

**Comment by Apot98** [comment]
Translation:
Transmitters as Standalone Mod
Currently logistical transporter can cause severe lags so I would like to be able to disable logistical transporter, or make transmitters a standalone mod, like what EnderIO have done.

Also for your question, I didn't find a config to disable transporters so you might try Minetweaker to remove transporters' crafting recipes.
关于你的问题，现在好像没有用配置文件关闭管道的方法，我建议你试试Minetweak把合成方式禁用

**Comment by EnterFor** [comment]
> Translation:
> Transmitters as Standalone Mod
> Currently logistical transporter can cause severe lags so I would like to be able to disable logistical transporter, or make transmitters a standalone mod, like what EnderIO have done.
> 
> Also for your question, I didn't find a config to disable transporters so you might try Minetweaker to remove transporters' crafting recipes.
> 关于你的问题，现在好像没有用配置文件关闭管道的方法，我建议你试试Minetweak把合成方式禁用

谢谢你帮我翻译，现在可以用插件禁用管道，但是强迫症有点难受。哈哈

**Comment by pupnewfster** [comment]
There are no current plans to split the transmitters into their own module. If you don't want players using them on your server you can either inform them or disable the recipes. Over the past year we have made many improvements to their performance so I would recommend making sure you are using the latest version (given you mentioned Ender IO I am assuming you are using 1.12), so the latest version would be 9.8.3.

I have made even more performance improvements to them in 1.15, and the next alpha will contain even more improvements to them.
