### ISSUE TITLE
Server Crash Report - 1.15.2 - 9.9.8.400

### ISSUE THREAD

**Issue by xxlio109** [mekanism/Mekanism#5853]
Issue description:
Server Crash Report

Version (make sure you are on the latest version before reporting):
Forge:  31.1.0
Mekanism:  1.15.2-9.9.8.400

https://gist.github.com/xxlio109/4eceb3689a56c9b8dd0ffc77738b1a0e

**Comment by pupnewfster** [comment]
No idea quite how that happened but the piece of code that is causing got removed in this commit https://github.com/mekanism/Mekanism/commit/8887e89f3f566a046bf3e2b6d48f50a19f873497 I believe this will be fixed in the next alpha.

**Comment by pupnewfster** [comment]
Closing this as it is fixed in 9.9.9, which is now released and on curseforge.
