### ISSUE TITLE
[1.15.2] Client crash after update..NullPointerException: Registry Object not present 	at java.util.Objects.requireNonNull

### ISSUE THREAD

**Issue by ProsperCraft** [mekanism/Mekanism#5855]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

The client crashes on load after updating.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.15.2-31.1.0
**Mekanism:** Mekanism-1.15.2-9.9.9.401.jar
--

**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/ProsperCraft/15b7fa42a5e074b8d88b4316677ea630

**Comment by Yoosk** [comment]
lastest.log is required

**Comment by ProsperCraft** [comment]
[latest.log](https://github.com/mekanism/Mekanism/files/4167772/latest.log)

**Comment by pupnewfster** [comment]
```
[14:03:06] [main/ERROR]: Error occurred applying transform of coremod patches/Entity.js function RandomPatches Entity Transformer
jdk.nashorn.internal.runtime.ECMAException: TypeError: Cannot set property "label" of undefined
	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57) ~[nashorn.jar:?]
```
I would guess this is a bug in random patches.

**Comment by ProsperCraft** [comment]
hmm, Random patches didn't update, was working before.

**Comment by ProsperCraft** [comment]
Same crash without Random Patches-
https://gist.github.com/ProsperCraft/43f536d64558559a514ae511be73354c

I will disable mek and see what is hiding under.

**Comment by pupnewfster** [comment]
```
[14:22:47] [modloading-worker-2/ERROR]: Failed to create mod instance. ModID: minecolonies, class com.minecolonies.coremod.MineColonies
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 1302 column 4 path $.
```

**Comment by ProsperCraft** [comment]
Yes, Minecolonies-
https://github.com/ldtteam/minecolonies/issues/4307

**Comment by MisteryDEAD7** [comment]
[crash-2020-02-24_00.04.38-client.txt](https://github.com/mekanism/Mekanism/files/4242666/crash-2020-02-24_00.04.38-client.txt)

**Comment by pupnewfster** [comment]
@MisteryDEAD7 are you attempting to report the fact that you are also getting this "issue"? And if so you are not providing any useful information due to https://github.com/MinecraftForge/MinecraftForge/issues/6374 I can probably give you an idea of what is causing your problem if you provide your latest log but that crash report is entirely useless.

***NOT TO MENTION*** it isn't even Mekanism that is the mod that shows in the crash report
```
at net.telepathicgrunt.ultraamplified.blocks.BlockColorManager$ForgeEvents.onBlockColorsInit(BlockColorManager.java:38) ~[?:?] {re:classloading,pl:eventbus:A}
```
(Though regardless the crash report is just trash data)

**Comment by MisteryDEAD7** [comment]
> @ MisteryDEAD7, ¿está intentando informar el hecho de que también está recibiendo este "problema"? Y si es así, no está proporcionando información útil debido a [MinecraftForge / MinecraftForge # 6374](https://github.com/MinecraftForge/MinecraftForge/issues/6374) Probablemente pueda darle una idea de lo que está causando su problema si proporciona su último registro, pero ese informe de bloqueo es completamente inútil.
> 
> _**NO MENCIONAR**_ , ni siquiera es Mekanism el mod que se muestra en el informe de bloqueo
> 
> ```
> at net.telepathicgrunt.ultraamplified.blocks.BlockColorManager$ForgeEvents.onBlockColorsInit(BlockColorManager.java:38) ~[?:?] {re:classloading,pl:eventbus:A}
> ```
> 
> (Aunque independientemente del informe de bloqueo son solo datos basura)

thanks for your time
