### ISSUE TITLE
Server crash at startup

### ISSUE THREAD

**Issue by GaanWeWeer** [mekanism/Mekanism#5858]
#### Issue description:
When i start my server with the modpack: Mc.Element i get this error
https://pastebin.com/KdM6kBhR

**Forge:14.23.5.2847** 
**Mekanism:1.12.2-9.8.3.390** 
**Other relevant version:**

**Comment by pupnewfster** [comment]
Not sure what happened as it seems like something failed in mod construction (which is a forge process), going ahead and closing this as it is likely an interaction with some mod (or core mod), and the entire mod construction process got rewritten when forge underwent a rewrite from 1.12->1.13/1.14 so I don't believe this should ever be able to happen anymore in 1.15.
