### ISSUE TITLE
Cannot extract from personal chest with hopper

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#5859]
#### Issue description:
Well trying to extract items from personal chest with a hopper under it results in nothing happening.

#### Steps to reproduce:
1.put a normal chest
2.Direct a hopper to it
3.Put a personal chest on top of the hopper and put a couple of items in it...
4. profit?... nope... nothing happens.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.5.2.3.10.0
**Mekanism: 9.9.9

**Comment by pupnewfster** [comment]
I am going to go ahead and take a wild guess that your personal chest is not on public? In which case this is entirely intended.

I do think various people have mentioned some potential ideas such as being able to automatically insert into a locked personal chest from neighboring machines of the same owner, and one for some sort of configuration of specific items to allow to be inserted/extracted from but no one has bothered to make a feature request for those.

**Comment by winsrp** [comment]
It is actually public as I play single player

**Comment by pupnewfster** [comment]
This has to do with the fact of how the inventory system used to work that we didn't allow extracting from underneath ever, except due to the fact we rewrote things I believe we can make it so extracting from underneath while on public is possible.

**Comment by winsrp** [comment]
Well if it's public I think you could extract from any side right?

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.
