### ISSUE TITLE
Game crashes before loading main menu

### ISSUE THREAD

**Issue by FuuNoKamiOka** [mekanism/Mekanism#5860]
#### Issue description:
Basically one thing happens; I install the mod and when I go to play the game it crashes. Starts the preload process and then crashes back to the launcher with the crash log.

#### Steps to reproduce:
1. Install the mod
2. Try to play
3. ???
4. Profit

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.1.0**
**Mekanism: 1.15.2-9.9.9.401** 
**Other relevant version: 
Mekanism Generators 1.15.2-9.9.9.401
Mekanism Tools 1.15.2-9.9.9.401**

**Comment by pupnewfster** [comment]
Please provide your latest.log file as that crash log is useless and provides no information due to https://github.com/MinecraftForge/MinecraftForge/issues/6374

**Comment by FuuNoKamiOka** [comment]
Last log of me trying to play with Mekanism installed.
https://pastebin.com/Gu1hXCXr

**Comment by pupnewfster** [comment]
```
[18:08:12] [modloading-worker-0/ERROR]: Failed to create mod instance. ModID: dankstorage, class tfar.dankstorage.DankStorage
java.lang.IllegalStateException: install mixin
    at tfar.dankstorage.DankStorage.<init>(DankStorage.java:53) ~[?:2.5]
```
Dank storage requires mixin to be installed.

**Comment by FuuNoKamiOka** [comment]
Huh...I didn't think that was the issue. Shows how much I know. LUL
