### ISSUE TITLE
[1.15.2] Trusted mode doesnt work, at all.

### ISSUE THREAD

**Issue by Quu1337** [mekanism/Mekanism#5861]
#### Issue description:
Trusted mode not working, locks out every player, even with security desk properly setupped.
Tried with multiple players as owner and users trying to access machines.

#### Steps to reproduce:
1. Place down security desk.
2. Security override: on
3. Set trusted mode
4. Add trusted player
5. Trusted player cant access any machine.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.0
**Mekanism:** 1.15.2-9.9.8.400
**Other relevant version:** All The Mods 5, 1.1

**Comment by STOKE-STER** [comment]
Can confirm I'm having this issue also.

**Comment by Yoosk** [comment]
Can confirm as well.

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.
