### ISSUE TITLE
Logistical sorter broken

### ISSUE THREAD

**Issue by Yoosk** [mekanism/Mekanism#5863]
#### Issue description:
Logistical sorter `tag` and `modid` functions does not work at all, while spamming logs with error.

#### Steps to reproduce:
1. place and logistical sorter
2. try to add modid or tag filter
3. no profit

[watch the video](https://yoosk.pl/ZGO6urZT.webm)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.0
**Mekanism:** 1.15.2-9.9.9.401
**Other relevant version:** modpack im on: RAM 0.2.1

#### If a (crash)log is relevant for this issue, link it here:
https://s.yoosk.pl/0Mlu7

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.
