### ISSUE TITLE
Entangloporter configuration doesn't trigger block updates

### ISSUE THREAD

**Issue by aidancbrady** [mekanism/Mekanism#5864]
#### Issue description:
Quantum Entangloporters do not trigger block updates to adjacent transmitters when frequency state is updated or side configuration is modified.

#### Steps to reproduce:
1. Place a Quantum Entangloporter and a transmitter (of any type) adjacent. The transmitter should start off disconnected (as the Entangloporter has no current frequency).
2. Set the frequency of the Entangloporter. The transmitter should connect, but it does not unless it is broken and replaced.

Additionally, side configuration settings are ignored- transmitters will always connect if a frequency is set (and vice versa), regardless of whether that transport type for a certain side is enabled/disabled in the side configuration. This doesn't happen with other machines.

**Comment by pupnewfster** [comment]
Linking this commit to here just to make it easier to track changes: https://github.com/mekanism/Mekanism/commit/1c63d267adc3a6cc389150309636e968e08bc283

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.
