### ISSUE TITLE
1.12.2 - Heat Generators passively producing very little power.

### ISSUE THREAD

**Issue by llloyd4** [mekanism/Mekanism#5866]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

According to the Wiki the heat generator is suppose to produce something on the order of 10 RF/t each if surrounded by 5 lava blocks, they are really only producing 1.5 RF/t and I can't find a config option to adjust that.

#### Steps to reproduce:
1. Create new world
2. Create 5 Heat Generators
3. Place down 5 blocks of lava on each side of the heat generator using blocks (like cobble) to hold them in place. 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.5.2846
**Mekanism:** 1.12.2-9.8.2.389
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by aidancbrady** [comment]
I've bumped the numbers a bit- a generator surrounded by 5 blocks of lava should now produce ~20J/t. Remember that this is *passive* energy generation, however, and is intended to be low.

**Comment by llloyd4** [comment]
Cool! And, yeah, it's early game for sure. But ... 20/2.5 is 8 RF/t ... Yeah, a couple of those should easily run an enrichment chamber / smelter combo to start ore doubling and building better. :D
