### ISSUE TITLE
Dragging broken on GuiScrollList

### ISSUE THREAD

**Issue by aidancbrady** [mekanism/Mekanism#5867]
#### Issue description:
Dragging the scroll bar doesn't work in GuiScrollLists.

#### Steps to reproduce:
1. try to drag
2. doesn't work

#### Version (make sure you are on the latest version before reporting): latest dev

**Comment by aidancbrady** [comment]
Fixed in c717de3

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.
