### ISSUE TITLE
Unset frequencies are not sustained upon world-load

### ISSUE THREAD

**Issue by aidancbrady** [mekanism/Mekanism#5868]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Frequencies aren't being written/read properly upon world reload

#### Steps to reproduce:
1. Place Entangloporter, create a few frequencies
2 On world load, only the frequency set by the Entangloporter will remain

#### Version (make sure you are on the latest version before reporting): latest dev

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.
