### ISSUE TITLE
Gas/heat/energy/fluid transmitter content visuals broken

### ISSUE THREAD

**Issue by aidancbrady** [mekanism/Mekanism#5869]
#### Issue description:
All transmitters (but transporters) don't properly show contents when transmitting. Usually one or two transmitters don't show contents while the rest do. Likely due to incomplete client-side visual sync.

#### Steps to reproduce:
1. Place transmitters, with source and dest on either side
2. Observe contents not showing in one or more transmitters

**Comment by pupnewfster** [comment]
Closing this as 9.9.10 is now up and on curseforge.
