### ISSUE TITLE
Rework bio fuel production values

### ISSUE THREAD

**Issue by pupnewfster** [mekanism/Mekanism#5877]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The amount of bio fuel produced by various items is rather inconsistent for how much a given item will produce. This should be reworked and maybe have various vanilla meats/foods be added to being able to produce bio fuel. While at it we may want to evaluate the base levels of power the bio generator produces.

#### Version (make sure you are on the latest version before reporting):
latest dev

**Comment by aidancbrady** [comment]
Fixed in 241b432.
