### ISSUE TITLE
Mekanism Ultimate tier installer

### ISSUE THREAD

**Issue by Karl-Markkus** [mekanism/Mekanism#5882]
I would like to see the Ultimate tier installer have more uses - for now it's only used to upgrade an Elite energy cube to Ultimate. What if we could use it to upgrade the factories to Ultimate tier? What I am imagining is that the Ultimate tier factories don't have an increase of processing slots, but it allows you to install 2-4 more speed/energy upgrades to make them even faster! Otherwise if we could put 8 more speed/energy upgrades, the energy cost would be ridiculous, not gonna even think how it would affect the TPS if it had 16 speed upgrades...

Personally, I am a super-industrial kind of guy and in one of my custom mod-pack, a simple 7-slot ore processor with max speed/energy is not enough for me... I am using 3 of them! (do keep in mind, by maxed out, I mean quadrupling the ores, I have 3 QUADRUPLERS). As well as automating smelting/crushing, I am using 4 each to speed up my automated crafting!

Any alternatives... not really thought about it... someone else could think about it ;p

**Any additional context can be got from a discussion if they like to "improve" this thought**

**Comment by Yoosk** [comment]
But... we can use them to update to ultimate tier factories.

**Comment by Karl-Markkus** [comment]
Oh really? I totally missed that. Let me be more precise then - for version 1.12.2!

**Comment by pupnewfster** [comment]
The ultimate tier installer is already able to handle a lot of things.
Elite -> Ultimate:
- Bins
- Energy Cubes
- Fluid Tanks
- Gas Tanks
And as yoosk has said in 1.15.2 (the version we are currently developing):
- Factories

We have stopped active development on 1.12.2, and are not going to end up backporting features like ultimate factories (as it would be an extreme hassle/pain), but basically everything in 1.15.2 that an installer can be used on, can also have ultimate installers used on them.

**Comment by Karl-Markkus** [comment]
Alright, thanks for the info. I just completely missed the fact that ultimate tier installer can be used on everything on ver. 1.15.2
