### ISSUE TITLE
Question with scuba air tank

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#5884]
Is it normal for the night vision potion to have a faster timer while the scuba tank is giving you air?

**Comment by Apot98** [comment]
"Any potion effect will instantly stop once you equip the Gas Mask and turn on the oxygen supply."
So yes it's a feature.

**Comment by winsrp** [comment]
well it doesn't stop, the timer just goes faster

**Comment by pupnewfster** [comment]
According to aidan, this is intended, and at one point it may have removed them instantly but we agreed that it just making the timer goes faster makes more sense anyways.

**Comment by winsrp** [comment]
cool, good to know, thanks!
