### ISSUE TITLE
Incompability with Digital Miner and by extension Mekanism

### ISSUE THREAD

**Issue by Niilyx** [mekanism/Mekanism#5885]
### Issue description:
I love the Digital Miner, however I'd like to know if it's possible to "add" compability to a mod (in this case, Way More Ores Mod) because I want my miner to mine every ores but these as they cannot be enriched and can't use a Logistical Sorter to put them elsewhere.

#### Version:
**Forge: 1.12.2-14.23.5.2847** 
**Mekanism: 1.12.2-9.8.3.390** 

No relevant crash log.

**Comment by Yoosk** [comment]
1.12.2 is not in active development anymore, and you can get compatibility by using other mods like `jaopca` or make your own by using `crafttweaker`.

**Comment by Niilyx** [comment]
Oh boy, then I think I can close this issue...
