### ISSUE TITLE
Digital Miner not working in the newest version

### ISSUE THREAD

**Issue by m-vlad** [mekanism/Mekanism#5886]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The Digital Miner doesn't seem to work for me properly in the last version, didn't change any filters nor battery setup, it worked properly before. It seems to show the number of blocks it needs to break for a split second then it disappears. The minecraft launcher shows no errors or any logs of any kind at that point.

#### Steps to reproduce:
1. Get a digital miner
2. Place it somewhere and give it a power cube (I was using the ultimate one, for reference)
3. Add any filters and press start

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.12
**Mekanism:** 9.9.10.402
**Other relevant version:** Valhelsia 2 2.0.5

**Comment by pupnewfster** [comment]
Can you provide your latest log file?

**Comment by Yoosk** [comment]
Works fine for me in singleplayer https://yoosk.pl/9xl0Nzf2.webm

**Comment by m-vlad** [comment]
[latest.log](https://github.com/mekanism/Mekanism/files/4220983/latest.log)
And a video
https://drive.google.com/open?id=1e0vOwhoQdOQ-nnZDVx-vbjCbMEONY35s

**Comment by term2112** [comment]
I have also noticed an issue with the miner "to mine" amount being incorrect, it will sometimes stop at some random number and stop mining as if there was 0 material left. Resetting the miner does not affect this number.

I am not sure if there is actually ore left and is unable to mine it or if the number is incorrect. Running latest forge and mekanism.

**Comment by m-vlad** [comment]
It was set to `*log*` from 70 to 255 and it was in the middle of a forest.

**Comment by TheFryGuy** [comment]
Is the digitalminer setup inside of a minecolony here? Because I've had the same issue the miner will not work properly inside the boundaries of a minecolony but the second you place it outside of one everything works fine on a server too.

**Comment by TheFryGuy** [comment]
Is the digitalminer setup inside of a minecolony here? Because I've had the same issue the miner will not work properly inside the boundaries of a minecolony but the second you place it outside of one everything works fine on a server too.

**Comment by m-vlad** [comment]
Actually yes! That might be it actually. Any way to fix it on my side?

**Comment by TheFryGuy** [comment]
If you are server owner, the only way to allow the digitalminer to mine in a colony is to go to the config and turn off ColonyProtection since it is stopping the miner from breaking blocks. (separate setting than explosion protection so creepers still won't blow your town up)

**Comment by aidancbrady** [comment]
Closing this issue, glad y’all found the problem.

**Comment by mirague** [comment]
Is there any way to make the miner able to work inside a Minecolony? I suppose it would require to be linked to a certain colony and I can imagine that being a bit flumsy to implement...

**Comment by pupnewfster** [comment]
Minecolonies has a config to allow fake players to mine in them.

**Comment by mirague** [comment]
Ah is that the `specialpermgroup = ["_Raycoms_"]`? If so, any idea what I should add there to allow Mekanism?

**Comment by pupnewfster** [comment]
> If you are server owner, the only way to allow the digitalminer to mine in a colony is to go to the config and turn off ColonyProtection since it is stopping the miner from breaking blocks. (separate setting than explosion protection so creepers still won't blow your town up)

**Comment by timstoop** [comment]
For those hitting this issue and finding this one high on a Google search: If you add a user "[Mekanism]" as an officer, the digiminer will work again. At least this worked for me in the Valhesia 2 modpack. Caution: This means that everything from Mekanism will have an effect on your colony, even things deployed by other users!

**Comment by JeweledUrchin** [comment]
Hey I've been reading this thread and I basically just can't get my digital miner to work in my solo world. No servers no colonies nothing my digital miner will not work even if I move it or outright build a new one. The ores dont show their picture once I select the tags from the OreDict. Ik it's a little late but any help would be greatly appreciated!
