### ISSUE TITLE
Laser Amplifier GUI Energy Update

### ISSUE THREAD

**Issue by MUHAKLorTheDorfTrottel4Github** [mekanism/Mekanism#5888]
mc 1.15.2
forge-1.15.2-31.1.12
Mekanism(all)-1.15.2-9.9.10.402
1:
Laser Amplifier GUI does not update stored power 
after restarting world , value is updated 
2: 
it seems , that the amplifier  is not "shifting" energy in "redstone ignored" , only on 
"low"
regards

**Comment by pupnewfster** [comment]
Fixed in dev: https://github.com/mekanism/Mekanism/commit/cc279549ee8c86a090200971e000bcb82d57aade

**Comment by pupnewfster** [comment]
Closing as 9.9.11 is now released and on curseforge.
