### ISSUE TITLE
Crash with OptiFine 1.15.2

### ISSUE THREAD

**Issue by Ibirtem** [mekanism/Mekanism#5889]
Crash report:
https://gist.github.com/Ibirtem/b8629157a45e0fe5cec2d79a6192a894

**Comment by pupnewfster** [comment]
Optifine for 1.15.2 (according to their own changelog), is not compatible with forge.

The crash is due to them breaking [this](https://github.com/MinecraftForge/MinecraftForge/commit/40de19f16ed4741cbd65483f83c12630188c18cc) forge patch which allows for custom entities to exist.
