### ISSUE TITLE
Combiners factory variants don't have purple input slots.

### ISSUE THREAD

**Issue by STOKE-STER** [mekanism/Mekanism#5890]
#### Issue description:
The combiner (non factory variant) has slots set up like this to add things like cobble.
![2020-02-21_10 01 06](https://user-images.githubusercontent.com/36657224/74991261-35555f80-5491-11ea-9cb6-fa550e7db810.png)
![2020-02-21_10 01 11](https://user-images.githubusercontent.com/36657224/74991271-3c7c6d80-5491-11ea-8cde-e6a44d625fea.png)
This works and allows cobble to be auto inserted.

However the factory variants are bugged and don't have this purple option or a purple side config option:
![2020-02-21_10 04 18](https://user-images.githubusercontent.com/36657224/74991385-89604400-5491-11ea-9b9d-fa6d3267d849.png)

This means cobble can't be pushed into it and has to be inserted by hand

#### Steps to reproduce:
1. build basic combining factory
2. try to setup the side config to have a purple extras input
3. try to automate cobble input
4. cobble will not go in to the machine

#### Version (make sure you are on the latest version before reporting):
Forge: 31.1.12
Mekanism: 9.9.10.402

**Comment by pupnewfster** [comment]
Closing as 9.9.11 is now released and on curseforge. There were two issues at play, one it wasn't being added as an extra slot so the configuration didn't support it as one, and the other was I didn't have the slot set so that it would show as purple in the GUI. Both of these are now fixed though.
