### ISSUE TITLE
Bed Duplication with the Atomic Disassembler

### ISSUE THREAD

**Issue by JustDoesGames** [mekanism/Mekanism#5891]
This may have been patched in a more recent version but... still worth saying something about it because it is easy to reproduce

Steps to reproduce:
1.place any bed
2.set the tool to "extended vein mining"
3.break the head portion of the bed

#### Version (make sure you are on the latest version before reporting):
**Forge:**  14.23.5.2836
**Mekanism:** 1.12.2-9.8.2.389

**Comment by pupnewfster** [comment]
I can confirm this is fixed by the rewrite I did of how the atomic disassembler breaks blocks in 1.15
