### ISSUE TITLE
Quantum Entangloporter does not connect to pipes upon world reloading

### ISSUE THREAD

**Issue by leofgiam** [mekanism/Mekanism#5893]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I have working Quantum Entangloporters set up all on my local world. 
When I exit and reload the world most of them do not connect to pipes or cables they were previously connecting.

To circumvent the issue I must only switch the affected side of that type (energy, items, fluid, etc). For example it's always on Output (as the example shown in the pictures). I must switch to Input, None, and then Output again and not only this one works, but also it fixes the other one attached on the side (as shown in the screenshot).

This is happening everytime I reload the world.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.1
**Mekanism:** Mekanism-1.15.2-9.9.9.401
**Other relevant version:** 
![2020-02-21_07 47 09](https://user-images.githubusercontent.com/60528167/75040824-24f5b280-549a-11ea-919b-606f91b4a4c6.png)
![2020-02-21_08 05 46](https://user-images.githubusercontent.com/60528167/75040826-26bf7600-549a-11ea-9281-eda65b84208a.png)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Can you reproduce this in 9.9.10. As we did a decent number of fixes to the quantum entangloporter in that version and I believe that was one of them.

**Comment by aidancbrady** [comment]
I'm 99% sure my changes fixed this exact issue. Will re-open if the issue is still recurring in 9.9.10.

**Comment by leofgiam** [comment]
> Can you reproduce this in 9.9.10. As we did a decent number of fixes to the quantum entangloporter in that version and I believe that was one of them.

I've had this world since Mekanism 9.9.1 or so when the Quantum Entangloporters dupplicated on breaking. I thought I dispossed of all the duplicated ones. Could it be that the ones that remained are buggy? Or does this have nothing to do with it?

**Comment by leofgiam** [comment]
I can confirm that in 9.9.10 this issue is gone. Thank you so much.
