### ISSUE TITLE
walkie talkie

### ISSUE THREAD

**Issue by creeperplayer20** [mekanism/Mekanism#5895]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

hi, when my friends uses walkie talkie, i cant hear them and they cant hear me...

everything is on and the port is same [default]

version:  1.12.2-9.8.3.390

**Comment by pupnewfster** [comment]
#4992
