### ISSUE TITLE
[1.15.2] Mekanism ChunkManager Console Spam

### ISSUE THREAD

**Issue by Boomflex** [mekanism/Mekanism#5897]
#### Issue description:

Mekanism ChunkManager is looking for Chunkloaders that may have previously existed and spamming the console.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.12
**Mekanism:** 1.15.2-9.9.10.402
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://hatebin.com/lrshonvifa - Starts line 4272
https://i.imgur.com/64OEcOL.png

**Comment by thiakil** [comment]
Your log appears to be truncated on hatebin btw.

- You said on Discord that those positions only had just "natural terrain gen" - had there ever been a Mekanism block there? e.g. Digital Miner
- Do you have any mods that do "moving wand" type things? i.e. where there's the chance the Tile doesn't get unloaded correctly.

It is possible something was missed for handling when a tile is removed from the world - I've added some logging when it does attempt to remove them so we can test if that is the case.

The invalid entries should also now get removed from the saved data on load.

**Comment by pupnewfster** [comment]
@Boomflex  9.9.11 is now released and on curseforge, so it probably would be useful to do some testing with it as it contains the logging thiakil was mentioning, and may allow us to further track down what is going on.

**Comment by pupnewfster** [comment]
@thiakil there is a log on #5956 that seems to be related to this.

**Comment by Lavan** [comment]
I stumbled on this issue today using Mekanism 9.9.15.

Loads of these lines:
`[12mar2020 13:16:49.350] [Server thread/WARN] [Mekanism ChunkManager/]: Tile at BlockPos{x=-1147, y=91, z=177} was either null or not an IChunkLoader?! Tile: null`

After this the log shows the server loading the world and then is halts not responding to anything.

The only player made items in the chunk was a Digital Miner with a biogenerator and storage attached.

I also tested starting the world without Mekanism which worked without problem.

The digital miner was equipped with an Anchor Upgrade which might be the cause.

**Comment by pupnewfster** [comment]
Actually was the chunk anchor in the miner placed before or after updating to 9.9.15. Given I did modify how the data for the component was saved, so there is a slight chance thinking about it that something went wrong rather than it just basically forgetting what chunks are loaded.

**Comment by EnterFor** [comment]
> 我今天使用Mekanism 9.9.15偶然发现了这个问题。
> 
> 这些行的负载：
> `[12mar2020 13:16:49.350] [Server thread/WARN] [Mekanism ChunkManager/]: Tile at BlockPos{x=-1147, y=91, z=177} was either null or not an IChunkLoader?! Tile: null`
> 
> 此后，日志显示服务器正在加载世界，然后停止不响应任何内容。
> 
> 唯一能制造物品的玩家是带有矿机和存储装置的Digital Miner。
> 
> 我还测试了在没有Mekanism的情况下启动世界的过程，该问题没有问题。
> 
> 数字矿机配备了锚固件升级，这可能是原因。

When I delete the chunk where the miner is located, the problem can be settled and the game can be entered

(only the upgraded mine anchor has been removed)

**Comment by pupnewfster** [comment]
I believe the loading on freezing issue is now properly fixed.
