### ISSUE TITLE
[1.15.1-9.9.10] Adding "trusted player" to security desk crashes server

### ISSUE THREAD

**Issue by Quu1337** [mekanism/Mekanism#5900]
#### Steps to reproduce:
1. Open Security Desk
2. Add any player, press the ok-button-thing (doesnt matter if they are online or offline, might not even matter what you write in the box)
3. Server crash.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.14
**Mekanism:** 9.9.10
**Other relevant version:** All The Mods 5

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/BwR30KVK
https://pastebin.com/7MTamZDh

**Comment by pupnewfster** [comment]
#5896

**Comment by Quu1337** [comment]
ah balls, looked trough the issues but didnt notice it. stoke 3 fast 5 me.
