### ISSUE TITLE
ArrayIndexOutofBounds

### ISSUE THREAD

**Issue by kornfan6589** [mekanism/Mekanism#5904]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Clientside crash when approaching a chunk containing a particular digital miner...

#### Steps to reproduce:
1. Log in
2. Get within render distance of the digital miner
3. crash, (note, the miner has been in place for 2 days now and only today has caused an issue)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.0
**Mekanism:** 9.9.8.400
**Other relevant version:** 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/z2beiEUJ

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Update mekanism

**Comment by kornfan6589** [comment]
Updated to 9.9.11.403 and forge to 31.1.16 and now it crashes without giving me a crash report.

but i do see this in server log

[21:32:46] [Server thread/WARN] [minecraft/TileEntity]: Block entity invalid: mekanismgenerators:reactor_frame @ BlockPos{x=-34, y=66, z=-122}
[21:32:46] [Server thread/WARN] [minecraft/TileEntity]: Block entity invalid: mekanismgenerators:reactor_frame @ BlockPos{x=-33, y=65, z=-122}
[21:32:46] [Server thread/WARN] [minecraft/TileEntity]: Block entity invalid: mekanismgenerators:reactor_frame @ BlockPos{x=-35, y=65, z=-122}
[21:32:46] [Server thread/WARN] [minecraft/TileEntity]: Block entity invalid: mekanismgenerators:reactor_frame @ BlockPos{x=-34, y=64, z=-122}

**Comment by pupnewfster** [comment]
If it is crashing there is a crash report, or at the very least give your latest log. Also those errors should not be showing as I fixed them in an earlier version so I would recommend maybe rebuilding your reactor to see if makes those go away.

**Comment by kornfan6589** [comment]
i promise it did not generate a crashlog, i dont know why, heres the client side log from the moment i joined the world to the game closing and the launcher telling me the game has crashed.

https://pastebin.com/bYDuFHx5

**Comment by pupnewfster** [comment]
Either you don't have enough ram dedicated to MC or your download corrupted the file:
```
[25Feb2020 21:11:40.438] [Render thread/WARN] [net.minecraft.client.renderer.texture.TextureManager/]: Failed to load texture: mekanism:render/digital_miner_overlay_on.png
java.io.IOException: Could not load image: Corrupt JPEG
``` so I would go ahead and try redownloading mekanism and see if it fixes it.

**Comment by kornfan6589** [comment]
im running 12 gigs of ram client side and 14 gigs server side. also i tried that a few times with fresh files to make sure. the problem is its intermittent. sometimes it works fine, others it crashes. as soon as i get within render distance of the miner it either works or crashes...

**Comment by pupnewfster** [comment]
No idea, but without the full log there is nothing I can do or suggest from my end.

**Comment by kornfan6589** [comment]
Ok, new findings, reinstalled client and server side jars again. loaded several times no issues. clicked on the miner and clicked "visuals off" and then it crashed. with a log this time

https://pastebin.com/Y1SSRdJP
