### ISSUE TITLE
Force sned option for the Logistical Sorter

### ISSUE THREAD

**Issue by FarmerThanos** [mekanism/Mekanism#5909]
A force send option for Logistical Sorters could bypass the mechanics of Mekanism checking the inventory of a block before sending items, thus making drawer upgrades like the void upgrade usable without a hopper, which will not be fast enough in mass-quantity situations. And since it needs to be set in the filter option (like max and min item quantity) it will not break anything.

An alternative to the force option can simply be a void option on the bins, so if they're full, they will delete new items.

The reason I wanted something like this is because I can't seem to find any 1.15.2 Trashcan mods. I'm playing Factory Builder, a 1.15.2 modpack, which has Alchemistry, and a byproduct of cellulose is hydrogen and oxygen, which outnumbers the carbon greatly. The diamond factory basically keeps overflowing with waste.

**Comment by aidancbrady** [comment]
For now I'd stick with hoppers/lava- I'd consider making something of a 'incinerator' in the future, but the Logistical Transporter option would be difficult to implement with the way they're engineered.
