### ISSUE TITLE
Ethylene is not pulled out of the Pressurized Reaction Chamber

### ISSUE THREAD

**Issue by d0em3** [mekanism/Mekanism#5910]

**Comment by pupnewfster** [comment]
Please don't just delete the issue format it is there for a reason. What version of mekanism are you using, and have you set it to auto eject in the side config?

**Comment by d0em3** [comment]
Sorry, I am new here and did not know there is the format. 
I am using the newest version and I believe I have not set it to auto eject. My bad. I will close the issue.
