### ISSUE TITLE
Teleporter Link Not Found Issue

### ISSUE THREAD

**Issue by RoastedToast36** [mekanism/Mekanism#5912]
I've set up a two teleporters which both work. After I log out of the world they both unlink even with a chunk loader on both sides. I can fix this by going to the other teleporter but there is no reason to actually have the teleporter if I'm going to have to travel thousands of blocks away just to activate it when I login.

**Comment by pupnewfster** [comment]
What version of Mekanism are you on, and can you please provide your latest log?
