### ISSUE TITLE
Digital Miner Clientside Crash

### ISSUE THREAD

**Issue by kornfan6589** [mekanism/Mekanism#5913]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Game Crashes when inserting items into material filter

#### Steps to reproduce:
1. Right Click Digital Miner
2. Config, Material Filter, Insert Material (any Material)
3. Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.16
**Mekanism:** 9.9.11.403
**Other relevant version:** 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/E1gGmjuR

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Yamza** [comment]
Another similar crash. Crashes when trying to access a filter made prior to latest mek update.
https://pastebin.com/RRrHHUHz
Forge 31.1.18

**Comment by aidancbrady** [comment]
Unable to reproduce this. Any particularities with your setup? Certain filter arrangement perhaps? Are you in SMP or singleplayer?

**Comment by aidancbrady** [comment]
Also, does this happen when placing a new digital miner without any filters installed?

**Comment by aidancbrady** [comment]
This is the result of #5933. Merging this issue.
