### ISSUE TITLE
General Kenobi

### ISSUE THREAD

**Issue by blooker20** [mekanism/Mekanism#5915]
Change the text on the Digital Miner to »General Kenobi!« on May 4th, Star Wars Day.

![https://i.gyazo.com/fa59a52313ab8c5f6dd584c045d47f61.png](https://i.gyazo.com/fa59a52313ab8c5f6dd584c045d47f61.png)

**Comment by aidancbrady** [comment]
<img width="719" alt="Screen Shot 2020-02-29 at 3 24 35 PM" src="https://user-images.githubusercontent.com/1508015/75614532-b2bf4680-5b07-11ea-8392-2a79f18c6b2f.png">
:)
