### ISSUE TITLE
Robit Renaming

### ISSUE THREAD

**Issue by jengeld4** [mekanism/Mekanism#5916]
Version: 1.15.2-9.9.11.403
Robit's name can't contain the letter e, because typing that closes the whole UI like closing your inventory

**Comment by aidancbrady** [comment]
Can't reproduce this. Anything particular with your keyboard layout or controls?

**Comment by jengeld4** [comment]
Not that I'm aware of. I try the rename button and try to name it "gal.exe". Everything up to the . works but as soon as I hit e, the UI closes.

**Comment by jengeld4** [comment]
if it helps, I'm playing Cipratech 1.0.1 on a server

**Comment by aidancbrady** [comment]
Does this happen in singleplayer?

**Comment by aidancbrady** [comment]
If the Robit's rename screen is opened and the cursor is flashing on the text entry box (meaning the entry box is *focused*), we have checks in place to prevent this from happening. I've tested in my local environment and can't reproduce this issue.

The one thing I can think of- maybe there's a mod installed that looks for the period ('.') character and the text entry box loses focus once you type it. Make sure you're focused on the text entry by clicking it. Other than that, I'm afraid there's not much I can do.
