### ISSUE TITLE
Crash on startup if sneak is bound to mouse button 4

### ISSUE THREAD

**Issue by winauer** [mekanism/Mekanism#5920]
#### Issue description:

Game crashes on startup if sneak is bound to mouse button 4.
(`key_key.sneak:key.mouse.4` in the options.txt file)

#### Steps to reproduce:

1. Bind sneak to mouse button 4
2. Restart game

#### Version:

**Forge:** forge-1.15.2-31.1.18
**Mekanism:** 1.15.2-9.9.11.403

#### Crashlog:

https://paste.ee/p/iVDqX

**Comment by aidancbrady** [comment]
I don't think this issue is related to Mekanism. It appears this crash occurs without Mekanism installed as well: https://www.reddit.com/r/Minecraft/comments/eab7b9/version_115_consistently_crashes_upon_startup/

Try out the solutions mentioned in that thread and see if it helps.

**Comment by winauer** [comment]
That linked crash is something different. I don't get a crash without Mekanism.

The crash happens if sneak is bound to any mouse key, not just mouse 4 as I originally thought. I believe it is caused by only handling keyboard keys [here](https://github.com/mekanism/Mekanism/blob/1.15x/src/main/java/mekanism/client/MekKeyHandler.java#L44). (The code for handling mouse buttons is commented out two lines above that)

Please reopen.
