### ISSUE TITLE
Logistical transporter redstone sensitivity

### ISSUE THREAD

**Issue by leofgiam** [mekanism/Mekanism#5928]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description: 

Cannot change the redstone sensitivity state of a logistical transporter. The goal is to lock (or not) a logistical transporter pulling from a machine (smelter, etc).
![2020-03-04_19 26 38](https://user-images.githubusercontent.com/60528167/75928884-1e7a1a00-5e4e-11ea-8377-d8360480b7c1.png)

I tried different things with the Configurator; but I could only change the color of the pipe. 
Maybe there could be a mode added to the Configurator to achieve this on every block that works with redstone sensitivity.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.18
**Mekanism:** 9.9.14
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Piefanatic555** [comment]
There may be potential to reopen this.

Modpack: Seaopolis 2 v3.0
uses
Mekanism v10.3.7.476
Forge v43.2.6

Same behavior as described in OP for this ticket: using Configurator on Logistical Transporters of any upgrade tier only changes or restates the color setting. Behavior unchanged across all "Configurate X" settings for the tool.

Tested on other Mekanism pipe variants and was able to change their Redstone Mode as normal.

Expected to change Redstone Mode for the Logistical Transporters to only receive the color setting of the block.
