### ISSUE TITLE
Updating to 4.0.6 causing issues

### ISSUE THREAD

**Issue by m-vlad** [mekanism/Mekanism#5930]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Server crashes when updating from 4.0.3 to 4.0.6

#### Steps to reproduce:
1. Have a server with 4.0.3
2. Try updating to 4.0.5. crashes.
3. See there's a new update and update to 4.0.6, crashes.

#### Version (make sure you are on the latest version before reporting):
**Forge:** .18
**Mekanism:** 4.0.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[pastebin](https://pastebin.com/UPTcZ0Dp)

**Comment by pupnewfster** [comment]
Firstly there is no version of Mekanism called 4.0.3 or 4.0.5 so no idea what you are talking about. But if you read the changelog you will see that it mentions that it is recommended to empty your factories before upgrading. You could probably downgrade mekanism, empty your factories then re-upgrade.
