### ISSUE TITLE
Chemical Injection Chamber disappears

### ISSUE THREAD

**Issue by bloodyraoul** [mekanism/Mekanism#5931]
Sometimes, when you break with a pickaxe or other tool  a chemical injection chamber, the item doesnt pop and disappears.
#### Steps to reproduce:
1. Place a chemical injection chamber
2. Break it with the good tool
3. No item appears

This bug appears randomly on all 1.15.2 versions in single or multiplayer

**Comment by pupnewfster** [comment]
I am not able to reproduce this. Is this on a server or in single player. And what type of pickaxes/tools have you tried breaking it with when this happens? Are they from another mod, given maybe it is some weird cross mod interaction.

**Comment by bloodyraoul** [comment]
The bug appears with any pickaxe or atomic disassembler on sologame or on a server
we are using RaoulTech modpack : https://www.curseforge.com/minecraft/modpacks/raoultech

**Comment by aidancbrady** [comment]
Unable to reproduce this. If this recurs or occurs with other blocks, let us know.
