### ISSUE TITLE
Problem with Digital Miner

### ISSUE THREAD

**Issue by KaxelDreamhack123** [mekanism/Mekanism#5932]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I launch Digital Miner(any ores and blocks) it doesnt mine.

#### Steps to reproduce:
1.Place Digital Miner in any worlds.
2.Go to mining configuration settings.
3. Choose any block and watch digital miner inventory.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2 - 31.1.18
**Mekanism:** 1.15.2-9.9.14.406
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Lavan** [comment]
For me it looks like it's mining (as in it's counting down the number of block to mine, but nothing comes out of it.

**Comment by pupnewfster** [comment]
Do you have minecolonies installed, given if so my guess is it is stopping the miner see #5886 for more info. The comments also contain information about a config option to allow the miner to be able to mine.

**Comment by Lavan** [comment]
No, I don't have Minecolonies installed. The only "major" mod I have installed is Mekanism.

**Comment by pupnewfster** [comment]
I think I managed to track it down... When I was fixing a few issues with the digital miner's sidedness https://github.com/mekanism/Mekanism/commit/5fb793d3f3b325bc3104a382aba6f80dd303bf93#diff-484c7eea70f1d1e3f34d0c47a7ebe2e3 I guess I forgot to test to confirm the miner could still mine (I only tested inserting and extracting from it). So it fails to add the items to the miner when it mines them.

**Comment by Lavan** [comment]
Awesome! (That you found it I mean). When do you think the update will be out?
