### ISSUE TITLE
Scrolling not working correctly in digital miner filter GUI

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#5933]
#### Issue description:
When scrolling inside the GUI, the elements shown don't match with the object after clicking on it. 

#### Steps to reproduce:
1. Fill filter with more than 4 items
2. Scroll up
3. Select item

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.18
**Mekanism:** Mekanism-1.15.2-9.9.14.406

Demonstration: https://gfycat.com/AgreeableNewBarracuda

**Comment by pupnewfster** [comment]
I will look into this later, but I just want to confirm this is on a server (and that I presume you can't reproduce it in single player?). Mainly just asking given if it is reproduceable in single player it will make debugging it a bit easier, though we will make sure to fix the desync regardless.

**Comment by Darkere** [comment]
Happens in singleplayer.
