### ISSUE TITLE
Tesselating block?

### ISSUE THREAD

**Issue by kornfan6589** [mekanism/Mekanism#5936]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Moving around our world and loaded some chunks that have mechanical pipe, crashed game. reason appears to be array out of bounds on tesselating blocks.

#### Steps to reproduce:
1. Log in
2. Load a chunk with ultimate mechanical pipe?
3. Random issue, sometimes happens consistently, other not so much.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.16
**Mekanism:** 9.9.11.403
**Other relevant version:** 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/mTz8fmKv

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Not quite sure *why* this happens or anything, but I did realize this should actually be relatively easy to fix just by giving an initial size to the map of what the max map size is so that it doesn't have to rehash things.
