### ISSUE TITLE
Project Red, Frames with multiblocks dissapear when moved by a Frame Motor, Doesn't happen when Mekanism is not installed

### ISSUE THREAD

**Issue by TortugoRTS** [mekanism/Mekanism#5937]
Issue description:
Title

 Steps to reproduce:
1. Set up Frame Motor
2. Set a Frame with internal multiblocks (either pressure tubes, red alloy wires, or covers
3. Activate Frame Motor and wait 30 seconds
4. Frame dissapears

#### Version (make sure you are on the latest version before reporting):
Forge:
Mekanism: 9.8.3.390
Minecraft Version: 1.12.2
CCL Version: 3.2.3.357
FMP Version: 2.6.2.83
MrTJPCore Version: 2.1.4.43
ProjectRed Version: 4.9.4.120

Error on minecraft console

<img width="436" alt="Capturar" src="https://user-images.githubusercontent.com/61862848/76065313-29c26800-5f6a-11ea-82c9-516f74f16f22.PNG">

Log:https://gist.github.com/TortugoRTS/7777aaaf88a3d19caf99d52b2b4eb7bd

Mekanism seems to mess with projectred bug detection, making it delete the Frames if they are multiblocks

Video shows bug being reproduced

https://videobin.org/+16x1/1cyz.html

**Comment by TortugoRTS** [comment]
Modpack is FTB Revelations with extra mods

**Comment by aidancbrady** [comment]
Unfortunately we are no longer supporting 1.12- all development is focused on 1.15 right now. We will definitely do through testing once ProjectRed updates for 1.15. In the meantime, I don’t see any references to Mekanism in the log that would cause the issue you mentioned.

**Comment by aidancbrady** [comment]
There’s a good chance that Forge Multipart is actually responsible for the issue, as this is installed by Mekanism before launch in 1.12 I believe.

**Comment by pupnewfster** [comment]
@aidancbrady Mekanism doesn't integrate at all with forge multipart if memory serves, just with MCMultipart (a different multipart API)

**Comment by aidancbrady** [comment]
Ah. McMultipart in that case :)
