### ISSUE TITLE
Infinite ingots generation with basic smelting factory

### ISSUE THREAD

**Issue by bloodyraoul** [mekanism/Mekanism#5938]
I have put any ore power in basic smelting factory configured with auto eject items
I have put a basic logistic transporter taking generated ingots to a chest

When the ingot is cooked, infinite ingots are generated in the transporter and go to the chest forever if you let the generated ingots in the output of the smelting factory.
If you remove it, it stops

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.1.18
**Mekanism: 9.9.14.406

**Comment by leofgiam** [comment]
I can confirm this happened to me yesterday. However, I logged out to recreate the issue on a creative test world, and when I relogged on my main world the issue stopped. Only one ore generated at a time. I think reloading stopped the issue. But it happened the very first time the same as @bloodyraoul told it.

**Comment by aidancbrady** [comment]
Any upgrades installed? Which side of the smelting factory are you ejecting from? Is this reproducible in single player? I'm unable to reproduce this locally.

**Comment by leofgiam** [comment]
> Any upgrades installed? Which side of the smelting factory are you ejecting from? Is this reproducible in single player? I'm unable to reproduce this locally.

No upgrades at the time. It was ejecting from the back side of the smelter to a single chest and the Logistical Sorter on top of it. (Setup like the picture)

![2020-03-06_16 38 40](https://user-images.githubusercontent.com/60528167/76116570-fbc04080-5fc8-11ea-8731-57ede1a706e9.png)

**Comment by aidancbrady** [comment]
Is this on a server?

**Comment by leofgiam** [comment]
> Is this on a server?

Local world, open in LAN.

**Comment by aidancbrady** [comment]
Hmm. Let me know if you're able to at least semi-consistently reproduce it- I'm unable to.

**Comment by bloodyraoul** [comment]
Yes, I am on a server
There are 8 energy upgrade installed
the items are ejected to the left side in a basic logistic transporter, then go in a chest.
I have tried to reproduce it in local without success....

**Comment by aidancbrady** [comment]
@leofgiam, would you mind posting your logs? We have some printouts to see if inventory access fails.

**Comment by leofgiam** [comment]
> @leofgiam, would you mind posting your logs? We have some printouts to see if inventory access fails.

Sure. What logs do you need and where do I find them?

**Comment by aidancbrady** [comment]
@bloodyraoul, do you know if the chest the transporter is feeding into is full or near-full?

@leofgiam, it would be 'debug.log' in your minecraft directory (assuming the issue occurred during the last time you had MC open, or while you currently have MC open).

**Comment by aidancbrady** [comment]
Also, is the factory on auto-sort mode in either of these cases?

**Comment by leofgiam** [comment]
For me the issue ocurred yesterday. And when it "solved" itselft after relogging, I continued playing on the world. So I'm providing all the logs I have from yesterday, and the last one also. But remember the error ocurred on March the 5th.

P.S.: Auto-sort was enabled.

[debug.log](https://github.com/mekanism/Mekanism/files/4300605/debug.log)
[debug-1.log](https://github.com/mekanism/Mekanism/files/4300606/debug-1.log)
[debug-2.log](https://github.com/mekanism/Mekanism/files/4300607/debug-2.log)
[debug-3.log](https://github.com/mekanism/Mekanism/files/4300608/debug-3.log)
[debug-4.log](https://github.com/mekanism/Mekanism/files/4300609/debug-4.log)

**Comment by aidancbrady** [comment]
Thanks so much for the logs. When you say 'relogging,' do you mean exiting the LAN world, loading it again, then opening it to LAN again?

**Comment by leofgiam** [comment]
> Thanks so much for the logs. When you say 'relogging,' do you mean exiting the LAN world, loading it again, then opening it to LAN again?

Exactly or not even reopening it to LAN again, just loading the world locally.

**Comment by aidancbrady** [comment]
One other clarification. Your screenshot appears to show that your smelting factory is not connected to a transporter, but is directly adjacent to a chest I'm assuming it's outputting to. Is this correct- you're encountering the issue without any transporters involved?

**Comment by leofgiam** [comment]
> One other clarification. Your screenshot appears to show that your smelting factory is not connected to a transporter, but is directly adjacent to a chest I'm assuming it's outputting to. Is this correct- you're encountering the issue without any transporters involved?

That's right. The smelter outputs to a single chest, and only then a transporter is attached to said chest. I had to do it like that for space reasons and it was like this when the dupp issue ocurred.

Electric Smelter > Chest > Logistical Transporter

**Comment by bloodyraoul** [comment]
> @bloodyraoul, do you know if the chest the transporter is feeding into is full or near-full?
it is empty

**Comment by bloodyraoul** [comment]
I dont know if you have fixed something about it in the 9.9.15.407 but I cannot reproduce it anymore
