### ISSUE TITLE
Break MultiBlock Machine have no loot (1.12.2)

### ISSUE THREAD

**Issue by kuzuanpa** [mekanism/Mekanism#5939]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Break MultiBlock Machine's (such as ‘wind generator’ or ‘digital miner’) boundingblock with "Atomic disassembler" "extend vein" mode will have no loot ,all block will disappear and there have nothing in ground...

#### Steps to reproduce:
1.put an digital miner
2.turn the "Atomic disassembler" to "extend vein" mode
3.break the bounding block (not the main block)
4.the machine will break and no loot in ground
(gif is here)
![record](https://user-images.githubusercontent.com/61902985/76141445-457b5a80-609f-11ea-8905-1528f4117988.gif)

)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.5.2847
**Mekanism:** 1.12.2-9.8.3.390
**Other relevant version:** MCMulitPart version 2.5.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Yoosk** [comment]
1.12.2 is no longer supported.

**Comment by kuzuanpa** [comment]
> 1.12.2 is no longer supported.

ok,i'm sorry to trouble you

**Comment by pupnewfster** [comment]
Ya this has been fixed in 1.15 when I rewrote the extended vein mine mode.
