### ISSUE TITLE
Rotary Condensentrator does not work at all

### ISSUE THREAD

**Issue by Apot98** [mekanism/Mekanism#5940]
#### Issue description:
Rotary Condensentrator does not work in Decondensentrate Mode with Liquid Lithium and power:
![decondensentrate](https://user-images.githubusercontent.com/20492252/76144362-7452fa00-60ba-11ea-93a2-2fdaa86eebad.png)

#### Steps to reproduce:
1.Set a Rotary Condensentrator in Decondensentrate mode, pump Liquid Lithium from Evaporation tower, and power it;
2.Watch if it's working or not.

#### Version (make sure you are on the latest version before reporting):
**Forge:1.15.2-forge-31.1.16** 
**Mekanism:Mekanism-1.15.2-9.9.15.407** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Apot98** [comment]
It turns out that Rotary Condensentrator recipe is completely broken, that I cannot do any condensentrate or decondensentrate process, such as Ethylene, Water vapor, etc.

**Comment by Apot98** [comment]
No, the Condensentrator recieves liquid/gas properly, but don't convert any.

**Comment by pupnewfster** [comment]
I understand that, my guess is that I restricted inserting into the tanks, not allowing for outputs. If you mean the reason I linked that issue is someone commented on it that it is accepting water but is not producing water vapor. So I redirected that person to this issue.

**Comment by jerdm** [comment]
HI.
I have the same problem with the Rotary Condensentrator. I put water and it doesn't turn it into water vapor. in decondensentrating mode. The machine has water and energy, but it does nothing.

**Comment by pupnewfster** [comment]
The reason this issue is just labeled fixed in dev, and is not closed is that it is only fixed it dev at the moment... so this is known

**Comment by jerdm** [comment]
oh thank. sorry

**Comment by jmgooden94** [comment]
Seems to be fixed, thanks. We were able to make HDPE pellets and Lithium just fine now.

**Comment by XTeamXeno** [comment]
It now does not work w/ o2

**Comment by Conversage** [comment]
doesnt work with Uranium hexafloride and Fissile Fuel

**Comment by pupnewfster** [comment]
> doesnt work with Uranium hexafloride and Fissile Fuel

Could you open another issue for this, as it isn't really related to this at all as the reason it doesn't "work" is there is no fluid version of those chemicals. Now I am not sure if we are going to end up adding those or not as it may be intended they don't have one, but if it has its own issue it will be easier to keep track of for when I talk to aidan at some point before 10.1 about various balance decisions.

**Comment by Chaos02** [comment]
Hey I'm somewhat still having this issue on 1.18.2:
![image](https://github.com/mekanism/Mekanism/assets/20928702/0e2f0365-c73d-40aa-9680-73d4fcd7f91b)

As you can see the machine has energy, water redstone mode is ignored and it is able to produce liquid ethylene, however no water vapor apparently... Left tank reads <empty>

EDIT:
Once I clicked with a gauge dropper on the full water side it magically started doing stuff
