### ISSUE TITLE
Consider bamboo as biomatter to make Biofuel on the Crusher

### ISSUE THREAD

**Issue by leofgiam** [mekanism/Mekanism#5941]
**Describe the the feature you'd like**
The ability to process bamboo on the Crusher to make Biofuel.

**Describe alternatives you've considered**

**Additional context**

**Comment by pupnewfster** [comment]
I will leave this open to get @aidancbrady 's opinion on the matter, but I believe the answer is going to be:

If you want it to be considered for making Biofuel you can always add your own recipe via data packs. We recently changed the base recipes we have for bio fuel values to be calculated based on vanilla's numbers of how efficient various items are in the composter. I am not sure if we want to be having to maintain an additional list/amounts (I will leave that to aidan to decide).

**Comment by aidancbrady** [comment]
@pupnewfster +1

We support all the item inputs of the Composter (which is a pretty long list). It's trivial to add support for new items via data packs.
