### ISSUE TITLE
Jam inside wires

### ISSUE THREAD

**Issue by KaxelDreamhack123** [mekanism/Mekanism#5943]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I put the wire above me and there is a wire under me and connect them, then I insert the wire into myself.

#### Steps to reproduce:
1.Connect  two wires together in the middle.
2.Maybe will not work because of need stay at hight(When I connect two wires from : It home and Wind Generator).
3. Swimming animation should play.
#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2 - 31.1.18
**Mekanism:** 1.15.2-9.9.15.407
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by aidancbrady** [comment]
Fixed in 7c0f0cd.
