### ISSUE TITLE
Very lagging when electrolytic separator lacks energy.

### ISSUE THREAD

**Issue by KaxelDreamhack123** [mekanism/Mekanism#5944]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Maybe this is my computer very lagging, but i dont know.

#### Steps to reproduce:
1.Connect electrolytic separator with any energy support.
2.When not have enough energy, watch to electrolytic separator
3.Enjoy ;)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2 - 31.1.18
**Mekanism:** 1.15.2-9.9.15.407
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
This is in part due to your computer, but we are tracking the issue here: #5848 as it has to do with us not having reimplemented the active duration checks yet.
