### ISSUE TITLE
Not working system auto-eject with crusher and enrichment chamber.

### ISSUE THREAD

**Issue by KaxelDreamhack123** [mekanism/Mekanism#5945]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description
This is machine not want working with system auto-eject. Even when I set up import and output for both machines correctly(Crusher and Enrichment Chamber). I play on server.
#### Steps to reproduce:
1. Placing 3 machines(Purification Chamber, Crusher, Enrichment Chamber). Crusher and Purification Chamber are working well.
2.Put any ore in p- chamber.
3.Crusher dont want give away enri- chamber his dust.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2 - 31.1.18
**Mekanism:** 1.15.2-9.9.15.407
**Other relevant version:** 

![2020-03-07_21 46 06](https://user-images.githubusercontent.com/61834161/76150746-d0b81880-60be-11ea-8d56-ef9e09088adc.png)
![2020-03-07_21 46 14](https://user-images.githubusercontent.com/61834161/76150747-d1e94580-60be-11ea-949b-f81a52bf14c1.png)

**Comment by aidancbrady** [comment]
Hi! I'm unable to reproduce this issue. A few questions:

- Can I see your configuration for both the Crusher and Enrichment Chamber?
- Are you on singleplayer or on a server?
- What are you trying to crush?

**Comment by KaxelDreamhack123** [comment]
> Hi! I'm unable to reproduce this issue. A few questions:
> 
> * Can I see your configuration for both the Crusher and Enrichment Chamber?
> * ~Are you on singleplayer or on a server?~ I see you're on a server.
> * What are you trying to crush?

Omg.... I sleep on today morning, join in my server, put ore and... 
EVERYTHING EARNED. I didnt change anything. Ohh this is version 1.15.2....For some reason, but it worked. I dont understand how, but it worked. 
Sorry for your time. 

Here by the way pictures from configs (From left to right: Enri-Chamber and Crusher).
![2020-03-08_08 28 43](https://user-images.githubusercontent.com/61834161/76157292-caa25600-6117-11ea-904a-81e4507e864e.png)
![crusher](https://user-images.githubusercontent.com/61834161/76157293-cbd38300-6117-11ea-9f6a-51a410b52ac2.png)

**Comment by aidancbrady** [comment]
Thanks for the followup. Let me know if the issue occurs again.

**Comment by Polosolo12** [comment]
I am now having this problem. I double, triple, and quadruple check and the input/output configuration is correct. From purification to crusher is fine, but the dirty ore just will not go into the enrichment chamber... However, I am also using a modpack so there isnt any way to single out a problem... Just letting you know I had this same EXACT problem.
