### ISSUE TITLE
Bug with Atomic dissambler.

### ISSUE THREAD

**Issue by KaxelDreamhack123** [mekanism/Mekanism#5947]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I mine sand under water in mode "extreme vein mining" it dont work. 

#### Steps to reproduce:
1.Take atomic dissambler.
2.Put sand, and pour a bucket of water on it, but on all sides
3. Try to get.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2 - 31.1.18
**Mekanism:** 1.15.2-9.9.15.407
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by aidancbrady** [comment]
Unable to reproduce this. Are you sure you're on Extended Mining and not 'Off' mode? Are you on a server?

**Comment by pupnewfster** [comment]
Also do you have any other mods installed, and if so can you reproduce it with just Mekanism installed? As this sort of sounds like some mod is for some reason making water able to be targeted.
