### ISSUE TITLE
Rotary Condensentrator

### ISSUE THREAD

**Issue by itsjustchrisbro** [mekanism/Mekanism#5948]
08 MAR 2020 

The Rotary condensentrator is bugged or just broken because i cannot get ethylene or hyrdrogen or any gas to turn into their respective liquid. I am on the most updated version of mekanism that came out about 2 days ago and I was wondering if anyone else was encountering these same problems that I am having. Also the digital miner is also buggy and it leads to some crashes when you click into the menu of the GUI.

**Comment by Yoosk** [comment]
Did you miss the issue template while creating this? That's not a valid report you made here.

**Comment by pupnewfster** [comment]
Also #5940
