### ISSUE TITLE
Enriching dupe

### ISSUE THREAD

**Issue by Sunekaer** [mekanism/Mekanism#5949]
Basic Enriching Factory auto-eject doesn't remove items from inventory but does input them to the chest 

https://s1.sunekaer.com/i/08-03-2020_18-39-54_%25pn.gif

I haven't checked if the other machines also do with it when using auto-eject

#### Version (make sure you are on the latest version before reporting):
**Forge:31.1.18
**Mekanism:** 9.9.15.407

**Comment by aidancbrady** [comment]
Yeah this is the same as #5938. Are you on a server? If not, can you reproduce this in single player?

**Comment by Sunekaer** [comment]
Yes on server, ill test

**Comment by Sunekaer** [comment]
Okay it doesnt happen in SP

**Comment by pupnewfster** [comment]
Closing this/merging this with #5938 as we are using that issue to track the problem.
