### ISSUE TITLE
Config files not working for baby skeletons

### ISSUE THREAD

**Issue by dave1505** [mekanism/Mekanism#5953]
#### Version (make sure you are on the latest version before reporting):
**Forge: 1.12.2-forge1.12.2-14.23.5.2847
**Mekanism: Mekanism-1.12.2-9.8.2.389

**Comment by pupnewfster** [comment]
Last I checked the config worked in 1.12, but as we are no longer developing the 1.12 version of Mekanism, even if this is broken there is not much we can do to help you.

**Comment by dave1505** [comment]
Like it would hurt to correct a simple mistake in the version 99.9% of people downloaded your mod in -.-

**Comment by Yoosk** [comment]
Is there any reason you are using old version of mekanism?

**Comment by dave1505** [comment]
> Is there any reason you are using old version of mekanism?

![Screenshot_2](https://user-images.githubusercontent.com/34339148/76329823-f9215c00-62e4-11ea-9f4a-74ab113f250b.png)
![Screenshot_1](https://user-images.githubusercontent.com/34339148/76329829-fa528900-62e4-11ea-9cbe-ce33c0ce6915.png)

I believe I can say it in the name of many people that 1.12.2 is the minecraft version that contains by far the best number and quality of mods. I've been improving my mod pack over the years to reach something special. This game's real potencial lies in how much it is customizable, and the new versions, even being well improved, will lose many great mods since every creator will eventualy leave their projects. Having this mod working well with the other 150 I somehow got working well together in 1.12.2 is an achievment.

**Comment by Yoosk** [comment]
I meant your 1.12.2 version. The one you listed, was not latest (389), and its not an achievement to make it work together with 150 other mods, that's at best decent.
