### ISSUE TITLE
Game Crash / Server Crash: Moving a "Thermal Evaporation Block" with a piston.

### ISSUE THREAD

**Issue by LilyLicht** [mekanism/Mekanism#5954]
The game and the server crashed while moving a Thermal Evaporation Block with a piston.

 Error:
> Description: Ticking block entity
> 
> java.lang.NullPointerException: Ticking block entity
> 	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_145829_t(TileEntityBasicBlock.java:149)
> 	at vazkii.quark.automation.feature.PistonsMoveTEs.getAndClearMovement(PistonsMoveTEs.java:201)
> 	at vazkii.quark.automation.feature.PistonsMoveTEs.setPistonBlock(PistonsMoveTEs.java:121)
> 	at vazkii.quark.base.asm.ASMHooks.setPistonBlock(ASMHooks.java:151)
> 	at net.minecraft.tileentity.TileEntityPiston.func_73660_a(TileEntityPiston.java:337)
> 	at net.minecraft.world.World.func_72939_s(World.java:1838)
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
> 	at net.minecraft.client.main.Main.main(SourceFile:123)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by pupnewfster** [comment]
What version of Mekanism is this?

**Comment by S4t0n3** [comment]
Mekanism-1.12.2-9.8.3.390
MekanismGenerators-1.12.2-9.8.3.390
MekanismTools-1.12.2-9.8.3.390

**Comment by pupnewfster** [comment]
My guess is that this is a bug with quark making TileEntities pushable, given if memory serves they are not natively pushable in 1.12. If this still occurs in 1.15, then feel free to open another issue and I can look into it more at that time, given I believe that Mojang did introduce a way for know if a Tile is being moved.

**Comment by LilyLicht** [comment]
Approved. Error came with Quark.
