### ISSUE TITLE
Mekanism, chisel and bits or other cover systems?

### ISSUE THREAD

**Issue by victoroos** [mekanism/Mekanism#5955]
Hi All

I'm trying to cover the pipes of mekanism.
BVut I'm reading on the internet a lot of things. Chise and bits should work apparently, but I can't get it to place in the block with the pipe.

Any tips?

vkr
victor
#### Version (make sure you are on the latest version before reporting):
**Forge:forge1.12.2-14.23.5.2847
**Mekanism:Mekanism-1.12.2-9.8.3.390
**Other relevant version:**

**Comment by pupnewfster** [comment]
Mekanism in 1.12 supports any mods that support the MCMultipart API. I believe chisel and bits does support this API but does not require it. So my guess is that you just don't have MCMultipart installed.
