### ISSUE TITLE
Server Startup Hang

### ISSUE THREAD

**Issue by ppoozl** [mekanism/Mekanism#5956]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Server Hang on Startup

#### Steps to reproduce:(maybe?)
1.place digitial miner
2.restart server
3.hang

#### Version (make sure you are on the latest version before reporting):
**Forge:31.1.18 
**Mekanism:9.9.15.407 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]
[debug.log](https://github.com/mekanism/Mekanism/files/4317818/debug.log)
digitial miner

**Comment by pupnewfster** [comment]
Rerouting this to #5897 as that is my best guess based on your debug.log
