### ISSUE TITLE
crash on launch 1.15.2

### ISSUE THREAD

**Issue by SDUBZ** [mekanism/Mekanism#5958]
Forge: 31.1.18
mek and addons: 9.9.15.407

#### Issue description:
Crashes on launch

#### Steps to reproduce:
1.load up game with versions mentioned
2.crash occurs
3.

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2020-03-11_08.52.41-client.txt](https://github.com/mekanism/Mekanism/files/4318992/crash-2020-03-11_08.52.41-client.txt)

**Comment by pupnewfster** [comment]
Please provide your latest log, as this crash report shows no useful information due to https://github.com/MinecraftForge/MinecraftForge/issues/6374

**Comment by SDUBZ** [comment]
[latest (1).log](https://github.com/mekanism/Mekanism/files/4321462/latest.1.log)

**Comment by pupnewfster** [comment]
Seems to be a lot of errors listed for various mods with "Not enough data available". RFTools storage is the first one listed, not sure if it is to blame and caused them all or if it is some bug in Night config, but I don't believe mekanism is at fault here.
```
[09:20:42] [modloading-worker-12/ERROR]: Failed to create mod instance. ModID: rftoolsstorage, class mcjty.rftoolsstorage.RFToolsStorage
com.electronwill.nightconfig.core.io.ParsingException: Not enough data available
```
