### ISSUE TITLE
[1.12.2] The One Probe doens't show correct power level

### ISSUE THREAD

**Issue by DevTimur** [mekanism/Mekanism#5960]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Energy Cubes and Induction Power Storage doesn't show correct power level using The One Probe.
I asked TOP developer to fix it, but he claim it's Mek's problem.
https://github.com/McJtyMods/TheOneProbe/issues/368

#### Steps to reproduce:
1. Install Mekanism
2. Install TOP
3. Look at Energy cube with more then 2.1 GRF

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** Mekanism-1.12.2-9.8.3.390
**Other relevant version:** 

![image](https://user-images.githubusercontent.com/22171136/76516090-812d7000-6463-11ea-8f21-46ed59b3478d.png)

**Comment by pupnewfster** [comment]
This won't be fixed in 1.12 as we are no longer developing for that version, but I will leave this open given we may look at some point into fixing this for 1.15

**Comment by aidancbrady** [comment]
This actually ties into the overarching issue of #3624. We definitely have plans to fix this at some point.
