### ISSUE TITLE
Digital Miner + Quantum Entangloporter Issue (Chunkloading?)

### ISSUE THREAD

**Issue by RaccolAIK** [mekanism/Mekanism#5968]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Hi. I will try to describe this in the best way that I can. Please ask questions if you do not understand.

I am trying to set up a system where I can move my digital miner anywhere while it is still able to have a constant supply of power (which comes FROM my base) and is able to output the materials it mines to my ore processing system (TO my base). So I set up a quantum entangloporter (I will call it QE 1) in my base, where energy is inputted to it. This is transferred to QE 2, which I have set a reasonable distance away from my base, which outputs the power to a digital miner. The digital miner's output system is then piped into QE 2 (its item sides are all set to input) which goes back to QE 1. QE 1 then outputs the items it receives from QE 2 to a logistical sorter (beginning the ore processing system that is not the issue here).

This seems to only work temporarily. Eventually, it just stops and stalls. As in, the items stop auto ejecting from the miner to QE 2. This does not seem to be an issue with power, because the digital miner is still getting a constant supply of power. But eventually I'll be in my base and notice that nothing is coming to QE 1 anymore. This problem still persists when I upgrade both QEs and the miner with an anchor upgrade. One odd thing about this is, when I reload the world, only a handful of items are sent to QE 2. The rest just stay in the digital miner and it starts to buildup/stall. Yes, they are both on the same channel.

Chunkloading is also allowed on mekanism's config.

Any help would be appreciated. Thank you very much!

#### Steps to reproduce:
1. Place a QE (call it QE 1). Connect it to a power cable (input) and have it output to a logistical transporter that goes into a chest (or whatever. For me it's an ore processing setup but I wouldn't imagine it matters where it goes).

2. Travel a reasonable amount of distance. Place a DM and a QE (call it QE 2). Have QE 2 output the power from QE 1 and send it to the DM. Have DM autoeject its items to an item input slot on QE 2. Use a configurator if necessary.

3. Try to travel away from your base and digital miner. Then return and see if the ores are still being sent to QE 1. For me, I just had to go downstairs and start working and eventually things started to stall.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2768
**Mekanism:** 9.8.3.390
**Other relevant version:**

**Comment by Lavan** [comment]
I have a similar setup with Forge 31.1.22 and Mekanism 9.9.16 and it works perfectly. Only difference is that I use two QEs as I try to avoid sending multiple resources over the same frequency.

**Comment by RaccolAIK** [comment]
> I have a similar setup with Forge 31.1.22 and Mekanism 9.9.16 and it works perfectly. Only difference is that I use two QEs as I try to avoid sending multiple resources over the same frequency.

Correct me if I'm wrong but that's for 1.15 only. Sorry for not making it clear before, but I am on 1.12. Haven't updated because the other mods I am using have not updated to 1.15 yet.

**Comment by Lavan** [comment]
You're quite right, forgot to mention that. My purpose for commenting was to help the developer to limit the issue to a specific version.

**Comment by pupnewfster** [comment]
Ya my guess is this has something to do with how things used to work (or didn't), given the chunk loading system is entirely different though and as Lavan has said it works fine in 1.15, I am going to go ahead and close this given we are not actively developing for 1.12 anymore.
