### ISSUE TITLE
[1.15.2]A very urgent problem

### ISSUE THREAD

**Issue by EnterFor** [mekanism/Mekanism#5969]
* both Please use the search functionality before reporting an issue. Also take a look at the closed issues! *

Issue description:

When I started the server, I got stuck. I don't know whose problem it was

It's very urgent. I don't want to lose my file

Steps to reproduce:

1. Install Immersive Portals for Forge

2. Install Mekanism

3. Start the server

Make sure you are on the latest Version before reporting:

* * Forge: 31.1.18

* * Mekanism: Mekanism - 1.15.2-9.9.16.408. Jar

**Other relevant version:immersive-portals-0.6(for MC 1.15 with forge).jar

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://github.com/qouteall/ImmersivePortalsModForForge/issues/52

**Comment by pupnewfster** [comment]
From the log it looks like this might be in part due to #5897. So I am closing this and routing it there, though given I am not really sure what is going on in that issue it may be helpful to know if you can load your world *without* immersive portals.

**Comment by EnterFor** [comment]
> 从日志看来，这可能部分是由于[＃5897引起的](https://github.com/mekanism/Mekanism/issues/5897)。因此，我正在关闭此路由并将其路由到那里，尽管鉴于我不确定该问题正在发生什么，所以了解是否可以在_没有_沉浸式门户的_情况下_加载您的世界可能会有所帮助。

When I deleted the immersiveportals, I still couldn't access the game. I had to delete Mekanism
It felt like the immersiveportals had corrupted my archive

**Comment by EnterFor** [comment]
> From the log it looks like this might be in part due to #5897. So I am closing this and routing it there, though given I am not really sure what is going on in that issue it may be helpful to know if you can load your world _without_ immersive portals.

So what am I going to do now, I'm not good at English, I don't quite understand what you mean
I'm very sorry

**Comment by Apot98** [comment]
> > From the log it looks like this might be in part due to #5897. So I am closing this and routing it there, though given I am not really sure what is going on in that issue it may be helpful to know if you can load your world _without_ immersive portals.
> 
> So what am I going to do now, I'm not good at English, I don't quite understand what you mean
> I'm very sorry
 “从日志文件上看这一定程度上可能是 #5897 的原因，所以我决定关闭这个issue并贴在另一个的下面，不过鉴于我不太清楚到底是怎么造成的，希望你能试试不使用immersive portals启动游戏并告诉我结果”

**Comment by EnterFor** [comment]
> > > From the log it looks like this might be in part due to #5897. So I am closing this and routing it there, though given I am not really sure what is going on in that issue it may be helpful to know if you can load your world _without_ immersive portals.
> > 
> > 
> > So what am I going to do now, I'm not good at English, I don't quite understand what you mean
> > I'm very sorry
> 
> “从日志文件上看这一定程度上可能是 #5897 的原因，所以我决定关闭这个issue并贴在另一个的下面，不过鉴于我不太清楚到底是怎么造成的，希望你能试试不使用immersive portals启动游戏并告诉我结果”

谢谢，这样我明白了。但是我删除了immersive portals也不能启动，只能删除MEK才可以，我有一个想法，我准备用MCEdit，删除数字采矿机方块，我感觉是锚升级引起的
