### ISSUE TITLE
[1.15.2]Wrong pipe position

### ISSUE THREAD

**Issue by EnterFor** [mekanism/Mekanism#5971]
both Please use the search functionality before reporting an issue. Also take a look at the closed issues! *
Issue description:

Wrong pipe position
When I remove a pipe and reconnect it, I temporarily fix the problem.
But it will happen again after a while

Steps to reproduce:

Install Mekanism

Enter the game

Check the pipeline

Make sure you are on the latest Version before reporting:

Forge: 31.1.18
Mekanism: Mekanism - 1.15.2-9.9.16.408. Jar

screen capture：https://i.loli.net/2020/03/16/5VCs4iUvhRHyPgO.png

**Comment by EnterFor** [comment]
I asked someone else to test it
He has the same problem

**Comment by pupnewfster** [comment]
#5922
