### ISSUE TITLE
Rendering bug

### ISSUE THREAD

**Issue by BLucky-gh** [mekanism/Mekanism#5975]
### Issue description:
Trying to render some stuff makes my minecraft window go blank. I'm playing all the mods 3 with a couple of other mods which I will mention later because I cannot remember them all at once (5-6 mods)

#### Steps to reproduce:
1. Grab configurator
2. Point at a machine (most machines, but not all, I think it's the ones with side configs available)
3. Screen goes blank

OR

1. Grab bio-generator
2. start filling it
3. screen will be blank until the bio generator is either empty or at least ~10% full.

OR

1. Build the Thermal evaporation plant
2. fill with water
3. screen goes blank.

In all cases, the game is still running and you start seeing as soon as the problematic thing is no longer in your field of view (afaik it's VanillaFix that stops rendering what you don't see, but I'm not sure).

#### Version (make sure you are on the latest version before reporting):
**Minecraft: 1.12.2**
**Forge: latest for 1.12.2 afaik (14.23.5.2847)** 
**Mekanism:9.8.0.381** 

Didn't crash so no crash log, but it might be relevant that I'm on Mac, since I know some mods that have OS specific issues

**Comment by pupnewfster** [comment]
It doesn't have to do with a configurator. 9.8.0 had a lot of rendering changes on our end, which were mostly fixed in 9.8.1, and then the remaining of which I believe got fixed in 9.8.2. I would recommend updating the the latest 1.12 version of mekanism 9.8.3
