### ISSUE TITLE
No Fussion reactor blocks

### ISSUE THREAD

**Issue by ZaosDaOne** [mekanism/Mekanism#5976]
I have the latest version installed (Mekanism-1.12.2-9.8.3.390) on both my server and client, However none of the fussion reactor blocks like the reactor frame shows up. It doesnt show up in Just enough items and when I try crafting it, it just doesnt output anything. I can still craft other mekanism blocks.

**Comment by pupnewfster** [comment]
Do you have mekanism generators installed?

**Comment by ZaosDaOne** [comment]
Oh, I didn't know I needed that, My bad.
