### ISSUE TITLE
Digital miner causing server to not start

### ISSUE THREAD

**Issue by Lavan** [mekanism/Mekanism#5978]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

I'm getting the followin error in the server log:

[10:38:30] [Server thread/WARN] [Mekanism ChunkManager/]: Tile at BlockPos{x=7, y=87, z=1523} was either null or not an IChunkLoader?! Tile: null

At that position is my Digital Miner with two Quantum Entangloporters connected. One for output and one for power.

The DM was fully upgraded with **Speed** and **Energy** upgrades as well as an **Anchor** upgrade.

The DM was active but had exhausted all mineable resources within its configured range/filter.

#### Steps to reproduce:
1. Set up a DM with energy and storage or as above. Place it in a chunk away from the spawnpoint so that the **Anchor** upgrade actually is required.
2. Add a configuration
3. Let it exhaust the resources
4. Save world and restart -> fail

I managed to replicate the issue in singleplayer after opening the game to LAN play once and restarting. 

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.1.25
**Mekanism: 9.9.16
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

See above.

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Apot98** [comment]
Probably same with issue #5897

**Comment by Lavan** [comment]
> Probably same with issue #5897

Yes, you are probably right. I would like to add some more information though. I have noticed that whenever the issue happens I have two choices.
1. Delete the region file that contains the faulty block (with the Digital Miner) that is causing the issue.
1. Delete the `mekanism_force_chunks.dat` file.

The first one obviously causes a very large area to be regenerated and I really don't know the full effect of the second alternative.

**Comment by Yoosk** [comment]
I had to delete the said file, then disable anchor upgrade to make sure and it worked fine. Region and world stayed untouched.
https://s.yoosk.pl/vMSU7

**Comment by pupnewfster** [comment]
I believe the freezing on loading issue is now properly fixed.
