### ISSUE TITLE
[1.15.2-9.9.16.408] Clientside render crash when placing down Elite Logical Transporter to Obsidian Chest

### ISSUE THREAD

**Issue by shortybsd** [mekanism/Mekanism#5982]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Placing down an Elite Logical Transporter pipe attached from an Obsidian chest to Quantum Entangloporter caused the crash. 
**Note:** This doesn't happen every time.
**Update:** My fiance warped to my 5 times ore processing plant in the desert and had the same exact crash. [Link to new crash - pastebin](https://pastebin.com/YhyVRtxP)

#### Steps to reproduce:
1. Attach an Elite Logical Transporter pipe to an Obsidian Chest which is attaches to a Quantum Entangloporter as well.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.25
**Mekanism:** 1.15.2-9.9.16.408
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

**Crash when right clicking, placing a pipe:** [pastebin](https://pastebin.com/4Eh3duVr)
**Update:** 
Any time I go to the 5x ore processing area I crash 9/10 times with 
**Crash teleporting to 5x ore processing area:** [pastebin](https://pastebin.com/FmfivHEy)
**Crash when right clicking any tank there**, 4 out of 5 times I crash with [pastebin](https://pastebin.com/amv61r41)

**Comment by pupnewfster** [comment]
I believe this is fixed in 9.9.17, as code paths have changed a decent bit since 9.9.16, but if it is not, feel free to comment (with a new crash report) and I will reopen the issue and look into it further.

**Comment by shortybsd** [comment]
Working great so far, many thanks. My whole crew thanks you as well, much love bro!
