### ISSUE TITLE
[1.15.2-9.9.15.407] Basic Infusing Factory doesn't connect to any tier of Universal Cable. 

### ISSUE THREAD

**Issue by ralpha6** [mekanism/Mekanism#5983]
#### Issue description:
After using Basic Tier Installer to upgrade Metallurgic Infuser, it no longer connects to any tier of Universal Cable. 
Crafted Basic Infusing Factory connects to any tier Universal Cable just fine.

![2020-03-21_18 49 54](https://user-images.githubusercontent.com/52944170/77238243-e6d8d500-6ba4-11ea-9e95-3b89ef675709.png)

#### Steps to reproduce:
1. Place Metallurgic Infuser
2. Upgrade to Basic Factory using Installer Tier Basic
3. Attempt to connect any Universal Cable.

#### Version (make sure you are on the latest version before reporting):
Pack: Enigmatica5-0.3.8
Forge: 31.1.17
Mekanism: 9.9.15.407
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
no crash

**Comment by pupnewfster** [comment]
Never bothered testing if this actually was an issue, but I can confirm it does connect in 9.9.17.
