### ISSUE TITLE
PRC infinitely sends substrate

### ISSUE THREAD

**Issue by jacksin125** [mekanism/Mekanism#5984]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I set the PRC to output the substrate to a logistic pipe connecting to a chest so I can, you know, keep producing power, the PRC just infinitely outputs substrate. I don't know how it's coded at all, but my guess is that the substrate in the output slot is not getting deleted when it sends it through the pipe.

#### Steps to reproduce:
1.Connect PRC to a basic or advanced logistical transporter
2.Place a chest at the end of the transporter
3.Set the PRC to output items in the right slot

#### Version (make sure you are on the latest version before reporting):
**Forge:**  forge 1.15.2 31.1.25
**Mekanism:** Mekanism 1.15.2 9.9.16.408
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No crash log, as there is no crash.
[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
#5981

**Comment by jacksin125** [comment]
I found a message in the logs that might help:

[22Mar2020 22:47:31.000] [Server thread/WARN] [Mekanism/]: An inventory's returned content count does not line up with InvStack's prediction.
[22Mar2020 22:47:31.001] [Server thread/WARN] [Mekanism/]: InvStack item: 64 substrate, ret: 1 air
[22Mar2020 22:47:31.003] [Server thread/WARN] [Mekanism/]: Tile: mekanism.common.tile.TileEntityPressurizedReactionChamber@77a89262 BlockPos{x=-171, y=57, z=260}

This error repeats many times.

**Comment by pupnewfster** [comment]
That is fine, and that log message will probably help. I plan to look at it some point before the next alpha, though it will be a bit as I am in the middle of rewriting our energy system.

**Comment by aidancbrady** [comment]
Just want to thank you for posting a detailed issue with specifically relevant logs. Reports like this make our job so much easier.
