### ISSUE TITLE
Rotary Condensentrator not working no matter what

### ISSUE THREAD

**Issue by killercoddbz** [mekanism/Mekanism#5986]
First time using github, so forgive me for formatting.

Issue description:

Trying to make lithium from liquid lithium, mechanical pipe inserting on right, decondensentrating setting set, no progress. Has power, pressurized tubes on the left pulling, absolutely no progress whatsoever. 

Steps to reproduce:
1. Place rotary condensentrator
2. Try to utilize either mode of the machine
3. No progress occures 

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.1.18**
**Mekanism: 9.9.15** 
**Other relevant version: Minecraft: 1.15.2**

**Comment by pupnewfster** [comment]
Update mekanism #5940
