### ISSUE TITLE
Free runners don't require power to stop damage

### ISSUE THREAD

**Issue by pupnewfster** [mekanism/Mekanism#5992]
#### Version (make sure you are on the latest version before reporting):
**Mekanism:** 9.9.17

**Comment by NillerMedDild** [comment]
I've received a report that this is happening in `Mekanism-1.16.1-10.0.9.432` again: https://github.com/NillerMedDild/Enigmatica6/issues/281

**Comment by pupnewfster** [comment]
Looking at the code that shouldn't be the case. I haven't tested it myself just now but my guess is they only jumped down a few blocks which isn't always enough in vanilla with no armor to cause damage or that they jumped onto some block that lessens the fall damage.

**Comment by brckts** [comment]
Person who made the report here, for testing I jumped off hundreds of blocks, landing on stone. If that can help somehow

**Comment by NillerMedDild** [comment]
I can confirm that they do drain energy correctly when mitigating fall damage in `Mekanism-1.16.1-10.0.9.432`
