### ISSUE TITLE
1.12.2 Mekanism Unique Item ID

### ISSUE THREAD

**Issue by MMMMMMMNMMMMMMM** [mekanism/Mekanism#5995]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

The /give command doesn't work for getting machines like the pressurized reaction chamber.
example:
/give MMMMMMMNMMMMMMM mekanism:machineblock2:10
It says that the item doesn't exist

#### Steps to reproduce:
1. /give <name> mekanism:machineblock<number>:<number>

#### Version (make sure you are on the latest version before reporting):
**Forge:** ForgeMultipart-1.12.2-2.6.2.83-universal
**Mekanism:** Mekanism-1.12.2-9.8.1.383

**Comment by pupnewfster** [comment]
No idea, my best suggestion is to double check the ID. We are no longer developing the 1.12 version of Mekanism, and ids have changed in the 1.15 version and I am unable to reproduce it with any of them. Secondly I believe the command would be `/give name mekanism:machineblock2 10` not `/give name mekanism:machineblock2:10`

**Comment by MMMMMMMNMMMMMMM** [comment]
That just gives me 10 rotary condensators :/

**Comment by pupnewfster** [comment]
Oh sorry I meant to type `/give name mekanism:machineblock2 1 10`

**Comment by MMMMMMMNMMMMMMM** [comment]
Oh yeah it worked now, thanks!
