### ISSUE TITLE
Formulaic Assemblicator not taking items from a Bin

### ISSUE THREAD

**Issue by leofgiam** [mekanism/Mekanism#5998]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
A Formulaic Assemblicator won't take items from a Bin next to it, even with the sides configured correctly and the Bin in the propper mode (lighted on with the Configurator). It only works with a Logistical Transporter between the blocks doing the work extracting from the Bin.

#### Steps to reproduce:
1. Place a Bin, and a Formulaic Assemblicator next to it.
2. Configure the sides of the F.A. and the recipe also.
3. Put the correct item on the bin, and change it's mode with the configurator. It doesn't move items from the Bin to the F.A.

![2020-03-27_21 48 33](https://user-images.githubusercontent.com/60528167/77810823-6703ac80-7075-11ea-8ad2-6c97b1d8c947.png)
![2020-03-27_21 48 19](https://user-images.githubusercontent.com/60528167/77810829-6bc86080-7075-11ea-840e-1d6d471af478.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.18
**Mekanism:** 9.9.17
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Bins only output downwards when activated.
