### ISSUE TITLE
Buildcraft MJ not working

### ISSUE THREAD

**Issue by Rsslone** [mekanism/Mekanism#5999]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Buildcraft Quarry will not accept Universal Cable connections. The UC claims to support MJ which in the newest builds they switched to exclusively.
https://github.com/BuildCraft/BuildCraft/issues/4486

#### Steps to reproduce:
1. Place Quarry
2. Place Universal Cable next to quarry
3. Observe cable not connecting

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2847
**Mekanism:** Mekanism-1.12.2-9.8.3.390.jar

**Comment by thiakil** [comment]
MJ is only a display format in Mekanism, we don't support the non-rf-based energy system. (ours is electrical, theirs is kinetic)

We're also no longer updating 1.12
