### ISSUE TITLE
keyPressed event handler

### ISSUE THREAD

**Issue by vertex101** [mekanism/Mekanism#6001]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
trying to increase the amount of energy the resistive heater uses just crashes you

#### Steps to reproduce:
1. trying to increase the amount of energy the resistive heater uses just crashes you
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** Forge: net.minecraftforge:31.1.30
**Mekanism:** Mekanism-1.15.2-9.9.17.409.jar Mekanism {mekanism@9.9.17 DONE}
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/vertex101/827239ddb9b3083a5bf468a459e28681

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
#5996
