### ISSUE TITLE
Digital Miner Filter Issues

### ISSUE THREAD

**Issue by Ceillian** [mekanism/Mekanism#6003]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Filter for cobblestone doesn't work on Digital Miner. I noticed similar issues with transporters.

#### Steps to reproduce:
1.  Insert filter for cobblestone
2. Mine
3. Still get cobblestone 

I tired both item ID and Material. Neither of these produce expected results.  Material filters all blocks while item doesn't work at all. 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 15.2.1
**Mekanism:** 15.2.1
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
What version of mekanism are you on...? 15.2.1 is not a valid forge version and it is also not a valid mekanism version.

**Comment by Ceillian** [comment]
Forge:  31.1.30
Mekanism 1.15.2-9.9.17.409

**Comment by pupnewfster** [comment]
What filter do you have set, and what behavior are you expecting to have happen. Given it sort of sounds like you are telling it to mine cobblestone and being surprised that it is doing so. The miner does have an "inverse" mode if I remember correctly though.

**Comment by Ceillian** [comment]
It's in inverse mode, It should mine all items except cobble. Instead, it continues to mine cobble. 

I tired both item ID and Material. Neither of these produce expected results. Material filters all blocks while item doesn't work at all.

![image](https://user-images.githubusercontent.com/6994101/77862667-98e65180-71e2-11ea-8615-7e0ff2cb25b1.png)

**Comment by Ceillian** [comment]
Need to put stone in.
