### ISSUE TITLE
Compatibility issues with supportive mods like ProjectE and BetterBuildersWands

### ISSUE THREAD

**Issue by Sl33pyM4n** [mekanism/Mekanism#6004]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description: 
Hi, i made my own modpack for casual play and found that when using duplication support mods (like the EMC system in ProjectE or a builders wand) some mekanism blocks like universal cables and energy cells don't duplicate correctly (eg when using a builders wand to try and create another line of elite universal cables, the builders wand takes the elite universal cables but places down basic universal cables), even though items like alloys (eg enriched alloy, quantum alloy) work just fine with ProjectE

#### Steps to reproduce:
1. Open up a modded minecraft world in 1.12.2 (may also occur in other minecraft versions), with the mods mekanism, projecte, projecte integration and better builders wands. 
2. give self stack of each of the following: all levels of universal cables and all levels of the energy cell, along with one transmutation table and any builders wand (none in particular)
3. place line of universal cables of either advanced, elite or ultimate in a line and try to use builders wand to create another row, or place all variants of energy cells in transmutation table

#### Version (make sure you are on the latest version before reporting): 
Minecraft Version: 1.12.2
Forge: forge-14.23.5.2847
Mekanism: 9.8.3.390
Other relevant version: ProjectE (version PE1.4.1), ProjectE Integration (version 2.5.0), BetterBuildersWands (version 0.13.2.271)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
This has to do with the fact that Mekanism in 1.12 and earlier used NBT as part of how it determined item variants, (we no longer do this in 1.15), and the fact that ProjectE did not used to be able to support NBT (as of 1.14 and 1.15 it does). I am on both teams (Mekanism and ProjectE), and there are not any plans to back port either of those changes to 1.12, as we do not have the time and at least with Mekanism we are fully focused on 1.15. (With 1.15 for ProjectE mostly at this point just receiving bug fixes when I have the time).

My guess is that BetterBuildersWands is not properly handling/firing place events in a way that has our blocks set the proper information to the tiles with how things are done in 1.12. So my guess is that it is a bug on their end (unless they just don't have support for NBT in general similar to how ProjectE didn't really in 1.12).

Going ahead and closing this issue as:
a. We are no longer developing for 1.12
b. There is nothing to be done on Mekanism's end (at least not that could be done in a backwards compatible way even if we wanted to and had the time to adjust things for 1.12)

If BetterBuildersWands has not moved on past 1.12 yet, then maybe you should make an issue for them not working properly with our blocks, but other than that there is not much you can do.

**Comment by Gabriellokoh** [comment]
@pupnewfster  Was there a specific version or date of Minecraft, Forge, or Mekanism (1.12.2) when this used to work? Because there's a YouTuber (Jazzghost) who obtained the ultimate version of the logistical cable on the transmutation table (note: he might have also acquired it in creative mode due to video cuts), but I just want to know if it used to work before. If it did, I'll test different versions myself until I find it 😂. I just needed your answer so I don't hunt in vain!
