### ISSUE TITLE
Crash while using the Resistive Heater.

### ISSUE THREAD

**Issue by X-otic** [mekanism/Mekanism#6005]
#### Issue description:
Typing in the input bar on the Resistive Heater and confirming makes the game crash.

#### Steps to reproduce (Follow steps or gif below):
1. Open the interface of a Resistive Heater.
2. Click the input bar and type a number.
3. Click confirm.

![Mekanism Crash](https://user-images.githubusercontent.com/62854852/77862789-0a8fc100-721e-11ea-8c10-6ca84a005d8e.gif)

#### Version (Current, latest version):
**Forge: 31.1.30**
**Mekanism: 9.9.17**

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[crash-2020-03-30_00.22.24-client.txt](https://github.com/mekanism/Mekanism/files/4399943/crash-2020-03-30_00.22.24-client.txt)

**Comment by pupnewfster** [comment]
#5996

**Comment by X-otic** [comment]
Whoops did the formating wrong. Sorry. It should now be correct.
