### ISSUE TITLE
Induction Matrix not inputting and outputting power properly GUI

### ISSUE THREAD

**Issue by JakeKonkowski** [mekanism/Mekanism#6007]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When transferring energy into or out of the induction matrix with the GUI, it will transfer energy at a tenth of the rate it is supposed to. In theory this could be abused for infinite energy.

#### Steps to reproduce:
1. Build induction matrix
2. Open GUI
3. Transfer energy using something like an ultimate energy cube.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2847-universal
**Mekanism:** Mekanism-1.12.2-9.8.3.390
**Other relevant version:** 1.12.2 Mod Pack from Technic Launcher

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by aidancbrady** [comment]
No longer reproducible in 1.15.
