### ISSUE TITLE
Industrial Turbine

### ISSUE THREAD

**Issue by kornfan6589** [mekanism/Mekanism#6008]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Maybe im dumb and searching has failed me, but i cant seem to extract power from an industrial turbine. the universal power cable does not connect to the turbine valve. i tried using the configurator to force it but it still will not connect. the turbine itself sparkled red and i can open the turbine stats and production menu and the pressurized tube im using for steam also connects to the other valve i have correctly. also, likely unrelated, im using a reactor to supply steam, but once the turbine fills with steam it stops producing and just sits there, setting from idle to dumping excess does not resolve this. the build contains 8 blades, 5 coils, 8 dispersers, and 33 vents. 

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.23
**Mekanism:** 9.9.16.408
**Other relevant version:** 1.15.2 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by kornfan6589** [comment]
For clarification, a screenshot

[https://drive.google.com/file/d/1oeoaE4Id4ARksnvUG46v_F249YAvYPn3/view?usp=sharing](url)

also, if this is relevent, the reactor is running at an injection rate of 6 and being fed water by 32 electric pumps upgraded 8 speed and 8 energy

**Comment by Chunkimunki** [comment]
9.9.17.409 version    forge-31.1.30

Can also confirm turbine accepting steam but not generating power

**Comment by aidancbrady** [comment]
This is not occurring in my dev environment; the cable connection issue was likely fixed in 9.9.17 with the energy changes. @Chunkimunki, your issue is strange- you shouldn't be able to open the UI if the multiblock isn't formed.

**Comment by aidancbrady** [comment]
Reopening as @Chunkimunki's issue was actually fixed for 9.9.18.

**Comment by shotgun12** [comment]
im having a problem with the turbine when im building it and trying to put turbine casing on top of one another it doesnt place the block but instead opens and closes a menu very quickly as if the structure is done and ready to see the information screen

**Comment by kornfan6589** [comment]
It may be worth noting that setting the turbine to dump all causes it to accept steam but it does not output water. Not sure if this is intended or not. To clarify, it seems i need to wait for 9.9.18 for this system to work properly.

**Comment by Greatone123** [comment]
As a note, since I came here for this same issue, but I can put a energy cube next to it, and it outputs energy to it. My issue is that the mechanical pipes won't connect to pull water out. I would assume if one is fixed then so is the other maybe.

**Comment by kd5crs** [comment]
Nice one Greatone123, I confirm. The Universal Cable does not connect to the turbine valve, but the Energy Cube does.
