### ISSUE TITLE
Server crash on launch

### ISSUE THREAD

**Issue by Yoosk** [mekanism/Mekanism#6010]
#### Issue description: 
One of the players did something, which resulted in server crashing whenever anyone joined the server.

#### Steps to reproduce:
1. Nothing conclusive, one person mentioned that he was removing some universal cables.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.27
**Mekanism:** 9.9.17.409
**Other relevant version:** RAM modpack 0.2.10

#### If a (crash)log is relevant for this issue, link it here: 
https://s.yoosk.pl/VuMtI

**Comment by LarryMoe11** [comment]
im getting same thing, look in logs and see if you are getting errors from a mod called minechem, if so i think we are having same issue
