### ISSUE TITLE
Mechanical Pipe not transferring correct amount

### ISSUE THREAD

**Issue by papaworld** [mekanism/Mekanism#6011]
Hi, thank you for bringing back Mekanism for 1.15.2.

I've been running 9.9.11.403 w/Forge 31.1.30. Upgraded to 9.9.17.409 yesterday. Basic Mechanical Pipe is now only transferring 100mb of the 1,000mb supplied. Advanced is transferring 400mb of the 1,000mb supplied. Did not test Elite and Ultimate. Re-Installed 9.9.11.403... worked correctly.

Setup: Engineer's Decor Small Melting Furnace feeding Lava thru Basic Mech Pipe to Silent's Mechanisms Lava Generator. It also can be replicated with the Melting Furnace feeding Lava thru Basic Mech Pipe to a tank.

ThanX

**Comment by pupnewfster** [comment]
Is this in regards to how much they are pulling when set to extract?

**Comment by papaworld** [comment]
With v403, the pipe in pull mode (configurator) would extract 100mb/t rate and empty out the Melter in 10ticks. It appears now, v409, the only the first 100mb comes out, but the Melter is empty (900mb missing). I just tried Advanced, Elite and Ultimate... they work fine at this slow rate. But, Advanced also fails at higher rates.

**Comment by pupnewfster** [comment]
Ah, ok I misunderstood what you had initially stated about I thought it had to do with the rate, rather than the total amount. I will look into this a bit more when I get the chance some time before 9.9.18

**Comment by papaworld** [comment]
Sorry 'bout the misunderstanding. I stand corrected, the Advanced Mech Pipe extracts 400mb of the 1,000mb... 600mb missing.

**Comment by pupnewfster** [comment]
The fluid voiding is a bug in Engineer's decor. (I am leaving this issue open for now to track/fix the fallback for before configs load that I found while looking for the issue.)

From what I can tell: <https://github.com/stfwi/engineers-decor/blob/master/1.15/src/main/java/wile/engineersdecor/blocks/BlockDecorMineralSmelter.java#L494> they are ignoring the amount we request to drain and just are draining whatever is stored from their mineral smelter. The reason it worked before, is that their other drain method seems to be implemented properly, and we used to use that before I switched to the fluid stack specific one to have proper support for tile's that have more than one tank.

**Comment by papaworld** [comment]
Very good pupnewfster, thank you very much for the info and your quick response. A workaround is using the Elite Mech Pipe (1600mb) to pull the entire 1000mb. BTW: Mekanism has been one my main-stay mods since 1.7.10. I really appreciate that the mods operational parameters have not changed (i.e., reactor setup is the same) even going in to 1.15.2. Well done and tip-of-the-hat to you and your team.

**Comment by pupnewfster** [comment]
It still would probably be a good idea to report the bug to Engineer's Decor so they are able to fix the fact they void their own contents, as there is nothing about that part of this bug report that we can do on our end.

**Comment by stfwi** [comment]
Hi, confirmed, that's an issue in my ED mod, I'll take over in https://github.com/stfwi/engineers-decor/issues/92 ;-). Cheers -

**Comment by papaworld** [comment]
Thank you stfwl. Enjoy!
