### ISSUE TITLE
Industrial turbine casing

### ISSUE THREAD

**Issue by shotgun12** [mekanism/Mekanism#6012]
Issue description:
I am building the industrial turbine and when i go to place a one casing on top of another to make the corners i get the screen that you would see when the structure is done. It only pops up for a split second then disappears and does not place the block when i go to try again the same thing happens.  This happens when placing two of these blocks next to or on top of each other my game could be messed up i did do a restart of my mine craft did not help the only way to place these blocks is to crouch and the place it next to or on top of one another

#### Steps to reproduce:
1. place one turbine casing on the ground.
2. place another one on top of it and you will see that it does not place the block but shows the turbine menu and info
3. if you crouch to place it works fine

#### Version 
**Mekanism:** 1.15.2

**Comment by pupnewfster** [comment]
#6008
