### ISSUE TITLE
Electric Pumps

### ISSUE THREAD

**Issue by kornfan6589** [mekanism/Mekanism#6013]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I am trying to water cool the fusion reactor, and cant help but think im doing something wrong, using electric pumps im trying to feed water in. i currently have 78 pumps with 8/8 upgrades sitting above an area of 17x14 and above 60 blocks deep of source blocks of water. when in operations all the pumps show no fluid, but a pumping just a little to the reactor. i assuming something im doing is incorrect. ive also tried spacing them out when i only had 32 pumps (2 blocks inbetween each in a grid) and it seemed to produce the same amount of water as just lining them all up in rows. they are currently in 6 rows of 13 pumps. i also tried submerging them and it seemed to make no difference.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.23
**Mekanism:** 9.9.16.408
**Other relevant version:** 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Apot98** [comment]
Possibly a duplicate of #6011, where Mechanical Pipes would void liquids that exceed network buffer.

**Comment by papaworld** [comment]
Hello, I originated the #6011 Mechanical Pipe issues.

The reactors and reactor/turbine combination work fine for me. The Mech Pipes work as intended when connected to Mekanism components and third party tanks.

kornfan6589: In a reactor/turbine combo you actually need very little water to the reactor. Even with just 1 pump with 8/8 upgrades it will produce 500mb/t using 400rf/t works for me. The speed of the turbine spin up time is based upon the amount of water you supply to the reactor. Eventually the turbine will get up to speed, faster with more water supplied. It seems you might be missing a water return from the turbine to the reactor. I prefer direct connections from reactor to/from turbine. Check to make sure you are using saturating condensers in the turbine. Ratio of 1 Saturating Condenser per 2 Turbine vents. Turbine will return water to the reactor. As the turbine fills its internal tank with steam (huge amount)... the turbine will take over the water supply to the reactor and relax the water pump(s). Also, confirm you are setting the steam/water in/out with the configurator on the reactor. Steam out red, water in green. Hope this helps.

**Comment by papaworld** [comment]
Apot98: reference above comment from me.
The reactor/turbine combo worked fine for me, it was a previous build with v403 (not functioning) then upgraded to v409 (working well). But, when I built a new system from scratch in the same test world w/v409 the system failed. There is not enough water returned from the turbine to sustain the system. Comparing this against my 1.12.2 system.

**Comment by kornfan6589** [comment]
It seems the relation is to issue #6008 as my turbine only can dump steam and does not output any water. I'm assuming this is on the fixit list for 9.9.18. to clarify, i would just like to know the expected output of a fully upgraded pump sitting over a source block of water that is 60ish blocks deep. And possibly the ideal scenario for a pump to "maximize" its output. ie: radius of water blocks around the pump and depth. I'm sure there's some math here.

**Comment by papaworld** [comment]
kornfan6589: I'm not part of the Mekanism Team, so this venue is not the proper place for me to help you without permission from Mekanism. As for now, as I see it, the reactor only systems work fantastic. On the other hand, the reactor/turbine combo system still needs some fine-tuning. They ported over an entire Mekanism mod from 1.7.10 to 1.12.2 to 1.15.2 and kept the parameters consistant (NICE WORK!). What a huge endeavor, but they are on top of it. If you have a way I can contact you I am willing to help you out. BTW: you can get 9.8MFE/t on a reactor only system taking less than 1 chunk of space.

**Comment by pupnewfster** [comment]
Not fully sure what you are describing as the "issue" or what you mean by not showing any fluid without pictures or anything. Though I do have a few comments, one when it comes to pumping water, electric pumps don't really care how deep the water is/if it is truly an infinite source or just a single block (unless the config option for actually picking up water source blocks is changed from the default value). I am not quite sure offhand of the rates of fluid use in the reactor as I have never used it for making steam personally.

**Comment by kornfan6589** [comment]
The issue is that the industial turbine in 9.9.16 does not seem to output water from the vents. (doesnt fill a pipe, doesnt feed the reactor) i was trying to water cool a reactor off a butt load of pumps, from what im reading here, that is not feasible. so i will wait until 9.9.18 and try to get the turbine up and running. 

As far as the pumps go, in testing (looking at reactor water input) it seemed that making the pool deeper supplied slightly more water so i went for broke and made it 60 blocks deep, but it did nothing, so i was curious if there was a block radius they pull from more efficiently. it seems that is also incorrect and they only pull from a source block, and thats it. which is misleading in the wiki. (kind of worded funny) so that being said i made a lot of pumps, but oh well. This is all just exploring the features of the mod, and trying to understand the limitations and expected mechanics of the machines in it. Basically just seeing if im seeing bugs, or this is intended. Mixture of both it seems. Either way mekanism is still the most complete tech mod with the most features for 1.15.

For others who find this page TLDR: You cant use pumps to water cool a reactor, you must use a few pumps to start the steam generation in the reactor then feed it to a turbine and output water from the turbine to fill the "system".
