### ISSUE TITLE
Inconsistency with vanilla ores regarding Mekanism's Combiner

### ISSUE THREAD

**Issue by BlackQuests** [mekanism/Mekanism#6014]
#### Issue description:
I'm reporting a duplication bug that has existed for a while and I can't see anyone else reporting on. Several 'other dimension' cyclic ores that drop multiple items do not work well with the Combiner from Mekanism. For example Redstone Nether Ore can be made in the Combiner using 3 redstone and Netherrack while normal redstone ore requires 16 Redstone and cobblestone.
Same thing holds for lapis and both end version of the ores.
I tried looking through the code to see which one of the two mods is responsible for this but could not find it. I'm therefore making a new issue on both githubs, the other issue can be found here: https://github.com/Lothrazar/Cyclic/issues/1354
I noticed similar issues were reported before (https://github.com/mekanism/Mekanism/issues/5636) but I'm guessing this is more of an actual bug then a balancing issues
#### Steps to reproduce:
1. Place 3 redstone with netherrack into combiner (given you have the cyclic mod)
2. Get 1 Nether redstone ore from combiner
3. Process ore in any way you want to gain more than 3 redstone and repeat

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2846
**Mekanism:** 9.8.3.390
**Other relevant version:** Cyclic 1.19.20
![Redstone_ore](https://user-images.githubusercontent.com/10686466/78034962-bfce9000-7368-11ea-91c9-7b13f6ea82ff.png)
![Nether_redstone_ore](https://user-images.githubusercontent.com/10686466/78034966-c0672680-7368-11ea-8d0d-7d0fd8d15370.png)

**Comment by BlackQuests** [comment]
It seems I am at fault here. Nether Redstone ore normally only produces a couple of redstone so this is more an error with crushers from other mods etc.

**Comment by BlackQuests** [comment]
I've been spending a couple of hours trying to figure out what mod causes every pulverizer and crusher in the game to behave like Cyclic Nether Redstone Ore is another version of Redstone Ore and sadly cannot figure this out in any way.
I coincidentally stumbled on the fact that Mekanism itself also allows for duplicating redstone via the enrichment chamber. One Nether Redstone Ore produces 12 Redstone which then allows for (basically) endless duplication.

![enrich_ore](https://user-images.githubusercontent.com/10686466/78051008-602eaf80-737d-11ea-99c1-b9ba13510f54.png)

(I copied this comment from the other issue on the cyclic github)

**Comment by pupnewfster** [comment]
It seems that the PR that originally added compat for Cyclic ores #5201, then had a bug. I am however going ahead and closing this issue, as at least currently we have not ported any cyclic compat yet to the 1.15 branch, and we are no longer working on developing the 1.12 branch. (For purposes of your own pack you probably could fix the recipes via CraftTweaker)
