### ISSUE TITLE
Side Config not working for Gas Tanks - 1.12

### ISSUE THREAD

**Issue by D3nnis3n** [mekanism/Mekanism#6018]
#### Issue description:
Side Config and Transporter Config do not work at Gas Tanks, despite them being shown.

#### Steps to reproduce:
1. Place any Gas Tank.
2. Click on Side or Transporter Config.
3. Nothing happens

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2847
**Mekanism:**  9.8.3.390

**Comment by D3nnis3n** [comment]
Additional Information:
It works as soon as a Mekanism Tube has **at least once** been placed next to it.
If that was done, Ender IO Gas Conduits are able to pull gas out at the output side as well.

If this was not done, EnderIO conduits can not take out any gas, no matter on which side (not even on the default output side) and sides cant be configured, as the buttons cannot be clicked.

All other machines can be configured without any type of pipe next to them and enderio conduits can extract at the default output side without any configuration to the output sides done.

If this is rather a EnderIO Gas Conduits issue, please give me a heads up.

**Comment by pupnewfster** [comment]
Last I tried things worked properly in 1.12 for gas tanks and the side config. Though as Mekanism 1.12 development is no longer taking place I am going ahead and closing this. Additionally if this is a bug in the gas conduits mod, it is unlikely to be fixed, as I am not planning on touching 1.12 again and am (hoping) enderio doesn't accidentally break their API again and cause me have to update that addon (given I am the one who made it).
