### ISSUE TITLE
Unable to craft basic purification factory

### ISSUE THREAD

**Issue by Tr1mbl3** [mekanism/Mekanism#6019]
#### Issue description:
I'm unable to craft a basic purification factory. I I mainly use Just enough items to auto fill the recipe, but neither that nor manually putting it into the crafting table allows me to see or grab the final product, despite the white box appearing on the output indicating there should be something there.

The upgrade from basic to advanced purification factory does still work. 

#### Steps to reproduce:
1. Build a purification chamber. 
2.  Use it a few times.
3. Attempt to use it to upgrade it to a basic purification factory.

#### Version (make sure you are on the latest version before reporting):
Forge: 1.15.2 - 31.1.25
Mekanism: 1.15.2 -  9.9.17.409

**Comment by Boomflex** [comment]
I had this on my server.

The user did not dump everything out of the purifier so it wouldn’t make the basic one. 

Might be worth looking at.

**Comment by aidancbrady** [comment]
This has to do with a deeper-rooted problem with the way we merge inventories during recipes. We'll look into this for the next alpha.

**Comment by SalmonCobra** [comment]
im having the same issue with crafting all the factories on my server
