### ISSUE TITLE
duplication of steel

### ISSUE THREAD

**Issue by closeshot** [mekanism/Mekanism#6020]
What happens: When the crafter is crafting steel dust it doubles itself.
What you expected to happen: Only to autocraft the steel with coal and output into the system.
Steps to reproduce:
place crafter
place barrel under crafter
place logistical transporter
place metallurgic infuser
placed interface for output items.
...
Version (make sure you are on the latest version before reporting):
Minecraft: 1.15.2
Forge: 31.1.27
Refined Storage: 1.8.1
Does this issue occur on a server? [yes/no] Don't have a server

If a (crash)log is relevant for this issue, link it here: No crashes
[pastebin/gist/etc link here]

**Comment by pupnewfster** [comment]
What version of mekanism is this, as this sounds like #5981
