### ISSUE TITLE
Maven api mekanism 1.15.2?

### ISSUE THREAD

**Issue by Edivad99** [mekanism/Mekanism#6022]
Hi, I wanted to ask for information. Is there a maven repo where you can get the API for mekanism 1.15.2?

**Comment by aidancbrady** [comment]
You can download the API from my website (aidancbrady.com/Mekanism/download) or Curse.

**Comment by aidancbrady** [comment]
Will probably set up a maven server at some point, just haven’t had time.

**Comment by Edivad99** [comment]
OK thank you very much

**Comment by Edivad99** [comment]
Sorry I wanted to tell you that in your site, for 1.15.2, there is no possibility to download only the API. Am I looking in the wrong place?
