### ISSUE TITLE
Electric pump flow

### ISSUE THREAD

**Issue by b4nst** [mekanism/Mekanism#6023]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I don't know if it's a bug, the intended behaviour or a misassembly from me. My electric pump doesn't work properly (I think). I have attached a screenshot of a very simple design including an electric pump, some basic mech pipes, a creative energy cube and a creative tank (for infinite flow). 

The pump's state alternate from `No fluid` to something like `Water: 400 mB/t`. The `No fluid` is longer than the `Water` state. When I add some speed modules, I end up not seing the `Water` state anymore.

When I debug the pipes with the *Network Reader*, the Throughput also alternate between 0 and 400 400mB/t (seems logic).

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.35
**Mekanism:** 9.9.17
**Other relevant version:** 

![2020-04-03_15 32 27](https://user-images.githubusercontent.com/7900600/78367002-ad02c800-75c1-11ea-918b-c845733a00a0.png)

**Comment by aidancbrady** [comment]
This looks perfectly normal to me. Creative fluid tanks don’t fill up with any water. You see only a bit of water in the pipes and pump because it’s getting forced out and into the fluid tank.

**Comment by b4nst** [comment]
Yeah I know that creative tanks don't fill up, that's exactly why I used it here. My problem is not with the tank not filling, it's with the very little throughout the pump delivers. The problem remains if I replace the creative tank with a classic tank (at least until the tank is full).

**Comment by aidancbrady** [comment]
No. The pump sucks source blocks independently (1000 mB at a time) with a delay in between that can be lessened with upgrades.

**Comment by aidancbrady** [comment]
I’ll note that the pump quickly reverting to “No Fluid” implies _high_ throughput of the popes.

**Comment by b4nst** [comment]
Ok, I tried to feed an Electrolytic Separator, and adding more pump and upgrades. What I understood of your last note and my test is that if the state revert to "No Fluid" it implies I have not enough pumps/upgrades, right ? The mechanism that need water will "suck" it back to the pumps as soon as water is available in the pipes/pumps ?

Indeed by using upgrades or adding more pumps, eventually the state stop reverting (obviously not with the creative tank, because of its infinity).

**Comment by aidancbrady** [comment]
Closing as it doesn’t sound like this is an issue.

‘No Fluid’ refers to the fluid stored in the pump’s buffer. The pump will say ‘no fluid’ once it’s sent all it’s contained fluid to a connected pipe (which will happen fast).

**Comment by b4nst** [comment]
Thanks for the clarification
