### ISSUE TITLE
Network Reader heat thruput formatting is not worked

### ISSUE THREAD

**Issue by karakufire** [mekanism/Mekanism#6024]
#### Issue description:
Network reader outputting stats, `"network.mekanism.heat_flow.efficiency"` is not formatted.

#### Steps to reproduce:
1. Use Network Reader for Thermodynamic Conductor (maybe can any languages)
2. Check stats in chat

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.25
**Mekanism:** 9.9.17.409
**Other relevant version:** Minecraft 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
1. in ja_jp(in progress)
![2020-04-03_23 30 40 described](https://user-images.githubusercontent.com/10906521/78373392-84042680-7605-11ea-9d30-750905432e2b.png)

2. in en_us
![2020-04-03_23 31 30 described](https://user-images.githubusercontent.com/10906521/78373427-8cf4f800-7605-11ea-921b-103ee8cf9c77.png)

\* words with red line.

**Comment by aidancbrady** [comment]
Pretty sure it's the extra % after the third %s. Will push a fix.

**Comment by aidancbrady** [comment]
Should be fixed in 76ad73c.
