### ISSUE TITLE
Resistive heater energy change - mouse event on the tick crashes client

### ISSUE THREAD

**Issue by Swallowtail23** [mekanism/Mekanism#6026]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Changing the energy level of a resistive heater and clicking the tick crashes client (repeatable)

#### Steps to reproduce:
1. Right click on resistive heater
2. Enter 1000 and click the tick
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.30
**Mekanism:** Mekanism-1.15.2-9.9.17.409
**Other relevant version:** ATM 5

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist]https://gist.github.com/Swallowtail23/2446add34568236abbcc9416b6594921]

**Comment by kohlth** [comment]
can reproduce, heres my crash log 
[crash-2020-04-04_05.38.55-client.txt](https://github.com/mekanism/Mekanism/files/4430817/crash-2020-04-04_05.38.55-client.txt)

**Comment by aidancbrady** [comment]
#5996 
should have a new release out soon
