### ISSUE TITLE
Mob farming and crop farming module or machines

### ISSUE THREAD

**Issue by kohlth** [mekanism/Mekanism#6029]
**Describe the feature you'd like**
A mekanism way to not only farm crops but a way to farm mob drops that could potentially be its own module 

instead of a normal machine to spawn mobs and a machine to kill them plus a machine to harvest and plant like other mods, I think the best way to fit mekanism is to have growth vats. what I mean is a way to grow mob drops by inputting power and some biomaterial (crops you could also grow in a vat with water and power). you would have to go out and get some mob DNA and then decode it then create a flesh seed that grows and then is possessed into a mob drop. there could be also upgrading flesh seeds and crops with DNA editing to boost yield, speed, and other factors like reducing a possible fail rate on flesh seeds.

**Describe alternatives you've considered**
honestly, I would love just a way to auto farm crops as currently, mekanism requires a secondary mod to automate crops for biofuel

**Additional context**
if it was its own module, people who prefer mekanism without farming of mobs and plants can not download a module all together without having to dig in configs

**Comment by aidancbrady** [comment]
Attaching this to your old issue #5278. We're definitely looking into this for v10.
