### ISSUE TITLE
Osmium isn't generating but in the Spawn-Chunk

### ISSUE THREAD

**Issue by PhiJoTo** [mekanism/Mekanism#6030]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I have a Modpack Server. There are many Mods including BoP. This could also cause issues. I really don't know where to post this so sorry if I'm wrong.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.7.10-10.13.4.1566-1.7.10-universal
**Mekanism:** Mekanism-1.7.10-9.1.1.1031
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I haven't used 1.7.10 in a very long time, and I also wasn't on the team back then so I don't know if there were any known bugs, but I am going ahead and closing this as we are currently only working on developing the 1.15 version of Mekanism.
