### ISSUE TITLE
insertion 

### ISSUE THREAD

**Issue by closeshot** [mekanism/Mekanism#6031]
**Describe the the feature you'd like**
Would it be possible to add a feature for the machines to auto insert without a logistical transport cable, would be a lot cleaner if this can be done.

**Describe alternatives you've considered**
The other alternatives would be to use transporters.

**Additional context**
No additional context.

**Comment by aidancbrady** [comment]
Your request is somewhat vague. If you mean the ability for machines to auto-eject to other machines without a transporter, that is already possible. We will not be adding ‘pulling’ functionality from nearby inventories anytime soon.
