### ISSUE TITLE
[1.15.2] Turbine not producing power

### ISSUE THREAD

**Issue by Chunkimunki** [mekanism/Mekanism#6034]
Turbine accepting steam but not generating FE

1. Built Turbine in creative
2.Used Creative steam Tank
3.Turbine full of steam - no power made

Forge: 31.1.36 
Mekanism:  9.9.18.410 

Logs available  [Debug](https://pastebin.com/cqqt5nc7)
                         [Latest](https://pastebin.com/fVLRLmht)

Cheers

**Comment by thiakil** [comment]
Please show the Turbine's gui - the main screen and the stats screen

**Comment by Chunkimunki** [comment]
Err....executes face palm! Forgot to add vents! Vents added and works perfectly! Sorry to waste your time folks - perhaps make it not form structure without these blocks might head off more twaddle from idiots like myself!! Just a thought. Thanks for a great mod and keep up the good work.
