### ISSUE TITLE
Bin duplication

### ISSUE THREAD

**Issue by AlpBilgin** [mekanism/Mekanism#6038]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*
I did. Last similarly worded issue is #2682 from 2019

#### Issue description:
I tired to upgrade a partially filled basic bin to an advanced bin. It got duplicated and filled up my inventory.

see screenshots

http://prntscr.com/ruq548
http://prntscr.com/ruq5h4

#### Steps to reproduce:
1. Take basic bin with 3989 dirt
2. Try to craft it into an advanced bin in Bluepower project table, using materials just taken out of refined storage grid
3. Advanced bin is crafted empty and crafting grid of project table now contains stacked basic bins filled with 3989 dirt
4. try to move bin stack to inventory, inventory is filled with stacks of basic bins with dirt. They are placeable on world.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.27
**Mekanism:** Mekanism-1.15.2-9.9.16.408.jar
**Other relevant version:** MC 1.15.2, All The Mods 5 1.13

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Does this happen in 9.9.18?

**Comment by AlpBilgin** [comment]
I tried a few times but couldn't replicate.

**Comment by pupnewfster** [comment]
Then I am going to go ahead and close this as I believe it was probably fixed in either 9.9.17 or 9.9.18
