### ISSUE TITLE
Oredictionfier 

### ISSUE THREAD

**Issue by Grant-K** [mekanism/Mekanism#6039]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.Use Mekanism-1.12.2-9.8.0.381.jar
2.Place oredictionfier
3.click new filter
4.Game will then crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2838-universal
**Mekanism: 1.12.2-9.8.0.381.jar
**Other relevant version: This is in the atm3 modpack Version: v5.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.] https://pastebin.com/UNTxiK6h

**Comment by pupnewfster** [comment]
Update mekanism, this was fixed in 9.8.1 or 9.8.2 don't remember. Latest and final 1.12 version of mekanism is 9.8.3
