### ISSUE TITLE
Flamethrower doesn`t work correctly

### ISSUE THREAD

**Issue by MoneyCatRUS** [mekanism/Mekanism#6042]
#### Issue description:

In version 1.15.2 - 9.9.18.410 flamethrower deals no damage to mobs and destroys no items. And, in inferno mode, it sets on fire only grass, but not leaves or something else.

#### Steps to reproduce:
1.Grab a flamethrower filled with hydrogen;
2.Set the flamethrower at combat mode;
3.Spit the flame at some innocent creature/item.
/
1.Grab a flamethrower filled with hydrogen;
2.Set the flamethrower at inferno mode;
3.Spit the flame at leaves.

#### Version:
**Forge:** 1.15.2-forge-31.1.35
**Mekanism:** 1.15.2 - 9.9.18.410

**Comment by aidancbrady** [comment]
Unable to reproduce this. If you're on a server, aestheticWorldDamage may be disabled

**Comment by MoneyCatRUS** [comment]
No, i play in my own world

**Comment by aidancbrady** [comment]
Fixed in a05dd1a.
