### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by IchigoGames** [mekanism/Mekanism#6043]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Server crash but i am not sure how or what from but now its in a crash loop

#### Steps to reproduce:
1.not sure
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.30
**Mekanism:1.15.2-9.9.17.409
MekanismGenerators-1.15.2-9.9.17.409
MekanismTools-1.15.2-9.9.17.409

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/gJzTSScH

**Comment by pupnewfster** [comment]
Update mekanism
