### ISSUE TITLE
[1.15.2] Power cables don't "light up" when powered

### ISSUE THREAD

**Issue by ocram9** [mekanism/Mekanism#6045]
#### Issue description:
Power cables don't "light up" when you power it (as in the cable doesn't have a color). This doesn't apply to pipes, pressurized tubes and logistical pipes.

#### Steps to reproduce:
1. Power cable
2. Run power through them

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.41
**Mekanism:** 9.9.18.410
**Other relevant version:** Mekanism Generators 9.9.18.410

#### Logs:
- Debug log: https://gist.github.com/ocram9/c63acce8271b968a5b07718baf01b0ed
- Latest log: https://gist.github.com/ocram9/689391a1b42ccf3c939086129ce20276

These logs are from a server with multiple mods in them but I have tested this issue in singleplayer with just Mekanism and it still occurs.

#### Screenshots:
Power cable:
![2020-04-09_16 04 16](https://user-images.githubusercontent.com/49008532/78905844-de2a3f00-7a7e-11ea-8ab9-c3ab6b109dc3.png)

When looking through a power cable (to water and a solar panel):
![2020-04-09_16 21 51](https://user-images.githubusercontent.com/49008532/78905891-ed10f180-7a7e-11ea-9652-505ac338fee5.png)

![2020-04-09_16 21 56](https://user-images.githubusercontent.com/49008532/78905899-ef734b80-7a7e-11ea-86b6-511e2b4539a0.png)

**Comment by ocram9** [comment]
Quite an important addon: Apparently I accidentaly DID leave optifine in my mods folder so the pressurized tube is an optifine issue. After definitely removing optifine the power cables still don't work though

**Comment by ocram9** [comment]
I got this completely wrong, there wasn't enough power in the cable for it to light up, I use HWYLA but I can't see the power in the cables. Sorry about this, I'll close the issue now :P

**Comment by aidancbrady** [comment]
@ocram9 your issue is actually real- the way we handle scales changed recently. I've made some changes to have cables, pipes and tubes show their contents when stuff is transferring, even when not at capacity.

**Comment by ocram9** [comment]
Fair enough, that will be handy in the future. Thanks!
