### ISSUE TITLE
Fusion Reactor ports not outputting power to universal cables or energy cubes

### ISSUE THREAD

**Issue by CapnSaltybeard** [mekanism/Mekanism#6047]
I am playing with Mekanism in FTB Omnia, using the FTB launcher, on a multiplayer server with friends; no configs or settings have been changed in the modpack itself. The reactor itself works fine, fuel is being used like normal and it is generating power, which is being put into buffer. However, when I try to extract the power using universal cables or an energy cube set to input, I am unable to extract any power from the ports, regardless of port position or cable mode, whether set to pull from the port or push into the cube. Screenshots attached show that the port is full, the cable is empty, and the cube is empty.

![2020-04-09_22 06 16](https://user-images.githubusercontent.com/23640805/78955835-7e4b8c80-7aae-11ea-989b-cec9ea886d1f.png)
![2020-04-09_22 06 18](https://user-images.githubusercontent.com/23640805/78955839-7f7cb980-7aae-11ea-900b-1715df24ede6.png)
![2020-04-09_22 06 20](https://user-images.githubusercontent.com/23640805/78955842-81467d00-7aae-11ea-86a0-16f2513f472c.png)

**Comment by pupnewfster** [comment]
Set the port to eject with a configurator
