### ISSUE TITLE
reactor parts completely missing from my game

### ISSUE THREAD

**Issue by ReturnedFromTheDead** [mekanism/Mekanism#6051]
Issue description:
The issue is simple. All the parts for the fusion reactor is missing. I've installed the latest version and others of the mod and tried in singleplayer and reproduced it multiple times. I'm playing in version 1.12.2 of minecraft. I looked in the config and there were settings for the fusion fuel injection. I don't know what's happening but I'd appreciate some help.

Steps to reproduce:
1. Install the mod in 1.12.2
2. start the game
3. Wammo

Version (make sure you are on the latest version before reporting):
Forge: 1.12.2-14.23.5.2847
Mekanism: 1.12.2-9.8.3.390

pls help :(

![nope](https://user-images.githubusercontent.com/63513140/79050591-546ba480-7c2b-11ea-9ab9-ee443e2fdd49.PNG)
![nope2](https://user-images.githubusercontent.com/63513140/79050593-559cd180-7c2b-11ea-9e0d-8c1a560cca87.PNG)

**Comment by Yoosk** [comment]
Did you install mekanism generators as well?

**Comment by ReturnedFromTheDead** [comment]
I did not! that may be the issue then. Didn't realize they were separate
mods lol

Den lør. 11. apr. 2020 kl. 19.38 skrev Yoosk <notifications@github.com>:
