### ISSUE TITLE
Mekanism registery object not present

### ISSUE THREAD

**Issue by AceSkym** [mekanism/Mekanism#6056]
#### Issue description:
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank
This is upon new install of the mod into a premodded and/or clean game. (tested both ways)

#### Steps to reproduce:
1. Download latest Mekanism file
2. Install into mod directory
3. Start minecraft

#### Version (make sure you are on the latest version before reporting):
Forge version 31.1.40
Minecraft 1.15.2
Mekanism-1.15.2-9.9.18.410

https://pastebin.com/e0cPniNN

**Comment by pupnewfster** [comment]
Please provide your latest log file as this crash report does not provide any useful information. There is a forge bug https://github.com/MinecraftForge/MinecraftForge/issues/6374 that is causing the actual source of the crash to be swallowed up, and then we crash given the game is in an invalid state when we attempt to do things.

**Comment by AceSkym** [comment]
This is my full latest crash log from my crash log folder and the crash that pops up when the crash occurs. I'm confused as to what additional information I am to provide.

**Comment by pupnewfster** [comment]
I am not asking for your crash log I am asking for the "latest log", aka the log called "latest" in your logs folder.

**Comment by AceSkym** [comment]
Apologies, I've never been asked for that one before, here is the latest 
[latest.log](https://github.com/mekanism/Mekanism/files/4467072/latest.log)

**Comment by pupnewfster** [comment]
There is something wrong given the fact that your latest log does not even contain the crash that you were sharing before. Are you sure that is the latest log from when you crashed?

**Comment by AceSkym** [comment]
[latest.log](https://github.com/mekanism/Mekanism/files/4467187/latest.log)
I'm sorry I'd tested it again with removing the mod and forgot. Here it is.

**Comment by pupnewfster** [comment]
I believe updating JAOPCA will fix this.

**Comment by AceSkym** [comment]
[latest.log](https://github.com/mekanism/Mekanism/files/4470925/latest.log)

I know this is closed, but wanted to update. Updating JAOPCA resulted in this error.

**Comment by pupnewfster** [comment]
Update the one probe, our integration requires features of TOP 2.0.2, but due to how they declare their version number, forge is unable to parse it and things the version number matches even though we specify that if TOP is loaded we need 2.0.2

**Comment by AceSkym** [comment]
Thank you!
