### ISSUE TITLE
[1.15.2] NullPointerException during Game Start

### ISSUE THREAD

**Issue by TheUntamed** [mekanism/Mekanism#6059]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crash During Game Start.

#### Steps to reproduce:
1. Start the Game with latest versions of mekanism, mekanism generators and mekanism tools

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.43 
**Mekanism:** 9.9.19.411 
**Other relevant version:** 
**Mekanism Generators:** 9.9.19.411
**Mekanism Tools:** 9.9.19.411
#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/ZKVmrEQE

Due to Line 9 you might think the problem is on the side of the torchslabsmod, but if I disable that mod it crashes again and just another mod (e.g. cookingforblockheads) is listed in the crashlog. If I remove that mod too it's another etc.

**Comment by thiakil** [comment]
Due to a forge issue failures earlier in startup do not halt execution.
Check your latest.log file for the error. (not sure why you're posting here if you don't even know its a mekanism issue)

**Comment by TheUntamed** [comment]
Well, if I backport mekanism to version 9.9.18.410 everything is fine. When I update it to 9.9.19.411 the game crashes. I didn't change anything else.
