### ISSUE TITLE
Placing down a wind generator crashed my game and now I can't get back into my world.

### ISSUE THREAD

**Issue by SRR8** [mekanism/Mekanism#6065]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
So I placed a wind generator down and my game crashed immediately. I now can't load back into my world. I placed the generator one block in front of me from the block below.

#### Steps to reproduce:
1. Place generator in front of you.
2.
3. 

#### Version (make sure you are on the latest version before reporting):
**Forge:31.1.44** 
**Mekanism:1.15.2-0.9.19.411** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

The game crashed whilst unexpected error
Error: java.lang.IllegalAccessError: tried to access class net.minecraft.client.renderer.model.ModelRenderer$TexturedQuad from class mekanism.client.model.ExtendedModelRenderer

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Update mekanism
