### ISSUE TITLE
Illegal Access to Model Renderer

### ISSUE THREAD

**Issue by ekobor** [mekanism/Mekanism#6070]
Hi;
I am running a server with one other person. 
We have a selection of mods running.
I have mostly been able to figure out an errors we've encountered, but this one confuses me. I am hoping you can help?
I think it is a Mekanism issue?

If I am wrong, I am very sorry. Maybe someone could help point me in the right direction?

#### Issue description:
Illegal Access to Model Renderer when looking at Wind Generator

Recently updated Forge to 31.1.44 and Mekanism to 9.9.19.411. Previous to update there was no issue. 

#### Steps to reproduce:
1. wind generator is placed in world
2. player looks at wind generator
3. cilent crashes

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.44
**Mekanism:** 1.15.2-9.9.19.411
**Mekanism Generators:** 1.15.2-9.9.19.411

[Client crash log](https://pastebin.com/3mrBtwpw)
[Most recent server log](https://pastebin.com/aajHqZcJ)

**Comment by pupnewfster** [comment]
Update Mekanism

**Comment by ekobor** [comment]
Oh, I am sorry I didn't notice the update!
That fixed it. Thank you for all your work!
