### ISSUE TITLE
[1.12.2-9.8.3.390] Cardboard Box Crash

### ISSUE THREAD

**Issue by arthurofus** [mekanism/Mekanism#6071]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Use Cardboard Box on a Drawer (in my case a redwood drawer (Biomes O Plenty));
2. Shift+Right click to take off the drawer.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2 - 14.23.5.2847
**Mekanism:** 1.12.2-9.8.3.390
**Other relevant version:** Storage Drawers: 1.12.2-5.4.1/Storage Drawers Extras: 1.12.2-3.1.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/CH9rhKmv

**Comment by pupnewfster** [comment]
You can blacklist blocks in the `config/Mekanism/BoxBlaclist` file (name may be slightly different its been a while)
