### ISSUE TITLE
[1.15.2] Vanilla hoppers get "stuck" while inserting into Mekanisms bins

### ISSUE THREAD

**Issue by elowanut** [mekanism/Mekanism#6072]
This issue seems to affect the insertion of items into Mekanism bins by vanilla hoppers; other insertion methods seem to work fine (Mekanism logistical transporters, the factory hopper from Engineer's Decor, etc. all work fine). 

Starting with a bin that has < one full stack of an item in it (so, <64 for most items, but < 16 for ender eyes, etc.), vanilla hoppers will insert that item until the "one full stack" amount is hit, then will get stuck. Even a hopper that is entirely full of that item cannot insert the 65th item(or 17th, etc. depending on the item). Once something else brings the item total to 65 (some other transfer method, manually placing a single additional item etc.), the hopper transfer resumes, and doesn't appear to stop anywhere else.

#### Steps to reproduce:
1. Start a modded game with only Forge and Mekanism.
2. Place a bin (anything except the creative bin, which obviously operates on a different principle)
3. Place a vanilla hopper on any side of the bin (shift-clicking it to 'attach' the hopper).
4. Fill the hopper with > 1 stack of a particular item, say 3 stacks of stone.
5. Observer the hopper steadily filling the bin with stone, then stalling once the bin contains 64.
6. Place a single additional stone in the bin, and watch the hopper transfer resume.

#### Version:
**Forge:** forge-1.15.2-31.1.46
**Mekanism:** Mekanism-1.15.2-9.9.20.412

**Comment by pupnewfster** [comment]
Strictly speaking I believe this is probably a forge bug with the implementation of their item handler wrapper, but when I get the chance to look into it I will try to submit a PR to forge to fix it if this does end up being the case.

**Comment by elowanut** [comment]
You're probably right to point at forge.

Just to add some info, this issue only occurs with Mekanism bins. Other high capacity storage systems, like Storage Drawers, Iron chests, etc. don't do this.

**Comment by pupnewfster** [comment]
This will be fixed when <https://github.com/MinecraftForge/MinecraftForge/pull/6631> gets merged.

**Comment by pupnewfster** [comment]
Updating to forge 31.1.71 or higher will fix this issue, leaving it open for now until we make another release of Mekanism, in which I will bump the minimum version of forge required to ensure this fix is included.
