### ISSUE TITLE
[1.15] Combiner: Light Blue Dye Recipe

### ISSUE THREAD

**Issue by Martin-Astos** [mekanism/Mekanism#6075]
If fixed or previously mentioned I am sorry, I have checked Twitch change log and searched the issue thread but I didn't see it. Desperate to play 1.15 mod packs so thought I had better try to help. Please close if fixed etc.

### Issue description:
Combiner recipe for Light Blue Dye is wrong.

Expected Behaviour:
Vanilla White Dye + Vanilla Blue Dye = Light Blue Dye x4

Current Behaviour:
Vanilla White Dye + Vanilla Blue Dye = Light GREY Dye x4

#### Steps to reproduce:
1. Build and power Combiner
2. Add dyes/check JEI
3. receive Light Grey Dye

#### Version (make sure you are on the latest version before reporting):
forge-31.1.44
Mekanism-1.15.2-9.9.18.410.jar

**Other relevant version:** 
ATM5 (I cant see the pack changing the recipes for these but maybe wrong. If I am will repost to their pages)

THANK YOU FOR YOUR HARD WORK.

**Comment by Martin-Astos** [comment]
Wow, that's fast and, in this troubling time, made my day to know that I have found and helped fix something (no matter how small).

Thanks

**Comment by pupnewfster** [comment]
Ya thanks for reporting it. Thankfully data generators make things nice and quick to fix. The funny thing is the comment I put in the code was correct, just seems the output was wrong, probably a copy paste error.
