### ISSUE TITLE
Personal Gas Tank Booster Pack

### ISSUE THREAD

**Issue by Martin-Astos** [mekanism/Mekanism#6076]
Scuba Gear and Jetpack are two of the best versions of themselves around, however they really don't scale up well as you progress through the mod and base game; you can make both really early and then sort of forget that you built them, just keep using them. You also have pre-existing upgradable gas tanks already built in the mod that already are "small" and about carryable size.

My idea is that could there be a way to have (a) tank(s) refill, either continuously or in a burst on depletion, the equipped item using a item much further/later in the game to improve the "things to aim for" and the "oooh mod progression". Now this has some negatives if done too simply, in particular, infinite life on item. Therefore my suggestion needs to include balancing both the setup costs (make sure it is a relatively top-ish of both the Mekanism (?inc. a Quantum Entangloporter (or just a teleportation core?) and some HDPE) and vanilla (?Chorus Fruit/Flower/Nether Star?) 'tech trees') and a degradation in efficiency of the gas transfer as the best tanks may make flight/breath time a bit too long also raising the cost of gas per second of flight/breath. 

Therefore I suggest an inventory item (a 'back pack'/'canister belt') or a pair of trousers (better as it limits the number that can be used at once without complex code, same armour comparison as Armoured Jetpack vs Diamond Chest piece or weaker?) that on their own does nothing, however can be combined with a tank of gas in the Combiner to provide the 'refill' functionality (and perhaps the armour). The gas would then be used up from the trousers at a balanced (perhaps scaling with tank size to reduce the time benefit to less extreme levels with the biggest tanks) rate until, like the Jetpack or Scuba Tanks, it is depleted. Then once placed in a crafting grid (or appropriate Mekanism machine) the tank can be removed, recovered, refilled and finally recombined with the same item. This process means that it cant be refilled on the fly meaning a return home once your trousers run out. If worried about carrying multiple copies of the item, well it will cost a lot and if you really want could be coded to not work or something if multiple are in your inventory?

**Describe alternatives you've considered**
Well generally (but not really important to you as you will only be looking inside the mod) the alternatives to my idea would be from other mods which will either have multiple tiers of Jetpack with ever increasing flight times or will have an inventory battery charging item resulting in a self recharging jetpack with lengthy flight times.

Internally the alternatives i can see, but that are less restrictive or easy to balance, would be to use the current gas tanks + chest pieces (Jetpack/Scuba Tank) in a combination recipe to increase their capacity, this just seems too simple, I would hope this could be a shining top tier item to aim for.

I am sure similar ideas have been put forward, in particular with regard to expanding Jetpack flight time, and probably been rejected. I want to propose my idea NOT for that benefit but to include a bit of the machine tier-ring system into the personal item side of the mod. Currently there are a plethora of other armours and normal tools but those are relatively speaking just "boring normal" items and progression, this brings a bit of the Mekanism core spice to the table into 2 of the best personal items you have. If you wanted, I could easily see you halving the duration of the basic tier items if necessary?

Anyway there's my piece on this matter.

Thank you for all your hard work to bring us more enjoyment in our modded worlds.

**Comment by aidancbrady** [comment]
The functionality you have described has almost exactly been implemented in the form of 'modules' for the upcoming MekaSuit.
