### ISSUE TITLE
Compatibility: java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank

### ISSUE THREAD

**Issue by PWaksman** [mekanism/Mekanism#6079]
Minecraft 1.15.2

The mod by itself is working, but it won't run with "Dank Storage" or "randomenchants" giving the error "Registry Object not present: mekanism:basic_fluid_tank".

The thing is other mods also give the same error, but they do work when added with only mekanism + the mod, which make it quite hard to find which one is causing the problem. At first it looks random which mod starts to crash with the error "Registry Object not present: mekanism:basic_fluid_tank".

In my first time looking this up, I couldn't add any of those:

- branders-sulfurpotassiummod-1.15.2-2.3.0
- buzzierbees-1.4, craftingstation-3.1.0
- SilentGems-1.15.2-3.5.2+85
- RingOfAttraction-1.15.2-1.1.26
- planttech2-0.02.04+-+1.15.2
- Bountiful-1.15.2-3.1.0

So I removed everything and add mekanism + all those mode above, and it worked. Than I started to re-add all mods back and get those mods, giving the "Registry Object not present: mekanism:basic_fluid_tank" error:

- lightestlampsmod-3.4.0
- extlights-2.0

There were other mods that didn't worked but there are just too many combinations to go through.

The funniest part is that during the process of trying to find the problem, I intentionally add back the "lightestlampsmod andextlights" to get the log and last file, and it actually manage run without the error, without downloading any upgrades. Which let me thinking if there is something to do with the order of adding mods to the game, running it, closing, adding more.

After all that, I was wondering, wouldn't be possible that the cause of the conflict with "Dank Storage" and "random enchants" is "something" close to the problem with other mods? So, maybe, solving this one would also fix the rest of them.

**Comment by thiakil** [comment]
Look through your latest.log, there will be an error earlier in the process which didn't halt loading properly

**Comment by pupnewfster** [comment]
Look at the latest.log registry object errors have nothing to do with mekanism it is a forge bug: https://github.com/MinecraftForge/MinecraftForge/issues/6374 that makes the wrong error be shown. I know at least dank storage requires mixin to be installed no idea about any of the others.

**Comment by PWaksman** [comment]
Oh damm, that is true. In the file, there is an error before, as you said. 

I bet you guys are getting tons of those false tickets, sorry for adding another thread.
