### ISSUE TITLE
[1.15.2] Setting power in Resistive heater crashes game

### ISSUE THREAD

**Issue by chestnutbak** [mekanism/Mekanism#6081]
The game crashed whilst mouseclicked event handler
Error: java.lang.RuntimeException: Un-encodable data passed to encode(): 480, full data: [480]

**Comment by chestnutbak** [comment]
[crash-2020-04-19_18.51.20-client.txt](https://github.com/mekanism/Mekanism/files/4498892/crash-2020-04-19_18.51.20-client.txt)

**Comment by TepperPepper** [comment]
Looks like you're running an outdated version of Mekanism. Try updating to the latest version (9.10.0.413).
