### ISSUE TITLE
Digital Miner Does not continue mining in end dimension

### ISSUE THREAD

**Issue by kornfan6589** [mekanism/Mekanism#6083]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Items not transferring across dimensions. Checked and made sure frequencies are correct and logistical transporters are configured properly. sucks items out of digital miner just fine. TP back to my home base in the overworld and nothing coming out of the quantum entan. however power is transferring correctly.

#### Steps to reproduce:
1. Place a digital miner with an anchor upgrade in the end (Ensuring it is contained to 1 chunk)
2. Hook up Quantum Entang. and make sure inputs and outputs are configured properly
3. Run digital miner and see items flowing through transporters into the quantum entang.
4. head back to overworld and check the other linked entang. and double check it is on the correct network, no items coming out of transporter hooked up to it.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.46
**Mekanism:** 9.10.0
**Other relevant version:** 1.15.2

EDIT: quantum entang works fine, miner stops mining when you leave the end despite being anchored and isolated to 1 chunk

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Are both chunks loaded?

**Comment by kornfan6589** [comment]
yes, the miner is anchored and remains loaded, and the entang in the overworld is anchored as well. ive been messing with it, i noticed chunks in the end are smaller? like 7 x 7? i think it might be a range issue, as in the miner going outside the chunk. im gonna test that now, but if so i dont think theres a way to fix it, just have to stand on the miner while in progress

**Comment by kornfan6589** [comment]
Update: Set radius to 3 so i know for sure its not trying to reach past its own chunk, and it stops transferring items after about 10 seconds, i can only assume the miner just stops even though the chunk shows to be active. But it does in fact transfer the items as long as i stay in the end. so, this is not a problem with the quantum entang, but a problem trying to keep the miner running. i dont know if thats fixable.

**Comment by kornfan6589** [comment]
updated title to reflect issue

**Comment by pupnewfster** [comment]
Managed to track this down and fix it so it will be fixed in 9.10.1. Took a bit to figure out but apparently if no players or vanilla force loaded chunks were in the same dimension as the chunks we were loading them in, then the chunks would stop ticking after about 15 seconds.
