### ISSUE TITLE
DigiMiner Bugged out after augmenting range to 11+

### ISSUE THREAD

**Issue by nelsonj1031** [mekanism/Mekanism#6084]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
[19Apr2020 20:43:35.792] [Server thread/DEBUG] [Mekanism_TileComponentChunkLoader/]: Attempting to remove chunk tickets. Pos: BlockPos{x=925, y=32, z=52311} World: minecraft:overworld

when a digi miner is place on overworld and we augment range to 11+ like 30 or so and add 8 speed and storage upgrades the server laggs out and kicks all players on time out.

#### Steps to reproduce:
1. set digiminer, config range
2. pick it up, put it back again
3. server crashes

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2-10.13
**Mekanism:** 1.15.2-9.9.20.412
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
If the server is crashing please provide the crash log with a gist/pastebin.
