### ISSUE TITLE
Higher Tier Transmitters (cables, pipes, tubes, etc)

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#6086]
One of the main issues that I have had with this mod is that the fusion reactor generates a massive amount of steam and electricity that the ultimate tier cables are overloaded. This is an idea to bring in a 5th and possible a 6th tier of transmitters.

-5th tier transmitters would have a diameter of 1.25 times the diameter of its counterparts and would carry 10x the material the ultimate form would.
-6th tier transmitters would have a diameter of 1.5 times the diameter of its counterparts and would carry 100x the material the ultimate form would.

Manufacturing these new tiers of cables would utilize the massive amounts of energy that is produced by the fusion reactor, for example, it would take 1gj to produce 1 5th tier tramsmitter while the 6th tier could use 25gj.

**Comment by PyroFlareX** [comment]
To add on:

Maybe use sodium?

**Comment by aidancbrady** [comment]
I think a better option is buffing our elite & ultimate tiers. I've already begun the process of doing so.
