### ISSUE TITLE
(Not Exactly a feature request) Is changing GUI text color possible?

### ISSUE THREAD

**Issue by BentoGambin** [mekanism/Mekanism#6089]
**Describe the the feature you'd like**
I'm creating a dark UI version of mekanism. I already understood the new procedural UI elements, but I couldn't find how to change the text collor. Is it even possible?
And before I forget: Thanks for the awesome mod!
(1.15.2 btw)

**Comment by pupnewfster** [comment]
Currently no, but theoretically I suppose we could probably create some sort of config option or file that gets read from resource packs. Though it probably won't happen super soon.

**Comment by BentoGambin** [comment]
Ok, now at least I know that I didn't miss anything. Btw dark backgrounds with green text would look dope and would actually fit the dark monitor in the digital miner. Just imagine the possibilities.
Thanks and bye bye

**Comment by aidancbrady** [comment]
This is now implemented in v10. Two config options- one for default title text, and one for the 'green' text color on our black screens. We also now have separate container lang mappings, so custom color codes for unique machines are possible.

**Comment by BentoGambin** [comment]
NO
WAY
you guys are awesome!
