### ISSUE TITLE
laser crash on start up

### ISSUE THREAD

**Issue by Warbringer12** [mekanism/Mekanism#6092]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. start minecraft
2. 
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.47
**Mekanism:** 1.15.2-9.10.0.413
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2020-04-22_16.56.13-client.txt](https://github.com/mekanism/Mekanism/files/4519496/crash-2020-04-22_16.56.13-client.txt)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Crash is invalid due to: https://github.com/MinecraftForge/MinecraftForge/issues/6374 Please provide your latest.log file and use something like gist/pastebin
