### ISSUE TITLE
[1.15.2] Placing Blocks on Mekanism Cables Disappearing

### ISSUE THREAD

**Issue by TR4D1T10N4L** [mekanism/Mekanism#6093]
#### Issue description:
When placing any block, onto a Mekanism cable directly. Say, if you were trying to place a machine that needs power, it might disappear. Haven't tested in singleplayer, but it happens on multiplayer. The item doesn't desync back either, it is gone forever.

#### Steps to reproduce:
1. Have a block
2. Place block on a Mekanism cable
3. Block might disappear permanently

#### Version
**Forge:** 31.1.47
**Mekanism:** 1.15.2-9.10.0.413

**Comment by pupnewfster** [comment]
Are there any specific blocks that you are trying to place that this happens with?

**Comment by TR4D1T10N4L** [comment]
Closing due to probable mod conflict.
