### ISSUE TITLE
[1.12.2] [Mek ver. 9.7.9.380] Oredictionificator creates no-texture blocks for RFTools dimensional shards that crash the game on placing in world

### ISSUE THREAD

**Issue by saianna** [mekanism/Mekanism#6096]
#5547 ## Issue description:

As in title. Using RFTools dimensional shards in Oredictionificator = no texture dimensional ore blocks that crash the game

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2 (is that the ver of MC - totally clueless - ?)
**Mekanism:** 9.7.9.380
**RFTools:** 7.73
**modpack used Dungeons, Dragons and Space Shuttles ver** 7.2b

#### If a (crash)log is relevant for this issue, link it here: https://pastebin.com/hb0ZU6FU

If this is the wrong place, i'm sorry.

**Comment by Yoosk** [comment]
1.12.2 is no longer developed or supported.

**Comment by thiakil** [comment]
nor does that crashlog point to mekanism. Try reporting to mcjty
