### ISSUE TITLE
Walkie Talkie doesnt work on 1.15.2

### ISSUE THREAD

**Issue by theLucy** [mekanism/Mekanism#6102]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Walkie Talkie doesn't work as we don't hear each other, I also enabled voice server in server config file.

#### Steps to reproduce:
1. Have turned on walkies talkies in hand
2. Push button to talk
3. No sound :/

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.49
**Mekanism:** 1.15.2-9.10.1.414
**MekanismAdditions:** 1.15.2-9.10.1.414
**Minecraft:** 1.15.2

**Comment by Tacos-5976** [comment]
Same problem in server 1.12.2 version of mods 9.8.3.390

**Comment by aidancbrady** [comment]
@Haruki1 are you playing on a Mac or PC? I’m worried that recent versions of macOS may be incompatible with the voice system- the peripheral permissions have totally changed and made it impossible to request access for things like the microphone.

**Comment by Haruki1** [comment]
Im playing on Windows 10

**Comment by nikosgram** [comment]
Same problem here

Versions
-
Forge: 31.2.0
Minecraft: 1.15.2
Mekanism: 1.15.2-9.10.6.419
MekanismAdditions: 1.15.2-9.10.6.419

**Comment by Arifuzzaman9** [comment]
Hey,

I am fan of you blog, it helps me to improve my study. Thanks for presenting such nice and great informative article named "Programming the Motorola XT420 Walkie Talkie".  Visit here...  [two way radio](https://www.nowiresradio.com)

Cheers
