### ISSUE TITLE
Missing items on version 1.15.2

### ISSUE THREAD

**Issue by edgefiller** [mekanism/Mekanism#6107]
#### Issue description:
Both Fuelwood heater and Resistive Heather doesn't appeared on my version, even when i'm using JEI or the recipies book from vanilla.

#### Steps to reproduce:
1. Gather the materials necessary for each heater.
2. Craft the items as shown on the mekanism wiki.
3. Look at both JEI or minecraft recipe book.

#### Version :
Forge: 1.15.2
Mekanism: 9.10.1.414

**Comment by Yoosk** [comment]
Did you install all mekanism modules like `mekanism generators` which should contain said generator?

**Comment by pupnewfster** [comment]
I believe the heaters are in the main module, but I don't remember them being missing. Is it possible they are disabled in whatever modpack you are playing for some reason?

**Comment by ocram9** [comment]
I just checked in my server, the heaters are showing up in JEI and have crafting recipes. It is indeed in the main module.

**Comment by edgefiller** [comment]
Confirmed, the problem is by some mean, most of the items in the mod are in the original language and the heat generators are translated, also, they reapeared in JEI by installing again all modules.
Thank you for your support to everyone.
