### ISSUE TITLE
Bug with Solar Panels

### ISSUE THREAD

**Issue by Ibirtem** [mekanism/Mekanism#6110]
The top advanced solar panels do not fall out if they are in another solar panel.

Steps to reproduce:
1. Make structure like on picture
2. Break the bottom solar panel

Forge: 31.1.63
Mekanism: 9.10.1.414

![image](https://user-images.githubusercontent.com/54157950/80632448-fc70d280-8a5f-11ea-8d87-628cc708dc59.png)

**Comment by aidancbrady** [comment]
You shouldn’t be able to place overlapping solar generators regardless.
