### ISSUE TITLE
Misformed Turbine Crashes Server

### ISSUE THREAD

**Issue by Malp12** [mekanism/Mekanism#6112]
(I don't know how tags work, I assume that's a mod action? Github noob here. I probably wrongly deleted my original issue...but in the interim, I reproduced the error and describe it below.)

#### Issue description:
My first attempt at a Turbine multiblock. I unknowingly omitted the electromagnetic coil level, but made a 2 high rotor. I closed up the structure, saw red sparks flash for a multiblock complete, then the server crashed.

#### Steps to reproduce:
1. Build the following (incorrect) reactor, 5x5 base, (I followed the guide wrong and missed the coils, I made the rotor 2x high, whereas the wiki's minimum is obviously 1x high): L1 base, L2 rotor, L3 rotor, L4 rotational complex + 8 pressure distributors, L5 casing.
2. The electromagnetic coil level above the rot complex and distributors doesn't exist.
3. As soon as you complete the top casing, client and server crash.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2-31.1.50
**Mekanism:** 1.15.2-9.10.1.414
**Other relevant version:** Mekanism Generators 1.15.2-9.10.1.414

#### If a (crash)log is relevant for this issue, link it here: [crash-2020-04-30_04.56.53-server.txt](https://github.com/mekanism/Mekanism/files/4556522/crash-2020-04-30_04.56.53-server.txt)

**Comment by pupnewfster** [comment]
Thanks for the detailed issue, but closing it as we are currently tracking this crash here: #6100 and it is fixed in dev.
