### ISSUE TITLE
digiminer tag for glowstone not working?

### ISSUE THREAD

**Issue by DoomSquirter** [mekanism/Mekanism#6113]
#### Issue description:
I put minecraft:glowstone into tag for digiminer but when I enable advanced tooltips (F3+H) it shows that under glowstone in JEI without a # in front of it.

A mod I guess adds a actual tag (prefaced with # in front of the name and I tried using that and it did not work either.
it says 
minecraft:glowstone
#lightestlamp:glowstones

in jei.  I assume the second one is a valid tag but it doesn't show anything for a image when I save it.  

Is this cause forge hasn't added a real forge:/glowstone or some tag for it already or is it mekanism issue?

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.1.49 ** 
**Mekanism:Mekanism-1.15.2-9.10.1.414** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Looks like the tag you are talking about would be: `lightestlamp:glowstones`. Note, the digitial miner would only be able to mine it if there is a block tag added with that. The mod displaying tags is likely only displaying item tags, and maybe that mod has only added glowstone to an item tag and not a block tag.

**Comment by DoomSquirter** [comment]
itemstack works fine.  thanks for responding.  guess it's forge's issue for not adding a valid tag.

**Comment by v-tron** [comment]
The forge tag would be: `forge:storage_blocks:glowstone`
