### ISSUE TITLE
Make electric bow fire arrows set blocks on fire too

### ISSUE THREAD

**Issue by kmecpp** [mekanism/Mekanism#6114]
Can the arrows shot from the electric bow in fire mod set blocks on fire too please?

**Comment by pupnewfster** [comment]
The arrows shot from an electric bow with fire mode enabled, behave and act the same way vanilla's flame enchantment works. If you want a mod that changes flaming arrows to be able to light blocks on fire you should look for another mod to do so, as we do not plan on changing that vanilla mechanic.
