### ISSUE TITLE
Server Crash at mekanism.common.content.transporter

### ISSUE THREAD

**Issue by IchigoGames** [mekanism/Mekanism#6115]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
server crashed looks like something to do with logic sorting pipes from mek

#### Steps to reproduce:
1.not sure as i was not the one crashed it
2.
3.

#### Version (make sure you are on the latest version before reporting):

**Minecraft 1.15.2
**Forge:**31.1.50
**Mekanism:** Mekanism-1.15.2-9.10.1.414

**Other relevant version:** 

MekanismGenerators-1.15.2-9.10.1.414
MekanismTools-1.15.2-9.10.1.414
MekanismAdditions-1.15.2-9.10.1.414

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/3emrXPpx
[latest.log](https://github.com/mekanism/Mekanism/files/4562366/latest.log)

**Comment by IchigoGames** [comment]
this may should be its own issue report but i am getting lots of spam in console from mek saying 
[01:19:35] [Server thread/ERROR] [Mekanism/]: Stack size changed by a different amount than requested. with lots of code and stuff under it so much so its the only thing showing up in console

**Comment by pupnewfster** [comment]
That would be its own issue report, and would need more information than that. Might not even be a bug in mekanism but the mod that your pipes are connected to.
