### ISSUE TITLE
During temperature calculation, there is a possibility of dividing by zero BUG

### ISSUE THREAD

**Issue by bamboo98** [mekanism/Mekanism#6117]
During temperature calculation, there is a possibility of dividing by zero BUG

I can reproduce it 100% in my first game save, but when I build the same structure in the new save, it fails
When I first discovered it,
My boiler temperature is displayed as "0.0 YK"
But no errors or crash logs were generated, although the output of the boiler became 0
Speculate (but did not reproduce):
When the heater is placed next to the quantum transmission, some incorrect block update sequence may cause the heater's temperature to be shifted, making it "0.0 YK"
Including other machines connected to this heater will also become "0.0 YK"

When the temperature of a machine (multi-block structure) becomes 0, unless the machine is completely removed, there is no other way to solve this problem during the normal game.
(I solved this problem with NBTExplorer, search for "temperature = NaN" tags in the ".mca" file, and confirm the cachedID, modify "temperature" to any positive number, since the result appears "NaN", I think this should Is a divide by zero bug)

The NBT of the block with the wrong data is as follows:
{
cachedWater: {
    Amount: 46656000
    FluidName: water
}
cachedID: xxxxxxxxxxxxxxxx
facing: 3
id: mekanism: boiler_casing
redstone: 0
temperature: NaN
x: xxx
y: xxx
z: xxx
}

#### Version (make sure you are on the latest version before reporting):
**Mekanism:9.8.1.383

**Comment by pupnewfster** [comment]
I don't remember and somewhat doubt it but there is a slight chance this got fixed in 9.8.2 or 9.8.3 as 9.8.1 is not the latest version of Mekanism for 1.12. If not this probably has been fixed our rewrite of the heat system in 1.15 so for now I am going to go ahead and close this.

**Comment by Breadabix** [comment]
I am currently on 9.8.3 and having this issue, do either of you know a fix for this as im guessing there wont be another 1.12 update for mekanism?
