### ISSUE TITLE
Oredictionificator not remembering which version of ingot/block has been requested

### ISSUE THREAD

**Issue by HowardRoark2016** [mekanism/Mekanism#6118]
#### Steps to reproduce:
1. All The Mods 5 v1.21 using Mekanism-1.15.2-9.10.1.414 (Both are the most current as of this post)
2. Set some ingots and blocks in Oredictionificator. Choose which mod's ingots and blocks to convert to.
3. Exit game and relaunch. Check Oredictionificator.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.63
**Mekanism:** 1.15.2-9.10.1.414

**Comment by pupnewfster** [comment]
I think I know what is going on, the issue is that tags are unordered (at least between restarts) so the way we persist which one is selected will need to change.
