### ISSUE TITLE
digiminer not accepting energy cubes in top right slot

### ISSUE THREAD

**Issue by DoomSquirter** [mekanism/Mekanism#6119]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
In another 1.15 pack, I was never able to get a energy cube into the energy slot of the digiminer so I assumed it was something still being worked on.
In this pack, right from the start I was able to put an ultimate energy cube into digiminer as well as take it out and charge it and put it back again, at least a few times.

I just charged it again and this time however, it just won't go in the slot.  I'm wondering if it picked up some metadata or something causing this to happen?

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.1.49 **
Mekanism:Mekanism-1.15.2-9.10.1.414

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by DoomSquirter** [comment]
for reference, here's the metadata for the cube
https://imgur.com/a/gAJUojm

**Comment by aidancbrady** [comment]
A 'bug' exists currently that doesn't allow insertion of energy cubes when a machine's energy buffer is full. This is fixed in v10.
