### ISSUE TITLE
questions about purification chamber / oxygen usage

### ISSUE THREAD

**Issue by DoomSquirter** [mekanism/Mekanism#6120]
#### Issue description:
1) is it normal for purification chamber to not have a gas input?

2) is it normal for purification chamber to not accept anything but the basic tank of oxygen?  (Ultimate tank full of oxygen does not go in the extra slot)

if true to either of the above, is the only way to truly automate it is by inputting flint into the extra?

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.1.49 **
Mekanism:Mekanism-1.15.2-9.10.1.414

**Comment by aidancbrady** [comment]
The Purification Chamber can accept Oxygen from Pressurized Tubes- you can configure which sides can accept using the Side Configuration tab.

**Comment by DoomSquirter** [comment]
ummm please reopen this.  I already tried that and there's no gas section, otherwise I would have done just that.
there is just items and energy, nothing else.

**Comment by DoomSquirter** [comment]
for proof:
https://imgur.com/a/0D2v6l1

**Comment by DoomSquirter** [comment]
I made another chamber and also spawned one in and both had no gas section to configure.  a pressurized tube connected to the back of the machine doesn't disconnect as if there wasn't a gas input but it also doesn't do anything, like input oxygen.  sorry for pinging, just want to ensure you see this...
@aidancbrady

**Comment by aidancbrady** [comment]
Do you have oxygen flowing in the connected pressurized tubes?

**Comment by DoomSquirter** [comment]
yeah, I used the configurator on both ends of pressurized pipe
but again, there's no section in the side menu for gas, just energy and items, which is why I posed the question in the first place.  
I've been making all the ore proc tiers going backwards and this is the only machine I've seen that seemed to be missing something.

**Comment by DoomSquirter** [comment]
ok I tried it again and yes, oxygen does go in.  It may have not worked previously cause I had thrown flint in?  coming from a tank?  (I saw the pipe turn blue so I know oxygen was going through it)
Really clueless why it's working now.
but just as a clarification, there are still 2 outstanding issues here.
1) there is no gas section in the machine to configure inputs/outputs
2) you can put a basic tank in the extra slot but not an ultimate (assuming anything other than basic will not work)

**Comment by aidancbrady** [comment]
@pupnewfster I think this might have to do with the full buffer fill slot issue

**Comment by DoomSquirter** [comment]
probably not a better place to say this, but seeing mek as the only all in one mod that were in the only 2 1.15 packs I've played thus far has been quite enjoyable.  Doing everything with mek and only mek brings me back :)  Been super happy about everything.  congrats on porting it so quickly.

**Comment by DoomSquirter** [comment]
I can confirm the ultimate tank goes in if the gas isn't full.  definately the <= issue.  so I guess the only issue is no gui for gas in the purification chamber
