### ISSUE TITLE
Possible Bug with Industrial Turbines

### ISSUE THREAD

**Issue by GoodGuyTuring** [mekanism/Mekanism#6121]
#### Issue description:
After upgrading to 1.15.2, it seems that Turbines can't be build anymore. After following construction steps from multiple sites (https://ftbwiki.org/Industrial_Turbine and https://wiki.aidancbrady.com/wiki/Industrial_Turbine) and trying different sizes, I am quite sure, the blocks wont combine into the turbine. I added multiple screenshots showing how I build the turbine. I also made sure, I didn't use vents instead of dispersers.
Every other structure is working properly.

#### Order I build the Turbine:
1. 5x5 Base of Turbine Casing
2. Shaft with 5 height and 2xRotors on every Shaft 
3. Building outer frame and Rotational Complex
4. Pressure Disperser and part of upper Casing
5. Coils and Structual Glass
6. 2 Layers of Vents
7. Finished upper Casing (at this point it should build into the Turbine
8. Placed 2 Valves at the bottom

**Forge:** 31.1.63
**Mekanism:** 1.15.2-9.10.1.414

![2020-05-02_11 53 12](https://user-images.githubusercontent.com/43540036/80861387-88f0e000-8c6e-11ea-99d0-0ae5ff2beacc.png)
![2020-05-02_11 55 02](https://user-images.githubusercontent.com/43540036/80861391-91491b00-8c6e-11ea-80fe-68cb3ab9b27a.png)
![2020-05-02_11 55 35](https://user-images.githubusercontent.com/43540036/80861393-94dca200-8c6e-11ea-94cb-c880534a4699.png)
![2020-05-02_11 56 07](https://user-images.githubusercontent.com/43540036/80861396-9c9c4680-8c6e-11ea-99f4-1a98ba0bd16c.png)
![2020-05-02_11 57 25](https://user-images.githubusercontent.com/43540036/80861411-acb42600-8c6e-11ea-9b00-ce67d1cc5330.png)
![2020-05-02_11 57 52](https://user-images.githubusercontent.com/43540036/80861413-b2117080-8c6e-11ea-9171-53b6bc8d8825.png)
![2020-05-02_11 58 28](https://user-images.githubusercontent.com/43540036/80861415-b5a4f780-8c6e-11ea-94c3-36141f06cc0a.png)
![2020-05-02_11 58 41](https://user-images.githubusercontent.com/43540036/80861419-b8075180-8c6e-11ea-8b13-450ee53884d3.png)

**Comment by pupnewfster** [comment]
The top needs to be turbine casing, try adding another row on top.

**Comment by GoodGuyTuring** [comment]
I tried it, still not working (and it should work with Vents ontop)
![2020-05-02_15 25 03](https://user-images.githubusercontent.com/43540036/80865357-2bb65800-8c89-11ea-88e7-e4b5a2583531.png)

**Comment by pupnewfster** [comment]
By forming you do mean the multiblock sparkle and attempting to right click it opening a GUI right? Not the connected textures which requires the connected textures mod that doesn't have a release version for 1.15 yet.

**Comment by aidancbrady** [comment]
Try making your turbine rotor stack a little shorter. It looks close to the edge- the turbine won’t form if rotor blades are touching (or almost touching) the sides.

**Comment by GoodGuyTuring** [comment]
@pupnewfster yes i mean the sparkles / hud
@aidancbrady makes no difference even at the height of 3 it won't work

**Comment by aidancbrady** [comment]
So it turns out the turbine’s narrowness calculation is a bit bugged. Make your turbine either shorter or wider and it will work fine.

**Comment by GoodGuyTuring** [comment]
But even when I build a 9x9x9 Turbine (Shaft height 5) it wont build.

**Comment by aidancbrady** [comment]
I've tweaked the logic of formation logic which should hopefully fix this (and similar) issues.

**Comment by celebite** [comment]
Just a suggestion as i ran into the same issue, i had 2 rows of vents ontop of each other. Once i made the top layer only vents it worked. May be wrong but i had to reduce my vent to the layer after saturation vents. Vents are still visible but purely 3 layers, pressure-saturation-vents

**Comment by cyruskhalvati** [comment]
same issue 1.12.2 wasted 4 hours thinkin im the one making mistakes -.-
