### ISSUE TITLE
Logistical Sorter not working with water buckets

### ISSUE THREAD

**Issue by lvaroqui** [mekanism/Mekanism#6122]
#### Issue description:

Logistical sorters do not work with water bucket in "Item Stack" Mode

#### Steps to reproduce:
Just try, it does not work

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2847
**Mekanism:** 9.8.3.390

**Comment by pupnewfster** [comment]
Unable to reproduce in 1.15, if it was broken in 1.12 it seems the port/rewrites we made in 1.15 fixed it.
