### ISSUE TITLE
[Mekanism/]: Stack size changed by a different amount than requested.

### ISSUE THREAD

**Issue by IchigoGames** [mekanism/Mekanism#6123]
#### Issue description:
console spam not sure what to make of it but cant see anything in console but this.
https://pastebin.com/1mpi4FLD

#### Steps to reproduce:
1.not sure
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.50
**Mekanism:** Mekanism-1.15.2-9.10.1.414
**Other relevant version:** 
MekanismAdditions-1.15.2-9.10.1.414
MekanismTools-1.15.2-9.10.1.414
MekanismGenerators-1.15.2-9.10.1.414

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/1mpi4FLD not crashlog
https://www.dropbox.com/s/fj7zf56i523icnn/latest.log?dl=0 could not add here said to large.

**Comment by pupnewfster** [comment]
Thank you for reporting this, going to close/merge this issue with #6090 as I believe there is some issue with network distribution where the numbers end up being slightly off. Hopefully between the two logs (the one aidan provided for me there), and this one I will be able to track down the issue.

**Comment by pupnewfster** [comment]
Actually if this is still currently happening in your world, would you be able to provide a world download as well as the name of the pack you are playing (or the mods you have installed). Given while I did go ahead and merge this issue with the other one, I still personally have yet to be able to replicate it so it would probably be useful to see the setup that is causing it.

**Comment by IchigoGames** [comment]
the modpack is https://www.curseforge.com/minecraft/modpacks/the-endless-frontier im the modpack creator and i atm i cant my internet sucks to bad to download and re upload world but im getting faster internet Thursday so i should be able to then if this is still a issue.

**Comment by pupnewfster** [comment]
Ended up releasing 9.10.2 with various fixes though I doubt it will fix this issue as I was unable to reproduce it (so will wait until you are able to upload a world with it included). I did however add *slightly* improved logging for the issue so that at least it will now show how much it expected the stack to change by versus how much it actually changed by.

**Comment by IchigoGames** [comment]
ya its still doing it https://pastebin.com/AbBHkacZ ill get you the world download as soon as i have faster internet.

**Comment by IchigoGames** [comment]
https://www.dropbox.com/s/rsvtoviux4ez9sc/world.zip?dl=0 world file

**Comment by pupnewfster** [comment]
Thank you for the world file. I am still having some issues reproducing the issue still though. Does the error always get logged to the console or only when specific players are online, and if it is only when specific players are online what are the coordinates of their bases (for purposes of tracking down which chunks the tubes are in that are causing the error to occur in).

**Comment by pupnewfster** [comment]
Never mind I looked through the code some more and was able to reproduce a scenario that causes it to break so I should be able to implement a fix for 9.10.3

**Comment by trexdel** [comment]
Hello - having a similar issue. Stack size changed by a different amount (7999) than requested (8000). 

https://pastebin.com/r9uDS5bg

Forge 1.19.2-43.3.0
Mekanism 1.19.2-10.3.9.13
No other mekanism addons included, though I do have ~210 mods. Custom pack.
Also having issues with [log spam #7733](https://github.com/mekanism/Mekanism/issues/7733), though I'll post about that over there.

Cheers.

Edit - apologies if necro.
