### ISSUE TITLE
[1.12.2] Digital Miner incompatible with Ore Stages after 9.8.3.375

### ISSUE THREAD

**Issue by Gamertech** [mekanism/Mekanism#6124]
#### Issue description:
Digital Miner now seems to be incompatible with Ore Stages. Previously once ores were revealed, it'd mine them fine, now it only mines the mask block and nothing else. Miners from other mods are working fine.

I've tracked it down to changes in Mekanism 9.8.3.375
.374 and earlier mine ore correctly.

#### Steps to reproduce:
1. Install 1.12.2 Mekanism/Game Stages/Ore Stages
2. Hide any ore using Ore Stages
3. Give yourself the required stage
4. Mine ore using Digital Miner
5. Get cobble or whatever mask block you've set instead of the ore

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2847
**Mekanism:** 1.12.2-9.8.3.390

**Comment by pupnewfster** [comment]
My guess is that it was an update/change in ore stages that "broke" it and isn't a change that happened in 9.8.3. As looking at the change log we did not touch the miner in 9.8.3. The digital miner uses a fake player and my guess is that the fake player does not have the stages that would be required to see the ore for what it is. Going ahead and closing this as we are no longer updating the 1.12 version and there is no version of ore stages for 1.15.

On a side note at some point during Mekanism V10 development I do plan on attempting to create some form of API to allow staging mods to "know" what player the fake player is acting on the benefit of.

**Comment by Gamertech** [comment]
My bad, typo. The actual version the digital miner broke was 9.7.4.375 onwards, not 9.8.3.

And yes, it was a Mekanism change that caused it. I can flick between 9.7.4.375 and 9.7.3.374 and start/stop the miner working correctly @pupnewfster

**Comment by pupnewfster** [comment]
Ah, looking at the changelog for that we did fix a few bugs with the digital miner. My guess is it is this [line](https://github.com/mekanism/Mekanism/commit/e3161cf2db8c9572a82182de42bdfbd68fd93bc5#diff-f8887ff5372bcf7cddb782bcb63d10adR106) that "broke" it by fixing our implementation to actually call the correct hooks which ended up allowing ore stages to "properly" intercept and stop the miner.

**Comment by Gamertech** [comment]
Does the DigiMiner have a set fakeplayer name? I might be able to dodgy it by granting it a default stage.

**Comment by pupnewfster** [comment]
The fake player for mekanism prints its name and uuid to the log on startup. I don't remember offhand what the values are.

**Comment by Gamertech** [comment]
The name was [Mekanism].

Managed to work around by adding a gameStagesFakePlayerData.json to config with:

[
  {
    "fakePlayerName" : "[Mekanism]",
    "stages": [ "zero", "one", "two", "three", "four", "five" ]
  }
]

Cheers
