### ISSUE TITLE
[1.15.2] Repairable Armor

### ISSUE THREAD

**Issue by NillerMedDild** [mekanism/Mekanism#6127]
**Describe the the feature you'd like**
I would like to be able to repair Lapis/Steel/Refined Glowstone/Refined Obisidian Armor in an anvil, using ingots or in the case of Lapis, Lapis "gems".

https://imgur.com/NVghyEY
https://imgur.com/LadrION
https://imgur.com/BGcMpNi

**Comment by pupnewfster** [comment]
#6105

**Comment by NillerMedDild** [comment]
Ah sorry, didn't find that ^^' thanks!

**Comment by pupnewfster** [comment]
No problem, but ya the issue more is that in the current released version it doesn't check tags and just checks our items given I didn't give it much thought when initially porting the repairing from 1.12 which didn't support things like oredictionary.
