### ISSUE TITLE
Mod Compatibility Issue (1.12.2):  Apotheosis Mob Spawner and Mek Cardboard Box

### ISSUE THREAD

**Issue by hyperjoe** [mekanism/Mekanism#6128]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When using Mekanism Cardboard boxes to move spawners that have been customized via the Apotheosis mod,  customizations such as Spawn delay (max and min) are maintained.

However,  if you pick up a spawner that has "Requires Redstone" or "Ignores Spawn conditions"   enabled (via a redstone comparator or dragon egg), that trait is stripped from the spawner either upon applying the cardboard box or removing it.  

I've not tested with "ignores player"  or "ignores spawn cap"  but I suspect that the same will happen in those situations as well.    

This may be an issue with Apotheosis so I reported this issue on their github as well.

#### Steps to reproduce:
1.  Right click an Apotheosis Spawner (most vanilla spawners when Apotheosis is installed) with a Redstone Comparator.
2.  Check the "Sneak Info" to confirm that the spawner now "Requires Redstone"
3.  Right click the spawner with an empty cardboard box.
4.  Right click the Cardboard box with an empty hand to remove the cardboard box.
5.  Check the "Sneak Info" to confirm that the spawner no longer "Requires Redstone"

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-14.23.5.2847   ** 
**Mekanism:  Mekanism-1.12.2-9.8.3.390  ** 
**Other relevant version: Apotheosis-1.12.2-1.12.5 ** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Unable to reproduce in 1.15 with both mekanism and apotheosis.

**Comment by hyperjoe** [comment]
Thanks for looking into it!  If it's no longer an issue in 1.15, then I look forward to when 1.15 mods are ported enough for me to migrate to that version!
