### ISSUE TITLE
Crushing recipe balance

### ISSUE THREAD

**Issue by Snownee** [mekanism/Mekanism#6130]
#### Issue description
![image](https://user-images.githubusercontent.com/16059084/80959652-d3728800-8e39-11ea-9f85-67e9282cced5.png)
![image](https://user-images.githubusercontent.com/16059084/80959659-d7060f00-8e39-11ea-9223-3172e097bb91.png)
![image](https://user-images.githubusercontent.com/16059084/80959669-db322c80-8e39-11ea-94cf-6137c7494494.png)

#### Version
**Mekanism:** 1.15.2-9.10.1.414

**Comment by pupnewfster** [comment]
I think this may be more of a vanilla bug but going to leave it open for @aidancbrady to decide on. Our crusher to bio fuel recipes are directly based on the rates vanilla uses in the [composter](https://github.com/mekanism/Mekanism/blob/1.15x/src/datagen/main/java/mekanism/common/recipe/MekanismRecipeProvider.java#L406-L414)

**Comment by aidancbrady** [comment]
Given there's no duplication here and we literally mirror Minecraft's own recipes, I'm gonna pass this off as 'not our problem.' Appreciate the report though.
