### ISSUE TITLE
Mechanical Pipes breaking on Thermal Evaporation Plant Valves (Version 1.15.2)

### ISSUE THREAD

**Issue by TheGameKing1001** [mekanism/Mekanism#6135]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I was in the process of making the 4x ore processing setup and I knew i would need to get brine from a Thermal Evaporation Plant. So i got the plant set up and i was getting the pipes in place on the valve ports and when i placed the pipes on the second valve the pipe on the first valve disconnected. And when i do get them connected if i place any block near them they break again.

# Steps to reproduce:
1. Build a Themal Evaporation Plant with two valve ports
2. place a mechanical pipe on one of the ports
3. place a mechanical pipe on the other port
4. notice that the pipe on the first port is not connected any more

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2-forge-31.1.74
**Mekanism:** 1.15.2-9.10.2.415
**Other relevant version:** Minecraft 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by tiphilou17** [comment]
i place a tesseract directly on salination's valve, its ok
