### ISSUE TITLE
Logistical Transporters cause a lot of lag

### ISSUE THREAD

**Issue by twothe** [mekanism/Mekanism#6136]
#### Issue description:

Mekanism Logistical Transporters use up a lot of server time for even the most simplest setup in comparison to other mods. As a result Mekanism transportation is banned on all larger servers.

#### Steps to reproduce:
![image](https://user-images.githubusercontent.com/1131621/81074362-2eaf8380-8ee9-11ea-8b6c-d07fa94acce0.png)

I did this simple setup where items are piped from one infinite BDSaM crate into a void crate, and the pipe uses 80 uS already for that simple task. Similar setups with more slots on the receiver side (e.g. any elite Mekanism machine, or even normal Minecraft chests) increase that even further. In a complete x3 ore processing setup with 1 gap between machines for the transporters, Logistical Transporters used more server time than the actual processing.

A similar setup with other mods, i.E. ProjectRed pipes use significantly less computation time:
![image](https://user-images.githubusercontent.com/1131621/81074560-759d7900-8ee9-11ea-83da-17f9f2bfc0a0.png)
30 uS in this case.

With more machines attached to a network that time increases drastically, while other mods handle that much smoother.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2854 (same result with other versions)
**Mekanism:** 1.12.2-9.8.390

**Comment by Yoosk** [comment]
Mekanism for Minecraft 1.12.2 is not supported or developed anymore.

**Comment by pupnewfster** [comment]
Additionally we have made various performance improvements in 1.15, so I don't think this is as much of an issue anymore. Not to mention 80 uS is really not that much when things are set to say force pull, a vanilla hopper often will be at 300 uS when stuck unable to insert.

**Comment by twothe** [comment]
With FTB withdrawing their mods especially the Quest mods, and several other mods gone missing, 1.15 will most likely one of these ignored versions, and 1.12 will most likely be around for quiet some more time. It would be great if you could backport those performance updates to 1.12 if that is not too much to ask.

On the 80uS: yes that is not much on it's own, but in most tech-mods like Skyblocks people tend to build truly massive installations with hundreds of pipes and such. With that every uS counts to make sure players have a good experience and not drown in lag. As I said: most larger servers disable Mekanism pipes for that reason, because those extra 50uS compared to other mods pile up to 5-10 more players that can play instead very fast.

**Comment by pupnewfster** [comment]
While I do agree that it is unfortunate when some mods get left behind/don't update due to the lack of time the mod developers have; we unfortunately do not have the time nor desire to spend hundreds of hours working on backporting changes to 1.12. Given as modders we do this in our free time, and would much rather spend it creating new and exciting features for Mekanism V10.

**Comment by thiakil** [comment]
You also cannot compare mods using _just_ lag goggles - our processing gets done on the tile entity, but if we did it in a separate handler it just wouldn't show

**Comment by twothe** [comment]
> You also cannot compare mods using _just_ lag goggles - our processing gets done on the tile entity, but if we did it in a separate handler it just wouldn't show

LagGoggles shows both, the tile entity time and the handler times. Additionally I compared it with the actual TPS to make sure the measurements are correct.

> And what do you mean by FTB withdrawing their mods? All of them are fine and available for 1.15.
FTB broke up with Twitch and will no longer support the Twitch Launcher. That will make a lot of things complicated for mod-pack developers.

**Comment by Yoosk** [comment]
I am modpack developer i have no issues with them leaving cruseforge. Their mods do `support` twitch launcher, it's just a launcher and its not related to how they left curse.

**Comment by twothe** [comment]
All I wanted to say is that abandoning 1.12 just yet might be a bit premature.
