### ISSUE TITLE
Resistive Heater Crashed Game on attempt to enter usage value

### ISSUE THREAD

**Issue by Dartouious** [mekanism/Mekanism#6138]
Just as the title suggests, when attempting to enter a usage value, the game crashes as soon as I clicked the checkmark. Anyways... here is the crash report. If you need any more information please let me know!

[crash-2020-05-06_01.39.57-client.txt](https://github.com/mekanism/Mekanism/files/4584962/crash-2020-05-06_01.39.57-client.txt)

**Comment by thiakil** [comment]
1. Please learn to follow instructions
2. Update mekanism and try again, comment here if it still happens
