### ISSUE TITLE
[1.15.2] Dupe-Bug 

### ISSUE THREAD

**Issue by MoeHunt3r** [mekanism/Mekanism#6142]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When right clicking a Sink from Cooking for Blockheads with a tank the tank is placed but also remains in players hand. 

#### Steps to reproduce:
1. Take a Fluid Tank 
2. Right click the sink with fluid tank
3. Item gets placed on top of the sink and one remains in the players hand. 

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.1.77
**Mekanism:  9.10.2.451
**Cooking for Blockheads: 8.0.1
** Just Enough Items: 6.0.0.4
Twitch-Clip:
https://clips.twitch.tv/KathishBlitheCamelKlappa

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/T1PZcHg2

**Comment by pupnewfster** [comment]
Did some testing and tracked it down to a [bug](https://github.com/blay09/CookingForBlockheads/blob/1.15.x/src/main/java/net/blay09/mods/cookingforblockheads/block/SinkBlock.java#L102) in CookingForBlockheads. I let the dev know and they are going to end up removing the extra check about block items which will fix this issue.
