### ISSUE TITLE
Enrichment chamber not working

### ISSUE THREAD

**Issue by bmatusz** [mekanism/Mekanism#6144]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
put any ore in enrichment chamber

#### Steps to reproduce:
1. craft enrichment chamber
2. place near heat generator - it's powered
3. put ore inside, like iron

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.49
**Mekanism:** 9.9.5
**Other relevant version:** Mekanism Generators  9.9.5
Mekanism Tools 9.9.5
#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]
![image](https://user-images.githubusercontent.com/16103569/81340789-bb586e00-90b0-11ea-86f4-2c478915e284.png)

**Comment by pupnewfster** [comment]
You are using a very old version of Mekanism for 1.15.

**Comment by bmatusz** [comment]
very old? It's from 18th April 2020
Mekanism-Mod-Tools-1.15.2.jar
Mekanism-Mod-Generators-1.15.2.jar
Mekanism-Mod-Core-1.15.2.jar

**Comment by pupnewfster** [comment]
Where did you download that from as those are not our file names? https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2868473 9.9.5 was released on jan 24th

**Comment by bmatusz** [comment]
OK got the newest one
Working fine thanks!
