### ISSUE TITLE
LEVER ON LASER AMPLIFIER REACTOR

### ISSUE THREAD

**Issue by tiphilou17** [mekanism/Mekanism#6145]
Hi,
Issue description:
i can't place a lever on the top of laser amplifier to load energy as this video : https://www.youtube.com/watch?v=WH_1JTaboOs

Steps to reproduce:
-place lever on laser amplifier to load system but impossible.

Version (make sure you are on the latest version before reporting):
**Forge: 1.15.2 - 31.1.77
**Mekanism-1.15.2-9.10.2.415

**Comment by pupnewfster** [comment]
The laser amplifier is not a full block just place a lever next to it.
