### ISSUE TITLE
game crash: Registry Object not present: mekanism:laser

### ISSUE THREAD

**Issue by juanretamales** [mekanism/Mekanism#6147]
The game crashed whilst initializing game
Error: java.lang.NullPointerException: Registry Object not present: mekanism:laser

[crash-2020-05-08_21.45.53-client.txt](https://github.com/mekanism/Mekanism/files/4602365/crash-2020-05-08_21.45.53-client.txt)

**Comment by pupnewfster** [comment]
This crash has nothing to do with mekanism and is a side effect of https://github.com/MinecraftForge/MinecraftForge/issues/6374 if you post your latest.log we can potentially point you to the actual crash.
