### ISSUE TITLE
Universal Cables broken in 9.10.3

### ISSUE THREAD

**Issue by twistedretard** [mekanism/Mekanism#6148]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Had some severe memory leaks in 9.10.2 from leaking lambdas, TNP Limitless 2 pack, so updated to test if the leak is still present in 9.10.3 but now I'm having problems with Universal Cables not transferring power to machines from other mods. Attaching energy cubes directly to the machines works and the universal cables works with Mekanism machines but no other machines that I've currently tested with.
Also the flux plugs visually attaches to the Cables if placed down next to them but if instead a cable is placed down next to the flux plug there is no visual update that the flux plug attaches to the cable.
 
#### Steps to reproduce:
1. Create new flat world
2. Place down Creative energy cube
3. Place down machine (tried Refined storage controller, Silent mechanics machines and Flux network plugs and points)
4. Connect with Universal Cable (any tier)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.74
**Mekanism:** 9.10.3
**Minecraft:** 1.15.2

**Comment by pupnewfster** [comment]
I will try to look into this at some point (rather busy currently with the final week of the semester), but in terms of the "leaking lambdas", I have no idea what you mean. If you have evidence of a memory leak coming from Mekanism feel free to open another issue for it including any profiling results that led you to the conclusion it was Mekanism.

**Comment by twistedretard** [comment]
Sorry maybe poor choice of wording.
My suspicion is that Powah! is leaking Mekanism listener registerd lambda functions (By using new in LazyOptional).
But if I find the error to be connected to Mekanism I will make a new issue.

**Comment by pupnewfster** [comment]
Turns out the main issue with the memory leak was on our end https://github.com/mekanism/Mekanism/commit/a83686c43a307efe4b87ad652731c4750390393b I wouldn't be surprised if them using a new lazy optional each time still causes a memory leak, but it should be a lot less severe now (especially when interacting with mods that do properly cache their lazy optionals).
