### ISSUE TITLE
NBT support for (machine)recipe inputs

### ISSUE THREAD

**Issue by winnetrie83** [mekanism/Mekanism#6153]
#### Issue description:

It seems NBT for recipe inputs is not working/supported.
Example: adding golden_sword to crusher and returning gold_dust.
The golden sword should only be crushed if the damage = 0 aka the durability is at max whenever NBT data for damage is given.

#### Steps to reproduce:
Tried many different (plausible) method to define nbt data, but to no avail.

#### Version (make sure you are on the latest version before reporting):
**Forge:*31.1.74* 
**Mekanism:*Mekanism-1.15.2-9.10.3.416.jar*

**Comment by pupnewfster** [comment]
Format for NBT inputs is now documented [here](https://github.com/mekanism/Mekanism/wiki/Ingredient-JSON-Syntax#item-with-nbt)
