### ISSUE TITLE
Dynamic Tank Fluid Dupe

### ISSUE THREAD

**Issue by MuteTiefling** [mekanism/Mekanism#6154]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Dynamic Tanks seem to be creating infinite amounts of fluid when using a PneumaticCraft Fluid Hopper to extract from them. Posting the issue to both mods as it's unclear to me where the problem is. 

https://github.com/TeamPneumatic/pnc-repressurized/issues/477

#### Steps to reproduce:
1. Create a Dynamic Tank with a fluid in it
2. Place a PneumaticCraft Fluid Hopper to extract from a valve
3. Create infinite fluid

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-31.1.74
**Mekanism:** Mekanism-1.15.2-9.10.1.414
**Other relevant version:** pneumaticcraft-repressurized-1.15.2-1.1.2-14

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

https://gist.github.com/MuteTiefling/35035792f5d37b3dc23c97a931ba7190

**Comment by aidancbrady** [comment]
Sounds like the issue isn’t reproducible in the latest Mekanism builds.
