### ISSUE TITLE
Unable to craft Infused Alloy

### ISSUE THREAD

**Issue by emanuele246gi** [mekanism/Mekanism#6155]
#### Issue description:
When I try to produce the Infused Alloy, nothing happens, even if there is energy inside of the machine.

#### Steps to reproduce:
1. Put the ingot into the infuser
2. Put the redstone too
3. It should go, but nope.

Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.78
**Mekanism:** 1.15.2-9.10.5.418
**Other relevant version:** It's also installed: Additions, Generators and Tools

Also it's a modpack.

**Comment by pupnewfster** [comment]
Does JEI display the recipe? If not it is possible that the modpack creator removed the recipe or some other mod is causing datapack loading to crash so the recipe never loads.

**Comment by emanuele246gi** [comment]
Yes JEI does it, and nope none removed the recipe because I'm the owner of the modpack

**Comment by pupnewfster** [comment]
Not sure what is going on given I am not able to reproduce this:
![image](https://user-images.githubusercontent.com/1203288/81832552-a6466980-950c-11ea-945e-00fcc158c9b8.png)

**Comment by pupnewfster** [comment]
If you could provide images of your setup and the GUI that may lead to helping us track down the issue. For example I think if you have eight speed upgrades installed and no energy upgrades the energy cost may be higher than the infuser can supply.

**Comment by emanuele246gi** [comment]
Ok I will provide the necessary when I will be able to do it :D

**Comment by emanuele246gi** [comment]
![2020-05-15_20 52 24](https://user-images.githubusercontent.com/61762317/82086005-25df5e80-96ee-11ea-8240-713e5d66ac02.png)

There you go, I know that it seems there isn't redstone, but I put it in there and it says it's 10

**Comment by pupnewfster** [comment]
Two things, one are you able to reproduce this yourself with just mekanism installed (given you originally said it is a modpack), and two could you please provide your latest.log I want to look to see if there are any errors being caused by other mods that may be the true issue here.

**Comment by emanuele246gi** [comment]
Ok I'll try it

**Comment by emanuele246gi** [comment]
Well obviously I did some things other than that, so maybe in the latest.log you will find something about Minecolonies, ect...

**Comment by emanuele246gi** [comment]
[latest.log](https://github.com/mekanism/Mekanism/files/4638233/latest.log)
There you go

**Comment by emanuele246gi** [comment]
Well... So where is the problem? :(

**Comment by pupnewfster** [comment]
No idea but I don't believe it has to do with Mekanism due to you saying you couldn't reproduce it with just Mekanism. I would try going through your latest log and look for instances of `Couldn't parse loot table` and `Parsing error loading recipe` removing the mods that have those until it starts working again.

**Comment by emanuele246gi** [comment]
I can't find those instances anywhere, I tried even in old file logs

**Comment by pupnewfster** [comment]
Open the log file you sent me in some sort of text editor or the like and use search (by default ctrl + f if you need a keybind instead of finding a button). Both strings I sen are repeated many times in that log.

**Comment by emanuele246gi** [comment]
Well I searched them with the classic "find" button in the notepad of Windows

**Comment by pupnewfster** [comment]
No idea I used Notepad++, but I just tried using the normal version of Notepad to verify if it could find them and it was also able to find those strings.

**Comment by emanuele246gi** [comment]
Ah crap, I dunno why I can't do it and this problem is making me a little bit upset D: I'm trying every possible answer
