### ISSUE TITLE
invisble jetpack, free runners, scuba tank, and gas mask with optifine

### ISSUE THREAD

**Issue by cpm9** [mekanism/Mekanism#6156]
#### Steps to reproduce:
1. Start game with mekanism, mek gen, mek tools, optifine
2. Put on any of the above listed items
3. Item is invisble on the player model

**Forge:** 1.15.2 - 31.1.74
**Mekanism:** 1.15.2 - 9.10.5.418
**Other relevant version:** optifine 1.15.2 - G1-Pre16

**Comment by pupnewfster** [comment]
Report it to optifine they are probably breaking something. Even once optifine releases that won't help us track it down due to how optifine works and it being closed source.
