### ISSUE TITLE
[1.15.2] Logistical Transporter don't connect to Minecraft Composter

### ISSUE THREAD

**Issue by MatthiasMann** [mekanism/Mekanism#6157]
#### Issue description:
The Mekanism Logistical Transporters (Item Pipes) do not connect to the Minecraft Composter (both the top/input or bottom/output side).
Minecraft hoppers are able to insert/extract on these sides to/from a Minecraft Composter.

#### Steps to reproduce:
1. Place a Basic Logistical Transporter
2. Place a Minecraft Composter on top
3. Place another Basic Logistical Transporter on top of the Composter

#### Version (make sure you are on the latest version before reporting):
forge-1.15.2-31.1.77
Mekanism-1.15.2-9.10.5.418

**Comment by pupnewfster** [comment]
https://github.com/MinecraftForge/MinecraftForge/issues/6691

**Comment by MatthiasMann** [comment]
And I only wanted to make some bone meal :)

**Comment by bloodscon** [comment]
pipe > hoppper >top compost bin bottom > hopper > pipe.  this should work will also stop the annoying habit of stuff popping out of the pipe as i have noticed with this like compost bins, barrel + crucible from ex nilo, as the don't seem to report the storage left like a standard inventory

**Comment by winsrp** [comment]
adding to this, logical transporters don't seem to respect colors from logical sorter
