### ISSUE TITLE
IS there a way to use windmils wthout have 256 block clear

### ISSUE THREAD

**Issue by josh-65** [mekanism/Mekanism#6158]
#### Issue description:
I have an amplified world where there's a big at least 150 block gap for wind but because there's about 30 block at the 200+ level so the windmills says sky's not visible and they don't work.

![2020-05-12_23 11 31](https://user-images.githubusercontent.com/26977075/81750730-f807d900-94a5-11ea-8d18-c076e46f4de4.png)

#### Versions:
**Minecraft:** 1.12.2
**Mekanism:** 9.8.3.390

**Comment by pupnewfster** [comment]
No, wind generators need to be able to see the sky
