### ISSUE TITLE
Rotten Flesh is not accepted by the Crusher

### ISSUE THREAD

**Issue by darki73** [mekanism/Mekanism#6159]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The Wiki states that you should be able to process Rotten Flesh in the crusher to create Bio Fuel, however right now, no matter what i do (chests, hoppers, manual inserts), Crusher does not accept the Rotten Flesh.

#### Steps to reproduce:
1. Install the latest `Release` version for mod
2. Place Crusher
3. Try to insert Rotten Flesh

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2-31.1.77
**Mekanism:** 9.10.5.418
**Other relevant version:** 

Seems like the main "problem" point is here https://github.com/mekanism/Mekanism/blob/301dc9a52966c1a0cab1bda203c45b6be4d2b928/src/datagen/main/java/mekanism/common/recipe/MekanismRecipeProvider.java#L406

As it takes the items which are able to be placed into the `Composter`, Rotten Flesh is not on the list

**Comment by pupnewfster** [comment]
In 1.15 we reworked bio fuel recipes to be based off the composter. This more just has to do with the fact that the wiki is not up to date, though you can always add more recipes yourself via datapacks.
