### ISSUE TITLE
Can't use machinery 

### ISSUE THREAD

**Issue by SilentSkull** [mekanism/Mekanism#6161]
I am not able to use digital miner it gets ready but doesn't show to mine.

#### Issue description:I am not able to use any machinery and can't use jetpacks and I am not even able to put robot.
The mods which I have with it are inside the folder of drive link

https://drive.google.com/folderview?id=1glDILxCZFcErP5CsHIOx7iOQJb0kH3hs
Please help ASAP I want to play with my friends.

I have installed everything of version 1.15.2

**Comment by pupnewfster** [comment]
I am not going to lookup what all the mods you have do, but my best guess is that at least one of the mods you have installed has some sort of world protection setup that makes it so you can't interact with things in the world. It is likely the miner is having a similar issue with some protection mod and you need to make that mod allow fake players to break blocks in the area it is "protecting"

**Comment by SilentSkull** [comment]
> I am not going to lookup what all the mods you have do, but my best guess is that at least one of the mods you have installed has some sort of world protection setup that makes it so you can't interact with things in the world. It is likely the miner is having a similar issue with some protection mod and you need to make that mod allow fake players to break blocks in the area it is "protecting"

Please tell me how can I do it??

**Comment by pupnewfster** [comment]
No idea look through the settings of your mods, my best guess is that it is either "MA essentials" or "Security Craft"

**Comment by SilentSkull** [comment]
> No idea look through the settings of your mods, my best guess is that it is either "MA essentials" or "Security Craft"

I have both in the modpack!!

**Comment by pupnewfster** [comment]
That is why I listed them??? I don't know what either of those two mods do specifically hence why I am guessing that one of them is the one that is doing some form of world protection.

**Comment by SilentSkull** [comment]
> That is why I listed them??? I don't know what either of those two mods do specifically hence why I am guessing that one of them is the one that is doing some form of world protection.

Okay Lemme check through there discord..

**Comment by bl4ckscor3** [comment]
SecurityCraft is not doing any world protection that would prevent players to access a block's interface. It adds blocks that can not be destroyed by anyone but the owner and are set to hardness -1. SecurityCraft would not cause the Digital Miner to be inaccessible.

**Comment by SilentSkull** [comment]
It worked I was doing it in a wrong way!!
😅😅😅
