### ISSUE TITLE
Logistical Sorter Filter - Priority only matters for the first item pull

### ISSUE THREAD

**Issue by sumsar2000** [mekanism/Mekanism#6162]
#### Issue description:
Just as the title says. Say I have a material filter set up to gather everything related to stone, so stairs, slabs, etc., but I want the actual normal stone in a chest on it's own.

To do that, I set up tag filter using forge:stone to sort all whole, uncrafted stones to a separate chest, and put that filter to the top of priorities. It works as intended, but only if the logistical sorter is handling ONE stack at a time. If I insert multiple stacks, or switch it to single item pulling, it starts alternating between the two rules. So if I have normal andesite, half of it will go into the stone-only chest, the other half will get sorted under the material filter.

This has to be a bug right? Or am I just stupid and missing a really obvious way to turn this off? I don't have round robin on, if that means anything.

![setup1](https://user-images.githubusercontent.com/657943/82040294-b09c6b00-96a6-11ea-9915-8fecca635c86.PNG)
![setup2](https://user-images.githubusercontent.com/657943/82040372-cad64900-96a6-11ea-873a-1810a41c633b.PNG)
![setup3](https://user-images.githubusercontent.com/657943/82040475-eccfcb80-96a6-11ea-8e97-d5cfa4c73d7c.PNG)

Example with Slate, which is a forge:stone tagged block. Note that I changed the colour of my second filter from red to green after taking the setup screenshots.
![setup result](https://user-images.githubusercontent.com/657943/82040604-1ee12d80-96a7-11ea-98d8-b01227d16523.PNG)

#### Steps to reproduce:
1. Make any broad filter in a sorter
2. Make a more specific filter that covers an item already covered by the previous filter.
3. Place second filter higher in priority (This step currently makes no differrence other than for the very first item pull).
3. Move a lot of items at the same time.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.87
**Mekanism:**  1.15.2-9.10.5.418
**Other relevant version:** Valhesia 2 2.2.0a (Modpack)

**Comment by aidancbrady** [comment]
I’ll try to take a look at this today. This does sound like a bug.

**Comment by aidancbrady** [comment]
A fix for this will be included in 9.10.6.
