### ISSUE TITLE
1.15.2 Gas registration broken in forge 31.1.95+

### ISSUE THREAD

**Issue by ArMoReDfUrY** [mekanism/Mekanism#6163]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
title.
java.lang.ExceptionInInitializerError: null

#### Steps to reproduce:
1.install forge 31.1.95+
2.launch game with mekanism
3.watch it crash in the registration phase

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.1.95+
**Mekanism:** -1.15.2-9.10.5.418
Mekanism Additions .418
Mekanism Generators .418
Mekanism Tools .418
 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/XAzrUvZR

it isn't set to expire.

**Comment by pupnewfster** [comment]
Please provide your full latest.log file

**Comment by pupnewfster** [comment]
This is two different bugs:
1. https://github.com/MinecraftForge/MinecraftForge/issues/6374 causing the invalid crash report
2. Biomes O' Plenty is not properly creating their music discs and so is crashing now that https://github.com/MinecraftForge/MinecraftForge/commit/765da1aca8db4c530d50db8d0578ebb585a6a3f9 has been merged into forge.

**Comment by pupnewfster** [comment]
https://github.com/Glitchfiend/BiomesOPlenty/issues/1602

**Comment by ArMoReDfUrY** [comment]
ok thanks. i'll roll back til they get a fix implemented.
