### ISSUE TITLE
Digital Miner mines in overworld Nether- and Endore from SilentGems?

### ISSUE THREAD

**Issue by cyberpunkbln** [mekanism/Mekanism#6167]
#### Issue description:
I have Silent Gems installed after generated the first Chunks. So i have maked the DigiMiner and then i'm digged in the nether far, far, faaaar away from the first Nethergate that the old chunks have without SilentGems. But the DigiMiner don't find in new generated Chunks in the Nether Mod:*silentgems*. Then i have set a new Nethergate from Nether to Overworld and came out in frsh generated Chunsk and the DigiMiner found SilentGem-Ores (Mod:*silentgems').

But he found all Ores from SilentGems, Nether,Overworld and Endores.

#### Steps to reproduce:
1. Mine with the DigiMiner in the Overworld
2. Set Filter to Mod-ID: *silentgems*
3. Start Mine (with all on (silk,pull,push) and with full range)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2-forge-31.2.0
**Mekanism:** 1.15.2-9.10.6.419 (all 4 parts)
**Other relevant version:** SilentGems-1.15.2-3.5.3+86

Thx

Edit: I have forgot to say that i have mined with the miner near the Nethergate where i came out;) and where i have tryed to mine in the nether (the digiminer don't have found any silentgems in nether on this position and on the other side(overworld) he found all silentgems (nether, end,overworld). But i don't know if this is important if i have mine near by the nethergate.

Edit: Yes it is very important. When i use the DigiMiner in the near of the Nethergate he mines Nether and Enderores from SilentGate, strange.

**Comment by pupnewfster** [comment]
I am not quite sure what you are trying to report here.
1. Are you sure there are ores nearby in the range that the digital miner has set
2. By nethergate do you mean a nether portal or something else entirely?
3. If the chunks the miner is in are not loaded it won't mine (not sure if this has anything to do with what you are reporting or not as I am not quite sure what you are reporting)

**Comment by cyberpunkbln** [comment]
Hi,

Nether Portal yes sure, sorry.

1. Yes its a fresh overworld chunk (dig in the nether trough many chunks and make a new nether portal, my classic way for late mods;)) with all new ores fom new mods like silent gems that i have later installed. I came out from the Portal in the overworld clean from all monsters and then set the digital miner in front of the nether portal. I use the mod-filter for *silentgems* and the i run with silk,pull and push on. And the digi miner has mined all, really all *silentgems* ores from nether,end and the overworld.

2. yes :)

3. Thats why this is so strange. I go to gamemode creative and set the digital miner a few block far from the nether portal and the digital miner only mines *silentgems*Overworld Blocks.

Sorry i don't where going back and test the digital miner again in the near of nether portal.

In the moment i have discarded all nether ores and end ores from SilentGems and don't use the digital miner in the near of an Nether Portal in the future:).

I think i close this thread and report when it's happened again.

Thanks for your answer, i know it is a really strange issue;). Can it be that the digital miner and the near of an nether portal somewhat changes in the way of chunkloading ?
