### ISSUE TITLE
Turbine:  Electromagnetic coil problem with connecting

### ISSUE THREAD

**Issue by egemasta** [mekanism/Mekanism#6170]
Hello

I have a problem with the turbine and the electromagnetic coil that won't connect. I won't get a sparkle red when I finish building it.
Here are some screenshots
![2020-05-18_18 49 51](https://user-images.githubusercontent.com/61972189/82239840-b9589f80-9939-11ea-9e58-d858f97afa46.png)
![2020-05-18_18 55 18](https://user-images.githubusercontent.com/61972189/82239843-ba89cc80-9939-11ea-8daa-e1b4367a0d09.png)
![2020-05-18_18 55 40](https://user-images.githubusercontent.com/61972189/82239846-ba89cc80-9939-11ea-8820-5b143037da57.png)

I play with the Valhelsia Modpack version 2.0.2a 
Mekanism-1.15.2-9.10.5.418.jar
MekanismAdditions-1.15.2-9.10.5.418.jar
MekanismGenerators-1.15.2-9.10.5.418.jar
MekanismTools-1.15.2-9.10.5.418.jar
Minecraft version: 1.15.2
(modded) forge-31.1.87

**Comment by aidancbrady** [comment]
Coils must all be connected & one must be directly above the rotational complex

**Comment by egemasta** [comment]
The problem is that they do not connect when placing, see https://youtu.be/fZZvsnw1nB0

**Comment by aidancbrady** [comment]
Visual ‘connection’ is purely aesthetic and a feature of CTM, which just yesterday moved to a beta 1.15 release if I’m not mistaken.

**Comment by egemasta** [comment]
I see. Thank you very much for the quick answer. Have a nice day.
