### ISSUE TITLE
[1.12.2] I can't launch the game

### ISSUE THREAD

**Issue by sugarzion** [mekanism/Mekanism#6172]
I can't launch the game when I install Mekanism-1.12.2-9.8.3.390 and its additionals.
Perhaps this isn't caused by Mekanism , but I always fail to launch only when I install Mekanism.
Is this a bug of Mekanism or not? please tell me.
[sorry for bad English. I'm a Japanese student.]
[crash-2020-05-19_10.46.01-client.txt](https://github.com/mekanism/Mekanism/files/4647808/crash-2020-05-19_10.46.01-client.txt)
 {PS}
here is the list of mods
[1.12]UncraftingTable-1.8-beta6
buildcraft-all-7.99.24.6
additionalpipes-6.0.0.8
AppleSkin-mc1.12-1.0.9
backpack-3.0.2-1.12.2
Bookshelf-1.12.2-2.3.585
GalacticraftCore-1.12.2-4.0.2.280
Galacticraft-Planets-1.12.2-4.0.2.280
industrialcraft-2-2.8.199-ex112
jei_1.12.2-4.8.5.147
liteloader-1.12.2-SNAPSHOT-release
mod_voxelMap_1.7.1_for_1.12.2
MicdoodleCore-1.12.2-4.0.2.280
OptiFine_1.12.2_HD_U_D1
[1.12][forge2413]mod_CutAllSMP_v2.5.2
[1.12][forge2413]mod_DigAllSMP_v2.3.2
[1.12][forge2413]mod_MineAllSMP_v2.6.5
GVCLib__1.12.2__2.1
HMGDollsFrontLine1.12.2.β.12.1
+Mekanism files

**Comment by aidancbrady** [comment]
1.12 is no longer supported. Likely an interaction issue- I don’t have time to check the crash log, but try removing mods until you find the culprit.
