### ISSUE TITLE
[1.12.2] Copper Dust has no smelting recipes 

### ISSUE THREAD

**Issue by pStann0** [mekanism/Mekanism#6173]
When trying to ore triple copper using the purifying chamber, crusher, enrichment chamber, and smelter the copper did not want to transfer into the furnace. I looked into it more and found that the copper dust produced by this process does not have any smelting recipes. 

![2](https://user-images.githubusercontent.com/65689885/82510838-9d8bff80-9ad9-11ea-8681-aa8f05642f35.png)

![3](https://user-images.githubusercontent.com/65689885/82510855-a5e43a80-9ad9-11ea-8bf1-bcc4168fa7b5.png)

The enriching factory is set to auto output with the output directly touching the smelting factory. Same thing happens if items are to be transferred using logistical transporters.

#### Version:
forge-14.23.5.2847
mekanism 1.12.2 9.8.3.390
mekanism generators 1.12.2 9.8.3.390
mekores 2.0.13

**Comment by pStann0** [comment]
This issue also occurs with tin dust.

**Comment by aidancbrady** [comment]
1.12 is no longer supported, but I assure you both copper and tin dust had smelting recipes in all our releases. Make sure your mod pack or config aren’t blocking the recipe.
