### ISSUE TITLE
Pump - Oil

### ISSUE THREAD

**Issue by Serzh812** [mekanism/Mekanism#6175]
minecraft 1.15.2
the pump does not pump oil - mods PneumaticCraft: Repressurized https://www.curseforge.com/minecraft/mc-mods/pneumaticcraft-repressurized
whose fault is this ?
![1](https://user-images.githubusercontent.com/29928405/82617827-e75c0f00-9bd9-11ea-8b20-a961db6e4ca1.jpg)
![2](https://user-images.githubusercontent.com/29928405/82617830-ed51f000-9bd9-11ea-933d-6edf045767df.png)

s?

**Comment by pupnewfster** [comment]
The fluidic plenisher is for placing fluids the electric pump is for picking them up. Based on your picture I am guessing you are using the wrong machine.
