### ISSUE TITLE
[1.12.2] Some Ore chunks from "How Fortunate" aren't picked up by mekanism automation but some are...?

### ISSUE THREAD

**Issue by Darkmega18** [mekanism/Mekanism#6176]
#### Issue description:
I'm the creator of a modpack called Timeless Technician, and I have the mod "how fortunate" in the modpack which unifies ores into ore chunks on drops and can allow them to get fortune mined if activated. All the ores are ore dicted seemingly properly and are picked up by all other crushing and ore multiplication processing recipes such as actually additions crushers, and enderio sag mills and pulvus.

However a lot of the primary ores like iron and gold ore chunks aren't being picked up, while a lot of secondary sort of ores like uranium, platinum, Aluminum are somehow picked up and allowed in the processing recipes. I think it's all the ores that appear here in the mod's items:
![image](https://user-images.githubusercontent.com/8104689/82659197-a280b880-9c6b-11ea-9121-77a7500d3b6f.png)
vs being here in the mods items:
![image](https://user-images.githubusercontent.com/8104689/82659245-b4faf200-9c6b-11ea-85c8-e78f386e6134.png)
I want to think it's a discrepancy between the base mod's registering of ores to the machines that was done and forgotten, vs mekanismores registering of ores to the machines done differently after mekanism was split into 3 parts.

#### Steps to reproduce:
1. Install my modpack for exact mods, or alternatively, presumably get all parts of mekanism for 1.12.2 and how fortunate and jei etc and some other stuff.

2. Check for recipes being used for ore chunks.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-14.23.5.2847
**Mekanism:** 
Mekanism-1.12.2-9.8.3.390.jar
MekanismGenerators-1.12.2-9.8.3.390.jar
MekanismTools-1.12.2-9.8.3.390.jar

fortunate-1.12.2-2.14.jar

**Comment by thiakil** [comment]
> Install my modpack for exact mods, or alternatively, presumably get all parts of mekanism for 1.12.2 and how fortunate and jei etc and some other stuff.

Word of advice: very few modders are going to do that. You're better off finding the _minimum_ reproduction scenario.

Aside from that, we've dropped 1.12 support as we don't have the time to spare.

You'll need to 

1.  Get a list of the oredict entries that aren't doing what you want
2. See if we have an integration [here](https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/common/integration/OreDictManager.java) or [here](https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/common/integration/MekanismHooks.java)

If we do, the other mod isn't registering them early enough.
If we don't you'll need to add them using CraftTweaker

**Comment by Darkmega18** [comment]
Had a feeling that was gonna happen. Guess thats one way to get me to try to learn crafttweaker,...

 but I'd hazard a guess that will probably keep happening later in your other versions of that mod updates. cause I don't see any hits for oreIron and so-on in either of those. so you might want to consider looking into it regardless for variants of these integral ores if it hadn't been done at some point already.

**Comment by thiakil** [comment]
Some base materials are done with a loop on the Resource enum. Oredict no longer exists either. 

I'd still put my money on them not being registered to the oredict as early as they should be, that's the number one issue with this kinda thing

**Comment by Darkmega18** [comment]
I'll bring it up with how fortunate then and let them know the concern and find out. since they did advertise it should work with everything. and it does, bar mekanism, which was why I decided to come here first. if it had problems with more other things, I would've pointed the finger the other way first.
