### ISSUE TITLE
Universal Cables with Charge Tech Reborn Machines

### ISSUE THREAD

**Issue by CrankySupertoon** [mekanism/Mekanism#6177]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

The cables won’t charge Tech Reborn Machines. These accept both IC2 EU and RF and I believe the cables might be getting confused
#### Steps to reproduce:
1. Plop down a TR machine
2. Cable it up
3. Try to charge it

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2 2847
**Mekanism:** 390

**Comment by Yoosk** [comment]
Mekanism is no longer updated or developed for minecraft 1.12.2. 
Maybe `TATW` mod could help.

**Comment by pupnewfster** [comment]
No idea but given tech reborn in 1.15 is for fabric not forge and we are not developing 1.12 anymore even if there was a bug there is not much we can do about it now.
