### ISSUE TITLE
[1.15.2] Placing block doesn't produce sound

### ISSUE THREAD

**Issue by ocram9** [mekanism/Mekanism#6179]
#### Issue description:
When placing a block on mekanism specific blocks (like the dynamic tank or the induction casing) it doesn't produce a sound of the block being placed. When shift placing a block it does create a sound.

#### Steps to reproduce:
1. Try to create a dynamic tank or induction matrix (or just use a single block, the structure doesn't need to be complete).
2. Place a block directly on it without holding shift.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.0
**Mekanism:** 9.10.6.419
**Other relevant version:** MekanismGenerators 9.10.6.419

**Comment by pupnewfster** [comment]
I will look into this issue some given it is odd, though I am unsure if there is anything I will be able to do about it as it seems similar to this vanilla issue: https://bugs.mojang.com/browse/MC-163921

**Comment by ocram9** [comment]
I thought this issue sounded familiar.. I just tested it some more and I also can't place any blocks while using my offhand. Which seems to be related to that same bug: https://bugs.mojang.com/browse/MC-166435

Same thing for water: https://bugs.mojang.com/browse/MC-165510

**Comment by ocram9** [comment]
If it turns out this issue is a vanilla issue it should be fixed in 1.16. That redstone bug has been fixed in 1.16 pre-release 3.

**Comment by pupnewfster** [comment]
Ya, we will see. At the very least there probably is a way via vanilla to now have it properly play the sound regardless, so putting this on hold until the port to 1.16.

**Comment by pupnewfster** [comment]
This is fixed in the 1.16 branch
