### ISSUE TITLE
[1.15.2] Configuration card does not update pipes

### ISSUE THREAD

**Issue by ocram9** [mekanism/Mekanism#6180]
#### Issue description:
When copying machine settings with the configuration card, the settings do get updated but the attached pipes aren't (see video).

#### Steps to reproduce:
1. Place a few mekanism factories next to each other
2. Change some settings in one factory (for example input at the top)
3. Place pipes above all the factories
4. Copy the settings from the first factory to the others with the configuration card
5. The pipes don't update to (in this example) input.

#### Version:
**Forge:** 31.2.4
**Mekanism:** 9.10.6.419

#### Video:
https://youtu.be/u1oTa29EuzI

**Comment by aidancbrady** [comment]
Fixed in b4cddcd
