### ISSUE TITLE
1.12.2 Digital miner does not accept sugar cane in "ItemStack" filter

### ISSUE THREAD

**Issue by Paandizz** [mekanism/Mekanism#6187]
#### Issue description:
While playing on a whitelisted server on 1.12.2, i tried using the digital miner to get sugar cane. Noticed that the miners "itemstack" filter wont accept Sugar cane, while it does accept ores and other blocks.

#### Steps to reproduce:
1. Set up digital miner
2. "ItemStack" filter
3. attempt putting in sugar cane

#### Version (make sure you are on the latest version before reporting):
**Forge:**  14.23.5.2854
**Mekanism:** 9.8.3.390
**Other relevant version:**  1.12.2  (minecraft forge)

https://gyazo.com/6abc49e23dd27892cc8e87fa4707a85b [gif showing the problem]

**Comment by pupnewfster** [comment]
I guess there was a little bit of miscommunication on discord given I had not realized you are in 1.12, which we are no longer actively developing. I did just test this in 1.15 and I am able to successfully put sugar cane in an itemstack filter.
