### ISSUE TITLE
Boiler boil rate ridiculously low in 1.15.2

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [mekanism/Mekanism#6189]
#### Issue description:
I created a 4x4x5 boiler, 5 fuelwood heaters all with 64 coals and connected them via thermodynamic conduits. However the boil rate is just 1-2mB/t.

That is odd because in 1.12.2, a single heater powering a 3x3x4 boiler generates 40mB/t of steam

#### Steps to reproduce:
1. Build a boiler multiblock
2. Use fuelwood heaters to heat it

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.0
**Mekanism:** 9.10.6.419

**Comment by Pythonic-Rainbow** [comment]
The boil rate is **STILL** the same

**Comment by Pythonic-Rainbow** [comment]
![2020-06-10_00 34 25](https://user-images.githubusercontent.com/25037295/84175180-31863100-aab2-11ea-8110-2e958643de77.png)
![2020-06-10_00 34 27](https://user-images.githubusercontent.com/25037295/84175245-44990100-aab2-11ea-8230-a34cbfd324ac.png)

**Comment by Pythonic-Rainbow** [comment]
@aidancbrady Sorry for tagging but this hasn't been resolved yet.

**Comment by Pythonic-Rainbow** [comment]
@pupnewfster Would you mind follow up this issue please?

**Comment by pupnewfster** [comment]
I don't know enough about the boiler system to really comment.

**Comment by Pythonic-Rainbow** [comment]
In that case, can you reopen the issue please? The boil rate is clearly not fixed yet as shown in the attached photos.

**Comment by NineStars9** [comment]
Still having this issue in 1.16.3, albeit not as bad, but it doesn't scale with fuelwoods.

**Comment by Pythonic-Rainbow** [comment]
> Still having this issue in 1.16.3, albeit not as bad, but it doesn't scale with fuelwoods.

They said they fixed it in Mekanism v10 aka for 1.16 but seems like it hasn't. Big rip for such a severe bug.

**Comment by Pythonic-Rainbow** [comment]
Ok, I managed to solve it months later, its **MY** fault. I was using resistive heaters without knowing that you can change the power supplied. If you are using resistive heaters as well, please enter a higher RF/t inside the heater.
