### ISSUE TITLE
Ultimate Factories for 1.12.2 version

### ISSUE THREAD

**Issue by SpeedCuber1** [mekanism/Mekanism#6195]
**Describe the the feature you'd like**
It would be cool if you added the ultimate factories that are in 1.15.2 to the 1.12.2 version.

**Comment by Yoosk** [comment]
Not gonna happen. Mekanism is no longer developed for 1.12.2.

**Comment by pupnewfster** [comment]
Not going to spend the hundreds of hours backporting features to 1.12.2. It is MIT licensed so feel free to backport it if you wish to spend the time.
