### ISSUE TITLE
Turbine power output 1.12

### ISSUE THREAD

**Issue by BasiliskL** [mekanism/Mekanism#6202]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I made a large steam turbine that said it should be producing 219 million RF but the output won't output more than 155 million RF, the internal power buffer is filled but it won't output any more energy, I've tried putting more energy output but the whole multiblock seems to be limited. I tried with both unlimited flux network flux plug and thermal dynamics cryostabilized fluxduct thinking it was just the transfer method but neither will increase it to the amount it should be

#### Steps to reproduce:
1. build turbine
2. provide enough steam
3. provide energy output

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Closing this as we are no longer developing for 1.12, the best place to help you trouble shoot this would probably be our [discord server](https://discord.gg/nmSjMGc). The main question I have for you is what is the max energy buffer in the turbine (if it is less than 219 MRF it won't be able to actually produce 219 MRF/t as it will never be able to have space to do so). If that is not the issue, have you tried seeing if it will output to universal cables, I don't fully remember how the turbine worked back in 1.12 and it may be possible it has its own limit that it allows force extraction from (if it even does), compared to how much it is willing to eject by itself.
