### ISSUE TITLE
plastic oredict?

### ISSUE THREAD

**Issue by jarjarpfeil** [mekanism/Mekanism#6203]
I noticed that HDPE has little purpose in the mod other than for solar neutron activators and decorative blocks. Since it is technically plastic, could you make it oredict with other mod's plastic so that it isn't just a useless byproduct o ethylene production? Maybe at least add more uses in the mod?

**Comment by pupnewfster** [comment]
If you want to add it to the plastic oredict you can do so with something like CraftTweaker. We will not be doing so ourselves as the only currently developed version of Mekanism is for a version of MC where the oredict does not exist, and currently we don't really have any plans to add it to tags. I am however for V10, planning on making the recipes for a couple new blocks/machines make use of HDPE.
