### ISSUE TITLE
Quantum Entangloporter dont work

### ISSUE THREAD

**Issue by HireSLH** [mekanism/Mekanism#6204]
#### Issue description:
I had a Quantum Entangloporter linked to 2 chest with Ultimate Logistical Transporter on my nether farm and another Quantum Entangloporter on my central storage system.
I wanna place it hidden under the chests so I delete it and place it on the new spot, i link to the same network but now the Ultimate Logistical Transporter doesn move any item to the Quantum Entangloporter, only transport between chest when i change the configurations push/pull
I litteraly try everything, delete and replace the Quantum Entangloporter on my storage, delete and replace the network, restart my game, restart my server. Try diferent configurations off the Transporter...Help me please i dont know what i should do

#### Version:
**Forge: 31.2.0**
**Mekanism:Mekanism-1.15.2-9.10.7.420**

**Comment by pupnewfster** [comment]
Are the chunks for both entangloporters loaded? You can try installing anchor upgrades into both entangloporters to make sure.

**Comment by HireSLH** [comment]
Both have anchor
