### ISSUE TITLE
Moving an Energy Cube to a Universal Cable causes crash on server and client. 

### ISSUE THREAD

**Issue by aetherpirate** [mekanism/Mekanism#6205]
Crash when moving an Energy Cube to a universal cable network. See pic. Pressing the button in this test will cause the crash. 

![crash](https://user-images.githubusercontent.com/11506409/83968938-8cddd680-a89a-11ea-95f2-c8fbfa9994ce.png)

Forge 1.15.2 (forge-1.15.2-31.2.5.jar)
Mekanism-1.15.2-9.10.7.420.jar

[crash-2020-06-07_03.26.27-server.txt](https://github.com/mekanism/Mekanism/files/4742057/crash-2020-06-07_03.26.27-server.txt)

**Comment by pupnewfster** [comment]
I am going to go ahead and say this is on Quark as Tile Entities are not usually movable with pistons in vanilla (Quark changes this) and moving them usually causes all sorts of problems. I would recommend setting `"Pistons Move Tile Entities"` to false in `quark-common` so you don't accidentally move tiles from various mods and break any assumptions they may be making based on vanilla.
