### ISSUE TITLE
Option to increase/set view distance of wind generator

### ISSUE THREAD

**Issue by madhatr** [mekanism/Mekanism#6206]
**Describe the the feature you'd like**
The wind generator disappears to quickly and I would like to increase it's view distance.  

I have searched the issues and wiki and did not find the info.

PS thanks for the great mod.

**Comment by pupnewfster** [comment]
Assuming you are talking about the wind generator disappearing when you are a decent distance away from it that is a vanilla function pertaining to how Tile Entity Renderers work. I don't believe there is anything we can do on our end to increase this range.

**Comment by madhatr** [comment]
Okay thanks,  missed that this was Mekanism Generators and not Mekanism itself.

**Comment by pupnewfster** [comment]
That isn't why I labeled it as not mekanism. I labeled it as not mekanism as it is vanilla.

**Comment by madhatr** [comment]
Oh ok.  Well i used your wording, because I would have had no idea what to search for exactly.  It appears [this](https://www.curseforge.com/minecraft/mc-mods/te-render-distance-options) mod does it(increase tile entity render distance or reduce it). I can test it out and report back if you'd like the info.
