### ISSUE TITLE
1.15.2 Digital Miner Can't Detect & Mined Mekanism Ore (osmium, copper, tin)

### ISSUE THREAD

**Issue by Chentrifuge** [mekanism/Mekanism#6207]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Place the Digital Miner on the ground. Powered it by ultimate energy cube.
2. Use item filter and select Osmium Ore, Copper Ore, and Tin Ore. Radi: 32, 
    Min:0, Max: 60, I: off, Eject: off, Pull: off, Silk: off.
3. Hit Start button, the display shows "To mine: 0".

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.0
**Mekanism:** Mekanism-1.15.2-9.10.7.420
**Other relevant version:** Mods list:
                                            furniture-7.0.0-pre16-1.15.1
                                            jei-1.15.2-6.0.0.4
                                            MekanismAdditions-1.15.2-9.10.7.420
                                            MekanismGenerators-1.15.2-9.10.7.420
                                            MekanismTools-1.15.2-9.10.7.420
                                            preview_OptiFine_1.15.2_HD_U_G1_pre18
                                            Xaeros_Minimap_20.12.2_Forge_1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant) N/A

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Tahakk** [comment]
Looks that it works just fine.

![2020-06-08_13 08 59](https://user-images.githubusercontent.com/25863620/84023988-5d59c780-a989-11ea-80ee-9e75f288fa76.png)
![2020-06-08_13 09 12](https://user-images.githubusercontent.com/25863620/84023986-5c289a80-a989-11ea-80c5-d45d4cdddd22.png)
![2020-06-08_13 09 07](https://user-images.githubusercontent.com/25863620/84023992-5e8af480-a989-11ea-89af-e0aaf727d654.png)

**Comment by pupnewfster** [comment]
@Chentrifuge did you add Mekanism to your existing world? As by default ores will not spawn in existing chunks (though you can force them to via retrogen).

**Comment by Chentrifuge** [comment]
@pupnewfster No I didn't. I created that world with Mekanism mod and SimpleOres mod; I removed SimpleOres before I starting to use the Digital Miner.
I will try to add retrogen mod to see if it helps.
