### ISSUE TITLE
Gas mask : upgrade feature Night Vision 

### ISSUE THREAD

**Issue by moulecake** [mekanism/Mekanism#6208]
**Describe the the feature you'd like**
_A clear and concise description of what you want._
Scuba and gas mask is very useful feature, but swim without night vision is juste awful and I think nobody use him and use other mod .
So i purpose to add Night Vision upgrade on Gas Mask for use only mekanism stuff :p.

**Describe alternatives you've considered**
_A clear and concise description of any alternative solutions or features you've considered._
I suggest a new recipe like jet pack to armored jet pack but for Gas Mask, like Gas Mask to Night Vision Gas Mask. Gas Mask don't need energy yet (fluid or electricity). So I suggest use electricity.

For recipe it possible to search something like "night vision goggle"
![recipe](https://user-images.githubusercontent.com/65726916/83982587-cdb70900-a8f5-11ea-831e-6b21a92c313a.PNG)
When energy is empty, just lost night vision.
They are not key for "head mode switch" so :
- When Night vision upgrade is done, night vision mode is always activate when equipped (and consume energy only when equip)
- or Add key "head mode switch" for on/off night vision
- use key "feet mode switch" but is very strange :/

**Additional context**
_Add any other context or screenshots about the feature request here._

**Comment by aidancbrady** [comment]
I think you’ll like Mekanism v10.
