### ISSUE TITLE
Server stuck in loading world step

### ISSUE THREAD

**Issue by bloodyraoul** [mekanism/Mekanism#6209]
#### Issue description:
one week ago, my server have started to not work well anymore, being stuck during the loading world step. no error log, just stuck after the preparing world at 100%. 
After investigating a lot, i have found that removing the region folder, then start, then stop, the put again the old region folder works well....but not very good solution if i have to do that every day....
yesterday, one log attract my eyes : **[Mekanism ChunkManager/]: Loading 398 chunks for dimension minecraft:overworld** 
.... why so many chunks ?! We are only 2 players on the server doing mekanism stuff
then I found this closed bug : https://github.com/mekanism/Mekanism/issues/5978 .... 
so I have removed the mekanism_force_chunks.dat file. and now all is really working well again. So maybe this is the same bug ? maybe when you move a digital miner with an anchor upgrade the old loaded chunks are not removed from the file ?

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.2.9
**Mekanism: Mekanism-1.15.2-9.10.7.420.jar

**Comment by pupnewfster** [comment]
Seems that this is the same thing as https://github.com/mekanism/Mekanism/issues/6174#issuecomment-643432951 so closing this and going to continue to track it there.
