### ISSUE TITLE
Crash when starting the game

### ISSUE THREAD

**Issue by kellixon** [mekanism/Mekanism#6210]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 08.06.20 17:41
Description: Initializing game

java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank
	at java.util.Objects.requireNonNull(Objects.java:290) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:92) ~[?:?] {re:classloading}
	at mekanism.common.registration.DoubleWrappedRegistryObject.getPrimary(DoubleWrappedRegistryObject.java:23) ~[?:?] {re:classloading}
	at mekanism.common.registration.impl.BlockRegistryObject.getBlock(BlockRegistryObject.java:19) ~[?:?] {re:classloading}
	at mekanism.client.ClientRegistrationUtil.registerBlockColorHandler(ClientRegistrationUtil.java:112) ~[?:?] {re:classloading}
	at mekanism.client.ClientRegistration.registerItemColorHandlers(ClientRegistration.java:352) ~[?:?] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_948_ClientRegistration_registerItemColorHandlers_Item.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.2.0-service.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168) ~[?:31.2] {re:classloading}
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader$$Lambda$8576/1561524882.accept(Unknown Source) ~[?:?] {}
	at java.util.HashMap.forEach(HashMap.java:1280) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[?:?] {re:classloading}
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260) ~[?:?] {re:classloading}
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:212) ~[?:?] {re:classloading}
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:84) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,xf:fml:randompatches:RandomPatches Minecraft Transformer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.15.2-31.2.9.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/822619898.call(Unknown Source) [forge-1.15.2-31.2.9.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {re:classloading}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at java.util.Objects.requireNonNull(Objects.java:290)
	at net.minecraftforge.fml.RegistryObject.get(RegistryObject.java:92)
	at mekanism.common.registration.DoubleWrappedRegistryObject.getPrimary(DoubleWrappedRegistryObject.java:23)
	at mekanism.common.registration.impl.BlockRegistryObject.getBlock(BlockRegistryObject.java:19)
	at mekanism.client.ClientRegistrationUtil.registerBlockColorHandler(ClientRegistrationUtil.java:112)
	at mekanism.client.ClientRegistration.registerItemColorHandlers(ClientRegistration.java:352)
	at net.minecraftforge.eventbus.ASMEventHandler_948_ClientRegistration_registerItemColorHandlers_Item.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:80)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:168)
	at net.minecraftforge.fml.ModLoader.lambda$postEvent$31(ModLoader.java:260)
	at net.minecraftforge.fml.ModLoader$$Lambda$8576/1561524882.accept(Unknown Source)
	at java.util.HashMap.forEach(HashMap.java:1280)
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218)
	at net.minecraftforge.fml.ModLoader.postEvent(ModLoader.java:260)
	at net.minecraftforge.client.ForgeHooksClient.onItemColorsInit(ForgeHooksClient.java:212)
	at net.minecraft.client.renderer.color.ItemColors.func_186729_a(ItemColors.java:84)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:420)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:166)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51)
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/822619898.call(Unknown Source)
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

-- System Details --
Details:
	Minecraft Version: 1.15.2
	Minecraft Version ID: 1.15.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3181679464 bytes (3034 MB) / 4823449600 bytes (4600 MB) up to 11453595648 bytes (10923 MB)
	CPUs: 12
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12G
	ModLauncher: 5.1.0+69+master.79f13f7
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-2.2.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.1.1-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.15.2-31.2.9.jar runtimedistcleaner PLUGINSERVICE 
		/OptiFine%20HD%20U%20G1%20pre23.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.15.2-31.2.9.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap%201.0.3.jar mixinbootstrap TRANSFORMATIONSERVICE 
		/MixinBootstrap%201.0.3.jar mixin PLUGINSERVICE 
		/MixinBootstrap%201.0.3.jar mixinbootstrap PLUGINSERVICE 
	FML: 31.2
	Forge: net.minecraftforge:31.2.9
	FML Language Providers: 
		javafml@31.2
		minecraft@1
		kotlinforforge@1.2.2
		kotori_scala@2.13.2-build-2
	Mod List: 
		CubePlus 1.2.1.jar Cube++ {cubeplus@1.2.1 CREATE_REGISTRIES}
		AdditionalEnchantedMiner 15.3.1.jar QuarryPlus {quarryplus@15.3.1 CREATE_REGISTRIES}
		RoughMobsRevamped 4.1.2.jar Rough Mobs Revamped {roughmobsrevamped@version CREATE_REGISTRIES}
		NetherPortalFix 6.0.2.jar NetherPortalFix {netherportalfix@6.0.2 CREATE_REGISTRIES}
		PreGenForge 0.1.0.jar PreGenForge {pregenforge@0.1.0 CREATE_REGISTRIES}
		CompactStorage 4.0.3.jar Compact Storage {compact-storage@4.0.0 CREATE_REGISTRIES}
		Prefab 1.5.0.9.jar Prefab {prefab@1.5.0.9 CREATE_REGISTRIES}
		FutureMC 1.0.1.jar Future MC {futuremc@1.15.2-1.0.1 CREATE_REGISTRIES}
		EmbellishCraftBOP2.0.0.jar EmbellishCraft BoP Addon {embellishcraft-bop@1.15.2-2.0.0 CREATE_REGISTRIES}
		ReloadAudioDriver 3.0.1.jar Reload Audio Driver {rad@3.0.1 CREATE_REGISTRIES}
		Borderless 1.0.2.jar Borderless Window {borderless@1.15.2-1.0.2 CREATE_REGISTRIES}
		McwWindows 1.0.1.jar Macaw's Windows {mcwwindows@1.0.1 CREATE_REGISTRIES}
		SilentMechanisms 0.7.2-52.jar Silent's Mechanisms {silents_mechanisms@0.7.2+52 CREATE_REGISTRIES}
		RSGauges 1.2.1.jar Gauges and Switches {rsgauges@1.2.1 CREATE_REGISTRIES}
		Neat 1.6-22.jar Neat {neat@1.6-22 CREATE_REGISTRIES}
		TerraForged 0.0.13.jar TerraForged {terraforged@0.0.13 CREATE_REGISTRIES}
		XaerosWorldMap 1.6.2.jar Xaero's World Map {xaeroworldmap@1.6.2 CREATE_REGISTRIES}
		EnhancedVisuals 1.3.15.jar EnhancedVisuals {enhancedvisuals@1.3.0 CREATE_REGISTRIES}
		Controlling 6.1.4.jar Controlling {controlling@6.1.4 CREATE_REGISTRIES}
		Powah 1.1.14.jar Powah {powah@1.1.14 CREATE_REGISTRIES}
		RangedPumps 0.7.1.jar Ranged Pumps {rangedpumps@0.7.1 CREATE_REGISTRIES}
		UTeamCore 2.11.0.156.jar U Team Core {uteamcore@2.11.0.156 CREATE_REGISTRIES}
		RandomPatches 1.21.1.3.jar RandomPatches {randompatches@1.15.2-1.21.1.3 CREATE_REGISTRIES}
		LowTechCrafting 0.2.2.jar Low Tech Crafting {lowtechcrafting@0.2.2 CREATE_REGISTRIES}
		GravestoneLite 1.0.2.jar GraveStone Lite {gravestone_lite@1.15.2-1.0.2 CREATE_REGISTRIES}
		StorageTech R7.1.jar Storage Tech {storagetech@R7.1 CREATE_REGISTRIES}
		AdvancedTools 1.0.2.jar Advanced Tools {advancedtools@1.15.2-1.0.2 CREATE_REGISTRIES}
		MekanismGenerators 9.10.7.420.jar Mekanism: Generators {mekanismgenerators@9.10.7 CREATE_REGISTRIES}
		TMechworks 2.1.1.jar Tinkers' Mechworks {tmechworks@2.1.1 CREATE_REGISTRIES}
		JEIResources 0.10.1.77.jar Just Enough Resources {jeresources@0.10.1.77 CREATE_REGISTRIES}
		MysticalLib 2.0.0.jar Mystical Lib {mysticallib@1.15.2-2.0.0 CREATE_REGISTRIES}
		RefinedStorage 1.8.4.jar Refined Storage {refinedstorage@1.8.4 CREATE_REGISTRIES}
		IndustrialReborn 0.4.0.jar Industrial Reborn {indreb@1.15.2-0.4.0 CREATE_REGISTRIES}
		PrettyPipes 1.5.4.jar Pretty Pipes {prettypipes@1.5.4 CREATE_REGISTRIES}
		ExtendedFurnace 2.2.jar Extended Furnace {extendedfurnace@2.2 CREATE_REGISTRIES}
		Corpse 1.0.7.jar Corpse {corpse@1.15.2-1.0.7 CREATE_REGISTRIES}
		McwBridges 1.0.4.jar Macaw's Bridges {mcwbridges@1.0.4 CREATE_REGISTRIES}
		IndustrialForegoing 2.3.2.jar Industrial Foregoing {industrialforegoing@2.3.2 CREATE_REGISTRIES}
		AngerManagement 1.0.0.jar Anger Management Mod {angermanagement@1.15.2-1.0.0 CREATE_REGISTRIES}
		TorchMaster 2.1.1-rc0.jar Torchmaster {torchmaster@2.1.1-rc0 CREATE_REGISTRIES}
		Entangled 1.2.5.jar Entangled {entangled@1.2.5 CREATE_REGISTRIES}
		EmbellishCraft 2.2.0.0.jar EmbellishCraft {embellishcraft@1.15.2-2.2.0.0 CREATE_REGISTRIES}
		Geolosys 4.0.21.jar Geolosys {geolosys@4.0.21 CREATE_REGISTRIES}
		BiomesOPlenty 10.0.0.365.jar Biomes O' Plenty {biomesoplenty@1.15.2-10.0.0.365 CREATE_REGISTRIES}
		ValhelsiaStructures 15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a CREATE_REGISTRIES}
		RailWand 0.1.2.jar RailWand {railwand@1.15.2-0.1.2 CREATE_REGISTRIES}
		Lollipop 1.0.15.jar Lollipop {lollipop@1.0.15 CREATE_REGISTRIES}
		IronFurnaces 1.9.0.jar Iron Furnaces {ironfurnaces@1.9.0 CREATE_REGISTRIES}
		SilentGear 1.7.2-96.jar Silent Gear {silentgear@1.7.2+96 CREATE_REGISTRIES}
		SimplyLight 0.9.0.jar Simply Light {simplylight@1.15.2-0.9.0 CREATE_REGISTRIES}
		SimpleFarming 1.2.9.jar Simple Farming {simplefarming@1.15.2-1.2.9 CREATE_REGISTRIES}
		SimplyBackpacks 1.4.6.jar Simply Backpacks {simplybackpacks@1.15.2-1.4.6 CREATE_REGISTRIES}
		Portality 2.1.2.jar Portality {portality@2.1.2 CREATE_REGISTRIES}
		Curios 2.0.2.4.jar Curios API {curios@FORGE-1.15.2-2.0.2.4 CREATE_REGISTRIES}
		Tetra 2.7.2.jar Tetra {tetra@1.15.2-2.7.2 CREATE_REGISTRIES}
		Botania r1.15-384.jar Botania {botania@r1.15-384 CREATE_REGISTRIES}
		Patchouli 1.2-33.jar Patchouli {patchouli@1.15.2-1.2-33 CREATE_REGISTRIES}
		LevelHearts 2.2.0.jar LevelHearts {levelhearts@2.2.0 CREATE_REGISTRIES}
		ExtLights 2.0.jar Extended Lights {extlights@2.0 CREATE_REGISTRIES}
		ClothConfig 2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 CREATE_REGISTRIES}
		OreExcavation 1.7.151.jar Ore Excavation {oreexcavation@NONE CREATE_REGISTRIES}
		TankNull 1.8a.jar Tank Null {tanknull@1.8a CREATE_REGISTRIES}
		EndReborn 0.5.4.jar End: Reborn {endreborn@0.5.4 CREATE_REGISTRIES}
		LottaTerracotta 1.3.0.jar Lotta Terracotta {lottaterracotta@1.15.2-1.3.0 CREATE_REGISTRIES}
		MaliLib 0.10.0-dev.20-b1.jar MaLiLib {malilib@0.10.0-dev.20+beta.1 CREATE_REGISTRIES}
		FlexibleMarker 4.2.jar FlexibleMarker {flexiblemarker@4.2 CREATE_REGISTRIES}
		WirelessRedstone 0.1.0.jar Wireless Redstone {wirelessredstone@0.1.0 CREATE_REGISTRIES}
		ExpandedStorage 1.1.8.jar Expanded Storage {expandedstorage@1.1.8+1.15.2 CREATE_REGISTRIES}
		WorldEdit 7.1.0.jar WorldEdit {worldedit@7.1.0;48cc31c CREATE_REGISTRIES}
		NoRecipeBook 1.5.4.jar No Recipe Book {norecipebook@1.5.4 CREATE_REGISTRIES}
		NaturesAura 28.2.jar Nature's Aura {naturesaura@28.2 CREATE_REGISTRIES}
		MoreVanillaArmor 1.2.jar MoreVanillaArmor {morevanillaarmor@1.15.2-1.2 CREATE_REGISTRIES}
		MekanismTools 9.10.7.420.jar Mekanism: Tools {mekanismtools@9.10.7 CREATE_REGISTRIES}
		McwRoofs 1.0.2.jar Macaw's Roofs {mcwroofs@1.0.2 CREATE_REGISTRIES}
		ChunkNoGoByeBye 1.2.0.jar ChunkNoGoByeBye {chunknogobyebye@1.15.2-1.2.0 CREATE_REGISTRIES}
		McwFurniture 1.0.1.jar Macaw's Furnitures {mcwfurnitures@1.0.1 CREATE_REGISTRIES}
		ItemPhysic 1.4.5.jar ItemPhysic {itemphysic@1.6.0 CREATE_REGISTRIES}
		TomsStorage 1.1.2.jar Tom's Simple Storage Mod {toms_storage@1.1.2 CREATE_REGISTRIES}
		FastLeafDecay v21.jar FastLeafDecay {fastleafdecay@v21 CREATE_REGISTRIES}
		Disenchanting 1.5.0.jar Disenchanting {disenchanting@1.5.0 CREATE_REGISTRIES}
		CodeChickenLib 3.3.0.373.jar CodeChicken Lib {codechickenlib@3.3.0.373 CREATE_REGISTRIES}
		ServerTabInfo 1.2.6.jar Server Tab Info {servertabinfo@1.2.6 CREATE_REGISTRIES}
		QuantumStorage 5.1.1.jar QuantumStorage {quantumstorage@NONE CREATE_REGISTRIES}
		B3M 1.15.2-01.jar Вращение Земли Майнкрафт {b3m@1.15.2-01 CREATE_REGISTRIES}
		Cyclic 0.4.1.jar Cyclic {cyclic@1.15.2-0.4.1 CREATE_REGISTRIES}
		BetterAdvancements 0.1.0.96.jar Better Advancements {betteradvancements@0.1.0.96 CREATE_REGISTRIES}
		DoubleDoors 2.0.jar Double Doors {doubledoors@2.0 CREATE_REGISTRIES}
		Cucumber 3.0.7.jar Cucumber Library {cucumber@3.0.7 CREATE_REGISTRIES}
		PamHC2Trees 1.0.5.jar Pam's HarvestCraft 2 Fruit Trees {pamhc2trees@version CREATE_REGISTRIES}
		CraftingStation 3.1.0.jar Crafting Station {craftingstation@3.1.0 CREATE_REGISTRIES}
		VanillaExcavators 2.1.jar Vanilla Excavators {vanillaexcavators@2.1 CREATE_REGISTRIES}
		JEI 6.0.0.4.jar Just Enough Items {jei@6.0.0.4 CREATE_REGISTRIES}
		JEICalculation 3.6.1.jar Just Enough Calculation {jecalculation@3.6.1 CREATE_REGISTRIES}
		FallingTree 2.1.3-28.jar Falling Tree {falling_tree@2.1.3+28 CREATE_REGISTRIES}
		Mekanism 9.10.7.420.jar Mekanism {mekanism@9.10.7 CREATE_REGISTRIES}
		BetterStorageToo 5.0.0.1.jar BetterStorageToo {betterstorage@1.15.2-5.0.0.1 CREATE_REGISTRIES}
		Reap 1.12.5.jar Reap Mod {reap@1.12.5 CREATE_REGISTRIES}
		InvTweaks 2.0.3.jar Inventory Tweaks Reborn {invtweaks@1.15.2-2.0.3 CREATE_REGISTRIES}
		Waystones 6.0.1.jar Waystones {waystones@6.0.1 CREATE_REGISTRIES}
		MGui 2.1.1.jar mgui {mgui@2.1.1 CREATE_REGISTRIES}
		LightOverlay 4.6.1.jar Light Overlay Forge {lightoverlay-forge@4.6.1 CREATE_REGISTRIES}
		Comforts 2.0.0.2.jar Comforts {comforts@FORGE-1.15.2-2.0.0.2 CREATE_REGISTRIES}
		NaturesCompass 1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 CREATE_REGISTRIES}
		FruitTrees 1.2.7.jar Fruit Trees {fruittrees@1.2.7 CREATE_REGISTRIES}
		Kiwi 2.7.1.jar Kiwi {kiwi@2.7.1 CREATE_REGISTRIES}
		SimpleStorageNetwork 0.3.2.jar Simple Storage Network {storagenetwork@1.15.2-0.3.2 CREATE_REGISTRIES}
		SereneSeasons 3.0.0.72.jar Serene Seasons {sereneseasons@1.15.2-3.0.0.72 ERROR}
		DungeonCrawl 1.6.3.jar Dungeon Crawl {dungeoncrawl@1.6.3 CREATE_REGISTRIES}
		BetterAnimalsPlus 8.2.1.96.jar Better Animals Plus {betteranimalsplus@8.2.1.96 CREATE_REGISTRIES}
		Repurpose 1.2.0.0.jar Repurpose {repurpose@1.2.0.0 CREATE_REGISTRIES}
		MCjtyLib 4.1.1.jar McJtyLib {mcjtylib@1.15-4.1.1-beta CREATE_REGISTRIES}
		RFToolsBase 1.1.1.jar RFToolsBase {rftoolsbase@1.15-1.1.1-beta CREATE_REGISTRIES}
		XNet 2.0.2.jar XNet {xnet@1.15-2.0.2-alpha CREATE_REGISTRIES}
		RFToolsStorage 1.1.4.jar RFToolsStorage {rftoolsstorage@1.15-1.1.4-beta CREATE_REGISTRIES}
		MapperBase 1.1.0.0.jar Mapper Base {mapperbase@1.15.2-1.1.0.0 CREATE_REGISTRIES}
		Traverse 3.2.0.jar Traverse {traverse@1.15.2-3.2.0 CREATE_REGISTRIES}
		EnderStorage 2.5.0.143.jar EnderStorage {enderstorage@2.5.0.143 CREATE_REGISTRIES}
		CraftTweaker 6.0.0.29.jar CraftTweaker {crafttweaker@6.0.0.29 CREATE_REGISTRIES}
		RFToolsPower 2.1.1.jar RFToolsPower {rftoolspower@1.15-2.1.1-beta CREATE_REGISTRIES}
		Dronecraft 0.5.jar Dronecraft {dronecraft@0.0.1 CREATE_REGISTRIES}
		forge-1.15.2-31.2.9-universal.jar Forge {forge@31.2.9 CREATE_REGISTRIES}
		MoreMobs 1.5.jar More Mobs {moremobs@1.0.0 CREATE_REGISTRIES}
		ExpBottling 1.15.2-1.jar EXP Bottling {exp_bottling@1.15.2-1 CREATE_REGISTRIES}
		MysticalAgriculture 3.0.7.jar Mystical Agriculture {mysticalagriculture@3.0.7 CREATE_REGISTRIES}
		IronChest 10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 CREATE_REGISTRIES}
		forge-1.15.2-31.2.9-client.jar Minecraft {minecraft@1.15.2 CREATE_REGISTRIES}
		CofhCore 0.4.0b.jar CoFH Core {cofh_core@0.4.0b CREATE_REGISTRIES}
		RFToolsUtility 2.1.3.jar RFToolsUtility {rftoolsutility@1.15-2.1.3-beta CREATE_REGISTRIES}
		TheOneProbe 2.0.3.jar The One Probe {theoneprobe@1.15-2.0.3 CREATE_REGISTRIES}
		SimplePortals 1.7.0.0.jar Simple Portals {simpleportals@1.15.2-1.7.0.0 CREATE_REGISTRIES}
		Titanium 2.4.1.jar Titanium {titanium@2.4.1 CREATE_REGISTRIES}
		InstaHouses 1.1.1.jar Slashkings InstaHouses {instahouses@1.1 CREATE_REGISTRIES}
		UsefulRailroads 1.3.2.21.jar Useful Railroads {usefulrailroads@1.3.2.21 CREATE_REGISTRIES}
		SilentLib 4.6.1-49.jar Silent Lib {silentlib@4.6.1+49 CREATE_REGISTRIES}
		MoreVanillaLib 1.2.4.jar MoreVanillaLib {morevanillalib@1.2.4 CREATE_REGISTRIES}
		MoreVanillaTools 2.1.jar MoreVanillaTools {morevanillatools@2.1 CREATE_REGISTRIES}
		ClayBucket 1.0.jar Clay Bucket {claybucket@1.0 CREATE_REGISTRIES}
		TravelBag 1.1.2.jar Travel Bag {travel_bag@1.1.2 CREATE_REGISTRIES}
		BluePower 0.4.188.jar Blue Power {bluepower@0.4.188-alpha CREATE_REGISTRIES}
		PamHC2Crops 1.0.5.jar Pam's HarvestCraft 2 Crops {pamhc2crops@version CREATE_REGISTRIES}
		CreativeCore 2.0.5.jar CreativeCore {creativecore@2.0.0 CREATE_REGISTRIES}
		CeramicBucket 1.2.2.jar Ceramic Bucket {ceramicbucket@1.2.2-1.14.4_1.15.X CREATE_REGISTRIES}
		MovingElevators 1.2.16.jar Moving Elevators {movingelevators@1.2.16 CREATE_REGISTRIES}
		IguanaTweaksReborn 2.1.4.jar IguanaTweaks Reborn {iguanatweaksreborn@2.1.4 CREATE_REGISTRIES}
		LargeFluidTank 15.3.0.jar FluidTank {fluidtank@15.3.0 CREATE_REGISTRIES}
		RFToolsBuilder 2.1.3.jar RFToolsBuilder {rftoolsbuilder@1.15-2.1.3-beta CREATE_REGISTRIES}
		DimDungeons 1.06.jar Dimensional Dungeons {dimdungeons@1.15.2-1.06 CREATE_REGISTRIES}
		Mantle 1.5.15.jar Mantle {mantle@1.5.15 CREATE_REGISTRIES}
		XaerosMiniMap 20.12.2.jar Xaero's Minimap {xaerominimap@20.12.2 CREATE_REGISTRIES}
		PamHC2FoodCore 1.0.3.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version CREATE_REGISTRIES}
		LavaMonster 1.0.4.jar Lava Monster {lava_monster@1.0.4 CREATE_REGISTRIES}
		AutoRegLib 1.5-40.jar AutoRegLib {autoreglib@1.5-40 CREATE_REGISTRIES}
		AkashicTome 1.3-13.jar Akashic Tome {akashictome@1.3-13 CREATE_REGISTRIES}
		Quark r2.1-243.jar Quark {quark@r2.1-243 CREATE_REGISTRIES}
		StorageDrawers 7.0.2.jar Storage Drawers {storagedrawers@1.15.2-7.0.1 CREATE_REGISTRIES}
		Backpacked 1.4.1.jar Backpacked {backpacked@1.4.1 CREATE_REGISTRIES}
		VanillaHammers 2.1.jar Vanilla Hammers {vanillahammers@2.1 CREATE_REGISTRIES}
		Structurize 0.10.321.jar Structurize {structurize@0.10.321-ALPHA CREATE_REGISTRIES}
		Smoke 2.0.0.jar Smoke {smoke@2.0.0 CREATE_REGISTRIES}
		PickleTweaks 4.0.3.jar Pickle Tweaks {pickletweaks@4.0.3 CREATE_REGISTRIES}
		Minecolonies 0.11.957.jar Minecolonies {minecolonies@1.15.2-0.11.957 ERROR}
		StatsKeeper 4.2.5.jar Stats Keeper {statskeeper@NONE CREATE_REGISTRIES}
		Transport 2.3.0.jar Transport {transport@1.15.2-2.3.0 CREATE_REGISTRIES}
		AppleSkin 1.0.13.jar AppleSkin {appleskin@1.0.13 CREATE_REGISTRIES}
		EngineersDecor 1.1.0-b1.jar Engineer's Decor {engineersdecor@1.1.0-b1 CREATE_REGISTRIES}
		RefinedRelocation 7.1.1.jar Refined Relocation {refinedrelocation@7.1.1 CREATE_REGISTRIES}
		ItemScroller 0.15.0.jar Item Scroller {itemscroller@0.15.0-dev.20200412.215325 CREATE_REGISTRIES}
		Aquaculture 2.0.14.jar Aquaculture 2 {aquaculture@1.15.2-2.0.14 CREATE_REGISTRIES}
		SilentGems 3.5.4-87.jar Silent's Gems 3 {silentgems@3.5.4+87 CREATE_REGISTRIES}
		XLFood 2.2.2.jar XL Food Mod {xlfoodmod@2.2.2 CREATE_REGISTRIES}
		RefinedStorageAddons 0.6.1.jar Refined Storage Addons {refinedstorageaddons@0.6.1 CREATE_REGISTRIES}
		BetterPvP 20.12.2.jar Better PVP Mod {xaerobetterpvp@20.12.2 CREATE_REGISTRIES}
		SoundFilters 0.13.jar Sound Filters {soundfilters@0.13_for_1.15.2 CREATE_REGISTRIES}
		LootBag 1.5.3.jar Loot Bag Mod {lootbagmod@1.15.1-1.5.3 CREATE_REGISTRIES}
		DrawBridge 1.4.3.18.jar Draw Bridge {drawbridge@1.4.3.18 CREATE_REGISTRIES}
	Launched Version: 1.15.2-forge-31.2.9
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660 SUPER/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 12x AMD Ryzen 5 2600 Six-Core Processor 
	OptiFine Version: OptiFine_1.15.2_HD_U_G1_pre23
	OptiFine Build: 20200607-215525
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1660 SUPER/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by pupnewfster** [comment]
I don't believe this has anything to do with Mekanism and is just an invalid crash report due to https://github.com/MinecraftForge/MinecraftForge/issues/6374 If you provide your latest log I can probably point you in the direction of the real crash.
