### ISSUE TITLE
Magical Bees and Thaumcraft crystals not sorted/ejected by logistical sorter

### ISSUE THREAD

**Issue by siax123** [mekanism/Mekanism#6211]
#### Issue description:
Magical Bees are not sortable by the logistical sorter, can be moved with logistical pipes however. Thaumcraft vis crystals also have this issue. Have tried to sort by Itemstack and Mod ID, neither of which are able to get the bees to eject.

#### Steps to reproduce:
1.Set up a chest, place bees inside
2. Connect a logistical sorter to another chest with any logistical pipe
3. Set filter for bees, they will not eject.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2847
**Mekanism:** 9.8.3.390
**Other relevant version:** Modpack (1.12.0 pack) ver 1.2.0

**Comment by pupnewfster** [comment]
The logistical supporter does not have NBT support in 1.12, it has since gained a fuzzy mode in 1.15
