### ISSUE TITLE
Digital Miner not mining all blocks as intended

### ISSUE THREAD

**Issue by benbenlaw** [mekanism/Mekanism#6213]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I have used craft tweaker to add some ores to the forge:ores tag and tried to use the digital miner to mine these ores but its not working

#### Steps to reproduce:
1. Add block to forge:ores tag using craftweaker
2. Config digital miner to mine tag, then forge:ores 
3. Only ores that had the forge:ores tag by default get mined

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.9
**Mekanism:**9.10.7
**Other relevant version:**  crafttweaker and immersive enginnering installed

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Are you adding it to the block `forge:ores` tag or the item `forge:ores` tag. The miner only looks at the block tags.

**Comment by benbenlaw** [comment]
<tag:forge:ores>.addItems([<item:immersiveengineering:ore_uranium>]);

thats the code im using

**Comment by benbenlaw** [comment]
my bad using wronf block tag thanks for reply
