### ISSUE TITLE
Fully bugged quantum Entangloporter 1.15

### ISSUE THREAD

**Issue by MrReps** [mekanism/Mekanism#6214]
Hello,
My quantum Entgloporter are fully bugged, they can't transfert steam (i tried liquid and gas). I also try to transfert liquid (water) with them but they are caped at 256mb/tick. That  very strange !

**Comment by pupnewfster** [comment]
The auto eject rate is 256 mb/t, it is being upped (and made configurable) to 1,024 mb/t in V10. If you want a higher output rate set your pipe to pull by using a configurator on it. With the lack of information you have provided I am not sure why the entangloporter is not transmitting steam.
