### ISSUE TITLE
[1.15.2] Synching the security access status

### ISSUE THREAD

**Issue by noncom** [mekanism/Mekanism#6216]
#### Issue description:
The security access alterations made on Security Station are not immediately propagated to the UI and do not seem to take effect in, for example, letting the previously trusted player to open up the teleporter UI of a teleporter owned by someone who now denied access. The previously trusted player is still capable on right-clicking the teleporter and seeing its UI. The access status on the lock icon inside the UIs remains unchanged. Client restart is required for the changes to take effect for the affected payer.

This probably affects more than just teleporters, but we've tested only the teleporters for now.

#### Steps to reproduce:
1. In a scenario with two players make player A trust player B via the Security Station.
2. Let player A place a teleporter and set it to a private frequency
3. Verify that the trusted player B is capable of opening the teleporter and seeing the private frequencies.
4. Make player A remove the player B from access roles in his Secutity Station
5. Player B is still capable of opening the teleporter UI
6. Restart player B client
7. Player B is no longer capable to access the teleporter UI, which should have been the case from the very moment of player A changing the permissions.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.5
**Mekanism:** Mekanism-1.15.2-9.10.7.420

**Comment by aidancbrady** [comment]
Now fixed in v10.
