### ISSUE TITLE
Fusion Reactor possibility to meltdown/explode

### ISSUE THREAD

**Issue by Paandizz** [mekanism/Mekanism#6217]
**Describe the the feature you'd like**
I want the fusion reactor multiblock to be able to create an explosion, preferably huge, which leaves a lingering radiation poisoning which deals a lot of damage to the player and other mortal entities in the blast radius. To counter this and prevent a players base from being nuked if they mess up while building their reactor, some kind of Radiation protection block could be added, like "Atomic plating" which is made by first making steel plating  (6 steel ingots that are laid out in lines of 3 in a rectangle  that resembles the recipe for a sign) and infusing that with reinforced alloy to make Reinforced plating, then infusing that with atomic alloy to make Atomic plating. what exactly leads to the reactor exploding, I leave to you people, from my research I could not understand what leads to it happening, Partly because of my lack of understanding and because of my poor english when it comes to those kinds of words.

*Describe alternatives you've considered**
Alternatively, the meltdown could only happen if the player made the reactor explode by pressing a button or shutting some safety setting off, to prevent people who dont want the risk from getting their places blown up.

Another alternative is having the reactor emit a sort of Electro Magnetic Pulse (EMP) that for a little while that depletes all machines of their currently saved up energy, aswell as temporarily shut off generators.

**Additional context**
N/A

**Comment by ASDFGHT0** [comment]
The problem with fusion reactor failures is that as soon as something starts to go wrong, the reaction shuts off instantaneously as the conditions required for it can no longer be maintained. A more realistic failure for them would have the reactor structure violently implode on itself leaving a pile of broken metal due to the outside air crushing it.

**Comment by pupnewfster** [comment]
This is not going to happen. V10 however is adding a fission reactor which will be able to meltdown.

**Comment by Adamherzallh** [comment]
My fission reactor explode what I could do

**Comment by North-West-Wind** [comment]
Wait for a few weeks until the radiation dies out.

**Comment by wheatleycrab123** [comment]
Fusion reactors in real life do not let off toxic radiation even if the exploded
