### ISSUE TITLE
Request [1.15]: Blast Furnace support for Energized Smelter

### ISSUE THREAD

**Issue by davqvist** [mekanism/Mekanism#6219]
**Describe the the feature you'd like**
Vanilla Minecraft has a Blast Furnace now. While the Blast Furnace doesn't have any recipes that the vanilla furnace doesn't have, it technically could (with datapacks). I either would like to see the Energized Smelter per default process all Blast Furnace recipes or add a button to the Energized Smelter GUI that toggles between BF and Furnace mode.

**Describe alternatives you've considered**
A config option that would be off per default and can be turned on to support BF recipes per default would be also an option.

**Additional context**
The reason I am asking this is because I am working on a modpack which has recipes specifically added to the Blast Furnace which the Energized Smelter can't process. If there is already a way to do this, but I am unaware, let me please know.

**Comment by pupnewfster** [comment]
I don't think this is going to happen. The energized smelter though does allow you to add additional recipes to it that are not in the normal smelting map. https://github.com/mekanism/Mekanism/wiki/Recipe-Type-JSON-Syntax#smelting You could always add to this map in addition to the blast furnace map.
