### ISSUE TITLE
[1.15.2] Gas indicators on tanks are inverted in creative

### ISSUE THREAD

**Issue by ocram9** [mekanism/Mekanism#6221]
#### Issue description:
The gas indicator for the creative gas tanks are inverted, they are so long they go off the screen. This only happens in the creative inventory when searched, not in JEI nor in the Mekanism creative tab:

![Screenshot_2](https://user-images.githubusercontent.com/49008532/84929225-d1a21280-b0cf-11ea-8e6c-0c10198b39ed.png)

#### Steps to reproduce:
1. Open the creative inventory in creative mode
2. Search for the creative gas tank (in the mekanism creative tab it works correctly)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.20
**Mekanism:** 9.10.8.421

**Comment by pupnewfster** [comment]
Regenerate your config, I am 90% sure this is due to updating from one of the alpha versions of Mekanism for 1.15 without paying attention to if the changelog mentioned any fixes to the configs needed to be done.

**Comment by ocram9** [comment]
Woops, must have missed that. That fixed it, thanks!
