### ISSUE TITLE
[1.15.2] Compatibility with IE's steel block

### ISSUE THREAD

**Issue by magic0whi** [mekanism/Mekanism#6223]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
https://github.com/BluSunrize/ImmersiveEngineering/issues/3995#issuecomment-645807069

#### Steps to reproduce:
1. Try to build a IE's Arc Furnace is not work with Mekanism's Steel block

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.20
**Mekanism:** 1.15.2-9.10.7.420

**Comment by thiakil** [comment]
Blu isn't saying we can make it build with our block (you'd have to request that from him). He's saying our recipe for a steel block should only accept mek ingots

**Comment by thiakil** [comment]
That said, you can use the Oredictionarificator to swap our steel block for theirs

**Comment by thiakil** [comment]
@pupnewfster this is probably one for you

**Comment by magic0whi** [comment]
> Blu isn't saying we can make it build with our block (you'd have to request that from him). He's saying our recipe for a steel block should only accept mek ingots



> Blu isn't saying we can make it build with our block (you'd have to request that from him). He's saying our recipe for a steel block should only accept mek ingots

I know, I mean the Mek had broken some IE's recipe, and if you want to reproduce(or make it as a verify way), you can try to build an Arc Furnace :p
Sorry for my vague expression.

**Comment by pupnewfster** [comment]
This is not something we are going to change, the whole point of tags is that it shouldn't matter which mods variant you have or not. Additionally for why we won't change it is that if for some reason some mod ***does*** care what version you have you can always just use the oredictionificator in Mekanism (which we have kept even though the oredictionary no longer exists and is just tags now) to switch the block to the correct "type". If memory serves the tag for steel blocks is `forge:storage_blocks/steel`. Alternatively you could use a datapack or a mod like CraftTweaker to change the recipes (on either our end or their end), to get it to craft properly.
