### ISSUE TITLE
1.15.2-9.10.8.421 Cannot set Redstone Mode on Logistical Transporter

### ISSUE THREAD

**Issue by OfficialStamper** [mekanism/Mekanism#6227]
#### Issue description:

This was reported a while ago but seems to have creeped back into the latest version #5928 

Right clicking Logistical Transporter with Configurator tool displays current color.  Action should toggle Redstone Sentivity Mode.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.15.2-31.2.0
**Mekanism:** 1.15.2-9.10.8.421
**Other relevant version:**

**Comment by pupnewfster** [comment]
This isn't actually a bug, and the previous "fix" was aidan forgetting the mechanics of Mekanism/some specifics about the logistical transporters and was actually a bug. The intended method for stopping transporters via redstone is to use a diversion transporter.

**Comment by pwaksman973** [comment]
Well, know that is old but. How would one stop the flow of items with the diversion transporter? It has the redstone sensitive but it doesn't disconnect. What people wanna do when they try to put redstone signal into the pipe is to disconnect it from the other pipes, like the other types of pies does (energy, pressurized). And this is not possible with the diversion pipe.

**Comment by pupnewfster** [comment]
Best guess is you are setting the redstone sensitivity of the wrong side of the diversion transporter (you can configure all six sides individually).

**Comment by pwaksman973** [comment]
Oh, thanks for the response. If you don't mind, can you take a look at this [video example](https://youtu.be/1g4wyo4wU_k) My guess would be that.

1. it is a bug
2. it isn't intended to be used in that way, so maybe, a new feature request?

Forgetting what other people might said, at least for me, I was expecting it to disconnect, not just get a low/higher priority in the system, cause when you have only one path, priority doesn't matter at all.

**Comment by pupnewfster** [comment]
The low/high thing the diversion transporter talks about is what level of redstone is required (so depending on the level you can have it change which sides are connecting to things). In your thing, for example you place two chests three blocks apart from each other. Next place the diversion transporter in the middle as you did, but instead of placing the normal transporters, on one of the sides facing a chest (doesn't really matter which one) use a configurator on it to change the mode. Then place the normal logistical transporters down and then try applying a redstone signal to the transporter.

**Comment by pwaksman973** [comment]
Dammmmmmmm, so it isn't any of my guesses hahhahaha. Thanks. Now I got how it works.
But have to say, its quite unintuitive. I'm sure people are trying the same thing I was doing, probably cause this is how you do it with energy/gas

So, in my example, I was using

   pipe - diversion - pipe
                leaver
                
in this case, before placing the pipes left/right, you need to go to the left side, and set it to the signal, than the same at the right side. The leaver side, doesn't need to get any config.

So in this example if you set "left to high, right to low" it will keep switching between connections when you toggle the signal on/off.

Would be nice to have a visual example in the wiki, or something like that.
Any ways, thanks for taking the time to explain it. I would never try that configuration.

**Comment by Stringer207** [comment]
So Ive noticed the diversion transporter is for logistical pipes only. How do I make pressurized tubes redstone sensitive so that I can turn them on and off?

**Comment by pupnewfster** [comment]
Use a configurator on them (right click not shift right click if I recall). Also these types of questions are better for our discord server than continuing to comment on an old closed issue....
