### ISSUE TITLE
Mekanism systems unstable in ATM5

### ISSUE THREAD

**Issue by Tiberias42** [mekanism/Mekanism#6229]
#### Issue description:
See  https://github.com/AllTheMods/ATM-5/issues/157

#### Steps to reproduce:
1. Build any system requiring stable gas, power or fluid flows
2. Run system
3. Watch wild fluctuations in levels, causing super slow processing

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.20
**Mekanism:** 1.15.2-9.10.8.421
**Other relevant version:** ATM5, started @ 2.0. Current is 2.4

COPY OF ATM5 REPORT:

## Expected Behavior

Mekanism used to have a stable, constant flow to the power, fluids, gases, etc. produced by all the equipment

## Current Behavior

Everything is lagging / surging, like the production is being throttled.  No longer has constant, smooth flow of power, fluids, gases, etc.

## Possible Solution

Same issues was happening in a different mod pack recently (Valhelsia 2), after they had updated some supporting mod that controlled tick rates or something... Maybe that happened here?

## Steps to Reproduce

1. Build any power generation (wind, heat surrounded by lava, gas burning)
2. Build ore tripling systems (smelter, enrichment chamber, crusher, purifier + electrolytic separator)
3. Configure systems for normal use
4. Insert any processable ore into tripling system, watch any piece of equipment power, gas or fluid levels fluctuate
5. ???
6. Frustratingly slow profits

## Detailed Description

I just want the equipment to be stable again, as it is still my primary processing system (until I can figure out IE / IE get fixed)

**Comment by pupnewfster** [comment]
I don't believe this has anything to do with Mekanism and is actually caused by performant's "load balancing of events". https://github.com/mekanism/Mekanism/issues/6178#issuecomment-633575178 I have yet to have anyone actually get around to trying either removing performant, or disabling in their config the load balancing for events and then telling me if it did indeed fix the problem. So if you are willing I would go ahead and disable it in their config and see if it fixes the issue and if so report back.

**Comment by thiakil** [comment]
A proper issue report contains a _minimal_ set of mods (preferably just Mekanism and Forge) and gives an actual reproduction scenario, not just "build a system"

We're not going to go on a wild goose chase to fix your issue.

**Comment by Tiberias42** [comment]
> 
> 
> I don't believe this has anything to do with Mekanism and is actually caused by performant's "load balancing of events". [#6178 (comment)](https://github.com/mekanism/Mekanism/issues/6178#issuecomment-633575178) I have yet to have anyone actually get around to trying either removing performant, or disabling in their config the load balancing for events and then telling me if it did indeed fix the problem. So if you are willing I would go ahead and disable it in their config and see if it fixes the issue and if so report back.

Im not in control of the server (Im playing on the public ATM 5 test server).  I just made this here to show the ATM5 group I was also making your group aware of the issue.  I will talk to a friend who has ATM5 running on a private server & see if they can make the changes you suggested & will report back if that did correct the issue.

**Comment by Tiberias42** [comment]
w

> 
> 
> A proper issue report contains a _minimal_ set of mods (preferably just Mekanism and Forge) and gives an actual reproduction scenario, not just "build a system"
> 
> We're not going to go on a wild goose chase to fix your issue.

I already explained everything in the ATM5 report, that's why I linked to it.  I can go & copy / paste the entire report here if that would be more appropriate.

**Comment by thiakil** [comment]
Atm5 is not minimal.

**Comment by Tiberias42** [comment]
> 
> 
> Atm5 is not minimal.

Correct.  I don't know how to run just forge & mekansim, I'm just running a pack off of the twitch launcher.  As stated above, I'm going to try and have a friend test the suggestion made by pupnewfster.  Ive also referenced his suggestion to the ticket in the ATM5 group.

**Comment by Tiberias42** [comment]
> 
> 
> I don't believe this has anything to do with Mekanism and is actually caused by performant's "load balancing of events". [#6178 (comment)](https://github.com/mekanism/Mekanism/issues/6178#issuecomment-633575178) I have yet to have anyone actually get around to trying either removing performant, or disabling in their config the load balancing for events and then telling me if it did indeed fix the problem. So if you are willing I would go ahead and disable it in their config and see if it fixes the issue and if so report back.

My friends server is unavailable right now, but I did try and do some testing in a single player world, turning off different parts of performant.  Unfortunately, while I was making progress on getting stable flow rates from Mekanism equipment (built to a 4x ore processing array, all connections advanced level, connected to basic factories, all equipment with at least 4 speed + 4 energy upgrades), I started getting wild FPS fluctuations.  I was jumping from 250+ FPS to around 10 FPS.  But when it was around a decent level, it looked like things were working better... Then I tried to boost the flow via pushing more upgrades & the client locked up, had to hard stop the program.  So it looks like the performant angle is the right track, but its all a bit touchy as far as maintaining stable performance in the big picture.  Im going to copy this information to the ATM5 team & open a ticket with the Performant team.  Ill close this ticket, as this is looks to be an "outside" issue.

**Comment by Tiberias42** [comment]
https://github.com/ldtteam/Performant/issues/46#issuecomment-647094454

FYI, Performant response.

**Comment by thiakil** [comment]
This is really between server owners and Atm5 to configure / remove. If you use a mod that does this, you're going to have issues like this

**Comment by Tiberias42** [comment]
Understood.  Thanks for your assistance.
