### ISSUE TITLE
[Enhancement] config for preferred ore processing output

### ISSUE THREAD

**Issue by Shandoo94** [mekanism/Mekanism#6231]
**Describe the the feature you'd like**
If multiple mods add the same ressource (i.e. copper) you don't have control over which mods ressource (dust, ingot, etc.)  you get during processing.
Solution: A config option which lets you set a mod priority list similar to unidict to choose the preferred recipe outputs for ore processing.

**Describe alternatives you've considered**
The only other option i could think off is to manually change every recipe for every material and material type in crafttweaker.

**Comment by pupnewfster** [comment]
I am going to assume this is 1.12 based on the fact that in 1.15 we don't have any "generic" recipe outputs except for things like our own. This is not going to happen in 1.15, as we are not going to add any generic styled outputs unless it exists/is specific to that mod already so this won't be nearly as much of a problem.
