### ISSUE TITLE
Evaporation Tower Input / Output Flowrates in v420

### ISSUE THREAD

**Issue by papaworld** [mekanism/Mekanism#6232]
Hi, the changes made between 1.15.2 v413 and 1.15.2 v420 caused issues in the Fusion Reactor functions... it stopped working because the Water to Brine Evaporation Tower throughput was reduced from 3000mb in to 2700mb in on a full size tower of 18 blocks. Thus, its production output reduced from 300mb to 270mb. This caused the Reactor to fail and I had to reduce its Injection Rate to keep it running. This also caused a problem with a small 4x4x3 Water to Brine Tower with 500mb Water in to make 50mb Brine. The 4x4x3 now only allows 450mb in and 45mb out, so I made it a 4x4x4 for 60mb out. Is it possible to return the Evaporator Tower equations back to the way they have been in 1.710, 1.12.2 and 1.15.2 v413? The entire Reactor/Tower Power Production Plant build was during 1.15.2 v390 built entirely in 1 chunk producing 9.8Mrf/t. Expansion for an additional tower would have to be outside this chunk :(

The current changes for the Fuelwood heater is a good and fair change (now needing 3 heaters instead of 1 for my current build). And most thankful that you increased the Laser production for 2000rf/t to 4000rf/t... NICE!

**Comment by aidancbrady** [comment]
The Evaporation Plant has gotten a serious bump-up in production for v10. Marking this as fixed in dev.
