### ISSUE TITLE
Chemical Dissolution Chamber gas use increases per unit processed with speed upgrades

### ISSUE THREAD

**Issue by Cunning247** [mekanism/Mekanism#6234]
#### Issue description:
The Chemical Dissolution Chamber uses approx 10x more Sulphuric Acid gas per unit of ore processed with speed upgrades installed. Obviously it should use more per tick because it is processing faster, but in my testing it was using an order of magnitude more per unit:

* No upgrades: Approx 92 mB per ore
* 8x Gas upgrades: Approx 10mB per ore
* 8x Gas, 8x Speed: Approx 96 mb per ore
* 8x Speed: Approx 900 mB per ore

I noted some variability in exactly how much was used, but far less than the changes from the 8x Speed / Gas upgrades.

#### Steps to reproduce:
1. Power CDC and fill with Sulphuric Acid
2. Disconnect Sulphuric Acid source to make taking usage readings easier
3. Insert Iron ore and observe drop in acid level
4. Insert 8x speed upgrades
5. Insert Iron ore and observe much larger drop in acid level

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.0
**Mekanism:**  9.10.8.421
**Other relevant version:**

**Comment by aidancbrady** [comment]
This scaling algorithm is also used for energy; it's perfectly intended behavior for 8 speed upgrades to require an order of magnitude more of resources/gas. Use energy upgrades or gas upgrades to mediate this.

**Comment by Cunning247** [comment]
OK, fair enough, but it's actually two orders of magnitude per second because it's 10x as much per unit and 10x units per second. Seems really odd that using 10 machines with no speed upgrades gets you the same throughput with 1/10th the resources as using one with a 10x speed upgrade.
