### ISSUE TITLE
Ores Mined in World not being Processed

### ISSUE THREAD

**Issue by GamerMomB** [mekanism/Mekanism#6236]
I'm having a strange issue and I cannot find the source of the problem. I'm submitting here because it's only happening with Mekanism Machines.

I created a modpack with all very popular mods. I've searched for possible conflict issues and didn't find anything documented. What is happening is that Ore mined either in world or in Aroma Mining Dimension are not being processed in Mekanism Machines. I set up an Ore Tripling system. First Machine the Purification Chamber, with Oxygen and Power, iron ore just sits there. If I cheat in an iron ore, it works fine. Also doesn't work in any of the other machines where its supposed to handle ores. Yet they work in Ender IO machines. I disabled a few mods that I thought could be changing something about the Ore Dictionary, I tried disabling Doogaloo Cities (adds some kind of money value system), Custom NPCs (I had read somewhere that this can cause issues with AE2 and ore tagging system), and UniDict (I thought maybe in the mining of the ore this might be changing something). This didn't fix the issue.

I reproduced the issue by loading a test world and setting up the same system. I mined iron ore and osmium both in world and in mining dimension. Again they didn't work. I cheated the ores in, and they worked.

I have included a list of the mods. All of them are popular mods, and I've never encountered this problem before. I'm at a loss at what could be causing this. Maybe something here will stand out as possible conflicts. I'm not super familiar with code or adding code to tweak files. So I don't want to try to mess with anything myself in case I break something.

Thank you for any help you can provide. My son and I were really looking forward to digging into the Mekanism Mods and learning them more in depth :) They look like a lot of fun.
#### Steps to reproduce:
1. Mine ore in world/dimension
2. Try to Process in Machine. Doesn't work.
3. Cheat the same exact ore in. It works.

I have screen shots where it shows it not working, and then working with cheated in ore. If they are needed I can post them.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2854
**Mekanism: 1.12.2-9.8.3.390

List of Mods:
Actually Additions
Additional Structures
Advanced Chimneys
Advanced Rocketry
AE2 Stuff
AE2 Wireless Terminal Library
AI improvements
Akashic Tome
Ancient Warfare 2
Animania
AppleCore
AppleSkin
AE 2
Aquaculture 2
Architecture craft
Aroma1997Core
Aroma1997s Dimensional World
AtomicStryker’s Infernal Mobs
Auto Pickup
AutoRegLib
Backpacks!
Baubles
BdLib
Better Advancements
BetterFps
BiblioCraft
Biomes o Plenty
Blockcraftery
Bloodmoon
Bookshelf
Botania
Bountiful
Brandon’s core
Buildcraft
Carry On
Chameleon
ChineseWorkshop
Chisel
Clumps
CodeChicken lib
Cofh Core
Cofh World
Common capabilities
CompatSkills
Connected Textures Mod
Controlling
Cooking for blockheads
Crafting tweaks
Craftstudio API
Craft Tweaker
Creeper confetti
Custom NPCs
CXLibrary
Cyclic
Cyclops core
Dark Utilities
Ding
Dooglamoo Cities
DoomLike Dungeons
Draconic Evolution
Dungeons2
Dynamic Surroundings
Dynamic Trees
Dyn Trees BoP
Enchantment Descriptions
Ender Crop
Ender IO
Ender Storage
Ender Core
Everlasting Abilities
Evil Craft
Extra Utilities
Extra Cells 2
Familiar Fauna
Farming for Blockheads
Farseek
Fast Leaf Decay
Faster Ladder Climbing
Fence Jumper
Fish’s Undead Rising
FoamFix
Forestry
Forge MutliPart CBE
Forge Endertech
GottschCore
Guide API
Gunpowder Lib
Heroic Armory
ICBM Classic
Ice and Fire
Integrated Dynamics
Integrated Tunnels
Inventory Pets
Inventory Tweaks
IvToolKit
JurassiCraft
Just Another Rotten Flesh to Leather Mod
JEE
JEHC
JEI
JER
KleeSlabs
Large Ore Deposits
Level Up Legacy
LibrarianLib
Library Ex
LibVulpes
LLibrary
Loot Slash Conquer
Macaw’s Bridges
Macaw’s Windows
Mantle
McJtyLib
MegaLoot
Mekanism
Mekanism Generators
Mekanism Tools
Minecraft Comes Alive
Mob Grinding Utils
Mod Name Tooltip
More Furnaces
Morpheus
MouseTweaks
Mowzies Mobs
MrCrayfish Furnture Mod
MrTJPCore
Mystcraft
Mystical World
Mystical Lib
Natures Compass
NetherEx
NoRecipe Book
Not Enough Ids
Omlib
Open Modular Turrets
OpenBlocks
OpenBlocks Elevator
OpenModsLib
OreExcavation
OreLib
Optifine
P455w0rd’s Library
Pams Harvestcraft
Patchouli
Placebo
Potion Core
Prefab
Project Red Base
PR Compat
PR Fabrication
PR Integration
PR Lighting
PR Mechanical
PR World
Pyramid Plunder
Quality Tools
Quark
Railcraft
Random Loot Mod
Random Things
Reborn Core 
Reborn Storage
Recurrent Complex
Redstone Flux
Refined Storage
Refined Storage Addons
Reskillable
Ruins
Rustic
Serene Seasons
Shadowfacts Forgelin
Silent Gear
Silent Lib
Simple Camp Fire
Simply Jetpacks 2 
Snad
Spartan and Fire
Speartan Weaponry
Statues
StimmedCow
Storage Drawers
Streams
Structurize
Swing Through Grass
Switch-Bow
Taiga
Tesla Core Lib
The Beneath
The Eight Fabled Blades
The Midnight
The Mighty Architecht
The One Probe
Thermal Cultivation
Thermal Dyn
Thermal Exp
Thermal Found
Thermal Inno
Tinkers Jei
T Contstruct
Tinkers tool leveling
TnTUtils
Toast Control
Torchmaster
Trample Stopper
UniDict
Useful Nullifiers
Vanilla Fix
ViesCraft
WanionLib
Waystones
Wizardry Mod
Xaeros MiniMap
Xaeros World Map
Xnet
XP from Harvest
YUNGs better Caves

**Comment by pupnewfster** [comment]
If memory serves this is probably due to a mod adding NBT to the ore. I believe you can setup an oredictionificator to convert that ore into "itself" and strip the NBT from it allowing for it to work properly in the machines.

**Comment by GamerMomB** [comment]
Is it the OreDictionificator that will actually do the stripping of the NBT? Or is this something extra I need to do after? I did try to do something with the oredictionificator, but I wasn't super clear how it was supposed to work. Not sure if I ever got anywhere with that because I had originally been using Caverns 2 mod as a mining dimension, and I thought that was the problem. Worried that it had corrupted my world, I started a new world with a different mining dim. I will try the Dictionificator again and post the results.

**Comment by GamerMomB** [comment]
Thank you. That did work. I remember now, that I wasn't sure how to use it, so I tried using Auto Ore Dictionary Converter assuming they did the same thing. That one didn't work, and then I started down a different path thinking Caverns 2 (which apparently has lots of issues) was the culprit.
