### ISSUE TITLE
[1.15.2]Energy Upgrade doesn't work for Electrolytic Separator

### ISSUE THREAD

**Issue by CatherineHHHHH** [mekanism/Mekanism#6240]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I put energy upgrades in electrolytic separator, the energy cost doesn't change. Having this issue when playing All the Mods 5 (version 2.5)

#### Steps to reproduce:
1. Give power to electrolytic separator
2. Put energy upgrades in it.
3. See the energy cell if the power cost changes

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-31.2.20
**Mekanism:** Mekanism-1.15.2-9.10.8.421
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by thiakil** [comment]
This is intended
