### ISSUE TITLE
[1.12.2] If you break the Logistical Sorter while it's working, it keeps making sound forever until you place it back down and allow it to finish

### ISSUE THREAD

**Issue by aaronhowser1** [mekanism/Mekanism#6245]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
It's working now, and making sounds
![image](https://user-images.githubusercontent.com/15698722/85898299-a4392100-b7c1-11ea-9f33-c4304f778937.png)
If I break it, it stops working but doesn't stop making sounds.
I have to place it back down and let it finish naturally for it to stop.

#### Steps to reproduce:
1. Allow Log Sorter to work
2. Break it before it finishes

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 1.12.2-9.8.3.390
**Other relevant version:** 14.23.5.2847

**Comment by aidancbrady** [comment]
Fixed in 1.15.
