### ISSUE TITLE
[1.15.2]Crash in launch game

### ISSUE THREAD

**Issue by Rumaruka** [mekanism/Mekanism#6246]
#### Steps to reproduce:
1. Launch game
2....
3.Catch crash log

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.27
**Mekanism:** 9.10.8.421

**Comment by pupnewfster** [comment]
Please provide your latest log as that crash report is useless due to https://github.com/MinecraftForge/MinecraftForge/issues/6374

**Comment by Rumaruka** [comment]
Sorry for delay 
Where latest log file : https://pastebin.com/gXPAUZVM

**Comment by pupnewfster** [comment]
At first glance it seems that the actual crash is: `Exception caught during firing event: The recipe component of org.cyclops.integrateddynamics.core.ingredient.IngredientComponentHandlers$1@1a69fe14 was null, it is probably not initialized yet!` 

I don't know enough about their system to know why that may be null (or why they are even doing things with recipes that early), but looking at https://github.com/CyclopsMC/IntegratedDynamics/issues/875 it seems like they are not quite sure what is causing that to fail yet.
