### ISSUE TITLE
Fuision Reactor Logic Adapter always showing Active cooling

### ISSUE THREAD

**Issue by ToMe25** [mekanism/Mekanism#6247]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
On the top of the Fusion Reactor Logic Adapter is a button with the tooltip "Toggle Cooling Measurements" next to which is the text "Active cooling", but clicking this button doesn't change anything, and the text remains "Active cooling".

#### Steps to reproduce:
1. Build a fusion reactor with a Logic Adapter
2. Rclick the Logic Adapter to open his GUI
3. Click the 'T' button, and see nothing happen

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.9
**Mekanism:** 225859d
**Other relevant version:** none

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by aidancbrady** [comment]
Fixed in v10.

**Comment by ToMe25** [comment]
The last v9 build was released, and this is fixed in v10, so i am closing this.
