### ISSUE TITLE
Server Crash after breaking Advanced Compressor Factory

### ISSUE THREAD

**Issue by tplc10** [mekanism/Mekanism#6255]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Breaking a Compressor Factory crashes the server

#### Steps to reproduce:
1. Place down Compressor Factory
2. (Maybe) Put liquid in the factory
3. Break the factory

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.2.21**
**Mekanism: 9.10.8.421** 
**Other relevant version: Valhesia 2.2.3 (Modpack)** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[server log](https://github.com/mekanism/Mekanism/files/4848503/message.1.txt)]

**Comment by pupnewfster** [comment]
I am not able to reproduce this in the V10 branch in 1.16. Is this just something that happened randomly once or are you able to easily reproduce it every time you place and break a factory.

**Comment by pupnewfster** [comment]
Feel free to comment and I will re-open if you are able to reproduce this in V10 on 1.16, as we are no longer developing for 1.15.
