### ISSUE TITLE
1.15.2 Electrolytic Separator power usage

### ISSUE THREAD

**Issue by 03453404558** [mekanism/Mekanism#6261]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I am producing hydrogen and oxygen, with 8/8 power and speed upgrades, the Electrolytic Separator uses 40k FE/T
I am on the modpack Valhelsia 2 and am using the latest version (don't know if that matters)

#### Steps to reproduce:
1. Place Electrolytic Separator
2. Connect power
3. Put 8 speed upgrades and 8 energy upgrades in
4. Give as much water as possible (I use the kitchen sink from cooking with blockheads and ultimate mechanical pipes)
5. Dump Excess on both hydrogen and oxygen
6. Check power usage.

![Electrolytic Separator](https://user-images.githubusercontent.com/67224154/86381419-3ab78780-bc85-11ea-86e0-22693ddb5db1.JPG)

**Comment by aidancbrady** [comment]
Very commonly reported issue. Energy Upgrades only increase power buffer of the Electrolytic Separator. Improving energy efficiency would create net power gain from water -> hydrogen -> energy, which is physically impossible.
