### ISSUE TITLE
Owner in the machine tooltip is 'null'

### ISSUE THREAD

**Issue by Fukutu** [mekanism/Mekanism#6264]
#### Issue description:

**This doesn't affect security.**
Reopening the world, the problem is solved.

![image](https://user-images.githubusercontent.com/60327358/86502785-6a49bb00-bd7d-11ea-9b00-a067bc4c1c8b.png)

#### Steps to reproduce:
1. You **MUST** create a new world
2. Place any machine
3. Dismantle the machine
4. Take a look at the machine tooltip 

#### Version:
**Forge: 31.2.30** 
**Mekanism: 9.10.8**

**Comment by aidancbrady** [comment]
Now fixed in v10 with 456f752.
