### ISSUE TITLE
[1.15.2] Recipe complications with CraftTweaker

### ISSUE THREAD

**Issue by TheUntamed** [mekanism/Mekanism#6268]
If I remove the tag from an item e.g. an steel ingot that ingot can still be used to craft the steel items of this mod.
This only happens for recipes of this mod. All other recipes using the item tag cannot longer use that item (because it doesn't have the tag anymore).

forge-31.2.30
MekanismTools-9.10.8.421

**Comment by pupnewfster** [comment]
Going to go ahead and say not mekanism, we use vanilla's tag system: https://github.com/mekanism/Mekanism/blob/1.15x/src/datagen/generated/mekanismtools/data/mekanismtools/recipes/steel/tools/pickaxe.json#L13 potentially crafttweaker is removing from the tag in a strange way or something no idea.
