### ISSUE TITLE
Heating evaporation concentration plant　1.15.2

### ISSUE THREAD

**Issue by Lard5626** [mekanism/Mekanism#6269]
↓Use GOOGLE translation.↓
When using a heating evaporation concentrating plant, I can bring in water but not salt water.
I personally searched for the cause as much as possible, but I could only find that the detailed explanation of the pipe that carries the fluid is "Minecraft forge" and the detailed explanation of the other pipes is "Mekanism".
The heating evaporative concentration plant itself was functioning, it was possible to relay buckets using tanks, and pipes could carry salt water and lithium through tanks.
The problem is that i cannot carry out the fluid from the heating evaporation concentration plant.
I tried using the configurator, but it didn't work.
I don't know if it is my own problem or an existing problem, so I asked a question. Thank you.

*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
It might be of use to provide pictures of your setup to make it easier to figure out what it is that you are currently trying.
