### ISSUE TITLE
Internal Exception at LAN world login

### ISSUE THREAD

**Issue by Fukutu** [mekanism/Mekanism#6270]
#### Issue description:

The server connection is lost when I join the **LAN** world

![image](https://user-images.githubusercontent.com/60327358/86544284-fbdf3700-befb-11ea-89d2-6133b8908cc0.png)

#### Steps to reproduce:
1. Open a world to **LAN**
2. Try to join the **LAN** world

#### Version:
**Forge: 32.0.47** 
**Mekanism: [10](https://github.com/Fukutu/Mekanism/tree/c0c9dfe8ea93d81fe2354271ff85333bb6143a93)**

**Comment by pupnewfster** [comment]
No idea if there are any other issues in LAN given for the most part I don't believe modders really tend to bother ensuring proper LAN support, but https://github.com/mekanism/Mekanism/commit/3d2fc3892327bec2b0257fc58d850b291829907d seems to at least allow the second player to connect via LAN (though I have not really bothered testing it beyond that).
