### ISSUE TITLE
Mekanism Industrial Turbine will not form

### ISSUE THREAD

**Issue by CodingJawa** [mekanism/Mekanism#6273]
#### Issue description:
MekanismGenerators Industrial Steam Turbines cannot form multiblock

#### Steps to reproduce:
1. Build standard size industrial turbine
2. Notice no connected textures, no particle effects
3. will not take steam

#### Version (make sure you are on the latest version before reporting):
**Forge:**  1.15.2-1.0.7
**MekanismGenerators:** 1.15.2-9.10.7.420

**Comment by CodingJawa** [comment]
Tested with 
5*9 and 13*18 size

**Comment by pupnewfster** [comment]
Without images it is kind of hard to have ideas of what you might have accidentally messed up. Do note however the connected textures have nothing to do with if the multiblock is formed or not; they have to do with if you have [CTM](https://www.curseforge.com/minecraft/mc-mods/ctm) installed.

**Comment by CodingJawa** [comment]
![2020-07-07_01 39 10](https://user-images.githubusercontent.com/66843176/86668620-206a0a80-bff3-11ea-8bee-392ef917fa41.png)
![2020-07-07_01 40 03](https://user-images.githubusercontent.com/66843176/86668631-22cc6480-bff3-11ea-9e73-04ccda7d0509.png)
![2020-07-07_01 40 10](https://user-images.githubusercontent.com/66843176/86668665-29f37280-bff3-11ea-9514-3f52f5788a90.png)

**Comment by aidancbrady** [comment]
Your turbine looks narrow. Try making it a little wider.

**Comment by aidancbrady** [comment]
Vents cannot go on edges, that is your issue.

**Comment by CodingJawa** [comment]
@aidancbrady those are cross sections, made for the purpose of demonstrating the correct inner build. The Vents are not on any edges. the reactor turbine has been made in size 5x9 and was built according to the FTB-Wiki entry (https://ftbwiki.org/Industrial_Turbine). Please reopen

**Comment by aidancbrady** [comment]
If you can provide a world upload I’ll take a look.
