### ISSUE TITLE
Baby Skeletons ignoring config 1.12.2

### ISSUE THREAD

**Issue by SubjectHawk66** [mekanism/Mekanism#6274]
I had a problem with baby skeletons (fun addition btw) so I tried to disable them but it didn't seem to work. I double checked to make sure. This is in multiplayer.

**Comment by pupnewfster** [comment]
They need to be disabled on the server side. If it doesn't work then you are unfortunately out of luck given we are no longer developing 1.12 and last I checked it works properly in both 1.15 and 1.16.
