### ISSUE TITLE
[1.15.2] Crash connecting logical transporters to immersive engineering multiblock

### ISSUE THREAD

**Issue by Jackzmc** [mekanism/Mekanism#6278]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When you have a logical transporter connected to a coke oven from Immersive Engineering, and try configuring it your game will crash. I also had the crash happen just creating a coke oven right next to an existing transporter.
When you load the world up from the crash, it will just crash again with the same error.

#### Steps to reproduce:
1.  Place logical transporters
2. Create a immersive engineering coke oven multiblock
3. Use the configurator to change the mode

#### Version (make sure you are on the latest version before reporting):
**Forge: ** 31.2.31
**Mekanism:** 1.15.2 - 9.10.9.422
**Other relevant version:** Immersive Engineering 0.15-103, no other mods except JEI

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://paste.ee/p/6lrfJ Crash report

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Not mekanism they are returning null from their get capability
