### ISSUE TITLE
Item Tags

### ISSUE THREAD

**Issue by TheUntamed** [mekanism/Mekanism#6280]
In mc 1.15.2 mekanism items have mekanism item tags instead of forge item tags. E.g. "mekanism:dirty_dusts" instead of "forge:dirty_dusts". That makes those item incompatible with similar items of other mods. Would be cool if that could be changed, at least in the future versions (mc 1.16+)

**Comment by pupnewfster** [comment]
The reason these tags are in Mekanism's domain and not forge's is that they are a bit more specific to Mekanism in my opinion and other mods may have some sort of "dirty dust" that means something entirely different and isn't equivalent for purposes of the ore processing recipes. Though there is nothing stopping pack makers (or other mod devs) from adding their things to our tags, or even to just make our recipes use some "generic" tag in the forge domain after making sure that all of those things are actually "interchangeable".
