### ISSUE TITLE
error when i open minecraft 

### ISSUE THREAD

**Issue by K04l4-mc** [mekanism/Mekanism#6282]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:when i open minecraft end enter in my world, my game crash and send me this error

The game crashed whilst ticking block entity
Error: java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=on, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateMachine{block=mekanism:machineblock2, properties=[active, facing, recipe, tier, type]}

i use the versione 1.12.2 

same1 can pls help me ?

**Comment by thiakil** [comment]
a) that is not nearly enough information
b) we no longer support 1.12

**Comment by K04l4-mc** [comment]
> a) that is not nearly enough information
> b) we no longer support 1.12

I have an old world of Minecraft and I have updated the mod in the package that I use for this world and I have updated the mekanism, since I have updated it if I enter the world my game crash and it only gives me this errors

**Comment by pupnewfster** [comment]
No idea what is going on, seems like something went wrong during the upgrade process. Your best bet would be to upgrade fewer versions at a time because maybe the data fixers had some edge case they didn't handle properly.
