### ISSUE TITLE
Mekanism Reactor will not accept fuel

### ISSUE THREAD

**Issue by alphanerd132** [mekanism/Mekanism#6285]
Good day  all, Playing on the FTB OMNIA pack
I have been playing around with, and built a Mekanism  reactor. I followed the official guide on how to build the reactor and use  it. I can start the reactor just fine running it off of straight D-T fuel. That works just fine. The issue comes down to when I go to add a fuel mixture rate for the separate tritium and deuterium fuels. I can type a number in the entry box, but when  I hit enter, it does nothing at all. To detail out my build of the reactor and how I start it and run it, I made a youtube video showing how everything is setup which is linked below. If this isn't a bug and me being dumb I do [apologies,](url) but I do not see where I am going wrong at this time. [Video Of Issue](https://youtu.be/XXvx_NmsaMs)

**Comment by pupnewfster** [comment]
Hmm not sure why it wouldn't be letting you hit enter given I am not able to reproduce . My best guess is that maybe something weird is going on with one of the other mods in the pack.

**Comment by alphanerd132** [comment]
> Hmm not sure why it wouldn't be letting you hit enter given I am not able to reproduce . My best guess is that maybe something weird is going on with one of the other mods in the pack.

Thanks for your input.  I  wanted to make  sure  I  wasn't doing  something wrong.  Ill  see  if I can get  a  hold of the OMNIA  team to see if they  changed something.

**Comment by alphanerd132** [comment]
> Hmm not sure why it wouldn't be letting you hit enter given I am not able to reproduce . My best guess is that maybe something weird is going on with one of the other mods in the pack.

I FOUND IT!! Only 1 of the 2 enter buttons work! My key pad button does not work with  the  reactor while the letter  pad enter works!

**Comment by pupnewfster** [comment]
Glad you figured it out, to be honest I had forgotten keyboards have multiple enter keys
