### ISSUE TITLE
cables + wind generators = xray

### ISSUE THREAD

**Issue by SirBit** [mekanism/Mekanism#6287]
#### Issue description:
Cables connected to wind generators allows you to see through blocks

![image](https://user-images.githubusercontent.com/68129475/87203525-143bc100-c303-11ea-8e9d-595bfee26c45.png)

#### Version :
**Forge:** 32.0.62
**Mekanism:** 10.0.0.423
**Other relevant version:** MC 1.16.1

**Comment by pupnewfster** [comment]
Is this with a mod like optifine or is this just forge and mekanism?

**Comment by SirBit** [comment]
i had optifine before but before i took this screenshot i deleted it

**Comment by pupnewfster** [comment]
Putting this on hold for now as an engine limitation with Mojang's WIP rendering engine and how custom render types are handled (Things like slime entities cause this same effect in fact). There are a few different things that we could do the help alleviate this issue, but they also come with their own separate issues so we will need to evaluate them carefully.
