### ISSUE TITLE
(1.16.1) Graphical Glitch Modification Station

### ISSUE THREAD

**Issue by SrSlime** [mekanism/Mekanism#6289]
#### Issue description:
Graphical issue with the modificaion station. Things go black _(Like shadow)_

West:
![2020-07-11_02 52 09](https://user-images.githubusercontent.com/68140292/87217619-91762e80-c321-11ea-9889-eae69f9082e6.png)
![2020-07-11_02 49 22](https://user-images.githubusercontent.com/68140292/87217608-74d9f680-c321-11ea-9a2a-eff26adb5af7.png)

North:
![2020-07-11_02 49 27](https://user-images.githubusercontent.com/68140292/87217609-75728d00-c321-11ea-84d3-4acab47e0f6c.png)

East:
![2020-07-11_02 49 31](https://user-images.githubusercontent.com/68140292/87217610-76a3ba00-c321-11ea-8038-6142034cf0d4.png)

South:
![2020-07-11_02 49 32](https://user-images.githubusercontent.com/68140292/87217611-773c5080-c321-11ea-83da-c5c38d48a592.png)

#### Steps to reproduce:
1. Just place the modification station anywhere, or/and
2. Place a block in the left upper side of the station to be more glitched.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.63
**Mekanism:** 10.0.0.423
**Other relevant version:** None

**Comment by aidancbrady** [comment]
Turn on Forge's experimental lighting pipeline in 'forge_client.toml' (in your config directory).

We'll probably be getting a lot of issues like this until the forge lighting pipeline is defaulted...
