### ISSUE TITLE
Logistical Sorter color button is bugged

### ISSUE THREAD

**Issue by aidancbrady** [mekanism/Mekanism#6291]
Clicking or right-clicking the Logistical Sorter ejection color past 'None' will not allow the user to select 'None' again, and no longer wraps around when selecting an out-of-bounds indexed color. Other ColorButton implementations are working fine.

**Comment by pupnewfster** [comment]
Additionally it seems that shift left clicking it does not reset it to 'None'. And it seems that we get this exception `java.lang.RuntimeException: VarInt too big` printed to the console.
