### ISSUE TITLE
Certain sounds are far too loud

### ISSUE THREAD

**Issue by dmtRoyal** [mekanism/Mekanism#6295]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The gear switch sound, as well as the Gravitational Modulating Unit's sound are unconscionably loud.  Compared to the regular hydrogen jetpack module, it's far louder than it needs to be.

Yes, I'm aware you can adjust Mekanism's sounds in the configs for the mod, but your mod should be tolerable out of the box without needing to change the configs.

#### Steps to reproduce:
1. Get the MekaSuit
2. Install Gravitational Modulating Unit
3. Acquire tinnitus

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.63
**Mekanism:** 10.0.0.423
**Other relevant version:** MC 1.16.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
N/A

**Comment by aidancbrady** [comment]
Thanks for the report, will be much more tolerable in v10.0.1 :)
