### ISSUE TITLE
Minecraft 1.16.1 crash on startup

### ISSUE THREAD

**Issue by skellitor301** [mekanism/Mekanism#6297]
[Crash Report](https://gist.github.com/skellitor301/7667fea5cf1e0a008fc457c8dfe6441d)
[Full Log](https://gist.github.com/skellitor301/18bed3e3f9e94c4f90641a59bfabd480)

I have installed all 4 files for Mekanism: [Mekanism-116.1-10.0.0.423](https://www.curseforge.com/minecraft/mc-mods/mekanism), [Generators-1.16.1-10.0.0.423](https://www.curseforge.com/minecraft/mc-mods/mekanism-generators), [Tools-116.1-10.0.0.423](https://www.curseforge.com/minecraft/mc-mods/mekanism-tools), [Addons-116.1-10.0.0.423](https://www.curseforge.com/minecraft/mc-mods/mekanism-additions). 
Game crashes upon startup, giving me this error: Error: java.lang.NullPointerException: Registry Object not present: mekanismadditions:black_plastic

**Comment by pupnewfster** [comment]
The crash report shows us due to [this](https://github.com/MinecraftForge/MinecraftForge/issues/6374) forge bug that causes the real crash to be hidden. In your latest log there is this message (and the start of the actual crash). It seems that better bedrock requires mixin bootstrap.
```
[12:58:28] [modloading-worker-3/ERROR]: Failed to create mod instance. ModID: betterbedrockgenerator, class be.nevoka.betterbedrockgenerator.BetterBedrockGenerator
java.lang.IllegalStateException: This is an expected crash because MixinBootstrap isn't (properly) installed. 
You can download it from: https://github.com/LXGaming/MixinBootstrap/releases 
Copy the jar into your mods folder.
	at be.nevoka.betterbedrockgenerator.BetterBedrockGenerator.<init>(BetterBedrockGenerator.java:20) ~[?:0.0.7]
```

**Comment by skellitor301** [comment]
I installed mixin bootstrap but there's still a crash with the same error message.
[Crash log](Error: java.lang.NullPointerException: Registry Object not present: mekanismadditions:black_plastic)
[Full log](https://gist.github.com/skellitor301/0fb18a6dd940b9eeb2213a82901835d6)
Btw, for future reference, where do I find the layout to post in the proper format? I looked around and I couldn't really find one.

**Comment by skellitor301** [comment]
Nevermind I have found it. somehow I was given a blank entry when creating a new issue

**Comment by pupnewfster** [comment]
No idea the latest log still claims that you don't have mixin bootstrap installed or that it is not properly installed.

**Comment by skellitor301** [comment]
That's correct, the download failed. the game doesn't crash anymore, thanks for the assistance
