### ISSUE TITLE
How exactly is the fission reactor multiblock built?

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#6301]
I know none of the wikis have been updated in a while and do not contain this information but I am just wondering about the construction of the new fission reactor

**Comment by aidancbrady** [comment]
Make a big frame with Fission Reactor Casing & Reactor Glass, min of 3x4x3 and max of 18x18x18. Inside, place as many fuel assembly towers as you want. Fuel assembly towers involve vertically stacked Fission Fuel Assembly blocks, with a Control Rod Assembly on top (NOT on the top layer of the multiblock where the glass or casing is). If you place your fuel assemblies too closely together you'll face a boil efficiency penalty, so make sure to give them proper space.
