### ISSUE TITLE
Magnetic Attraction Unit Hotkey

### ISSUE THREAD

**Issue by ChloeDawn** [mekanism/Mekanism#6307]
There is currently no way to conveniently disable magnetic attraction temporarily, which can lead to situations where items follow you around until you either have inventory space or manage to move fast enough to get out of range. Some way of temporarily disabling the magnetic attraction to easily get out of range from items without hassle would be great. A dedicated hotkey that disables attraction when held down could work.

**Comment by aidancbrady** [comment]
You can always use the module tweaker to disable the module. The hot key is backslash by default.

I don’t see a huge need to add a keybind for this, but perhaps I’ll do so if this continues to be a problem.
