### ISSUE TITLE
no jump boost - hydraulic propulsion uni

### ISSUE THREAD

**Issue by Fidulus** [mekanism/Mekanism#6308]
Hy, i Love your mod. It's so much fun. Can't thank you enough for it, brings so much more fun into the game.

Issue: I build the meka-suit- boots. And i installed the hydraulic propulsion unit and everything else.
problem is the "jump boost" does nothing. Simply won't work at all. The "stepping assist" works fine.
If i can be of any help regarding this issue or maybe i am doing something wrong just tell me.

**Comment by vlad-gfr** [comment]
it works only on sprint

**Comment by Fidulus** [comment]
> it works only on sprint

hmm sadly doesn't work while sprinting either.
At least for me.

**Comment by ChloeDawn** [comment]
There is a boost keybind that you hold whilst performing an action to have it boost. Check what it is set to in your controls.

**Comment by Fidulus** [comment]
Thanks for the all your kind replies. 
It's bound to the sprint key = strg
Thought that's intented. I'll try a different one, and report back.

**Comment by Fidulus** [comment]
> There is a boost keybind that you hold whilst performing an action to have it boost. Check what it is set to in your controls.

**YOU GOT IT** XD
Thank you so much. I just defined the boost key to a different one and when i hold it AND jump it works!
I would never have figured that out on my own. 
Have a great day.
