### ISSUE TITLE
railcraft esque update and midgame energy

### ISSUE THREAD

**Issue by Wotzinator** [mekanism/Mekanism#6311]
**Describe the the feature you'd like**
i find that the mod at its current state somewhat lacks transportation on long range without teleportation so i think adding railcraft esque systems with a mekanism spin on the would be amazing.
-locomotives too pull other custom train part or push certain carts,i think a gas powerewd and an electrical locomotive       would fit the mod quit well
-carts like tank carts storage carts etc would be awsome especially with high tech models wich mekanism is known for instead of the vanilla cart looks also interesting would be drills wich need too be pushed.
-loading and unloading stations

i also have the feeling that it is very hard to get enough energy early on without spamming solar panels and wind turbines so im suggesting some carbon based energy varients
-early steam power:i know that steam is mostly used in great scales in this mod in big turbines but i do think that a modern steam engine plus generator would do really well in early to mid game it should be fired by normal furnace fuels

**Describe alternatives you've considered**

**Additional context**

**Comment by pupnewfster** [comment]
Trains are not in line with what Mekanism is about so this will not be happening.
