### ISSUE TITLE
7x7 Fission Reactor Not Working

### ISSUE THREAD

**Issue by phillmorgan28** [mekanism/Mekanism#6314]
#### Issue description:
7x7 Fission reactor is not recognised as a multiblock.

#### Steps to reproduce:
1. Construct a 7x7 fission reactor underground using fission reactor casing for the whole base and corner pieces. (This makes a cubic frame of fission casing with a filled in base.)
2. Fill in the walls with reactor glass for the sides and top.
2. Add 4 fission ports in place of some glass on the walls and and fill the chamber with water.
3. Add 12 fuel assemblies in 4 stacks of 3 with a control rod on top of each. These are positioned so they are not touching the walls, roof or each other. They are only in contact with the base. The control rods are 1 block below the water line.

#### Version (make sure you are on the latest version before reporting):
**Minecraft:** 1.16.1
**Forge:** 32.0.63
**Mekanism:** 10.0.1.424
**Other relevant version:** Installed generators, tools and additions addons all matching version of Mekanism

**Comment by aidancbrady** [comment]
Right-click the multiblock with a configurator to see what the issue is.

**Comment by DefineNaCl** [comment]
fill the chamber with water. <- dont do that (I removed the water and it worked)
