### ISSUE TITLE
Atomic disassembler's vein mining mode doesn't work on Nether gold ore an gilded blackstone.

### ISSUE THREAD

**Issue by UnitedFire** [mekanism/Mekanism#6315]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Hello,
I just found a bug while beeing in the nether. 
When i mined nether gold ore it didn't mined the the vein at all. 
I was using the normal vain mode of the atomic disassembler. I tried with the extended vein mode and it worked. 
I tested the vein mode on gilded blackstone too and it doesn't work but the extended vein mode do work.
They are no crashes while doing these actions.
Your mod is amazing,
Have a nice day.
#### Steps to reproduce:
1. Equip the Atomic Disassembler
2. Activate vein mode
3. Mine nether gold ore or gilded blackstone
4. The vein isn't mined
#### Version (make sure you are on the latest version before reporting):
**Forge:* 32.0.63* 
**Mekanism:* 10.0.1* 
**Other relevant version:* 1.16.1* 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Robball14** [comment]
It isn't a bug, it's a forge thing that didn't associate the nether gold ore to `forge:ores`

**Comment by pupnewfster** [comment]
As Robball said this isn't a bug, forge hasn't decided on tags for the 1.16 blocks yet https://github.com/MinecraftForge/MinecraftForge/issues/6870. I am going to leave this issue open however so that we don't have other people opening the same issue. If you really want you can add those types of things to the different tags yourself via a datapack.

**Comment by UnitedFire** [comment]
Ok thanks for the help.
