### ISSUE TITLE
Duplication/Time Rewind

### ISSUE THREAD

**Issue by GrubbySculpin** [mekanism/Mekanism#6316]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I started in a new 1.16.1 world, and I'm at the point of checking out the nether with a jet pack. After returning from the nether, I noticed that my jet pack was still in my electrolytic separator as well as on my person. After a few more trips, I found another jet pack in my machine, as well as some of my machines having been moved to a previous state. This might be a Mekanism bug, or just 1.16.1 being weird, but I'm not quite sure.

#### Steps to reproduce:
1. Took something out of machine
2. went to nether and came back
3. object is returned to previous state and may still be in inventory

#### Version (make sure you are on the latest version before reporting):
**Forge:** latest
**Mekanism:** 10.1
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I am going to assume you mean you are on version 10.0.1 not 10.1 as we have not made a version 10.1 yet. Could you please provide your latest log as maybe it will provide some clues.

**Comment by Dynamiczbee** [comment]
I've had the same thing happen on my private server I was hosting yesterday. It seemed similar to the book dupe to me in functionality, although it seemed to be a 50/50 chance the duped items would stay in my inventory or disappear. The block removal seems to appear only if you leave a chunk very quickly after placement.

**Comment by thiakil** [comment]
Something in the chunk (could be non Mekanism) is likely causing errors on saving, so the chunk isn't being saved.

We need the log to be able to offer clues

**Comment by Dynamiczbee** [comment]
What log file should I look for to get you guys?

**Comment by thiakil** [comment]
Latest.log is its name

**Comment by Dynamiczbee** [comment]
It's just a straight up 1KB line of text on my server, is it client side?

**Comment by Dynamiczbee** [comment]
Ok I shut down the server, this is what I've got:
[latest.log](https://github.com/mekanism/Mekanism/files/4917235/latest.log)

**Comment by pupnewfster** [comment]
Slightly hard to say but I wonder if https://bugs.mojang.com/browse/MC-194811 has something to do with this.

**Comment by pupnewfster** [comment]
I am going ahead and marking this fixed in dev as I have made a bunch of changes in this commit https://github.com/mekanism/Mekanism/commit/47772164bf5a8dcdb16cf8eb74af2ad3c29b68fd that I believe might fix this issue as it fixes various issues pertaining to chunks not properly unloading.

**Comment by Dynamiczbee** [comment]
Thanks chief, sorry for the late upload of the log file.

**Comment by pupnewfster** [comment]
I believe 10.0.2 (which is now released) should fix this issue. If it does not, feel free to comment (and provide a new latest log) and I will re-open the issue.
