### ISSUE TITLE
1.16.1 metallurgic infuser

### ISSUE THREAD

**Issue by luisragnorak** [mekanism/Mekanism#6328]
i recently downloaded your mod and was trying to make a metallurgic infuser when i put the recipe in nothing happened then i checked the recipe over several times

**Comment by pupnewfster** [comment]
I highly recommend using something like JEI, but with the lack of information you have given/what you "believe" the recipe is there is not much we can do to help you figure out why you are unable to craft it.

**Comment by luisragnorak** [comment]
I am using JEI but when i insert the metallurgic infuser recipe the output
product is blank as is there is no recipe.

**Comment by pupnewfster** [comment]
I am not able to reproduce this, I highly recommend sending a picture of the crafting grid with the recipe in it where it won't show you the output.

**Comment by luisragnorak** [comment]
After taking these screenshots I took all the mods out of my mods folder
and put the mods back in. After this i made a new world, on that world the
crafting recipe worked, so i attempted the recipe again on the world in the
screenshots but the recipe didn't work.

**Comment by pupnewfster** [comment]
You are mentioning screenshots but I am not able to see any. I am not sure if this is due to github's reply via email system just not including images or if you didn't upload any.

**Comment by luisragnorak** [comment]
Just forget about this i found an additional mod that gets rid of the
Recipe book and since then i can craft every item in the mekanism mod
