### ISSUE TITLE
Cannot make polonium

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#6330]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

Forge: 32.0.63
Mekanism: 10.0.1

The solar neutron activator does not accept nuclear waste and it is impossible to make polonium

**Comment by pupnewfster** [comment]
The solar neutron activator only accepts inputs from underneath, are you attempting to input there or through the port on the front?

**Comment by term2112** [comment]
Yes, didnt realize that, thank you
