### ISSUE TITLE
not compatible mods

### ISSUE THREAD

**Issue by Alifu8** [mekanism/Mekanism#6336]
Hello
I will try to make clear
because i am french with translation
so here's a little problem a mods can't work
so you can adjust
and here it is link

[https://hatebin.com/rclbqmabrq](https://hatebin.com/rclbqmabrq)

![2020-07-15 (10)](https://user-images.githubusercontent.com/68350455/87587159-078fe200-c6e2-11ea-8692-83195e89551e.png)

**Comment by C0rn3j** [comment]
You should figure out which exact mod conflicts, so the developers can reproduce and fix it.
