### ISSUE TITLE
Solar recharging unit - does it really charge the suit? | suggestions on charge pad and a new tool

### ISSUE THREAD

**Issue by Fidulus** [mekanism/Mekanism#6337]
I got a question about the "solar recharging unit" you can put into the "mekasuit helmet".
I just love the concept and possibilitis of all those items, but the "solar recharging unit" doesn't seem to work.
I also installed the "Charge distribution unit" into the mekasuit chest piece.

But when i am out in the sun i still lose power regardless if i am turning the "solar recharging unit" on or off.

Do i just lose less energy or is this unit not functional at the moment?

ps: also two suggestions which would be awesome in my opionon: A gun or laser beam like weapon for ranged combat. The bow seems kinda... archaic.

And would it be possible to change the chargepads, so they don't got the vertical slap on the side? They are charged with power from below anyway and it would be much easier to create a grid to walk on. :-)
Thank you for this amazing mod.
I would say this is the single best mod i have ever played in minecraft.

Please keep up working on those awesome ideas and features.

**Comment by ToMe25** [comment]
The Solar Recharging Unit does work, but some things in the suit use up alot of energy, it might not be strong enough to balance that out.
You can also add multiple Solar Recharging Units to the Helmet.
One of the main things that seems to just use alot of power(or that was a bug when testing) is the inventory charging mode of the Charge Distribution Unit, while that is enabled it seems to use more energy then the Solar Recharging Unit produces, just for being enabled.

**Comment by Fidulus** [comment]
Thank you so much for that information. I already got the maximum of solar charging units installed.
i will try to disable the inventory charging mode and see if that helps. :)

**Comment by ToMe25** [comment]
I think i now know what the problem with the inventory charging is, and i will try to fix it.

**Comment by ToMe25** [comment]
I made a PR to fix that now, its #6339.

**Comment by Fidulus** [comment]
Thats amazing. I am so happy to have been able to be of any assistance at all :-)
Is it possible for me to get your fixed version in any way?
I am not very keen with java and how to change out lines of code.

**Comment by ToMe25** [comment]
technically yes, it is, but if you don't know much about gradle & git you should atleast wait until its merged, which is probably today or tomorrow, and even then it might be better to wait for an official release then building it yourself.

**Comment by Fidulus** [comment]
Thank you very much. I'll just be patient :-)
Have a great day.

**Comment by pupnewfster** [comment]
Now that that is merged going to mark this fixed in dev (once it is closed 10.0.2 will be released, probably will end up happening a bit later today). In regards to the enhancement aspects of this, I believe there is another issue somewhere tracking a requested "laser" styled ranged weapon, and in regards to the chargepad part I don't think that is likely to happen as the "primary" way of charging them is meant to be from the back, the fact they also support energy from the bottom is more just a quality of life thing to not force people to have to use the energy port that is behind them.
