### ISSUE TITLE
Mekanism V1.16.1-10.0.1.424 ctd with forge V32.0.67

### ISSUE THREAD

**Issue by Krethyan** [mekanism/Mekanism#6340]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.fresh / current up to date forge install
2.launch and create new world
3. CTD

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.67
**Mekanism:** 10.0.1.424
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2020-07-16_19.18.08-server.txt](https://github.com/mekanism/Mekanism/files/4930610/crash-2020-07-16_19.18.08-server.txt)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by thiakil** [comment]
Fixed by 113691555962d6350c86f72ab7cb657916efc7a7 - downgrade forge if possible in the meantime

**Comment by Krethyan** [comment]
Forge 32.0.66 is working with a clean install

**Comment by pupnewfster** [comment]
10.0.2 (which is now released and on curseforge) fixes compatibility with forge 32.0.67.
