### ISSUE TITLE
[1.12.2] Laser amplifier redstone output not working

### ISSUE THREAD

**Issue by obnys** [mekanism/Mekanism#6343]
Greetings =)

I can't get the Laser amplifier to emit a redstone signal either for entitiy detection nor for energy content. I tried different items like redstone, redstone lamp etc. on every side of the amplifier in different charging states, as well with different min- and max-values.

I'm using
Mekanism-1.12.2-9.8.3.390
MekanismGenerators-1.12.2-9.8.3.390
Forge 14.23.5.2854

Any help would be appreciated! =)

**Comment by pupnewfster** [comment]
I am not able to reproduce this in 1.16, not sure if it was bugged in 1.12 or not, but one thing that may be worth trying is it is potentially possible that it only properly updated in 1.12 either with a comparator or maybe a block update (in which case it probably is more or less just broken for 1.12 unfortunately).
