### ISSUE TITLE
Suggestion Add examples to wiki

### ISSUE THREAD

**Issue by edotenseilove** [mekanism/Mekanism#6344]
Hello,

I was wondering if you could add an actual examples on how to create a new recipes for machines and other stuff on wiki. For example an actual set up of reinforced alloy recipe or some crushing recipe and so so that is easier to understand the basic of creating those recipes.

Back than it was easy all i had to do was just download crafttweaker and modtweaker than dump all recipes and i would know how to use it as an exemple for creating new recipes but since it is no longer possible i was thinking if you could add a few real recipes using actual items as examples so that even a beginner could understand the basics of creating those recipes and deduce the other recipes as well.

**Comment by ToMe25** [comment]
Do you even know how up to date the wiki is, lol

**Comment by edotenseilove** [comment]
I know it is very well made but for someone like me who is a begginner at creating new recipes is quite hard to create new ones. I know that it took effort to create all this stuff and i know that with new version and new stuff that has been added by this mod comes a lot of work to do to fix and to add a new stuff and i really admire the work and the new splendid stuff that has been added so far. I did not mean to upset or to angry anyone i just ment it as possible upgrage because I could not find examples anywhere.

**Comment by ToMe25** [comment]
My comment above was a joke :)
On the [wiki](https://wiki.aidancbrady.com/wiki/Mekanism) if that is the one you mean, my favorite quote to show how up to date it is is this:
```
NOTICE: Wiki is in transition from 8.0 to 9.0. Most information is still accurate, but there are some changes to recipes.
There are also new features and improvements that may not yet have been documented. 
```
Note that the current version is 10.0.2.

**Comment by edotenseilove** [comment]
I see sorry for misunderstanding.

**Comment by pupnewfster** [comment]
I already updated the "wiki" that shows recipe syntax to V10. https://github.com/mekanism/Mekanism/wiki/Recipe-Type-JSON-Syntax For how to use Data Packs in general I am sure there are tons of vanilla tutorials, and for example recipes you can just look at any of our recipes as all the recipes we add are done using json.
