### ISSUE TITLE
Crash when viewing custom PRC recipe(s) in JEI

### ISSUE THREAD

**Issue by Jokercortex** [mekanism/Mekanism#6347]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When attempting to view a pair of custom recipes that use EnderIO's silicon item, Water Vapor, and PneumaticCraft's Kerosene (or Lava) to produce Nether Quartz in JEI, my game crashes.  The custom recipes I had defined in a Chemical Injection chamber beforehand worked fine.  

#### Steps to reproduce:
1. Create an instance with CraftTweaker2-1.12-4.1.20.574, PneumaticCraft:Repressurized-1.12.2-0.11.15-398, EnderCore and Ender IO versions 1.12.2-0.5.76 and 1.12.2-5.2.59 respectively, JEI 1.12.2-4.15.0.296, and Mekanism with Generators and Tools modules.
2. Implement the following scripting: 
import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.item.IItemStack;
mods.mekanism.reaction.addRecipe(<enderio:item_material:5>, <liquid:lava>*500, <gas:water>*500, <minecraft:quartz>, <gas:water>*0, 4000, 200);
mods.mekanism.reaction.addRecipe(<enderio:item_material:5>, <liquid:kerosene>*144, <gas:water>*500, <minecraft:quartz>*3, <gas:water>*0, 4000, 200);
3. Launch the game and attempt to view recipes for Nether Quartz using the PRC in JEI.

#### Version (make sure you are on the latest version before reporting):
Forge: 14.23.5.2854
Mekanism: 1.12.2-9.8.3.390 
Crash log:
https://pastebin.com/kCR7ZTYx

**Comment by pupnewfster** [comment]
My best guess is it is due to the `<gas:water>*0` we are no longer developing 1.12, but if memory serves for the PRC to make it only have one output (be it item or gas), you use `null` not a zero stack size one.

**Comment by Jokercortex** [comment]
I'll see if that does it.  Thanks for the timely response.
