### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by edotenseilove** [mekanism/Mekanism#6349]
Hello I am trying to figure out what I am doing wrong in this recipe. Could you help me please? I think that it is something in infusion input but i can figure it out.

 {
  "type": "mekanism:metallurgic_infusing",
  "itemInput": 
 {
  "ingredient":
		{
		"item": "minecraft:stone"
		},
  "amount":	1
},
  
  "infusionInput": 
  {
  "infuse_type": "mekanism:redstone",
  "amount": 10.00
},
  "output":
  {
  "item": "minecraft:apple",
  "count": 5
  }
}

**Comment by pupnewfster** [comment]
I believe the infusion input's amount is a whole number (and no commas either). so it would be `10` not `10.00`

**Comment by edotenseilove** [comment]
I tried still not working but thanks

**Comment by edotenseilove** [comment]
I believe that it would be some stupid typo or different name but i have not found it.

**Comment by edotenseilove** [comment]
oh I found it it was a typo but in a different part of the document and then i have changed the numbers and it works now. thanks a lot
