### ISSUE TITLE
V10 for 1.12.2

### ISSUE THREAD

**Issue by CactusCool** [mekanism/Mekanism#6350]
Will mekanisim v10 ever be avilible to play on 1.12.2 so it can be Incorporated into other mod-packs that run on 1.12.2.

**Comment by pupnewfster** [comment]
No, but it is MIT licensed so you are more than free to spend the 2,000+ hours backporting itself if you really want it.

**Comment by ToMe25** [comment]
Feel free to backport it yourself, but noone of the mod team will.

**Comment by CactusCool** [comment]
Well that sucks I guess I better start learning java.
