### ISSUE TITLE
SPS core renders multiple times per sps if multiple of them are seen

### ISSUE THREAD

**Issue by ToMe25** [mekanism/Mekanism#6355]
#### Issue description:
While there are multiple working sps rendered each one has as many rendered lightning + core groups as there are sps rendered.
![2020-07-19_20 25 21](https://user-images.githubusercontent.com/38815969/87882655-d37a3100-ca01-11ea-8983-305a25d686a7.png)

#### Steps to reproduce:
1. Build a sps
2. Make it run
3. Do both again
4. look one as many directions as possible while keeping the other one on the screen

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.67
**Mekanism:** d77fd2d
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
![2020-07-19_16 25 28](https://user-images.githubusercontent.com/1203288/87884551-e3cbe500-c9dc-11ea-8c45-717a4c6fc511.png)
Can confirm it happens, and seems it occurs even if they are not both active.
