### ISSUE TITLE
Forge compatibility lost after 32.0.66 (method moved)

### ISSUE THREAD

**Issue by KylePoe** [mekanism/Mekanism#6357]
#### Issue description:
Mekanism calls `net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()` when loading a world. This method appears to have been removed as of forge 32.0.66, as shown in [this commit](net.minecraftforge.fml.event.server.FMLServerStartingEvent.getCommandDispatcher()). Therelevant function appears to have been moved to src/main/java/net/minecraftforge/event/RegisterCommandsEvent.java .

#### Steps to reproduce:
1. Install forge 32.0.62, 32.0.63, 32.0.64, 32.0.65, or 32.0.66 and observe that everything is fine
2. Install forge 32.0.67 or later, observe a `java.lang.NoSuchMethodError` is raised

#### Version (make sure you are on the latest version before reporting):
**Forge: 32.0.67 and later** 
**Mekanism: 10** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[pastebin](https://pastebin.com/skaQ9vsR)

**Comment by pupnewfster** [comment]
I am going to go off the assumption that you are on 10.0.0 (or maybe 10.0.1)... given all you bothered putting for the version is `10`. We fixed compatibility in 10.0.2

**Comment by KylePoe** [comment]
Sorry about that, I'm new to open source stuff. Just wanted to help out.

**Comment by pupnewfster** [comment]
That is fine, and it is useful to report bugs like that, though it is useful to double check if you are on the latest version of a mod and also to include the full version you were using. In any case, updating to 10.0.2 should fix the issue for you.
