### ISSUE TITLE
pressurized tube and chemical tanks capacitys

### ISSUE THREAD

**Issue by shotgun12** [mekanism/Mekanism#6358]
I am currently on mekanism 1.16.1 and forge version 32.0.70 I am having a problem with holding gasses. When ever I take any machine that uses or creates a gas(electrolytic separator, chemical infuser, etc..) and I try to store the gasses produced by them in a chemical tank they work just fine the problem is when i hook a pressurized tube to pipe it out of the chemical tank somewhere else the chemical tank starts to show that I lose all of my gas but in reality its not registering that i still have 95% of all the gas. This is seen when I hook up the hydrogen side of the electrolytic separator to a gas burning generator off of a chemical tank. With this problem it causes the machines to run even though the amount of gas stored is at its max causing more power usage and more resourses to be use. This same effect is seen when converting sulfur dioxide to sulfur trioxide.

steps to reproduce
1. set up electrolytic separator with water and power with two chemical tanks.
2. set to dumping excess on oxygen side and upgrade the electrolytic separator with 8 speed upgrades
3. take the hydrogen chemical tank and pipe it into a gas burning generator
4. hook gas burning generator up to a energy cube or keep it disconnected from any power bank(happens on both)
5. check chemical tank to see that it is empty or losing gas at rapid amount

**Comment by pupnewfster** [comment]
Are you sure it isn't just filling the buffer of the pressurized tubes? Right click a pressurized tube with a network reader to view content information.

**Comment by shotgun12** [comment]
I'm sorry for wasting your time i played previous versions and never had this before so I didn't know what was the problem, i guess the buffers have been increased or i wasn't playing right before. Thank you for your quick response and keep up the amazing work.

**Comment by shotgun12** [comment]
The Buffers were filling just to answer the question though.

**Comment by pupnewfster** [comment]
We did increase the size of the buffers in V10 so ya that is probably it
