### ISSUE TITLE
Cannot use Logistical Transporters to insert infusion types into Infusers

### ISSUE THREAD

**Issue by DStrand1** [mekanism/Mekanism#6360]
Testing this on the Advanced Infusing Factory. I attempted to insert enriched redstone into the factory, and set both items and infuse types to the left side of the machine. Neither way could I get the enriched redstone into the machine.

Apologies if this is intended behavior, but I figured if not, it was worth bringing attention to it.

**Comment by DStrand1** [comment]
Using:
Forge 32.0.70
Mekanism 10.0.2

**Comment by pupnewfster** [comment]
I believe items have a configuration type called "extra" which is where you insert infusion items from.
