### ISSUE TITLE
Inventory occasionally gets stuck when inserting into Storage Drawers controller

### ISSUE THREAD

**Issue by DStrand1** [mekanism/Mekanism#6361]
#### Issue description:
Exporting items from the Digital Miner with Logistical Transporters into a Storage Drawers Drawer Controller. Occasionally, despite having a drawer assigned to the item and having space for the item, the item will get stuck in the Miner's inventory and not get exported. Adding more empty drawers will fix the issue, even if they are not for the original item. I.e., coal is stuck, I add a drawer for Iron, and now the coal is unstuck and will be transferred properly.

#### Version
**Forge:** 32.0.70
**Mekanism:** 10.0.2

**Comment by pupnewfster** [comment]
https://github.com/jaquadro/StorageDrawers/issues/811
