### ISSUE TITLE
Free Runners aren't doing step assist but do prevent fall damage? 1.16

### ISSUE THREAD

**Issue by chardo440** [mekanism/Mekanism#6366]
Issue description:
I have the free runners fully charged in regular mode and they don't step assist. I've tried control and it just doesn't go up a block. It does, however, stop fall damage from the jetpack.

Steps to reproduce:
Fully charged free runners set to regular running into cobblestone grass any block I've tried really.
Version: 1.16.1
Forge: 1.16.1-forge-32.0.66
Mekanism-1.16.1-10.0.1.424

**Comment by pupnewfster** [comment]
First off what version of Mekanism are you using in 1.16, and secondly what blocks are you trying to walk up.

**Comment by chardo440** [comment]
> First off what version of Mekanism are you using in 1.16, and secondly what blocks are you trying to walk up, and what block are you walking from being on top of.

Fixed the description. I was just going from grass to grass or grass to cobblestone and it's not stepping up. I've tried the chest controls to turn the jet pack off I've taken the jet pack off and I still can't get the free runners to step assist.

**Comment by pupnewfster** [comment]
Are you able to reproduce it with Mekanism 10.0.2? I adjusted how we apply the auto step in 10.0.2.
