### ISSUE TITLE
Personal chest naming does not save when placed and picked-up

### ISSUE THREAD

**Issue by Avlyssna** [mekanism/Mekanism#6371]
#### Issue description:
When a personal chest is named from an anvil and placed, once it is picked up, the item loses its custom name. This problem does not occur when using normal Minecraft chests, for reference.

#### Steps to reproduce:
1. Name a personal chest using an anvil.
2. Place the personal chest.
3. Pick up the personal chest.
4. The name should be reverted to "Personal chest".

#### Version: 1.16.1
**Forge: 1.16.1-forge-32.0.69** 
**Mekanism: Mekanism-1.16.1-10.0.2.425**

**Comment by pupnewfster** [comment]
I think I am going to end up bumping this (as it is really closer to a feature request than a bug so will take a bit more free time than I have currently) to 10.1.0.

**Comment by halvors** [comment]
Seems to affect energy cubes as well, and possibly other blocks.

**Comment by mijofa** [comment]
Naming Personal Chests also doesn't affect the name in the UI when looking inside the chest. Not a big deal, but normal chests & barrels do, so I think the Personal Chest probably should too.
