### ISSUE TITLE
Fission Reactor Ports not able to be connected to power.

### ISSUE THREAD

**Issue by TGibson94** [mekanism/Mekanism#6372]
#### Issue description:
It seems that fission Reactor Ports will not connect to power under any configuration. The description makes it seems like this should be a possibility. 

#### Steps to reproduce:
1. Build a fission reactor
2. Add a reactor port
3. Place universal power cable next to port
4. Change config of port
5. No configuration allows for power output

Mekanism v10

**Comment by ASDFGHT0** [comment]
Fission reactors do not produce power directly. They instead produce steam from the supplied water, and this steam must go through a turbine to produce power.

**Comment by term2112** [comment]
Another tip, use saturating condensers in the turbine to recycle the steam back into water, the fission reactor will suck up a lot of water as coolant.

**Comment by term2112** [comment]
I am also not sure about the advantages of using sodium instead of water as coolant and how it is converted into energy, is the output some kind of sodium vapor that can be fed into the turbine or gas generator?

**Comment by aidancbrady** [comment]
Sodium can more efficiently absorb heat from Fission Reactors. This allows for you to run your reactor hotter without running the risk of a meltdown.

**Comment by aidancbrady** [comment]
Reopening this, as I now see this is an issue with the block's description.
