### ISSUE TITLE
What exactly is mekanism defense

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#6377]
I have noticed a package called mekanism defense in the downloads folder but noticed that it doesn't really do anything. Is this supposed to contain the forcefield?

**Comment by term2112** [comment]
Think it has something to do with #6322 too

**Comment by pupnewfster** [comment]
#6322 Mekanism defense currently is a dummy/empty jar and contains no content as it has been bumped to V11. It will eventually contain forcefields among other features.
