### ISSUE TITLE
[1.16] Losing nuclear waste gas

### ISSUE THREAD

**Issue by Taurvi** [mekanism/Mekanism#6378]
This is kind of a weird one, if I pipe nuclear waste gas anywhere that is not a radioactive waste barrel, it just disappears (perhaps this is by design?). I've tried piping it to an entangloporter and it just poofed. I also had issues extracting it from the fission reactor where it also just randomly poofed

**Comment by Taurvi** [comment]
Currently using v.1.16.1-10.0.2.425 across the board

**Comment by pupnewfster** [comment]
Tested this and it is properly not accepted by things like the quantum entangloporter (and also is not voiding it). My best guess is that it is filling up the pressurized tubes (try using a network reader on the tubes to view the stored contents)
