### ISSUE TITLE
Maybe don't give personal chests the "chest" tag by default

### ISSUE THREAD

**Issue by SeriousCreeper** [mekanism/Mekanism#6379]
**Describe the the feature you'd like**
Currently personal chests use the chest tag, which means when you craft something that requires a chest (and uses tags), it can use the personal chest. 

I just accidentally lost the one i've been carrying around for a while due to a recipe requiring a chest (and not paying enough attention), and of course lost all stored items with it. 

It would be really useful if those wouldn't be able to be used in recipes by default.

**Comment by pupnewfster** [comment]
This isn't going to happen given they *are* a chest, and if something just wants a chest it is valid. The more likely solution is you want the recipes that use it to be replaced with `chest/wooden` or whatever the chest tag is specifically for wood chests.
