### ISSUE TITLE
Electrolytic Breathing Unit not working when sprinting

### ISSUE THREAD

**Issue by Joshman106** [mekanism/Mekanism#6380]
When Using the MekaSuit helmet with the Electrolytic Breathing Unit it will work if stood up fully under water, however when sprinting it will stop functioning when you are too short,

**Comment by pupnewfster** [comment]
Going to add onto this just so I remember, but when looking into this it should also be made to work (at a reduced rate) while it is raining, which was initially intended of the module but I don't think ever happened.
