### ISSUE TITLE
Steam from boiler to turbine issue....

### ISSUE THREAD

**Issue by Zeekata** [mekanism/Mekanism#6384]
Issue description: Tried both mechanical pipes and pressurized tube to transfer steam from the boiler to the turbine, cant seem to get the turbine to work/ intake steam. Also attempted to connect creative steam tank to the turbine, still doesn't work.  
![turbine boiler build](https://user-images.githubusercontent.com/68709360/88330491-b5098380-cce8-11ea-89da-1148fb50a870.png)

Steps to reproduce:
1.build turbine and boiler
2. attempt to connect boiler valve and turbine turbine valve via pressurized tubes or mechanical pipes.
3.make sure everything is powered i.e. pump

 Version:
Forge: 32.0.70
Mekanism: 10.0.3.426

**Comment by minecrafterseppe** [comment]
put the valve on output mode on the boiler

**Comment by Zeekata** [comment]
that did it. couldn't find that information anywhere for some reason. watched multiple how to videos and everything. Thank you.
