### ISSUE TITLE
Steam turbine rotor wont stack 

### ISSUE THREAD

**Issue by PHARAOHGAMING23** [mekanism/Mekanism#6385]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

I literally cant place any of the rotors on top of each other. 
I posted it on Reddit as well. https://www.reddit.com/r/ModdedMinecraft/comments/hwbsak/mekanism_steam_turbine_rotor_not_working/
#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-14.23.5.2854
**Mekanism:** 1.12.2
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Pretty sure you just need to sneak to be able to place them higher.
