### ISSUE TITLE
[1.15.2] Forge tag for lapis dust

### ISSUE THREAD

**Issue by TheUntamed** [mekanism/Mekanism#6386]
Lapis Lazuli dust assed by this mod has the tag _forge:dusts/lapis_lazuli_ while all other lapis items have a tag with only lapis and without lazuli. E.g. _forge:gems/lapis_ or _forge:storage_blocks/lapis_
That's not an emergency but it broke my algorithm and took me a while to find out why. Would be neat if it could be adjusted.

Mekanism 9.10.9.422

**Comment by pupnewfster** [comment]
This won't be fixed in 1.15 as we are no longer developing for that version, but if the standard for lapis is `lapis` and not `lapis_lazuli` then I will look into changing what we add it to for Mekanism 10.0.4. Not sure yet if I will just switch over or end up having us just add it to both.
