### ISSUE TITLE
Hydraulic Propulsion Unit not increasing jump height

### ISSUE THREAD

**Issue by EmilyWeston** [mekanism/Mekanism#6387]

**Comment by EmilyWeston** [comment]
Accidentally pressed enter without typing anything - on Mekanism 10.0.2.425 and the Hydraulic Propulsion Units I have on my Meka-Suit Boots aren't increasing jump height at all

**Comment by pupnewfster** [comment]
Are you pressing the keybind that activates it? I believe it is bound to control by default.
