### ISSUE TITLE
Can't get Steam Gas from Boiler Multistructure

### ISSUE THREAD

**Issue by Karunkh** [mekanism/Mekanism#6388]
i got the newest Version of Mekanism for MC 1.16.1 and the Boiler works just fine except you can't extract the produced Steam.

**Comment by Robball14** [comment]
can you send a screenshot of the structure?

**Comment by Jer0me27** [comment]
Hey, 
I'm playing with Karunkh on the same Server and could send some Screenshots later.
But we can tell you, that there is nothing wrong with the boiler itself. It produces a lot of steam, but we can't get it out of there.
we have a boiler valve on steam catch layer and tried to use it as output to drive our turbine. 
We tried both pipes and tubes to move the steam out, but it won't work :/

**Comment by pupnewfster** [comment]
I think the confusion may be that the boiler valve in V10 now has multiple modes so you need to set it to the proper output mode with a configurator.

**Comment by Karunkh** [comment]
Thank You very much!
 We were confused^^
Now everything is fine ;)

Honor Brother!
