### ISSUE TITLE
Reproducible Crash Rendering Items

### ISSUE THREAD

**Issue by FUZEYBOI** [mekanism/Mekanism#6389]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Game crashes while trying to render the 'QIO' items in Mekanism.

#### Steps to reproduce:
1. New world (Creative).
2. Switch to Mekanism Creative tab or search @Mekanism in JEI.
3. Sometimes crash? (Tested without other mods as well, still occurs).

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.1 (32.0.75)
**Mekanism:** 1.16.1 (10.0.3.426)
**Other relevant version:**

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[pastebin](https://pastebin.com/LawRkZXv)

**Comment by pupnewfster** [comment]
Can you reproduce this without optifine?

**Comment by FUZEYBOI** [comment]
Wow that was instant, I'll test now!

**Comment by FUZEYBOI** [comment]
Ok, can't seem to be able to reproduce after removing Optifine.

**Comment by pupnewfster** [comment]
Going to go ahead and say this is probably optifine's fault then.
