### ISSUE TITLE
Dynamic tanks computercraft integration V1.12.2-9.8.3.390 modpack:The 1.12.2 pack

### ISSUE THREAD

**Issue by AriaKerrigan** [mekanism/Mekanism#6392]
Hi

i have looked everywhere i can think of to try and find this out, does Dynamic tanks have computer-craft integration?
if its already integrated where do it finds its commands?
i am trying to write a monitoring program to monitor my dynamic tanks fluid levels.

thanks 
Aria

**Comment by pupnewfster** [comment]
It doesn't seem to have integration, but you should be able to put a comparator on a valve and it will output a signal based on how much is stored.
