### ISSUE TITLE
Nether Gold Ore cannot be processed in the chemical dissolution chamber

### ISSUE THREAD

**Issue by TheAdversary808** [mekanism/Mekanism#6395]
Gilded Blackstone and Nether Gold Ore cannot be processed to the max potential of normal gold ore. I don't know if this is a bug or an intended feature, but I wanted to post this just to double-check.  

Forge-32.0.75
Mekanism-1.16.1-10.0.5.428

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism/issues/6315#issuecomment-657564339
