### ISSUE TITLE
Digital Miner deletes items when auto-pull is enabled

### ISSUE THREAD

**Issue by mbfrog** [mekanism/Mekanism#6400]
1. Place a digital miner with some itemstack filter and require replace enabled (use netherack as a replacement block for example)
2. Place a any container containing stacks of the replacement block (netherack) on top of the digital miner
3. Turn on auto-pull
4. Start the digital miner

**Forge:** 32.0.67
**Mekanism:** 10.0.0.3

**Comment by pupnewfster** [comment]
Someone reported this at some point and I was unable to reproduce... are you sure it just isn't making them "disappear" because it is, well you know... placing them in the world because of require replace being enabled?

**Comment by mbfrog** [comment]
Tested again: in order to reproduce, the filter must match minable blocks in the configured area. In a new creative world (select the "redstone ready" preset, the top layers will be sandstone):

Radius: 5, Min: 55, Max 60, filter on sandstone, replace with cobblestone. Then a chest full of cobblestone on top. It should show 121 items to mine once started. Then the miner will pull the items (at a rate that "seems" to be the mining rate), but not actually mine or replace anything, the items pulled from the chest are just gone.

**Comment by mbfrog** [comment]
Forgot to mention: Java 11.0.7 64 bits (openjdk/linux), installed mods:

- CTM 1.1.0.1
- FastLeafDecay v23
- gravestone 1.0.3
- JEI 7.0.0.6
- Xaero's Minimap 20.17.0
- Xaero's WorldMap 1.7.4
