### ISSUE TITLE
I cannot pick up some items from qio while holding shift.

### ISSUE THREAD

**Issue by mllightitup** [mekanism/Mekanism#6401]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I cannot pick up some items from qio while holding shift. For example charged resistive heater
Maybe this is my personal problem, but I tried it on different versions of forge and mekanism with other mods and without.

charged resistive heater = CRH

And one more addition: I can pick up CRH without holding shift, but as soon as I try to pick up CRH with shift held down, after that I can not pick up the CRH at all and I need to re-enter qio or change height

**This does not happen with the new resistive heater. Only with that which contains energy**

#### Steps to reproduce:
1. Create world
2. Take resistive heater
3. Сharge it from creative energy cube
2. Create qio
3. Put this resistive heater and other items in qio
4. Hold shift and click on resistive heater and other items

Video: https://youtu.be/Lp6qmE4ZAFo
For each item in the video I click with held shift

#### Version (make sure you are on the latest version before reporting): 1.16.1
**Forge:** 32.0.96
**Mekanism:** 10.0.6.429
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I feel like this may have something to do with another mod that is installed as I am not able to reproduce this. Also is this on a server or in single player?

**Comment by mllightitup** [comment]
> I feel like this may have something to do with another mod that is installed as I am not able to reproduce this. Also is this on a server or in single player?

Can you put this topic on hold? I don't have a chance to double-check everything in the next two days. From what I can answer, it was in single-player. Installed mods: hwyla, optifine, just enough items . And maybe mouse tweaks

**Comment by pupnewfster** [comment]
Ok, I will put it on hold for now but my best guess then is maybe mouse tweaks is doing something weird

**Comment by mllightitup** [comment]
> Ok, I will put it on hold for now but my best guess then is maybe mouse tweaks is doing something weird
I removed all unnecessary mods, recreated the world and it still happens. I can't understand what could be wrong

**Comment by mllightitup** [comment]
Mods folder:
![image_2020-08-03_090428](https://user-images.githubusercontent.com/43480503/89150900-55bd3600-d568-11ea-8cc9-f654bdcf02f6.png)

**Comment by mllightitup** [comment]
Maybe I should write about it to the mouse tweaks developer if it's not a mekanism problem?

**Comment by pupnewfster** [comment]
There is a slight chance it is on our end but I find it much more likely that it is on their side so I think it is worth writing to them about it. If it turns out that we are doing something weird they can comment here and I will reopen this issue.
