### ISSUE TITLE
QIO Dupe/Item Loss

### ISSUE THREAD

**Issue by watlok** [mekanism/Mekanism#6404]
#### Issue description:
Moving drives around in QIO overwrites drive contents of one drive with that of another

#### Steps to reproduce:

1. Place two drives into QIO
2. Pick one up on to cursor
3. Click on the other drive a few times
4. Place held drive back into QIO (maybe unneeded)
5. The contents of one drive will completely overwrite the other. 

If you place a drive into slot 1 and another into slot 2 then pick up slot 1 and repeatedly click on drive 2 it will overwrite one of the drives with the contents of the other.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  forge-1.16.1-32.0.75
**Mekanism:** Mekanism-1.16.1-10.0.3.426
**Other relevant version:** Running in SMP, did not test single player

Did not see an open issue reporting this. If it's fixed in dev then sorry! It was just really awkward losing all of the items in my supermassive drive, and this is something that's pretty easy to abuse after figuring it out.

**Comment by nathanee** [comment]
I have run into this issue on the most current version and have been able to reproduce with multiple drive sizes. 

**Forge:** 35.1.11
**Mekanism:** Mekanism-1.16.4-10.0.18.445.jar
**Other relevant version:** Running in SMP, did not test single player
