### ISSUE TITLE
Isotropic centrifuge internal tank does not fill with gas and continuously consumes input

### ISSUE THREAD

**Issue by soapiestwaffles** [mekanism/Mekanism#6405]
#### Issue description:
Isotropic centrifuge will not fill will gas when there is a pipe connected to the output which causes it to constantly consume uranium hexaflourite (or whatever else you may be using -- using it with the Uranium is the only time I have used a centrifuge) 

[See video of issue here](https://youtu.be/XgIx8zjSo6M)

#### Steps to reproduce:
1. Place centrifuge, power
2. Have incoming uranium hexaflourite
3. centrifuge's internal tank will start to fill
4. connect an output pipe
5. internal tank will be stuck at 1mB and continue to consume uranium

#### Version:
* **Forge:** 1.16.1-32.0.88
* **Mekanism:** 10.0.6.429

__THIS IS MULTIPLAYER - HAVE NOT TRIED SINGLE PLAYER)__

**Comment by pupnewfster** [comment]
From looking at the video I don't believe this is a bug? I think what is happening is the pressurized tube's buffer is just filling (right click it with a network reader to see stored contents)

**Comment by soapiestwaffles** [comment]
I had it originally with a basic tank there and everything had been running long enough for the basic tank to be full for a long time. I will hook a pipe back up and watch it for a while with the network reader!

**Comment by soapiestwaffles** [comment]
You're correct, my apologies! I didn't realize each segment had such a large buffer! I retract my issue 😅
