### ISSUE TITLE
Digital Miner chunkloading large amounts of chunks

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#6406]
#### Issue description:
The digital miner sometimes(?) chunkloads very large areas of land. 
Red areas are fully loaded.
![image](https://user-images.githubusercontent.com/4283717/89045144-50cf6b00-d34b-11ea-805c-49790f92f83d.png)

After removing the anchor upgrade: 
![image](https://user-images.githubusercontent.com/4283717/89045195-69d81c00-d34b-11ea-9bcd-06a87f5da186.png)

Digiminer seems to have run and finished its task. It has been reset to check the configuration: 
![image](https://user-images.githubusercontent.com/4283717/89045351-ad328a80-d34b-11ea-9eb5-539dd93496b0.png)

Reinserting the anchor upgrade causes the chunks to be loaded again. 
#### Steps to reproduce:
1. No idea :/

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.75
**Mekanism:** Mekanism-1.16.1-10.0.3.426.jar
**Other relevant version:**

**Comment by thiakil** [comment]
Are all the red areas supposedly Mekanism?

**Comment by pupnewfster** [comment]
Ah, seems like a copy paste error to me from when I was inlining some code: https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/common/tile/machine/TileEntityDigitalMiner.java#L901
