### ISSUE TITLE
Mechanical pipe causes game crash and world is unable to load without crashing

### ISSUE THREAD

**Issue by NiamiTV** [mekanism/Mekanism#6408]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Connecting a mechanical pipe to an AE2 fluid interface causes an issue that causes the world to not load and crash on startup

#### Steps to reproduce:
1. Place AE2 fluid interface block
2. Place mechanical pipe next to the interface block
3. Expect game to immediatelly crash and the world is now unable to load

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2-31.2.23
**Mekanism:** 1.15.2-9.10.9.422
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/wMvtDVLd

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Nothing we can do about this AE2 is returning null for a capability https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/fluids/helper/DualityFluidInterface.java#L213 when they should be returning an empty lazy optional instead. getCapability is nonnull in 1.14+
