### ISSUE TITLE
Possible Fabric port ?

### ISSUE THREAD

**Issue by FluffyDiscord** [mekanism/Mekanism#6409]
**Describe the the feature you'd like**
Would it be possible to make Fabric version of this mod ?

**Describe alternatives you've considered**
None

**Additional context**
While Forge has "all the bells and whistles", it's quite heavy to run and we do not really have any way to boost performance. FastCraft is dead. Optifine tends to break mods and the newer MC is, the less performance boost it offers, while more options are not working or broken. Other performance mods do so little, that it's not worth even mentioning.

Now there's a Fabric and recent performance mods, such as Sodium, which basically does magic (not really) and does what Mojang seems to refuse to do.

But the Fabric is still new and we do not have many larger or more "complicated" mods to play with - so here comes an idea (pretty hard I would say to pull of, but will probably be worth the time)

Please consider this for more than just a minute.

**Comment by pupnewfster** [comment]
We have no plans on porting Mekanism to fabric. Our stance when people ask has been and still is, that Mekanism is MIT licensed, if someone wants to spend the time to port it to fabric they are more than free to, we will not be spending the time doing so.
