### ISSUE TITLE
Reactor Logic Adapter and OpenComputers

### ISSUE THREAD

**Issue by Craftler** [mekanism/Mekanism#6410]
Hello,
I have a problem using the Reactor Logic Controller with OpenComputers. As written in the wiki (https://wiki.aidancbrady.com/wiki/Reactor_Logic_Adapter) you can use opencomputers with that block. I connected the block with an adapter (from opencomputers). I also read about the creation of the opencomputers-api in this forum (https://github.com/mekanism/Mekanism/issues/2826). 

When connecting an reactor port to an computer the commands from the wiki don't work. Is there something i have to download? Where can i find these files? I use MC 1.12.2 btw

Other Mods work without problems.

I would be happy if someone knows whats wrong.

**Comment by pupnewfster** [comment]
I believe just having OpenComputers, Mekanism and Mekanism Generators installed should be enough. Personally I never really used OpenComputers or ComputerCraft so I may not be of that much help, but the different methods the logic adapter supports can be found here: https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/generators/common/tile/reactor/TileEntityReactorLogicAdapter.java#L15-L17

They seem to be for the most part the same as on the wiki page you linked, so I am not quite sure why it is not working for you.

**Comment by Craftler** [comment]
I will have a look at the page you linked, maybe i find something important. Or do i have to write the commands in an special programm in opencomputers craft? I used the command "lua" before typing an command, is that wrong? Is there anything else to do before typing that commands?
Maybe i ask in the opencomputers forum as well.

**Comment by pupnewfster** [comment]
No idea as I have said I haven't used OpenComputers before so I don't know what is required to make it work with mods.

**Comment by ben-mkiv** [comment]
did you just type in the component calls?
you got to address the logic port component, like 
```lua
component.reactor_logic_adapter.isIgnited()
```

if you write a lua script you can bind the component to a variable like
```lua
local reactor = require("component").reactor_logic_adapter

print(reactor.isIgnited())
```

**Comment by Craftler** [comment]
Thanks, 
i forgot to adress the component.
I thought that the commands from the linked website are enough.
