### ISSUE TITLE
Mekasuit hemlet air scrubber suppresses ALL potion effects?

### ISSUE THREAD

**Issue by Wodong77** [mekanism/Mekanism#6411]
As far as I can tell this hasn't been asked for 1.16.1, Mekanism-1.16.1-10.0.6.426

#### Issue description:
The mekasuit helmet with the air scrubber seems to suppress ALL potion effects.  The description says "negative effects" but the effect of say a 8 minute fire resistance potion lasts a matter of 30 seconds. My guess is that the air scrubber acts similarly to a gas mask and just kills any potion effects. Is this an intended effect for the mekasuit air scrubber modifcation?

#### Steps to reproduce:
1. Install Mekanism-1.16.1-10.0.6.426.jar
2. Mekasuit with full upgrades
3. Drink fire resistance potion 8 minute duration

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.67
**Mekanism:** Mekanism-1.16.1-10.0.6.426.jar
**Other relevant version:** Optifine 1.16.1 pre-14 (possibly relevant?)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

regular log, no crash
https://pastebin.com/QnzmTvQQ

**Comment by Wodong77** [comment]
Updated to version 1.16.1 - 10.0.6.429 and issue persisted.  Until I turned off the mask filter.  So I guess it's a non-issue.

**Comment by pupnewfster** [comment]
I am not sure if this is intended or not (waiting for aidan to respond), but part of the reason that we haven't looked into this earlier is when someone mentioned it on our discord server and I asked them to open an issue so that we can remember to look into it, that never happened.

**Comment by pupnewfster** [comment]
So it isn't exactly a bug but for 10.0.7 we will add a module setting for changing between negative effects and all effects.
