### ISSUE TITLE
Mekasuit unit bug

### ISSUE THREAD

**Issue by SpiCy0** [mekanism/Mekanism#6413]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When both the jetpack and creative flight modules are installed on your mekasuit, neither show up on your back, and neither work. When one is removed, the other one continues to not work, but will work when removed and added back.

#### Steps to reproduce:
1. Add the jetpack and creative flight modules to your mekasuit
2. Walk around and attempt to use either to fly, and look at your back in f5 mode
3. Remove the jetpack and attempt to fly again.
4. Remove and put back the creative flight module and attempt to fly one last time

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.91
**Mekanism:** 10.0.6.429
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Not able to reproduce this, as I mentioned on discord I believe this is likely just due to not paying attention to the fact that they are "unique" modules so you can only have one active at once. My guess is that you just have both disabled in the module configuration.
