### ISSUE TITLE
Mekanism 10.0.7.430 crashes trying to register ItemArmorJetpack

### ISSUE THREAD

**Issue by mallrat208** [mekanism/Mekanism#6417]
#### Issue description:
Minecraft fails to launch with Mekanism version 10.0.7.430 when using Forge. The Crash Report is for creating a GasStack from an unregistered Gas. That is not the source of the crash however.

```
Caught exception during event RegistryEvent.Register<minecraft:item> dispatch for modid mekanism
java.lang.IllegalAccessError: tried to access field net.minecraft.item.ArmorItem.field_185084_n from class mekanism.common.item.gear.ItemArmoredJetpack
```

Forge is shutting down the registry process when Mekanism tries to access ArmorItem.ARMOR_MODIFIERS which is private and not in the Mekanism accesstransformer.cfg 

I was able to get this to work in a local instance by just updating the AT to include:
```public net.minecraft.item.ArmorItem field_185084_n # ARMOR_MODIFIERS```

#### Steps to reproduce:
1. Setup an instance with Forge and Mekanism 10.0.7.430
2. Crash when Launching
3. Profit?

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.1-32.0.77** 
**Mekanism: 1.16.1-10.0.7.430** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gist.github.com/mallrat208/8d25643068c0f229278087fdc899656f

**Comment by pupnewfster** [comment]
Please provide your latest log as I believe the crash report here is useless.
