### ISSUE TITLE
Atomic disassembler no longer works as a hoe, or to make dirt paths

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#6421]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. get an atomic disassembler
2. try to use it as a hoe, or to make dirt paths... (tried click, shift + click, control + click, right click, shift + right click, etc etc)
3. doesn't work... is this intended?

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-1.16.1-32.0.90-installer
**Mekanism:1.16...431

**Comment by pupnewfster** [comment]
This feature got moved to the farming module that can be installed on the meka-tool

**Comment by winsrp** [comment]
I see... thanks for the info
