### ISSUE TITLE
[1.16.1] Industrial Turbine Dump Excess Energy

### ISSUE THREAD

**Issue by papaworld** [mekanism/Mekanism#6423]
Hi, dumping excess steam in the Turbine is problematic for water supply to the Fission Reactor. Is it possible to have the option for Dumping Excess Energy in the Turbine GUI? Thank you.

**Comment by pupnewfster** [comment]
No, the only reason it makes any sense that you can even dump excess steam is that you can just do so into the atmosphere. If you really want to "void" energy one of the "solutions" people on discord have suggested is using a resistive heater. Either way you probably want an induction matrix for more storage and to use various redstone signals and comparators attached to things to ensure that your fission reactor automatically turns off when it is no longer safe.

**Comment by papaworld** [comment]
Hi pup, I've been using Big/Extreme Reactors in 1.7.10 and 1.12.2 to produce steam for the industrial turbine and RFTools RF Monitor to do the excess RF removal in to an Energy void can. This would keep the reactor running for its waste output items.

The problem is a good source signal from the Fission Reactor, the redstone signal outputs are at "Critical" states, ie: temperature and damage. A turbine will fill with RF and stop, no water goes to the Fission Reactor which then depletes the water which would produce a water shortage and does not recover, filling the Reactor with steam where water should be. At a rate of 8.0mb this occurs quickly edging on disaster. Why have a turbine if the system still needs many water pumps? (2 gas-burn gens produce lots more power with no disaster lurking.)

It seems to make sense to keep the Fission Reactor running 24/7 for its Nuclear Waste output to feed the advanced features of the mod.

With a turbine attached all that is necessary is 1 pump with 8/8 upgrades for the entire system, the Reactor and the 3 "sulfur" machines (yeah, it took quite awhile to fill the reactor with water).

Is it possible to get a better source redstone signal from the Fission Reactor that detects early stage issues? Like, with a Turbine attached, there should be no steam in the Fission Reactor steam tank... once any build-up occurs or user set level, a signal goes out.

I really like the concept of the Fission system and advancements thereafter... but the baby sitting should not be part of the equation.

**Comment by pupnewfster** [comment]
One thing that lots of people have been doing is attaching a comparator to their induction matrix (via an extra induction port), so that when their energy storage is full then they stop producing energy. I know some people also have been putting comparators on their waste barrels to get a sense of how full their waste storage is so if they are running out of space then it stops as well.
