### ISSUE TITLE
Unable to extract empty gas tank item from a gas tank placed as a block

### ISSUE THREAD

**Issue by MuteTiefling** [mekanism/Mekanism#6425]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Unable to extract empty gas tank item from a gas tank placed as a block

#### Steps to reproduce:
1. Place down empty gas tank
2. Insert gas tank full of ethylene into the red slot and wait for it to transfer
3. Attempt to extract the empty gas tank

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.30
**Mekanism:** 1.15.2-9.10.9.422
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/MuteTiefling/eb28915fa59f112be3923216884d76cc

I've attempted to extract with hoppers, PneumaticCraft Drones, and logistical transporters. I've tried configuring all sides for either input or output. Nothing works. Once a tank is inserted into the red slot, I can't get it out other than manually. 

https://streamable.com/goiejn

**Comment by MuteTiefling** [comment]
Not sure if this should be a separate issue, but it seems closely related, so I'm just going to put it here: Same applies to extracting energy cubes from a PRC. Bottom is set to green and I'm unable to extract an empty cube from there. 

I can input just fine. Is it possible this is simply intended? My goal here was to try to automate Mek machines with PNC drones. No pipes whatsoever. I wanted to shift around filled batteries and gas tanks, for instance. For the most part this works. I can take ethylene from the PRC by placing a tank next to it and charging another tank inside. Then I can move that to the generators no problem, in and out. But moving hydrogen to the PRC this way is problematic due to the above issue, and now moving energy to the machines is proving problematic since I can't extract the batteries to recharge them :(

**Comment by pupnewfster** [comment]
I believe I see the issue and will fix this for 10.0.9, though unfortunately this won't really help you much as we are no longer developing the 1.15 version of Mekanism.

**Comment by MuteTiefling** [comment]
Fair enough. Thanks for looking into it.
