### ISSUE TITLE
Silk Touch Meka-Tool produces exp orbs

### ISSUE THREAD

**Issue by YotaXP** [mekanism/Mekanism#6427]
#### Issue description:
Breaking ore blocks with a silk touch-enabed Meka-Tool produces both the block of ore, and the exp you would get for breaking it without silk touch. This is repeatable for effectively free exp.

#### Steps to reproduce:
1. Install and enable a Silk Touch Unit on a Meka-Tool
2. Break a block of ore that normally drops items. (Coal, redstone, diamond, quartz, etc)

#### Version:
**Forge:** 32.0.106
**Mekanism:** 10.0.8.431

![image](https://user-images.githubusercontent.com/1637936/89420137-4a9d0e00-d700-11ea-8d89-2dede497f699.png)

**Comment by winnetrie83** [comment]
I think in the mekatool this line:
`if (exp > 0) {
                //If we have xp drop it
                block.dropXpOnBlockBreak(world, pos, exp);
`
should be like this:
` 
if (exp > 0 && !silk) {
                //If we have xp drop it
                block.dropXpOnBlockBreak(world, pos, exp);
`
This way that if statement returns false when silk was true and thus not giving xp
Don't slap me if i'm wrong
