### ISSUE TITLE
[1.16.1] Ore gen is broken

### ISSUE THREAD

**Issue by C0rn3j** [mekanism/Mekanism#6428]
```
Mekanism-1.16.1-10.0.8.431.jar
MekanismGenerators-1.16.1-10.0.8.431.jar
MekanismTools-1.16.1-10.0.8.431.jar
Forge 32.0.106
```

Haven't seen any Mekanism ores in a few hours and JustEnoughResources does not add a world gen tab to them either, so they must be broken.

**Comment by pupnewfster** [comment]
Is this in an existing world or a new world? Given in an existing world you would need to enable retro-gen if you want them to spawn in existing chunks. Also I don't believe JER has support for any modded ores without running some command to analyze a bunch of chunks.

**Comment by C0rn3j** [comment]
I just started today. I am 90% sure I didn't start the server up unmodded beforehand.

However, the first run crashed due to a BetterSprinting issue... maybe I've got into some weird state.

I created a new world using the same setup and Mekanism ores were there, so sorry for a false alarm.

I enabled retrogen (https://github.com/mekanism/Mekanism/issues/3513#issuecomment-234422889) so hopefully that fixes my current world.

**Comment by pupnewfster** [comment]
One thing to note about enabling retrogen is you also need to bump the "world gen version" (don't remember the exact wording of the config name) to something higher than one in addition to enabling retrogen so that it happens in pre-existing chunks.

**Comment by C0rn3j** [comment]
Yup! It worked.

For people running into this issue at a later date - what needs to be changed:

`world.toml`

```
enableRegeneration = true
userWorldGenVersion = 1 # Increased by 1 from 0
```

**Comment by C0rn3j** [comment]
Seems like the retrogen happened at a cost though... it messed some chunks up in a weird way where hundreds of blocks are missing.

![image](https://user-images.githubusercontent.com/1641362/89456820-badd7b00-d764-11ea-8f8a-58f1566108ae.png)

**Comment by pupnewfster** [comment]
I think there may be something more/odd going on with your world in general given how retrogen is setup it replaces stones with our ores and isn't able to replace them with air.
