### ISSUE TITLE
All paxels break melons/pumpkins slowly

### ISSUE THREAD

**Issue by HyzenB** [mekanism/Mekanism#6430]
### Issue description:
Although melons and pumpkins (and carved pumpkins) break faster with axes as the main tool,
paxels from mekanism tools break them as slow as an empty hand would.

### Steps to reproduce:
break melon/pumpkin blocks with *any* paxel.

### Versions:
Forge: 32.0.69
Mekanism: 10.0.3.426
Mekanism Tools: 10.0.3.426

### Possible fix:
I don't know if this is a problem with forge or mekanism, but you can add hard-coded checks similar to the snow blocks or other materials.

**Comment by pupnewfster** [comment]
Ah this is a problem with Mekanism and I will fix it for 10.0.9. It seems that Mojang in 1.16 added more hardcoded material type checks that I forgot to look and see if they did.
