### ISSUE TITLE
Self-made modpack crashed on startup due to Mekanism

### ISSUE THREAD

**Issue by YuriGawa** [mekanism/Mekanism#6433]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description: 
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2020-08-07 11:08:52 SGT
Description: Initializing game

java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at net.minecraft.util.NonNullList.get(SourceFile:44)
    at net.minecraft.item.crafting.ShapedRecipes.checkMatch(ShapedRecipes.java:109)
    at net.minecraft.item.crafting.ShapedRecipes.matches(ShapedRecipes.java:80)
    at net.minecraft.item.crafting.CraftingManager.findMatchingRecipe(CraftingManager.java:213)
    at mekanism.common.integration.OreDictManager.addSawmillLog(OreDictManager.java:477)
    at mekanism.common.integration.OreDictManager.addLogRecipes(OreDictManager.java:465)
    at mekanism.common.integration.OreDictManager.init(OreDictManager.java:49)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_484_OreDictManager_init_Register.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
    at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 925737792 bytes (882 MB) / 3422552064 bytes (3264 MB) up to 5100273664 bytes (4864 MB)
  JVM Flags: 10 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4864m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 98 mods loaded, 98 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version                  | Source                                             | Signature                                |
       |:----- |:--------------------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
       | LCH   | minecraft                         | 1.12.2                   | minecraft.jar                                      | None                                     |
       | LCH   | mcp                               | 9.42                     | minecraft.jar                                      | None                                     |
       | LCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                             | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | creativecoredummy                 | 1.0.0                    | minecraft.jar                                      | None                                     |
       | LCH   | itemphysic                        | 1.4.0                    | minecraft.jar                                      | None                                     |
       | LCH   | foamfixcore                       | 7.7.4                    | minecraft.jar                                      | None                                     |
       | LCH   | ambientsounds                     | 3.0                      | AmbientSounds_v3.0.12_mc1.12.2.jar                 | None                                     |
       | LCH   | applecore                         | 3.4.0                    | AppleCore-mc1.12.2-3.4.0.jar                       | None                                     |
       | LCH   | jei                               | 4.15.0.296               | jei_1.12.2-4.15.0.296.jar                          | None                                     |
       | LCH   | appleskin                         | 1.0.14                   | AppleSkin-mc1.12-1.0.14.jar                        | None                                     |
       | LCH   | appliedenergistics2               | rv6-stable-7             | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
       | LCH   | appliedintegrations               | 8.0.16.7                 | AppliedIntegrations-1.12.2-e2884e6f.jar            | None                                     |
       | LCH   | betteranimals                     | 5.3.0                    | betteranimals-1.12.2-5.3.0.jar                     | None                                     |
       | LCH   | quark                             | r1.6-179                 | Quark-r1.6-179.jar                                 | None                                     |
       | LCH   | autoreglib                        | 1.3-32                   | AutoRegLib-1.3-32.jar                              | None                                     |
       | LCH   | betterbuilderswands               | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
       | LCH   | better_diving                     | 1.5.7                    | BetterDiving-1.12.2-1.5.7.jar                      | None                                     |
       | LCH   | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
       | LCH   | bookworm                          | 1.12.2-2.5.2.1           | bookworm-1.12.2-2.5.2.1.jar                        | None                                     |
       | LCH   | codechickenlib                    | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | redstoneflux                      | 2.1.1                    | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
       | LCH   | brandonscore                      | 2.4.18                   | BrandonsCore-1.12.2-2.4.18.210-universal.jar       | None                                     |
       | LCH   | carryon                           | 1.12.3                   | carryon-1.12.2-1.12.3.15.jar                       | fd21553434f4905f2f73ea7838147ac4ea07bd88 |
       | LCH   | chunkanimator                     | 1.2                      | ChunkAnimator-MC1.12-1.2.jar                       | None                                     |
       | LCH   | cofhcore                          | 4.6.6                    | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
       | LCH   | cofhworld                         | 1.4.0                    | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
       | LCH   | cookingforblockheads              | 6.5.0                    | CookingForBlockheads_1.12.2-6.5.0.jar              | None                                     |
       | LCH   | coralreef                         | 2.0                      | CoralReef-2.5-1.12.2.jar                           | None                                     |
       | LCH   | creativecore                      | 1.10.0                   | CreativeCore_v1.10.16_mc1.12.2.jar                 | None                                     |
       | LCH   | customspawner                     | 3.11.4                   | CustomMobSpawner-3.11.5.jar                        | None                                     |
       | LCH   | cyberware                         | 0.2.11.26                | cyberware-1.12.2-0.2.11.26.jar                     | None                                     |
       | LCH   | ptrmodellib                       | 1.0.4                    | PTRLib-1.0.4.jar                                   | None                                     |
       | LCH   | props                             | 2.6.3                    | Decocraft-2.6.3_1.12.2.jar                         | None                                     |
       | LCH   | thermalfoundation                 | 2.6.7                    | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
       | LCH   | draconicevolution                 | 2.3.25                   | Draconic-Evolution-1.12.2-2.3.25.351-universal.jar | None                                     |
       | LCH   | mocreatures                       | 12.0.5                   | DrZharks MoCreatures Mod-12.0.5.jar                | None                                     |
       | LCH   | orelib                            | 3.6.0.1                  | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | dsurround                         | 3.6.1.0                  | DynamicSurroundings-1.12.2-3.6.1.0.jar             | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCH   | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                        | None                                     |
       | LCH   | enderio                           | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | enderiointegrationtic             | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | enderiobase                       | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | enderioconduits                   | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | enderioconduitsappliedenergistics | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | enderioconduitsopencomputers      | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | enderioconduitsrefinedstorage     | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | enderiointegrationforestry        | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                           | None                                     |
       | LCH   | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                   | None                                     |
       | LCH   | enderiointegrationticlate         | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | enderiomachines                   | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | enderiopowertools                 | 5.2.59                   | EnderIO-1.12.2-5.2.59.jar                          | None                                     |
       | LCH   | ageofabyssalcraft                 | 0.7                      | Engender Mod-1.12.2-0.7-pre1.jar                   | None                                     |
       | LCH   | ageofchaos                        | 0.7                      | Engender Mod-1.12.2-0.7-pre1.jar                   | None                                     |
       | LCH   | ageofminecraft                    | 0.7                      | Engender Mod-1.12.2-0.7-pre1.jar                   | None                                     |
       | LCH   | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.9.jar                         | None                                     |
       | LCH   | farmingforblockheads              | 3.1.28                   | FarmingForBlockheads_1.12.2-3.1.28.jar             | None                                     |
       | LCH   | fastleafdecay                     | v14                      | FastLeafDecay-v14.jar                              | None                                     |
       | LCH   | flansmod                          | 5.5.1                    | Flan's Mod-1.12.2-5.5.1.jar                        | None                                     |
       | LCH   | flansmodapocalypse                | 1.0                      | Flan's Mod-1.12.2-5.5.1.jar                        | None                                     |
       | LCH   | foamfix                           | 0.10.10-1.12.2           | foamfix-0.10.10-1.12.2.jar                         | None                                     |
       | LCH   | gravestone                        | 1.10.3                   | gravestone-1.10.3.jar                              | None                                     |
       | LCH   | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
       | LCH   | immersiveengineering              | 0.12-98                  | ImmersiveEngineering-0.12-98.jar                   | None                                     |
       | LCH   | immersivecables                   | 1.3.2                    | ImmersiveCables-1.12.2-1.3.2.jar                   | None                                     |
       | LCH   | immersivepetroleum                | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                | None                                     |
       | LCH   | immersiveposts                    | 0.2.1                    | ImmersivePosts-0.2.1.jar                           | 0ba8738eadcf158e7fe1452255a73a022fb15feb |
       | LCH   | immersivetech                     | 1.3.10                   | immersivetech-1.12-1.3.10.jar                      | None                                     |
       | LCH   | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                           | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                  | None                                     |
       | LCH   | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
       | LCH   | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                        | None                                     |
       | LCH   | mekanism                          | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
       | LCH   | mekanismgenerators                | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar            | None                                     |
       | LCH   | mekanismtools                     | 1.12.2-9.8.3.390         | MekanismTools-1.12.2-9.8.3.390.jar                 | None                                     |
       | LCH   | mekores                           | 2.0.13                   | mekores-2.0.13.jar                                 | None                                     |
       | LCH   | numina                            | 1.12.2-1.0.38            | Numina-1.12.2-1.0.38.jar                           | None                                     |
       | LCH   | powersuits                        | 1.12.2-1.0.46            | ModularPowersuits-1.12.2-1.0.46.jar                | None                                     |
       | LCH   | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                      | None                                     |
       | LCH   | oreexcavation                     | 1.4.150                  | OreExcavation-1.4.150.jar                          | None                                     |
       | LCH   | brewcraft                         | 1.12.2-1.0.2             | Pam's BrewCraft 1.12.2-1.0.2.jar                   | None                                     |
       | LCH   | getalltheseeds                    | 1.12a                    | Pam's Get all the Seeds! 1.12a.jar                 | None                                     |
       | LCH   | harvestcraft                      | 1.12.2zb                 | Pam's HarvestCraft 1.12.2zg.jar                    | None                                     |
       | LCH   | simplerecipes                     | 1.12.2c                  | Pam's Simple Recipes 1.12.2c.jar                   | None                                     |
       | LCH   | pamscookables                     | 1.1                      | pamscookables-1.1.jar                              | None                                     |
       | LCH   | quarkoddities                     | 1                        | QuarkOddities-1.12.2.jar                           | None                                     |
       | LCH   | simplyjetpacks                    | 2.2.15.69                | SimplyJetpacks2-1.12.2-2.2.15.69.jar               | None                                     |
       | LCH   | spiceoflife                       | 1.3.12                   | SpiceOfLife-mc1.12-1.3.12.jar                      | None                                     |
       | LCH   | stg                               | 1.12.2-1.2.3             | stg-1.12.2-1.2.3.jar                               | None                                     |
       | LCH   | surge                             | 2.0.77                   | Surge-1.12.2-2.0.77.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | texfix                            | 4.0                      | TexFix V-1.12-4.0.jar                              | None                                     |
       | LCH   | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
       | LCH   | vanillafix                        | 1.0.10-150               | VanillaFix-1.0.10-150.jar                          | None                                     |
       | LCH   | zawa                              | 1.12.2-2.1.0             | zawa-1.12.2-2.1.0.jar                              | 3ee471ded1bba54aa82f4f5ca5ca82dd67b8ef42 |
       | LCH   | densemetals                       | 2.0.0                    | DenseMetals-1.12.2-2.0.0.30.jar                    | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCH   | matteroverdrive                   | 0.7.0.0                  | MatterOverdrive-1.12.2-0.7.1.0-universal.jar       | None                                     |
       | LCH   | phosphor-lighting                 | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50-universal.jar        | f0387d288626cc2d937daa504e74af570c52a2f1 |
  Loaded coremods (and transformers): TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      Quark Plugin (Quark-r1.6-179.jar)
                                        vazkii.quark.base.asm.ClassTransformer
                                      AppleCore (AppleCore-mc1.12.2-3.4.0.jar)
                                        squeek.applecore.asm.TransformerModuleHandler
                                      CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50-universal.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      ItemPatchingLoader (ItemPhysic_Full_1.4.34_mc1.12.2.jar)
                                        com.creativemd.itemphysic.ItemTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
                                        
                                      LoadingPlugin (ChunkAnimator-MC1.12-1.2.jar)
                                        lumien.chunkanimator.asm.ClassTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 445.87' Renderer: 'GeForce GTX 1070/PCIe/SSE2'
  AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            Authlib is : /C:/Users/pc/Documents/Curse/Minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - wailaIntegration (Enabled/Not Forced)
                                   - quarkIntegration (Enabled/Not Forced)
  Suspected Mods: Mekanism (mekanism)
  Launched Version: forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1070/PCIe/SSE2 GL version 4.6.0 NVIDIA 445.87, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 4x Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2854
**Mekanism:** 9.8.3.390

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
No idea best guess is one of the mods is doing something weird to recipes causing lookups to fail, but as we are no longer developing for 1.12 and I barely even remember how any of our systems used to work there is unfortunately not much that I can suggest.
