### ISSUE TITLE
Mekanism 10 - Fission Reactor

### ISSUE THREAD

**Issue by iced00d** [mekanism/Mekanism#6434]
Good day folks. So, I just finished building the Fission Reactor and Turbine from Mekanism 10. Following tutorials, I have water going in, fuel going in , steam outputting to the turbine and a water return to the reactor. The problem that I'm running into is that i'm not getting enough steam in the turbine to create power. Yet when I''m in the Fission Reactor Statistics and I bump the rate limit to anything above 0.1mB/T, immediately I run out of coolant. Even though I have 2 water pumps that are maxed out with speed and energy upgrades. Attached are screenies. Any help would be greatly appreciated. Tks in advance..
![2020-08-07_11 45 45](https://user-images.githubusercontent.com/46030013/89673665-be801780-d8b4-11ea-9355-3e9c0c33abc7.png) 
![2020-08-07_11 45 52](https://user-images.githubusercontent.com/46030013/89673676-c475f880-d8b4-11ea-84d7-039b8116254c.png) 
![2020-08-07_11 46 01](https://user-images.githubusercontent.com/46030013/89673685-c8a21600-d8b4-11ea-9efc-2a1133218590.png) 
![2020-08-07_11 53 25](https://user-images.githubusercontent.com/46030013/89673691-cc359d00-d8b4-11ea-9eab-c42dcec44bba.png)

**Comment by Oct0bass** [comment]
Github is for  bugs with the mod, not gameplay problems you might be experiencing.  Ask on [the Mekanism discord](https://discord.gg/67GEDyx) for things like this.  I'd say you need more pumps.

**Comment by iced00d** [comment]
Sorry about that, someone mentioned it might be a bug and advised me to report it.  Tks for the discord info.  I apprecaite it

**Comment by Caltinor** [comment]
iced00d,  check the turbine's statistics page.  you should see a stat at the bottom telling you how much water is being produced.  your build uses 4 shafts and 8 blades.  if you are using 8 dispersers around your rotational complex, you will need 32 vents to balance (6 on each side, 8 on top).  for the layer above the complex use 2 coils and put saturating condensers in the other 7 slots.  all that together should give you the right build.  I am guessing you probably have the coils and condensers incorrectly configured.

as a personal preference I put the turbine and the reactor right next to each other to avoid pipe restrictions on steam output and water return.  Just line up the ports.
