### ISSUE TITLE
Java NBT tag to big 

### ISSUE THREAD

**Issue by neithie** [mekanism/Mekanism#6437]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Running server with latest Mekanism and all was working fine until lately. Now I'm getting an error: 
Internal Exception: io.netty.handler.codec.DecoderException:java.lang.RuntimeException: Tried to read NBT tag that was too big; tried to allocate: 16777219bytes where max allowed 16777216

Error boots me from the server without crashing server whenever I try to use any mekanism tool, machine, ect. 

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** Latest
**Mekanism:**  Latest
**Other relevant version:** Server is running latest HR New Beginnings modpack. 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by thiakil** [comment]
send full log then

**Comment by pupnewfster** [comment]
Also latest means nothing give us a number
