### ISSUE TITLE
Game crash on load

### ISSUE THREAD

**Issue by SotirisX7** [mekanism/Mekanism#6438]
Issue description:
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (mekanism)

Version:
Forge: 1.12.2 - 14.23.5.2854
Mekanism: 9.8.3.390

[crash-2020-08-08_15.39.02-client.txt](https://github.com/mekanism/Mekanism/files/5045257/crash-2020-08-08_15.39.02-client.txt)

**Comment by pupnewfster** [comment]
#6182

**Comment by SotirisX7** [comment]
Thanks!
