### ISSUE TITLE
Turbine doesn't work when update from 425 to 431 (1.16.1)

### ISSUE THREAD

**Issue by idonhavename** [mekanism/Mekanism#6441]
When I update from 10.0.8.425 to 10.0.8.431, everything is normal except the turbine, It just stops spinning, can't click, even I rebuild it, still doesn't work.
Forge: 32.0.107
Mekanism: 10.0.8.431
![2020-08-09_23 00 58](https://user-images.githubusercontent.com/52009098/89737019-15921200-da98-11ea-81d7-47ee1a8064ca.png)

**Comment by idonhavename** [comment]
I accidentally pressed close...

**Comment by pupnewfster** [comment]
Your turbine is way too tall the max height is 18
