### ISSUE TITLE
Unable to unify metals.

### ISSUE THREAD

**Issue by SubjectHawk66** [mekanism/Mekanism#6443]
I'm on 1.12.2 btw. I play on a pack with a "unify metals" script. It seems like no matter what, the mekanism machines don't obey this script. I'm not sure why but I know for a fact it is an issue on mekanism's end. I'm not sure if this is a problem or if it's for a reason.

**Comment by pupnewfster** [comment]
No idea but I know for a fact the CrT integration we had in 1.12 does work so my best guess is it is probably with your "unify metals" script.
