### ISSUE TITLE
Custom recipes: lacking doc

### ISSUE THREAD

**Issue by luisbrandao** [mekanism/Mekanism#6447]
Hello. 
I see i can add custom recipes to the machines (the syntax is in the github wiki), but i have no idea were to put the new files.
I HAVE to inject then inside the jar, or there is an easier way?
Could someone include that in the docs?

**Comment by Oct0bass** [comment]
No need for mekanism to reinvent the wheel, it's all there already on the [Minecraft Wiki](https://minecraft.gamepedia.com/Tutorials/Creating_a_data_pack ).

**Comment by pupnewfster** [comment]
As Oct0 said it just uses vanilla's data pack system which I am sure there is plenty of documentation on the internet for. I believe CrT also has a way to add json recipes (though I am not fully sure how that system works)
