### ISSUE TITLE
Progress arrows can go past their max size when installing speed upgrades

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#6448]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Pressurized Reaction Chamber only takes 1 speed upgrade to make HDPE pellets, putting a second upgrade stops the machine (this is without any other upgrades )

#### Steps to reproduce:
1. setup HDPE production (rotary condensentrator has 8 speed upgrades, electrolitic separator has 7 speed upgrades)
2. add a single speed upgrade on Pressurized Reaction Chamber -> all good so far
3. add a second speed upgrade on Pressurized reaction Chamber -> machine stops, and won't work
4. add the other 6 speed upgrades, gui breaks showing a long arrow

![image](https://user-images.githubusercontent.com/13665046/89944185-a07c2500-dbdc-11ea-9e3d-1dfe40bb68d4.png)

#### Version (make sure you are on the latest version before reporting):
**Forge: .99
**Mekanism: .431

**Comment by winsrp** [comment]
doing some further tests on this, this is related to the machine not having enough power to complete a single operation with the machine internal energy buffer, so it stops, instead of taking power from the connected cables... adding power upgrades fixes the machine stopping, but the GUI bug is still there without the energy upgrades, and it would be nice to know that the machine is not working because internally it does not have enough power, even when the cables do provide it with such.

**Comment by pupnewfster** [comment]
Does the GUI bug still happen if you remove optifine?

**Comment by winsrp** [comment]
I don't have optifine

**Comment by pupnewfster** [comment]
Hmm I will try to look into it at some point when I get the chance then, before now everyone who reported that issue with the arrows in the GUI had optifine installed, and could not reproduce it without it installed.

**Comment by winsrp** [comment]
can I also suggest adding like a symbol that reports errors for power in this case, something that you can hover on with your mouse and tells you what is going on, like a red triangle with an exclamation symbol or something... for you consideration.

Thanks for the help

**Comment by pupnewfster** [comment]
I would recommend making an issue for that on the feature request issue tracker, https://github.com/mekanism/Mekanism-Feature-Requests/issues so as to not have it be forgotten. I agree it is something that makes sense and probably will be done but I am not quite sure when I will get around to it as that is a bit more involved.
