### ISSUE TITLE
[1.16.1] Mekanism -> storage drawers => pipes not sending all available items to Drawer Controller over time

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#6449]
#### Issue description:

after some time of operation the pipes wont send items to the drawer controller (assuming you can still accept items, because there is enough space in the connected drawers) you can manually extract the items from containers and double click the drawer controller and it will take in all items, but it wont move them with pipes, even after removing the drawer controller the pipes and the source from mekanism

#### Steps to reproduce:
1. setup drawer array (can be any size but lets say 2 row 8 columns of drawers, with a single emerald upgrade each) attach at any position a drawer controller
2. Setup a digital miner (8 speed upgrades, 8 energy upgrades, filter tag = *ore*, filter item = diorite, filter item = granite) connect with advanced logistical transport pipe to drawer controller
3. let it run for 10/15 mins
4. check the digital miner to see if it is sending everything (sometimes the error already shows in here)
4. break the drawers and rearrange them a bit in any configuration (you can even break the drawer controller and put it somewhere else)
5. let it run a 5/10 more mins
6. at this point I had 100% replicability of the issue where there might be some mineral, or rock that is not being sent the drawer controller, even when there is a ton more space left

#### Version (make sure you are on the latest version before reporting):
**Forge: .99
**Mekanism: .431

**Comment by pupnewfster** [comment]
Until Storage Drawers fixes their mod https://github.com/jaquadro/StorageDrawers/issues/811 I am not going to spend any time investigating further issues with it as it is not worth the time as most likely all issues interacting with that mod relate to the issue I linked and that they do not implement inventories properly.
