### ISSUE TITLE
In version 1.16.1, industrial turbines are not available.

### ISSUE THREAD

**Issue by liukenny961** [mekanism/Mekanism#6455]
In version 1.16.1, I built thermal boilers and industrial turbines. I wanted to bring the steam from the thermal boiler into the turbine, but I found that it was not possible to use mechanical pipes and that the turbine valve did not recognize it. I switched to a pressurized pipe, but I couldn't transfer steam. What's the reason?
![Snipaste_2020-08-13_11-42-38](https://user-images.githubusercontent.com/65520199/90092196-db0bcc00-dd5a-11ea-963c-024ea6e6a633.png)

**Comment by pupnewfster** [comment]
Steam uses a pressurized tube not mechanical pipes, you also probably haven't changed the boiler valve's mode to output from input.

**Comment by liukenny961** [comment]
So how to change the output input mode of the boiler valve?

**Comment by pupnewfster** [comment]
Using a configurator

**Comment by liukenny961** [comment]
I've tried configuring it with a debugger before, but no matter how switched to that state, the boiler valve didn't react (neither highlighted). Is it possible to do this with version 1.16.1?



在 2020-08-15 21:53:56，"Richard Freimer" <notifications@github.com> 写道：

Using a configurator
