### ISSUE TITLE
Is liquid steam still steam？

### ISSUE THREAD

**Issue by asdf3601a** [mekanism/Mekanism#6461]
![unknown](https://user-images.githubusercontent.com/12381354/90208632-d9eea380-de1b-11ea-940d-b856bad22a88.png)

**Comment by asdf3601a** [comment]
Maybe it should be water？

**Comment by pupnewfster** [comment]
No, the sole reason it exists is for compat for other mod's steam, hence it is liquid steam because for all extents and purposes that is what other mod's steam is
