### ISSUE TITLE
Digital Miner don't showing remaining entities to mine in language different of EN-US

### ISSUE THREAD

**Issue by Gmartins12** [mekanism/Mekanism#6463]
Issue description:
In a language different of English(US), the remaining entities to mine showed in digital mine don't appear.

Steps to reproduce:
1.Build a Digital Miner;
2.Select other language different of English(US);
3.See that the entity counter does not appear.

Forge:32.0.108
Mekanism:1.16.1-10.0.8.431

**Comment by Mingu2209** [comment]
I can confirm this problem for Spanish version
