### ISSUE TITLE
Heat Energy generation Bug

### ISSUE THREAD

**Issue by mrmegusta** [mekanism/Mekanism#6465]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The Heat Generator was producing 16x more energy than the usual, the bug shows on advanced energy cube with input mode purple ( input/output )

#### Steps to reproduce:
1. I've build 13 heat generator, with 5 sides lava. And the expected energy prodution was 73,63 x 13 = 957,19 J/t
2. I put an advanced power cube connected to the 13 heat generators
3.When I put only Input mode ( red color ) the energy incoming is normal, 957,19 J/t
4. But If I put on purple mode, the incoming was 16,60k J/t ?? ( with all cables empty )

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108
**Mekanism:** 1.16.1-10.8.431
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
If you turn off auto eject for the energy cube does it then show the number you expect? My best guess is that the confusion is that the energy cube is filling the cable each tick and then accepting all the power back again, and thus causing how much it is accepting to appear a lot higher.

**Comment by mrmegusta** [comment]
yeah, you are right, I'm sorry for the waste of time XD It was only visual, but the incoming was the same than before, my bad
