### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by FlashFearsomeBear** [mekanism/Mekanism#6466]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
There are several null textures on several of the place-able objects and machines, such as the automated miner and all of the cables/pipes.

#### Steps to reproduce:
1.Go into world
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
1.16.1-forge-32.0.108
**Mekanism:** 
Mekanism-1.16.1-10.0.9.432.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Please provide your latest log, also are you using optifine, and are you using a resource pack? It sort of sounds like you are using a broken resource pack.

**Comment by FlashFearsomeBear** [comment]
Using optifine 1.16.1 release. No resource pack, when we use the previous
version of Mek 10.0.8.431 everything works fine.

**Comment by pupnewfster** [comment]
I still will need the latest log, and does it happen without optifine?

**Comment by FlashFearsomeBear** [comment]
haven't tried without optifine, also, what's a log? Sorry, i'm not really
knowledgable about this stuff.

**Comment by pupnewfster** [comment]
In your minecraft instance folder, there is a folder called `logs`, and inside of it there should be a file named `latest.log` or just `latest` if you have file extensions hidden.

**Comment by halvors** [comment]
I can confirm that i'm experiencing the same issue. Here is the latest.log: https://paste.ubuntu.com/p/S5CSB4X4qT/
Was there a change in 10.0.9 that could have caused this?

**Comment by pupnewfster** [comment]
Can you reproduce this without optifine.

**Comment by Henryws** [comment]
For me it does work without Optifine. The cable is above the back to game button

![image](https://user-images.githubusercontent.com/58742515/90313951-e46d7380-ded5-11ea-9d65-26a7516148f9.png)

**Comment by pupnewfster** [comment]
I am going to go ahead and say optifine is not fully compatible with forge 32.0.107+ then.
