### ISSUE TITLE
Textures break with OptiFine installed

### ISSUE THREAD

**Issue by TheSpicePhantom** [mekanism/Mekanism#6475]
#### Issue description:
Machines are rendered as missing texture when using latest OptiFine for 1.16.1.

#### Steps to reproduce:
1. Install Mekanism (all 4 Parts)
2. Install OptiFine 1.16.1 HD U G2
3. Launch a Game and put down some machines.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108
**Mekanism:** 
- Mekanism-1.16.1-10.0.9.432
- MekanismAdditions-1.16.1-10.0.9.432
- MekanismGenerators-1.16.1-10.0.9.432
- MekanismTools-1.16.1-10.0.9.432

**Other relevant version:** OptiFine 1.16.1 HD U G2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_) 
No, it isn't.

[imgur](https://imgur.com/gallery/fyphP7s)

**Comment by pupnewfster** [comment]
Uninstall optifine or have them fix compat with forge

**Comment by halvors** [comment]
Did not start at all without Optifine, sone problem related to CTM.

**Comment by pupnewfster** [comment]
CTM needs to update to support 32.0.107+ as well, either remove it or download the update from their maven given they haven't released it on CF yet.
