### ISSUE TITLE
Atomic Disassembler 'extended vein mining' mode deletes Digital Miner when you break it. (And possibly more multiblocks?)

### ISSUE THREAD

**Issue by Credit-Score** [mekanism/Mekanism#6477]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Place a Digital miner
2. Get an atomic disassembler and set it's mode to 'extended vein mining'
3. break a corner block of the digiminer
Then it will just delete the digiminer

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-14.23.5.2854
**Mekanism:** MekanismGenerators-1.12.2-9.8.3.390
**Other relevant version:** N/A

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

No crash.

**Comment by pupnewfster** [comment]
No longer an issue in 1.15+
