### ISSUE TITLE
The Fission Reactor Logic Adapter can't charge the block in front.

### ISSUE THREAD

**Issue by sagesse-cn** [mekanism/Mekanism#6478]
#### Issue description:
The Reactor Logic Adapter can't charge the block in front.

#### Steps to reproduce:
1. Input the command `/mek build fission`
2. Place a `Fission Reactor Logic Adapter` on top of it, set to `Insufficient Fuel mode`.
3. Place a `Dirt Block` on top of `Fission Reactor Logic Adapter` and place a `Redstone Torch` on top of it.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.1-forge-32.0.108
**Mekanism:** Mekanism-1.16.1-10.0.8.431/MekanismGenerators-1.16.1-10.0.8.431
**Other relevant version:** appliedenergistics2-8.0.0-alpha.3

**Comment by pupnewfster** [comment]
Finally had a chance to test/look into this and I think it is working as intended, most non directional redstone things (such as redstone blocks) don't go through other blocks. I put a port on top of the reactor set to insufficient fuel mode, and then tried putting a piece of redstone on top of the port (it got powered), I then tried replacing that piece of redstone with a redstone torch (no dirt block in between), and the redstone torch became deactivated.
