### ISSUE TITLE
AE2 dust recipes missing from Mekanism Crusher

### ISSUE THREAD

**Issue by sagesse-cn** [mekanism/Mekanism#6479]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*
Closed issue: #4881

#### Issue description:
The certus, charged certus and fluix dust from Applied Energistics 2 can't produced in the crusher.
ModTweaker It seems that no one has maintained it for a long time and relying on another mod to solve the problem seems like a bad idea.

#### Steps to reproduce:
1. Place certus quartz or fluix into crusher.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.1-forge-32.0.108
**Mekanism:** Mekanism-1.16.1-10.0.8.431
**Other relevant version:** appliedenergistics2-8.0.0-alpha.3

**Comment by thiakil** [comment]
The recipes likely got commented out in 1.16 as AE hadn't updated yet

**Comment by pupnewfster** [comment]
You can solve it by adding the recipes with a datapack if you care. Until AE2 fixes their maven we are not going to add back our compat for it.

**Comment by sagesse-cn** [comment]
```shell
diff --git a/build.gradle b/build.gradle
index f7fa44f3d..70c6275ae 100644
--- a/build.gradle
+++ b/build.gradle
@@ -290,6 +290,14 @@ repositories {
         name 'HWYLA'
         url "https://maven.tehnut.info"
     }
+    maven {
+        name "AE2"
+        url "https://maven.pkg.github.com/AppliedEnergistics/Applied-Energistics-2"
+        credentials {
+            username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
+            password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
+        }
+    }
 }
 
 test {
@@ -325,6 +333,8 @@ dependencies {
     datagenmainCompileOnly fg.deobf("curse.maven:biomes-o-plenty-api:${biomesoplenty_api_id}")
     datagenmainRuntimeOnly fg.deobf("curse.maven:biomes-o-plenty:${biomesoplenty_id}")
     //datagenmainCompile fg.deobf("curse.maven:i-like-wood:${ilikewood_id}")
+
+    compileOnly "appeng:appliedenergistics2:8.0.0-beta.1:api"
 }
 
 processResources {
```

I've tried to integrate and build success from this changs. 
If your think generation a token is too much trouble, can fill in a fixed one.
I can also provide one.

**Comment by thiakil** [comment]
I don't want to add a maven dep that requires a token to use

**Comment by pupnewfster** [comment]
> I don't want to add a maven dep that requires a token to use

This is exactly why I have not done so, especially after talking the other day with someone from AE2 who was saying there are plans for it to be mirrored on another maven that does not require a token to use.

**Comment by sagesse-cn** [comment]
> > I don't want to add a maven dep that requires a token to use
> 
> This is exactly why I have not done so, especially after talking the other day with someone from AE2 who was saying there are plans for it to be mirrored on another maven that does not require a token to use.

The not require a token maven is upload in modmaven.
https://modmaven.k-4u.nl/appeng/appliedenergistics2/8.0.0-beta.1

**Comment by TheCreepyGinger** [comment]
How do I implement this solution? Or do I just wait for the mods to be updated?
