### ISSUE TITLE
[Feature Suggestion]: immersive portals mod compatiblity / more customizable portals / other portals specifity requests

### ISSUE THREAD

**Issue by mariodk** [mekanism/Mekanism#6480]
immersive portals mod compatiblity:
i want the Mekanism portals to work with: https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge
but not by default maybe have a portal upgrade for this so you can choice what portals has this active or not 

more customizable portals:
would like if the portals can be mostly any sizes and most shapes too like having it formed as a "ring"
instead of only have 1 size/scape of portal 
could do some balancing like the bigger the portal the more power it uses 

other stuff: 
make the portal computercraft / open computer mods compatiblity
so we can make a ComputerCraft(or OC´s equal to that) touch screen(gold monitor) with a UI to controll where a portal will link to 
if not that maybe mekanism´s own way to do that so you dont need to code in those mods 
just link the portal somehow up to a screen/controll panel thing you can choose what other portals shows up in that screen/controll panel thing

**Comment by pupnewfster** [comment]
I believe there is already an open issue on the feature tracker for larger portals, compat with immersive portals is not going to happen on our end because immersive portals isn't even fully compatible with forge and breaks various features that we make use of.

**Comment by LuizLoyola** [comment]
This is almost 2 years old, is this something that can happen later? The forge version is pretty stable now
