### ISSUE TITLE
Some mekanism blocks are showing as pink and black textures and/or invis

### ISSUE THREAD

**Issue by jakecroftford** [mekanism/Mekanism#6481]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
certain items seem to not be showing item icons or even their block form and are defulting to a pink and black broken texture and the digital miner is just invis when places minus the outline of the center block

#### Steps to reproduce:
1.Play Valhelsia 3 (modpack)
2.I do have optifine added into the pack
3.check out @mekanism in jei and you will spot them
![unknown](https://user-images.githubusercontent.com/69786040/90366244-ffb7ba80-e05e-11ea-808a-2f68c131526b.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by jakecroftford** [comment]
It does appear to be an issue with optifine as removing it fied the issue

**Comment by thiakil** [comment]
_Please use the search functionality before reporting an issue_
