### ISSUE TITLE
CTM Error with Mekanism

### ISSUE THREAD

**Issue by karakufire** [mekanism/Mekanism#6482]
#### Issue description:
Loading Error at sided_setup event phrase

![image](https://user-images.githubusercontent.com/10906521/90396227-d0419600-e0d0-11ea-816f-7733a866e1cf.png)

#### Steps to reproduce:
1. Setup Forge for mc 1.16.1
2. Install Mekanism and CTM
3. Run

#### Version (make sure you are on the latest version before reporting):
**Forge:32.0.108** 
**Mekanism:1.16.1-10.0.9.432** 
**Other relevant version:CTM - 1.1.0.1** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
latest.log - https://pastebin.com/dhh4z8wx
debug.log - https://pastebin.com/7azL3Zj9

**Comment by pupnewfster** [comment]
I have no idea why you are reporting the fact that CTM isn't updated to the latest forge to us and not CTM... so either remove it while you wait for it to update or look at their maven for a newer build

**Comment by karakufire** [comment]
OK, I see. In other words it's not mekanism defect.

**Comment by pupnewfster** [comment]
Correct
