### ISSUE TITLE
Updated Mekanism to include Mekanism Generators: Textures break

### ISSUE THREAD

**Issue by krlsmnk** [mekanism/Mekanism#6483]
#### Issue description:
Wanted to add Mekanism generators to my pack. Forge told me I needed to update Mekanism due to version mismatch. I did. Pipes and blocks from Mekanism stopped rendering correctly, and I <think> they're not working quite right, but I can't really see the pipe configurations to confirm. 

#### Steps to reproduce:
1. Playing on Mekanism version .8.431 with no problems. I wanted to add Mekanism generators. 
2. Forge told me to update Mekanism because of the version mismatch between it and Mekanism Generators. 
3. Replaced Mekanism with new version, on client and server.
4. Stopped then launched server. 
5. Stopped and launched client. 
6. Connected to existing world. Existing placed pipes, pipes in inventory, and Mekanism Generator blocks showing issue.
 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108 for MC version 1.16.1
**Mekanism, Old Working Version:** 10.0.8.431
**Mekanism, New Version with Error:** 10.0.9.432
**Mekanism Generators Version:** 10.0.9.432

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No crash. 

Screenshot of issue:
[https://imgur.com/a/TQRTLtc](url)

**Comment by pupnewfster** [comment]
Optifine is not fully compatible with forge 32.0.107+. Forge fixed a bug so I removed my messy workaround for the bug and am now using the proper system in 10.0.9 of Mekanism. It seems that optifine is reverting this forge fix. So either remove optifine or if you don't care about the various fixes in Mekanism 10.0.9, downgrade Mekanism and Mekanism generators to 10.0.8

**Comment by krlsmnk** [comment]
Got it. Thanks a ton for your insanely prompt response.
