### ISSUE TITLE
optifine rendering cables/pipes

### ISSUE THREAD

**Issue by HiddenGhost121** [mekanism/Mekanism#6484]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
when i install optifine the cables, and the pipes textures become corrupted and turn black and purple
https://imgur.com/IBAbuuS

#### Steps to reproduce:
1.install mekanism
2.install optifine 
3.place cables/pipes

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-32.0.108
**Mekanism:** Mekanism-1.16.1-10.0.9.432
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by thiakil** [comment]
_Please use the search functionality before reporting an issue_

**Comment by sagesse-cn** [comment]
> _Please use the search functionality before reporting an issue. Also take a look at the closed issues!_
> 
> #### Issue description:
> when i install optifine the cables, and the pipes textures become corrupted and turn black and purple
> https://imgur.com/IBAbuuS
> 
> #### Steps to reproduce:
> 1.install mekanism
> 2.install optifine
> 3.place cables/pipes
> 
> #### Version (make sure you are on the latest version before reporting):
> **Forge:** forge-32.0.108
> **Mekanism:** Mekanism-1.16.1-10.0.9.432
> **Other relevant version:**
> 
> #### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
> [[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

If use OptiFine mod, plase install additional for OptiForge
