### ISSUE TITLE
CraftTweaker Sawing recipe issue

### ISSUE THREAD

**Issue by djmattyg007** [mekanism/Mekanism#6485]
#### Issue description:
Sawing recipes do not accept numbers with decimal places in the `secondaryChance` field. If you attempt to do so, CraftTweaker reports the following error:

```
Empty map without known type
```

I've tried many different combinations of values and am very confident this is the issue.

#### Steps to reproduce:
Create a CraftTweaker script that looks like so:

```
<recipetype:mekanism:sawing>.addJSONRecipe("immersiveengineering_stairs_treated_wood_horizontal", {
    "input": {
        "ingredient": {
            "item": "immersiveengineering:stairs_treated_wood_horizontal"
        }
    },
    "mainOutput": {
        "item": "immersiveengineering:treated_wood_horizontal",
        "count": 1
    },
    "secondaryOutput": {
        "item": "immersiveengineering:treated_wood_horizontal",
        "count": 1
    },
    "secondaryChance": 0.5
});
```

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2-31.2.36
**Mekanism:** 1.15.2-9.10.9.422
**Other relevant version:** CraftTweaker 1.15.2-6.0.0.39

**Comment by jaredlll08** [comment]
What is your CraftTweaker log?
