### ISSUE TITLE
I can't add or remove recipes 

### ISSUE THREAD

**Issue by FariZTheKiller** [mekanism/Mekanism#6486]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Type " mods.mekanism.enrichment.removeAllRecipes(); " in a .zs file in the scripts folder
2. Load up a world
3. it'll say in chat: "ERROR Crystals.zs:1:0: Member not foundL mekanism. Scripts are invalid"

#### Version (make sure you are on the latest version before reporting):
**Forge: 31.2.36
**Mekanism: 1.15.2-9.10.9.422
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I am not sure why you are using the 1.12 CrT docs for the 1.15 version of CrT and just expecting it to work... especially given we have not rewritten our CrT integration yet, so 1.15+ does not have it and instead only currently supports data packs.
