### ISSUE TITLE
Charge Inventory feature doesn't charge anything by Immersive Engineering. (1.16.1)

### ISSUE THREAD

**Issue by idonhavename** [mekanism/Mekanism#6488]
Issue description: Charge Inventory feature doesn't charge anything by IE (Ex: railgun) unless something needs to charge by Mekanism (Like Atomic Disassembler) and then railgun will charge. But as soon as I remove the Atomic away and shot the railgun, it's not getting any charge.

Steps to reproduce:
1. Download both Mek and IE.
2. Upgrade MekaSuit Body Armor.
3. Turn on "Charge Inventory" and railgun doesn't charge.

Version (make sure you are on the latest version before reporting):
Forge: 32.0.108
Mekanism: 10.0.8.431
Other relevant version: Immersive Engineering 1.16.1-3.2.0-115

![2020-08-18_21 08 34](https://user-images.githubusercontent.com/52009098/90638989-40c6ef00-e258-11ea-972e-3f714ac3eccc.png)

![2020-08-18_21 09 32](https://user-images.githubusercontent.com/52009098/90639452-e11d1380-e258-11ea-865e-276e16965343.png)

Sorry for my bad English.

**Comment by pupnewfster** [comment]
I will fix this for 10.0.10, but it turns out the issue is just that it doesn't properly distribute charge while in creative and has nothing to do with IE.
