### ISSUE TITLE
Mekanism-1.16.1-10.0.9.432 missing images

### ISSUE THREAD

**Issue by Bannta** [mekanism/Mekanism#6489]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
universal cables
tanks stuff in general 
security desk
tubes stuff in general 
pipes stuff in general 
basic restrictive transporter
basic thermodynamic conductors 
QIO stuff in general 

#### Steps to reproduce:
1. downgrade Mekanism-1.16.1-10.0.9.431 - images are present
2. redownload Mekanism-1.16.1-10.0.9.432 - images still not present
3. take a nap

#### Version (make sure you are on the latest version before reporting):
**Forge:*1,32* 
**Mekanism:*Mekanism-1.16.1-10.0.9.432* 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[latest.log](https://github.com/mekanism/Mekanism/files/5097454/latest.log)

**Comment by pupnewfster** [comment]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

Remove optifine it isn't fully compatible with forge 32.0.107+. Someone on our discord mentioned installing optiforge fixes it but I am not sure if that is true or not but if you really don't want to remove optifine that is something you can try.

**Comment by Bannta** [comment]
Thanks, I did not have OptiForge mod loaded with my PotiFine mod. Adding the mod OptiForge-MC1.16.1-0.1.9 corrected the images from rendering. 
Thanks
