### ISSUE TITLE
Solar Neutron Activator It doesn't work

### ISSUE THREAD

**Issue by angeldeleon1** [mekanism/Mekanism#6492]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I connect nuclear waste to Solar Neutron Activator and it does not fill, I already tried in creative with a tank and also with a fission reactor and it does not work.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.1 / 32.0.77** 
**Mekanism: 1.16.1-10.0.8.431** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Going to make an assumption that this is what wrong (if it isn't feel free to comment and I will reopen the issue), but the port in front of the SNA is the output port the port on the bottom of the SNA is the input port.
