### ISSUE TITLE
I can't get rid of nuclear waste in a fission reactor.The port is set

### ISSUE THREAD

**Issue by lcxlnm** [mekanism/Mekanism#6493]
![QQ图片20200821195134](https://user-images.githubusercontent.com/70017482/90888070-215ecc00-e3e8-11ea-84fa-9138551ae120.png)
![QQ图片20200821195152](https://user-images.githubusercontent.com/70017482/90888075-23288f80-e3e8-11ea-8634-7b751bcf01f8.png)

#### Issue description:
Nuclear waste from a fission reactor cannot be exported. The port has been set to output

#### Steps to reproduce:
1.Activation of fission reactor
2.Nuclear waste has not decreased, but water vapor is decreasing
3.There is no gas in the Chemical tank

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.1-forge-32.0.106
**Mekanism:** Mekanism-1.16.1-10.0.8.431
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by PROBROVOVAyt** [comment]
I have the same problem but here I am transferring the waste to the radioactive waste barrel via the gas tube, I have tried without it but the waste still does not disappear
Minecraft: 1.16.5 Forge 
Modpack: All The Mods 6 1.9.2
Mekanism: Mekanism-1.16.5-10.1.2.457
