### ISSUE TITLE
Condensentrator uses more energy when supplied with energy upgrades

### ISSUE THREAD

**Issue by caseirouowotm8** [mekanism/Mekanism#6496]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Rotary condensentrator uses more energy the more energy upgrades are installed

#### Steps to reproduce:
1. Place down condensentrator, fill it with speed upgrades and make it do some work
2. Install energy upgrades
3. Watch as energy required goes up and not down

It might be due to the low energy storage in the block, and how installing more energy upgrades increases it. But it's still unexpected behaviour

#### Version (make sure you are on the latest version before reporting):
**Forge: 32.0.108** 
**Mekanism:10.0.9.432** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Do you have speed upgrades installed? I believe the condensentrator is one of the machines that speed upgrades up the number of operations that can be performed in one tick (as it only takes a tick in the first place). This means if the energy buffer is not high enough to go at max speed based on the installed speed upgrades it will only use as much energy as it can (the amount stored), and installing energy upgrades will allow it to be closer to its max rate limit and it will "seem" to be using more energy.

**Comment by caseirouowotm8** [comment]
That seems to be the case, as it uses as much energy as is in the buffer except for the last upgrade, where it uses like 70%. The buffer is just too low to handle the speed upgrades without energy upgrades as well.
