### ISSUE TITLE
Digital Miner 

### ISSUE THREAD

**Issue by Ghostwolf7881** [mekanism/Mekanism#6502]
I am in the process of making an automatic Mining/smelting farm using mekanism problem is my digital miner is not working right i would put in an filter for gold and it would mine cobblestone and  granite at 1st i thought it to be a ID issue or something so i tried taking some gold from my ME system and put it in and my gold is turning into cobblestone and granite  i dont know what to do

**Comment by pupnewfster** [comment]
Please don't just delete the issue format it contains information we need.... Also my best guess is you are using a material filter not an item or tag filter.

**Comment by Ghostwolf7881** [comment]
@pupnewfster I have tried all the filter and still experience the same problem

**Comment by pupnewfster** [comment]
You still have yet to provide any useful information about your setup, such as versions and pictures of how your filters/miner is configured.

**Comment by Ghostwolf7881** [comment]
So sorry for this late reply my parents needed my help moving some stuff also sorry for not doing this from the beginning there is no excuse for my stupidity  
![2020-08-25 23-04-46 00_00_42_38 Still005](https://user-images.githubusercontent.com/70248235/91251261-0c0bd980-e729-11ea-86a2-e24834a71105.jpg)
![2020-08-25 23-04-46 00_00_10_20 Still001](https://user-images.githubusercontent.com/70248235/91251263-0ca47000-e729-11ea-8234-0f4608f94c23.jpg)
![2020-08-25 23-04-46 00_00_18_07 Still002](https://user-images.githubusercontent.com/70248235/91251264-0ca47000-e729-11ea-8b69-dbe100afbd18.jpg)
![2020-08-25 23-04-46 00_00_23_05 Still003](https://user-images.githubusercontent.com/70248235/91251266-0ca47000-e729-11ea-99ee-bd605ff7b2c3.jpg)
![2020-08-25 23-04-46 00_00_39_15 Still004](https://user-images.githubusercontent.com/70248235/91251267-0d3d0680-e729-11ea-8ee6-2f1d05d9beef.jpg)
![ver](https://user-images.githubusercontent.com/70248235/91251280-14641480-e729-11ea-983b-ae480c19aa88.PNG)

**Comment by pupnewfster** [comment]
The oredict filter should be `oreGold` and should preview gold ore, the material for gold ore is "stone" so that filter would mine all the different forms of stone.

**Comment by Ghostwolf7881** [comment]
I just tried it and it works Thank you and sorry for being such an idiot and not putting this info up with my 1st post this is my 1st time on github as well as my 1st time having any sort of problem with any mod
