### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by Scornage** [mekanism/Mekanism#6505]
some structures lack texture.
All pipes, wires and logistical transporter.
MC v1.16.1
Forge v32.0.108
Meka v10.0.9.432
I've tried disabling all resource packs and shaders. The result is the same.
I also tried downloading from different resources.
https://www.curseforge.com/minecraft/mc-mods/mekanism
https://aidancbrady.com/mekanism/download/
![2020-08-27_20 50 40](https://user-images.githubusercontent.com/8597461/91312322-500ce600-e7de-11ea-83cc-67be6731705b.png)
![2020-08-27_20 50 54](https://user-images.githubusercontent.com/8597461/91312346-556a3080-e7de-11ea-854d-56b05eac6646.png)
![2020-08-27_20 50 56](https://user-images.githubusercontent.com/8597461/91312369-5b601180-e7de-11ea-921d-7e9ef3e98615.png)

**Comment by Tahakk** [comment]
try to disable the optifine as a whole, disabling shaders & texture packs isn't enough

**Comment by Scornage** [comment]
Thank. That helped. so i can't use optifine with this mod?

**Comment by sagesse-cn** [comment]
> Thank. That helped. so i can't use optifine with this mod?

If use OptiFine mod, plase install additional for OptiForge
