### ISSUE TITLE
incompatible with other mods 

### ISSUE THREAD

**Issue by AllDiagram4276** [mekanism/Mekanism#6509]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I have tried using the most recent version of 1.12.2 mekanism with Speedsterheros but for some reason it crashes my modpack and my server. 

#### Steps to reproduce:
1.Could possibly make it compatible with specific mods? (SpeedsterHeros)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2854 
**Mekanism:** Mekanism-1.12.2-9.8.3.390.jar
**Other relevant version:** 

SpeedsterHeroes-1.12.2-2.2.1
--
#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2020-08-15_16.05.04-client.txt](https://github.com/mekanism/Mekanism/files/5138137/crash-2020-08-15_16.05.04-client.txt)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
#6182
