### ISSUE TITLE
Digital miner not mining

### ISSUE THREAD

**Issue by cc3768** [mekanism/Mekanism#6510]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Digital miner failing to work

#### Steps to reproduce:
1. set Logic
2. Start

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108
**Mekanism:** 10.0.9.432
**Other relevant version:** Engimatic 6 0.2.14

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Video of it happening: https://drive.google.com/file/d/1u4B-IY4i9VQXDY7iPsea7x3EoeVs6sF0/view?usp=sharing
[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Do you have any mods protecting the land?

**Comment by cc3768** [comment]
nope not active at least

**Comment by cc3768** [comment]
ftb utilities is installed its just not in a claimed chunk

**Comment by pupnewfster** [comment]
Are you sure that you don't have anything protecting the land like minecolonies or maybe it is currently trying to mine in a nearby claimed chunk? Also I recommend in `config/forge-client` enabling the experimental lighting pipeline as it will fix the miner rendering strangely and dark at the top.

**Comment by Fenris235** [comment]
I think im getting the same issue. Im playing Enigmatica6-0.3.2 and Mekanism-1.16.4-10.0.18.445 is the version in the pack. Ive set the ModID for the packs ore generation mod (Emendatus Enigmatica) as the filter, no FTB claims or any other chunk protection is active to my knowledge.
the filter shows a cycling image of a bunch of the different ores from the mod in its thumbnail on the filters menu, but when fully powered and running, no blocks are being mined, i can even see a vein of copper ore about 10 blocks from the miner, well within the set range

**Comment by CallMeSage** [comment]
I am also now getting this issue. 

Mekanism 10.0.21 and Enigmatica6 0.4.14

No claimed chunks or anything.

Tried on server and single player neither works.

https://i.imgur.com/dmuXO5h.png

https://i.imgur.com/CR07ykO.png

https://i.imgur.com/O7tEx4m.png
