### ISSUE TITLE
Mekanism Null Blocks

### ISSUE THREAD

**Issue by clarence5192007** [mekanism/Mekanism#6513]
Mekanism has issues with some blocks. For example

![Ultimate Mechanical pipe](https://user-images.githubusercontent.com/65398791/91636840-50072300-ea36-11ea-8ea2-6528b6e7e094.png)
Ultimate mechanical pipe

![Creative inventory](https://user-images.githubusercontent.com/65398791/91637018-c0627400-ea37-11ea-958e-5ad038054a68.png)
Creative Tab

Pls Help!

Mekanism ver: 10.0.9.432
Forge ver: 32.0.108 (Latest)

**Comment by Robball14** [comment]
2 things:

1) check if someone else had the same problem before submitting
2) Unistall Optfine, is the cause of it

**Comment by clarence5192007** [comment]
i think optifine is the cause (issue #6466)

let me try

**Comment by clarence5192007** [comment]
ok optifine is the issue. Thanks!
