### ISSUE TITLE
Ability to add new infusen type

### ISSUE THREAD

**Issue by DoktorAerzt** [mekanism/Mekanism#6518]
**Describe the the feature you'd like**
The ability to add new custom infusen types for the metallurgic infuser. 
I want to add lapis ass an infusen type. 

**Describe alternatives you've considered**
There are no real alternatives when you want the metallurgic infuser with lapis in your custom recipes. 

**Additional context**
It would be great if we can just add infusen types with datapacks.

**Comment by Robball14** [comment]
that's how it works, you can change it with datapacks and stuff like that

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/21

**Comment by DoktorAerzt** [comment]
@Robball14 i was not able to change it with in the datapacks. 
I added a tag for mekanism:lapis and then i added a infusion_conversion for mekanism:lapis and get followring error

`Couldn't load infuse_type tag mekanism:lapis as it is missing following references: mekanism:lapis`

Can you tell me what i am missing? 

infusion_conversion/lapis/from_dust.json
`{"type":"mekanism:infusion_conversion","input":{"ingredient":{"item":"minecraft:lapis_lazuli"}},"output":{"infuse_type":"mekanism:lapis","amount":10}}`

tags/infuse_types/lapis.json
`{"values":["mekanism:lapis"]}`

**Comment by UwUCoopNutt** [comment]
> @Robball14 i was not able to change it with in the datapacks. I added a tag for mekanism:lapis and then i added a infusion_conversion for mekanism:lapis and get followring error
> 
> `Couldn't load infuse_type tag mekanism:lapis as it is missing following references: mekanism:lapis`
> 
> Can you tell me what i am missing?
> 
> infusion_conversion/lapis/from_dust.json `{"type":"mekanism:infusion_conversion","input":{"ingredient":{"item":"minecraft:lapis_lazuli"}},"output":{"infuse_type":"mekanism:lapis","amount":10}}`
> 
> tags/infuse_types/lapis.json `{"values":["mekanism:lapis"]}`
> 
> Full Log https://pastebin.com/eN6Jhua1

did you ever find the solution
