### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by ohyourgosh** [mekanism/Mekanism#6519]
#### Issue description: latest version of mekanism has missing textures for some of the blocks (pink and black box)
Some of the blocks are: Gas burning generator, advanced solar generator, all types of universal cables, charging pad.
I have optifine in my mods as well. I've googled this.problem and i see other people having problems with it as well.
**Forge: X.x.108
**Mekanism: x.x.432

**Comment by pupnewfster** [comment]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

Remove optifine

**Comment by Oct0bass** [comment]
@pupnewfster you should pin the original issue.

**Comment by ohyourgosh** [comment]
Why remove optifine when the last version supported optifine with no problems?

**Comment by pupnewfster** [comment]
Mods don't support optifine... optifine supports mods. The last version "worked" because we had a messy patch to work around a forge bug. Forge fixed the bug, we removed the patch, and optifine reintroduces the bug. That is on them not us

**Comment by ohyourgosh** [comment]
I'll play on the last version until the devs make it compatible with optifine, thanks

**Comment by pupnewfster** [comment]
Again, it is until ***optifine*** becomes compatible with forge again not anything else. This is on optifine to fix
