### ISSUE TITLE
Disappearing items during logistical transport

### ISSUE THREAD

**Issue by Parck92** [mekanism/Mekanism#6521]
Hi guys, i made a set up for some cake autocrafting using the logistical and the assemblicator and i find a problem, the buckets that move from the animal rancer and the assembler always disspears and i have to craft new ones.
I have the Logistical pipes set on green for full buckets and on red for empty ones.
The logistic thing Is set in accordance to that.

Minecraft: 1.16 
ModPack: Valhesia 3

**Comment by thiakil** [comment]
1. Follow the issue template
2. At least provide a reproducible setup we can use

As it stands, there's not enough information to reproduce
