### ISSUE TITLE
No side configuration possible on ELectrlytic Separator

### ISSUE THREAD

**Issue by Mahony1986** [mekanism/Mekanism#6525]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Installed 2 different modpacks for MC 1.15 both with Mekanism. (HR NEw Beginnings / Valhelsia 2)
Both have the issue that there is no side configuration possible for Electrolytic Separator.
Water pipes only conect to rear. then it fills with water. But no output possible.
Similar issue with other machines using gases.

#### Steps to reproduce:
1. Just place Separator
2. No button there for Side config
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 9.10.9
**Other relevant version:** MC 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
The electrolytic seperator in V9 can accept water in the front and the back and outputs gases to either side. It has a side config in V10
