### ISSUE TITLE
Liquid Ethylene

### ISSUE THREAD

**Issue by dave71129** [mekanism/Mekanism#6526]
I have been trying to get my liquid Ethylene from my condenser to my RPC and I cant transfer in no way means. I am playing Valhesia 3

Thanks

#### Steps to reproduce:
1. Connected the Rotary condenser with advance Mechanical pipe on the left side 
2.into the right side of the RPC. 
3. Switch toggeles to accept on all sides liquid
![Untitled](https://user-images.githubusercontent.com/62248902/92293300-60b11080-eef0-11ea-9d24-70357064b85b.png)

#### Version (make sure you are on the latest version before reporting):
forge-1.16.1-32.0.108
Mekanism-1.16.1-10.0.9.432

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Do you have the side config set to auto eject? Because if not without putting your mechanical pipe on pull it won't get transfered.

**Comment by dave71129** [comment]
I dont think I set up auto eject. Let me log in and try. Also I tried to set my mechanical pipe on pull but when i shift right click it does nothing

**Comment by dave71129** [comment]
Thank you ! 
It was the Auto Eject Feature
