### ISSUE TITLE
Registry Object Crash (1.15.2)

### ISSUE THREAD

**Issue by frostfire50** [mekanism/Mekanism#6530]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

Issue description: Registry Object crash when initializing game. Registry object is the basic fluid tank.

Steps to reproduce:
1. Start up the game
2.
3.

Version (make sure you are on the latest version before reporting): 1.15.2
Forge: 1.15.2-forge-31.2.36
Mekanism: 1.15.2-9.10.9.422
Other relevant version:

 If a (crash)log is relevant for this issue, link it here:  https://pastebin.pl/view/de14babf)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Please provide your latest log as the crash report is invalid due to this forge bug: https://github.com/MinecraftForge/MinecraftForge/issues/6374

**Comment by frostfire50** [comment]
https://pastebin.pl/view/39810f6d

**Comment by thiakil** [comment]
You have a couple of bad mods: RandomEnchants, Waila & your options file has something the datafixer doesn't like.

Nothing to do with Mek.

**Comment by frostfire50** [comment]
Yeah it was RandomEnchants causing it. Thank you.
