### ISSUE TITLE
Condensentrating Steam produces Liquid Steam instead of Water

### ISSUE THREAD

**Issue by rehwinkel** [mekanism/Mekanism#6531]
#### Issue description:
This issue is not a bug report. The issue is that condensentrating steam produces liquid steam instead of water, which makes very little sense. I'm not sure if this is intended or if there is a point behind having liquid steam, but I think it makes very little sense.

#### Steps to reproduce:
1. Put steam in Rotary Condensentator
2. Produces "Liquid Steam" instead of water.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108
**Mekanism:** 10.0.9

**Comment by pupnewfster** [comment]
It has to do with balance and how hard it is to get "steam" and "water vapor" though I agree the naming is not great
