### ISSUE TITLE
does the digiminer have a harvest level? (not mining ores that it says are there)

### ISSUE THREAD

**Issue by DoomSquirter** [mekanism/Mekanism#6534]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
using digiminer, doesn't seem to be mining ores I think it thinks are there.  wondering if the digiminer has a harvest level when it mines ores, cause that might explain the issue.

#### Steps to reproduce:
playing allthemods6, has mod allthemodium which has 3 ores of increasing harvest level past diamond pick.
got digiminer and trying to mine unobtainium ore which has a harvest level of 6 I guess.  
digiminer will pick up all other ores with tag: forge:ores
but if I put a sample of unobtainium ore and choose itemstack with no other filters, it says 27 blocks to mine, then goes to zero and returns no ores.  restart, start does exactly same.  shows 27 blocks then zero

#### Version (make sure you are on the latest version before reporting):
**Forge:**  32.0.108
**Mekanism:** 
Mekanism-1.16.1-10.0.9.432
MekanismAdditions-1.16.1-10.0.9.432
MekanismGenerators-1.16.1-10.0.9.432
MekanismTools-1.16.1-10.0.9.432
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
It doesn't have a harvest level but it acts as if it is using an atomic disassembler which flags that it can harvest any block. Does ATM6 have other mods like ftb chunks or minecolonies which may be protecting the land the miner is trying to break?

**Comment by DoomSquirter** [comment]
yes, it has ftb chunks but I don't have any claims in the end where I'm trying this.
that might explain tho regarding the atomic disassembler.  

I just checked the config and there doesn't seem to be a harvestlevel config option in the gear.toml file for the disassembler.

do you happen to know what it defaults to?  I assume diamond?

**Comment by DoomSquirter** [comment]
urgh, should have done this before I replied there.  I spawned in a dissassembler and yeah, it works just fine mining that ore

so I guess the harvest level shouldn't be an issue

so I did place another block anyways since I was testing it.  and now if I go back to digiminer and reset/start it says it has 28 blocks to do but then returns none and sets count to 0

so it definately isn't mining those blocks

**Comment by DoomSquirter** [comment]
ok, I created a ticket in atm6 and they say this is intended behavior, so I'll close this issue then.  thanks for participating!  :)
