### ISSUE TITLE
Metallurgic Infuser won't accept anything piped except redstone and redtone goes to the energy slot

### ISSUE THREAD

**Issue by Dalltop** [mekanism/Mekanism#6535]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Robball14** [comment]
please compile the module, we can't help you if you don't tell us the version
 of forge and mekanism

**Comment by pupnewfster** [comment]
Closing this due to lack of information but my best guess is that you have the side config set to the wrong thing. You want it set to "extra" for items to be able to accept infuse types.
