### ISSUE TITLE
"Ore chunks" from LevelUP mod doesn't feet in Enrichment chamber

### ISSUE THREAD

**Issue by Demeroom** [mekanism/Mekanism#6537]
#### Issue description:
Ore chunks from levelup are suposed to be normal ore blocks, but when u put them into the Enrichment chamber, the machine does nothing.

#### Version:
**Forge:** 14.23.5.2854
**Mekanism:** 9.8.3.390
**Other relevant version:** Minecraft 1.12.2

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
If memory serves they have some weird sort of NBT on them and a workaround is to filter them through an oredictionificator so that they get converted to ores without NBT.
