### ISSUE TITLE
fluid dictionary error

### ISSUE THREAD

**Issue by BasiliskL** [mekanism/Mekanism#6538]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
a lot of Mekanism fluids are named "liquid" instead of just the fluid name which makes other mods that add the same fluids not work with mekanism machines

I used F3+H and mekanisms hydrogen fluid is called liquid hydrogen instead of just hydrogen

brine and sulfuric acid don't have this issue even though there are both liquid and gas because they are just called brine or sulfuricacid in the fluid registry instead of liquidbrine or liquidsulfericacid

I am using mekanism and Immersive intelligence in a modpack and they both add sulfuric acid, hydrogen, chlorine, and brine as fluids but the hydrogen and chlorine aren't compatible even though they should be

#### Steps to reproduce:
1. just do F3+H with mekanism and actually additions installed and look at the liquid hydrogen bucket and hold the left shift and control buttons to view advanced info (may need ceramics installed so you can view liquid hydrogen clay bucket as I can't see a regular bucket of liquid hydrogen)

**Comment by pupnewfster** [comment]
This is no longer an issue due to the existence of fluid tags that mekanism makes use of as of 1.15

**Comment by BasiliskL** [comment]
well it is still an issue in 1.12 which is still the most played modded version

**Comment by pupnewfster** [comment]
Mekanism is only currently developing for MC 1.16
