### ISSUE TITLE
[1.12.2] the game crashes at start with Fex's Vehicle and Transportation mod

### ISSUE THREAD

**Issue by gatoborrachon** [mekanism/Mekanism#6539]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
if i have both Mekanisn and FVTM the game crashes when its loading

#### Steps to reproduce:
1. add both Mekanism and FVTM https://www.curseforge.com/minecraft/mc-mods/fexs-vehicle-mod
2. starts minecraft
3. minecraft will not be able to startup

#### Version (make sure you are on the latest version before reporting):
**Forge:**  14.23.5.2854 
**Mekanism:** 9.8.3.390
**FVTM:**  3.4.44

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/v3iu3E2c

**Comment by pupnewfster** [comment]
Seems they are trying to attach capabilities to an item that only exists as a render and not an actual entity?
```
Caused by: java.lang.NullPointerException
    at net.fexcraft.mod.fvtm.util.Resources.onAttachEntityCapabilities(Resources.java:455)
```
Not sure which end is really causing it but I am going ahead and closing this given we are no longer developing for 1.12

**Comment by gatoborrachon** [comment]
not even crash fixes?

**Comment by pupnewfster** [comment]
We are only actively developing 1.16
