### ISSUE TITLE
Radiation commands require OP level 4

### ISSUE THREAD

**Issue by HueboWasTaken** [mekanism/Mekanism#6542]
The commands used to clear radiation and heal the player should not be confined to op level 4, as this is usually reserved for /stop and the command can't be used in the console. 

/mek radiation commands should be moved to op level 3 or should be executable from the console.

**Comment by pupnewfster** [comment]
I looked into op permission levels some more and decided to move all our commands to op level 2 which is what most vanilla commands are at except for the multiplayer exclusive commands.
