### ISSUE TITLE
Hydraulic Propulusion Module Step Assist not functioning

### ISSUE THREAD

**Issue by Saxymansam** [mekanism/Mekanism#6546]
Playing on a modpack Valhesia 3 0.16 with Mekanism-1.16.1-10.0.9.432 

4/4 installed into the mekasuite boots, jump boost seems jump but the step assist seems to not assist in stepping up. Might me being dumb but I assume Step Assist makes you climb block like if they were stairs or on a horse?

Don't know if it is a bug, or a user error.

**Comment by pupnewfster** [comment]
If you open the module config (default keybind of `\`) what does it have for the stepheight? My guess is either it is lower than you are expecting or another mod in that pack is breaking it.

**Comment by Saxymansam** [comment]
No there is a step height of 2.0 but when you walk into a 1 block tall block it doesn't seems to step up.

**Comment by pupnewfster** [comment]
I feel like another mod in the pack is breaking the autostep then, as it is not that hard to accidentally overwrite all other mod's autostep/flying toggles. The easiest way to figure this out would be to try to reproduce it with just mekanism (in a creative world), and then assuming autostep works properly, look at the mods that Valhesia 3 has that have a way of modifying step height and try removing one at a time until it starts working. Or potentially report it to the Valhesia 3 modpack devs so they can go through the process and report the bug to the proper mod author.

**Comment by Saxymansam** [comment]
I will do just that good sir.

**Comment by BobVonBob** [comment]
For anyone finding this in the future, the mod "Step" is disabling step assist from other mods in Valhelsia 3. I submitted a PR a few days ago that would fix the issue, but until that gets merged just disable that mod if you want to use step assist.
