### ISSUE TITLE
Client Crash: java.lang.NullPointerException 1.15.2

### ISSUE THREAD

**Issue by ClaudiusMinimus** [mekanism/Mekanism#6547]
#### Issue description:
I'm updating my pack, [Survival in Chaos](https://www.curseforge.com/minecraft/modpacks/survival-in-chaos) and replacing Crafttweaker with kubejs since Crafttweaker for 1.15.2 does not have Mekanism support. With a minimal amount of mods loaded everything worked until I added kubejs. 

#### Message:
> java.lang.NullPointerException: Registry Object not present: mekanism:basic_fluid_tank

#### Steps to reproduce:
1. Start Minecraft
2. Crash

**Forge:** tried with both 31.2.36 & 31.2.37
- appliedenergistics2-7.0.4
- JAOPCA-1.15.2-3.2.0.14
- jei-1.15.2-6.0.3.15
- kubejs-2.7.1.15
- Mekanism-1.15.2-9.10.9.422
- MekanismAdditions-1.15.2-9.10.9.422
- MekanismGenerators-1.15.2-9.10.9.422
- MekanismTools-1.15.2-9.10.9.422
- theoneprobe-1.15-2

https://paste.ee/p/aBTzO

**Comment by pupnewfster** [comment]
[m[1;31m[16:54:07] [modloading-worker-7/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: kubejs, class dev.latvian.kubejs.KubeJS
java.lang.RuntimeException: Mixins not found! Please install MixinBootstrap mod!

**Comment by ClaudiusMinimus** [comment]
Sorry about that! MixinBootstrap did not show up on the dependency page, but that fixed it. I with error logs were easier to read for non-java devs
