### ISSUE TITLE
dual slot mechanics like thermal machines

### ISSUE THREAD

**Issue by deadlywolf301** [mekanism/Mekanism#6548]
want to be able to ues your machins with AE/RS for auto craftion but can only insert in to one slot per side of machine needs dual like thermal machins please

**Comment by pupnewfster** [comment]
I don't even understand what this request is trying to say also feature requests should go over https://github.com/mekanism/Mekanism-Feature-Requests/issues

**Comment by deadlywolf301** [comment]
so what i was trying to say is that on one side of your machines it can only perform one action like inserting but once that is set i cannot also extract from the same side witch made automation of some things impossible or verry hard to find a way aroud
