### ISSUE TITLE
Missing textures in Valhelsia 3 [3.0.16]

### ISSUE THREAD

**Issue by Alia-Rose** [mekanism/Mekanism#6551]
In Valhesia 3 I am having issues with quite some missing textures. This includes the following:

- Digital miner
- Security desk
- Charge pad 
- Chemical crystaliser
- Resistive heater
- Modification station
- Antiprotonic nucleosyntesizer
- All the QIO items
- All the cables, pipes, tubes, transporters and conductors

I have the same issue with some missing textures from Mekanism Additions and Generators.

I have downloaded the latest version of the Mekanism mod 10.0.9.432 and replaced the files from the modpack with no change in the results. I am currently using forge 32.0.108.

I'm suspecting that there might be an issue with the modpack, but I'm not sure how to fix it. Any help would be appreciated.

**Comment by pupnewfster** [comment]
This is caused by optifine, supposedly installing optiforge might fix it but I have not tested if it actually does. Removing optifine *will* fix it though.
