### ISSUE TITLE
have no resource picture

### ISSUE THREAD

**Issue by hiritsuki** [mekanism/Mekanism#6553]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

something have no resource picture

#### Steps to reproduce:

[https://i.imgur.com/5qeqtPh.png](https://i.imgur.com/5qeqtPh.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.1-forge-32.0.108
**Mekanism:** Mekanism-1.16.1-10.0.9.432
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Remove optifine
