### ISSUE TITLE
Logistical Transporter issue

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#6554]
#### Issue description:
Upgrading a logistical transporter with items inside it will drop the item in world but also keep them inside the pipe. 
The item in the pipe disappears if it reaches a dead end, but will be inserted into any inventory if it finds one. 

#### Steps to reproduce:
1. put items in logistical transporter
2. make sure there are items in it
3. upgrade by using alloys on it

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108
**Mekanism:** Mekanism-1.16.1-10.0.9.432.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Writing this here so I don't forget to fix it when I am fixing the reported issue, but it seems that upgrading universal cables, pressurized tubes, and mechanical pipes cause the contents to be voided in most cases (at least if it is a new transmitter and hasn't had its contents saved to world).
