### ISSUE TITLE
Crash on sneak-placing Oredictionifier on a Basic Crusher

### ISSUE THREAD

**Issue by iInjection** [mekanism/Mekanism#6559]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Server Crash on sneak-placing Oredictionifier on a Basic Crusher

#### Steps to reproduce:
1. place basic crusher
2. place oredictionifier with sneak on top
3. crash

EDIT: It happens if a Oredictionifier with filters is placed, the server is crashing.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.36
**Mekanism:** 9.10.9.422
**Other relevant version:** Modpack Plunger 1.21

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[crash-2020-09-15_20.17.49-server.txt](https://github.com/mekanism/Mekanism/files/5226937/crash-2020-09-15_20.17.49-server.txt)

**Comment by iInjection** [comment]
Update: Its not only the Crusher, and its not only while sneaking,,

**Comment by pupnewfster** [comment]
This has to do with accidentally calling a client side only method (that I think in my initial experimental port in 1.14 wasn't client side only), I have since fixed this in 1.16, but unfortunately we are no longer developing for 1.15 so it is not going to end up getting fixed in 1.15.
