### ISSUE TITLE
Missing texture w/ optifine (1.16.1)

### ISSUE THREAD

**Issue by JeNaiKe** [mekanism/Mekanism#6561]
#### Issue description:
Using optifine, the following items are missing textures (black and purple square):
 - **Universal Cable**s
 - **Pipe**s and **Conductor**s
 - **Security Desk**
 - **Digital Miner**
 - **Chargepad**
 - **Chemical Crystallizer**
 - **Resistive Heater**
 - **Modification Station**
 - **antiprotonic Nucleosynthesizer**
 - Every **QIO** item
 - **Ballon**
 - specific **Lime Transparent Plastic Slab**
 - **Heat Generator**
 - **Gas-Burning Generator**
- **Bio-Generator**

Both placed and in inventory show the missing texture.

#### Steps to reproduce:
1. Modpack used is "Valhelsia 3" from Curse/Twitch, version 3.0.17
2. Installed Optifine 1.16.1_HD_U_G2

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.1-32.0.108
**Mekanism:** 1.16.1-10.0.9.432
**Optifine:** 1.16.1_HD_U_G2

**Comment by pupnewfster** [comment]
Bug in optifine

**Comment by CallumCarmicheal** [comment]
For those who are searching up this issue and finding this. There is a mod that fixes issues with optifine and forge called [OptiForge.](https://www.curseforge.com/minecraft/mc-mods/optiforge) 

That should work until optifine is fixed @JeNaiKe

**Comment by JeNaiKe** [comment]
Holy! Thanks!
And sorry for bothering

**Comment by GoldMutiny** [comment]
optiforge does not work for me, it crashes my game.

**Comment by pupnewfster** [comment]
Take it up with them, optifine and optiforge is unsupported by us.
