### ISSUE TITLE
placing slabs infront of active lasers will hard-crash the server

### ISSUE THREAD

**Issue by geemayn** [mekanism/Mekanism#6562]
chunk gets corrupt and anyone who loads into that chunk will crash the whole server.

**Comment by Oct0bass** [comment]
"In front" meaning in the laser's path?  Also please provide versions, crash logs, etc.

**Comment by geemayn** [comment]
yes, i placed the slab right in the laser path. also sorry about not following format, not used to github at all. 

it's Valhelsia 2 modpack MC version 1.15.2

the exact situation was me shooting this laser down a really narrow 1-block wide tube. it was only stretching about ~32 blocks since i had an amplifier set to 0 at the end of the room. i accidentally placed a concrete slab against the tube wall while I was building, so the laser was shooting into the empty air directly above the slab, and the server immediately crashes, and it if i try to log in after it starts back up, same result

also a separate bug i noticed, if you have an amplifier shooting out a laser, and pick up the amplifier block while it's active, you can place it down anywhere and it'll shoot out a laser for a split second (and probably kill you) before it refreshes. i think this was even happening with amplifiers i had set to 0.

thank you

**Comment by Oct0bass** [comment]
Yeah, thanks for the extra info.  The devs are no longer maintaining
mekanism for versions less than 1.16, but maybe a newer version for 1.15
fixes it (I jumped straight from playing 1.12 to 1.16 so I wouldn't know)

**Comment by pupnewfster** [comment]
Without the crash report there is not much we can even do to suggest for steps to take/if it may be another mod actually causing the crash
