### ISSUE TITLE
Elite Injection factory wont accept Oxygen

### ISSUE THREAD

**Issue by dragoonz99** [mekanism/Mekanism#6563]
#### Issue description:

I cant get my injecting factory to accept oxygen. I have other factories accepting hydrogine chloride. I'v tried setting up this one exactly how i have the others set up, but it doesnt work. I've looked everywhere for an answer, this is kinda my last resort

![1](https://user-images.githubusercontent.com/71470600/93534823-d1562500-f913-11ea-88c3-e063650affda.png)

![2](https://user-images.githubusercontent.com/71470600/93534841-d6b36f80-f913-11ea-9f01-3fca6a6e9804.png)

![3](https://user-images.githubusercontent.com/71470600/93534848-d87d3300-f913-11ea-9f7a-297425c07167.png)

Ive tried multiple different factories, completely replacing the gas line, moving the factory, inputting on every side, just a regular injection chamber, none of them worked. Any help is appreciated.

sorry if this is the wrong place to post this, i usually only lurk, or quit if i cant find the answer someone else asked. i just rly wanna make this work

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I don't believe there are any recipes in the chemical injection chamber that make use of oxygen which is why it won't accept it so that you don't get "stuck" with it being stored in it.
