### ISSUE TITLE
Factory wont accept oxygen

### ISSUE THREAD

**Issue by dragoonz99** [mekanism/Mekanism#6564]
Just posted this but the thread was closed before i could respond, cant find where to dm someone to ask. 

![1](https://user-images.githubusercontent.com/71470600/93535748-a4a30d00-f915-11ea-8134-e1eb910c9018.png)

![2](https://user-images.githubusercontent.com/71470600/93535754-a7056700-f915-11ea-9005-d04c48af4724.png)

![3](https://user-images.githubusercontent.com/71470600/93535756-a967c100-f915-11ea-9017-af4ea38b69de.png)

![4](https://user-images.githubusercontent.com/71470600/93535760-abca1b00-f915-11ea-8655-ee4ee619959b.png)

![5](https://user-images.githubusercontent.com/71470600/93536050-3874d900-f916-11ea-85e5-6625381a6de3.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
You could just made a comment on the issue, but your picture clearly shows that you want to be inserting into a purification chamber (or purifying factory) based on the recipe, but you are trying to a chemical injection chamber (or injecting factory).

**Comment by dragoonz99** [comment]
sorry about that, i done goofed. thanks for your help bud, stupid moment on me. if theres somewhere more appropriate to ask these questions in the future, can you link me to it?

**Comment by pupnewfster** [comment]
Our discord will probably give better/quicker results: https://discord.gg/kc2YGgk
