### ISSUE TITLE
Can't update recipes with CraftTweaker in 1.15.2

### ISSUE THREAD

**Issue by Crackroach** [mekanism/Mekanism#6565]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Can't update recipes for Mekanism with CraftTweaker as mods.mekanism is not a recognize symbol. 

I have looked on the wiki and copied the exact line and this does not work.

#### Steps to reproduce:
1. Install CraftTweaker
2. Install Mekanism
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-31.2.9
**Mekanism:** Mekanism-1.15.2-9.10.9.422
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
You are using a 1.12 wiki for 1.15 I don't know what you expected, mekanism currently does not have CrT support and only has support for datapacks.

**Comment by Crackroach** [comment]
> You are using a 1.12 wiki for 1.15 I don't know what you expected, mekanism currently does not have CrT support and only has support for datapacks.

I expected the wiki to be up to date. I had figured out that the wiki wasn't helpful.

Thanks for the quick response. I appreciate. That and the mod.

**Comment by Crackroach** [comment]
Any information on how to use your implementation of datapacks?

**Comment by Oct0bass** [comment]
http://wiki.aidancbrady.com/wiki/Recipe_Type_Json_Syntax

**Comment by jaredlll08** [comment]
> I expected the wiki to be up to date. I had figured out that the wiki wasn't helpful.

The wiki is up to date if you choose the right version on https://docs.blamejared.com

Default is 1.16.

**Comment by Crackroach** [comment]
@jaredlll08 I used the 1.15 wiki for crafttweaker to get to know how to do things. It was the mekanism wiki that wasn't up to date. 

Sorry for not being specific on which documentation seemed off.
