### ISSUE TITLE
No keybinding for "Armour Mode Switch" 1.16.1

### ISSUE THREAD

**Issue by Debonairesnake6** [mekanism/Mekanism#6566]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
There is no keybinding for "Armour Mode Switch" so the jetpack has to stay in the regular state.

#### Steps to reproduce:
1. Search for category "mek" in the keybindings

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.1-froge-32.0.108
**Mekanism:** 1.16.1-10.0.9.432
**Other relevant version:** Enigmatica 6 v0.2.17

![image](https://user-images.githubusercontent.com/22126580/93672128-7ab52c00-fa76-11ea-8869-e63af64b8c88.png)

**Comment by pupnewfster** [comment]
The jetpack goes in the chest slot use the chest mode switch key?

**Comment by Debonairesnake6** [comment]
I thought the "Chest Mode Switch" was for the personal chest since the wiki mentioned the jetpack uses the "Armour" key binding: https://wiki.aidancbrady.com/wiki/Jetpack. Nevertheless the "Chest" keybinding did not work. I tried all of them with the jetpack equipped and while the jetpack was in hand, nothing switched the mode.

**Comment by pupnewfster** [comment]
The wiki is somewhat outdated but we renamed a couple of the mode switch keybinds I believe to make it more clear which slot of armor it affects. I will try to look into if I can reproduce it not changing modes on the jetpack though if memory serves when I was testing something about the jetpack the other day I was properly able to have it change modes

**Comment by pupnewfster** [comment]
Got a chance to test and the chest mode switch is properly changing the jetpack's mode. My best guess is maybe one of the other mods in that pack is somehow breaking our check for if the key is pressed.
