### ISSUE TITLE
Some Items doesnt have Texture Pack

### ISSUE THREAD

**Issue by RandomGuyWithNoName** [mekanism/Mekanism#6567]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
This items doesnt have a texture pack
- All tires in pipes, tubes, cables, transporters and conductores
- QIO Importer, exporter, Drive Array, Dashboard and Redstone Adapter
- Gas-Burning Generator
- Bio-generator
- Heat Generator
- Security Desk
- Digital Miner
- Chargepad
- Chemical Crystallizer
- Modification Station
- Resistive Heater
- Antiprotonic Nucleosynthesizer

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108
**Mekanism:** 1.16.1-10.0.9.432
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Please use the search functionality before reporting an issue. Also take a look at the closed issues!
