### ISSUE TITLE
Texture of a lot of items are broken.

### ISSUE THREAD

**Issue by Fotan10** [mekanism/Mekanism#6569]
#### Issue description:
The majority of the items textures are fine.
Though the textures of a lot of items seem to be broken.

**Example of items whose textures are broken:**

* Digital Miner
* Chargepad
* Resistive heater
* Security Desk
* QIO Exporter/Importer/Dashboard/Redstone Adapter
* Modification Station
* Antiprotonic Nucleosynthesizer
* Heat Generator
* The different colored balloons from **Mekanism: Additions**
* Basic/Advanced/Elite/Ultimate Universal Cable
* Basic/Advanced/Elite/Ultimate Mechanical Pipe
* Basic/Advanced/Elite/Ultimate Pressurized Tube
* Basic/Advanced/Elite/Ultimate Logistical Transporter
* Basic/Advanced/Elite/Ultimate Thermodynamic Conductor

#### Steps to reproduce:
1. Open up the game.
2. Enter any world.
3. Look at the item(s), for example "Digital Miner". Whether it is placed in the world, in your inventory, in the creative inventory or in JEI page doesn't matter. The texture of these items are broken everywhere.

**Forge:** 1.16.1-forge-32.0.108
**Mekanism:** Mekanism-1.16.1-10.0.9.432
**Other relevant version:** Not tested on other versions of Mekanism and Forge/Minecraft.

**Comment by Robball14** [comment]
Delete Optifine
