### ISSUE TITLE
Dynamic tank

### ISSUE THREAD

**Issue by Minecraft2p0** [mekanism/Mekanism#6572]
the dynamic tank takes in hydrogen, but unfortunately does not release it again. the tank is built correctly. am i doing something wrong?

I use MC version 1.16.1 with the latest mod version and Forge ... 108

It would be great if the problem could be fixed for version 1.16.1 as I am using it in a modpack.

**Comment by Seniorendi** [comment]
Can you send the latest log here?

**Comment by pupnewfster** [comment]
We are no longer updating the 1.16.1 version as there is no reason to the next release will be for 1.16.3. And I am not quite sure what you mean by "does not release it again". I don't think the dynamic tank has auto eject so you would need to be using a configurator to set a tube to pull to extract it from the tank.
