### ISSUE TITLE
Sulfuric acid being voided 1.16.1

### ISSUE THREAD

**Issue by Asmodeus-69** [mekanism/Mekanism#6573]
Forge version 32.0.108 
Mekanism verson 1.16.1-10.0.9.432
Enigmatica 6 modpack
Currently have sulfuric acid auto crafted into a dynamic tank. Using advanced pressure tube to transport to a chemical dissolution chamber. The acid is just being voided once the chamber is full. Disconnected the pressure tube and let the acid build up in the tank and once I reconnected the tube it voided the acid. Only disconnected one tube so there was more than enough built up to fill the buffer.
Using the same system for brine and it is working fine.

**Comment by pupnewfster** [comment]
The tubes have a buffer, use a network configurator on them my guess is it is just filling the buffer.

**Comment by Asmodeus-69** [comment]
Ok, you are correct. I was not aware of the different buffer size between the advanced mechanical pipe (16000mb) and the advanced pressure tube (192000mb). I figured the same tier of pipes would be more similar.

Thanks.
