### ISSUE TITLE
QIO Crafting Grid

### ISSUE THREAD

**Issue by Jaymus3** [mekanism/Mekanism#6574]
**Describe the the feature you'd like**
I'd like the QIO dashboard and/or QIO portable dashboard to have a crafting grid option.  Not having one turns what could be a really useful alternative to refined storage/AE2 bulk storage into mostly an item teleporting network.

**Describe alternatives you've considered**
I attempted to use a QIO network as my primary storage for a little while but the lack of a crafting grid made the portable dashboard niche in usefulness.

**Additional context**
The crafting grid upgrade could be made fairly expensive as it does give a considerable upgrade to the system's usability.  Requiring a formulaic assemblicator in the recipe seems like good flavor.

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/94
