### ISSUE TITLE
Quantum Entangloporter Auto Eject stupidly slow

### ISSUE THREAD

**Issue by EternalClickbait** [mekanism/Mekanism#6575]
**Issue**
At the moment, the Quantum Entangloporter only ejects fluids/gases at 256mb/tick. I havent tested with items and RF, but I believe it's a similar issue.

**Alternatives**
It is possible to use pull mode on pipes, or simply to use a large pipe loop instead of the quantum entangloporter, but that defeats the entire purpose of it. As it is, I'm being forced to do things like this to get decently high enough transfer rates
![2020-09-27_12 39 23](https://user-images.githubusercontent.com/48875125/94354503-ff2f2c80-00be-11eb-91b3-0d34e9acf2f8.png)

**Proposed Solution**
Make the Quantum Entangloporter automatically eject it's entire 'inventory'/stored buffer each tick.

**Comment by pupnewfster** [comment]
As of V10 the auto eject default is 1,024 mB/t, and if you want the quantum entangloporter to eject faster just change the rate in the config.
