### ISSUE TITLE
QIO crafting grid

### ISSUE THREAD

**Issue by nathanenns** [mekanism/Mekanism#6576]
With the addition of the QIO system, which I love, the only thing lacking is either a crafting grid built into the QIO dashboard, or Portable QIO dashboard.  

In playing with mek 10 I have noticed I still needed either an AE2/RS system, or regular crafting benches all over the place to craft items as I built up my base, and the factories.  I would prefer a crafting grid built into the 2 QIO dashboards, or perhaps an upgrade you can add to them that adds a crafting grid functionality to it

**Comment by Jaymus3** [comment]
I just opened this issue yesterday so maybe use the search for feature requests.  Turns out they have another github repo for specifically feature requests. https://github.com/mekanism/Mekanism/issues/6574 https://github.com/mekanism/Mekanism-Feature-Requests/issues/94

**Comment by nathanenns** [comment]
Oh, good to know it was already requested.  I didn't notice the other repo, I did search for this, but didn't see anything.
