### ISSUE TITLE
[1.7.10] Soft crash on world start

### ISSUE THREAD

**Issue by skull1** [mekanism/Mekanism#6577]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
i wanted to add mekanism to my agrarian skies 2 mod pack,but the game soft crash every time i try to open world.
I know its an old version,but if u know an easy solution or can help...
I tried to disable copper and tin per chunks in config, as other report suggested, but nothing changed.
With a clean installation of ags2 it can added with no problems, so i suspect an interaction with my current added mods or config.

#### Steps to reproduce:
1.select world
2.play
3.soft crash(back on singleplayer/multiplayer menu)

#### Version (make sure you are on the latest version before reporting):
Forge: forge-10.13.4.1614 
Mekanism: Mekanism-1.7.10-9.1.1.1031 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/j7HpuRaA

**Comment by thiakil** [comment]
```
[Client thread/ERROR]: Unable to parse metadata from sanguimancy:textures/blocks/AltarDiviner.png
java.lang.RuntimeException: broken aspect ratio and not an animation
```

definitely not mekainsm

**Comment by thiakil** [comment]
you probably have some broken recipes somewhere from another mod
