### ISSUE TITLE
Digital Miner picks up mekanism machines if set to Ancient Debris

### ISSUE THREAD

**Issue by OutcastZeroOne** [mekanism/Mekanism#6578]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Set Filter for Ancient Debris
2. have power generation for miner 
3. run DM

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108
**Mekanism:** Mekanism-1.16.1-10.0.9.432
**Other relevant version:** Minecraft 1.16.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Can you show a picture/better describe how you set the filter?

**Comment by OutcastZeroOne** [comment]
![2020-09-28_10 27 47](https://user-images.githubusercontent.com/8162248/94465884-70c9b200-0175-11eb-9c45-07edad9fc4d8.png)
![2020-09-28_10 27 59](https://user-images.githubusercontent.com/8162248/94465893-732c0c00-0175-11eb-8352-78e93191527c.png)
![2020-09-28_10 28 26](https://user-images.githubusercontent.com/8162248/94465897-74f5cf80-0175-11eb-823e-a1328a8d83a8.png)

**Comment by pupnewfster** [comment]
Material and ItemStack filters are not the same thing, most mekanism blocks use "Iron" as their material which seems to also be the material that ancient debris sets.
