### ISSUE TITLE
qio sys integrated crafting

### ISSUE THREAD

**Issue by anontaco** [mekanism/Mekanism#6579]
pleaseeee add integrated crafting table to the qio system and possibly the wireless terminal ive had to stick to refined storage simply because the qio system is lacking crafting availability which feels a little heartbreaking considering how expensive it is and how absolutely amazing it would be to use otherwise. ps thank you guys for the greatest mod which has kept me away from sleep for many many weeks

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/94

**Comment by Robball14** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/94

**Comment by anontaco** [comment]
sorry for the duplicate i didnt see it before thank you
