### ISSUE TITLE
Digital Miner Disappear

### ISSUE THREAD

**Issue by KhanhPham05** [mekanism/Mekanism#6580]
### Issue description:
After I leave my Digital Miner from a far place from my base, It will disapear 

#### Steps to reproduce:

1. place and activate a WayStone near by ut spawn then place the Digital Miner as far as you can
2. Fully Upgraded it [Includes Speed, Energy and Anchor] and fully power it then let's it run
3. Place the WayStone nearby it then go back to your spawn WayStone
4. Exit the entier Minecraft game then log back to the game then load ur world, go back to ur miner and see it disappear

#### Mods / Forge Versions : [ All in 1.16.1]
**Forge:** : 1.16.1 - 32.0.108
**Mekanism:** 1.16.1 - 10.0.9.432
**Other relevant version:** 
 All mekanism add-on are version 10.0.9.432
 
WayStone mod: 1.16.1-7.1.1
 AzureDoom Chunk Loader: 1.16.1-1.0.1
 Xaeo's Minimap: 20.20.1_Forge_1.16.1

**Comment by pupnewfster** [comment]
Could you please provide your latest log, I am somewhat curious to see if maybe one of the other mods you have is causing a vanilla bug that spams the log about chunks failing to save because if so it would be because the chunk you put the digital miner in never ended up saving.

**Comment by KhanhPham05** [comment]
https://pastebin.com/CBXhNfpQ 
here is your latest.log file

**Comment by pupnewfster** [comment]
Well I was correct that something is causing the chunks to not save:
```
[14:19:02] [Server thread/ERROR]: Failed to save chunk -289,358
java.lang.NullPointerException: null
	at net.minecraft.world.chunk.storage.ChunkSerializer.func_222649_a(ChunkSerializer.java:421) ~[?:?]
```
but I am not quite sure what it is due to, but my suspicion is that it is not related to Mekanism.

**Comment by KhanhPham05** [comment]
ok because I have a mod for chunk loading
with ID is 'chunk'
