### ISSUE TITLE
Mechanical Pipes broke after every world loading

### ISSUE THREAD

**Issue by KhanhPham05** [mekanism/Mekanism#6581]
#### Issue description:
 The Mechanical Pipes [ I use Elite tier] will not transfering water everytime I log back in my world

#### Steps to reproduce:
1. Place the Mechanical Pipes then connect it with a running Fluid Pump [Fully Upgraded except Fillter]
2. Connect the pipes with the HDPE sheet processing system and the HDPE out put will be the Quantum Storage Unit
3. Wait for 10 seconds then exit the entier game then log back to the world. You can see the pipes will not transfering water even it have the full water texture inside the pipes

#### Mods/ Forge Versions [ All in 1.16.1] :
**Forge:** 32.0.108
**Mekanism:** 10.0.9.432
**Other relevant version:**   Quantum Storage 1.16.1-5.2.0
all mekanism addons

**Comment by pupnewfster** [comment]
I am not able to reproduce this, I am assuming based on the log back in, that it is single player (is this correct)? Also could you provide an image of your setup, given maybe there is some weird thing going on with how things are structured so my small test setup isn't reproducing it.

**Comment by KhanhPham05** [comment]
I think the electrical pump broke every i go back to my base from nether and i have to remove one of the pump or enter the Pump GUI so it can back pumping water

**Comment by pupnewfster** [comment]
If you are in the nether the pump won't be working while you are there unless the chunk is chunk loaded

**Comment by KhanhPham05** [comment]
I am in nether so the pump will not work i know but the problem is when i turn back to the overworld, it still broke
