### ISSUE TITLE
[Request] New Audio for Smelting Factory

### ISSUE THREAD

**Issue by SteveHeist** [mekanism/Mekanism#6584]
**Describe the the feature you'd like**
As of the 9.10.9 version of Mekanism for Minecraft 1.15.2, the Smelting Factories create this *insane* racket including a ringing noise akin to tinnitus. I would like to request a new audio file for them in a future update, if they haven't already been replaced, because it's kind of headache inducing.

**Comment by Robball14** [comment]
Mekanism V9 will be no longer updated.
if the sound annoys you, use muffler upgrades or disable game sounds

**Comment by pupnewfster** [comment]
I don't think there are currently any plans to change the sound for the energized smelter/smelting factories. You can do as Robball suggested or also use a resource pack that changes the sound to your liking.
