### ISSUE TITLE
[1.12.2] Bin Duplication

### ISSUE THREAD

**Issue by AshtonMemer** [mekanism/Mekanism#6586]
#### Issue description:
It is possible to duplicate empty Basic Bins (and possibly Advanced and Elite, have not tried them) with Tier Installers. This does not work on bins with items in them, so item duplication is impossible with this method. Don't know how useful the duplication of Basic Bins is, but I decided to report this anyway.

#### Steps to reproduce:
1. Place Basic Bin & Advanced Tier Installer into crafting grid.
2. Craft Basic Bin w/ Tier Installer, giving you the bin, yet leaving a Basic Bin inside the crafting grid.
3. Place new Basic Bin inside of crafting grid to remove Tier Installer, leaving you with two Basic Bins and your original Tier Installer.
4. Repeat the process.

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-14.23.5.2847** 
**Mekanism: 1.12.2-9.8.3.390** 
**Other relevant version: N/A** 

Producing the bug: https://i.imgur.com/hYEnq1C.gif

**Comment by pupnewfster** [comment]
We are no longer developing for 1.12, but I tested to make sure this no longer happens in 1.16, and I am not able to reproduce this is the latest dev of Mekanism for 1.16.3 and Refined storage for 1.16.3. My best guess it the rewrite/overhaul I did to our implementations of the bin recipes in 1.15 fixed/made this issue go away.
