### ISSUE TITLE
Compatibility with Angel ring + Botania 

### ISSUE THREAD

**Issue by Mingu2209** [mekanism/Mekanism#6587]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

We can't fly in our server with some mods. According to other messages that we saw, seems that it was an incompatibility with your mod. We can't fly with Angel Ring and Flügel tiara from Botania. We saw that there was an update to solve it, but the problem is still the same. Is there any way to solve it? Thanks a lot in advance for your hard work!

#### Steps to reproduce:
1. Install Mekanism latest version Mekanism-1.16.1-10.0.9.432
2. Install any angel ring mod + botania
3. Use ring or tiara.
4. Flight will not work.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108
**Mekanism:** 1.16.1-10.0.9.432
**Other relevant version:**  angelring 1.16.1-1.3.1, botania 1.16.1-403

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_) We don't have any crash or log in the server

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I will look into this when I have a chance but my guess given we rewrote the system to be properly compatible with other mods is that maybe another mod you have installed is breaking it. Are you able to fly with them if you remove mekanism?

**Comment by pupnewfster** [comment]
My best guess is one of those two mods is doing something wrong. I tested with the 1.16.3 dev version of mek against the 1.16.3 version of angel rings and was properly able to use a ring to fly.

**Comment by Mingu2209** [comment]
Hi!! 

Sorry for the late reply. 2 hours ago I discovered that the issue was from Vulcan. Thanks a lot for answering that fast anyway and sorry for the inconvenience
