### ISSUE TITLE
 OptiFine HD U G2 have display issue

### ISSUE THREAD

**Issue by rickyhoho** [mekanism/Mekanism#6589]
![image](https://user-images.githubusercontent.com/24563814/95055029-4784c500-0725-11eb-8781-4376c4ed34b0.png)
the photo showed that many item cant show cause by optfine.
for example, digital miner and different type of tube have this bug
the optfine version is 
OptiFine HD U G2

**Comment by Robball14** [comment]
1) you provided nearly no information
2) check if someone else already had the same trouble
3) It's optifine fault, delete it

**Comment by rickyhoho** [comment]
yes
i have deleted all mod except optifine and mekanism, as i delete optfine.
As the problem should be make by optifine, i just report it for a issue

**Comment by 04Slash** [comment]
(For anyone who wants to use Optifine and Makanism and actually uses the search feature) You can downgrade mekanism to Mekanism-1.16.1-10.0.8.431.jar and this will fix the issue. The newest version breaks the textures when Optifine is installed.

**Comment by rickyhoho** [comment]
> (For anyone who wants to use Optifine and Makanism and actually uses the search feature) You can downgrade mekanism to Mekanism-1.16.1-10.0.8.431.jar and this will fix the issue. The newest version breaks the textures when Optifine is installed.

thank for your reply

**Comment by pupnewfster** [comment]
> (For anyone who wants to use Optifine and Makanism and actually uses the search feature) You can downgrade mekanism to Mekanism-1.16.1-10.0.8.431.jar and this will fix the issue. The newest version breaks the textures when Optifine is installed.

You mean OPTIFINE breaks the textures nothing about it is on mekanism's end. Optifine is reverting a fix that forge did that the latest version of mekanism relies on instead of a messy ugly hack I did as a workaround before hand.

**Comment by 04Slash** [comment]
> > (For anyone who wants to use Optifine and Makanism and actually uses the search feature) You can downgrade mekanism to Mekanism-1.16.1-10.0.8.431.jar and this will fix the issue. The newest version breaks the textures when Optifine is installed.
> 
> You mean OPTIFINE breaks the textures nothing about it is on mekanism's end. Optifine is reverting a fix that forge did that the latest version of mekanism relies on instead of a messy ugly hack I did as a workaround before hand.

I should have stated that the incompatibility is between the latest version of mekanism and Optifine. I didn't mean that Mekanism was at fault at all. My apologies if it came off that way.
