### ISSUE TITLE
Pipes and energy cubes reset/stop working when world is loaded in single player and on server.

### ISSUE THREAD

**Issue by Angelo2724** [mekanism/Mekanism#6591]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The energy cubes as well as the universal cables stop working when you load into a single player world or a server. The cubes stop outputting power and all of the cables look like they are placed down and not attached to anything. In the picture the cable on the right shows the issue I am describing and the one on top shows that the cable connects when you place it down, but that it will disconnect if you reconnect to the world. 

#### Steps to reproduce:
1. Place down energy cube
2. Connect pipes
3. Re-log into the world

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2854
**Mekanism:** 1.12.2-9.8.3.390

#### If a (crash)log is relevant for this issue, link it here: No crash log

Picture of the issue:
![2020-10-05_14 06 05](https://user-images.githubusercontent.com/18407348/95116278-c8879080-0714-11eb-8f51-0c12531e6554.png)

Mod list:
[filesnames.txt](https://github.com/mekanism/Mekanism/files/5329327/filesnames.txt)

**Comment by pupnewfster** [comment]
Not really sure what is going on there and I don't recall any bugs like that from when we used to work on 1.12. I am going ahead and closing this as we aren't actively developing 1.12 anymore, but if you provide your `latest.log` file from when this happens maybe it will have something in it that we can point you towards.
