### ISSUE TITLE
Optifine breaks Mekanism pipes and cabels

### ISSUE THREAD

**Issue by Simps0909** [mekanism/Mekanism#6594]
Optifine breaks mekanism items meaning they show up as broken tecture items. I have here some screenshots of the broken tecture items.
![2020-10-06_23 04 48](https://user-images.githubusercontent.com/52635673/95254432-92d3cc00-0828-11eb-9e2d-bbb7f5336bb5.png)
![2020-10-06_23 04 43](https://user-images.githubusercontent.com/52635673/95254435-9404f900-0828-11eb-8c24-29cb2b9369c2.png)
![2020-10-06_23 04 38](https://user-images.githubusercontent.com/52635673/95254440-949d8f80-0828-11eb-9681-9cc498b6124f.png)
![2020-10-06_23 04 26](https://user-images.githubusercontent.com/52635673/95254444-95362600-0828-11eb-98c6-92a74abeb174.png)
![2020-10-06_23 04 24](https://user-images.githubusercontent.com/52635673/95254445-95cebc80-0828-11eb-9578-f1184228acca.png)
![2020-10-06_23 04 21](https://user-images.githubusercontent.com/52635673/95254450-96675300-0828-11eb-8a25-2d50bb4be96c.png)
![2020-10-06_23 04 18](https://user-images.githubusercontent.com/52635673/95254455-96ffe980-0828-11eb-9cc0-6bf5c22cc251.png)
![2020-10-06_23 04 17](https://user-images.githubusercontent.com/52635673/95254458-97988000-0828-11eb-8612-070f0e41d9fe.png)
![2020-10-06_23 04 14](https://user-images.githubusercontent.com/52635673/95254461-98311680-0828-11eb-9ae5-99befb8fa562.png)
![2020-10-06_23 04 09](https://user-images.githubusercontent.com/52635673/95254464-98c9ad00-0828-11eb-9062-e18467ab7671.png)
![2020-10-06_23 04 08](https://user-images.githubusercontent.com/52635673/95254466-98c9ad00-0828-11eb-88c3-fd0daefd772c.png)
![2020-10-06_23 04 06](https://user-images.githubusercontent.com/52635673/95254467-99624380-0828-11eb-9d9d-d0c4a048c035.png)

![IMG_20201006_230035](https://user-images.githubusercontent.com/52635673/95254127-19d47480-0828-11eb-94a2-8f9d11dff568.jpg)

**Comment by pupnewfster** [comment]
Congratulations? What do you want us to do about it. Optifine is a closed source mod it isn't like we can submit a PR to fix them reverting a fix by forge pertaining to a bug that was in forge code (not even one that was in vanilla code)...
