### ISSUE TITLE
Digital miner's filter misbehaves

### ISSUE THREAD

**Issue by Zaflis** [mekanism/Mekanism#6601]
#### Issue description:
I can't get digital miner to mine specific ores. From what i can tell the correct way is to use either Tag Filter or Material Filter. Now i do know tag filter * ores * (without spaces) that will mine only all ores except certus quartz and then mod filter for applied energistics would try to look for every single block entity from that mod, including the certus ore. I tried thing like tag filter for * certus * but it only shows blank, so that doesn't work.

#### Steps to reproduce:
1. Make 2 material filters, 1 for diamond ore and other for emerald ore. Set Inverse mode off, silk touch on.
2. Now start miner, you should see it found maybe 200k things to mine and inventory starts filling with stone. We don't want stone.
3. Now set Inverse mod on and start miner again. It still finds over 50k things to mine, this time dirt comes in. Why is this? Neither dirt or stone were in the filters.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.1-32.0.108 ** 
**Mekanism: 1.16.1-10.0.9.432 ** 
**appliedenergistics2-8.0.0-beta.4 **

**Comment by Zaflis** [comment]
It seems the material filter is responsible of adding all the stone in the world. When i try to add certus to the * ores * tag filter it only works with mod filter if i don't want also stone.

But this doesn't help too much with my original case that we already have so much of the other ores that we only want few things like diamonds, gold and certus at this point. Others flood the containers needlessly.

**Comment by pupnewfster** [comment]
Last I checked applied energistics is not adding certus quartz ore to any block tags. In regards to material filters they are for the internal material that the block declares (for both diamond and emerald that is stone (or other things that inherit the same properties as stone), most likely you want the itemstack filter not the material filter).

**Comment by Zaflis** [comment]
Yeah that works, it's just very deceiving that filters normally rotate the block types that the filter concerns. Just in this case it sticks with the one set in material filter. Maybe you can change that? Or otherwise does anyone actually want material filter to behave like it does, not focusing on what it's filtered to?

**Comment by pupnewfster** [comment]
Both material and itemstack filters behave as intended, though I do agree the material filter probably should cycle through the different things that match the material (and I will change it to do so).
