### ISSUE TITLE
1.16.3-[java.lang.IllegalStateException: Failed to load description for particle mekanism:laser]

### ISSUE THREAD

**Issue by SDUBZ** [mekanism/Mekanism#6604]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
crashes on load up

#### Steps to reproduce:
1.load up 
2. wait for things to load 
3.crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.3-34.1.14
**Mekanism:** Mekanism-1.16.3-10.0.11.436 plus addons all 436
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2020-10-09_15.04.02-client.txt](https://github.com/mekanism/Mekanism/files/5352478/crash-2020-10-09_15.04.02-client.txt)
[latest.log](https://github.com/mekanism/Mekanism/files/5352479/latest.log)

**Comment by RedProjectZer0** [comment]
@SDUBZ 

This is a compatibility problem with the mod "Overloaded+Compressed+Blocks-1.16.3-1.0.14"
**----------------------------------------------------------------------------------------------------------**

**Note for the Dev:**
Also there is a compatibility  problem with the mod "torchslabmod-1.16.3_v1.6.17"
[crash-2020-10-09_13.42.30-client.txt](https://github.com/mekanism/Mekanism/files/5354725/crash-2020-10-09_13.42.30-client.txt)
[latest.log](https://github.com/mekanism/Mekanism/files/5354727/latest.log)

**Comment by pupnewfster** [comment]
#6602
