### ISSUE TITLE
Creative Bin causes server lag with AE2 storage bus when autocrafting

### ISSUE THREAD

**Issue by ToMe25** [mekanism/Mekanism#6608]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When a Creative Bin is attached to a ME system using a Storage Bus, you try to order the crafting of an item using the content of the Creative Bin, the internal server will freeze for a few seconds, until it finally finished calculating the neccessary resources.

#### Steps to reproduce:
1. Build a simple ME system
2. Attach a Creative Bin using a Storage Bus
3. Teach the ME system a recipes that uses the contents of the Creative Bin
4. Try to let the ME system craft one of the new recipe
5. See the internal server freeze for some time

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.12
**Mekanism:** 10.0.11
**Applied Energistics 2:** 8.1.0-alpha.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by thiakil** [comment]
What item(s) did you test with? If the recipe has items that need NBT, it ain't a Bin issue

**Comment by ToMe25** [comment]
With a bunch of different things, the easiest(thus the one i tested in a new world again after restarting the game) was having sand in the bin(just plain sand, without any nbt) and trying to craft sandstone from it(again, without nbt afaik).

**Comment by pupnewfster** [comment]
This sounds like it is a bug on AEs end? The bin literally only has a single slot so its not like it has to be iterated over a bunch or anything.

**Comment by ToMe25** [comment]
I reported that here, because i didn't have the same issue with creative Storage Drawers, but if you say its an AE2 issue i will go report it there.

**Comment by pupnewfster** [comment]
As I said my guess is it is on their end, though you could always profile it to see what the hotspot is in the code.

**Comment by ToMe25** [comment]
I am going to try and find where it is stuck for so long, but i guess it will be looping between AE2 and Mek code.

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism/commit/4e79a768c608df7fd44fd21f9209cffd8cb26a58 very minorly improves the performance by making our sided item handler not need to query the world the ~33 million times AE2 queries us. I am going to go ahead and close this though as discussed on discord the bug is on AE2's end as we follow the IItemHandler spec correctly.
