### ISSUE TITLE
Crash en changeant de serveur

### ISSUE THREAD

**Issue by Dylandt1** [mekanism/Mekanism#6610]
####Description:

Hello,

I recently had the project to open a minecraft server with mods, mekanism being a must-have mod I would like it to be on my server. During the installation of the server everything went very well, the server starts without problems and runs well. But the problem comes from the client, at least that's what I understood, or from a bug that cuts the connection between the client and the server and the client crashes. The answer of this last one is:

Translated with www.DeepL.com/Translator (free version)
The game crashed whilst unexpected error
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism: Tools (mekanismtools)
Exit Code: -1

#### Steps to reproduce:

1. Installing a server under ubuntu version 20.04.1
2. Installing a Bungeecord server with two configured servers
3. Install two forge 1.12.2-14.23.5.2854 servers, one with mekanism mods and a lobby without mods
4. Connect to the server (lobby by default) then from the lobby connect to the server with the mods.

#### Version :

**Forge:*1.12.1-14.23.5.2854* 
**Mekanism:*Mekanism-1.12.2-9.8.2.390* 

####Rapport de plantage:

https://gist.github.com/Dylandt1/1094d0ea2b084fb19f8703d7257aeb35

Thank you for your possible answers.

**Comment by TepperPepper666** [comment]
While Mekanism is no longer being worked on for 1.12 I noticed you have an outdated version (latest for 1.12 is 1.12.2-9.8.3.390) so maybe try updating to the latest 1.12 version?

**Comment by pupnewfster** [comment]
We are no longer developing 1.12, and I am not quite sure as I never ran into that bug personally (though I knot there was talk about it over #5797). My best guess is that Bungeecord is probably not properly having the various things fire (though this is just a wild guess)
