### ISSUE TITLE
1.16.3 Mekanism 10.0.x - Formulaic Assemblicator Dupe items

### ISSUE THREAD

**Issue by igentuman** [mekanism/Mekanism#6614]
Sometimes when you remove items from assemblicator, it dupes items. 
This is happening on my server for a normal non operator user. I can reproduce the same issue in solo world as well.
I don't know the exact steps to reproduce. But you can follow some steps on videos.

https://youtu.be/mh8azYUAA64
https://youtu.be/7YCS1pNFdjI

Forge 1.16.3-34.1.12 - 1.16.3-34.1.17
Mods installed:
ftb-chunks-1.1.2.36.jar
ftb-gui-library-1603.1.1.19.jar
jei-1.16.3-7.5.0.43.jar
Mekanism-1.16.3-10.0.10.434.jar
MekanismAdditions-1.16.3-10.0.10.434.jar
MekanismGenerators-1.16.3-10.0.10.434.jar
MekanismTools-1.16.3-10.0.10.434.jar

Getting many of these errors in logs
[Server thread/ERROR] [Mekanism/]: Critical error: Formulaic Assemblicator had items left over after organizing stock. Impossible!

I had no such issue in 1.16.1. It appears only in 1.16.3

**Comment by igentuman** [comment]
Well. Seems fixed now. Thank you

**Comment by pupnewfster** [comment]
Actually, I haven't released the version with the fix yet (planning on doing that probably in a few hours).

**Comment by igentuman** [comment]
I built it from sources
