### ISSUE TITLE
[1.12.2] - Ore Regen spam on every restart.

### ISSUE THREAD

**Issue by Frost212** [mekanism/Mekanism#6616]
#### Issue description:
After enabling the settings for ore regeneration (Both of them), the ores regenerated fine. Afterwards i disabled the settings in the config to avoid the server console spam ([Sever thread/INFO] [Mekanism]: Regenerating Ores at chunk ]x, x] ). But every time the server restarts or is booted up it still goes through and spams my console and log file with a message for every single chunk. 

#### Steps to reproduce:
1. Enable ore regeneration via EnableWorldRegeneration and WorldRegenVersion
2. Boot server up, wait for it to go through all the generation, change values back to false / 0 and wait for next restart
3. look at log file after the restart. 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2847
**Mekanism:** 1.12.2-9.8.3.390
**Other relevant version:**

**Comment by pupnewfster** [comment]
We are no longer actively developing for 1.12, and I am 95% certain I fixed this at some point during 1.15 (if not then in the port to 1.16). On the slight chance I am wrong and this still is happening in 1.16.3 just comment and I will reopen it and look at it again.
