### ISSUE TITLE
[1.16.3] Dosimeter always shows 99.999 nSv

### ISSUE THREAD

**Issue by ultranine** [mekanism/Mekanism#6618]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
No matter where you are in the world, or if a radiation field is nearby, or if you've even come in contact with radiation, both the dosimeter item and MS module always show 99.999 nSv, even on a completely new world. The numbers do not change when near a radioactive spot.

#### Steps to reproduce:
1. Obtain a dosimeter
2. Use dosimeter
3. ???

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.17
**Mekanism:** 10.0.11.436
**Other relevant version:** 1.16.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Are you per chance looking for a Geiger counter? The dosimeter shows you what radiation level you are at (like how much you have absorbed), so if you are in creative or have a hazmat suit on/mekasuit with the radiation protection modules on you won't end up absorbing any radiation.

**Comment by ultranine** [comment]
Occurred while wearing a hazmat suit in creative. I then generated an entirely new creative world and still got a 99.999.

**Comment by pupnewfster** [comment]
Given you didn't answer my question based on the information provided I am going to assume my initial guess was correct that you are confusing the Dosimeter for the Geiger counter. As in creative you won't absorb any radiation so it wouldn't show a number higher than the base level.
