### ISSUE TITLE
Configurator wrench tag doesnt match Thermal's wrench tag

### ISSUE THREAD

**Issue by RogueLogix** [mekanism/Mekanism#6622]
#### Issue description:
Configurator is tagged with `forge:wrenches` instead of `forge:tools/wrench`

It is my understanding that KingLemming and McJty use the `forge:tools/wrench` tag for their wrenches, while mekanism uses `forge:wrenches`. I only check for forge:tools/wrench, so the configurator doesn't work with my mod.

From a quick search over the repo, it appears that this also applies in 1.15.2 where a Thermal wrench does co-exist with Mekanism's wrench.

This isn't technically a strictly *Mekanism* issue, but this seem like the right place to open the issue as it appears to be the outlier.

#### Steps to reproduce:
1.  check tags for items?

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.19 (MDK)
**Mekanism:** 1.16.3-10.0.11.436

**Comment by pupnewfster** [comment]
I will add a workaround and just add to both, but we are just following the same scheme that forge did with `forge:shears` by putting it in `forge:wrenches`
