### ISSUE TITLE
[MC 1.16.3] Missing Fireanimation at MekaSuite Jetpack 

### ISSUE THREAD

**Issue by Ischtaratu** [mekanism/Mekanism#6628]
#### Issue description:
The Jetpack module of the suit no longer has fire animation. I changed from version 10.0.9.432 for MC 1.16.1 to version 10.0.11.436 for MC 1.16.3 and since then there is no fire animation anymore. You can still hear the sound but there is no animation.

#### Steps to reproduce:
1. Install MC 1.16.3 with Forge 34.1.17
2. Install Mekanism Mod and all Addons (Tools, Generators and Additions)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.17
**Mekanism:** 10.0.11.436
**Other relevant version:** n/a

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No Crashlog

**Comment by Ischtaratu** [comment]
In addition: The singel Jetpack and the Armored Jetpack have the same Problem: no Fire-Animation.

Items:
mekanism:jetpack
mekanism:jetpack_armored

**Comment by pupnewfster** [comment]
I am not able to reproduce this, if you turn around while flying do you still see the particles briefly? I think at some point between 1.16.1 and 1.16.3 added particle culling, which we could disable for the jetpacks particles but from what I can tell it is properly working for it.
