### ISSUE TITLE
Is configurator broken or innacurate now?

### ISSUE THREAD

**Issue by Wodong77** [mekanism/Mekanism#6629]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Attempt to use configurator in wrench mode on placed Mekanism machine block
2a. Right click using configurator (wrench) acts as rotate (didn't do that in any of the 10.0.11 releases)
2b. Right click using configurator (rotate) does nothing.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.23
**Mekanism:** 10.0.12
**Other relevant version:** MC 1.16.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
I seriously doubt the log will be helpful but here it is in the entirety of what was in the file.  No crash.

https://pastebin.com/5uK0tvR8

**Comment by Seniorendi** [comment]
I do not use the Configurator often. But i think everything looks good.

[https://cloud.srendi.de/index.php/s/8sNnWNriNRTEYkC](url) <-- Video

**Comment by Wodong77** [comment]
I just checked the video. 
    Maybe I just didn't understand what the configurator is supposed to do, I swear it didn't used to spin the blocks 90 degrees to the left every time I would right click them.  My updated testing included 1.16.3 and Mekanism modules (base + additional) only, all on 10.0.1.437; Forge v34.1.23.  NO optifine, NO other mods, not even JEI.
    1. placed several different machine blocks, had charged configurator in hand.
    2. Wrench mode: shift-right click in pops mekanism machines and cables out like I expect.  right click does the rotate 90 degrees thing (always to the left) with every click. (This is not behavior I observed previously.)
    3. Using configurator in rotate mode: whichever side of the machine I would click on became the "front".  I always thought it would just do a 90 degree rotate in the direction that I clicked the corner side of, ie. click on the left facing side and it rotates left, click on the right facing side and it rotates right.

So maybe it's a nonissue and I'm just really unobservant.  If so, my bad, and probably I had something else in the mod folder making it behave like I thought it did in the 1.16.1 versions.
