### ISSUE TITLE
Tengo un problema con los gráficos de algunos generadores del mod

### ISSUE THREAD

**Issue by LionZ29** [mekanism/Mekanism#6632]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.  No conosco la causa real de esto debido a que solo descargue el mod y lo instale junto a los otros archivos del mod
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108
**Mekanism:** 10.0.9.432
**Other relevant version:** MC 1.16.1

**Comment by pupnewfster** [comment]
Assuming I understand what you are saying the issue is by using google translate... Remove optifine
