### ISSUE TITLE
Mekanism + Optiforge crashing server on startup

### ISSUE THREAD

**Issue by Moonwolfhunter** [mekanism/Mekanism#6635]
#### Issue description:
I've installed optifine and optiforge on both my Minecraft client and server, which while the client loads without problem the server can't start with it crashing everything (crash log linked). Sorry if this isn't an issue with Mekanism
#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.19
**Mekanism:** 1.16.3-10.0.11.436
**Other relevant version:** Optiforge 0.3.2 & Optifine 1.16.3 HD U G3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.pl/view/b41b618a

**Comment by thiakil** [comment]
if it runs with Mekanism and doesn't with OptiWhatevers, then no, it's not a Mekanism problem. 

That's like saying your foot is the problem when you scald it pouring boiling water on it...

One of your (core) mods is screwing with vanilla classes or screwing with ours.
