### ISSUE TITLE
Valhelsia 2 - cant extract liquids

### ISSUE THREAD

**Issue by CptEagleX** [mekanism/Mekanism#6636]
Hello,
i have a little problem, im building a dynamic tank. I can insert liquids into it, but i cant extract them through dynamic valve, tried in creative and still dont work, please help. (Valhelsia 2 modpack)

**Comment by CapturedCherry** [comment]
Have you used the configurator tool to set the pressurized tubes to extrat the liquids?
Also what version of minecraft, forge and mekanism are you runing?

**Comment by CptEagleX** [comment]
Its minecraft 1.15.2 and forge 31.2.36. I tried the configurator, but it does not work.

**Comment by CptEagleX** [comment]
And mekanism is 9.10.9.422

**Comment by CptEagleX** [comment]
Works now, thanks a lot, i am dump. Have a nice day
