### ISSUE TITLE
[1.16.3] Issue with Storage Drawers

### ISSUE THREAD

**Issue by raziel23x** [mekanism/Mekanism#6637]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
found a issue between Mekanism and storage drawers with the Logistical Transporter ands the storage drawers mod as they will not trans port items into the controller or the storage drawers but it will with the compacting drawers but i found a work around by doing this in my test environment https://github.com/raziel23x/StorageDrawers/tree/1.16 is the latest test build for the 1.16.3 version of storage drawers as its not released for 1.16.3 like projecte is it something on our end or is it on meks? I am looking for a second set of eyes to figure out who end is it really on
 to bypass the issue i used Cyclic item cable and a chest in the example screenshot i am using the diamond chest from iron chest mod
![image](https://user-images.githubusercontent.com/441966/96452600-3e94f880-11e7-11eb-905c-76fc782a76f3.png)

### Version (make sure you are on the latest version before reporting):
**Forge:**
34.1.23 
**Mekanism:** 
Mekanism-1.16.3-10.0.12.437
**Other relevant version:** 
StorageDrawers-1.16.3-8.2.0-SNAPSHOT
Cyclic-1.16.3-0.8.2
ironchest-1.16.3-11.2.6

**Comment by pupnewfster** [comment]
https://github.com/jaquadro/StorageDrawers/issues/811
