### ISSUE TITLE
Security desk, trusted player get erased after server restart

### ISSUE THREAD

**Issue by GrandMJ** [mekanism/Mekanism#6638]
#### Issue description:
I tried to set my machines to trusted only while adding a security desk and add a trusted player.
That is actually working as long as no server restart occurs. After each restart, the trusted player section is empty.

We did some testing and it seems like the corresponding SecurityFrequencyHandler.dat isnt even created at our dedicated server.
I copy&pasted that handler from a single player world to server but even with then the timestamp is its upload value.
Changes seem not being saved while save-on and restarting.

Follow the discord discussion: https://discordapp.com/channels/554379889122213888/560583846509281280/767744899524853760

#### Steps to reproduce:
1. Play on dedicated server, place down a security desk
2. Set override and trusted only
3. Add a trusted player, confirm it's listed as trusted player
4. Restart server
5. Trusted entry is gone

#### Version
Forge: 32.0.108
Mekanism: 10.0.9.432
Other relevant version: Modpack: Valhelsia 3 on its version 3.0.17

##### Side note:

The user Captured Cherry on discord did tests on a current 1.16.3 server with latest mek release 10.0.12.437 and will hopefully confirm that issue ;)

**Comment by CapturedCherry** [comment]
I can confirm that I have the same issue. I have also compiled the mod and had no change in results.

**Comment by CapturedCherry** [comment]
Following the new code changes, I ran some test and found the security desk to be working as intended.
