### ISSUE TITLE
[MC 1.12.2 PO3 3.3.59] Caught exception from Mekanism: Tools

### ISSUE THREAD

**Issue by froob956** [mekanism/Mekanism#6639]
#### Issue description:
Player can login the first time without issue, when they go afk and get dced (either to the hub or disconnect fully) and try to reconnect, it crashes MC. I know this is an outdate version but would appreciate someone at least pointing me in the correct direction, it is the only player out of many known to be having this issue. 

#### Steps to reproduce:
1. Login
2. Go afk
3. Reconnect

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2847** 
**Mekanism: 1.12.2-9.8.3.390** 
**Other relevant version: PO3 3.3.59** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[latest.log](https://github.com/mekanism/Mekanism/files/5406030/latest.log)
[crash-2020-10-19_22.09.13-client.txt](https://github.com/mekanism/Mekanism/files/5406031/crash-2020-10-19_22.09.13-client.txt)

**Comment by froob956** [comment]
Can you at least please tell me what it is a duplicate of? I've searched and I'm clearly searching the wrong thing then.

**Comment by pupnewfster** [comment]
#5797 pretty sure they also had an issue about it, but the bigger thing is we are no longer developing for 1.12 so it isn't going to get fixed (and isn't an issue in 1.15 (not being developed currently either), or 1.16 (being developed)
