### ISSUE TITLE
Interaction Range of Fission Reactor Logic Adapter is too big.

### ISSUE THREAD

**Issue by new-3** [mekanism/Mekanism#6640]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When you include some Fission Reactor Logic Adapter in Fission Reactor multiblocks, R-clicking other outer blocks(reactor glass or casing) than Logic Adapter opens Logic Adapter GUI, not GUI of Fission Reactor control panel. 
You should interact blocks that is very far from Logic block to open Fission Reactor GUI.

After rejoining the world Logic Adapter GUI only opens when interacting with the logic block itself, so it seems to be uninteded behavior.

#### Steps to reproduce:
1. Build Fission Reactor Multiblock.
2. Replace some outer blocks with Fission Reactor Logic Adapter blocks.
3. R-click some Reactor Glass blocks around the Logic blocks.

#### Version (make sure you are on the latest version before reporting):
**Forge: 34.1.24
**Mekanism: Mekanism-1.16.3-10.0.12.437.jar
**Other relevant version: MekanismGenerators-1.16.3-10.0.12.437.jar, MekanismTools-1.16.3-10.0.12.437.jar

**Comment by Seniorendi** [comment]
You should use the latest Mekanism version

**Comment by new-3** [comment]
> You should use the latest Mekanism version
I'll check agian after updating my mods

**Comment by new-3** [comment]
Can confirm same thing happens on the latest version on 1.16.3

**Comment by Seniorendi** [comment]
Okay
