### ISSUE TITLE
Vanilla ores not spawning

### ISSUE THREAD

**Issue by LlubNek** [mekanism/Mekanism#6643]
#### Issue description:
Mekanism and something else (not sure what yet) are preventing vanilla ores such as iron or coal from generating except as part of other structures.  Modded ores seem unaffected.

#### Steps to reproduce:
1. install mekanism and ??? ...
2. install large ore deposits
3. create new world
4. go into creative mode
5. use /lods strip around
6. observe absence of vanilla ores

#### Version (make sure you are on the latest version before reporting):
**Minecraft:** 1.16.3
**Forge:** 34.1.23
**Mekanism:** Mekanism-1.16.3-10.0.12.437.jar
**Other relevant version:** ???

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[latest.log](https://github.com/mekanism/Mekanism/files/5416789/latest.log)

**Comment by raziel23x** [comment]
I have Mekanism installed on my private modpack and there is no issues with ore gen on my end of it is there a way you can list the mods you have installed

**Comment by pupnewfster** [comment]
We don't touch/modify vanilla's ore generation

**Comment by LlubNek** [comment]
If I remove Mekanism the problem goes away.  This is Mekanism related.

I'm still trying to track down what other mods are involved.  I've got over 300 mods in the pack I'm working on.

Weird thing is, if I disable everything that /shouldn't/ touch ores the problem goes away...

**Comment by pupnewfster** [comment]
My best guess is that for some reason the large ore deposits mod is breaking from us adding our ores in the way forge exposes for mods to add features to biomes and is just not adding the alternative spawns after removing the vanilla ore spawns. No idea why and I can't really speculate more than that given the mod is closed source. Your best bet is taking up the issue with them given from what I can tell from the CF description they *do* touch vanilla ores, and then if after they look at it and they can point us at some particular thing we are doing on our end that causes it to break we can look at adjusting that.

**Comment by LlubNek** [comment]
Large ore deposits is just there for testing.  It's where the `/lods strip around` command comes from.  It lets me see the ores, without the dirt, stone, etc.
I've been slowly narrowing this down for the last few hours (if all else fails... Newton's method).  I'll have it pinned down soon.

**Comment by LlubNek** [comment]
well... optifine's involved... which makes no sense... but there's at least one more since just Mekanism and optifine/optiforge doesn't do it by themselves.

Here's the list of mods I'm working with if somebody else wants to poke at it:
[mods.txt](https://github.com/mekanism/Mekanism/files/5419010/mods.txt)
