### ISSUE TITLE
[1.15.2] Oredictionificator crashes dedicated server when placed from an item with existing NBT data

### ISSUE THREAD

**Issue by XFactHD** [mekanism/Mekanism#6644]
#### Issue description:
When an Oredictionificator that was placed and configured before is placed again, it will crash a dedicated server due to `ResourceLocation#isResourceNameValid() / ResourceLocation#func_217855()` being marked client-only.
Looking through the Mekanism and MC sources, I found that this can be fixed by using the implementation of `NBTUtils#setResourceLocationIfPresent()` from 1.16 because `ResourceLocation#tryCreate()` also exists in MC 1.15.

A very similar issue was reported [here](https://github.com/mekanism/Mekanism/issues/6333) but in that case it seems to not have caused a crash.

#### Steps to reproduce:
1. Join a dedicated server
2. Place an Oredicitionificator, break it and place the dropped item again

#### Version:
**Forge:** 1.15.2-31.2.41
**Mekanism:** 1.15.2-9.10.9.422

#### Crashlog
https://gist.github.com/XFactHD/da1c58bce57f6a0a02f1ec3ef086b115

**Comment by pupnewfster** [comment]
We are no longer actively developing Mekanism for 1.15.2.

**Comment by XFactHD** [comment]
Would you accept a PR to fix this?

**Comment by pupnewfster** [comment]
Not sure, mostly because our build system is not really currently setup to handle multiple versions of MC and I don't really currently have the desire to look into how to change that (as I don't even fully know how the build system is setup personally).

**Comment by XFactHD** [comment]
I decided to create a PR (#6647) just in case you do decide to release another update for 1.15.2. I would be very happy if that happened as this bug makes the Oredictionificator completely useless currently.
