### ISSUE TITLE
Placing lava inside mekanism blocks as if they were not there

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#6645]
#### Issue description:
![image](https://user-images.githubusercontent.com/41069911/96767302-58cb0400-13aa-11eb-9a51-353b86c58fd9.png)
#### Steps to reproduce:
1. attempt to place lava on top of heat generator
2. the lava goes through it

#### Version (make sure you are on the latest version before reporting):
**Forge: 34.1.25** 
**Mekanism: latest dev**

**Comment by Seniorendi** [comment]
Its a feature to place lava inside a generator. But it should float like water...

**Comment by Oct0bass** [comment]
Yeah pretty sure this is an intended new feature.

**Comment by term2112** [comment]
I noticed that this happens to the infuser too, did not know that this was intended

**Comment by term2112** [comment]
going to close this issue now

**Comment by pupnewfster** [comment]
Ya it is intended, it is now possible (by lava logging both the generator and the cables) to have "seven sides" be "adjacent" to lava for the heat generator instead of just five.
