### ISSUE TITLE
[1.16.1] Exception Ticking World

### ISSUE THREAD

**Issue by lulabyte** [mekanism/Mekanism#6646]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

When we load into a certain area, we crash out of the server/single player game. I had Mekanism installed and then removed it, perhaps this is the issue?

#### Steps to reproduce:
1. Install Mekanism, create a world. Save and exit. Open world and in your travels it will randomly crash out.
2. Save and exit.
3. Remove mod.
4. Re-open world and travel around.
5. Crash out.

If we leave the chunk in time, we don't crash out.

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.1
**Mekanism:* 1.16.1

#### If a (crash)log is relevant for this issue, link it here:

---- Minecraft Crash Report ----
// Shall we play a game?

Time: 10/21/20 3:27 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot set property BooleanProperty{name=south, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{mekanism:osmium_ore}
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:114) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.block.VineBlock.func_196544_a(VineBlock.java:228) ~[?:?] {re:classloading}
	at net.minecraft.block.VineBlock.func_225542_b_(VineBlock.java:212) ~[?:?] {re:classloading}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:617) ~[?:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:501) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:quark:add-rave-hook,xf:fml:quark:change-sleeping-player-count,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(SourceFile:390) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$17237/1183519672.accept(Unknown Source) ~[?:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1249) ~[?:1.8.0_51] {}
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:368) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:326) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:quark:add-rave-hook,xf:fml:quark:change-sleeping-player-count,pl:mixin:APP:abnormals_core.mixins.json:ServerWorldMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:121) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$16158/1376257977.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.state.StateHolder.func_206870_a(SourceFile:114)
	at net.minecraft.block.VineBlock.func_196544_a(VineBlock.java:228)
	at net.minecraft.block.VineBlock.func_225542_b_(VineBlock.java:212)
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227034_b_(AbstractBlock.java:617)
	at net.minecraft.world.server.ServerWorld.func_217441_a(ServerWorld.java:501)
	at net.minecraft.world.server.ServerChunkProvider.func_241099_a_(SourceFile:390)
	at net.minecraft.world.server.ServerChunkProvider$$Lambda$17237/1183519672.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(SourceFile:368)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(SourceFile:337)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:326)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['lulabyte'/309, l='ServerLevel[Friendship World 1.0]', x=2443.85, y=70.76, z=-1313.55]]
	Chunk stats: ServerChunkCache: 3923
	Level dimension: minecraft:overworld
	Level spawn location: World: (1492,77,-1242), Chunk: (at 4,4,6 in 93,-78; contains blocks 1488,0,-1248 to 1503,255,-1233), Region: (2,-3; contains chunks 64,-96 to 95,-65, blocks 1024,0,-1536 to 1535,255,-1025)
	Level time: 5048021 game time, 870563 day time
	Level name: Friendship World 1.0
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 51334 (now: false), thunder time: 138874 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:852)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:788)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:121)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:643)
	at net.minecraft.server.MinecraftServer.lambda$func_240784_a_$0(MinecraftServer.java:230)
	at net.minecraft.server.MinecraftServer$$Lambda$16158/1376257977.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1695290600 bytes (1616 MB) / 6442450944 bytes (6144 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 6.1.1+74+master.966c698
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.1-32.0.108.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.1_HD_U_G2.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.1-32.0.108.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.1-0.1.9.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-MC1.16.1-0.1.9.jar optiforge TRANSFORMATIONSERVICE 
	FML: 32.0
	Forge: net.minecraftforge:32.0.108
	FML Language Providers: 
		javafml@32.0
		minecraft@1
	Mod List: 
		enchantedbookredesign-3.0.jar Enchanted Book Redesign {enchantedbookredesign@3.0 DONE}
		randomloot-2.1.6.jar Random Loot Mod {randomloot@2.1.6 DONE}
		foodexpansion-1.6.0.jar Food Expansion: Reimagined {foodexpansion@1.6.0 DONE}
		NetherPortalFix_1.16.1-7.0.1.jar NetherPortalFix {netherportalfix@7.0.1 DONE}
		aiotbotania-1.16.1-1.3.jar AIOT Botania {aiotbotania@1.3 DONE}
		SBM-BoneTorch-1.16.1-0.0.1.jar [SBM] BoneTorch {bonetorch@0.0.1 DONE}
		mcws-win-1.16.1-v1.0.2.jar Macaw's Windows {mcwwindows@1.0.2 DONE}
		bambooeverything-1.16-1.0.0.jar Bamboo Everything {bambooeverything@1.16-1.0.0 DONE}
		ForgeEndertech-1.16.1-7.0.1.0-build.0008.jar Forge Endertech {forgeendertech@7.0.1.0 DONE}
		CTM-MC1.16.1-1.1.1.5.jar ConnectedTexturesMod {ctm@MC1.16.1-1.1.1.5 DONE}
		CookingForBlockheads_1.16.1-9.0.2.jar Cooking for Blockheads {cookingforblockheads@9.0.2 DONE}
		Controlling-7.0.0.3.jar Controlling {controlling@7.0.0.3 DONE}
		Placebo-1.16.2-4.2.0.jar Placebo {placebo@4.2.0 DONE}
		Elementary+Staffs+1.9.jar Elementary Staffs {element@1.9 DONE}
		Powah-1.16.1-2.2.0.jar Powah {powah@2.2.0 DONE}
		potionofbees-1.16.1-1.0.1.0.jar Potion of Bees {potionofbees@1.16.1-1.0.1.0 DONE}
		gemsnjewels-1.16.1-0.16.0.jar Gems & Jewels {gemsnjewels@{file.jarVersion} DONE}
		Bookshelf-1.16.1-6.3.21.jar Bookshelf {bookshelf@6.3.21 DONE}
		Uncrafted-1.16-4.0.0pre1.jar Uncrafted {uncrafted@4.0.0pre1 DONE}
		guardvillagers-1.16.1-1.1.4.jar Guard Villagers {guardvillagers@1.1.4 DONE}
		u_team_core-1.16.1-3.1.3.170.jar U Team Core {uteamcore@3.1.3.170 DONE}
		randompatches-1.16.1-1.22.1.1(1).jar RandomPatches {randompatches@1.16.1-1.22.1.1 DONE}
		buildinggadgets-3.5.1.jar Building Gadgets {buildinggadgets@3.5.1 DONE}
		Apotheosis-1.16.1-4.1.3.jar Apotheosis {apotheosis@4.1.3 DONE}
		mcw-doors-1.0.1fix-mc1.16.1.jar Macaw's Doors {mcwdoors@1.0.1 DONE}
		Hwyla-forge-1.10.10-B77_1.16.1.jar Waila {waila@1.10.10-B77_1.16.1 DONE}
		SnowRealMagic-1.16.1-2.0.1.jar Snow! Real Magic! {snowrealmagic@2.0.1 DONE}
		JustEnoughResources-1.16.1-0.11.1.98.jar Just Enough Resources {jeresources@0.11.1.98 DONE}
		horsestandstill-1.16.1-1.0.1.jar Stupid Horse Stand Still {horsestandstill@1.16.1-1.0.1 DONE}
		shetiphiancore-1.16-3.8.0.jar ShetiPhian-Core {shetiphiancore@3.8.0 DONE}
		MysticalAgradditions-1.16.1-4.0.0.jar Mystical Agradditions {mysticalagradditions@4.0.0 DONE}
		quickhomes-1.16.1-1.2.6.jar QuickHomes {quickhomes@1.2.6 DONE}
		FarmersDelight-1.16.1-0.2.3.jar Farmer's Delight {farmersdelight@1.16.1-0.2.3 DONE}
		useful_backpacks-1.16.1-1.11.3.78.jar Useful Backpacks {usefulbackpacks@1.11.3.78 DONE}
		torchmaster-2.3.2-alpha.jar Torchmaster {torchmaster@2.3.2-alpha DONE}
		repurposed_structures-1.16.1-2.0.6.jar Repurposed Structures {repurposed_structures@1.16.1-2.0.6 DONE}
		endertanks-1.16-1.9.0.jar EnderTanks {endertanks@1.9.0 DONE}
		BiomesOPlenty-1.16.1-11.0.0.396-universal.jar Biomes O' Plenty {biomesoplenty@1.16.1-11.0.0.396 DONE}
		valhelsia_structures-16.0.2.jar Valhelsia Structures {valhelsia_structures@16.0.2 DONE}
		Lollipop-1.16.1-3.0.0.jar Lollipop {lollipop@3.0.0 DONE}
		invisiblights-forge-6.0.jar InvisibLights {invisiblights@6.0 DONE}
		SilentGear-1.16.1-2.1.1+162.jar Silent Gear {silentgear@2.1.1+162 DONE}
		simplefarming-1.16.1-1.3.2.jar Simple Farming {simplefarming@1.16.1-1.3.2 DONE}
		curios-FORGE-1.16.1-3.0.0.2.jar Curios API {curios@FORGE-1.16.1-3.0.0.2 DONE}
		Botania-1.16.1-403.1.jar Botania {botania@1.16.1-403.1 DONE}
		managear-1.16.1-2.1.1.jar Mana Gear {managear@1.16.1-2.1.1 DONE}
		Patchouli-1.16-39.jar Patchouli {patchouli@1.16-39 DONE}
		extlights-3.0.jar Extended Lights {extlights@3.0 DONE}
		tanknull-2.0.jar Tank Null {tanknull@2.0 DONE}
		angelring-1.16.1-1.3.1.jar Angel Ring {angelring@1.3.1 DONE}
		EndReborn+[0.7.5].jar End: Reborn {endreborn@0.7.5 DONE}
		elevatorid-1.16.1-1.7.3.jar Elevator Mod {elevatorid@1.16.1-1.7.3 DONE}
		tombstone-5.0.2.jar Corail Tombstone {tombstone@5.0.2 DONE}
		neoncraft-2.0.jar Neon Craft {neoncraft@2.0 DONE}
		worldedit-forge-mc1.16.1-7.2.0-beta-03.jar WorldEdit {worldedit@7.2.0-beta-03+94ce464 DONE}
		mcws-roofs-1.16.1-v2.0.0.jar Macaw's Roofs {mcwroofs@2.0.0 DONE}
		MrCrayfishs-Furniture-Mod-1.16.1.jar MrCrayfish's Furniture Mod {cfm@7.0.0-pre18 DONE}
		productivebees-1.16.1-0.3.2.jar Productive Bees {productivebees@1.16.1-0.3.2 DONE}
		AdChimneys-1.16.1-6.0.0.0-build.0006.jar Advanced Chimneys {adchimneys@6.0.0.0 DONE}
		[1.16.1][Forge]+RPG-HUD-3.8.2.jar RPG-Hud {rpg-hud@3.8.2 DONE}
		ServerTabInfo-1.16.1-1.3.3.jar Server Tab Info {servertabinfo@1.3.3 DONE}
		QuantumStorage-1.16.1-5.2.0.jar QuantumStorage {quantumstorage@NONE DONE}
		Cyclic-1.16.1-0.6.1.jar Cyclic {cyclic@1.16.1-0.6.1 DONE}
		Kiwi-1.16.1-3.2.1.jar Kiwi {kiwi@3.2.1 DONE}
		Ma-Enchants-1.16.1-3.2.1.jar Ma Enchants {ma-enchants@1.16.1-3.2.1 DONE}
		SimplyJetpacks2-1.16.1-2.6.2.2.jar Simply Jetpacks 2 {simplyjetpacks@1.16.1-2.6.2.2 DONE}
		Cucumber-1.16.1-4.0.2.jar Cucumber Library {cucumber@4.0.2 DONE}
		mermaidtail-1.4.jar Mermaid Tail Mod {mermaidtail@1.16.1-1.4.0 DONE}
		jei-1.16.1-7.0.0.6.jar Just Enough Items {jei@7.0.0.6 DONE}
		OptiForge-MC1.16.1-0.1.9.jar OptiForge {optiforge@0.1.9 DONE}
		FallingTree-Forge-1.16.1-2.5.0.jar Falling Tree {falling_tree@2.5.0 DONE}
		AttributeFix-1.16.1-8.0.1.jar AttributeFix {attributefix@8.0.1 DONE}
		fishtraps-0.1.1.jar Fish Traps {fishtraps@1.16.1-0.1.1 DONE}
		Abnormals-Core-1.16.1-2.0.5.jar Abnormals Core {abnormals_core@2.0.5 DONE}
		RandomTP-MC1.16-4.1.2.jar Random Teleport Mod {randomtp@MC1.16.1-4.1.2 DONE}
		Upgrade-Aquatic-1.16.1-2.0.1.jar Upgrade Aquatic {upgrade_aquatic@2.0.1 DONE}
		ropebridge-1.16.1-2.0.jar Rope Bridge {ropebridge@1.16.1-2.0 DONE}
		WAWLA-1.16.1-4.0.1.jar WAWLA {wawla@4.0.1 DONE}
		Extra-Boats-1.16.1-1.4.1.jar Extra Boats {extraboats@1.4.1 DONE}
		Waystones_1.16.1-7.1.1.jar Waystones {waystones@7.1.1 DONE}
		fakeblocks-1.16.1-1.0.5.jar Fake Blocks {fakeblocks@1.16.1-1.0.5 DONE}
		comforts-FORGE-1.16.1-3.0.0.1.jar Comforts {comforts@FORGE-1.16.1-3.0.0.1 DONE}
		appliedenergistics2-8.0.0-beta.2.jar Applied Energistics 2 {appliedenergistics2@8.0.0-beta.2 DONE}
		NaturesCompass-1.16.1-1.8.5.jar Nature's Compass {naturescompass@1.16.1-1.8.5 DONE}
		Artifacts-1.16.1-2.5.2.jar Artifacts {artifacts@1.16.1-2.5.2 DONE}
		decorative_blocks-1.16.1-1.5.jar Decorative Blocks {decorative_blocks@1.5 DONE}
		BotanyPots-1.16.1-3.0.7.jar BotanyPots {botanypots@3.0.7 DONE}
		AdHooks-1.16.1-6.0.0.0-build.0006.jar Advanced Hook Launchers {adhooks@6.0.0.0 DONE}
		DungeonCrawl-1.16.1-2.1.0.jar Dungeon Crawl {dungeoncrawl@2.1.0 DONE}
		creeperconfetti-3.3.jar Creeper Confetti {creeperconfetti@3.3 DONE}
		japanese_food_mod-1.16.1-1.0.5.jar Japanese Food Mod {japanese_food_mod@1.16.1-1.0.5 DONE}
		mapperbase-1.16.1-2.0.0.0.jar Mapper Base {mapperbase@1.16.1-2.0.0.0 DONE}
		embellishcraft-1.16.1-3.0.0.0.jar EmbellishCraft {embellishcraft@1.16.1-3.0.0.0 DONE}
		mahoutsukai-1.16.1-v1.21.6.jar Mahou Tsukai {mahoutsukai@1.16.1-v1.21.6 DONE}
		PackingTape-1.16.1-0.9.6.jar Packing Tape {packingtape@0.9.6 DONE}
		forge-1.16.1-32.0.108-universal.jar Forge {forge@32.0.108 DONE}
		MysticalAgriculture-1.16.1-4.0.2.jar Mystical Agriculture {mysticalagriculture@4.0.2 DONE}
		ironchest-1.16.1-11.0.4.jar Iron Chests {ironchest@1.16.1-11.0.4 DONE}
		SimpleDivingGear-5.0.0+mc+1.16.1.jar Simple Diving Gear {simpledivegear@5.0.0 mc 1.16.1 DONE}
		forge-1.16.1-32.0.108-client.jar Minecraft {minecraft@1.16.1 DONE}
		EnchantmentDescriptions-1.16.1-3.0.2.jar EnchantmentDescriptions {enchdesc@3.0.2 DONE}
		mcpaint-1.6.1.jar Mc Paint {mcpaint@1.6.1 DONE}
		SilentLib-1.16.1-4.7.1+59.jar Silent Lib {silentlib@4.7.1+59 DONE}
		AdLods-1.16.1-4.0.0.0-build.0007.jar Large Ore Deposits {adlods@4.0.0.0 DONE}
		Craftable+Saddles+[1.16.1]-1.3.jar Craftable Saddles {craftable_saddles@1.3 DONE}
		foamdome-1.1.0.jar Foam Dome {foamdome@1.1.0 DONE}
		Mantle-1.16.1-1.6.27.jar Mantle {mantle@1.6.27 DONE}
		Inspirations-1.16.1-1.2.0(1).jar Inspirations {inspirations@1.16.1-1.2.0 DONE}
		pamhc2foodcore-1.16.1-1.0.6.jar Pam's HarvestCraft 2 Food Core {pamhc2foodcore@version DONE}
		multibeds-1.16-1.7.0.jar Multi-Beds {multibeds@1.7.0 DONE}
		AutoRegLib-1.6-43.jar AutoRegLib {autoreglib@1.6-43 DONE}
		Quark-r2.3-265.jar Quark {quark@r2.3-265 DONE}
		[1.16.1]+SecurityCraft+v1.8.19.3.jar SecurityCraft {securitycraft@v1.8.19.3 DONE}
		StorageDrawers-1.16.2-8.1.0.jar Storage Drawers {storagedrawers@1.16.2-8.1.0 DONE}
		sit-1.16.1-v1.3.jar Sit {sit@v1.3 DONE}
		RingOfAttraction-1.16.1-1.2.0.jar Ring of Attraction {ring_of_attraction@1.2.0 DONE}
		Aquaculture-1.16.1-2.0.20.jar Aquaculture 2 {aquaculture@1.16.1-2.0.20 DONE}
		SilentGems-1.16.1-3.6.3+100.jar Silent's Gems 3 {silentgems@3.6.3+100 DONE}
		CosmeticArmorReworked-1.16.1-v1b.jar CosmeticArmorReworked {cosmeticarmorreworked@1.16.1-v1b DONE}
		SoundFilters-0.14_for_1.16.jar Sound Filters {soundfilters@0.14_for_1.16 DONE}
		chiselsandbits-0.0.6-BETA.jar Chisels & bits {chiselsandbits@NONE DONE}
		lootbagmod-1.16.1-1.5.jar Loot Bag Mod {lootbagmod@1.16.1-1.5 DONE}
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
	Patchouli open book context: n/a
	Player Count: 1 / 8; [ServerPlayerEntity['lulabyte'/309, l='ServerLevel[Friendship World 1.0]', x=2443.85, y=70.76, z=-1313.55]]
	Data Packs: vanilla, mod:enchantedbookredesign, mod:randomloot, mod:foodexpansion, mod:netherportalfix (incompatible), mod:aiotbotania, mod:bonetorch, mod:mcwwindows, mod:bambooeverything (incompatible), mod:forgeendertech, mod:ctm, mod:cookingforblockheads (incompatible), mod:controlling, mod:placebo (incompatible), mod:element, mod:powah, mod:potionofbees (incompatible), mod:gemsnjewels, mod:bookshelf (incompatible), mod:uncrafted (incompatible), mod:guardvillagers (incompatible), mod:uteamcore, mod:randompatches (incompatible), mod:apotheosis (incompatible), mod:mcwdoors (incompatible), mod:snowrealmagic, mod:jeresources (incompatible), mod:horsestandstill (incompatible), mod:shetiphiancore, mod:mysticalagradditions, mod:farmersdelight, mod:usefulbackpacks, mod:torchmaster (incompatible), mod:repurposed_structures, mod:endertanks, mod:biomesoplenty, mod:valhelsia_structures (incompatible), mod:lollipop, mod:invisiblights, mod:silentgear (incompatible), mod:simplefarming, mod:curios (incompatible), mod:botania, mod:managear, mod:patchouli (incompatible), mod:extlights, mod:tanknull (incompatible), mod:angelring (incompatible), mod:endreborn (incompatible), mod:elevatorid, mod:tombstone, mod:neoncraft, mod:worldedit (incompatible), mod:mcwroofs, mod:cfm, mod:productivebees, mod:adchimneys, mod:servertabinfo, mod:cyclic (incompatible), mod:kiwi, mod:ma-enchants (incompatible), mod:cucumber, mod:mermaidtail, mod:jei (incompatible), mod:falling_tree, mod:attributefix (incompatible), mod:fishtraps (incompatible), mod:abnormals_core, mod:ropebridge (incompatible), mod:extraboats, mod:waystones (incompatible), mod:fakeblocks, mod:comforts (incompatible), mod:appliedenergistics2, mod:naturescompass (incompatible), mod:artifacts, mod:decorative_blocks (incompatible), mod:botanypots (incompatible), mod:adhooks, mod:dungeoncrawl (incompatible), mod:creeperconfetti (incompatible), mod:japanese_food_mod (incompatible), mod:mapperbase, mod:embellishcraft (incompatible), mod:mahoutsukai, mod:packingtape, mod:forge, mod:mysticalagriculture, mod:ironchest, mod:simpledivegear (incompatible), mod:enchdesc (incompatible), mod:mcpaint, mod:silentlib (incompatible), mod:adlods, mod:craftable_saddles (incompatible), mod:foamdome (incompatible), mod:mantle (incompatible), mod:inspirations (incompatible), mod:pamhc2foodcore (incompatible), mod:multibeds, mod:autoreglib (incompatible), mod:securitycraft (incompatible), mod:storagedrawers (incompatible), mod:sit, mod:ring_of_attraction (incompatible), mod:aquaculture, mod:silentgems (incompatible), mod:cosmeticarmorreworked (incompatible), mod:soundfilters (incompatible), mod:chiselsandbits (incompatible), mod:lootbagmod (incompatible), mod:buildinggadgets (incompatible), mod:quark, mod:simplyjetpacks, mod:quantumstorage (incompatible), mod:randomtp (incompatible), mod:quickhomes (incompatible), mod:waila, mod:rpg-hud, mod:optiforge, mod:upgrade_aquatic, mod:wawla (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.1_HD_U_G2
	OptiFine Build: 20200802-005745
	Render Distance Chunks: 7
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: BSL_v7.1.04.1.zip
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by pupnewfster** [comment]
I am going to go ahead and close this as I think it is due to a forge bug that got fixed in 1.16.3 with this commit: https://github.com/MinecraftForge/MinecraftForge/commit/37f226eda597b42893049507f8fca6b94ba6f700 and has to do with vines causing the crash and not actually our ore. If this does end up to still happen in 1.16.3 with forge 34.1.16 or higher feel free to comment and I will reopen this.

**Comment by lulabyte** [comment]
I will say that adding Mekanism back in does seem to have fixed it. Still stress testing and on my way to work, but yes. It does seem to be working now.
