### ISSUE TITLE
Bug in Isotopic Centrifuge interaction

### ISSUE THREAD

**Issue by KhanhPham05** [mekanism/Mekanism#6648]
#### Issue description:

The Isotopic Centrifuge only can open GUI and install upgrades from the bottom, can not interact with it on the top 
#### Steps to reproduce:
Follow The Description

#### Version (make sure you are on the latest version before reporting):
**Forge:** : 33.1.23
**Mekanism:** : 10.0.12-437
**Other relevant version:** all mekanism addons

**Comment by pupnewfster** [comment]
I cannot reproduce being unable to open the GUI from the top block, but I can reproduce the inability to install upgrades to the top block.
