### ISSUE TITLE
[Mekanism 10 Requests]
Radioactive Meter

### ISSUE THREAD

**Issue by KhanhPham05** [mekanism/Mekanism#6649]
**Describe the the feature you'd like**
A Nuclear Meter for use to calculate nuclear gas in the air nearby player

**Describe alternatives you've considered**
The Nuclear Meter will:
1. measure the nuclear gas in the air surrounding using the vanilla clock mechanic. Stand closer the where place have radiation the clock will spin to the red side, place have less radioactive will spin to green side more
It also can be calculated how much radioactive in the air by print it to the (Tier 2) meter the number which will turns red if it have the most radioactive and turn less when radioactive level decrease 

2. If there is no radioactive the meter will said "No Radioactive" in the actionbar

**Additional context**
None

**Comment by Robball14** [comment]
There is already such a thing, is called Geiger counter, there is also another version which calculates if the player is affected by radiation

**Comment by pupnewfster** [comment]
As robball said this is already basically a thing
