### ISSUE TITLE
Robit Issue

### ISSUE THREAD

**Issue by matthewgrey1** [mekanism/Mekanism#6652]
**Issue description:**
Making a modpack. Fixed all errors except one, where there is an exception: Caused by: java.lang.NoClassDefFoundError: mekanism/common/entity/EntityRobit.

**Steps to reproduce:**
Version: 1.12.2
Forge: 14.23.5.2854
Mekanism: 9.8.3.390

[Crash Log](https://imgur.com/a/wKqwLVX)

**Comment by pupnewfster** [comment]
#6182
