### ISSUE TITLE
Can't craft Chargepad.

### ISSUE THREAD

**Issue by qtp1** [mekanism/Mekanism#6653]
I can't seem to craft the chargepad, no matter what I do? I have all the materials listed on the wiki, I have the steel ingots, the Energy Tablet, and the stone pressure plates and have them set up in the same exact way as the wiki shows. I've tried on multiple crafting tables but it hasn't worked. I've built plenty other things and it's been fine, so I don't understand why the recipe won't work.

**Forge:** 34.1.25
**Mekanism:** 10.0.13.438

**Comment by thiakil** [comment]
Check the recipe in game with JEI or similar, IIRC it now needs blackstone
