### ISSUE TITLE
HDPE pellet recipe gets stuck with 2+ speed upgrades

### ISSUE THREAD

**Issue by andrewsf** [mekanism/Mekanism#6654]
#### Issue description:

The following recipe:

```
        //Ethene + oxygen
        PressurizedReactionRecipeBuilder.reaction(
              ItemStackIngredient.from(MekanismItems.SUBSTRATE),
              FluidStackIngredient.from(MekanismTags.Fluids.ETHENE, 50),
              GasStackIngredient.from(MekanismGases.OXYGEN, 10),
              60,
              MekanismItems.HDPE_PELLET.getItemStack(),
              MekanismGases.OXYGEN.getStack(5)
        ).energyRequired(FloatingLong.createConst(1_000))
              .build(consumer, Mekanism.rl(basePath + "ethene_oxygen"));
```

works in a Pressurized Reaction Chamber without speed upgrades, or it works with one speed upgrade. But adding any additional upgrades causes the progress to get stuck.

#### Steps to reproduce:
1. Create a Pressurized Reaction Chamber (can repro in Creative)
2. Give it power (can repro with Creative Energy Cube)
2. Give it Liquid Ethylene & Oxygen gas (can repro with Creative Fluid Tank & Creative Chemical Tank)
3. Insert a stack of Substrate
4. Start adding Speed Upgrade, one by one

Expected behavior: Any number of speed upgrades will work.
Actual behavior: The machine works with 1 speed upgrade but progress gets stuck with 2, 3, 4, .......

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.24
**Mekanism:** 1.16.3-10.0.12.437 on all four of: Mekanism, MekanismAdditions, MekanismGenerators, MekanismTools
**Other relevant version:** AllTheMods 6, version 1.1.6b

#### Crash log

N/A

#### Notes

I only tested with the full mod pack, not with just vanilla + Mekanism.

**Comment by pupnewfster** [comment]
The energy per tick requirement is higher in some machines with speed upgrades and no energy upgrades than the energy buffer, at some point we have plans to add a warning symbol to show *why* the machine isn't working but this is fully intended.

**Comment by andrewsf** [comment]
Thanks! Is there any documentation in-game about the full +/- effects of each upgrade?
