### ISSUE TITLE
Fusion Reactor is non functional (does not form) in 10.0.13

### ISSUE THREAD

**Issue by Letoric** [mekanism/Mekanism#6656]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Covered in title

#### Steps to reproduce:
1. Load minecraft 1.16.3 with forge forge-1.16.3-34.1.25 and Mekanism 10.0.13 mod suite
2. Launch minecraft, create world, use command /mek build fusion
3. Attempt to access the control, it is not formed and thus not accessible.

**Comment by PoolloverNathan** [comment]
I am on 1.16.1 and it works, strange for something to break in a later version...
Try removing a block and replacing it? Or building it from scratch?
