### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by harmalom** [mekanism/Mekanism#6662]
happens when you open JEI

Forge version forge-1.16.3-34.1.25
Mekanism version 1.16.3-10.0.15.441
Minecraft 1.16.3
jei-1.16.3-7.6.0.48

https://pastebin.com/kgr7YRtn

**Comment by Seniorendi** [comment]
Can you try it with the latest Forge version(34.1.32)?

**Comment by pupnewfster** [comment]
Is that a full crash report? It doesn't show that you have Mekanism or JEI installed which it should. Also do you have optifine or another mod like that installed and if so does it happen without it?

**Comment by Oct0bass** [comment]
Unable to reproduce with latest forge, mek, and JEI.  I only installed the mek core, not the other modules, so maybe that's it?  Will try that
