### ISSUE TITLE
Improve Multiblock build help

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#6663]
https://github.com/mekanism/Mekanism/blob/1.16.x/src/generators/java/mekanism/generators/common/content/fission/FissionReactorValidator.java#L126-L128

As discussed on discord if there is no Control Rod assembly the output doesn't mention the problematic location. 

Also is there some documentation about the configurator being the tool to use for this? Not sure if that should be in a tooltip somewhere.

**Comment by pupnewfster** [comment]
For now I am not adding to the configurator's tooltip that it can be used to validate multiblocks, but that does sound like something that we will want to include somewhere at the very least in #6651
