### ISSUE TITLE
Digitial Miner Glitching out JEI UI

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#6669]
#5354 ## Issue description:
The arrows within the JEI UI are glitched out whenever entering the digital miner menu

#### Steps to reproduce:
![image](https://user-images.githubusercontent.com/41069911/97599676-a1a03f80-19de-11eb-84fc-ff1bbe49e5e2.png)

#### Version (make sure you are on the latest version before reporting):
**Forge: 34.1.25** 
**Mekanism: 10.0.15** 
**JEI: 7.5.0.43**

**Comment by pupnewfster** [comment]
https://github.com/mezz/JustEnoughItems/issues/2129
