### ISSUE TITLE
[1.16.3] Crash at launch "Failed to load description for particle mekanism:laser"

### ISSUE THREAD

**Issue by LotuxPunk** [mekanism/Mekanism#6670]
#### Issue description:
When we try to launch the game, it crash. I saw that you consider it as a "NotMekanism" crash, but I think it's something wrong with the accesstransformer on particle.

#### Steps to reproduce:
1. Install mods
2. Press launch
3. Enjoy the crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.3-34.1.33
**Mekanism:** 1.16.3-10.0.15.441
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/hU9B0X0b

**Comment by pupnewfster** [comment]
This has nothing to do with Mekanism, if you provide your latest log we can help you read it to find the actual crash but the crash report itself is worthless and has the wrong error.

**Comment by LotuxPunk** [comment]
> 
> 
> This has nothing to do with Mekanism, if you provide your latest log we can help you read it to find the actual crash but the crash report itself is worthless and has the wrong error.

Sure, here's the latest.log : https://pastebin.com/J1ne18wk

**Comment by LotuxPunk** [comment]
We try to launch it without Immersive and Optifine, same result 😅

**Comment by pupnewfster** [comment]
Looks like the following mods are registering things incorrectly causing a crash: immersive portals and yung's better caves. It seems that both mods have updates on CF to fix the issue: https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves/files/3094882 https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge/files/3096065 though I have not tested them myself to see if they actually fixed the issue.

**Comment by LotuxPunk** [comment]
It was that ! Thanks a lot for the help ! 🙏
