### ISSUE TITLE
Cardboard Box

### ISSUE THREAD

**Issue by Apwalchan** [mekanism/Mekanism#6672]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I Picked up a diamond chest in Valhelia 3 and now I can't get the chest out

#### Steps to reproduce:
1.clicked on the chest with the box
2.break box
3.try and place box with sneak right-click, doesn't work

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 1.16.1-10.0.9.432.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
What version of forge is this, what version of Mekanism, and does hovering over the cardboard box say that it is stored and you just are unable to unbox it or does it not show that it has it stored at all?

**Comment by Apwalchan** [comment]
> What version of forge is this, what version of Mekanism, and does hovering over the cardboard box say that it is stored and you just are unable to unbox it or does it not show that it has it stored at all?

I'm using twitch 
1.16.1-10.0.9.432.jar - Mekanism
and it doesn't say it's stored but the chest is gone

**Comment by pupnewfster** [comment]
Not quite sure what is going on here as I am not able to reproduce this issue in testing, if you go into a new world in creative to try and test are you able to reproduce this? (You will have to switch to survival to break the cardboard box)

**Comment by Apwalchan** [comment]
> Not quite sure what is going on here as I am not able to reproduce this issue in testing, if you go into a new world in creative to try and test are you able to reproduce this? (You will have to switch to survival to break the cardboard box)

i did try it in creative/survival, it came out of the box half of the time i placed it, nothing changed in the way i placed it, it just only worked half the time

**Comment by pupnewfster** [comment]
Hmm I will look into this a bit more later today then and try it a bunch of times, I only tried it once or twice so if it is only something that happens some of the time it is possible it just didn't happen for me.

**Comment by pupnewfster** [comment]
I still am not able to reproduce this (at least in 1.16.3) after testing it a bunch more times and I don't believe anything about the cardboard box's implementation really changed since 1.16.1 so my best guess is that maybe some other mod in that modpack is causing weird things to happen.
