### ISSUE TITLE
Particle Mekanism Laser: Crashing Forge?

### ISSUE THREAD

**Issue by DrainDoc** [mekanism/Mekanism#6673]
[crash-2020-10-31_10.51.30-client.txt](https://github.com/mekanism/Mekanism/files/5469550/crash-2020-10-31_10.51.30-client.txt)
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description: Minecraft/Forge keeps crashing ever since Forge went to 1.6.13-forge-34.1.27 and beyond
The game crashed whilst rendering overlay
Error: java.lang.IllegalStateException: Failed to load description for particle mekanism:laser
Exit Code: -1

Minecraft/Forge launches fine if you revert back to Forge 1.16.3-forge-34.1.25
I understand this could very well be a Forge issue. But just trying to get to the bottom of it.

Thanks

#### Steps to reproduce:
1. Install Forge 1.16.3-forge-34.1.27 --- 1.16.3-forge-34.1.35
2. Install Mekanism 1.16.3-10.0.15.441.jar
3. Launch Minecraft

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.3-forge-34.1.35
**Mekanism:** 1.16.3-10.0.15.441.jar
**Other relevant version:** 1.16.3-forge-34.1.25(works)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Nothing to do with mekanism, if you provide your latest log  I can help you read it to find the actual crash though.

**Comment by DrainDoc** [comment]
[2020-10-31-5.log.gz](https://github.com/mekanism/Mekanism/files/5469591/2020-10-31-5.log.gz)

**Comment by pupnewfster** [comment]
Looks like optifine is crashing.

**Comment by DrainDoc** [comment]
Oh....ok.
 Thanks for the help! I'll look into that....all though, not sure Optifine has had an update since September.
Anyway....thanks again.

**Comment by DrainDoc** [comment]
Just uninstalled Optifine to test.....still crashes with the same error message about Mekanism: laser

**Comment by DrainDoc** [comment]
Kind of convinced at this point that it's a Forge issue.

**Comment by pupnewfster** [comment]
Could just be another mod is crashing after forge but before us that wasn't showing in the log because of all the spam and errors optifine was throwing. And it *is* a forge issue that it is blaming the wrong mod (us), it *is not* a forge issue that is causing the crash though.
