### ISSUE TITLE
Cardboard box blacklist unclear

### ISSUE THREAD

**Issue by MarioSMB** [mekanism/Mekanism#6674]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
According to the description of the cardboardModBlacklist setting, listing any mod ID will block the boxing of "any of their blocks", but it is unclear what a mod ID is in this context, and there are no given examples. Adding an invalid entry here will freeze the game when loading a world.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
There is no example given modid is a very common concept in modded MC, for example `minecraft`, or `mekanism`. I will look into it freezing the world though when loading with invalid entries.

**Comment by MarioSMB** [comment]
As I understand, it can be used as such: `cardboardModBlacklist = ["refinedstorage"]`, but the lack of clear documentation here makes that a difficult thing to find out (in my searches through Google, this is a fairly common issue and it is difficult to find answers regarding the cardboard box in newer versions). I think it would be best to just list "mekanism" as the example in a commented out copy of the setting to avoid this confusion.

**Comment by pupnewfster** [comment]
I will add an example, though I am unable to reproduce it crashing with an invalid modid.

**Comment by MarioSMB** [comment]
The freezing when loading a world appears to have been a configuration error on my part (I intitially did not add the quotation marks around refinedstorage), that is likely a general issue with Forge.  
On that note, I think it's safe to consider this resolved once the clarity issue is fixed.
