### ISSUE TITLE
Error to start Minecraft, error Rendering overlay, Problem of compatibility with mod immersive engineering

### ISSUE THREAD

**Issue by juanretamales** [mekanism/Mekanism#6675]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crash on start, i create this issue for **future question of other peoples** but i delete the mod immersive engineering who reveal crash with this mod and i dont want fix

#### Steps to reproduce:
1. Start Minecraft
2.
3.

#### Version MC 1.16.3:
**Forge:** 34.1.35 (and 34.1.34 but the log is the .35 version)
**Mekanism:** Mekanism-1.16.3-10.0.15.441.jar
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
> The game crashed whilst rendering overlay
> Error: java.lang.IllegalStateException: Failed to load description for particle mekanism:laser
> Código de error: -1

The log file: [here ](https://pastebin.com/LesGemsq)

The log without Apostheosis Mod [here](https://pastebin.com/sRggAxwD)

The problem is the mod immersive engineering 4.1.0-124 , causes crash on start with mekanism.

> Time: 11/1/20 1:52 AM
> Description: Rendering overlay
> 
> java.lang.IllegalStateException: Failed to load description for particle mekanism:laser
> 	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:226) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.particle.ParticleManager.lambda$null$0(ParticleManager.java:169) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.particle.ParticleManager$$Lambda$7730/1716489065.run(Unknown Source) ~[?:?] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) ~[?:1.8.0_51] {}
> 	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) ~[?:1.8.0_51] {}
> 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
> 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
> 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {}
> 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
> Caused by: java.io.FileNotFoundException: mekanism:particles/laser.json
> 	at net.minecraft.resources.SimpleReloadableResourceManager.func_199002_a(SimpleReloadableResourceManager.java:63) ~[?:?] {re:classloading,pl:accesstransformer:B}
> 	at net.minecraft.client.particle.ParticleManager.func_215236_a(ParticleManager.java:205) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	... 8 more
>

**Comment by thiakil** [comment]
_Any_ mod will cause this if it crashes in a specific phase of startup. We already have 50x of these reports, we don't need yours. 

One can find the error simply by looking in one's log file.
