### ISSUE TITLE
[1.16.4] Addons crash the game before even launching

### ISSUE THREAD

**Issue by Excederus** [mekanism/Mekanism#6680]
When I enable any of the Addons (the base mod works fine) they all throw this error:

[main/FATAL] [ne.mi.fo.la.MavenVersionAdapter/]: Failed to parse version spec [[34,),)

paste of the full thing: [https://pastebin.com/fj3fBH9C](https://pastebin.com/fj3fBH9C)

EDIT: I dont know if you can see I'm using Java 14 anywhere in there, but I did test with Java 8 too and it threw the same error

**Comment by pupnewfster** [comment]
Ya I was an idiot, the current build is broken and Mek 10.0.17 is currently being processed by CF, I will close this once it has been approved.
