### ISSUE TITLE
The Thermal Evaporator isn't working

### ISSUE THREAD

**Issue by FaithOmega** [mekanism/Mekanism#6682]
I tried making it in both it's simple and advanced forms and it simply wouldn't work. I'm using the most recent version of Mekanism and Forge. Did the structure simply change or is this a bug?

**Comment by pupnewfster** [comment]
The structure didn't change unless you have valves in the edges and are talking about since 1.15 because in 1.15 it was bugged and allowed for valves on the edges. Though saying most recent of mekanism and forge provides no information... We want numbers

**Comment by Oct0bass** [comment]
Does it emit red particles?  If not try not putting ports on the corners or edges

**Comment by Oct0bass** [comment]
lol sorry pup didn't see you

**Comment by FaithOmega** [comment]
It was the corners thing. God damnit. Thanks.
