### ISSUE TITLE
Mekanism Shield causing crash in chest when chest is opened.

### ISSUE THREAD

**Issue by Allyraya** [mekanism/Mekanism#6684]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. mekanism shield is in chest
2. attempt to open chest
3. crash to desktop

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.42
**Mekanism:** 
[crash-2020-11-03_20.11.05-client.txt](https://github.com/mekanism/Mekanism/files/5484968/crash-2020-11-03_20.11.05-client.txt)

MekanismTools-1.16.4-10.0.17.444
MekanismAdditions-1.16.4-10.0.17.444
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[crash-2020-11-03_20.11.05-client.txt](https://github.com/mekanism/Mekanism/files/5484968/crash-2020-11-03_20.11.05-client.txt)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
If you remove `enchantedbookredesign` does this still happen?

**Comment by Allyraya** [comment]
Yes, even if enchantedbook redesign is disabled.

**Comment by Chunkey** [comment]
My game crashes when I bring up the bronze shield in jei. Flipping through enchantments it crashes when I get to a page with the mekanism bronze shield.
[crash-2020-11-08_14.55.32-client.txt](https://github.com/mekanism/Mekanism/files/5507092/crash-2020-11-08_14.55.32-client.txt)

**Comment by Chunkey** [comment]
Actually, disabling enchantedbookredesign seemed to fix my issue...

**Comment by pupnewfster** [comment]
I can only reproduce this if enchanted book redesign is installed so I am closing this, as I am pretty sure it is something on their end.
