### ISSUE TITLE
Chemical Infuser Unable To Be Crafted

### ISSUE THREAD

**Issue by Dektra1990** [mekanism/Mekanism#6685]
#### Issue description:
Unable to craft chemical infuser in survival mode (available in creative as a stand-alone item, however, the recipe does not allow construction manually in this game mode either)

![2020-11-04_21 50 36](https://user-images.githubusercontent.com/73939486/98102529-cf5a1c80-1ee7-11eb-8d2e-9537fb07262e.png)

#### Steps to reproduce:

1. Attempt to craft a chemical infuser
2. ????
3. profit!

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.25
**Mekanism:** v10 +tools, generators
**Other relevant version:** 1.16.3 minecraft

**Comment by Seniorendi** [comment]
I can try it in 1 hour

**Comment by Robball14** [comment]
please write the version of the mod, it might got fixed in the latest (10.0.17)

**Comment by Dektra1990** [comment]
> please write the version of the mod, it might got fixed in the latest (10.0.17)

Currently running 10.0.13 so i'll try that

**Comment by pupnewfster** [comment]
Try using a steel casing instead of a dynamic tank??

**Comment by Seniorendi** [comment]
Bruh

**Comment by Robball14** [comment]
Bruh
