### ISSUE TITLE
[1.16.x] Radioactive mobs / animals

### ISSUE THREAD

**Issue by YOYOK9** [mekanism/Mekanism#6686]
**Describe the the feature you'd like**
So was watching some videos of the Chernobyl disaster and it got me thinking, Since Mekanism now has radiation would be kinda cool/neat if instead of the mobs around the source just dyeing from the radiation they instead became irradiated / aggressive towards any player. They could also give an effect when attacking the player. These mobs would stay irradiated till death. 

**Describe alternatives you've considered**
Since the aggressive mobs can be annoying enough as is, specially with the new tiny additions, maybe just doing the passive ones. Be rather interesting if for example you had a cow and sheep instead of them getting killed they become angry towards the player due to a radiation spill. Meaning the player will either have to un radiate them or kill them off completely and find new set of "safe" animals. And since the radiation spreads all animals within the area are also angry. 

Ex: like wolves when you punch one on accident in vanilla or angry "radioactive" bees

**Comment by pupnewfster** [comment]
I believe https://github.com/mekanism/Mekanism-Feature-Requests/issues/100 more or less covers this request, so I am going to close this and more or less treat them as "merged".

**Comment by 238-Pu** [comment]
Something else to consider is that radiation does not actually cause living things to become more aggressive. Instead, it either has no effect, or causes health degradation at higher levels.
