### ISSUE TITLE
Gravitational Modulating Unit no longer works when changing dimension with other ways than vanilla portals

### ISSUE THREAD

**Issue by jinkhya** [mekanism/Mekanism#6687]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When you use a waystone (waystones mod) or a command like /home to travel from one dimension to the other, the gravitational module doesn't work anymore. You have to use the keybind to disable/reenable to get it to work again.

#### Steps to reproduce:
1. Wear Mekasuit with gravitational modulating unit
2. travel to nether from overworld using a waystone for example
3. You can no longer fly

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.41
**Mekanism:** 10.0.17.444
**Other relevant version:** waystones 7.3.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Oct0bass** [comment]
Does it also occur with `/execute in <dimension> tp <...>`?

**Comment by pupnewfster** [comment]
Or via mekanism's own teleporters? (You may need to lay them flat on the ground so that you don't touch the ground on the other side.

**Comment by jinkhya** [comment]
The execute tp command suffers the same issue as waystones.
The Mekanism teleporters don't. They can even be vertical, horizontal, I can fly or not before entering the portal, it works fine.

**Comment by andrewsf** [comment]
Also seen with All the Mods 6's "Teleport Pad".
