### ISSUE TITLE
Mek Tool Teleportation doesn't work when seated

### ISSUE THREAD

**Issue by corhean** [mekanism/Mekanism#6689]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When seated using a meka tool's teleport function will not successfully teleport the player, it will place them into a free-cam mode limited by loaded player chunks and exitable by dismounting.

#### Steps to reproduce:
1.hold meka tool with teleport unit installed
2.sit in minecart
3. use teleport from meka tool

#### Version (make sure you are on the latest version before reporting):
**Forge:** 32.0.108
**Mekanism:** 1.16.1-10.0.9.432
**Other relevant version:** (Valhelsia 3 modpack)

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

no log per se as it's not a crash, just unexpected behavior.  works from any object that a player can sit on.

**Comment by corhean** [comment]
trivial tag....it did make me giggle, but it's also true.

**Comment by pupnewfster** [comment]
It is trivial because I fixed a similar thing with teleporters not properly teleporting players riding minecarts so should be pretty easy to just copy paste me fix from that. The harder part will be deciding if I want to make it so you can't teleport or that it teleports the minecart with you.
