### ISSUE TITLE
Rendering problem using ressource pack

### ISSUE THREAD

**Issue by hodo1962** [mekanism/Mekanism#6692]
#### Issue description:
When using a 128x128 ressource pack, mekanism cables do not render correctly (see screenshot):
Optifine didn't help too.
 
![2020-11-05_15 41 21](https://user-images.githubusercontent.com/69686049/98440562-c771c680-20f9-11eb-85c0-a268f44ef8c7.png)

After clicking the cables with the configurator or break them and rebuild, the cables render correctly for a while. 
After a short time, the cables look like before. 

All Mekanism cables are affected. The functionality is not limited.

#### Steps to reproduce:
1. Break the cables or rebuild the configuration
2. After a short time cables do not render correctly
3. Using the original (build in) Minecraft textures - cables render correctly

#### Version (make sure you are on the latest version before reporting):
Minecraft:** 1.16.3
Forge:**  : 31.1.42
Mekanism:** 1.16.3-10.0.15.441

Other relevant version:** 
Mekanism Addons 1.16.3-10.0.15.441
Mekanism Tools 1.16.3-10.0.15.441
Mekanism Generators 1.16.3-10.0.15.441

Tested with the following Ressource Packs:
- LBPR+Reload!+1.16+release+v.4.2
- Mainly Photo Realism x128
- Monsterley_128_16_200803

**Comment by thiakil** [comment]
Post your full mod list

**Comment by hodo1962** [comment]
Here are the list of my mods:
Mods:
  [✔️] aawitherskull_1.16.3_1.1
  [✔️] ava-1.5.0
  [✔️] BetterCaves-1.16.2-1.0.4
  [✔️] BetterMineshaftsForge-1.16.2-1.0.1
  [✔️] biggerreactors-1.16.3-0.2.2-beta
  [✔️] BiomesOPlenty-1.16.3-12.0.0.417-universal
  [✔️] chunkloaders-1.1.0-mc1.16.3
  [✔️] cofh_core-1.16.3-1.0.4
  [✔️] collective-1.16.3-1.51
  [✔️] connectedglass-1.0.6-mc1.16.3
  [✔️] ContentTweaker-1.16-1.0.0.develop.8
  [✔️] CraftTweaker-1.16.3-7.0.0.40
  [✔️] CTM-MC1.16.1-1.1.1.5
  [✔️] Cucumber-1.16.3-4.1.2
  [✔️] curios-forge-1.16.3-4.0.2.0
  [✔️] dankstorage-3.11
  [✔️] extradisks-1.16.3-1.3.3
  [✔️] FluxNetworks-1.16.3-6.0.0.3
  [✔️] ftb-gui-library-1603.1.1.24
  [✔️] gravestone-1.16.3-1.0.2
  [✔️] immersive-portals-0.7-mc1.16.3-forge
  [✔️] industrial-foregoing-1.16.3-3.1.1-a834e76
  [✔️] invtweaks-1.16.2-1.0.0
  [✔️] jei-1.16.3-7.6.0.51
  [✔️] LargeFluidTank-16.0.6
  [✔️] Lollipop-1.16.3-3.2.2
  [✔️] Ma-Essentials-1.16.3-3.4.0
  [✔️] mcjtylib-1.16-5.0.11
  [✔️] Mekanism-1.16.3-10.0.15.441
  [✔️] MekanismAdditions-1.16.3-10.0.15.441
  [✔️] MekanismGenerators-1.16.3-10.0.15.441
  [✔️] MekanismTools-1.16.3-10.0.15.441
  [✔️] metalbarrels-3.3a
  [✔️] mineralchance_1.16.3-1.0
  [✔️] mininggadgets-1.7.0
  [✔️] movingelevators-1.2.24-mc1.16.3
  [✔️] MysticalAgradditions-1.16.3-4.1.0
  [✔️] MysticalAgriculture-1.16.3-4.1.1
  [✔️] MysticalCustomization-1.16.3-2.1.0
  [✔️] NoFog-1.16.2-Forge-b1
  [❌] OptiFine_1.16.3_HD_U_G4.jar (disabled)
  [❌] OptiForge-MC1.16.3-0.3.5.jar (disabled)
  [✔️] phosphophyllite-1.16.3-0.1.1-beta
  [✔️] reap-1.16.3-1.0.2
  [✔️] refinedstorage-1.9.8
  [✔️] refinedstorageaddons-0.7.2
  [✔️] rftoolsbase-1.16-2.0.6
  [✔️] rftoolsbuilder-1.16-3.0.8
  [✔️] rftoolspower-1.16-3.0.8
  [✔️] rftoolsstorage-1.16-2.0.6
  [✔️] rftoolsutility-1.16-3.0.14
  [✔️] rsrequestify-1.16.3-2.0
  [✔️] ScalableCatsForce-2.13.3-build-3-with-library
  [✔️] SolarFluxReborn-1.16.3-16.2.3
  [✔️] staretilltheygrow-1.16.3-1.0.2
  [✔️] theoneprobe-1.16-3.0.4-beta
  [✔️] thermal_cultivation-1.16.3-1.0.5
  [✔️] thermal_expansion-1.16.3-1.0.5
  [✔️] thermal_innovation-1.16.3-1.0.3
  [✔️] thermal_locomotion-1.16.3-1.0.3
  [✔️] thermal-1.16.3-1.0.5
  [✔️] titanium-1.16.3-3.1.0
  [✔️] TrampleStopper-2.4.7+mc-1.16.4
  [✔️] trashcans-1.0.3-mc1.16.3
  [✔️] u_team_core-1.16.3-3.1.10.183
  [✔️] useful_backpacks-1.16.3-1.11.6.83
  [✔️] Xaeros_Minimap_20.25.1_Forge_1.16.3
  [✔️] XaerosWorldMap_1.11.0_Forge_1.16.3
  [✔️] xnet-1.16-3.0.7

**Comment by thiakil** [comment]
immersive-portals-0.7-mc1.16.3-forge

remove that, its the one breaking it.
