### ISSUE TITLE
Logistical transporter issue

### ISSUE THREAD

**Issue by Seniorendi** [mekanism/Mekanism#6695]
#### Issue description:
Hey, i have 2 Chemical Oxidizer which produce uranium oxide. I have one enrichment chamber which produce yellow cake uranium. The ultimate logistical transporter only puts in the first machine the yellow cake uranium because it's always under 64. The second chemical oxidizer does not get  yellow cake uranium(see screen).

![image](https://user-images.githubusercontent.com/67484093/98449367-459e8f00-2133-11eb-8133-2ef66e54aa29.png)

![image](https://user-images.githubusercontent.com/67484093/98449369-4afbd980-2133-11eb-9033-65b978f51dc7.png)

#### Steps to reproduce:
1. Split one logistical transporter into two. 
2. One target does not get enough items.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.3
**Mekanism:**  10.0.17
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No

**Comment by pupnewfster** [comment]
Are you using a logistical sorter set to round robin? If not this is intended as logistical transporters will always try to send to the "closest" destination, and because the first oxidizer's input is not full yet it doesn't attempt to send it to the second one.

**Comment by Seniorendi** [comment]
I will try it with a sorter

**Comment by Seniorendi** [comment]
It works, thanks. :D
