### ISSUE TITLE
Pressurized Reaction Chamber Problem

### ISSUE THREAD

**Issue by lapinoe** [mekanism/Mekanism#6698]
Issue description:
When the ethylene in the Gas-Burning Generator is full, the Pressurized Reaction Chamber still does not stop producing ethylene.

Version:
forge-1.15.2-31.2.45
Mekanism-1.15.2-9.10.9.422

**Comment by Robball14** [comment]
i don't understand where is the problem, seems normal to me

**Comment by thiakil** [comment]
Unless you have some specific redstone setup, this isn't a bug.
