### ISSUE TITLE
Mekanism's portable tank only gives 800mB?

### ISSUE THREAD

**Issue by Algester** [mekanism/Mekanism#6699]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I'm not sure if this is an integration issue with Ex Nihilo but witch water requires 1 bucket's worth (1000mB) to work on anything

#### Steps to reproduce:
1. use a portable tank have it carry witch water
2. in bucket mode right click an exnihilo barrel
3. expect 1000mB worth of fluid but the graphics and HWYLA reports 800mB is only in the barrel

#### Version (make sure you are on the latest version before reporting):
**Forge:43.1.42**
**Mekanism:10.0.17.444** 
**Other relevant version:Ex Nihilo: Sequentia:1.2.1.2**

**Comment by pupnewfster** [comment]
Which tier of tank?

**Comment by Algester** [comment]
Advance tier since its red

**Comment by pupnewfster** [comment]
The reason for this is that the default transfer rate for advanced fluid tanks is 800 mB (There is special handling for picking up and placing liquids in world, to allow it to happen even though the rate is lower). I do think the rates should be adjusted/increased though I am waiting on Aidan to give some input on #6473 before making any changes to it. In the meantime either upgrading your tank to elite (which has a rate limit of 1,600 mB) or adjusting the tiers config for fluid tank tiers to a higher number for basic/advanced should solve what you are running into. In theory though if it is accepting 800 mB you could just click it a second time to provide the last 200 mB it is missing.
