### ISSUE TITLE
minecraft error

### ISSUE THREAD

**Issue by kokokopopo** [mekanism/Mekanism#6700]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  ForgelinPlugin (Forgelin-1.8.3.jar)
  llibrary (llibrary-core-1.0.11-1.12.2.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.10.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  iceandfire (iceandfire-1.9.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 11/9/20 6:43 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (mekanism)
Caused by: java.lang.NoClassDefFoundError: mekanism/common/entity/EntityRobit
	at mekanism.common.MekanismItems.<clinit>(MekanismItems.java:67)
	at mekanism.common.Mekanism.preInit(Mekanism.java:793)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mekanism.common.entity.EntityRobit
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 42 more
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/entity/IEntityBreathable
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 44 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.api.entity.IEntityBreathable
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 48 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1005598360 bytes (959 MB) / 3221225472 bytes (3072 MB) up to 8589934592 bytes (8192 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 61 mods loaded, 61 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                                | Version           | Source                                         | Signature                                |
	|:----- |:--------------------------------- |:----------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft                         | 1.12.2            | minecraft.jar                                  | None                                     |
	| LCH   | mcp                               | 9.42              | minecraft.jar                                  | None                                     |
	| LCH   | FML                               | 8.0.99.99         | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                             | 14.23.5.2854      | forge-1.12.2-14.23.5.2854.jar                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | obfuscate                         | 0.2.6             | minecraft.jar                                  | None                                     |
	| LCH   | ctm                               | MC1.12.2-1.0.2.31 | CTM-MC1.12.2-1.0.2.31.jar                      | None                                     |
	| LCH   | appliedenergistics2               | rv6-stable-7      | appliedenergistics2-rv6-stable-7.jar           | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | codechickenlib                    | 3.2.3.358         | CodeChickenLib-1.12.2.jar                      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | avaritia                          | 3.3.0             | Avaritia-1.12.2-3.3.0.33-universal.jar         | None                                     |
	| LCH   | baubles                           | 1.5.2             | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCH   | guideapi                          | 1.12-2.1.8-63     | Guide-API-1.12-2.1.8-63.jar                    | None                                     |
	| LCH   | bloodmagic                        | 1.12.2-2.4.3-105  | BloodMagic-1.12.2-2.4.3-105.jar                | None                                     |
	| LCH   | bookshelf                         | 2.3.590           | Bookshelf-1.12.2-2.3.590.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | jei                               | 4.16.1.301        | jei_1.12.2-4.16.1.301.jar                      | None                                     |
	| LCH   | chisel                            | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                   | None                                     |
	| LCH   | redstoneflux                      | 2.1.1             | RedstoneFlux-1.12-2.1.1.1-universal.jar        | None                                     |
	| LCH   | cofhcore                          | 4.6.6             | CoFHCore-1.12.2-4.6.6.1-universal.jar          | None                                     |
	| LCH   | cofhworld                         | 1.4.0             | CoFHWorld-1.12.2-1.4.0.1-universal.jar         | None                                     |
	| LCH   | darkutils                         | 1.8.230           | DarkUtils-1.12.2-1.8.230.jar                   | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | enderstorage                      | 2.4.6.137         | Ender-Storage-Mod-1.12.2.jar                   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | endercore                         | 1.12.2-0.5.76     | EnderCore-1.12.2-0.5.76.jar                    | None                                     |
	| LCH   | thermalfoundation                 | 2.6.7             | ThermalFoundation-1.12.2-2.6.7.1-universal.jar | None                                     |
	| LCH   | thermalexpansion                  | 5.5.7             | ThermalExpansion-1.12.2-5.5.7.1-universal.jar  | None                                     |
	| LCH   | enderio                           | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | enderiointegrationtic             | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | enderiobase                       | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | enderioconduits                   | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | enderioconduitsappliedenergistics | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | enderioconduitsopencomputers      | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | enderioconduitsrefinedstorage     | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | enderiointegrationforestry        | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | mantle                            | 1.12-1.3.3.55     | Mantle-1.12-1.3.3.55.jar                       | None                                     |
	| LCH   | tconstruct                        | 1.12.2-2.13.0.183 | TConstruct-1.12.2-2.13.0.183.jar               | None                                     |
	| LCH   | enderiointegrationticlate         | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | enderiomachines                   | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | enderiopowertools                 | 5.2.59            | EnderIO-1.12.2-5.2.59.jar                      | None                                     |
	| LCH   | enderutilities                    | 0.7.15            | enderutilities-1.12.2-0.7.15.jar               | 2b03e1423915a189b8094816baa18f239d576dff |
	| LCH   | extrautils2                       | 1.0               | extrautils2-1.12-1.9.9.jar                     | None                                     |
	| LCH   | zerocore                          | 1.12.2-0.1.2.8    | zerocore-1.12.2-0.1.2.8.jar                    | None                                     |
	| LCH   | bigreactors                       | 1.12.2-0.4.5.67   | ExtremeReactors-1.12.2-0.4.5.67.jar            | None                                     |
	| LCH   | fluxnetworks                      | 4.0.14            | fluxnetworks-1.12.2-4.0.15-32.jar              | None                                     |
	| LCH   | forgelin                          | 1.8.3             | Forgelin-1.8.3.jar                             | None                                     |
	| LCH   | speedsterheroes                   | 1.12.2-2.2.1      | SpeedsterHeroes-1.12.2-2.2.1.jar               | None                                     |
	| LCH   | lucraftcore                       | 1.12.2-2.4.10     | LucraftCore-1.12.2-2.4.10.jar                  | None                                     |
	| LCH   | heroesexpansion                   | 1.12.2-1.3.5      | HeroesExpansion-1.12.2-1.3.5.jar               | None                                     |
	| LCH   | llibrary                          | 1.7.19            | llibrary-1.7.19-1.12.2.jar                     | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCH   | iceandfire                        | 1.9.1             | iceandfire-1.9.1-1.12.2.jar                    | None                                     |
	| LCH   | ic2                               | 2.8.221-ex112     | industrialcraft-2-2.8.221-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCE   | mekanism                          | 1.12.2-9.8.3.390  | Mekanism-1.12.2-9.8.3.390.jar                  | None                                     |
	| LC    | teslacorelib                      | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar               | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | industrialforegoing               | 1.12.2-1.12.2     | industrialforegoing-1.12.2-1.12.13-237.jar     | None                                     |
	| LC    | ironchest                         | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LC    | mcjtylib_ng                       | 3.5.4             | mcjtylib-1.12-3.5.4.jar                        | None                                     |
	| LC    | mekanismgenerators                | 1.12.2-9.8.3.390  | MekanismGenerators-1.12.2-9.8.3.390.jar        | None                                     |
	| LC    | mowziesmobs                       | 1.5.8             | mowziesmobs-1.5.8.jar                          | None                                     |
	| LC    | rftools                           | 7.73              | rftools-1.12-7.73.jar                          | None                                     |
	| LC    | texfix                            | 4.0               | TexFix+V-1.12-4.0.jar                          | None                                     |
	| LC    | thermaldynamics                   | 2.5.6             | ThermalDynamics-1.12.2-2.5.6.1-universal.jar   | None                                     |
	| LC    | sm                                | 1.3               | TypicalHeroes-1.0.2.jar                        | None                                     |
	| LC    | immersiveengineering              | 0.12-89           | ImmersiveEngineering-0.12-89.jar               | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | teslacorelib_registries           | 1.0.15            | tesla-core-lib-1.12.2-1.0.15.jar               | None                                     |

	Loaded coremods (and transformers): 
ForgelinPlugin (Forgelin-1.8.3.jar)
  
llibrary (llibrary-core-1.0.11-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.10.jar)
  lucraft.mods.lucraftcore.core.LCTransformer
EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
  com.enderio.core.common.transform.SimpleMixinPatcher
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
iceandfire (iceandfire-1.9.1-1.12.2.jar)
  com.github.alexthe666.iceandfire.patcher.IceAndFireRuntimePatcher
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 27.20.100.7988' Renderer: 'Intel(R) UHD Graphics 620'
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	Ender IO: No known problems detected.
	Authlib is : /C:/Users/Samsung%20Expert%20X50/AppData/Roaming/.minecraft/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar

	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
	!!!You are looking at the diagnostics information, not at the crash.       !!!
	!!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
	!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)

**Comment by pupnewfster** [comment]
#6182 not mek
