### ISSUE TITLE
Inconsistent biome ambient temperature

### ISSUE THREAD

**Issue by alyxferrari** [mekanism/Mekanism#6702]
#### Issue description:
In certain biomes, multiblocks report different ambient temperatures when not producing heat.
All official Mekanism addons are installed. The only thing connected to the fission reactor is a water source. There is no heat source or solar panel connected to the thermal evaporation plant. I found this in the snowy taiga biome, and haven't tried reproducing it in other biomes.

#### Steps to reproduce:
1. Construct a thermal evaporation plant and fission reactor in the snowy taiga biome (issue may be present in other biomes too).
2. Open up the GUI for each, and you'll see that the temperatures are different.

#### Version (make sure you are on the latest version before reporting):
**Forge: 34.1.42** 
**Mekanism: 10.0.15.441**

#### Screenshots
[Imgur Album](https://imgur.com/a/7D6UT9u)
This is reproducable in the snowy taiga biome, not sure about the others, I didn't test it anywhere else.

**Comment by Genzilla** [comment]
Are the multiblocks at the same elevation? Minecraft's temperature decreases by 1/625 per block above sea level.  While testing/using solar panels in normal worlds (multiple biomes rather than single biome), I have also noticed very small differences in power output from panels side by side with another at the same elevation, leading me to speculate that biome temperature is actually on a gradient. Displaying the temperature at player location would be useful if one were testing.

**Comment by alyxferrari** [comment]
The two multiblocks in the screenshots are at y=68 and y=70, respectively, but there is a >20°C difference between them. As an experienced programmer and mod dev myself, I'd assume that the issue is that the thermal evaporation plant ambient temperature is calculated based on the environment its in, but that the fission reactor temperature is not, instead using some sort of constant for the "scram"'d temperature. This might not be true, I haven't looked at the source or tested in other biomes, it's just speculation.

**Comment by pupnewfster** [comment]
I can confirm that they have different values, it seems the evaporation plant takes biome temperature into account, whereas the fission reactor does not at all. I am not sure if this is an oversight or not, but I am not sure how to fix it so going to just put this on hold for now until @aidancbrady has time to look into this.
