### ISSUE TITLE
Isotopic centrifuge has black gradient on texture when not running

### ISSUE THREAD

**Issue by alyxferrari** [mekanism/Mekanism#6704]
#### Issue description:
The isotopic centrifuge has a black gradient on some faces on the texture when not processing uranium hexafluoride.
This issue still occurs with only Mekanism installed.

#### Steps to reproduce:
1. Place an isotopic centrifuge.
2. Compare texture when processing uranium hexafluoride, and the texture when the centrifuge is not processing anything.

#### Version (make sure you are on the latest version before reporting):
**Forge: 34.1.42** 
**Mekanism: 10.0.15.441** 

#### Screenshots
[Screenshot of issue](https://imgur.com/a/PRjP8jS/)

**Comment by pupnewfster** [comment]
In forge's client config enable the experimental lighting pipeline
