### ISSUE TITLE
Mekanism's tank will get removed by crafting Treated wood from Immersive Engineering

### ISSUE THREAD

**Issue by Algester** [mekanism/Mekanism#6710]
#### Issue description:
when crafting Treated Wood from Immersive engineering and you used the tank filled with treated wood the recipe results in the tank getting "eaten" by the crafting results, where in it should have given the player a bucket

#### Steps to reproduce:
1. fill a Mekanism Tank with creosote oil
2. craft treated wood from immersive engineering

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.42
**Mekanism:** 1.16.4-10.0.17.444
**Other relevant version:** 
**Immersive Engineering:** 1.16.3-4.1.1-127

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://github.com/BluSunrize/ImmersiveEngineering/issues/4449#event-3997217369

according to bluesunrize Mekanism Tank needs "getContainerItem" to so it won't be eaten by the recipe probably making it the same as TE's Portable Tank back in the day

**Comment by pupnewfster** [comment]
I've thought about this more, and there isn't really anything I can do on our end about immersive engineering improperly using/making assumptions about fluid handler items without various side effects, this is something they need to fix.
