### ISSUE TITLE
Items missing in survival crafting but not creative

### ISSUE THREAD

**Issue by rcfergu2** [mekanism/Mekanism#6716]
Hello,

I have recently installed mekanism along with all the additions (list below ) and I opened a survival world and various items are not craftable in survival, such as the charge pad, the fission reactor blocks, etc. However upon inspecting creative mode I found the items in creative just fine. Any help would be appreciated.

List of Mekanism Files in "mods" folder:
1. Mekanism-1.16.4-10.0.17.444
2. MekanismAdditions-1.16.4-10.0.17.444
3. MekanismDefense-1.16.4-10.0.17.444
4. MekanismGenerators-1.16.4-10.0.17.444
5. MekanismTools-1.16.4-10.0.17.444

Any help greatly appreciated

Best

**Comment by Oct0bass** [comment]
What do you mean "not craftable"? Do you have [JEI](https://curseforge.com/minecraft/mc-mods/jei) installed?  If not try installing it and seeing whether they show up there. Not sure how you'd even know the recipes if you didn't have JEI beccause the wiki isn't up to date with them..If the recipes are actually removed for some reason do you have any datapacks or are you playing on a modpacks? If so probably the pack removed it.

**Comment by rcfergu2** [comment]
well I was using the wiki for most of the other craftables, you are saying there isnt a wiki out there with all the crafting recipes and I have to get JEI?

**Comment by pupnewfster** [comment]
If you are playing modded MC you should install JEI as most mods show recipes using it and wikis quickly become out of date. Also Mekanism defense isn't really a mod yet #6322. But yes the recipe for the charge pad has changed in V10.
