### ISSUE TITLE
Mekanism wind generators are cutting out other Minecraft sound

### ISSUE THREAD

**Issue by dylan99rhyne** [mekanism/Mekanism#6721]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Place generators
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Minakill** [comment]
https://github.com/mekanism/Mekanism/issues/6693#issuecomment-730109988

**Comment by Oct0bass** [comment]
Yes, please stop spamming the same issue over and over again, it won't make it get fixed any faster.
