### ISSUE TITLE
Carborad boxes won't open with a full left hand

### ISSUE THREAD

**Issue by Trabber** [mekanism/Mekanism#6723]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
You cannot unwrap blocks in carboard boxes if holding anything in your left hand.

#### Steps to reproduce:
1. Put something in your shield slot (vanilla food, pam's food, and vanilla shield tested)
2. Put a cardboard box over a block (vanilla chest, iron chest, mekanism machine, and skulker box tested)
3. Shift/sneak right click the cardboard box (actual result: nothing happens; expected result: the box pops off leaving the original block)
4. Remove the thing from your shield slot
5. Shift/sneak right click the cardboard box (success)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.3-forge-34.1.42
**Mekanism:** 1.16.3-10.0.15.441
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I looked into this some, and from what I can tell this is intended due to the fact there is not much we can do about this. In vanilla the block never gets "activated" while sneaking if there is something in one of your hands.
