### ISSUE TITLE
Digital Miner does not Auto-Pull

### ISSUE THREAD

**Issue by NillerMedDild** [mekanism/Mekanism#6727]
#### Issue description:
The Digital Miner does not Auto-Pull from any inventories on top.

#### Steps to reproduce:
1. Enable Auto-pull
2. Place inventory with items on top
3. Profit

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.4-35.0.18
**Mekanism:** 1.16.4-10.0.17.444

Original issue: https://github.com/NillerMedDild/Enigmatica6/issues/389

**Comment by pupnewfster** [comment]
Unable to reproduce this, what inventory are you trying? It seems to work as intended with both a vanilla chest and a mekanism bin. One thing to note is it auto pulls when it needs it, it doesn't just fill the miner's inventory with the thing on top just to make sure we still have space for the outputs in the inventory. One thing I did notice though while testing this is that the missing block/all is well icon was rendering at the wrong layer (which I am fixing now).

**Comment by Ridanisaurus** [comment]
I tried it with Mekanism Bin, and Vanilla Chests. Both were not accessible by the Digital Miner for Auto-Pull.

**Comment by Ridanisaurus** [comment]
64 Stacks of Logs in the Bin.
![image](https://user-images.githubusercontent.com/64355028/99855253-ab086c00-2b86-11eb-9276-9018f8594114.png)
After 5 Copper Ores mine, with Auto-Pull set to on, the Bin remains with 64 Logs.
![image](https://user-images.githubusercontent.com/64355028/99855325-e73bcc80-2b86-11eb-89ce-cb3a0d4777cb.png)

**Comment by NillerMedDild** [comment]
> One thing to note is it auto pulls when it needs it

It works just fine, sorry about that :)

**Comment by Seniorendi** [comment]
I do not really unterstand why i should pull things into the miner

**Comment by NillerMedDild** [comment]
The Digital Miner is able to replace the blocks it mines with a block you select, those blocks need to be in the Digital Miner for the replacement to happen.

**Comment by Seniorendi** [comment]
Oh, thanks
