### ISSUE TITLE
Energy Upgrades do not reduce power consumption of the Electrolytic Separator

### ISSUE THREAD

**Issue by Gluton-Official** [mekanism/Mekanism#6729]
#### Issue description:
Energy Upgrades do not reduce the power consumption of the Electrolytic Separator, behavior is no different with Speed Upgrades installed as well (although they do properly increase power consumption).

#### Steps to reproduce:
1. Install any number of Energy Upgrades in an Electrolytic Separator
2. Run the machine and observe power drain

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.42 (1.16.3)
**Mekanism:** 1.16.4-10.0.17.444

**Comment by TepperPepper666** [comment]
This is intended, if the Electrolytic Separator had its power drain reduced with the energy upgrades it'd be possible to create a power loop with a gas burning generator, violating the laws of thermodynamics.

**Comment by Gluton-Official** [comment]
Ah, well in that case, it says it supports Energy Upgrades, and probably should not.

**Comment by pupnewfster** [comment]
It does support energy upgrades, they increase the size of the energy buffer in the machine.
