### ISSUE TITLE
Mobs can spawn inside Boilers

### ISSUE THREAD

**Issue by PongoSapiens** [mekanism/Mekanism#6730]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mobs can spawn inside the multi-block boiler, has no impact on function, just looks incongruous given that it's > 3K degrees in there

#### Steps to reproduce:
1. Build Big Boiler
2. Hang around near it.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 34.1.42
**Mekanism:** 10.0.17.444
**Other relevant version:** MC 1.16.3

**Comment by iiiCpu** [comment]
Mekanism: 10.0.17.444
Frontend:
![2020-11-28_18 05 45](https://user-images.githubusercontent.com/40638625/100514104-7c048280-31a4-11eb-88f3-25017d715273.png)
Backend:
![2020-11-28_18 05 58](https://user-images.githubusercontent.com/40638625/100514115-90e11600-31a4-11eb-8d18-13e3b4eed20d.png)
