### ISSUE TITLE
Digital miner did not recognize all minerals

### ISSUE THREAD

**Issue by Grounli** [mekanism/Mekanism#6731]
Hello, the Digital miner is not able to find some ores, mainly those of AE2 and Compact Ores, and the Dictionary indicates that it does not have tags but the JEI does.

![nokey_3](https://user-images.githubusercontent.com/18368802/99906209-1e6cc380-2cd6-11eb-85a4-6ec5e18b137e.png)
[mc filter.txt](https://github.com/mekanism/Mekanism/files/5579639/mc.filter.txt)
![nokey](https://user-images.githubusercontent.com/18368802/99906210-1f9df080-2cd6-11eb-977e-d7b380035600.png)
![nokey_2](https://user-images.githubusercontent.com/18368802/99906211-20368700-2cd6-11eb-8986-6581f2dcdfab.png)

Modpack:
[The+Final+Frontier+2-1.5.zip](https://github.com/mekanism/Mekanism/files/5579643/The%2BFinal%2BFrontier%2B2-1.5.zip)
https://www.curseforge.com/minecraft/modpacks/the-final-frontier-2/files

I play on a server created by me from this modpack of version 1.5

Greetings

**Comment by pupnewfster** [comment]
They don't add their blocks to block tags take it up with them https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/4763
