### ISSUE TITLE
potential Mod conflict with BYG

### ISSUE THREAD

**Issue by IchigoGames** [mekanism/Mekanism#6736]
#### Issue description:
Mod conflict? when using Digital Miner typeing in *ore shows ores and log wood from byg iv reported this on both sides

#### Steps to reproduce:
1.add mek
2.add byg-1.1.5
3.useing Digital  Miner type in *ore and you will see logs as well as ore also i think related to this sawmill will not accept logs from byg

#### Version (make sure you are on the latest version before reporting):
**Forge: 35.1.0
**Mekanism:Mekanism-1.16.4-10.0.17.444
**Other relevant version:byg-1.1.5
https://github.com/CorgiTaco/BYG/issues/177

**Comment by pupnewfster** [comment]
Not a bug, it is matching our tag: `mekanism:atomic_disassembler_ore` which has all logs and ores in it by default. It is what the normal vein mine mode of the atomic disassembler can mine. Use a more specific tag than just `*ore`. In terms of not accepting logs from BYG, there is no wildcard attempt get all log support anymore for recipes as of the fact that recipes are not defined at runtime. If you want you can open a feature request for support for their logs/planks and I may look into it when I get a chance.
