### ISSUE TITLE
Game crash on enchanting Osmium Shield in server

### ISSUE THREAD

**Issue by TheLenaFox** [mekanism/Mekanism#6737]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When trying to enchant an Osmium shield, the whole game just freezes and crashes, after restarting the game it doesn't allow me back in the server unless I delete the userdata of that user, removing all their items etc etc.

#### Steps to reproduce:
1. craft Osmium Shield
2. Use enchantment table to enchant the shield
3. Game freezes and crashes, not allowing you back inside the server (in my case) until the userdata is deleted.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.3-forge-34.1.42
**Mekanism:**  1.16.4-10.0.17.444
**Other relevant version:** using Valhesia 3 pre5-3.1.0 on server

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Remove enchanted book redesign/report it to them #6684
