### ISSUE TITLE
Nucleosynthesizer shows confusing/wrong antimatter cost

### ISSUE THREAD

**Issue by Paspartout** [mekanism/Mekanism#6739]
#### Issue description:

The JEI Recepie view of the Nucleosynthesizer shows 200mB for each recepie which is way too much and confusing in my opinion. Looking at the code it seems like it somehow displays the mB/t but I think it should show the amount of mB needed for one operation.

![confusing_antimatter_jei](https://user-images.githubusercontent.com/2720369/100115270-9bcd3b00-2e72-11eb-9d26-099281f63f5a.png)

#### Steps to reproduce:
1. Load up any game/save using Mekanism 10 and JEI
2. Press U or right click on antimatter gas in JEI to see usages
3. Hover over the gas tank in the Nucleosynthesizer, it shows 200mB antimatter usage for all recepies.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.0.18
**Mekanism:** 10.0.17 (latest version from 1.16.3 branch)

**Comment by pupnewfster** [comment]
Aha! Looking at it, it is because the JEI code is copy pasted and assumes a per tick usage but the nucleosynthesizer actually passes to the recipe that it has a zero per tick usage, should be trivial to fix for 10.0.18.

**Comment by Paspartout** [comment]
I am trying to get into the mekanism codebase myself at the moment, so I might try to fix it myself.
Would making the NucleosynthesizingRecipe similar to the MetallurgicInfuserRecipe be a good fix for this?

**Comment by pupnewfster** [comment]
I think in theory removing the following lines:
https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/client/jei/machine/NucleosynthesizingRecipeCategory.java#L111-L112
https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/client/jei/machine/NucleosynthesizingRecipeCategory.java#L115-L116
And changing https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/client/jei/machine/NucleosynthesizingRecipeCategory.java#L120 from `scaledGases` to `gasInputs` probably would be enough to fix it, as well as changing:
https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/client/jei/machine/NucleosynthesizingRecipeCategory.java#L93-L96 to be `ingredients.setInputLists(MekanismJEI.TYPE_GAS, Collections.singletonList(recipe.getChemicalInput().getRepresentations()));`

**Comment by Paspartout** [comment]
Thanks for the hints! I figured the first 3 changes out myself but was not paying attention to the setIngredients() method.
My PR should fix it:
![fixed](https://user-images.githubusercontent.com/2720369/100130656-464d5a00-2e83-11eb-8a71-475700904fac.png)
