### ISSUE TITLE
Teleporter stopped working for one player after a couple of days.

### ISSUE THREAD

**Issue by OliverWilen** [mekanism/Mekanism#6742]
I play on a private multiplayer server with around 7 other people. We have the 1.12.2 pack installed. 

We have a portal hub set up which has 8 portals set up leading to peoples bases. After a couple of days of playing on the server, ny portal in my base stopped working. I could however teleport with my personal teleporter to the hub and go to my base through the portal, but it only works one way. All of the other players on the server can use the teleport both ways though.  I have a chunk loader on top of my teleporter, and all of the other portals are working as intended.

I have tried to destroy the portals and create new frequencies etc. but nothing works!

**Comment by pupnewfster** [comment]
Closing this as we are no longer developing for 1.12, though does the teleporter that is not working have enough energy in it to teleport to the other destination? Because if it is out of power that could explain why it is not working.
