### ISSUE TITLE
Shield causes game to crash while searching for its usage (NEI)

### ISSUE THREAD

**Issue by Dimagreg** [mekanism/Mekanism#6744]
**Issue description:**
While using Not Enough Items "U" Key (Shows the recipes that the selected block or item is used in.) on a new or damaged Mekanism Shield (Osmium in my case), game freezes and crashes. 

![2020-11-26_13 41 59](https://user-images.githubusercontent.com/73190746/100347680-68afb680-2fee-11eb-8ddf-f297602ece61.png)

Steps to reproduce:
1. Open NEI GUI and search for an Osmium Shield.
2. Press right click.
OR
1. Craft an osmium shield
2. Damage it
3. Press "U" on the item.

**Version (make sure you are on the latest version before reporting):**

**Forge:** 34.1.42
**Mekanism:** 10.0.17.444
**Other relevant version:** MC 1.16.3 , 
**Modpack:** Valhelsia 3 (1.16.3)  https://www.curseforge.com/minecraft/modpacks/valhelsia-3

**If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)**

[crash-2020-11-26_13.33.43-client.txt](https://github.com/mekanism/Mekanism/files/5602778/crash-2020-11-26_13.33.43-client.txt)

**Comment by pupnewfster** [comment]
#6684 #6737 remove enchanted book redesign this isn't on mekanism's end
