### ISSUE TITLE
Dynamic Tank Improvements

### ISSUE THREAD

**Issue by C4J3** [mekanism/Mekanism#6745]
**Describe the the feature you'd like**
Better Dynamic Tanks.

Currently dynamic tanks, aside from looking cool and being a component of other blocks, are basically useless beyond early game. The single block fluid tanks start negligibly worse at basic and increase to nearly 8x better; and even the higher tier fluid pipes that are meant to be used with them offer more storage per block than the tank blocks themselves.

I think it would be interesting if the dynamic tanks reflected their energy counterparts in the Induction Cell systems with tiered options for both better throughput and storage.

**Describe alternatives you've considered**
Other mods may offer this and most ME systems (RF and AE2) have support for disk based solutions for high quantity and throughput but neither of them offer the same visual feedback as the DT's from mekanism. Also I think having an 'in house' option would be a nice addition to the mod.

**Additional context**
A complete aside but I would also love if Gas Tanks (or chemical tanks as I think they're called now) got the same treatment with a tiered contents visible multiblock storage option from mekanism itself. The tiered stuff could all be collective moved to a new 'sub-mod' or something called mekanism storage if necessary.

**Comment by pupnewfster** [comment]
I don't think this would really work for the dynamic tanks in terms of visually for components. In relation to the balance of tanks/pipes that is being tracked in #6473 (which we do want to adjust, but I don't want to make drastic changes to it until aidan has a chance to review it). In terms of gas/other chemical types you can store those in dynamic tanks as of V10.

**Comment by C4J3** [comment]
If by visually you mean the rainbow of block tiers I can see where you're coming from but functionally I think it works. I really would love to see than DT's still be viable especially later on. Also the DT's storing both types of substances is 👌
