### ISSUE TITLE
Ore Retrogen Not Generating Everywhere

### ISSUE THREAD

**Issue by ntroutman** [mekanism/Mekanism#6746]
I have a world where I enabled ore retro gen, but it isn't generating everywhere, it seems to be generating around spawn, but when I move out to chunks (-44,4,4) there is nothing being added. I've tried regening several times but the server logs never say its regenerating for the chunks where my base is. I'm checking  in game using an xray resource pack. 

Is there some sort of max range from spawn it will work? Or something wrong with the chunks?

**Server Version**
>27.11 08:02:40 [Server] modloading-worker-9/INFO [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 35.1.0, for MC 1.16.4 with MCP 20201102.104115
27.11 08:02:40 [Server] modloading-worker-9/INFO [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v35.1.0 Initialized

**Mods**

> 27.11 08:04:38 [Server] main/INFO [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, bukkit, useful_backpacks-1.16.4-1.11.6.86.jar, decorative_blocks-1.16.4-1.6.0.jar, tombstone-6.0.2.jar, Bookshelf-1.16.4-9.1.13.jar, u_team_core-1.16.4-3.1.13.187.jar, Hwyla-forge-1.10.11-B78_1.16.2.jar, Mekanism-1.16.4-10.0.17.444.jar, forge-1.16.4-35.1.0-universal.jar, AppleSkin-mc1.16.2-forge-1.0.14.jar, KleeSlabs_1.16.3-9.2.0.jar, FastLeafDecay-v25.jar, StorageDrawers-1.16.3-8.2.1.jar, NaturesCompass-1.16.3-1.8.5.jar, ender-chested-1.16.4-1.0.2.jar, MekanismGenerators-1.16.4-10.0.17.444.jar, sleeping_bags-1.16.4-1.0.1.jar, scuba-gear-1.16.4-1.0.1.jar, mrp_v2datagenlibrary-1.16.4-2.0.0.0.jar, morewires-1.16.4-2.0.0.0.jar, MouseTweaks-2.13-mc1.16.2.jar, jei-1.16.4-7.6.0.58.jar, invtweaks-1.16.4-1.0.1.jar, MekanismTools-1.16.4-10.0.17.444.jar, MekanismAdditions-1.16.4-10.0.17.444.jar, PackingTape-1.16.3-0.10.0.jar

**Potentially Useful Log from Server?**
https://paste.shockbyte.com/itamazufikiyeqicetub
https://paste.shockbyte.com/egehafilekosuyazosoy

**Comment by ntroutman** [comment]
Adding a command to force regen for a specific or range of chunks would be nice.

**Comment by ntroutman** [comment]
Just to see if it changed I returned to approximatley world spawn, stopped the server, bumped the world gen version in the config, and relaunched the server:

*Note: Using `/tp troutinator ~ ~ ~` to display coordinates in the log*

```
28.11 06:55:52 [Server] Server thread/INFO [minecraft/DedicatedServer]: [troutinator: Teleported troutinator to -156.97100816122824, 75.0, 248.21427104849272]
28.11 06:56:22 [Server] Server thread/INFO [minecraft/DedicatedServer]: Unknown or incomplete command, see below for error
28.11 06:56:22 [Server] Server thread/INFO [minecraft/DedicatedServer]: #### CHUNK: 3 11 8 in -10 4 15<--[HERE]
```

Then flew over to the area that wasn't generating:

```
28.11 06:57:43 [Server] Server thread/INFO [minecraft/DedicatedServer]: [troutinator: Teleported troutinator to -691.3602117103945, 84.0, 62.31256135662899]
28.11 06:58:02 [Server] Server thread/INFO [minecraft/DedicatedServer]: Unknown or incomplete command, see below for error
28.11 06:58:02 [Server] Server thread/INFO [minecraft/DedicatedServer]: #### CHUNK: 12 4 14 in -44 5 3<--[HERE]
```

Still no ore being generated:

**Full Log:** https://paste.shockbyte.com/camavureqevakahibaji

**Comment by ntroutman** [comment]
Flying back towards spawn the ore gen stops at -29. You can see bellow that Chunk -29 shows tons of ores including Mekanism ores, then in Chunk -30 its all gone
![Chunk-29](https://user-images.githubusercontent.com/1730042/100496022-98051700-3105-11eb-931d-cd1ab3331f48.png)
![Chunk-30](https://user-images.githubusercontent.com/1730042/100496025-9b000780-3105-11eb-8fe1-1b7f5ac27bb0.png)

**Comment by pupnewfster** [comment]
Hmm not quite sure, though I will try to look at it when I get a chance (or at least add a command to force retrogen for a given chunk, as that should be simple enough). Part of me is curious if this [mod](https://www.curseforge.com/minecraft/mc-mods/blame) would add any info to the log about mods doing things incorrectly/strangely and thus causing things not to spawn properly (though part of me doubts it given then I would assume none of the chunks would have it be generating). But it might be worth a shot. Also if you go into entirely unexplored chunks are there ores in general (not just say mekanism but also like vanilla)?

**Comment by ntroutman** [comment]
So.....I installed blame, bumped the version yet again in the ore-regen, and low and behold it generated the chunks that were previously not being generated. Being a software engineer myself, I have two theories...a ghost in the machine, or perhaps somehow the world gen version was somehow already set on the chunks making it be skipped...so, the gamer is just glad my world is working. The SDE is like, WTF happened.

**Comment by pupnewfster** [comment]
My best guess is that the world gen version was somehow already set or something by accident, (I will leave this issue open for now as a reminder to add a command to force add a chunk to be retrogenned as it isn't a bad idea and should be pretty simple to do). One thing to note (though I doubt this was the issue), we only log a message about retrogen if things actually successfully generated (as to not spam the log), so if nothing actually generated from retrogen it won't display the message, though given the vast number of types of ores we spawn I find it unlikely it couldn't find a valid position for any of them in that many chunks.
