### ISSUE TITLE
Crash with mekanism blocks are moved with carry on mod

### ISSUE THREAD

**Issue by benbenlaw** [mekanism/Mekanism#6747]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crash with mekanism blocks are moved with carry on mod

#### Steps to reproduce:
1. place a mekanism block with a recipe in
2. Hold shift to pick up block with carry on mod
3. Plac e block down 
4. The crash

#### Version (make sure you are on the latest version before reporting):
**Forge: 34.1.42** 
**Mekanism:** "Mekanism-1.16.4-10.0.17.444"
**Other relevant version:** carry on "carryon-1.16.3-1.15.1.7"

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by benbenlaw** [comment]
[Uploading crash-2020-11-27_02.29.05-server.txt…]()
[Uploading crash-2020-11-27_01.21.03-server.txt…]()

**Comment by pupnewfster** [comment]
Those crash reports aren't viewable

**Comment by benbenlaw** [comment]
[crash-2020-11-27_02.29.05-server.txt](https://github.com/mekanism/Mekanism/files/5608338/crash-2020-11-27_02.29.05-server.txt)
[crash-2020-11-27_01.21.03-server.txt](https://github.com/mekanism/Mekanism/files/5608339/crash-2020-11-27_01.21.03-server.txt)

**Comment by benbenlaw** [comment]
there you go my bad

**Comment by pupnewfster** [comment]
Seems like this may be on carry-on https://github.com/Tschipp/CarryOn/issues/263#issuecomment-718818067
