### ISSUE TITLE
Mekanism & Quark interaction - Enchant Glints

### ISSUE THREAD

**Issue by TheArtOfGamingMC** [mekanism/Mekanism#6748]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Quark runes don't change the colour of the enchant glint on Meka armour from Mekanism. Although when holding an item with a rune applied, the glint from that item is then applied to the armour.

#### Steps to reproduce:
1.Apply quark rune to item.
2.Hold item in hand while wearing enchanted Meka armour.

#### Versions:
**Forge: 1.16.4 35.1.4** 
**Mekanism-1.16.4-10.0.17.444** 
**Quark-r2.4-276**
**Other relevant version: ATM6-1.3.3**

**Comment by pupnewfster** [comment]
Meka armor can't be enchanted through normal means, and I fixed apotheosis bypassing this for 10.0.18 so honestly not really concerned about this.
