### ISSUE TITLE
Pieces of Mekanism's glowstone armor for some reason are invisible with Mo' Bends installed

### ISSUE THREAD

**Issue by CaptainYoRw** [mekanism/Mekanism#6750]
#6750 Issue description:

#### Steps to reproduce:
1.Installed Mekanism-1.12.2-9.8.3.390
2.Installed MoBends_1.12.2-1.0.0-beta-20.06.20
3.Put on character glowstone armor and look at it from third-view.
4.Some pieces of armor are missing, every time different.
Notice: it only happened with glowstone armor, other types of Mekanism armor working properly.

1.12.2 Version (make sure you are on the latest version before reporting):
Forge: 1.12.2-14.23.5.2854
Mekanism:1.12.2-9.8.3.390

Here's log on Pastebin: https://pastebin.com/mXbKNnWR

**Comment by pupnewfster** [comment]
No idea, probably on mo-bends but we are no longer developing for 1.12
