### ISSUE TITLE
The One Probe Compatibility

### ISSUE THREAD

**Issue by Rover656** [mekanism/Mekanism#6753]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I am unable to look at the power etc. inside of a mekanism tile entity with The One Probe.

#### Steps to reproduce:
1. Install The One Probe and Mekanism
2. Look at a mekanism tileentity

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.7
**Mekanism:** 10.0.17.444
**Other relevant version:** (TOP) 3.0.6

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist](https://gist.github.com/Rover656/d22b2f7d673dc9ebf209ff6846dfb4ca)

**Comment by pupnewfster** [comment]
Are you able to reproduce it with just TOP and Mekanism? From my brief tests I can't reproduce it, and looking at the log looks like something is screwing with the packets and causing the client to not be able to receive data in a form it can understand and thus causing a ton of errors. So if you can't reproduce it with just TOP and Mekanism my best guess is that some other mod you have is either breaking packets in general or packets for TOP by adding garbage data that it doesn't then read properly as well to balance it out.

**Comment by Rover656** [comment]
I shall give this a go for you in a little while

**Comment by Rover656** [comment]
I don't think that I can reproduce this; I think this bug is an artefact of a world upgrade from 1.16.1 -> 1.16.4. I'll close this issue as I've no further things I can test or suggest. Feel free to reopen if someone else has this issue.
