### ISSUE TITLE
reactor frame and Chemical Crystallizer they are not crafted

### ISSUE THREAD

**Issue by rex13164** [mekanism/Mekanism#6754]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I can't build according to the recipes 
<img width="223" alt="Schermata 2020-12-01 alle 08 29 50" src="https://user-images.githubusercontent.com/36922129/100711122-2224d800-33b1-11eb-8810-79382d4f0b4e.png">
chemical crystallizer 
and I can't build reactor frame
<img width="217" alt="Schermata 2020-12-01 alle 08 30 14" src="https://user-images.githubusercontent.com/36922129/100711216-4385c400-33b1-11eb-803f-9042c4301e51.png">

are there any conditions I have to meet?

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  34.1.40 single play
**Mekanism:** 1.16.4-10.0.17.444
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Robball14** [comment]
do you have installed all the mekanism addition mods?
i mean
- Mekanism: tools
- Mekanism: generators
- Mekanism; addition

**Comment by rex13164** [comment]
yes, I tried both with single module installation and with .all files

**Comment by rex13164** [comment]
in cheat mode I find them

**Comment by pupnewfster** [comment]
Use JEI the recipes have changed since V9
