### ISSUE TITLE
1.15.2 digital miner crashes when used

### ISSUE THREAD

**Issue by takeanappa** [mekanism/Mekanism#6755]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
when I try to use my digital miner on my lan minecraft world it crashes leading to me having to fix a Ticking block entity

#### Steps to reproduce:
1. place the miner
2. create a filter
3.hit start

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2-31.2.46-universal
**Mekanism:** 1.15.2-9.10.9.422
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/zbvBwL32

**Comment by pupnewfster** [comment]
Looks like the crash is from a mod called effortlessbuilding
