### ISSUE TITLE
Thermoelectric Boiler Enderman Placing blocks inside

### ISSUE THREAD

**Issue by aowassup** [mekanism/Mekanism#6758]
Having issues with Enderman placing grass blocks inside the water tank even if the Multiblock is already completed.
Unable to place any lighting inside to prevent mobs from spawning. Would like to know if this is an issue or this is expected?

**Comment by Robball14** [comment]
1) this made me laugh
2) you didn't provide any information regarding the version of mekanism and forge, so we can't tell you if it's already fixed or it's a new bug

**Comment by aowassup** [comment]
Apologies. My first time logging an issue.
Mekanism Versions:
Mekanism-1.16.4-10.0.17.444.jar
MekanismAdditions-1.16.4-10.0.17.444.jar
MekanismGenerators-1.16.4-10.0.17.444.jar
MekanismTools-1.16.4-10.0.17.444.jar

Forge Version:
forge-34.1.42

**Comment by aowassup** [comment]
Would like to add the following details. Built an 18x18 Thermoelectric Boiler and a 17x17 Turbine Reactor. So far the Thermoelectric Boiler spawns mobs inside even filled with it filled with water. Checked both the Water Tank and the Steam Tank. For the Turbine Reactor, a Grass block was placed on the upper half of the Turbine but it only occur once and haven't experienced again.

**Comment by pupnewfster** [comment]
Ya already tracking mobs spawning in multiblocks in #6730 (haven't had time yet to look into it given in theory they shouldn't be able to). Leaving this issue open for more specifically looking into if there is a way to stop where endermen can place blocks/teleport to, though it may require me to make a forge PR if there is no hooks currently exposed for it.

**Comment by aowassup** [comment]
Any workarounds I can apply for this? I dont want to let my Boiler disconnect from my fission reactor that would cause it to go boom randomly.

**Comment by Algester** [comment]
My idea would have some sort of filtered entity detector that would prevent emit a redstone signal to your reactor for any endermen nearby

**Comment by iiiCpu** [comment]
> Ya already tracking mobs spawning in multiblocks in #6730 (haven't had time yet to look into it given in theory they shouldn't be able to). Leaving this issue open for more specifically looking into if there is a way to stop where endermen can place blocks/teleport to, though it may require me to make a forge PR if there is no hooks currently exposed for it.

Maybe fill multiblock structures with fake blocks like BedAir?

**Comment by iiiCpu** [comment]
> Any workarounds I can apply for this? I dont want to let my Boiler disconnect from my fission reactor that would cause it to go boom randomly.

Industrial Foregoing's mob slasher is OP.
Also fission reactor has redstone ports. Redstone controlled ultimate pipes themselves can store enough water to cool down medium sized reactor. You can also make thin value under reactor itself to provide extra stop water. _There's always a way, except when there's no way._

**Comment by Algester** [comment]
> > Any workarounds I can apply for this? I dont want to let my Boiler disconnect from my fission reactor that would cause it to go boom randomly.
> 
> Industrial Foregoing's mob slasher is OP.
> Also fission reactor has redstone ports. Redstone controlled ultimate pipes themselves can store enough water to cool down medium sized reactor. You can also make thin value under reactor itself to provide extra stop water. Just make it not connected with main volume. _There's always a way, except when there's no way._

Thing is this is sodium cooled reactor water isnt going into the reactor its sodium which means its the going to go boom regardless because the boiler isnt accepting any super heated sodium from the reactor

**Comment by pupnewfster** [comment]
Putting this on hold for now until something like https://github.com/MinecraftForge/MinecraftForge/pull/7548 gets merged which should make it a lot easier/cleaner for me to deny endermen from placing blocks inside of multiblocks.
