### ISSUE TITLE
Speed upgrades into Solar Neutron Activators

### ISSUE THREAD

**Issue by kill05** [mekanism/Mekanism#6761]
**Describe the the feature you'd like**
Being able to speed upgrade Solar Neutron Acrivators

**Describe alternatives you've considered**
Having a faster/better way to do the processes made into a Solar Neutron Acrivators

**Additional context**
You could put speed upgrades in the Solar Neutron Acrivators until v9, but it is not a thing in v10

**Comment by pupnewfster** [comment]
Correct SNAs got rebalanced to act more like solar panels and be based off of biome temperature and sunlight

**Comment by kill05** [comment]
Thanks for the answer, but what about a faster multi-block/electric version?

**Comment by pupnewfster** [comment]
No, our goal is to eventually remove/replace the SNA we aren't going to be adding more variants of it that would just be counter productive.

**Comment by kill05** [comment]
Okay, thanks!
