### ISSUE TITLE
Entangloporter item buffer? [question]

### ISSUE THREAD

**Issue by LennyPBottom** [mekanism/Mekanism#6763]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I've been using the entangloporter in order to transport items long distances but noticed that it only had an one item buffer. I looked in the config and only saw energy, gas, and fluid buffers, is there a way to increase it for items?

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.36
**Mekanism:**  9.10.9.422
**Other relevant version:** Minecraft 1.15.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
No, it doesn't really make sense mechanically either, with fluids and the like it still also is only one type it is just how much of that one type can fit in the buffer. The closest there is (in V10, so 1.16 I am aware you are in 1.15) is that you could use a QIO as a multitype quantum entangloporter as the QIO system is entirely wireless.
