### ISSUE TITLE
Chemical Dissolution Chamber doesn't allow output to be extracted

### ISSUE THREAD

**Issue by Basedgod199** [mekanism/Mekanism#6764]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Using xnet, i am unable to remove hydrofluoric acid from the Chemical Dissolution Chamber. I'm certain the problem is with the Chemical Dissolution Chamber as i was able to remove hydrofluoric acid from a gas tank using xnet

#### Steps to reproduce:
1.configure xnet to extract gas from the chemical dissolution chamber
2.insert it to any valid block (i was trying to insert it into a chemical infuser)
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.4-35.1.3
**Mekanism:** 1.16.4-10.0.17.444
**Other relevant version:** xnet-1.16-3.0.9 + xnetgases-1.16.4-2.1.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_) N/A

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Is the dissolution chamber setup to allow gas to be extracted from the side you are trying to extract it from? As I don't believe there is any difference in implementation (other than default side config) for how we expose gases for gas tanks and the chemical dissolution chamber.

**Comment by Basedgod199** [comment]
yes i set it to allow extract from every side, still didn't work
