### ISSUE TITLE
Compressing Factory not using 200mb of osmium.

### ISSUE THREAD

**Issue by NeverSnows** [mekanism/Mekanism#6765]
#### Steps to reproduce:
1. Install in Osmium Compressor / Compressing Factory 1 to 8 speed upgrades;
2. Put an osmium ingot in the purple slot;
3. Put a Refined obsidian / refined glowstone dust on the top slot;
4. After the process is finished, hovering over the osmium bar will show you manny diferent results, ranging from not compleeting the compression, to 9mb of osmium beeing left behind.

#### Version:
**Forge: 1.16.3 - 34.1.24**
**Mekanism: 10.0.15.441**

**Comment by kill05** [comment]
Can confirm, I've noticed some strange behaviour with osmium usage.

**Comment by pupnewfster** [comment]
I think this might be/have been intended, though I do agree when it specifically comes to the osmium compressor (and factory) that it makes sense that it should be consistent; for injecting and purifying not so much.
