### ISSUE TITLE
Mekanism crash on minecraft startup

### ISSUE THREAD

**Issue by BryceMalloy** [mekanism/Mekanism#6766]
Hello! Working on a modpack for my server but I can't start Minecraft without it crashing and Forge telling my Mekanism is to blame, unfortunately. I read through the report and tried to start it with foam fix core mod disabled in foam fix configurations like it said, but the outcome did not change. If you can help me that would be very much appreciated.

---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 2020-12-05 23:16:25 EST
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (mekanism)
Caused by: java.lang.NoClassDefFoundError: mekanism/common/entity/EntityRobit
    at mekanism.common.MekanismItems.<clinit>(MekanismItems.java:67)
    at mekanism.common.Mekanism.preInit(Mekanism.java:793)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
    at net.minecraft.client.Minecraft.init(Minecraft.java:467)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: mekanism.common.entity.EntityRobit
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 42 more
Caused by: java.lang.NoClassDefFoundError: micdoodle8/mods/galacticraft/api/entity/IEntityBreathable
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
    ... 44 more
Caused by: java.lang.ClassNotFoundException: micdoodle8.mods.galacticraft.api.entity.IEntityBreathable
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 48 more
Caused by: java.lang.NullPointerException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 791246024 bytes (754 MB) / 2212495360 bytes (2110 MB) up to 4671930368 bytes (4455 MB)
  JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5011m -Xms256m -XX:PermSize=256m
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 88 mods loaded, 88 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID                                | Version                  | Source                                           | Signature                                |
       |:----- |:--------------------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
       | LCH   | minecraft                         | 1.12.2                   | minecraft.jar                                    | None                                     |
       | LCH   | mcp                               | 9.42                     | minecraft.jar                                    | None                                     |
       | LCH   | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | forge                             | 14.23.5.2854             | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCH   | LambdaLib|Core                    | 0.2.0                    | minecraft.jar                                    | None                                     |
       | LCH   | lambdalib2                        | 0.2.0                    | AcademyCraft-1.1.3.jar                           | None                                     |
       | LCH   | academy                           | 1.1.3                    | AcademyCraft-1.1.3.jar                           | None                                     |
       | LCH   | orbis-lib                         | 0.2.0                    | orbis-lib-1.12.2-0.2.0+build411.jar              | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCH   | aether                            | 0.3.0                    | aether_ii-1.12.2-0.3.0+build411-universal.jar    | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
       | LCH   | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                           | None                                     |
       | LCH   | astralsorcery                     | 1.10.27                  | astralsorcery-1.12.2-1.10.27.jar                 | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
       | LCH   | jei                               | 4.16.1.302               | jei_1.12.2-4.16.1.302.jar                        | None                                     |
       | LCH   | cyclicmagic                       | 1.20.8                   | Cyclic-1.12.2-1.20.8.jar                         | 0e5cb559be7d03f3fc18b8cba547d663e25f28af |
       | LCH   | guideapi                          | 1.12-2.1.8-63            | Guide-API-1.12-2.1.8-63.jar                      | None                                     |
       | LCH   | bloodmagic                        | 1.12.2-2.4.3-105         | BloodMagic-1.12.2-2.4.3-105.jar                  | None                                     |
       | LCH   | ctm                               | MC1.12.2-1.0.2.31        | CTM-MC1.12.2-1.0.2.31.jar                        | None                                     |
       | LCH   | chisel                            | MC1.12.2-1.0.2.45        | Chisel-MC1.12.2-1.0.2.45.jar                     | None                                     |
       | LCH   | chiselsandbits                    | 14.33                    | chiselsandbits-14.33.jar                         | None                                     |
       | LCH   | codechickenlib                    | 3.2.3.358                | CodeChickenLib-1.12.2-3.2.3.358-universal.jar    | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | cyclopscore                       | 1.6.6                    | CyclopsCore-1.12.2-1.6.6.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | commoncapabilities                | 2.4.8                    | CommonCapabilities-1.12.2-2.4.8.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | cucumber                          | 1.1.3                    | Cucumber-1.12.2-1.1.3.jar                        | None                                     |
       | LCH   | endercore                         | 1.12.2-0.5.76            | EnderCore-1.12.2-0.5.76.jar                      | None                                     |
       | LCH   | thaumcraft                        | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                 | None                                     |
       | LCH   | enderio                           | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | mantle                            | 1.12-1.3.3.55            | Mantle-1.12-1.3.3.55.jar                         | None                                     |
       | LCH   | enderiointegrationtic             | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | tconstruct                        | 1.12.2-2.13.0.183        | TConstruct-1.12.2-2.13.0.183.jar                 | None                                     |
       | LCH   | p455w0rdslib                      | 2.3.161                  | p455w0rdslib-1.12.2-2.3.161.jar                  | 186bc454cd122c9c2f1aa4f95611254bcc543363 |
       | LCH   | mousetweaks                       | 2.10                     | MouseTweaks-2.10-mc1.12.2.jar                    | None                                     |
       | LCH   | danknull                          | 1.7.91                   | DankNull-1.12.2-1.7.91.jar                       | 644f38521a349310a5dae0239577dc7beebefaec |
       | LCH   | ebwizardry                        | 4.3.1                    | ElectroblobsWizardry-4.3.1-MC1.12.2.jar          | None                                     |
       | LCH   | enderiobase                       | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | enderioconduits                   | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | enderioconduitsappliedenergistics | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | enderioconduitsopencomputers      | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | refinedstorage                    | 1.6.16                   | refinedstorage-1.6.16.jar                        | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCH   | enderioconduitsrefinedstorage     | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | enderiointegrationforestry        | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | enderiointegrationticlate         | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | enderioinvpanel                   | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | enderiomachines                   | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | enderiopowertools                 | 5.2.66                   | EnderIO-1.12.2-5.2.66.jar                        | None                                     |
       | LCH   | enderstorage                      | 2.4.6.137                | EnderStorage-1.12.2-2.4.6.137-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCH   | everlastingabilities              | 1.5.3                    | EverlastingAbilities-1.12.2-1.5.3.jar            | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | potioncore                        | 1.9_for_1.12.2           | PotionCore-1.9_for_1.12.2.jar                    | None                                     |
       | LCH   | eapotioncore                      | 1.0.2                    | EverlastingAbilities-PotionCore-1.12.2-1.0.2.jar | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | fpsreducer                        | mc1.12.2-1.18            | FpsReducer-mc1.12.2-1.18.jar                     | None                                     |
       | LCH   | gravestone                        | 1.10.2                   | gravestone-1.10.2.jar                            | None                                     |
       | LCH   | lucraftcore                       | 1.12.2-2.4.10            | LucraftCore-1.12.2-2.4.10.jar                    | None                                     |
       | LCH   | heroesexpansion                   | 1.12.2-1.3.5             | HeroesExpansion-1.12.2-1.3.5.jar                 | None                                     |
       | LCH   | integrateddynamics                | 1.1.10                   | IntegratedDynamics-1.12.2-1.1.10.jar             | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | integrateddynamicscompat          | 1.0.0                    | IntegratedDynamics-1.12.2-1.1.10.jar             | None                                     |
       | LCH   | integratedtunnels                 | 1.6.13                   | IntegratedTunnels-1.12.2-1.6.13.jar              | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
       | LCH   | integratedtunnelscompat           | 1.0.0                    | IntegratedTunnels-1.12.2-1.6.13.jar              | None                                     |
       | LCH   | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | LCH   | ironbackpacks                     | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                | None                                     |
       | LCH   | ironchest                         | 1.12.2-7.0.67.844        | ironchest-1.12.2-7.0.72.847.jar                  | None                                     |
       | LCH   | journeymap                        | 1.12.2-5.7.1             | journeymap-1.12.2-5.7.1.jar                      | None                                     |
       | LCH   | jeresources                       | 0.9.2.60                 | JustEnoughResources-1.12.2-0.9.2.60.jar          | None                                     |
       | LCH   | lostcities                        | 2.0.22                   | lostcities-1.12-2.0.22.jar                       | None                                     |
       | LCH   | lostsouls                         | 1.1.4                    | lostsouls-1.12-1.1.4.jar                         | None                                     |
       | LCH   | lunatriuscore                     | 1.2.0.42                 | LunatriusCore-1.12.2-1.2.0.42-universal.jar      | None                                     |
       | LCE   | mekanism                          | 1.12.2-9.8.3.390         | Mekanism-1.12.2-9.8.3.390.jar                    | None                                     |
       | LC    | mekanismgenerators                | 1.12.2-9.8.3.390         | MekanismGenerators-1.12.2-9.8.3.390.jar          | None                                     |
       | LC    | mekanismtools                     | 1.12.2-9.8.3.390         | MekanismTools-1.12.2-9.8.3.390.jar               | None                                     |
       | LC    | monk                              | 1.4                      | monk-mod-1.4.jar                                 | None                                     |
       | LC    | mysticalagriculture               | 1.7.5                    | MysticalAgriculture-1.12.2-1.7.5.jar             | None                                     |
       | LC    | mysticalagradditions              | 1.3.2                    | MysticalAgradditions-1.12.2-1.3.2.jar            | None                                     |
       | LC    | nonvflash                         | 1.2.0                    | NoNVFlash-1.12.2-1.2.0.3-universal.jar           | None                                     |
       | LC    | patchouli                         | 1.0-22                   | Patchouli-1.0-22.jar                             | None                                     |
       | LC    | pymtech                           | 1.12.2-1.0.2             | PymTech-1.12.2-1.0.2.jar                         | None                                     |
       | LC    | refinedstorageaddons              | 0.4.5                    | refinedstorageaddons-0.4.5.jar                   | None                                     |
       | LC    | xreliquary                        | 1.12.2-1.3.4.796         | Reliquary-1.12.2-1.3.4.796.jar                   | None                                     |
       | LC    | roughmobsrevamped                 | 2.3.21                   | roughmobsrevamped-1.12.2-2.3.21.jar              | None                                     |
       | LC    | schematica                        | 1.8.0.169                | Schematica-1.12.2-1.8.0.169-universal.jar        | None                                     |
       | LC    | solarflux                         | 12.4.11                  | SolarFluxReborn-1.12.2-12.4.11.jar               | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LC    | thaumicjei                        | 1.6.0                    | ThaumicJEI-1.12.2-1.6.0-27.jar                   | None                                     |
       | LC    | tinkertoolleveling                | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar              | None                                     |
       | LC    | treechopper                       | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                     | None                                     |
       | LC    | valkyrielib                       | 1.12.2-2.0.20.1          | valkyrielib-1.12.2-2.0.20.1.jar                  | None                                     |
       | LC    | universalmodifiers                | 1.12.2-1.0.16.1          | valkyrielib-1.12.2-2.0.20.1.jar                  | None                                     |
       | LC    | vanillafix                        | 1.0.10-150               | VanillaFix-1.0.10-150.jar                        | None                                     |
       | LC    | veinminer                         | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar            | None                                     |
       | LC    | veinminermodsupport               | 0.38.2                   | VeinMiner-1.12-0.38.2.647+b31535a.jar            | None                                     |
       | LC    | worleycaves                       | 1.5.2                    | worleycaves-1.12.2-1.5.2.jar                     | None                                     |
       | LC    | phosphor-lighting                 | 1.12.2-0.2.6             | phosphor-1.12.2-0.2.6+build50.jar                | f0387d288626cc2d937daa504e74af570c52a2f1 |
       | LC    | reauth                            | 3.6.0                    | reauth-3.6.0.jar                                 | daba0ec4df71b6da841768c49fb873def208a1e3 |
  Loaded coremods (and transformers): AstralCore (astralsorcery-1.12.2-1.10.27.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.10.jar)
                                        lucraft.mods.lucraftcore.core.LCTransformer
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.76-core.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6+build50.jar)
                                        
                                      MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
                                        mekanism.coremod.KeybindingMigrationHelper
                                      CorePlugin (AcademyCraft-1.1.3.jar)
                                        cn.lambdalib2.render.mc.PipelineTransformer
                                        cn.lambdalib2.registry.impl.RegistryTransformer
                                      pymtech (PymTech-1.12.2-1.0.2.jar)
                                        lucraft.mods.pymtech.core.PymTechClassTransformer
                                      CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
  GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 26.20.100.7925' Renderer: 'Intel(R) UHD Graphics 620'
  Ender IO: No known problems detected.
            Authlib is : /C:/Users/bmall/OneDrive/Documents/Curse/Minecraft/Install/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - chiselsandbitsIntegration (Enabled/Not Forced)
  Suspected Mods: Mekanism (mekanism)
23:16:25.948
Minecraft ran into a problem! Report saved to: C:\Users\bmall\OneDrive\Documents\Curse\Minecraft\Instances\Server Modpack\crash-reports\crash-2020-12-05_23.16.25-client.txt

**Comment by pupnewfster** [comment]
Not us #6182 take it up with lucraft
