### ISSUE TITLE
Some way to condense steam into water directly.

### ISSUE THREAD

**Issue by SomewhatDamaged** [mekanism/Mekanism#6767]
**Describe the the feature you'd like**
Right now, the only way to deal with steam is to run it through a turbine or vent it. Using the rotary condensentrator on the steam gives _liquid steam_. 

**Describe alternatives you've considered**
A small multiblock structure that turns steam back into water. Perhaps have some kind of fan system that requires power to condense the steam faster.

Maybe making the rotary condensentrator actually output water.

**Additional context**
In this instance, I'm trying to make a small fission reactor that is only there to provide waste products for processing—in effect a "breeder reactor". It would be great to be able to recycle the steam into water without having to build a turbine.

**Comment by Robball14** [comment]
I don't get why this should be added in the mod, the turbine basically does the same thing + produces energy. Adding another multiblock or functionality to the rotary condensator would be totally useless as nobody would want to use something that wastes energy instead of something that basically does the same thing, but also produces energy

**Comment by SomewhatDamaged** [comment]
> I don't get why this should be added in the mod, the turbine basically does the same thing + produces energy.

The reason is I don't want to have to build a turbine just to make a fission reactor. I don't need its power and don't want to waste resources on a turbine. It doesn't have to be a multiblock, just something to turn steam into water rather than "liquid steam" (which is kinda crazy to have, mind you).

**Comment by pupnewfster** [comment]
The way is a turbine.... "liquid steam" is for compat with other mods that use steam using forge's system
