### ISSUE TITLE
[1.12.2] Make concrete powder into concrete via Injection Chamber

### ISSUE THREAD

**Issue by Auroraah** [mekanism/Mekanism#6768]
**Describe the the feature you'd like**

Copy from issue #6166 
Currently I can create clay by injection dirt with water vapor.

It would be nice to be able to create concrete (all 16 colors) by inject water vapor into concrete powder.

It would be nice if this feature could be added to the 1.12.2 version of Mekanism too.

**Comment by pupnewfster** [comment]
We are no longer actively developing 1.12, if you want the recipes in 1.12 you will have to add them via CraftTweaker or something.
