### ISSUE TITLE
[1.12.2] Modded ores not x5 compatible, why?

### ISSUE THREAD

**Issue by Chaoschaot232** [mekanism/Mekanism#6774]
Compared to 1.7.10 in the +1.12.2 version only some ignorable default ores are x5 able but ores like Yellorite, Bauxite and so on are not, why is this so?

Normaly, in 1.7.10, all smeltable ores where be able to be x5ed. Got this functionality removed? I couldn't found anything in the config either to black-/whitelist ores to this.

Max possible is x2 for them (crushing -> smelting).

**Comment by pupnewfster** [comment]
Best guess is you had a mod like JAOPCA installed in 1.7... installing JAOPCA in 1.12 probably will end up adding what you believe is missing.

**Comment by Seniorendi** [comment]
https://www.curseforge.com/minecraft/mc-mods/jaopca (:
