### ISSUE TITLE
Optimize Reactor/Turbine rendering

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#6776]
The reactor and turbine could use some rendering performance upgrades.
This is from a single max size reactor + max size turbine

Conversation from Discord: 
![image](https://user-images.githubusercontent.com/4283717/101996562-e43e8280-3cd3-11eb-8a42-80cbbba48aaa.png)
![image](https://user-images.githubusercontent.com/4283717/101996595-54e59f00-3cd4-11eb-8a79-b13126523b9f.png)

Profiling:
[reactorprofiling.zip](https://github.com/mekanism/Mekanism/files/5683859/reactorprofiling.zip)

Note that I've not used any reactor glass in either of the builds which is probably also something that could be considered.

**Comment by pupnewfster** [comment]
Marking this as fixed in dev, there are a couple more improvements I can think of that I will try to implement in 10.1, but it should make a decent start now.
