### ISSUE TITLE
inhilation purification unit using power even when set not to remove neutral potion effect

### ISSUE THREAD

**Issue by antrobot1234** [mekanism/Mekanism#6778]
#### Issue description:
The inhilation Purification Unit module for the MekaSuit helmet consumes power when a neutral effect is applied, even when it's set to not remove the effect in the tweaker menu.
#### Steps to reproduce:
1. put on helmet with power and an inhalation uni
2. toggle the 'remove Neutral' setting to false
3. apply 'Neutral' potion effect (like levitation)
4. it consumes helmet's power supply (bug) but doesn't get rid of the potion effect (intended)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.0
**Mekanism: ** 10.0.17

**Comment by pupnewfster** [comment]
What other neutral potion effects did you try, I am looking into this and mojang marks levitation as a "Harmful" potion effect.
![image](https://user-images.githubusercontent.com/1203288/106203855-07d96180-618a-11eb-8798-4ce1ffe36824.png)
