### ISSUE TITLE
"Electrolytic Separator" does not respond the "Energy Upgrades"

### ISSUE THREAD

**Issue by BlacKHaraZ** [mekanism/Mekanism#6779]
#### Issue description:
"Electrolytic Separator" does accept "Energy Upgrades" but if you put some in the power consumption don't sink.

#### Steps to reproduce:
1. Tage "Energy Upgrades" in inventory and open "Upgrade"-GUI at "Electrolytic Separator"
2. Put "Energy Upgrades" in Upgrade-Slot and let them load
3. Control your power consumption of the machine. It will be still 160 FE/t and doesn't matter how much Upgrades you put in. Other Upgrades workes well.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.0 up to 35.1.13
**Mekanism:** 1.16.4-10.0.18.445
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No Crash

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Robball14** [comment]
#6729

**Comment by BlacKHaraZ** [comment]
Not seen. Sry. =(

**Comment by pupnewfster** [comment]
Yes and this is not a bug which if you read the responses to the issue linked you would know.

**Comment by BlacKHaraZ** [comment]
I'm really sorry about this.

I wrote the last at work and was too busy at that moment. 'xD

So sry guys =)
