### ISSUE TITLE
Digital Miner won't mine things using the Tag Filter

### ISSUE THREAD

**Issue by TheOwnerOfThis** [mekanism/Mekanism#6781]
#### Issue description:
The digital miner won't mine anything use the Tag Filter, but works fine if I use itemstack with the ore.

#### Steps to reproduce:
1. Open the digital miner config
2. Click new filter and then tag
3. Enter a tag of an ore, such as *Diamond or *Iron
4. Save and start the digital miner

#### Version:
**Forge:** 35.1.11
**Mekanism:** 10.0.18
**MC Version:** 1.16.4
**Other relevant version:** ?

#### If a (crash)log is relevant for this issue, link it here:

Latest log: https://www.dropbox.com/s/tz1zccoqqveq67p/latest.log?dl=1
Video: https://www.dropbox.com/s/e97if9eh2t8h8l0/Base%20Profile%202020.12.13%20-%2012.21.35.03.mp4?dl=0

#### Additional Information:
I do have a claiming mod but unless it's doing something very finicky, the digital miner will mine ores using the itemstack option.

The claiming mod is FTB Chunks
**Mod Version:** 1604.2.1.50

**Comment by Seniorendi** [comment]
forge:ores/iron is the tag for iron ore
not just Iron

**Comment by pupnewfster** [comment]
Are you actually using capital letters or not in the filters given tags don't support capitals (it is on my list of things to do to make it so it auto lowercases the string input, but I don't think it currently does so). For example the full tag for diamond would be `forge:ores/diamond` though using the pseudo regex `*diamond` should in theory work, but `*Diamond` probably won't as I don't think it currently auto converts to `*diamond` from `*Diamond`.

**Comment by Seniorendi** [comment]
Oh, i didn't know that *diamond works.

**Comment by pupnewfster** [comment]
> Oh, I didn't know that *diamond works.

Well it will also grab any other matching things like `forge:storage_blocks/diamond` which may not be desired but it will match `forge:ores/diamond` as part of the match.

**Comment by TheOwnerOfThis** [comment]
> Are you actually using capital letters or not in the filters given tags don't support capitals

It seems to be that writing *diamond works, and *Diamond does not. Thank you.

**Comment by TheOwnerOfThis** [comment]
I guess another rule of thumb would be to craft the Dictionary and write whatever it says because so far at least one of the tags it gives works 100% of the time
