### ISSUE TITLE
multiblocks ignoring multiple valid output gas pipes

### ISSUE THREAD

**Issue by Lexi-kelly** [mekanism/Mekanism#6782]
#### Issue description:
if you have a multiblock, (for example a boiler) that is outputting more gas than the connected pipe can extract, (for example 1.5 ultimate pipes worth of steam) it backs up into the multiblock's internal buffer, this makes sense. if you add a second output pipe, it would be logical for the first pipe to be fully used, and the second pipe at 50% flow rate. meaning the full output would be extracted. this is not what happens, instead, every pipe after the first is ignored, and it continues to backup into the internal buffer.

**Comment by pupnewfster** [comment]
1. What version are you on
2. Do you have both ports set to output?

**Comment by Lexi-kelly** [comment]
i'm on version 10.0.18.445 of mekanisim and both ports are set to output.

**Comment by pupnewfster** [comment]
I am not able to reproduce this it seems to be properly outputting to both networks of tubes when the rate is higher than the capacity of a single tube network. Do you have any pictures of your setup/is this still happening to you?
