### ISSUE TITLE
Discord Server?

### ISSUE THREAD

**Issue by TheOwnerOfThis** [mekanism/Mekanism#6783]
**Describe the the feature you'd like**
A discord server, and if there is one, maybe put the discord invite link somewhere in the wiki or on the curseforge page. Unless I really missed it, I tried hard to look for it!

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pupnewfster** [comment]
There is one listed on both the curseforge page (or at least was pre V10), as well as on the readme for this github.
