### ISSUE TITLE
Pipe covers or compatibility with chisels and bits

### ISSUE THREAD

**Issue by RedTech64** [mekanism/Mekanism#6784]
**Describe the the feature you'd like**
It seems like since MCMultipart is gone, there is no longer a way to use a mod like Chisels and Bits to cover Mekanism cables (1.16.4). This is really unfortunate since there is no longer a way to easily hide cables. Native covers would be great if it isn't possible to get the cables to work with Chisels and bits.

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/114

**Comment by thakyZ** [comment]
Will this ever be added to 1.16.4 since chisel and bits is updated, and in 1.12.2 it works with chisels and bits?
