### ISSUE TITLE
Osmium compressor: speed mods change osmium usage in recipes

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [mekanism/Mekanism#6787]
#### Issue description:
Normally, say, for refined obsidian ingots you will use 200 mb of osmium per ignot. However, if you add in speed upgrades to the compressor, the osmium usage increases in an unpredictable way.

#### Steps to reproduce:
1. Have an osmium compressor and speed mods at ready.
2. Put two osmium ingots in and two refined obsidian dusts. (400 mb osmium used)
3. Observe that you get 2 refined obsidian ingots with no residual osmium left.
4. Put in, say, 4 speed mods.
5. Put two osmium ingots in and two refined obsidian dusts again
6. Not enough osmium now.
7. Add one more osmium ingot
8. Observe you'll have 102 mb of osmium left (thus 498 mb of osmium was used instead of the expected 400)

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.3 - 34.1.42** 
**Mekanism: 10.0.17.444** 
**Other relevant version: Valhesia 3 modpack** 

#### Screenshots
Initial state (59 osmium ingots, 2 refined dusts in, no speed mods):
![javaw_FbLIKGW1hd](https://user-images.githubusercontent.com/860874/102368633-e27b0480-3fdc-11eb-9e76-dc04ef8adb31.png)

Intermediate state (no residual osmium, 2 osmium ingots used):
![javaw_8qPM6rU117](https://user-images.githubusercontent.com/860874/102368729-fe7ea600-3fdc-11eb-903d-e4f8c70f3d48.png)

Final state (102 mb of residual osmium, 3 osmium ignots used):
![javaw_Ij5wJEgqvv](https://user-images.githubusercontent.com/860874/102368991-49002280-3fdd-11eb-93a3-652b5cf6a3e8.png)

**Comment by DeltaEpsilon7787** [comment]
Related issue: #6765, however, seems like there the usage was lower than intended.

**Comment by pupnewfster** [comment]
This is intended, since that last issue I talked with aidan and it is fully intended that it is supposed to use/require more osmium if you install speed upgrades.

**Comment by DeltaEpsilon7787** [comment]
This is pretty weird. The only machine where the resource usage is amplified by speed mods, not in a very predictable way (4 speed mods increase the speed by 16x, but the osmium usage is increased by ~1.245x).

Not to mention, if you want to converse resources, then it'd better to build more osmium compressors than to use speed mods.

**Comment by pupnewfster** [comment]
Incorrect, the osmium compressor, purification chamber, and chemical injecting chamber all have the cost of the "gas' increased with speed upgrades. Also it is always better to build more than install speed upgrades if you want to conserve resources as the energy cost goes up as well at a faster rate than the speed increase.

**Comment by DeltaEpsilon7787** [comment]
Hm, alright then.

**Comment by BenCat07** [comment]
it makes automation very annoying, instead of being able to just give a machine 1 osmium + one reinforced redstone for example, you need to make sure to provide it a constant source, thus requiring you to build multiple different osmium compressors if you want to automate different recepies, as else the tank having contents will hinder you

**Comment by pupnewfster** [comment]
Either don't install speed upgrades then, or just always fill it with osmium as there are no other recipes that require something other than osmium unless a modpack adds them that use the osmium compressor. In which case it probably is easier to just do what people tend to do and have a machine per type of secondary input.
