### ISSUE TITLE
I cant disable testrules

### ISSUE THREAD

**Issue by desconection** [mekanism/Mekanism#6788]
how i disable mekanism /mek testrules ? i did the command and now. i dont have day night cycle....

**Comment by pupnewfster** [comment]
Just use the gamerules command to re-enable whatever rules that it says it disables. It is just a utility command to change a bunch of gamerules in a new world to not be annoyed by mobs and the like while testing.

**Comment by desconection** [comment]
Can you please tell me what gamerules the mek testrules set?

**Comment by pupnewfster** [comment]
keepInventory -> true
doMobSpawning -> false
doDaylightCycle -> false
doWeatherCycle -> false
mobGriefing -> false
