### ISSUE TITLE
Thermal evaporation plant should have a "Dump" option

### ISSUE THREAD

**Issue by whizvox** [mekanism/Mekanism#6791]
**Describe the the feature you'd like**
The Thermal Evaporation Plant can get "stuck" with a very small amount of water or brine in the input slot, meaning you have to craft 2 separate plants if you want to get liquid lithium, which seems quite excessive in my mind. In a past issue (#6222), this same problem was brought up. It appeared that removing then replacing the controller voided any fluids, but that no longer seems to be the case. Currently, the excess input fluid stays stuck unless you disassemble the entire structure and move it somewhere else. There appears to be no other way to get it out.

My suggestion is to follow what the Energetic Infuser does and add a "Dump" option, which will void any remaining input fluids at the click of a button.

**Describe alternatives you've considered**
An alternative would be to fix the previously mentioned issue. Another would be the option to add an empty tank in the top-left-hand slot to collect the excess fluid for you, rather than only allowing sources of water or brine.

**Additional context**
![2020-12-17_21 29 16](https://user-images.githubusercontent.com/8813286/102578432-04dd5280-40af-11eb-9114-3374e1a5ecd9.png) (From version 10.0.18)

**Comment by pupnewfster** [comment]
I don't think this is going to happen as the GUI is already rather crowded, but you can void the contents using a gauge dropper. Left click the tank with a gauge dropper to pick up the contents, or shift left click to void them (this works in all our GUIs)

**Comment by whizvox** [comment]
Alright then, thanks for the info!
