### ISSUE TITLE
Liquid source block and basic tank in same block space after shift right click

### ISSUE THREAD

**Issue by korti11** [mekanism/Mekanism#6794]
#### Issue description:
Idk if this is intended but, I shift right clicked a basic tank with a lava bucket and the lava source block got placed in the same block space as the basic tanks. I also got the same behavior with a water bucket.

#### Steps to reproduce:
1. Shift right click a Basic Tank with full bucket.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.13
**Mekanism:** 10.0.18.445
**FTB Presents Direwolf20 1.16 Modpack:** 1.0.0

![](https://i.imgur.com/0ug3RFI.png)

**Comment by pupnewfster** [comment]
Yes, this is because our blocks can be water and lava logged, and by shift clicking it instead of just normally right clicking it to transfer you said "I want to place this fluid" so it got placed.
