### ISSUE TITLE
Quantum Entangloporter randomly stops teleporting items from digital miner to base

### ISSUE THREAD

**Issue by Sketchyaesthetic** [mekanism/Mekanism#6795]
#### Issue description:
After moving my Digital Miner for the first time I set up two Quantum Entagloporters to send the ores back to base. while it was working fine at first it seems like it breaks randomly and has now stopped working all together. Its not an issue with the logistical sorter because when I set it to pull from a chest instead of the Entangloporter it works just fine.

#### Steps to reproduce:
1.Set up digital miner away from base to send ores back via two quantum entagloporters
2. Filter ores through logistical sorter and send them to enrichment chamber and then smelters
3. pipe newly created bars into their own respective bins.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.4
**Mekanism:** V10
**Other relevant version:**

**Comment by Robball14** [comment]
did you gave to both the Quantum entangloporters an anchor upgrade?

**Comment by pupnewfster** [comment]
1. What version of V10 is it (there are about 19)?
2. Attach a normal transporter or something and pull into the chest, the entangloporter has a buffer of one stack, my best guess is something is "stuck" inside because the sorters aren't configured to remove whatever it is or there is no valid destinaation.

**Comment by Sketchyaesthetic** [comment]
I was able to find the issue. I didn't have anchors installed. thanks for the help.
