### ISSUE TITLE
Mekasuit: Charge Distribution Unit distributes charge to lasers in inventory (if the "charge inventory items" setting is active)

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [mekanism/Mekanism#6796]
#### Issue description:
Lasers get charged by charge distribution unit, which makes placing them in a mekasuit insanely annoying. Though the setting does exactly what it says on the tin, a laser should probably be an exception to the rule.

#### Steps to reproduce:
1. Obtain a mekasuit with a charge distribution unit (ensure the suit has charge) that's set to charge items in your inventory.
2. Get a laser
3. Place it down.
4. The laser is always placed down charged

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.3 - 34.1.42** 
**Mekanism: 10.0.17.444** 
**Other relevant version: Valhesia 3 modpack**

**Comment by pupnewfster** [comment]
As there are plenty of ways to cause this to happen:
- Breaking a laser with energy in it
- Crafting one with energy tablets that have a charge
- This one with the charge distribution unit
We don't think it is something that is really worth working around as there are plenty of other ways that can case you to accidentally zap yourself if you are not being careful enough.
