### ISSUE TITLE
Crash with universal cables

### ISSUE THREAD

**Issue by dangsc2** [mekanism/Mekanism#6802]
https://pastebin.com/FHLEuB0v

Server crashed when placing a universal cable.

**Comment by pupnewfster** [comment]
I am 99% certain this is due to moving either the cable or the machine you connected it to with carryon https://github.com/Tschipp/CarryOn/issues/263

**Comment by dangsc2** [comment]
It was universal cable connected to a heat generator, and the cable was only 3 blocks long. It was a super simple and not complicated setup as the server is only a few hours old.

**Comment by pupnewfster** [comment]
That has nothing to do with it, the only time I have seen that crash report before is when CarryOn (which you do have installed) is used to move blocks because it doesn't properly update position information so the tile is invalid.
