### ISSUE TITLE
Personal Chests cannot be used in crafting recipies if they have items in them

### ISSUE THREAD

**Issue by Sketchyaesthetic** [mekanism/Mekanism#6803]
**Describe the the feature you'd like**
A personal chest cannot be used in crafting recipes if you already have items stored inside of it.

**Describe alternatives you've considered**

**Additional context**
This will stop players from accidentally using they're chest with a ton of important stuff as crafting material and losing everything inside

**Comment by pupnewfster** [comment]
We already don't allow people to use personal chests in our recipes if they can't transfer the contents to the thing being crafted. We can't control if other mods allow using it or not, as I am not going to remove the personal chest from the chests tag as it is a chest... The real thing is other mods probably should consider if they should be using the chests tag or the chests/wooden tag.

**Comment by Sketchyaesthetic** [comment]
the issue happened when I was creating a modification station which is a mekanism recipe.

**Comment by pupnewfster** [comment]
Didn't realize that aidan added a recipe in V10 that has this issue.
