### ISSUE TITLE
Redstone signal does not work with diversion transporter

### ISSUE THREAD

**Issue by BLEEPBLOOPforLife** [mekanism/Mekanism#6805]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I am using the diversion transporter and am trying to disconnect it from the other diversion transporters with redstone. However, after setting the diverter mode to active with signal, it still is connected and works even without a signal. Same thing with active without signal.

#### Steps to reproduce:
1. Place a diversion transporter.
2. Set the diverter mode.
3. Watch as items still go through with the appropriate redstone signal.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2847
**Mekanism:** Mekanism-1.12.2-9.8.3.390
**Other relevant version:** Minecraft 1.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

No relevant logging output.

**Comment by pupnewfster** [comment]
I fixed this sometime late 1.15 or in V10 I forget which, unfortunately we are no longer developing for 1.12 so the state the transmitters are in will stay how they are.
