### ISSUE TITLE
Is there anywhere to easily see the computercraft functions?

### ISSUE THREAD

**Issue by MASACR99** [mekanism/Mekanism#6806]
That's all, in case there isn't it would be a nice addition to the wiki/readme

**Comment by Seniorendi** [comment]
You kan use peripherals.getMethods(String). But Mekanism has no CC functionality.

**Comment by pupnewfster** [comment]
I believe the wiki has some misc things it mentions for what integration there was in 1.12, but for 1.15+ we don't have computer craft integration again yet. #6445
