### ISSUE TITLE
Sawdust's drop chance from logs in the precision sawmill isn't 100% as your wiki says!

### ISSUE THREAD

**Issue by Qattos** [mekanism/Mekanism#6808]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Trying to get sawdust to make paper using the precision sawmill but it's taking so much time, its drop chance isn't 100% as your mod's wiki says, it feels more like 25%.

#### Steps to reproduce:
1. self-explanatory
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.13
**Mekanism:** 10.0.18 
**Other relevant version:** Valhelsia 3 (v3.1.1) modpack

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
It is 25% and has been for a long time if not always. If the wiki says 100% then it is either out of date or incorrect.

**Comment by Qattos** [comment]
@pupnewfster Thank you, I'm still new to your mod.
Seems like any wooden stairs have a 38% drop chance.

**Comment by pupnewfster** [comment]
Just look at the chance using JEI (Just enough items)
