### ISSUE TITLE
[1.12.2] Energy Upgrade on Electrolytic Seperator not working correctly

### ISSUE THREAD

**Issue by Chaoschaot232** [mekanism/Mekanism#6809]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Energy Upgrades on Electrolytic Seperator don't take effect

#### Steps to reproduce:
1. Make and place an Electrolytic Seperator, dump the Oxygen excess and only extract the Hydrogen into a Gas-Burning Generator
2. Add Energy Upgrades and you'll see that the 160 RF/t not going down. Instead the "needed RF/t" raises up to arround 700 kRF/t (with and without speed upgrades)

#### Version (make sure you are on the latest version before reporting):
**Forge:** latest available for 1.12.2
**Mekanism:** latest available for 1.12.2
**Other relevant version:** n/a

I wounder while this was never reported/fixed in 1.12.2 main times but it is definitly not the intended behavior as any Energy Upgrade reduces the required amount of energy instead of raising it up.

**Comment by Seniorendi** [comment]
#6779

**Comment by Chaoschaot232** [comment]
I see, so I've to write my own addition for this. Sorry, but I can't agree with this even if the upgrades rasing up the internal energy storage buffer and even if it ends up in a loop but this is what I and maybe some other players, wanting ... that little bit magic in the block and mechanic ;)
