### ISSUE TITLE
New coral block recipes aren't working

### ISSUE THREAD

**Issue by VegetarianDomo** [mekanism/Mekanism#6811]
Issue description: Every new coral recipe that uses the chemical injection chamber to turn dead coral to normal coral aren't working. Tried both steam and water vapor and they both don't work.

#### Steps to reproduce:
1. Use Chemical Injection Chamber 
2. Put dead coral into the Chemical Injection Chamber
3. Input water vapor or steam

#### Version (make sure you are on the latest version before reporting):
**Forge: 35.1.13
**Mekanism: 10.0.18.445

![2020-12-23_20 50 27](https://user-images.githubusercontent.com/76543903/103056004-5ed39180-4561-11eb-8584-d2bb0a181f23.png)

**Comment by mockanist** [comment]
I believe I found a fix. The file for dirt to clay has the `amount` under `gasInput` set to 1, while tube coral block has the same `amount` set to 750. I tested that the recipes work when using a machine that has an internal gas buffer with more than 750 millibuckets, so using an Advanced Injecting Factory should work. The recipe incorrectly shows you need 200 millibuckets though, which is the cause of the perceived bug.

```
Mekanism/src/datagen/generated/mekanism/data/mekanism/recipes/injecting/dirt_to_clay.json
Mekanism/src/datagen/generated/mekanism/data/mekanism/recipes/injecting/coral/tube_coral_block.json
```

**Comment by DrGeno** [comment]
> I believe I found a fix. The file for dirt to clay has the `amount` under `gasInput` set to 1, while tube coral block has the same `amount` set to 750. I tested that the recipes work when using a machine that has an internal gas buffer with more than 750 millibuckets, so using an Advanced Injecting Factory should work. The recipe incorrectly shows you need 200 millibuckets though, which is the cause of the perceived bug.
> 
> ```
> Mekanism/src/datagen/generated/mekanism/data/mekanism/recipes/injecting/dirt_to_clay.json
> Mekanism/src/datagen/generated/mekanism/data/mekanism/recipes/injecting/coral/tube_coral_block.json
> ```

I've tried using the advanced injecting factory but with no luck, still refuses to process any of the coral blocks

![image](https://user-images.githubusercontent.com/60858383/103517893-c5628480-4e6a-11eb-9ad7-7ba280336f77.png)

**Comment by cambamsyt** [comment]
Same problem here on the latest 1.16 FTB Direwolf20 pack.  The 210mB seems fishy to me.
![image](https://user-images.githubusercontent.com/64878418/104628702-89979e00-5666-11eb-9db2-156c062b6a1e.png)

**Comment by ThePixelaxt** [comment]
Same problem here, also on the latest version of Direwolf20 pack on 1.16.4.

![image](https://user-images.githubusercontent.com/9498198/105835246-dc107d00-5fcb-11eb-88e9-cd01ce422d28.png)

**Comment by pupnewfster** [comment]
Started looking into this and there are two issues:
1. As mentioned our JEI integration isn't properly scaling the required amount
2. I forgot how the recipe works and that we specify a per tick multiplier so the recipes are requiring a couple hundred times the intended amount.

**Comment by elite0x33** [comment]
I had maxed out speed/energy upgrades, removing 1-2 of the speed upgrades allowed me to process the coral.

**Comment by cambamsyt** [comment]
I used a full gas tank and that resolved the issue.

**Comment by dgspades** [comment]
I tried it with a full gas tank and max gas upgrades and I  cannot revive my coral, please help 
![image](https://user-images.githubusercontent.com/78623411/107094691-b3a33280-67c4-11eb-9605-ce89793e47a1.png)

**Comment by ThePixelaxt** [comment]
> I tried it with a full gas tank and max gas upgrades and I cannot revive my coral, please help
> ![image](https://user-images.githubusercontent.com/78623411/107094691-b3a33280-67c4-11eb-9605-ce89793e47a1.png)

Install some installers to make it a factory, I don't know when it actually works, but with ultimate Tier, it definetly does.
