### ISSUE TITLE
SPS: power usage is not limited by process rate

### ISSUE THREAD

**Issue by DeltaEpsilon7787** [mekanism/Mekanism#6812]
#### Issue description:
SPS will take and consume an arbitrary amount of power given to it regardless of polonium feeding rate as long as it's active.

#### Steps to reproduce:
1. Build an SPS.
2. Provide it with, say, 1 mB/t of polonium by running a fission reactor at 10 mB/t burn rate.
3. Give it however much power you want by any means
4. Observe the SPS consuming (and therefore waste) all of the power provided even though 1 mB/t of polonium is supposed to only take 1 MJ/t.
Ω. Is this intended?

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.3 - 34.1.42** 
**Mekanism: 10.0.17.444** 
**Other relevant version: Valhesia 3 modpack**

**Comment by pupnewfster** [comment]
Yes this is intended
