### ISSUE TITLE
Pressurized reaction chamber will not make HDPE under certain conditions

### ISSUE THREAD

**Issue by YaBoiFast** [mekanism/Mekanism#6814]
#### Issue description:
PRC will not produce HDPE pellets if 2 or more speed upgrades are installed and will not produce 
The same thing will also happen if you use Ethylene and water to duplicate substrate but will stop after 4 are installed instead of 2
The issue only appears when ethylene is used in the recipe and not for others (ex: Sulfur and Substrate from BioFuel)
#### Steps to reproduce:
1. Setup Pressurized Reaction Chamber with Ethylene and water
2. Install 2 or more speed upgrades
3. Put Substrate into PRC which will cause it to freeze
4. If you remove speed upgrades down to 1 it works

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.11
**Mekanism:** 10.0.18.445 (Latest)
**Other relevant version:** Minecraft 1.16.4

**Comment by YaBoiFast** [comment]
I first noticed this when playing ATM6 and replicated it in a creative world with just Mekanism and forge installed

**Comment by pupnewfster** [comment]
Install energy upgrades
