### ISSUE TITLE
metallergic infuser not working

### ISSUE THREAD

**Issue by ItsEvelynn** [mekanism/Mekanism#6816]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
yeah uhm... me metallurgic infuser no work, when i put coal/ redstone in the place where you put in carbon or redstone, it no work, still say empty and the thingie doesnt do the processing. me also got full power too.

#### Steps to reproduce:
1.  make the infuser
2. put in redstone and iron
3. say no carbon in left bar
4. no take my coal
5.  have full power
6.  no process into the dust i need

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.5.2854** 
**Mekanism: 1.12.2** 
**Other relevant version: minecraft version 1.12.2** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.] <-- idk what this link is but im not gonna touch it

**Comment by Robball14** [comment]
Send a pic of the metallurgic infuser internal GUI and specify the mekanism version you're in

**Comment by pupnewfster** [comment]
Closing as we no longer are developing 1.12, if you provide an image as robball suggests we may be able to give you pointers though if it is something you are doing wrong
