### ISSUE TITLE
Mekanism crashes on MacOS Big Sur

### ISSUE THREAD

**Issue by HenrikoMagnifico** [mekanism/Mekanism#6819]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The game crashes when trying to run Mekanism on Forge for 1.16.4 on MacOS Big Sur.

#### Steps to reproduce:
1. Install Mekanism for 1.16.4 Forge on MacOS Big Sur
2. The game crashes.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.13
**Mekanism:** 10.0.18.445
**Other relevant version:** Latest java 8 is installed. Optifine is not installed.

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[crash-2020-12-26_20.04.57-fml.txt](https://github.com/mekanism/Mekanism/files/5743534/crash-2020-12-26_20.04.57-fml.txt)

**Comment by Oct0bass** [comment]
Still using Catalina, so can't test, but this doesn't look to related to the operating system.  Not sure tho

**Comment by pupnewfster** [comment]
I don't have a mac so can't test this but I feel like one of the other mods you have installed is likely causing this as the renderer should not be able to be null ever in that line unless some mod is massively screwing with entity render layers. Does this happen consistently or just randomly sometimes happens on launching?
