### ISSUE TITLE
Digital Miner shuts off if im out of range

### ISSUE THREAD

**Issue by HeckMeck95** [mekanism/Mekanism#6820]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

I have a Windows 2019 Server and i play on Infinity Evolved 3.1.0
I Set up 2 Digi Miners at one Spot. The first one only mines *Draconium *Yellorium * Diamond and *Emerlad.
The second one mines every other ore. Both are connected to a Enderchest via "Ultimate Logical Transporter" (Push and Pull configured) and with a Tesseract wich is connected to a Draconium Energy Core T4 with 6B RF stored. And the chunks are loaded.

So if i start the miners, all works perfectly. The "big" one has abt. 9k ores to mine and the small one 2k. If i go home now, maybe 3-4 chunks away, and go back to the miners 10 min later, the miners say "to mine: 0" but if i stop, reset and start again, they have 8k (or 2k) to mine again

#### Steps to reproduce:
1. Setup miner
2. Go home or in another dimension and wait a bit
3. Go back do the digi miner

#### Version (make sure you are on the latest version before reporting):
**Forge:** 10.13.4 1614
**Mekanism:** 9.1.1 1031
**Other relevant version:** MC: 1.7.10

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

No log.

**Comment by pupnewfster** [comment]
The chunks have to be loaded, try installing an anchor upgrade or loading it with some other mod

**Comment by HeckMeck95** [comment]
As i said, the chunks are loaded. In the Infinity Evolved is a chunkloader implemented and it works finde like, the reactor and the hole ore quadruple system in my home is running perfectly fine, even when noone is online.

**Comment by pupnewfster** [comment]
Are just the miners loaded or also the chunks they are setup to mine?

**Comment by HeckMeck95** [comment]
I alway load 4 or even 6 chunks around the miner .. on other servers was that enough

**Comment by pupnewfster** [comment]
No idea then, 1.7.10 is not being developed anymore. Personally I didn't start helping develop Mekanism until 1.12.2 so not only is 1.7.10 ancient I don't really know what bugs it even had.
