### ISSUE TITLE
[1.15.2] mod references recipe type that doesn't exist

### ISSUE THREAD

**Issue by tlsctf2** [mekanism/Mekanism#6825]
#### Issue description:
According to diesieben07 on the Forge forums, the mod references a recipe type that doesn't exist. [Here's](https://forums.minecraftforge.net/topic/95696-1152-every-world-generated-chest-is-empty/) the link to the thread where I found out.

#### Steps to reproduce:
Unsure of specifics.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.15.2-31.2.47
**Mekanism:** 1.15.2-9.10.9.422
**Other relevant version:** Minecraft 1.15.2

**Comment by pupnewfster** [comment]
1. We are no longer developing for 1.15
2. `mekanism:processing/allthemodium/dust/from_ore` is not our recipe, this is a recipe added by a your modpack take it up with them
