### ISSUE TITLE
Elytra Unit for MekaSuit

### ISSUE THREAD

**Issue by Elrekay** [mekanism/Mekanism#6827]
It would be a smart addition to have an Elytra unit for the MekaSuit which would allow the player to use the elytra in conjunction with the jetpack to cover greater distances. Double tap space would deploy the elytra so whilst deployed the jetpack would like a firework and if its not deployed it would work like a regular jetpack. Either the jetpack should function like a constant firework. 

This could also be added to the jetpack instead and work as an upgraded version similar to the armoured jetpack.

For context it would then function like in this mod, Having an elytra with armour and not needing fireworks to fly.
https://www.curseforge.com/minecraft/mc-mods/colytra

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/103#issuecomment-680221367
