### ISSUE TITLE
mekasuit and immersive engineering

### ISSUE THREAD

**Issue by ShibaRoTatsuya** [mekanism/Mekanism#6828]
#### Issue description:
while wearing a MekaSuit immersive engineering shock damage from tesla coils and uninsulated wires bypasses the damage protection.

will there be updates to protect against different forms of damage? I saw another post about adding base armor to help with other forms of damage.
#### Steps to reproduce:
1. wear MekaSuit.
2. have tesla coil powered or unshielded wire powered.
3. walk in range.
4. damage bypasses any sort of protection.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.3
**Mekanism:** Mekanism-1.16.4-10.0.18.445
**Other relevant version:** pack is all the mods 6

**Comment by jonnyawsom3** [comment]
Would be especially nice if void damage could be negated for at least a while, lost everything because i dipped too low in the end with the jetpack and within 2 seconds i was dead

**Comment by delucain** [comment]
The Immersive Engineering Railgun also bypasses all Meka Suit armor.

**Comment by Waisse** [comment]
On that note, the Meka Suit doesn't allow to be discharged by the electron tube from the Revolver.

**Comment by pupnewfster** [comment]
We have decided we have no intentions of ignoring mods when they say damage is supposed to ignore armor. 10.1 will allow addons to create custom modules that can be installed, so if someone wants to go ahead and add a module that can block other damage types they can do so.
