### ISSUE TITLE
Metallurgic Infuser not accepting input

### ISSUE THREAD

**Issue by rickyritvik** [mekanism/Mekanism#6830]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism's Metallurgic Infuser is not accepting any type of input from a range of cables including Cyclic, Refined Storage export bus, Refined Storage Crafter, and Mekanism pipes.

#### Steps to reproduce:
1.Fill chest with infusing material or infusible material
2. Set up any type of piping.
3. Ensure all of the machine's sides are correctly configured.

I did confirm it was extracting by placing another chest, which the redstone did go into.

#### Version (make sure you are on the latest version before reporting):
**Forge: 35.1.13 ** 
**Mekanism: 1.16.4-10.0.18.445** 
**Other relevant version: All the Mods 6-1.3.7 ** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]
![image](https://user-images.githubusercontent.com/35642078/103390671-5d631580-4adb-11eb-8c80-4dea4e5388d4.png)
![image](https://user-images.githubusercontent.com/35642078/103390685-6f44b880-4adb-11eb-8921-13801ab92c38.png)
![image](https://user-images.githubusercontent.com/35642078/103391120-69e86d80-4add-11eb-99fd-a9564e399463.png)

**Comment by pupnewfster** [comment]
Redstone ore isn't valid as an infuse type or target unless your pack adds one for it. If that tag is for redstone in general, your side config is wrong you have it set to input you want it set to extra if you want it for the infuse type.
