### ISSUE TITLE
Mechanical dirt redstone signal share

### ISSUE THREAD

**Issue by Bellwar** [mekanism/Mekanism#6834]
**Describe the feature you'd like**
A clear and concise description of what you want.

Mechanical dirt will have the same redstone state as all the other. Same as fluid and energy get shared.

**Describe alternatives you've considered**

Having to wire signal to each one of them.

**Additional context**

Set up: All mechanical dirt set to work only with redstone signal. Applying the signal to one block will turn on all of them on.

**Comment by pupnewfster** [comment]
I don't understand what you are asking? Mechanical dirt is not a mekanism thing.

**Comment by Bellwar** [comment]
... Im so... ehm stupid. So sorry, really sorry.
