### ISSUE TITLE
Question about fluid tanks

### ISSUE THREAD

**Issue by Zjalost** [mekanism/Mekanism#6835]
Do  the fluid tanks have a setting to where when stacked, they fill as intended but emptying from the bottom only empties the bottom tank. the tanks above stay filled and do not empty to the bottom

**Comment by pupnewfster** [comment]
I do not understand the question, as this is the default behavior of our fluid tanks, if you want the upper tanks to send their contents back down to the lower tanks you need to sneak right click them with a configurator so that they auto eject out the bottom
