### ISSUE TITLE
[Feature request] Induction matrix redstone level emitters 

### ISSUE THREAD

**Issue by A-wolf** [mekanism/Mekanism#6836]
So what i would want is something similar to a the Fission Reactor Logic Adapter block but for the induction matrix. My idea of how it could work would be it is set to at a certain point (preferably a percentage of how full the structure is) output a redstone signal. Personally would i use this by hooking up at least two to turn on and of a fission reactor at about 90% full and then back on at around 50% full as to not cause power overflow and risk wasting an energy

**Comment by pupnewfster** [comment]
Slap a comparator down against an induction port, it outputs a level based on the percentage filled.

**Comment by A-wolf** [comment]
Oh thanks didn't know that's was a thing I'll do that in the future 👍
