### ISSUE TITLE
QIO Networks Crashing Game

### ISSUE THREAD

**Issue by ArticulatedDrunk** [mekanism/Mekanism#6837]
#### Issue description:
Game crashes/dces when opening qio drive container.

#### Steps to reproduce:
1. put a lot of items inside a qio network I think I had roughly 2000-3000 types and 600,000-1.2 million items
2. open gui for qio container block or break and pick up that block

#### Version 
**Forge:35.1.13** 
**Mekanism:1.16.4-10.0.18.445** 

#### Crash Log
I don't think I have a log or I don't know where it is but I have this.
![crash](https://user-images.githubusercontent.com/22388690/103468728-8375f900-4d19-11eb-9722-b435cb085927.png)

As a side note they also seem to just be very laggy generally. Not sure what can be done about that but I did want to bring that up somewhere.

**Comment by pupnewfster** [comment]
This has to do with NBT size, and I will look into how to fix it when I get the chance. I think part of it may end up requiring syncing stuff in multiple packets.

In regards to your claim that they are laggy in general,either provide profiling data that shows it is the QIO that is lagging, or there is nothing that can be done in regards to it, if it is even the source of the lag.

**Comment by ArticulatedDrunk** [comment]
How do I get that profiling data? and I'm pretty sure it's qio because it happens when I actually open and use the network. It's not generally laggy in chunks around it in case that was misunderstood.
Also when you do get around to figuring  out a fix I ask that if possible you make it backwards compatible with old qio drives as I have all of my stuff on the server I was on stuck in there?

**Comment by Ko3ntjuh** [comment]
Haven't had any issues besides slowness when you have over 16.5 million items in it, up to now. 
Having the same issue on our server as well. Can do everything, except for opening the QIO drive, instant crash with this message.
Running a Valhelsia 3 server with latest version 3.1.7a.
It contains the mekanism mods:
Mekanism-1.16.4-10.0.19.446
MekanismAdditions-1.16.4-10.0.19.446
MekanismTools-1.16.4-10.0.19.446
MekanismGenerators-1.16.4-10.0.19.446

Is there any outlook on a fix or workaround that can be used to resume playing ? 
Server reboot/Personal pc reboot didn't fix it.

**Comment by pupnewfster** [comment]
Not sure to be honest for the most part reworking this system will not happen until 10.1 given I will be and have been working on a bunch of QIO stuff for that, but I might be able to mitigate at least some issues for 10.0.20 by making it not send all the NBT to the client, which will cause some issues in creative but should at least make it not cause crashes.

**Comment by Ko3ntjuh** [comment]
Sounds good to me, will wait until the new version gets here.

Possibly interesting to finding the issue at hand/making it more resillient until the rework can be done:
I have 3 qio drives;
A: 2k items of which 50 item types
B: ~14 million items and 100 item types
C: ~4 million items and 8000 item types

I have the issue only when accessing the C one. The others work completely fine.

**Comment by pupnewfster** [comment]
Unfortunately after looking into it slightly further the "patch" I was thinking may work causes a bunch of other issues so it will unfortunately have to wait until the more proper/complete fix when I rework the system in 10.1. One thing I remembered though while looking into it, is as a temporary workaround it should be possible to move the world to single player, then interact with it and the like move some stuff (namely the more NBT heavy items) out of drives, and then transfer it back to the server.

**Comment by Pantheris2019** [comment]
Now experiencing the issue again this time the drive crashes on dashboard.  Discord is currently having an API outage preventing me from reaching you guys on discord.

**Comment by Pantheris2019** [comment]
This really needs to be fixed as it is a very HUGE problem in my modpack which very much punts players from the server.

**Comment by Pantheris2019** [comment]
I would suggest marking this one as a mission critical issue as this PREVENTS players from using the maximum capacity of the drives to store their stuff in as a working storage solution.  I mean AE does it and AE has NOWHERE NEAR the issues that these QIO drives do.  This means you will lose downloads to AE if you don't fix this issue, and Mekanism is a fun mod which allows me to commit Satisfactory in Minecraft with the help of Create.  I don't want to see this mod lose its storage drive functionality because, not gonna lie, it is SOOOO much more convenient than using AE for all of my storage needs.  I absolutely fekkin love the QIO drives.  They are just SOOOO useful.  As a workaround, do not stuff ALL your shit in one drive, have a seperate drive for your mob farms and a main one for all of your stuff like resources and such.  I've run into this problem due to the sheer amount of ITEMS that mob farms produce.
