### ISSUE TITLE
Free-Runners not stepping up 1 high blocks (Valhelsia 3)

### ISSUE THREAD

**Issue by Chreaus** [mekanism/Mekanism#6838]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.Make Free Runners
2.Charge/Equip them
3.Walk over 1 high block

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.28
**Mekanism:** , Mekanism-1.16.1-10.0.18.445
**Other relevant version:** 
https://user-images.githubusercontent.com/61051851/103470626-66e1bd00-4d29-11eb-8ca4-23bf3fd95617.mp4

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Report to the pack dev or try and track it down yourself, 99% sure that one of the other mods in the pack is breaking it by resetting the step height each tick if their auto step condition is not met.
