### ISSUE TITLE
Request: Thermoelectric Cooler (Resistive Heater opposit)

### ISSUE THREAD

**Issue by UnhappyCodings** [mekanism/Mekanism#6839]
**Describe the the feature you'd like**
its a block powered by FE and produces cold. like the resitive heater but with cooling instead of heating

**Describe alternatives you've considered**
some liquid or block for cooling

**Comment by Robball14** [comment]
ok
but what's the purpose of this?
i mean, where it can be used?
how much can it be useful to the average player?

**Comment by UnhappyCodings** [comment]
Its useful for so many other mods because no other mod adds such a Block and cooling is for example for the pneumatic craft mod very useful. For the average its useful because in nearly every modpack you need an cooling liquid/block

**Comment by pupnewfster** [comment]
I don't see much point of this in Mekanism, as there is not much point to a cooling block in mek just because other mods don't provide a way to cool themselves.
