### ISSUE TITLE
No Flow Logistical Sorter

### ISSUE THREAD

**Issue by SquidsGrowHouse** [mekanism/Mekanism#6844]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I have set up a logistical sorter on a Quantum Entagloporter but ablsolutly nothing with come out of the pipe. I have tried varies ways with multiple chest, with colors, without colors and can not get a single item to push through the sorter. 

#### Steps to reproduce:
1. Place Quantum Entagloporter with the same frequency as Miner that is mining.  
2. Place pipes with sorter at base of Entagloporter.
3. Set color of last pipe to one chest, Blue and the other Red. 
4. Make sure to set all pipe with correct flow configuration
5. no flow

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.20
**Mekanism:** 10.0.18.445
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Do you have auto enabled on the sorter with a chest it can fallback on or have you tried extracting directly from the entangloporter? 98% of the time when people hook a sorter up directly to an entangloporter and it stops working it is because the entangloporter is jammed with an item the sorter is not setup to pull.

**Comment by SquidsGrowHouse** [comment]
I have attempted with it on the entangloporter and with it on it, with no success. I have tried extracting into chest then sorter and still no success.

**Comment by SquidsGrowHouse** [comment]
> 
> 
> Do you have auto enabled on the sorter with a chest it can fallback on or have you tried extracting directly from the entangloporter? 98% of the time when people hook a sorter up directly to an entangloporter and it stops working it is because the entangloporter is jammed with an item the sorter is not setup to pull.

I have attempted with it on the entangloporter and with it on it, with no success. I have tried extracting into chest then sorter and still no success.

**Comment by pupnewfster** [comment]
Next step then would be to provide pictures of the filters, and the pipe setup so that we can see if something is configured incorrectly, also it would be useful to know the side configs of the machines.

**Comment by SquidsGrowHouse** [comment]
> 
> 
> Next step then would be to provide pictures of the filters, and the pipe setup so that we can see if something is configured incorrectly, also it would be useful to know the side configs of the machines.

![entangloporter config](https://user-images.githubusercontent.com/77035936/103726005-75380f00-4f9d-11eb-89e0-d1978381936e.png)
![miner entangloporter](https://user-images.githubusercontent.com/77035936/103726013-779a6900-4f9d-11eb-83f2-1fd456cc4e65.png)
![miner](https://user-images.githubusercontent.com/77035936/103726016-79fcc300-4f9d-11eb-9e95-207255554c95.png)
![pipes](https://user-images.githubusercontent.com/77035936/103726021-7bc68680-4f9d-11eb-8990-9c4d0bb989c9.png)
![sorter config](https://user-images.githubusercontent.com/77035936/103726025-7e28e080-4f9d-11eb-9b46-8b9bd6cda4ff.png)

**Comment by pupnewfster** [comment]
You can't put logistical sorters in the middle of transporter networks, they need to be against an inventory for what it is pulling from.

**Comment by SquidsGrowHouse** [comment]
> 
> 
> You can't put logistical sorters in the middle of transporter networks, they need to be against an inventory for what it is pulling from.
> 
> Edit: Additionally you have the output side of the sorter facing where the items are supposed to come from if I understand your setup correctly.

Yeah, like I said, I tried with a chest between the sorters and still no success. 
The config youre looking at is the one for inside my factory. the one at the miner is all red for input. Every other input is set to none. Everything is set to auto eject.

**Comment by SquidsGrowHouse** [comment]
APPARENTLY....I never tried with the chest behind the sorter at the factory...fixed and working. Thank you again for your help haha.

**Comment by pupnewfster** [comment]
Glad you got it working.
