### ISSUE TITLE
Entangloporter wont transport nuclear waste

### ISSUE THREAD

**Issue by EBRPyle** [mekanism/Mekanism#6845]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.Hook-up entagloporter to pressure tub carring nuclear waste
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  35.1.13
**Mekanism:** 10.0.18.445
**Other relevant version:** All the mods 6

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
This is intended

**Comment by EBRPyle** [comment]
The big issue I have is building my reactor in the ATM mining dimension and am unable to use neutron activator, I was looking for a solution to move it.

**Comment by pupnewfster** [comment]
It is intended that you can't move it from one dimension to another so that you don't just transfer the waste to another dimension and not have to deal with it. In regards to the ATM mining dimension, that is being tracked here: #6801
