### ISSUE TITLE
Modder Support for adding custom Modules / Units 1.16.4

### ISSUE THREAD

**Issue by Robocraft999** [mekanism/Mekanism#6846]
Is there a way to add custum modules in my own mod ? I tryed it by creating my own Modules class, but I cant init my Modules, because the method only accepts Modules.ModuleData, which i cant use because its constructor is private.
I think a solution is to add a public 
`addModule(String name, LangEntry name? (or String) , LangEntry (or String) description, Supplier<ModuleData<>> module, int stackcount)`.

Please add something in this direction. Thanks.

Robocraft999

**Comment by pupnewfster** [comment]
For 10.1 I will try to move more stuff to the API module in relation to making some of the newer V10 systems more expandable, though it may be a bit until this is done though, as recently I have been spending most of my time modding trying to finish porting another mod I have been neglecting to 1.16
