### ISSUE TITLE
Digital Miner adds Wood stems if typing *ore in TAG-Filter

### ISSUE THREAD

**Issue by Robocraft999** [mekanism/Mekanism#6847]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The Digital Miner adds Wood stems if I typ *ore in the TAG-Filter

#### Version (make sure you are on the latest version before reporting):
**Forge:*35.1.32* 
**Mekanism:*445*

**Comment by Robball14** [comment]
i suppose you're talking about 1.16 given the forge version (please next time write the Mekanism version fully and not only the last numbers).
anyway "*ore" doesn't work anymore for that version, you have to type "forge:ores"

**Comment by Robocraft999** [comment]
thank you

**Comment by pupnewfster** [comment]
yes because it matches this tag https://github.com/mekanism/Mekanism/blob/1.16.x/src/datagen/generated/mekanism/data/mekanism/tags/blocks/atomic_disassembler_ore.json
