### ISSUE TITLE
Single tick 60+ seconds crash 1.16.4

### ISSUE THREAD

**Issue by Flexz9** [mekanism/Mekanism#6849]
#### Issue description:
Single tick taking 60+seconds. No idea if this is mekanism related or not.
No one was online at the time.

Server is running on AMD Ryzen 9 5900x having 8 threads dedicated to single modded MC server

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.16.4-35.1.13
**Mekanism:** Mekanism-1.16.4-10.0.18.445

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[pastebin](https://pastebin.com/Jm3JTPbf)

**Comment by pupnewfster** [comment]
You can try profiling your server using a tool like spark, but I am closing this for now as when watchdog kills a server it just logs whatever it happens to be doing at the time it dies which rarely is actually the thing that made the tick take so long.
