### ISSUE TITLE
Diversion Transporters are not diverging items

### ISSUE THREAD

**Issue by whuppo** [mekanism/Mekanism#6850]
#### Issue description:
Items being transported via Logistic Transporters ignore Diversion Transporters and take the shortest path no matter which redstone mode you set the Diversion Transporter.

#### Steps to reproduce:
1. Copy this structure, with the Logistical Sorter set with Single mode and Auto-eject on, and the Diversion Transporter set to Active with signal.
![java_BebGbkDpyo](https://user-images.githubusercontent.com/8893526/103813280-b28bb380-5014-11eb-893f-50d2a8c02f0f.png)

2. Place items in the Logistical Sorter inventory block, and start toggling the lever. Observe the items not being diverged no matter what redstone signal there is.
![2021-01-06_11 28 22](https://user-images.githubusercontent.com/8893526/103813482-01d1e400-5015-11eb-8b8b-133df5d68ac9.png)
![2021-01-06_11 28 33](https://user-images.githubusercontent.com/8893526/103813485-026a7a80-5015-11eb-846a-361c03aee25e.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.32
**Mekanism:** 10.0.18.445

**Comment by pupnewfster** [comment]
Diversion transporters don't make it take a longer path, they allow you to disconnect the network on command on specific sides with redstone (you need to set it on the face you want disabled, there are 6 faces). What you may be thinking of is the restrictive transporter which is memory serves add `1,000` to a cost of a path.
