### ISSUE TITLE
crashes when i use the digital miner

### ISSUE THREAD

**Issue by Pavstar** [mekanism/Mekanism#6851]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Once i configure the digital miner and start it, the server crashes

#### Steps to reproduce:
1. place and power digital miner
2. filter any ore with any range
3. start it

#### Version (make sure you are on the latest version before reporting):
**Forge:**  latest 1.16
**Mekanism:** v10.0.18.455 
**Other relevant version:** 

Crash report:
https://pastebin.com/Jh9T6vWd

**Comment by pupnewfster** [comment]
Can you reproduce this on forge and not on Mohist?

**Comment by thiakil** [comment]
It's a result of me overriding `getGameProfile` - afaik vanilla doesn't call that during the constructor, but this server is for whatever reason.
i.e. it's being called before the MekFakePlayer is fully initialised.
