### ISSUE TITLE
What exactly is going to happen to copper when 1.17 is released with vanilla copper?

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#6854]
I am just curious what exactly would happen to mechanism copper once 1.17 is released with vanilla copper. Will mekanism copper just be deleted and the recipes work with vanilla copper?

**Comment by Robball14** [comment]
most likely

**Comment by thiakil** [comment]
Mekanism recipes should already work with any other copper (provided it's tagged correctly), so yes vanilla would work whether we delete Mek's or not
