### ISSUE TITLE
Configuration Card does not work with QIO Exporter/Importer

### ISSUE THREAD

**Issue by Synergyst** [mekanism/Mekanism#6857]
#### Issue description:
I am unable to use my configuration card on my QIO exporter on my server.

#### Steps to reproduce:
1. Sneak right click the QIO exporter
2. See nothing happens (as opposed to the card actually working with the digital miner and other items)

#### Version:
**Forge: 35.1.11** 
**Mekanism: Mekanism-1.16.4-10.0.18.445** 
**Other relevant version: Mekanism Additions, Generators, and Tools are installed..**

**Comment by pupnewfster** [comment]
This turned out a lot easier to do than I thought it might be because it seems this was actually already implemented and aidan accidentally just forgot to expose the capability so the configuration card didn't know it had support.
