### ISSUE TITLE
Mekanism Cardboard Boxes are not removed with shift right click.

### ISSUE THREAD

**Issue by dmitry-diolan** [mekanism/Mekanism#6858]
#### Issue description:
Mekanism Cardboard Boxes are not removed with shift right click.

I created the cardboard box and wrapped the drawer with it. I can break the box and get it into the inventory. It correctly writes that it contains the drawer. I can place the box back in the world, but I can't remove it with shift right click. I tried to use configurator without any success.

It seems there is now way to remove the cardboard box and release the entity that is wrapped. 

#### Steps to reproduce:
1. I created the cardboard box and wrapped the drawer with it.
2. I can break the box and get it into the inventory.  It correctly writes that it contains the drawer. 
3. I can place the box back in the world, but I can't remove it with shift right click.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  35.1.13
**Mekanism:**  1.16.4-10.0.18.445
**Other relevant version:**  I play Enigmatica 6, version 0.3.2

**Comment by thiakil** [comment]
Make sure your off hand is empty, sometimes that can interfere

**Comment by dmitry-diolan** [comment]
Yes, you are right. Sorry for bothering your.

**Comment by enl** [comment]
I spent good ten minutes before I tried to empty my hand. Would be nice to add this information to wiki or investigate if it is possible to work it around :)
