### ISSUE TITLE
Carry On Crash

### ISSUE THREAD

**Issue by Seniorendi** [mekanism/Mekanism#6859]
#### Issue description:
When i pickup a MekanismTileEntity and place it over a Hopper, the Server crashed.

#### Steps to reproduce:
1. Carry a TileEntity(like crusher or enrichment chamber)
2. Place it over a hopper or a logistical transporter
3. The Server will crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.32
**Mekanism:** 10.0.18
**Other relevant version:** Carry On 1.15.1.7

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Crash log: https://paste.gg/p/anonymous/49017baf79aa40e38bc153b7e46a25b6

**Comment by pupnewfster** [comment]
See https://github.com/Tschipp/CarryOn/issues/263 they move the block but not the tile so then the tile when it tries to query the block fails because it isn't there.

**Comment by Seniorendi** [comment]
Kay
