### ISSUE TITLE
[1.12.2] Energized Smelter not smelting Dusts (of any kind)

### ISSUE THREAD

**Issue by vizthex123** [mekanism/Mekanism#6862]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
_Currently only seen in my [Capitalia](https://www.curseforge.com/minecraft/modpacks/capitalia) modpack, but you can't smelt any of the dusts from Mekanism or any other mod._

1. Place dust into smelter's input slot
2. Provide power
3. See how it won't smelt

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2854
**Mekanism:** 9.8.3.390
**Other relevant version:** Mekanism Generators & Tools 9.8.3.390

**Comment by thiakil** [comment]
In general, 1.12 isn't supported by us any longer.

You'll need to remove mods to work out what's interfering (I recommend removing half, checking, then halving again if it still occurs).

And if you're using Crafttweaker, check without your scripts.
