### ISSUE TITLE
Digital miner range

### ISSUE THREAD

**Issue by aPolymorph** [mekanism/Mekanism#6867]
So, in the 1.12.2 version of mekanism i use to change digital miner's range on the mod config, but now in 1.16.4 we cant access mod config anymore , is that any way to do it anyway?

**Comment by pupnewfster** [comment]
The config still exists it is in `config/Mekanism/general.toml` if memory serves

**Comment by aPolymorph** [comment]
> The config still exists it is in `config/Mekanism/general.toml` if memory serves

Where is that config/Mekanism/general.toml? i cant click the button that says config in minecraft, its just not clicable, so im on the mod folder, can you explain me how to change the digital miner radius?

**Comment by pupnewfster** [comment]
There is no in game config currently, as forge doesn't have a prebuilt GUI. And I gave you the file path from your minecraft install. There is a config folder in it, inside it there is a Mekanism folder, and inside it I believe the general file is the one that has the range.
