### ISSUE TITLE
Thermal Evaporation Plant won't heat up past ambient temperature on JAMD dimension

### ISSUE THREAD

**Issue by Mig979** [mekanism/Mekanism#6870]
Issue description: I'm playing Direwolf20 1.16.4 version 1.3.1 and I've set up a Thermal Evaporation Plant with 4 Advanced Solar Generators on the dimension of the mod [JAMD ](https://www.curseforge.com/minecraft/mc-mods/jamd) and the temperature won't go past 308.34K.

Version: 1.16.4
Forge: 35.1.36
Mekanism: 10.0.18.445
JAMD: 1.1.4

**Comment by pupnewfster** [comment]
Their mining biome seems to declare it is a baseline temperature, https://github.com/UnRealDinnerbone/JAMD/blob/main/src/main/resources/data/jamd/worldgen/biome/mining.json#L34 so this is intended, if you want to use it there you will need to use heaters or something to raise the temperature.
