### ISSUE TITLE
Mekanism incompatible with Optifine + Forge 35.0.1.

### ISSUE THREAD

**Issue by RealDashU** [mekanism/Mekanism#6872]
**Describe the the feature you'd like**
Mekanism as stated in the title does not load with Forge 35.0.1 + Optifine + Minecraft 1.16.4 all together and Forge refuses to load Mekanism as Mek is not compatible with that older version of 35.0.1 -- However, in order to run Optifine all together it is required to use Forge 35.0.1 and is therefore an inconvenience for people that have grown attached to shader packs and the like that all need Optifine. Note: I'm wanting to stay on Minecraft 1.16.4.

**Describe alternatives you've considered**
I've tried searching for previous versions of Mekanism and have yet to find anything without having to roll back the Minecraft version.

**Additional context**
N/A

**Comment by pupnewfster** [comment]
Take it up with optifine
