### ISSUE TITLE
Purification Chamber does not accept Ancient Debris

### ISSUE THREAD

**Issue by mikehoyle** [mekanism/Mekanism#6873]
(I could find no dupes)

#### Issue description:
Purification Chamber (and subsequent factories) do not accept the Ancient Debris ore, so it cannot be tripled in the same way as all other ores. This may be WAI, but I would expect it to work the same as other smelted ores

#### Steps to reproduce:
Attempt to insert Ancient Debris into Purification Factory.

#### Version (make sure you are on the latest version before reporting):
Enigmatica 6 on 1.16.4
Mekanism: Mekanism-1.16.4-10.0.18.445

**Comment by pupnewfster** [comment]
Ancient Debris has a different trippling method as it is different than other smelted ores.
