### ISSUE TITLE
quantum entangloporter and logistical sorter dispensing item issue.

### ISSUE THREAD

**Issue by desmondyipyc** [mekanism/Mekanism#6875]
Issue : connection : digital miner > logistical sorter > quantum entangloporter item dispensing out at low speed and seem to skip multiple items. tried ultimate pipe and tried to use separate quantum entangloporter solely for accepting item from miner 

but when the connection is : digital miner > logistical sorter > chest, item dispenses out normally (with just basic pipe)

Forge: 35.1.36
Mekanism: Mekanism-1.16.4-10.0.18.445

**Comment by pupnewfster** [comment]
The entangloporter has a buffer slot of a single item, I recommend pumping directly from the miner into the entangloporter, and then on the other end into a chest and using a sorter from that chest.

**Comment by desmondyipyc** [comment]
okay this fixed the issue, is this a temporary workaround or it is suppose to work this way?

**Comment by desmondyipyc** [comment]
smelting factory have the same buffer slot of single item for it's input and output? same issue dispensing from transporter and logistical sorter. currently using immersive engineering conveyor belt as a workaround.

**Comment by pupnewfster** [comment]
The entangloporter is meant to have the single item type buffer slot, which means that your source can't start sending items of another type to it until it has room. The smelting factory will only accept items into slots that are valid, if you have an output in it that can't be produced by what you are inserting, it won't be able to insert it.
