### ISSUE TITLE
quantum entangloporter and logistial sorter item dispensing issue.

### ISSUE THREAD

**Issue by desmondyipyc** [mekanism/Mekanism#6876]
Issue : connection : digital miner > logistical sorter > quantum entangloporter item dispensing out at low speed and seem to skip multiple items. tried ultimate pipe and tried to use separate quantum entangloporter solely for accepting item from miner 

but when the connection is : digital miner > logistical sorter > chest, item dispenses out normally (with just basic pipe)

Forge: 35.1.36
Mekanism: Mekanism-1.16.4-10.0.18.445

**Comment by pupnewfster** [comment]
Closing this as it seems to have double posted #6875 is the one made first
