### ISSUE TITLE
Atomic Disassembler and RLCraft

### ISSUE THREAD

**Issue by Optimalhoiboy123** [mekanism/Mekanism#6877]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I Made an atomic dissasembler in my survival server but when i tried to break blocks on fast mode the blocks broke but didn't drop anything
i did try normal and slow but they didn't drop anything either

![image](https://user-images.githubusercontent.com/77358664/104365439-462f1980-5518-11eb-949a-0fc926f7fb2c.png)
it is an edited version of rlcraft so here are the mods i didn't made any changes in the config

#### Steps to reproduce:
1. install the mods
2. get an Dissasembler
3. try to break a block in survival

#### Version (make sure you are on the latest version before reporting):
**Forge:14.23.5.2554** 
**Mekanism:1.12.2-9.8.3.390** 
**Other relevant version: Minecraft 1.12.2** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Closing this issue as we no longer are developing for 1.12 so any bugs that may exist on our end are there to stay, but can try at least some to help theorize what the issue may be. Best guess is the blocks you broke don't have drops or handle drops in an odd way when you broke them and isn't recognizing the atomic disassembler as a valid tool. What blocks specifically did you try breaking?

**Comment by NuanKi** [comment]
Even an iron ore drops nothing
