### ISSUE TITLE
AE2 Certus Quartz in Enrichment Chamber: recipe conflict.

### ISSUE THREAD

**Issue by Cerbrus** [mekanism/Mekanism#6878]
#### Issue description:
There's a conflict in the Enrichment Chamber recipe registration for AE2's "Certus Quartz" ores (Both "charged" and normal)

_Both_ ores have _2_ entries in JEI:

- 1 ore to 2 dust.
- 1 ore to 4 crystals.

![image](https://user-images.githubusercontent.com/2911988/104515632-62ec4f80-55f3-11eb-8cf6-dd4224e2159e.png)

When processing these ores, the "dust" recipe is used.

#### Steps to reproduce:
1. Look up the "usage" of (Charged) Certus Quartz Ore in JEI.
2. Dump some ore into the enrichment chamber. You'll get 2 dust.

I'd expect both ores to have only one recipe for the machine. (Preferably ore -> 4 crystals, of course ;-) )

#### Version:
**Forge:** forge-1.16.4-geckolib-3.0.0 (Is that the version?)
**Mekanism:** Mekanism-1.16.4-10.0.18.445
**Other relevant version:** 
- "FTB Presents DireWolf20 1.16" pack, version 1.3.1
- appliedenergistics2-8.2.0-beta.2

**Comment by pupnewfster** [comment]
Report it to your modpack, as we have a [recipe](https://github.com/mekanism/Mekanism/blob/1.16.x/src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/certus_ore_to_crystal.json) for ore -> crystal, and a [recipe](https://github.com/mekanism/Mekanism/blob/1.16.x/src/datagen/generated/mekanism/data/mekanism/recipes/compat/appliedenergistics2/charged_certus_ore_to_crystal.json) for charged ore -> charged crystal. We don't add any recipes for ore to dust, it is likely either something the FTB added or one of the other mods they are including in the pack added, as I doubt it is something the AE2 devs added themselves, as they worked with us via PRs in adding back our compat recipes I linked into Mekanism.

**Comment by Cerbrus** [comment]
Well that was quick!

Thanks, will do 👍
