### ISSUE TITLE
Evaporation Tower Wont Form

### ISSUE THREAD

**Issue by Solverbolt** [mekanism/Mekanism#6880]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Have tried building it in multiple locations, heights from 4 high to 16 high. Tried in Forest, Snow, Desert, Plains and Mountains Biomes.  Will Not Form. Every build has 2 to 4 valves, controller on top, as its meant to built,  4x4 Base, then a 4x4 ring going up, with slots left open for placement of valve, top has the 7 blocks, 1 controller minus corners for Resistive Heater or Advanced Solar Panel placement.  

#### Steps to reproduce:
1. Build Tower
2. Place Valves and Controller
3. Nothing Forms, always listed as Incomplete

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 1.12.2-9.8.3.390
**Other relevant version:** 
On latest MC Eternal 3.4 
#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]
![image](https://user-images.githubusercontent.com/38087746/104538841-81415380-55d1-11eb-93ff-6540edab4a86.png)

**Comment by thiakil** [comment]
Show pictures of your tower please

**Comment by Solverbolt** [comment]
![2021-01-13_19 35 44](https://user-images.githubusercontent.com/38087746/104541507-9967a180-55d6-11eb-97fa-3e69670e5f6a.png)
![2021-01-13_19 35 51](https://user-images.githubusercontent.com/38087746/104541514-9b316500-55d6-11eb-988e-fea599603a84.png)

This is just a small one, been trying in every biome i can find

**Comment by Solverbolt** [comment]
Does not accept any kind of power

**Comment by pupnewfster** [comment]
If memory serves pre V10, which includes 1.12 you either need advanced solar panels in the top four corners OR evaporation blocks, it can't just be air.

**Comment by Solverbolt** [comment]
i tried to use the previous items that worked as well, the heaters that convert rf/mj to heat
but it wouldnt form with those either

**Comment by thiakil** [comment]
See pupnewfster's comment, your construction is incomplete

**Comment by SteelBlue8** [comment]
The four empty corners at the top are your issue- either put an advanced solar panel in each one or thermal evaporation blocks. They cannot be empty.

**Comment by Solverbolt** [comment]
so what you are saying is that Resistive heaters are no longer functional, and the most worthless item now in Mekanism. Got it.  I will remember this for later, when someone recommends adding Mekanism to a pack, and i will vote against it.

**Comment by SteelBlue8** [comment]
Sir resistive heaters still work for solar evaporation towers. You just connect them to a valve, instead of including them as a component of the multiblock.

**Comment by pupnewfster** [comment]
No one said that, we said you need to finish the multiblock... You either need to use advanced solar panel or thermal evaporation blocks. Resistive heaters will work just fine... ONCE the multiblock is formed. I am sorry that you seem incapable of reading.
