### ISSUE TITLE
Pressurized Reaction Chamber NEEDS a Dump Option For Input Tanks.

### ISSUE THREAD

**Issue by DizzyDJW** [mekanism/Mekanism#6881]
**Describe the the feature you'd like**
The Pressurized Reaction Chamber NEEDS a Dump Option For Input Tanks. I'm stuck with one that has oxygen in the input and it is virtually useless now, as there is no way to get rid of the oxygen, aside from forcing the machine to use it in a reaction.

**Describe alternatives you've considered**
A simple Dump option for all tanks or even a way to "craft" it into a "fresh" one.

**Comment by SteelBlue8** [comment]
You can remove gases from it! Use a gauge dropper, and click on the slot containing the unwanted stuff. It's a little tedious, but it works!

**Comment by pupnewfster** [comment]
^ You can click to put the stuff in a tank in the gauge dropper or shift click to dump it into the atmosphere.
