### ISSUE TITLE
Server crash when using flamethrower

### ISSUE THREAD

**Issue by SampsonnZ** [mekanism/Mekanism#6886]
#### Issue description:

Hello, I met an issue. I'm using the flamethrower to ignite the TNT, but soon the server crash, and all the players disconnected.

#### Steps to reproduce:
1.Put some TNT.
2.Use flamethrower to ignite them.
3.Crash

#### Version 

**Forge: 35.1.36
**Mekanism: 10.0.18.445
[crash-2021-01-15_23.06.59-server.txt](https://github.com/mekanism/Mekanism/files/5821359/crash-2021-01-15_23.06.59-server.txt

**Comment by pupnewfster** [comment]
Same crash as #6861
