### ISSUE TITLE
Infusing factory unable to import items through refined storage crafter

### ISSUE THREAD

**Issue by albinobeach** [mekanism/Mekanism#6887]
Issue description:
I've been trying to automate the elite tier crafting recipes through Refined Storage, but I've run into an issue of being unable to import the specific items into the Metallurgic Infuser/Infusing Factory. The core item (such as obsidian dust) is imported through the Refined Storage Crafter, however the infusing material (like enriched diamond) doesn't import into the block.
Steps to reproduce:
-Place down resource specific infuser (basic or factory, doesn't make a difference)
-Connect crafter to infuser (all sides reproduce the same issue)
-place correct recipe on pattern into crafter
-queue up craft
-Crafting Monitor will read "Machine doesn't accept item." 

Version (make sure you are on the latest version before reporting): 1.16.4-10.0.18.445

Forge: 35.1.13
Mekanism: Mekanism-1.16.4-10.0.18.445
Other relevant version: Direwolf20 1.16 Modpack (version 1.3.1) which uses Refined Storage-1.16.4-1.9.11

I've tried importing items into a chest connected to the infuser, but I still run into the same issue. I've tried placing the Crafter on every side of the infuser. The only way I can see to get around this is to manually supply each infuser with the required material (redstone/coal/diamond), but then what's the point of trying to automate it? I'm sure there has to be something I'm doing wrong but I'm at a loss on figuring out how to fix this. Let me know if this should be reported on Refined Storage's GitHub instead of here.

**Comment by pupnewfster** [comment]
The infuser needs to have the **item**'s tab set to `extra` on the side you want to be inserting it from.

**Comment by albinobeach** [comment]
Thanks for the quick help! I've set the item tab to extra on the back side where the crafter is importing the necessary items, however the crafting monitor is still displaying the same message. I exchanged the factory with the basic infuser to see if that made a difference and to make it a little more simple for troubleshooting. Attached will be a handful of pictures that might help to pinpoint what is happening.

![SetupPic](https://user-images.githubusercontent.com/73551890/104782812-b10b6b00-5739-11eb-8d6f-2e61dfc61bc3.png)
   -This is how the Mekanism machines are set up, with different infusers for each type.
![Item Config](https://user-images.githubusercontent.com/73551890/104782824-b668b580-5739-11eb-9df5-6197aeb6157d.png)
   -This is the item tab config for the redstone infuser
![EncodedRecipe](https://user-images.githubusercontent.com/73551890/104782831-b8327900-5739-11eb-843b-70ba7fc9552f.png)
    -I adjusted the recipe to just include basic redstone in lieu of refined redstone.
![Queuing Craft](https://user-images.githubusercontent.com/73551890/104782841-bbc60000-5739-11eb-8181-2182060b4ade.png)
   -Queuing up an Infused Alloy
![Crafting Error](https://user-images.githubusercontent.com/73551890/104782847-be285a00-5739-11eb-8dcd-573eeaf20f70.png)
   -Crafting Monitor displays the error message.

**Comment by pupnewfster** [comment]
My best guess is it is trying to insert both the iron and the redstone on the same side except they need to be inserted on different sides, the redstone (more efficient if you enrich it into enriched redstone) on a side set to extra, and the iron on a side set to input.

**Comment by albinobeach** [comment]
I'm guessing that's the case, I'll just need to figure out how to do that! Thanks for the help, I really appreciate it.

**Comment by Siddhant1995** [comment]
The easiest way to set this up is to have a crafter import the material to be infused, and have an exporter with a regulator upgrade to input the enriched infuse material. For example, if you want to make infused alloys:

The pattern for the recipe should be: 1 Iron Ingot -> 1 Infused Alloy

Put this pattern into the crafter connected to the input of the Infuser. On another side of the infuser, attach an exporter. Set that side of the infuser to "Extra". Put a regulator upgrade in the exporter, along with an enriched redstone. Set the value of the redstone to 1, so that there will always be 1 enriched redstone in the exporter. 

The downside to this is that the infuser can only run 1 type of operation, so you will need multiple infusers to run different operations.

**Comment by albinobeach** [comment]
Siddhant, you're a life saver! Or at the very least, a great person for saving me the time of messing around with refined pipes' extractors. Thanks a bunch!

**Comment by Siddhant1995** [comment]
Always glad to help! I've been in the same position you have, and it took far too long for me to figure it out than I'd like to admit lol.

**Comment by Tuumke** [comment]
Sorry to rake up such an older post, but i can't get this to work. 
- I've tried with Autocrafter -> Elite Infusing Factory. It's loaded up with Enriched Redstone already, still put a exporter on top as "extra".

Autocrafter on the right side with the recipe
<img width="1022" height="775" alt="Image" src="https://github.com/user-attachments/assets/f9d36412-3734-423e-9446-ef542138a8fb" />

<img width="572" height="344" alt="Image" src="https://github.com/user-attachments/assets/18f36d7e-000a-41d1-b226-1f462f708e48" />

 Elite Infusing Factory on the left side, with right side set as input (the autocrafter).

<img width="628" height="438" alt="Image" src="https://github.com/user-attachments/assets/c73b8bd7-343b-45a7-88e9-83f036a6fdf9" />

<img width="610" height="486" alt="Image" src="https://github.com/user-attachments/assets/cf955043-823c-433f-958b-17e4008cc5d0" />

<img width="898" height="377" alt="Image" src="https://github.com/user-attachments/assets/d47357e9-1254-4558-a534-598f719d4447" />

Seems to me everything is setup just right. But still when i go into my wireless too and tell the network to craft 10 alloys, it just sits there doing nothing.

<img width="749" height="516" alt="Image" src="https://github.com/user-attachments/assets/5ca63023-8bbe-4bde-8523-e86d5b56ad88" />

**Comment by DeadShot2748** [comment]
@Tuumke Your autocrafter is facing the wrong way, face it so it points into the infusing factory. It's currently facing down into the ground.

**Comment by Tuumke** [comment]
That is, great information to have! Didn't know there would be sides like that on the autocraft. Works fine now!

<img width="768" height="717" alt="Image" src="https://github.com/user-attachments/assets/b4135dab-750b-485d-8981-a75a2d981646" />

**Comment by ikwru** [comment]
Sorry for taking a really older post. I'm having trouble automating Industrial Foregoing, idk why is not working. I wonder someone can help me.

Netherite Autocrafter -> Dissolution chamber:
<img width="693" height="396" alt="Image" src="https://github.com/user-attachments/assets/5727ebce-e8ac-4168-8653-bef9ceced324" />

Processing pattern:
<img width="448" height="293" alt="Image" src="https://github.com/user-attachments/assets/476de27c-f74e-45dc-9d5d-625bcf859228" />

Dissoluton chamber input:
<img width="470" height="438" alt="Image" src="https://github.com/user-attachments/assets/5c6d8e1a-bdb2-4864-acb8-049290581b4d" />

Autocrafting monitor:

<img width="831" height="513" alt="Image" src="https://github.com/user-attachments/assets/d646f45e-a135-4b88-b98b-b8e552ad45fb" />
