### ISSUE TITLE
flamethrower crash with OptiFine upon launch

### ISSUE THREAD

**Issue by FullMetalMaster** [mekanism/Mekanism#6888]
ava.lang.NullPointerException: Unexpected error
	at mekanism.common.base.PlayerState.setFlamethrowerState(PlayerState.java:319) ~[?:10.0.18] {re:classloading}

wasn't getting this crash before but I updated my pack and started getting this crash even though I haven't changed mechanism,
I don't know if it's a render issue or if there's any way to fix it but it just crashes with OptiFine as soon as I load into a server or world the item doesn't even have to be in my hand it just seems the two mods don't like each other

this can be reproduced with the latest versions of mechanism and OptiFine with the add-ons

Forge versions I've tested on are 1.16.4 - 35.1.37, 35.1.36, 35.1.35

**Comment by FullMetalMaster** [comment]
removed mechanism config loaded OptiFine first and it seemed to fix no idea wtf XD sorry go ahead and close this lol

**Comment by thiakil** [comment]
You can close issues yourself btw...

We don't support optifine anyway.

**Comment by TechniumUnlimited** [comment]
@FullMetalMaster so, resetting mekanism's config fixed it?

**Comment by TechniumUnlimited** [comment]
If anyone finds this - this issue can be resolved by deleting the configs on the server side or client side (if in Single Player) - I don't know what it reset to work, but it seems to have worked.. for now
