### ISSUE TITLE
Mekanism update for 1.12.2?

### ISSUE THREAD

**Issue by V4kodin** [mekanism/Mekanism#6890]
Should we wait for new updates of Mekanism at 1.12.2 Minecraft version?

**Comment by Robball14** [comment]
No
the mod won't receive any more update for 1.12.2

**Comment by Seniorendi** [comment]
And why do you want an update for 1.12.2?

**Comment by pupnewfster** [comment]
1.12 is not under active development anymore.

**Comment by V4kodin** [comment]
> And why do you want an update for 1.12.2?

Because much mods for example ic2 has not  ported at 1.16.4  Minecraft version
