### ISSUE TITLE
mushroom generation 

### ISSUE THREAD

**Issue by wasntavailable** [mekanism/Mekanism#6894]
hi i am new to playing crop block but ive got to the point where i need mushrooms for the end steel (zombie is required for enderman which is used in end seeds) but for some reason the mushroom wont generate ive got mycelium inbetween carrot and potatoes and nothings happening when i water them am i just dumb or is this a bug

**Comment by Oct0bass** [comment]
What? Mushroom generation? How is this mekanism related?

**Comment by pupnewfster** [comment]
No idea what you are talking about but either way this seems more like a question for the pack devs of the modpack you are playing.
