### ISSUE TITLE
Digital miner crashing server Valhelsia 2

### ISSUE THREAD

**Issue by Simen22** [mekanism/Mekanism#6895]
#### Issue description:
When using the digital miner, the game crashes, and i become unable to log onto that server without the game crashing instantly. Have to use a backup to get on again. Had the digital miner set to a radius of 10, and that dig completed, but have tried some bigger digs, and they always lead to a crash. It does not crash instantly. The digital miner digs for a while, but it almost always crashes the game. 

Have 8 speed upgrades and 8 power upgrades. Using the * ores * filter. Playing on the Valhelsia 2 modpack. 

#### Steps to reproduce:
1. Place down digital miner, and set radius to >10
2. Start the dig process, and wait
3. Game will crash, and will be unable to log in to server without instantly crashing.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-31.2.47
**Mekanism:** Mekanism-1.15.2-9.10.9.422.jar
**Other relevant version:** Minecraft 1.15.2

**Comment by pupnewfster** [comment]
The crash seems to have to do with your pressurized tubes not the digital miner. I believe we fixed this at some point in V10, unfortunately we are no longer developing for 1.15 so your best bet may to be use some sort of external world editor if any are updated past 1.12 and try to remove the tubes that way.
