### ISSUE TITLE
Dedicated Server Crash with Quantum Entangloporter

### ISSUE THREAD

**Issue by jwiley17** [mekanism/Mekanism#6898]
#### Issue description:
Creating a channel on quantum entangloporter causes crash on dedicated server, from what I can tell its either an incompatibility with minecraft version 1.16.5 or the forge versions that come along with it.

#### Steps to reproduce:
1. Create a new channel on quantum entangloporter using this version of forge on a dedicated server.

#### Version:
**Forge:** 36.0.1
**Mekanism:** 10.0.18.445

#### Crashlog:
https://mcpaste.io/5577be71c595e5d6

**Comment by jwiley17** [comment]
Closed issue due to bug not being reproducible after a few tries.

**Comment by pupnewfster** [comment]
Reopening this at least for now as I believe based on the crash this is something that theoretically can happen at times and should add a bit of null safety.
