### ISSUE TITLE
Where is the file that stores damage to a fission generator

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#6900]
I built a fission generator and accidently left a setting changed which damaged it, which file is the fission generator stats stored in?
![image](https://user-images.githubusercontent.com/41069911/105210949-b2fa7300-5b19-11eb-9709-50ee9034b07f.png)

**Comment by Robball14** [comment]
C:\Users...\Appdata\Roaming\.minecraft\config\mekanism\generators.toml
remember to open the file with notepad++ or similar

**Comment by term2112** [comment]
Im looking more to delete damage of a specific fission reactor in the saved worlds file, in the mean time, i can set meltdown chance to zero

**Comment by term2112** [comment]
Nevermind, I found that the damage goes down over time after cooling it

**Comment by thiakil** [comment]
You'd need to use NBTExplorer or similar to view the tile entity data
