### ISSUE TITLE
[1.16.4] Mekanism Teleporter in the Nether

### ISSUE THREAD

**Issue by NillerMedDild** [mekanism/Mekanism#6902]
Original report: https://github.com/NillerMedDild/Enigmatica6/issues/982

#### Issue description:
After restarting the server, the teleporter in the nether is unavailable, although the anchor improvement is installed, and you need to load chunks with a regular portal to the nether. There is no such problem with the teleporter in the End.

#### Steps to reproduce:
(0. Must be on a server I believe)
1. Build Mekanism Teleporters in overworld + nether
2. Put anchor upgrade in both
3. Restart the server
4. Attempt to teleport from the overworld to nether teleporter and fail to

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.4-35.1.29
**Mekanism:** 1.16.4-10.0.18.445
**Other relevant version:**

**Comment by Gliese-832-c** [comment]
Sorry if I'm not helping here, but could it be something with Vanilla Minecraft updates changing the nether code to mess with Mekanism portals?

**Comment by pupnewfster** [comment]
How reliably can you reproduce this, I just loaded up my dev environment test server and the teleporter that I had previously setup to the nether worked just fine without me having to separately go into the nether.

**Comment by NillerMedDild** [comment]
I've asked the original reporter here: https://github.com/NillerMedDild/Enigmatica6/issues/982#issuecomment-770437694

**Comment by NillerMedDild** [comment]
Thank you for the help :)
