### ISSUE TITLE
[1.12.2] Minecraft crash "Caused by: java.lang.NoClassDefFoundError: mekanism/generators/common/tile/TileEntityHeatGenerator"

### ISSUE THREAD

**Issue by PedroMeira2006** [mekanism/Mekanism#6904]
Issue description:

I got this error when tried launching my new modpack, need help to figure out the issue

Mods:
https://pastebin.com/NRzAzLzV

Version
Forge: 1.12.2-forge1.12.2-14.23.5.2768
Mekanism: Mekanism-1.12.2-9.8.3.390
MekanismGenerators-1.12.1-9.4.1.326
MekanismTools-1.12.2-9.8.3.390

Crash report: https://pastebin.com/mCErkJbD

**Comment by pupnewfster** [comment]
Why do you have Mekanism Generators 9.4.1 installed instead of 9.8.3 like the rest of the modules? My best guess is that is what is casing it to crash.
