### ISSUE TITLE
Game crash with multiplayer

### ISSUE THREAD

**Issue by HIN0815** [mekanism/Mekanism#6906]
#### Issue description:
When I get into the server, the game will crash with an error message.
And I need to go to singleplayer before go to multiplayer, after that can get into the server. 
But when I play with around 5 to 20 mins, the game still crash with the same error message.

#### Steps to reproduce:
1. get into the server
2. game crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.37
**Mekanism:** 10.0.18.445

#### crash log, link it here: 
https://pastebin.com/9hdCZTMk

**Comment by Shanghai-** [comment]
@HIN0815 this is a duplicate of #6892 / #6888 . People are reporting that the newest prerelease optifine version, OptiFine 1.16.5_HD_U_G7_pre4, fixes this bug. I suggest that you try upgrading to that version.

**Comment by HIN0815** [comment]
Thanks for the reply. I will try on it.
If there is any update, I will report to you
