### ISSUE TITLE
Electric Pump and crude oil from pneumaticCraft

### ISSUE THREAD

**Issue by Sunekaer** [mekanism/Mekanism#6907]
#### Issue description:
Placing an Electric Pump (mekanism) directly over a pool of pneumaticcraft:crude_oil source blocks in the world does not register as a valid fluid to the Electric Pump. Pump reports "no fluid". Works as expected with other liquids.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.36
**Mekanism:** Mekanism-1.16.4-10.0.18.445.jar
**Other relevant version:** pneumaticcraft-repressurized-1.16.4-2.9.2-116.jar

Im not sure if this issue is on you or pneumaticCraft

**Comment by pupnewfster** [comment]
I am not able to reproduce this. I tried loading PNC (from their maven 1.16.5-2.9.6-130) in my dev environment and it seems to be working just fine 
![image](https://user-images.githubusercontent.com/1203288/106389902-da6ffc00-63b3-11eb-894d-1338e3294860.png)

**Comment by Sunekaer** [comment]
Seems to working for me now too, maybe the pneumaticCraft dev changed something in their update
