### ISSUE TITLE
Miner using too little power?

### ISSUE THREAD

**Issue by XxZajoZzO** [mekanism/Mekanism#6908]
#### Issue description:
I setup my digital miner yesterday (Full spped and energy upgrades) and it was using 8k FE/t if I remember correctly, but today it's using only 400 FE/t. I didn't change anything since yesterday.

#### Steps to reproduce:
1. Setup a miner
2. Reload world/minecraft?
3. Miner is using less power for no reason

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.35
**Mekanism:** Mekanism-1.16.4-10.0.18.445
**Other relevant version:** 
Minecraft: 1.16.4, WIndows 10 64-bit, Java 1.8.0_271

https://i.imgur.com/PssJrIM.png

**Comment by pupnewfster** [comment]
Given the fact that your buffer is talking about micro FE, my best guess is going to be that maybe somehow the conversion rates between Joules and FE got changed in the config? Might be worth checking the file `config/Mekanism/general.toml` and under the sub category `general.energy_conversion`, the values for `JoulePerForgeEnergy` (default is "2.5000") and `ForgeEnergyPerJoule` (default is "0.4000").

**Comment by XxZajoZzO** [comment]
Checked the configs, everything is fine.
It says miliForgeEnergy beacuse that free buffer (not filled buffer). Buffer is full so thats why its showing miliFE.
The filled buffer is in MFE (Million, Mega).
I checked power consumption in other units (EU, J...) and it's the same.
If you break and place the miner down, it will start consuming 8kRF again.

**Comment by pupnewfster** [comment]
Hmm I wonder if it was actually only using 400 FE/t then or if the usage display was just showing baseline before radius/speed upgrades etc got taken into account. Will try to look into it further for 10.0.19

**Comment by XxZajoZzO** [comment]
It was actually using 400FE because flux network was reporting 400FE and my cell at home was barely draining.

**Comment by Deutschland12** [comment]
I had the same issue so I did some messing around. It seems that the displayed power consumption in the bottom left of the GUI is 'correct' in the sense that it displays the power that is currently being consumed (but not necessarily what **should** be consumed). However, increasing the power consumption by increasing the radius from 10 to 32 blocks (x2 increase) or activating silk touch mode (x6 increase) are both reversed on relogging, while keeping the new settings active.

This means you can run a DM at 32 blocks radius with silk touch for the base consumption of 100J / 10EU by changing the settings to this and then relogging. Both the displayed consumption and the actual consumption are reverted back to the base value. As far as I can tell, upgrades are handled correctly, in that the consumption is not reset on relogging.

Judging by the fact that OP has silk touch enabled in their image, I'm pretty sure the same thing is going on here. 

I hope this helps - I can take some screenshots if needed.

**Comment by pupnewfster** [comment]
That is rather helpful information, out of curiosity is this on a server or single player so when I look into it further sometime this week I can try to accurately reproduce this. Also if it is in a server is it chunk loaded or not (my guess would be probably not but always good to double check when trying to reproduce an issue).

**Comment by Deutschland12** [comment]
I tested it on singleplayer while always in the same chunk as the DM.

**Comment by XxZajoZzO** [comment]
I had flux point that had chunk loading enabled powering the miner and I spawned like 150 away from the miner after world reload. Also it was singleplayer.
