### ISSUE TITLE
Unexpected error - Crash

### ISSUE THREAD

**Issue by szymulewsky** [mekanism/Mekanism#6909]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

After installing the Mekanism mods(Mekanism,Additons,Tools,Generators) and attempting to enter the server, client forge crashes.
Only shows on the server:
https://pastebin.pl/view/b7118f61

#### Steps to reproduce:
1. Install Mods on server and client
2.  try to join on server

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.4 35.1.37** 
**Mekanism:
Mekanism-1.16.4-10.0.18.445.jar
MekanismAdditions-1.16.4-10.0.18.445.jar
MekanismGenerators-1.16.4-10.0.18.445.jar
MekanismTools-1.16.4-10.0.18.445.jar

--

** 
**Other relevant version:**

**Comment by pupnewfster** [comment]
#6892 #6888 #6906, according to https://github.com/mekanism/Mekanism/issues/6906#issuecomment-765208693 updating optifine fixes it or at the very least removing optifine will fix it.

**Comment by szymulewsky** [comment]
Working Thanks!
