### ISSUE TITLE
Boiler Multiblock not forming

### ISSUE THREAD

**Issue by VOIDpotatoVOID64** [mekanism/Mekanism#6910]
#### Issue description:
I tried to make a thermo-electric boiler but the multiblock wouldn't form, I did my best to make sure that it wasn't an error on my part but couldn't figure out what was done wrong

#### Steps to reproduce:
Boiler- 7x7x11
![image](https://user-images.githubusercontent.com/73615162/105550847-c131c600-5cb6-11eb-8d61-6732256742db.png)

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.4; 35.1.13** 
**Mekanism: MekanismGenerators-1.16.4-10.0.18.445.jar** [if I need to share the version of the Mekanism base mod I can do that as well]
**Other relevant version:** 
Valhelsia 3 modpack version 3.1.1

**Comment by pupnewfster** [comment]
Does it say anything in particular is wrong if you right click the boiler casing with your configurator?

**Comment by VOIDpotatoVOID64** [comment]
> Does it say anything in particular is wrong if you right click the boiler casing with your configurator?

nothing happens when I click the casing with my configurator

**Comment by Robball14** [comment]
![Mek #6910](https://user-images.githubusercontent.com/54327191/105553153-36c48300-5d05-11eb-93bd-412f4a2c71fe.png)

Doesn't it miss a block here?

**Comment by VOIDpotatoVOID64** [comment]
> ![Mek #6910](https://user-images.githubusercontent.com/54327191/105553153-36c48300-5d05-11eb-93bd-412f4a2c71fe.png)
> 
> Doesn't it miss a block here?

omg I'm so dumb xD
with the gridlike pattern on everything it was hard to see, it's working now
