### ISSUE TITLE
Crash on joining server

### ISSUE THREAD

**Issue by Thefuzz1234555** [mekanism/Mekanism#6914]
**Issue Description:**
Upon joining a modded server the game will crash the player, this seems to be related to flamethrowers even though the player has very had a flamethrower and there were no crashes for the player in forge version 35.1.36

**Steps to reproduce:**
Attempt joining a modded server, Client works fine

**Version (make sure you are on the latest version before reporting):**
**Forge:** 35.1.37
**Mekanism:** Mekanism-1.16.4-10.0.18.445
**Other relevant version:**

Crash Log:
https://mcpaste.io/7f9f6f95c9d6661b

**Comment by pupnewfster** [comment]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*
Remove or update optifine they version you are using isn't compatible with the version of forge you are using.
