### ISSUE TITLE
java.lang.NullPointerException: Unexpected error 1.16.4 on 1.35.37 forge and OptiFine G6

### ISSUE THREAD

**Issue by carlucci9660** [mekanism/Mekanism#6918]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
logging into my home server, able to get in then kicked out immediately. 

#### Steps to reproduce:
1. Load all 96 mods fine, I can join a local game on my own pc....no boot
2. Try to log into my Home server with Local Ip, i get kicked.....Found 
3. Thread: Render thread
Stacktrace:
	at **mekanism**.common.base.PlayerState.setFlamethrowerState(PlayerState.java:319) ~[?:10.0.18] {re:classloading}
	at **mekanism**.client.ClientTickHandler.tickStart(ClientTickHandler.java:183) ~[?:10.0.18] {re:classloading}
	at **mekanism**.client.ClientTickHandler.onTick(ClientTickHandler.java:146) ~[?:10.0.18] {re:classloading}

#### Version (make sure you are on the latest version before reporting):
**Forge:1.35.37
**Mekanism:*1.16.5* 
**Other relevant version: MC 1.16.4 and OptFine G6

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/dpGrPQdP

[crash-2021-01-25_00.06.33-client.txt](https://github.com/mekanism/Mekanism/files/5864339/crash-2021-01-25_00.06.33-client.txt)

**Comment by thiakil** [comment]
Optifine is breaking it.
