### ISSUE TITLE
Add Mekanism to the service side (client) and then any appendages, such as Mekanism Generators, which crashes

### ISSUE THREAD

**Issue by 3269199948** [mekanism/Mekanism#6919]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description: 
Add Mekanism to the service side (client) and then any appendages, such as Mekanism Generators, which crashes

#### Steps to reproduce:
1.Adding Mekanism to the service side (client) works correctly at this time
2.Join any appendage, such as Mekanism Generators, which crashes on the service side (client).

#### Version
**Forge:*forge-1.16.4-35.1.29* 
**Mekanism:*Mekanism-1.16.4-10.0.18.445-all* 
**MekanismGenerators:*MekanismGenerators-1.16.4-10.0.18.445.*
**Other relevant version:*no other* 

#### crash-reports
https://pastebin.com/r2TW98kK

Bing translation is being used, I'm sorry if you don't understand

**Comment by tyler489** [comment]
Failure message: fml.modloading.dupedmod
2 versions of mekanism?

**Comment by 3269199948** [comment]
> Failure message: fml.modloading.dupedmod
> 2 versions of mekanism?

I don't quite understand, they are version consistent and I have three dependencies: Mekanismgenerators, Mekanismadditions, MekanismTools none of which work well with Mekanism.

**Comment by 3269199948** [comment]
> > Failure message: fml.modloading.dupedmod
> > 2 versions of mekanism?
> 
> I don't quite understand, they are version consistent and I have three dependencies: Mekanismgenerators, Mekanismadditions, MekanismTools none of which work well with Mekanism.

But Mekanism can run on its own

**Comment by Seniorendi** [comment]
Do you have the generator blocks(fission reactor, wind generator,...) when you remove Mekanismgenerators, Mekanismadditions and MekanismTools? Cause, the name of your Mekanism file is "Mekanism-1.16.4-10.0.18.445-all.jar", this "all" should mean, there is already everything in it.

**Comment by 3269199948** [comment]
> Do you have the generator blocks(fission reactor, wind generator,...) when you remove Mekanismgenerators, Mekanismadditions and MekanismTools? Cause, the name of your Mekanism file is "Mekanism-1.16.4-10.0.18.445-all.jar", this "all" should mean, there is already everything in it.

Yes, there is. Does that mean that these dependencies are already included?

**Comment by 3269199948** [comment]
> Do you have the generator blocks(fission reactor, wind generator,...) when you remove Mekanismgenerators, Mekanismadditions and MekanismTools? Cause, the name of your Mekanism file is "Mekanism-1.16.4-10.0.18.445-all.jar", this "all" should mean, there is already everything in it.

暂时先这样，感谢

**Comment by Seniorendi** [comment]
> Yes, there is. Does that mean that these dependencies are already included?

Yes, from where do you have this file?

**Comment by pupnewfster** [comment]
If you are using the all jar you already have all the modules, if you aren't you need to install them manually.
