### ISSUE TITLE
setFlameThrowerState Crash

### ISSUE THREAD

**Issue by SillyGoose078** [mekanism/Mekanism#6920]
I am hosting a dedicated server with Mekanism installed, which also includes the addons Mekanism Tools, Mekanism Generators, and Mekanism Additions. They are all the same version, running on version 10.0.18.445.
I can load into a singleplayer world fine, but I can't connect to my dedicated server. If I try to join the dedicated server, The client will crash with the following error message:

https://paste.ee/p/LjXbW

I have tried resetting Mekanism's config on both the server and client, and resetting the world on the server side.

**Comment by Seniorendi** [comment]
Optifine is the problem. Try to update to the newest Optifine version(1.16.5) or remove it.

**Comment by HydrogenC** [comment]
But the latest 1.16.5 Optifine also causes this crash.
