### ISSUE TITLE
Crashing when starting multiplayer world together with OptiFine

### ISSUE THREAD

**Issue by Unbuckle** [mekanism/Mekanism#6921]
it keeps crashing whenever I join my multiplayer world. Optifine is only installed client sided! And I did not pick any shader yet, its just basic Optifine 1.16.4_HD_U_G6 (which supports Forge .35 and up I think so there should not be any problem there). The Crash report says something about the Flamethrower state. 
Crash report can be found here: https://pastebin.com/R71QUPFX

**Comment by HydrogenC** [comment]
I also met with this problem -- it seems to happed occasionally.
