### ISSUE TITLE
Optifine incompatibility

### ISSUE THREAD

**Issue by peterbro1** [mekanism/Mekanism#6925]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Install forge 35.1.37 server with latest version of mekanism installed.
2. Connect via client with optifine installed
3. Crash

**Important note: **This issue is fixed by downgrading to forge 35.1.16, but many new mods are requiring the x.17 api.
#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.17
**Mekanism:** 1.16.4-10.0.18.445
**Other relevant version:** Optifine: Latest

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/peterbro1/c11b9ec29490cb1b248822a63d3d187a)

**Comment by Seniorendi** [comment]
With optifine latest, you mean U G6?

**Comment by Robball14** [comment]
> at mekanism.common.base.PlayerState.setFlamethrowerState(PlayerState.java:319) ~[?:10.0.18] {re:classloading}
yep
#6918 #6921 #6920 #6909 #6892 #6888 #6906 
it's optifine fault
