### ISSUE TITLE
Not detecting Forge version properly

### ISSUE THREAD

**Issue by CrazyGamer2241** [mekanism/Mekanism#6927]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I've got forge 35.1.4 and the latest mekanism update (released today) and it says i need forge version 35.1.11 or higher, but clearly i have got higher because ive got .4 which is like 20 versions higher than .11

#### Steps to reproduce:
1. install forge 1.16.4 35.1.4
2. install mekanism 1.16.4-10.0.19.446
3. launch the game

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.4
**Mekanism:** 1.16.4-10.0.19.446
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: https://pastebin.com/xWkpR5PX

**Comment by Seniorendi** [comment]
Forge 35.1.4 is .4 and not .40. You need to use forge 35.1.11 or later. Just use the latest forge version(35.1.37 for 1.16.4)

**Comment by pupnewfster** [comment]
That is not how version numbers work, each number is its own component `4 < 11`, version numbers aren't decimal numbers.
