### ISSUE TITLE
The server crashed and then failed to start

### ISSUE THREAD

**Issue by 3269199948** [mekanism/Mekanism#6940]
#### Steps to reproduce:
1.run Digital Miner
2.Then crash directly

#### Version (make sure you are on the latest version before reporting):
**Forge:*forge-1.16.4-35.1.29* 
**Mekanism:*Mekanism-1.16.4-10.0.18.445-all* 
**Other relevant version:*no* 

#### link https://pastebin.com/DYh1P4na

now,my server not run

**Comment by thiakil** [comment]
Report to arclight, their mixin is failing.
