### ISSUE TITLE
Basic Pressurized Tube

### ISSUE THREAD

**Issue by pc03hachibee** [mekanism/Mekanism#6941]
**Basic Pressurized tube** wont connect to **purification chamber** in survival, when I tried in creative mode it connect, sometimes it won’t connect  electrolytic separator , I think Basic Pressurized tube randomly wont connect..

**Mechanism Mod I used:**
Mekanism-1.16.4-10.0.19.446
MekanismGenerators-1.16.4-10.0.19.446

**Comment by pupnewfster** [comment]
How is the side config of the machine setup?
