### ISSUE TITLE
Power / Machine Stopping

### ISSUE THREAD

**Issue by FrezixAlan** [mekanism/Mekanism#6946]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
My machines would stop every once in awhile.. I have to break the electrical cables behind and replace them for them to work. Why does that happen? And is there a way to fix it..?

#### Steps to reproduce:
1. Joining / reloading the chunk (sometimes)
2. Unknown, just happens even if Ive been afking at the same spot.
3. 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.36
**Mekanism:** 10.0.18
**Other relevant version:** Direwolf 20  1.5.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]
![Unaaawawatitled](https://user-images.githubusercontent.com/46044782/106405939-b9221500-6472-11eb-950c-9aaa9d533983.png)
![Unaawatitled](https://user-images.githubusercontent.com/46044782/106405943-bb846f00-6472-11eb-95be-6f8e2f3b1127.png)

**Comment by FrezixAlan** [comment]
Yes, theres oxygen supplied. FYI. It stops too.

**Comment by pupnewfster** [comment]
Is this the same as #6356 (I am guessing not given it looks like your cables still have power). Out of curiosity are the machines and cables in different chunks? (F3+G should show chunk borders). Also if you could provide your latest log (or the server's if it is on a server) that may also hopefully reveal something useful.

**Comment by FrezixAlan** [comment]
Their in the same chunk. Sure, give me abit for the logs. ![image](https://user-images.githubusercontent.com/46044782/106409694-1c647500-647c-11eb-85c1-bafc800175bf.png)

**Comment by FrezixAlan** [comment]
[Compiled.zip](https://github.com/mekanism/Mekanism/files/5911436/Compiled.zip)

This is another instance.
![hmmmled](https://user-images.githubusercontent.com/46044782/106607306-21214a00-659e-11eb-8662-5ce7898afad9.png)
![hbbmmmled](https://user-images.githubusercontent.com/46044782/106607318-2383a400-659e-11eb-8c8f-f8fd218ba737.png)

**Comment by FrezixAlan** [comment]
This is new, It just happened when i broke the cable above.

![UntitlEWWQEed](https://user-images.githubusercontent.com/46044782/106607609-7bbaa600-659e-11eb-92ef-12666e7e68df.png)

**Comment by pupnewfster** [comment]
Thanks and ya this seems to be the same thing as #6356 so merging this issue with that one. Still not quite sure what causes and it isn't something I have really been able to reproduce though but it is something I want to look further into at some point and have some vague ideas what may be causing it.
