### ISSUE TITLE
Nuclear waste deletion bug

### ISSUE THREAD

**Issue by watlok** [mekanism/Mekanism#6947]
#### Steps to reproduce:
1. Connect waste output port of fission reactor to an ultimate pressurized tube
2. Connect ultimate pressurized tube to the fluid output port of a solar neutron activator (and nothing else)
3. Turn on reactor
4. Waste does not accumulate anywhere

I have only tried this on SMP and not in single player. Likely a reproducible version of #6378

#### Version (make sure you are on the latest version before reporting):
**Mekanism:** 1.16.4-10.0.18.445

**Comment by pupnewfster** [comment]
If you right click the pressurized tubes with a network reader does it say there is anything stored? (Also there is no fluid port in the SNA, and connecting it to the output port doesn't do anything for purposes of inputting).

**Comment by watlok** [comment]
Network reader clears it up. It's in the pipe but does not render when connected to the SNA's output.

**Comment by pupnewfster** [comment]
It isn't a bug but there has been enough confusion about contents and stuff in transmitters I think I will go through and implement what I discussed with aidan at one point and then scrapped of always showing at least something if there is any contents at all.
