### ISSUE TITLE
Missing Dictionary Tags For Prismarine and maybe more. 

### ISSUE THREAD

**Issue by TwoPointInfinity** [mekanism/Mekanism#6950]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I am playing on valhelsia 2, 1.15.2 with the latest version of mekaqnism and Prismarine and prismarine bricks do not have keys in mekanism dictionaries. I cannot mine them with the digital miner and have "no key" from the dictionary. There could be other blocks from vanilla minecraft that do not have keys but i am unaware of them.

#### Steps to reproduce:
1. check prismarine with the mekanism dictionary
2. try to mine [Tag] *prismarine* with the digital miner
3. be confused

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.37
**Mekanism:** 1.15.2-9.10.9.422
**Other relevant version:** Valhelsia 2 with manually updated minecolonies. 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by thiakil** [comment]
Tags are a vanilla thing, the Dictionary just lists them. Talk to your pack maker
