### ISSUE TITLE
Can not exit boats with base Mekanism mod and Better Diving mod Installed

### ISSUE THREAD

**Issue by Siber18** [mekanism/Mekanism#6952]
#### Issue description:

I noticed the other day while adding mods to my own server that I could no longer exit a boat so I went through and removed mods one by one until finally I found that Mekanism and Better Diving were the culprits. Even if I removed all of the key binds for Mekanism it still would not let me exit a boat just with the base mod installed along with Better Diving. I checked it on single player and the same issue came up. My guess is that either since better diving rewrites how water physics work, it interacts with some custom physics in Mekanism in a negative way, or that the key binds for something in Mekanism breaks better diving and boat controls. Idk im not a Minecraft dev I'm a Unity dev ¯\_(ツ)_/¯

I am on forge version 36.0.13 for minecraft 1.16.5

Link to Better Diving: https://www.curseforge.com/minecraft/mc-mods/better-diving

These are all the mods used to break the functionality.
![image](https://user-images.githubusercontent.com/31034109/106622441-927edf80-6541-11eb-891e-d6215b26875c.png)

#### Steps to reproduce:
1.  Install the forge and minecraft clients as well as the better diving and mekanism mods. 
(I am also using OptiFine_1.16.5_HD_U_G6 and OptiForge-MC1.16.5-0.5.0, I don't think they are part of the issue however.)

2. Start forge and make any new world.

3. Sit in a boat and wait a couple of seconds and try to exit and you wont be able to. 
(You can still exit if you hit exit fast enough, but after a little bit it wont let you)

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.16.5-36.0.13
**Mekanism:** Mekanism-1.16.4-10.0.19.446
**Other relevant version:** BetterDiving-1.16.5-1.1.0

**Comment by pupnewfster** [comment]
Does this happen without Mekanism given my best guess is this is a BetterDiving issue? Given we don't change dismounting at all and our keybinds that default to shift (the same as sneak and exiting boats) only takes effect while in GUIs.

**Comment by Siber18** [comment]
> Does this happen without Mekanism given my best guess is this is a BetterDiving issue? Given we don't change dismounting at all and our keybinds that default to shift (the same as sneak and exiting boats) only takes effect while in GUIs.

Ah, I just tested this and forgot to see if that was the case, It would appear so, sorry for the issue!
