### ISSUE TITLE
Animated machine texture in resource pack causes error texture

### ISSUE THREAD

**Issue by SteelBlue8** [mekanism/Mekanism#6953]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I'm working on creating a resourcepack and I've noticed that if you include a .MCMETA animation on certain machines that don't have on by default, instead of loading the animation as logic dictates it should, it simply loads the error animation. Testing has concluded that this is not due to bad formatting in the MCMETA or incorrect file names, mekanism simply refuses to load any texture that isn't a square. 

#### Steps to reproduce:
1. Make a resourcepack that adds animated textures to the energized smelter or purification chamber (other blocks may be affected but these are the ones I've found)
2. Apply resourcepack and turn on machine
3. Profit??

#### Version (make sure you are on the latest version before reporting):
**Forge:**  35.1.37
**Mekanism:**  V10? Latest update, as far as I'm aware. 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by thiakil** [comment]
Those 2 models mentioned are vanilla models, so I doubt it's our fault

**Comment by thiakil** [comment]
post your client log if you cant spot the model error in it

**Comment by SteelBlue8** [comment]
> post your client log if you cant spot the model error in it

Will do this later, but what do you mean by vanilla models? Both are from mekanism, not vanilla.

**Comment by pupnewfster** [comment]
The two models are using vanilla's model json system (and loader), additionally using mcmeta files for animations is also vanilla.

**Comment by SteelBlue8** [comment]
[2021-01-29-1.log.gz](https://github.com/mekanism/Mekanism/files/5922007/2021-01-29-1.log.gz)
This is the client log, I can't actually open it because I have never seen the .gz extension before, but as far as I can tell the base mod uses the same format for animations and models as my resource pack does? IE, default mekanism uses .json models and .MCMETA animations, so I cannot figure out why it is refusing to work with the resource pack specifically.

**Comment by SteelBlue8** [comment]
(Apologies for my idiocy, I just genuinely cannot figure out why its doing this)

**Comment by pupnewfster** [comment]
The client's latest log is one that is called `latest.log`. You sent one of your previous logs (gz is basically just a zip file with a slightly different format). All the log you sent shows is that Mekanism failed to load as it needs forge 35.1.11 or higher and you are using forge 35.1.4.

**Comment by SteelBlue8** [comment]
Hm, well, it seemed to load just fine in the game, that must be an outdated log. Sorry for the inconvenience, looking through the log I seem to have scuffed something with the json so I just need to figure out what
