### ISSUE TITLE
Metallurgic Infuser not accepting any input for enriched materials

### ISSUE THREAD

**Issue by BigBear123196** [mekanism/Mekanism#6958]
So I'm playing on Direwolf20 1.16 and using autocrafting from refined storage and realized the Metallurgic Infuser is just not accepting any input for enriched materials. I've tried using a hopper, used a enrichment chamber to output it to the machine but it's just not working. Is this a bug in just this pack?

**Comment by BlueAgent** [comment]
Have you set the sides correctly? By default the bottom side accepts extra (infuse) items. Can't seem to reproduce.

<details>
<summary>Screenshots</summary>

![2021-02-04_18 30 35](https://user-images.githubusercontent.com/630920/106880450-57360980-6717-11eb-93d7-95475d5c3bdb.png)
![2021-02-04_18 31 03](https://user-images.githubusercontent.com/630920/106880499-66b55280-6717-11eb-9ea2-a7fa0d9ea8fb.png)
</details>

**Comment by BigBear123196** [comment]
> Have you set the sides correctly? By default the bottom side accepts extra (infuse) items. Can't seem to reproduce.
> 
> Screenshots

I'm a Fucking Idiot, thank you for your help

**Comment by BlueAgent** [comment]
No worries you're fine.
