### ISSUE TITLE
1.7.10 Digital Miner Chunk Loading

### ISSUE THREAD

**Issue by OfflinePing** [mekanism/Mekanism#6960]
Hey, is there a way to let the Digital Miner chunk loaded in 1.7.10. I know that Mekanism has a chunk load module in the higher version but i dont know if there is anything like this in the 1.7.10.

**Comment by Seniorendi** [comment]
There should be an anchor upgrade.

**Comment by Burgerguys** [comment]
mekanism no longer supports lower versions. I would recommend looking to external chunk loader mods outside of mekanism.

**Comment by pupnewfster** [comment]
I believe the anchor upgrade exists in all versions of V9 or at least I would assume it does. If not, just use some other mod; Mekanism has been out of active development for 1.7.10 for a very long time.

**Comment by OfflinePing** [comment]
Well, i know that there is an anchor upgrade for like 1.10.* or higher with mekanism but in my case there is no upgrade in 1.7.10
If i only have a wrong version of Mekanism please tell me
Mekanism: 8.1.5
MekanismGenerators: 8.1.5
MekanismTools:8.1.5

**Comment by pupnewfster** [comment]
Use Mekanism V9 not V8
https://www.curseforge.com/minecraft/mc-mods/mekanism/files/all?filter-status=1&filter-game-version=2020709689%3A4449
https://www.curseforge.com/minecraft/mc-mods/mekanism-generators/files/all?filter-status=1&filter-game-version=2020709689%3A4449
https://www.curseforge.com/minecraft/mc-mods/mekanism-tools/files/all?filter-status=1&filter-game-version=2020709689%3A4449

**Comment by OfflinePing** [comment]
Can i just upgrade it without issues, or will my items be gone?

**Comment by pupnewfster** [comment]
No idea wasn't part of the development team back then, just backup your world and see?

**Comment by OfflinePing** [comment]
Well, it doesnt add the upgrade in the newer version so i will just use the old version so i dont need to update the server
