### ISSUE TITLE
Infusing factory Enriched *material* cost increased for some recipes, potential accident?

### ISSUE THREAD

**Issue by BenOHedges** [mekanism/Mekanism#6964]
Using the Direwolf20 pack and updated the version for Mek and some of the recipes changed, Ive tried to find a change log with the latest update with what im noticing but couldnt find anything so i think its a bug but correct me if im wrong.

I am used to the Enchricment recipes in an Infusing Factory to all be a 8:1 ratio, E.g 1 Enriched Redstone can be used with 8 osmium ingots to make 8 basic control circuits, etc. However in this version its gone down to 4:1. Same goes for reinforced alloy. it fills up the infusing factory by 80 per Enrichment item but uses 20 per craft causing the 4:1 ratio. Not sure about other recipies.

The reason i think this might of been a bug is because Infused Alloy stays with the 8:1 that im used to seeing.

Pardon me if this is a recipe change, i couldn't find mention of it anywhere.

Versions:
forge-1.16.5-36.0.14
Mekanism-1.16.4-10.0.19.446.jar

**Comment by pupnewfster** [comment]
We adjusted the costs of some of the infusing recipes in V10 as in my opinion especially for later game stuff a bunch of them were extremely cheap, and also it isn't really *all that more* expensive as long as you are enriching the materials to get 80 out of your inputs instead of 10.
