### ISSUE TITLE
Cardboard Box Caused Crash with Metal Barrels Mod

### ISSUE THREAD

**Issue by smigel32** [mekanism/Mekanism#6965]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. Create cardboard box
2. Place metal barrel from metal barrels mod
3. Use cardboard box on metal barrel

#### Version (make sure you are on the latest version before reporting):
**Forge:36.0.1
**Mekanism:10.0.18.445
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/6SuFFJt9

**Comment by pupnewfster** [comment]
It looks like some mod you have installed is breaking tags loading on the client, if I had to guess one of the many coremods you have installed. Can you reproduce this with just Mekanism and Metal Barrels?

**Comment by Yadokingu** [comment]
I have the same problem in the pack "All the Mods - Slice of Pi2".
But it's not just metal barrels, the cardboard box crashes the game when used on any block.

Mod list: https://www.modpackindex.com/modpack/26187/all-the-mods-slice-of-pi2-atm-slop2
Crash Log: https://pastebin.com/RS9VP4YL

**Comment by smigel32** [comment]
> It looks like some mod you have installed is breaking tags loading on the client, if I had to guess one of the many coremods you have installed. Can you reproduce this with just Mekanism and Metal Barrels?

After testing it out, I can confirm from the other commenter, that this issue is not exclusive to the Metal Barrels. My game crashed trying it on a vanilla dirt block.

**Comment by smigel32** [comment]
> I have the same problem in the pack "All the Mods - Slice of Pi2".
> But it's not just metal barrels, the cardboard box crashes the game when used on any block.
> 
> Mod list: https://www.modpackindex.com/modpack/26187/all-the-mods-slice-of-pi2-atm-slop2
> Crash Log: https://pastebin.com/RS9VP4YL

Yes I am playing the same modpack. I'm experiencing the issue with all blocks as well.

**Comment by pupnewfster** [comment]
No idea, but we are not going to be testing massive packs to find the conflicts for you. Best bet is either report the issue to devs of the pack you are playing so they can track it down or keep removing mods until you find which one is breaking tags as there is no case where the world should be loaded enough that a player can be in it where tags are not bound.

**Comment by pupnewfster** [comment]
It may also be of use to provide your debug or latest log as well on the chance that shows something exploding earlier on, though in the end it may still come down to a bunch of trial and error.

**Comment by Yadokingu** [comment]
Couldn't it at least fail a bit more gracefully when the baclklist isn't set instead of crashing the game? Like either being to able to pick up all blocks or none.

**Comment by pupnewfster** [comment]
It is vanilla minecraft that is failing... I am *not* going to add in stupid try catches because some coremod wants to break vanilla and put it in a state that is impossible to enter otherwise.

**Comment by Yadokingu** [comment]
Thank you for your work.
My issue was fixed by the SLOP update. Not @smigel32's issue was the same. But I guess since he didn't say anything else, it probably was also an issue with that mod pack.
