### ISSUE TITLE
Fission Reactor won't output any material (Steam/Waste)

### ISSUE THREAD

**Issue by bimmerlucas** [mekanism/Mekanism#6967]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Fission Reactor won't output any material (Steam/Waste). Have already ensured correct pipes are being used and that ports are set to the correct configuration (See image: https://user-images.githubusercontent.com/78285299/107126061-9aa98880-687b-11eb-9dea-9dcf2d26bcc5.png) (See other image: https://user-images.githubusercontent.com/78285299/107126102-f411b780-687b-11eb-8198-862ade75a43b.png)
Have already tried restarting game and server. Outputs don't work, but inputs do for some reason. 

#### Steps to reproduce:
1. Build Fission Reactor
2. Build Turbine
3. Build waste tank
4. Attempt to connect everything together
Version
Forge: 36.0.14
Mekanism: 10.0.19

**Comment by Seniorendi** [comment]
Set the tupes to output with an configurator

**Comment by bimmerlucas** [comment]
@Seniorendi That was already done

**Comment by bimmerlucas** [comment]
Solved, used a network reader and saw that there was fissile fuel blocking the pipes.
