### ISSUE TITLE
[Request] Finer grained control over weapon/tool stats in configs..

### ISSUE THREAD

**Issue by Vaelzan** [mekanism/Mekanism#6968]
**Describe the the feature you'd like**
Currently the configuration for sword damage is an integer value, while a float value instead would allow people to give finer control when balancing materials against other mods. Hoes are the same, although not as important in most cases.

In general the request would be to make all weapon/tool/armour statistics float values, usually only to allow values ending in .5 to be used.

**Describe alternatives you've considered**
Giving up and just rounding up or down the values we settled on. :)

**Additional context**
Doing a big balancing parse over all the weapons, tools, and armour in Valhelsia to ensure that things feel right in context of the entire pack.

**Comment by pupnewfster** [comment]
Went ahead and added float support for the damage values of: swords, pickaxes, and hoes. These config options will end up being reset to the defaults but not much that can be done about that.

**Comment by Vaelzan** [comment]
Thanks! No problem with the configs resetting, that's easy enough for us to deal with once the update is pushed to CurseForge, as we have everything in a separate design doc. Appreciate you letting me know.
