### ISSUE TITLE
Rename/add some items to be more scientifically accurate.

### ISSUE THREAD

**Issue by ausberg** [mekanism/Mekanism#6969]
**Describe the the feature you'd like**

There are some ambiguities and inaccuracies with the way that some items are currently named pertaining to fluids and chemicals. Fluids are a phase of matter that include liquids, gases and plasma. Chemicals are any material with a definite chemical composition.

In the current state of the mod, there are 'Fluid Tanks' that can only hold liquids and 'Chemical Tanks' that can only hold gases. For accuracy and clarity, I propose renaming 'Fluid Tanks' to 'Liquid Tanks' and 'Chemical Tanks' to 'Gas Tanks'. By extension, it would also make sense to add a third item called a 'Fluid Tank' that can actually hold any liquid, gas, or plasma. I don't see a need for a fourth item named a 'Chemical Tank' since just about everything made of matter is a chemical. This renaming effort should also extend to any references found in other items/tool-tips.

**Describe alternatives you've considered**
Ignore the real life inaccuracy and accept that fluids and chemicals have their own meaning in the Minecraft Universe.

**Additional context**
N/A

**Comment by thiakil** [comment]
Gas Tanks were renamed to Chemical Tanks as they can, in fact, hold more than just Gasses as of v10. e.g. Infusion types & slurries

Liquid vs Fluid has been done to death, and we're leaving things separate for balance reasons.

**Comment by ausberg** [comment]
> Liquid vs Fluid has been done to death, and we're leaving things separate for balance reasons.

Suit yourself...
