### ISSUE TITLE
Tooltip Text on the bottom left is extremely small and unreadable

### ISSUE THREAD

**Issue by Oyami-Srk** [mekanism/Mekanism#6970]
#### Issue description:

I set the GUI Scale to 2 but not auto to make UI elements not displayed too big, and found the text of Mekanism is too small to read (in English is better, but in Chinese is totally a disaster). I reproduce that for a clean install minecraft with only Mekanism and forge. May the problem releate the forge beta? I haven't tried variant forge version.
I tried Mekanism-1.12.2-9.8.3.390 on Minecraft 1.12.2 with GUI Scale set to middle, there is no that problem.
![](https://ftp.bmp.ovh/imgs/2021/02/0f89217b5f12616a.png)

#### Steps to reproduce:
1. Download Minecraft and install forge-36.0.14 then install Mekanism mod;
2. Entering game, scale screen larger (1920x1080) and change GUI scale to 2;
3. Use Jetpack or configurator and check the tips on the bottom left.
4. It will be too small to read.

#### Version (make sure you are on the latest version before reporting):
**Forge: 36.0.14** 
**Mekanism: Mekanism-1.16.4-10.0.19.446** 
**Other relevant version:**

**Comment by pupnewfster** [comment]
Currently that text is always the same size if memory serves, though I can look into making it scale/at least have a config option to change the size.

**Comment by pupnewfster** [comment]
Added a config option to our client config for 10.0.20 (which is still probably a few days off as I am waiting for some stuff on Forge's end). Example of how it will look on GUI scale 2 with the new config option set to max. I might end up increasing the max at some point if people still think it is too small but at least not it should be able to be configured to be a lot more readable.

![2021-02-07_12 11 41](https://user-images.githubusercontent.com/1203288/107153848-ab223780-693d-11eb-8b40-1f636389c9ca.png)
