### ISSUE TITLE
Crashing when rendering item portable_qio_dashboard

### ISSUE THREAD

**Issue by xTrM-EN** [mekanism/Mekanism#6971]
#### Issue description:
Crashing when trying to render mekanism:portable_qio_dashboard on some instances.

#### Steps to reproduce:
1) Render the portable_qio_dashboard item
2) N/A

This might be a bit cryptic, but it only happens on *some* minecraft runtimes and under specific conditions which I don't have full knowledge of yet.

I'll happily provide more information on demand, but I'm not sure about what's currently needed.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 35.1.37
**Mekanism:** 10.0.19
**Other relevant version:** N/A

#### If a (crash)log is relevant for this issue, link it here: 

[pastebin](https://pastebin.com/9rRkM1mp)

**Comment by pupnewfster** [comment]
Does this happen without optifine?

**Comment by xTrM-EN** [comment]
Going to try

**Comment by xTrM-EN** [comment]
I cannot seem to reproduce the issue consistantly even with optifine. I'm trying with different people with different render settings, some of which did crash before but now don't.
Maybe this'd be caused due to a combination of rendering flags? (something in worldrendering that causes ItemRenderer to fail)

**Comment by xTrM-EN** [comment]
Update: Since the start I've been using "Chocapic13's Shaders (High)" constantly and haven't had any issue. I tried disabling shaders and when I did with the item in my inventory I got the same exception and crash report. 
[crash-2021-02-07_23.04.54-client.txt](https://github.com/mekanism/Mekanism/files/5940122/crash-2021-02-07_23.04.54-client.txt)

**Comment by xTrM-EN** [comment]
Update #2: Relaunched the game, got the item without any shaders, worked fine. Deleted the item, loaded a shader "Chocapic13's Shaders (Low)", tried rendering the item and got the crash. This is most definitely an OptiFine caused issue. I kinda want to confirm 100% that it won't trigger a crash without a shader and whether a fix for shaders could be thinked of.

**Comment by pupnewfster** [comment]
Report it to optifine then, as it is just crashing deep in vanilla code trying to render an item there is nothing we can do about it. Even if there was there would not be much we can do about it as optifine is closed source and stuff and isn't worth the effort to try hacking around such a massive hack of a mod when we can't even see what the mod is doing.

**Comment by xTrM-EN** [comment]
I understand. That being said, OptiFine has been decompiled and deobfuscated by the community (https://optifinesource.co.uk/), but still I do understand the hassle that it'd be. Thanks for your help!
