### ISSUE TITLE
Visible Icon, but no model rendering

### ISSUE THREAD

**Issue by VictorJ02** [mekanism/Mekanism#6972]
I'm having a problem with a modpack containing Mekanism. Everything is showing up in the inventroy, all the icons for Mekanism are there, but when I try to for example but the gas mask on it doesn't render on me. Same with the Scuba Tank. They don't show up on my character in 3rd person. I have tried the set allowEmissiveItems to false workaround with no luck.

Minecraft: 1.12.2
Forge: 14.23.5.2854
Mekanism: 1.12.2-9.8.3.390

**Comment by pupnewfster** [comment]
Do you have optifine? If so try removing it as optifine does a lot of random hacks that breaks other mods.

**Comment by VictorJ02** [comment]
No, i don't have optifine installed.

**Comment by pupnewfster** [comment]
Not really sure then. Does this happen with just mekanism (and its various modules) or just in the modpack as a whole? My best guess is some other mod is probably breaking the rendering somehow; though I am not really sure how nor what to suggest you do to try and fix it given we are no longer developing for 1.12, so if it is on our end and not another mod's end there is nothing at all that can be done about it. Even if it is on another mod's end (which I think is far more likely), that mod may no longer be in active development for 1.12 anymore either.
