### ISSUE TITLE
Crafting Heat Generator will not work

### ISSUE THREAD

**Issue by ItsDevinBro** [mekanism/Mekanism#6973]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When following the wiki for the materials used to craft a heat generator it does not show the heat generator as a craftable item. No icon for it in the crafting table, no name pop up when hovering the mouse over the spot where it should pop up. 

#### Steps to reproduce:
1. In the same server gave the items to another player to attempt - no solution
2. Restarted the server - no solution
3. Tried on a different crafting table - no solution 

#### Version (make sure you are on the latest version before reporting):
**Forge:** - 1.16.5   (36.0.15)
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)  NONE

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Do you have mekanism generators installed? Also just use JEI to see the recipe

**Comment by ItsDevinBro** [comment]
it turned out to be missing the generator pack, thank you!
