### ISSUE TITLE
Configurator Wrench mode doesn't work anymore

### ISSUE THREAD

**Issue by Viperium** [mekanism/Mekanism#6974]
#### Issue description:
Sinds latest update of Direwolf20 1.16 pack Mekanism got updated aswell. Since then I am not able to break the pipes with the Configurator tool in wrench mode anymore.

Sneak right-click doesn't do anything anymore.

#### Steps to reproduce:
1. Install instance of Direwolf20 1.16 v 1.61
2. Get mekanism pipes
3. Get Configurator, set to Wrench mode and try destroying the pipes

#### Version:
**Minecraft:** 1.16.5
**Forge:** 36.0.14 
**Mekanism:** 1.16.4-10.0.19 
**Other relevant version:** Direwolf20 modpack 1.16 v1.61

**Comment by thiakil** [comment]
This sounds like a pack support issue. If they can reproduce it get them to post here
