### ISSUE TITLE
[Request] Facades, Similar to AE2

### ISSUE THREAD

**Issue by agentmarine** [mekanism/Mekanism#6976]
**Describe the the feature you'd like**
The ability to add Facades, slimline blocks that can be added on top of any cable or pipe to disguise the aforementioned from the general view.

**Describe alternatives you've considered**
This would be similar to what is available with AE2, but would be great to do within mekanism.
This has also been accomplished by Thermal Dynamics.

(both of these packs arent in

**Additional context**
[AE Facade ](https://ae-mod.info/Cable-Facade/ )
![image](https://user-images.githubusercontent.com/3437134/107297165-ac9d4e00-6a6a-11eb-8273-24688d3beeeb.png)

![image](https://user-images.githubusercontent.com/3437134/107297246-d22a5780-6a6a-11eb-89eb-aef03b566458.png)

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/114
