### ISSUE TITLE
can't access block inventorys 

### ISSUE THREAD

**Issue by darkridertj** [mekanism/Mekanism#6977]
currently using mekanism-1.16.4-10.0.19.446 in the direwolf20 1.16 pack on a server
i have tried refreshing the chunks and restarting the server which hasnt worked. they were working perfectly fine yesterday and nothing has changed since. as you can see in the video provided certain blocks wont open whilst others do.

https://user-images.githubusercontent.com/16530339/107356484-c53c5100-6ac8-11eb-8b6f-a8a292fc527e.mp4

**Comment by pupnewfster** [comment]
Could you please provide your latest log (and the server's latest log) from when it isn't working. I am wondering if some error is showing up in the log.

**Comment by darkridertj** [comment]
Hi just a quick update thought of trying to restart my client even though
it was on a server and that has seemed to fix it, do you still want the
logs if so I can try amd find them for you 😊

**Comment by pupnewfster** [comment]
Eh probably not worth it for now and I will just close this, but if it happens again probably worthwhile. My best guess is there is some other mod interacting strangely.
