### ISSUE TITLE
MekaSuit HUD vibrates violently when waving the mouse around with a framerate >10

### ISSUE THREAD

**Issue by TechEpic** [mekanism/Mekanism#6979]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When you have a framerate over 10, having the MekaSuit HUD active while rotating the player causes it to spazz out. It sort of looks like it's trying to have a sort of "lag-behind" effect similar to that of the player's hand, but it rapidly jumps back and forth between where it would be if it was lagging behind and where it would be if you weren't rotating at all, making it hard to read and very distracting.

#### Steps to reproduce:
1. Open game
2. Acquire mekasuit, make sure HUD is on
3. Try to get a framerate over 10
4. Wave the mouse around

#### Version (make sure you are on the latest version before reporting):
Forge: forge-35.1.37
Mekanism: Mekanism-1.16.4-10.0.19.446

#### Log
https://hatebin.com/iuuwcrfnap

**Comment by thiakil** [comment]
That honestly sounds like your computer is simply struggling to render Minecraft at all - the gui in the same place every time on our side, the engine handles any OpenGL translations based on camera position

**Comment by pupnewfster** [comment]
If I understand what you are talking about this is actually intended and took aidan a decent amount of time to implement as I believe he mentioned in this interview https://www.youtube.com/watch?v=BokUzAHSRR0

**Comment by TechEpic** [comment]
@pupnewfster I know what it's trying to do, and it's not doing it right on my computer.

**Comment by BlueAgent** [comment]
Maybe record a video and show us? If your computer can't do it use a phone or something perhaps?

**Comment by TechEpic** [comment]
@BlueAgent I thought about that, but I'm not sure how I would share said video.

**Comment by BlueAgent** [comment]
Upload to YouTube, Google Drive or drop box etc. of your choice and link it here.

More recently GitHub [supports video uploads](https://github.blog/changelog/2020-12-16-video-upload-public-beta/), so you can do that too if you want but it has to be MP4 or MOV formats. Should just be able to drag and drop it here.
