### ISSUE TITLE
Server Crash Issue 

### ISSUE THREAD

**Issue by SLSpicy** [mekanism/Mekanism#6980]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
when loading in game crashes

#### Steps to reproduce:
1. open minecraft
2. join the server

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.5
**Mekanism:** 1.16.4
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/AbVhnQcc

**Comment by Seniorendi** [comment]
Fast answer: Optifine is the issue. Update optifine and Mekanism to the latest version, then it should be fixed.
