### ISSUE TITLE
Dupe glitch with personal chests

### ISSUE THREAD

**Issue by Ale32bit** [mekanism/Mekanism#6981]
#### Issue description:
Minecraft allows to move items from the hotbar by pressing number keys, this can be used to move the personal chest while it's open.

Also that closing the GUI without taking back the chest will send it to the void.

#### Steps to reproduce:
1. open a personal chest in your inventory
2. (insert items you want to duplicate)
3. (close personal chest and open again)
4. press number of personal chest's hotbar slot while hovering over any slot in personal chest inventory (if personal chest is in slot 9, press 9)
5. remove items you want to duplicate
6. move personal chest from itself to any slot in your inventory except the original slot
7. close personal chest
8. repeat

#### Version:
**Forge:** 35.1.36
**Mekanism:** 10.0.19
**Other relevant version:** Tools: 10.0.19, Generators: 10.0.19

**Comment by pupnewfster** [comment]
Do you have quark or another mod installed that may mess with these keys. I will look into it before 10.0.20 is released but I know quark overrides and break's vanilla's `f` to switch to offhand key so I wouldn't be that surprised if it or another mod might be breaking the protections we have in place to stop it from being transferred to another slot.

**Comment by Ale32bit** [comment]
Yes, I'm using Quark r2.4-303 and its addon Quark Oddities.
