### ISSUE TITLE
My fission reactor is not forming. HELP

### ISSUE THREAD

**Issue by Mytical0** [mekanism/Mekanism#6982]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
My fission reactor does not form even though I have nevertheless respected all the conditions of the wiki( https://wiki.aidancbrady.com/wiki/Fission_Reactor )

#### Steps to reproduce:
1 .5*6*7 box with the two pillars in the middle
 (
![image](https://user-images.githubusercontent.com/54602334/107704300-4fe5a180-6cbd-11eb-9c2f-41b31550a04e.png
)),
(
![image](https://user-images.githubusercontent.com/54602334/107704391-7277ba80-6cbd-11eb-99ac-ffc7c5e410ae.png)
(
![image](https://user-images.githubusercontent.com/54602334/107704550-b66abf80-6cbd-11eb-8703-eb3a2ff86100.png)

2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.4
**Mekanism:** Mekanism-1.12.2-9.8.3.390.jar ( I think that's it )
**Other relevant version:** Installed generators, tools and additions addons all matching version of Mekanism

**Comment by pupnewfster** [comment]
Is that dynamic glass or reactor glass? Reactors only support reactor glass. Also try right clicking the fission casing with a configurator

**Comment by Robball14** [comment]
Excuse my rudeness but...

What?
![Screenshot_20210212_071730](https://user-images.githubusercontent.com/54327191/107736480-72e67480-6d02-11eb-99e7-f2c4248198f1.jpg)

**Comment by Mytical0** [comment]
sorry actually that's it : Mekanism-1.16.4-10.0.19.446

**Comment by Mytical0** [comment]
Thanks to you, the problem disappeared after I relaunched minecraft

**Comment by Robball14** [comment]
better leave this open IMO
just as a reminder that sometimes the mod might bug and not form some structures

**Comment by Mytical0** [comment]
OK like you want
