### ISSUE TITLE
Pink color in pipes, tanks  and portals is white

### ISSUE THREAD

**Issue by vysmirnov** [mekanism/Mekanism#6983]
#### Issue description:
Pink color of liquid ethylene in pipes and tanks is white. When in bucket or as liquid source ethylene is pink.
Also, portal is white when selected "pink" color.

#### Steps to reproduce:
1. Make infinite liquid ethytylene tank, portal frame and controller
2. Place it in the world, select portal color as "pink"
3. Look at this

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.0.21
**Mekanism:**  10.0.20

**Comment by pupnewfster** [comment]
I will try to come up with a fix for this sometime in the next few days, seems like it has something to do with my actually using proper normals now causing the diffuse lighting to wash the color out.
