### ISSUE TITLE
Mekanism doesn't work on a server

### ISSUE THREAD

**Issue by Cabu** [mekanism/Mekanism#6984]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Can't connect to a server with Mekanism. Client receive the message: 
Connection Lost
incomplete set of tags received from server.
Please contact server operator.

#### Steps to reproduce:
1. Install a fresh Forge server
2. Add Mekanism mods
3. Client can't connect anymore on the server

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.16.5-36.0.22
**Mekanism:** Mekanism-1.16.5-10.0.20.447, MekanismTools-1.16.5-10.0.20.447, MekanismGenerators-1.16.5-10.0.20.447, MekanismAdditions-1.16.5-10.0.20.447
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/Cabu/886ba2d2af03efbf01d6ce1043a15a3f

**Comment by pupnewfster** [comment]
Do you have mekanism installed on the server...?

**Comment by Seniorendi** [comment]
And please send logs wia https://gist.github.com or pastebin

**Comment by Cabu** [comment]
Hi, To be sure I added Biomes O' Plenty on my server. With only this one, that work fine. But as soon as i add Mekansim I got the error...

**Comment by pupnewfster** [comment]
Please provide both the full server log.

**Comment by Seniorendi** [comment]
![image](https://user-images.githubusercontent.com/67484093/107863420-9f120a80-6e54-11eb-9f38-fbb75f008ffd.png)
If this is your full Server log, you did not installed forge or something else. This is just Vanilla.

**Comment by Cabu** [comment]
Ok. Sorry for the trouble. I seen now that my systemd startup script didn't start the correct JAR :( It work now. Once again. sorry for the inconvenience :(
