### ISSUE TITLE
Industrial Turbine "max water output" value overflow on French language

### ISSUE THREAD

**Issue by AlexHgC** [mekanism/Mekanism#6985]
**Issue description:**

When you build Industrial Turbine with water output, the translation is too big, so the water rate overflow.

**Steps to reproduce:**

1. Put the game in French 
2. Make an Industrial Turbine
3. Go on statistics and check water output

**Version (make sure you are on the latest version before reporting):**
**Forge:** 36.0.22
**Mekanism:** 10.0.20

![image](https://user-images.githubusercontent.com/31996023/107863971-59efd780-6e58-11eb-918a-450dc8e6e675.png)

**Comment by pupnewfster** [comment]
![image](https://user-images.githubusercontent.com/1203288/107883293-19c24080-6ebc-11eb-8f1d-6ec3a875228a.png)

It ends up a little bit on the small side, but at least it will fit properly now and hopefully be more readable.
