### ISSUE TITLE
Robito stuck in seat

### ISSUE THREAD

**Issue by dimauloagustin** [mekanism/Mekanism#6989]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

When Robit go near a bibliocraft seat it get stuck into it.

#### Steps to reproduce:
1. Put a bibliocraft seat
2. put robit in the world and turn on follow mode
3. walk near the seat

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2847
**Mekanism:** Mekanism-1.12.2-9.8.3.390.jar

**Comment by pupnewfster** [comment]
1. We are no longer developing for 1.12 and bibliocraft isn't updated to 1.16
2. I don't think there is anything we could do about this regardless as my guess is their seats are like boats, minecarts etc that auto "grab"/pickup entities that get too close.
