### ISSUE TITLE
Digital Miner crashes server - TickingBlockEntity

### ISSUE THREAD

**Issue by andrekato1** [mekanism/Mekanism#6990]
#### Issue description:
Digital miner crashes server/world upon turning on. Also tested on the 1.16.5 version of Mekanism, which leads me to believe the crash probably occurring due to an interaction with other mod, but I wasn't able to fully understand what the crash reports were saying.

For completeness, I will also include the report generated by testing the 1.16.5 version, although I believe it's the same error. Used the same modpack, just replaced the Mekanism mods for its more recent counterparts.

#### Steps to reproduce:
1. Hook up a digital miner to a creative power source
2. Add dirt and cobblestone filters and turn on inverse mode
3. Turn on the miner

#### Version (make sure you are on the latest version before reporting):
**Forge: 1.16.5 - 36.0.22** 
**Mekanism: 1.16.4 - 10.0.19** 
**Other relevant version: 1.16.5 - 10.0.20** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist - 1.16.4](https://gist.github.com/andrekato1/0eeafa961ddad1df565528f908a3433d)
[gist - 1.16.5](https://gist.github.com/andrekato1/3a46d875c1817ed1094f6123e0899a07)

**Comment by pupnewfster** [comment]
I think this bug is really in effortless building for trying to send packets to fake players, but I will see if I can add in protection code on our end to prevent this for 10.0.21.

**Comment by andrekato1** [comment]
I confirmed removing effortless building solves the issue.
Thanks for the quick reply.
