### ISSUE TITLE
Digital miner not mining/finding any vanilla ores

### ISSUE THREAD

**Issue by GrameJunior** [mekanism/Mekanism#6991]
#### Issue description:
I am using the tag `forge:ores` with min=0 and max=18, but out of 600 blocks, no iron/gold/diamond was mined.
When using `forge:ores/diamond` or `*diamond`, it shows 0 blocks all around the world

Stuff i tried:
- forge:ores
- *ores*
- *diamond
- Putting ore in the ItemStack configuration

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.0.13
**Mekanism:** 10.0.19

**Comment by pupnewfster** [comment]
Are you sure another mod isn't just breaking ore gen and there are actually ores in the world? As last I tested it worked just fine.

**Comment by Robball14** [comment]
also try the same thing but in Mekanism 10.0.20 and forge 36.0.21

**Comment by GrameJunior** [comment]
Thanks for the hints!
The mod "Ore Stone Variants" in the modpack made the issue. It is generated as "osv_iron_ore", but a vanilla ore in the inventory.
