### ISSUE TITLE
Dynamic Tanks bug (1.12.2)

### ISSUE THREAD

**Issue by Mugiwaxar** [mekanism/Mekanism#6996]
#### Issue description:
I know this is a know issue and this was already fixed but I'm still playing with minecraft 1.12.2.
Any why to make the Dynamic Tank not loosing its content? This not append with all fluids.

#### Steps to reproduce:
1. Fill tank
2. save/quit/load
3. Tank is empty, have to remove and replace a block

#### Version (make sure you are on the latest version before reporting):
**Forge:**  14.23.5.2854
**Mekanism:** 1.12.2 - 9.8.3.390

**Comment by pupnewfster** [comment]
No idea but given it doesn't happen in 1.16.5 there is not much we can do about it as we are not developing for 1.12 anymore, so unfortunately any existing bugs are there to stay.
