### ISSUE TITLE
Induction Matrix Power Reading 

### ISSUE THREAD

**Issue by waffleattack** [mekanism/Mekanism#6997]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Trying to use an rf tools power screen module on an induction matrix only displays internal buffer of the IO port rather than entire matrix. Same goes for an xnet logic reader.

#### Steps to reproduce:
1. Create an induction matrix
2. Use a power screen module from rf tools utility on a port
3.put it in a screen

#### Version (make sure you are on the latest version before reporting):
**Forge: 8
**Mekanism:most recent version, not sure which one that is
**Other relevant version:** ATM 6 1.5.1

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
This would be because the matrix can go way past the max of Forge's energy system which those things use and there is nothing we can do about that on our end. Best bet for now until we reimplement computer craft support is to just use a comparator to get a percentage filled.
