### ISSUE TITLE
[1.16.5] Lava Crystal From Blood Magic in Heat Generator causes server crash

### ISSUE THREAD

**Issue by NillerMedDild** [mekanism/Mekanism#7000]
Original report: https://github.com/NillerMedDild/Enigmatica6/issues/1328

#### Issue description:
After placing a lava crystal (from blood magic) in a heat generator (mekanism), server crashes whenever someone enters that chunk. I've reverted the server to a version prior to putting the lava crystal in the heat generator, but wanted to report it!

#### Steps to reproduce:
1. Place Lava Crystal in Heat Generator

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.5-36.0.22
**Mekanism:** 1.16.4-10.0.19.446
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/NillerMedDild/d3578ea6917a89eaf658996d845c175b

**Comment by pupnewfster** [comment]
Hmm my best guess is that we are slightly too strict on the validator and that the lava crystals when emptied don't provide a capability (like empty buckets do) and they don't have a "burn" value. I will make sure to expand validation to allow for all items at some point (though potentially not before 10.1), as I figured everyone would make their empty containers still be fluid handlers for purposes of being able to be filled with automation, but it is technically valid that they are not.
