### ISSUE TITLE
(1.12.2) is this supposed to be correct ? 

### ISSUE THREAD

**Issue by ballsofheaven** [mekanism/Mekanism#7002]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
a recipe i cant create, with the tools i cant create because the recipe i need is not a recipe i can make 

#### Steps to reproduce:
1.download the mod for 1.12.2 
2.play the game 
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  forge-1.12.2-14.23.5.2854-installer
**Mekanism:** Mekanism-1.12.2-9.8.3.390
![Screenshot 2021-02-17 054758](https://user-images.githubusercontent.com/61277043/108158778-f8449d00-70e5-11eb-9b9e-f23d2855dba6.png)
![Screenshot 2021-02-17 054846](https://user-images.githubusercontent.com/61277043/108158788-fbd82400-70e5-11eb-8566-500b5d67d062.png)

**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by ballsofheaven** [comment]
craft tweaker was installed after mekanism and does NOTHING

**Comment by thiakil** [comment]
What? Take it up with the uncrafting table devs if it's not symmetric.

If you can't work out the recipe to craft it, check jei
