### ISSUE TITLE
[1.16.5] Mekanism and Mekanism Addition version error

### ISSUE THREAD

**Issue by Xiaolin2-g** [mekanism/Mekanism#7003]
![image](https://user-images.githubusercontent.com/79189625/108168697-83b63200-70d6-11eb-804d-aff260993c66.png)

Mekanism version is **Mekanism-1.16.5-10.0.21.448**
Mekanism Additions version is **MekanismAdditions-1.16.5-10.0.21.448**
Forge version is **36.0.42**

But Mekanism Additions ask for a previous version of Mekanism, regardless being both up to date.

**Comment by thiakil** [comment]
The error indicates your additions jar is not up to date...

**Comment by Seniorendi** [comment]
I installed every Mekanism addon for the latest version and everythign works just fine.

**Comment by Xiaolin2-g** [comment]
It must be a curseforge launcher error then, I downgraded the mekanism mods and installed them again and now it detects them fine. In the folder it said both mods were up to date.

**Comment by Seniorendi** [comment]
I tested it with Curseforge too.
