### ISSUE TITLE
Visual bug when Vein mining multibloc structure

### ISSUE THREAD

**Issue by AlexHgC** [mekanism/Mekanism#7005]
#### Issue description:

When i use vein mining for destroy multiblock structure, there is sometines an visual bug. Actually, this bug work with Thermal evap, dynamic tank, industrial turbine and other. Quit/join server work for fix

#### Steps to reproduce:
1. Make any multibloc
2. Make it full
3. Destroy with Vein

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.0.42
**Mekanism:** 10.0.21

![image](https://user-images.githubusercontent.com/31996023/108272182-325b8080-7172-11eb-832e-9d542d5c5f39.png)

**Comment by pupnewfster** [comment]
Is this in single player or on a server?

**Comment by Seniorendi** [comment]
I'm not able to recreate it in singleplayer

**Comment by AlexHgC** [comment]
New : I have break structural glass without vein mining, just with meka tool, and i have the same issue : 

![image](https://user-images.githubusercontent.com/31996023/108602131-b1360080-73a0-11eb-931f-594276c1e687.png)

**Comment by pupnewfster** [comment]
Do you have any mods that change rendering such as optifine? Honestly what sort of seems like is happening is that something is caching the fact that we added quads and not stopping when the multiblock is no longer formed (which may just be that our code from server to client to tell it the multiblock is not formed got broken or is being broken by another mod changing how update packets happen).

**Comment by AlexHgC** [comment]
I don't use optifine because i have everytime problem with.
I don't think i have mods that change rendering, here is my modlist : 

- AI Imporvements
- BasicNetherOres
- BiomesOPlenty
- Bookshelf
- Botania
- ChanceCubes
- ChickenChunks
- Clumps
- CodeChickenLib
- Controlling
- Connected Textures Mods
- Cucumber
- Curios
- Elevatorid
- FastLeafDecay
- VoxelMap
- FTB Ultimine
- Mr.Crayfish Furniture
- HWLYA
- **Immersive Portals** ( Maybe he broke model ? )
- IronChest
- JEI
- JEV
- JER
- Mekanism ( ofc ) with generators / tools 
- Morpheus
- Mystical Agriculture/Aggraditions
- NatureCompass
- Obfuscate
- Patchouli
- **Randompatches** ( idk if he change rendering )
- Simple Storage Network
- Torchmaster
- u team core
- Useful Backpacks
- Mr.Crayfish Vehicle
- WAWLA

**Comment by pupnewfster** [comment]
I definitely would try it without Immersive Portals as that mod does all sorts of screwy things related to models, rendering, and data syncing.

**Comment by Seniorendi** [comment]
I can confirm, it's an issue with Immersive Portals.
