### ISSUE TITLE
Items Output bug with Chemical Tank

### ISSUE THREAD

**Issue by AlexHgC** [mekanism/Mekanism#7006]
#### Issue description:

When you put "Output" on any face on chemical tank, Output don't work. But when you put "Input/Output", the Output work.

#### Steps to reproduce:
1. Configure Chemical Tank with output chest like this, it will not work
![image](https://user-images.githubusercontent.com/31996023/108298050-909d5900-719c-11eb-81f3-7ee29e58304f.png)

2.  Now, change the Output face to Input/Output, and it will work 
![image](https://user-images.githubusercontent.com/31996023/108298158-c4787e80-719c-11eb-8a2d-35ecd36f1f45.png)

#### Version:
**Forge:** 36.0.42
**Mekanism:** 10.0.21

**Comment by Seniorendi** [comment]
I can confirm that on 1.16.5

**Comment by BlueAgent** [comment]
Seems like what's happening is the "input slot" is the filling slot and the "output" slot is the emptying slot. Might need to split the "input" config to "fill input", "fill output" and "fill input/output". Similarly the for emptying slot.

Alternatively renaming "input" to "fill" and "output" to "empty" and "in/out" could maybe be for extracting complete or something.

Another option is having the tank be switchable from filling items or emptying items mode and the + and - graphics can change depending on mode or just removed. This might break existing setups though.

**Comment by pupnewfster** [comment]
I will try to fix this before 10.1, but going to leave my notes here for now from looking at it briefly as I am not going to actually fix it right now as I need to think about it a bit more and also check if there are any other slots that need fixing/adjusting and don't want to forget what I have found. Basically the issue has to do with when we setup the side config we only [mark](https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/common/tile/component/TileComponentConfig.java#L183-L184) one of the slots as an output slot when for the chemical tank and potentially some others we should mark both slots as valid input/output slots even on just input or just output as the slots themselves control.

**Comment by pupnewfster** [comment]
So as it turns out I had just entirely forgotten how things work (and it is all working properly and as intended), and input/output isn't purely based on if it only allows inputting or outputting but is more based on which slots are which. This means if you instead pull from it when it is set to input, once the item is *full* it will allow extraction.
