### ISSUE TITLE
FTB Chunks forces fission reactors to explode indefinitely

### ISSUE THREAD

**Issue by Direwolf20-MC** [mekanism/Mekanism#7008]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*
Done.

#### Issue description:
Caused a radioactive area in my world. Equipped a Hazmat suit (Full) and went to the area, died within a second or 2 with the message 'direwolf20 blew up'. Happened repeatedly, eventually went into creative to survive the area and use the / command to remove radiation.

#### Steps to reproduce:
1. See above.

#### Version (make sure you are on the latest version before reporting):
**Forge: 36.0.14** 
**Mekanism: Mekanism-1.16.4-10.0.19.446** 
**Other relevant version: N/A** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

https://cdn.discordapp.com/attachments/688824836105306119/812037485525729350/unknown.png
https://cdn.discordapp.com/attachments/688824836105306119/812037590231941120/unknown.png

**Comment by Seniorendi** [comment]
If you put the suit on AFTER you go to the radiation zone, you will die cause the hazmat will not remove the radiation from your body.

**Comment by Direwolf20-MC** [comment]
> If you put the suit on AFTER you go to the radiation zone, you will die cause the hazmat will not remove the radiation from your body.

I equipped the suit prior to going out there (But after i died from the first exposure) if that makes sense?

So I died -> Spawned at my base (far from the reactor), made a suit, equipped it, went back to the area, and died immediately.

**Comment by Seniorendi** [comment]
Kay, i will try that out

**Comment by Direwolf20-MC** [comment]
> Kay, i will try that out

Pup and I chatted and suspect what happened was: FTB Chunks was blocking block destruction from explosions, and therefore the explosions kept happening, and were killing me. So its probably less an issue with radiation protection and moreso the explosion mekanism. (Pun intended)

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism/commit/6c3066d741fb00e48c6a24bd31d8599edf461575 should fix our prevention against FTB Chunks making it so the reactor can infinitely explode...
