### ISSUE TITLE
Ultimate pressurized cables

### ISSUE THREAD

**Issue by ZirMc** [mekanism/Mekanism#7009]
**Describe the the feature you'd like**
Pressurized tubes have a way to big buffer compared to machine output, making it more difficult identifying bottlenecks. 

**Describe alternatives you've considered**
Did a fusion reactor in direwolf pack (mekanism 10.0.19.446) and I have spent more than 7 days ingame and not been able to fill the the buffer of the pressurized tubes. As an example I have 16 pumps with filter upgrades, and full speed upgrades, running at full power going into 2 separators (also with full speed and energy) and running one fusion reactor at injection rate 2, and I am still filling the pipes with deuterium after 1 or 2 weeks ingame time (incl some sleeping). It seems there is some scaling issue with the pressurized pipes, as one block length requires 8 000 mB, while a 20 - 30 block length requires over 300 000 000 mB to fill (same I have 4 full size thermal evaporation plants at max production, with 6 solar neutron activators and still have a backlog on the pipes after same time). 
 
**Additional context**
As I am using a pack, not entirely sure if this is down or up stream, so I put it as a feature request, if I *****d up, please feel free to mark as solved.

**Comment by pupnewfster** [comment]
We are tracking rebalancing/fixing the balance of various things like pressurized tubes in #6473
