### ISSUE TITLE
The default dissolution recipes can't be deleted by erasing the jonson files

### ISSUE THREAD

**Issue by Appdato** [mekanism/Mekanism#7013]
#### Issue description:
If you remove the tin and lead dirty slurry recipes nothing changes.

#### Steps to reproduce:
1.decompile the mod
2.Go to data> mekanism> recipes> processing> lead/tin> slurry
3.errase the dirty file
5.compile the mod
6.launch minecraft
7.see the recipe/check it

#### Version (make sure you are on the latest version before reporting):
Forge-36.0.42
Mekanism-1.16.5-10.0.21.448

**Comment by pupnewfster** [comment]
Either remove the recipe by overwriting it with a datapack with a disabled recipe, or use CraftTweaker/KubeJS to remove the recipe. Editing the jar to try and remove recipes is not something we are going to spend time supporting.

**Comment by Appdato** [comment]
> omething

I already use craft tweaker but it makes the same, I am reporting it here because it isen't a problem of crafttweaker. Here is my scrpt: https://pastebin.com/0QppwQ65

**Comment by Appdato** [comment]
> 
> 
> Either remove the recipe by overwriting it with a datapack with a disabled recipe, or use CraftTweaker/KubeJS to remove the recipe. Editing the jar to try and remove recipes is not something we are going to spend time supporting.

I already used crafttweaker, but it leaves to the same. I am repoting it here because it isen't a crafttweaker problem (as shown by removing it in the files don't fix it). Here is my script: https://pastebin.com/0QppwQ65

**Comment by jaredlll08** [comment]
@Appdato please upload your CraftTweaker.log file (`/ct log`) to pastebin

**Comment by Appdato** [comment]
> @Appdato please upload your CraftTweaker.log file (`/ct log`) to pastebin
@jaredlll08 I changed my code to only be the removing recipe and it work, soo maby is a problem with my scripts o crafttweaker. Here is my log: https://pastebin.com/P6L0VGCx

**Comment by Appdato** [comment]
> 
> 
> @Appdato please upload your CraftTweaker.log file (`/ct log`) to pastebin

Found the issue, there was a un finish code in my script. I thought it was some kind of bug because it didn't fix it when I deleted the jonson... Thanks for helping me!
