### ISSUE TITLE
Compatibility with RFTool eternal day dimensions

### ISSUE THREAD

**Issue by DoryanD** [mekanism/Mekanism#7014]
#### Issue description:
I'm using a RFTool dimension with eternal day in it, mainly for tritium creation.
But all the Solar Neutron Activator won't process any lithium. So i checked every Advanced Solar Generator and they're not detecting the sun, but i'm in a desert, with eternal day.

#### Steps to reproduce:
1. Create a RFTool dimension (mine got Flat, Desert, and Day as dimlet)
2. Setup a Solar Neutron Activator (even with creative tanks) or any blocks that require the sun (like solar panels)

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.16.4-35.1.36
**Mekanism:** 1.16.4-10.0.19.446 (got MekanismAdditions, Generators & Tools in the same version)
**Other relevant version:** 
- rftoolsbase : 1.16-2.0.10
- rftoolsbuilder : 1.16-3.0.13
- rftoolscontrol : 1.16-4.0.7
- rftoolsdim : 1.16-7.0.0-alpha
- rftoolspower : 1.16-3.0.8
- rftoolsstorage : 1.16-2.0.10
- rftoolsutility : 1.16-3.0.22

I've got the map and the modpack, I can send it if it's necessary

**Comment by pupnewfster** [comment]
I believe this should be fixed by Mekanism 10.0.20, are you able to reproduce this with an updated version of Mekanism? (Latest is 10.0.21). You will probably have to update to 1.16.5, but as all 1.16.4 mods should be compatible with 1.16.5 out of the box that shouldn't be a problem.

**Comment by DoryanD** [comment]
Ok thanks, it seems to solve the problem. I didn't knew i could go in 1.16.5 even if i still use some 1.16.4 mods.
Thanks ;)
