### ISSUE TITLE
Prevent Heat Generator Overlay from 'render' folder from being used

### ISSUE THREAD

**Issue by BentoGambin** [mekanism/Mekanism#7017]
Hi, I'm developing a resource pack that supports some mods, obviously mekanism is one of them, when making textures for the heat generator I encountered some issues that I think are caused by the overlays for it at the 'render' folder (these:
![image](https://user-images.githubusercontent.com/41645690/108806317-214ead00-7580-11eb-9017-9db4bf919477.png))

I already tried:
> Customizing the heat_generator.json and heat_generator_active.json block models;

> Editing the heat_generator.json blockstate to use differently named models,

> To set the overlays textures from the 'render' folder to be 100%transparent (and used proper exporting in gimp to keep image data on transparent pixels)

and none of the above worked, so I figured I'd need some help

#### Issue description:
![image](https://user-images.githubusercontent.com/41645690/108806819-86ef6900-7581-11eb-988b-3718616c8861.png)
^ how the heat generator looks (normal mapping kinda works, parallax occlusion mapping does not (which makes me think it's caused by some sort of overlay) and specular mapping does not work at all).
![image](https://user-images.githubusercontent.com/41645690/108806703-2fe99400-7581-11eb-9f45-e11b12c4425e.png)
^This picture is of the resitive heater, in which all the custom PBR maps work (they are basically the same: same reflection, smoothness, same POM depth, etc)

#### Steps to reproduce:
1. Use my rp, or any thing that customizes the heat generator's textures (my rp is at https://github.com/BentoGambin/FaithForge-64x)
2. Use a shader (in screenshots I used loop, (https://github.com/espen96/Loop/tree/loop2) but also happens with other shaders (i.e. Chocapic13's))
3. Confirm issue/problem?

To note: On some shaders the texture works as expected (that's how I know it's not an error on my part), but since I want broad shader support, I'd love a way to disable the overlay, thanks in advance!

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.0.41
**Mekanism:** 1.16.5-10.0.20.447
**Other relevant version:** MekanismGenerators-1.16.5-10.0.20.447

**Comment by thiakil** [comment]
Those textures in the render folder aren't used (for the heat gen), it's just the block model.

**Comment by CyanideX** [comment]
As thiakil mentioned, those textures are no longer used.
The new heat generator model used three textures found in **assets\mekanismgenerators\textures\block\model:**

- heat_generator.png
- heat_generator_led.png
- heat_generator_led_overlay.png

**Comment by BentoGambin** [comment]
Okay,Thank you all for the response! I will mess around a bit more, now that I have every info I may need I should find a fix.
And thank you for the awesome mod!
(Issue may be closed now)

**Comment by BentoGambin** [comment]
Okay, first of all very sorry to comment on a closed thread but I did further investigation and now I'm VERY intrigued:
I copied the contents from the resistive heater block model to the heat generator .json.
If it was something texture/resource related, both models would look indistinguishable. BUT they are somehow not:
![2021-02-23_17 27 29](https://user-images.githubusercontent.com/41645690/108904197-f9e9f580-75fc-11eb-98b3-5cf835219c2e.png)

Left: Resistive heater loding the resistive heater model.
Right: Heat generator loading the resistive heater model.
No additional change, same models, same textures used. etc.
As you can see, both are using the same model as they should, although the problems with shading regarded in the first post are somehow still there.

**Comment by CyanideX** [comment]
Does it still happen with the active/on state?

**Comment by BentoGambin** [comment]
Yes same behaviour

**Comment by pupnewfster** [comment]
Best guess is either it is because the shape of the blocks is different and is being used somewhere or some weird optifine/shader bug which I don't think there is really anything we can do to fix on our end.

**Comment by BentoGambin** [comment]
Well, I hoped it could be something fixable (preferably by me) but already expected it would be optifine/shader related. I will go bother the shader dev and see if he can do something. Thanks and have a nice one!

**Comment by pupnewfster** [comment]
Ok, so looked into this a bit further after discussing it with Cyanide, and the theory of what is causing it is that the heat generator renders in both the solid and translucent block layers using forge's multilayer model loader. Best guess is that optifine is ignoring the fact that only parts of it should render in specific layers and thus acting as if it is all one type and massively screwing up how lighting among other things happen. So ya seems like it is probably just an optifine bug that should be reported to them that they don't properly handle forge's multilayer loader.

**Comment by CyanideX** [comment]
Oh yeah, multilayer models. You will find that the Isotopic Centrifuge most likely has the same issue.

**Comment by BentoGambin** [comment]
Actually, the isotropic centrifuge works perfectly (maybe because since it has a translucent window in the texture is is in another render layer?)

**Comment by CyanideX** [comment]
I would have tried another shader as the **_first_** step in troubleshooting. 😅
