### ISSUE TITLE
D-T fuel chemical infuser recipe change

### ISSUE THREAD

**Issue by toddlersizedsharkcage** [mekanism/Mekanism#7020]
#### Issue description:
Producing D-T fuel in chemical infuser requires 1mb deuterium and 1mb tritium to produce 1mb D-T fuel.  Combining the two should logically result in 2mb of D-T fuel.  Combining 1mb deuterium and 1mb tritium in the reactor is a rate of 2, which equates to 2mb of D-T fuel.  Issue opened per pup's request.

#### Steps to reproduce:
1. Power fusion reactor with D-T, then power with deuterium and tritium separated
2. Production (MFE output, non-cooled) is doubled when injecting D and T separately vs injecting D-T pre-mixed (1mb/t of D plus 1mb/t of T produces the same MFE/t as 2mb/t of D-T)
3. Rates confirmed with network reader on pressurized tubes as well as confirming energy output into induction matrix

#### Version (make sure you are on the latest version before reporting):
**Forge: 36.0.39** 
**Mekanism: 10.0.21** 
**Other relevant version: MC 1.6.5** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
N/A

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Looked into this further, and ya seems like when I was moving recipes over to data gen (or maybe to json initially before moving back to data gen) I lost one of the mB of the output given looking back at [1.12](https://github.com/mekanism/Mekanism/blob/1.12/src/main/java/mekanism/common/Mekanism.java#L512) it was 2 mB that was produced.
