### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Teddygithubs** [mekanism/Mekanism#7021]
this is not somthing about Mekanism but im new to github. my game keeps crashing and i dont know why. ps. im using mods. I dont know whats making it crash but i hope that i can get some help!
[crash-2021-02-24_20.33.44-client.txt](https://github.com/mekanism/Mekanism/files/6038408/crash-2021-02-24_20.33.44-client.txt)

**Comment by Oct0bass** [comment]
If it's not mekanism then why are you posting it in the mekanism repository?

**Comment by pupnewfster** [comment]
Seems it failed to load this config `coldsostrich-common.toml` from the mod `coldsostrich` Best bet is try deleting the config it probably is corrupted if it still doesn't fix it go take it up with them. But yes if you know the issue has nothing to do with Mekanism don't post it here...
