### ISSUE TITLE
Personalized Chests disappear after quick-swapping

### ISSUE THREAD

**Issue by cubeslice** [mekanism/Mekanism#7025]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Personalized chests disappear along with everything in it if it is quick-swapped with another item in the hot bar.

#### Steps to reproduce:
1. Open a personalized chest (in hotbar)
2. Take an item out by quick-swapping it to the slot where the personalized chest was (if chest is in slot 5, click 5)
3. Lose your chest and everything in it after closing out of the GUI.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.5-36.0.15
**Mekanism:** 10,0.19
**Other relevant version:**

**Comment by Robball14** [comment]
Welp this is strange given that you aren't supposed to move the chest at all. 
Can you check if the bug appears in the latest Mekanism version? (10.0.21, requires forge 36.0.39 or superior)

**Comment by pupnewfster** [comment]
#6981
