### ISSUE TITLE
multiblock structures don't connect

### ISSUE THREAD

**Issue by SpeedrunnerG55** [mekanism/Mekanism#7026]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

multiblock structures don't have connected textures and have thick borders on them

![2021-03-01_02 50 38](https://user-images.githubusercontent.com/9276267/109467976-fa89ee00-7a39-11eb-88d4-a0344b4acec4.png)

#### Steps to reproduce:
1.install forge
2.install makanism
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  36.0.43
**Mekanism:** 10.0.21.448
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Robball14** [comment]
install CTM (ConnectedTexturesMod)

**Comment by SpeedrunnerG55** [comment]
oh, I didn't realize that mod was removed from my pack in a recent update and I thought mekanism changed.
