### ISSUE TITLE
Chemical Injection Chamber won't turn dead coral into normal coral.

### ISSUE THREAD

**Issue by xTobyPlayZ** [mekanism/Mekanism#7027]
Issue description: Chemical Injection Chamber won't turn dead coral into normal coral. I tried using steam and water vapour and neither of them work.

Steps to reproduce:
Use Chemical Injection Chamber
Put dead coral into the Chemical Injection Chamber
Input water vapor or steam

Version (make sure you are on the latest version before reporting):
**Forge: 36.0.14
**Mekanism: 10.0.19.446
![Bug](https://user-images.githubusercontent.com/40534430/109700600-d6274080-7bf6-11eb-9235-7561d2eeea0c.PNG)

**Comment by pupnewfster** [comment]
Update mekanism
