### ISSUE TITLE
security desk and quantum entangloporter are broken 

### ISSUE THREAD

**Issue by pondsters** [mekanism/Mekanism#7030]
when I open the security desk it says "security offline" underneath the remove button. I cannot add trusted players as whenever I type in the text box and press the tick button nothing happens.
if I open the quantum entangloporter and type in a frequency name it disappears but my friend can see the frequency. 
I have tried wiping player data but that did not work.

**Forge:** 
**Mekanism: 10.0.21.448** 
**1.16.5**

**Comment by pupnewfster** [comment]
I believe something is breaking your instance's world save data that mods try to use thus causing us to not be able to have any frequencies that work. Can you reproduce this with just Mekanism in a test instance? Also 1.16.5 provides very little information about what forge or mekanism version you are using as that is the minecraft version not the forge of mek version you have listed.

**Comment by pondsters** [comment]
I tried it in a single player world with the other mods i had installed and did not get the issue so i do not think it is because of another mod

**Comment by pupnewfster** [comment]
My guess is the refactoring I did in https://github.com/mekanism/Mekanism/commit/0f35046a070c610f312f702a68092712e69d06f7 will fix this for 10.1, so I am going to mark it as fixed in dev, though if after 10.1 gets released (and this issue gets closed) and you still have this issue I will reopen it.
