### ISSUE TITLE
I cannot use machine

### ISSUE THREAD

**Issue by max0n4ik** [mekanism/Mekanism#7032]
#### Issue description:
I cannot use machine beacuse i am not owner but its my world in singl. i changed acc(uuid).
how i can fix owner mod 

Forge: 1.12.2-14.23.5.2854
Mekanism: Mekanism-1.12.2-9.8.3.390

**Comment by Oct0bass** [comment]
Security Desk?

**Comment by max0n4ik** [comment]
yeap

**Comment by pupnewfster** [comment]
In theory you may be able to bypass it if you edit the configs to let ops bypass security and have cheats enabled on the world as well. Alternatively you could just change back to the other account set things to public and then be able to use them again.

**Comment by max0n4ik** [comment]
what config are we talking about?

**Comment by pupnewfster** [comment]
Mekanism's config
