### ISSUE TITLE
QIO Features

### ISSUE THREAD

**Issue by OfflinePing** [mekanism/Mekanism#7033]
**Describe the the feature you'd like**
I would love to see that the QIO System gets a Crafting Terminal (Dashboard) and some sort of auto-craft

**Comment by AidenWilkins** [comment]
This would make QIO even more useful and make it more than just a bulk storage system

**Comment by OfflinePing** [comment]
Yep,
it is  such a great mod, but this is something that is really missing :)

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/161
https://github.com/mekanism/Mekanism-Feature-Requests/issues/42
