### ISSUE TITLE
Covers for Cables/Pipes, etc

### ISSUE THREAD

**Issue by AidenWilkins** [mekanism/Mekanism#7034]
**Describe the the feature you'd like**
Covers for Cables/Pipes, with MCMultipart no longer being supported it would be nice to have the option for newer version of mekanism to have a way to make Cables/Pipes look clean when going through walls or simply hiding them

**Comment by Robball14** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/114
