### ISSUE TITLE
Mekanism V10 Fast Nuclear waste

### ISSUE THREAD

**Issue by OfflinePing** [mekanism/Mekanism#7035]
Hey,
Whats a fast way to get much nuclear waste for polonium (since bigger rectors doesnt give more waste)

**Comment by pupnewfster** [comment]
Waste is based on injection rate, bigger reactors allow for you to have a higher max injection rate (assuming you can keep it cooled properly so it doesn't explode). Though future questions may be better suited for our discord server https://discord.gg/nmSjMGc
