### ISSUE TITLE
logistic transporter and Ex Nihilo's barrel

### ISSUE THREAD

**Issue by Pupun2542** [mekanism/Mekanism#7037]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
when I use logistic transporter input seeds into Ex Nihilo's barrels they didn't consume any seeds but they do produce dirt for me. I don't know where to report this bug so I decided to report both Ex Nihilo and Mekanism.

#### Steps to reproduce:
1. place a barrel and 2 chest
2. connect chests and barrel with logistical transporter input a stack or two any seeds
3. quit world and enter it again

#### Version (make sure you are on the latest version before reporting):
**Forge: release 1.16.5-forge-36.0.43
**Mekanism: Mekanism-1.16.5-10.0.21.448
**Other relevant version: exnihilosequentia-1.16-2.0.2.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by remplerus** [comment]
couldnt reproduce that exact bug, but the barrel uses "virtual" saplings that it shouldnt have.
E.g. for 3 dirt, it uses not 24 saplings. it uses (depends on pipe) between 4 and 24 saplings, but never exact 24 saplings.

**Comment by pupnewfster** [comment]
99% sure this is on ex nihilo's end as they probably are doing something weird with their IItemHandler. Pretty sure at some point in some previous issue the response was they aren't supposed to support automation in their stuff at all (so not sure why they expose it) not sure. Either way pretty sure the issue is on their end.

**Comment by tyler489** [comment]
Leaving this here.
https://github.com/NovaMachina-Mods/ExNihiloSequentia/issues/164
they think it's a bug on your end it seems.

**Comment by pupnewfster** [comment]
No idea why literally took under two minutes to find the bug on their end via github, which is that they are entirely ignoring the simulate tag. Either way left a comment on their issue pointing them in the correct direction.

**Comment by tyler489** [comment]
> No idea why literally took under two minutes to find the bug on their end via github, which is that they are entirely ignoring the simulate flag. Either way left a comment on their issue pointing them in the correct direction.

Thanks Pup I figured it was something like that.
