### ISSUE TITLE
Reactor blocks dont work on server.

### ISSUE THREAD

**Issue by MilkMGN** [mekanism/Mekanism#7040]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When i or someone else places a reactor block, it shows an entirely different block. Only happens on a server though, and other players can see the reactor fine.

#### Steps to reproduce:
1.make block
2.place block
3.see wrong block.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 31.2.49
**Mekanism:** 9.10.9
**Other relevant version:** 
minecraft 1.15.2
Ubuntu server 18.04
client running win10
latest java (auto updating)

This also happens on biggerreactors.
https://user-images.githubusercontent.com/42798255/110262784-7a96f180-8000-11eb-824d-fb609be4c6b5.mp4

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Dont have a crash log.
[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by MilkMGN** [comment]
Server runs latest java with the auto updater, my pc runs this:
`openjdk version "15.0.1" 2020-10-20`

**Comment by thiakil** [comment]
That's an issue with your client or the server itself. Try with Java 8, remove any hacky client-only coremods and/or don't use a hacked client

**Comment by pupnewfster** [comment]
1.15 doesn't support java 15, it is only quite recently in 1.16 forge got support for java 15

**Comment by MilkMGN** [comment]
i have switched back to 1.8.0, and its still not working. i would go back on the server, but it makes me think its something between the link with client <-> server.
