### ISSUE TITLE
Ingame Manual

### ISSUE THREAD

**Issue by Epsilon-2** [mekanism/Mekanism#7041]
**Describe the the feature you'd like**
An ingame manual, this would allow for the construction of multiblocks with no need for the wiki or through images on google. There's no way somebody will construct a working turbine, or a working fusion reactor, or a working SPS without having to search it up or do an ungodly amount of trial and error. This is why an ingame manual, which gives proper descriptions and shows how a multiblock can be built would be key to helping with this.

**Describe alternatives you've considered**
I guess googling the items up, there's not really too many alternatives.

**Additional context**
Many mods (including a whole deluge of tech mods) have ingame manuals, this allows for the player to have some clue on how to construct a multiblock structure.

**Comment by pupnewfster** [comment]
#3070 #6651
