### ISSUE TITLE
Reading energy with computercraft caps at 2.15B FE

### ISSUE THREAD

**Issue by VulpTheHorseDog** [mekanism/Mekanism#7043]
**Issue description:**
At the very least with the induction matrix, reading the energy or energy capacity maxes at 2.15 billion, roughly where the integer limitations are at. Not sure how easy a fix it might be, but even a rather simple induction matrix is too big for a simple power monitor. I did read that some work on integration was done recently, so sorry if this has already been covered.

**Steps to reproduce:**
1. Set up a smallish induction matrix with over 2.15B energy capacity.
2. Try to read the max energy from one of the ports using computercraft.
3. It caps at the integer cap.

**Version:**
**Forge:** 36.0.35
**Mekanism:** 10.0.20 (Yes not the latest, but close to it and the changelog for .21 didn't seem to have anything on this.)
**Other relevant version:**

**Comment by thiakil** [comment]
Yes this will be covered by the computercraft peripheral code when it releases

**Comment by VulpTheHorseDog** [comment]
Alright thanks!
