### ISSUE TITLE
Computercraft integration for dynamic tanks

### ISSUE THREAD

**Issue by VulpTheHorseDog** [mekanism/Mekanism#7044]
**Describe the the feature you'd like:**
So most things that you think would have computercraft support have them, but the dynamic tank seems to not have any integration at all. The induction matrix multiblock for storing power having the integration but the dynamic tank not having it got me down a little, seeing as the dynamic tanks seem to be some of the best fluid/gas storage available of most mods and with mekanism having a metric ton of fluids and gasses, there becomes a big need to store them all in relative bulk

**Describe alternatives you've considered:**
A comparitor can do the same thing, but only to a slight degree. It has no way of accurately telling anything other that fullness, which only pertains to 16 values. There's no way to actually read how much is inside the tank, what fluid/gas it is, the exact number of the resource, or anything else which might prove useful to have.

**Additional context:**
Yes, there's a previously closed issue also somewhat relating to this. Not sure whether it was closed as a solid no, or just because it was a simple question and not a feature proposal.

**Comment by pupnewfster** [comment]
#6445
