### ISSUE TITLE
Atlas texture usage optimization

### ISSUE THREAD

**Issue by BentoGambin** [mekanism/Mekanism#7047]
So, Mekanism uses a lot of atlas space, which is fine, since it has texture for lots o'blocks.
I just want to bring attention to 2 models which have an unnecessary texture size for it's image content:
The quantum entangleporter in mekanism\textures\block\models folder can fit in a texture half of it's height  (256x256 -> 256x128)
Also the same can be said for the electrolytic_separator in the same folder.
I know it's something pretty stupid to ask, but yk, that would be very welcome.
Thanks in advance and keep up the amazing work!
![image](https://user-images.githubusercontent.com/41645690/110851459-d3c88480-828f-11eb-977e-be809424dc45.png)
Btw how they look like in the atlas^

**Comment by CyanideX** [comment]
Those two models have yet to be updated to the new model format but are certainly on my todo list!

**Comment by BentoGambin** [comment]
Glad to hear! Just out of curiosity, can you give an example of a block that has been formated?

**Comment by CyanideX** [comment]
Left is the old Techne format and the right is the new compressed json models.  ![image](https://user-images.githubusercontent.com/3106700/110891379-bb179900-82a6-11eb-9721-74dbaf6027d2.png)

**Comment by BentoGambin** [comment]
Impressive!
