### ISSUE TITLE
Robit cant walk over rails

### ISSUE THREAD

**Issue by oguh43** [mekanism/Mekanism#7050]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Robit cant walk over rails

#### Steps to reproduce:
1. get robit
2. place rails around him
3. watch him be sad

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.0.46
**Mekanism:** 10.0.21.448
**Other relevant version:** 1.16.5

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Started looking into this and I don't think there is really anything we can realistically do about this as the same exact thing happens/is true for vanilla mobs (for example cows and zombies).
