### ISSUE TITLE
Liquid Effects

### ISSUE THREAD

**Issue by Epsilon-2** [mekanism/Mekanism#7051]
**Describe the the feature you'd like**
Many fluids in the mod do not do anything to the player, this can be seen with sulfuric acid and hydrofluoric acid or many other normally hazardous materials. If their liquid versions actually dealt damage, harmed entities, and/or placed negative status effects (when applicable), it would open up plenty of nonconventional uses for the liquids.

**Describe alternatives you've considered**
It is quite difficult to think up alternatives for these without just doing what was already said.

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/59
