### ISSUE TITLE
mekanism digital miner crashes server 1.15.2 

### ISSUE THREAD

**Issue by detno** [mekanism/Mekanism#7052]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

[crash-reports.zip](https://github.com/mekanism/Mekanism/files/6135282/crash-reports.zip)

**Comment by Robball14** [comment]
whatever it is
doubt has anything to do with mekanism

**Comment by pupnewfster** [comment]
Looks like advent of ascension is sending packets to fake players which they should not be doing... So this probably should be reported to them. We added a workaround for mods who send packets to fake players *anyways* in 10.0.21 but that requires 1.16.5.

**Comment by detno** [comment]
ahh ok. advent hasnt updated to 1.16 yet. so is there a way for me to bypass this? like not have it mine certain blocks or certain dephs

**Comment by pupnewfster** [comment]
Report the bug to them because it is on their end and have them fix it?

**Comment by detno** [comment]
Ok I'll try. Hopefully they can do something
