### ISSUE TITLE
Dosemeter always says 99.99nSv, even if radiation present in environment

### ISSUE THREAD

**Issue by slugbaitsoul** [mekanism/Mekanism#7055]
#### Issue description:
Dosimeter (either handheld, or the one built into meka suit module and HUD) never changes, even if there is radiation in the environment.  Unless I am misunderstanding the purpose of the dosimeter, it does not seem to be telling me when the environment has radiation.

#### Steps to reproduce:
1. build fission reactor, and run it and allow reactor damage, to generate radiation
2. use dosimeter, or observe dosimeter in Meka Suit HUD, always says 99.99 nSv
3. using /mek radiation get ~ ~ ~ shows radiation (example 128.785 Sv/h), and radiation particles in the air

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.0.21
**Mekanism:** Mekanism-1.16.4-10.0.19.446.jar 
**Other relevant version:** All The Mods Modpack v6-1.5.2
minecraft version 1.16.5

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
There is no crash log, the behaviour is observed in game.

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
The dosimeter shows how much radiation you have absorbed, if you want to see how much is in the environment use a geiger counter.

**Comment by slugbaitsoul** [comment]
*forehead slap*.  I'm so sorry, thank you very much!
