### ISSUE TITLE
Config constantly re-creatig itself

### ISSUE THREAD

**Issue by Rodg88** [mekanism/Mekanism#7057]
#### Issue description:
The tools.toml file seems to have some error, so forge keeps re-creating it, but the freshly made one has the same error, whatever it is, so it just keeps repeating the re-creation.
See https://github.com/NillerMedDild/Enigmatica6/issues/1396

#### Version (make sure you are on the latest version before reporting):
36.0.40 - 36.0.45
**Mekanism:** 
10.0.21.448
**Other relevant version:** 
Enigmatica 6 modpack 0.4.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
latest.log
https://gist.github.com/Rodg88/eabe69a174c6c9bb43efefaaece3246b

**Comment by pupnewfster** [comment]
Does this happen with forge 36.0.58 (well really forge 36.0.54+ but the versions above that but before 36.0.58 had a couple other issues so I wouldn't use them)?

**Comment by Rodg88** [comment]
Yeah I've heard .54+ fixes it, but the pack I'm playing isn't on that forge yet. Is 58 the 'recommended' forge now?

**Comment by pupnewfster** [comment]
Sort of, if you mean officially "recommended" usually people suggest using the latest, as recommended for forge is more of a "minimum", but I believe either later today or tomorrow an official "recommended" build will be out after a couple minor things are addressed/cleaned up.
