### ISSUE TITLE
MC crash upon using RFtools Transmitter and receiver with radiation

### ISSUE THREAD

**Issue by mcintosh109** [mekanism/Mekanism#7059]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.get radiation on plyer
2. use the rf tools transmitter and recever
3.game crash DW1.16.5 Pack Ver1.7.0

#### Version (make sure you are on the latest version before reporting):
**Forge: forge-1.16.5-36.0.45** 
**Mekanism: Mekanism-1.16.5-10.0.21.448** 
**Other relevant version: rftoolsutility-1.16-3.0.23  ** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

crashlog online ----> https://paste.ee/p/BRrpp

will upload to RFtools crash report as well

[Crashreport 3.15.21.txt](https://github.com/mekanism/Mekanism/files/6145086/Crashreport.3.15.21.txt)

**Comment by pupnewfster** [comment]
Looks like the crash has nothing to do with Mekanism and is caused by AE2 (or potentially RFTools doing something weird with worlds that AE2 does not expect).

**Comment by mcintosh109** [comment]
will move report to AE2
