### ISSUE TITLE
[1.12.2]  Mekanism =crashes

### ISSUE THREAD

**Issue by 593681878** [mekanism/Mekanism#7061]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

The game had an unknown crash, and the report showed that it was the problem

Sorry to bother you

#### Version (make sure you are on the latest version before reporting):
**Forge:1.12.2** 
**Mekanism:1.12.2-9.8.3.390** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: https://gist.github.com/593681878/726b5ddb4695bc79728298323c04a3ba

**Comment by Robball14** [comment]
from what i can understand, Deep Mob Learning is trying to do something with mekanism but failing at it

**Comment by pupnewfster** [comment]
Something corrupted/screwed up your world and is causing a deep mob learning extraction chamber tile to be in the spots one of our blocks is. As a work around you can probably in the forge config set it to remove erroring tile entities (which might fix it I forget), if not you can probably use an external world editor like MCEdit to remove the block.
