### ISSUE TITLE
Electrolytic Separator consumes too much energy 

### ISSUE THREAD

**Issue by Maximullius** [mekanism/Mekanism#7064]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Electrolytic Separator pumping hydrogen into a gas burning generator is consuming 640kRF/t
#### Steps to reproduce:
1. I have no idea
2. 
![2021-03-16_16 48 22](https://user-images.githubusercontent.com/80789827/111378584-66926600-8678-11eb-9b1a-23a3c686392c.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.2-14.23.5.2847-universal.jar
**Mekanism:** Mekanism-1.12.2-9.8.3.390
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Don't burn hydrogen in a gas burning generator you won't gain energy you should just break even. If you want to make energy with a gas burning generator use ethylene.
