### ISSUE TITLE
Metallurgic Infuser not accepting diamonds despite recipe for Reinforced Alloy

### ISSUE THREAD

**Issue by adammbaker** [mekanism/Mekanism#7065]
#### Issue description:
In trying to make Reinforced Alloys I am unable to add diamond in any form to the Metallurgic Infuser despite the three options the recipe states.

#### Steps to reproduce:
1. Set up a Metallurgic Infuser.
2. Try to insert either Diamond Dust from Thermal Series, Enriched Diamond from Mekanism, or any Mekanism tank with Diamond infuse type.
3. Try adding redstone to see that it indeed does accept redstone.

#### Version (make sure you are on the latest version before reporting):
**Forge: 36.0.46** 
**Mekanism: 1.16.5-10.0.21.448** 
**All The Mods 6 - To The Sky - ATM6S: 1.0.2**

**Comment by pupnewfster** [comment]
Does it already have redstone in it or is the buffer empty? Also do you have anything in the item slot of the infuser?

**Comment by adammbaker** [comment]
*Oh how embarrassing*. I thought I checked that but I apparently didn't. Yes, there was redstone already in there. Feel free to delete this issue.
