### ISSUE TITLE
Show Meka-Tool Energy Percentage on the HUD

### ISSUE THREAD

**Issue by AyScorch** [mekanism/Mekanism#7069]
**Describe the feature you'd like**
A way to set and select "presets" to the Meka-Tool (Possibly even the Meka-Suit itself) to allow for easier configuration.
You would be able to switch the presets just like the Atomic Disassembler, by either shift-clicking or through the selection circle.
A small selection of Icons can be set for each preset, as well as a name. 
More presets can be added per a new module type, Data Storage.
Preset Status can be shown on the HUD

Also, the Meka-tool Battery Percentage should be shown when the Meka-Tool is on the Hotbar with the Meka Suit Helmet is on the user. 
**Describe alternatives you've considered**
Manually configuring the MekaTool each time is still possible but it is very tedious. This is why I haven't switched to the Meka-Tool fully from the Atomic Disassembler 
**Additional context**
No other context.

**Comment by pupnewfster** [comment]
Most of your thing is covered by this https://github.com/mekanism/Mekanism-Feature-Requests/issues/140 not quite sure what you mean about battery percentage though.

**Comment by ScorcherOfAwesomeness** [comment]
> Most of your thing is covered by this [mekanism/Mekanism-Feature-Requests#140](https://github.com/mekanism/Mekanism-Feature-Requests/issues/140) not quite sure what you mean about battery percentage though.

Battery percentage on HUD as in when the MekaTool is in your Hotbar, the energy percentage is displayed like the rest of the MekaSuit.
