### ISSUE TITLE
3 Heavy Bug In Nether [36.1.1]

### ISSUE THREAD

**Issue by KhanhPham05** [mekanism/Mekanism#7070]
#### Issue description:
1. Elictrical Pump reset its' data when placed in nether
2. Crash when open energy cube Screen in nether
3. Energy Cube disapears

#### Steps to reproduce:
_Bug 1:_
1.Go to nether 
2.Place a Electric pump but there is some water in it then use fluid tank to empty the pump
3. Go to overworld and come back

_Bug 3:_
1. go to nether
2. Place Energy Cube with Energy in it
3. Go to Overworld and then comeback to nether

#### Version (make sure you are on the latest version before reporting):
**Java**: 14.0.2
**Forge:** 36.1.1
**Mekanism:** 10.0.21.448
**Other relevant version:** None

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

_Bug 2:_
 [pastebin](https://pastebin.com/hy81SzY6)

**Comment by pupnewfster** [comment]
Don't make one bug report for multiple unrelated issues:
1 and 3. Sounds like some other mod you have installed is causing the world not to save.
2. Does the crash happen without optifine as my best guess is it or some other mod is causing it so the tile is null for no reason.

So on second thought maybe the issues are all related and you just have some mod massively breaking/screwing with your game.

**Comment by KhanhPham05** [comment]
I will make a instance with only mekanism and give feedback to u very quick

**Comment by KhanhPham05** [comment]
Ok i think i will close this issue, it works fine
