### ISSUE TITLE
Gauge dropper and radioactive materials

### ISSUE THREAD

**Issue by Yusunoha** [mekanism/Mekanism#7071]
Currently radioactive materials can only be moved through pressurized tubes. Gas tanks don't accept these gasses, and you can store the gasses in machines, but if you try to move a machile while there's radioactive material inside it, the radioactive material gets released in the surroundings, which ofcourse is dangerous.

I thought about trying to gauge dropper, because why not. So I opened a PRC, and tried picking up the polonium with the dropper. Not surprising, left clicking didn't work. So I tried shift-right clicking.... bad decision, REALLY bad decision.

It appears shift-left clicking with a gauge dropper in a machine voids the material, but doing this with a radioactive material will... yes, you guessed it by now, release it into the surroundings.

I want to suggest to change this behaviour with the gauge dropper and radioactive materials to not do anything, whether you left-click, right-click, shift left or right click. If the gauge dropper can't be used to move radioactive materials, it shouldn't release it either.

And if the intention of this behaviour was to void any radioactive materials inside a machine if you want to remove the gasses, then you can just break the machine without using a gauge dropper to do that.

**Comment by pupnewfster** [comment]
This behavior is fully intended
