### ISSUE TITLE
Wireless Network Trusted Security Option

### ISSUE THREAD

**Issue by LogosWorks** [mekanism/Mekanism#7074]
**Describe the the feature you'd like**
Currently all devices have public, private, and trusted as options. It would be nice for this functionality to exist for networks also to allow for shared QIO systems and Entanglopers without opening up a network to be public to a whole server.

**Describe alternatives you've considered**
While this can be sidestepped by having each player hook up a pair of entanglopers to a pipe there are no scalable solutions for shared QIO other than public.

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/125
