### ISSUE TITLE
BC problem

### ISSUE THREAD

**Issue by 3269199948** [mekanism/Mekanism#7075]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.Build a BC (waterfall -> Paper or Spigot, login server)
2.Join the mod
3.Join the server via port BC and be directed to the login server
4.This problem appears....

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.16.5 36.1.2
**Mekanism:** Mekanism-1.16.5-10.0.21.448
**Other relevant version:** paper 1.16.5 waterfall 1.16

When I was using this mod, I was off waterfall -> Paper (Login Server) - BBB>X and I couldn't get into the Login Server, he told me

Incomplete server tags, disconnecting. Missing

why？When I use other mods, that's not the case

If so, I cannot join my login server

**Comment by pupnewfster** [comment]
This is because Mekanism is required on both the server and the client so we have no reason to make the tags "optional" and have forge inject them.

**Comment by 3269199948** [comment]
> This is because Mekanism is required on both the server and the client so we have no reason to make the tags "optional" and have forge inject them.

The 1.12.2 version of MEK does not

**Comment by pupnewfster** [comment]
Tags don't exist in 1.12.... They are a concept vanilla added in either 1.13 or 1.14 not sure offhand which.

**Comment by 3269199948** [comment]
> Tags don't exist in 1.12.... They are a concept vanilla added in either 1.13 or 1.14 not sure offhand which.

Well, in that case, I'll add MEK to my BC



Unless we can get around him
