### ISSUE TITLE
Pressurised reaction chamber does not accept gas upgrade

### ISSUE THREAD

**Issue by Mechrior** [mekanism/Mekanism#7080]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1. place PRC
2. Open UI try to insert GU
3. Try to crouch R-click GU

**Forge:** 36.0.45
**Mekanism:** 1.16.5-10.0.21.448
**Other relevant version:** FTB Direwolf20 1.16 modpack

honestly thought the PRC would use the GU as it uses gas o.O

**Comment by pupnewfster** [comment]
It doesn't the machines that accept gas upgrades if memory serves are the ones that have per tick gas costs as a secondary input.
