### ISSUE TITLE
Crash report on startup

### ISSUE THREAD

**Issue by NoCeleryPlease** [mekanism/Mekanism#7088]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### _**Issue description:**_
While trying to start up the game. It crashes

#### **_Steps to reproduce:_**
1. Launch the game

#### _**Version**:_

**Forge: 36.1.4**
 
**Mekanism: Mekanism-1.16.5-10.0.21.448** 

**_Crash Report:_**
[crash-2021-04-06_00.18.26-fml.txt](https://github.com/mekanism/Mekanism/files/6262891/crash-2021-04-06_00.18.26-fml.txt)

**Comment by Robball14** [comment]
your forge version is wrong
you need 36.1.39 or higher
.39 is NOT a decimal number

**Comment by Seniorendi** [comment]
What do you mean? 36.1.4 is the newest version.
See http://files.minecraftforge.net
You mean 36.0.39.

**Comment by Robball14** [comment]
oh wait i got confused nvm
*facepalms*

**Comment by pupnewfster** [comment]
Some mod is being dumb and adding a null layer render to an entity, this has nothing to do with us, but I did add protection code against mods being dumb like this in 10.1

**Comment by NoCeleryPlease** [comment]
> Some mod is being dumb and adding a null layer render to an entity, which would normally cause the game to crash as soon as the game tries to render that entity. So this doesn't really have anything to do with us beyond the fact that we end up causing it to crash on startup instead of on rendering due to us trying to check what type of render layers it has.. I did add protection code against mods being dumb like this in 10.1 but truth be told the crash isn't really as much Mekanism's fault as one of your other mods.

Is there any specific direction of what the mod confliction could be? Or do I have to look into it more

**Comment by pupnewfster** [comment]
It most likely is some mod that adds entities, though there is a very remote chance that it is a mod not adding an entity that is causing it.

**Comment by NoCeleryPlease** [comment]
Alright, I have a few ideas of what it could be. Thank you very much!

**Comment by NoCeleryPlease** [comment]
> It most likely is some mod that adds entities, though there is a very remote chance that it is a mod not adding an entity that is causing it.

Found it. It was a mod called "Outvoted". Added a mob that was from an old minecraft update that wasn't released. So ig don't keep these two mods away from each other haha
