### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by gdegreen** [mekanism/Mekanism#7089]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I did not directly experience this issue but it was caused by a player on my server which caused it to crash. This player went to mine (what I believe) what was a basic smelting factory in his smelting setup. He accidentally used the vein miner option on his atomic disassembler, which destroyed all of the smelting factories at once. He had basic logistical transporters connected to the smelting factories. I believed this is important to note because I see that this item was mentioned in the crash log. Apparently he also had many items within the smelting system while this happened. When he mined the smelting factory, all of the items dropped and he was immediately disconnected from the server. He said that the message on the screen after he disconnected said "too many stacks" or along the lines of that.

#### Steps to reproduce:
1. Own an atomic disassembler
2. Construct a smelting setup using smelting factories and use basic logistical transporters to transfer items in and out of them
3. Have many items within the smelting system
4. Use the vein miner option of the atomic disassembler on one of the smelting factories

#### Version (make sure you are on the latest version before reporting):
**Forge:1.16.5-36.1.4** 
**Mekanism:1.16.5-10.0.21.448** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://gist.github.com/gdegreen/30e8d675755b23892357cd631960a0f5

####EDIT
Another crash now happened, it seems to have been caused by the mechanical crafter, such as @thiakil mentioned it with the first one. It did have basic logistical transports attached to it, and that seems to be common between the two crashes. All he did was break the mechanical crafter with a regular pickaxe and it caused the server to crash. Same version for everything.
Crash Report: 
https://gist.github.com/gdegreen/7f5dffb5b7d5d89223fa88f1a4d96062

####EDIT 2
I didn't realize the mechanical crafter was from Create. It seems to be a clash between two mods. Of which one carrying the blame, I have no clue

**Comment by thiakil** [comment]
Looks like `MechanicalCrafterTileEntity` didn't invalidate its capability when the block was broken...

**Comment by gdegreen** [comment]
> Looks like `MechanicalCrafterTileEntity` didn't invalidate its capability when the block was broken...

A second crash happened and it seems to have the mechanical crafter in common. Sort of unrelated, could you elaborate "invalidate its capability" for me?

**Comment by thiakil** [comment]
https://mcforge.readthedocs.io/en/latest/datastorage/capabilities/#exposing-a-capability

**Comment by gdegreen** [comment]
> https://mcforge.readthedocs.io/en/latest/datastorage/capabilities/#exposing-a-capability

Based off of what you're saying, does that imply this is an issue with create then, and not mekanism?

**Comment by thiakil** [comment]
It is a distinct possibility, yes
