### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by slimewing** [mekanism/Mekanism#7093]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When I summon a robit by command, my server and client are all crashed!

#### Steps to reproduce:
Summon a robot by command

#### Version (make sure you are on the latest version before reporting):
**Forge:*36.0.54* 
**Mekanism(include meka, mekg, mekt):*10.0.21.448* 
**Minecraft:*1.16.5* 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2021-04-10_15.19.24-client.txt](https://github.com/mekanism/Mekanism/files/6289436/crash-2021-04-10_15.19.24-client.txt)
[crash-2021-04-10_15.23.33-server.txt](https://github.com/mekanism/Mekanism/files/6289438/crash-2021-04-10_15.23.33-server.txt)

**Comment by thiakil** [comment]
we don't support "summoning" it, as you're not giving it the required owner and home position tags.
Use the item and place it on a charging pad, as designed.
