### ISSUE TITLE
mekanism issue with items entities deleting on server disconnect 

### ISSUE THREAD

**Issue by MajorMinority** [mekanism/Mekanism#7094]
hi all this is what im getting every time i place a mekanism item in game and disconnect from the server. then once i re connect the item is gone as is the error..  

0.04 16:07:20 [Server] Server thread/WARN [minecraft/TileEntity]: Block entity invalid: mekanism:ultimate_energy_cube @ BlockPos{x=-3660, y=64, z=-1117}

the complete log is below however this log i dont think contains this specific error but does contain many more associated with it
https://paste.shockbyte.com/ekoyijuteqozijomeqob

to replicate this 
1. insert mekanism item
2. disconnect from server
3. re connect to server
4. item gone.

version
forge 36.1.4
mekanism 1.16.5-10.0.21.448.jar
minecraft 1.16.5

**Comment by Seniorendi** [comment]
Please follow the issue tracker template

**Comment by pupnewfster** [comment]
What version of mekanism, forge and minecraft are you on, and can you please provide the entire log not just a snipet (and please don't just paste the contents of the log in a comment when you do so).

**Comment by MajorMinority** [comment]
> What version of mekanism, forge and minecraft are you on, and can you please provide the entire log not just a snipet (and please don't just paste the contents of the log in a comment when you do so).

this has been added now

**Comment by pupnewfster** [comment]
That does not appear to be a complete log as it starts in a middle of a stacktrace instead of with the server turning on. It is hard to tell from the log what is going on but it looks like AE2 might be making chunk loading fail.

**Comment by MajorMinority** [comment]
> That does not appear to be a complete log as it starts in a middle of a stacktrace instead of with the server turning on. It is hard to tell from the log what is going on but it looks like AE2 might be making chunk loading fail.

hey, im hoping this is a full log as requested. 
https://paste.shockbyte.com/okijonabonedovovajib

does this elaborate more as to whats going on, i have tried to replicate the issue direct as well from a server restart so its just the 1. server boot
2. add item
3. disconnect
4. reconnect
5. missing item

**Comment by pupnewfster** [comment]
Seems that it still isn't the full log, but if I was you I would:
a. Make a backup of your world
b. Try removing AE2
c. Try replicating this issue

Given from what little I can tell/surmise it seems that AE2 is causing chunk loading to at least partially fail.

**Comment by MajorMinority** [comment]
> Seems that it still isn't the full log, but if I was you I would:
> a. Make a backup of your world
> b. Try removing AE2
> c. Try replicating this issue
> 
> Given from what little I can tell/surmise it seems that AE2 is causing chunk loading to at least partially fail.

thats strange that as i shared the log direct from console after a clear and restarted the server ... unless im doing it wrong?

i will attempt this  mod removal now.

**Comment by MajorMinority** [comment]
thankyou for your help it seems you were right, but my question now is how can i without mc edit remove any and all blocks associated with ae2?

**Comment by pupnewfster** [comment]
No idea, going ahead and closing this though as it isn't an issue on our end, best bet is to ether ask AE2 for help/report the crash to them or look in some MC modding discord that you can probably find on google for help with removing blocks.
