### ISSUE TITLE
Teleporters Glitching and not working

### ISSUE THREAD

**Issue by Dave-lab-source** [mekanism/Mekanism#7098]
Im using Mekanism 1.12.2 With Galacticraft and all add-ons for 1.12.2. Whenever i activate a teleporter in the overworld, make a code all that stuff, and i repeat the same with a teleporter on the moon and connect it, it works. But then when i go back to the overworld, the teleporter behind me just shuts down, it has power, it has connection, it just completely shuts down. And i really dont know what to do with it

**Comment by pupnewfster** [comment]
Both teleporters need to be chunk loaded (such as with an anchor upgrade) which is the issue I think you are running into. I vaguely recall issues have also been reported that on server restart galacticraft dimensions don't actually load up initially and require going to said dimension manually to then have the chunks load again. That issue unfortunately even if we were still developing for 1.12 I don't think there would be anything we could do about.
