### ISSUE TITLE
Add a config for the gauge dropper to not be able to be used on creative tanks

### ISSUE THREAD

**Issue by EnabledEnzo** [mekanism/Mekanism#7100]
I help plan ideas for a mod pack and was wondering if its possible to add a config for the gauge dropper on being able to be used  on creative chemical/fluid tanks or not.

we have considered just black listing the item but we came to the conclusion its just too useful to blacklist.

**Comment by ShaleTheRock** [comment]
In my opinion, this would not make much sense because the creative tank is only obtainable via the creative inventory (unless you added a recipe for it of course).

- some random modded MC player

**Comment by thiakil** [comment]
But why don't you want it usable on the creative tank? You can just... use any other tank to get from the creative and use the dropper on that...

**Comment by EnzoBenzo1** [comment]
That is exactly the goal adding a recipe for one but the problem is once someone gets it they can just empty it and add anything else they wanted and that gas would become infinite.

**Comment by thiakil** [comment]
Er, have you actually tried that? The creative tank's contents should **never** decrease. It is not possible to empty it.

**Comment by EnzoBenzo1** [comment]
yeah tested before coming here

**Comment by pupnewfster** [comment]
It is actually fully intended to clear the creative tank's/chemical tank's contents. I am not fully against the idea of adding a config option for it other than I get the feeling like it may be a bit of a headache to implement.

**Comment by pupnewfster** [comment]
We discussed this some and the plan is for 10.1 to try and make it so that it only can be used to dump the contents of creative tanks when the player is in creative.

**Comment by djnugets** [comment]
that would work perfectly for what we are trying to do
