### ISSUE TITLE
Nutrition PASTE is a gas

### ISSUE THREAD

**Issue by CodingBenny** [mekanism/Mekanism#7102]
#### Issue description:
Nutrition paste should be im my opinion either a slurry or a fluid, but not a gas.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:1.16.4-10.0.19.446** 
**Other relevant version:Minecraft 1.16.5** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Slapping a 1.17 label on this to re-evaluate it but there is nothing that can be easily done about this before then due to backwards compat.
