### ISSUE TITLE
Alle Cabels over Elite are Broken.

### ISSUE THREAD

**Issue by Titan-EDV** [mekanism/Mekanism#7103]
#### Issue description:
All Cabels over the Elite (German language) are wasting 100% Energy. So if you place a full Energy Cube and 3 Cabels (over elite) then the cube will loose its energy at full speed.

#### Steps to reproduce:
1. Make the best cube
2. Make the best cabels
3. Connect 3 cabels and 1 cube and it will loose its energy till its empty

#### Version

**Mekanism:488** 
**Minecraft:1.16.5**
**Forge:Newest at the 04/13/2021**

**Comment by pupnewfster** [comment]
Are you sure the energy is not just going into the cables?

**Comment by Titan-EDV** [comment]
How could these cables use 100% of 40 Wind generators for 10 min...? I will test it more

Liebe Grüße

Justin Schmitt
Am 13. Apr. 2021, 14:46 +0200 schrieb Sara Freimer ***@***.***>:

**Comment by pupnewfster** [comment]
Not sure but it is probably worth right clicking the cables with a network reader to see what the stored levels are and some other stats.

**Comment by Titan-EDV** [comment]
I will definitely do. I will reach out tomorrow with the results.

(But how could 2 ultimate cubes don't fill 3 ultimate cabels with energy..)

Liebe Grüße

Justin Schmitt
Am 13. Apr. 2021, 17:25 +0200 schrieb Sara Freimer ***@***.***>:

**Comment by Titan-EDV** [comment]
Thanks for the Tip. The Cabels truely have a buffer, and it takes nearly 5 min to get full. Thanks!
