### ISSUE TITLE
Pressurized tube is not working very well

### ISSUE THREAD

**Issue by Guiefur** [mekanism/Mekanism#7109]
#### Issue description:
The pressurized tubes are not transporting gases to the machines. ( Sry for bad english ; w; )

#### Steps to reproduce:
1. The video has all the steps.

#### Version (make sure you are on the latest version before reporting):

**Forge: 36.1.0** 
**Mekanism: 10.0.21.448** 

#### If a (crash)log is relevant for this issue, link it here:

Vid link: https://youtu.be/Rz-LjFIPox0

**Comment by Robball14** [comment]
with a configurator, try setting the tube's end attached to the Output Quantum Entagloporter to "Pull"

**Comment by Guiefur** [comment]
> with a configurator, try setting the tube's end attached to the Output Quantum Entagloporter to "Pull"

It still doesn't work

**Comment by ShaleTheRock** [comment]
You can't transfer radioactive gasses though quantum entangloporters
