### ISSUE TITLE
Digi Miner disappears when mined with enchanted Netherite pick

### ISSUE THREAD

**Issue by davehaertel** [mekanism/Mekanism#7112]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
2 digiminers disappeared when I broke them using my Netherite pick.  The following enchants are on the pick:
Efficiency V
Soulbound
Fortune III
Mending
Excavate V

#### Steps to reproduce:
1. Mined with above mentioned pick.
2. Miner disappears
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.0.45
**Mekanism:** 10.0.21
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

First time happened in the mining dimension, so I thought that may have played a part, so I repeated in the overworld with the same result.  Another user built one and witnessed the same thing happened to a 3rd device.

**Comment by pupnewfster** [comment]
If I had to guess this has to do with the excavate enchantment probably being poorly implemented and thus not calling the correct methods on the blocks and not letting the miner know it was broken (this in theory would also have a silk touch excavate pick probably not drop ice if I remember which methods are which and where vanilla actually uses them). If I was you I would test if that is the case in a creative world and if so report the bug to whatever mod is adding the excavate enchantment.
