### ISSUE TITLE
A bug that can produce infinite gas.

### ISSUE THREAD

**Issue by ChanseiFu** [mekanism/Mekanism#7114]
![image](https://user-images.githubusercontent.com/79683281/115015925-f9782780-9ee6-11eb-8053-68ef3df575c9.png)
If you connect the gas tank to the pressurized pipe like this, and set the gas tank to the following figure.
![image](https://user-images.githubusercontent.com/79683281/115016122-3f34f000-9ee7-11eb-88f5-a6d1c061747d.png)
The place where the pipe is connected to the tank is set to "pull", while the inside of the pipe is set to purple（input/output）.Then an infinite amount of gas will be pumped out of the tank.And will not consume the amount of gas in the tank.

**Comment by ChanseiFu** [comment]
This is the latest MEK10,  1.16.5

**Comment by Seniorendi** [comment]
Are you sure the pipe is filled?
The pipe can be colored without any gas in it.

**Comment by Seniorendi** [comment]
https://cloud.srendi.de/index.php/s/t8cJmMLZe6Mef2s
I made a video. I can't reproduce that.
The pipe is always empty.

**Comment by Robball14** [comment]
the bug has been confirmed on discord by sagesse-cn#3230 and Shark#9926

video made by sagesse:
https://user-images.githubusercontent.com/54327191/115031912-fff7a680-9ec8-11eb-8562-3c9e58616aa0.mp4

**Comment by ChanseiFu** [comment]
> https://cloud.srendi.de/index.php/s/t8cJmMLZe6Mef2s
> I made a video. I can't reproduce that.
> The pipe is always empty.

You need to fill the gas tank first (with any kind of gas), and then connect it to the ultimate pressure pipe.

**Comment by Seniorendi** [comment]
Ah, well

**Comment by ChanseiFu** [comment]
https://user-images.githubusercontent.com/79683281/115044160-d14cf080-9f07-11eb-8057-fe13348cb0c3.mp4
I made a video and installed WailaHarvestability (a mod), so we could see the gas changes clearly.

**Comment by ChanseiFu** [comment]
https://user-images.githubusercontent.com/79683281/115044160-d14cf080-9f07-11eb-8057-fe13348cb0c3.mp4
I made a video and installed WailaHarvestability (a mod), so we could see the gas changes clearly.

**Comment by Seniorendi** [comment]
Well, now I have a source for my fissile fuel <:

**Comment by ChanseiFu** [comment]
> Well, now I have a source for my fissile fuel <:
All you have to do is build an industrial turbine big enough, and put ten gas tanks filled with steam, and you'll have unlimited electricity.XD

**Comment by Bauws** [comment]
I can confirm that bug still exist. Im currently playing Enigmatica 2 Expert Skyblock (newest version that is available at this time) and ran into the bug on accident. You dont even need to set it on pull. Simply fill a gas tank with any gas to its limit and then put the front to output and the top to input. Voila you got an infinite gas source.

**Comment by Bauws** [comment]
I am currently playing enigmatica 2 expert skyblock and ran into the bug aswell. I can break it down to the pressurized tube. I have  an advanced generator which is getting hydrogen from an electrolytic seperator. Once everything is filled up on max i can simply break the ES and leave the tube alone. It will never run out of hydrogen.
