### ISSUE TITLE
Industrial Turbine not forming

### ISSUE THREAD

**Issue by mmanaolana** [mekanism/Mekanism#7115]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Hi, this is my first time posting on a Github so I'm sorry if this is wrong. I asked for help on r/feedthebeast but nothing has been working. I'm trying to build an industrial turbine but it's not forming. Photos below. I've built multiple different versions following YouTube tutorials, the FTB wiki, nothing is working. There have been no crashes associated with it, it's just not forming. Thanks for any help.

https://www.reddit.com/r/feedthebeast/comments/mruba2/mekanism_turbine_not_forming_any_help_would_be/
Here is the Reddit post so attempted fixes can be seen.

#### Version:
**Forge:** 36.1.3
**Mekanism:** Newest version, 1.16.5-10.0.21.448
**Other relevant version:** 

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]
![2021-04-15_21 51 37](https://user-images.githubusercontent.com/82677204/115073368-da18d480-9ebd-11eb-8ffe-807a8cc34ebd.png)
![2021-04-15_21 51 29](https://user-images.githubusercontent.com/82677204/115073370-dab16b00-9ebd-11eb-96c0-b2986c38252f.png)
![2021-04-15_21 51 01](https://user-images.githubusercontent.com/82677204/115073371-db4a0180-9ebd-11eb-80fd-4c880a44b021.png)

**Comment by toddlersizedsharkcage** [comment]
Right click with a configurator and see if there's a message telling you what's wrong.  I would recommend joining on Discord for assistance: https://discord.gg/nmSjMGc

**Comment by mmanaolana** [comment]
Nothing comes up, and I tried all the different settings on the configurator. I'll jump in the Discord, thanks!

**Comment by pupnewfster** [comment]
Solved on discord (for anyone looking at this in the future the issue was having vents inside the turbine instead of just on the sides)
