### ISSUE TITLE
No config option for electrolytic separator

### ISSUE THREAD

**Issue by Seniorendi** [mekanism/Mekanism#7119]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*
*Yes I did that 😉*

#### Issue description:
There is no configuration option for the electrolytic separator. 
The full config: https://paste.myst.rs/byn7xpeq
I also tried to search the config option with my text editor.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.4
**Mekanism:** 10.0.21
**Other relevant version:** ATM 6 - To the sky 1.0.7

**Comment by pupnewfster** [comment]
`general.toml` -> `general.energy_conversion.HydrogenEnergyDensity`
