### ISSUE TITLE
Cannot rotate teleporter

### ISSUE THREAD

**Issue by Mlodko** [mekanism/Mekanism#7122]
The teleporter should have an option to specify what direction the teleported player should be facing, either through how you place it, the configurator or a new internal component to its UI

Forge - 1.16.5/36.1.4
Mekanism - 10.0.21

**Comment by Robball14** [comment]
place a block in front of the teleporter on the direction you don't want to face

**Comment by Mlodko** [comment]
Oooh, thanks, I couldn't find it anywhere and reddit said that you can't do it either, closing the issue
