### ISSUE TITLE
Version 1.16.5 problème vanne dynamique et vanne d'évaporation thermique.

### ISSUE THREAD

**Issue by Morve74** [mekanism/Mekanism#7123]
Bonjour je sais pas si je suis au bon endroit, mais je vais quand même décrire le problème que je rencontre, une fois le dynamique tank construit, il se rempli parfaite avec tout type de liquide et gaz  mais lorsque je veux exporter de l'eau, pour exemple, les tuyaux mécaniques n'exporte rien, les tuyaux ou tubes indique de l'air, la même chose se produit avec les deux vanne du coup sa bloque vite le jeux pour certain élément, à moins que je sois très con ^^ et dans se cas je suis preneur de tout aide merci pour ceux qui s'amuseront a lire sa 

![2021-04-21_22 14 58](https://user-images.githubusercontent.com/82973497/115615425-3e3cfd80-a2ef-11eb-88f1-2f35db6a1b79.png)
![2021-04-21_22 15 10](https://user-images.githubusercontent.com/82973497/115615493-53b22780-a2ef-11eb-860a-2ae5b3555b1e.png)
![2021-04-21_22 15 16](https://user-images.githubusercontent.com/82973497/115615518-5ca2f900-a2ef-11eb-8e24-4ebed596423f.png)
![2021-04-21_22 15 42](https://user-images.githubusercontent.com/82973497/115615544-64629d80-a2ef-11eb-92d2-ce4759c16f44.png)

**Comment by pupnewfster** [comment]
Neither dynamic tanks nor evaporation towers have the ability to auto eject. You need to set the pipe to pull by right clicking with a configurator on the small piece of the pipe that is connecting to the valve.

**Comment by Morve74** [comment]
je ne vois pas que quel petite pièce vous parlez surtout que l'eau se stock bien donc le tuyau le tuyau brancher sa devrais fonctionner car je ne peut pas faire de clique droit sur le tuyau sa ne fait rien et le tuyau se connecte directement

**Comment by pupnewfster** [comment]
![image](https://user-images.githubusercontent.com/1203288/115617904-f9e63900-a2bf-11eb-83ab-2bf090256c58.png)
This part, also I am sorry, I meant sneak right click not just right click.

**Comment by Morve74** [comment]
il ne se passe absolument rien, pour moi shift click, droit click, j'avais déjà essayé avant mais rien ne s'ouvre

**Comment by Burgerguys** [comment]
There is no screen that opens up or GUI that appears. you need to shift right click on that section of the pipe with an item called a "configurator". it looks like a little wand and allows you to change the mode of the end of the pipe, push or pull. Then simply follow the instructions Pupnewfster and has already provided.

this is what the configurator looks like
![image](https://user-images.githubusercontent.com/77478620/115620491-3bc4ae80-a2c3-11eb-8514-17673efa0fbb.png)

additionally this wiki page may be helpful.

https://wiki.aidancbrady.com/wiki/Configurator

**Comment by Morve74** [comment]
wouaaah fallait le savoir j'étais passé à côté de cette outil un grand merci a toi pour ton temps et ta rapidité a me répondre, tu m'as grandement aidé et je sais pas si tu es ou fais parti du/des développeur mais votre modd c'est de la tuerie
