### ISSUE TITLE
Atomic disassembler can't change mode

### ISSUE THREAD

**Issue by Lukeskyf** [mekanism/Mekanism#7129]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Hello everyone,

I know this issue has been treated many times, but I can't find a solution for my specific problem.
It's simple : I can't change my atomic disassembler mode as usual by crouch+right click (I've rebind my crouch which is on 'c').
I've tried a lot of different combination of keys : LeftShift+right click, left shift+crouch+right click, left shift+m, ctrl+right click, left shift+left click, left shift+mouse wheel click, shift+ctrl+right click, etc...
I've reseted all mekanism controls but still don't works.
I thought it was a conflict with MouseTweaks, but it isn't.

I've done a huge session on an old version of the mod (for minecraft 1.15.2) and I never had this issue.

I'm on a custom modpack that I made myself, inspired by Enigmatica6, that contains 170mods.

Thanks for your help
Lukeskyf

#### Version (make sure you are on the latest version before reporting):
**Forge:*36.1.2* 
**Mekanism:*10.0.21* 
**Other relevant version:*KubeJS Mekanism 1604.1.1.6* 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by Oct0bass** [comment]
Press N

**Comment by pupnewfster** [comment]
The atomic disassembler no longer changes modes with right click/sneak right click or whatever it was. It now makes use of the item mode switch and also supports the shift + scroll wheel that the configurator supports for changing modes.

**Comment by Lukeskyf** [comment]
Thank you all

**Comment by pupnewfster** [comment]
Yes config/Mekanism/client.toml should have an option to disable scrolling changing modes

**Comment by SnowBerryZ** [comment]
Thanks you so much, lol .. I have search this on all Server Configs and not of the Clientside ...
