### ISSUE TITLE
no wind for the wind generator 

### ISSUE THREAD

**Issue by Akerutari** [mekanism/Mekanism#7136]
#### Version
**Forge:** 14.23.5.2847
**Mekanism:** MekanismGenerators-1.12.2-9.8.3.390
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

![Capture d’écran (2)](https://user-images.githubusercontent.com/83316975/116322852-dffa9980-a78a-11eb-9cc1-c8434fa19805.png)

**Comment by Akerutari** [comment]
i need some help to repair this de generator is on y 61

**Comment by pupnewfster** [comment]
It needs clear access of the sky

**Comment by Akerutari** [comment]
he have nothing up the generator and at y 240 did the same thing

**Comment by pupnewfster** [comment]
Hmm what dimension is the wind generator in? I think the only other case that message may show up is if the dimension is blacklisted in the config.

**Comment by Akerutari** [comment]
normal world and qhat config do you talk?

**Comment by pupnewfster** [comment]
config/Mekanism.cfg and something about wind generator blacklist I forget the exact naming

**Comment by Akerutari** [comment]
i dont have the mekanism.cfg

**Comment by Seniorendi** [comment]
Are you sure? 
The file is located here: `*MINECRAFTFOLDER*/config/mekanism/Mekanism.cfg`
The minecraft folder is not the .minecraft folder if you use a launcher.

**Comment by pupnewfster** [comment]
I am pretty sure in 1.12 the only file inside the mekanism subfolder was for cardboard box configs and the main config was in the main config folder.

**Comment by Seniorendi** [comment]
Ahh yes. I didn't see that he use 1.12.

**Comment by Akerutari** [comment]
what config i do change in the mekanism.cfg
