### ISSUE TITLE
First-time Mekanism User. Can't figure out Metallurgic Infuser.

### ISSUE THREAD

**Issue by Phosphonothioic** [mekanism/Mekanism#7137]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
So, I built a Metallurgic Infuser. It's sitting atop a cobblestone block. I placed coal in the yellow slot until the reserve was full (1000 mB). I put an Iron Ingot in the red slot, but nothing happens. According to JEI, I should be getting Enriched Iron Dust. What am I missing?

#### Version (make sure you are on the latest version before reporting):
**Forge: 36.1.4
**Mekanism: 10.0.21
**Minecraft: 1.16.5 

[https://ibb.co/94H8VrV](url) <-- Screenshot of Metallurgic Infuser

**Comment by pupnewfster** [comment]
Some form of energy, be it through one of the generators in Mekanism generators like the heat generator or via some other mod in your modpack

**Comment by Phosphonothioic** [comment]
Ok, I'm confused. I was trying to use the Infuser to get work up to the basic cable to connect my heat generators to the Metallurgic Infuser. The basic cables require steel ingots, which I don't think I can get without the Infuser. So, am I missing a step or another pathway.

Mekanism is the only engineering mod I have, so only the power sources included in that mod are available to me.
