### ISSUE TITLE
Patterns lost when transporting refined storage and extra storage crafters with cardboard box

### ISSUE THREAD

**Issue by Publius2** [mekanism/Mekanism#7139]
version 1.16.5-10.0.21.445
playing as part of the Direwolf20 1.16 modpack version 1.9.0
transporting crafters with cardboard box in the hopes that It would save me the trouble of having to replace all my recipes after moving them. after unpacking crafter is empty. remains empty after relog and if the block is destroyed recipes don't drop so I don't think its a desync issue. 

I'm new to the world of modded so I appologize If I formatted this wrong

**Comment by pupnewfster** [comment]
Sounds like they don't write all their tile's data to NBT, which either they should or they should add it to one of the forge blacklist tags we look at so that it can't be picked up so this probably should be reported to them.

**Comment by Publius2** [comment]
ok will do thank you
