### ISSUE TITLE
Advanced Rocketry crash with mechanical pipes

### ISSUE THREAD

**Issue by Seniorendi** [mekanism/Mekanism#7141]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Connect a mechanical pipe to an Advanced Rocketry fluid input hatch and the Server crashed.

#### Steps to reproduce:
1. Place fluid hatch
2. Place Mechanical Pipe
3. Crashy Crashy

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.13
**Mekanism:** 10.0.21
**Other relevant version:** Advanced Rocketry 2.0.0-10

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

Stacktrace https://gist.github.com/Seniorendi/7e9bbd11e75b4a558ffa3bde841c11ff

Should i report this at advanced rocketry?

**Comment by pupnewfster** [comment]
You probably should report it to them given I am pretty sure (at a very brief glance) the only way that could happen is if the fluid handler they provide is `null`, though I may try to take a bit longer of a check at their end of stuff later.

**Comment by Seniorendi** [comment]
Kay 👍🏻

**Comment by pupnewfster** [comment]
Closing this for now given it seems they are using nulls in places they shouldn't be. If it still happens after they fix those, just comment here and I can reopen this.

**Comment by Seniorendi** [comment]
Yep. Advanced rocketry is buggy, even my game crashes when we want to use rockets.
But thank you, that you're always so kind
