### ISSUE TITLE
quantum Entangloporter not connecting

### ISSUE THREAD

**Issue by Logics2996** [mekanism/Mekanism#7142]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
so i have the quantum Entangloporter setup like this but the pipe is not connecting to it and there is no channel set in the GUI, iv tried everything at this point and nothing is working
![quantum 1](https://user-images.githubusercontent.com/83439271/116642139-12acb980-a966-11eb-8926-fe34eba4131d.png)
![quantum 2](https://user-images.githubusercontent.com/83439271/116642144-14767d00-a966-11eb-8d44-42bd71fac167.png)
![quantum 3](https://user-images.githubusercontent.com/83439271/116642145-150f1380-a966-11eb-9bb8-9929215a10ad.png)
![quantum 4](https://user-images.githubusercontent.com/83439271/116642146-150f1380-a966-11eb-81b8-148f90fcf8e6.png)

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Set a frequency

**Comment by Logics2996** [comment]
how do i do that?

**Comment by pupnewfster** [comment]
Type a name in the box next to set and hit set.

**Comment by Logics2996** [comment]
thank you, im dumb lmao, i was trying to connect before setting it up
