### ISSUE TITLE
Some text overflow on other langage

### ISSUE THREAD

**Issue by AlexHgC** [mekanism/Mekanism#7145]
I create this thread for grouping all the text overflow i find instead of open a lot of issues. I will use french as example, but i think this appears on some other languages.

I will add comments if i run into more, you can delete screen and comment when it's done.

Here is all i have found for now :

- [x] Gas Burning Generator ( inventory/rate )
- [x] QIO Dashboard + portable ( search )
- [x] QIO Dashboard + portable ( height )
- [x] Set QIO Frequency 
- [x] Can't Eject windows
- [x] All eject on/off windows
- [x] Digital Miner Config
- [x] Delete frequency windows
- [x] Auto sort button
- [x] Laser Amplifier
- [x] Upgrade Window
- [x] Transporter Config
- [x] New filter window
- [ ] Security Desk owner + "Add" translation illegible
- [x] Infusion Types face configuration
- [x] QIO Crafting Windows

**Comment by AlexHgC** [comment]
Here are the screens : 

**Gas Burning Generator ( inventory/rate ) :**

![Capture d’écran 2021-04-30 161513](https://user-images.githubusercontent.com/31996023/116711223-ed09c980-a9d2-11eb-9535-5f13c67d6d71.png)

**QIO Dashboard + portable ( search/height ):**
![Capture d’écran 2021-04-30 161314](https://user-images.githubusercontent.com/31996023/116711312-06127a80-a9d3-11eb-9d61-36023cc92653.png)


**Set QIO Frequency:**
![Capture d’écran 2021-04-30 161214](https://user-images.githubusercontent.com/31996023/116711282-fdba3f80-a9d2-11eb-8018-d908b475bcb1.png)

**Can't Eject windows:*
![Capture d’écran 2021-04-30 162944](https://user-images.githubusercontent.com/31996023/116711367-0f9be280-a9d3-11eb-9733-266f9c03c7de.png)

**All eject on/off windows:**
![Capture d’écran 2021-04-30 163103](https://user-images.githubusercontent.com/31996023/116711385-162a5a00-a9d3-11eb-95b7-ab24cd380628.png)

**Comment by AlexHgC** [comment]
**Digital Miner config:**
![Capture d’écran 2021-04-30 221823](https://user-images.githubusercontent.com/31996023/116750058-2ad21680-aa02-11eb-8a70-1f760d69fef0.png)
![Capture d’écran 2021-04-30 221849](https://user-images.githubusercontent.com/31996023/116750067-2dcd0700-aa02-11eb-8c8f-7ceaa3377108.png)

**Comment by AlexHgC** [comment]
**Delete frequency windows :**

![image](https://user-images.githubusercontent.com/31996023/116784560-2e62ad80-aa95-11eb-9671-4e546e47d4d2.png)

**Comment by AlexHgC** [comment]
**QIO Crafting Windows**

![image](https://user-images.githubusercontent.com/31996023/140612502-593450d9-ca43-4d08-be5f-2d72cf8d2ae9.png)

**Comment by pupnewfster** [comment]
Closing this as fixed, if you want you can open a new issue for the too small to read text one that is left, but given it is sort of the opposite issue as this I don't think it makes sense to leave this open to track it.
