### ISSUE TITLE
ME System Automation

### ISSUE THREAD

**Issue by Logics2996** [mekanism/Mekanism#7147]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

so i am trying to import smelted items from my smelting factory (mod=Mekanism) to my Me System, have it configured to output items on the side i need it to and i have an export bus going from the smelting factory to my ME system i have also tried the Me interface but thats not working either, i dont know if its me or if the mods are being weird with each other
![1](https://user-images.githubusercontent.com/83439271/116752511-96fe4b80-a9fd-11eb-968a-777ec21512c7.png)
![Uploading 2.png…]()

**Comment by pupnewfster** [comment]
Have you tried an ME import bus? It has been quite a while since I last played/used AE2 but if memory serves import bus -> importing into the ME system, export bus -> exporting out of the ME system
