### ISSUE TITLE
Thermoelectric boiler and turbine not connecting

### ISSUE THREAD

**Issue by Logics2996** [mekanism/Mekanism#7148]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

so im trying to use a thermoelectric boiler for steam for my turbine, both of them are working but the boiler will not connect to my turbine to input the steam

![1](https://user-images.githubusercontent.com/83439271/116766350-eeaeae00-aa21-11eb-8dae-074e4f36390f.png)
![2](https://user-images.githubusercontent.com/83439271/116766352-efdfdb00-aa21-11eb-8606-78699581c1df.png)
![3](https://user-images.githubusercontent.com/83439271/116766354-f0787180-aa21-11eb-95bb-7eea823da14c.png)

**Comment by pupnewfster** [comment]
Steam needs to be transferred using pressurized tubes. You also need to set the boiler port to output steam or whatever it is using a configurator

**Comment by Logics2996** [comment]
iv done that, they are now connected but the turbine is still not powering up

**Comment by Logics2996** [comment]
![Uploading 4.png…]()

**Comment by Logics2996** [comment]
![5](https://user-images.githubusercontent.com/83439271/116767090-ce80ee00-aa25-11eb-944a-920163e88a66.png)

**Comment by toddlersizedsharkcage** [comment]
https://discord.gg/nmSjMGc

You'll get better support on the discord server in this case. Interactive support would benefit you here.

**Comment by pupnewfster** [comment]
> You also need to set the boiler port to output steam or whatever it is using a configurator
