### ISSUE TITLE
Ethylene Extraction Into Pressurized Reaction Chamber with Oxygen

### ISSUE THREAD

**Issue by ImKruzik** [mekanism/Mekanism#7149]
Not really sure how to extract the ethylene into the PRC with oxygen once you have the production going to make the HDPE pellets. I headed over to Creative and replicated everything and tried different ways of pulling liquid/gases out of a unit and nothing would just work... If you guys don't mind helping me I appreciate it not sure if it's bugged or i'm just not understanding the concept to the fullest.

**Comment by pupnewfster** [comment]
You might get a bit better back and forth help on our discord (https://discord.gg/nmSjMGc) but I am a bit confused what your current issue is (so I am listing a few potential understandings and their rough answers):
Are you trying to remove the things from the input? (If so you need to use a gauge dropper or something)
Are you trying to get both oxygen and ethylene in it? (If memory serves it needs to be liquid ethelyne which means that you need to run it through a rotary condensentrator first)
Do you have them in and it just isn't running? (Best guess you have a bunch of speed upgrades and no energy so per tick energy cost is higher than energy buffer)
