### ISSUE TITLE
Mekanism Fluid Tooltip display error When show all recipes

### ISSUE THREAD

**Issue by sagesse-cn** [mekanism/Mekanism#7152]
![image](https://user-images.githubusercontent.com/6903353/116817740-79b2b400-ab9a-11eb-9ea2-fabd3cc119d3.png)

#### Steps to reproduce:
Click Any Using Fluid Mekanism Machine `show all recipes` button.

#### Version:
**Forge:** Minecraft 1.16.5/Forge 36.14
**Mekanism:** Mekanism 10.0.21 
**JEI:** JEI 7.6.1.75

**Comment by AlexHgC** [comment]
Try updating your JEI, you have "old" version, and you can see that on the .76 : 
![image](https://user-images.githubusercontent.com/31996023/116818888-e6fc2000-ab6d-11eb-8213-48120cdf14d9.png)

**Comment by pupnewfster** [comment]
This is on @CyanideX 's end (assuming that he hasn't released a new version still of his unity dark resourcepack), basically it is overriding lang entries with ones that don't work properly.
