### ISSUE TITLE
Add a factory version of Nutritional Liquifier

### ISSUE THREAD

**Issue by ianlavr** [mekanism/Mekanism#7155]
Add a factory version of Nutritional Liquifier. The factory version would be useful for industrial food production and increasing up Nutritional Paste production rates.

**Comment by Seniorendi** [comment]
I do not think that you need that much paste

**Comment by ianlavr** [comment]
Ok. Thanks for responding

**Comment by pupnewfster** [comment]
Nutritional liquifiers don't really make sense as a factory as there is only one output type.
