### ISSUE TITLE
Server crash before launch Chroma Technology

### ISSUE THREAD

**Issue by gugnyr** [mekanism/Mekanism#7157]
Issue description:

Hi, I currently have a minecraft server, I'm usign the modpack Chroma Technology on Minecraft 1.12 and when I try to start server I get an error linked below "Crash log" from my personnal investigation it seems to come from chunck loader upgrade from Mekanism but I didn't found any issue and I'm not sure for this.
I already disabled the "AllowChunkloading" option in mekanism.cfg but it fix nothing.
Did you guys have any issue for that ?

Version:
Mekanism: 1.12.2-9.8.3.390 
Modpack : Chroma Technology 1.14.3 
Minecraft : 1.12

Crash log : https://pastebin.com/qFiX5QS9

Thanks in advance,

**Comment by AlexHgC** [comment]
![image](https://user-images.githubusercontent.com/31996023/117025179-f9579480-acfa-11eb-8357-b8c37cba2277.png)
It seems to be a problem with MDECore, all other mods are loaded correctly. Idk why it's named minecraft.jar, delete it on your mods folder and download the real version here : https://www.curseforge.com/minecraft/mc-mods/mattdahepic-core/download/3118780

**Comment by gugnyr** [comment]
I haven't minecraft.jar on mods folder. 
![image](https://user-images.githubusercontent.com/83656902/117026855-6ae41280-acfc-11eb-8840-83003cc687f3.png)

**Comment by gugnyr** [comment]
I delete this mdecore and downladed a new one and replace.
I didn't know why but now the server start and when I connect the server go down and close.....
https://pastebin.com/1DkJPhcC

And on at end of log I got it :
https://pastebin.com/3C4gcbCv
Maybe it can help to find any issue.

**Comment by thiakil** [comment]
Looks like some mod is causing the chunk to not be loaded at that point, which I don't think I've seen anyone else have issue with.

Since we're no longer supporting 1.12 unfortunately there's not much we can do.
