### ISSUE TITLE
Logistical transporters can't have their redstone sensitivity changed

### ISSUE THREAD

**Issue by dan3401** [mekanism/Mekanism#7158]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Not possible to change Redstone sensitivity on logistical transporters, right-clicking only says the colour

#### Steps to reproduce:
1. Get a logistical transporter and a configurator
2. right-click to change the sensitivity 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.0
**Mekanism:** 1.16.5-10.0.21.448
**Other relevant version:** only using mekanism

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Use a diversion transporter, they let you configure the redstone sensitivity each of the six sides of them separately.

**Comment by ruattd** [comment]
but the diversion transporter is tooooooooo slow, how to make it faster without other mods?
