### ISSUE TITLE
Fuel and Waste integration with CC is returning the wrong values.

### ISSUE THREAD

**Issue by folke13** [mekanism/Mekanism#7160]
#### Issue description:
When using the getFuelCapacity() I instead get the percentage the reactor is filled with.
When using getWasteCapacity() I always get 0 even though the reactor is empty of waste.

#### Steps to reproduce:
1. wrap the reactor and call the said methods on them.

#### Version (make sure you are on the latest version before reporting):
**Forge: 36.1.4** 
**Mekanism: 10.0.21 (.448 if i remember correctly)** 
**Other relevant version: latest CC version** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Are you sure you are on 10.0.21.448? As our CC integration isn't out yet (it is coming in 10.1, which still builds as 10.0.21, but by default be building as 10.0.21.homebaked).

**Comment by folke13** [comment]
Oh yes, it's called homebaked. I remembered the wrong version.
