### ISSUE TITLE
turbine not formaing 

### ISSUE THREAD

**Issue by RaidingBandit** [mekanism/Mekanism#7161]
![2021-05-05_13 38 08](https://user-images.githubusercontent.com/35550245/117206703-08485080-ada8-11eb-823a-475687c401f8.png)
![2021-05-05_13 38 25](https://user-images.githubusercontent.com/35550245/117206706-09797d80-ada8-11eb-8c25-bd4231699289.png)
when i build turbines any bigger thaan 5x5 they do not form iv checked god knows how many times that there even ect any help would be great 
![2021-05-05_08 50 20](https://user-images.githubusercontent.com/35550245/117206953-4a719200-ada8-11eb-97f7-5903da435493.png)
![2021-05-05_13 37 31](https://user-images.githubusercontent.com/35550245/117206956-4b0a2880-ada8-11eb-8168-0e6fafd628c1.png)
![2021-05-05_13 37 39](https://user-images.githubusercontent.com/35550245/117206962-4c3b5580-ada8-11eb-893d-ba88bd8c759a.png)
![2021-05-05_13 37 45](https://user-images.githubusercontent.com/35550245/117206964-4cd3ec00-ada8-11eb-8879-0a8f943f3ed1.png)
![2021-05-05_13 37 50](https://user-images.githubusercontent.com/35550245/117206969-4d6c8280-ada8-11eb-80bb-157888c110b5.png) the center coil has one ontop just showing in the pic that the bottom one is touching the top of the complex block

**Comment by AlexHgC** [comment]
Your turbine have 19 width, 17 is max

**Comment by RaidingBandit** [comment]
iv tried 17 before

**Comment by RaidingBandit** [comment]
> 
> 
> Your turbine have 19 width, 17 is max

iv tried 17 10 ect

**Comment by AlexHgC** [comment]
Your turbine is badly build, it's not a bug with mekanism. Join the discord for better help on the #help-desk : https://discord.gg/nmSjMGc

**Comment by RaidingBandit** [comment]
> 
> 
> Your turbine is badly build, it's not a bug with mekanism. Join the discord for better help on the #help-desk : https://discord.gg/nmSjMGc

im gonna edit it now and show u

**Comment by AlexHgC** [comment]
Show me the message when you right click on turbine with configurator

**Comment by RaidingBandit** [comment]
> 
> 
> Show me the message when you right click on turbine with configurator

it dosnt show anything


> 
> 
> Show me the message when you right click on turbine with configurator

![2021-05-05_14 12 31](https://user-images.githubusercontent.com/35550245/117209987-f8cb0680-adab-11eb-8dee-33b4d58ab6e7.png)

**Comment by RaidingBandit** [comment]
wtill dont work

**Comment by pupnewfster** [comment]
Assuming I can count correctly which is very hard with that picture your turbine is 14x15 they have to be a square in x, z not a rectangle and odd.

**Comment by AlexHgC** [comment]
Your turbine seems to be 15x14 and not 15x15.. and you need to right click with an configurator, not with your hand

**Comment by RaidingBandit** [comment]
> 
> 
> Your turbine seems to be 15x14 and not 15x15.. and you need to right click with an configurator, not with your hand

nvm thxs for the help got it now lol i cant count lol
