### ISSUE TITLE
Fission reactor waste disappearing once pumped out

### ISSUE THREAD

**Issue by ThatTonybo** [mekanism/Mekanism#7163]
#### Issue description:
Any time I try to pump waste from my Fission reactor using ultimate pressurized tubes into a tank or into a PRC, it disappears

#### Steps to reproduce:
1. Set up a normal Fission setup (water cooled, 5x7x5 reactor, 5x9x5 turbine)
2. Wait until waste builds up in the reactor
3. Try to pump it out into a tank or PRC

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.0
**Mekanism:** 10.0.21
**Other relevant version:** Minecraft 1.16.5

#### If a (crash)log is relevant for this issue, link it here:
No crash

**Comment by pupnewfster** [comment]
Right click the tubes with a network reader are you sure it isn't just in them?

**Comment by ThatTonybo** [comment]
Okay so, I worked out that it has to go into a Solar activator. But same issue applies pumping Polonium out. Network reader says its coming out and staying in buffer, but the tank won't fill otherwise.
![image](https://user-images.githubusercontent.com/28176227/117236770-bfa69b00-ae6c-11eb-8a45-20d25892e600.png)

**Comment by pupnewfster** [comment]
You can't store radioactive materials in chemical tanks only in waste barrels (polonium/plutonium won't decay in them)

**Comment by ThatTonybo** [comment]
Oh, I understand. So they act as the chemical tank for radioactive materials and can then pump into PRCs?

**Comment by toddlersizedsharkcage** [comment]
You should probably just process polonium or plutonium as needed and then put the spent waste into the barrels, but you can also store radioactive materials in barrels and extract from them if needed. You should join the discord server since you'll likely have more questions.

**Comment by ThatTonybo** [comment]
Thanks. Joined in, will direct further questions there.
