### ISSUE TITLE
MekaSuit Colors

### ISSUE THREAD

**Issue by DDR2001** [mekanism/Mekanism#7165]
Since the MekaSuit reminded me of the armor found the Halo games I was saddened to see there was no way to customize the colors of them.
So I was thinking maybe make an RGB Unit for each piece of the MekaSuit that would let you change the color of the white part on the armor or even the colored lights.  Maybe the RGB Unit could also work on the Meka-Tool?

**Comment by Robball14** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/72
