### ISSUE TITLE
Cable crash

### ISSUE THREAD

**Issue by Peca21** [mekanism/Mekanism#7166]
#### Issue description:
I was far away from my base in a stronghold when my game crashed. Crash says mekanism cable crashed the game which is loaded at home by ChickenChunks Chunk loader. I was also auto-mapping with JourneyMap when game carshed.

#### Steps to reproduce:
1. I have no idea

#### Version (make sure you are on the latest version before reporting):
**Forge:**  : 36.1.16
**Mekanism:** : Mekanism-1.16.5-10.0.21.448
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[pastebin](https://pastebin.com/NjLVQ3CD)

**Comment by AlexHgC** [comment]
Caused by performant i think, this mod totally break some mods, including mekanism, and you have perfomant error everywhere in your logs : 
![image](https://user-images.githubusercontent.com/31996023/117491969-4349b000-af71-11eb-81e9-b806a2195e28.png)

**Comment by Peca21** [comment]
OK, I will disable it

**Comment by Peca21** [comment]
Yea it was performant
