### ISSUE TITLE
Transfer Rate Quantum Entangloporter

### ISSUE THREAD

**Issue by TheFallen00** [mekanism/Mekanism#7170]
#### Issue description:
I'm triyng to use the quantum entangloporter to transfer the steam produced from the fission reactor to the turbine but it transfer just 1024 mb/t. There is a way for make the transfer rate limitless or something like that?
Thanks

#### Steps to reproduce:
1. Attach the quantum entangloporter to the coolant output and then set the gas to all input
2. Attach the other one to the input of the turbine and then set the gas to all output and "auto-eject: on"

**Forge:36.1.2** 
**Mekanism:1.16.5-10.0.21.448**

**Comment by Seniorendi** [comment]
There is a configuration located `config/Mekanism`. I do not know, which file it's. But searching it is not hard

**Comment by TheFallen00** [comment]
I've triyed for maybe half hour, now i'll search better. Thank you

**Comment by pupnewfster** [comment]
The entangloporter currently uses the generic auto eject rate limits set in the config (I believe config/Mekanism/general.toml), which defaults to 1,024 mB/t. This is something I am planning on adjusting in 10.1 to potentially remove the auto eject limit from the entangloporter.

**Comment by TheFallen00** [comment]
But in the config/Mekanisn there is no general.toml... there are just client.toml and tools-client.toml and i've searched in both of them and didn't find anything

**Comment by TheFallen00** [comment]
ahhh ok, now i've found the file you was talking about. Thank you! Just for now, in there can I change alse the max range of the digital miner?

**Comment by pupnewfster** [comment]
You can't really unless you change the ratios of the recipe.

**Comment by pupnewfster** [comment]
There is no config and please stop just asking question after question here... the issue tracker is not the place for that use discord.
