### ISSUE TITLE
Some GUI elements do not use gui_objects colormap

### ISSUE THREAD

**Issue by koolboat** [mekanism/Mekanism#7171]
#### Issue description:
Some GUI elements do not use the gui_objects colormap, which leads to some elements not matching with others if a resource pack changes it. This can be seen on the induction matrix, boiler, fission reactor, fusion reactor, and industrial turbine.
![image](https://user-images.githubusercontent.com/61613274/117563751-956ffb80-b06d-11eb-8552-3f6e4ca3dfd6.png)
![image](https://user-images.githubusercontent.com/61613274/117563760-9ef96380-b06d-11eb-88f3-0d250fdc8bc1.png)

#### Steps to reproduce:
1. Install a resource pack which modifies the gui_objects colormap (e.g. Unity: Dark Edition)
2. Right click on one of the structures mentioned above

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.0
**Mekanism:** Mekanism-1.16.5-10.0.21.448
MekanismGenerators-1.16.5-10.0.21.448

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism/blob/1.16.x/src/generators/resources/assets/mekanismgenerators/textures/colormap/gui_objects.png

**Comment by koolboat** [comment]
After editing the colormap you provided and putting it into a resource pack with only the colormaps for both mods, the issue is still there on the stats button background
![image](https://user-images.githubusercontent.com/61613274/117585508-65aa0d80-b0d8-11eb-946c-14b7a18bb942.png)
![image](https://user-images.githubusercontent.com/61613274/117585601-f2ed6200-b0d8-11eb-9daa-80dfafa5ba08.png)
