### ISSUE TITLE
[Question] Is there a way to disable crafting of the digital miner without a 3rd party mod?

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#7172]
is there a config option, or a local way to disable crafting of the digital miner?

Tx

**Comment by Oct0bass** [comment]
Overwrite the recipe using a datapack.   The recipe id is `mekanism:digital_miner`, so you'd want to create the file `data/mekanism/recipes/digital_miner` in your datapack and disable it using the "false" condition (not exactly sure what this is).

**Comment by winsrp** [comment]
I'll give it a check, tx

**Comment by winsrp** [comment]
just as reference, if anyone else asks in the future, following @Oct0bass recommendation, I just entered this recipe that replaces digital miner original recipe. Works for any modded or standard item if you put it on the proper folder. Only the name of the file is important, and defined which item this recipe is applied to.

in this case "digital_miner.json"

{
  "type": "crafting_shapeless",
  "ingredients": [ { "item": "minecraft:air" } ],
  "result": { "item": "minecraft:barrier" }
}

tx.

**Comment by Nia42** [comment]
As long as the file is in the right location, if you only put `{}` in the file, the file will register,
however the recipe will fail to validate and is fully removed.
_I've had mixed results with the air/barrier method._
_Also, sorry for necro post._
