### ISSUE TITLE
Functional but Misplaced TEP Controller

### ISSUE THREAD

**Issue by NotReviere** [mekanism/Mekanism#7174]
#### Issue description:
Thermal Evaporation and Fusion Controller being functional despite being misplaced.

#### Steps to reproduce:
1. Construct a TEP (or Fusion) without the controller.
2. Place a TEP (or Fusion) controller adjacent to the TEP, but not in it (as in not properly part of the multiblock).
3. Place a TEP (or Fusion) controller properly in the multiblock. The TEP (or Fusion) should now be functional with both controllers functional as well. The number of controllers seem to be infinite too.

#### Additional Information:
![2021-05-11_13 12 16](https://user-images.githubusercontent.com/69776492/117857238-8dc17a00-b25a-11eb-8fc1-19722d3337ec.png)

https://user-images.githubusercontent.com/69776492/117857492-d4af6f80-b25a-11eb-91a6-5eaf8e8c0078.mp4

![unknown](https://user-images.githubusercontent.com/69776492/117869814-442c5b80-b269-11eb-8d95-b73fa911c1d4.png)

#### Version (make sure you are on the latest version before reporting):
**Forge:**  36.1.2
**Mekanism:** 10.0.21.448

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by toddlersizedsharkcage** [comment]
Possibly related - placing a fission reactor logic adapter against a fission reactor functions as part of the multiblock.  Attached image is of a working adapter which is set to activation and is able to control the activation status of the reactor it's attached to.  Video embedded as well.

![image](https://user-images.githubusercontent.com/59610016/122572830-1f6f9480-d01c-11eb-8fc8-c7681dc39308.png)


https://user-images.githubusercontent.com/59610016/122573171-7ecda480-d01c-11eb-9b26-3bca7a55f533.mp4
