### ISSUE TITLE
[Question] How can I reduce the amount of damage done by the atomic disassembler?

### ISSUE THREAD

**Issue by winsrp** [mekanism/Mekanism#7176]
I went through the config, server config and datapack inside the mod, and could not find something that allows me to reduce the damage from the atomic disassembler.... 

It seems to be at 20, and I would love to put it somewhere in the 10 range. Tx.

**Comment by pupnewfster** [comment]
To an extent questions are probably better suited for our [discord](https://discord.gg/nmSjMGc) but the answer to the question is this:
File: `config/Mekanism/gear.toml`
Config entry: `gear.atomic_disassembler.maxDamage` (you also can configure the minDamage and other settings of the atomic disassembler there.

**Comment by winsrp** [comment]
Thanks so much!
