### ISSUE TITLE
Digital Miner Claim/Protection

### ISSUE THREAD

**Issue by ThisIsDelyria** [mekanism/Mekanism#7178]
I have my own Modpack and tried different mods and plugins for protection to allow players to claim/protect areas, but the digital miner just ignores everything, if u place the digital miner outside /at the edge of the claim u can farm blocks that are inside the claim.

I tried it myself with friends and even let everyone try it on different claims from different claim mods/plugins

Mods/Plugins i tried:
ftb guy libary
claimit

**Comment by pupnewfster** [comment]
If you are able to mine in the claim yourself my guess is that the mod claimit is properly noticing our proxying of who the miner is to you (assuming you are on one of the newer versions of mekanism as you just deleted the issue format...). If you can't but the miner can my guess is that this is a bug in claimit that is just entirely ignoring fake players at which point you should take it up with them.

**Comment by ThisIsDelyria** [comment]
i let someone else with normal player permission tried to mine on someone elses claim (normal player too) with his own miner, he could not mine on the claim but his miner could... so then iam going to contact the claim plugin owner thanks for your quick answer^^
