### ISSUE TITLE
MekaTool energy usage for normal, silk touch, and teleport modes all use the same variable name in the config

### ISSUE THREAD

**Issue by connor-belli** [mekanism/Mekanism#7180]
https://github.com/mekanism/Mekanism/blob/b0a96e1eb7b5f5741cb1ca2f4ce656084ae923d5/src/main/java/mekanism/common/config/GearConfig.java#L252-L259

**Comment by pupnewfster** [comment]
Thanks for pointing this out, while fixing them I also noticed that the electric bow's energy usage and energy usage when in fire mode were overlapping as well.
