### ISSUE TITLE
Share Private Teleporter Frequencies

### ISSUE THREAD

**Issue by Peekofwar** [mekanism/Mekanism#7182]
It would be nice if a user could setup a private frequency and share this frequency with other specified users such as those in a trusted list, so that they could for instance, teleport to said private frequency using their own portable teleporters.

Theoretically placing a frequency in the public list makes the location vulnerable to invasion by unwanted or hostile intruders.

Perhaps there could be a third frequency list in addition to the `public` and `private` lists called "`shared`" which would be shared with users in your trusted list.

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/125
