### ISSUE TITLE
Induction Matrix bug

### ISSUE THREAD

**Issue by MobilGame06** [mekanism/Mekanism#7183]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
After every server restart the induction restart don't work anymore until i remove a block and build it again.

#### Steps to reproduce:
1. build induction matrix
2. restart server

#### Version (make sure you are on the latest version before reporting):
**Forge:*1.12.2-14.23.5.2855* 
**Mekanism:*1.12.2-9.8.3.390* 
**Other relevant version:**

**Comment by pupnewfster** [comment]
Unfortunately I think you are probably out of luck as we are no longer developing for 1.12
