### ISSUE TITLE
bin problem

### ISSUE THREAD

**Issue by sk-KAZU** [mekanism/Mekanism#7184]
bin is clicked twice on the first click
forge : 1.16.5
mekanism : v10

**Comment by pupnewfster** [comment]
Could you elaborate on what you mean, as it sounds like your mouse potentially is just dying. Also is this say left clicking to remove items or right click to put items in or what?

**Comment by sk-KAZU** [comment]
When taking out one item
I changed the right click assignment, but it has no effect

**Comment by sk-KAZU** [comment]
I'm flipping the left click and right click assignments

**Comment by pupnewfster** [comment]
I am unable to reproduce this, have you tried using another mouse?

**Comment by sk-KAZU** [comment]
Yes, but it's still happening
