### ISSUE TITLE
Logistical Sorter Prioritizing Closest Chest Instead of Colored Pipe

### ISSUE THREAD

**Issue by Peekofwar** [mekanism/Mekanism#7187]
#### Issue description:
When I moved my output chest next to the input chest, I noticed that the logistical sorter started acting as if sorted items were unsorted; sending all colored items to the uncolored output instead of the colored outputs.

It seems as though it prioritizes the closest inventory instead of prioritizing the closest inventory of the correct color. If the item is being sent with a sorted color, it should instead prioritize the nearest colored output instead of the nearest uncolored path.

![2021-05-15_21 53 16 - Copy](https://user-images.githubusercontent.com/10189526/118383035-5b43b400-b5af-11eb-9523-17373277e2d5.png)

#### Steps to reproduce:
1. Place an input chest with a logistical sorter and setup a filter to send items to a colored logistical pipe.
2. Place a logistical pipe going into an inventory about a dozen metres away with the same color as the filter you setup.
3. Place an output chest without a colored logistical pipe next to the logistical sorter.
4. Input the filtered item into the input chest.

#### Version:
**Forge:** v36.1.0
**Mekanism:** v10.0.21
**Minecraft:** v1.16.5

**Comment by pupnewfster** [comment]
This is intended. It does closest valid destination colors are used to change the validity of paths.

**Comment by Peekofwar** [comment]
Would you consider adding a "force color" option then?

**Comment by pupnewfster** [comment]
No, the system is not setup for that and would be bad for performance if you want to make a path lower priority use restrictive transporters they add a cost of 1,000 if memory serves to the path.

**Comment by Peekofwar** [comment]
I did not know that restrictive transporters existed. Thanks.
