### ISSUE TITLE
Duplication glitch w/ AE2

### ISSUE THREAD

**Issue by CaptainPlasma101** [mekanism/Mekanism#7188]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Using a cardboard box on a container with fluix seeds inside duplicates the fluix seeds

#### Steps to reproduce:
1. Put fluix seeds in a chest
2. Use a cardboard box
3. Fluix seeds drop. The original fluix seeds are still inside the chest.

#### Version (make sure you are on the latest version before reporting):
**Forge: 36.1.2**
**Mekanism: 10.0.21.448** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
#7053
