### ISSUE TITLE
dupe/multiplication glitch

### ISSUE THREAD

**Issue by zaze06** [mekanism/Mekanism#7192]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
items get duped/multiplied when a machine gets upgraded from basic to advanced

#### Steps to reproduce:
1. place a basic infusing factory
2. fill it whit iron and coal
3. wait until the its something in the output
4. upgrade it to advanced
5. now you will get infinit out until you tack something out from the output

#### Version (make sure you are on the latest version before reporting):
**Forge: 36.1.0** 
**Mekanism: files say 10.0.21 (but i have the cc: tweaked integration so it might just be the build.gradel or something that isn't updated to say 10.1)** 
**Other relevant version:**

**Comment by zaze06** [comment]
do you wish for me to try it in me 10.1 or dos 10.0 work?

**Comment by pupnewfster** [comment]
I mainly care about 10.1, given this was apparently with the 10.1 branch and I can't reproduce it on the 10.1 branch (I didn't try on the 10.0.x branch). Though if you can't reproduce it on 10.1 and can on 10.0.x that might be worth at least knowing.

**Comment by zaze06** [comment]
yes.

**Comment by zaze06** [comment]
I can't reproduce it in 10.0.x
but I will try that again in 10.1. where can I get 10.1 more than making it from the sorcefiles? also, I will get my friend to try it sens he was acely the one who find it out

**Comment by pupnewfster** [comment]
The same way you presumably got it initially, via building it yourself from source.

**Comment by pupnewfster** [comment]
From some people on discord who ran into this issue it seems I misunderstood it before and didn't realize it had to do with ejecting and thought it was inventory contents, so I will look at this a bit more after I finish with what I am in the middle of doing locally.
