### ISSUE TITLE
Waiting for server... 

### ISSUE THREAD

**Issue by ROOTBEEROFF** [mekanism/Mekanism#7195]
#### Issue description:
When looking at a pipe or a machine it should normally show stats like how much items or gas or liquid but instead its saying "waiting for server..." I look online and look it a issue that been there for awhile. I contact my server host provider and they cannot do anything since it look like a mod problem but im not sure. Sometime after multiple restart it will work again and actually show the information

#### Steps to reproduce:
1. No step, just look at a machine and see if you can see the information of how much stuff there is in it

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.16
**Mekanism:** V10 - 1.16.5

**Comment by pupnewfster** [comment]
Do you have TOP installed on both the server and client and also what version of TOP do you have installed.

**Comment by ROOTBEEROFF** [comment]
TOP ?

**Comment by pupnewfster** [comment]
The One Probe. Aka the mod that I believe is probably what is showing the "Waiting for server..." you are talking about.

**Comment by ROOTBEEROFF** [comment]
theoneprobe-1.16-3.0.8 (Installed on both client and server)

**Comment by dcorallo** [comment]
I have the same issue. Using theoneprobe-1.16-3.1.4.jar in modpack Seaopolis. This bug occured on my client on day 10 since the server started, but the "lag" or "wating" is purely client-based. My friend was experiencing similar issues earlier.

**Comment by Novtalath** [comment]
As above similar situation. Seaopolis and "Waiting for server". I might have something to add here though - managed to catch a screenshot - it shows that info for like 0.5 sec and goes to "Waiting..." again
![Mekanism_Issue](https://user-images.githubusercontent.com/13785880/124041627-21176000-d9ff-11eb-84a4-fb4ea4ff0256.png)

**Comment by pupnewfster** [comment]
> As above similar situation. Seaopolis and "Waiting for server". I might have something to add here though - managed to catch a screenshot - it shows that info for like 0.5 sec and goes to "Waiting..." again
> ![Mekanism_Issue](https://user-images.githubusercontent.com/13785880/124041627-21176000-d9ff-11eb-84a4-fb4ea4ff0256.png)

Someone on our discord had this issue as well and removing TOP Addons solved it. I believe it is a fundamental bug in how TOP is written that if the server and client have a different number of element factories then the ids can mismatch and the client will try to read the data as the wrong format.
