### ISSUE TITLE
Unable to read Induction Matrix maxEnergy/currentEnergy with other mods.

### ISSUE THREAD

**Issue by Riewest** [mekanism/Mekanism#7196]
#### Issue description:
I've been attempting to get a display working to show how much energy is stored in my induction matrix but it seems that all the mods I can think to use to read the energy get the wrong data back. They all cap out at 2,147,483,647 energy stored, but my actual energy stored is 4 times that at this point and will eventually reach trillions.

**Mods/Blocks I've used to get the FE Stored:**
CCTweaked Advanced Computer
RFToolsUtility Energy Screen Module/Energy Plus Module
IntegratedDynamics Machine Reader

#### Steps to reproduce:
1. Make an Induction Matrix and fill with power
2. Attempt to read power with other mods (CC Tweaked, RFTools, etc)
3. See that the energyStored/maxCapacity are incorrect.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  36.1.4
**Mekanism:**  10.0.21
**Other relevant version:** 
**Pack:** FTB Direwolf20 1.16 (1.9.0)

![image](https://user-images.githubusercontent.com/16376061/118914182-0625dc00-b8e8-11eb-8dc7-ebd8a1f806b7.png)
![image](https://user-images.githubusercontent.com/16376061/118914190-0920cc80-b8e8-11eb-8977-2bdab63e2d45.png)
![image](https://user-images.githubusercontent.com/16376061/118914206-0cb45380-b8e8-11eb-8917-1e7c6608b11b.png)
![image](https://user-images.githubusercontent.com/16376061/118914213-0faf4400-b8e8-11eb-81d5-ff6f566bd5d8.png)

**Comment by pupnewfster** [comment]
That would be because the max value is higher than they can handle. Our computer craft integration is coming back in 10.1 #6445 which should make that work and in terms of the other two mods I am not sure if they have APIs and I am not likely to spend the time attempting to implement integration with them (though if someone wants to PR it I will review and merge it).
