### ISSUE TITLE
why; this is a cheat recipe

### ISSUE THREAD

**Issue by burdoto** [mekanism/Mekanism#7200]
(closed immediately due to low priority) ![grafik](https://user-images.githubusercontent.com/42473485/119225172-7f008000-bb02-11eb-890b-b8867490bff3.png)

**Comment by burdoto** [comment]
like, can i also put pumpkin seeds in the enrichment chamber or what? same logic error

**Comment by pupnewfster** [comment]
The same way you remove any other recipe. Either with a datapack or something like CraftTweaker or KubeJS
