### ISSUE TITLE
My fission reactor went to 37282% damage without blowing up...

### ISSUE THREAD

**Issue by YouHasBeenWarned** [mekanism/Mekanism#7202]
#### Issue description:
I am not sure, if this is a bug or whatever, but my fission reactor went to 37282% damage without blowing up
and just released some radiation. My industrial turbine next to it was responsible for cooling and worked perfectly fine afterwards

#### Steps to reproduce:
1. build a fission reactor with industrial turbine.
2. let it run overnight.
3. wake up to find your reactor with extreme damage and radiation output, but no explosion.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.0
**Mekanism:** 10.0.21
**Other relevant version:** 

Here is a picture of the reactor gui after I shut the reactor down
![Minecraft_ 1 16 5 23 05 2021 11_24_01](https://user-images.githubusercontent.com/75141962/119255121-3ad0b680-bbba-11eb-9aa7-16b563e2080a.png)

**Comment by Robball14** [comment]
the explosion is either disabled in the configs or, more likely, FTB chunks preventing the explosion

**Comment by YouHasBeenWarned** [comment]
I have installed FTB Chunks, I play on a server with a few friends, thank you

**Comment by YouHasBeenWarned** [comment]
Gonna close this then
