### ISSUE TITLE
QIO Crafting makes most items

### ISSUE THREAD

**Issue by zaze06** [mekanism/Mekanism#7203]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I get gust items from the crafting in QIO and it isn't compatible whit JEI
Example and for refrains I have 0 contol circits, 15 polonium and 522 lead in the system when this photo was tacken
![image](https://user-images.githubusercontent.com/54169874/119326470-353ea380-bc82-11eb-8c73-54b6fd2684c8.png)

#### Steps to reproduce:
1. Make a QIO system
2. try to craft something 
3. you will now have a gust item

#### Version (make sure you are on the latest version before reporting):
**Forge: 36.1.0** 
**Mekanism: 10.1 (old one tho have no newer one)** 
**Other relevant version: ** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
JEI integration for it is not complete yet...

**Comment by zaze06** [comment]
still that docent explain the gost items (don't know if its gost or gust my Mac says no to both)

**Comment by zaze06** [comment]
Don't know if this is counted as "prof" or make it confirmed (I have all the items) and I get a ghost item
Sorry if this just spent your time if this isn't needed/bad
https://user-images.githubusercontent.com/54169874/119366473-4c48ba00-bcb1-11eb-9932-543b91b464d5.mp4

**Comment by pupnewfster** [comment]
Are the server and your client are both running the same exact build of 10.1? Given if not who knows what sort of desync issue may happen due to various protocol changes that don't get a version bump corresponding to them because 10.1 isn't released so there is no point.

**Comment by zaze06** [comment]
that run on the same build from what I know and what I know my friend docent have any way to get/make a build him self fo probably the same

**Comment by zaze06** [comment]
but I can re-upload the build I have on my client and test

**Comment by zaze06** [comment]
didn't change anything
