### ISSUE TITLE
Factory machine speed scaling

### ISSUE THREAD

**Issue by TepTheStep** [mekanism/Mekanism#7206]
#### Issue description:
When speed upgrades are installed in a machine such as the Metallurgic Infuser the speed scales up to 10x at max upgrades, however with a factory variant the speed appears to double with each upgrade like how the Electrolytic Separator handles speed upgrades.

#### Steps to reproduce:
1. Get some speed upgrades for a standard machine and a factory.
2. Install the upgrades.
3. Observe the GUI.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.24
**Mekanism:** 10.0.21.448
**Other relevant version:** Minecraft 1.16.5

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
Latest log here: 
https://pastebin.com/wxiPzbiN
Video:
https://user-images.githubusercontent.com/84690118/119529118-cdef2500-bd4f-11eb-8fdb-fb5aa0fdb413.mp4

**Comment by pupnewfster** [comment]
Fixed for 10.1, turns out the string in the GUI was just using the wrong calculation method for a few machines.

**Comment by TepTheStep** [comment]
Very cool, thanks.
