### ISSUE TITLE
[Compat] Using Mekanism's Cardboard Box destroys the lock from Locks mod (1.16.5)

### ISSUE THREAD

**Issue by Lgmrszd** [mekanism/Mekanism#7210]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Using cardboard box on locked blocks (using lock from [Locks](https://www.curseforge.com/minecraft/mc-mods/locks) mod causes lock to break and disappear.
Locks mod author suggested that issue might be on a Mekanism side, as it does not check if blocks are breakable. (https://github.com/Melonslise/Locks/issues/85)

#### Steps to reproduce:
1. Put a lock on a chest.
2. Put a cardboard on a chest with a lock.
Expected behavior:
Either putting box on chest without breaking the lock or failure to put on the box.
Actual behavior:
Box is put on chest and lock is destroyed.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.24
**Mekanism:** 1.16.5-10.0.21.448
**Other relevant version:**  Locks: 1.16.5-3.0.3

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

No crash so no log.

**Comment by pupnewfster** [comment]
Report to the locks mod, if their mod block can't properly be picked up they should either add it to the block tag:
`forge:relocation_not_supported` or one of the tile tags: `forge:relocation_not_supported`, `forge:immovable`. These tags are used by multiple mods as defaults for blacklists so that way all the mods can see that it doesn't support moving instead of say just Mekanism.

**Comment by Melonslise** [comment]
My mod doesn't add any new blocks. What, do you expect me to add every single block from the game and every mod to your tags? You can't be serious. How about you actually check if the block is breakable by the given player by using, oh I don't know, maybe the default forge block BreakEvent???

**Comment by pupnewfster** [comment]
I misunderstood how the locks mod work in that it doesn't add any blocks.

**Comment by Melonslise** [comment]
Thanks
