### ISSUE TITLE
Industrial Turbine Work Weird

### ISSUE THREAD

**Issue by FarmerRacing** [mekanism/Mekanism#7213]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
See video https://vimeo.com/555997282
Cant Stabilize it 

#### Steps to reproduce:
1. fusion reactor
2. insdustrial turbine
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:*36.1.4* 
**Mekanism:*1.16.5* 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://vimeo.com/555997282 take a look 
[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Potentially this is due to you having dumping excess turned on but my better guess is:
Do you have performant installed?

**Comment by FarmerRacing** [comment]
I was thinking dumping excess is for the energy   i will try to turn it off
i got optiFine is that a performant? 

Thx !

**Comment by FarmerRacing** [comment]
that was not my problem :(
even with dumping set to Idle it's does the same thing..

**Comment by FarmerRacing** [comment]
it Been Fixed ! i ask the server owner to remove the mod performant and it work now ! thx a lot
