### ISSUE TITLE
Can't set digital miner radius > 32

### ISSUE THREAD

**Issue by vmspionage** [mekanism/Mekanism#7214]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Digital miner radius set to 256 on client and server config (maxRadius = 256).  When configuring miner radius on client anything above 32 is not accepted.

#### Steps to reproduce:
1. Configure miner radius 256 on client and server
2. Place miner
3. Attempt to set radius > 32

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.18
**Mekanism:**  10.0.21.448
**Other relevant version:**  Valhelsia 3 - 1.16.5

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by vmspionage** [comment]
This can be closed, wasn't able to verify on local server (works as expected).  There is something else probably going on with my other server.  Sorry about that.

**Comment by pupnewfster** [comment]
Best guess then is the file isn't saving properly or something then. If you are editing it while the server is up might be worth trying to edit it while the server is off to see if it just isn't letting the active file be updated or something.

**Comment by quinchs** [comment]
Also make sure if you edit a config to restart the server/client to load the new changes
