### ISSUE TITLE
Walkie talkie

### ISSUE THREAD

**Issue by devmasu** [mekanism/Mekanism#7215]
#### Issue description:
More a question than a bug report, do the walkie talkies work on version 1.16.5 because I could not get them to work and I just saw that it was planned once the porting finished. Thank you in advance!

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.24
**Mekanism:** 1.16.5-10.0.21.448

**Comment by pupnewfster** [comment]
I don't believe they currently work (#6102)
