### ISSUE TITLE
Inconsistent colours when putting resourceful bees custom honey in mekanism pipes/tanks

### ISSUE THREAD

**Issue by Vaerys-Dawn** [mekanism/Mekanism#7220]
#### Issue description:
In our development version of resourceful bees there seems to be an issue with fluids not rendering properly.

When custom honey is placed inside a mekanism tank or pipe it will not show the correct colour.

Rainbow honey seems to be working just fine (Rainbow honey changes colour every tick).
Pipes configured to inputs or outputs show the correct colour.
Fluid interfaces work fine and show the right colour

#### Steps to reproduce:
1. create a custom fluid with a custom colour
2. put said custom fluid into a mekanism tank/pipe
3. configure the pipes to have inputs and outputs.
4. observe the inconsistency in the colours 

#### Versions:
**Forge: 36.1.6** 
**Mekanism: 10.0.20** 
**ResourcefulBees: 1.0.0_alpha** 

#### Relevant extra information:
![image](https://i.imgur.com/nBwAk5q.gif)

![image](https://user-images.githubusercontent.com/5305116/120131753-61bb6800-c20c-11eb-8247-27285220b4e5.png)

[pastebin of relevant resourceful bees code.](https://pastebin.com/WUqMa5Ja)

**Comment by pupnewfster** [comment]
Update to 10.0.21

**Comment by Vaerys-Dawn** [comment]
will do, will return if it's still an issue

**Comment by Vaerys-Dawn** [comment]
works just fine now, thank you :D
