### ISSUE TITLE
Mekanism 1.12.2 crashes

### ISSUE THREAD

**Issue by InvIzIbleWQW** [mekanism/Mekanism#7223]
Found here https://github.com/mekanism/Mekanism/issues/5522 about problem is not in Meka.
But.
My modpack doesn't include WirelessRedstone mod at all. Crash only solves by removing only Meka's mod and its addons.

**Comment by NotReviere** [comment]
Could you provide the crash log please?

**Comment by InvIzIbleWQW** [comment]
Well, found by myself, now looks like IC-2 became the problem, which is caused by a little outdated IC-2 version.
