### ISSUE TITLE
[1.16.5] Jetpack phantom bug

### ISSUE THREAD

**Issue by bigenergy** [mekanism/Mekanism#7224]
#### Issue description:
If you simply remove the "Jetpack", the phantom will remain on it, you can also fly and soar. It does not consume any fuel and does damage upon landing.

![image](https://user-images.githubusercontent.com/17977139/120573625-8d199f00-c426-11eb-8ac7-d0c206634766.png)
![image](https://user-images.githubusercontent.com/17977139/120573633-8f7bf900-c426-11eb-82b9-658829e92140.png)

#### Steps to reproduce:
1. put on a jetpack
2. take off the jetpack
3. description above

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.24
**Mekanism:** 10.0.21.448
**Other relevant version:** 

The problem exists both on the server and in the single player game

**Comment by bigenergy** [comment]
There is also a problem in the "Atomic disassembler" The problem is also in phantom, but it does not break blocks, but makes them invisible.

**Comment by pupnewfster** [comment]
What other mods do you have as it sounds like some other mod you have is massively screwing with how item moving in the inventory works

**Comment by beholderface** [comment]
Are you sure this isn't just a client-server desync?

**Comment by bigenergy** [comment]
> Are you sure this isn't just a client-server desync?

No, this happens in single player too

> What other mods do you have as it sounds like some other mod you have is massively screwing with how item moving in the inventory works, and can you reproduce this with just mekanism?

I'll try to reproduce

**Comment by beholderface** [comment]
For quite a while now Minecraft has technically been hosting a server even in singleplayer, it's just not exposed to the internet most of the time

**Comment by Caldoric** [comment]
I've been experiencing this too, on a server hosting Valhelsia 3 (ver. 3.3.2a), with whatever version of melanism and forge that carries. Freerunners also sometimes do it, though less frequently.

**Comment by syorito-hatsuki** [comment]
> Could be caused by Mouse Tweaks, as far as I'm aware that's the only inventory management mod in a pack I'm using and I have the ghost item glitch for all mekanism tools/armor. (1.16.5)

I play without Mouse Tweaks and have same bug
