### ISSUE TITLE
mekanism crash with other mods

### ISSUE THREAD

**Issue by TheKingOmar** [mekanism/Mekanism#7225]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
i made a modpack but when i tried to launch it with mekanism it crashed just that

#### Steps to reproduce:
1.make a modpack
2.test it
3.add mekanism 
4.modpack crash
#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2855
**Mekanism:** latest
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]
https://pastebin.com/pwWrwcH9 (crash log)

**Comment by Seniorendi** [comment]
You say, you use the latest version of mekanism. But the latest mekanism version is only available for 1.16.

**Comment by pupnewfster** [comment]
#6182

**Comment by TheKingOmar** [comment]
i meant the last version for 1.12.2

**Comment by TheKingOmar** [comment]
> You say, you use the latest version of mekanism. But the latest mekanism version is only available for 1.16.

is there a fix ????

**Comment by pupnewfster** [comment]
If you would read the issue I linked... either install Galacticraft or remove Lucraft core. Lucraft core has a hard dep on galacticraft if any other mods that have an optional dep on galacticraft are installed as it causes them to crash because of how lucraft does their galacticraft integration.

**Comment by TheKingOmar** [comment]
i just found the fix it's simply by adding galactic craft mods

**Comment by TheKingOmar** [comment]
> If you would read the issue I linked... either install Galacticraft or remove Lucraft core. Lucraft core has a hard dep on galacticraft if any other mods that have an optional dep on galacticraft are installed as it causes them to crash because of how lucraft does their galacticraft integration.

I read it and fixed the problem
