### ISSUE TITLE
Configuration card doesn't copy "Dumping" and "Dumping excess" from the electrolytic separator

### ISSUE THREAD

**Issue by Catchears** [mekanism/Mekanism#7228]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
The configuration card doesn't copy "dumping" and "dumping excess" settings from the electrolytic separator.

#### Steps to reproduce:
1. Place an electrolytic separator.
2. Set it to "Dumping" or "Dumping Excess".
3. Copy the configuration with a configuration card.
4. Right click on another electrolytic separator.
5. Open it and see that it still says "Idle".

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.0.37
**Mekanism:** 10.0.20.447
**Other relevant version:** Modpack: [Create101 2.0.1](https://github.com/ZengineeringTeam/Create-101)

**Comment by Catchears** [comment]
Uhh, the quick label adding makes me feel like this issue has already been reported. I had a look and couldn't see anything - am I just blind or are you just fast?

**Comment by pupnewfster** [comment]
Nothing was reported but it was something I noticed and fixed in dev a bit over a month ago when I was working on [overhauling](https://github.com/mekanism/Mekanism/commit/771daad364b011cf0ef542f2a60de0b465e9168d) our configuration cards to be even more useful.

**Comment by Catchears** [comment]
Ah, thanks.
