### ISSUE TITLE
[10.1] QIO new imported item add new stack instead of stacking correctly

### ISSUE THREAD

**Issue by AlexHgC** [mekanism/Mekanism#7229]
#### Issue description:
On 10.1, when you stay on QIO interface, new imported item add new stack instead of stacking correctly. We eneed to close and reopen the dashboard to see all stacks correctly

https://user-images.githubusercontent.com/31996023/121187988-ef303500-c868-11eb-920a-4bfd57874abe.mp4

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.25
**Mekanism:** 10.1 latest commit

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
I am not able to reproduce this. Is this on a server or in single player?

**Comment by AlexHgC** [comment]
It's on Server. Diamond come from Formulaic Assemblicator with importer, but i have this bug with all items, like chest with importer. I don't use performant/optifine/Immersive Portal

**Comment by Edi1717** [comment]
I've seen this too, though only when the same item is being exported somewhere else on the network at the same time. Are you exporting diamonds somewhere else in the video?

**Comment by AlexHgC** [comment]
Oh, yes, you are right
