### ISSUE TITLE
Gravitational Modulating Unit is either wildly overpriced, or wildly underfeatured

### ISSUE THREAD

**Issue by drysdan** [mekanism/Mekanism#7232]
**Describe the the feature you'd like**
Considering the ludicrously high cost of crafting this, it really should do a LOT more, or be a LOT cheaper. It is, effectively, a marginal upgrade to Hover Mode on a Jetpack, and if that's all it will ever do, the recipe cost should reflect that. Maybe a few Atomic Alloy and an Elytra, but certainly not 3 Antimatter, 2 Ultimate Induction Providers, and a Nether Star!  Or else it should be the ultimate, end-all-be-all of flight options.  Right now it has laughably underwhelming vertical speed, and even with 4 Locomotion units, the horizontal speed isn't even on par with vanilla Elytra flight. 

**Describe alternatives you've considered**
Either A) make the unit MUCH cheaper (maybe a few Atomic Alloy and an Elytra), or B) give it MUCH better flight dynamics - vertical speed increase as well as horizontal speed increase, options to control 'drift' so as to either be able to stop on a dime or smoothly decelerate.  Option to toggle off sound effect would also be really nice. It's fun for the first couple minutes, then really obnoxious.

**Comment by pupnewfster** [comment]
a. #7048
b. DataPacks, CraftTweaker, and KubeJS all exist

**Comment by drysdan** [comment]
> 
> 
> a. #7048
> b. DataPacks, CraftTweaker, and KubeJS all exist

So the official stance from the Mekanism development team to this is that the module is intended to be this underwhelming, underpowered, and overpriced?  No plans to make it actually be better at its function?
