### ISSUE TITLE
Crash Report (Stoneblock 2)

### ISSUE THREAD

**Issue by PlayWithShay** [mekanism/Mekanism#7234]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Booting up Stoneblock 1.16.0 MC version 1.12.2 join a server play.mc-complex.com
Joins server properly, once joining the Stoneblock Server they have it crashes, says Mekanism: Tools is the potential Cause and gives this crash report (Linked below)

Love the modpack and would love to play on servers with my friends but seem to have issues on number of servers not sure why. Hopefully you can see the problem and hopefully fix it, love the work, keep up the hard work thank you guys for some great stuff!

#### Steps to reproduce:
1. Download Curse forge Modpack Loader Thingy Hub Place or whatever its called
2. Install 'Stoneblock 2" its version 1.16.0 (Not the latest version, the lastest released with server packs) MC version 1.12.2
3. Join multiplayer server: play.mc-complex.com
4. crash

#### Version (make sure you are on the latest version before reporting):
**Forge:**  not sure versions of what i know listed above 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://paste.dimdev.org/cikabizuto.mccrash

[[gist](https://gist.github.com/) / [pastebin](https://pastebin.com/) / etc link here. Please make sure that it isn't set to expire.]

**Comment by pupnewfster** [comment]
Has to do with #5797, not really sure what causes it to be honest given I never had it happen to me. Closing this though as we are no longer developing for 1.12 and it isn't an issue in 1.16
