### ISSUE TITLE
Crash on starup

### ISSUE THREAD

**Issue by TomasArrinda** [mekanism/Mekanism#7236]
MC version 1.12.2

Mekanism is crashing the game on startup, something about exceptions?

Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (mekanism)

**Forge:** 14.23.5.2855
**Mekanism:** 9.8.3.390

Full crash report:
https://ghostbin.com/paste/Gzzro

**Comment by pupnewfster** [comment]
#6182 lucraft bug, remove lucraft core or install galacticraft
