### ISSUE TITLE
Mekanism v10 1.16.5 Terrible fps on new world and or server.

### ISSUE THREAD

**Issue by xKronos58** [mekanism/Mekanism#7237]
Description:
When i try to run mekanism v10 in 1.16.5 on a new world or a sever i drop frame rate from a stable 300-400 without mekanism to 1-2 fps when running mekansim. When i load up the debug screen with the debug pie chart is says the <83% of the game tick is being used where as when i run any other mod or modpack i have no issues. i have tried several diffrent fixes that are on the internet and some of my own but none of them have seemed to do anything. the best i could do was create a new directory running just mekanism with 10gb of ram lowes graphics settings lowest render distance, but that would only bring my fps to 10-15. I have tried running mekanism on serevr but i have the same issue the client tick is running at <83% but the server TPS is avaraging 20.00. Any solutions or fixes would be greatly appreicated ty...

I am running:
Forge: 36.1.31 (1.16.5)
Mekanism:10.0.21.448

Pc Specs:   (put these here if they are needed)
GPU: Asus renadon rx 570
Ram: 16gb
CPU: AMD ryzen 5 3600
Mother board: Asrock b450m steel legend
650w power supply
![image](https://user-images.githubusercontent.com/85923609/122005302-d12e7b80-cdf8-11eb-8ba0-58886032af0b.png)
![2021-06-15_16 41 58](https://user-images.githubusercontent.com/85923609/122005502-10f56300-cdf9-11eb-99a7-2ccff4b47600.png)

**Comment by pupnewfster** [comment]
I am not quite sure if this is it or if this is a full fix but copied from foamfix's description.

> For some GPU/driver configurations (in particular, certain AMD driver/card pairs), disabling mipmaps (setting Mipmap Levels to 0) will boost FPS considerably. This is due to lag caused by animated texture updates being much higher with increasing amounts of textures to update, which scales linearly with the amount of mipmap levels.

So I would start by trying to see if setting mipmapping in the settings to zero helps any.

**Comment by xKronos58** [comment]
Thankyou, This seems to have boosted my frame rate to over 100 so that seems to have worked. :)
