### ISSUE TITLE
[1.16] ItemPhysic compatibility

### ISSUE THREAD

**Issue by CreativeMD** [mekanism/Mekanism#7239]
Hey there,
I'm the author of ItemPhysic and apparently there is an issue of items spinning inside logistical transporter.
ItemPhysic overwrites the way items are rendered. It also uses a few tricks to prevent issues like these:
* items with an age of 0 are ignored
* there is a custom field `skipPhysicRenderer` (boolean) which has to be false

Maybe you could add support for it? Either by not increasing the age of the item or by setting `skipPhysicRenderer` to `true` once the ItemEntity is created.

In Regards
CreativeMD

**Comment by pupnewfster** [comment]
Sounds reasonable enough to add an extra thing [here](https://github.com/mekanism/Mekanism/blob/v10.1/src/main/java/mekanism/client/render/transmitter/RenderLogisticalTransporter.java#L76-L77) that just resets the age to zero. It probably would need an AT but that should be easy enough to do for Mek 10.1
