### ISSUE TITLE
Placed laser wrongly, ate an Ultimate cable, then possibly a Ghost RS cable

### ISSUE THREAD

**Issue by EterniaLogic** [mekanism/Mekanism#7240]
#### Issue description:
In front of my amplifier, somehow laser was placed looking at Ultimate cable and broke the ultimate cable, immediately crashed game. Also note that the area was protected by FTB Chunks and some of the errors seem to deal with refined storage?
Unfortunately, the location of the laser chunk was right next to my multi-Fusion reactor/Turbine setup (the laser was pointed away) so I cannot just delete and refresh the chunk.
https://github.com/refinedmods/refinedstorage/issues/3020

#### Steps to reproduce:
1. (possibly) have FTB Claimed chunk
2. Place powered Ultimate Cable
3. (Possibly) have a Refined storage cable connected to system in the way of the laser right after it dug through a cable right in front of it when placing it down.
4. Place Laser down facing ultimate cable (and possibly a location of a refined storage cable)
5. Cannot log into world anymore since minecraft logs block places immediately

#### Version (make sure you are on the latest version before reporting):
**Forge:** 36.1.13
**Mekanism:** 1.16.5-10.0.21.448
**Refined Storage:** 1.9.12

**Comment by EterniaLogic** [comment]
This might also just be a Refined Storage error, where RS author should've just put a Throw/Catch instead of crashed-to-desktop.

**Comment by pupnewfster** [comment]
If memory serves this is a problem on RS' end that their blocks really don't like being broken by fake players. Given the fact the RS issue got labeled with it being a bug (but closed because of it being a duplicate issue) I am going to close this on our end.
