### ISSUE TITLE
QUI Redstone Adapter confusion

### ISSUE THREAD

**Issue by aaronhowser1** [mekanism/Mekanism#7242]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

![image](https://user-images.githubusercontent.com/15698722/122636394-acfbc480-d0ae-11eb-8944-f8b34299948b.png)
I can't figure out how to change the Trigger Count. When I click the slot, it makes a beep, but nothing else. When I place a stack of 64 logs, it stays as 0.

Is there a way to make it trigger when UNDER an amount, or would that just be done with a redstone torch?

#### Version (make sure you are on the latest version before reporting):
**Forge:**  36.1.10
**Mekanism:** Mekanism-1.16.5-10.0.21.448
**Other relevant version:**

**Comment by pupnewfster** [comment]
Click next to the `>` it is a text box.  And to make it trigger under an amount use a redstone torch to invert the redstone signal.
