### ISSUE TITLE
My teleporters will not activate, saying "no link"

### ISSUE THREAD

**Issue by Digifox08** [mekanism/Mekanism#7251]
### Issue description

Hello, there is an issue with the teleporters I build.

I build 2 teleporters around 2000 blocks away from each other powered to around halfway and I am using a private frequency. However, like the title, both teleporters say "no link". I am super confused and Think this may be a bug.

### Steps to reproduce

1. Create teleporters
2. fill around halfway
3. create private frequency
4. Now it should say "no link"

### Minecraft version

1.15.x or earlier (No longer being developed)

### Forge version

1.12.2

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
Are both teleporters chunk loaded?

**Comment by Digifox08** [comment]
> Are both teleporters chunk loaded?

I wouldn't know about that but have travelled between both teleporters multiple times in confusion. Is there some way to keep them both loaded?

**Comment by pupnewfster** [comment]
Easiest way would be to just install an anchor upgrade in the teleporter which ensures the teleporter stays loaded.

**Comment by Digifox08** [comment]
> Easiest way would be to just install an anchor upgrade in the teleporter which ensures the teleporter stays loaded.

Oh, sadly I can't do that because I am playing on a server. There is a chance I could talk to the owner, but is there some other way?

**Comment by pupnewfster** [comment]
Unless they disabled anchor upgrades in the config there is no reason that you couldn't on a server. But if they did if the server has some other chunk loading mod that could be used instead.

**Comment by Digifox08** [comment]
I did not know that it was just in the config. If you have the time, do you think you could walk me though how to do this?
