### ISSUE TITLE
My teleporters will not activate, saying "no link"

### ISSUE THREAD

**Issue by Digifox08** [mekanism/Mekanism#7252]
### Issue description

Hello, there is an issue with the teleporters I build.

I build 2 teleporters around 2000 blocks away from each other powered to around halfway and I am using a private frequency. However, like the title, both teleporters say "no link". I am super confused and Think this may be a bug.

### Steps to reproduce

1. Create teleporters around 2000 blocks apart
2. fill around halfway
3. create private frequency
4. Now it should say "no link"
![image](https://user-images.githubusercontent.com/86581283/123569858-be1e9280-d78c-11eb-9345-e08475c06ad9.png)

### Minecraft version

1.15.x or earlier (No longer being developed)

### Forge version

1.12.2

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
#7251
