### ISSUE TITLE
The game keeps crashing

### ISSUE THREAD

**Issue by ybquality** [mekanism/Mekanism#7253]
### Issue description

Mekanism: -1.16.5-10.0.21.448

### Steps to reproduce

Constantly, suddenly collapsed for some reason

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.32

### Mekanism version

10.0.21 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://paste.ubuntu.com/p/S6pfSZFJcj/

**Comment by pupnewfster** [comment]
Does this happen on forge or only on whatever weird bukkit/forge hybrid that server is using?

**Comment by thiakil** [comment]
That's not even a crash, just a thread dump because you server decided a tick was taking too long or something.

It just happened to be running Mekanism code at the time
