### ISSUE TITLE
Digital Miner Not Scanning 

### ISSUE THREAD

**Issue by HelpAccepted** [mekanism/Mekanism#7254]
### Issue description

I was using the digital miner on my friends private server and after running my first mining cycle with all my filters in the nether I picked it up and moved locations to further away to start again. Now the miner won't scan any blocks and says blocks to mine 0. I even removed all the filters and went into the overworld found an ore I wanted to mine and set it as the filter and placed the miner nearby and it still said 0 to mine after turning it on. Im running the 1.12 pack on the technic launcher and running mekanism 9.8

### Steps to reproduce

1. power and set the filters on the digital miner 2. press start 

### Minecraft version

1.15.x or earlier (No longer being developed)

### Forge version

8.0.99

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Did you hit reset before hitting start again? (My guess is yes given you mentioned removing the filters which it needs to be reset for first but doesn't hurt to ask). Also did you accidentally change the redstone sensitivity of the miner? (Bottom right corner)

**Comment by HelpAccepted** [comment]
Yes I did hit the reset. The red stone functionality is disabled. It ran fine before and then I moved it and now it won't scan anything. Right now I have the filter to everything tagged with ore* in the ore dictionary.
![2021-06-28_14 30 08](https://user-images.githubusercontent.com/35672044/123686307-ab07d300-d81d-11eb-8c19-61b60d64dda6.png)
![2021-06-28_14 30 30](https://user-images.githubusercontent.com/35672044/123686308-aba06980-d81d-11eb-8439-afb16be015c6.png)

**Comment by pupnewfster** [comment]
You realize you have it set to only check y = 255 right? Set min to something like zero

**Comment by HelpAccepted** [comment]
I never touched that after I set it the first time. I think maybe when I reloaded the chunks that might've changed. I changed that and set it to 0 and it worked again but as soon as I reset it after it ran its operation it reset that number back to 255. I don't know why it does that but at least I know how to get it to work.
