### ISSUE TITLE
creative tank side config causes server crash 

### ISSUE THREAD

**Issue by Coop25** [mekanism/Mekanism#7255]
### Issue description

creative tank side config causes server crash 

### Steps to reproduce

1. Place creative gas tank
2. open ui on gas tank
3. go to side config
4. server crash

### Minecraft version

1.16.5

### Forge version

36.1.36

### Mekanism version

Current Dev Branch (Manually Compiled)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/X6NHRiwb

**Comment by pupnewfster** [comment]
I wasn't able to reproduce the crash, but I believe I just pushed a fix that should work around the cause of this issue so if you could test that would be great.

**Comment by CapturedCherry** [comment]
After the following fix I can no longer reproduce the above issues.
