### ISSUE TITLE
Mekanism Crash With Direwolf20

### ISSUE THREAD

**Issue by ravioliboy13** [mekanism/Mekanism#7256]
### Issue description

Mekanism seems to crash with direwolf20 1.12.2 and i cant figure it out but im not  that good with crash reports

### Steps to reproduce

1. Install direwolf20 1.12.2 latest
2. Install Mekanism
3. It should crash

### Minecraft version

1.15.x or earlier (No longer being developed)

### Forge version

14.23.5.2768

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/ravioliboy13/0fc0a7e3ea15d54dcb7c18ae9cb4c0e3

**Comment by pupnewfster** [comment]
You reached the max item or block id limit, either take some mods out or install a mod like Just Enough IDs.

**Comment by ravioliboy13** [comment]
ok thank you
