### ISSUE TITLE
Electrolytic Separator consumes more power than it should when speed upgrades are used

### ISSUE THREAD

**Issue by szikra** [mekanism/Mekanism#7257]
### Issue description

I noticed a massive power drain in my system which lead me to some investigation and testing the power consumption of my Electrolytic Separator. 

Now I know that Energy Upgrades do not affect the power consumption (which is the intended, documented behavior), and though that was my issue (and I posted a feature request about it https://github.com/mekanism/Mekanism-Feature-Requests/issues/262 ) that's not why I'm here. 
During the investigation I discovered a discrepancy between the documentation and the observed behavior concerning speed upgrades. 

The wiki (https://wiki.aidancbrady.com/wiki/Upgrades) says that power consumption should go up by a factor of 100 (for a 10 times speed increase) when 8 speed upgrade cards are used. It also says that the "EnergyMultiplier is a configurable multiplier that defaults to 10" (which would result 10^2=100 times power consumption)

But when I tested it, the power consumption of Electrolytic Separator doubled with every speed upgrade card.
From 400 to 800, 1.6k, 3.2k... 102.4k [J/t].
That's a 256 times increase and not a 100!

(I tested Electric Pump and it behaved as expected, went from 100J/t to 10kJ/t)

The https://wiki.aidancbrady.com/wiki/Electrolytic_Separator wiki page only says that "Electrolytic Separator requires 400 joules of power (J/t)." and that Energy Upgrades don't affect the machine's energy efficiency, but I haven't read anything about speed upgrades working differently than normal.
So I assume this is a bug.

### Steps to reproduce

1. place down an energy source (Creative Energy Cube)
2. then an Electrolytic Separator 
3. place a fluid tank (filled with water) in it 
4. optionally switch it to dump excess
5. observe energy usage [Using: 400 J/t]
6. place speed upgrade cards in it while observing power consumption [Using: 800 J/t]
7. repeat  [Using: 1.60 kJ/t], [Using: 3.20 kJ/t], [Using: 6.40 kJ/t] ... [Using: 102.40 kJ/t]

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.0

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
The separator and all other machines that operate in one tick have speed upgrades provide up to a 256x multiplier in efficiency.

**Comment by szikra** [comment]
The Digital Miner also says on the speed upgrade "Amount: 8/8" "Effect 256.0x" but I don't think it is. The Digital Miner wiki says it should have a 10x effect (and I'm pretty sure it does).

I don't know what "all other machines that operate in one tick" means ... "256x multiplier in efficiency." you mean 256x speed?
The pump only has 10x speed, which other machines have 256x? Is there a list somewhere? Am I looking at the wrong wiki?
