### ISSUE TITLE
Duplicate Fissile Fuel

### ISSUE THREAD

**Issue by D4RKTARGET** [mekanism/Mekanism#7258]
### Issue description

Issue: Able to duplicate infinite amounts of Fissile Fuel

### Steps to reproduce

1: Use any chemical tank
2: Set any side of the chemical tank to "Input/Output"
3: Use any pipe, connect it to the chemical tank but do not set the pipe to pull or push, keep it as normal
4: You should start to see the fuel in the pipe rapidly duplicate leading to an endless supply of fuel

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.32

### Mekanism version

10.0.21 (Latest)

**Comment by OstoraSiraj** [comment]
It's not working for me

**Comment by pupnewfster** [comment]
#7114
