### ISSUE TITLE
Pressurized tubes connect to each other on loading a saved world if one is empty

### ISSUE THREAD

**Issue by szikra** [mekanism/Mekanism#7259]
### Issue description

I made long pipelines with Ultimate Pressurized Tubes running side by side. 
They had different gases in them and I had no problem laying them. During processing the gases one (or two) got empty. I still had no problem, they were fine, empty tubes laying next to somewhat filled ones. 
But when I loaded my saved world today the empty tubes were connected to nearby tubes and got filled up with their gas.

I know you can configure tube faces with the configurator tool to not connect to each other (I used it a few places where I had to) but that would be way too much work for long stretches of tubes running along each other.
Is there a way to lock an entire length/section of tubes to a certain gas?

Because the empty tubes did not connect to nearby tubes when they got empty this leads me to believe that this is a bug and not a feature.

### Steps to reproduce

1. place 2 creative tanks (A,B) next to each other with different gasses in them
2. configure 'B' to output on top
3. make a tube line from 'A' starting from its front face
4. start a tube line on top of 'B' and bring it down next to line 'A' and continue the line side-by-side
5. remove tank 'B'
6. place empty creative tank next to line 'B'
7. wait for line 'B' to empty (not that nothing happens after, lines are not connected)
8. save and exit
9. load the world back in

now the tube lines are connected (without doing anything, besides loading the world)

Before save:
![image](https://user-images.githubusercontent.com/8597510/124362903-4fcc4b00-dc38-11eb-9acb-5aab397c9999.png)

After loading the save
![image](https://user-images.githubusercontent.com/8597510/124362868-15fb4480-dc38-11eb-8416-958d0a718fd6.png)

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.0

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
If one gets empty they merge. This is fully intended. If you don't want pipelines merging set the connecting between them to none. The only reason that they don't connect before hand is to avoid voiding the contents of one of the lines due to them being different but as soon as they are the same or one is empty and they can become the same they do so.

**Comment by szikra** [comment]
Then it is still a bug, because they do not merge when they become empty (as I have pointed it out at step 7).

**Comment by 0xAdachi** [comment]
what a stupid and annoying thing not to fix. is there no one smart enough to fix this annoying issue ?

**Comment by BijuuKrunos** [comment]
This is still a bug, thanks to that my fission reactor just exploded after 10 sec, after I joined the world again -.- Please fix!
