### ISSUE TITLE
Flux Network seems to have issues with Induction Matrix

### ISSUE THREAD

**Issue by Pultex** [mekanism/Mekanism#7261]
### Issue description

while using the flux network mod attached to the induction matrix frame rate drops over time if the power is not stable

### Steps to reproduce

1.Build two flux networks one to fill the matrix and one to draw from it

2 .attach multiple powered machines to the flux system,not the induction matrix, that do not run all at the same time

3. wait for some time and be in the same chunk that the induction matrix is in, the rate of power transfer should be fluctuating wildly from 0 to a large negative to a large positive every tick if the issue is happening even if the flux network shows stable

4. look at the induction matrix while the power it drawn from it

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.16

### Mekanism version

10.0.21 (Latest)

### Other relevant versions

FluxNetworks-1.16.5-6.1.7.12

also if you made logic with redstone to make the machine time to run all at once then the fps issue disappears 
only when the power is not steady does the fps and tp drop

did not let it crash but when the issue was happening the gui of the induction matrix would kick you out of it when opened 

only after breaking the connection from the two did the fps issue stop and the gui work as normal

**Comment by pupnewfster** [comment]
Is this one flux network or two? Because if this is one (and not a separate one for input/output) my best guess is that via flux networks it is transferring the power out of and then back into the matrix.

**Comment by soggythesausage** [comment]
can confirm this on purifying factory, energized smelter, enriching factory and basically all other mekanism machines

**Comment by MorningSage** [comment]
> 
> 
> Is this one flux network or two? Because if this is one (and not a separate one for input/output) my best guess is that via flux networks it is transferring the power out of and then back into the matrix.


> 
> 
> 1.Build two flux networks one to fill the matrix and one to draw from it

**Comment by pupnewfster** [comment]
Hmm out of curiosity does changing `config/Mekanism/general.toml`  > `general.energy_conversion.blacklistFluxNetworks` from `false` to `true` fix this (at least as a workaround)? That would force flux networks/mekanism to transfer energy via Forge Energy instead of FluxNetwork's extended version, and at least on Mekanism's end our conversions to FE have been tested against a lot of mods.
