### ISSUE TITLE
Free runner charge is depleted after hitting the ground on the "You died!" screen on a keep inventory world

### ISSUE THREAD

**Issue by alyxferrari** [mekanism/Mekanism#7264]
### Issue description

When using free runners in a keep inventory world, if you die in the air before hitting the ground, the free runners' charge still gets depleted. I assume this is unexpected behavior, but I could be wrong. I'd submit a pull request fixing it, but I couldn't find the charge depletion code after a bit of searching.

### Steps to reproduce

1. Start a survival world with cheats and keep inventory
2. Give yourself fully charged free runners and optionally, a jetpack
3. Fly up with the jetpack or fall from a height
4. Execute /kill before you hit the ground

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.0

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
Thanks for the report, and yes it is rather unexpected that the entity attack event still fires even when the entity is dead.
