### ISSUE TITLE
Chemical Infuser speed

### ISSUE THREAD

**Issue by GameAndMatch** [mekanism/Mekanism#7266]
### Issue description

The chemical infuser doesnt seem to benefit from speed upgrades.  This was an issue a few years ago but I am playing on ATM6 so the Mekanism version in use should be updated for that old issue.  It's possible the issue is coming from the electrolytic separator, as the two are connected (used for the ore quadrupling).

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.31

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
Do you have energy upgrades installed? If not the energy cost may just be more than you can supply.
