### ISSUE TITLE
Mekanism ores Conflict with thermal ores

### ISSUE THREAD

**Issue by AngelOfTheN1ght** [mekanism/Mekanism#7267]
### Issue description

I was playing the modpack with thermal and Mekanism and then when I go to heat up the copper miner from thermal, copper ore from Mekanism comes out.  I do not know what to do, I had never had this problem, I'm also playing with the official mekanism addons.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.32

### Mekanism version

10.0.21 (Latest)

### Other relevant versions

Generators: 10.0.21
Tools: 10.0.21

**Comment by AlexHgC** [comment]
Don't care about the visual, if copper have the same tag, you can use mekanism copper with thermal, if they don't have the same tag, you just have 2 different copper ores to mine, or use another machine from thermal to process ores

**Comment by toddlersizedsharkcage** [comment]
This is because of the modpack. Mekanism has no control over a thermal machine producing a mekanism item. If recipes are done properly in the modpack, you should be able to use mekanism copper for any recipe that calls for thermal copper.
