### ISSUE TITLE
Industrial Turbine Forming Without an Electromagnetic Coil

### ISSUE THREAD

**Issue by NotReviere** [mekanism/Mekanism#7268]
### Issue description

An Industrial Turbine can form without an electromagnetic coil which prompts a couple of issues.

1. Not really an issue, but an industrial turbine without a coil seems illogical.
2. The Industrial Turbine does not produce energy nor does it return the water rendering it basically useless.

Maybe at least 1 coil is needed for an Industrial Turbine to form.

### Steps to reproduce

1. Build an Industrial Turbine
2. Remove/Don't include the electromagnetic coils
3. Attempt to use the turbine

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.32
EDIT: Test was done on 36.1.0 but I'm assuming it's the same for 36.1.32

### Mekanism version

Current Dev Branch (Manually Compiled)

**Comment by toddlersizedsharkcage** [comment]
Forge version I tested is 36.1.0
