### ISSUE TITLE
Restrictive Transporter not restricting

### ISSUE THREAD

**Issue by lhill123** [mekanism/Mekanism#7270]
### Issue description

I am using All The Mods 6 on Minecraft v. 1.6.15. I have a digital miner running with it's output going to a chest. Coming out of the chest are 4 Logistical Transporters and a Restrictive Transporter. I have filters set on the Logistical Transporters to direct certain items to peripheral chests. It is my understanding that the Restrictive Transporter should only pass items which have no other route to leave the primary chest. However, some of the items specified in the Logistical Transporters' filters are passing through said transporters to the appropriate chests as intended, and some of the same items are passing through the Restrictive Transporter. For example, I have a Logical Transporter with a filter set to pass iron ore to a peripheral chest, which it does. However, not all of the iron ore goes through this Logistical Transporter. Some of the iron ore also passes through the Restrictive Transporter to it's connected chest.

### Minecraft version

1.16.5 (Latest)

### Forge version

CurseForge 0.177.1.5

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
Could you provide a picture of your setup?

**Comment by lhill123** [comment]
![2021-07-13_17 35 55](https://user-images.githubusercontent.com/87396657/125534617-06795957-e4d9-499c-86e3-42f337c6b46a.png)

**Comment by pupnewfster** [comment]
The restrictive transporter is the only path? That is why it is taken. The restrictive transporter adds a "cost" to a transporter path so that you can make certain branches have lower priority without having to make them excessively long given transporter pathfinding prioritize closest target. You have a chest and you have 5 things that are all trying to take stuff from it (in some potentially arbitrary order but each one is trying to take regardless of what the others are doing)

**Comment by lhill123** [comment]
How do I manipulate the "costs" so that the logistical transporters are accessed before the restrictive transporter?

**Comment by pupnewfster** [comment]
![image](https://user-images.githubusercontent.com/1203288/125535442-1c3ac13f-4659-458a-ae01-5d6870490605.png)

**Comment by lhill123** [comment]
I just realized the I was saying Logistical Transporter when I should have said Logistical Sorter, but I hope you realized that from the picture I uploaded. I would like to see the ability in the Logistical Sorter to invert each individual filter in order to create a black list of items and provide a higher degree of sorting.

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/3

**Comment by lhill123** [comment]
Is there currently a way, that I don't understand, to sort items like I am trying to do?

**Comment by lhill123** [comment]
The chest has four logistical sorters, each having a filter specifying one type of ore and leading to a peripheral chest. How do I make the four ores specified in the logistical sorters take those paths rather than the fifth path which passes everything else?

**Comment by pupnewfster** [comment]
I linked that feature request so if you wanted to you could subscribe to it so if it ever ends up getting implemented you will know. The way you could for now is by setting filters with allow default as false/disabled, and set a color for them. Then you place a transporter and color it to some different color and in the sorter on the main screen set it to that color and turn auto mode on.
