### ISSUE TITLE
QIO redstone adapter limiting does not immediately work when loading into a world.

### ISSUE THREAD

**Issue by CreativeAnarchy** [mekanism/Mekanism#7272]
### Issue description

I have several process automated.  All ores that can be 5x, enriched redstone, enriched carbon, steel, infused alloy.

I have them set to pull product from QIO storage.

I'm using a QIO redstone adapter on top of an exporter to limit the product into the machine, I have the QIO exporter redstone switch to inverted.

When I load in to the world, the system isn't preventing product from being placed into the machines.  A small batch will get processed of every automated process every time I load into the world.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.0

### Mekanism version

10.0.21 (Latest)

**Comment by CreativeAnarchy** [comment]
Additional info...

I forgot that I have 3 formulaic assemblicator with redstone switch to inverted with a QIO redstone to limit.  They work correctly and are not making anything extra when I load in the world.

So far, it seems to be limited to the QIO redstone adapter on a QIO exporter.

**Comment by pupnewfster** [comment]
Could you please provide some pictures/additional detail about how exactly the exporter and redstone adapter are set up (both in the GUIs and actual placement), as I am not able to reproduce this issue. Also is this on a server or in single player, and is the redstone adapter in the same chunk as the exporter?
