### ISSUE TITLE
infusing factory not accepting fuel

### ISSUE THREAD

**Issue by vhalras** [mekanism/Mekanism#7273]
### Issue description

i'm trying to make automation for all the alloys but my infusing factories do not accept any "fuel" unless fed manualy
i've tried using other machines but didn't work
i'v tried using chest and cable but alos dindn't work 
i'm out of idea and i'ts fustrating
sorry if my english is bad i'm not a native  speaker
in case it helpes here are screnshoot
![image](https://user-images.githubusercontent.com/75691376/126087313-1b1015ac-f4b9-4065-8bdf-c4ada11bbbcf.png)
![image](https://user-images.githubusercontent.com/75691376/126087382-0e3e42e4-65c1-4567-ac90-1c8b6563a3a1.png)
![image](https://user-images.githubusercontent.com/75691376/126087406-dbb0be9e-deac-4377-be70-baf501a74503.png)
![image](https://user-images.githubusercontent.com/75691376/126087391-012c1f59-54b4-4049-aba0-6a66d360a2a4.png)

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.31

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
To insert items into the slot that turns into infuse types you want the "extra" side config setting not input. As it isn't an input
