### ISSUE TITLE
Clicking the Sort Inv key while the cursor is in machines deletes the output items

### ISSUE THREAD

**Issue by BRuhMAnIJsutwantadownoad** [mekanism/Mekanism#7274]
### Issue description

Title

### Steps to reproduce

Open a machine
Put cursor in machine like around the output while items are in it
Tap the key which sorts items

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.32

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
Assuming that you don't mean the auto sort button on factories, I am going to go with report this to whatever mod is adding the ability to sort your inventory as if I had to guess it is not properly validating what can go in what slot and trying to do things it shouldn't be and deleting items that it failed to put elsewhere.
