### ISSUE TITLE
Single Player Restriction Should not be here

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [mekanism/Mekanism#7275]
### Issue description

As Player UUID Changes on Single Player, The Orignal UUID Owner is Lost.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.62

### Mekanism version

10.0.21 (Latest)

**Comment by thiakil** [comment]
Uhh, no it does not change

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
Yes. It Does, As Of Tlauncher. It Does Not Let Me Open Portable QIO, Even This is Single World.

**Comment by thiakil** [comment]
So buy minecraft
