### ISSUE TITLE
Chargepad Not Putting Out Much Power

### ISSUE THREAD

**Issue by DizzyDJW** [mekanism/Mekanism#7277]
### Issue description

Regardless of whether I place the Chargepad on an Ultimate Universal Cable attached to my MASSIVE system of over 500+ cables, (_of which are attached to my Induction Matrix with 1 Ultimate Provider and 1 Ultimate Cell_), or on top of a Quantum Entangloporter with the other attached directly to an output of the Induction Matrix, the Chargepad refuses to charge my Mekasuit at even 1/20th the speed that placing each piece directly into the Induction Matrix does.

I cannot find the cause for this, as even placing the Chargepad DIRECTLY on top of the output of the Induction Matrix has no noticeable difference. I believe the Chargepad needs an update with a MUCH higher output.

I shouldn't have to wait 2+ hours of real time to fully charge my max upgraded Mekasuit in the chargepad, and I shouldn't have to resort to taking each piece off and placing them into the Induction Matrix itself instead. Maybe the Chargepad needs to accept Energy and Speed Upgrades in the future?

### Steps to reproduce

1. Place a Chargepad on a large network of Ultimate Universal Cables or some massive power source.
2. Fully upgrade a Mekasuit with Max Energy Upgrades.
3. Stand on Chargepad.
4. Watch Chargepad trickle power into Mekasuit.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.31

### Mekanism version

10.0.21 (Latest)

**Comment by szikra** [comment]
LOL
I just wrote a comment (I mean finished writing, I started like 2 hour ago before your ticket was posted, but took a break and did some testing during :) for an other ticket (https://github.com/mekanism/Mekanism/issues/6786) and I fully agree: Chargepad is too slow.

**Comment by DizzyDJW** [comment]
Glad someone agrees lol

I've had to resort to using Flux Networks but it's not very Mekanism immersive to do so lol

**Comment by pupnewfster** [comment]
I adjusted the defaults slightly and gave a bit more configuration options to it but the chargepad is still going to be drastically slower at charging things with massive buffers like a mekasuit... There is no reasonable reason why a tiny plate would or should be able to charge something as fast as multiple ultimate induction providers.
