### ISSUE TITLE
Clicking "Show Recipes" in the Metallurgic Infuser just shows all recipes, not Infuser recipes

### ISSUE THREAD

**Issue by aaronhowser1** [mekanism/Mekanism#7278]
### Issue description

![image](https://user-images.githubusercontent.com/15698722/126917331-b70f2ea1-05f6-4e4f-8988-028377830864.png)
![image](https://user-images.githubusercontent.com/15698722/126917375-1cad8bee-aed0-421f-8330-2e5c4c8414e2.png)

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.61

### Mekanism version

10.0.21 (Latest)

**Comment by aaronhowser1** [comment]
Also holy shit, this is the fanciest github issue template I've seen in my life. Is that new?

**Comment by AlexHgC** [comment]
What version of JEI do you use ? Try to download the latest version [here](https://www.curseforge.com/minecraft/mc-mods/jei/download/3399829/file)

**Comment by aaronhowser1** [comment]
I'm using `jei-1.16.5-7.7.1.110`, and I can't update JEI at the moment as I don't have access to the server files right now.

**Comment by AlexHgC** [comment]
Okay so, i tried with **Mekanism10.0.21**, **Forge 36.1.61** and **JEI 110** and i have the same issue. After updating to **JEI115**, the issue is still there. After updating to the latest **Forge 36.2.1**, the problem is still here. I also tried with my personal game, with 10.1 build, and same problem here.

**Comment by AlexHgC** [comment]
Downgrading to **JEI 107** have fixed the issue. 108 and newer don't work. So, something on the 108 version have broken the recipe for infuser. This is not Mekanism related, so the only way to fix it actually is to downgrade JEI to `jei-1.16.5-7.7.1.107`

**Comment by mezz** [comment]
My mistake, I have a fix out in `jei-1.16.5-7.7.1.116`
