### ISSUE TITLE
Mekanism machine sounds playing over itself

### ISSUE THREAD

**Issue by ToatyBread** [mekanism/Mekanism#7280]
### Issue description

Im using Mekanism on a modded server I am hosting and when anyone uses (almost) any machine, the sound constantly plays every tick and plays even more sounds overtop of the currently playing sound. This makes it hard to use the machines without turning off the sounds altogether which I would prefer not to. 
This is happening with everyone on the server.

### Steps to reproduce

1. Place down any machine, such as a crusher.
2. Start the machine by placing items in it to make it work.
3. Sounds playing every tick, even when sound is already being played

### Minecraft version

1.16.5 (Latest)

### Forge version

36.1.65

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
Do you know if have any mods installed that change how sounds work/act? Or if you open a new instance with just mekanism in say single player or a local server are you able to reproduce it?

**Comment by ToatyBread** [comment]
Sorry for the wait, I have the sound filters mod installed and that is the only sound altering mod I know of.
I'll test out the thing you said.

**Comment by ToatyBread** [comment]
I just tested and it appears that the problem isn't Mekanism itself.

**Comment by pupnewfster** [comment]
Ya not sure what to say then, best bet is try mek with half of your other mods, then if it still doesn't happen try the other half and keep cutting them in two sets for mods to try until you narrow down which one is causing sounds to continuously restart./play on top of themselves.
