### ISSUE TITLE
Incorrect display of temperature in the Heat Graph of the Fission Reactor

### ISSUE THREAD

**Issue by Dimiral** [mekanism/Mekanism#7281]
### Issue description

I chose to display the temperature in Celsius, and in the Heat Graph it is always in Kelvin 
![MekIssue3](https://user-images.githubusercontent.com/31587426/127609806-4cc2842e-bedf-4221-98db-110d877f671b.png)

### Steps to reproduce

1. Build Fission Reactor
2. Choose a Celsius temperature
3. Look at Heat Graph

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
Hmm so I think there are actually two things going on here:
1. There is an issue with rounding at least slightly at larger numbers (way higher than this is at currently though and not what this is running into)
2. The heat graph isn't converting to the units you have selected and is just showing in Kelvin which is different than celcius by 273 and is why the temperature looks much higher.
