### ISSUE TITLE
Configurator wont mine cables faster

### ISSUE THREAD

**Issue by Imachicken29** [mekanism/Mekanism#7282]
### Issue description

Iv been trying for about 20 mins now figuring out how to mine these cables faster, I figured out I need to use the configurator set to wrench mode. But it doesn't mine them faster, I have tried right-clicking, shift+right clicking etc. but noting is working.

Im using 1.16.5 on the latest version of mekanism

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.21 (Latest)

**Comment by Seniorendi** [comment]
The atomic dissasembler is very fast

**Comment by pupnewfster** [comment]
Closing this as I can't reproduce it and the poster tried reproducing it with just mek and couldn't so this is most likely due to some weird mod interaction.

**Comment by kortregt** [comment]
do you have something in your offhand? I believe it needs to be free to wrench up the cables with shift+right-click
