### ISSUE TITLE
Basic universal cable fail to work after server restarting

### ISSUE THREAD

**Issue by HarryTsui313** [mekanism/Mekanism#7286]
### Issue description

Basic universal cable fails to work after server restarting
The cable is connected with the machines properly, yet the machine cannot receive any FE unless breaking the cable and replacing it. 

### Steps to reproduce

1.Turning off the server
2.Restart the server
3.Join the server and check the Mekanism machines and found that they are out of FE even with universal cables properly connected.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.21 (Latest)

### Other relevant versions

My mod pack used is All the Mods 6 
The version of the mod pack is 1.7.6 (lastest)

**Comment by pupnewfster** [comment]
Are portions of the cable not lit up?

**Comment by HarryTsui313** [comment]
All of them are lit. (in light green colour)

**Comment by pupnewfster** [comment]
Hmm, if you right click the cables with a network reader does it show it all as one network or as multiple networks/a smaller number than the number of cables there actually is.

**Comment by HarryTsui313** [comment]
![mek normal](https://user-images.githubusercontent.com/26271541/128602974-dad3ee68-7011-4097-9327-00c4da06bd1f.png)
This is the status before stopping the server. All cables are properly connected

![mek abnormal](https://user-images.githubusercontent.com/26271541/128603015-c3133433-4c89-4a84-8302-15ce6f5c3e75.png)
This is the status of the network after the server is restarted. Machines cannot receive FE properly.

**Comment by jaz0894** [comment]
I had the same issue. What I did is I added a lever closed to the main cable comming out of my energy source (matrix, cube, etc) and when the issue happens I push the lever on and off and the machines start working, would be the same if you remove a piece of cable and add it back again.  Still got no clue what is causing this so would be useful to know.

**Comment by pupnewfster** [comment]
Going to close this as I think it is relatively likely this is just the same issue as #6356 and there is not much sense in having two issues open relating to the same thing.
