### ISSUE TITLE
QIO and refined storage compatibility

### ISSUE THREAD

**Issue by jaz0894** [mekanism/Mekanism#7289]
### Issue description

Is it possible to add compatibility to the QIO with refined storage external storage?

I opened a ticket with them and the answer I got was that was being blocked on purpose.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
From the FAQ on our discord:

Q: Is there a way to connect the QIO to Refined Storage or Applied Energistics 2?
A: Currently no, we do not expose the QIO's inventory as an IItemHandler as not only would it be a headache to wrap into an IItemHandler it would be little more than a lag switch for players as "external storage" systems using IItemHandlers that RS/AE2 have native compat with scale really poorly with the more types of items there are. Mekanism's QIO was designed to be able to store mass amounts of items without causing lag. If someone wants to go ahead and implement the proper solution and make a compat addon between our QIO and either RS and/or AE2 that teaches the other system(s) how to read our advanced item cache, we are willing to help explain how our system works and move various parts of it to our API.
