### ISSUE TITLE
Teleporter only works in one Direction

### ISSUE THREAD

**Issue by KastenKlicker** [mekanism/Mekanism#7290]
### Issue description

I'm running a server on forge 1.16.5-36.2.2 with Mekanism 1.16.5-10.0.21.448. A friend of mine tries to teleport himself, in one Direction works but in the other Direction it says the teleporter are not linked.
The server throws the following debug message:
`[Mekanism TileComponentChunkLoader/]: Attempting to remove 0 chunk tickets. Pos: BlockPos{x=-271, y=60, z=162} World: minecraft:overworld`

He says it's working in his Singleplayer world.

### Steps to reproduce

1. Build both teleporter
2. Set them to one frequency
3. Teleport yourself
4. Try to teleport back -> not working

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.21 (Latest)

**Comment by AlexHgC** [comment]
Do you have anchor upgrade on both teleporter to load the chunk where the teleporter is ?

**Comment by KastenKlicker** [comment]
The anchor upgrade solved the problem. Thank you for your help!
