### ISSUE TITLE
Configuration Card won't paste configurations to different factory tiers 

### ISSUE THREAD

**Issue by Lordfirespeed** [mekanism/Mekanism#7291]
### Issue description

Copying configuration from basic factory, upgrading factory block to advanced/elite/ultimate, then attempting to paste the configuration fails due to blocks not being recognised as being able to accept the configuration.

### Steps to reproduce

1) Copy configuration from configured basic enriching factory by shift-right-clicking on the factory with a configuration card
2) Attempt to paste configuration to a 'default' advanced enriching factory.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
That is more or less intended, *but* is implemented as part of https://github.com/mekanism/Mekanism-Feature-Requests/issues/133 for Mekanism 10.1 when that ends up being released.
