### ISSUE TITLE
Mekanism crash in loading

### ISSUE THREAD

**Issue by TomBoxCZ** [mekanism/Mekanism#7292]
### Issue description

Hello,
I installed mekanism, but every time I start the game it starts loading and after the first loading phase the game shuts down and throws me this error.

"The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: codechicken/lib/packet/PacketCustom$ICustomPacketHandler
Exit Code: -1"

Thank you for your help TomBoxCZ

### Minecraft version

1.15.x or earlier (No longer being developed)

### Forge version

10.13.4.1614

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/vcuwiLfS

**Comment by toddlersizedsharkcage** [comment]
Do you have ForgeMultipart-1.7.10-1.2.0.345-universal.jar installed?

**Comment by AlexHgC** [comment]
![image](https://user-images.githubusercontent.com/31996023/129941380-dd7de42c-4309-4915-8496-3064e0f096d7.png)

As you can see, you have something wrong with ForgeMultipart, where have you downloaded the jar ? Curseforge ?

**Comment by TomBoxCZ** [comment]
Yeah i downloaded it.
