### ISSUE TITLE
Duplicate of copper with "Ice and Fire: Dragons" mod.

### ISSUE THREAD

**Issue by SierraDT** [mekanism/Mekanism#7293]
### Issue description

Not sure which mod made a mistake in here so will report for both. While using the Mekanism and Ice and Fire mods together (which is quiet an odd combination), there are two copper ores in the world.  One of them (I think the Ice and Fire one) seems to be very rare and the second one more common. It seems that they can be used in same recipes, but the ingots are slightly different color from each ore, and thus they cannot be used together in one recipe.

Edit: Added screenshots. I did a lot of changes to the modpack after a while and now I am not sure it if actually didn't work with different copper ingots, but now it works. Out of all the copper I can craft Ice and Fire armor for example, or a copper block which is always the one from mekanism, no other choices. I am fairly new to this and as I mentioned below in a reply, It feels like it would be logical to merge all the ores in one, so I think that the current state of this is unacceptable. But if that's not considered as an issue...

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.21 (Latest)

![2021-08-19_14 27 31](https://user-images.githubusercontent.com/64656577/130061114-f69b4759-b97d-473a-8fa5-9dbfba32ef4e.png)
![2021-08-19_14 33 49](https://user-images.githubusercontent.com/64656577/130061803-c6392fb1-33d2-4c74-b1f9-875c1e8412ba.png)

**Comment by thiakil** [comment]
Please provide examples of things that don't work.

It's not likely to be Mekanism because our metals use Tags correctly, and so do our recipes.

Likely I&F doesn't have them tagged correctly, or more likely the recipe you're trying doesn't accept the tagged item correctly

**Comment by SierraDT** [comment]
> Please provide examples of things that don't work.
> 
> It's not likely to be Mekanism because our metals use Tags correctly, and so do our recipes.
> 
> Likely I&F doesn't have them tagged correctly, or more likely the recipe you're trying doesn't accept the tagged item correctly

Screenshot added. Also didn't notice the third variation of copper from Create. I am not really sure how it is supposed to work. Like if there is copper from three mods wouldn't it be better if it was merged automatically in one of those? Cause if not, it's just annoying then.

**Comment by thiakil** [comment]
Your second screenshot shows it working perfectly fine. If a recipe doesn't support mixing like that, report it to that mod (or pack if it's non-standard)

**Comment by SierraDT** [comment]
> Your second screenshot shows it working perfectly fine. If a recipe doesn't support mixing like that, report it to that mod (or pack if it's non-standard)

I also edited the report, as I said I am kinda new to this and I don't think that having 3 separate ores just to be used as a single one at the end is ok. Using trees in such a way is cool, having different colors and such. Using 3 different coppers for a single result at the end is useless.

**Comment by thiakil** [comment]
There are mods to do that unification, but they're also often kind of hacky. It's not as easy as you think and is quite normal for moddes minecraft.

Merging them is out of scope for an individual tech mod

**Comment by AlexHgC** [comment]
Also, you can change ore spawn on config file for each mod, so you can choose to spawn only one copper type if you want
