### ISSUE TITLE
mine colonies raids bypass the suits energy shield and do direct damage. is this a bug?

### ISSUE THREAD

**Issue by virass21** [mekanism/Mekanism#7300]
### Issue description

while i am defending against minecolonies raids the archers are doing direct damage to me and the suits shields are not functioning. other mobs work fine though. is this intended or is this a bug?

### Minecraft version

1.16.5 (Latest)

### Forge version

0.181.1.15

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
No, we respect the fact that minecolonies declares their damage as bypassing armor.
