### ISSUE TITLE
Digital Miner Mining non AE2 Drives Feature or Bug?

### ISSUE THREAD

**Issue by s3ptum** [mekanism/Mekanism#7305]
### Issue description

BUG: When ME Drive is in range of mining area of Digital Miner, ME Drive is broken and Storage Cells are dumped on to ground.

Opinion: A "miner" should only mine resource blocks, not machines.

If this is a feature then it has potential to lose players tens of thousands of items like it did me.
Also, if above is a feature then documentation needs to be much clearer.

### Steps to reproduce

1. Place ME Drive.
2. Place Digital miner so mining range encompasses ME Drive.
3. Filter for Mod ID "Applied Energistics 2".
4. Apply power and start
5. Notice ME Drive disappear.

In my instance drive ended up in ME system because miner was dumping directly to it.

### Minecraft version

1.15.x or earlier (No longer being developed)

### Forge version

14.23.2854

### Mekanism version

Older

### Other relevant versions

Applied Energistics 2 rv-6-stable-7

**Comment by pupnewfster** [comment]
If it is mining AE2 blocks then you have your miner's filter targetting to target said blocks... So just don't do that?
