### ISSUE TITLE
Miner Tag Filter Error

### ISSUE THREAD

**Issue by cdrobinson** [mekanism/Mekanism#7306]
### Issue description

When using a digital miner, logs are being mined when the tag filter of *ores* is used. 

![image](https://user-images.githubusercontent.com/5030972/132247050-3fc1882b-7665-43ed-83b2-70db9db6d4ac.png)
![image](https://user-images.githubusercontent.com/5030972/132247061-14350fe3-bdaf-4536-a33f-ed1072372f01.png)

You can even see logs showing up in the filter preview: 
![image](https://user-images.githubusercontent.com/5030972/132247128-49784f33-28ef-4f81-9a3a-a2a1d7d5f65f.png)

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
Use a dictionary drag a log into it from JEI and switch from items to blocks. There is a tag is matching your search string that contains logs. Best bet is just use a more specific filter.
