### ISSUE TITLE
Cable capacity buffer visually disappearing in alternate dimensions

### ISSUE THREAD

**Issue by kalkafox** [mekanism/Mekanism#7310]
### Issue description

This issue does not occur in the Overworld.

Reproduced using only Mekanism as the loaded mod. In any dimension other than the Overworld, if a piece of connected cable with a buffer is broken, the visual capacity on the cable stops working indefinitely (the cable network itself still functions and ticks, however). This bug persists until the world is reloaded in singleplayer, or rejoining in multiplayer

[Here](https://user-images.githubusercontent.com/9144208/134239243-63647bca-8f9a-4378-bcd6-6f1a03d1e315.mp4) is a documented demo of the circumstance.

### Steps to reproduce

1. Launch Minecraft with Mekanism
2. Load into a dimension that is NOT the Overworld
3. Place down any inventory with a Mekanism-compatible buffer (water, gas, etc.)
4. Place down cables and configure it to properly output
5. Break a single cable off the network to reproduce the aforementioned above.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.5

### Mekanism version

10.0.21 (Latest)

**Comment by kalkafox** [comment]
UPDATE: I'm not able to reproduce this in `10.1` dev, but some additional testing can be done relating to this and if so, I will happily re-open this issue with my findings.

Cheers.

**Comment by pupnewfster** [comment]
Ah that just reminded me of the fact that when we switched to mojmap in the 10.1 branch I noticed one of the methods we were using for figuring out what players to send the content update packet to was using the wrong method, so when we fixed that it was this issue it was fixing.
