### ISSUE TITLE
Digital Miner

### ISSUE THREAD

**Issue by sorimicro9** [mekanism/Mekanism#7311]
### Issue description

digital miner is overridden

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.5

### Mekanism version

10.0.21 (Latest)

**Comment by toddlersizedsharkcage** [comment]
https://www.google.com/url?sa=i&url=https%3A%2F%2Fglobalnews.ca%2Fnews%2F5938632%2Fblinking-white-guy-reaction-gif-ms-research%2F&psig=AOvVaw2qSItAq2QVTRhhqjIqdHqI&ust=1632421892259000&source=images&cd=vfe&ved=0CAsQjRxqFwoTCJD7zsubk_MCFQAAAAAdAAAAABAD

**Comment by toddlersizedsharkcage** [comment]
![image](https://user-images.githubusercontent.com/59610016/134401434-37bb10a8-2fd9-4522-95ac-c73e6815f8a3.png)

**Comment by Seniorendi** [comment]
What do you mean with "overridden"

**Comment by Seniorendi** [comment]
Well
