### ISSUE TITLE
quantum entangloporter

### ISSUE THREAD

**Issue by Limkanimka** [mekanism/Mekanism#7314]
### Issue description

V: Mekanism-1.16.5-10.0.21.448.jar 

I play with a friend on the server, before that they transferred energy to the miner, but at some point he stopped working. He no longer transfers items or anything else (checked)

restarting the server didn’t help
however in single player it works

there were no errors
just at some point it stopped working and that's it

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.21 (Latest)

**Comment by AlexHgC** [comment]
You need Anchor Upgrade on both QE to make QE chunkloaded

**Comment by Limkanimka** [comment]
They were installed

after some time I crafted 2 new quantum entangloporter and they already worked

the two cubes that were before still did not work
(although there was an anchor, the network was created, all sides were set up correctly and energy was also present)
so we decided to just delete them

I suppose the issue can be closed since there was no error in the logs and I can not provide additional information

**Comment by Limkanimka** [comment]
> You need Anchor Upgrade on both QE to make QE chunkloaded
