### ISSUE TITLE
The digital miner is not working in my multiplayer server

### ISSUE THREAD

**Issue by NxarkNxark** [mekanism/Mekanism#7320]
### Issue description

I recently created a server with aternos to play with my friend, i downloaded lots of mods, etc... and at some point i tested the Digital Miner, and it just don't work, the configs are fine and everything is supposed to work but it don't, i tried in singleplayer and it works perfectly, the problem is probably one of my mods but i don't know wich one is causing this problem.
Here is the list of my mods (except some mods that i added after the problem with the digital miner), not sure if someone can help me but i didn't find anything about that on google.

Thanks.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.21 (Latest)

### Other relevant versions

[Mod list.txt](https://github.com/mekanism/Mekanism/files/7280279/Mod.list.txt)

**Comment by AlexHgC** [comment]
Can you send some screen please, config GUI, main GUI, and Upgrades GUI.

Do you have generated the World Map before adding mekanism ?

**Comment by NxarkNxark** [comment]
Oh wait, i don't understand why or how, i litteraly didn't do anything, i just opened the server to take the screens and it just started working suddently and then stopped working again, i am really confused but here's the screens (The tag is *Ores in the config GUI and in the Main GUI the Digital Miner is on)

![Config](https://user-images.githubusercontent.com/91837775/135903942-b4f4949a-8c12-4bee-9e76-bd8d0ac099ad.PNG)
![Main Gui on](https://user-images.githubusercontent.com/91837775/135903944-840c576d-44c5-4945-8198-b9981dbc09ac.PNG)
![Upgrades Gui](https://user-images.githubusercontent.com/91837775/135903945-8e856d57-3f31-4a8a-876d-5562e1273ff8.PNG)

**Comment by toddlersizedsharkcage** [comment]
If it's *Ores and not *ores, change it.  It's case sensitive.

**Comment by AlexHgC** [comment]
First, you can go UP to 32 radius if you want. Second, try to add Anchor Upgrade to have the chunk loaded. 

Can you try with *iron + Anchor upgrade + 32 radius ?

**Comment by NxarkNxark** [comment]
Well, it was the *Ores that was causing problems, and honestly it's really strange cause i tried with both *Ores and *ores but i didn't work and now it works, i'm confused as hell but thanks anyway !
