### ISSUE TITLE
issue with crafttweaker 

### ISSUE THREAD

**Issue by Nessuno6** [mekanism/Mekanism#7328]
### Issue description

reproduce this recipe

### Steps to reproduce

{
  "type": "mekanism:nucleosynthesizing",
  "itemInput": item:avaritia:infinity_catalyst,
  "gasInput": mekanism:gas_stack_antimatter,
  "output": item:storagedrawers:creative_vending_upgrade,
  "duration": 500
}

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.8

### Mekanism version

10.0.21 (Latest)

**Comment by AlexHgC** [comment]
V10 doesn't support CrT, V10.1 will
