### ISSUE TITLE
PRC Stopping production of HDPE Pellets 

### ISSUE THREAD

**Issue by xanderhunter** [mekanism/Mekanism#7329]
### Issue description

Attempting to get HDPE Sheets for a singularity in Oceanblock 1.3, and the PRC randomly stops producing.  Still have full inputs full but the progress bar stops.  Replacing the block and flipping the redstone modes do nothing.  Making a new one lets it run for a little bit but then bugs out.
![HDPE Pellet Bug](https://user-images.githubusercontent.com/11369206/137829003-04d40f9e-ea6e-4be6-a482-d4ee975b1a70.png)
 

### Steps to reproduce

1. Place PRC and set up inputs and outputs.
2. Let PRC run for a while.
3. PRC breaks.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.8

### Mekanism version

10.0.21 (Latest)

**Comment by pupnewfster** [comment]
What upgrades do you have installed in the PRC?
