### ISSUE TITLE
PRC stops creating HDPE when more than 1 Speed Upgrade Module is in place

### ISSUE THREAD

**Issue by Clayh0814** [mekanism/Mekanism#7334]
### Issue description

HDPE production will PAUSE or not start reacting when putting in two or more speed upgrades into the Pressurized Reaction Chamber. 
With only one speed upgrade it works fine.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.8

### Mekanism version

10.0.22 (Latest)

### Other relevant versions

ATM6 1.8.8 (latest at time of writing)

**Comment by AlexHgC** [comment]
That's not an issue, you just need to put energy upgrades to increase buffer size. If the machine need 1kfe/t but have only 500fe buffer, it make sense that it doesn't work, so just add energy upgrades 👌
