### ISSUE TITLE
Infinity Backpack upgrade bug

### ISSUE THREAD

**Issue by Brindial** [mekanism/Mekanism#7335]
### Issue description

When placing an entry level Infinity Backpack (2048 Items) into the Induction Matrix for charging, you get a max level Infinity Backpack (67,000,000+ items) back. I have done this multiple times to verify.

### Steps to reproduce

1. Craft an entry level Infinity Backpack.
2. Place in Induction Matrix to charge.
3. Get the max level Infinity backpack back.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.28

### Mekanism version

10.0.23 (Latest)

**Comment by pupnewfster** [comment]
I have no idea how the infinity backpack works, but this feels more like an industrial foregoing bug given we just interact with the energy capability they provide.

**Comment by Brindial** [comment]
Thank you for the response. I will check some more and post under their site :-)
