### ISSUE TITLE
Disconnecting pipes from each other makes pipe not register to network

### ISSUE THREAD

**Issue by Ashley123477** [mekanism/Mekanism#7336]
### Issue description

Upon changing it so that two pipes do not connect, the pipes no longer connect to a network

### Steps to reproduce

Import from a chest to another inventory
Do the same again right next to the first
Disconnect the pipes from connecting to each other

### Minecraft version

1.16.5 (Latest)

### Forge version

1.16.5 - 36.2.9

### Mekanism version

10.0.23 (Latest)

**Comment by AlexHgC** [comment]
I can confirm this issue, here is a video :

https://user-images.githubusercontent.com/31996023/140544008-3eb5a300-bcba-4b73-a6f4-a2cf2ebba4d9.mp4

**Comment by pupnewfster** [comment]
This should be fixed in 10.0.24 which has now been released.

**Comment by Seniorendi** [comment]
fast fix
