### ISSUE TITLE
Formulaic Assembler don't use reusable item again

### ISSUE THREAD

**Issue by TagonZ** [mekanism/Mekanism#7340]
### Issue description

There is a pipe which supply all required mats for crafting Flour (from Pam's HarvestCraft Mod) which require 1 Wheat and 1 Mortar & Pestle (no durability but reusable).
First craft is always successfully, so the Flour is sent to the Bin, a that another item just stay there and cant be reused (as on screenshot)

Stock control and Auto craft is ON
[Screenshot of setup](https://i.imgur.com/vB6VrTu.png)

### Minecraft version

1.15.x or earlier (No longer being developed)

### Forge version

forge-1.12.2-14.23.5.2855

### Mekanism version

Older

**Comment by Seniorendi** [comment]
Should be fixed in the newest mekanism version.
1.12 is not longer supported.
