### ISSUE TITLE
Mekanism api is not launching

### ISSUE THREAD

**Issue by LongBaton191158** [mekanism/Mekanism#7341]
### Issue description

:When I put the mekanism in the mods list the server crashes, but when I see in the crash report that the mekanism api is giving an error message:

 java.lang.NullPointerException
 
 Complete Log: https://mclo.gs/rBWj6Tf

### Minecraft version

1.16.5 (Latest)

### Forge version

mohistmc:36.2.9

### Mekanism version

10.0.21

**Comment by AlexHgC** [comment]
iirc OpenJ9 isn't compatible with forge and you use it. And you use Mohist, a modified version of forge, some other people have similar issues with Mohist

**Comment by pupnewfster** [comment]
Can you reproduce this without OpenJ9 and if so can you reproduce this without Mohist as well?

**Comment by LongBaton191158** [comment]
> Can you reproduce this without OpenJ9 and if so can you reproduce this without Mohist as well?

Log  without Open J9: https://mclo.gs/F4c60I7

**Comment by AlexHgC** [comment]
Can you send the crash-report too ?

**Comment by LongBaton191158** [comment]
I switched to the lastest 1.16.5 Forge but keeps crashing

Crash Report: https://mclo.gs/esUKPLa

**Comment by pupnewfster** [comment]
> Mod File lemonlib-1.3.6.jar needs language provider javafml:36 or above to load
There are a bunch of these ^. Your mods want 1.16.5, you are using 1.16.4

**Comment by LongBaton191158** [comment]
I put forge version 1.16.5 with java 11 but it keeps crashing 

Log: https://mclo.gs/4SArH34

crash report: https://mclo.gs/hT62JzC

**Comment by pupnewfster** [comment]
> Mod File: industrial-foregoing-1.16.5-3.2.14.7-16.jar
 Failure message: Mod industrialforegoing requires forge 36.2.8 or above
 Currently, forge is 36.2.0

Industrial foregoing requires a newer version of forge than you are using.

**Comment by LongBaton191158** [comment]
> > Mod File lemonlib-1.3.6.jar needs language provider javafml:36 or above to load
> 
> There are a bunch of these ^. Your mods want 1.16.5, you are using 1.16.4

**Comment by pupnewfster** [comment]
Yes and one of the mods you are needing requires a newer version of forge for 1.16.5 it requires forge 36.2.8 or higher and you are using forge 36.2.0.

**Comment by LongBaton191158** [comment]
I took the industrial Foregoing mod but it still crashes 

log: https://mclo.gs/81VUBqT

crash report: https://mclo.gs/cgIiLQX

**Comment by pupnewfster** [comment]
> Failure message: Curios API (curios) encountered an error during the common_setup event phase
 java.lang.OutOfMemoryError: Metaspace

I believe you ran out of memory but your best bet is to ask either on the forge discord in the tech support channel or one of the general modded mc discords that offer support such as MMD as this has nothing to do with Mekanism
