### ISSUE TITLE
Crash with mekanismgenerators:electromagnetic_coil

### ISSUE THREAD

**Issue by ApollonSys** [mekanism/Mekanism#7342]
### Issue description

I was playing Minecraft, with optifine with a shader, and just went to the Mek tab and crashed because of the item being rendered "mekanismgenerators:electromagnetic_coil". It didn't matter what version of optifine or which shader I used. I don't know why it happened now.

### Steps to reproduce

1. Have Optifine for 1.16.5 ( I was using the latest one for it)
2. Put on any shader
3. go to mek tab and if no crash try to scroll down till you do.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.24 (Latest)

### Other relevant versions

OptiFine_1.16.5_HD_U_G8
and basically any shader.

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/ApollonSys/590b04b47f6c75aca6e3ea7271b42dba

**Comment by pupnewfster** [comment]
Report to optifine. Also looks more like it is optifine having issues with CTM than with Mek

**Comment by AlexHgC** [comment]
Feel free to give à try with Optifine G7 and not G8, G8 have a way more bugs than G7
