### ISSUE TITLE
Configurator in wrench mode dupes Cyclic Cables

### ISSUE THREAD

**Issue by JakeMoe** [mekanism/Mekanism#7343]
### Issue description

Not sure which side this is on (Mekanism or Cyclic), but if I try to remove Cyclic Cables with the Configurator in wrench mode, it gives me the cable but also leaves the cable behind with the connection configs changed, i.e., it looks like it's changing the connections.  If I have a cable that connects a chest to a machine, and I shift-right-click the cable on a non-connected side, the cable changes to push / pull, and if I look in chat, I can see messages saying that it's changed.

If I just right-click the block (without shift) with the Configurator in wrench mode, it also changes the connections, but doesn't dupe the cable.

### Steps to reproduce

Put Configurator into wrench mode
Shift-right-click a Cyclic Cable

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.2

### Mekanism version

10.0.21

### Other relevant versions

Am running the mod in the FTB DireWolf20 1.16 modpack, version of Cyclic in the pack is Cyclic-1.16.5-4.0.5.2.

**Comment by pupnewfster** [comment]
I am going to take a guess and say it is on their end as our configurator doesn't have any specific "wrench" logic (it is our blocks that have specific logic that react to the configurator being in wrench mode).
