### ISSUE TITLE
Wind generator working underwater

### ISSUE THREAD

**Issue by Porcy** [mekanism/Mekanism#7344]
### Issue description

As title says. I don't think this should be the case

### Steps to reproduce

Place wind generator under water.
Get power.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.9

### Mekanism version

10.0.24 (Latest)

**Comment by pupnewfster** [comment]
By under water do you just mean the bottom block or is the entire thing under water?

**Comment by Porcy** [comment]
The entire thi
![2021-11-22_19 15 09](https://user-images.githubusercontent.com/8096340/142959182-97a23ea5-24d8-442b-a572-d6e788dc41b0.png)
ng

**Comment by pupnewfster** [comment]
One more thing, what is the y value of the blocks there? The main reason I am asking is if memory serves vanilla treats water as "air" for purposes of checking if it can see the sky at above 64 blocks or so (though I could always add in at least some partial checks to see if it is waterlogged and fail then).

**Comment by Porcy** [comment]
y:94. But it works also at y:37
![2021-11-22_21 01 13](https://user-images.githubusercontent.com/8096340/142961120-7987ba58-b2bf-4434-9da8-12e57057cc6e.png)

**Comment by pupnewfster** [comment]
Are you able to reproduce this with just Mekanism and Mekanism Generators? I tried to reproduce this and I am not able to reproduce this issue so I feel like you may have some coremod installed that is changing how vanilla's can block see sky method works.

**Comment by Porcy** [comment]
It's on FTB Oceanblock, Better Diving might be the culprit as it heavily changes water behavior / properties. Didn't test only with Mekanism / Mekanism Generators.

**Comment by pupnewfster** [comment]
I am unable to produce this with just mekanism and better diving so the best bet might be to report it to the Oceanblock pack devs and see if they can track down which mod is changing how `canSeeSky` works. In the meantime though I will add a little bit of extra protection against this case in particular by ensuring the top of the generator isn't fluid logged.
