### ISSUE TITLE
Невозможно переработать ядерные отходы

### ISSUE THREAD

**Issue by Razvedka2020** [mekanism/Mekanism#7345]
### Issue description

Одиночная игра. Невозможно переработать ядерные отходы в солнечном активаторе, так как он не принимает их через герметичную трубу. Вручную так же невозможно, так как газовые баллоны тоже не принимают ядерные отходы.

Single player game. It is not possible to recycle nuclear waste in a solar activator as it does not accept it through a sealed tube. It is also impossible manually, since gas cylinders also do not accept nuclear waste.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.24 (Latest)

**Comment by pupnewfster** [comment]
Solar Neutron Activators input through the bottom and output through the front. My guess is you are trying to insert the waste through the front instead of underneath?

**Comment by Razvedka2020** [comment]
Спасибо за совет\замечание. Сейчас нет возможности проверить это, но вы правы, я подключил солнечный активатор с задней стороны. Почему газовые баллоны не принимают ядерные отходы? Ведь в творческом режиме есть газовый баллон с ядерными отходами...

Thanks for the advice / remark. There is no way to check this now, but you are right, I connected the solar activator from the back. Why are gas cylinders not accepting nuclear waste? After all, in creative mode there is a gas cylinder of nuclear waste ...

**Comment by pupnewfster** [comment]
Assuming you mean chemical tanks those are purposes of making testing things in creative easier, you can only store radioactive chemicals in waste barrels.

**Comment by Razvedka2020** [comment]
Спасибо за помощь и разъяснение.

Thanks for the help and clarification.
