### ISSUE TITLE
Mekanism Combiner Auto Input

### ISSUE THREAD

**Issue by rich0952** [mekanism/Mekanism#7350]
### Issue description

The combiner only accepts an auto input for the top slot. I am using emerald dust and cobblestone in the combiner to make emerald ores, but the combiner only automatically accepts emerald dust. Using the crusher, my emeralds become emerald dust that are automatically inputted into the combiner using logistic pipes from mekanism. I then tried to put stone into the crusher (and make cobblestone) to automatically have that outputted into the combiner but the combiner doesn't accept it. I didn't change any piping between doing the emeralds. I have tried hoppers, mekanism pipes, and putting the crusher next to the combiner to see if that would work. 

### Steps to reproduce

1. Get a combiner, emerald dust, and cobblestone. Also get a form of item transport - mekanism logistical pipes, a hopper, etc.
2. Place the combiner (and power it) and use the hopper/pipes to transfer the emerald dust and cobblestone into the combiner.
3. Watch the combiner only accept emerald dust (top slot of combiner) but not the cobblestone (bottom slot of combiner).
4. Cry. Profusely.

### Minecraft version

1.16.5 (Latest)

### Forge version

1.16.5 Forge 36.2.0

### Mekanism version

10.0.24 (Latest)

### Other relevant versions

No

**Comment by toddlersizedsharkcage** [comment]
Have you set the side config for items to yellow where you want the cobble to go in?  Cobble would be the "extra" item, and extra is yellow in the items config.

**Comment by toddlersizedsharkcage** [comment]
![image](https://user-images.githubusercontent.com/59610016/143881431-d8cde77a-a623-4756-a9dd-63160205b4e6.png)

**Comment by pupnewfster** [comment]
As shark has said cobblestone goes in the extra slot of the side config.

**Comment by toddlersizedsharkcage** [comment]
Further support will be easier on Discord if you need it:
https://discord.gg/nmSjMGc
