### ISSUE TITLE
Creative Energy Cube - Can't add Charge?

### ISSUE THREAD

**Issue by ArkavianX** [mekanism/Mekanism#7352]
### Issue description

ATM6 - To The Sky 

Built an creative energy cube, everything I've done to add some charge is flat out ignored.

I have tested Ultimate cube, it does work, surprisingly I had enough for the creative one, yet does not work.  

### Steps to reproduce

ATM Sky
Build Creative E-Cube, try to add power....

### Minecraft version

1.16.5 (Latest)

### Forge version

Curseforge ATM6 TTS Pack 

### Mekanism version

10.0.21

**Comment by toddlersizedsharkcage** [comment]
The full creative cube send infinite power, won't accept power.  The empty creative cube is a power sink and will not hold power you send to it.  It's for testing purposes only.

**Comment by pupnewfster** [comment]
^ As shark said it is fully intended empty = power sink, full = infinite power. If some modpack is adding a very expensive recipe for it I don't really know why given most modpacks that add recipes for creative stuff also has various types of trash cans but you are better off asking them why they did that as we have no idea.

**Comment by ArkavianX** [comment]
That irritatingly make sense, cost 4x vibranium blocks to make...
