### ISSUE TITLE
Diversion Transporter redstone sensitivity changes when configuring pull from adjacent chest

### ISSUE THREAD

**Issue by mjevans** [mekanism/Mekanism#7353]
### Issue description

Pack: Enigmatica 6 - Nov 2nd.
mods/Mekanism-1.16.5-10.0.22.449.jar
mods/MekanismGenerators-1.16.5-10.0.22.449.jar
mods/MekanismTools-1.16.5-10.0.22.449.jar

I'm trying to use a Diversion Transporter to react to a redstone signal in an adjacent block to pull items from a chest.

Literally it's a line: trash can - Diversion Transporter - chest + 1 solid block above the Diversion Transporter which will be activated by a button or lever.

If I remove the chest to clearly see the face of the Diversion Transporter that the chest will be against I can alter the redstone sensitivity mode of that face and set it to Active with signal; which is printed in the chat console.

Next I re-place the chest against the Diversion Transporter; it does not connect by default when in this mode.

Now I need to use shift+right click again to get the Diversion Transporter into 'pull items' mode from the chest; but this also changes the Active with signal setting to 'active without signal'.

If I instead try to anticipate the forward shift by one by leaving it 'Always Active' the Diversion Transporter will default to pulling items from the chest, when I go to configure the face I am _only_ able to cycle the operation type between Push/Pull/None.

As far as I can tell while middle-mouse wheel scrolling the Configurator it does not have a dedicated mode for Redstone Control nor for Directionality.

Bug:
Inconsistent Diversion Transporter behavior as outlined above; were it consistent I might be able to deduce a way around the issue.

Suggested fixes / improvements:

Add Configurator modes for Redstone Control and Directionality (push/pull/none but could be more).

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.4

### Mekanism version

10.0.22

**Comment by pupnewfster** [comment]
Hmm not sure if there is a good way about this but I will try to look into it. Though I am guessing as a "workaround" you might be able to just apply a redstone signal and then adjust the pull mode when it is out or make it so it is out configure pull it will remember it and then remove the chest and change the redstone mode.

**Comment by mjevans** [comment]
Reviewing, this appears to work ONLY if there's a redstone signal applied during the setup procedure.

Importantly, for someone who's never used a Diversion Transporter before this, the visual behavior does not indicate that it is linked to the chest if it is removed.

I was expecting something more like E.G. how Thermal whatever used to work, where there was a visual change in color (like redstone off to redstone on) when operating.  I did not expect the pipe to vanish entirely when the signal was removed, which seriously confounds the initial setup for a button driven block I had been going for.

**Comment by pupnewfster** [comment]
After messing around with this some locally I think the changes I am going to make which should make the diversion transporter a bit easier to figure out how to use:
- Switch configuring redstone sensitivity of it from sneak right click against an empty face to just right clicking (similar to how other transmitter types have their redstone sensitivity toggled by just normal right clicking)
- Allow targeting the "connection" pieces with this right click so that the redstone sensitivity can be changed without requiring removing the block on a given face
