### ISSUE TITLE
Digital Miner causing lags if jumping

### ISSUE THREAD

**Issue by Kirame1717** [mekanism/Mekanism#7359]
### Issue description

If you stand near the digital miner and jump, you get short freezes (Doesnt happen when using hovermode and flying up and down

https://user-images.githubusercontent.com/95510533/144726834-c7435ee8-e36a-48d3-9d8e-dffc20755abb.mp4

)

### Steps to reproduce

1. Step infront of the digital miner
2. Jump

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.0

### Mekanism version

10.0.24 (Latest)

**Comment by pupnewfster** [comment]
I will leave this open for now to see if anyone else can reproduce this, but at least personally I am unable to reproduce this issue. Every fifty or so jumps I get the frame time graph to spike into barely red which it does at times in my test world regardless of what I am looking at I think purely just to how much stuff is in it.
