### ISSUE TITLE
Mekasuit charge levels not updating until suit piece is removed

### ISSUE THREAD

**Issue by Liam-Ryan** [mekanism/Mekanism#7360]
### Issue description

Mod Pack - Valhelsia 3, 1.16.5 via curseforge. No other mods installed 

Expected Behaviour - when charging or taking damage the charge level of the mekasuit is updated in 
1) Top left of HUD
2) HUD to left and right of health bars showing armour charge level
3) In player inventory in equipped slots

Actual Behaviour - Taking damage or charging the suit shows the charge level remains unchanged until I remove a piece of armour from inventory at which point all armour updates the charge level

### Steps to reproduce

1. Equip full mekasuit in Valhelsia 3
2. Take damage - observe no UI charge level updates and hovering over mekasuit pieces shows full charge
3. remove a piece of armour with the mouse - observe updated charge levels in UI and UI text

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.8

### Mekanism version

10.0.22

### Other relevant versions

Modpack shows Mekanism 10.0.22.449 for Mekanism, Mekanism Additions, Mekanism Generators and Mekanism Tools

**Comment by pupnewfster** [comment]
Best guess is this might be related to #7224, so I am closing it as a duplicate for now
