### ISSUE TITLE
Server Crash by Piston

### ISSUE THREAD

**Issue by ikarosu** [mekanism/Mekanism#7363]
### Issue description

活塞使酿造台移动，连接到物流管道时，服务器崩溃
Translate:
Piston moves the brewing table and crashes the server when connected to the logistics pipeline.

### Steps to reproduce

![QQ截图20211215142816](https://user-images.githubusercontent.com/10465428/146135042-3baf31f0-44f0-4114-9bee-411fe30c9938.png)

如果此时活塞收回，服务器将崩溃
Translate:
If the piston is retracted at this point, the server will crash.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.19

### Mekanism version

10.0.24 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/ikarosu/4bc7fcf2af193a0854dc304c8b6cab00#file-crash-2021-12-15_14-22-03-server-txt

**Comment by pupnewfster** [comment]
Report to quark looks like the crash is on their end.
