### ISSUE TITLE
Misc dynamic tank capacity issues

### ISSUE THREAD

**Issue by alyxferrari** [mekanism/Mekanism#7366]
### Issue description

Empty Dynamic Tanks updated to their new 10.1 capacities on my Mekanism world, but tanks with fluid already in them stayed at their old 10.0 capacity. I tried draining one of my full tanks and the capacity updated to the new 10.1 capacity when it hit 0 mB. The even weirder part is that when I reconnected my input pipes, the capacity went back to the 10.0 capacity. [I have a screen recording of this issue here](https://drive.google.com/file/d/1OxA_gqmD9NhvGuzGZ6txqLePKoUu6Tnt/view?usp=sharing).

### Steps to reproduce

Fill a tank on Mekanism 10.0.x
Load the world in 10.1
Play around with the contents and observe the capacity

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.0 (Latest)

**Comment by alyxferrari** [comment]
Thought I should add this, I also tried reforming the multiblock, but that didn't change anything.

**Comment by alyxferrari** [comment]
Didn't regenerate my configs.

**Comment by alyxferrari** [comment]
Quit Minecraft, deleted `.minecraft/configs`, opened my world, and the issue persists.

**Comment by pupnewfster** [comment]
Aha! I figured out the confusion. Basically chemicals and fluids have two different capacities in the dynamic tank (similar to how their tanks are different). So when it is empty it is showing the chemical tank's capacity and otherwise once it has water in it it shows the fluid capacity (which is still higher than it was in 10.0.x.

**Comment by alyxferrari** [comment]
Ah, thanks. Didn't know dynamic tanks could hold gases. No more rotary condensentrators for me I guess lol
