### ISSUE TITLE
Game crash (error) in 1.7.1

### ISSUE THREAD

**Issue by amatunana** [mekanism/Mekanism#7369]
### Issue description

When I try to play the game with the Mekanism mod in 1.7.10, it crashes.
The following file is the crash report.

[crash report.txt](https://github.com/mekanism/Mekanism/files/7774308/crash.report.txt)

### Steps to reproduce

I put Forge 1.7.10-10.13.4.1614 in Minecraft version 1.7.10 and installed Mekanism
Mekanism Tools.

Then you will be able to start Mikla.

After a while, the software crashes and returns to unchart.

### Minecraft version

1.15.x or earlier (No longer being developed)

### Forge version

10.13.4.1614

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

[crash report.txt](https://github.com/mekanism/Mekanism/files/7774308/crash.report.txt)

**Comment by AlexHgC** [comment]
Because 1.7.10 need Forge Multiparts mod

**Comment by Seniorendi** [comment]
Yes
And 1.7.10 is not supported anymore.
You need this mod: https://www.curseforge.com/minecraft/mc-mods/forge-multi-part

**Comment by amatunana** [comment]
It worked!
Thank you for your ministry!
