### ISSUE TITLE
Digital Miner in 1.16.5 not working

### ISSUE THREAD

**Issue by Lewyfcb9pro** [mekanism/Mekanism#7370]
### Issue description

Well when I try to set the digital miner to ore* in 1.16.5 it just doesn't work but in 1.12.2 it works normally . I expect the digital miner just to mine the ores.

### Steps to reproduce

1. (1.16.5) place it down and in the tags config write ore*
2. it doesn't work when it starts

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.20

### Mekanism version

10.0.24

**Comment by Matyrobbrt** [comment]
Did you try using the tag `forge:ores`

**Comment by AlexHgC** [comment]
1.16 don't use the same system, * is now before like *ores *diamond *gold...

**Comment by Lewyfcb9pro** [comment]
oh thanks

**Comment by pupnewfster** [comment]
More accurately: `forge:ores/type` or `forge:ores`/`forge:ores*`

**Comment by Lewyfcb9pro** [comment]
ok
