### ISSUE TITLE
Geiger unit not working

### ISSUE THREAD

**Issue by rob-katt** [mekanism/Mekanism#7373]
### Issue description

I might just be doing somthing really wrong but for me the Geiger unit just doesent work but the Geiger counter works just fine

### Steps to reproduce

1. make reactor go boom so you have radiation
2. check the radioation levels with the mek suit and notice it doesent work
3. use the Geiger counter becuase it works

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.0 (Latest)

**Comment by AlexHgC** [comment]
Is it turned on ?

**Comment by rob-katt** [comment]
yup and its displays 99.99nsv

**Comment by beholderface** [comment]
It's working just fine on my end. 
I just created a fresh profile (curseforge app) with all Mek modules, hwyla, and CTM.

https://i.imgur.com/IWgD6Lz.png

**Comment by pupnewfster** [comment]
Best guess is that it might not be working on a dedicated server.

**Comment by AlexHgC** [comment]
I can confirm it, the geiger unit not working on dedicated server : 

![image](https://user-images.githubusercontent.com/31996023/147679158-87a6265c-a236-4bc0-a133-75cec556934e.png)

**Comment by rob-katt** [comment]
oh well then i know i didnt do anything wrong
