### ISSUE TITLE
MekaSuit filtration unit effect immunity remains after disabling unit and completely unequipping suit, and also seems to apply immunity to the wrong effects

### ISSUE THREAD

**Issue by TinyDeskEngineer06** [mekanism/Mekanism#7374]
### Issue description

I have a full MekaSuit with the filtration unit on the helmet, and am trying to give myself Regeneration, but when I use a potion, the effect isn't applied. It also gives me an error when I use /effect. I also tried Strength, another beneficial effect, and it works fine. I never set the module to remove beneficial effects, and also set it to not remove neutral effects, so it's most likely that Regeneration was accidentally marked as a negative effect, or something along the lines of that.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.20

### Mekanism version

10.0.24

**Comment by pupnewfster** [comment]
What sort of error do you get when you use `/effect` and could you provide your latest log especially assuming it is like "an internal error occurred". My best guess is that you have some other mod screwing with effects as I am unable to reproduce this.
