### ISSUE TITLE
QIO Crafting Transfer Handler doesn't use space in QIO

### ISSUE THREAD

**Issue by AlexHgC** [mekanism/Mekanism#7376]
### Issue description

When you change the crafting recipe in the QIO, it will send old recipe items in your inventory. As Pupnewster said, it's designed to use the QIO inventory if player inventory is full, but this isn't the case, JEI just say "Inventory is full", so you have to empty your inventory.

Here is a video :

https://user-images.githubusercontent.com/31996023/147879463-a89ff1a1-98b1-4e58-a93f-2c5071ac5086.mp4

### Steps to reproduce

1. Add some blocks in your inventory
2. does some crafting recipe with different items
3. JEI will say " inventory full" and can't change the recipe

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.1 (Latest)

### Other relevant versions

**Tested on server**

**Comment by pupnewfster** [comment]
I can't reproduce this, but I will leave it open for now so that I remember to look into it in more depth sometime in 1.18 as maybe I will notice some error in the code that makes it be more cautious at times than it should be.

**Comment by WolfSleep** [comment]
Currently having the same issue.

**Comment by pupnewfster** [comment]
Finally was able to reproduce it, and it seems to only happen for portable dashboards, and that is because they don't actually tell the client any information about the frequency... not sure of the best way to fix it, but I definitely agree it is a nuisance.
