### ISSUE TITLE
Chemical injection Chamber gas uses

### ISSUE THREAD

**Issue by jamesjimmy88** [mekanism/Mekanism#7377]
### Issue description

The Chemical Injection Chamber has two issues:
- The recipes use less gas than expected, in a seemingly random amount, (around 180 mB out of the 200 mB expected by the recipes)
- The amount of gas used increases when the machine is using speed upgrades. This is in contrast with the Osmium Compressor, which always uses the same amount of gas regardless of the amount of speed upgrades.
Both issues are present both in the basic machine and in the factory variants

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.1 (Latest)

**Comment by jamesjimmy88** [comment]
The same issues appear with both the Purification Chamber and its factory counterparts

**Comment by pupnewfster** [comment]
I *believe* this is intended <https://github.com/mekanism/Mekanism/blob/1.16.x/src/main/java/mekanism/common/tile/prefab/TileEntityAdvancedElectricMachine.java#L97-L99>. I have no idea why they use a statistical mechanic as that is from long before I joined the dev team all I know is that they do.

**Comment by jamesjimmy88** [comment]
Isn't this issue kinda the same as [this ](https://github.com/mekanism/Mekanism/issues/7309) one that was recenty fixed?
The Osmium Compressor now always uses 200 mB of Liquid Osmium, regardless of the amount of installed speed upgrades. I expected the same behaviour for the Chemical Injection Chamber and the Purification Chamber, which are now the only machines that still act in unpredictable ways.

**Comment by thiakil** [comment]
Seems to be working as expected
