### ISSUE TITLE
Speed upgrades' energy consumption scaling is way too high for some machines

### ISSUE THREAD

**Issue by jamesjimmy88** [mekanism/Mekanism#7378]
[EDIT: the issue isn't actually in the storage]
### Issue description

There are two main issues with the default energy values:
- Some machines have an Energy Storage that's waaaay too small for them to be fully used with the max amount of speed upgrades:
[EDITED: I got the value for the Isotopic Centrifuge wrong]
Pigment Mixer, Isotopic Centrifuge, Chemical Infuser and Chemical Washer: energy use: 5,12 MJ/t - energy storage: 80kJ
Rotary Condensentrator: energy use: 1,28 MJ/t - energy storage: 20kJ
The above values are expressed in Joules - the energy use refers to a machine with 8 Speed Upgrades and no Energy Upgrades.
- The default energy usage of the Pressurized Reaction Chamber is 5 J/t; I'm pretty sure there's a missing digit or two in there, since the most basic machines like the Metallurgic Infuser and the Energized Smelter use 50 J/t

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.1 (Latest)

**Comment by AlexHgC** [comment]
> * Some machines have an Energy Storage that's waaaay too small for them to be fully used with the max amount of speed upgrades:

This is why Energy upgrades exist.. They don't only reduce the energy usage, but increase the energy buffer too

**Comment by jamesjimmy88** [comment]
I'm aware of it, but I think that upgrades shouldn't require other upgrades to be able to work properly.
After looking at it again I noticed that I got it wrong and the issue is not the storage size, but on the energy consumption scaling: other machines, when upgraded with 8 speed upgrades, consume 100 times more energy compared to their un-upgraded counterparts The only exception I noticed is the Electrolytic separator, which uses a factor of 256 (doubles with every installed upgrade). The machines listed above instead consume 25600 times more power (or 10000 more times in the case of the Isotopic Centrifuge), which is way too much.

**Comment by AlexHgC** [comment]
This is how the scaling is designed, and in my opinion, everything is fine with the actual scale, the mod is really not hard. 
But if you don't like it, ofc all things you have mentionned here ( energy consumption / scale with upgrades / buffer ) can be changed in config files !

**Comment by jamesjimmy88** [comment]
There's no way that it's a design choice. Every other machine in the mod scales in the exact same way, with the only exception being the Electrolytic Separator - which **has** to behave differently because of the way hydrogen is treated, which is basically a way to store energy.
Those machines have no reason to be the exception to the rule. And even if they were, there's no consistency - The Chemical Infuser and the Chemical Washer have that scaling, but the Chemical Dissolution Chamber, the Chemical Crystallizer and the Chemical Oxidizer (all being parts of the 5x ore processing chain) do not?

Those five machines, even with 8 energy upgrades, still consume 512 kJ/t / 200 kJ/t / 128 kJ/t - for comparison, a fully upgraded (speed and energy) Ultimate Factory that's parallel processing 9 items consumes 4,5 kJ/t - you know, more than a hundred times less. Is this fine in your opinion? Is the Pressurized Reaction Chamber using 5 J/t also fine?

Lastly, the scaling of the upgrades is not configurable... you can change the factor of upgrades, but not the scaling of the energy consumption given by speed upgrades.......

**Comment by Seniorendi** [comment]
I don't really see the issue in here.
It's supposed that you use energy upgrades with speed upgrades in some environments.

**Comment by jamesjimmy88** [comment]
Since apparently I can't get my point across I'll provide more numbers:
- Pigment Mixer, Isotopic Centrifuge, Chemical Infuser and Chemical Washer:
base energy consumption: 200 J/t out of a machine storage of 80 kJ (ratio: 0,25%)
with 8 speed upgrades: 5,12 MJ/t (but actually only uses 80 kJ/t, since it's what the machine's buffer can hold)
with 8 speed upgrades and 8 energy upgrades: 512 kJ/t, out of a machine storage of 800 kJ (energy buffer needed: 64%)
- Rotary Condensentrator:
base energy consumption: 50 J/t out of a machine storage of 20 kJ (ratio: 0,25%)
with 8 speed upgrades: 1,28 MJ/t (but actually only uses 20 kJ/t, since it's what the machine's buffer can hold)
with 8 speed upgrades and 8 energy upgrades: 128 kJ/t, out of a machine storage of 200 kJ (energy buffer needed: 64%)
**If we compare the energy consumption values of the machine with and without upgrades we can get 25600 (5120000/200 or 1280000/50), which is around 3,5566^8**

And since some people see this as normal, I also went and created an instance on 1.12 to check what the values used to be, and guess what? The rates for the same machines are way lower:
- Rotary Condensentrator:
base energy consumption: 50 J/t out of a machine storage of 20 kJ (ratio: 0,25%) - same as in 1.16
with 8 speed upgrades: 12,8 kJ/t - **one hundredth of the value found in 1.16**
with 8 speed upgrades and 8 energy upgrades: 1,28 kJ/t, out of a machine storage of 200 kJ (energy buffer needed: 0,64%)
- Chemical Washer:
base energy consumption: 200 J/t out of a machine storage of 80 kJ (ratio: 0,25%) - same as in 1.16
with 8 speed upgrades: 51,2 kJ/t - **again, one hundredth of the value found in 1.16**
with 8 speed upgrades and 8 energy upgrades: 5,12 kJ/t, out of a machine storage of 800 kJ (ratio: 0,64%)
**Doing the same calculation as above: 12800/50 or 51200/200 equals 256, which is 2^8**

Now let's compared this to most other machines (with the exception being the Electrolytic Separator):
- As an example, but they all scale the same way: Ultimate purifying Factory (while processing 9 items):
base energy consumption: 1800 J/t out of a machine storage of 360 kJ (ratio: 0,5%)
with 8 speed upgrades: 180 kJ/t
with 8 speed upgrades and 8 energy upgrades: 18 kJ/t, out of a machine storage of 3,6 MJ (energy buffer needed: 0,5%)
**Doing the same calculation as above: 180000/1800 = 100, which is around 1,7782^8**

in the 1.16 version of the mod the Electrolytic separator seems to be the only machine that has a multiplier of 2, but it is also the only machine that has no downsides to the installation of Speed Upgrades, since they also increase the production rate by the same amount, meaning that there's zero efficiency loss at all levels - energy upgrades also work differently, by only increasing the machine's energy buffer. There's a valid reason for upgrades behaving differently for the Electrolytic Separator though, because Hydrogen in Mekanism is basically a way to store power.

My guess is that the multiplier is supposed to be 1,777 like it is for all the other machines except the Electrolytic Separator, but during the port that value got somehow doubled for those machines - meaning that with 8 speed upgrades the energy consumption multiplier should be 100 but instead it's 25600.
Just so you have the full picture:
1,7777^8 = 100 (all other machines except the Electrolytic Separator)
2^8 = 256 (Electrolytic Separator)
3,5555^8 = 25600 (The machines that are the subject of this issue)

And before somebody else mentions Energy Upgrades: they can only reduce the final cost by a factor of 10, meaning that the final cost multiplier would still be 2560x, which is just ridiculous, expecially when considering that every other machine, when fully upgraded, will have a energy cost multiplier of 10x but since it will also work 10x faster it means that there is no efficiency loss, because the final cost for processing a recipe will be the same. In no case a fully upgraded machine should be 2560 times worse than its unupgraded counterpart, expecially not in a mod that has zero efficiency losses when fully upgrading machines.

**Comment by jonasKoehler** [comment]
Just want to say that i agree with you on the inconsistent design. It hurts the player expirience imo. But alas its up to the mod author to rethink that design approach or if major rebalancing, changing calculations and testing is too much of a hassle.

**Comment by Boolyman** [comment]
I love the upgrade costs... they really give the player a reason to build large energy producers... instead of just making a Bio Gen setup and coasting on 10k FE/t forever.

**Comment by thiakil** [comment]
> Some machines have an Energy Storage that's waaaay too small for them to be fully used with the max amount of speed upgrades

This is intentional.

> The default energy usage of the Pressurized Reaction Chamber is 5 J/t; I'm pretty sure there's a missing digit or two in there, since the most basic machines like the Metallurgic Infuser and the Energized Smelter use 50 J/t

The PRC usage varies by recipe

As for things not being perfectly "consistent", I don't really see why they need to be given different machines have different processes and reasons for energy usage. I'm really not understanding why it _needs_ to change.

**Comment by jamesjimmy88** [comment]
The big issue I'm having is that the efficiency loss provided by the speed upgrades appears to be 10 times too high:
- Normally, applying 10 speed upgrades increases the total cost of machine operations by 10 times while also increasing the speed by the same factor, meaning that there's a 90% energy efficiency loss, that is brought down to 0% if you install energy upgrades.
- For those machines the cost per operation is instead increased by 100 times, bringing the energy consumption rate up by 25600 times ,meaning that there's a 99% energy efficiency loss, or 90% if you install energy upgrades.
Just so you know, this started because I wanted an experience that's closer to a factory sim by completely disabling energy upgrades so that energy production is actually a significant part of the system, but the harsher efficiency losses for those machines make things way too hard. I can't really fix this with configs or recipe editing.

Regarding the need of energy upgrades to fully use speed upgrades: I'm complaining so much against it because a past patch increased the energy storage of machines _specifically_ to fix this (an Electrolytic Separator with 8 speed and zero energy upgrades consumes 102.4 kJ/t, out of a 160 kJ energy storage - before the patch the energy storage used to be 40 kJ, and had exactly this issue). I'm not 100% sure, but I remember that other machines (maybe factories) were also affected by the patch. It's really not a big deal because I can simply increase the energy storage via configs, but I still think that by default the need of energy upgrades shouldn't be a thing anymore, epecially not after a patch that specifically removed it - well, it's not up to me to decide.

Regarding the PRC: Several recipes only specify a duration, not the energy cost - when they don't, the machine uses the default config value, which is 5 J/t

**Comment by Aevaris** [comment]
IIRC, i think i saw this on the wiki or in a past issue ticket. The electrolytic separator is intentionally different by design to avoid allowing you infinite energy by separating water to hydrogen at a fairly early game point. As others have mentioned, if you'd like to customize it, it can be done in config though :)

**Comment by clarketronics** [comment]
Considering the  Electrolytic Separator is splitting apart liquids (usually water) and that requires huge amounts of energy i don't see it as that much of an issue
