### ISSUE TITLE
Pumping RFTools dimlets from a chest to a cabinet manager creates massive tick lag 

### ISSUE THREAD

**Issue by Peca21** [mekanism/Mekanism#7380]
### Issue description

Using an ultimate transporter to move dimlets from a chest to a cabinet manager (from [Storage Cabinets](https://www.curseforge.com/minecraft/mc-mods/storage-cabinet)) creates tick time spikes up to 50ms (from 10ms).
Not sure if this is a problem in mekanism or cabinet mod, feel free to close this if I am wrong.
Screenshot of tick times:
![2022-01-03_01 33 03](https://user-images.githubusercontent.com/13818400/147951544-1ec7dd76-93a0-498a-8638-0a0beff3f836.png)

### Steps to reproduce

1. Place down a cabinet manager and two cabinets
2. Connect the manager with the chest using transporter pipes
3. Pull from chest
4. Lag spikes

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.1 (Latest)

**Comment by Peca21** [comment]
Also happens with translocators
https://github.com/TheCBProject/Translocators/issues/76

**Comment by pupnewfster** [comment]
Given how other mods also have this issues I am pretty sure this likely is due to the item handler implementation is storage cabinets and there is nothing we can do on our end related to it.
