### ISSUE TITLE
Logistical transporter pipes dropping items on ground.

### ISSUE THREAD

**Issue by Toximisity** [mekanism/Mekanism#7381]
### Issue description

So, as the title says, im having issues of random amounts between 5 and 6 items dropping out of elite transporter pipes, while piping them into some netherite furnaces from the iron furnaces mod. The furnaces are almost always bouncing between mid 50s and low 60s in their input slot, so every time i go back over to the array of furnaces after a certain amount of time, they'll throw them onto the ground. 

### Steps to reproduce

1.Place a machine that processes the item, like furnaces. (Not getting this issue with inventories that just hold items)
2.Setup a pipe to insert, and another to output. (The output pipe never bugs, but the system needs to be continuous)
3. Have it run constantly, usually every 10-20 minutes, it'll spit out about that amount of items. 

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.20

### Mekanism version

10.0.22

**Comment by pupnewfster** [comment]
Try updating to 10.1.1 (I would make a backup of your world first in case you need to downgrade for some reason), as I am pretty sure this has been fixed in 10.1.0

**Comment by Toximisity** [comment]
Will test that, im currently playing cuboid outpost, so as soon as i finish my current mini project, i will try updating, and get back to you.

**Comment by Toximisity** [comment]
That did fix it, thank you for the info, i was unaware this was a patched thing, i guess i didn't look hard enough for the info. My bad.
