### ISSUE TITLE
Main inventory of QIO doesn't work with JEI when pressing R or U

### ISSUE THREAD

**Issue by TheOwnerOfThis** [mekanism/Mekanism#7384]
### Issue description

The main inventory of the QIO still doesn't work with JEI when pressing R or U

### Steps to reproduce

1. Open QIO
2. Press R or U on any item in the inventory
3. Notice how JEI does nothing

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.1 (Latest)

### Other relevant versions

JEI 7.7.1.139

**Comment by Th3Fanbus** [comment]
Hmmm, I can use R/U if I make sure the search bar isn't selected. It would be nice to be able to not autofocus the search bar. I am using `Mekanism-1.16.5-10.1.1.456.jar` and `jei-1.16.5-7.7.1.145.jar` with `Forge 36.2.26`.

**Comment by Th3Fanbus** [comment]
Oh, sorry, I misread you. Indeed, pressing R/U **on the main inventory of QIO** does nothing.
