### ISSUE TITLE
bypass protected areas

### ISSUE THREAD

**Issue by joaoespanhol** [mekanism/Mekanism#7386]
### Issue description

The following items from the list below, bypass redprotect and worldguard protections, thus allowing players who are not allowed to interact with protected areas to break the item.

Example:
cardboard, digital miner, laser

### Steps to reproduce

Install plugin redprotect and worldguard

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.1 (Latest)

**Comment by pupnewfster** [comment]
All of those mods fire the block break event (as the player who owns them) to check if they can be break blocks in a given spot. If they can take it up with those mods for not actually using forge's event?

**Comment by Seniorendi** [comment]
Worldguard is a spigot/sponge plugin. So it does not use the forge events.

**Comment by pupnewfster** [comment]
Unless they stopped having forge versions... it has had a forge version for a long time as well. https://www.curseforge.com/minecraft/mc-mods/worldedit

**Comment by joaoespanhol** [comment]
> A menos que eles tenham deixado de ter versões forjadas ... já há muito tempo que existe uma versão forjada. https://www.curseforge.com/minecraft/mc-mods/worldedit
> 
> Edit: Você disse WorldGuard, não WorldEdit, mas, de qualquer forma, use qualquer software de servidor híbrido que estiver usando, é mais provável que esteja neles.

redprotect is no work, you need check.

**Comment by pupnewfster** [comment]
Either use forge instead of sponge or mohist or whatever other hybrid hack you are using or report the issue to them.
