### ISSUE TITLE
Mobs spawn inside the Supercritical Phase Shifter

### ISSUE THREAD

**Issue by Boolyman** [mekanism/Mekanism#7391]
### Issue description

Mobs spawn inside the Supercritical Phase Shifter

### Minecraft version

1.16.5 (Latest)

### Forge version

wgrrhbeaqf

### Mekanism version

10.1.1 (Latest)

**Comment by Seniorendi** [comment]
I think you forgot the forge version

**Comment by pupnewfster** [comment]
> It's unavoidable. Put some torches around it to avoid it. Endermen will still teleport into things like the SPS and turbine, but they can't place blocks. The mobs shouldn't affect the functionality of either of those.

In theory multiblocks should not allow mobs to *spawn* in them as of 10.0.some high number, so for 10.1.1 this shouldn't be possible unless I accidentally messed something up that I will look at when I get a chance.

**Comment by pupnewfster** [comment]
Unable to reproduce.
