### ISSUE TITLE
[1.18.x] How to build the repo documentation and resolving third-party dependencies error

### ISSUE THREAD

**Issue by FrederickEngelhardt** [mekanism/Mekanism#7392]
### Issue description

Hi all,

I attempted to build 1.18.x to test but was unable to build it. Running into an error with ./gradlew not being able to resolve third party dependencies. 

I have java 17 on a macos. Curious if there are steps missing and/or if documentation needs to be updated on build process.

Also, is this issue because the dependencies do not exist for 1.18.x for some of these libs (or need to be manually built locally)?

Example
```
Cause 2: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find ilikewoodxbiomesoplenty:ilikewoodxbiomesoplenty-1.18.1:7.1.0.
Searched in the following locations:
```

### Steps to reproduce

1. `brew install --cask temurin`
2. set java home to java 17 path. `JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home`
3. Clone the mekanism repo.
4. Run ./gradlew build
5. Errors with dependencies not being resolved in gradle caches.

### Minecraft version

1.18.1 (Latest)

### Forge version

39.0.14

### Mekanism version

Current Dev Branch (Manually Compiled)

**Comment by pupnewfster** [comment]
Some of the libs do need to be manually built currently and even modified manually though I have been working to simplify it some. But basically at the moment your best bet is likely to wait or you can try to figure it out on your own, but support is not being given for the 1.18 version yet as it isn't out yet.
