### ISSUE TITLE
Null pointer crash when breaking and placing a fusion reactor block too quickly (1.16 and 1.18)

### ISSUE THREAD

**Issue by toddlersizedsharkcage** [mekanism/Mekanism#7394]
### Issue description

Reported by beholderface, and I verified.  Null pointer crash when breaking and placing a fusion reactor block too quickly. I am going to attach a video of the issue along with the reported crash and crash logs.  Single player. The block placed can be a port, reactor glass, or fusion reactor frame.  EDIT: removed comments stating this only happens with a block adjacent to a matrix.

### Steps to reproduce

Quickly break and replace blocks on a fusion reactor.  The reactor is formed before doing this.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.19, 39.0.20

### Mekanism version

10.1.1 (Latest)

### Other relevant versions

Latest 1.18 build from GitHub
Happens with some basic mods installed, but nothing that should be game breaking (TOP, CTM, JEI, etc.)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/MWp1qCEZ https://pastebin.com/yRmzucSF

**Comment by toddlersizedsharkcage** [comment]
https://user-images.githubusercontent.com/59610016/149629184-0aceadff-14a2-4860-a153-24f3522f7d09.mp4

1.16 crash screen:
![image](https://user-images.githubusercontent.com/59610016/149629199-aec3aff0-68d8-4162-a4f3-d4ae709d76e5.png)

1.18 crash screen:
![image](https://user-images.githubusercontent.com/59610016/149629204-674e4c3e-a77e-4ea7-b4b8-6d1c60f64886.png)

**Comment by beholderface** [comment]
Just tried it, it still crashed for me when using a non-matrix side

**Comment by pupnewfster** [comment]
Not able to reproduce this, BUT I can see from the stack trace why it is potentially crashing so I will add a null check to it.
