### ISSUE TITLE
Crash with Wind Generator

### ISSUE THREAD

**Issue by chaseyrt** [mekanism/Mekanism#7395]
### Issue description

Placed the wind generator, and the Client crashed, but the Server didn't. Only seems to crash when the generator is generating power, and not when the buffer is full. We did have a crash earlier related to sound issues with another mod.

### Steps to reproduce

1. Place Wind Generator
2. Profit?

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.23

### Mekanism version

10.1.1 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/zSGrsGaf

**Comment by beholderface** [comment]
I think you should try disabling Sodium, since skimming the crash log seems to indicate that this is a rendering issue, and Sodium is heavy on rendering optimizations and stuff like that

**Comment by pupnewfster** [comment]
Yeah this definitely looks like a sodium crash
