### ISSUE TITLE
Items in storage bins being overridden/duplicated 

### ISSUE THREAD

**Issue by Hiby227** [mekanism/Mekanism#7396]
### Issue description

When upgrading bins using QIO crafting it dose not care what the bin is that you are upgrading if it is auto filed out of the QIO storage into the crafting window. It will always craft the first bin including its internal storage and disregards the contents of the bin that is being upgraded into it which can easily be used for duplication of items.

### Steps to reproduce

https://user-images.githubusercontent.com/97855322/149679945-16f9e81c-2ad5-4aee-bcad-8277695e6bad.mp4

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.21

### Mekanism version

10.1.1 (Latest)

**Comment by Seniorendi** [comment]
Wonderful

**Comment by wacaser2** [comment]
So I can confirm that it exists in the version of 10.1 I'm on. It's also worse than was described. It doesn't need to be autofilled from qio, it just uses the output from when it first matches the recipe(with the qio crafting window, didn't try the vanilla table), then any other bin can be swapped in and the output stays the same. Works for all levels of bins, also tested with chemical tanks and it worked. Willing to bet it would also work with fluid tanks, as well as energy cubes and induction cells, but didn't try it.
