### ISSUE TITLE
Logistical Transporter bad performance 

### ISSUE THREAD

**Issue by bigenergy** [mekanism/Mekanism#7397]
### Issue description

![image](https://user-images.githubusercontent.com/17977139/150435421-e87b1991-f1df-46cf-9313-8b419aed2d42.png)

https://spark.lucko.me/M4dSF1buYu

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.1 (Latest)

**Comment by NotReviere** [comment]
Could you give us more information please? Things like how the setup looks like and what items are flowing through the system could help us identify the issue.

**Comment by bigenergy** [comment]
> Could you give us more information please? Things like how the setup looks like and what items are flowing through the system could help us identify the issue.

Unfortunately, I cannot determine the coordinates of the system that gives such a load, there are quite a lot of them on my server

**Comment by Seniorendi** [comment]
Use the mod "Observable" to find the chunks of these cables.

**Comment by pupnewfster** [comment]
Without more info about the setups or more accurate profiling data there isn't really anything we can do about this as the lag is on the side of the chests which implies to me you likely have tons and tons of chests being pumped into or something especially given you said there are quite a lot of them on the server (and of course it all adds up)
