### ISSUE TITLE
Transfer Pipes/Cables Not Working

### ISSUE THREAD

**Issue by ABCLTheSecond** [mekanism/Mekanism#7403]
### Issue description

I just recently started a new server with Mekanism on it. Whenever I would place a Cable to an energy cube, it would only show the middle part. Here is a picture.
![Minecraft 1 12 2 1_28_2022 10_38_00 PM](https://user-images.githubusercontent.com/98631887/151647480-5679ede8-276b-4e51-8e8d-77ed1fea432a.png)

### Minecraft version

1.15.x or earlier (No longer being developed)

### Forge version

14.23.5.2860

### Mekanism version

Older

**Comment by AlexHgC** [comment]
Check the energy side config in your cube. 

1.15 and less are no longer developed, try to join the discord server to have more help if it not work with the right energy side config

**Comment by pupnewfster** [comment]
Closing this as we no longer are developing 1.12, if what Alex said to try doesn't help we may be able to provide some other suggestions on discord.
