### ISSUE TITLE
Can't load mekanism

### ISSUE THREAD

**Issue by KoalaNinjaOfc** [mekanism/Mekanism#7404]
### Issue description

I'm having some problems loading Mekanism in the latest version. I tried downgrading the Optifine version from G8 to G7, which didn't work, I tried removing Optifine, which didn't work too, and tried downgrading the forge version from 36.2.23 to 36.2.21, which, again, didn't work. I don't know what is causing this problem and don't know what else I could try to solve this problem.

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.21

### Mekanism version

10.1.1 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/iWzk723t

**Comment by Seniorendi** [comment]
You use the mod `mekanism addons` which is not made by the mekanism team and also does not work

**Comment by KoalaNinjaOfc** [comment]
I removed the mod `mekanism addons` and it gave me the same error:
https://pastebin.com/iwEtdgp4

**Comment by Matyrobbrt** [comment]
Backpacker is the mod causing this

**Comment by KoalaNinjaOfc** [comment]
Yep, after removing it worked. Thanks for the help!
