### ISSUE TITLE
Dirty Tin Slurry

### ISSUE THREAD

**Issue by Minion123456** [mekanism/Mekanism#7406]
### Issue description

Dirty Tin Slurry means "污浊锡浆液" in Chinese, but in Mekanism, its name in Chinese is "污浊锌浆液"(dirty zinc slurry).

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.23

### Mekanism version

10.1.1 (Latest)

**Comment by Seniorendi** [comment]
If you want to improve the language of your choice, you can do it via Crowdin
https://crowdin.com/project/mekanism

**Comment by thiakil** [comment]
Confirming Seniorendi's comment. If it won't let you directly change it, create an issue on Crowdin and I'll unlock it
