### ISSUE TITLE
Mekanism generator additions' industrial turbines construction have a big issue.

### ISSUE THREAD

**Issue by YangKenSHEEPS** [mekanism/Mekanism#7407]
### Issue description

When I am trying to build a industrial turbines in minecaft even though I followed the step on the wiki. I still can't build one. Every time I click the machine itself it warns me that Couldn't validate center , found invalid block at(  ,  )(show in picture) , but the whole structe is the same as the wiki said. May be it is a new issue or something else.
![2022-02-06_12 06 34](https://user-images.githubusercontent.com/43960448/152667523-15e6d579-b7b8-4dbf-be92-ab9dd62fd808.png)

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.32

### Mekanism version

10.1.1 (Latest)

**Comment by toddlersizedsharkcage** [comment]
you don't have a layer of dispersers with a rotational complex.  which wiki are you looking at?

**Comment by YangKenSHEEPS** [comment]
I build one with complete moduels But It still has its issue

**Comment by YangKenSHEEPS** [comment]
![2022-02-06_12 30 54](https://user-images.githubusercontent.com/43960448/152667863-ba5a08d1-769f-473b-a864-60145a34377e.png)

**Comment by toddlersizedsharkcage** [comment]
what's at 86 11 -189?

**Comment by AlexHgC** [comment]
Hi, this isn't a Mekanism issue but a wrong build issue. Can you join the discord [Here](https://discord.gg/euHT5nyHeC) to get more help ?
