### ISSUE TITLE
About Fission Reactor

### ISSUE THREAD

**Issue by Minion123456** [mekanism/Mekanism#7408]
### Issue description

The temperature shown on the heat graph is wrong. It should be 296.17K but it's 296.0K now.
![image](https://user-images.githubusercontent.com/93816576/152674300-322e70f1-a1be-4226-8dc0-9c72244bfe7f.png)

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.23

### Mekanism version

10.1.1 (Latest)

**Comment by pupnewfster** [comment]
After looking into this a little it is because the graph system clamps at whole numbers. I will try and adjust this to fix it some, but not until 1.18.

**Comment by Minion123456** [comment]
The graph is still wrong.
Version: Mekanism 10.1.2.457.
<img width="387" alt="屏幕截图 2022-02-27 155205" src="https://user-images.githubusercontent.com/93816576/155873640-696cf2ca-8e8b-490d-af88-6ca9af1d2d92.png">
