### ISSUE TITLE
Thermal Evaporation plant stopped working

### ISSUE THREAD

**Issue by OculusRex** [mekanism/Mekanism#7412]
### Issue description

Max size TEF with a Resistive Heater, making Brine.

Was working fine and suddenly it's just not working at all. Filling from a Sink using mechanical pipe. Fills just fine when formed. Can access UI.

Not accepting heat from the Resistive Heater. Production is 0.0. Not even the minimal amount it should be by itself.

Have tried breaking and replacing blocks. Have completely rebuilt it. It is in a chunk that has been loaded the whole time.

![Screenshot (84)](https://user-images.githubusercontent.com/43069841/154578894-968e7309-46c4-4a16-bdec-09500afe8844.png)

### Minecraft version

1.16.5 (Latest)

### Forge version

1.8.18

### Mekanism version

10.1.1 (Latest)

**Comment by toddlersizedsharkcage** [comment]
Check the resistive heater to make sure it has energy and isn't disabled (redstone setting on bottom right)

**Comment by toddlersizedsharkcage** [comment]
What's the amount you have the heater set to?

**Comment by AlexHgC** [comment]
Is the white side touching the valve ? And not the black side ? Send a screenshots of your heater connected to the tep, and what value for heater ?

**Comment by leadwolf32** [comment]
Just wanna make sure, there isn't like a tiny sliver of something in the output is there?

**Comment by AlexHgC** [comment]
Your resistive heater need to have the white side touching the valve, this is not the case on your screen. you have the grey side touching it. juste replace it to make it touch the white side

**Comment by OculusRex** [comment]
> Your resistive heater need to have the white side touching the valve, this is not the case on your screen. you have the grey side touching it. juste replace it to make it touch the white side

Nope. The configuration it's in is the only way it's ever worked for me. Plus there's the already stated fact that it was working fine before. Additionally there's the OTHER already stated fact that the TEF isn't producing anything at all. Not even the minimal amount it should be by itself.

**Comment by pupnewfster** [comment]
Try setting a higher amount of energy in the resistive heater? As the heaters temperature is basically at ambient.

**Comment by toddlersizedsharkcage** [comment]
![Screenshot_20220218-083719](https://user-images.githubusercontent.com/59610016/154692887-89d642b6-df0a-48c0-82b8-507bc22dd9db.png)
It's disabled.

**Comment by toddlersizedsharkcage** [comment]
also, normal people say "thanks for trying" instead of acting like an entitled shit.  like we owe you anything.

**Comment by toddlersizedsharkcage** [comment]
![image](https://user-images.githubusercontent.com/59610016/154712962-8712c328-6577-425e-b08a-fced98f1c677.png)

and the heater isn't producing heat, genius.  keep telling us it isn't the heater, though.
