### ISSUE TITLE
Sequential Fabricator reset NBT

### ISSUE THREAD

**Issue by busa13** [mekanism/Mekanism#7414]
### Issue description

https://imgur.com/a/XWplxFI

### Steps to reproduce

Place Sequential Fabricator
Save craft
Put blocks for crafting
There is no correct result 

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.26

### Mekanism version

10.1.1 (Latest)

**Comment by pupnewfster** [comment]
Do you potentially mean the Formulaic Assemblicator? If not I believe you have the wrong mod as we do not add a block called a Sequential Fabricator.

**Comment by Seniorendi** [comment]
Nice answer!
