### ISSUE TITLE
Travis CI no longer works

### ISSUE THREAD

**Issue by H4ckerxx44** [mekanism/Mekanism#7415]
### Issue description

The "build: passing" badge returns a 404 on opening

### Steps to reproduce

1. Open [link](https://www.travis-ci.com/mekanism/Mekanism)
2. Read

### Minecraft version

1.16.5 (Latest)

### Forge version

None

### Mekanism version

10.1.1 (Latest)

**Comment by sxjeru** [comment]
The correct link: https://app.travis-ci.com/github/mekanism/Mekanism

But the 1.18 version hasn't built yet, can't even find this branch.

**Comment by thiakil** [comment]
I decided to remove the badge completely (at least for now), as Travis moved everything to their paid platform and we'd need to apply for open source credits for something we barely even use
