### ISSUE TITLE
Cardboard boxes

### ISSUE THREAD

**Issue by bsylve1996** [mekanism/Mekanism#7417]
### Issue description

When using carboard boxes on refined storage disk drive, the cardboard box will delete the storage cells stored inside it.

### Steps to reproduce

1. click carboard box on refined storage disk drive with storage cells in it. 
2. shift click the carboard box off the disk drive.
3. no storage cells in the disk drive

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.22

### Mekanism version

10.1.1

**Comment by pupnewfster** [comment]
Nothing we can do about that, if memory serves refined storage doesn't save its disks to the tile and does it some other way.
