### ISSUE TITLE
Cant break Boat and Minecart with Meka-Tool or Atomic Disassembler

### ISSUE THREAD

**Issue by umutkrdgg** [mekanism/Mekanism#7423]
### Issue description

minecart or Boat cannot be broken with both tools. Tried different efficiency settings on meka-tool. Fast spamming maybe broke them.
i am playing on 1.18.1 but a1qs on discord channel says it is same in 1.16.5

### Steps to reproduce

just try to break boat or minecart with meka-tool/atomic disaassembler

### Minecraft version

1.16.5/1.18.1 (Latest)

### Forge version

1.18.1 39.0.88

### Mekanism version

10.1.2 (Latest)

**Comment by pupnewfster** [comment]
Hmm, this is somewhat complicated as the way vanilla does damage for non living entities is by the damage attribute, but both of those calculate damage based on energy in the hurt living entity method. I potentially will be able to implement handling for this by listening to an event and then just manually hurting the boat but we will see.
