### ISSUE TITLE
1.16.5 Smallest dynamic tank (3x3x3) reporting 432,000,000mB, also wont empty,only fills up. 

### ISSUE THREAD

**Issue by mookie1590** [mekanism/Mekanism#7431]
### Issue description

Just the title, the size of the tank is 432,000,000 (3x3x3). wont empty either only fills up. Ive swt5iched blocks around and shape.
I do ahve 2 seperate tanks both doing this

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.31

### Mekanism version

10.1.2 (Latest)

**Comment by toddlersizedsharkcage** [comment]
Please share a pic of the tank GUI

**Comment by mookie1590** [comment]
sure. also noticed that the valve blocks only also are reporting 0mB of air, the other blocks dont appear to be doing this. Ive messed with the button that lets you set empty, fill, or both. Doesnt seem to change anything.
![2022-03-22_20 21 49](https://user-images.githubusercontent.com/77138346/159807658-928fd50d-298c-4c82-b7b5-acdafe54df0c.png)
![2022-03-23_18 35 31](https://user-images.githubusercontent.com/77138346/159807670-0d6f404d-5877-4d96-bca2-639e94f2414e.png)
![2022-03-23_18 36 38](https://user-images.githubusercontent.com/77138346/159807685-46ae051b-bcb0-4f8e-b7e4-1fa8b1259758.png)

**Comment by toddlersizedsharkcage** [comment]
![image](https://user-images.githubusercontent.com/59610016/159830169-6234a9a2-dac7-4bdc-bb2e-88c093f890a3.png)

Shift right click here with a configurator to pull from the tank.  

You might be better off joining us on Discord if you have questions like this:  https://discord.gg/nmSjMGc

**Comment by mookie1590** [comment]
Yeah, setting the pipe to pull worked, dunno why I didn't consider that. I did assume a bug all ready, because the 3x3x3 is reporting 432,000,000, wiki says it should be 432,000 but looking at the wiki, the 18x18x18 one should be 93,312,000. unless the wiki is just outta date. 
Assumed it was bugged because the numbers were not matching up
I'll join the discord, thanks for your help.

**Comment by toddlersizedsharkcage** [comment]
The capacity is set in the config files and was increased a lot for 10.1 and higher. If you're good here, please close the issue. Glad I could help.
