### ISSUE TITLE
mekanism and industrial meat are crashing the game

### ISSUE THREAD

**Issue by dokimiki** [mekanism/Mekanism#7439]
### Issue description

The game crashes when Mekanism's energy is sent to the Meat Packer(industrialmeat:meat_packer).

### Steps to reproduce

1. Place the Meat Packer(industrialmeat:meat_packer)
2. Place a block next to the Meat Packer where the mekanism can transmit power(e.g. Basic Universal Cable(mekanism:basic universal_cable))

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.33

### Mekanism version

10.1.2 (Latest)

### Other relevant versions

industrialmeat 1.16-1.0.4

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/dokimiki/66e1c538ef49acc913844159dda77a8e

Translate by deepl.com

**Comment by pupnewfster** [comment]
Report to Industrial Meat, they are returning null from a nonnull method https://github.com/abused/Industrial-Meat/blob/1.16/src/main/java/abused_master/industrialmeat/tileentity/TileEntityMeatPacker.java#L194
