### ISSUE TITLE
Minecraft server randomly crashes with mekanism 

### ISSUE THREAD

**Issue by Sollos1** [mekanism/Mekanism#7441]
### Issue description

here is crash log

### Steps to reproduce

randomly

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.20

### Mekanism version

10.1.2 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://haste.mohistmc.com/lodafatira

**Comment by pupnewfster** [comment]
Does this happen on forge or only on Mohist?

**Comment by Sollos1** [comment]
it looks like only on  Mohist

**Comment by Sollos1** [comment]
but only thing i was offered in their support is instaling older version of Mekanism

**Comment by pupnewfster** [comment]
No idea we don't support Mohist as they are known for breaking forge and thus not being fully compatible with forge even though they claim it is. Take it up with them or better yet just don't use hybrid softwares as they are known for causing issues. If you have to use one, spongeforge is known to be the least breaking of them even though it also ends up breaking things
