### ISSUE TITLE
Minecraft frequently crashes

### ISSUE THREAD

**Issue by Taimeshi** [mekanism/Mekanism#7444]
### Issue description

I'm using Google Translate, so the translation may not be accurate.

The crashes happen suddenly, and IndexOutOfBoundsException or ConcurrentModificationException occurs.
Crash logs say IndexOutOfBoundsException occured because of sound bugs.
Sometimes it works fine, but sometimes it freezes in a few seconds no matter how many reboots I make.

### Steps to reproduce

1. Play Minecraft
2. ( I felt they especially often occured when I used a teleporter, got closer to machines, or moved fast )
3. Minecraft suddenly freezes

### Minecraft version

1.16.5 (Latest)

### Forge version

36.2.31

### Mekanism version

10.1.2 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/DaEdv0QJ

**Comment by pupnewfster** [comment]
Nothing in that crash log points at mekanism, there is one thing that might point at abnormals_core or it may just be they have a mixin and aren't causing the crash
