### ISSUE TITLE
failed to load entity

### ISSUE THREAD

**Issue by Mrkripl** [mekanism/Mekanism#7448]
### Issue description

game crashing when trying to load glowstone armor on a entity
[crash-2022-04-12_09.44.06-client.txt](https://github.com/mekanism/Mekanism/files/8470802/crash-2022-04-12_09.44.06-client.txt)

### Minecraft version

1.18.2 (Latest)

### Forge version

40.0.44

### Mekanism version

10.2.0 (Latest)

**Comment by pupnewfster** [comment]
Remove optifine they are breaking forge
