### ISSUE TITLE
Refined Glowstone armor on piglin causes crash

### ISSUE THREAD

**Issue by Zuramax** [mekanism/Mekanism#7450]
### Issue description

I was vibing in the nether when suddenly my game crashed, and when i tried to open my world again the game crashed instantly. I had to remove "Mekanism: tools" mod to make it work again.

### Steps to reproduce

/summon piglin ~ ~ ~ {ArmorItems:[{},{},{},{id:"mekanismtools:refined_glowstone_helmet",Count:1b}]}

This is the command i used to recreate the crash.

### Minecraft version

1.18.2 (Latest)

### Forge version

40.0.44

### Mekanism version

10.2.0 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Zuramax/a9e21b11cbf3da736ef7dccaca82220e

**Comment by pupnewfster** [comment]
This is an optifine bug reverting forge changes our refined glowstone requires to render properly
