### ISSUE TITLE
Wires don't connect

### ISSUE THREAD

**Issue by intergalacticlemon** [mekanism/Mekanism#7451]
### Issue description

I was testing out mechanism in a Minecraft server and I haven't been able to get any wires to connect
https://medal.tv/games/minecraft/clips/hNrz4cCyXea0M/d1337iStumr6?invite=cr-MSxYODQsMzE0MTU1Mzgs

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

1.12.2

### Mekanism version

9.8.3,390

**Comment by toddlersizedsharkcage** [comment]
There's no way you have that combination of forge (not their versioning format), mekanism (10.2 is only for 1.18.2), and Minecraft (1.16 goes up to 10.1.2 for mekanism). Please update.

**Comment by intergalacticlemon** [comment]
updated it

**Comment by toddlersizedsharkcage** [comment]
Why does the URL have the word "invite" in it? Please post screenshots of your issue. The link is suspicious.

**Comment by intergalacticlemon** [comment]
![2022-04-15_16 21 32](https://user-images.githubusercontent.com/82805490/163545652-70c495f1-e122-48eb-988a-b8fc54b730cd.png)

**Comment by toddlersizedsharkcage** [comment]
Did you try any of the other things I suggested?
