### ISSUE TITLE
Anchor Upgrade is invalid.

### ISSUE THREAD

**Issue by Fiocher** [mekanism/Mekanism#7453]
### Issue description

I used Anchor Upgrade for Transporter, but it cannot be teleported after restarting game: No link.
After testing, use this mod [https://www.curseforge.com/minecraft/mc-mods/chunk-loaders](url) can be teleport.
Is it a chunk load problem?

### Minecraft version

1.18.2 (Latest)

### Forge version

40.0.45

### Mekanism version

10.2.0 (Latest)

**Comment by pupnewfster** [comment]
Transporters can't accept anchor upgrades? They don't even have a GUI.

**Comment by Fiocher** [comment]
> Transporters can't accept anchor upgrades? They don't even have a GUI.

It's been upgraded, but not working. Distant chunk can't keep loaded. I used other chunk load mod to keep loaded.

**Comment by PmanAce** [comment]
I think he means teleporters. I can confirm I have the same issue, anchor upgrades on both ends and no link when loading world. Link only activates when using cheats to teleport to other teleporter.

**Comment by Fiocher** [comment]
> teleporters

Yeah I mean teleporters, sorry.
