### ISSUE TITLE
Mekanism Crash apon startup 1.16.5 Forge

### ISSUE THREAD

**Issue by Pyrarius** [mekanism/Mekanism#7454]
### Issue description

I started up Curseforge and made a modpack, putting in the mods listed below:
inzhefop's core
Mekanism
Mekanism Additions
Mekanism Generators
Mekanism Matter
Mekanism Tools
Mekanism Addons
And every time I start it up, it crashes saying Mekansim and Mekanism addons is the issue, even thou none of the others work without Mekanism.
Here is my screens:
[crash-2022-04-18_16.24.00-fml.txt](https://github.com/mekanism/Mekanism/files/8508338/crash-2022-04-18_16.24.00-fml.txt)
![Crash 3 - Mod List](https://user-images.githubusercontent.com/103967088/163883032-1653cf2c-c21c-4fa7-820c-86bba5b31d8e.png)
[Crash 2 - Latest Log
![Crash 1](https://user-images.githubusercontent.com/103967088/163883049-cecfa12d-9280-46b1-a379-920f2aa940df.png)
.txt](https://github.com/mekanism/Mekanism/files/8508339/Crash.2.-.Latest.Log.txt)
I hope this helps

### Steps to reproduce

1. Open a Custom Profile with the specifications as follows: Forge 1.16.5 Version 36.2.29
2. Download the mods as follows:
inzhefop's core
Mekanism
Mekanism Additions
Mekanism Generators
Mekanism Matter
Mekanism Tools
Mekanism Addons
3. Launch and behold

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.29

### Mekanism version

Older

### Other relevant versions

Mekanism Addons - 2.2.1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/hFnpSPX6

**Comment by AlexHgC** [comment]
Remove mekanism Addons. And if it doesn't works, remove Mekanism Matter too. 

Addons and Matter aren't from Mekanism team. And mekanism Addons isn't compatible with mekanism 10.1 

Additions / Tools / Generators are official, other aren't

**Comment by Seniorendi** [comment]
*Didn't bother searching*

**Comment by Pyrarius** [comment]
It worked! TY Guys!
