### ISSUE TITLE
Cant Join Lan 

### ISSUE THREAD

**Issue by Cockfacelover** [mekanism/Mekanism#7456]
### Issue description

I cant join Lan servers

### Minecraft version

1.18.2 (Latest)

### Forge version

1.18.2 - 40.1.0

### Mekanism version

10.2.0 (Latest)

### Other relevant versions

![image](https://user-images.githubusercontent.com/104235633/164814216-8cc04cec-f2a5-4adb-b26e-d4ac6281a9c4.png)

**Comment by pupnewfster** [comment]
Unable to reproduce. Can you reproduce this with just mekanism (and submods: additions, generators, tools)?
