### ISSUE TITLE
Named personal chest losses his name

### ISSUE THREAD

**Issue by Appdato** [mekanism/Mekanism#7457]
### Issue description

When you have a named personal chest and you place it in the world it doesn't have his name on top as named vanilla containers do (the "chest" in the GUI becomes whatever you named) and when break it doesn't maintain his name as named vanilla containers  do.

### Steps to reproduce

1. Name a personal chest using an anvil
2. Place the chest in the world like a block
3. Open the chest and see that it doesn't maintain his name
4. Break the chest and see that it doesn't maintain his name

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

forge-1.16.5-36.2.33

### Mekanism version

Older

**Comment by pupnewfster** [comment]
This is not going to be fixed as support for this wasn't implemented until 1.18
