### ISSUE TITLE
Cannot invoke "mekanism.client.render.lib.Vertex.pack(com.mojang.blaze3d.vertex.VertexFormat)"

### ISSUE THREAD

**Issue by Cannabis-CFG** [mekanism/Mekanism#7459]
### Issue description

When going through the item list in JEI on a certain page the game will freeze and crash with the following output:
`The game crashed whilst rendering item
Error: java.lang.NullPointerException: Cannot invoke "mekanism.client.render.lib.Vertex.pack(com.mojang.blaze3d.vertex.VertexFormat)" because "this.vertices[v]" is null
Exit Code: -1`

### Steps to reproduce

1. Install JEI & Mekanism
2. Scroll through the item list until crash has occured

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.0

### Mekanism version

10.2.0 (Latest)

### Other relevant versions

The actual Mekanism version is 10.2.0.459, if this ties into anything specific.

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/9zQXhrYA

**Comment by AlexHgC** [comment]
Remove optifine

**Comment by Cannabis-CFG** [comment]
> Remove optifine

I'm actually currently attempting to recreate the issue to determine if it was a one-off issue or otherwise and am finding no luck with no changes to the mods loaded, including with optifine still included in said list.

I will uninstall optifine for the time being just in-case this issue does come back and persists for a while.

**Comment by AlexHgC** [comment]
> > Remove optifine
> 
> I'm actually currently attempting to recreate the issue to determine if it was a one-off issue or otherwise and am finding no luck with no changes to the mods loaded, including with optifine still included in said list.
> 
> I will uninstall optifine for the time being just in-case this issue does come back and persists for a while.

Render issue are 99% of the time Optifine cause. After reading crash log, there is a lot of mentions of optifine for render. 
Some people love optifine, but never forget that it break a *lot* of mods, including Mekanism

If the crash doesn't appear everytime, feel free to you to use Optifine, but this isn't Mekanism issue

**Comment by pupnewfster** [comment]
Yeah not quite sure what is going on here. Best guess is it is related to optifine but could also be that our baked quad transformer is being ran for some item it shouldn't be or something but without knowing the specific item that it was trying to render and then potentially what vertex format it was using (as we assume it should be using the block vertex format and more importantly that it should have four vertices)... I don't think there is much we can do about this unfortunately.

**Comment by Cannabis-CFG** [comment]
> Yeah not quite sure what is going on here. Best guess is it is related to optifine but could also be that our baked quad transformer is being ran for some item it shouldn't be or something but without knowing the specific item that it was trying to render and then potentially what vertex format it was using (as we assume it should be using the block vertex format and more importantly that it should have four vertices)... I don't think there is much we can do about this unfortunately.

Ah okay. I'll have to keep an eye on it. So far it's working perfectly with no issues despite me just relaunching without changing a single thing.

I appreciate the thought and responses! I'll be sure to keep you posted if I notice anything amiss during my playtime.
