### ISSUE TITLE
meka and SME

### ISSUE THREAD

**Issue by l34nd35** [mekanism/Mekanism#7460]
### Issue description

Hello, my friend and me. We figured out that so many enchants and mekanism are 
incompatible on the latest minecraft-version (1.18.2):

If i acrivate an resourcepack it will crash but it also crashed while join oure server
ore an singelplayer world:

We used forge (40.1.0 and also 40.0.49)
and the latest versions of mecanism and SME.

We also test it with older versions but nothing worked.
Best Regarts L34nd35 ore Leander🤯

### Steps to reproduce

1.install mekanism and so many enchants
2.install your favorit resourcepack 
3.i hope you find the bug

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.0

### Mekanism version

10.2.0 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

The game crashed whilst rendering overlay Error: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "java.util.HashMap.get(Object)" is null Exit-Code: -1 [18:42:07] [main/INFO]: ModLauncher running: args [--username, mr_nuss0815, --version, forge-40.0.49, --gameDir, C:\Users\Mr.Nuss\curseforge\minecraft\Instances\Solo World, --assetsDir, C:\Users\Mr.Nuss\curseforge\minecraft\Install\assets, --assetIndex, 1.18, --uuid, 967e99368f59459f89bdb9ebc0e62bd2, --accessToken, ????????, --clientId, MWRhMzAyNmEtMTlkMy00MjVlLWExYjYtZDcxMGEwOTI1Nzdj, --xuid, 2535469818246810, --userType, msa, --versionType, release, --width, 1920, --height, 1080, --launchTarget, forgeclient, --fml.forgeVersion, 40.0.49, --fml.mcVersion, 1.18.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20220404.173914] [18:42:07] [main/INFO]: ModLauncher 9.1.3+9.1.3+main.9b69c82a starting: java version 17.0.1 by Microsoft [18:42:07] [main/INFO]: OptiFineTransformationService.onLoad [18:42:07] [main/INFO]: OptiFine ZIP file URL: union:/C:/Users/Mr.Nuss/curseforge/minecraft/Instances/Solo%20World/mods/OptiFine_1.18.2_HD_U_H7.jar%2352!/ [18:42:08] [main/INFO]: OptiFine ZIP file: C:\Users\Mr.Nuss\curseforge\minecraft\Instances\Solo World\mods\OptiFine_1.18.2_HD_U_H7.jar [18:42:08] [main/INFO]: Target.PRE_CLASS is available ... (69 kB verbleibend)

**Comment by pupnewfster** [comment]
Does it work if you remove optifine? Also could you please state which resource pack you are using/provide a link to their website as a brief google does not show any results for `SME`

**Comment by l34nd35** [comment]
No, it doesn't work without optifine either and I've tried several resourcepacks but I prefer to use Fresh Animations from FreshLX_official. I have sent the above message to So many Enchants (SmE), but have not yet received a message from them.

we also had the problem that the game crashed when changing the language,
 he received the same crashrepo

**Comment by l34nd35** [comment]
![image](https://user-images.githubusercontent.com/104382436/165939018-eda4ec45-0f6c-4b93-81df-63f80eedd252.png)


So many Enchants hat das problem scheinbar gelöst aber danke

**Comment by pupnewfster** [comment]
Ah good to know, and looking at the issue you opened there it seems it was something on their end.
