### ISSUE TITLE
Electrolytic Separator dumping feature bug.

### ISSUE THREAD

**Issue by SpawnofHavok** [mekanism/Mekanism#7462]
### Issue description

I'm having a major issue with the electrolytic converter. The dump and dump excess features don't work for the oxygen part of the machine, so I can't properly use anything having to deal with that feature. The oxygen should be able to be dumped out no problem, but it just builds up until there's no more room and my entire generator stops working.

### Minecraft version

1.18.2 (Latest)

### Forge version

40.0.46

### Mekanism version

10.2.0 (Latest)

**Comment by AlexHgC** [comment]
Can you send a screenshot of the GUI when it's full with dumping excess or dump ?

**Comment by pupnewfster** [comment]
Not able to reproduce this. Any more details on the setup?
