### ISSUE TITLE
When CTM is installed, few machines interact has bugged.

### ISSUE THREAD

**Issue by korAPUcard** [mekanism/Mekanism#7463]
### Issue description

When CTM is installed, few machines interact has bugged. Right click is still work but GUI is not opened.

### Steps to reproduce

1. Install the CTM mod.
2. Run the game.
3. Create new world or load saved world.
4. Interact Mek machines.

Result: Right click is still work, but GUI does not opened.   
(Multi-block machines too)

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.26

### Mekanism version

10.2.0 (Latest)

### Other relevant versions

[CTM - MC1.16.1-1.1.2.6](https://www.curseforge.com/minecraft/mc-mods/ctm/files/3137659)

**Comment by pupnewfster** [comment]
Are you sure you just have mekanism and CTM? I never ran into this issue and neither has anyone else I have talked with. Also could you please provide your latest log after it fails to open the GUI.
