### ISSUE TITLE
[1.18.2]Log Spam w/ Female Gender Mod 

### ISSUE THREAD

**Issue by Lucent-Spire** [mekanism/Mekanism#7476]
### Issue description

No matter player's gender and/or without any other mods installed, having both Mekanism and Wildfire's FGM installed causes the log to constantly output the following warning (see pastebin in crash reports). 
- Tested with the newest versions of both mods for 1.18.2 
- Tested on a fresh install (issue came up with other mods installed) 
- Tested on listed forge ver. and 40.1.16
- Tested with multiple combinations of gender/breast physics settings
- Message in pastebin will repeat up to 2-3x every second if jetpack is equipped and flying, will also repeat on spawning mekasuit and/or interacting with it in inventory in creative mod 
- Note that the game doesn't crash and both mods seem to function fine otherwise, but the log spam is a bit much. 
- Hopefully that's enough for you to narrow down the issue, can provide more info if needed. 

### Steps to reproduce

1) Install all listed mods 
2) Load any world 
3) Open console log (tested on both multiMC and polyMC) 
4) (OPTIONAL) equip jetpack and fly around 
5) Observe log spam 

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.15

### Mekanism version

10.2.0 (Latest)

### Other relevant versions

- Wildfire's Female Gender Mod v. 2.9 

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/SH81fBuz

**Comment by Lucent-Spire** [comment]
Thanks for the fix!

**Comment by Lucent-Spire** [comment]
Hi! 

This is still occurring on MC 1.18.2, Mekanism 10.2.1, Forge 40.1.25, and WFGM 2.9. No other mods installed, same reproduction method. 

Log: https://pastebin.com/7Tf9UUH5 (more complete this time)

**Comment by pupnewfster** [comment]
Hmmm I don't get how that is possible but I will try looking at it again because maybe I missed something.

**Comment by Lucent-Spire** [comment]
Can provide more info/do whatever on request, just lmk.

**Comment by Lucent-Spire** [comment]
Built the latest commit from source, looks like that fixed it under the same conditions. Thanks!
