### ISSUE TITLE
Is it even possible...

### ISSUE THREAD

**Issue by Furious1964** [mekanism/Mekanism#7480]
### Issue description

To get the max RF Energy Output of 668,570,000 J/t (267,420,000 RF/t) by building a max turbine? I built one using the diagram shown here https://ftbwiki.org/Industrial_Turbine and it's always say that the vents are "Limiting". Ive calculated the flow rate of water and steam and what I get is that I need one more vent....is this build correct and if not, what was changed?

Playing the FTB Oceanblock Mod Pack.

### Steps to reproduce

1. Build the turbine.
2. Look at the stats.

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.33

### Mekanism version

10.1.2

**Comment by toddlersizedsharkcage** [comment]
It just means the volume of the lower part of the turbine can handle higher steam flow than the vents can. You'll almost always see vents as limiting. Nothing to be done about it.
