### ISSUE TITLE
Failure message: Mekanism (mekanism) has failed to load correctly (v10.1.2)

### ISSUE THREAD

**Issue by Davigamer10** [mekanism/Mekanism#7481]
### Issue description

I can't even enter in the menu of minecraft, the mensage saying that the mekanism isn't working pops up

### Steps to reproduce

1. I click to enter in Minecraft application
2. After the loading screen finaly gone, it pops up
3. I cry a lot

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.29

### Mekanism version

Older

**Comment by toddlersizedsharkcage** [comment]
![image](https://user-images.githubusercontent.com/59610016/168517171-c3cb1e92-796b-42af-bd20-e7c25d4da91b.png)

**Comment by pupnewfster** [comment]
If I had to guess this is a duplicate and Mekanism addons which is not one of our mods but yeah no idea given you have provided no information.
