### ISSUE TITLE
Anchored Teleporters Don't Work After Server Restart

### ISSUE THREAD

**Issue by Peekofwar** [mekanism/Mekanism#7482]
### Issue description

A user on my server reported being unable to teleport to my teleporter pad that's located inside of my base. I thought that was odd, since it's equipped with an anchor, and they only need power when used as a portal. When I logged into the server, I had no issues using it, however, I discovered I had the same issue but with my Digital Miner teleporter pad that I place near my digital miner so that I can check on it at remote sites.

It turns out that anchored machines don't seem to load when the server starts and only once they've been loaded do they stay loaded. They aren't forcefully loaded on world load/server start.

https://user-images.githubusercontent.com/10189526/168712114-535ee653-1dca-40b7-aabf-0c8f8b2ead1e.mp4

### Steps to reproduce

In a dedicated multiplayer server:
1. Place down a teleporter pad somewhere in the world and upgrade it with an anchor upgrade.
2. Place down a second teleporter pad far from the spawn area and far from the first pad and equip it with an anchor upgrade.
3. Return to the first pad and stop the server.
4. Restart the server and login. Select the second teleporter and attempt to teleport to it. You should see the option to teleport is grayed out. 
5. Travel to the location of the second pad and select it again in your personal teleporation device. You'll notice that it is no longer grayed out.

Optional:
1. Teleport back to the first teleporter.
2. Logout of the dedicated multiplayer server.
3. Login to the server and select the second teleporter. You should see that it is available and ready to be teleported to, since the chunk has already been loaded and remained loaded.

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.0

### Mekanism version

10.2.0 (Latest)

**Comment by TwiceDaIce** [comment]
Can someone point to the specific commit where this was fixed? Can't seem to find. Thanks
