### ISSUE TITLE
Mekanism breaks tinkers and vanilla pickaxes.

### ISSUE THREAD

**Issue by SpiderKraken** [mekanism/Mekanism#7484]
### Issue description

after installing makanism all tinkers and vanilla picks break at fist speed and dont drop blocks almost as if mekanism removed the flag for "pickaxe" and its relative mining level.

### Steps to reproduce

installed mekanism.
logged in
tools janky
reboot
samething
remove mekanism
problem gone

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.19

### Mekanism version

10.2.0 (Latest)

**Comment by SpiderKraken** [comment]
[latest.log](https://github.com/mekanism/Mekanism/files/8740935/latest.log)

**Comment by SpiderKraken** [comment]
having removed all dependencies and mekanism the issue has popped back up so i dont know if it made a change to the config for the server that needs to be reverted or not but no other mod was added as a new mod to my pack so its a very weird issue 
that im unsure how to even locate the required config or setting to reenable or correct

**Comment by pupnewfster** [comment]
```
 Couldn't load tag minecraft:mineable/pickaxe as it is missing following references: ae2:256k_crafting_storage (from appliedenergistics2-11.0.0.jar), 
	mcwbridges:deepslate_brick_bridge (from mcw-bridges-2.0.3-mc1.18.2.jar), 
	mcwbridges:deepslate_tile_bridge (from mcw-bridges-2.0.3-mc1.18.2.jar), 
	mcwbridges:deepslate_brick_bridge_pier (from mcw-bridges-2.0.3-mc1.18.2.jar), 
	mcwbridges:deepslate_tile_bridge_pier (from mcw-bridges-2.0.3-mc1.18.2.jar), 
	mcwbridges:deepslate_tile_bridge_stair (from mcw-bridges-2.0.3-mc1.18.2.jar), 
	mcwbridges:deepslate_brick_bridge_stair (from mcw-bridges-2.0.3-mc1.18.2.jar)
```
Looks like AE2 is breaking the pickaxe mineable tag

**Comment by SpiderKraken** [comment]
ahh thats oddd, they did update earlier. i didnt do any pickaxe stuff before i added mekanism so didnt even think to check that ...ok ill have a look at that config etc. thanks . apologies for the issue post

**Comment by SpiderKraken** [comment]
did it have errors for all block types?
