### ISSUE TITLE
Unable to craft digital miner

### ISSUE THREAD

**Issue by Thegameinglemon10** [mekanism/Mekanism#7488]
### Issue description

So, I was watching an mc series will playing on an modpack and I saw they had a digital miner. Naturally, I wanted to make my own, so I opened JEI to get the recipe but when clicking on the miner no recipe appears. I went into creative and tried using the recipe I found on a wiki and nothing. I even went through the configs to see if there was an option to disable the digital miner, which there was, but it's enabled. I'd like help finding out what's causing the recipe to be corrupted/disabled/whatever is going on.

### Steps to reproduce

1. Install "DigSite" on the FTB launcher
2. Add the following mods to the pack: https://drive.google.com/file/d/1sYdQqCyZdsCr9ExpO3YPzsxl-5UPQLbg/view
3. Standard stuff: Launch, create world, open menu
4. Search digital miner in JEI and click on it to view the recipe
5. When clicking on the miner, nothing will happen.

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

14.23.5.2854

### Mekanism version

Older

### Other relevant versions

MC: 1.12.2
Mekanism: 9.8.3.390

**Comment by pupnewfster** [comment]
The modpack probably just disabled the recipe

**Comment by Thegameinglemon10** [comment]
How would I re-enable it?

**Comment by tuc56** [comment]
look in the file "recipes.zs" in the scripts folder for a line removing the digital miner recipe
