### ISSUE TITLE
EMC gets broken

### ISSUE THREAD

**Issue by Agentx49** [mekanism/Mekanism#7491]
### Issue description

so I'm just going to start off saying I don't know what other mod mekanism is interacting with to cause this bug I just know that if I backtrack the version it goes away. also I did try this with just mekanism and projecte but the bug didn't occur

so on the most recent up date things items like stone, cobblestone and all the items they craft lose their emc values
modpack: [](https://www.curseforge.com/minecraft/modpacks/project-spacee)

### Minecraft version

1.18.2 (Latest)

### Forge version

tested on both 40.1.23 and 40.1.25

### Mekanism version

10.2.1 (Latest)

### Other relevant versions

bug doesnt occur in Mekanism 10.2.0.459

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Agentx49/a386aec96b2119e63aa8b64e2c3bf5db

**Comment by pupnewfster** [comment]
If it doesn't happen with just Mekanism and projecte and doesn't happen with Mekanism 10.2.0 (where our EMC mappers were broken). Then the odds are some other mod is adding a recipe to our machines that cause emc values to go to zero.

**Comment by Agentx49** [comment]
surprisingly it was Oh, the biomes you'll go

**Comment by Agentx49** [comment]
figured it out the issue was being caused by a mod that adds alot of random recipes to vanilla items

**Comment by LazarusCaine** [comment]
> figured it out the issue was being caused by a mod that adds alot of random recipes to vanilla items

What mod caused the issue and what did you do about it?

**Comment by Agentx49** [comment]
The mod was "just another vanilla addon"(just another venerable addon on
curseforge) I just ended up removing it
