### ISSUE TITLE
Game Hard-Crashes when opening certain mod config menus (something about Mekanism's upgrade menus?)

### ISSUE THREAD

**Issue by LonelySauce** [mekanism/Mekanism#7498]
### Issue description

Currently I've only had this happen with: Corail Tombstone-6.7.6 (latest) and Quark-r2.4-322 (latest) when attempting to view their config screens via the main menu.

### Steps to reproduce

I don't see how this will help but alright...

1. Launch the game
2. In the Main Menu after the game is done loading, click on "Mods"
3. Click on either "Corail Tombstone" or "Quark"
4. Click "Config" while having either mod selected
5. Game should hard-crash immediately

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.24

### Mekanism version

Older

### Other relevant versions

For some weird reason, it says "Saving World" despite me never joining a world. All I did was launch the game and click on the "q" button to open Quark's config screen the first time around and the game just crashed. While I did recently update Draconic Evolution, downgrading it to it's previous version had no effect on the crashes nor the reports generated.

Disabling/Removing Mekanism fixes the crash (go figure).

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/yyRgUpDe

**Comment by pupnewfster** [comment]
Invmove bug not us
