### ISSUE TITLE
incorrectly displayed MekaSuit

### ISSUE THREAD

**Issue by V4kodin** [mekanism/Mekanism#7509]
### Issue description

Incorrectly displayed MekaSuit with mod "Epic Fight Mod" (16.5.13) this problem may meet with other mods that change the animation of character. Other armor work fine.
PLS add support MekaSuit animation
![Безымянный](https://user-images.githubusercontent.com/61556245/172691477-013c09cb-4736-46d5-8353-6c49713bce7a.png)
![Безымянный3](https://user-images.githubusercontent.com/61556245/172691479-4a6cf751-a67e-4ba4-ae65-ddabf0c1026d.png)

### Steps to reproduce

1) install minecraft 1.16.5
2) install forge 36.2.35 or above
3) install mekanism latest
4) install Epic Fight Mod latest
5) equip MekaSuit
6) ready!

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.35

### Mekanism version

10.1.2.457 (Latest)

**Comment by pupnewfster** [comment]
Best guess is epic fight mod is breaking how custom layers render, in which case there is nothing we can do about that.

**Comment by V4kodin** [comment]
May be  you can add to mod config parameter to switch render model of MekaSuit? I mean other armor work nice, may be it possible to switch render model of MekaSuit to regular armor?

**Comment by pupnewfster** [comment]
No
