### ISSUE TITLE
Mekanism: Generators (mekanismgenerators) has failed to load correctly java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by DarklyNightly** [mekanism/Mekanism#7514]
### Issue description

when loading Minecraft this message appears Mekanism: Generators (mekanismgenerators) has failed to load correct java.lang.NullPointerException: null

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.35

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/DarklyNightly/1ddca04953c87bb5643703deb78fd625

**Comment by pupnewfster** [comment]
Hmm that is a very weird crash log, do you mind sharing your latest log? I am wondering if it maybe has some error higher up that caused things to fail.

**Comment by DarklyNightly** [comment]
i will try to find it
