### ISSUE TITLE
Ore duplication errors with 3x, 4x,and 5x duplication (Please check Recipes [raw ore, dirty ore, clumps, shards, crystals.  Might be an INDEX issue because of new Vanilla RAW Ores?]

### ISSUE THREAD

**Issue by IzumiKonataKun** [mekanism/Mekanism#7516]
### Issue description

Ore duplication is not working at the Tier 2, 3, and 4 Levels.  (3x, 4x and 5x ore duplication)

Tier 0: (1:1 ratio expected) Works as expected: 1 raw iron ore to Energized Smelter -> 1 iron ingot output.

Tire 1: (1:2 ratio expected) Error: 3 raw iron ore (required) into Enrichment Chamber -> 4 iron dust out. -> 4 iron ingots out of Energized Smelter 

Tire 2: (1:3 ratio expected) Error: 1 raw Iron ore in Purification Chamber yields 2 iron clumps yields 2 dirty iron dusts (Crusher) yields 2 iron dusts (Enrichment) yields only 2 iron ingots (Smelter)

Tier 3: (1:4 ratio expected) Error: 3 raw iron ore (required) in Chemical Injection Chamber yields 8 iron shards each yielding 1 iron clump (Purification) yielding 1 each until final product of only 1 iron ingot.

Tier 4: (1:5 ratio expected) Error: 1 iron crystal yields 1 shard each until final product of only 1 iron ingot.

 ---

Possible Solution: 
Check for Recipe errors.  Perhaps the MC 1.18.x change to Vanilla "RAW ORES" messed up the index?) -- Just a guess.
It could also be the Mecinism 10 ore duplication path does not follow the Mecinism 9 flow chart.
(In which case I am an idiot, my apologies if this is the case.)
See: https://wiki.aidancbrady.com/wiki/File:Mekanism-flowchart-v7.png

Thank you for your time and hard wiork on the mod! :)

---

Operating System & Hardware Environment (if needed)

Mods List:
Minecraft: 1.18.2
Forge: 40.1.46 (Used to connect to friend's multiplayer server Forge 40.1.18 Minimum Required)
Mekanism Tools: 10.2.3
Mekanism Additions: 10.2.3
Mekanism Defense: 10.2.3
Mekanism Generators: 10.2.3
Mekanism (Main Mod): 10.2.3
JEI: 9.7.0.196 (So I can see the Recipes and Uses)

Minecraft Launcher version: Launcher for Windows
Windows 10.0 2.3.228
Bootstrap: 1.1.17
UI:  2.3.228

Java Runtime: Default Java bundled with Minecraft / Minecraft Launcher
Java Arguments: 
-Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M

Computer Specs:
Processor: AMD Ryzen 5 3600XT 6-Core Processor; 3.79 GHz
Installed RAM: 16.0 GB
System type	64-bit operating system, x64-based processor
GPU: Nvidia GeForce RTX 2060
Nvidia Driver Version 512.77

Logs: (Debug and Latest) - No crash logs (Game does not crash.) :)
[debug.log](https://github.com/mekanis
[latest.log](https://github.com/mekanism/Mekanism/files/8885998/latest.log)
m/Mekanism/files/8885996/debug.log)

### Steps to reproduce

Tested in Minecraft single player creative peaceful mode with only the mods listed.
JEI "Uses" and "Recipes" (U / R keys) confirm all errors mentioned above.

Simply use JEI to confirm Recipes or test with creative setup.

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.46

### Mekanism version

10.2.3 (Latest)

### Other relevant versions

Minecraft: 1.18.2
Forge: 40.1.46 (Used to connect to friend's multiplayer server Forge 40.1.18 Minimum Required)
Mekanism Tools: 10.2.3
Mekanism Additions: 10.2.3
Mekanism Defense: 10.2.3
Mekanism Generators: 10.2.3
Mekanism (Main Mod): 10.2.3
JEI: 9.7.0.196

**Comment by IzumiKonataKun** [comment]
I have also tested under Forge 40.1.51
Mekanism Requires Forge 40.1.27 or Higher.

**Comment by pupnewfster** [comment]
Said ratio still exists if you use ores. You are using raw ores which support fortune hence the lower ratio.

**Comment by IzumiKonataKun** [comment]
You are absolutely correct; I am so sorry for the trouble.  Thank you for your time.
