### ISSUE TITLE
QIO exporter and Importer only accepting 1 item as filter per instance

### ISSUE THREAD

**Issue by leopupin** [mekanism/Mekanism#7519]
### Issue description

From the interface looks, like it should work like a logistical sorter for filtering, I mean I could make it export or import multiple items at the same time, instead the maximun it can do is one default and one fuzxzy mode, is it a settings somewhere, a feature being implemented or just intended this way?

### Steps to reproduce

1. Place QIO importer or exporter
2. open and place an "itemStack" as filter
3. Try to add another one

### Minecraft version

1.18.2 (Latest)

### Forge version

40,1,31

### Mekanism version

10.2.4 (Latest)

**Comment by pupnewfster** [comment]
Unable to reproduce this issue, what things are you trying to filter exactly?

**Comment by leopupin** [comment]
To be fair I re-tested and with vanilla items it did workout, what I wasn't capable of filtering was combs from "[Productive Bees](https://github.com/JDKDigital/productive-bees)" mod, however, it seems that any comb serves as filter for all combs, now I ain't sure if it's mod compatibility or something (and don't know which mod should try integrate with each other), but looks like it is, since raw ore, even from mods can be added multiples per instance.

**Comment by pupnewfster** [comment]
My guess would be each comb is the same item then so fuzzy would match any, and not only matches the exact nbt or something not really sure.

**Comment by leopupin** [comment]
> My guess would be each comb is the same item then so fuzzy would match any, and not only matches the exact nbt or something not really sure.

My toughs exactly after testing, guess the combtype os smth like that may be some nbt info, for performance idk, so maybe adding nbt filter solve this, but it's too especific of a case to be worth the attention, since I had access to other mods, I did magane to work around that.
