### ISSUE TITLE
The mekanism:oredictionificator is broke

### ISSUE THREAD

**Issue by michaelng1129** [mekanism/Mekanism#7520]
### Issue description

It cant input any capital letters and it cant search any ore

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.34

### Mekanism version

Older

### Other relevant versions

The version is 10.1.2

**Comment by AlexHgC** [comment]
What are you trying to search ? 

And don't use 1.12 tags ofc, use 1.16 tags, so you never need to use capital letters

**Comment by pupnewfster** [comment]
You can't enter capital letters because capital letters are not valid elements of a tag

**Comment by michaelng1129** [comment]
> What are you trying to search ?
> 
> And don't use 1.12 tags ofc, use 1.16 tags, so you never need to use capital letters

Oh.... I know what you are saying, Yup, its my fault, i use the old tags methods. thank!!!!!!!!!!

**Comment by michaelng1129** [comment]
> You can't enter capital letters because capital letters are not valid elements of a tag

oh............. its my fault, i use the old tags methods. The problem is completely solve. Thank!!!!!!!! and sorry for delayed replay.
