### ISSUE TITLE
1.18 QIO Display

### ISSUE THREAD

**Issue by ixam22** [mekanism/Mekanism#7521]
### Issue description

Stored item count in portableqio System only in the first three rows.
![grafik](https://user-images.githubusercontent.com/72611276/174458517-8b3a6403-a05d-43c9-b109-377756cbb00a.png)
![grafik](https://user-images.githubusercontent.com/72611276/174458526-48e9824f-9638-4d81-b9ac-c33b179a10b2.png)
![grafik](https://user-images.githubusercontent.com/72611276/174458530-7b6edc8f-ee81-4796-a949-7c9ee0d06d8c.png)

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.41

### Mekanism version

10.2.4 (Latest)

**Comment by pupnewfster** [comment]
Okay after a brief inspection this isn't a bug. We only display the extra tooltip to specify how much is actually stored if the actual amount being displayed is truncated.
