### ISSUE TITLE
Dimensional Stabilizer energy upgrades don't work.

### ISSUE THREAD

**Issue by Stinksworth** [mekanism/Mekanism#7523]
### Issue description

The Dimensional Stabilizer's energy cost isn't lowered by Energy upgrades.

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.51

### Mekanism version

10.2.4 (Latest)

**Comment by pupnewfster** [comment]
Correct it only increases the energy buffer so you can afford more chunks
