### ISSUE TITLE
mekanism logistical pipe items getting stuck endlesly    1.16.5-1.18.2

### ISSUE THREAD

**Issue by minecrafterseppe** [mekanism/Mekanism#7525]
### Issue description

if u build the setup from the image below 
ull notice behind the red block ull see items accumilating over its lifetime of the thing running 
endlesly 
a server admin told me about this and over 4k items had accumilated

this still occurs on later versions

### Steps to reproduce

![image](https://user-images.githubusercontent.com/13523046/174671472-0463b23f-2076-4960-bcf7-8097ed966931.png)

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.34

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Which version are you on exactly? As I am fairly certain I fixed that for Mekanism 10.1.0 in this commit: https://github.com/mekanism/Mekanism/commit/934056efdaf284a8b92954e08e2341d3cbbe4aa1
