### ISSUE TITLE
Crash after setting mekanism slurry in interface

### ISSUE THREAD

**Issue by Sakreton** [mekanism/Mekanism#7527]
### Issue description

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6396
also reported to the AE2 team

Our server crashes after i set a mekanism slurry in an interface. But looking at the crash report it looks like its a problem on mekanisms end instead of AE2

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.51

### Mekanism version

10.2.4 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Sakreton/6c8a2114e1b874def26a039f19b360a2

**Comment by Technici4n** [comment]
Fixed in Applied Mekanistics, a version will the fix will be out soon. Thanks for the report.
