### ISSUE TITLE
Industrial Foregoing Chunk Loading

### ISSUE THREAD

**Issue by ixam22** [mekanism/Mekanism#7528]
### Issue description

Industrial Foregoing machines like the Black hole Tank or the mob duplicator aren`t chunk loaded by the dimensional loader.
both mods and titanium on latest 1.18.2 version

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.41 because of CTM

### Mekanism version

10.2.4 (Latest)

**Comment by pupnewfster** [comment]
I don't really understand what the problem is as I don't see why either of those wouldn't be working. In what way does the black hole tank not work?
