### ISSUE TITLE
"Bad Omen" effect drains Mekasuit battery.

### ISSUE THREAD

**Issue by WillZdeKillr** [mekanism/Mekanism#7535]
### Issue description

With the Inhalation Purification Unit installed on a Mekasuit Helmet, the "Bad Omen" status effect received from killing an Illager captain is not removed, but seems to constantly and rapidly drain the suits power. If the module is turned off this stops, but this behavior seems to be a bug.

### Steps to reproduce

1. Install an Inhalation Purification Unit on a charged Mekasuit Helmet.
2. Equip the Helmet.
3. Kill an Illager to receive the "Bad Omen" status effect.
4. Watch helplessly as your suits power drains.

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.52

### Mekanism version

10.2.4 (Latest)

**Comment by pupnewfster** [comment]
Disable it making it have neutral effects go away quicker in the module tweaker. Vanilla marks it as a neutral effect.
