### ISSUE TITLE
Mekanism v9.8.3.390 - Crash while Initialization phase

### ISSUE THREAD

**Issue by VodaVodichka** [mekanism/Mekanism#7538]
### Issue description

Just a crash while loading Minecraft with my modpack

### Steps to reproduce

1. Run Minecraft with this mod
2. Wait for Initialization 
3. Profit!

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

14.23.5.2860

### Mekanism version

Older

### Other relevant versions

9.8.3.383
9.8.3.380

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/UdVeeZpQ

**Comment by thiakil** [comment]
One of your Mods' coremods is incorrectly patching Minecraft code, we don't do that in that version
