### ISSUE TITLE
Ultimate Injection Factory stops processing raw ore when input slot has one item left.

### ISSUE THREAD

**Issue by pettyron** [mekanism/Mekanism#7539]
### Issue description

When using the ultimate injecting factory, ores stop processing when the input slot reaches a count of 1 raw ore. The factory is setup to auto-eject and that works fine. Screenshots are the best I have to show the behavior. One thing I can say is if I add two more raw ores to the input slot, of the single ore for a total count of three, then the input slot will process again. This doesn't cause any crashes, on my system at least.

I searched around all the issues and found nothing that describes this bug. Hopefully, I'm not reporting something you're already aware of. But from what I've seen this hasn't been reported. I've used this same ore processing set-up on previous versions of Mekanism and it appears that this is unique on Minecraft 1.18.2.

### Steps to reproduce

1. Drop at least one stack of raw ore into the input slot.
2. Wait for the ores to process to shards.
3. Watch as one raw ore will remain in the input slot and not process into a shard.
4. Add 2 more raw ores to the remaining one in the input slot.
5. Watch as the remaining ores process into shards again

![2022-07-04_14 54 05](https://user-images.githubusercontent.com/5108440/177213309-3a6edbf3-5b9f-4dc3-ab16-bf6ba9bee117.png)
![2022-07-04_14 54 15](https://user-images.githubusercontent.com/5108440/177213355-3bfc0ee4-27f9-4741-b99d-6d8123b41a27.png)
![2022-07-04_14 54 22](https://user-images.githubusercontent.com/5108440/177213361-54a36b93-2524-498b-bdc1-edb9e9383b87.png)
![2022-07-04_14 54 25](https://user-images.githubusercontent.com/5108440/177213367-7425c132-9d4d-47c6-96c7-aa4ebb77d563.png)

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.52

### Mekanism version

10.2.4 (Latest)

### Other relevant versions

_No other versions appear to be effected._

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

_This bug doesn't cause the game to crash. At least not on single player client driven games._

**Comment by pupnewfster** [comment]
Look at the recipe, you don't have enough input for the recipe you are trying to do.

**Comment by pettyron** [comment]
This has nothing to do with a recipe. I've used this setup for 4 times ore processing in every single version of Mekanism and have never had this happen not once. I have enough energy and enough hydrogen chloride. If I fill every slot with raw ores it will still leave one raw ore unprocessed in the input slot. Every single one of the other machines processes shards, dusts etc just as before. It's only the injection factory that is now behaving differently. I've read the wiki. Nothing there says any different behavior applies to the Chemical Injection Chamber.

**Comment by Matyrobbrt** [comment]
As Pup said, look at the recipe. It was changed in 1.18

**Comment by pupnewfster** [comment]
No it wasn't changed... just the recipe for raw ore to resources is not the same as the pre-existing ore block recipes
