### ISSUE TITLE
Quantum Entangloporter Nothing is Connecting 

### ISSUE THREAD

**Issue by SilverBackHorse** [mekanism/Mekanism#7545]
### Issue description

Im trying to use the quantum entangloporter and nothing I do will allow anything to connect to it so its unusable 

Mekanism-1.18.2-10.2.4.464.jar

Forge 1.18.2 - 40.1.60

Minecraft 1.18.2

Tested Single Player And My Server with 110 Mods 

### Minecraft version

1.18.2 (Latest)

### Forge version

1.18.2 - 40.1.60

### Mekanism version

10.2.4 (Latest)

**Comment by pupnewfster** [comment]
Did you set a frequency?

**Comment by SilverBackHorse** [comment]
Yes I spent a few hours watching videos and nothing I do gets the cables to connect or function

**Comment by SilverBackHorse** [comment]
I apologize I got it to work :D
