### ISSUE TITLE
voice wont work 1.16.5

### ISSUE THREAD

**Issue by sophienix** [mekanism/Mekanism#7548]
### Issue description

i am on 1.16.5 and the voice server wont work there is no sound but its enabled and the walkie talkies are on the same channel

### Steps to reproduce

1.enable voice server 
2.turn on walkie talkie
3.push and hold talk key

### Minecraft version

1.16.x or earlier (No longer being developed)

### Forge version

36.2.34

### Mekanism version

Older

**Comment by AlexHgC** [comment]
And what about the port ? 
You need to set a port that is open on your hoster, or on your box

**Comment by pupnewfster** [comment]
Also are you on 10.1.x or are you on 10.0.x

**Comment by sophienix** [comment]
you mean the server that i am hosting ?

**Comment by sophienix** [comment]
> Also are you on 10.1.x or are you on 10.0.x

im on 10.1.2

**Comment by sophienix** [comment]
> And what about the port ? You need to set a port that is open on your hoster, or on your box

im hosting a server with a port i dont know about the voice thing

**Comment by pupnewfster** [comment]
Do you have the voice port you have set open or only the main port of the server?

**Comment by sophienix** [comment]
> Do you have the voice port you have set open or only the main port of the server?

i found out i cant do voice server my set up cant do it cause the way im hosting my server on my laptop with ngrok
