### ISSUE TITLE
1.18.2 Max tier Logistical Transporter can pull items infinitely and they get stuck in the pipe

### ISSUE THREAD

**Issue by Raidobw2** [mekanism/Mekanism#7551]
### Issue description

The max tier of logistical transporters keeps pulling items, until one day you get a disconnect issue because the NBT contained in the transporters is too big
![image](https://user-images.githubusercontent.com/17010632/178635519-b1aca59f-a7f6-44d9-aa91-06295734b8d6.png)
![image](https://user-images.githubusercontent.com/17010632/178635528-b70583e2-34ff-422d-9ce8-934c99de789c.png)
Breaking the pipe
![image](https://user-images.githubusercontent.com/17010632/178635543-b9139aab-61e1-445e-a421-89bafb31d6c0.png)
Packet header
![image](https://user-images.githubusercontent.com/17010632/178635557-ceb20770-42fb-411f-99f3-aa382e90a330.png)
Middle of packet, which composes most of the packet in a repeating manner
![image](https://user-images.githubusercontent.com/17010632/178635615-9e053464-92d5-4daa-9702-46dbb2df5de9.png)

### Steps to reproduce

1. Setup crystal growth chamber from AE2Things
2. Pull items from chamber
3. Send into filled drawer
4. Let it run for a long time
5. Reconnect one day and get a packet error while joining

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.52

### Mekanism version

10.2.4 (Latest)

### Other relevant versions

MC: `1.18.2`
Forge: `40.1.52`
Mek: `Mekanism-1.18.2-10.2.4.464.jar`
AE2Things: `AE2-Things-1.0.3-beta.jar`
AE2: `appliedenergistics2-11.1.3.jar`
Storage Drawers: `StorageDrawers-1.18.2-10.2.1.jar`

Modpack: `FTB Plexiglass Mountain 1.1.1`

Relayed from https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1106

Let me know if you need anything else, and thanks for your time in advance!

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://paste.feed-the-beast.com/view/23f9d01c

**Comment by pupnewfster** [comment]
Storage drawers has historically had very buggy implementations of item handlers so I am going to go ahead and say it is related to that and there is nothing on our end we can do. I highly recommend switching from storage drawers to functional storage.

**Comment by Raidobw2** [comment]
I thank you for that information! I've got it noted for the future and I'll pass the message along as well. Cheers
