### ISSUE TITLE
Minimum requirement of ore before processing

### ISSUE THREAD

**Issue by dittymargoo** [mekanism/Mekanism#7553]
### Issue description

I've just encountered the new 3 ore to 4 dust in an enrichment chamber and suddenly started to realise the implications.  I'm using the 1.18.2 version 10.2.4.464 and about 156 mods.  

My issue is...What can I do to prevent the machines from clogging when they get down to less than 3 ores in the input slot or slots?  Is there something I'm missing? How will this effect a triple (probably not) or quadruple process when all machines will get blocked up or is this only relevant for 'double' processing?  Would it be possible to make the machines not accept ores unless there are the required input of 3, or multiples of 3, and to discharge any ore that clogs up a system?

Is it possible to turn off the 3 ore requirement in the configs?  At least until I can figure out how to redesign my ore processing setup using another mod to limit what goes in.

My apologies if this question has been asked before.

Thanks for any ideas.

### Minecraft version

1.18.2 (Latest)

### Forge version

40.1.60

### Mekanism version

10.2.4

**Comment by tuc56** [comment]
If you silk touch the ores, it's still 1-2. This was added because fortune can multiply raw ores.
