### ISSUE TITLE
Error executing task on Chunk source main thread executor for minecraft:overworld net.minecraft.ReportedException: Feature placement

### ISSUE THREAD

**Issue by Azodox** [mekanism/Mekanism#7556]
### Issue description

I started my server today, and an error started to occurs whenever my friend joined my server, I think one of my chunk is corrupted but even though I teleported him out of this chunk, my server still crashes.
I don't know if it's related to Mekanism, but that's our biggest mod installed, and if it's not maybe you can still help us. Thank you in advance.

### Steps to reproduce

I don't really know, it's random.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.60

### Mekanism version

Older

### Other relevant versions

Everything is in the crash report.

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/M46vLWWN

**Comment by pupnewfster** [comment]
I don't think this has anything to do with Mekanism and just looks like vanilla is having issues spawning in a shipwreck or something, but no idea as I don't have a deep understanding of how world gen works.

**Comment by Azodox** [comment]
Thank you, I opened this issue just to make sure :)
