### ISSUE TITLE
Hang on auto-subscribing MekanismRenderer to MOD

### ISSUE THREAD

**Issue by RavynousHunter** [mekanism/Mekanism#7557]
### Issue description

I'm attempting to play with the current version of Mekanism (v10.3.0) under Forge 41.0.100 with a few other mods, but it kept hanging before the loading screen would pop up.  I saw that the last thing recorded in the debug.log was an attempt to auto-subscribe MekanismRenderer.  When I disable Mekanism, my instance starts up just fine; re-enable Mekanism, and the hang shows back up.  I've tried letting it sit for nearly an hour without success; the only thing that works is disabling Mekanism.

This is the last thing in debug.log before it would hang:

`[net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber/LOADING]: Auto-subscribing mekanism.client.render.MekanismRenderer to MOD`

The full debug.log can be read [here](https://pastebin.com/WXXvA2Hv).

[Here](https://pastebin.com/iLUwfnYM) is the primary log, as well.

### Minecraft version

1.19 (Latest)

### Forge version

41.0.100

### Mekanism version

10.3.0 (Latest)

**Comment by pupnewfster** [comment]
Are you able to get it working with just mekanism and no other mods? Also please try testing the issue on forge 41.0.108 as that fixed some issues that maybe are related though I slightly doubt it.

**Comment by RavynousHunter** [comment]
Apologies, my internet's been out for the past 2 days, else I'd have replied earlier.  It seemed to have been a Forge issue; updating to 41.0.105 (haven't yet updated for aforementioned reasons) seems to have corrected the problem.
