### ISSUE TITLE
Not support IC2's EU

### ISSUE THREAD

**Issue by heipiao233** [mekanism/Mekanism#7564]
### Issue description

![叶公好龙](https://user-images.githubusercontent.com/81846300/181779945-da39d253-5d77-40d1-ab4e-061e67bbf6f2.jpg)

### Steps to reproduce

1. install the mods
2. place a IC2 machine
3. place a universal cable beside
4. place a IC2 cable

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.60

### Mekanism version

Older

### Other relevant versions

IC2: 2.9.95+ex118

**Comment by pupnewfster** [comment]
Ic2 does not have a stable api yet. Until they do in a version we support nothing is going to happen
