### ISSUE TITLE
Crashing on placement of Mechanical pipes

### ISSUE THREAD

**Issue by NeoAzaezel** [mekanism/Mekanism#7566]
### Issue description

Encountered an issue resulting in a game crash when placing Basic Mechanical pipes on stone
[crash-2022-08-03_19.47.27-client.txt](https://github.com/mekanism/Mekanism/files/9255825/crash-2022-08-03_19.47.27-client.txt)

### Steps to reproduce

place mechanical pipe

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.31

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Given the fact this isn't even giving a proper stack trace (please try providing your latest log maybe it will show something), I am going to go with odds are likely it is one of the 100s of mixins/coremods you have. Also if you can reproduceably get this crash please try it without not enough crashes installed as I feel like that might make the crash log a lot easier to read.
