### ISSUE TITLE
Bomba de agua

### ISSUE THREAD

**Issue by erdeivid88** [mekanism/Mekanism#7568]
### Issue description

cuando pongo la bomba de agua con en el agua no coge agua aunque tenga energia

### Steps to reproduce

1. pongo el agua en el suelo , 2. pongo la bomba de agua , 3. le conecto la electricidad , 4. le conecto la tubeia , 5. no sale agua

### Minecraft version

1.19(.1) (Latest)

### Forge version

42.0.2

### Mekanism version

10.3.1 (Latest)

**Comment by pupnewfster** [comment]
Usando el traductor de Google:

¿Puedes mostrar una foto de tu configuración? Mi mejor suposición es que colocó la bomba en el agua en lugar de sobre el agua, esto no funciona.
