### ISSUE TITLE
cannot manually compile the mod

### ISSUE THREAD

**Issue by term2112** [mekanism/Mekanism#7569]
### Issue description

I am getting the following error when trying to compile the mod, i am not sure what is going on.

Microsoft Windows [Version 10.0.22000.795]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\system32>cd C:\Users\allen\Downloads\Mekanism-1.19.x\Mekanism-1.19.x

C:\Users\allen\Downloads\Mekanism-1.19.x\Mekanism-1.19.x> gradlew build
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Mekanism-1.19.x'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.ajoberstar.grgit:grgit-gradle:5.0.0.
     Required by:
         project : > org.ajoberstar.grgit:org.ajoberstar.grgit.gradle.plugin:5.0.0
      > No matching variant of org.ajoberstar.grgit:grgit-gradle:5.0.0 was found. The consumer was configured to find a runtime of a library compatible with Java 8, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '7.5.1' but:
          - Variant 'apiElements' capability org.ajoberstar.grgit:grgit-gradle:5.0.0 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares an API of a component compatible with Java 11 and the consumer needed a runtime of a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.5.1')
          - Variant 'javadocElements' capability org.ajoberstar.grgit:grgit-gradle:5.0.0 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.5.1')
          - Variant 'runtimeElements' capability org.ajoberstar.grgit:grgit-gradle:5.0.0 declares a runtime of a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component compatible with Java 11 and the consumer needed a component compatible with Java 8
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.5.1')
          - Variant 'sourcesElements' capability org.ajoberstar.grgit:grgit-gradle:5.0.0 declares a runtime of a component, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 8)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '7.5.1')

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
2 actionable tasks: 2 executed

### Steps to reproduce

- Download latest zip
- Attempt to compile using gradlew command
- Error occurs

### Minecraft version

1.19(.1) (Latest)

### Forge version

N/A

### Mekanism version

Current Dev Branch (Manually Compiled)

**Comment by pupnewfster** [comment]
Given we recently updated a gradle plugin you need to make sure you are using JDK 11 or higher to run the gradle warpper, but it seems you are trying to run gradle using JDK8.

**Comment by term2112** [comment]
Installed JDK18, it appears to have worked
