### ISSUE TITLE
Metalurgic Infuser not working

### ISSUE THREAD

**Issue by rafokes** [mekanism/Mekanism#7570]
### Issue description

Hi, I came to report my problem. I put the metallurgical infuser on the ground, and then I put redstone, the ore, and when I go to put the fuel, it doesn't work. It just keeps counting 64 coals, or 64 redstones, doesn't go down and doesn't fill the fuel bar.

### Steps to reproduce

1. Place te Metallurgic Infuser in the ground
2. Put redstone in power.
3. Put coal in the fuel.
4. Nothing happens, the fuel bar does not rise

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

14.23.5.2859

### Mekanism version

Older

**Comment by AlexHgC** [comment]
Not a bug, that's just not how it works. Coal can't be used as "fuel" because it doesn't make energy itself ( need a heat generator ). 

Energy slot on machines use Redstone, not coal. 
Put Redstone on the energy slot then Redstone ore, and it will works

**Comment by pupnewfster** [comment]
Could you show a picture of your Infusers GUI. Also hover over the infuse type's bar, is there some other infuse type currently "stuck" in it that might just not be fully evident/rendering because it is at such a tiny amount stored?
