### ISSUE TITLE
Atomic Disassembler does not till soil as stated in Wiki

### ISSUE THREAD

**Issue by TheOrionsun** [mekanism/Mekanism#7571]
### Issue description

When the different speeds for the Atomic Disassembler are sulected none will till the soil as described in the wiki.
Is this still a expected function for the Atomic Disassembler?

### Steps to reproduce

Created new game with only Mekanism loaded.
Went into creative and equipped  a Atomic Disassembler.
Tried all speed settings on a grass block and does nothing.
Tried in creative and survival.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.69 and older versions

### Mekanism version

Older

### Other relevant versions

Running Mekanism version 10.2.5 
MC version 1.18.2

**Comment by pupnewfster** [comment]
The wiki is outdated on some things as it is mainly maintained by the community. As of Mekanism 10.0 that feature was remove from the disassembler and moved to the meka-tool's farming module

**Comment by TheOrionsun** [comment]
Ok, I will update the Wiki
