### ISSUE TITLE
Mekanism multiblocks become not formed

### ISSUE THREAD

**Issue by MechanID** [mekanism/Mekanism#7573]
### Issue description

While playing on server sometimes multiblock structures like thermal evaporation plant or fusion reactor become not formed:
evaporation plant - two times for last 24h, maybe 8times last 7 days.
fusion reactor - one time.
All structures are built inside chunk borders,
Chunks are loaded via ftbchunks
Server was not restarted when issue occurs
If i remove one block and place it back structure becomes formed, and Fusion rector still running 

### Steps to reproduce

I am not sure how this reproduce, but i can upload map to google drive or somewhere
![2022-08-08_14 19 05](https://user-images.githubusercontent.com/9780710/183409566-35e82d62-896c-40df-86c8-8aa80555b292.png)
![2022-08-08_14 19 14](https://user-images.githubusercontent.com/9780710/183409608-0eaf89e1-a30e-488c-91e9-6a439ba02bc7.png)
![2022-08-08_14 18 47](https://user-images.githubusercontent.com/9780710/183409630-c65bf8ac-cea4-46ab-b709-01c9e8f369ef.png)
.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.67

### Mekanism version

Older

### Other relevant versions

I am playing modpack FTB Presents Direwolf20 1.80:
minecraft version: 1.18
forge version: 40.1.67
Mekanism mods version: 1.18.2-10.2.5.465

**Comment by pupnewfster** [comment]
Yeah I have no clue what could be causing this especially given you say they are fully contained in a single chunk. Does right clicking with a configurator on them show an error message for what it thinks is wrong with it? (It may just make it form I forget how it would handle cases like it being valid but it isn't actually formed)

**Comment by MechanID** [comment]
Hello, 
yep - right click with configurator "items mode" make it forms, no errors.
Is there way to enable some debug info to logs ?

**Comment by pupnewfster** [comment]
Unfortunately no, and I am honestly sort of unsure what might be causing something like this to happen as the multiblock is entirely in a single chunk AND on top of that it is chunk loaded so there is even less things that might have potentially somehow gone wrong. I am not sure what the default ftb chunks configs are or how your server is setup but I think ftb chunks does have a config that can make chunks unload a certain amount of time after the "owner" of them has logged off, so it might be of some use to know how that is configured on the server. (If the chunks do unload there is a very minor idea I have of what is going wrong that is semi related to what the issue of #6356 was, though even with that and how multiblocks recheck for validity I would presume they would fix themselves anyway, not to mention be extremely unlikely to have that happen in the first place when they are in a single chunk)
