### ISSUE TITLE
Endergenic generators are not rendering the pearl. UI for wrench is also missing. (v1.18)

### ISSUE THREAD

**Issue by WildstyleTrinity** [mekanism/Mekanism#7574]
### Issue description

The endergenic generators are not rendering anything (Screenshot and world are attached). The Wrench is also not displaying a UI which makes it almost impossible to configure the generator.
I know that OneProbe is showing some sort of information, but trust me, it is a "blind configuration" even with OneProbe.

This energy is by far the most genius and visual awesome I have ever seen. So I would love to see it fully functional again. :)

### Steps to reproduce

Building an endergenic generator

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.67 (Direwolf20 1.18 Modpack)

### Mekanism version

Older

### Other relevant versions

Mekanism 1.18.2-10.2.5.465
plus Generators and Tools

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://drive.google.com/drive/folders/1P6AjzXjcUoAA_DrS_Uw83UOSTjaMJKZn?usp=sharing

**Comment by pupnewfster** [comment]
None of that stuff is from Mekanism.

**Comment by Seniorendi** [comment]
My friend, you need to read.
![image](https://user-images.githubusercontent.com/67484093/183903363-fd76e8e9-bd28-477c-8763-3985d188ff7b.png)
RFTools Power is what you searching for
