### ISSUE TITLE
Index out of bounds error on lan server

### ISSUE THREAD

**Issue by Bazyliii** [mekanism/Mekanism#7577]
### Issue description

As in the title of issue, me and my friends had been experiencing out of bounds errors whenever something like entering nether, or Mekanism block placement happens. We tried only 4 mekanism mods without any other mods, and error stil occurs. 

### Steps to reproduce

1. Create new world
2. Build nether portal
3. Open game to lan
4. Ask your fiend to walk in to the portal
5. His game should throw an error
![PXL_20220812_213809138](https://user-images.githubusercontent.com/67436562/184431400-07dd3192-cec7-4c23-8c85-edaeeb1cd24c.jpg)
Sorry for photo instead of ScreenShot but my friend had problems with sniping tools :/

### Minecraft version

1.19.1 or 1.19.2 (Latest)

### Forge version

43.0.8

### Mekanism version

10.3.2 (Latest)

**Comment by pupnewfster** [comment]
Please provide the latest log of the client that disconnected, as a picture of your monitor of an undescript error provides no information.

**Comment by Bazyliii** [comment]
My Log:
[latest.log](https://github.com/mekanism/Mekanism/files/9331067/latest.log)
My friends Log (the one who is getting kicked with error message):
[latest.log](https://github.com/mekanism/Mekanism/files/9331069/latest.log)

**Comment by pupnewfster** [comment]
Hmm weird, I don't see anything in the logs so I will need to try this when I get the chance and see if I can reproduce it, is it just going through a nether portal or is there more steps like placing specific blocks? (I also presume given you tried with just mekanism's base mods you also tried without Mekanism to confirm there isn't just some general lan issue in the current version of mc?)

**Comment by Bazyliii** [comment]
This error took place in some more instances like placing mekanism blocks and dying but it was random, when going through nether portal had 100% chance of error on my friends side.

We actually did try without mekanism with just forge and everything was good.

**Comment by pupnewfster** [comment]
I haven't gotten around to releasing the workaround I implemented yet, but if you update to forge 43.0.12 or higher this should no longer happen.
