### ISSUE TITLE
Some "Silk Touch" mined ores are not processed by Mekanism

### ISSUE THREAD

**Issue by Antaiir** [mekanism/Mekanism#7578]
### Issue description

Hi there, thanks for this great mod.

I built Mekanisms ore processing chain as described in the official wiki (tier 3 atm). But some ores mined with silk touch (enchanted diamond pickaxe) are not accepted by the Purification Chamber nor the Chemical Injection Chamber, both machines are upgraded to it's factory version.

The ores as far as i found are Diamond, Lapislazuli and Redstone so far. Other ores like Iron, Copper, Gold and Osmium for example are processed like expected.

I play together with a friend on my own dedicated forge server, in case this is important.

I would expect, that _all_ silk touched ores are properly processed by the chain. Am i wrong or is this indeed an issue?

Thanks in advance! :-)

### Steps to reproduce

1. Build the processing chain.
2. Mine ores with silk touch.
3. Insert the ores into the processing chain.
4. ... or at least try to insert them... ;-)

### Minecraft version

1.19.1 or 1.19.2 (Latest)

### Forge version

42.0.1

### Mekanism version

10.3.1

### Other relevant versions

"Mekanism: Tools", "Mekanism: Additions" and "Mekanism: Generators" 10.3.1 are installed.

**Comment by UnknownSerhan** [comment]
This is how ore processing works, you only can process the ores that dropped ore blocks in older versions. Redstone, diamond, lapis, coal, emerald and fluorite won’t work with ore processing. To put it in short, anything that doesn’t drop raw ores won’t work with ore processing.

**Comment by Jorue23** [comment]
Everything that UnknownSerhan said is right, if you want to process the ores you listed as not working, you'll have to use a enrichment chamber. And maybe also consider install the mod "just enough items" it shows you all the recipes to avoid such issues in the future and also maybe not use the wiki cause it's outdated.

**Comment by Antaiir** [comment]
Thanks for your replies. Well... that's a pity tbh.

Yes, i know JEI from an older game version. But since i play on MC 1.19.1, there's only an alpha version of JEI available atm, so i'll wait for a release version before i use it again.

**Comment by pupnewfster** [comment]
JEI is stable just use it, the only reason it is alpha is mezz doesn't get around to marking builds as release all that often. But yes as others have mentioned those things that process directly into output or drop their fully processed output when not using silk touch do not support the 3-5x chain and only support being put in an enricher.

**Comment by KarnatourWasTaken** [comment]
I think installing JAOPCA could fix your issue https://www.curseforge.com/minecraft/mc-mods/jaopca

**Comment by Jorue23** [comment]
This is not an issue? It's just a person that lacks some information. Also jaopca mostly just adds block forms of items like the sulfur dust block.
