### ISSUE TITLE
Block placing sound sometimes doesn't play on Multiblocks

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#7580]
### Issue description

The sound of block placing doesn't play sometimes, I don't think I can tell this by words, so I got a video for it.

Video: https://discord.com/channels/554379889122213888/726460788734296136/1008380319889641505

### Steps to reproduce

1. Form a multiblock, then place a part of other multiblock (I used reactor glass in the video)
2. Keep replacing and breaking the same block, it will eventually will have no block place sound.

### Minecraft version

1.19.1 or 1.19.2 (Latest)

### Forge version

43.0.8

### Mekanism version

10.3.2 (Latest)

**Comment by pupnewfster** [comment]
Upon further investigation I don't believe this bug is on Mekanism's end as much as Minecraft's end as I seem to be able to reproduce it with stone blocks.
