### ISSUE TITLE
Ore gets stuck in machine

### ISSUE THREAD

**Issue by closeshot** [mekanism/Mekanism#7586]
### Issue description

The ore gets stuck in the enrichment chamber and doesnt smelt, using sophisticated chests and the pipez mod to transport items into the enrichment chamber. 

Also using the chunk loaders mod to keep the chunks loaded when away from base.

One other thing I am using pipez to transport energy from the basic gens mod so not sure if that can be the cause to when leaving base doesn't think it has energy in the block

### Steps to reproduce

1. Insert ore into sophisticated chest.
2.  Pipez insert ore into enrichment chamber.
3. When I walk away the ore doesn't smelt in the enrichment chamber.
4. Come back and ore isnt transported into the energized smelter :(

### Minecraft version

1.19.1 or 1.19.2 (Latest)

### Forge version

43.1.1

### Mekanism version

10.3.2 (Latest)

**Comment by Omikron-Delta** [comment]
Could you please include a screenshot of your setup? As well as confirming that the Enrichment Chamber has Eject Items turned on and the sides configured correctly.

**Comment by closeshot** [comment]
Ok, here is the setup

![2022-08-21_09 48 45](https://user-images.githubusercontent.com/35141563/185794100-a4d032d2-f530-4cdc-9060-063306691c07.png)
![2022-08-21_09 48 49](https://user-images.githubusercontent.com/35141563/185794101-3f316c57-42bb-47d5-85b5-fb3aa2ccc10a.png)
![2022-08-21_09 49 01](https://user-images.githubusercontent.com/35141563/185794102-264ab13a-4efe-4811-962a-861c6c755558.png)

**Comment by pupnewfster** [comment]
Look at the recipe you don't have enough input
