### ISSUE TITLE
Fusion reactor reaction stops every time the server launchs and we join it

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#7587]
### Issue description

When we leave and stop the server while fusion reactor runs, the reaction stops once we relaunch the server and join it, even though the chunks are always loaded. Although it keeps all the plasma and case heat etc. So only the reaction stops.

### Steps to reproduce

1. Build a fusion reactor, ignite it and leave the server.
2. Stop the server and relaunch the server.
3. Join the server. The fusion reactor ignition will stop.

### Minecraft version

1.19.1 or 1.19.2 (Latest)

### Forge version

43.1.1

### Mekanism version

10.3.2 (Latest)

**Comment by pupnewfster** [comment]
Question given I did reproduce it initially, but upon closer investigation it is just because of running `/stop` without first running `save-all` so the server rolled back (the hohlraum went back into the fusion reactor, etc). Did you save the world to ensure all block's had a chance to save if needed before stopping the server?

**Comment by UnknownSerhan** [comment]
I use the server panel to stop the server, so no, I don’t use save-all command before stopping the server. But iirc, the server actually saves everything before stopping?

**Comment by pupnewfster** [comment]
I have no idea, I know vanilla doesn't automatically I have no idea what your server host does when you press the stop button.

**Comment by aaron330i** [comment]
I solved this by putting a filled Hohlraum into a creative bin then piping them to the fusion reactor. Works great but you will need to cheat in a creative bin for it to work. I view the creative bin as making the fusion reactor function as it's supposed to work. If you have modular routers, you can even hide the whole setup.
