### ISSUE TITLE
Digital Miner energy usage is more than energy buffer when in nether with y -64 to y 319

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#7589]
### Issue description

Adding speed and energy upgrades onto a digital miner, then turning on silk touch, setting range to 32, and setting min and max y numbers to y -64 and y 319, and then bringing the miner to nether and trying to mine something "locks" the miner. It needs more energy than its energy buffer.
![Uploading 2022-08-22_16.35.15.png…]()

### Steps to reproduce

1. Get a digital miner, add speed and energy upgrades on it and turn on silk touch.
2. While in overworld, set the range to 32 , min and max y numbers to -64 to 319.
3. Go to the nether, place down the miner, set it to mine something then start it.
4. The miner won't be able to mine anything because it will need more energy than its energy buffer.

### Minecraft version

1.19.1 or 1.19.2 (Latest)

### Forge version

43.1.1

### Mekanism version

10.3.2 (Latest)

**Comment by UnknownSerhan** [comment]
The image didn't load for some reason, sorry for that. https://discord.com/channels/554379889122213888/726460788734296136/1011266895036551189 this should work.

**Comment by iCloudly** [comment]
im playing 1.20.1 version of Mekanism and i have same issue here
