### ISSUE TITLE
Transporters break upon reloading a world

### ISSUE THREAD

**Issue by ILaxaiI** [mekanism/Mekanism#7592]
### Issue description

After reloading a world, all transporters inside loaded chunks (anchor upgrades/spawn chunks)
show up as having no network with the network reader, and transport no energy/items.

### Steps to reproduce

0) (re-)Start MC.
1) Load a world (place pipes).
2) save & exit.
3) load the same world, if you load a different world it seems to work properly, but only once.
4) network reader reads "no network"
![image_2022-08-24_210506872](https://user-images.githubusercontent.com/58485516/186502172-f4d7d99b-2052-402c-acf7-99d3c9ded008.png)

### Minecraft version

1.19.1 or 1.19.2 (Latest)

### Forge version

43.1.2

### Mekanism version

10.3.2 (Latest)

### Other relevant versions

It happens with only Mekanism (tools/additions/generators) installed

**Comment by pupnewfster** [comment]
Could you please run `/mek debug` and then exit and rejoin the world and upload your latest log? It should add some extra logging related to transmitters.

**Comment by ILaxaiI** [comment]
[latest.log](https://github.com/mekanism/Mekanism/files/9418960/latest.log)

**Comment by ILaxaiI** [comment]
Im entirely guessing, but i think it might be due to Minecraft not fully unloading chunks when you save & exit, and thus not reloading them properly the second time

**Comment by ILaxaiI** [comment]
So another funny thing i noticed:
First load testworld 1:
![image](https://user-images.githubusercontent.com/58485516/186511441-bb0fcf26-b677-49ea-8512-c230b26d0070.png)

Here all pipes work properly after a game restart


Second load:
![image](https://user-images.githubusercontent.com/58485516/186511522-7c31c31a-d913-4c0b-bb01-a38936d3f20f.png)

pipes are broken as described.

First load of a 2nd testworld, at the exact same coordinates:
![image](https://user-images.githubusercontent.com/58485516/186511656-894e7901-aa0a-4af5-9160-494ddd7e8b0d.png)

The Pipes wich overlap with the previous world break, however the new ones work fine

[debug.log](https://github.com/mekanism/Mekanism/files/9419087/debug.log)
[latest.log](https://github.com/mekanism/Mekanism/files/9419088/latest.log)

**Comment by pupnewfster** [comment]
I will try to get a build out sometime in the next couple days containing the fix, but yeah looks like when earlier in 1.19 I fixed a different bug I accidentally introduced this by not properly clearing the extra caches I added.
