### ISSUE TITLE
Fusion Reactor Controller doesn't drop the hohlraum in it when broken

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#7594]
### Issue description

When we break a fusion reactor controller while it has a hohlraum in it, it doesn't drop the hohlraum.

### Steps to reproduce

1. Build a Fusion Reactor.
2. Put a hohlraum in the Fusion Reactor Controller.
3. Break the controller, the hohlraum won't drop.

### Minecraft version

1.19.1 or 1.19.2 (Latest)

### Forge version

43.1.1

### Mekanism version

10.3.2 (Latest)

**Comment by pupnewfster** [comment]
I am fairly certain this is intended as it is stored in the multiblock so then if you replace the reactor controller it should have it inside of it?

**Comment by UnknownSerhan** [comment]
Nope, it disappears.
