### ISSUE TITLE
[extra-golems] Enriching factory produces 1:12 when processing raw iron | gold

### ISSUE THREAD

**Issue by FrederickEngelhardt** [mekanism/Mekanism#7596]
### Issue description

Any version of the enriching facility will turn "raw iron" or "raw gold" into 12 iron|gold dust.

### Steps to reproduce

1. Put "raw iron" or "raw gold" in an enrichment chamber.
2. Get 12 iron|gold dust back when it should only be 2.

Only applies to "raw iron" and "raw gold" which is a minecraft base item. 

### Minecraft version

1.19.1 or 1.19.2 (Latest)

### Forge version

43.1.1

### Mekanism version

10.3.2 (Latest)

**Comment by UnknownSerhan** [comment]
![image](https://user-images.githubusercontent.com/69000972/187033305-44e374ce-aed5-4679-997c-e3d3c309007a.png)
![image](https://user-images.githubusercontent.com/69000972/187033337-de5e752f-dccc-462a-bb72-08f89e16e799.png)

**Comment by pupnewfster** [comment]
Yeah definitely going to need more information on what you mean by "raw iron". Do you mean the item (first picture of serhan's), do you mean the block (second picture), or do you mean like the actual ore block (which some places used to call the "raw ore block" to represent that it was the literal ore block.

**Comment by Seniorendi** [comment]
You changed the title but didn't answered the questions?

**Comment by FrederickEngelhardt** [comment]
> You changed the title but didn't answered the questions?

Lol I never hit refresh, so I missed this message.

To clarify
This issue includes "raw iron", "raw gold", "raw copper" which output to 12 raw "X". IE 1 ingredient turns into 12 dust
![mekanism-1-19-2-12x-raw-ores](https://user-images.githubusercontent.com/31741411/187070681-1661f267-1a5a-4f44-a61b-b8efc3a0244b.png)



If you were to do the same thing with the silk touch version of iron, copper, gold it would output 2 dust.

If you look for the recipe for raw osmium it shows 3 raw osmium -> 4 dust. This seems more reasonable.

**Comment by FrederickEngelhardt** [comment]
Update: With mekanism only on 1.19.2 I can't replicate this bug. So this should issue should be an incompatibility with some other mod. 

Any recommendations on how to find it? My modlist is attached below.

**Modlist**
ToolBelt-1.19-1.19.6.jar
Vampirism-1.19.2-1.8.0-beta.1.jar
waystones-forge-1.19-11.1.0.jar
wormhole-1.1.10b-forge-mc1.19.jar
wthit-forge-5.11.3.jar
zombieawareness-1.19.2-1.12.3.jar
[1.19.2] MacroKeybindsMod-1.1.jar
AI-Improvements-1.19-0.5.1.jar
appleskin-forge-mc1.19-2.4.2.jar
Aquaculture-1.19.2-2.4.6.jar
architectury-6.2.43-forge.jar
armorplus-1.19.2-19.0.0-beta.jar
ars_elemental-1.19.1-0.5.1.1.jar
ars_nouveau-1.19.1-3.2.10.jar
ars_scalaes-1.19.1-1.7.0.5.jar
Atlas-Lib-1.19.2-1.1.5.jar
AttributeFix-Forge-1.19.2-17.1.2.jar
AutoRegLib-1.8-54.jar
badpackets-forge-0.2.0.jar
balm-4.5.3.jar
BetterAdvancements-1.19.2-0.2.2.142.jar
betteranimalsplus-1.19-11.0.7-forge.jar
blockui-1.19-0.0.60-ALPHA.jar
Bookshelf-Forge-1.19.2-16.1.4.jar
caelus-forge-1.19.2-3.0.0.6.jar
cant_sleep_clowns_will_eat_me-1.19.2-1.1.0.0.jar
carryon-1.19-1.18.1.2.jar
cloth-config-8.0.75-forge.jar
Clumps-forge-1.19.2-9.0.0+11.jar
CodeChickenLib-1.19.2-4.3.0.469-universal.jar
collective-1.19.2-4.50.jar
comforts-forge-6.0.0+1.19.2.jar
configured-1.5.8-1.19.jar
Controlling-forge-1.19.2-10.0+6.jar
coroutil-1.19.2-1.2.37.jar
corpse-1.19.2-1.0.0.jar
CosmeticArmorReworked-1.19.2-v1.jar
craftable_slimeballs 1.19.2.jar
craftingtweaks-forge-1.19-15.1.0.jar
creeperoverhaul-2.0.4-forge.jar
Cucumber-1.19.1-6.0.0.jar
curios-forge-1.19.2-5.1.1.0.jar
domum_ornamentum-1.19-1.0.59-ALPHA-universal.jar
elevatorid-1.19-1.8.7.jar
elytraslot-forge-6.0.0+1.19.2.jar
EnchantmentDescriptions-Forge-1.19.2-13.0.1.jar
EnderStorage-1.19.2-2.10.1.181-universal.jar
Enhanced_Celestials-forge-1.19-2.1.0.1.jar
extragolems-19.2.1.jar
FastLeafDecay-30.jar
Follow-Me-1.19.2-1.1.8b.jar
geckolib-forge-1.19-3.1.18.jar
Guide-API-VP-1.19.2-2.2.4.jar
ilikewood-1.19.2-10.1.1.0.jar
ilikewoodxbyg-1.19.2-10.1.0.jar
improvedmobs-1.19-1.10.15-forge.jar
infernalmobs-1.19.2.1.jar
inventorysorter-1.19.2-21.0.0.jar
ironbows-1.19.2-1.2.jar
ironchest-1.19-14.1.4.jar
IronJetpacks-1.19.1-6.0.0.jar
jei-1.19.2-forge-11.2.0.256.jar
journeymap-1.19.1-5.9.0beta2-forge.jar
JustEnoughResources-1.19.2-1.1.0.179.jar
K-Turrets-2.0.0-1.19.jar
mcjtylib-1.19-7.0.2.jar
Mekanism-1.19.2-10.3.3.470.jar
MekanismAdditions-1.19.2-10.3.3.470.jar
MekanismGenerators-1.19.2-10.3.3.470.jar
MekanismTools-1.19.2-10.3.3.470.jar
minecolonies-1.19.2-1.0.988-ALPHA.jar
MobCatcher-Forge-1.19.2-1.2.7.jar
MouseTweaks-forge-mc1.19-2.23.jar
movingelevators-1.3.9-forge-mc1.19.jar
multi-piston-1.19-1.2.16-ALPHA.jar
NaturesCompass-1.19.2-1.9.7-forge.jar
Oh_The_Biomes_You'll_Go-forge-1.19.2-2.0.0.9.jar
OptiFine_1.19.2_HD_U_H9.jar
Patchouli-1.19.2-76.jar
Quark-3.3-369.jar
rftoolsbase-1.19.1-4.0.2.jar.disabled
rftoolsbuilder-1.19.1-5.0.3.jar.disabled
rftoolspower-1.19-5.0.1.jar.disabled
rftoolsstorage-1.19-4.0.1.jar.disabled
Satako-6.0.0-1.19.jar
ScalingHealth-1.19.2-7.0.0+6.jar
silencemobs_1.19.2-2.3.jar
silent-lib-1.18.2-6.2.0.jar
silent-lib-1.19-7.0.1.jar
SimpleStorageNetwork-1.19-1.6.4.jar
smallships-1.19.2-2.0.0-Alpha-0.4.jar
sophisticatedbackpacks-1.19.2-3.18.17.679.jar
sophisticatedcore-1.19.2-0.5.1.97.jar
spawnermod-1.19.0-1.9.1+Forge.jar
structurize-1.19.2-1.0.437-ALPHA.jar
supermartijn642configlib-1.1.6b-forge-mc1.19.jar
supermartijn642corelib-1.0.19a-forge-mc1.19.jar
swingthroughgrass-1.19.2-1.10.0.jar
tenshilib-1.19-1.6.10-forge.jar
TerraBlender-forge-1.19.2-2.0.1.125.jar
thedragonlib-1.19-1.0.0.jar

**Comment by FrederickEngelhardt** [comment]
Okay figured out the issue, it's a compatibility issue with [Extra Golems](https://github.com/MinecraftModDevelopmentMods/Extra-Golems). Not sure why their mod would conflict, but maybe there is something that modifies the recipe for raw ores and their outputs.

**Comment by pupnewfster** [comment]
https://github.com/MinecraftModDevelopmentMods/Extra-Golems/blob/master-1.19/src/main/resources/data/forge/tags/items/storage_blocks/raw_copper.json looks like they are claiming the raw items are raw blocks... nothing we can do about it they just have to stop adding things to the wrong tags, forge already adds vanilla things to the proper storage blocks tags: https://github.com/MinecraftForge/MinecraftForge/blob/1.19.x/src/generated/resources/data/forge/tags/items/storage_blocks/raw_copper.json

**Comment by skyjay1** [comment]
Fixed in Extra Golems 19.2.2, my apologies.
