### ISSUE TITLE
Unable to Launch with new mekanism version

### ISSUE THREAD

**Issue by mason4475** [mekanism/Mekanism#7597]
### Issue description

I am trying to do a modded survival with a couple people
When I try to launch my game, it says

The game crashed whilst initializing game
Error: net.minecraftforge.fml.ModLoadingException: Mekanism (mekanism) encountered an error during the common_setup event phase

Exit Code: -1

Anyone know how to fix it?

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.3

### Mekanism version

10.3.3 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/FxPqAvuM

**Comment by pupnewfster** [comment]
Please provide your latest log as I believe something is crashing higher up the chain.

**Comment by Godstorm7** [comment]
> Please provide your latest log as I believe something is crashing higher up the chain and blaming the wrong mod in the crash report.

for me happens this too

**Comment by pupnewfster** [comment]
I still need the latest log if you want help seeing what is causing it though.

**Comment by DimaSheiko** [comment]
I am experiencing errors as soon as minecraft finishes loading. I've been trying for an hour to find a solution, but I can't get anything in the log to tell me specifically what's going wrong.

Any idea what is going on?
https://www.klgrth.io/paste/p8e48

**Comment by pupnewfster** [comment]
Optifine it isn't compatible with the version of forge you are using

**Comment by DimaSheiko** [comment]
> Optifine it isn't compatible with the version of forge you are using

Unbelievable, I didn't think it was optifine, before asking here I deactivated all mods except optifine thinking it was impossible that it was the problem since the other mods were loading normally.

Thank you very much for helping me. I've lowered the forge version a little bit.
