### ISSUE TITLE
MEKANISM CRASH NO LAODING

### ISSUE THREAD

**Issue by wuggyfoot** [mekanism/Mekanism#7598]
### Issue description

Crashes on start and says Mod appmek requires forge 41.0.0 to 42.0.0, currently forge is 43.1.3

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.3

### Mekanism version

10.3.3 (Latest)

### Other relevant versions

10.3.2
10.3.1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/Pcvx9cYT

**Comment by Seniorendi** [comment]
> appmek

Has nothing to do with mekanism
Update appmek or remove that addon

**Comment by pupnewfster** [comment]
Mod appmek requires forge 41.0.0 or above, and below 42.0.0

**Comment by wuggyfoot** [comment]
lit sorry :( i was ocnfussed
