### ISSUE TITLE
Infinite XP with Cardboard on Furnace

### ISSUE THREAD

**Issue by AzuryxxVortex** [mekanism/Mekanism#7600]
### Issue description

Putting a cardboard box on a furnace with smelted things that give XP in it will output the XP, forever, without ever depleting. As long as the output stays in the furnace that is

### Steps to reproduce

1. Smelt some ores or something that gives XP in a furnace
2. Put a cardboard box on it
3. You get the XP without grabbing the output.
4. Get it off, and on again, more XP, and there you have it. Infinite XP. 

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.3

### Mekanism version

10.3.3 (Latest)

**Comment by UnknownSerhan** [comment]
Yeah I was able to reproduce it as well
