### ISSUE TITLE
Ultimate Universal Cable power input to Induction Matrix Multiblock no longer working after server reset

### ISSUE THREAD

**Issue by RuneOracle** [mekanism/Mekanism#7602]
### Issue description

We've been using the UUC's to input power into an Induction Matrix system for about 2 days now, on an ATM7 private server, and after today's daily server restart, the cables have ceased to work. I noticed when i logged in, the cables were "visually broken" (i.e. horizontal green energy how the cable's are oriented, but the cable's physical portion was facing vertically, best way i can explain since i did not screenshot)

Power can exit the system okay, but no longer enter it.

I've tried manually replacing every single cable in the network, however they have not been fixed. It seems there may be an issue with the Matrix system itself, because when i break the singular cable that connects them together, the rest of the cables that are receiving power, start to rise in RF again. However, replacing the cable instantly drops the Rf/t back down to 0.

I'm 100% sure the power is not being pushed into the buffers of the output cables, using an RFtools screen to visualize the RF/t and manually checked each output cable's internal power stored, all are maxed.

EDIT: I notice the issue seems to be something between the Matrix and the Cables, when i connect a power cell from other mods to the input, that battery charges correctly, and the cables are still inputting power. No idea where to go from here though, any insight greatly appreciated.

### Steps to reproduce

1. Connect Mekanism UUC to Induction Port (green port)
2. Power drops to 0 on every connected cable with no power flowing into the system
3. Break UUC connecting to port
4. Power begins to generate again in the cables
5. Repeat

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.68

### Mekanism version

Older

### Other relevant versions

Mekanism Tools & Mekanism Generators are also installed on this server.

**Comment by RuneOracle** [comment]
![yespower](https://user-images.githubusercontent.com/75599640/187250310-8bd483b4-5499-4f50-ae1a-73bf9cefe890.png)
![nopower](https://user-images.githubusercontent.com/75599640/187250316-f0f8844c-4ca9-4194-9251-1dbf152d520d.png)

Here are some attached images showing the troubleshooting steps in a simple manner.

**Comment by RuneOracle** [comment]
![rftic](https://user-images.githubusercontent.com/75599640/187285514-a840e0e5-1146-4846-bf5a-5e9ec05410d5.png)
Apologies for extra comments, editing my previous wouldn't let me attach another image. There are 8 Magmators, several Create Alternators, and a few other misc sources feeding into the Matrix, yet still 0 RF/T. We had over 10k+ prior to the server restart.

**Comment by H4ckerxx44** [comment]
Could it be that the matrix is filled up? A picture of the matrixes dashboard thingy would be helpful I think.

**Comment by pupnewfster** [comment]
> I noticed when i logged in, the cables were "visually broken" (i.e. horizontal green energy how the cable's are oriented, but the cable's physical portion was facing vertically, best way i can explain since i did not screenshot)

That part sounds sort of like what is shown in #5922 which tends to imply some mod breaking forge's model data system.

> I'm 100% sure the power is not being pushed into the buffers of the output cables, using an RFtools screen to visualize the RF/t and manually checked each output cable's internal power stored, all are maxed.

One other way that might help visualizing what is going on with the network is right clicking somewhere on the cable network with a network reader, as I believe that will show if there is throughput vs the rftools screen which likely is checking what the power level is and comparing it to before?

Though yeah this issue definitely sounds quite strange and I agree showing a picture of the matrix's stats gui might be of some help in trying to theorize ideas.
