### ISSUE TITLE
Blocks disappear when interacting with water from the Water Physics Overhaul mod

### ISSUE THREAD

**Issue by ww1150** [mekanism/Mekanism#7606]
### Issue description

When installing mekanism blocks or pipes in a liquid, they disappear
Minecraft: 1.16.5
Mod version: Mekanism-1.16.5-10.1.2.457

### Steps to reproduce

1. We install a pump with pipes under water
2. We are waiting for the water to flow
3. The block disappears

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

36.2.34

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Sounds like they are breaking fluid logged blocks.
