### ISSUE TITLE
lasersssssssssss cause server lag. pls help

### ISSUE THREAD

**Issue by onenok** [mekanism/Mekanism#7607]
### Issue description

**lasers' laser(that red thing) causes server lag**

### Steps to reproduce

put a lot of lasers or laser point a lot of Laser Amplifier

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.76

### Mekanism version

Older

### Other relevant versions

none

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

none

**Comment by AlexHgC** [comment]
What server plan do you have ?

**Comment by Seniorendi** [comment]
Define "lag"

**Comment by onenok** [comment]
> What server plan do you have ?

free
