### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by Khytwel** [mekanism/Mekanism#7608]
### Issue description

Hi,

When I try to configure Mekanism to particularly balance the different tools against the Vanilla, most of the time after a change, the file is reset after the restart.

For example, I tried to change the spawn chances for pieces of Lapis Lazuli gear by setting it to 0.0 (because I want to deactivate entirely the Lapis Lazuli tools) and after restarting the game, the file is reset.

Most of the time, it also creates another .bak file.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.16

### Mekanism version

10.3.3 (Latest)

**Comment by pupnewfster** [comment]
I am not able to reproduce this. How are you editing the file? Is it when the game is loaded or when it is closed? Also what editor are you using to edit it?

**Comment by Khytwel** [comment]
After checking, the bug does not occur when the game is closed.
