### ISSUE TITLE
Paxel Mining Slow

### ISSUE THREAD

**Issue by Daihok41** [mekanism/Mekanism#7610]
### Issue description

I am using a steel paxel which has mining speed of 8 compared to vanilla iron speed of 6, seems like it mines cobblestone very slow in comparison. Not sure if its the case with all paxels but yea its like its not registering the paxel as a pickaxe. Even in the Jade tips it says the paxel is not valid mining tool.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.16

### Mekanism version

10.3.3 (Latest)

**Comment by pupnewfster** [comment]
Could you please provide your latest log as if I had to guess some other mod might be breaking datapacks and causing things to not load properly.

**Comment by Daihok41** [comment]
Trying to figure out best way to show the file is to large for pastebin.

**Comment by Daihok41** [comment]
But i did try loading instance with just mekanism and your right it works just fine on its own

**Comment by pupnewfster** [comment]
> Trying to figure out best way to show the file is to large for pastebin.

gist.github.com
