### ISSUE TITLE
Issue with 5x ore processing

### ISSUE THREAD

**Issue by DiegoRAP2003** [mekanism/Mekanism#7611]
### Issue description

I have 2 issues with my 5x ore processing method, first is, I have 5 crystallizer getting the clean slurry, but every some times they don't receive an even amount of slurry and the whole production stops because the washers don't have the same slurry, and the crystallizers are stuck with less than a 100 slurry, the other issue is every once in a while my ultimate tubes just disconnect from the line and stop feeding the slurry

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

14.23.5

### Mekanism version

Older

**Comment by UnknownSerhan** [comment]
1. Attach a logistical sorter above the Chemical Dissolution Chamber and set its filter to ore blocks and then set the size (min and max) both to 2 so the Chemical Dissolution Chamber will never get less than 2 ores and this will fix the first issue.

2. I don’t know about this one.

**Comment by pupnewfster** [comment]
For the second issue I am not really sure what may be going on other than maybe some issue related to chunk loading, but 1.12 was so long ago I don't remember what bugs really existed so beyond maybe trying to make sure the chunks are loaded I don't have any ideas.
