### ISSUE TITLE
Modrinth mod page links issue 

### ISSUE THREAD

**Issue by Fluboxer** [mekanism/Mekanism#7613]
### Issue description

So basically there is a modrinth Mekanism mod page - and it have some links to curse forge. Problem is - this stuff are already on modrinth and there is no need to take people to another website 

Links are: [Unity](https://modrinth.com/resourcepack/unity/), [Unity Dark Edition](https://modrinth.com/resourcepack/unity-dark-edition/)

Sorry if it is wrong place to tell about that little inconvenience 

### Steps to reproduce

1. Go to [https://modrinth.com/mod/mekanism](https://modrinth.com/mod/mekanism) 
2. Scroll down to "We HIGHLY RECOMMEND playing Mekanism with CyanideX's Unity: Dark Edition resource pack." line
3. Next two links to those packs will lead to CF instead of their pages on modrinth  

### Minecraft version

1.19.2 (Latest)

### Forge version

not relevant

### Mekanism version

10.3.3 (Latest)

**Comment by pupnewfster** [comment]
Ah, at the time I made the pages cyanide had not put those on modrinth and I have not been paying attention to the fact that as of 18 days ago they are on modrinth. Should be fixed now
