### ISSUE TITLE
Mekanism crashing with OptiFine

### ISSUE THREAD

**Issue by creep3rcrafter** [mekanism/Mekanism#7615]
### Issue description

Game Crashes on startup when Optifine and Mekanism-1.19.2-10.3.3.470 are both installed

### Steps to reproduce

Load Game
Game Crashes

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.25

### Mekanism version

10.3.3 (Latest)

### Other relevant versions

OptiFine HD U H9

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/Gfu0f4Fz

**Comment by pupnewfster** [comment]
Optifine isn't compatible with your version of forge

**Comment by creep3rcrafter** [comment]
Optifine works fine on that version and with every other mod(74 others) I add, Its just when I add Mekanism.

**Comment by pupnewfster** [comment]
Well then we likely are using a forge feature that changed and happens to not be used by any other mods

**Comment by creep3rcrafter** [comment]
welp if anyone else has this issue forge 43.1.3 seems to work right now with the current Optifine haven't tested much tho.

**Comment by FruitJelliesGD** [comment]
use 43.1.23 fix the crash

> welp if anyone else has this issue forge 43.1.3 - 43.1.23 seems to work right now with the current Optifine haven't tested much tho.

use 43.1.23 fix the problem, thx bro
