### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Yajur28** [mekanism/Mekanism#7616]
### Issue description

As soon as i activate my fission reactor. The server crashes and the world somehow corrupted and  im unable to play on that world anymore. Luckily I had a backup so i made more servers with the same world file just to check if it was a one time thing but everytime i activate the reactor the server gets crashed and corrupted. How do i fix this

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

forge 1.16.5-36.2.35.jar

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Yajur28/fcab9ef3c8222197095eea043904cbca

**Comment by tyler489** [comment]
Seems to be an issue with this mod https://github.com/North-West-Wind/MekanismFissionRecipe/issues?q=is%3Aopen+is%3Aissue

**Comment by pupnewfster** [comment]
Yes that mod that tyler linked breaks Mekanism on servers by hacking at our internals and adding things that don't work on servers
