### ISSUE TITLE
mekanismgenerators:heat_generator can crash server in some cases

### ISSUE THREAD

**Issue by aleaksah** [mekanism/Mekanism#7617]
### Issue description

Hello.
Few days ago I updated Mekanism and Mekanism Generators on my 1.19.2 server from version 1.19.2-10.3.2.469 to 1.19.2-10.3.3.470. I'm not sure that update caused problem, but after it server crashed few times with error like "Ticking block entity", crashdump attached. It always mention same heat generator at coordinates (-159,69,-243).
Anyway, crashlog will be much more informative than me.
Thank you for you work.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.24

### Mekanism version

10.3.3 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/bRgRAg0x

**Comment by pupnewfster** [comment]
I would try reinstalling mek and mek generators and see if that helps at all as I see no reason this should happen or be possible. If that doesn't help the only other thing I can think of is maybe some other mod you have installed has some faulty coremod or something breaking things but no idea.
