### ISSUE TITLE
Corrupted connector textures

### ISSUE THREAD

**Issue by shdanielpark** [mekanism/Mekanism#7618]
### Issue description

The base, unconnected textures for the various connectors (cables, pipes, transporters, etc.) appear to be corrupted and display a staticky texture rather than the typical magenta+black missing texture.

When connected, the texture connecting the two blocks renders correctly.

<img width="1440" alt="Screen Shot 2022-09-23 at 2 36 50 AM" src="https://user-images.githubusercontent.com/75617944/191814512-26d95d9d-4aa8-4609-b0b9-d2d3c3e63d71.png">

### Steps to reproduce

1. Place down any of the connector blocks.
2. Place down two connector blocks adjacent to one another.
3. Observe corrupted and rendered textures.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.27

### Mekanism version

10.3.3 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/shdanielpark/3897efeb8aef98c864c906c77125a6cf

**Comment by pupnewfster** [comment]
Does this happen without oculus and rubidium and other mods that screw with rendering?

**Comment by shdanielpark** [comment]
I just tested it after removing Rubidium and Oculus and the texture renders correctly. However, I have been playing in this world for a while with the two prior mods installed, and everything was rendering fine. I updated a few mods in between the last working session and today, and the issue appeared for the first time. To my knowledge, none of the mods in question should affect texture rendering (TwilightForest, Aquaculture 2, Jade, Minecolonies/Structurize, FarmersDelight, etc.). I can provide a complete list if necessary.

**Comment by pupnewfster** [comment]
Hmm yeah no idea, I am inclined though for now to leave this until I get around to releasing 10.3.4, as it seems like rendering mod screwyness/hackery and I already did some rewrites for the next version for transmitter rendering to improve memory usage/simplify some of the logic related to how it bakes them (granted I feel like odds are it won't change anything).

A couple tests you could do if you want to try and figure out why it might have worked before but doesn't now would be:
1. Try with all mods in a fresh world/superflat and see if they render correctly or incorrectly (would potentially determine if there is some other thing in your view that is then corrupting the gl state of the renderer)
2. Make a backup of your world/just use a fresh one if it still has issues and try downgrading those mods and see if it is them and then potentially try narrowing down which one updating caused it to break.

Though honestly I feel like this is some issue on rubidium/oculus' end, potentially with shaders enabled or just having both installed, or with just having at least rubidium installed, not sure.

**Comment by shdanielpark** [comment]
Yeah I'm not entirely sure what would cause this either as nothing's really been changed apart from updating a few mods. I would like to point out that the tests I ran after the screenshot in the original post were in two fresh worlds, one with Rubidium/Oculus and one without, and the texture didn't render correctly in the fresh world with Rubidium/Oculus.

I'm going to run it again with the previous versions of the mods that I had before, I'll post another comment here with the results.

**Comment by shdanielpark** [comment]
Found the issue - looks like there's some kind of incompatibility with the current version of the [Pedestals](https://www.curseforge.com/minecraft/mc-mods/pedestals) mod. The cable textures render correctly with just that mod removed and everything else left updated to their current versions. I'm guessing there's a conflict with how that mod implements the energy/exp/fluid transfer feature, not sure if it's a hard incompatibility since the author isn't done porting that mod to 1.19.2 yet.

**Comment by pupnewfster** [comment]
No idea, going to go ahead and close this though as I find it highly unlikely it is something on our end/fixable on our end if it requires two other mods (one of which being a major render changing mod) in order for it to break.
