### ISSUE TITLE
How do I mass transfer ownership from all mekanism items to another player?

### ISSUE THREAD

**Issue by Lion4K** [mekanism/Mekanism#7619]
### Issue description

Where is the UUIDs for mekanism stored?

I need to change the ownership of N amount of items from UUID X to UUID Z.

I have changed the UUIDs on the server files and I was able to transfer all items, achievements, EMC, waystones, everything to this new UUID, except mekanism stuff.

Where does ownership is stored?

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.1

### Mekanism version

10.3.1

**Comment by pupnewfster** [comment]
There is no way to do so, they are stored on the individual items/blocks by referencing the uuid. The only way to transfer them/remove the owner is via the security desk (or I suppose editing all the items and block data for the blocks in question)

**Comment by Lion4K** [comment]
Right and as a server operator, can I use the security desk to change other players belongings?

**Comment by pupnewfster** [comment]
I think you can if you change the config in config/Mekanism/general to allow ops to bypass security

**Comment by Lion4K** [comment]
Or how do I change the data on each block?

**Comment by pupnewfster** [comment]
Some way via mojang's `/data modify` command but like I don't know offhand how it works as I never used it.

**Comment by beholderface** [comment]
Looks like you can't just paste a UUID into a given block's NBT to change its security settings, it's stored in some other format
![screenshot from test world](https://user-images.githubusercontent.com/13290805/192109030-b219924b-0c53-49d7-bbee-0c8f06f68c0e.png)
