### ISSUE TITLE
Chemical injection Chamber gas (hydrogen chloride) uses

### ISSUE THREAD

**Issue by YoSiJo** [mekanism/Mekanism#7620]
### Issue description

# Issue description

This issue has some similarity to this #7377

The Ultimate Injectiing Factory has a random gas consumption.

The machine tier is Ultimate

The machine is provided with 8 Speed, 8 Energy and 8 Gas upgrade.

The recipe says 1 Gunpowder and 0.2 H. Cloride.

Always craftet 100 Sulfur Dust.

## Autosort off

Run 1: 271
Run 2: 381
Run 3: 140

## Autosort on

Run 1: 318
Run 2: 68
Run 3: 344

### Steps to reproduce

1. Craft machine
2. Connect machine with AE2 Provider
3. Set Ports
4. Add recipe for Sulfure
5. Craft 100 Sulfure

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.25

### Mekanism version

10.3.3 (Latest)

### Other relevant versions

[Applied Energistics 2](https://github.com/AppliedEnergistics/Applied-Energistics-2): 12.5.2-beta
[Applied Mekanistics](https://github.com/AppliedEnergistics/Applied-Mekanistics#readme): 1.3.2

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

 No response

**Comment by YoSiJo** [comment]
The same problem exists with the "C. Dissolution Chamber" with the "Sulfuric Acid".

**Comment by UnknownSerhan** [comment]
Imo speed upgrades are making the gas usage really random because it is always correct when speed upgrades are not installed. So basically machine is trying to do the process so fast that it might need more or less gas based on its RNG.

**Comment by YoSiJo** [comment]
RNG?
And is it a mistake or a deliberate circumstance?

**Comment by pupnewfster** [comment]
As far as I know this isn't a bug and is intended as the code explicitly references using a method for calculating the inverse poisson value on the curve based on the mean calculated by how many speed upgrades are installed. Those two processes are meant to have some variation in the gas usage and the only reason it shows a constant amount in JEI is to try and show the rough average when no upgrades are involved to get a general sense and know that it is needed in general.

**Comment by pddshk** [comment]
Though it is claimed not to be a bug, it remains a problem for interaction with AE2. Moreover this is not the case for similarly working infuser. Infuser consumes constant amount of infuse type regardless of amount of upgrades installed, so maybe injection may be reworked in a similar way? 👉👈

**Comment by UnknownSerhan** [comment]
The best thing to do is to not put the chemicals that have randomized usage in the patterns. Just feed them in the machines continuously and make the pattern without the said chemical.

I *believe* one of the newer versions have a config setting which removes the randomizing factor from the machines.
