### ISSUE TITLE
some items/recipes completely disappearing from the game

### ISSUE THREAD

**Issue by mahabongo** [mekanism/Mekanism#7622]
### Issue description

i was playing the game normally until i got steel and then tried to make a steel pick and it just kinda didnt work no matter what i tried so i just ignored it for a while until i tried to make a heat generator and that also didnt work so i went into creative to try and find the items and they didnt even exist 

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.27

### Mekanism version

10.3.3 (Latest)

**Comment by pupnewfster** [comment]
https://www.curseforge.com/minecraft/mc-mods/mekanism-generators
https://www.curseforge.com/minecraft/mc-mods/mekanism-tools

**Comment by mahabongo** [comment]
ok im just an idiot then whoops
