### ISSUE TITLE
Auto miner corrupting save files

### ISSUE THREAD

**Issue by Curlychump** [mekanism/Mekanism#7623]
### Issue description

I have found an issue where using the automatic miner can corrupt save when mining and replacing certain blocks

### Steps to reproduce

1. Set Miner to mine any type of energy cube
2. Set Miner to force replace the energy cube with a different energy cube
3. Start the miner
4.Game crash, Corrupted World

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

36.2.26

### Mekanism version

Older

### Other relevant versions

Unchecked

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/CCgBkLrc

**Comment by pupnewfster** [comment]
Unable to reproduce in 1.19
