### ISSUE TITLE
MekaSuit Lag

### ISSUE THREAD

**Issue by SallyMcSaggy** [mekanism/Mekanism#7625]
### Issue description

When 2-3 or more players have a fully upgraded MekaSuit set while wearing it, the server TPS drops drastically. It seems like some of the modules are causing it, from the testing I've been doing while enabling them one by one. When all of the modules are disabled, everything is fine.

### Steps to reproduce

1. Put on all of the MekaSuit armor pieces.
2. Enable all, or some of the modules.
3. Server TPS go brrrrrrrrr.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.80

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Could you please provide some profiling using [spark](https://www.curseforge.com/minecraft/mc-mods/spark) or something?

**Comment by SallyMcSaggy** [comment]
https://spark.lucko.me/bR4vAh4L0M?hl=45,47,80,56,34,29,4649,4700

**Comment by pupnewfster** [comment]
Looks like the main source of lag is due to having a ton of advancements that trigger based on changes to your inventory that then are being checked a ton. Doesn't seem to be related to mekanism at all (unless maybe ever so slightly indirectly due to say the charge distribution unit causing the NBT of items to change as it charges them)

**Comment by ceraso-42** [comment]
> Looks like the main source of lag is due to having a ton of advancements that trigger based on changes to your inventory that then are being checked a ton. Doesn't seem to be related to mekanism at all (unless maybe ever so slightly indirectly due to say the charge distribution unit causing the NBT of items to change as it charges them)

Staff member of the affected multiplayer server here, I'll investigate this when I have some time to throw at it. Server's running All The Mods 7 v0.4.32 if anyone wants to get to it before I do

**Comment by ceraso-42** [comment]
Update: I don't seem to notice any advancements outright yet, but I think I can comfortably say that this is only a MekaSuit issue by proxy. The server hardware definitely wasn't up to the task, but I will leave it to be known that on an E5 2680 v2, the server TPS changed from 8.85 to ~19.5 on a mid-to-end game world by having three players on the server remove their MekaSuits with these CDUs and putting them in storage where they don't tick. It's possible they might need some additional optimization in how they go about being charged, but I'm going to jump down the rabbit hole of advancements in this monster pack to figure it out, and if possible, I'll raise an issue with the ATM team.

This issue has been mitigated by a hardware upgrade but not completely resolved. It's still a 25 -> 35 MSPT change on a Ryzen 7 3800X for just two of these players to re-equip their MekaSuits on the same world. Could still be a Mekanism advancement, so I'm not closing this issue just yet.

**Comment by JustAnotherGhostName** [comment]
Can confirm a similar issue, uncertain the cause since if I clone the armor, and all the configs from someone, I dont have the error.

**Comment by JustAnotherGhostName** [comment]
Potentially new info regarding it? This issue may be linked to ftb quests I think. So far its been basically impossible for me to link it to anything, baring completely copying a players data to me and becoming them. Plus in spark reports, meka suites themself never show up high on the lists. However, I noticed this time that FTB Quests was higher in the spark profiler list than normal, and we havent had the meka suite issue too much till now where a player was over 20000 micro tics.

Still ATM8, on version 1.0.17, the latest as of writing. This is their FTB Quests section for mekanism for the player online with the worst individual player tick lag:
![image](https://user-images.githubusercontent.com/122759195/236941297-d7bfbd98-dbad-407e-ac88-08f84083594a.png)

Here is Observable pointing out players are lagging (only 9 players on at the time):
![image](https://user-images.githubusercontent.com/122759195/236941814-313b7ae3-1606-4ce7-8b39-dcd2cf2d446d.png)

Overall spark fire tree, showing mekanism isnt really high up there, but something is taking up a bunch of a servers player tick calculation:
![image](https://user-images.githubusercontent.com/122759195/236942464-8bfedc42-ab97-41e7-b4ec-03e5fe165eba.png)

Close up spark fire tree for the player tick:
![image](https://user-images.githubusercontent.com/122759195/236942663-107e2d46-f943-4e83-a28e-8a23b6a2b7ef.png)


This should line up with the players as observable is reporting the overall player ticks at around 32308 u/t:
![image](https://user-images.githubusercontent.com/122759195/236943107-ca1ecdaa-a961-476d-ba1b-67057397af6e.png)

And the tics for the server player tick being 26,844 ms. I know they are not the same ect, but these measurements are also not taken directly during the same time frame, and were slightly different durations:
![image](https://user-images.githubusercontent.com/122759195/236943591-aff1190d-33c4-4983-bbe9-be6ef820bcfd.png)

This guess could be wrong, but I have been wondering what causes ftb quests to show up high on the list inconsistently, and i think its just about as inconsistent as meka suites being laggy.

**Comment by selbbit** [comment]
I haven't really checked the FTB Quests section, but I noticed that the players with the Vision Enhancement Unit caused lag. Both players with the unit had a considerable amount of u/t, one with 9900 and one with 28000 (both on the same team, having the same quests).

With the Unit/s:
![image](https://github.com/mekanism/Mekanism/assets/60442398/aef6005f-e1df-4037-af52-e63c3bfc93b9)
![image](https://github.com/mekanism/Mekanism/assets/60442398/a1b465ad-9242-4457-8573-5d2f0e50bb5d)

Without the Unit/s:
![image](https://github.com/mekanism/Mekanism/assets/60442398/aff63ac3-152b-4859-9844-9a5e31198ac4)
Lost the screenshot for the other player

**Comment by JustAnotherGhostName** [comment]
> 

Ill have to test this myself, as I know in the past I tried to replicate it by copying a players meka suite and I could not reproduce it. I will update here if I can replicate it.

**Comment by JustAnotherGhostName** [comment]
> I haven't really checked the FTB Quests section, but I noticed that the players with the Vision Enhancement Unit caused lag. Both players with the Vision Enhancement Unit had a considerable amount of u/t, one with 9900 and one with 28000 (both on the same team, having the same quests).
> 
> With the Vision Enhancement Unit/s: ![image](https://user-images.githubusercontent.com/60442398/241643685-aef6005f-e1df-4037-af52-e63c3bfc93b9.png) ![image](https://user-images.githubusercontent.com/60442398/241643759-a1b465ad-9242-4457-8573-5d2f0e50bb5d.png)
> 
> Without the Vision Enhancement Unit/s: ![image](https://user-images.githubusercontent.com/60442398/241643904-aff63ac3-152b-4859-9844-9a5e31198ac4.png) Lost the screenshot for the other player

I tried two things. First thing I did was copy the meka suite armor from someone who was end game, and sat there tweaking the settings of the module and removing then reading it. This had no affect on my player entity lag. 

I then cleared my inventory, spawned in a fresh meka helm, and threw in 4 vision module upgrades and enabled them. This still had no affect. 

Are you able to confirm that their impact on the server is reduced when they remove the upgrade?

**Comment by JustAnotherGhostName** [comment]
Update on this, I noticed the aggregated results for players was at around 9k us/t, so I requested players to disable the upgrade and remove them, just to see. This was the results.

Before:
![image](https://github.com/mekanism/Mekanism/assets/122759195/bb3dc3a7-93ba-45f4-a7d6-1e69cc032bee)

After:
![image](https://github.com/mekanism/Mekanism/assets/122759195/3724d368-7f6b-4f69-98c4-868ac944461a)

Strange that this does cause it, but I cant replicate it on my person....

**Comment by ceraso-42** [comment]
Apologies: This pack was actually retired from my server, although I can pull it out of the mothballs for a test. Life's been busy too.

I had issues with replication and was simply able to narrow it down to the suits, not any specific module. This is very interesting to see and I've noted the compound problem. Probably time to take this to FTB, I think. This issue can be slept pending investigation on third parties.

**Comment by thiakil** [comment]
Not really enough info to go one here, aggregates don't help isolate anything.

Indeed seems to be related to ftb quests checking things

**Comment by D-Alessian** [comment]
I can confirm this happened to me too, it happened only after I did a manual inventory rollback . It was on atm8 1.1.0. . I've got plenty of spark and obsrevable profiles to go around if it can be useful. I also found out the lag is there but reduced when you activate it without chestplate. https://www.reddit.com/r/admincraft/comments/18s7mdi/inventory_rollback_caused_some_lag/ wrote a reddit post about it here

**Comment by thiakil** [comment]
Your profiles show its also due to advancements, just like was commented on your reddit thread

**Comment by D-Alessian** [comment]
Well I know, this is what I thought at first as well but evidently it's not. I'm no developer so I don't know why this happens but I troubleshot it thoroughly and lose about half my tps when activating the vision enhancement unit, so clearly something is going on.

**Comment by thiakil** [comment]
It uses power, which updates the saved data, which then triggers checking all the item based advancements

**Comment by KingJetsoar** [comment]
So i had this issue on my server running ATM9 1.20.1 0.2.34
I was sent this, and did some learning, though idk about ftb quest, since we don't have mecha suit as a quest in atm9, but advancement mabey, but don't see it. But I do know when you are wearing the mecha suit and you are charging it/using it. It does start causing massive tps issues, idk if that is helpful for anyone.

**Comment by creaper33** [comment]
I'm having this issue too. The charge distribution unit also causes lots of lag. If anyone has a fix please tell. For now I've just been telling players to not use those modules.

**Comment by thiakil** [comment]
Remove all item based advancements and quests if present. That's the only way.

**Comment by santosgamingdev-pixel** [comment]
https://www.curseforge.com/minecraft/mc-mods/mekanism-gear-optimizer Fixed it. Let me know if  you guys want it backported or for forge
