### ISSUE TITLE
Forge version over 43.1.23 will crash the game.

### ISSUE THREAD

**Issue by Fiocher** [mekanism/Mekanism#7626]
### Issue description

43.1.23 works fine, but later versions crash the game.
[crash-2022-09-30_08.54.35-client.txt](https://github.com/mekanism/Mekanism/files/9680054/crash-2022-09-30_08.54.35-client.txt)

### Minecraft version

1.19.2 (Latest)

### Forge version

＞43.1.23

### Mekanism version

10.3.3 (Latest)

**Comment by pupnewfster** [comment]
Optifine bug
