### ISSUE TITLE
crash issue 

### ISSUE THREAD

**Issue by Yurikia** [mekanism/Mekanism#7627]
### Issue description

crash at loading minecraft

### Steps to reproduce

1. when the mod loaded in main menu minecraft

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.1

### Mekanism version

Current Dev Branch (Manually Compiled)

**Comment by UnknownSerhan** [comment]
No one can help you without some sort of crash report or log

**Comment by pupnewfster** [comment]
Remove optifine
