### ISSUE TITLE
Smelting Factory causing Lags

### ISSUE THREAD

**Issue by Tempritscher** [mekanism/Mekanism#7630]
### Issue description

Greetings everyone.
we setup an server today with the latest github build: Mekanism-1.19.2-10.3.3.homebaked-all

after we put some items like clay into the smelting factory the server has bunch of small lags and we were unable to mine stuff or attack mobs.
soon after the last clay was baked to bricks the lags are gone.

### Steps to reproduce

1.We have a Mekanism Smelting factory combined with the ME system from Applied Energistics 2 build: [AE2 12.7.0 [FORGE]
2. We put Clay in the Red smelting factory
3. try do mining or attacking mobs
4. server console will spam: can't keep up the system.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.33

### Mekanism version

Current Dev Branch (Manually Compiled)

### Other relevant versions

We use Better Minecraft Modpack 1.19.2 v6

**Comment by Tempritscher** [comment]
alright i will test this now

**Comment by Tempritscher** [comment]
here is the result:
https://spark.lucko.me/FomeAz6V5U

**Comment by Tempritscher** [comment]
i did one more scan: https://spark.lucko.me/EmwKuSf79x

**Comment by pupnewfster** [comment]
Most of the lag from those reports seem to be caused by the rootling entity from biomemakeover attempting to pathfind and maybe check if it is in rain and pathfind differently because of it. Seems it is attempting to pathfind to an unloaded chunk and causing a ton of chunks to load in order to query if it can pathfind there.

**Comment by Tempritscher** [comment]
alright. so how can i fix this?

**Comment by pupnewfster** [comment]
Report it to that mod and/or remove that mod in the time being. From what I can tell this has nothing to do with mekanism and is purely related to their mob's ai trying to pathfind causing the lag. And just so happened it was at the same time you were smelting something.
