### ISSUE TITLE
Crashes on loading screen.

### ISSUE THREAD

**Issue by JANDMIT** [mekanism/Mekanism#7634]
### Issue description

Exit Code: 255

<img width="2032" alt="Screen Shot 2022-10-07 at 10 53 43 PM" src="https://user-images.githubusercontent.com/115333484/194686968-c3595b23-7b8f-4988-b3f8-9a601fdb42a5.png">

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.33

### Mekanism version

10.3.4 (Latest)

**Comment by JANDMIT** [comment]
[crash-2022-10-07_20.11.09-fml.txt](https://github.com/mekanism/Mekanism/files/9738363/crash-2022-10-07_20.11.09-fml.txt)

**Comment by pupnewfster** [comment]
Optifine
