### ISSUE TITLE
Crashing From New Update 1.19.2 Forge 31.3.33

### ISSUE THREAD

**Issue by Thisguyneedshelp** [mekanism/Mekanism#7635]
### Issue description

crash on start up

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.33

### Mekanism version

10.3.4 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/wyRPOhP

**Comment by pupnewfster** [comment]
Seems to be on BetterFusionReactor's end it is using/changing our internals or something and referencing things that no longer exist in the latest update
