### ISSUE TITLE
Fussion Reactor turns off when out of render for to long/ exiting the game

### ISSUE THREAD

**Issue by itstaajaae** [mekanism/Mekanism#7637]
### Issue description

whenever I leave my temporary base for 10+ mins my fusion reactor just turns off for some reason even tho its filled/capped out with fuel. the same thing happens if I leave the game and come back
1.16.5

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

36.2.39

### Mekanism version

Older

**Comment by Omikron-Delta** [comment]
Are all parts of your fusion reactor chunk loaded? Including the machinery that produces the fuel.

**Comment by UnknownSerhan** [comment]
I am not sure but I think a bug related to fusion reactor shutting off upon server/game starts has been fixed. I am not sure why it would shut off when out of render for too long though.

**Comment by pupnewfster** [comment]
I believe said bug was fixed after 1.16 (though I forget the specific reproduction steps as it didn't *always* happen). But also yeah my guess is that there are parts that are not chunk loaded.
