### ISSUE TITLE
Incompatible with the latest CraftTweaker Update

### ISSUE THREAD

**Issue by TemplarLouai** [mekanism/Mekanism#7638]
### Issue description

"CraftTweaker has failed to load correctly"
[crafttweaker.log](https://github.com/mekanism/Mekanism/files/9763702/crafttweaker.log)
[latest.log](https://github.com/mekanism/Mekanism/files/9763703/latest.log)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.11

### Mekanism version

10.3.3

**Comment by IchigoGames** [comment]
hopefully a fix for this will be in the next Mekanism update im trying to update my pack to 1.19 but need both mek and crafttweaker
