### ISSUE TITLE
opening a carboard box

### ISSUE THREAD

**Issue by BlueCyborgHoock** [mekanism/Mekanism#7639]
### Issue description

when I place down the carboard box it has data in it but if I shift right click with nothing in my left hand or right hand it just breaks the box but doesn't leave what's in the box its keeps what is in the box and I can't figure out how to change it to where what's in the box will stay put and only the carboard box will break and I can get it back not the carboard box with the data still in it

if it helps I'm playing on atm8 (all the mods 8)

### Minecraft version

1.19.2 (Latest)

### Forge version

latest?

### Mekanism version

10.3.4 (Latest)

**Comment by pupnewfster** [comment]
What sorts of things are you trying to move with the cardboard box? (I am curious if it is some data or something that is failing to place in a way it expects, so what happens if you say use it on a piece of dirt)

**Comment by BlueCyborgHoock** [comment]
i figured it out it was something to do with ultimine

**Comment by LOR1A** [comment]
I got the same error, it was indeed the key bind  of ftb ultimine that was preventing opening
