### ISSUE TITLE
Fission Reactor Logic Adapter can power other other adapters

### ISSUE THREAD

**Issue by nskobelevs** [mekanism/Mekanism#7641]
### Issue description

If a Logic Adapter set to "Active" is placed right beside any other adapter that outputs a signal during a fault, that adapter will power the "Active" logic adapter preventing any automation from disabling the reactor.

Logic Adapter Setup:
<img width="671" alt="Screenshot 2022-10-15 at 20 20 59" src="https://user-images.githubusercontent.com/34107736/196004399-141bf27c-b010-4573-8e8c-033540aeb1a0.png">

Left Adapter:
<img width="482" alt="Screenshot 2022-10-15 at 20 20 52" src="https://user-images.githubusercontent.com/34107736/196004407-44d24e75-200c-4047-bf6c-2d944dbc57e2.png">

Right Adapter:
<img width="459" alt="Screenshot 2022-10-15 at 20 20 49" src="https://user-images.githubusercontent.com/34107736/196004411-63546f8b-83ae-4ebe-baf8-854ff3c53e39.png">

The right one is outputting due to damage critical but that in turn keeps the fission reactor operational as the left adapter is receiving power.

### Steps to reproduce

1. Build a fission reactor
2. Place two logic adapters
   - One set to "Active"
   - One set to any of the fault settings
3. Cause the reactor to malfunction
4. Watch the reactor keep powering itself causing a full-on meltdown

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.30

### Mekanism version

10.3.4 (Latest)

**Comment by cnordbakk** [comment]
I hope this is the intended behavior as it's very useful
