### ISSUE TITLE
PRC not accepting Biofuel

### ISSUE THREAD

**Issue by mjrae** [mekanism/Mekanism#7642]
### Issue description

PRC will not accept biofuel from logistic pipes, The PRC is accepting both water and oxygen.

### Steps to reproduce

1) Hook up a pipe that should pump biofuel into the PRC from chest or crusher
2) Biofuel will not move into the PRC

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.38

### Mekanism version

10.3.4 (Latest)

**Comment by UnknownSerhan** [comment]
Are you sure you set the PRC item side config correctly? You have to set the side of the logistical transpoter to "input".

**Comment by mjrae** [comment]
Yes. I have the right side set to ‘Input Dark Red’. I have also tried the front. Both the water and oxygen are setup the same and are working. I have also tried using the configurator on the logistical transporter to pull from both the grinder and chest and push into the PRC.

Thanks.

**Comment by mjrae** [comment]
![Base Profile Screenshot 2022 10 17 - 13 51 09 24](https://user-images.githubusercontent.com/116035774/196281248-662f3c6d-ccdc-4a9b-adf6-16c4654f6d42.png)

![Base Profile Screenshot 2022 10 17 - 13 50 01 59](https://user-images.githubusercontent.com/116035774/196281272-9c679624-a321-4032-96cc-abdeb64ee5c8.png)

![Base Profile Screenshot 2022 10 17 - 13 50 23 67](https://user-images.githubusercontent.com/116035774/196281292-cd4306ba-a8f3-46e6-a8ca-ac37ed552e7b.png)

![Base Profile Screenshot 2022 10 17 - 13 50 31 80](https://user-images.githubusercontent.com/116035774/196281328-ac371e60-365c-4af2-acf0-29ca1ebb47e6.png)

![Base Profile Screenshot 2022 10 17 - 13 50 35 97](https://user-images.githubusercontent.com/116035774/196281350-445a6982-0851-4d06-9505-c8c1bf48144c.png)

**Comment by UnknownSerhan** [comment]
You got the recipe wrong; you need hydrogen instead of oxygen. That's probably why the PRC doesn't accept the bio fuel.

**Comment by mjrae** [comment]
Sorry for taking your time. Bad online recipe. Same setup works with hydrogen. Thank you!
