### ISSUE TITLE
Atomic Disassembler ignores attack speed

### ISSUE THREAD

**Issue by Shadows-of-Fire** [mekanism/Mekanism#7643]
### Issue description

The atomic disassembler always performs a full strength attack regardless of the player's current attack cooldown. This impacts all versions from the last 7 years - https://github.com/mekanism/Mekanism/issues/3584

### Steps to reproduce

Hit something with the disassembler
do it again before the cooldown resets
observe full damage (20 points) each time

### Minecraft version

1.19.2 (Latest)

### Forge version

N/A

### Mekanism version

10.3.4 (Latest)

**Comment by Shadows-of-Fire** [comment]
My suggestion is put this logic in a helper method
<https://github.com/mekanism/Mekanism/blob/1.19.x/src/main/java/mekanism/common/item/gear/ItemAtomicDisassembler.java#L124-L134>
and then reference it in hurtEnemy to compute the energy cost and in getAttributeModifiers to provide the stat

**Comment by Shadows-of-Fire** [comment]
Utilizing the attribute will also fix another related bug - weakness prevents attacking with the disassembler entirely because the game thinks you have 0 attack damage.

**Comment by Authrec** [comment]
The Meka Tool also has this bug.
