### ISSUE TITLE
Enrichment Chamber Not Turning Ores into Dust

### ISSUE THREAD

**Issue by Megalaladon** [mekanism/Mekanism#7644]
### Issue description

Hi,
I am currently playing on a 1.19 aternos server with my friend and recently made a jetpack. Anyway, I needed osmium dust and found out that I need an enrichment chamber so I make one and try to put a osmium ingot in the box and it doesn't take it. Its fully connected to power and everything. Please help.

Thanks,
Megh

### Minecraft version

1.19.0 or 1.19.1 (No longer being developed)

### Forge version

41.1.0

### Mekanism version

10.3.1

**Comment by Seniorendi** [comment]
Please use https://www.curseforge.com/minecraft/mc-mods/jei 
So you always know how to make things

**Comment by Megalaladon** [comment]
Hi,
Thanks for the reply but to make a crusher you need dusts if I’m not mistaken. And I’m not quite sure how to get ore dusts with any other methods.

Thanks,
Megh

**Comment by Seniorendi** [comment]
you need two lava buckets, some steel and a bit of redstone to make the crusher

**Comment by Seniorendi** [comment]
![image](https://user-images.githubusercontent.com/67484093/196671267-fcb843ba-fcdf-4205-941e-541fa1a9d484.png)
No dusty
