### ISSUE TITLE
Duplication in QIO with Bins

### ISSUE THREAD

**Issue by Xuno-ui** [mekanism/Mekanism#7645]
### Issue description

I appologize if this has already been brought to your attention, I looked through the issues to the best of my ability and didn't find this. 

Using two bins you can duplicate items inside a QIO crafting grid. I believe this only works in the QIO crafting grid. I tested it inside a normal 2x2 inside my inventory and an actual crafting table. I'll try to explain this as best as I can using pictures step by step.

### Steps to reproduce

Put a bin inside the QIO Crafting Grid.

![Screenshot_1](https://user-images.githubusercontent.com/74331630/196713865-dd469487-2fc9-4d97-b879-7d1abb999fb4.png)

Replace the current bin with a different bin (just drop it on top of the current bin). In this instance the second bin was filled with wooden shovels.

![Screenshot_2](https://user-images.githubusercontent.com/74331630/196714035-d2f0ada4-6e65-4c4d-a4d4-b765ff4fd8cb.png)

You will be able to take out the first bins items but it will take items from the second bin instead. 1 Wooden Shovel = 32 Ultimate Control Circuits

If you're using an item that actually stacks like Cobblestone or Dirt, it will take one stack at a time out of the second bin.

I think you can use this to dupe anything almost since you can put tanks and stuff into a bin.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

36.2.23

### Mekanism version

Older

### Other relevant versions

Minecraft 1.16.5

**Comment by UnknownSerhan** [comment]
I just tried this in 1.19.2, it doesn't let you take the items out from the bin on the QIO Crafting Window

**Comment by Xuno-ui** [comment]
Awesome! In 1.19.2 are you able to put items into bins via the QIO Crafting Window and normal Crafting Grid?

**Comment by pupnewfster** [comment]
What version of Mekanism are you on, given I know 1.16, but I sort of feel like this was fixed when fixing #7396 which was part of 10.1.2 (a version for 1.16)

**Comment by Xuno-ui** [comment]
10.1.1.456, that would probably be it. I'm playing on a modpack and they seem to have just not updated Mekanism.
