### ISSUE TITLE
Items deleting in QIO

### ISSUE THREAD

**Issue by Xuno-ui** [mekanism/Mekanism#7647]
### Issue description

I apologize if this has already been brought to your attention, I looked through the issues to the best of my ability and didn't see anything relating to this. Closest thing I could find was an old issue with QIO Drives overwriting each other when clicking fast.

If you click too fast inside the QIO main window, left or right I believe, item stacks will randomly be deleted.

### Steps to reproduce

Click things fast in the QIO main window. 

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

36.2.23

### Mekanism version

Older

### Other relevant versions

Minecraft 1.16.5

**Comment by pupnewfster** [comment]
To validate is this in single player or on a server? (Best theory currently without even attempting to reproduce it is potentially client sending the packet twice and maybe the server doesn't validate action against whether the cursor is currently holding something)

**Comment by anzu81** [comment]
We are having the same issue on the ATM 8 public server where just in the last day multiple users have QIO systems have lost hundreds of thousands of dollars items after resets

**Comment by pupnewfster** [comment]
I looked into this a bit, and it seems I fixed this in the initial port to 1.19, but while looking at it more I also found a few other (non-voiding) issues that could be caused by the same set of circumstances that I went ahead and fixed for the next 1.19 version
