### ISSUE TITLE
Electrolytic separators make me feel sick

### ISSUE THREAD

**Issue by MaxiveLegend** [mekanism/Mekanism#7648]
### Issue description

The sound that the Electrolytic separators make greatly amplifies my motion sickness while playing and listening to it for longer than about 2 minutes gives me horrible headaches. I don't know if more people have this issue, but it really makes me hate these machines in an otherwise amazing mod. I know the sound can be muffled with muffler upgrades but that both prevents me from getting into mechanism ore processing early game until I have enough materials to afford all those upgrades, especially at scale, as well as making it a horrible experience watching let's plays on YouTube. I didn't really know where else to come with this.

### Steps to reproduce

activate an electrolytic separator.

### Minecraft version

1.19.2 (Latest)

### Forge version

all

### Mekanism version

10.3.4 (Latest)

### Other relevant versions

this has been an issue for as long as I've played with/known about mekanism

**Comment by UnknownSerhan** [comment]
Install muffling upgrades. Easy peasy.

**Comment by toddlersizedsharkcage** [comment]
There's also a mod called "muffler mod" that allows you to mute anything you like.  I suggest using it if you have auditory troubles.

**Comment by MaxiveLegend** [comment]
I do know about the muffler mod, but I can still imagine scenarios (modpacks, or playing with only mekanism and no other mods) where the issue can't be fixed with something like that. wouldn't be an issue for me personally to install the mod, but that still leaves the issue in let's plays and also for other people that have the same issue as me. shouldn't the mod be able to stand by itself without making some people nauseous with a high pitched noise?

**Comment by MaxiveLegend** [comment]
to clarify, I'm not trying to tell the developers/contributors how to make a mod. I'm just trying to make them aware this is an issue for at least one person, and I can imagine more people have the same problem.

**Comment by toddlersizedsharkcage** [comment]
Extreme Muffler Mod is client side, so you don't have to rely on a modpack having it. I get what you're saying, but I can only offer alternatives to your request.

**Comment by Jimmy-sheep** [comment]
Maybe you can try change the settings in .minecraft\config\Mekanism\client.toml, in the first part there's some settings about sounds.

**Comment by johalun** [comment]
The sound is unpleasant for sure. This is an accessibility issue that'll hopefully get some attention. I'm surprised all replies are just about workarounds instead of addressing the source of the issue...

**Comment by ProsperCraft** [comment]
In my packs we always turn the default volume for the machines way down, and include Extreme sound muffler mod.
