### ISSUE TITLE
Digital Miner randomly stops

### ISSUE THREAD

**Issue by SirEndii** [mekanism/Mekanism#7649]
### Issue description

We play ATM8 on a private server, and we have the problem that digital miner randomly stops mining.
This can happen after a night(IRL) or just 10 minutes.
When we go home, working a bit on other stuff and coming back 15 minutes later to our miners, it's like they got a reset.

"To mine" goes to 0 and after clicking on stop and reset, it starts to search again. It's like someone deleted the cache while it was running... after hitting stop, reset and start again, it searches, finds 300k ores and starts to mine.

We use anchor upgrades AND FTB Chunks chunk loading
The teleporter works(Without upgrade), so the chunk does not seem to be the problem here.

After starting:
![image](https://user-images.githubusercontent.com/67484093/197190296-dabc3836-a39a-46f3-9ae9-9b33a6a036b9.png)

Coming back:
![image](https://user-images.githubusercontent.com/67484093/197189997-4e99506a-ba55-4069-9b8e-0e9be1e7d107.png)

### Steps to reproduce

1. Place a digital miner - We have our like 5k-10k blocks away from the spawn and homes
2. Use filters - We use tag filters like `forge:ores` or `minecraft:logs`. Often both together
3. We use a radius of 128 with a min height of -64 and a max height of 319
3. Go home
4. Come back after like 5-15 minutes 
5. "To mine" is zero, but it's "Ready" and "Running"

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.43

### Mekanism version

10.3.4 (Latest)

### Other relevant versions

ATM8 v0.1.5

**Comment by Seniorendi** [comment]
Forgot to send a log -> https://gist.github.com/Seniorendi/64b2dd8a825a94635e9b7428fbd2f0ec
I uploaded the log in the timestamp where I tested it

**Comment by UnhappyCodings** [comment]
I can confirm that! It also happens when you standing right next to it. Sometimes it also just doesnt stop. ATM8

**Comment by pupnewfster** [comment]
This sounds like the chunks it is trying to mine are unloaded. Are all the chunks loaded by the chunk anchors you are using? As looking at ATM8's configs anchor upgrades loading chunks [is disabled](https://github.com/AllTheMods/ATM-8/blob/main/config/Mekanism/general.toml#L7), so especially if you increase the max radius then it increases the odds that the chunks you are targeting is not loaded and it is waiting for them to load

**Comment by SirEndii** [comment]
https://user-images.githubusercontent.com/67484093/212994828-92a45363-5592-4081-8a8a-462ef4f5f7a3.mp4

Lil' example video
The weird shit starts at second 12

**Comment by pupnewfster** [comment]
Uhhhh but we only decrement that value except for when searching is finished and we update, so I honestly don't see how that video is possible. Except for maybe [this](https://github.com/mekanism/Mekanism/blob/eeb17e7f9f12333c0d202bc42ad409aeded7fe77/src/main/java/mekanism/common/tile/machine/TileEntityDigitalMiner.java#L207-L217) relating to loading from disk, except that should only happen at most once so I don't see how it would go up twice.

**Comment by SirEndii** [comment]
The same issue also occurs when we set the max radius too high (way over 256)

**Comment by pupnewfster** [comment]
Well I realized my previous comment was semi wrong just in that the number will be going up as far as the client side is concerned as the digital miner's search thread runs, but somewhat unsure why it seems to be taking the search thread so long to run. Does manually resetting/stopping it and then starting it again make it find the blocks quicker?

**Comment by SirEndii** [comment]
Yes it does

**Comment by blackthijs0** [comment]
I have this exact same issue. I suspect it is not related to chunkloading as I have intentionally set the machine to only mine a very small area.
When I press "Start" there are about 100 blocks to mine, then a few seconds later it drops to 0 without having mined any blocks.
Are there any know fixes/work-arounds yet?

**Comment by SirEndii** [comment]
I was never able to test this with the newest mek version since I stopped playing the block game

**Comment by Lord-Volkner** [comment]
I'm having this same issue. I don't think it's a chunk loading issue because I haven't left the area. I'm standing beside the miner and it isn't doing anything.

It did at first. It mined about half the area, then it quit. Now I can't get it to restart no matter what I do. I've moved to a different area. I don't know what else to try.

I know that the block I want to mine is present. The miner is sitting right on top of it. Soul Sand

**Comment by blackthijs0** [comment]
@Lord-Volkner 
Did you see the last edit to my post?
Can you confirm if the chunks giving the problems are claimed by "FTB chunks"?
If so, you can probably fix it by temporarily unclaiming or allowing machines to modify (I forgot the exact name of the setting and cannot look it up right now)

**Comment by SirEndii** [comment]
You can tell ftb chunks that he's allowed to mine in this chunks

**Comment by Lord-Volkner** [comment]
@blackthijs0

Thanks, but it turns out that my problem was an ID10T error. I accidentally set both the min and the max to the same value, so of course nothing happened. With proper settings, it's working just fine.

What was I thinking?

**Comment by WallaceFvck** [comment]
It was happening to me, loading chunks from the FTB was buggy on the Digital Miner, so I put a Familiar from Mahou Tsukai to load the chunk and it resolved it. (Yes, my Digital Miner's chunk limit was increasing)

Maybe outer chunk loading methods work, but I only tested it with Familiar.

![image](https://github.com/mekanism/Mekanism/assets/172298092/2fe1b3d3-ca33-4603-9bc2-0cf0d8fe33c5)

**Comment by RedTTG** [comment]
This is happening for me on local LAN
