### ISSUE TITLE
Enrichment Chamber Basic Tier Upgrade

### ISSUE THREAD

**Issue by LolBomer** [mekanism/Mekanism#7656]
### Issue description

When upgrading an enrichment chamber using a basic tier installer, you instead get a basic smelting factory. It should be basic enriching factory. Not game breaking because of alternative crafting recipe.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

14.23.5.2860

### Mekanism version

Older

### Other relevant versions

this is back in 1.12.2 but may have been easily overlooked in future versions

**Comment by pupnewfster** [comment]
Not an issue on modern versions, but thanks for the report. If I had to guess it likely was due to how factories shared the same block id in 1.12 and some bug with that.
