### ISSUE TITLE
Game not staring

### ISSUE THREAD

**Issue by XxDrexX-cmd** [mekanism/Mekanism#7658]
### Issue description

When i have mekanism installed my game won't start

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.43

### Mekanism version

10.3.5 (Latest)

**Comment by pupnewfster** [comment]
Provide your latest log

**Comment by Atomiiku** [comment]
Having same issue, here's my latest log.
[latest.log](https://github.com/mekanism/Mekanism/files/10037606/latest.log)

**Comment by Atomiiku** [comment]
> 

Having same issue, here's my latest log.
[latest.log](https://github.com/mekanism/Mekanism/files/10037608/latest.log)

**Comment by pupnewfster** [comment]
Optifine isn't compatible with the version of forge you are using.
