### ISSUE TITLE
Industrial Craft 2 Classic compatibility issues

### ISSUE THREAD

**Issue by NavedNoor** [mekanism/Mekanism#7662]
### Issue description

Sadly it´s not possible to connect universal cables to IC2C machines or IC2C cables to Energy Cube´s or Mekanism Machines.

### Steps to reproduce

1. Place IC2C machine
2. Try to connect universal Cable
3. No connection

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.43

### Mekanism version

10.3.5 (Latest)

**Comment by pupnewfster** [comment]
https://github.com/mekanism/Mekanism-Feature-Requests/issues/482
