### ISSUE TITLE
Wind generator energy production is same on y = -64 and y = 0

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#7663]
### Issue description

Wind generator energy production decreases with the height. On y = 0, it is 24 FE/t. When we go to y = -64 and place a wind generator there, the energy production is still 24 FE/t. 

### Steps to reproduce

1. Place 2 wind generators; one on y = -64, one on y = 0.
2. Check their energy productions. They will produce the same amount of energy, while the y = -64 wind generator should produce less energy.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.43

### Mekanism version

10.3.5 (Latest)

**Comment by pupnewfster** [comment]
Have you changed the generators config option for `windGenerationMinY` or is it still at its default of y = 24

**Comment by pupnewfster** [comment]
Confirmed on discord that the above is the case and the default config wasn't modified thus meaning this isn't an issue.
