### ISSUE TITLE
 poor connection of pipes with structures

### ISSUE THREAD

**Issue by W1ndit** [mekanism/Mekanism#7665]
### Issue description

there are 2 thermal evaporators and there are constant problems with connecting all the pipes from the mekanism, there were also two tanks from the tinker construct and they had the same problem, restarting does not help. When I removed 2 drain blocks from the tinker construct, one thermal evaporator connected to the pipes
![1](https://user-images.githubusercontent.com/89810110/201687392-9df575da-6bbb-4ea4-80f5-c35d05ded401.jpg)

### Steps to reproduce

1. connect the pipes to the heat evaporator
2. Go so far as to miss loading chunks

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

14.23.5.2860

### Mekanism version

Older

### Other relevant versions

mekanism versions 1.12.2-9.8.3.390
there is also Shadowfacts forgelin version 1.8.4

**Comment by Seniorendi** [comment]
looks like the towers are not formed (not properly built)

**Comment by pupnewfster** [comment]
They aren't connecting because the evap tower isn't formed. Valves can't be on the edges (including on the bottom).

**Comment by W1ndit** [comment]
> Они не соединяются, потому что испарительная башня не сформирована. Клапанов не может быть по краям (в том числе и по низу).

![2](https://user-images.githubusercontent.com/89810110/201708271-b77ae797-5946-481d-8188-38bc3523ca2d.jpg)
There are 2 more blocks down

**Comment by pupnewfster** [comment]
Evaporation towers are a 4x4 structure and need gaps between different towers. While it looks like yours is four deep, it seems to be 8 wide. Though not quite sure why the other one works without that one working, in theory neither should work given they are touching.

**Comment by W1ndit** [comment]
rearranged one tower and everything worked, thanks)
