### ISSUE TITLE
non-prescription universal cable

### ISSUE THREAD

**Issue by Galaxy188** [mekanism/Mekanism#7667]
### Issue description

I installed a pack of mods called skyfactory 4 in which the mekanism mod is included but upon reviewing in detail I realized that no recipe appears for several of the types of power cables that the jei mod does not appear and in creative mode if they appear but without a recipe
![image](https://user-images.githubusercontent.com/118588868/202837442-2fc91344-ab57-4b55-afc4-964c919f6e07.png)

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

14.23.5.2860

### Mekanism version

Older

### Other relevant versions

Mekanism-1.12.2-9.8.3.390

**Comment by pupnewfster** [comment]
If memory serves SF4 disables our transmitters.

**Comment by zappermax** [comment]
That’s because the modpack creator have blacklisted those items from being obtainable in the pack. The mod itself doesn’t do that.
