### ISSUE TITLE
Disabling energy buffer for cables removes their ability to transport energy

### ISSUE THREAD

**Issue by E-daw** [mekanism/Mekanism#7668]
### Issue description

When lowering the buffer capacity of universal cables in config the transport capacity is also lowered. I'm not sure if this is intentional.

### Steps to reproduce

1. Lower buffer capacity of universal cable in config
2. attempt to transport energy in game
3. watch as transport capacity is also lowered.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.52

### Mekanism version

10.3.5 (Latest)

**Comment by UnknownSerhan** [comment]
This is how transmitters work in Mekanism; their transfer rates are defined by their internal capacity. Lowering the capacity will also lowee the transfer rate.
