### ISSUE TITLE
Unable to fill Mekasuit helm or nutrient canteen from tanks

### ISSUE THREAD

**Issue by AgentKlunk2** [mekanism/Mekanism#7672]
### Issue description

Cannot fill the Mekasuit helmet or the Canteen with nutritional paste stored in any of the tanks (basic tanks all the way up to ultimate tanks and even dynamic tanks). Can only fill in the nutritional liquifiers built in tank.

### Steps to reproduce

1. fill tank with nutritional paste
2. attempt to place helmet in the output slot

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.80

### Mekanism version

Older

**Comment by UnknownSerhan** [comment]
There is a button bottom right on tank GUIs (both dynamic tank and fluid tanks) that let you input/output the content from items. You have to set it to “fill” to make it fill up.

**Comment by AgentKlunk2** [comment]
wow I feel really dumb right now, thanks
