### ISSUE TITLE
1.19.2 bugs

### ISSUE THREAD

**Issue by Joshernoob** [mekanism/Mekanism#7673]
### Issue description

Version: Mekanism-1.19.2-10.3.5.473
yellow cake has no recipe making it impossable to make a reactor without another mod

The isotopic centrifuge keeps only giving one fissile fuel eating the uranium hexafuoride unless you pull it out as its make

### Steps to reproduce

1: have isotopic centrifuge set up and a setup to make uranium hexafuoride (or cheat if testing) 
2: do not put a tank at the end for the fissile fuel or hook it up to anything
3: watch it eat the uranium hexafuoride while staying at 1 fissile fuel

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.55

### Mekanism version

10.3.5 (Latest)

**Comment by UnknownSerhan** [comment]
Those are not bugs... Yellow cake is maybe some recipe change due to modpack. Isotopic Centrifuge will always show 1 fissile fuel because it outputs it to somewhere else.

**Comment by Joshernoob** [comment]
> Those are not bugs... Yellow cake is maybe some recipe change due to modpack. Isotopic Centrifuge will always show 1 fissile fuel because it outputs it to somewhere else.

this is a custom pack with no recipe changes for a few small streamer and it wasn't outputing to anything i have nothing connected to it and it was just showing 1 hence why i said eating it

**Comment by Joshernoob** [comment]
even if its ment say 1 fact that when there nothing conected to the block it just eat the gas to make the fuel seem wrong

**Comment by UnknownSerhan** [comment]
These bugs are basically impossible to reproduce, so it is about your game, maybe the pack.

**Comment by pupnewfster** [comment]
Unable to reproduce, guessing it is just filling a buffer in tubes or something
