### ISSUE TITLE
Paxels stronk

### ISSUE THREAD

**Issue by RandoJohn-bit** [mekanism/Mekanism#7675]
### Issue description

https://github.com/mekanism/Mekanism/issues/6536 - covered before, stated fixed but is not

paxels are tooo powerfull!!!

for example : 
iron sword - 6dmg and 1.6 speed
iron axe - 9dmg 0.9 speed
iron paxel - 10dmg 1.6speed

also osmium paxel is mad op , its stronger than netherite paxel

in general : nerf paxel

### Steps to reproduce

1. craft praxel (any)
2. Note damage
3. craft a sword, even the best swords are worse than medium ranged paxels
4. profit??

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.57

### Mekanism version

10.3.5 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

I really highly doubt that

**Comment by pupnewfster** [comment]
If you want to rebalance things for your playthrough use the configs. You are looking at only a couple of the stats of various things and saying they are stronger because of that when there are other stats they  are worse on
