### ISSUE TITLE
mekanism crashes the game at the opening

### ISSUE THREAD

**Issue by Kareem987789** [mekanism/Mekanism#7676]

**Comment by UnknownSerhan** [comment]
You need to provide crash report/log so we can help you.

**Comment by Kareem987789** [comment]
> You need to provide crash report/log so we can help you.
i didnt get any report

**Comment by pupnewfster** [comment]
Look at your minecraft's instance folder and grab the latest log or crash log. So due to lack of information my best guess is remove optifine.
