### ISSUE TITLE
Rendering glitch of inside part of energy cube

### ISSUE THREAD

**Issue by matix931** [mekanism/Mekanism#7677]
### Issue description

I suppose this issue will be ignored due to using shaders, but anyway I will try my luck.

**What is happening?**
Inside part from energy cube is rendering somewhere on the screen while walking around nearby cube.
This part is moving like it has been connected to moon or sun. When moon or sun appears it's possition is significantly changing.
![2022-12-07_21 19 32](https://user-images.githubusercontent.com/1347171/206287364-b187cb07-b9c0-420a-8e76-4c6cca8c78e9.png)
![2022-12-07_21 19 36](https://user-images.githubusercontent.com/1347171/206287398-85722f55-1f9e-4e89-be2c-f561f1f87b26.png)

**What is expected?**
This thingy should not render on screen.

### Steps to reproduce

1. Build couple Basic Energy Cubes filled with energy somewhere.
2. Go away for about 3 blocks
3. Look around somewhere on the sky (better visible at night)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.57

### Mekanism version

10.3.5 (Latest)

### Other relevant versions

* rubidium-0.6.2
* oculus-mc1.19.2-1.2.8
* any shaderpack for example BSL

**Comment by pupnewfster** [comment]
Does this happen without shaders or rubidium or oculus?

**Comment by matix931** [comment]
No, even with installed rubidium and oculus it is not happening, disabling shader is "fixing" this issue, but it is happening on every shaderpack, tried couple. I hope you could change how It is rendered or add option to disable this effect.

**Comment by pupnewfster** [comment]
Report to oculus, guessing it is a bug with how they integrate with forge
