### ISSUE TITLE
Gas burning generator not Craftable in Survival

### ISSUE THREAD

**Issue by McD1nkel** [mekanism/Mekanism#7679]
### Issue description

i have the newest version installed of the mekanism mod and the mekanism generator, tools and ... mods. But the Gas burning generator isnt craftable. I surched up the crafting recipe on the internet and i still cant craft it. Why

### Minecraft version

1.19.2 (Latest)

### Forge version

10.3.5.473

### Mekanism version

10.3.5 (Latest)

**Comment by pupnewfster** [comment]
Please provide your latest log, and also does the recipe show up in JEI for either the gas burning generator or any of the other generators?

**Comment by McD1nkel** [comment]
Jei shows the recipe for every other generator except for the bio gas one

Sara Freimer ***@***.***> schrieb am Di., 20. Dez. 2022,
20:24:

**Comment by pupnewfster** [comment]
Are you playing a prebuilt modpack? It is possible they disabled the gas burning generator recipe
