### ISSUE TITLE
Game crashing with Mekanism

### ISSUE THREAD

**Issue by AlfaM0de** [mekanism/Mekanism#7682]
### Issue description

The game crashes on startup with the Mekanism mod. The mod "Not enough crashes" indicates the cause in Mekanism.

### Steps to reproduce

I was making a modpack to play with friends, but when Mekanism is added, the game crashes.

Mod list:

1. AppleSkin
2. Balm
3. Better Advancements
4. Bookshelf
5. Cloth Config v8 API
6. Clumps
7. Controlling
8. Corpse
9. Durability Tooltip
10. EnchantmentDescriptions
11. Explorer's Compass
12. Ferrite Core
13. HT's TreeChop
14. Inventory Profiles Next
15. Iron Chests
16. Jade
17. Jade Addons
18. Journeymap
19. Just Enough Effect Description
20. Just Enough Items
21. Just Enough Resources
22. Kiwi
23. libIPN
24. Mekanism
25. More Overlays Updated
26. Mouse Tweaks
27. Nature's Compass
28. NetherPortalFix
29. Not Enough Crashes
30. Passable Foliage
31. Placebo
32. Polymorph
33. Shutup Experimental Settings!
34. Sound Physics Remastered
35. SpectreLib
36. SuperMartijn642's Config Libra
37. Toast Control
38. TrashSlot
39. Optifine

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Mekanism version

10.3.5 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://crashy.net/BBAyhEa54C8yhUoZSBa0

**Comment by pupnewfster** [comment]
Optifine isn't compatible with your version of forge and removes features of forge that Mekanism uses
