### ISSUE TITLE
Mekanism cable joint texture is screwed up from using Rubidium 0.6.2 

### ISSUE THREAD

**Issue by D4RKTARGET** [mekanism/Mekanism#7685]
### Issue description

While using Mekanism-1.19.2-10.3.5.473 and rubidium-0.6.2, the joint in almost all mekanism cables with the energy icon seem to be screwed up, removing rubidium brought back the texture of the cable joint to normal but there are no settings as far as I know that would of screwed with the texture.

I've noticed the Elite cables are fine but if you use rubidium_extra and textrues_sodium_options it seems to break the Elite cables as well

### Steps to reproduce

1. Install Rubidium-0.6.2 and Mekanism-1.19.2-10.3.5.473
2. Place down any variant of mekanism cable (energy, pressurized, mechanical, etc)
3. The joint texture of the cable will be screwed up (not necessarily missing a texture)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.1

### Mekanism version

10.3.5 (Latest)

### Other relevant versions

Rubidium-0.6.2

Pictures:
![2022-12-21_16 04 28](https://user-images.githubusercontent.com/55817520/209233205-a46f2f48-905a-4cf7-821e-f33bb05d0bcf.png)

![2022-12-17_14 52 00](https://user-images.githubusercontent.com/55817520/209233255-d517031b-3704-4e29-9e8e-4234c284dd6b.png)

**Comment by pupnewfster** [comment]
Report to rubidium, nothing we can do about it we just use normal forge systems.

**Comment by UnknownSerhan** [comment]
Press f3 + a to fix it
