### ISSUE TITLE
MekaSuit Inhalation purification unit consumes energy rapidly when attempting to remove bad omen status effect

### ISSUE THREAD

**Issue by Ryuunosuk3** [mekanism/Mekanism#7686]
### Issue description

Very simple yet annoying bug, when a MekaSuit helmet is equipped with an Inhalation Purification unit and you have the bad omen effect, it continuously tries to remove the status effect but fails, resulting in a perpetual loss of energy of the helmet.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.65

### Mekanism version

10.3.5 (Latest)

**Comment by toddlersizedsharkcage** [comment]
Disable neutral effects from the unit in the module tweaker. It takes that much energy to remove bad omen, and bad omen is neutral

**Comment by pupnewfster** [comment]
Adding on to what shark said it is because vanilla applies bad omen on a two hour timer so having to get it to zero takes a while.
