### ISSUE TITLE
Can‘t put anything into the Base compression plant which is the upgrade version of Metallurgic Infuser

### ISSUE THREAD

**Issue by player0010** [mekanism/Mekanism#7687]
### Issue description

For the 1.19.2-10.3.5.473 Forge version, I can't put anything into the plant, but the other plants work as normal. And I don't install any other mods, even the Optifine, only forge.
 
 

### Minecraft version

1.19.2 (Latest)

### Forge version

10.3.5.473

### Mekanism version

10.3.5 (Latest)

**Comment by player0010** [comment]
![image](https://user-images.githubusercontent.com/121457160/209578336-f1ac89ec-cba7-483e-ad77-5ca93cf788ac.png)
![image](https://user-images.githubusercontent.com/121457160/209578372-438bf11c-e9b5-475d-8280-48009cedcd2b.png)


that‘s how I place the things

**Comment by pupnewfster** [comment]
Can you please show a picture of the machine's GUI?

**Comment by player0010** [comment]
sorry I figure it out, thx, I just use the wrong machine. thx again
