### ISSUE TITLE
Using /data command to modify ownership of mekanism stuff

### ISSUE THREAD

**Issue by Ja1Lopes** [mekanism/Mekanism#7690]
### Issue description

So, given the shady nature of a certain minecraft launcher resurfacing, I've recently changed to TLegacy thus changing my uuid, I've been able to change almost every uuid conflict on files but couldn't find the mekanism ones, so how can you select the owner part of the nbt data of the item with the /data modify command? (I figured out the uuid formatting so I just need to know how to select it)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.1

### Mekanism version

10.3.5 (Latest)

**Comment by pupnewfster** [comment]
But the game, we provide no support for cracked installs.

**Comment by Ja1Lopes** [comment]
But, even if I buy the game(witch I'm planning to do next month), won't I have the same exact same problem because the uuid will change again?

**Comment by Jcodeerd** [comment]
usernames are linked to UUIDs, and your UUID never changes.

**Comment by Ja1Lopes** [comment]
The thing is, when you change from one launcher to the other, or upgrade to the original version, even if you have the same username, your uuid changes, thus voiding your access to most of the items

**Comment by tyler489** [comment]
> The thing is, when you change from one launcher to the other, or upgrade to the original version, even if you have the same username, your uuid changes, thus voiding your access to most of the items

Only if you are using pirated copies of the game, An official copy  will have the same uuid for All launchers, if the server is in online mode.
