### ISSUE TITLE
More than one Attack module has no effect

### ISSUE THREAD

**Issue by clubpetey** [mekanism/Mekanism#7691]
### Issue description

Adding one attack module brings the damage of the Meka-Tool from 5 to 13.  However adding more attack modules after the first has no effect.  The damage stays at 13.  Also, the Damage value listed in the HUD when holding the tool is shows as "8".  

Since the meka-tool uses an atomic disassembler in the crafting recipe, it seems strange that the base damage starts at 5 when the AD base damage is 21.  If each Attack module is designed to add 8 to attack value, then it takes 2 modules just to get the to base damage of the AD?

### Steps to reproduce

1. Craft the meka-tool and 2 attack modules
2. place the meka-tool into the modification table -- note damage is 5
3. add one attack module -- note damage is 13
4. add second attack module -- note damage stays at 13
5. Place meka-tool in hand, note damage in HUD is listed as 8

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.1

### Mekanism version

10.3.5 (Latest)

**Comment by pupnewfster** [comment]
Have you adjusted the damage in the module tweaker? Default keybinding is `\`

**Comment by clubpetey** [comment]
Ah! so that explains why the damage increase is +8.  After moving the slider around it does increase the damage. Which means perhaps its working as designed.  However I still have two issues with the design:

1. Why does it take 2 modules just to get back to the default attack power of the Atomic Disassembler, when the meka-tool is crafted with one.  The base damage should be at least 21.
2. The "Damage" value in the HUD is misleading, as it is not damage, but damage increase.  i would either change the name to "Damage Increase" or maybe change the value to "+8"

**Comment by pupnewfster** [comment]
1. No idea why the values were chosen the way they were but we aren't increasing the base damage, certainly not to 21. You can change the configs if you want. Some reasoning could be that it is a more broad spectrum tool so by default doesn't have as much stats as the disassembler does at taking things apart. Alternatively it is just a crafting recipe... not everything inherits the component stats of ingredients entirely.
2. I think I will change it to `Damage Amplification:` as I agree it is a bit confusing
