### ISSUE TITLE
Geothermal Generator Units don't seem to do anything

### ISSUE THREAD

**Issue by clubpetey** [mekanism/Mekanism#7692]
### Issue description

There's no description I can find on these units beyond the tool tip, but I've added 1, 2 and 8 into the meka-pants, and I cannot see any effect.  

What I expected to happen is that when standing on a magma block or in lava, the suit would not take damage, but instead get re-charged.  But doing either of these just causes the suit to take damage, whether I install 1 or 8 modules.

### Steps to reproduce

1. Craft Geothermal modules
2. insert 1 - 8 modules into meka-pants
3. step on magma block or step into lava

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.1

### Mekanism version

10.3.5 (Latest)

**Comment by pupnewfster** [comment]
I will look into this further but with default configs, when having 8 geothermal generator units installed it should reduce damage to things like lava, fire, and magma blocks by 80%, and also create energy based on how hot the thing you are in is (standing on magma blocks doesn't generate power/heat) and how much of it your "legs" is in. This means when standing inside of lava the amount of energy generated should be a net gain compared to how much power is lost. But yes it is not a massive amount of power as it is passive power gen
