### ISSUE TITLE
The Electrolytic Separator can't output oxygen to the Purification Chamber

### ISSUE THREAD

**Issue by player0010** [mekanism/Mekanism#7693]
### Issue description

![image](https://user-images.githubusercontent.com/121457160/210236393-0f511c79-ba31-400d-aeaa-1131e2b53c02.png)
![image](https://user-images.githubusercontent.com/121457160/210237100-8c26be4f-9578-4803-a839-93c8a5293551.png)
![image](https://user-images.githubusercontent.com/121457160/210236512-73c7eeb6-80a9-405c-9f25-d877460f653e.png)

settings of my electrolytic separator, I out put the oxygen gas at the right, then I access the Basic Pressurized Tube at the right of machine,  

![image](https://user-images.githubusercontent.com/121457160/210236685-7162078a-ae7f-4891-b322-6e2be4df917d.png)
![image](https://user-images.githubusercontent.com/121457160/210237150-9072fb60-d80e-43c1-92d4-d6c9ef4cbf60.png)
![image](https://user-images.githubusercontent.com/121457160/210236902-24796871-ed09-4e5f-8693-5b4780c7c552.png)

settings of my purification chamber, and all the interface is set to the "input"
I access the tube at the left of it, but the gas can't go into the machine.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.1

### Mekanism version

10.3.5 (Latest)

**Comment by UnknownSerhan** [comment]
You are outputting hydrogen, not oxygen.

**Comment by player0010** [comment]
> 

but I set the hydrogen output at the left, why it can output at the right

**Comment by player0010** [comment]
thx i figure it out
