### ISSUE TITLE
MekaSuit does not render with shaders

### ISSUE THREAD

**Issue by Mohawk1025** [mekanism/Mekanism#7695]
### Issue description

I am playing on the All The Mods 8 pack, which has a few versions of Complementary Shaders included with it. When any of the shaders are turned on, the MekaSuit does not render. It is completely invisible.

You can see the suit in the little preview window in the inventory screen, but in-game it does not render.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.55

### Mekanism version

10.3.5 (Latest)

**Comment by pupnewfster** [comment]
Report to whatever mod you are using to load shaders.
