### ISSUE TITLE
Jetpack doesn't preserve velocity from speed potions

### ISSUE THREAD

**Issue by McStebb** [mekanism/Mekanism#7696]
### Issue description

When you walk and begin hovering, the Jetpack wil preserve your walking velocity.

When you sprint and begin hovering, the Jetpack will also preserve your sprinting velocity as long as you keep holding W.

Taking a Speed potion and attempting to sprint and hover, the jetpack will revert back to normal "running" speed after leaving the ground.

Given that the jetpack preserves sprinting speed, it seems like it should preserve forward speed from speed potions.

### Steps to reproduce

1. Brew/give yourself a Potion of Swiftness (the effect is most obvious with Speed II)
2. Begin running. With Speed II you will go quite fast.
3.  Jump to begin flying with the jetpack. Your forward speed will be reduced to normal run speed.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.85

### Mekanism version

Older

**Comment by pupnewfster** [comment]
After looking at this and discussing this a bit internally this is intended. The way the jetpack works is it just modifies the current delta movement of the player. When moving in the air minecraft uses a separate flight speed variable (be it when you are in the air just from jumping or falling, or if you are flying in creative). This speed variable is not affected by things like speed potions.
