### ISSUE TITLE
"Game crashed whilst rendering overlay" crash in my modpack

### ISSUE THREAD

**Issue by AshiDeino** [mekanism/Mekanism#7698]
### Issue description

I have been slowly developing a modpack that i play on and i decided i really wanted stuff like the fluid tank from mekanism since it works well, so when i added mekanism i also added the following mods.
Mekanism Additions
Mekanism Generators
Mekanism Tools
Mekanism Rotten Flesh Crusher Conversion
More Mekanism Processing
When i launched minecraft with these mods and Mekanism added to my modpack, my game crashed before i even saw the starting menu where you can choose singleplayer or multiplayer.
I tried again without these mods, worked just fine.
Tried again a third time with just mekanism added, not the other mods, and it crashed again with the same issue
The pastebin crash report i added at the end of this report shows with every mod mentioned above aswell as mekanism, but mekanism is the cause of the problem as i tested and stated above.

### Steps to reproduce

1. Added Mekanism to my modpack
2. Open Minecraft, and watch it crash before even getting to see starting menu

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Mekanism version

10.3.5 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/4Q4qr8ui

**Comment by pupnewfster** [comment]
Remove optifine

**Comment by AshiDeino** [comment]
> Remove optifine

I did and it still crashed for the same reason
