### ISSUE TITLE
Retrogen Crashes Server

### ISSUE THREAD

**Issue by wiggle1000** [mekanism/Mekanism#7699]
### Issue description

Attempting to retrogen causes crash on both dedicated and internal server. Originally noticed in a full modpack on a dedicated server, then isolated in a new instance.

### Steps to reproduce

1. Create clean forge install with no mods
2. Generate world, load some chunks
3. Close game, install Mekanism
4. load into world again to generate all configs, then close minecraft
5. Change "enableRegeneration" to true in world.toml
6. Load back into world and run /mek retrogen

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.3

### Mekanism version

10.3.5 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/wiggle1000/5c1a44d1b5eacf5e77fcb56e82d7fd82

**Comment by pupnewfster** [comment]
I think I see how this happens and will fix it in the next version, but I believe you can fix this by bumping the `userWorldGenVersion` in the world config from `0` to `1` or something

**Comment by wiggle1000** [comment]
Ah! Thank you for the workaround! 😊
