### ISSUE TITLE
Universal cable won't connect to the Redstone Flux Cell (Thermal Series)

### ISSUE THREAD

**Issue by princess-mikus** [mekanism/Mekanism#7700]
### Issue description

Title. None of the Universal cables would connect to the RF Cell from Thermal Foundation. The transfer rate on itself is right (3.2k in the cable, 1k max output on the cell). 

### Steps to reproduce

1. Place RF Cell.
2. Place Universal cable to the side.
3. No connection.
4. The cable does connect to the dynamos, just not the cell.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Mekanism version

10.3.5 (Latest)

**Comment by SirEndii** [comment]
Have you changed the side configuration of the flux cell?

**Comment by princess-mikus** [comment]
Yeah, it was that. Sorry.
