### ISSUE TITLE
Minecraft Crash rendering mekanismtools:refined_glowstone_layer_1.png

### ISSUE THREAD

**Issue by Timkokain** [mekanism/Mekanism#7701]
### Issue description

The game crashes after finding this entity in view. Optifine is not installed.

### Steps to reproduce

Entering the field of view of an object wearing certain Glowstone armor.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Mekanism version

10.3.5 (Latest)

### Other relevant versions

The list of mods is in the logs

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Timkokain/5cd308f24e9b267294e948a1e8ba9486

**Comment by pupnewfster** [comment]
Report to Rotten Creatures. I am guessing they are using some copy of vanilla's `HumanoidArmorLayer#getArmorLocation` instead of the version forge uses `HumanoidArmorLayer#getArmorResource` that adds better support for mods

**Comment by Timkokain** [comment]
> Report to Rotten Creatures. I am guessing they are using some copy of vanilla's `HumanoidArmorLayer#getArmorLocation` instead of the version forge uses `HumanoidArmorLayer#getArmorResource` that adds better support for mods

Ok, thank you.  I will write to them.
