### ISSUE TITLE
Luck Perms & Mekanism Security configuration crash

### ISSUE THREAD

**Issue by JustAnotherGhostName** [mekanism/Mekanism#7703]
### Issue description

When luckperms is installed, and Mekanism is configured under `general.toml` in `general.security` to have `allowProtection = true` and the `opsBypassRestriction = true`, the server will crash upon startup. This is currently tested on a ATM8 version 1.0.7 server.

There appears to also be some link to Industrial Forgoing, as the block entity being ticked is a block pacer as part of a standard fluid extraction setup, however, nothing about this setup seems abnormal (IE, its not trying to place any mekanism blocks, and the only mekanism thing attached to the block placer is an advanced universal cable.)

### Steps to reproduce

Note that this is only tested on my server, not in single player yet as this is a lower priority issue for me.

1. Startup a new ATM8 1.0.7 server
2. Shutdown to do config changes
3. Add `LuckPerms-Forge-5.4.57.jar` to the mods folder
4. Configure `./serverFiles/config/Mekanism/general.toml` to have `allowProtection = true` and the `opsBypassRestriction = true`.
5. Start server back up
6. Crash?

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.55

### Mekanism version

10.3.5 (Latest)

### Other relevant versions

LuckPerms-Forge-5.4.57.jar
industrial-foregoing-1.19.2-3.3.2.1-3.jar

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/JustAnotherGhostName/66e2209d8c3fe93288a7f1d4af1e02d8

**Comment by pupnewfster** [comment]
Sounds like a luckperms bug, we are just using forge systems that add support for permissions in general.
