### ISSUE TITLE
Crashes when loading the world

### ISSUE THREAD

**Issue by luacoder279** [mekanism/Mekanism#7704]
### Issue description

the game crashes when opening the world

### Steps to reproduce

1. Have mods installed
2. Crash
3. Remove mods
4. Crash again
5. report issue on github

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.1

### Mekanism version

10.3.5 (Latest)

**Comment by pupnewfster** [comment]
Logs or it didn't happen

**Comment by luacoder279** [comment]
no logs it just crashes when the world loads

**Comment by luacoder279** [comment]
oh now it works
