### ISSUE TITLE
Occultism Machine Operators and Mekanism machines don't appear to be compatible

### ISSUE THREAD

**Issue by bigfoott** [mekanism/Mekanism#7706]
### Issue description

When going through the steps to link an Occultism Machine Operator to a machine, the link doesn't appear to work.

Also see: https://github.com/klikli-dev/occultism/issues/879

I also want to note that this isn't necessarily a bug on Mekanism's end, but a mod in Occultism's Discord suggested making an issue here just so you guys are aware as well :)

### Steps to reproduce

See video: https://www.youtube.com/watch?v=r11uasiGbbk

### Minecraft version

1.19.2 (Latest)

### Forge version

43.1.55

### Mekanism version

10.3.5 (Latest)

### Other relevant versions

Occultism 1.19.2-1.60.0

Also worth mentioning this is in ATM8 version 1.0.7 - https://www.curseforge.com/minecraft/modpacks/all-the-mods-8

**Comment by pupnewfster** [comment]
Is the side config of the machine setup to expect inputting/outputting from the corresponding side?

**Comment by bigfoott** [comment]
Yeah, it is. This is most likely something on Occultism's end, just wanted to include an issue here just in case.

**Comment by pupnewfster** [comment]
Yeah no idea, my best guess would be they don't actually use the side you select as the side they query the cap for, but who knows.

**Comment by klikli-dev** [comment]
creator of occultism here, chiming in :)

Occultism does query the capability for the side configured by the player.
I think in this case the issue might have been that all sides were unset and did not offer a cap ( in which case the machine will never be linked, and we don't see a "has been linked" message in the video" )
Or the target side was unset and did not offer a cap, which will cause the machine to get removed.

I think it is fair to call this working as intended for both mods - players just need to configure the mekanism machine's sides before linking it, and keeping the settings in tact (or re-linking the machine with correct settings after making breaking changes)

**Comment by pupnewfster** [comment]
Ah, good to know, and yeah when the side config changes the existing caps for the changed sides get invalidated and if set to a different config provided with that new cap, otherwise if set to none they won't provide a new cap.

**Comment by bigfoott** [comment]
Hi! Sorry, I've been unable to update the issue(s) ive made regarding this bug.

From my testing, if *any* side is unset, occultism is unable to make the connection, not just the target side. I unset the bottom face (while the given machine is sitting on the ground) and the issue persisted  despite me clicking on the other faces.

As long as every side is set, it seems to work fine. I dont mind if the issue is closed as I'm now using this workaround, but it doesn't feel intended.
