### ISSUE TITLE
Fission reactor lost fuel and waste upon save and load

### ISSUE THREAD

**Issue by Wgairborne** [mekanism/Mekanism#7707]
### Issue description

When I saved and quit my singleplayer world right after shutting down my fission reactor (which is the bare minimum setup for a reactor and turbine), I came back to it essentially reset. All stored fuel and nuclear waste was gone, and the burn rate was reset to 0.1 as if it was just built. Oddly though, the water in it remained.

Update: One issue I've now noticed with my setup after some research is that I just so happened to build my fission reactor between four chunks... very bad luck. I am still unable to reproduce it on another save, however I highly suspect that it is the issue at hand.

Due to this possibly being an unfixable issue due to core chunk mechanics in MC, I suggest a slightly intrusive fix of preventing players from forming multiblocks on chunk boundaries, with a chat message noting them of why the multiblock failed to form.

### Steps to reproduce

~~I attempted to reproduce this, with no luck. I'm making this issue so that it can be known to the devs and others that this has occurred, and hopefully someone can eventually find a solid way to reproduce this bad bug.~~

(allegedly)
1. Create fission reactor right where four chunks intersect.
2. Save and quit until expected bug.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Mekanism version

10.3.5 (Latest)

**Comment by pupnewfster** [comment]
Have you been able to reproduce this wiith just mekanism (and sub modules)? It sort of just sounds like something might be causing saving to fail.
