### ISSUE TITLE
[1.12.2] Modpack Crashing When opening, Mekanism detected as a problem by Vanilla Fix

### ISSUE THREAD

**Issue by NotThisTime4587** [mekanism/Mekanism#7712]
### Issue description

While trying to start it crashed, didn't happen before adding Mekanism, suspect a possible complication with another mod

### Steps to reproduce

1. Launch the game

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

14.23.5.2860

### Mekanism version

Older

### Other relevant versions

Mekanism-1.12.2-9.8.3.390

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/DJyiZtZ9 and https://pastebin.com/cD0wYyCG

**Comment by pupnewfster** [comment]
#6182
