### ISSUE TITLE
Fission Reactor Ports

### ISSUE THREAD

**Issue by Anirra** [mekanism/Mekanism#7713]
### Issue description

I'm having problems with my fission reactor. It turned into a multiblock, I got the red particles, but all of my ports look exactly the same. I've gotten water in and the fissile fuel in, but I can't get the nuclear waste or the steam out of a port. It's like it's not an output. But they are all the same looking port. Not different colors.

### Steps to reproduce

I've tried completely disassembling it and starting over and it still forms with all the ports looking the same green color.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.3

### Mekanism version

10.3.5 (Latest)

**Comment by SirEndii** [comment]
Click with a configurator onto the port, it will change its output to steam/waste

**Comment by Anirra** [comment]
Ah okay, had no idea that was needed. Thank you!
