### ISSUE TITLE
Smallest Fission Reactor (3x4x3) can't take the fissile fuel

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#7718]
### Issue description

Apparently after the new update, the smallest fission reactor can't take the fissile fuel in. The fuel tank of the reactor is completely "removed" because there is no way to put fuel in there, even gauge dropper doesn't work. This issue only happens with 3x4x3 reactor.

### Steps to reproduce

1. Build a 3x4x3 fission reactor.
2. Try to insert fissile fuel into it, it won't insert.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.4

### Mekanism version

10.3.6 (Latest)

**Comment by Mjolinir** [comment]
I can confirm this, I noticed it this morning while testing a new reactor setup. As soon as I reverted to the previous version it works again.

MC 1.19.2
Mekanism ver 10.3.6.475
Forge ver 43.2.3

**Comment by pupnewfster** [comment]
Yeah, I hope to get a fix out in the next couple days. It should be a pretty straightforward fix, basically it just doesn't update the capacity properly if there is only a single fuel assembly. The second you have more than one it updates fine.
