### ISSUE TITLE
Cant access any machines inventory

### ISSUE THREAD

**Issue by j4n3k2212** [mekanism/Mekanism#7719]
### Issue description

Hi,

i am playing "All the mods 7 to the sky" on Version 1.2.0 of the pack and just got my first mekanism machine, the metallurgic infuser and when i placed it and tried to access the inventory it didnt let me. its sometimes showing for a split second but thats it, cant access the inventory. it feels like it instantly "kicks" me out of the inventory. I then tried other Mekanism machines but same issue. I also restarted my world and also the whole pack but issue is still there. I then tried to make a new world but also there the issue exists.

Its on Minecraft Version: 1.18.2
Mekanism Version: 10.2.5.465
Also installed is Mekanism Tools and Mekanism Generators.

### Steps to reproduce

- Download ATM7 to the sky version 1.2.0
- Generate a world
- place a mekanism machine
- try to access the inventory

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.86

### Mekanism version

Older

**Comment by pupnewfster** [comment]
This sounds like some cross mod interaction causing guis to exit as I cannot reproduce this issue with just mekanism. I would recommend you report this to the ATM team to see if they can figure out what combination of their mods is causing this issue (and if they can even reproduce it in the first place)
