### ISSUE TITLE
Logistical transporters doesnt transport items to machines but it transports to bins

### ISSUE THREAD

**Issue by DieAnotherDayTD** [mekanism/Mekanism#7721]
### Issue description

when i try to connect a bin to a machine it doesn't transfer the items from bin to machine but it transfers when its the other way around and it transfers from machine to machine idk what the problem is im currently playing on all the mods 7 modpack and it doesnt work properly i didnt test it individually and i dont know if it work on the other modpacks

### Steps to reproduce

https://user-images.githubusercontent.com/124405070/216721751-84d57422-dceb-4166-ba79-5f94a6839fb6.mp4

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.1.80

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Is the side config for the back of those infusers set to "extra" (yellow) on the items tab?

**Comment by DieAnotherDayTD** [comment]
oh yeah sorry my bad i just turned it to input thanks
