### ISSUE TITLE
Advanced Bin display missing while using shaders

### ISSUE THREAD

**Issue by djzg** [mekanism/Mekanism#7722]
### Issue description

Greetings, not sure if this bug was reported earlier but I couldn't find it using usual search topics.

I'm running a Manufactio modpack that includes Mekanism. It runs on 1.12.2 Minecraft version.
Few days ago I've installed Complementary shaders v4.7.1 and noticed the display that shows items in Advanced bin is blacked out and only a black contour can be seen. 
I've reported it to the Complementary devs and they said:
"Unfortunately the problem is caused by incorrect color values being passed from the mod to the shaderpack. I don't think we can do much about it on the shader side."

Is there any chance from your side to try and fix this issue? 
I'm attaching few screenshots, if there's anything else, please let me know.

Thanks for the help.
![mc_prtscn3](https://user-images.githubusercontent.com/12217840/216722223-67b5c93e-131e-453a-996b-bce870eb1e40.png)
![mc_prtscn1](https://user-images.githubusercontent.com/12217840/216722248-31fe386d-b808-4cf4-8ad8-d8fff43cb1df.png)

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

14.23.5.2860

### Mekanism version

Older

### Other relevant versions

Optifine 1.12.2_HD_U_G5
ComplementaryShaders_v4.6, or v.4.7.1

**Comment by pupnewfster** [comment]
1. We are no longer developing for 1.12
2. Report to Optifine. We are just passing colors normally (granted might be slightly less normal in 1.12 I forget), and optifine's hacks to the rendering system are probably just garbling things.

**Comment by djzg** [comment]
Interesting. So the plot thickens. 

Thanks for the info. If the Optifine is at fault, perhaps I might have better shot with other similar tools like Iris?
I'll try switching and if it doesn't help, I'll write to Optifine devs. 
Thanks again!

**Comment by pupnewfster** [comment]
Who knows how Iris does things, in general it tends to handle some stuff better than optifine, but other stuff worse than it. Granted it is 1.12 so all bets are off as could be mek just was doing super messy stuff back then for rendering that (I forget, and only was part of the dev team towards the end of our support for 1.12). Though I don't think iris and stuff go back to MC 1.12 (granted could be wrong, haven't checked in a long time).

**Comment by djzg** [comment]
Yes, it might be a too old version for the newer tools. I'll create an issue on their page and let you know if I receive an answer.
It's a bit strange no one reported this bug, or I've missed it during search. Both mod and optifine are quite old so I wonder perhaps the bug wasn't solvable and it stayed that way. 

Thanks again, I'll write when I get the response from them.
