### ISSUE TITLE
Digital Miner causing a ticking block entity crash

### ISSUE THREAD

**Issue by mannbruhmann** [mekanism/Mekanism#7726]
### Issue description

I recently moved my Digital Miner away from my base so I added a anchor upgrade to it. I leave the chunk and return to my base and then the game crashes and now I can no longer join the world without it crashing

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Mekanism version

Current Dev Branch (Manually Compiled)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/mannbruhmann/32861c6bc5a6f5d267448b682f2d09ba

**Comment by pupnewfster** [comment]
This is fixed in dev but your issue is wrong about what version you selected as the one you currently are on, as it is already fixed in dev and the log shows you are on the released 10.3.7 version

**Comment by mannbruhmann** [comment]
How do I find what version I am in?

**Comment by mannbruhmann** [comment]
anyways in the mean time, I just reverted to an older version of Mekanism and now it works

**Comment by Midnight-Vortex** [comment]
when we release 10.3.8 because the fix would help us to play with it normally again

**Comment by batmanrobin68002** [comment]
there is one simalar to that i encountered. where if you put speed upgrades it goes to fast and duplicates ores causeing the world to crash over and over

**Comment by batmanrobin68002** [comment]
and that is in 1.19

**Comment by batmanrobin68002** [comment]
specificly 1.19.2
