### ISSUE TITLE
Translate error in zh_cn

### ISSUE THREAD

**Issue by Mineablechn** [mekanism/Mekanism#7727]
### Issue description

"block.mekanism.block_fluorite" should be translated to"氟石块" instead of "萤石块", "萤石块" is glowstone!

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

It doesn't matter

### Mekanism version

Older

**Comment by SirEndii** [comment]
You can fix translation issues by yourself via crowdin → https://crowdin.com/project/mekanism
The maintainer of mekanism do not change these translations on their own.
