### ISSUE TITLE
Meka Suit invisible on 1.19.2

### ISSUE THREAD

**Issue by Nonen7** [mekanism/Mekanism#7729]
### Issue description

My meka suit is for me and for all others on the server invisible in third person.
I am using the unity resource pack.
https://gyazo.com/4b8ab7a630adfe7fc920a742c5ca5425
Version: Mekanism-1.19.2-10.3.5.473

### Minecraft version

1.19.2 (Latest)

### Forge version

Serverside 43.2.3 - Clientside 43.2.0

### Mekanism version

10.3.5

**Comment by SirEndii** [comment]
Which mod do you use for shaders

**Comment by Nonen7** [comment]
Complementary Shader

**Comment by Nonen7** [comment]
ohh i see its the issue of the shader. Without shader its working fine. 
Do you have supported shaders?

**Comment by SirEndii** [comment]
Which mod do you use for loading it?
Optifine, Oculus, anything else?

**Comment by Nonen7** [comment]
Oculus

**Comment by SirEndii** [comment]
> Oculus

You already have a good shader, but you may need to adjust some settings
But I don't know how to fix it

**Comment by Nonen7** [comment]
Ok i didnt know that its because of Oculus. Thank you very much!
