### ISSUE TITLE
World-Crash - duplicate Element - Digital Miner

### ISSUE THREAD

**Issue by BlacKHaraZ** [mekanism/Mekanism#7732]
### Issue description

Hey guys..
I've a small technic mod server and mekanism is the one and only elementary mod for years to my packs.

Now we got an issue and world crash without any player being on the server which corrupted my world so the server (or in singleplayer) can't load the world.

[crash-2023-02-08_17.11.10-server.txt](https://github.com/mekanism/Mekanism/files/10689743/crash-2023-02-08_17.11.10-server.txt)

### Steps to reproduce

I could not reproduce this issue yet but if I understood this error right it's the digital miner so I can say what I did with that:

I placed the miner and configed it:
 - Auto-Eject: on
 - Auto pull: off
 - Silktouch: off
 - Filters: 15
     - Tag Filter: "*coal"
     - Tag Filter: "*iron"
     - Tag Filter: "*copper"
     - Tag Filter: "*tin"
     - Tag Filter: "*osmium"
     - Tag Filter: "*silver"
     - Tag Filter: "*gold"
     - Tag Filter: "*lapis"
     - Tag Filter: "*redstone"
     - Tag Filter: "*diamond"
     - Tag Filter: "*niter"
     - Tag Filter: "*sulfur"
     - Tag Filter: "*emerald"
     - Tag Filter: "*fluorite"
     - Tag Filter: "*lead"
- Radius: 16
- Min. Lvl: -64
- Max. Lvl: 60
- Inverse mode: off

I connected a full "Elite Energy Cube" and a chest to it and started mining.
It said ca 2.200 ores to mine.

After half of the time I had to repower the cube and added upgrades:
- 8x Energy Upgrade
- 2x Speed Upgrade
- 1x anchor upgrade

It went well until ther were no ores to find anymore.

After that I replaced the miner. While replacing server restarted (miner in my inventory).

After restart I set the miner to another place and connected transportation Pipes with a bunch of Bin to it to sort the items. I started and disconnected.

one hour later server gave me the error.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Mekanism version

10.3.6

### Other relevant versions

Don't know if relevant but I've installed "Mekanismm: Tools 10.3.6" and "Mekanism: Generators 10.3.6"

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://github.com/mekanism/Mekanism/files/10689743/crash-2023-02-08_17.11.10-server.txt

**Comment by pupnewfster** [comment]
Update Mekanism to 10.3.8

**Comment by BlacKHaraZ** [comment]
I'm very sorry.

Now I've seen that there is v10.3.8 since yesterday. xD

It works. thx
