### ISSUE TITLE
Redstone input does not turn off laser amplifier

### ISSUE THREAD

**Issue by dannysmc95** [mekanism/Mekanism#7734]
### Issue description

Custom modpack in use, I have setup a fusion reactor as suggested by various videos, and as I am coming to ignite the reactor, I put the amplifier facing the laser focus matrix, and start 4 lasers on each side and a lever at the back, turning on the power instantly triggers the laser, toggling the lever makes no difference, the amplifier will consistently fire.

The whole thing is done in creative, and it has the fuels required, everything is there, but the laser won't stop firing to charge and send one burst of energy, so it's impossible to ignite the reactor.

### Steps to reproduce

Make a fusion reactor.
Setup as shown below:

![image](https://user-images.githubusercontent.com/5339861/218112639-06bdd1df-ffc0-4ca3-8082-ca0a8e440fb8.png)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Mekanism version

10.3.8 (Latest)

**Comment by SirEndii** [comment]
The lever needs to be placed next to the laser.
Redstone does not transfer over corners

**Comment by SirEndii** [comment]
Have you set the redstone mode of the laser amplifier?
You can see that in the lower right corner of the gui

**Comment by dannysmc95** [comment]
> Have you set the redstone mode of the laser amplifier? You can see that in the lower right corner of the gui

Oh you're amazing, I tried it earlier and it didn't work, so must of done it wrong, yeah it's fine now, thank you!
