### ISSUE TITLE
Multiplying Items with the personal chest

### ISSUE THREAD

**Issue by Dnx4** [mekanism/Mekanism#7738]
### Issue description

You can basically multiply any item you want just doing this with the personal chest.

### Steps to reproduce

1. Put the personal chest in the hotbar
2. Open the personal chest
3. Put the item you want to multiply inside the chest
4. With the mouse over the item, click the respective number of the personal chest in the hotbar
5. With the personal chest inside itself bring it back to your inventory
6. Close the chest
7. Open the chest, and be happy

### Minecraft version

1.16.4/1.16.5

### Forge version

32.6.9

### Mekanism version

10.0.19

**Comment by pupnewfster** [comment]
1. Your forge version is not valid
2. What MC version/mek version are you using as the mekanism version you are listing is for Minecraft 1.19.2 so given you say you are using 1.18 or older at least one of those two things is not correct
3. I am unable to reproduce this in 1.19 (and I am pretty sure my fix goes back to 1.18 or even 1.16) so my best guess is you may have another mod installed that is ignoring various checks on the slots. Are you able to reproduce this with just Mekanism?

**Comment by Dnx4** [comment]
> 1. Your forge version is not valid
> 
>     2. What MC version/mek version are you using as the mekanism version you are listing is for Minecraft 1.19.2 so given you say you are using 1.18 or older at least one of those two things is not correct
> 
>     3. I am unable to reproduce this in 1.19 (and I am pretty sure my fix goes back to 1.18 or even 1.16) so my best guess is you may have another mod installed that is ignoring various checks on the slots. Are you able to reproduce this with just Mekanism?

I'll try

**Comment by Dnx4** [comment]
> 1. Your forge version is not valid
> 
>     2. What MC version/mek version are you using as the mekanism version you are listing is for Minecraft 1.19.2 so given you say you are using 1.18 or older at least one of those two things is not correct
> 
>     3. I am unable to reproduce this in 1.19 (and I am pretty sure my fix goes back to 1.18 or even 1.16) so my best guess is you may have another mod installed that is ignoring various checks on the slots. Are you able to reproduce this with just Mekanism?

it worked with only him

**Comment by Dnx4** [comment]
![2023-02-20_15 16 28](https://user-images.githubusercontent.com/125909731/220176922-6b25b784-5a8e-40c7-a47c-fa5f82c3674e.png)
![2023-02-20_15 16 35](https://user-images.githubusercontent.com/125909731/220176927-e2b5c2d2-c182-49ac-a967-9b3ef71629dc.png)
![2023-02-20_15 16 39](https://user-images.githubusercontent.com/125909731/220176930-3820eb8b-aead-44b0-9d92-e75bf839321c.png)
![2023-02-20_15 16 46](https://user-images.githubusercontent.com/125909731/220176933-6523b600-e0c4-4056-b299-a2f78cbb7eab.png)

**Comment by Dnx4** [comment]
already fixed, thanks

Em seg, 20 de fev de 2023 14:48, Sara Freimer ***@***.***>
escreveu:
