### ISSUE TITLE
Digital Miner crash in Direwolf20 1.19 Modpack

### ISSUE THREAD

**Issue by falconraptor** [mekanism/Mekanism#7742]
### Issue description

Digital miner (Energy, Anchor) causes crash in base when mining `forge:ores`. 
[latest.log](https://github.com/mekanism/Mekanism/files/10798263/latest.log)
[crash-2023-02-20_23.35.30-server.txt](https://github.com/mekanism/Mekanism/files/10798265/crash-2023-02-20_23.35.30-server.txt)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.3

### Mekanism version

10.3.7

### Other relevant versions

Direwolf20 1.19 Modpack: 1.3.2

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://github.com/mekanism/Mekanism/files/10798265/crash-2023-02-20_23.35.30-server.txt

**Comment by pupnewfster** [comment]
Update to 10.3.8
