### ISSUE TITLE
Electrolytic separator has no config menu on server 

### ISSUE THREAD

**Issue by Godx-sys** [mekanism/Mekanism#7745]
### Issue description

![2023-02-26_12 31 24](https://user-images.githubusercontent.com/83438336/221426843-2841e958-f528-4dee-a3d9-c763dd6dfd49.png)

As you can see from this photo I'm on my server and the separator has not configs I'm trying to use it with x-net but without config I cannot push or pull or anything of that sort please let me know what you think is happening.

### Steps to reproduce

no idea...

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

1.12.2 latest

### Mekanism version

Current Dev Branch (Manually Compiled)

**Comment by pupnewfster** [comment]
Correct 1.12 didn't support side config for many machines and was strictly sided.
