### ISSUE TITLE
Cables using their "default" variant without Immersive Protal

### ISSUE THREAD

**Issue by Nova-22** [mekanism/Mekanism#7746]
### Issue description

Hi there, I have the visual cable problem, I looked at the issue.. but all of them talk about Immersive Portal but I don't have it on my modpack :/ 
![image](https://user-images.githubusercontent.com/94980144/221442613-307f190f-3074-4ac5-9bb3-079539701c81.png)
Any idea?

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.2.1

### Mekanism version

Older

### Other relevant versions

1.18.2 - 10.2.5.465

**Comment by SirEndii** [comment]
Could be a issue with rubidium

**Comment by pupnewfster** [comment]
Rubidium seems to occasionally cause this as well (though forcing a chunk reload with F3+A seems to actually fix it with rubidium). Either way it isn't something on our end
