### ISSUE TITLE
Could not find specified recipe

### ISSUE THREAD

**Issue by WFPhantom** [mekanism/Mekanism#7750]
### Issue description

[Server thread/WARN] [me.co.Mekanism/]: Received transfer request from: ServerPlayer['WFPhantom'/50953, l='ServerLevel[world]', x=-221.73, y=63.00, z=540.27], but could not find specified recipe.

Some recipes cannot be performed in a QIO but can be performed in a crafting table. Currently trying to craft a Melee Turtle from CC and it doesn't work. I have also gotten reports from people playing that it also happens with some Botania and Ars Nouveau recipes but I cannot confirm that. It MIGHT have something to do with unstackable items but I'm not sure.

### Steps to reproduce

1. Set up a QIO
2. Open the QIO with the Portable Dashboard
3. Try to craft something via JEI
4. Error

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.5

### Mekanism version

10.3.8 (Latest)

**Comment by WFPhantom** [comment]
Got another one while trying to make a rotary condensentrator this one is different
Received transfer request from: ServerPlayer['WFPhantom'/264618, l='ServerLevel[world]', x=-156.43, y=65.00, z=566.17], but source items aren't valid for the requested recipe: mekanism:rotary_condensentrator.

**Comment by pupnewfster** [comment]
Wait do the recipes work but just don't support transferring via JEI or are the recipes not working at all? Given just processed the fact hat given it is transfer request that is the JEI thing, so it could be that some stuff isn't matching properly when the server validates the client sent a valid request. (Also I presume the tank/things with nbt are in your inventory? or are they in the QIO as that might cause different things.

**Comment by WFPhantom** [comment]
Tank was in my inventory when i tested having it in the QIO produces the same error. The recipe doesn't work at all with the tank full of lava.

**Comment by pupnewfster** [comment]
Interesting, I would expect the recipe to function but for the transferring automatically with JEI to just be what doesn't quite work, but when moving the item into the crafting window manually I would think it should work, Either way I will try to look into it some for the next version.
