### ISSUE TITLE
Electrolytic Separator power usage doesn't decrease with energy upgrades

### ISSUE THREAD

**Issue by DudeDnB** [mekanism/Mekanism#7752]
### Issue description

The electrolytic separator power usage doesn't decrease after adding energy upgrades.

### Steps to reproduce

1. Place electrolytic separator
2. Power up the machine
3. Provide any ingredient to separate (water, brine, etc.)
4. Review the power usage while it is working (default power usage with no speed upgrades is 200 J/t)
5. Add energy upgrades
6. Review power usage again (power usage remains the same no matter how many energy upgrades are added)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.6

### Mekanism version

10.3.8 (Latest)

### Other relevant versions

AllTheMods 8 version 1.0.13

**Comment by DudeDnB** [comment]
I searched for this issue but didn't find anything. What did I miss?

**Comment by pupnewfster** [comment]
#7361, #7533, #7503, #7426, #7257, #6885, #6779, #6729, etc etc. That is just from the first page or two of searching `separator` in the issues tab.

From our FAQ on discord:

**Q**: *Why do energy upgrades not make the electrolytic separator use less energy?*
**A**: There are a few machines where speed/energy upgrades behave a bit differently, the one that people notice/ask about the most is the electrolytic separator. A big reason as to why the separator doesn't reduce its power consumption with energy upgrades is to prevent infinite power looping by separating water into oxygen and hydrogen and then burning hydrogen in the gas burning generator (we already have it get separated at 100% efficiency unlike real life where it is quite a bit lower). For specifics to how energy and speed upgrades effect the electrolytic separator see: https://discord.com/channels/554379889122213888/560583846509281280/799018624740229170

**Comment by DudeDnB** [comment]
Thanks, I had only searched through open issues.
