### ISSUE TITLE
Broken textures on most of mekanism pipes

### ISSUE THREAD

**Issue by Branjoman** [mekanism/Mekanism#7753]
### Issue description

Central connection points on most of the Mekansim pipes are not displaying their proper texture, and instead displaying a broken texture atlas. This affects all pipes except their ultimate versions, the advanced logistical transporter, and the restrictive transporter.

Image of issue: https://i.imgur.com/63YAD4Y.jpg

So far I haven't been able to narrow down which other mod is causing this issue (as it does not occur with mekanism alone), however I have confirmed that Rubidium is not the cause of the issue.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.6

### Mekanism version

10.3.8 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/KipjnKf

**Comment by pupnewfster** [comment]
Remove rubidium this is caused by something they do that breaks part of the texture atlas

**Comment by Branjoman** [comment]
See I thought it would be Rubidium causing the issue too, so I explicitly tested it in an instance with just Mekanism and Rubidium, and the issue didn't happen, so clearly there's something else going on here.

**Comment by pupnewfster** [comment]
Yes it has to do with what part of the atlas rubidium breaks. With just Mekanism none of the assets happen to fall into that part of the atlas and odds are it is some vanilla stuff that end up there.
