### ISSUE TITLE
[Crash] The game crashed whilst rendering overlay Error: net.minecraftforge.fml.ModLoadingException

### ISSUE THREAD

**Issue by DeclineD-Com-AMXX** [mekanism/Mekanism#7756]
### Issue description

The game crashed whilst rendering overlay Error: net.minecraftforge.fml.ModLoadingException: Mekanism (mekanism) encountered an error during the done event phase

ERROR: 0:43: error(#162) Wrong operand types no operation ':' exists that takes a left-hand operand of type 'const int' and a right operand of type 'float' (or there is no acceptable conversion)

I've researched the problem hoping it would be my fault and tried everything but i can't get past this.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.6

### Mekanism version

Current Dev Branch (Manually Compiled)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/Z18UZgJB

**Comment by toddlersizedsharkcage** [comment]
Does it happen without Rubidium?

**Comment by DeclineD-Com-AMXX** [comment]
With Rubidium.

**Comment by DeclineD-Com-AMXX** [comment]
It seems that for this modpack i use, ALL THE MODS 8, it uses Rubidium to render something .. I tried with simple optifine and what i said above and either crash with errors or crash with error code 1 which can't be.

**Comment by DeclineD-Com-AMXX** [comment]
It could be (https://github.com/mekanism/Mekanism/blob/8dc9dfd2bbcde2a1413d5dc599c84277dc8bce52/src/main/java/mekanism/client/ClientTickHandler.java#L301)

**Comment by pupnewfster** [comment]
It probably has something to do with this line: https://github.com/mekanism/Mekanism/blob/1.19.x/src/main/resources/assets/mekanism/shaders/core/rendertype_mekasuit.fsh#L44 but I am guessing it is due to some other mod installed doing weird things to loading shaders. Does this crash happen when you are *only* using Mekanism?

**Comment by DeclineD-Com-AMXX** [comment]
Never tried Mekanism alone. I was using this modpack 'All the mods 8' and to some people it works but as the problem occurs when probably other mods come in (i will test tommorow since it's 3am here) i thought thst you should add that 'compatibility' so we can use this mod with many other mods. As i said idk for sure.

**Comment by paplaukes** [comment]
I'm getting this as well as part of Enigmatica 9 (version 1.4.2) with Mekanism-1.19.2-10.3.8.477 / Forge 43.2.4,
I've tested it on Enigmatica 9 with/without optifine/rubidium.
I've tested it on a fresh 1.19.2 install with just Forge (43.2.0, 43.2.4, 43.2.14) and Mekanism (with/without generators) and it still happens. Fresh install without mekanism is able to load.

https://pastebin.com/kVANtMX8

This is on ATI Mobility Radeon series 4500, so at least that's a pattern. No ATI drivers on win10 for this, just whatever Microsoft supplies.

**Comment by pupnewfster** [comment]
Hmm I will talk with some people about this, I wonder if maybe it is a gl implementation specific thing and has to do with the hardware you are on, and if so how to best maybe get around it.

**Comment by paplaukes** [comment]
Thank you for looking into this. I realize it's an edge case.
I can test something if needed.

**Comment by paplaukes** [comment]
Thank you! I edited it in, works.
