### ISSUE TITLE
Mekanism Doesn't support Oredict selection

### ISSUE THREAD

**Issue by Speiger** [mekanism/Mekanism#7758]
### Issue description

Immersive Engineering has shown me recipes where you can make storage results choseable by the player.
By simply making the Center piece of the Storage recipe hardcoded to the mod this would allow you to choose which output you want.

Personally I think this should be a standard.

Reference issue to show what is wanted. The top recipe shows it clearly
https://github.com/TinyModularThings/IC2Classic/issues/568

### Steps to reproduce

Try craft any ore storage block from any mod and try to get the result you want.

### Minecraft version

1.19.2 (Latest)

### Forge version

Any

### Mekanism version

Current Dev Branch (Manually Compiled)

Small side note:
Since its a feature request.
It only requires a small recipe change.

**Comment by a-droid-boop** [comment]
Here is the feature request branch, you posted a feature request in the incorrect location.
https://github.com/mekanism/Mekanism-Feature-Requests

**Comment by pupnewfster** [comment]
Closing in favor of the more properly located issue https://github.com/mekanism/Mekanism-Feature-Requests/issues/525
