### ISSUE TITLE
Cardboard Box overwrites Dank Storage inventory with player inventory

### ISSUE THREAD

**Issue by ninjachicken1** [mekanism/Mekanism#7760]
### Issue description

This is more or less copy/pasted from [the issue I posted for Dank Storage](https://github.com/Tfarcenim/Dank-Storage/issues/199), because I don't know which mod the issue lies in.

I was reorganising my storage with a Mekanism Cardboard Box, and put my Dank Dock (containing a Dank 7, which in turn contained a 16x16 block quarry's worth of materials) in it out of habit. When I put it down where I wanted it the contents were gone, and it contained a copy of my own inventory. I then loaded a backup of my world, went to bed and made the exact same mistake the next morning, proving both that the issue is replicable and that I'm a dumbass. I didn't investigate further to figure out whether I'd duplicated my inventory or was accessing my inventory through the dock.

I encountered this while playing FTB University 1.16 v1.8.0.

### Steps to reproduce

In FTB University 1.16 v1.8.0:

1. Put your Dank in a Dock
2. Put your Dock in a Box
3. Then you open the Box

And that's the way you do it! It's a Dock in a Box!

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

36.2.35

### Mekanism version

Older

**Comment by pupnewfster** [comment]
If I had to guess odds are they don't save all their data to the block entity for the dock which there is nothing we can really do about other than recommend they put the block/tile in one of the tags to prevent picking them up.

Block tags:
- `#forge:relocation_not_supported`
Block Entity tags:
- `#forge:immovable`
- `#forge:relocation_not_supported`
