### ISSUE TITLE
No exp

### ISSUE THREAD

**Issue by Ashwinaaaaaaahdt** [mekanism/Mekanism#7763]
### Issue description

An energized smelter doesn't produce any exp in smelting 
But regular furnaces can produce exp in smelting

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

36

### Mekanism version 
V10

**Comment by Ashwinaaaaaaahdt** [comment]
> This isn't a bug, and while yes I do have plans to eventually try to make some sort of xp upgrade for machines it isn't a priority nor is it thought of as a bug fix.

And can you make it double or triple or 4times or 8 times card?

**Comment by pupnewfster** [comment]
No
