### ISSUE TITLE
[1.12.2]Why won't my wires be linked Industrial Upgrade machines.

### ISSUE THREAD

**Issue by chenming0v0** [mekanism/Mekanism#7767]
### Issue description

[1.12.2]The cable cannot be linked to Industrial Upgrade machines！！！
![image](https://user-images.githubusercontent.com/122023652/230722343-550312ee-c2b3-45fd-9247-771903a51d14.png)

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

14.23.5.2859

### Mekanism version

Older

**Comment by pupnewfster** [comment]
No idea, guessing there is something that is wrong with their handler given it visually is connecting, but we also no longer are developing for 1.12
