### ISSUE TITLE
Error 255 when playing in curse forge on macbook air m2 macos macOS monterey

### ISSUE THREAD

**Issue by Sunlord330** [mekanism/Mekanism#7768]
### Issue description

I am assembling a tech modpack  on 1.7.10 and tried putting Mekanism in it and it gave me a 255 error. I then tried tuning off all of the mods besides Mekanism the same thing happened.

### Steps to reproduce

1) buy a 2022 m2 macbook air
2) download curseforge and install Mekanism on 1.7.10
3) get error

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

10.13.4.1614

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Sunlord330/e81b88184c7ee186576d93fb9bb115ea#file-crash-2023-04-08_15-37-53-client-txt

**Comment by SirEndii** [comment]
You need multipart installed. 
This should be the one you need to install https://www.curseforge.com/minecraft/mc-mods/forge-multi-part/files

**Comment by Sunlord330** [comment]
> You need multipart installed. This should be the one you need to install https://www.curseforge.com/minecraft/mc-mods/forge-multi-part/files

thanks i will try this soon
