### ISSUE TITLE
texture advanced solar pannel

### ISSUE THREAD

**Issue by EReichmann** [mekanism/Mekanism#7772]
### Issue description

today i downloaded the newest version 1.19.2 -10.3.8 and i couldn't see the texture of the solar pannels. Would be nice if u can fix that somehow

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.1

### Mekanism version

10.3.8 (Latest)

**Comment by pupnewfster** [comment]
Are you using any other mods that are known to break rendering like optifine or rubidium? And if so does the texture render fine without them?
