### ISSUE TITLE
Issues with the diving suit and status effects.

### ISSUE THREAD

**Issue by Anewri** [mekanism/Mekanism#7773]
### Issue description

If you have the diving suit supplying air, the status effects deplete quickly. This applies to effects acquired before and after activating the air vent.

### Steps to reproduce

Does not apply

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.0

### Mekanism version

10.3.8 (Latest)

### Other relevant versions

Does not apply

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

Does not apply

**Comment by pupnewfster** [comment]
That is an intended feature

**Comment by Anewri** [comment]
You're telling me this is intentional, for what purpose if not more of a nuisance to the player.

**Comment by pupnewfster** [comment]
The main use case is for preventing negative effects and the like as it prevents magic splash potions and makes things go away quicker by replacing what you are breathing quicker. Yes it also removes positive effects but that is because unlike the MekaSuit it doesn't provide as refined control.

**Comment by Anewri** [comment]
Ok, I understand, this costume would be the most basic, therefore it has this drawback.
