### ISSUE TITLE
Waste Barrel Config

### ISSUE THREAD

**Issue by RulsOfficial** [mekanism/Mekanism#7774]
### Issue description

Is there any config for making the radioactive waste barrels obtainable (with gases in it) without having to copy the nbt in creative?
I think they will be obtainble with silktouch, but actually they aren't, is there any config for mining the barrels without release the contents ?

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.7

### Mekanism version

10.3.8 (Latest)

**Comment by pupnewfster** [comment]
No and it is not intended to be possible. In theory if you really wanted for a recipe you can probably spawn one in using similar syntax to the one for chemical tanks and specifying what chemical is in them. The whole point is to make it so you can't pick up the contents as then it can be trivially just instantly deleted.
