### ISSUE TITLE
Solar Neutron Activator not turning on during daylight in a specific chunk.

### ISSUE THREAD

**Issue by Data-Shark1** [mekanism/Mekanism#7775]
### Issue description

I have a SNA in a chunk, along with other machines for waste processing, a fission reactor, turbine, and SPS. The SNA is accepting waste from the reactor, but even during daylight, no rain, with direct sunlight above it, it will not turn on. I can confirm this using computercraft's computer by simply using the canSeeSun() function. If I put down an SNA in any spot in the chunk, the function returns false. If I put it anywhere else (during daytime with direct sunlight) outside the chunk, the function returns true, and the SNA functions properly. Modpack is ATM8, mutliplayer.

### Steps to reproduce

1. Have fission reactor, turbine, and SPS active in 1 chunk
2. pipe waste into SNA, located in same chunk, ensure SNA has direct view of sunlight during daytime
3. place computercraft computer in front of SNA
4. enter computer and type lua, hit enter
5. type `x=peripheral.wrap("back")`, hit enter
6. type `x.canSeeSun()`, hit enter

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.6

### Mekanism version

10.3.8 (Latest)

**Comment by pupnewfster** [comment]
Sounds like #7754 which the user indicated doesn't actually have to do with Mekanism
