### ISSUE TITLE
PneumaticCraft lamp will prevent to build mekanism multi-block structure

### ISSUE THREAD

**Issue by zyxkad** [mekanism/Mekanism#7779]
### Issue description

If I try to build a mekanism multi-block structure (e.g. thermal evaporation tower) near a active pneumatic lamp, it won't assemble cause some block placed wrong.

It actually is because pneumatic lamp will place some light source block to light the area, but mekanism only check air block.

(Not sure if other mod that have large area lighter will cause this problem too)

### Steps to reproduce

1. Install pneumaticCraft
2. Place a pnC lamp, active it
3. Build a thermal tower next to it
4. The tower won't assemble cause there are some invalid blocks

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.6

### Mekanism version

10.3.8 (Latest)

### Other relevant versions

pneumaticCraft 4.3.3-22

**Comment by pupnewfster** [comment]
There is nothing that can be done about this other than them marking that "ghost" light block as being air so that other blocks can go there and other mods can properly treat it as being equivalent to air.

**Comment by desht** [comment]
For the record, Kerosene Lamp light blocks extend `AirBlock` but apparently it's not enough to do that. Looks like they also need to be marked as `.air()` in their block properties on construction.

**Comment by pupnewfster** [comment]
Yeah, Mojang changed that at some point for how air is checked ([up until recently](https://github.com/MinecraftForge/MinecraftForge/pull/9440/files#diff-4160c09ca6daa65cc4314e5a700b4d411402774515601b0fae927bea395d4203R495)) forge's own dummy blocks had the same issue for not being treated as air.
