### ISSUE TITLE
Portable QIO Crafting | Does not recognize recipe

### ISSUE THREAD

**Issue by CodeLabsCEO** [mekanism/Mekanism#7780]
### Issue description

![image](https://user-images.githubusercontent.com/123798868/235266385-177eb1f3-8454-401e-9708-bcdaf3a69316.png)
Making white barrels using the QIO crafting grid does not work as i am showcasing in the photos.
![image](https://user-images.githubusercontent.com/123798868/235266524-61203a3b-ac3d-44e6-9142-a83f2840d883.png)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.8

### Mekanism version

10.3.8 (Latest)

**Comment by pupnewfster** [comment]
Which mod is adding those colored barrels so that I can test with it and see if I can track down the issue?

**Comment by Pedrinhoreidelas** [comment]
This bug still happens in newer versions. It happened to me too with the mekanism recipes, and you can dupe items or if you try to use JEi to move the items to the QIO crafting grid, some items will be destroyed (just got disappeared).

like to dupe, just put some itens to craft a block, like steel, and remove 1 ingot from the recipe, and it still create the recipe without using the itens
![mek1](https://github.com/mekanism/Mekanism/assets/111616543/9236c422-138e-4faf-a1e1-283444ccaa0a)
![mek2](https://github.com/mekanism/Mekanism/assets/111616543/784eb253-3537-49f1-927c-87df29242f94)
![mek3](https://github.com/mekanism/Mekanism/assets/111616543/a0789b30-db2e-4dd2-9a03-2979856fa4a0)
![mek4](https://github.com/mekanism/Mekanism/assets/111616543/50c840eb-2e51-4b7a-a673-e723a01df155)
