### ISSUE TITLE
upgrades are glitched

### ISSUE THREAD

**Issue by GabkoMC** [mekanism/Mekanism#7784]
### Issue description

i crafted  two speed and two energy upgrades for my machines but they stacked to 64, being unefective because they were stacking to 8 in my last save and i an confused
![obrázok](https://user-images.githubusercontent.com/125188781/236616686-338cec4a-8b26-48b8-b903-8f93dc87dd2b.png)

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.2.0

### Mekanism version

Current Dev Branch (Manually Compiled)

**Comment by pupnewfster** [comment]
Report/ask the person who made the modpack you are playing. If I had to guess they used other mods to change the max stack size of upgrades as that is not a feature we provide.
