### ISSUE TITLE
CC:Tweaked generic fluid tanks api disappeared

### ISSUE THREAD

**Issue by zyxkad** [mekanism/Mekanism#7786]
### Issue description

The generate fluid storage API that list in <https://tweaked.cc/generic_peripheral/fluid_storage.html> is not in mekanism's tank.

https://github.com/cc-tweaked/CC-Tweaked/issues/1435

### Steps to reproduce

1. install mekanism and CC:tweaked with forge
2. place a mekanism tank next to it
3. After `peripheral.wrap`, the generic api wasn't in the tank

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.8

### Mekanism version

10.3.8.477

### Other relevant versions

- CC:Tweaked 1.101.2

**Comment by xXjojojXx** [comment]
same problem

**Comment by thiakil** [comment]
Based on the author's response, this is expected behaviour - we add our own methods to a peripheral which can get tank info

**Comment by SirEndii** [comment]
This bug will remain until [this](https://github.com/cc-tweaked/CC-Tweaked/discussions/1093) issue gets addressed

Or mekanism introduces a plugin peripheral system like [UPW](https://github.com/SirEdvin/UnlimitedPeripheralWorks/blob/1.20/projects/core/src/main/kotlin/site/siredvin/peripheralworks/computercraft/plugins/specific/SpecificPluginProviders.kt#L15) or AP

**Comment by thiakil** [comment]
I'm happy to add a compatible tank info method, but personally (not an official Mekanism opinion) I don't like the idea of pushing / pulling fluids via a modem - it doesn't make sense

**Comment by SirEndii** [comment]
Yeah, it does not 
But CC was never intended to be realistic

**Comment by pupnewfster** [comment]
Yeah, the main reason I didn't include any transfer styles hooks is that I didn't really see a use case nor even how it would logically work.

**Comment by zyxkad** [comment]
> I'm happy to add a compatible tank info method, but personally (not an official Mekanism opinion) I don't like the idea of pushing / pulling fluids via a modem - it doesn't make sense

It doesn't makes sense that meka pipe can pull/push fluids too, I don't see the construct difference between cc modem and meka pipe
