### ISSUE TITLE
Cant get coal from energized smelter to metallurgic infuser

### ISSUE THREAD

**Issue by Pers0on** [mekanism/Mekanism#7787]
### Issue description

I'm playing mechanical mastery and trying to automate steel production but I can't get the coal from an energized smelter to a metallurgic infuser

### Steps to reproduce

1. Energized smelter with basic logistical transporter on top and an EMC link set to coal ore on top of that
2. Set a basic logistical transporter from any side leading into a metallurgic infuser with iron in it
3. Make sure everything is powered

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

224.1.1

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Are the sides of the smelter configured to auto eject or are the transporters set to pull?

**Comment by Pers0on** [comment]
> Are the sides of the smelter configured to auto eject or are the transporters set to pull?

Yeah, I made sure to check that the input and output was right

**Comment by Pers0on** [comment]
![2023-05-13_11 33 33](https://github.com/mekanism/Mekanism/assets/133517159/8ce18013-e6f7-4520-88c3-8bef246f6ece)
set-up I'm using for steel production

**Comment by pupnewfster** [comment]
And to confirm the infusers are set to "extra" and not "input" right? Given the infuse type item is meant to go into the extra slot rather than the main input/processing slot

**Comment by Pers0on** [comment]
> And to confirm the infusers are set to "extra" and not "input" right? Given the infuse type item is meant to go into the extra slot rather than the main input/processing slot

Thought I had it set but I guess when I was rearranging everything I forgot to re-set it

**Comment by pupnewfster** [comment]
Is it working properly now?

**Comment by Pers0on** [comment]
> Is it working properly now?


it was working for awhile but now the smelter on the right wont output, the left one is working fine and i have them both set-up the same

**Comment by HonkerBonker** [comment]
You know , i had similar issue where infuser configured to accept items to infuse from all sides (yellow sqares on all sides in infuser interface) was refused to get coal from mekanism pipe. Pipe was transporting coal fine if it was to to chest. A hopper was transporting coal to infuse in infuser fine. AE2 export bus was transporting coal into infuser fine. But not logisticcal transporter , mekanism pipe.
   I made fresh instance , just makanism , jei , ae2 to test that without other mods influenc - and mekanism pipe worked fine for tranporting infuse item in infuser. Then i loaded instance with all the mods i was using previously but disabled optifine( to test if it was optifine maybe) , replaced previous infuser with new one , set config to accept item to infuse (yellow sqare in interface) - and mekanism pipe transported coal fine. Then re enabled optifine - still works. So it works now and i cant replicate it or figure out why it was not working. Was it some weird setting on that infuser ? Complicated interaction with optifine ? I  did missed something ? But it did happened for some time , infuser not accepted items from mekanism pipes
 ( mekanism smelter i tested worked with mek pipes fine all the time btw).
 Strange it all is.
PS minecraft 1.18.2 , forge 40.2.1 , mekanism 10.2.5 (latest for 1.18.2 as of now)
