### ISSUE TITLE
1.19 Electrolytic Separator doesn't output gases according to configuration

### ISSUE THREAD

**Issue by TronWoWGamer** [mekanism/Mekanism#7789]
### Issue description

I don't know if this is intended behavior, but seems like a bug to me.

Set the right side to output hydrogen and it doesn't work.  Set the left side to output hydrogen and it's fine.  I know the internal tanks are Hydrogen on the left and Oxygen on the right, but that's not always where I want my tanks.  If I put my tank on the right and try to have it output hydrogen into that tank, it sits there forever and does nothing and the pressurized tubes always say empty.  All I have to do it swap sides and it works properly.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.6

### Mekanism version

10.3.7

**Comment by pupnewfster** [comment]
When changing the side config did you change the side config for gases or for items?
