### ISSUE TITLE
Digital Miner does not mine in Other dimension

### ISSUE THREAD

**Issue by thedoctorking** [mekanism/Mekanism#7791]
### Issue description

I set up digital miner in the Other dimension from the Allthemodium mod. It sets up correctly, shows that it is receiving power through an quantum entangler. I set up filters to tell it to mine the unwanted blocks (Ancient Stone and Deepslate in this mod). Push the start button, miner shows a large number of blocks to mine, but after a few seconds the number to mine drops to zero and the panels on the front of the block go dark. 

### Steps to reproduce

1. Place Digital Miner in the Other dimension, 
2. Attach quantum entangloporters for power and item transmission
3. Set up filters to mine Ancient Stone and Deepslate
4. Push start
5. Wat a few seconds

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.11

### Mekanism version

10.3.8 (Latest)

### Other relevant versions

Allthemodium 2.1.6-1.19.2-43.1.1

**Comment by thedoctorking** [comment]
No, they are loaded through FTB utilities. And the GUI still shows that the device has plenty of power in it.

**Comment by thedoctorking** [comment]
Tried with RfTools Builder and it didn't work either so I suspect this is an issue with Allthemodium mod instead of Mekanism.

**Comment by pupnewfster** [comment]
Yeah guessing with that piece of information that they explicitly don't allow `FakePlayer`s to mine in the dimension as given it shows a large to mine number before zeroing out it sounds a lot like when the miner checks for permission to break blocks and is unable to.

**Comment by SirEndii** [comment]
They indeed block Fake Players from breaking stuff in their dimension or their ores
