### ISSUE TITLE
[1.19.2] Dupe with bin and any bag

### ISSUE THREAD

**Issue by bigenergy** [mekanism/Mekanism#7798]
### Issue description

bin stacks non-stackable items and allows you to dupe items

### Steps to reproduce

See video: https://youtu.be/SWP5jTvUdWQ
In this example, we can dupe with a bag of supplementaries

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.6

### Mekanism version

10.3.8 (Latest)

**Comment by pupnewfster** [comment]
Ah I see, it specifically has to do with the empty mode on configurators not respecting the max stack size of items. Thanks for the report.
