### ISSUE TITLE
MekanismTools Armor piece causes renderer crash on all clients in range

### ISSUE THREAD

**Issue by Spid3rdr4gon** [mekanism/Mekanism#7799]
### Issue description

Random simultanious crashes on multiple clients related to an issue with a type of mekanism tools armor.

### Steps to reproduce

1. Playing the game for a long while.
It seems to have something to do with an armor piece of mekanism tools spawning on a mob. so it is probably some type of armor needing to be displayed for recreating the crash.

The server was fine but all the clients crashed.
After a short while the crashes stopped happening. Probably because the mob wearing the bugged armor piece despawned.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.2.4

### Mekanism version

Older

### Other relevant versions

Occulus-1.5.2 and Rubidium-0.6.5 Renderer is used so it may be a compatibility issue.

There is a newer version of Occulus avaliable which might fix it but that is to be tested.

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/LYuux2CT

**Comment by pupnewfster** [comment]
Rotten creatures is using some vanilla method instead of the forge version for purposes of getting armor resource location report it to them
