### ISSUE TITLE
Metallergic Infuser impossible to atuomate

### ISSUE THREAD

**Issue by thatmaxplayle** [mekanism/Mekanism#7801]
### Issue description

I have this setup below, using a small AE2 subnet in attempt to automate the Metalergic Infuser, however it will not accept any input (or infuse items) from the AE2 export busses.

This is the same if I'm using Logistical Transporters. 

![image](https://github.com/mekanism/Mekanism/assets/63079841/a6f5fce4-3aac-4a9c-91cc-eb13dac84bcb)

![image](https://github.com/mekanism/Mekanism/assets/63079841/21caa0cc-fa0a-476c-8b3b-33847941d5fe)

### Steps to reproduce

1. Create a metallergic infuser
2. Hook up any sort of automated item input device to multiple sides of the block.
3. Try to pump in Osmium and Redstone (those are the ones I tested) to create a Basic Control Circuit
4. The machine will **refuse** to accept the input.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.14

### Mekanism version

10.3.8

**Comment by trunksbomb** [comment]
Show the content of the chest and the GUI of the export buses and the storage Bus.

**Comment by pupnewfster** [comment]
Given you are on 10.3.8 you also could hook a logistical transporter to two sides of the infuser, set one to extra and one to input and then put the AE2 connection on the transporter instead of on the machine itself. That or use the system most people do where you just keep a different infuser for each type filled with the enriched variant.

**Comment by trunksbomb** [comment]
They claim it happens with transporters too. I think there is something fundamentally wrong with their setup and/or how they think it works.

**Comment by RedIODev** [comment]
> > Given you are on 10.3.8 you also could hook a logistical transporter to two sides of the infuser, set one to extra and one to input and then put the AE2 connection on the transporter instead of on the machine itself. That or use the system most people do where you just keep a different infuser for each type filled with the enriched variant.
> 
> Think I'm going to go with keeping a infuser for each type full of the given infuse type, given that's what I've done previously and just wanted to try automating it "properly". I've tried using logistical transporters too, no luck. Oh well! Thanks for the guidance anyway.

With the bridge mod applied-mekanistics you can store chemicals in applied energistics. This way you can setup a metalergic infuser that is connected to a pattern provider directly for items and via 2 pressurited pipes (puting the one on the metalergic infuzer in extract mode). Now you can make a pattern that teaches the me system to produce infused types. In the second step you simply place a infusing factory next to a pattern provider and configure the touching side Item in/out and infused types in. Then you can make a pattern that uses the input material and the infused type as input (you can use a chemical tank to place the infused type from the me system into the pattern input slot and ajust the amount with middle click)
Et voila the ME system is crafting with the metalergic infuser. 

Sadly this currenly doesn't work with the osmium compressor, as the gas config on it is input only, making osmium gas unobtainable in survival. I will file a bug/feature request to add gas out to the osmium compressor or another way to produce osmium gas.
