### ISSUE TITLE
Purification chamber only producing two clumps instead of three

### ISSUE THREAD

**Issue by weebykun** [mekanism/Mekanism#7803]
### Issue description

Purification chamber only producing two clumps instead of three. Not sure if this has been changed since older versions.

### Steps to reproduce

Put iron into purification chamber
Purification produces two clumps of iron instead of three

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.8

### Mekanism version

10.3.8

### Other relevant versions

Using modpack TNP Limitless 6-LL6

**Comment by SirEndii** [comment]
This is intended
Raw iron produces two, normal iron ore should produce three

**Comment by weebykun** [comment]
Makes sense lol thank you for the clarification!

**Comment by Leah96xxx** [comment]
So basically its still designed for pre-1.17?
