### ISSUE TITLE
Jetpack bug

### ISSUE THREAD

**Issue by ExpoTr** [mekanism/Mekanism#7804]
### Issue description

Jetpack indicators in the lower left will disappear when you sit on something that can be seated while wearing the jetpack (for example, a helicopter in simple planes mod).

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.11

### Mekanism version

10.3.9 (Latest)

### Other relevant versions

i dont know.i have rubidium and rubidium extra(last versions)

**Comment by pupnewfster** [comment]
If I had to guess this sounds like it is probably intentional on the other mod's part as it sounds like they are just hiding the HUD while you are sitting down. Though maybe boats do as well? I forget what parts of the HUD that hides.
