### ISSUE TITLE
Infusing factories dont open.

### ISSUE THREAD

**Issue by ExpoTr** [mekanism/Mekanism#7805]
### Issue description

When I right click on infusing factories they don't open. This is just starting to happen. I have rubidium and rubidium extra mods in my package. I don't have the slightest idea why this is happening.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.11

### Mekanism version

10.3.9 (Latest)

### Other relevant versions

Rubidium and rubidium extra (last versions)

**Comment by pupnewfster** [comment]
Please provide your latest log

**Comment by ExpoTr** [comment]
My problem was solved when I updated the forge version.

**Comment by ExpoTr** [comment]
N
