### ISSUE TITLE
Energy cube side orientation depends on player view when placed

### ISSUE THREAD

**Issue by Spongman** [mekanism/Mekanism#7806]
### Issue description

(FTB Skies 1.2.1)

unlike _every other_ Mekanism block, for an Energy Cube "Top" is _not_ always in the negative-y direction.

If I look vertically up and place an Energy Cube on the ceiling, then "Front" is the side pointing towards the floor.

In what universe does this make sense? Why are Energy Cubes different from all other machines?

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.11

### Mekanism version

Current Dev Branch (Manually Compiled)

**Comment by pupnewfster** [comment]
It is a six directional block the same as the quantum entangloporter, lasers, and various other blocks in the mod.

**Comment by Spongman** [comment]
that's dumb. in what universe does "Top" not mean "toward the sky" ?

![image](https://github.com/mekanism/Mekanism/assets/1088194/5174891b-d78a-43e0-bbf9-1445851c1402)


Especially for something that looks that same from all sides?

person A: "what side is the top of this box here"
person B: "this one, surely, the one on top?"
person A: "oh, no, actually the 'Top' side is this one on the side here, because the person who put the box down was looking down  when they placed it."
person B: "are you insane?"


Just because it's also broken for other blocks, doesn't mean it's not broken. It just means it's broken for those blocks, too.

**Comment by SirEndii** [comment]
Top is the top side of the block which respects the placed Direction.
Top is a relative direction, always referring the blocks placed direction.

Side fact
"Up" would be a cardinal direction, but mekanism does not use cardinal directions in this context. 

So always remember how you placed the block or place it in a predictable way(for example if you place it in your wall already full of machines, place the block from the front of the wall)

**Comment by Spongman** [comment]
Yeah, i understand how it works now. I'm just saying that it doesn't make any sense for something that looks the same from all sides to have a "top" direction that isn't "up".

The only time IRL this happens is when something is placed on its side and it's obvious by looking at it that it's wrong.

**Comment by SirEndii** [comment]
Top isn't up 
Top is relative and up is cardinal

I can understand that a directional block with the same textures can be confusing but note that the block model adapts to the configuration mode of the side. If right is toggled disable, the port vanishes on the right

**Comment by Spongman** [comment]
yeah, you keep saying the same thing "this is how it works"

i'm saying that _that_ doesn't make any senes.

**Comment by SirEndii** [comment]
What does not make any sense? The directions are used, the model adapts to the side configuration 

The model how it is now would not work if the block isn't directional

**Comment by Spongman** [comment]
> What does not make any sense

please read my previous comments. the answer to this question should be obvious from what i wrote. 

Maybe "top" and "up" mean something different for you?
