### ISSUE TITLE
1.20.1 Energy cube does not sync "eject" mode with client properly

### ISSUE THREAD

**Issue by DBotThePony** [mekanism/Mekanism#7809]
### Issue description

![AYumVrJ1hA.webm](https://github.com/mekanism/Mekanism/assets/6339511/9491d9c9-c0d9-43d6-8537-5906b9cb134d)

Keep in mind this happened in my dev environment when Mekanism is loaded as `implementation`

### Steps to reproduce

1. Load world
2. Place down energy cube
3. Switch Eject to Off
4. Save world
5. Load world
6. Observe energy cube behaving as expected (does not push power to output sides), but "eject" in gui says "on"

### Minecraft version

1.20.1

### Forge version

47.0.19

### Mekanism version

Current Dev Branch (Manually Compiled)

### Other relevant notes

Machines are not affected

**Comment by pupnewfster** [comment]
Should be fixed now, going to leave this open though as it wasn't a porting artifact so until there is a release with this out might as well have it still be tracked as an issue.

**Comment by hallool** [comment]
where do i download 1.20.1? on cursed forge only 1.19 exist
