### ISSUE TITLE
Resistive heater z-fighting connector overlay

### ISSUE THREAD

**Issue by leagris** [mekanism/Mekanism#7810]
### Issue description

The Resistive heater connector overlay texture is z-fighting with the machine background texture.

![screenshot](https://files.noiraude.net/index.php/apps/files_sharing/publicpreview/YJagNAgqdHtcSrg?x=1920&y=403&a=true&file=Image%2520coll%25C3%25A9e.png&scalingup=0)

### Steps to reproduce

1. Look at it

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.14

### Mekanism version

10.3.8

**Comment by pupnewfster** [comment]
Do you have rubidium? Does this happen without it?

**Comment by leagris** [comment]
There was rubidium installed:
- rubidium-0.6.2b
- oculus-mc1.19.2-1.6.4

Removed and the z-fighting issue is gone. The overlay now renders with emissive lightness which is very cool-looking.
![image](https://github.com/mekanism/Mekanism/assets/1111474/485d4388-b48d-41c4-a1e5-6916bb631e8a)

Thank-you for the head-up about rubidium!

**Comment by pupnewfster** [comment]
Yeah nothing we can do about rubidium breaking things and causing z-fighting, you can try reporting it to them though I doubt much will come of it.
