### ISSUE TITLE
Error: java.lang.NullPointerException: Registry Object not present: emendatusenigmatica:enigmatic_hammer

### ISSUE THREAD

**Issue by StarmanAkremis** [mekanism/Mekanism#7811]
### Issue description

When I installed it and ran the game it appeared.

### Steps to reproduce

1. Install Version
2. Run Game

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.14

### Mekanism version

Current Dev Branch (Manually Compiled)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/n9wvqF7B

**Comment by pupnewfster** [comment]
This has nothing to do with us? It is the mod that you mentioned in the issue title

**Comment by StarmanAkremis** [comment]
this was a mistake, i pasted the error on google and there was a page talking about mekanism, but in reality it was another mod, i don't need assistance.
