### ISSUE TITLE
Rendering error and game crash

### ISSUE THREAD

**Issue by n1ret** [mekanism/Mekanism#7813]
### Issue description

[latest.log](https://github.com/mekanism/Mekanism/files/11948836/latest.log)

### Steps to reproduce

1. Start Divine journey 2
2. Join world with thermoelectric boiler

### Minecraft version

1.12.2 (No longer being developed)

### Forge version

14.23.5

### Mekanism version

latest on 1.12.2

**Comment by pupnewfster** [comment]
No idea what is going on given while yes the stack trace does make it look like mekanism I have never seen this crash before and am not sure why it is occurring. Unfortunately not much I can do to help you as I don't remember how things worked in 1.12 at all, best bet would be to try removing optifine and see if it still crashes.
