### ISSUE TITLE
Crash when using Jetpack, possibly only on Multiplayer

### ISSUE THREAD

**Issue by WizzyModpack** [mekanism/Mekanism#7816]
### Issue description

I realise this version is no longer being developed but thought I would post about the issue anyway just in case there were any suggestions as to how I could avoid it or fix it.

The crash seems to happen when flying with the jetpack - sometimes while flying and sometimes when just beginning to fly. It is the same error in the crash report each time, and it can sometimes happen quite close together, however I have not been able to determine if it is something specific happening at the same time that is causing the crash.

So far, this crash has only happened when another player is joined via LAN. I have not experienced this crash when it has only been myself on the world. The crash also only seems to happen when I am flying or if we are both flying, not if only the second player is flying. When it does happen, the second player will be kicked from the world back to the main menu, and my game will exit completely. I think it is more likely for the crash to happen if we are close together, however I have not been able to confirm this as I cannot recreate the crash reliably.

### Steps to reproduce

1. Have another player on the world and close to you (unconfirmed)
2. Fly using the Jetpack

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

10.13.4.1614

### Mekanism version

Older

### Other relevant versions

Mekanism 9.1.1.1031 for Minecraft 1.7.10

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/hpCHRsGT

**Comment by pupnewfster** [comment]
Unfortunately I am not really sure what is causing this (in part given I joined the dev team mid/late 1.12), but glancing at the code I don't see why it would happen but I also don't see any potential workaround to keep said piece of code from happening. My best guess is that it has to do with LAN and how things are updated and if you ran a local dedicated server that you both connected to that it might not happen. One other potential solution is to try out https://www.curseforge.com/minecraft/mc-mods/mekanism-ce THOUGH I do not know much about it (so can't endorse it) beyond the fact that it is a version that appears to be being continued to maintained by the community to fix bugs and the like in old versions of Mekanism. But even if it doesn't fix it if you report it to them potentially they would be able to fix the issue.
