### ISSUE TITLE
Fission reactor insta-dissipates any coolant input into steam

### ISSUE THREAD

**Issue by Xplodin** [mekanism/Mekanism#7817]
### Issue description

I recently made an update to my modpack and for some unknown reason I cannot get the reactor to hold any input water;
it takes the water instantly and converts it to steam (even if the reactor is OFF & never booted on)

Steam gets made despite water being instantly dissipated when its put into the reactor port.

### Steps to reproduce

Download beanpack refrigerated
Create new world and run /mek build fission
apply the ports as necessary to input water creative or non creative methods.

any water being inputted into the reactor instantly gets eaten and turned into steam even if the reactor isnt on. (REALLY ODD)

Im using latest mekanism + addons (official) & including latest mek fission recipe and mekanism tweaks addons (unofficial addons)
if there is a way to debug this thatd be great as ive tried all I know to fix this.
This is my last resort as im unsure what could possibly be breaking fission.
![2023-07-12_06 45 16](https://github.com/mekanism/Mekanism/assets/13007677/dbbd52d5-5f62-467a-abd2-ef5b7b3c4ef3)
![2023-07-12_06 45 18](https://github.com/mekanism/Mekanism/assets/13007677/b3e2ec5d-cdea-4c76-b83c-e67ca30490b1)
![2023-07-12_06 45 24](https://github.com/mekanism/Mekanism/assets/13007677/4b54e9de-ec29-45a4-9ae9-4bd00ea8b719)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.14

### Mekanism version

10.3.8

### Other relevant versions

10.3.5 (ive tried both)
10.3.7

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Xplodin/ab43ebde87fc6e9dfc4206c11f16fcd5

**Comment by Xplodin** [comment]
This is definitely a mod conflict with another mod but I cant figure out which mod could possibly do this with mekanism.
Ive deleted a bunch of performance mods except modernfix and cant seem to get results

**Comment by pupnewfster** [comment]
Does this happen without "Mekanism Fission Recipe"? No idea what that mod does beyond coremodding mekanism to change our internals at runtime so if I had to guess it probably is breaking baseline functionality.

**Comment by Xplodin** [comment]
it was mek fission recipe. sorry!
It used to work but I guess the 1.19.2 version is bugged

**Comment by Xplodin** [comment]
by any chance would there be a way to implement custom coolants and reactants without forking/using a separate mod?
I had my modpack setup in a way to use custom reactants and coolants but it seems impossible without an addon

**Comment by pupnewfster** [comment]
Custom coolants yes, custom reactants no the fission reactor only runs on fissile fuel. But custom coolants can be made with CraftTweaker and adding the [coolant attribute](https://github.com/mekanism/Mekanism/blob/1.19.x/src/main/java/mekanism/common/integration/crafttweaker/chemical/attribute/gas/CrTCoolantAttribute.java) to a custom made gas.
