### ISSUE TITLE
1.20.1 Server chrashes due to NullPointer on block

### ISSUE THREAD

**Issue by zaze06** [mekanism/Mekanism#7819]
### Issue description

Server crashes when finished loading the world due to a null pointer exception on IGasTank.isEmpty()

### Steps to reproduce

1. Make a world
2. Play a bit(i got to point of soon turning on my fission reactor)
3. crash

### Minecraft version

1.19.2 (Latest)

### Forge version

47.1.14

### Mekanism version

Current Dev Branch (Manually Compiled)

### Other relevant versions

Minecraft version is 1.20.1 not 1.19.2
My version of Mekanism was compiled about 20m ago so the last commit that is included should be b759b4440c0628c348748f64e71b08b9e2c3cbe6
I have tried version 47.1.1 of Forge before 47.1.14 and the crash still happened

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/zaze06/32a1f265e7b061bfb1171f40feb133cd

**Comment by pupnewfster** [comment]
Turns out this actually was an issue for the 1.19.2 branch as well so I went ahead and fixed it in both.

**Comment by zaze06** [comment]
Thanks, so just fetch, compile, try?

**Comment by pupnewfster** [comment]
Yeah

**Comment by zaze06** [comment]
ok, thanks

**Comment by zaze06** [comment]
Server booted hopefully it doesn't crash when I join
