### ISSUE TITLE
[1.20]NullPointerException when Ticking Block Entity in Mekanism

### ISSUE THREAD

**Issue by windy664** [mekanism/Mekanism#7826]
### Issue description

I encountered a NullPointerException when running the server with Mekanism installed. The crash seems to occur during the ticking of a block entity. The error message indicates a null reference when invoking the method IGasTank.isEmpty() on outputTank. I expect outputTank to be properly initialized before its methods are invoked.

### Steps to reproduce

1. 1.Start the server with Mekanism installed..
2. Perform the operation that triggers the ticking of a block entity.
3. The server crashes and the error message is displayed.

### Minecraft version

1.20.1 (Latest)

### Forge version

43.2.8

### Mekanism version

10.3.9 (Latest)

### Other relevant versions

• mods_folder [前置][神秘主义][聪明大脑库]SmartBrainLib-fabric-1.20-1.11.jar : smartbrainlib (1.11) - 1
• mods_folder [前置][动态联合]CyclopsCore-1.20.1-1.18.6.jar : cyclopscore (1.18.6) - 1
• mods_folder [天空村庄] SkyVillages-1.0.2-1.20.1-forge-release.jar : skyvillages (1.0.2-1.20.1-forge) - 1
• mods_folder [通电动力]energizedpower-1.20.1-1.7.6.jar : energizedpower (1.20.1-1.7.6) - 1
• mods_folder [前置][炼金化学]alchemylib-1.20.1-1.0.24.jar : alchemylib (1.0.24) - 1
• mods_folder [前置]geckolib-forge-1.20.1-4.2.1.jar : geckolib (4.2.1) - 1
• mods_folder [更多灯笼] additionallanterns-1.0.4-forge-mc1.20.jar : additionallanterns (1.0.4) - 1
• mods_folder [前置][铁魔法]player-animation-lib-forge-1.0.2-rc1+1.20.jar : playeranimator (1.0.2-rc1+1.20) - 1
• mods_folder [JEI物品管理器]jei-1.20.1-forge-15.2.0.23.jar : jei (15.2.0.23) - 1
• mods_folder [更多实用工具]scalar_utils-1.20.1-5.4.10.jar : scalar_utils (1.20.1-5.4.10) - 1
• mods_folder [网络发包修复]connectivity-1.20.1-4.4.jar : connectivity (1.20.1-4.4) - 1
• mods_folder [史蒂夫模型]yesstevemodel-1.20-release-1.1.4.jar : yes_steve_model (1.1.4) - 1
• mods_folder [前置][铁魔法]caelus-forge-3.1.0+1.20.jar : caelus (3.1.0+1.20) - 1
• mods_folder [更多结构]Structory_1.20.1_v1.3.2.jar : structory (1.3.2) - 1
• mods_folder [懒人厨房] cookingforblockheads-forge-1.20-16.0.0.jar : cookingforblockheads (16.0.0) - 1
• mods_folder [摩登生活]modernlife-1.20.1-1.64.jar : modernlife (1.20.1-1.64) - 1
• mods_folder [自然罗盘／生物群系指南针] NaturesCompass-1.20.1-1.11.1-forge.jar : naturescompass (1.0.0) - 1
• mods_folder [前置][柠檬核心]lemon_core-1.20.1-1.0.20.jar : lemon_core (1.20.1-1.0.20) - 1
• mods_folder [更多光源] additional_lights-1.20.1-2.1.7.jar : additional_lights (2.1.7) - 1
• mods_folder [魔法使]mahoutsukai-1.20.1-v1.34.52.jar : mahoutsukai (1.20.1-v1.34.52) - 1
• mods_folder [前置][懒人厨房]balm-forge-1.20-7.0.4.jar : balm (7.0.4) - 1
• mods_folder [更多磁盘] ExtraDisks-1.20.1-3.0.0.jar : extradisks (1.20.1-3.0.0) - 1
• mods_folder [原神乐器]genshinstrument-1.20.1-2.8.jar : genshinstrument (2.8) - 1
• mods_folder [前置]cloth-config-11.0.99-forge.jar : cloth_config (11.0.99) - 1
• minecraft forge-1.20.1-47.1.3-universal.jar : forge (47.1.3) - 1
• mods_folder [精致存储] refinedstorage-1.12.2.jar : refinedstorage (1.12.2) - 1
• mods_folder [更多箱子]ironchest-1.20.1-14.4.4.jar : ironchest (1.20.1-14.4.4) - 1
• mods_folder [集成合成学] IntegratedCrafting-1.20.1-1.1.3.jar : integratedcrafting (1.1.3) - 1
• mods_folder [炼金化学] alchemistry-1.20.1-2.3.0.jar : alchemistry (2.3.0) - 1
• minecraft server-1.20.1-20230612.114412-srg.jar : minecraft (1.20.1) - 1
• mods_folder [农夫乐事] FarmersDelight-1.20.1-1.2.2a.jar : farmersdelight (1.20.1-1.2.2a) - 1
• mods_folder [小画] LittleFrames_FORGE_v1.1.20_mc1.20.1.jar : littleframes (1.1.20) - 1
• mods_folder [前置][集成动力]CommonCapabilities-1.20.1-2.9.0.jar : commoncapabilities (2.9.0) - 1
• mods_folder [前置][生物群系]TerraBlender-forge-1.20.1-3.0.0.167.jar : terrablender (3.0.0.167) - 1
• mods_folder [汉堡包]burgermod-2.9.4-1.20.1.jar : burgermod (2.9.4) - 1
• mods_folder [前置][妖怪之山通用库] mysterious_mountain_lib-1.2.7-1.20.jar : mysterious_mountain_lib (1.2.7-1.20) - 1
• mods_folder [更多生物群系]BiomesOPlenty-1.20.1-18.0.0.592.jar : biomesoplenty (18.0.0.592) - 1
• mods_folder [前置][创造核心]CreativeCore_FORGE_v2.10.28_mc1.20.1.jar : creativecore (2.10.28) - 1
• mods_folder [前置]supermartijn642corelib-1.1.9-forge-mc1.20.jar : supermartijn642corelib (1.1.9) - 1
• mods_folder Botania-1.20.1-441-FORGE-SNAPSHOT.jar : botania (1.20.1-441-FORGE-SNAPSHOT) - 1
• mods_folder [炼金术]theurgy-1.20.1-1.3.7.jar : theurgy (1.3.7) - 1
• mods_folder [倒置火把] ceilingtorch-1.20-1.25.jar : ceilingtorch (1.25) - 1
• mods_folder [工匠之家]workshop_for_handsome_adventurer--mc1.20.1--1.05.jar : workshop_for_handsome_adventurer (1.05) - 1
• mods_folder [前置][饰品栏]curios-forge-5.2.0-beta.3+1.20.1.jar : curios (5.2.0-beta.3+1.20.1) - 1
• mods_folder [通用机械]Mekanism-1.20.1-10.3.9.homebaked-all.jar : mekanism (10.3.9) - 5
• mods_folder [赛🐎娘]umapyoi-0.2.15-1.20.jar : umapyoi (0.2.15-1.20) - 1
• mods_folder [管道]pipez-1.20.1-1.1.3.jar : pipez (1.20.1-1.1.3) - 1
• JarInJar flywheel-forge-1.20-0.6.9-4.jar : flywheel (0.6.9-4) - 1
• mods_folder [机械动力] create-1.20.1-0.5.1.d.jar : create (0.5.1.d) - 1
• mods_folder Patchouli-1.20.1-82-FORGE-SNAPSHOT.jar : patchouli (1.20.1-82-FORGE-SNAPSHOT) - 1
• mods_folder [动态联合]IntegratedDynamics-1.20.1-1.16.8.jar : integrateddynamics (1.16.8) - 2
• mods_folder [前置][化学]chemlib-1.20.1-2.0.17.jar : chemlib (2.0.17) - 1
• mods_folder [作物胜景]Croptopia-1.20.1-FORGE-2.3.2.jar : croptopia (2.3.2) - 1
• mods_folder [照相机]camera-1.20.1-1.0.4.jar : camera (1.20.1-1.0.4) - 1
• mods_folder [法术书]irons_spellbooks-1.20.1-1.1.7.jar : irons_spellbooks (1.20.1-1.1.7) - 1
• mods_folder [前置][手册]modonomicon-1.20.1-1.37.0.jar : modonomicon (1.37.0) - 1
• mods_folder [飞车奇匠] automobility-0.4.2+1.20.1-forge.jar : automobility (0.4.2+1.20.1-forge) - 1
• mods_folder [前置]architectury-9.0.8-forge.jar : architectury (9.0.8) - 1
• mods_folder [铁氧体磁芯] ferritecore-6.0.0-forge.jar : ferritecore (6.0.0) - 1
• mods_folder [神秘学]occultism-1.20.1-1.81.1.jar : occultism (1.81.1) - 1
• mods_folder [卡哇伊]KawaiiDishes_1.10-1.20.1.jar : kawaiidishes (1.10) - 1
• mods_folder [浩渺能源]VoluminousEnergy-1.20.1-0.4.0.0.jar : voluminousenergy (1.20.1-0.4.0.0) - 1
• arclight arclight-1.20.1-1.0.0-SNAPSHOT-381d013.jar : arclight (1.20.1-1.0.0-SNAPSHOT-381d013) - 1
• mods_folder [精致存储附属] refinedstorageaddons-0.10.0.jar : refinedstorageaddons (0.10.0) - 1
• mods_folder [跑图延迟修复]chunksending-1.20.1-2.5.jar : chunksending (1.20.1-2.5) - 1
• mods_folder [豆腐工艺]TofuCraftReload-1.20.1-5.2.4.1.jar : tofucraft (1.20.1-5.2.4.1) - 1
• mods_folder [循环] Cyclic-1.20-1.11.1.jar : cyclic (1.11.1) - 1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/suiheng/785bc0f0c82a5f26ee34b86aeca8fa00

**Comment by thiakil** [comment]
Please update to the latest code from got before reporting bugs on an alpha version without an actual release

This was already fixed
