### ISSUE TITLE
Concurrency crash in mod constructor

### ISSUE THREAD

**Issue by Darkere** [mekanism/Mekanism#7827]
### Issue description

https://gist.github.com/Tanden22/240a2af8a9a8ff98e4b1e43a984cfe16

Crashlog is likely useless due to EE continuing to run even when the game has already stopped
https://gist.github.com/Tanden22/407fdc7ba0684c3bfcba368a59769cdb

### Steps to reproduce

¯\_(ツ)_/¯

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.14

### Mekanism version

10.3.9 (Latest)

**Comment by pupnewfster** [comment]
Uhh this looks like a CME in modlauncher's classloader more than something in mek. Is this at all reproduceable by the user?

**Comment by Darkere** [comment]
I kinda doubt it. https://github.com/EnigmaticaModpacks/Enigmatica9/issues/530

**Comment by NielsPilgaard** [comment]
I can't reliably reproduce it, it happens occasionally but a re-launch makes it go away.

**Comment by Su5eD** [comment]
I think the error occurs as a result of a mod injecting a modlauncher plugin service during mod construction. FML invokes mod constructors in parallel, and if the mod injects the plugin while modlauncher is [preparing](https://github.com/McModLauncher/modlauncher/blob/22f00f846494ff98678fa4a1f871914ba2d9fb62/src/main/java/cpw/mods/modlauncher/LaunchPluginHandler.java#L68C47-L68C47) to transform another class, a CME is thrown.

After a github search, I found a mod that perfectly matches this scenario and also happens to be installed in your instance: [Create: Steam 'n' Rails](https://legacy.curseforge.com/minecraft/mc-mods/create-steam-n-rails). See their injection code [here](https://github.com/Layers-of-Railways/Railway/blob/1584b7ae46452ded048ffcd9074967c1f4b286b7/forge/src/main/java/com/railwayteam/railways/forge/RailwaysImpl.java#L54). Advice for Steam n Rails maintainers: please perform injection in a transformation service or mixin plugin, before the transformable layer is even created.  
CC @techno-sam @IThundxr

**Comment by techno-sam** [comment]
@Su5eD could you point me in the direction of the documentation for transformation services/mixin plugins?

Can mixin plugins do *custom transformation*?
