### ISSUE TITLE
Not support IC2classic's EU

### ISSUE THREAD

**Issue by JackieJK** [mekanism/Mekanism#7828]
### Issue description

mekanism10.3.9 and ic2classic2.0.6.2(not ic2experimental) on 1.19.2 

### Steps to reproduce

1. install the mods
2. place a IC2 machine
3. place a universal cable beside

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.8

### Mekanism version

10.3.9 (Latest)

**Comment by pupnewfster** [comment]
Mekanism has never supported ic2c directly and on top of that last time I looked they said their api is unstable and also it isn't documented so it is basically impossible to know how to use it since the main mod is closed source.

**Comment by gfbbkon** [comment]
You can ask Speiger for permission to use the source code 
> Mekanism никогда не поддерживал ic2c напрямую, и вдобавок к этому в прошлый раз, когда я смотрел, они сказали, что их API нестабилен, а также он не задокументирован, поэтому практически невозможно узнать, как его использовать, поскольку основной мод имеет закрытый исходный код.

**Comment by gfbbkon** [comment]
> Mekanism has never supported ic2c directly and on top of that last time I looked they said their api is unstable and also it isn't documented so it is basically impossible to know how to use it since the main mod is closed source.

You can ask Speiger for permission to use the source code.
