### ISSUE TITLE
ConcurrentModificationException on QIO Exporter

### ISSUE THREAD

**Issue by andriihorpenko** [mekanism/Mekanism#7830]
### Issue description

QIO Exporter threw `ConcurrentModificationException` exception randomly, causing server to shutdown. This happened once, however, might be important for you. Crash report is attached below (uploaded to Pastebin).

### Steps to reproduce

Unfortunately, there are no guaranteed reproduction steps for this exception to occur.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.17

### Mekanism version

10.3.9 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/aY91daey

**Comment by pupnewfster** [comment]
Hmm, from looking at the code I have one idea of what might be going on. I am going to go ahead and take a guess that you have export without filter enabled?

**Comment by andriihorpenko** [comment]
Yep, you’re correct. I’ve checked player’s Exporter and that seems to be correct.

**Comment by pupnewfster** [comment]
Okay, thanks that at least gives me a decent spot to start when it comes to trying to come up with a fix and actually reproduce the issue.

**Comment by pupnewfster** [comment]
Does this happen without performance mods (like [canary](https://www.curseforge.com/minecraft/mc-mods/canary), [servercore](https://www.curseforge.com/minecraft/mc-mods/servercore), or [starlight](https://www.curseforge.com/minecraft/mc-mods/starlight-forge/files))?

As after taking another look at the code I realized the thing I thought might be causing issues is written in a way that should be avoiding the issues unless somehow multiple blocks are ticking at the same time, or there is some addon that in their iitemhandler is trying to insert into the QIO and the exporter is inserting into the thing from that addon.

**Comment by andriihorpenko** [comment]
This issue is so rare that it occurred once in 2 weeks, hence I can’t confirm if this happens with or without performance mods. If only I could reproduce it at 100% rate, I could try binary search to pinpoint a problematic mod.
With that said, I suppose there are no other options for us to proceed with this issue?

**Comment by pupnewfster** [comment]
Yeah, unfortunately doesn't seem like there is anywhere to proceed on this issue as I am fairly certain it is due to some performance mod breaking things.
