### ISSUE TITLE
Refined Obsidian Dust cannot extract to an AE2 pattern provider

### ISSUE THREAD

**Issue by CouchPotato935** [mekanism/Mekanism#7833]
### Issue description

I'm trying to automate refined obsidian ingot production using AE2 and have found that pattern provider will not pull refined obsidian dust (ROD) from the connected ME network when a request for refined obsidian ingots is made. I have tried various setups with the compressor configs and ME network. Osmium will extract and enter the Compressor normally but not ROD.
In this image the bottom is set to Input/Output, the left side is set to Extra, and auto-eject is enabled. The export bus is exporting osmium.
![2023-08-01_15 43 02](https://github.com/mekanism/Mekanism/assets/141186593/1234228f-3cab-461b-acc8-f5f28e0058d4)

### Steps to reproduce

1.Put a processing pattern that requires ROD into a pattern provider
2.Request said item

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.11

### Mekanism version

10.3.8

### Other relevant versions

appliedenergistics2-forge-12.9.4.jar

**Comment by thiakil** [comment]
This is an issue with ae2. If they need something from us, they will open an issue
