### ISSUE TITLE
Server Hang Issue with TileEntityMekanism.insertEnergy

### ISSUE THREAD

**Issue by windy664** [mekanism/Mekanism#7835]
### Issue description

While running a Minecraft server with the Mekanism mod installed, I encountered a server crash. The crash report indicates that the server hang was detected due to a single server tick taking 60.00 seconds, whereas it should be a maximum of 0.05 seconds. The issue seems to stem from the TileEntityMekanism.insertEnergy method in the Mekanism mod. The expected outcome would be for the server to run smoothly without any extended tick durations.

### Steps to reproduce

1.Set up a server with the specified versions of Minecraft, Forge, and Mekanism.
2.Observe the server tick duration and potential server crash with the mentioned issue.

### Minecraft version

1.20.1 (Not yet released, manually compiled)

### Forge version

1.20.1-47.1.3

### Mekanism version

Current Dev Branch (Manually Compiled)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/windy664/3ebffb606bea5b5353a314d04beb80b1

**Comment by ErythroCraft** [comment]
Last version of [Mekanism](https://github.com/mekanism/Mekanism) is [v1.19.2-10.3.9.13](https://github.com/mekanism/Mekanism/releases/tag/v1.19.2-10.3.9.13)

Are you sure, you are running forge/mc 1.19.2 ?

**Comment by Jorue23** [comment]
He said that he manually compiled 1.20.1

**Comment by pupnewfster** [comment]
The server watchdog tends to not be the best indicator of what is necessarily causing the lag as it just includes in the stack trace what was going on when it finally hit the limit. I would recommend trying to set `max-tick-time` to `-1` in the `server.properties` to disable the watchdog, and then using a profiler like [spark](https://www.curseforge.com/minecraft/mc-mods/spark) to create a profile to get a better idea of what is using up all the tick time.

**Comment by ErythroCraft** [comment]
Hello.

I couldn't find any bugs in Mekanism that indicate importing energy.
**Testet Client and Server side.**

**_Apart from that, I couldn't find any other bugs or shortcomings that affect play or compatibility with other mods._**

![2023-08-07_04 32 52](https://github.com/mekanism/Mekanism/assets/76217862/db0eb03c-9234-4691-b172-d4557a59d3fe)

![Screenshot 2023-08-07 032909](https://github.com/mekanism/Mekanism/assets/76217862/0d89ff1d-0c60-4a6d-8aac-56a6006bf45d)

![Screenshot 2023-08-07 032949](https://github.com/mekanism/Mekanism/assets/76217862/a76c2f28-d4ad-4a0c-bf56-0fd6a812764b)

![Screenshot 2023-08-07 033046](https://github.com/mekanism/Mekanism/assets/76217862/aa35a2a3-7bd3-4511-afa6-0135f71b4b20)

![Screenshot 2023-08-07 033541](https://github.com/mekanism/Mekanism/assets/76217862/7d4a675b-8726-44ca-aafa-1d2f4d82b75a)

![Screenshot 2023-08-07 035046](https://github.com/mekanism/Mekanism/assets/76217862/9632cd5b-b248-4731-8e92-d0828be30a39)

**Comment by ErythroCraft** [comment]
**Server side:**
[debug.log](https://github.com/mekanism/Mekanism/files/12271548/debug.log)
[latest.log](https://github.com/mekanism/Mekanism/files/12271549/latest.log)

**Client side:**
[debug.log](https://github.com/mekanism/Mekanism/files/12271604/debug.log)
[latest.log](https://github.com/mekanism/Mekanism/files/12271606/latest.log)

**Comment by windy664** [comment]
> The server watchdog tends to not be the best indicator of what is necessarily causing the lag as it just includes in the stack trace what was going on when it finally hit the limit. I would recommend trying to set `max-tick-time` to `-1` in the `server.properties` to disable the watchdog, and then using a profiler like [spark](https://www.curseforge.com/minecraft/mc-mods/spark) to create a profile to get a better idea of what is using up all the tick time.

When I update to the latest version, this problem does not appear .

**Comment by thiakil** [comment]
a watchdog crash doesnt indicate what took so long, only what was running when it decided enough is enough.
