### ISSUE TITLE
help me see spark

### ISSUE THREAD

**Issue by windy664** [mekanism/Mekanism#7836]
### Issue description

The mek mod causes the tps of the server to be extremely low, but I don't know how to use spark

### Minecraft version

1.20.1 (Not yet released, manually compiled)

### Forge version

47.1.3

### Mekanism version

Current Dev Branch (Manually Compiled)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://spark.lucko.me/FIrnRJUQ77

**Comment by SirEndii** [comment]
Why didn't you answer on your old issue

**Comment by windy664** [comment]
> Why didn't you answer on your old issue

抱歉，我不是很会用github
I'm not very familiar with github

**Comment by thiakil** [comment]
what leads you to the belief that Mekanism is the problem?

**Comment by windy664** [comment]
> what leads you to the belief that Mekanism is the problem?
![IMG_20230807_205049](https://github.com/mekanism/Mekanism/assets/81475218/9302d58d-1210-4bbd-a1e7-3bb78989de5e)

this

**Comment by thiakil** [comment]
And why is that problematic?

**Comment by windy664** [comment]
> And why is that problematic?

tps is not stable

**Comment by thiakil** [comment]
Not what I mean. Why is Mekanism's appearance in your screenshot significant?

You have 1200 entities and 20000-26000 tile entities. To even be maintaining 16 tps consistently is impressive (which appears to be stable in the graph in your report)

**Comment by SirEndii** [comment]
Yeah, the tps you currently have are very normal for this amount of entities/block entities

Every server starts to get slower over time, especially modded ones
