### ISSUE TITLE
"Energy" displaied twise on wthit

### ISSUE THREAD

**Issue by zaze06** [mekanism/Mekanism#7837]
### Issue description

While looking at the machines whit wthit I see two energy bars/displays (image)

![image](https://github.com/mekanism/Mekanism/assets/54169874/c5e098a2-f35d-46bc-b4f9-66aa74de229d)

### Steps to reproduce

1. Compile the latest as off 2680a3a2490afdf1e56d929ebf905fabe284c39f
2. Lunch game whit mekanism-all(unsure if that's important) whit wthit
3. Look at a machine
4. Issue

### Minecraft version

1.20.1 (Not yet released, manually compiled)

### Forge version

47.1.43

### Mekanism version

Current Dev Branch (Manually Compiled)

### Other relevant versions

wthit: 8.3.0

Full modlist+versions:
AppleSkin(appleskin): 2.5.0+mc1.20.1
Cloth Config v10 API(cloth_config): 11.1.106
Just Enough Resources(jeresources): 1.4.0.222
Searchables(searchables): 1.0.1
Bad Packets(badpackets): 0.4.1
CC: Tweaked(computercraft): 1.106.1
Light Overlay(lightoverlay): 8.0.0
SuperMartijn642's Config Library(supermartijn642configlib): 1.1.7
Curios API(curios): 5.2.0-beta.3+1.20.1
Memory Leak Fix(memoryleakfix): 1.1.1
Full Brightness Toggle(fullbrightnesstoggle): 3.0
Collective(collective): 6.65
SuperMartijn642's Core Lib(supermartijn642corelib): 1.1.12a
speedometer(speedometer): 4
Simple Voice Chat(voicechat): 1.20.1-2.4.16
Rechiseled(rechiseled): 1.1.2a
Advanced Peripherals(advancedperipherals): 0.7.32b
Architectury(architectury): 9.1.12
Controlling(controlling): 12.0.2
Corail Tombstone(tombstone): 8.5.2
Easy Anvils(easyanvils): 8.0.1
Fusion(fusion): 1.0.5
Journeymap(journeymap): 5.9.12
Just Enough Items(jei): 15.2.0.23
Puzzles Lib(puzzleslib): 8.0.15
Sound Physics Remastered(sound_physics_remastered): 1.20.1-1.1.2
wthit(wthit): 8.3.0
Not Enough Crashes(notenoughcrashes): 4.4.6+1.20.1
Mekanism(mekanism): 10.3.9(This is the compiled version from commit 2680a3a2490afdf1e56d929ebf905fabe284c39f)

**Comment by ErythroCraft** [comment]
You are running the latest build of Forge. 
This ist not recommended. Half stars means the forge version is in build for the next star.
Recommended Versions has got a full star, but most likely MDK for mod creator is forge-1.20.1-47.1.3

So. Please test your mod-pack with [forge-1.20.1-47.1.3](https://maven.minecraftforge.net/net/minecraftforge/forge/1.20.1-47.1.3/forge-1.20.1-47.1.3-installer.jar)

**Comment by zaze06** [comment]
sure I can test it on an older version, I'm running 47.1.43 due to trying to resolve an earlier bug and haven't changed back afterward

**Comment by ErythroCraft** [comment]
![2023-08-07_23 09 33](https://github.com/mekanism/Mekanism/assets/76217862/50183621-7990-4285-a1d4-94e41be97d14)

**Comment by zaze06** [comment]
nope, running 47.1.3
![image](https://github.com/mekanism/Mekanism/assets/54169874/ccb4a5f3-be7b-48c2-a5d6-3fc1da5100e9)

**Comment by ErythroCraft** [comment]
And maybe they pick a version. Either they want to use [Just Enough Resources(jeresources): 1.4.0.222] or [Just Enough Items(jei): 15.2.0.23]. I personally prefer JEI

**Comment by zaze06** [comment]
You  do know that Just Enough Resources is an addon to JEI? that adds Mob drops, World gen information and more

source: [JER on modrith](https://modrinth.com/mod/just-enough-resources-jer)

**Comment by zaze06** [comment]
so i did a test whit just wthit, mekanism and badpackets(required for wthit)
![image](https://github.com/mekanism/Mekanism/assets/54169874/847cd668-b04e-4af3-926e-65a7b92d4d5c)
so the issue is ether mekanism, wthit, or forge

**Comment by ErythroCraft** [comment]
And what mod are you using to do that?

![Screenshot 2023-08-07 231723](https://github.com/mekanism/Mekanism/assets/76217862/45940b49-7afd-459f-ae81-e38aef797655)

**Comment by zaze06** [comment]
that image? that is using the original mod list, so wthit is producing that block display

**Comment by ErythroCraft** [comment]
Yes

**Comment by zaze06** [comment]
so yes the mod "wthit" version 8.3.0 is making that block info display

**Comment by ErythroCraft** [comment]
Ah. See it.

First. It is not a bug or issue of Mekanism, because Mekanism hasn't got this future.

Uninstall - WTHIT - and - bad packets -

Instead of this mods install [The one Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)

**Comment by zaze06** [comment]
So WTHIT cuases the issue? Okay then i will report this to them insted?

Also i prefer the WTHIT's block display box more then The One Probe. Thanks for the help tho

**Comment by ErythroCraft** [comment]
It's not a bug of Mekanism.

It's a a bug of WTHIT's or BadPackets

**Comment by zaze06** [comment]
Thanks for the help. Best of luck to you

**Comment by pupnewfster** [comment]
This is a bug in mek as we need to declare to WTHIT to not display the energy as we are taking over doing that. My guess is they added their own display since we last tested it.

**Comment by zaze06** [comment]
So wait for a commit that fixes this then recompile? Okay

**Comment by ErythroCraft** [comment]
I don't think so

Configuration "Energy" display on/off with WTHIT
https://youtu.be/mniuQFZ_J3U
