### ISSUE TITLE
solar neutron activator don't works

### ISSUE THREAD

**Issue by TheGamerFarmer** [mekanism/Mekanism#7839]
### Issue description

I put Nuclear waste in my SNA, he is in the sun, the Nuclear waste is in the SNA but he didn't transform into polonium. I try anything I can do.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.2.0

### Mekanism version

Older

**Comment by pupnewfster** [comment]
What dimension is the SNA in? Is there sunlight in that dimension?

**Comment by TheGamerFarmer** [comment]
![image](https://github.com/mekanism/Mekanism/assets/142070067/9b8713f8-6daf-478e-bbc8-6c7b67c0e870)
![Uploading image.png…]()
The SNA is in the overworld.

**Comment by TheGamerFarmer** [comment]
And YES I have a problem of radiation

**Comment by TheGamerFarmer** [comment]
![image](https://github.com/mekanism/Mekanism/assets/142070067/5133902d-921c-438a-bf5b-e2a1fc7c8705)
