### ISSUE TITLE
help fusion reactor with "better fusion reactor for mekanism plus" addon

### ISSUE THREAD

**Issue by TheGamerFarmer** [mekanism/Mekanism#7840]
### Issue description

I try to do the computer's system of this vidéo https://youtu.be/AQoTdYvbDH8 but the vidéo is in Russia and he didn't tell us who the computer's systeme works

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.2.0

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Neither better fusion reactor, nor mekanism plus are our mods
