### ISSUE TITLE
Mekansim Crash?

### ISSUE THREAD

**Issue by HerrArchitekt** [mekanism/Mekanism#7841]
### Issue description

Minecraft crashes/produces black screen when right clicking with balloon without a target.
Cannot join Server anymore. Same in singleplayer

[crash-2023-08-14_00.04.56-client.txt](https://github.com/mekanism/Mekanism/files/12330540/crash-2023-08-14_00.04.56-client.txt)

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.21

### Mekanism version

10.3.9 (Latest)

**Comment by pupnewfster** [comment]
I believe iris does not play nicely with balloons. We have this fixed for 1.20, but for now either don't use shaders or don't place any balloons in the world.
