### ISSUE TITLE
help me see spark about mek

### ISSUE THREAD

**Issue by windy664** [mekanism/Mekanism#7842]
### Issue description

hello , in this link https://spark.lucko.me/EdGeI9M77D click  on all in the top bar , you can see mek is taking more CPU tham other mods.

### Minecraft version

1.20.1 (Not yet released, manually compiled)

### Forge version

47.1.3

### Mekanism version

Current Dev Branch (Manually Compiled)

**Comment by thiakil** [comment]
I see nothing wrong there. CPU time isn't distributed evenly amongst mods.

Please stop trying to blame Mekanism.
