### ISSUE TITLE
Mekanism crashes seemingly out of the blue

### ISSUE THREAD

**Issue by HenrikoMagnifico** [mekanism/Mekanism#7843]
### Issue description

Mekanism seems to crash the server seemingly at random, and I have no idea why. The crash does not generate a crash-log, and just seems to cause the server to hang indefinitely, until it's forcibly restared.

### Steps to reproduce

Install and use the Yao Pack 3 modpack on a server, which has Mekanism inside of it.
Wait until the crash occurs.
Profit...?

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.21

### Mekanism version

10.3.9 (Latest)

### Other relevant versions

Mekanism-1.19.2-10.3.9.13
MekanismAdditions-1.19.2-10.3.9.13
ekanismGenerators-1.19.2-10.3.9.13
MekanismTools-1.19.2-10.3.9.13

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/HenrikoMagnifico/4d941325e71f26b7a9c2afd3d4b812d3

**Comment by thiakil** [comment]
What leads you to believe it's caused by Mekanism?

I noticed you have a bunch of mixin version errors in the first log, something may be wrong with your installation.

**Comment by HenrikoMagnifico** [comment]
Only because the latest.log mentions Mekanism last in the file, before the server froze.
