### ISSUE TITLE
Mekanism NoClassDefFoundError

### ISSUE THREAD

**Issue by windy664** [mekanism/Mekanism#7844]
### Issue description

While running the server with Mekanism least code, I encountered a crash with the error java.lang.NoClassDefFoundError. The error points to a missing class in the Mekanism mod. The expected outcome should have been a stable server without any crashes.But there is no such situation in the previous code

### Steps to reproduce

1. Start the Minecraft server with Mekanism version 10.3.9.
2. Interact with or place specific tank related to Mekanism
3. Server crashes with the described error.

### Minecraft version

1.20.1 (Not yet released, manually compiled)

### Forge version

47.1.3

### Mekanism version

Current Dev Branch (Manually Compiled)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/windy664/75bc43f85c05a665b89a3a7a597c4b35

**Comment by thiakil** [comment]
Likely a problem with your built file. We don't provide support for that or for Sponge
