### ISSUE TITLE
Mekanism Crash on startup

### ISSUE THREAD

**Issue by MetalBox47** [mekanism/Mekanism#7846]
### Issue description

Upon launching the game, the game crashes in modloading.  It throws a "MixinTransformerError", as shown in the crashimage.png.
![crashimage](https://github.com/mekanism/Mekanism/assets/35822953/c590b1da-302e-4871-a41c-8c849e5c3c09)
[latest.log](https://github.com/mekanism/Mekanism/files/12375991/latest.log)

### Steps to reproduce

1. Start Minecraft Launcher
2. Press "Play Game"
3. Crash

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.2.10

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/2MPNbJuD

**Comment by thiakil** [comment]
Not us, we don't use mixin. Take it up with Sponge
