### ISSUE TITLE
Fission Reactor Water Filling Issue

### ISSUE THREAD

**Issue by CerberusX11** [mekanism/Mekanism#7847]
### Issue description

Hello everyone,
I hope you're all doing well. I'm facing a challenge with my Fission Reactor setup. Specifically, I'm having difficulty keeping the reactor filled with water.  Here's what's happening: It seems that the reactor rapidly converts water into steam, which is then sent to the wind turbine. The turbine condenses the steam back into water and sends it back to the Fission Reactor, but unfortunately, it's not refilling the reactor adequately.  I'm attaching these screenshots for you, and if you need more, please let me know.

As you can see in the images, the Fission Reactor has 5 configured ports as follows:
1- Input only WATER: Connected to a water pump.
2- Output WASTE: Connected to the waste processor.
3- Output coolant STEAM: Connected to the turbine.
4- Input only WATER TURBINE: Connected to the steam turbine, which condenses the steam back into water and returns it to the reactor.
5- Input only FUEL: Not connected to the fuel manufacturing mechanism because I can't activate the fission reactor without first filling it with water.

I hope the images clearly show that both the ports and cables are configured correctly. I still don't understand why the Fission Reactor isn't filling up with water. Any help would be greatly appreciated.
I have already asked in a Mekanism Discord server, but nobody has been able to figure out the issue. I hope you can assist me.

![1](https://github.com/mekanism/Mekanism/assets/142595499/0534f21b-a8b6-4027-956c-abf004ca9744)
![2](https://github.com/mekanism/Mekanism/assets/142595499/a54657c7-098e-4df7-b1f9-c02f4824fb11)
![3](https://github.com/mekanism/Mekanism/assets/142595499/06ac49e1-d2dc-4e5e-8fc3-6df6201c0162)
![image](https://github.com/mekanism/Mekanism/assets/142595499/18ea5a28-41cf-44e2-a0bf-73ce5e6543da)
![image](https://github.com/mekanism/Mekanism/assets/142595499/754bc7ed-6c15-4a4e-80a7-a68889eee7ef)
![image](https://github.com/mekanism/Mekanism/assets/142595499/6c36af3b-6efb-47ed-8391-36c412d47b05)
![image](https://github.com/mekanism/Mekanism/assets/142595499/99d94e7c-7e93-4d95-a2d3-01d147784de5)

### Minecraft version

1.19.2 (Latest)

### Forge version

1.19.2-43.2.21

### Mekanism version

10.3.9 (Latest)

**Comment by thiakil** [comment]
Pipes have limited throughput, also limited by their buffer - you can increase that with more pipes, or build the multiblocks with their ports touching and no pipe is needed

**Comment by CerberusX11** [comment]
SOLVED, is a conflict with this mod:
[https://www.curseforge.com/minecraft/mc-mods/mekanism-fission-recipe](https://www.curseforge.com/minecraft/mc-mods/mekanism-fission-recipe)
I remove this, and all work fine.
Ty for the time.
