### ISSUE TITLE
Fission Reactor Logic Adapter - Excess Waste signal is "waste"

### ISSUE THREAD

**Issue by uhloin** [mekanism/Mekanism#7851]
### Issue description

Signal about "Excess waste" is too late (on 100% level) and does not prevent catastrophic release of radiation.
Possible solutions:
- Just shut down reactor on 100% level of waste
- Send signal on 90% level
- Send signal on selected level (90% by default)
- Send signal level in proportion of waste tank filling

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.14

### Mekanism version

10.3.9 (Latest)

**Comment by Antaiir** [comment]
I second that. The excess waste logic is not very useful at the moment. Would be great, if this could be tweaked a bit. Thanks in advance! :-)

**Comment by VorpalLemur** [comment]
Agreed.  The current signal is only useful for notifying you that a catastrophic release of radiation has already occurred.  Would love it to have it changed to 'high waste'
