### ISSUE TITLE
Mekanism 1.7.10 working on singleplayer but not on multiplayer

### ISSUE THREAD

**Issue by Prime266** [mekanism/Mekanism#7853]
### Issue description

So I've been playing with modded on one of my worlds since 1.7.10 and still return to it to this day. Mekanism-1.7.10-8.1.5.246 being one of he mods and I've never had any issues before playing with the mods I've had. Yesterday I decided to make a server with the same mods and import the world to the server so I would be able to play with my friends, it crashed and I narrowed it down to Mekanism being the issue for whatever reason. I've looked everywhere why this could have happened but no luck at all.

I know this version is very old and not supported anymore but I hope I can get some help. It just doesn't make sense to me why it would work perfectly fine on singleplayer but not on multiplayer.

The forge I am using is forge-1.7.10-10.13.4.1558-1.7.10
I also have: 
CodeChickenCore-1.7.10-1.0.2.9
ForgeMultipart-1.7.10-1.1.2.331
CodeChickenLib-1.7.10-1.1.3.127

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

forge-1.7.10-10.13.4.1558-1.7.10

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

[<script src="https://gist.github.com/Prime266/a01ac421d288e96e946b747c163d5977.js"></script>](https://gist.github.com/Prime266/a01ac421d288e96e946b747c163d5977)

**Comment by AlexHgC** [comment]
1.7.10 need multipart : https://www.curseforge.com/minecraft/mc-mods/codechickencore and https://www.curseforge.com/minecraft/mc-mods/forge-multi-part

**Comment by Prime266** [comment]
I have CodeChickenCore-1.7.10-1.0.2.9 and ForgeMultipart-1.7.10-1.1.2.331. Sorry I forgot to mention that. I also have CodeChickenLib-1.7.10-1.1.3.127 if anyone else wonders.

**Comment by AlexHgC** [comment]
Check in the server mods folder if you have any folder inside. If yes you have the old bug from multipart, deleted it

**Comment by Prime266** [comment]
ForgeMultipart and CodeChickenLib is in a folder called 1.7.10 in the mod folder. Do I delete both of them or just the ForgeMultipart? Or should I drag it out of the folder?

**Comment by AlexHgC** [comment]
Ok so you have this issue. Delete the folder, and download latest codechicken lib / core and forge multipart from curseforge and put them in the mods folder

**Comment by Prime266** [comment]
It worked! Thank you so much! I'm not sure how getting a newer version of Codechicken lib/core and forgemultipart never occured to me or how I never found this anywhere else. But I'm very thankful that it was so easy and grateful for your fast responses :D !
