### ISSUE TITLE
dupe with mekanism personal chest and fast fingers

### ISSUE THREAD

**Issue by Xplodin** [mekanism/Mekanism#7855]
### Issue description

a user in my discord let me know of a bug that deals with personal chest and dropping and opening them at the same time

### Steps to reproduce

https://www.imgur.com/RotgkTW
^
it basically right click, 10ms, drop item

It works on all versions of mekanism from what I heard

### Minecraft version

1.19.2 (Latest)

### Forge version

1.20.1 - 1.12.2

### Mekanism version

10.3.9 (Latest)

### Other relevant versions

apparently it works from latest - 1.12.2

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

sorry, no logs are required this time around.

**Comment by pupnewfster** [comment]
Does this happen with just Mekanism or do you have any performance mods or inventory modifications mods like one that changes how item transfer happens. As far as I know we have fixed all the remaining issues related to this bug unless some other mod is breaking it. (Though I will try look into it some regardless)
