### ISSUE TITLE
Rebalancing Gas-Burning Generator + Melon Combo

### ISSUE THREAD

**Issue by ngoetti** [mekanism/Mekanism#7856]
### Issue description

The gas-burning generator is easy to build even in the early game and provides so much energy that it outperforms all the start to midgame generators. This is especially true considering how easy it is to grow melons, which disincentivizes all other forms of power generation. I think the gas generator should be nerfed/adjusted. If you think otherwise, please close this issue. If not, I would be willing to make the effort to propose a more balanced solution.

### Steps to reproduce

Irrelevant

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

Irrelevant

### Mekanism version

Older

**Comment by Xplodin** [comment]
just config nerf it lol

**Comment by ngoetti** [comment]
I think the default value should be balanced, because the default will get used 90+ % of the time.

**Comment by thiakil** [comment]
what do you define as a "mid-game" generator?

**Comment by ngoetti** [comment]
@thiakil basically everything except the large multiblock reactors.

**Comment by thiakil** [comment]
The gbg is meant to be the one you use until you get a big reactor. Kinda sounds like it's in the correct spot if it's outperforming the others

**Comment by ngoetti** [comment]
@thiakil I don't mind it outperforming the others. I just think it does so way to much. You can burn though stacks of coal and get less energy than 1 melon slice. Which does not seem balanced. (I would have too check the exact numbers, but you get the idea)

**Comment by thiakil** [comment]
It's not just the melon though, you're combining it with a few things before the energy is extracted

**Comment by ngoetti** [comment]
@thiakil Yes, I agree, and I think this should be considered. However, I still think it is not in proportion. All the other things that needed are easy to make, even in the early game.
