### ISSUE TITLE
Osmium (gas) is unobtainable in survival

### ISSUE THREAD

**Issue by RedIODev** [mekanism/Mekanism#7861]
### Issue description

Osmium gas is not obtainable without the creative chemical tank. 
There is no machine producing osmium gas but the osmium compressor.
The osmium compressor allows for gas input only (which is inconsistent to the metallergic infuser that allows input and output).
This also makes the input useless in survival as you can't put any gas into it besides osmium which is unobtainable.

Solutions:
1. Lift the input only restriction on the osmium compressor.
2. Allow the chemical oxidizer to create osmium gas.
3. Create some other way to obtain osmium gas.

### Minecraft version

1.18.x or earlier (No longer being developed)

### Forge version

40.2.10

### Mekanism version

10.3.9 (Latest)

### Other relevant versions

All (as far as I know)

**Comment by pupnewfster** [comment]
The main way of getting it in survival would be to use a gauge dropper. Though I do think it might be reasonable to allow force extracting when a side is set to output in a similar way that we started allowing infusers to have their contents pulled.

**Comment by Wolfizen** [comment]
I'm playing on 1.18.2 and I wanted access to osmium gas other than via the gauge dropper, but I noticed this feature was added only for 1.21.x.

To get this capability in my modpack, I wrote a custom [KubeJS](https://kubejs.com/wiki/tutorials/recipes) script that adds a new recipe to the Chemical Oxidizer that converts 1 osmium ingot to 200mB of osmium gas.

To get this recipe in your 1.18.x modpack with KubeJS, drop a new file at `<server root>/kubejs/server_scripts/mekanism_oxidizing_osmium.js` (or any other file in the server_scripts folder) with the following code and `/reload`:
```js
onEvent('recipes', event => {
    event.custom({
        'type': 'mekanism:oxidizing',
        'input': {
            'ingredient': {
                'tag': 'forge:ingots/osmium'
            }
        },
        'output': {
            'gas': 'mekanism:osmium',
            'amount': 200
        }
    }).id('kubejs:oxidizing/osmium')
})
```
