### ISSUE TITLE
Digital Miner ignores Filter for Cobbled Deepslate in inverse mode

### ISSUE THREAD

**Issue by km-manzm** [mekanism/Mekanism#7864]
### Issue description

When using the Digital Miner Filter in inverse mode, everything will get filtered out but Cobbled Deepslate.

### Steps to reproduce

Placing Digital Miner

Configure the Digital Miner like the following:

Filters->New Filter->ItemStack-> Place Cobbled Deepslate in left slot -> Save
Turn on Inverse Mode

Start Digital Miner.

Output: Cobbled Deepslate will be mined and put into digital miners inventory.

### Minecraft version

1.19.2 (Latest)

### Forge version

43.3.21

### Mekanism version

10.3.9 (Latest)

### Other relevant versions

Mekanism: Tools v10.3.9
Mekanism: Additions v10.3.9
Mekanism: Generators: v10.3.9

**Comment by pupnewfster** [comment]
Highly doubt there is cobbled deep slate in the world. You probably want it to not be mining deepslate instead

**Comment by km-manzm** [comment]
okay, thanks for your answer. I Found the problem that was confusing me:
i put cobble stone into the filter and it wasn't mining stone. 
As i found out i put some cobblestone into the replacement slot, but as i set it to "Inverse mode requires replacement: no" i thought that empty spaces would never be replaced with it, if this setting is set to no.
IMHO the documentation in the wiki isn't that clear on the functioning of this inverse mode.
