### ISSUE TITLE
Mekanism Heat Generator Lava Dupe

### ISSUE THREAD

**Issue by liviniumnetwork** [mekanism/Mekanism#7868]
### Issue description

Found a, mostly useless, duplication glitch for lava that can be placed inside of the heat generator. Useless by itself but can become annoying for players trying to remove their heat generator only to place it down and have lava also place with it. This issue is specific to anyone that uses a mod that allows you to shift click and pick up a block in your hands such as CarryOn, as well as Mekanism and Mekanism:Generators of course.

### Steps to reproduce

Have CarryOn installed, alongside Mekanism and Mekanism:Generators.

1: Get a heat generator.
2: Place lava inside of it.
3: Shift + Right click to pick up the gen.
4: Place down somewhere else.

Lava source block comes with it whilst also leaving the lava source block behind.

Here is a short video showing it too.

https://imgur.com/a/P1H1mJU

### Minecraft version

1.19.2 (Latest)

### Forge version

43.2.21

### Mekanism version

10.3.9 (Latest)

### Other relevant versions

carryon-forge-1.19.2-2.0.5.17.jar
MekanismGenerators-1.19.2-10.3.9.13.jar
Mekanism-1.19.2-10.3.9.13.jar

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

Isn't one for this issue

**Comment by thiakil** [comment]
That's a carryon bug, not really for us

**Comment by liviniumnetwork** [comment]
Will raise with CarryOn and link this post to them^, cheers.
