### ISSUE TITLE
Digiminer Textures

### ISSUE THREAD

**Issue by AngryDragonflyStudios** [mekanism/Mekanism#7869]
### Issue description

After compiling 9.15.23 (Latest) noticed the DigiMiner Textures are gone. 

### Steps to reproduce

1) make Digi Miner
2) Place down digi Miner

### Minecraft version

1.20.1 (Not yet released, manually compiled)

### Forge version

47.1.3

### Mekanism version

Current Dev Branch (Manually Compiled)

### Other relevant versions

n/a

**Comment by pupnewfster** [comment]
This is known some of the textures and models are WIP
