### ISSUE TITLE
Villagers/easy villagers not working

### ISSUE THREAD

**Issue by DarkholdUser** [mekanism/Mekanism#7870]
### Issue description

I am in an atm9 server with the 1.20.1 version of mekanism installed, and villagers dont take professions and the easyvillagers traders dont work.

### Minecraft version

1.20.1 (Not yet released, manually compiled)

### Forge version

47.1.3

### Mekanism version

10.3.9 (Latest)

**Comment by pupnewfster** [comment]
Just because your modpack has Mekanism installed doesn't mean it is the cause of whatever bug you are running into. We don't do anything related to villagers or villager trading so I don't see how we could be breaking it.

**Comment by DarkholdUser** [comment]
> Just because your modpack has Mekanism installed doesn't mean it is the cause of whatever bug you are running into. We don't do anything related to villagers or villager trading so I don't see how we could be breaking it.

Yea but we tested the modpack without mekanism, and the villagers worked without mekanism, so thats why

**Comment by pupnewfster** [comment]
Could you please provide the latest log? Maybe there is some error in it then that might show something or some connection with Mekanism, given as I stated we don't touch villagers in any way so I am truly at a loss for how we could be breaking it (unless it is maybe some other mod in the pack that has integration with mek that is broken on their end)

**Comment by DarkholdUser** [comment]
> Could you please provide the latest log? Maybe there is some error in it then that might show something or some connection with Mekanism, given as I stated we don't touch villagers in any way so I am truly at a loss for how we could be breaking it (unless it is maybe some other mod in the pack that has integration with mek that is broken on their end)

[latest.log](https://github.com/mekanism/Mekanism/files/12703158/latest.log)
