### ISSUE TITLE
Encountered exception while building chunk meshes

### ISSUE THREAD

**Issue by Micaxs** [mekanism/Mekanism#7878]
### Issue description

Renderring crash happens when placed down a heat exchanger.

### Steps to reproduce

Connecting energy pipe and added heat exchanger.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.3

### Mekanism version

10.4.0 (Latest)

### Other relevant versions

All the Mods 9 - 0.1.12

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/g6c21WE

**Comment by thiakil** [comment]
you'll need to update Embeddium
