### ISSUE TITLE
[1.20.1] Rain goes through energy cubes

### ISSUE THREAD

**Issue by ocram9** [mekanism/Mekanism#7879]
### Issue description

I'm not 100% sure if this is intended or not but rain goes straight through energy cubes (see screenshot).

![2023-10-03_17 58 57](https://github.com/mekanism/Mekanism/assets/49008532/e85146ee-3606-4208-9d16-923865c25804)

### Steps to reproduce

1. Place a energy cube in the air
2. Make it rain
3. Rain goes through

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.3

### Mekanism version

10.4.0 (Latest)

**Comment by thiakil** [comment]
I think that's just how minecraft works, since it's not a solid block

**Comment by pupnewfster** [comment]
Yeah, it isn’t necessarily intentional but it also isn’t unintentional.
