### ISSUE TITLE
industrial Turbine Menu not showing water output

### ISSUE THREAD

**Issue by Botkum** [mekanism/Mekanism#7881]
### Issue description

Whenever I open my Industrial Turbine (IT) the water output does not show for some reason

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

Forge - 43.2.14

### Mekanism version

Older

**Comment by AlexHgC** [comment]
Please post a picture ?

**Comment by thiakil** [comment]
Do you have saturating condensers?
