### ISSUE TITLE
Missing key in ResourceKey[minecraft:root / mekanism:robit_skin]

### ISSUE THREAD

**Issue by TinyPandas** [mekanism/Mekanism#7884]
### Issue description

Game crashes when Robit entity is expected in the UI.

### Steps to reproduce

1. Open anything that has Robit in REI view (ie: Recipe view for something craftable by Robit)

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.1

### Mekanism version

10.4.0 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/TinyPandas/8ccfe9fdc5133dbfcd8ceee27ec98ae8

**Comment by TinyPandas** [comment]
Versions tested with:

Roughly Enough Items: 12.0.665
Just Enough Item: 15.2.0.27

Might be something specific to my mod setup, but couldn't reproduce in Mekanism + REI/JEI setup. :(

**Comment by thiakil** [comment]
Looks like it may be getting a bad item definition, though it still shouldn't crash

**Comment by pupnewfster** [comment]
Could you please provide the servers log, and to confirm it isn’t a hybrid server or some sort of bungee cord proxy right?

**Comment by TinyPandas** [comment]
I don't have the server log, but it is reproducible in the modpack during a single player world.
To confirm: It is Forge only and no bungee cord proxy.

**Comment by TinyPandas** [comment]
I found the cause of this issue:

Cyanide: https://www.curseforge.com/minecraft/mc-mods/cyanide-forge

[latest.log](https://github.com/mekanism/Mekanism/files/12840525/latest.log)
[crash-2023-10-08_04.33.57-client.txt](https://github.com/mekanism/Mekanism/files/12840527/crash-2023-10-08_04.33.57-client.txt)
![image](https://github.com/mekanism/Mekanism/assets/10274646/a34c8009-4734-4ca1-bb8a-b6e09fa9083d)

**Comment by thiakil** [comment]
doesn't look like there's much we can do here, unless Cyanide's devs can tell us otherwise - it's failing to retrieve our default skin, which should always exist
