### ISSUE TITLE
bioethanol bucket crashes me

### ISSUE THREAD

**Issue by QTPieMuffet** [mekanism/Mekanism#7885]
### Issue description

bioethanol bucket crashes me
here is the crash log 

[crash-2023-10-08_11.42.38-client.txt](https://github.com/mekanism/Mekanism/files/12839728/crash-2023-10-08_11.42.38-client.txt)

### Steps to reproduce

1. start mc
2. make world
3. search up bioethanol bucket
4. crash

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.1 forge

### Mekanism version

Current Dev Branch (Manually Compiled)

**Comment by thiakil** [comment]
not mekanism, we don't do a custom model for that. One of your other mods is doing weird things with rendering
