### ISSUE TITLE
QIO drives empty after upgrade from 1.18.2 to 1.19.2 (forge)

### ISSUE THREAD

**Issue by comical-uk** [mekanism/Mekanism#7886]
### Issue description

Hi

we upgraded a magma server running 1.18.2 to forge 1.19.2 , this was an 'in-place' upgrade to the same instal location on a dedicated machine

we have found that QIO drives are now empty and just wondered if you could suggest anything please, everything else was ok

is the QIO contents stored in specific files?

thanks!

### Steps to reproduce

1.) items were placed in a QIO drive on 1.18.2 (dedicated server - magma)
2.) forge was upgraded to 43.3.0 on 1.19.2
3.) 1.18.2 mods were removed
4.) 1.19.2 mods were added 
5.) no other files were moved/changed (manually)

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

43.3.0

### Mekanism version

10.4.0 (Latest)

**Comment by AlexHgC** [comment]
1.19.2 rewrited how the stored contents of QIO drives works, and make it not compatible from older files. See this commit : https://github.com/mekanism/Mekanism/commit/ccf003878c6d11bf6bd411070a3f5bd7f73fd7d0

**Comment by comical-uk** [comment]
thanks for the info
