### ISSUE TITLE
Crash immediately after world loads

### ISSUE THREAD

**Issue by Lucrecious** [mekanism/Mekanism#7888]
### Issue description

When loading into a multiplayer server, client crashes.
When loading in single player, the client loads, but the player ends up in a void, no terrain, no world loads.

Here's our world if it helps:
https://drive.google.com/drive/folders/1UGs9GtEb6cyWFwfoC6DdiRMn_Gpnaw0D?usp=sharing

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.3 Forge

### Mekanism version

10.4.0 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Lucrecious/c22f6be45c377e2da5fa90e5da1043ee

**Comment by thiakil** [comment]
Update embeddium. Report to them if it still happens
