### ISSUE TITLE
Infusion Factory Requires More gas than it should.

### ISSUE THREAD

**Issue by nathanfusselman** [mekanism/Mekanism#7890]
### Issue description

When creating a basic circuit, it is taking 4 redstone or 40mB for one iron when it should only take 1. It is also consuming the redstone even before it has the 4 required redstone making it just continue to take redstone but not produce output if it is slowly inserted.

### Steps to reproduce

1. Get ultimate infusion factory.
2. Place one Iron in factory.
3. Place 1 redstone in factory.
4. Watch it consume the redstone.
5. Place 4 redstone in factory.
6. Watch it consume all redstone and work but take 4x the redstone.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

1.20.1-47.1.3

### Mekanism version

10.4.0 (Latest)

### Other relevant versions

ATM9 0.1.12

**Comment by pupnewfster** [comment]
The injection factory does not accept redstone, do you by any chance mean infusing?

**Comment by nathanfusselman** [comment]
Sorry I edited it but I meant the infusion factory.

**Comment by thiakil** [comment]
what does the recipe in JEI show?

**Comment by nathanfusselman** [comment]
Sorry never mind, I found that it seems to allow for extraction now with the update and the is just pulling the redstone out.
