### ISSUE TITLE
Flamethrower deals damage when PvP is turned off

### ISSUE THREAD

**Issue by BloodInAs** [mekanism/Mekanism#7892]
### Issue description

Flamethrower deals damage when PvP is turned off

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.1

### Mekanism version

10.4.0 (Latest)

**Comment by pupnewfster** [comment]
I am unable to reproduce this. How are you disabling PVP? I tried setting it off in the `server.properties` and it functions as expected (doesn't do damage).

**Comment by pupnewfster** [comment]
While I couldn't reproduce, https://github.com/mekanism/Mekanism/commit/c17cf16b79a2b5d88cb7943fe6d733b6cf5c1ff9 does add an extra check related to this so hopefully that will cover whatever case you were running into.
