### ISSUE TITLE
the laser breaks blocks in a private region when it is not in a private region

### ISSUE THREAD

**Issue by BloodInAs** [mekanism/Mekanism#7893]
### Issue description

`'mekanism:laser'`
the laser breaks blocks in a private region when it is not in a private region

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.1

### Mekanism version

10.4.0 (Latest)

**Comment by pupnewfster** [comment]
Report to whatever mod is protecting the land, we fire the [block break event](https://github.com/mekanism/Mekanism/blob/244b531cdf43b69ba4aa2f78e49983485f594c3f/src/main/java/mekanism/common/tile/laser/TileEntityBasicLaser.java#L302C60-L302C60) so that mods can stop it when it shouldn't occur
