### ISSUE TITLE
1.20.1 : Rendering ingredient crash

### ISSUE THREAD

**Issue by Daltaxy** [mekanism/Mekanism#7894]
### Issue description

Hello.
I saw Mekanism came to 1.20.1; I hadn't played in a while so I added it as I really like this mod. Added it with the generators addon.
I start playing, experience other issues but whatever. I try to look up a recipe for an item I forgot (would know which one if another issue from Atlantis didn't prevent me from accessing my world right now)
As I click on the item on JEI, the game freezes then quickly crashes, generating a crash report.

### Steps to reproduce

1. open inventory
2. search an unrelated item on JEI
3. click on the item to see the recipe
4. crash (some mekanism recipe was probably somewhere in the tab that was about to open)
I can't remember the item sadly, I just know it's not a @Mekanism or Mekanism addon mod item.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.1 (probably NeoForge)

### Mekanism version

10.4.0 (Latest)

### Other relevant versions

Mekanism-1.20.1-10.4.0.14.jar, not sure where this stands
MekanismGenerators-1.20.1-10.4.0.14.jar

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

crash report: https://mclo.gs/GF0cEtb

**Comment by Daltaxy** [comment]
just clicked on "Mud Brick Stairs" from minecraft itself and it still crashed, probably any item

**Comment by pupnewfster** [comment]
See #7884 bug in Cyanide
