### ISSUE TITLE
Formulaic assemblers causing massive lag

### ISSUE THREAD

**Issue by creaper33** [mekanism/Mekanism#7895]
### Issue description

The Formulaic assemblers are causing massive lag when full. Using observable, we can see this. I'm using pipez with them

### Steps to reproduce

Make a formulaic assembler, provide power etc
Turn auto mode on
Start creating items when it is full
lag

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.3

### Mekanism version

Current Dev Branch (Manually Compiled)

**Comment by creaper33** [comment]
![2023-10-14_12 42 10](https://github.com/mekanism/Mekanism/assets/147256938/59f894f0-7d55-446f-ab5a-e5dda97e2d83)
![2023-10-14_12 50 47](https://github.com/mekanism/Mekanism/assets/147256938/773aa1dd-8239-4c6b-8f47-4f4e13fd04cc)
![2023-10-14_12 42 02](https://github.com/mekanism/Mekanism/assets/147256938/1a8719c8-78cc-4e86-a80e-1b2bbf3c9815)

**Comment by thiakil** [comment]
Microseconds per tick is nothing. Please provide a profiler dump
