### ISSUE TITLE
The problem of rendering MekaSuit with the EpicFight mod

### ISSUE THREAD

**Issue by KaxelDreamhack123** [mekanism/Mekanism#7896]
### Issue description

When the battle mode (Epic Fight mode) is enabled, if the player has at least one part of the armor or all of it, then it will not follow the animation of the player's movement. This problem could be solved with the help of a Wiki provided by Yessman (Epic Fight Developer), which explains in detail how it can be fixed. However, despite any attempts to fix it, the armor both did not obey the player's animation and does not obey. The developers of Epic Fight are aware of this problem. Maybe the problem is in the player's rendering?

### Steps to reproduce

Download the Epic Fight and Mekanism mod. Put on the Mekasuit armor and turn on the battle mode, then try to do something, jump, fly, anything. 

There is such a problem on both 1.19.2 and 1.20.1

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.1

### Mekanism version

10.4.0 (Latest)

**Comment by pupnewfster** [comment]
I am fairly certain we already are [copying](https://github.com/mekanism/Mekanism/blob/244b531cdf43b69ba4aa2f78e49983485f594c3f/src/main/java/mekanism/client/render/layer/MekanismArmorLayer.java#L42) the part rotations and positions from the model to the armor.

**Comment by KaxelDreamhack123** [comment]
> I am fairly certain we already are [copying](https://github.com/mekanism/Mekanism/blob/244b531cdf43b69ba4aa2f78e49983485f594c3f/src/main/java/mekanism/client/render/layer/MekanismArmorLayer.java#L42) the part rotations and positions from the model to the armor.

so the problem is not because of the armor?

**Comment by pupnewfster** [comment]
I have no idea how EpicFight mod works internally but assuming they are updating the rotations and positions of the vanilla model's model parts I don't know why the MekaSuit would not work with it.
