### ISSUE TITLE
1.20.1 Crash when attempting to make components for Digital Miner

### ISSUE THREAD

**Issue by Zelioth** [mekanism/Mekanism#7897]
### Issue description

Players are having issues where the server will crash if they attempt to make some parts of the Digital miner. I believe the Robot. 
Crash report for Reference 

Server enviroment
Minecraft 1.20.1
Forge 47.2.1
Mekanism 10.4.0.14
Additions 10.4.0.14
Generators 10.4.0.14
Tools 10.4.0.14

### Steps to reproduce

Attempt to create the digital miner
crafting the components will crash server

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.1

### Mekanism version

10.4.0 (Latest)

### Other relevant versions

all mekanism mods 

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Zelioth/bbb52c72104a81143d34820fc470f94d

**Comment by thiakil** [comment]
This should be fixed in 10.4.1
