### ISSUE TITLE
extended vein mining not working in 1.16.5

### ISSUE THREAD

**Issue by Jevnaker** [mekanism/Mekanism#7898]
### Issue description

Hi i am unable to turn on the atomic dissasemblers extended vein mining feature in the configs for 1.16.5 i managed to get the other vein mining feature to work though but not the extended one which was the one i was hoping to use. 1.16.5-10.1.2 457 version

### Steps to reproduce

Get an atomic dissasembler look at its avaible modes then go to config and try to edit that to make it add the vein mining and extended vein mining modes. start game back up and see if it worked.

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

36.2.34 Forge

### Mekanism version

Older

**Comment by pupnewfster** [comment]
That feature was moved to the mekatool

**Comment by Jevnaker** [comment]
oh ok ill just downgrade my install to an version before this change was made then.
