### ISSUE TITLE
Tier 4 ore processing only triples output

### ISSUE THREAD

**Issue by Leah96xxx** [mekanism/Mekanism#7901]
### Issue description

The tier 4 ore processing setup only produces just a little over 3x, instead of 5x.
My setup is (I'll use iron as an example):
- Dissolution chamber (1 Block of raw iron = 6000mb dirty iron slurry OR 3 raw iron = 2000mb dirty iron slurry)
- Chemical washer (1mb dirty iron slurry = 1mb clean iron slurry)
- Chemical crystallizer (200mb clean iron slurry = 1 iron crystal)
- Injection chamber (1 iron crystal = 1 iron shard)
- Purification chamber (1 iron chard = 1 iron clump)
- Crusher (1 iron clump = 1 dirty iron dust)
- Enrichment chamber (1 dirty iron dust = 1 iron dust)
- Energised smelter (1 iron dust = 1 iron ingot)

I feel like at least one of those recipes should have more than 1 output item... Been a while since I played an older version, so I can't quite remember which one had more.

### Steps to reproduce

Follow ATM9 quest line for Mekanism to get tier 4 ore processing. Insert raw iron, get less than expected.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.3 Forge

### Mekanism version

10.4.0

### Other relevant versions

All The Mods 9-0.2.6

**Comment by AlexHgC** [comment]
Because you have to use iron ore, not raw. 

1 iron ore = 1000mb slurry = 5 iron crystal, so it's x5

**Comment by Leah96xxx** [comment]
So basically it's still balanced for pre 1.17?

**Comment by AlexHgC** [comment]
It works the same as pre 1.17 to get full ore multiplier, but have raw compatibility with less multiplier to avoid it being too OP with fortune
