### ISSUE TITLE
Oredictionificator doesn't accept "forge:raw_materials" tag

### ISSUE THREAD

**Issue by KaelaniRevyruun** [mekanism/Mekanism#7905]
### Issue description

Expected behaviour:
1: Open oredictionifier
2: Enter "forge:raw_materials/[material]"
3: Click tick to select filter
4: select item under the tag for output
5: click "save" to apply filter

Observed Behaviour:
1: Open oredictionifier
2: Enter "forge:raw_materials/[material]"
3: Returns "Unsupported Tag!"

(Tested with "Forge:raw_materials/lead")

### Steps to reproduce

1: Open oredictionifier
2: Enter "forge:raw_materials/[material]"

Scenario that led to this issue specifically was entering tag "forge:raw_materials/lead"

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

Forge 40.2.4 1.18.2

### Mekanism version

Older

### Other relevant versions

Mekanism build is Mekanism 10.2.5

**Comment by UnknownSerhan** [comment]
![image](https://github.com/mekanism/Mekanism/assets/69000972/5343b263-f227-4970-b0e2-c586252b6a48)

In 1.20.1, doesn't look like a problem. You are in an unsupported version of the mod.
