### ISSUE TITLE
Geiger Counter/Dosimeter Stuck at 99.999

### ISSUE THREAD

**Issue by ItsFoxy87** [mekanism/Mekanism#7908]
### Issue description

When using either the Geiger Counter or Dosimeter, each will always show 99.999nSv/h in Creative Mode, even when switching to Survival. I saw two other issues and each one said "Dosimeter shows how much radiation you've absorbed", but I shouldn't have absorbed any radiation. The Geiger Counter also shows 99.999 no matter the world or location I'm in, whether there's radiation or not. The Mekasuit Dosimeter has the same problem. Using the Geiger Counter for the first time always gives me the advancement "Oops, did I do that?"

### Steps to reproduce

1. Load any world in Creative
2. Right-Click while holding Geiger Counter or Dosimeter

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.3 Forge

### Mekanism version

10.4.0

**Comment by pupnewfster** [comment]
Is there radiation in the world or are you irradiated? If not then this is expected as 99.99 is the baseline background radiation

**Comment by ItsFoxy87** [comment]
That does make sense, as I just realised the mod was measuring in nanosieverts (nSv) instead of microsieverts (mSv). In my opinion, the mod should instead use mSv/h instead of nSv/h since 1 nSv is 1.0E-6mSv. According to the Candian Nuclear Safety Commission, the worldwide background radiation (accounting for human influence) is 2.4mSv, which in nSv would be 2,400,000nSv, which is a very big number for a small amount of radiation. Again, that's my opinion, just need to state this before people get mad at me lol.
