### ISSUE TITLE
Flamethrower usage causes game to crash. 1.20.1

### ISSUE THREAD

**Issue by SOVETSKAYA-CHERDACHNAYA-TABURETKA** [mekanism/Mekanism#7909]
### Issue description

Minecraft 1.20.1 Java edition, Forge 47.2.1, Mekanism 10.4.0.14 with addons MekanismAdditions, MekanismGenerators, MekanismTools. When the flamethrower is used with a right click, all game crashes. 

### Steps to reproduce

1. Install Forge 47.2.1
2. Install Mekanism 10.4.0.14 with all addons
3. Create any Minecraft world and log in
4. Give yourself a loaded flamethrower and use it with a right click

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.1

### Mekanism version

10.4.0

**Comment by pupnewfster** [comment]
Please provide the crash log
