### ISSUE TITLE
Nutritional Paste incorrect usage values

### ISSUE THREAD

**Issue by ThePyroGod** [mekanism/Mekanism#7910]
### Issue description

Consuming nutritional paste is supposed to be a configurable amount of mB per half hunger. The issue is the amount of mB consumed at 0.5 hunger missing vs a full bar of 10 hunger is exactly the same, being 128mB. 

Altering the config does not change the values, and I tested this thoroughly in all 3 versions of Mekanism-1.20.1

### Steps to reproduce

1. Have missing hunger points which require food, both high and low values.
2. Consume nutritional paste with both values.
3. The amount of paste consumed is the same.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 47.1.44

### Mekanism version

10.4.2 (Latest)

**Comment by a-a-GiTHuB-a-a** [comment]
In addition, the bucket of Nutritional Paste is _insanely_ underpowered, which is likely related to this bug in some way.

**Comment by pupnewfster** [comment]
I am unable to reproduce this issue, do you have a video or something with this occurring?

**Comment by ThePyroGod** [comment]
> I am unable to reproduce this issue, do you have a video or something with this occurring?

I'll get an example back to you then, will take a day or two
