### ISSUE TITLE
Personal chests are op.

### ISSUE THREAD

**Issue by Wdits** [mekanism/Mekanism#7913]
### Issue description

It completely replaces the idea of going to the end, and farming shulkers, or using backpacks from other mods, atleast make it expensive.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.0

### Mekanism version

10.4.2 (Latest)

**Comment by pupnewfster** [comment]
If you don't like an item's recipe for use in your modpack then just change it using a datapack, CraftTweaker, or KubeJS.

**Comment by Wdits** [comment]
> If you don't like an item's recipe for use in your modpack then just change it using a datapack, CraftTweaker, or KubeJS.

but it's needed for other crafts in the mod, i can't just ban the item
