### ISSUE TITLE
Some Mekanism tool/class causing CTD

### ISSUE THREAD

**Issue by MrFunEGUY** [mekanism/Mekanism#7914]
### Issue description

CTD randomly (from player perspective). Crash report lists a Mekanism class as the first issue. 

I am using the Minecolonies Dimensional Adventure modpack.

### Steps to reproduce

1. Play long enough

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.1

### Mekanism version

Current Dev Branch (Manually Compiled, specify git commit hash)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/GhEiTC2k

**Comment by pupnewfster** [comment]
`modify$dio000$injectArmor` I am going to guess someone is coremodding and making some assumption about something and breaking things
