### ISSUE TITLE
Mekanism.tools -- ClassCastException -- GlowArmor

### ISSUE THREAD

**Issue by Aves-Swiftflyer** [mekanism/Mekanism#7915]
### Issue description

ClassCastException on multiple occasions

```
The game crashed whilst rendering entity in world
Error: java.lang.ClassCastException: class mekanism.tools.client.render.GlowArmor cannot be cast to class net.minecraft.client.model.HumanoidModel (mekanism.tools.client.render.GlowArmor is in module mekanismtools@10.4.2 of loader 'TRANSFORMER' @6ad198c9; net.minecraft.client.model.HumanoidModel is in module minecraft@1.20.1 of loader 'TRANSFORMER' 
```

See full crash logs from two separate days here:
- https://github.com/Aves-Swiftflyer/CrashLogs/blob/main/MinecraftCrashReport/November-5/crash-2023-11-05_00.32.50
- https://github.com/Aves-Swiftflyer/CrashLogs/blob/main/MinecraftCrashReport/November-8/crash-2023-11-08_08.28.16-client.txt

There were also several occasion of "ClassCastException: Null" that can be seen in my CrashLogs repository that may be relevant. 

Occurred in the instant of the "MineColonies: Dimensional Adventure" modpack and was also reported by a couple other discord members using the modpack. If a member of the discord see "crash-report" channel for logs submitted by other players.

### Steps to reproduce

Entity (Skeleton/Zombie) spawning nearby with GlowArmor appears to be the cause.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.1 Forge

### Mekanism version

10.4.2 (Latest)

### Other relevant versions

MekanismTools-1.20.1-10.4.2.16.jar

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Aves-Swiftflyer/9bbecc2d96b32c41b9ddd79d4617fc3f

**Comment by pupnewfster** [comment]
Report to AzureLib Armor, they are entirely ignoring the fact that forge hooks means the armor isn't necessarily an instance of that: https://github.com/AzureDoom/AzureLib-Armor/blob/1.20.1/NeoForge/src/main/java/mod/azure/azurelibarmor/mixin/MixinHumanoidArmorLayer.java#L44

**Comment by izaschniuu** [comment]
any solve way?

**Comment by Aves-Swiftflyer** [comment]
> any solve way?

I solved it by disabling Mekanism.Tools.
I assume I'll have to keep it disabled until Azurelib and Mekanism collaborate and implement a fix.

**Comment by izaschniuu** [comment]
> > any solve way?
> 
> I solved it by disabling Mekanism.Tools. I assume I'll have to keep it disabled until Azurelib and Mekanism collaborate and implement a fix.

ooo, thank u broo

**Comment by izaschniuu** [comment]
> > any solve way?
> 
> I solved it by disabling Mekanism.Tools. I assume I'll have to keep it disabled until Azurelib and Mekanism collaborate and implement a fix.

i doesnt helped(( im just deleted it
