### ISSUE TITLE
Logistical Sorter (version 1.20.1-10.4.2.16) [ATM 9 - 0.2.14]

### ISSUE THREAD

**Issue by Thunder-Nova** [mekanism/Mekanism#7917]
### Issue description

In simple terms the ItemStack set to Max 1, with size mode on. Isn't working as intended. Where it should release 1 of each material. (both were set to Max 1), yet it empties the whole batch before going for the next material ignoring the max.

![image](https://github.com/mekanism/Mekanism/assets/31967337/20142bd2-77d7-4193-88e5-76f416d419c8)
![image](https://github.com/mekanism/Mekanism/assets/31967337/654890d2-b854-4bdc-a41a-bb42bbc36d6c)
![image](https://github.com/mekanism/Mekanism/assets/31967337/dc413b19-b907-4b52-a542-0cbf53e4f7a7)

I even tested it with Vanilla containers, instead of relying on another mod if they were the problem.

I use the Energizing Orb from powah for the best use of redstone since 1 item = 1 comparator's redstone power.

### Steps to reproduce

1. Use a Logistical sorter between 2 storages.
2. Set up 2 different Items with the ItemStack filters set to Max 1, Size mode On.
3. All other Filters should be Off (Single, RR, Auto)
4. Redstone detection should be set up to preferable state for quantity if using a redstone setup.
Powah is best used with Logistical Sorter over the years, here is a redstone example video: https://www.youtube.com/watch?v=seeDqBZ3u6E

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.3 Forge

### Mekanism version

10.4.2 (Latest)

**Comment by thiakil** [comment]
Sounds like it's working as intended, it starts at the top each time it's trying to send something
