### ISSUE TITLE
[1.20.1] Opening GUIs drops fps significantly

### ISSUE THREAD

**Issue by Vapaman** [mekanism/Mekanism#7919]
### Issue description

FPS drops by a significant amount when opening any GUI
its especially noticeable with GUIs that have animated elements

Few exambles below:
![2023-11-09_16 44 32](https://github.com/mekanism/Mekanism/assets/77460466/6737c923-dc87-4d1c-b8d4-417743835f2a)
![2023-11-09_16 45 21](https://github.com/mekanism/Mekanism/assets/77460466/5960873c-9b7b-4f6c-b927-b62a362b679f)

![2023-11-09_16 48 29](https://github.com/mekanism/Mekanism/assets/77460466/8b8c9f4f-7ee1-43e7-b069-0f4247a2badc)
![2023-11-09_16 48 38](https://github.com/mekanism/Mekanism/assets/77460466/b550a8e5-5e0f-41c9-ac21-9d09336157a0)

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.79

### Mekanism version

10.4.2 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Vapaman/9fa95fdb8145d8f4d33c2bc8aef62f9e

**Comment by thiakil** [comment]
this should be better in 10.4.5, but make sure you compare to a vanilla gui. They will all be slightly lower fps than the world, especially when JEI is showing
