### ISSUE TITLE
Advanced Purifying Factories Bug

### ISSUE THREAD

**Issue by harinezumisan** [mekanism/Mekanism#7920]
### Issue description

There was a problem with Advanced Purifying Factories.　We had built and used a triplication line, but it stopped working, and when we investigated the cause, we found that it was due to a bug in Advanced Purifying Factories.
I was feeding items through the item pipe, but they would not go in and I could not manually feed them into the slots before processing.
I then created Purifying Factories again, but I was unable to process the gemstones, although I am not sure if this was a server bug or not.
Solo play is not a problem.
I will send you the video if necessary.
I'm submitting it again because it seems to have been closed on its own.
Please investigate properly. Please don't try to leave the bug. Please take the time to fix it.

### Steps to reproduce

(1) Assemble the triplication line and run it for several hours.
(2) I think that the phenomenon of being unable to process will occur sooner or later.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge47.1.3

### Mekanism version

10.4.2 (Latest)

**Comment by harinezumisan** [comment]
Turns out he's a jerk who doesn't want to deal with bugs.
A guy who can't respond in good faith, really.
FK

**Comment by thiakil** [comment]
Maybe if you actually read my reply on your other issue before adding a jerky reply
