### ISSUE TITLE
Changing the Security of Personal Chests/Barrel in Offhand Causes Desync

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#7923]
### Issue description

When we open a personal chest/barrel in offhand and try to change the security mode, it doesn't show that we changed the mode. When we open the chest in main hand, the security mod updates to whatever we changed it to.

### Steps to reproduce

1. Have a personal chest/barrel that you own.
2. Put it in your offhand and open it by right clicking into air.
3. Try to change the security mode, it will look like it doesn't change.
4. Move the chest to main hand and open it.
5. The security mode will be updated.

https://github.com/mekanism/Mekanism/assets/69000972/1297d426-3939-4259-a195-83b197e5d4fa

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge - 47.2.4

### Mekanism version

10.4.4 (Latest)

**Comment by pupnewfster** [comment]
Seems vanilla doesn't synchronize the offhand while in GUIs by default... slightly annoying but definitely will be possible to fix when I figure out how I want to go about ensuring it is sync'd
