### ISSUE TITLE
Latest update breaks GUI

### ISSUE THREAD

**Issue by g45635g** [mekanism/Mekanism#7924]
### Issue description

After latest update (10.4.4.18), right clicking anything to open its GUI will randomly cause it to glitch out. Tested and does not occur in previous update (10.4.4.16), only the most recent one.

![2023-11-13_19 12 00](https://github.com/mekanism/Mekanism/assets/123435316/9472f6ba-a4fb-40f5-b69d-2b55830cb3ad)
![2023-11-13_19 13 38](https://github.com/mekanism/Mekanism/assets/123435316/7b0192da-c2c1-4cc5-bec7-b3bb0cf91b10)
![2023-11-13_19 01 13](https://github.com/mekanism/Mekanism/assets/123435316/c4672700-5b45-4a6a-b148-046ec31c3d30)
![2023-11-13_19 11 56](https://github.com/mekanism/Mekanism/assets/123435316/ba7a07ba-f775-4424-9392-eb3d1c8ecbdf)
![2023-11-13_19 00 54](https://github.com/mekanism/Mekanism/assets/123435316/d34c0796-1c9a-4682-abe8-b42bb8b3e329)

### Steps to reproduce

1. Right Click on different machines to open their GUI
2. GUI starts to glitch out as shown in screenshots

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.0 Forge

### Mekanism version

10.4.4 (Latest)

### Other relevant versions

Initially ran into this issue in FTB Presents Direwolf20 1.20 modpack after it updated to 1.6.0 today. Went to test with only Mekanism installed and the same issue started to occur, confirming the issue isn't related to other mods.

**Comment by thiakil** [comment]
Fixed in 10.4.5
