### ISSUE TITLE
Electrolytic Seperator cannot accept water

### ISSUE THREAD

**Issue by Crystalined** [mekanism/Mekanism#7926]
### Issue description

The electrolytic separator cannot accept water in order to produce hydrogen and oxygen.

### Steps to reproduce

While in ATM 9 Pack was trying to pipe water from a sink (used both Pipez and Xnet) into an electrolytic separator and even though the pipes would connect they would never allow water into the electrolytic seperator.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge - 47.1.3

### Mekanism version

10.4.2

**Comment by thiakil** [comment]
Duplicate #7845 #7831
