### ISSUE TITLE
1.20.1 When the chunk is rebooted, the Mekanism wires stop transferring energy from the panel

### ISSUE THREAD

**Issue by BloodInAs** [mekanism/Mekanism#7928]
### Issue description

I installed the wires, connected them to the panels, went to spawn, returned and the wires stopped, the energy stopped being transmitted from the panel

### Steps to reproduce

1. I installed the wires and connected them to the solar panels, 2. went to spawn,3. returned and the wires stopped, energy stopped being transmitted from the panel

Mekanism-1.20.1-10.4.1.15

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 47.2.1

### Mekanism version

10.4.5 (Latest)

**Comment by thiakil** [comment]
have you tried using Neoforge? Please also add a full mod list
