### ISSUE TITLE
nuclear (fission) reactor exploded while not loaded

### ISSUE THREAD

**Issue by Underbeta** [mekanism/Mekanism#7930]
### Issue description

I was trying to assemble a nuclear fission reactor and had managed to assemble it correctly, but when I reopened the server the reactor had exploded, as I had just reopened the server there was no other player in the world, this problem had happened before but no one was near the reactor. Possibly this related to not loaded Chunks
This server is running a custom mod pack

### Steps to reproduce
0.Only works in a server
1.Build a reactor and a working turbine
2.Move away from turbine and reactor (enough to not load) or close the server
3.Approach the reactor or open the server

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

36.2.39

### Mekanism version

Older

### Other relevant versions

Not shure

**Comment by UnknownSerhan** [comment]
For a fission setup to work properly, you need to chunkload every part of the setup. If the chunks get unloaded, your setup is very likely to fail and cause a meltdown.

**Comment by thiakil** [comment]
Things can't explode when not loaded, so it must have been loaded _somehow_ and likely your supporting infrastructure wasn't.

Your best bet is to try keep in a single chunk or ensure it is properly chunkloaded
