### ISSUE TITLE
SPS multiblock causes insane server lagg

### ISSUE THREAD

**Issue by Jermain6066** [mekanism/Mekanism#7933]
### Issue description

We run a decently sized Direwolf20 1.20 modpack server which has recently had some players reach the stage of endgame mekanism. When they setup the SPS multiblock we reached the problem of our entire server just dying out of the blue. 

### Steps to reproduce

Start the SPS mutliblock 
instand drop of tps to 9 avarage with a 80ms increase in mean tick time

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Neoforge

### Mekanism version

10.4.4

**Comment by thiakil** [comment]
Need more details, like the exact setup around the sps and some profiler logs (visualvm, spark, etc)

Having done it myself on that pack, I can assure you it's not just the sps

**Comment by Jermain6066** [comment]
I have found the issue it was due to the multiblock being in more then 1 chunk once it as moved into a single chunk the lagg was gone
