### ISSUE TITLE
Industrial Reborn EU support

### ISSUE THREAD

**Issue by NospamNospam** [mekanism/Mekanism#7934]
### Issue description

Said on wiki that Mekanism supports EU energy, when in fact it doesn't and all the issues regarding this are closed as "not planned" because there is "no stable API" in any EU-mod people ask about. Does Industrial Reborn also not have a stable API?

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

40.2.13 Forge

### Mekanism version

Older

**Comment by thiakil** [comment]
When the wiki was written, ic2 was the only one that existed. Not classic, not whatever reborn is

**Comment by NospamNospam** [comment]
> When the wiki was written, ic2 was the only one that existed. Not classic, not whatever reborn is

reborn is https://github.com/Maciej916/Industrial-Reborn

**Comment by pupnewfster** [comment]
No idea if this will get done but please open a feature request as this is not actually an issue... not to mention it isn't on the latest version of MC yet and on top of that their curse page has this:
> THIS MOD IS CURRENTLY NOT MAINTAINED AS WE ARE NOW WORKING ON REWRITING IT

**Comment by NospamNospam** [comment]
> No idea if this will get done but please open a feature request as this is not actually an issue... not to mention it isn't on the latest version of MC yet and on top of that their curse page has this:
> 
> > THIS MOD IS CURRENTLY NOT MAINTAINED AS WE ARE NOW WORKING ON REWRITING IT
I will open such a request. But I don't understand what the lack of an announced feature has to do with versions or the intention of the author of the other mod to someday rewrite it.

**Comment by thiakil** [comment]
We don't specify "every EU of every mod" so it's not a lack of a feature, you're just not using the mod it was designed around
