### ISSUE TITLE
Mekanism invalid fluid for a tank

### ISSUE THREAD

**Issue by xXshadowWolf** [mekanism/Mekanism#7938]
### Issue description

Mekanism is giving me a Crash error saying invalid fluid for a tank And I want an even using any tanks I was setting up the Turbine with the fusion reactor

### Steps to reproduce

[crash-2023-11-23_14.35.32-server.txt](https://github.com/mekanism/Mekanism/files/13453174/crash-2023-11-23_14.35.32-server.txt)
[debug.log](https://github.com/mekanism/Mekanism/files/13453176/debug.log)

[crash-2023-11-23_14.38.58-server.txt](https://github.com/mekanism/Mekanism/files/13453175/crash-2023-11-23_14.38.58-server.txt)
[latest.log](https://github.com/mekanism/Mekanism/files/13453177/latest.log)

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.3

### Mekanism version

Current Dev Branch (Manually Compiled, specify git commit hash)

### Other relevant versions

BetterFusionReactor -1.20.1-1.4.5
JustEnoughMekanismMultiblocks-1.20.1-4.2
Mekanism-1.20.1-10.4.5.19
MekanismAdditions-1.20.1-10.4.5.19
MekanismGenerators-1.20.1-10.4.5.19
MekanismTools-1.20.1-10.4.5.19
Mekanism-MoreSolarPanels-1.20.1-1.5.7
MekanismWeapons-1.20.1-1.2
MoreMekanismProcessing-1.20.1-4.0

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)
[crash-2023-11-23_14.38.58-server.txt](https://github.com/mekanism/Mekanism/files/13453228/crash-2023-11-23_14.38.58-server.txt)
[crash-2023-11-23_14.35.32-server.txt](https://github.com/mekanism/Mekanism/files/13453229/crash-2023-11-23_14.35.32-server.txt)

_No response_

**Comment by thiakil** [comment]
Looks like some mod has removed water from the water tag or is otherwise messing with tags.

Youll need to remove mods until it stops. I'd suggest starting with sinytra and the fabric mods
