### ISSUE TITLE
solar neutron activators think they can't see the sun

### ISSUE THREAD

**Issue by jlp1528** [mekanism/Mekanism#7940]
### Issue description

Every time I reload my world, I have to place and break blocks above my solar neutron activators to get them to work. Please investigate so I don't have to set up some janky timer system for the piston reset trick I came up with.

It's possible I have placed them too high and the issue does not manifest at lower Y-levels, but it should not matter. If they can see the sun, they should work and they should not stop working unless they legitimately can't see the sun for some reason.

### Steps to reproduce

1. Place a solar neutron activator.
2. Put nuclear waste in them.
3. Reload world.
4. SNA stops working.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.76 NeoForge

### Mekanism version

10.4.5 (Latest)

**Comment by jlp1528** [comment]
Note: Direwolf20 1.20 pack (1.7.0)

**Comment by thiakil** [comment]
Where are you placing them exactly? And in what dimension?

I had no troubles in dw20

**Comment by jlp1528** [comment]
Overworld, Flower Forest biome, Y-level 136 on top of an Industrial Turbine.

**Comment by thiakil** [comment]
Closing as related ftb bug closed
