### ISSUE TITLE
Amor-Bypassed Damage does not have proper protection

### ISSUE THREAD

**Issue by TheROFL98** [mekanism/Mekanism#7942]
### Issue description

When the MekaSuit is charged to any capacity and takes damage from a source that bypasses armor, it acts as if I didn't have any armor at all. However, when the MekaSuit is discharged and falls back to netherite armor, it is able to sustain some damage.

I'm not asking for the MekaSuit to ignore any armor-piercing damage, rather I'm asking for it to act like regular armor when armor-piercing damage is received, as the behavior is different when the suit is charged vs. not charged.

### Steps to reproduce

1. Wear MekaSuit, discharged
2. Take damage from something that bypasses armor (i.e. Immersive Engineering Railgun)
3. Take note of how much health is lost
4. Heal up and charge the MekaSuit
5. Take damage again from the same source
6. Take not of how much health is lost this time

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

43.3.5

### Mekanism version

Older

**Comment by UnknownSerhan** [comment]
“Armor-piercing” damage bypasses all armor stats, if you take armor piercing damage from a source, having any armor won’t have any effect because it is “bypassing” the armor. MekaSuit has armor stats just like all the other armors in the game, but it doesn’t matter what stats it has, because the armor-piercing damage you take “bypasses” all of that.

**Comment by TheROFL98** [comment]
Other armors, including the Refined Obdisian armor, seem to resist the attacks just fine however. When I manually buff the armor stats for the MekaSuit and discharge it completely it sustains the damage, reducing the user's health by 4 hearts. When it's charged and I get the same attack all of my health drops.

**Comment by TheROFL98** [comment]
Ok taking a closer look it seems to affect just the railgun for some reason

**Comment by pupnewfster** [comment]
No idea, but if it is just the railgun I am guessing they intentionally do something to fully bypass protection rather than just have part of it bypassed.
