### ISSUE TITLE
Cable and Pipe - Logic Question

### ISSUE THREAD

**Issue by xhytenzhi** [mekanism/Mekanism#7944]
### Issue description

Its about Capacity and transmission rate:
During the config, cables can only be changed in puffer. Alright, but it would be nice to set upn a transmission rate, for example 256FE/t ( not for each, in summary ). It is not logical, that a row of 10 cables have a 10 times more output, thana single one. Example from IndustrialCraft: copper cable transmiss 128EU, no matter how many. Thats the way it should be.

After that i had a look at the mechanical pipes. There i can setup a puffer and also pull-amount. Sounds fine. Puffer stacks within all cables, thats correct functional. But i dont get it, why also the pull-amount stacks. When i have a pipe with 1l of water pull-amount, it wont get more when my pipe gets longer... it should stay at 1l of water.

Is there any way to setup a logical config?

Else, there is no reason for building better cables/pipes than Basic, because i can stack all values endless. I can build some kind of energy Cube out of cables.. it just takes more space, but my output rate and puffer increases..

Am i the only one who thinks this is wrong?

All Version the same issue.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

0

### Mekanism version

10.4.5 (Latest)

### Other relevant versions

ALL

**Comment by thiakil** [comment]
> Is there any way to setup a logical config?

not in the way you want

> Am i the only one who thinks this is wrong?

No
