### ISSUE TITLE
Speed Upgrade increases amount of fuel needed to perform an operation

### ISSUE THREAD

**Issue by Ponanoix** [mekanism/Mekanism#7945]
### Issue description

I have noticed that Speed Upgrade in Mekanism, besides multiplying the speed by 10 and cost by 100, also multiplies the amount of additional fuel needed to perform an operation by 10. This means that in, for example, Chemical Injection Chamber, normal amount of Hydrogen Chloride needed to turn an ore into a shard is 200 mB, but with 8 Speed Upgrades it raises the cost to 2000 mB.

At the same time, Energy Upgrade decreases the electrical cost 10 times, but doesn't affect the fuel cost at all.

Question is, why does Speed Upgrade affect the amount of fuel needed in the first place, but even if so, then why doesn't Energy Upgrade decrease it?

I calculated that in order to break even in terms of fuel inflow for a SINGLE x10 speed Chemical Injection Chamber, one would need:
- Normal -> ~20 Chemical Infusers with x10 speed
- Basic -> ~60 Chemical Infusers with x10 speed
- Advanced -> ~100 Chemical Infusers with x10 speed
- Elite -> ~140 Chemical Infusers with x10 speed
- Ultimate -> ~200 Chemical Infusers with x10 speed

I doubt this was intentional, that's why I am reporting this issue

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 47.2.14

### Mekanism version

Current Dev Branch (Manually Compiled, specify git commit hash)

### Other relevant versions

I think this has always been the case

**Comment by thiakil** [comment]
Gas upgrades exist
