### ISSUE TITLE
BlockCollisions.computeNext

### ISSUE THREAD

**Issue by Sultia** [mekanism/Mekanism#7947]
### Issue description

When item touches liquid lithium server tick freeze

### Steps to reproduce

Pour bucket of lithium on the ground

Throw item into liquid

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 47.2.6

### Mekanism version

10.4.5 (Latest)

### Other relevant versions

create 0.5.1.f
ad_astra_giselle_addon 1-5.8
balm 7.1.4
shetiphiancore 1.2
curios 5.4.3
attributeslib 1.2.0
corail tombstone 8.5.5
itemphysic full 1.6.16
ad_astra 1.15.5
netherportalfix 13.0.0
bookshelf 20.1.6
create steam n rails 1.5.3
customportalapi 0.0.1
smallships 2.0.0-a2.3.3
tofucraft 5.8.1.1
artifacts 9.2.0
irons_spellbooks 2.1.1
armourersworkshop 2.0.10
automobility 0.4.2
structure_gel 2.15.1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Sultia/d9db5af0e5cd204beef251acfebb6363

**Comment by thiakil** [comment]
Does it happen without item physic?

**Comment by Sultia** [comment]
Does not occur with Item physics out of the modpack, should I forward this to them then?

**Comment by thiakil** [comment]
Yup, our liquids don't do anything special
