### ISSUE TITLE
Jade is Showing Nothing/Wrong Stuff on Bounding Blocks

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#7948]
### Issue description

Having Jade and then looking at a bounding block doesn't show anything. If you were looking at another block before looking at the bounding block, Jade continues to show what you were last looking at.

### Steps to reproduce

1. Install Jade and Mekanism together.
2. Look at any bounding block, it will not show anything.
3. Look a different block then look at the bounding block, Jade will continue to show what you were last looking at before looking at the bounding block.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 47.2.14

### Mekanism version

10.4.5 (Latest)

**Comment by pupnewfster** [comment]
Is this on a dedicated server? I am not able to reproduce this in single player (but that might be because I am on 1.20.4 and maybe Jade fixed a bug on their end)

**Comment by UnknownSerhan** [comment]
Can't reproduce on 1.20.4, seems to be fixed.
