### ISSUE TITLE
Mekanism Mekasuit is not rendering in OculusMC 1.20.1 Forge.

### ISSUE THREAD

**Issue by ghost** [mekanism/Mekanism#7951]
### Issue description

Mekasuit is invisible.

### Steps to reproduce

put you mekasuit on and activate shader.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

forge 47.2.8

### Mekanism version

10.4.5 (Latest)

### Other relevant versions

oculus-mc1.20.1-1.6.9
ComplementaryUnbound_r5.1.1

**Comment by UnknownSerhan** [comment]
This is Oculus’s fault as they change the rendering stuff that Mekanism uses.

**Comment by ghost** [comment]
okay

https://github.com/Asek3/Oculus/issues/503
