### ISSUE TITLE
mekanism:atomic_disassembler_ore, #forge:ores

### ISSUE THREAD

**Issue by Sultia** [mekanism/Mekanism#7952]
### Issue description

Tag issue being thrown from forge for mekanism:atomic_disassembler_ore

log line 2146

### Steps to reproduce

Load mod along side all other mods in the pack

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.17 Forge

### Mekanism version

Current Dev Branch (Manually Compiled, specify git commit hash)

### Other relevant versions

Mod list in latest log

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Sultia/b7019cf738c73a586edefedb3cbdff73

**Comment by thiakil** [comment]
You're somehow missing the Forge ores tag. Something is wrong with your install
