### ISSUE TITLE
fps drops

### ISSUE THREAD

**Issue by deNStep123** [mekanism/Mekanism#7953]
### Issue description

When I look at the solar panel, my fps drops to 60-70 fps which feels like 25-30, but in general I have a stable 100-120+ fps

![5555](https://github.com/mekanism/Mekanism/assets/129552974/a1d2b3e2-bc81-426b-964f-e809854de66f)
![66666](https://github.com/mekanism/Mekanism/assets/129552974/d75fe27f-0ee3-4834-8a9b-7132fd83bb35)

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

43.3.0

### Mekanism version

Older

**Comment by UnknownSerhan** [comment]
Do you have Man From The Fog mod? It is either than mod or something else
