### ISSUE TITLE
[1.7.10] Curseforge not installing required Libraries

### ISSUE THREAD

**Issue by GroupXyz1** [mekanism/Mekanism#7956]
### Issue description

Curseforge does not install CodeChickenCore and Forge Multi Part which made me a hard time figuring out why my game is continoiusly crashing

### Steps to reproduce

Install Mekanism on 1.7.10 via CurseForge App

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

10.13.41614 Forge

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/Swe1n90H

**Comment by pupnewfster** [comment]
Marked forge multipart as required for the 1.7.10 versions so hopefully it should work properly now.
