### ISSUE TITLE
cardboard box deletes pipez upgrades

### ISSUE THREAD

**Issue by jlp1528** [mekanism/Mekanism#7958]
### Issue description

https://github.com/henkelmax/pipez/issues/213
Pipez author/contributor says this is an issue with Mekanism discarding all item entities and has linked a code blob.

### Steps to reproduce

1. Place an inventory.
2. Set pipez pipe to extract from inventory.
3. Add an upgrade to the extracting pipe.
4. Pick up inventory with cardboard box.
5. Pipez upgrade is deleted.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.76 NeoForge

### Mekanism version

10.4.5 (Latest)

**Comment by pupnewfster** [comment]
If the pipez blocks don't store their data in their nbt then they should add their blocks to the relocation not supported tag
