### ISSUE TITLE
crash when using a mekanism tool

### ISSUE THREAD

**Issue by Kvakochka** [mekanism/Mekanism#7959]
### Issue description

Meka-tool, when quickly breaking, throws kelp from the server
Upg: also paints when breaking sea grass
```
'mekanism:meka_tool'
'minecraft:kelp'
'minecraft:seagrass'
```

### Steps to reproduce

https://youtu.be/R6LGDlYc63E

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 47.2.1

### Mekanism version

10.4.5 (Latest)

### Other relevant versions

![image](https://github.com/mekanism/Mekanism/assets/148980088/7a48ccdb-b7ab-40a6-a30b-5405fdc83437)

**Comment by thiakil** [comment]
Need logs
