### ISSUE TITLE
Enhanced Jump doesn`t work

### ISSUE THREAD

**Issue by Kvakochka** [mekanism/Mekanism#7960]
### Issue description

Module not working
"Boost Jump"
Module:Powered Jump-`'mekanism:module_hydraulic_propulsion_unit'`

### Steps to reproduce

1) use this moduel
2) try to config it(moduel)
3) it doesn`t work

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 47.2.1

### Mekanism version

10.4.5 (Latest)

**Comment by jlp1528** [comment]
Confirming this issue. Could be a pack interaction but I don't know of anything else I'm using that would affect jump height.

**Comment by Ezio-realLOSTINSOUND** [comment]
You need to use the Boost key. Default is Ctrl. I had the same problem until i spammed ctrl while jumping and i jumped super high in the air. hope it works

**Comment by jlp1528** [comment]
Holy crap I can jump over 100 blocks in the air. Not sure if intended, nor if I have another jump height modifier. Probably both tbh. Anyway thanks! This also applies for uber fast flight! :D

**Comment by satonagrad1234** [comment]
Everything is as the people said, if you press ctrl, then jump boost works, but step assist (automatic climbing on the block) does not work.
I downloaded this version of the mod, and it only worked in single player mode, but it doesn't work on the server

![image](https://github.com/Gravity-Craft/Supports/assets/112409236/4f9eb31a-f2a8-4ae5-b1c2-de771800147e)

Mods on the server:
		saturn-mc1.20.1-0.0.6.jar
		dynamiclightsreforged-1.20.1_v1.6.0.jar
		CyclopsCore-1.20.1-1.18.10.jar
		notenoughcrashes-4.4.6+1.20.1-forge.jar
		supermartijn642configlib-1.1.8-forge-mc1.20.jar
		[C]braincabinet-1.20.1.jar
		geckolib-forge-1.20.1-4.2.2.jar
		HammerLib-1.20.1-20.1.14.jar
		connectivity-1.20.1-4.5.jar
		rubidium-mc1.20.1-0.7.1.jar
		Neat-1.20-35-FORGE.jar
		ForgeEndertech-1.20.1-11.1.0.0-build.0142.jar
		Prism-1.20.1-forge-1.0.5.jar 
		Placebo-1.20.1-8.3.7.jar 
		modernfix-forge-5.7.2+mc1.20.1.jar 
		citadel-2.4.3-1.20.1.jar
		mixinextras-forge-0.2.0-rc.2.jar
		moreoverlay-1.22.1-mc1.20.jar 
		balm-forge-1.20-7.0.7.jar
		FpsReducer2-forge-1.20-2.5.jar
		cloth-config-11.1.118-forge.jar
		shetiphiancore-forge-1.20.1-1.2.jar
		twilightforest-1.20.1-4.3.2145-universal.jar
		supplementaries-1.20-2.5.28.jar
		Emojiful-Forge-1.20.1-4.2.0.jar
		industrial-foregoing-1.20.1-3.5.15.jar
		FarmersDelight-1.20.1-1.2.3.jar
		torchmaster-20.1.4.jar
		HostileNeuralNetworks-1.20.1-5.1.3.jar
		endertanks-forge-1.20.1-1.2.jar
		CommonCapabilities-1.20.1-2.9.0.jar
		AmbientSounds_FORGE_v5.2.22_mc1.20.1.jar
		crashutilities-8.1.4.jar
		getittogetherdrops-forge-1.20-1.3.jar
		[Nova]mining_dimension-1.20.1-1.0.4.jar
		supermartijn642corelib-1.1.12a-forge-mc1.20.jar
		Botania-1.20.1-441-FORGE-SNAPSHOT.jar
		curios-forge-5.3.1+1.20.1.jar
		[C]IndustrialCraft-3-1.20.1.jar
		Patchouli-1.20.1-81-FORGE.jar
		oculus-mc1.20.1-1.6.9.jar
		elevatorid-1.20.1-lex-1.9.jar
		constructionwand-1.20.1-2.11.jar 
		architectury-9.1.12-forge.jar
		AI-Improvements-1.20-0.5.2.jar
		cupboard-1.20.1-1.9.jar
		productivebees-1.20.1-12.2.11.jar 
		trashcans-1.0.18a-forge-mc1.20.jar 
		chunkloaders-1.2.7-forge-mc1.20.jar 
		rubidium-extra-0.5.2+mc1.20.1-build.104.jar
		inventoryessentials-forge-1.20-8.0.0.jar 
		observable-4.4.0.jar 
		FastLeafDecay-31.jar 
		DivineRPG-1.10.6.1.jar
		SmartBrainLib-neoforge-1.20.1-1.12.jar
		clienttweaks-forge-1.20-11.0.0.jar 
		rhino-forge-2001.2.2-build.6.jar
		AdFinders-1.20.1-9.1.0.0-build.0142.jar 
		Fastload-Reforged-mc1.20.1-3.4.0.jar 
		ftb-library-forge-2001.1.3.jar
		ftb-teams-forge-2001.1.4-clean.jar
		item-filters-forge-2001.1.0-build.55.jar
		jei-1.20.1-forge-15.3.0.4.jar
		kubejs-forge-2001.6.3-build.45.jar 
		metalbarrels-1.20.1-1.jar
		AttributeFix-Forge-1.20.1-21.0.2.jar 
		Mekanism-1.20.1-10.4.5.19.jar 
		lemonlib-4.0.1.jar 
		reap-1.20.1-1.0.2.jar 
		FastSuite-1.20.1-5.0.1.jar 
		journeymap-1.20.1-5.9.12-forge.jar
		NaturesCompass-1.20.1-1.11.2-forge.jar
		LibX-1.20.1-5.0.5.jar
		Dungeon+Crawl-1.20.1-2.3.14.jar
		worldeditcui-1.20.1.jar
		mcjtylib-1.20-8.0.2.jar
		rftoolsbase-1.20-5.0.1.jar
		xnet-1.20-6.0.1.jar
		xnetgases-1.20.1-5.0.0.jar
		farsight-1.20.1-3.3.jar
		forge-1.20.1-47.2.1-universal.jar 
		bloodmagic-1.20.1-3.3.2-44.jar 
		ironchest-1.20.1-14.4.4.jar 
		ZeroCore2-1.20.1-2.1.40.jar
		ExtremeReactors2-1.20.1-2.0.76.jar
		client-1.20.1-20230612.114412-srg.jar 
		cofh_core-1.20.1-11.0.0.51.jar
		thermal_core-1.20.1-11.0.0.15.jar 
		thermal_integration-1.20.1-11.0.0.23.jar
		thermal_innovation-1.20.1-11.0.0.21.jar
		thermal_foundation-1.20.1-11.0.0.62.jar
		thermal_expansion-1.20.1-11.0.0.27.jar
		theoneprobe-1.20.1-10.0.1.jar 
		appliedenergistics2-forge-15.0.21-client.jar
		ae2wtlib-15.2.1-forge.jar 
		ExtendedAE-1.20-0.1.31-forge.jar 
		TerraBlender-forge-1.20.1-3.0.0.169.jar
		moonlight-1.20-2.8.21-forge.jar
		MouseTweaks-forge-mc1.20-2.25.jar
		titanium-1.20.1-3.8.25.jar 
		Re-Avaritia-forged-1.20.1-1.3.3.jar 
		ftb-quests-forge-2001.1.3.jar
		ftb-xmod-compat-forge-2.0.0.jar 
		ImmersiveEngineering-1.20.1-10.0.0-169.jar 
		CreativeCore_FORGE_v2.10.34_mc1.20.1.jar
		smoothboot-mc1.20.1-0.0.3.jar
		Ding-1.20.1-Forge-1.4.1.jar
		EnderIO-1.20.1-6.0.23-alpha.jar
		kffmod-4.5.0.jar
		jeiintegration_1.20.1-10.0.0.jar
		Iceberg-1.20.1-forge-1.1.15.jar
		LegendaryTooltips-1.20.1-forge-1.4.5.jar
		JAOPCA-1.20.1-4.4.1.2.jar
		FastWorkbench-1.20.1-8.0.2.jar
		experienceobelisk-v1.4.8-1.20.1.jar
		storagedrawers-1.20.1-12.0.2.jar
		FluxNetworks-1.20.1-7.2.0.14.jar
		enderchests-forge-1.20.1-1.2.jar
		entityculling-forge-1.6.2-mc1.20.jar
		canary-mc1.20.1-0.2.7.jar
		Applied-Botanics-forge-1.5.0.jar
		modonomicon-1.20.1-forge-1.39.0.jar 
		appleskin-forge-mc1.20.1-2.5.0.jar   
		Vampirism-1.20.1-1.9.2.jar    
		vampirism_integrations-1.20.1-1.8.0-beta.1.jar
		VampiresNeedUmbrellas-1.20.1-1.0.1.jar
		GodlyVampirism-1.20.1-1.0.6.jar 
		ferritecore-6.0.0-forge.jar 
		BetterF3-7.0.1-Forge-1.20.1.jar 
		Applied-Mekanistics-1.4.2.jar
		megacells-forge-2.2.9-1.20.1.jar
