### ISSUE TITLE
Charged energy tablet can't be moved by JEI for crafting recipe

### ISSUE THREAD

**Issue by Phoupraw** [mekanism/Mekanism#7962]
### Issue description

Charged energy tablet should able to be moved by JEI for crafting recipe.
![image](https://github.com/mekanism/Mekanism/assets/50520903/d90a34eb-3048-460a-84c9-060099ccc2bb)
![image](https://github.com/mekanism/Mekanism/assets/50520903/7b0e12ad-248e-443a-ab2a-4288350f915f)

### Steps to reproduce

1. Get some charged energy tablets.
2. Try applying a crafting recipe that needs energy tablet by JEI.
3. Unable to move ingredients.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.44

### Mekanism version

10.4.5 (Latest)

### Other relevant versions

Just Enough Items: 15.2.0.27

**Comment by thiakil** [comment]
Take it up with jei
