### ISSUE TITLE
Item Conflict with Immersive intelligence

### ISSUE THREAD

**Issue by SunnyJim53** [mekanism/Mekanism#7963]
### Issue description

When trying to create lithium with a thermal evaporation multiblock from brine the brine isn't Mekanism brine and mekanism'ss variant of brine isn't in JEI also there is a texture that isn't loading for the brine. The only brine that is loaded is immersive intelligence's brine with appears to be incompatible with mekanism for the creation of lithium. Note - The game doesn't crash upon interaction just the thermal evaporation multiblock doesn't complete the operation of turning immersive intelligence brine into lithium. 
<img width="197" alt="Screenshot 2023-12-19 122909" src="https://github.com/mekanism/Mekanism/assets/150128481/f3fe3e1d-743c-4416-88f1-eabb0978c8c4">
<img width="174" alt="Screenshot 2023-12-19 122902" src="https://github.com/mekanism/Mekanism/assets/150128481/42a35f98-ea36-4837-b410-cc98a31358b2">

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

Forge - 14.23.5.2860

### Mekanism version

Older

### Other relevant versions

Immersive Intelligence - 0.2.1

**Comment by thiakil** [comment]
That looks like more of a pack issue - there's no code that conditionally registers fluids on our end.

Also note we no longer support such old versions
