### ISSUE TITLE
Voice client ignores JVM proxy settings

### ISSUE THREAD

**Issue by NospamNospam** [mekanism/Mekanism#7964]
### Issue description

The client connection for walkie-talkies ignores the SOCKS proxy set in the JVM system properties and attempts to connect to the server directly.

### Steps to reproduce

1. Set a SOCKS proxy for the client JVM to use (via -DsocksProxyHost=X.X.X.X -DsocksProxyPort=YYYYY arguments for example)
2. Launch the game
3. See the attempted connection on the voice server port to the server address without a proxy

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

40.2.13 Forge

### Mekanism version

Older

**Comment by thiakil** [comment]
we don't do anything that would prevent the use of a proxy

**Comment by NospamNospam** [comment]
lol, I know. more like you just ignored the possibility of a proxy. the idea was to make you find out what in used libs or your code causes this, like proxy usage in jvm being not automatic or you using raw sockets instead of jvm transports. at least be honest and say you never planned this.

**Comment by thiakil** [comment]
Uh, no you misunderstand. The properties you mentioned are built in to Java. There should not be anything we need to do specially, as far as I know.

And improve your shitty attitude

**Comment by SanityVoice** [comment]
lol, it seems that GitHub doesn't delete comments just because you want it to :D
isn't it nice? despite you trying to hide the fact that you are a dumb arrogant snitch who is a shitty coder and doesn't have a clue what their code does, people can still know this ^.^
github is still a good platform, after all :D
