### ISSUE TITLE
Mekanism Armor And Tools don't have forge tags

### ISSUE THREAD

**Issue by DripThanos** [mekanism/Mekanism#7966]
### Issue description

Im not sure if this is an issue in the newer versions as well, but none of the items from the Tools addon for mekanism have the forge:tools tag or forge:armor tag respectively. This makes them incompatible with any recipe that requires "forge:armor" or "forge:tools", while also making sorting mob farm loot more difficult.

### Steps to reproduce

NA

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

Forge 40.2.10

### Mekanism version

Mekanism-1.18.2-10.2.5.465

**Comment by pupnewfster** [comment]
We added support for the tags once a standard was set in 1.19.2. We no longer are developing for mc 1.18
