### ISSUE TITLE
Uranium oxide not going inside of Chemical infuser

### ISSUE THREAD

**Issue by beefyyyy** [mekanism/Mekanism#7967]
### Issue description

When trying to make fissle fuel in All the mods 9 (version 9-0.2.32) , the chemical infuser didn't allow any Uranium oxide to come in. I've tried also putting the chemical oxidizer next to the Chemical infuser but i still didn't work. I have all the inputs and outputs all right but i still didn't work, (You can see it on the top part of the screen)
![2023-12-25_02 46 39](https://github.com/mekanism/Mekanism/assets/154580474/0ce9df44-026a-4c61-9ad5-ece0fac44386)
![2023-12-25_02 46 50](https://github.com/mekanism/Mekanism/assets/154580474/c6da1f05-d25c-43db-ac37-e60940a6706f)

![2023-12-25_02 46 28](https://github.com/mekanism/Mekanism/assets/154580474/22255651-d548-4801-bf42-3ed4968273fb)

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge - 47.2.16

### Mekanism version

10.4.5 (Latest)

**Comment by kittycloudz** [comment]
hello! i was wondering what the solution was here. I seem to be having the same issue and I've tried everything to solve it but nothing seems to be working for me.
