### ISSUE TITLE
Recipe missing for Ethylene to Liquid Ethylene

### ISSUE THREAD

**Issue by nick-selsby** [mekanism/Mekanism#7971]
### Issue description

No recipe seems to exist to make Liquid Ethylene. 
Seen in the Valhelsia 6 modpack. Haven't seen anyone else with this problem, either. 
See below:
- Ethylene gas in the pipe
- No ethylene in the Rotary Condensentrator (Both modes tried)
- No recipe shown on Roughly Enough Items (When pressing R on Liquid Ethylene)

![2023-12-30_01 15 41](https://github.com/mekanism/Mekanism/assets/92050082/a808eaed-a5d2-4612-b05a-1481eb210e2f)
![2023-12-30_01 15 59](https://github.com/mekanism/Mekanism/assets/92050082/258bdd9a-10d5-4025-8f10-cb0eb2df4318)
![2023-12-30_01 14 44](https://github.com/mekanism/Mekanism/assets/92050082/11280ddf-98e2-47e7-ba66-d0f3a1185f05)

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 47.2.18

### Mekanism version

10.4.5 (Latest)

**Comment by H4ckerxx44** [comment]
This has to be an issue with the modpack.

I have my own modpack in which I have only changed some smaller stuff leaving Mekanism mostly untouched.
I have this.
![grafik](https://github.com/mekanism/Mekanism/assets/56711385/f356bbc4-e52e-4c59-adcf-90c7d08bf59a)

The gas on the left is 
![grafik](https://github.com/mekanism/Mekanism/assets/56711385/8f689590-3023-4f9f-882b-a6bec499cbfd)
