### ISSUE TITLE
Mekanism recipes in JEI crashes game

### ISSUE THREAD

**Issue by LiterallyAidan** [mekanism/Mekanism#7972]
### Issue description

I'm on a server with my brother and some of his friends and we all have this issue. When looking at mekanism recipes in the JEI menu, we are able to see the recipes but the second we close the menu, the game crashes. I've been trying to look this up for a few days now to find a fix and I haven't been able to find one yet.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.17 Forge

### Mekanism version

10.4.5 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/5wXytU0S

**Comment by thiakil** [comment]
That's fabric screen api  crashing

**Comment by LiterallyAidan** [comment]
> That's fabric screen api crashing

Is there a way to fix it

**Comment by thiakil** [comment]
You'd have to ask the author of that mod

**Comment by nnotyan** [comment]
@LiterallyAidan have u found a fix?
