### ISSUE TITLE
Rotary Condensentrator not accepting Ethylene

### ISSUE THREAD

**Issue by alucard87pl** [mekanism/Mekanism#7975]
### Issue description

Pretty much as the title - haven't checked other gasses/liquids, as this is the first thing I used the Rot Con on this playthrough

### Steps to reproduce

1. Place Rot Con
2. power it sufficiently
3. put tank with liquid ethylene on top
4. set tank to auto eject, output on bottom
5. set Rot Con gas input on top
6. observe no Ethylene in input tank in Rot Con

This also happens when piping Ethylene into the machine, the input/output config doesn not seem to affect anything.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 47.2.18

### Mekanism version

10.4.5 (Latest)

**Comment by thiakil** [comment]
Have you set the condensentrator to the correct mode? (button on the top left of the gui)

**Comment by alucard87pl** [comment]
Yes. And I toggled it back and forth. Although, it **does work** in Single Player.
And I also noticed that in SP I can put a chem tank in the `-` slot,  but on SMP the chem tank "jumps" back under the cursor, still no Ethylene in the machine tank.

**Comment by thiakil** [comment]
Restart the server or trigger a recipe reload, something is stopping all the recipes from loading

**Comment by pupnewfster** [comment]
Closing/merging into #7831
