### ISSUE TITLE
Mekanism without Fission reactor blocks.

### ISSUE THREAD

**Issue by oshmyshogsh** [mekanism/Mekanism#7978]
### Issue description

I don't have any fission reactor part so I can't earn nuclear waste. Can anyone help? mekanism version:Mekanism-1.16.5-10.1.2.457.jar

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

36.2.34

### Mekanism version

Older

**Comment by UnknownSerhan** [comment]
Install Mekanism: Generators mod

**Comment by oshmyshogsh** [comment]
Thank you

**Comment by oshmyshogsh** [comment]
but can you give me a link

**Comment by oshmyshogsh** [comment]
I have now. Thank
