### ISSUE TITLE
Tin ore keeps kicking out my friend from server

### ISSUE THREAD

**Issue by Python498** [mekanism/Mekanism#7980]
### Issue description

So i use Mekanism on server(aternos) everything is fine but when my friend tries to join he get kicked out for tin ore not present in registry but he have the same version as me  and ecerything is smooth for me

but he has managed to join before, but now h can t

PS : idk where i should post this (reddit - mekanism , minecraft forge , here?)

Mekanism-1.18.2-10.2.5.465.jar

![Obrázok WhatsApp 2024-01-22 o 19 46 21_8bc20d83](https://github.com/mekanism/Mekanism/assets/81637514/e5b0687e-4326-4de8-80f7-1595a2910c2b)

### Steps to reproduce

1. have modded server
2. have unlucky friend
3. server kicks him(tin ore not in registry)

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

40.2.0

### Mekanism version

Older

**Comment by thiakil** [comment]
That's not a Mekanism ore listed, so you'll have to check the other mod

**Comment by Python498** [comment]
but Mekanism is only mod that has tin ore
mod list:
Applied-Mekanistics-1.2.2.jar
appliedenergistics2-forge-11.7.6.jar
caelus-forge-1.18.1-3.0.0.2.jar
cfm-7.0.0-pre35-1.18.2.jar
citadel-1.11.3-1.18.2.jar
ferritecore-4.2.2-forge.jar
iceandfire-2.1.13-1.18.2-beta-3.jar
ironchest-1.18.2-13.2.11.jar
Jade-1.18.2-forge-5.3.1.jar
JadeAddons-1.18.2-forge-2.5.0.jar
jei-1.18.2-forge-10.2.1.1002.jar
journeymap-1.18.2-5.9.7-forge.jar
Mantle-1.18.2-1.9.45.jar
Mekanism-1.18.2-10.2.5.465.jar
MekanismAdditions-1.18.2-10.2.5.465.jar
MekanismGenerators-1.18.2-10.2.5.465.jar
MekanismTools-1.18.2-10.2.5.465.jar
mekanismtweaks-1.1.jar
MoreMekanismProcessing-1.18.2-2.5.jar
origins-forge-1.18.2-1.18.2-1.5.0.1-fatjar.jar
ProjectE-1.18.2-PE1.0.2.jar
servercore-forge-1.3.5+1.18.2.jar
TConstruct-1.18.2-3.6.4.113.jar
Tinkers Reforged 1.18.2-2.0.8.jar
(at least what game shows)
![Obrázok WhatsApp 2024-01-23 o 13 29 14_a815db4a](https://github.com/mekanism/Mekanism/assets/81637514/4fadd1d6-9d5f-4e5d-b8e4-dd29b6238dbe)
only tin ore that showed

**Comment by Python498** [comment]
tried it on non mekanism server, everything went smoothly

**Comment by thiakil** [comment]
And yet it's not Mekanism listed in the missing object.

**Comment by Python498** [comment]
hmmm so you say that it isn t   the mod from which the ore comes? thank you .....

**Comment by Python498** [comment]
deeply sorry , it was Tinkers construct or Tinkers reforged
