### ISSUE TITLE
Refined Obsidian Paxel Instant mine?

### ISSUE THREAD

**Issue by PB-Bloor** [mekanism/Mekanism#7981]
### Issue description

In a single player creative world I made my self a refined obsidian paxel and gave it Efficiency V, Unbreaking III, Sharpness V and Mending. It has a maximum durability of 3000 has 18 attack damage and CAN instant mine stone. On a server I have with some friends I have the same paxel with the same enchantments and it has a maximum of 8192 durability, 20 attack damage and CAN NOT instant mine stone

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.0 Forge

### Mekanism version

10.4.5 (Latest)

**Comment by pupnewfster** [comment]
Honestly this sounds like the server and your client just have different configs for the stats of the paxel. Do you know that this isn't the case?
