### ISSUE TITLE
Personal Chest is not sortable or extractable/insertable with Quark's inventory modifications

### ISSUE THREAD

**Issue by DereC4** [mekanism/Mekanism#7986]
### Issue description

![image](https://github.com/mekanism/Mekanism/assets/53978637/916a61c2-9003-4121-8a66-5d7daf106719)

Default containers like chests and other mod containers allow for the sorting and easy extracting/filtered insertion of items, but Personal Chest GUIs don't seem to have this functionality. 

![image](https://github.com/mekanism/Mekanism/assets/53978637/d4d909c5-cb45-4632-aa28-6d5c26f82a07)

### Steps to reproduce

1. Open Personal Chest with Quark installed

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.2.0 Forge

### Mekanism version

Current Dev Branch (Manually Compiled, specify git commit hash)

**Comment by thiakil** [comment]
That's a quark feature, not a Mekanism one...

**Comment by DereC4** [comment]
> That's a quark feature, not a Mekanism one...

Do you know if the Personal Chest extends the Chest class?

**Comment by thiakil** [comment]
It does not
