### ISSUE TITLE
FloatingLong.java:1081 - NullPointerException

### ISSUE THREAD

**Issue by GlitchTech** [mekanism/Mekanism#7987]
### Issue description

My friend and I were playing and, at separate times, we both had the game crash out seemingly randomly. The only similarity is we were in the same area. Other players on the server were fine. So it all appears to be a client side bug.

`java.lang.NullPointerException: Cannot read field "value" because "this" is null
	at mekanism.api.math.FloatingLong.toString(FloatingLong.java:1081) ~[Mekanism-1.20.1-10.4.5.19.jar%23234!/:10.4.5]`

I _think_ it might be caused in game by the Digital Miner trying to read and output some value. Neither of us had a crash before I placed it (unpowered & unconnected to anything). It wasn't a consistent thing either. But I removed the miner and so far my game is stable again.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 47.2.18

### Mekanism version

10.4.5 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/GlitchTech/a6fac7b13853d546b35106c96c3e4caf

**Comment by thiakil** [comment]
It's not possible for `this` to be `null` unless your Java is doing some weird things
