### ISSUE TITLE
Metallurgic Infuser - Cant Infuse Iron with Redstone

### ISSUE THREAD

**Issue by ghost** [mekanism/Mekanism#7988]
### Issue description

I set up 5 Metallurgic Infuser (one for each infusing type). They where all running with all types of material to infuse. Sadly I cant Infuse iron with restone anymore. Infusing osmium with redstone is fine but as soon i put iron into the infuser, the single iron or even a stack of it apears in the slot for a second and getting returned into my inventory.

I also tryed to build a new infuser with a basic setup. Place it, power it, put Redstone (also tried with enriched redstone) in it and then the iron bars. > iron instandly gets back into my inventory. Then dump the redstone, put iron into it. The iron stays in it, but now i got the problem with redstone and enriched redstone. As soon as i try to put it into the infuser as infusing material, it gets back into my inventory. Same maschine in basic setup also works with redstone and osmium.
  

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

CurseForge v0.244.1.15948

### Mekanism version

10.4.5 (Latest)

### Other relevant versions

Mekanism 10.4.5.19
MekanismAdditions 10.4.5.19
MekanismGenerators 10.4.5.19
MekanismTools 10.4.5.19

Part of Valhelsia 6 via CurseForge

**Comment by IONayrus** [comment]
This sounds just like Issue #7845.
Cause when i try to put a basic tank with heavy water into the electrolyzer it also appears for a tick and is then put back into my inv.

Edit: Seems like theres been a bug hunt going on for almost half a year #7831

**Comment by pupnewfster** [comment]
Closing/merging into #7831
