### ISSUE TITLE
Conflict between 'Mekanism Tools' and 'Dungeons Mobs' mod

### ISSUE THREAD

**Issue by minibombardier** [mekanism/Mekanism#7990]
### Issue description

The game crashes when a mob from the 'Dungeons Mobs' mod spawns wearing armor from Mekanism Tools.

### Steps to reproduce

1.Download both Mekanism, Mekanism Tools and Dungeons Mobs
2.Wait for a Dungeons Mob to spawn wearing Mekanism Tools Armor
3.Game Crashes

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

Forge 43.2.21

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/EQWmm5Am

**Comment by thiakil** [comment]
Geckolib is doing something unsafe, report to them and/or Dungeons mobs
