### ISSUE TITLE
[1.20.1] Crash on pose energy cube

### ISSUE THREAD

**Issue by JLSkyzer** [mekanism/Mekanism#7991]
### Issue description

When i pose an purple energy cube my game crash

### Steps to reproduce

Start minecraft 1.20.1 with Mekanism-1.20.1-10.4.5.19
Try to pose an energy cube collide to a flux network power out

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.20

### Mekanism version

10.4.5 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/JLSkyzer/d7902eee431331e3ebcaa05f2d98463f

**Comment by thiakil** [comment]
You likely have some mod which is doing bad things outside the main thread. Unfortunately we can't offer much help there.

If you can reliably reproduce it, you'll need to do a binary search on your mod list

**Comment by pupnewfster** [comment]
Yeah, I don't see anything in that log that points to mekanism
