### ISSUE TITLE
Mekanism Ui issues

### ISSUE THREAD

**Issue by Chaotic02** [mekanism/Mekanism#7992]
### Issue description

none of the machines in mekanism open for more than half a second before it forcefully closes

### Steps to reproduce

1 install forge 1.18.2 (40.2.17)
2 install mekanism
3 make a world and try to open any machine

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

40.2.17

### Mekanism version

Current Dev Branch (Manually Compiled, specify git commit hash)

**Comment by CraftyZombie** [comment]
Can't seem to replicate this. Do you have any other mods installed?

**Comment by thiakil** [comment]
![c45994f](https://github.com/mekanism/Mekanism/assets/1788847/44598ea6-7d98-4ee4-b31c-60fc00e0ef37)

**Comment by Chaotic02** [comment]
mekanism is the only mod I have installed, and I have no idea how to read the logs

**Comment by thiakil** [comment]
There are plenty of guides on Google. It will vary based on your launcher

You just need to post the latest.log here

**Comment by Chaotic02** [comment]
[latest.log](https://github.com/mekanism/Mekanism/files/14186598/latest.log)

**Comment by thiakil** [comment]
There is something seriously wrong with your install. There are so many errors in that log I'm surprised you can even get into the game.

Please reinstall minecraft and Forge and then your modpack - you clearly have more than just Mekanism installed
