### ISSUE TITLE
QIO Hard Drive Clearing All Items

### ISSUE THREAD

**Issue by Jerome028** [mekanism/Mekanism#7993]
### Issue description

I transfered most of my items in storage to a Hyper-Dense QIO Drive that filled up around 70,000 items yesterday, when I loaded into the world today there was nothing in there, I put one item back into the drive and when I exited and entered the world that item was gone but when I did it again it the items didn't clear. How do I get my items back

### Minecraft version

1.19.x or earlier (No longer being developed)

### Forge version

Forge - 43.3.7

### Mekanism version

Older

### Other relevant versions

Mekanism version 10.3.9.13

**Comment by jaynotgay** [comment]
Did you find out what file to restore to get items back?
We have same issue and dont know what file to load as backup

**Comment by Jerome028** [comment]
Not really, I found out in the logs and the mekanism discord is that the way the qio data works is that it's a temp file and after you log out it gets renamed and put into the main data, however this shouldn't happen and a mod is likely to cause this (idk which one yet, but you can maybe find out with a binary search). Another suggestion was to manuelly rename the file but I couldn't do this since a overwrote the data by putting stuff in the qio after. I found that the data had all the stuff that I had previously with nbt but that was only half the data or something according to someone else and it had already been overwritten.

**Comment by Jerome028** [comment]
> Did you find out what file to restore to get items back? We have same issue and dont know what file to load as backup

Not really, I found out in the logs and the mekanism discord is that the way the qio data works is that it's a temp file and after you log out it gets renamed and put into the main data, however this shouldn't happen and a mod is likely to cause this (idk which one yet, but you can maybe find out with a binary search). Another suggestion was to manuelly rename the file but I couldn't do this since a overwrote the data by putting stuff in the qio after. I found that the data had all the stuff that I had previously with nbt but that was only half the data or something according to someone else and it had already been overwritten.

**Comment by thiakil** [comment]
Indeed, you need a full world backup to restore items - the Saved Data is just the definitions of the Types, the item contains the actual contents
