### ISSUE TITLE
Crashes when opening the inventory with both EMI and JEI installed

### ISSUE THREAD

**Issue by Kevadroz** [mekanism/Mekanism#7994]
### Issue description

EMI is a item and recipe viewer, much like JEI, however when both are installed EMI uses JEI as a backend, for mod compatibility.
When the three mods are installed opening the inventory chrashes the game with the next exception:
`java.lang.NullPointerException: Cannot invoke "mekanism.common.lib.attribute.AttributeCache.get()" because the return value of "it.unimi.dsi.fastutil.ints.Int2ObjectMap.computeIfAbsent(int, it.unimi.dsi.fastutil.ints.Int2ObjectFunction)" is null`
within the `ItemMekaTool.getAttributeModifiers` method.

### Steps to reproduce

1. Have Mekanism, JEI and EMI installed.
2. Open the game, enter a world.
3. Open the inventory, crash.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

47.1.98

### Mekanism version

10.4.5 (Latest)

### Other relevant versions

JEI: 15.2.0.27
EMI: 1.1.0+1.20.1+forge

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/Awc2DqBH

**Comment by nnotyan** [comment]
have u solved it?

**Comment by pupnewfster** [comment]
I am not able to reproduce this in 1.20.4, but also does this happen consistently? Given my best guess is that there is some sort of multithreading race condition going on, as that error really shouldn't be possible otherwise.

**Comment by Kevadroz** [comment]
> I am not able to reproduce this in 1.20.4, but also does this happen consistently? Given my best guess is that there is some sort of multithreading race condition going on, as that error really shouldn't be possible otherwise.

I just opened a world 2 times after updateng all my mods and it doesn't happen anymore, something may have fixed the bug.

**Comment by Kevadroz** [comment]
I can confirm that this issue still exists but it's just inconsistent. Try reloading the game and opening the inventory until it crashes.

**Comment by pupnewfster** [comment]
My guess is this no longer should be an issue given we now have native EMI compat, can you confirm if it still happens on the latest version?

**Comment by Kevadroz** [comment]
> My guess is this no longer should be an issue given we now have native EMI compat, can you confirm if it still happens on the latest version?

Does not seem to happen.
Just to be sure JEI compat is disabled when EMI is present right?
Also is the 1.20.1 branch no longer being updated?

**Comment by RedstoneWizard08** [comment]
Experiencing the same issue here.

**Comment by nnotyan** [comment]
> Experiencing the same issue here.

Hey. I solved this issue by deleting what i think was inventory management. The mod that lets u sort ur inventory by the click of a button. After i deleted it, it hasn’t happened again

**Comment by RedstoneWizard08** [comment]
Interesting. I'll give it a try when I have a chance.
