### ISSUE TITLE
Wind turbines cause extreme lag

### ISSUE THREAD

**Issue by LughtMon** [mekanism/Mekanism#7996]
### Issue description

When I look at the turbine at certain angle, my fps drops immediately. When I stare still on it, it stabilize the fps, but they are way lower than before (120 to 30 or less fps). With shaders it's even worse. I have old CPU (i5-7500), it is used almost 100% the whole time, but even with shaders there were no problem, I got about 60 fps. The blades seems to disform somehow. The issue occur on singleplayer, but even on multiplayer and that's interesting. When my friend stared at the blades, his fps dropped, but mine too.

Maybe a little offtopic, but I have installed also some other mods like Alex's caves and some mobs tend to dissapear from the screen at certain angle (similarity with the blades) but not just these mobs, players and other mobs tend to dissapear too. So I start to think, that there is problem somewhere else.

We both use TLauncher.
![image](https://github.com/mekanism/Mekanism/assets/159626781/f19974cd-ef63-4c00-8e7d-9f2f2335f618)

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Forge 1.20.1

### Mekanism version

10.4.5 (Latest)

**Comment by LughtMon** [comment]
I forgot to mention that I tried using newest forge version 47.2.20, also 47.2.0 - no change, issue remains.

**Comment by UnknownSerhan** [comment]
First of all, TLauncher is not supported. It would help if you also provided the mods you have.

**Comment by LughtMon** [comment]
> First of all, TLauncher is not supported. It would help if you also provided the mods you have.

TLauncher not beiing supported is quite a shame. I tried removing all mods and added just the Mekanism mods. Now it's fine, but do you know some way how to track the faulty mods?

**Comment by LughtMon** [comment]
Hi, I tried removing mods one by one and I have find out, that the issue was made by the mod "Man From the Fog".
