### ISSUE TITLE
Item bouncing in logistical transporters

### ISSUE THREAD

**Issue by Porcy** [mekanism/Mekanism#7998]
### Issue description

When using the transporters with either a storage drawer from "Storage Drawers" or a barrel from "Sophisticated Storage", they don't seem to detect that the destination inventory is full. Replace the inventory with a vanilla chest and it works like a charm. Now, I've seen this issue also happening with Pretty Pipes, so I'm not sure at what level this should be addressed: on Mekanism / Pretty Pipes side or on the Storage Drawers / Sophisticated storage side.
![2024-02-11_17 13 42](https://github.com/mekanism/Mekanism/assets/8096340/5c2bc2a2-ec8a-45b0-8e9f-dc6150b80d7b)

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

40.2.10

### Mekanism version

Older

**Comment by UnknownSerhan** [comment]
The logistical transporters are sending items depending on if the inventory still accepts them or not. Possibly they don’t mark their inventories as full so the transporters still end up trying to send items.

**Comment by Porcy** [comment]
Yeah, but I'm not sure if it's their job to mark the inventories as full. As I said, even the pipes from pretty pipes mod have this issue so I don't know if it's Mekanism's job to address or not. It doesn't happen with a vanilla chest. I mention it here just in case something easy can be done. I have a feeling inventory mods like Storage Drawers and Sophisticated Storage should also do something. Or maybe it comes from Forge...

**Comment by thiakil** [comment]
The drawers accept the item on simulation but reject it on actual insertion. It's the drawer's fault
