### ISSUE TITLE
[Regrowth][1.7.10][9.1.1.1031] "Ticking block entity" on world load. Connected to Auto Assembler from Enhanced Inventories

### ISSUE THREAD

**Issue by ppozniak** [mekanism/Mekanism#8000]
### Issue description

My world now crashes upon loading after like 2 seconds.
Removing Mekanism mod solves the issue, but it obviously removes all the blocks.

I just got new Logistical pipes and attached them to Auto Assembler from Enhanced Inventories. That pipe goes to JABBA barrel.
That Auto Assembler is connected to another Auto Assembler and also to another JABBA barrel.

Sorry for such a dinosaur 🦕 

### Minecraft version

1.19.x or earlier (No longer being developed)

### (Neo)Forge version

forge-1.7.10-10.13.4.1614

### Mekanism version

Older

### Other relevant versions

* Minecraft: `1.7.10`
* Forge: `10.13.4.1614`
* Regrowth (modpack): `1.0.2`
* Mekanism: `9.1.1.1031`
* CodeChickenCore: `1.0.7.46`

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/ppozniak/dd449d6373b96633b519bdb98dd3ef1d

**Comment by thiakil** [comment]
Sorry, we no longer even have development environments for 1.7.
The inventory it's connected to is likely doing something unexpected
