### ISSUE TITLE
Getting visual bug with any Energy Cube on high coordinates.

### ISSUE THREAD

**Issue by Oskal79** [mekanism/Mekanism#8004]
### Issue description

Getting visual bug with any Energy Cube on high coordinates, tried on spawn and around him in ~10k blocks not see problem, and my friends using /rtp on ATM 9 and live on ~2M blocks, and getting problems with energy cubes.
![NVIDIA_Share_y3QK32NED5](https://github.com/mekanism/Mekanism/assets/23283921/5cf09244-40a1-42b3-a1cc-ce842e281146)

### Steps to reproduce

1. Go to high cords on Minecraft 1.20.1 and place any energy cube.
2. Done.

### Minecraft version

1.20.1 (Latest)

### (Neo)Forge version

Not NeoForge

### Mekanism version

10.4.5

**Comment by SoccPuppet** [comment]
This seems to be a problem with loss of precision when you go too far, causing the cube's smooth animations to be more rounded and therefore look jittery, although it is strange how obvious it is at such a (relatively) low distance away from spawn
