### ISSUE TITLE
Cardboard boxes let you place water in the nether

### ISSUE THREAD

**Issue by EliConstructor** [mekanism/Mekanism#8007]
### Issue description

Cardboard boxes let you pick up and place waterlogged blocks in the nether, transporting the water with them. No other mods installed other than Mekanism and it's addons (additions, generators and tools).

### Steps to reproduce

1. Place cardboard box on waterlogged block (seagrass for example).
2. Pick it up.
3. Go to the nether
4. Place the cardboard box down.
5. Open it.
6. Water in the nether!

### Minecraft version

1.20.4 (Latest)

### NeoForge version

20.4.182

### Mekanism version

10.5.0 (Latest)

**Comment by pupnewfster** [comment]
The solution I think I am going to go for is:
- Don't allow unboxing things that can't have a bucket used to pick up the fluid from the block
- By default allow unboxing others and try to remove the fluid by picking it up as a bucket. Given there are chances this may not work for some modded implementations, I am also providing a config option to hard block unboxing even if a bucket can be used on the block.
