### ISSUE TITLE
Computercraft Integration Breaking On World Rejoin

### ISSUE THREAD

**Issue by DinnerBeef** [mekanism/Mekanism#8010]
### Issue description

Computercraft Integration Breaking On World Rejoin

Have Tested with both indication matrix and Dynamic Tank

### Steps to reproduce

1. Make a Dynamic
2. Hook a modem up to the tank
4. Use a computer to get the data from the tank
5. Relog
6. Use a computer to get the data from the tank. And it is missing most of the objects you should be able to call from the modem

### Minecraft version

1.20.4 (Latest)

### NeoForge version

20.4.193

### Mekanism version

10.5.0 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://s.dinnerbeef.com/gOXe5/nOBUdiNi75.mp4

**Comment by pupnewfster** [comment]
Forgot to link it from the commit's side but fixed via https://github.com/mekanism/Mekanism/commit/812e145306956ac6c10ed13a635adae468452828
