### ISSUE TITLE
Armor is not displayed

### ISSUE THREAD

**Issue by NABS2ER** [mekanism/Mekanism#8011]
### Issue description

I don’t see the armor I’m wearing, I thought the problem was in shaders or texture packs, but no, without them it’s the same, the armor just isn’t displayed
![2024-02-28_11 20 05](https://github.com/mekanism/Mekanism/assets/141981213/9904ca25-81ff-4175-9dd9-6f45621e808a)

![2024-02-28_11 23 11](https://github.com/mekanism/Mekanism/assets/141981213/c977a64d-e468-42b6-a0a3-e761f86ea98f)

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

forge 47.2

### Mekanism version

10.5.0 (Latest)

**Comment by NABS2ER** [comment]
Why did you close?

**Comment by NABS2ER** [comment]
There are a lot of threads here with this problem, but where is the solution, tell me!

**Comment by pupnewfster** [comment]
Bug in your shader mod

**Comment by NABS2ER** [comment]
Other armor from other mods is fine, which means there is a bug in mekanism. Tell me, is there a solution? The decision to disable shaders is not a solution

**Comment by NABS2ER** [comment]
You created such a big and cool mod, is it really a problem for you to fix a constant error with your armor, which all users who play with shaders have, and more than 70% of players play with shaders! I just can't believe you can't fix this! most likely you just don’t want, as a deliberate detriment to the players, for them to play without shaders or without your mod! Please solve the problem, you just need to correct a line in the code and everything will work, I’m sure! 5 minutes of work for you.
