### ISSUE TITLE
Resistive Heater Resets Consumption When Broken

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#8012]
### Issue description

After setting an energy consumption and breaking the resistive heater, the heater resets the consumption back to its default value, which is 40 FE. This also causes the energy stored in the resistive heater to be bigger than the internal buffer, causing the stored energy to get voided when the heater is placed.

### Steps to reproduce

1. Set a consumption to the heater and supply it with power.
2. Break the heater, check the stored energy of the heater while in item form.
3. Place the heater back, the consumption is reset.

![image](https://github.com/mekanism/Mekanism/assets/69000972/6a74b9d6-7f51-42a3-8075-565fb7d82b24)

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

47.1.99

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Turns out I fixed this already for 10.5.0's release as part of my move to attachments.
