### ISSUE TITLE
Speed of elytra module with jetpack boost depends on direction

### ISSUE THREAD

**Issue by jonab03** [mekanism/Mekanism#8015]
### Issue description

When boosting with a jetpack module while flying with an elytra module the speed depends on which direction you fly in.

I would expect the boost speed to remain identical regardless of direction.

Video demonstration of issue and demonstration of how fireworks function in comparison:

https://github.com/mekanism/Mekanism/assets/57867790/0b2f90b0-99da-458b-a6e5-74d8bacd00a9

### Steps to reproduce

1. Equip a mekasuit with both the elytra module
2. Take off and start boosting in a direction
3. Measure the speed and notice how it increases as you turn southeast and decreases as you turn northwest.

### Minecraft version

1.20.4 (Latest)

### NeoForge version

20.4.190

### Mekanism version

10.5.2 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/jonab03/1ad1759eaa66d5095fb61c30812a3fac

**Comment by pupnewfster** [comment]
What is the mod that is displaying the altitude and speed? It might help when it comes to testing and fixing this, to making sure it actually is fixed.

**Comment by pupnewfster** [comment]
Also I am fairly certain that once we merge #7475 this will be addressed, though even once that is released, I likely will leave this open until someone is able to confirm.

**Comment by jonab03** [comment]
The overlay is provided by [Elytra Auto Flight](https://modrinth.com/mod/auto-elytra-flight). 

I also went ahead and compiled a build off of the PR you mentioned and that does indeed fix the issue, thanks!

**Comment by pupnewfster** [comment]
That's great to hear; just keep in mind that PR is off of an older commit of 1.20.4, so it might contain other bugs or issues that are fixed in the current released version of Mekanism (and thus you may want to wait until it is merged before using it in your world).

**Comment by jonab03** [comment]
I have no intention of using it on my main world, the issue was actually found on a 1.20.1 server I play on, I just make sure to reproduce issues in a clean instance with the lastest version, I don't expect this to be backported but I am glad that it will be fixed in future versions.
