### ISSUE TITLE
Recipe Menu Crash

### ISSUE THREAD

**Issue by DalekZED** [mekanism/Mekanism#8016]
### Issue description

While in the GUI for machines (the two I discovered this in are the Rotary Condensor and the Chemical Injection Chamber), if you follow the recipe link to the crafting menu (running JEI) on 1.20.1, then pressing escape will crash the game. Crash went to launcher, citing exit code 151 'crash while key press'.

Disabled some of the other mods I am running to see if that is the issue however did not disable all, issue persisted during these semi-complete tests.

### Steps to reproduce

1. Open Minecraft 1.20.1, Better MC pack with Mekanism and Refined Storage added.
2. Open GUI for Rotary Condensor or Chemical Injection Chamber.
3. Press Recipe link in GUI to open JEI screen for recipes pertinent to that machine.
4. Press 'Esc' key to exit menu.
5. Crash out to launcher.

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

na

### Mekanism version

10.5.1

**Comment by thiakil** [comment]
Post your crashlog

**Comment by likmum001** [comment]
Hi,
I have same problem. Using BMC v32.5 with Mekanism, Ender IO and Create. When observing recipes in JEI game sometimes (1 in 10) crashes when I press ESC with text crash while key press.
[2024-09-16-7.log.gz](https://github.com/user-attachments/files/17014879/2024-09-16-7.log.gz)
