### ISSUE TITLE
1.20.4 Item classification BUG

### ISSUE THREAD

**Issue by misaka10384** [mekanism/Mekanism#8017]
### Issue description

Classification system failure
![332bc1db19cee7607ff2757b0a660041](https://github.com/mekanism/Mekanism/assets/61707010/71ca7a35-814b-4f2a-bb68-5cbc894bde7e)

### Minecraft version

1.20.4 (Latest)

### NeoForge version

20.4.192

### Mekanism version

10.5.2 (Latest)

**Comment by thiakil** [comment]
You likely have auto eject turned on, which will export all items that don't match a filter.

Otherwise we can't help much because your video is very fast and we can't read the language
