### ISSUE TITLE
QIO Redstone adapter doesn't show colour on block model

### ISSUE THREAD

**Issue by thiakil** [mekanism/Mekanism#8023]
### Issue description

![image](https://github.com/mekanism/Mekanism/assets/1788847/597a0378-b952-4c1f-9ad7-5214465f3834)

frequency on picked up item is rendering correctly, but when placed down or selected in UI, doesnt seem to show the frequency colour.

### Steps to reproduce

NB: found in dev

### Minecraft version

1.20.4 (Latest)

### NeoForge version

20.4.196

### Mekanism version

10.5.3

**Comment by pupnewfster** [comment]
Seems I accidentally broke it when doing https://github.com/mekanism/Mekanism/commit/fcfa71022c7e53aa9fabbdf5bf61595755af3850 because I forgot there was two different "states" of it being active that need to be handled.
