### ISSUE TITLE
MekaSuit Energy Units Don't Work

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#8024]
### Issue description

Installing energy units to the MekaSuit enlarges the energy buffer of the suit but doesn't allow charging more than the default energy buffer (6.40 MFE). It also wastes any energy that is being transferred to the suit.

### Steps to reproduce

1. Have any MekaSuit armor piece with energy units.
2. Try to charge the suit in any way.
3. The stored energy never goes more than 6.40 MFE.

### Minecraft version

1.20.4 (Latest)

### NeoForge version

20.4.196

### Mekanism version

10.5.4 (Latest)

**Comment by UnknownSerhan** [comment]
Could reproduce it once in a pack where Mekanism got updated from 1 or 2 older versions to latest. But made a fresh pack with 10.5.4 and couldn’t reproduce anymore.

**Comment by UnknownSerhan** [comment]
The above comment no longer applies, it still can be reproduced easily.

**Comment by hubertlejaune** [comment]
When first crafting the suit display was bugged (show 6.40MFE/1.63GFE) but
- charging was still working
- energy bar ahead of the armor bar was working
After a server reboot display still bugged but when charging energy is just "wasted" the energy bar doesn't increase

**Comment by jellyfishjoshua** [comment]
the same thing happens with the meka-katana added the energy unit and it doesn’t give more energy😔

**Comment by laportatie** [comment]
> the same thing happens with the meka-katana added the energy unit and it doesn’t give more energy😔

same problem still going.. is there anyone can solve?
