### ISSUE TITLE
Bioethanol Bucket crashes game/JEI

### ISSUE THREAD

**Issue by mvl666Darkrio** [mekanism/Mekanism#8025]
### Issue description

Searching for a Bioethanol Bucket in creative will crash the game and searching for it in JEI makes every item in JEI be an error
![2024-03-06_17 17 19](https://github.com/mekanism/Mekanism/assets/144204068/25250169-d22a-446f-8110-2009a142d17d)

### Steps to reproduce

1: Search for a Bioethanol Bucket in JEI or the Creative menu
2: Watch as either JEI or the entire game crashes, depending on where you searched for it.

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

Forge 47.2.0

### Mekanism version

Older

### Other relevant versions

JEI 15.3.0.1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/U69SGezQ

**Comment by thiakil** [comment]
looks like your shader mod is broken
```
Caused by: java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.Object2IntMap.getInt(Object)" because "this.uniformCache" is null
	at net.minecraft.client.renderer.ShaderInstance.redirect$zeh000$redirectGetUniformLocation(ShaderInstance.java:615) ~[client-1.20.1-20230612.114412-srg.jar%23374!/:?]
	at net.minecraft.client.renderer.ShaderInstance.m_173363_(ShaderInstance.java:348) ~[client-1.20.1-20230612.114412-srg.jar%23374!/:?]
```

**Comment by mvl666Darkrio** [comment]
The closest I can think of to a shader mod that I have is Rubidium.

**Comment by thiakil** [comment]
Yeah that's a likely culprit

**Comment by thiakil** [comment]
I'd recommend embeddium if you're able to swap it out, as the auther cares about mod compatibility

**Comment by mvl666Darkrio** [comment]
Yeah it was Rubidium, and Embeddium works perfectly! Thanks for the help!
