### ISSUE TITLE
Mekanism 10.4.5 PRC not accepting Liquid Ethylene

### ISSUE THREAD

**Issue by Undeadbear** [mekanism/Mekanism#8029]
### Issue description

In pack All the mods 9 0.2.41 Minecraft 1.20.1,  Forge 47.2.19

Playing on a small hosted server with 3 other people. I have seen liquid Ethylene in a machine.

Mekanism, Base +Generators + tools + Just Enough Mekanism multiblocks 4.2 and Applied mekanistics 1.4.2

Issue: PRC does not accept liquid Ethelyn, but does the gas form.

Have tried filling with Mekanism Mechanical pipe, EnderIO fluid conduit, Pipez fluid pipe.

Have tried to fill with the dropper in the UI.

Have tried every face of the block, changing settings with the configurator tool from the outside and via the UI.

Have tried multiple PRC's in multiple locations, with and withouth chunkloading or in base or in wilderness.

Could make subsrate 1 to 8 with Ethylene gas and water.

Unable to reproduce in a single player world in creative.

 

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

47.2.19

### Mekanism version

Older

**Comment by thiakil** [comment]
full mod list?

**Comment by thiakil** [comment]
This is a known issue, and there is no known fix. Some mod is causing the recipes to not fully load on the server.

It needs a restart to fix

**Comment by Undeadbear** [comment]
A few days later it just worked. Never changed anything, the server problem
got restarted to fix it

**Comment by nayfaan** [comment]
> This is a known issue, and there is no known fix. Some mod is causing the recipes to not fully load on the server.
> 
> It needs a restart to fix

Facing the same issue. Do we know which mod is causing the conflict? Or is it a KubeJS script thing?
