### ISSUE TITLE
Electrolytic separator ignores Energy improvement (The electrolytic separator is not in the config)

### ISSUE THREAD

**Issue by kelllmonakil** [mekanism/Mekanism#8032]
### Issue description

I installed the Energy improvement in the separator and noticed the fact that the consumption did not decrease, but the amount of energy increased. I went to the Mekanism config to reduce it myself and noticed that the separator is not in the "machine-usage" file, but it is in the "machine-storage" file. This problem exists both on 1.18.2 and on 1.20.1, on other versions I have not checked it.
![изображение_2024-03-16_142014528](https://github.com/mekanism/Mekanism/assets/157976200/cd60e145-79c5-4c3f-9b2d-d1fc48520e6f)
![image](https://github.com/mekanism/Mekanism/assets/157976200/9b1a9da9-2792-423b-aff6-71ba096f20fc)

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

Forge 40.2.17

### Mekanism version

Older

**Comment by UnknownSerhan** [comment]
Energy upgrades do not decrease the consumption of electrolytic separators intentionally. It is not a bug. It is so that you can't create infinite energy by burning hydrogen.

**Comment by thiakil** [comment]
see `general.toml` section `general.energy_conversion`:
```
#How much energy is produced per mB of Hydrogen, also affects Electrolytic Separator usage, Ethylene burn rate and Gas generator energy capacity.
HydrogenEnergyDensity = "200"
```
