### ISSUE TITLE
Rotary Condenser is Very Broken

### ISSUE THREAD

**Issue by MadSciSlack** [mekanism/Mekanism#8033]
### Issue description

The rotary condenser used to run continuously, making gaseous brine for my sulfur plant.  Suddenly it has stopped, completely full of brine and energy, and just sits there.  Changing modes does nothing, and it's not being blocked by a redstone mode.  It's not being blocked by input / output modes.  Even with no upgrades of any kind, it just won't run.

I cleared the fluid with a dropper, and now it won't accept liquids at all.  When manually placing a liquid container / bucket into the input slot, it goes in for a split second and then rejects it back into my hand.

I replaced the rotary condenser with a new one, and it still does the same thing (not accepting any fluids or anything).

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

Forge 43.3.7

### Mekanism version

10.5.7 (Latest)

### Other relevant versions

MC 1.19.2
Mekanism 10.3.9.13

**Comment by thiakil** [comment]
If it's on a server, restart it. Something stops all recipes from loading

**Comment by MadSciSlack** [comment]
Trying the server restart just in case our auto-restarts aren't working.  We've experienced this with the metallurgic infuser as well since the original issue. 

Is there anything I can do to help diagnose this issue? I've got a dev server and a VERY custom modpack for stress testing things.

**Comment by MadSciSlack** [comment]
Update: The metallurgic infuser is working again, so I suspect that the condensentrator will as well.  My offer to assist however possible still stands though.

**Comment by thiakil** [comment]
The only real thing would be a binary search, but complicated by the fact that it only sometimes happens
