### ISSUE TITLE
Shaders break the player model

### ISSUE THREAD

**Issue by BazZziliuS** [mekanism/Mekanism#8034]
### Issue description

Shaders break the player model

### Steps to reproduce

Turn on the shaders and put on the meka armor
![image](https://github.com/mekanism/Mekanism/assets/18011884/c313cfa4-93bf-4de1-8f0f-dc837ef21616)
![image](https://github.com/mekanism/Mekanism/assets/18011884/0ac14051-caa0-42c4-92a5-c143baeaff25)

### Minecraft version

1.20.1 or earlier (No longer being developed)

### Forge version

Forge 47.2.20

### Mekanism version

10.4.6.20

### Other relevant versions

embeddium-0.3.9+mc1.20.1
embeddiumextras-1.20.1-v2.0.0
oculus-mc1.20.1-1.6.15a
rubidium-extra-0.5.4.2+mc1.20.1-build.118

https://modrinth.com/shader/complementary-unbound/version/r5.1.1 or PrismarineV4.2a

**Comment by UnknownSerhan** [comment]
Not Mekanism’s fault. Take it with the shaders

**Comment by BazZziliuS** [comment]
> Not Mekanism’s fault. Take it with the shaders

I've tried different shaders and haven't found any that don't break the model.
