### ISSUE TITLE
Machine Menu into Crafting - Crash to Launcher

### ISSUE THREAD

**Issue by DalekZED** [mekanism/Mekanism#8037]
### Issue description

I have 1.20.1 MC installed with Mekanism and many other mods installed. I can provide a list if necessary.
When I have a mekanism machine GUI open and go straight into crafting options and figuring out how to make something through JEI I am now locked into that inventory menu. Whenever I try to leave the game will crash to launcher.

### Steps to reproduce

1. Enter world.
2. Open a mekanism machine GUI.
3. Left or Right click on a JEI icon for recipe.
4. Esc or E to close menu back to GUI.
5. Crash.

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

NA, Forge 47.2.17

### Mekanism version

Older

**Comment by thiakil** [comment]
Your crash log is missing
