### ISSUE TITLE
Very strong FPS drops when looking at generators

### ISSUE THREAD

**Issue by dldev32** [mekanism/Mekanism#8047]
### Issue description

When I try to hover over any of the generators, the FPS drops to 15, and I have no idea why this could be.
[Video](https://youtu.be/OtIEkX20DXw)

### Steps to reproduce

1. Go to the generator and hover your cursor over it.
2. You'll see your FPS drop sharply from 500 to 15.
3. You don't understand why this is happening.

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

47.1.101

### Mekanism version

Older

### Other relevant versions

Mekanism-1.20.1-10.4.6.20

**Comment by chucaLw** [comment]
Maybe you got Man From The Fog installed, I had that mod installed and then I deleted it and finally no FPS drops when looking at the generators or digital miner

**Comment by dldev32** [comment]
> Maybe you got Man From The Fog installed, I had that mod installed and then I deleted it and finally no FPS drops when looking at the generators or digital miner

Yes, that's right, I just forgot about this issue because there was no feedback on this matter.

**Comment by pupnewfster** [comment]
Am I correct in understanding that this was due to another mod interacting poorly?

**Comment by UnknownSerhan** [comment]
We have had this same case in Mek discord too a few times, all were caused by Man From The Fog mod, I would guess that’s the same reason here.
