### ISSUE TITLE
Refined obsidian dust recipe bugged

### ISSUE THREAD

**Issue by Eckodinho** [mekanism/Mekanism#8048]
### Issue description

In our project i made refined obsidian dust with obsidian dust and refined diamond
then when i tried to make more, i shift clicked the obsidian dust in and it went right back to my inventory
so i tried with hopper and logistical transporters, didnt work either
then a friend also tried to do it, and it didnt work
i also tried to break the metallurgic infuser and place it back down, also crafted a new one and didnt work

mekanism is on version 10.4.5.20 in the modpack time 2 on curseforge

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

forge 47.2.0

### Mekanism version

Older

**Comment by thiakil** [comment]
something in your modpack is causing minecraft to not load the complete list of recipes. The server will need to be restarted.
