### ISSUE TITLE
rare random Crafting Issue

### ISSUE THREAD

**Issue by MSandro** [mekanism/Mekanism#8056]
### Issue description
It's hard to reproduce. When I enter a world it happens about 1 in 30 times that the crafting outputs are messed up. So recipes without input are loaded.

![image](https://github.com/mekanism/Mekanism/assets/10937159/eb072723-3911-438e-9e20-ee0efb322847)

### Steps to reproduce
load a world and try to craft something.

It does not matter what I put in the crafting table, it is always the same wrong output.
![image](https://github.com/mekanism/Mekanism/assets/10937159/97f2ce11-8ee0-48ff-a5a2-5bc4d2e64f3b)
![image](https://github.com/mekanism/Mekanism/assets/10937159/e159ef47-4020-49bc-8ea0-47901abf699e)

reloading / re joining the world solves the issue. But I would like to know why this happens.

### Minecraft version
1.20.4 (Latest)

### NeoForge version
20.4.225

### Mekanism version
10.5.18 (Latest)

**Comment by thiakil** [comment]
That's likely to be an issue with Neoforge or one of your other mods. We saw it happening in earlier neoforge versions, but that bug got fixed

**Comment by MSandro** [comment]
Thanks for the fast reply. Yes I am absolutely not sure which mod is cuasing it.
That's why I reported the issue to other mods as well.
https://github.com/AztechMC/Modern-Industrialization/issues/694
https://github.com/TeamTwilight/twilightforest/issues/2022

I'm trying to reproduce the problem in a small modpack with as few mods as possible in order to be able to narrow down the cause. But since this is a issue that does not always occur, it is very time-consuming.

**Comment by MSandro** [comment]
I have found this bug in this modpack: https://www.curseforge.com/minecraft/modpacks/new-game-neoforge-version
Since Mekanism is not part of these packs, I can rule it out.
