### ISSUE TITLE
Silent Gear support uses wrong values

### ISSUE THREAD

**Issue by uhloin** [mekanism/Mekanism#8057]
### Issue description

If use refined obsidian ingots to create armor, then you use different stats then if create the same armor with silent gear templates.

For example:
Refined Obsidian Chestplate from ingots: +12 armor, +5 armor toughness, +2 knockback resistance, 1200 durability
Refined Obsidian Chestplate from template: +12 armor, +4 armor toughness, +0 knockback resistance, 800 durability 

Also (not real bug, but balance issue) refined obsidian has values greater than final gameplay materials from End, but is accessible before Nether.

Armor value for helm/chestplate/leggins/boots: 
Diamond (best Overworld material): 3/8/6/3
Crimson Steel (best Nether material): 4/8/6/4
Tyrian Steel (best End material): 5/9/7/4
Refined Obsidian: 5/12/8/5

This lead to another problem: any alloys of high tier materials with refined obsidian lead to worse material instead of improve it because of synergy. 

The possible solution is to create several versions of refined obsidian ingots, with the same armor as for best materials, but better toughness and/or knockback resistance, like this:
Refined Obsidian (only overworld materials)
Blazed Obsidian (+blaze rod powder)
Warped Obsidian (+shulker powder)

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

47.1.100

### Mekanism version

Older

### Other relevant versions

Mekanism-1.20.1-10.4.6.20.jar 
MekanismTools-1.20.1-10.4.6.20.jar 
silent-gear-1.20.1-3.6.3.jar 
silent-lib-1.20.1-8.0.0.jar

**Comment by thiakil** [comment]
> If use refined obsidian ingots to create armor, then you use different stats then if create the same armor with silent gear templates.

That would be a bug on Silent's end, as we don't have any integration as far as I know

> This lead to another problem: any alloys of high tier materials with refined obsidian lead to worse material instead of improve it because of synergy.

That would be a modpack-level concern, as it's a modpack task to ensure inter-mod balance

**Comment by uhloin** [comment]
"That would be a bug on Silent's end, as we don't have any integration as far as I know"

You mean Silent made integration with Mekanism, but not Mekanism supported Silent?

I wrote a similar report to Silent team

**Comment by thiakil** [comment]
Yes
