### ISSUE TITLE
When the mouse cursor passes over the mode switch button of the Rotary Condensentrator, it crashes.

### ISSUE THREAD

**Issue by uuu0322** [mekanism/Mekanism#8058]
### Issue description

When the mouse cursor passes over the mode switch button of the Rotary Condensentrator, it crashes.

Installed MODs
jei-1.20.4-neoforge-17.3.0.49.jar
Mekanism-1.20.4-10.5.18.39.jar
MekanismGenerators-1.20.4-10.5.18.39.jar
MekanismTools-1.20.4-10.5.18.39.jar

https://github.com/mekanism/Mekanism/assets/78357083/9ad30701-2863-433b-82d1-bc0524fee4c5
[crash-2024-04-12_12.48.13-client.txt](https://github.com/mekanism/Mekanism/files/14953798/crash-2024-04-12_12.48.13-client.txt)

### Steps to reproduce

Reproduction Steps

Obtain the item
/give @p mekanism:rotary_condensentrator
Open the UI of the Rotary Condensentrator
Move the mouse cursor over the mode switch button

### Minecraft version

1.20.4 (Latest)

### NeoForge version

20.4.225

### Mekanism version

10.5.18 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://github.com/mekanism/Mekanism/files/14953798/crash-2024-04-12_12.48.13-client.txt

**Comment by liamwibo** [comment]
Hi i also have this issue and you can get around it by using an autoclicker setting it to1 click per milisecond and hope it clicks just before the crash.
