### ISSUE TITLE
Compatibility with sound muffler from extraUtils?

### ISSUE THREAD

**Issue by ruifung** [mekanism/Mekanism#806]
Is it possible to make mekanism compatible with the sound muffler from extraUtils? Because I don't want to disable sounds entirely, just the sounds from certain machines like the generators.

**Comment by megaxlr** [comment]
This is still an issue in version 9.4.1 any chance of you fixing it?

**Comment by thiakil** [comment]
I'm fairly certain the custom sound system mentioned in the above comments still exists. You can lower the volume in your client config.

**Comment by Vaygrim** [comment]
Custom sound system IS still in the mod, which means mod-external sound mufflers will still not work, unless specially coded to have Mekanism sound system support.
