### ISSUE TITLE
Electric Pump not pumping unless ABOVE fluid source?

### ISSUE THREAD

**Issue by ZTagre** [mekanism/Mekanism#8060]
### Issue description

The Electric Pump (as I have always used it in the past) was able to pump when the FLUID was touching a SIDE of the pump, but now it only "sees" fluid when it is DIRECTLY OVER IT (ie. not submerged). This makes all worlds with a setup such as the one in the screenshot (#1) I have included non-functional. Screenshot #1 shows the non-functional setup (has always WORKED previously...), and screenshot #2 shows what one must do now, which is position the electric pump ABOVE the fluid source!

   Minecraft v. 1.19.2
   Forge v. 43.3.0
   Mekanism 10.3.9.13

   Note that, as this is the LATEST version currently available for MC 1.19.2, the problem is one I can't "work around...
   Also note that NO OTHER MODS are present when I took these screenshots, to confirm it IS indeed an issue with Mekanism, and not some other mod "conflict".
![Screenshot #1](https://github.com/mekanism/Mekanism/assets/25883951/87b5f90b-598d-4fd3-910e-c122abd3c069)
![Screenshot #2](https://github.com/mekanism/Mekanism/assets/25883951/ccb5a1bd-7a32-4283-92ed-20342d5ae409)

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

43.3.0

### Mekanism version

Older

**Comment by pupnewfster** [comment]
That was a bug that we fixed at some point. It always was only meant to look below

**Comment by ZTagre** [comment]
Now, I was AFRAID that might just be the case! I liked it the way it worked with the "bug", and I think it made a bit more sense, as to look at the pump, it seems it SHOULD be able to "see" the fluid all around it! Oh well, thanks for the quick response! I will "live", of course :-}

   I'm a HUGE fan of Mekanism, and will always use it when it is available. I don't really know what I would do without it by this point lol

  -ZTagre

**Comment by ZTagre** [comment]
Oh, and I guess I should mention that, if this was a bug that was fixed, then maybe do an update for MC 1.18.2, because I just moved up from that MC version last week, and the "bug" is still present in that version of Mekanism (v. 10.2.5.465). I was just building with just the method I show in the first screenshot...

  -ZTagre
