### ISSUE TITLE
CC:Tweaked Method issue getEnergy() and getMaxEnergy() with the Induction Matrix

### ISSUE THREAD

**Issue by Zonk1987** [mekanism/Mekanism#8063]
### Issue description

I am playing at the moment FTB Skies Expert in the newest Version 1.7.0. Both of the Methods that are discribed in the Titel only give me the Value from one of the installed cells and if i want to have the total amount of the FEStorage i need to multiply the this with the amount of cells. Now Imagine there are a mix out of all different tiers of cells inside the Induction Matrix this wouldn't work then.

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

forge-1.19.2-43.3.8

### Mekanism version

Older

**Comment by thiakil** [comment]
I don't think that's how that works.

Can you show what you're seeing? i.e. how did you come to this conclusion?

**Comment by Zonk1987** [comment]
![Screenshot 2024-04-17 162409](https://github.com/mekanism/Mekanism/assets/25836879/53ce720f-3f88-4aaa-9dc9-09f9262ea5d2)


In the Induction Matrix are 4 Ultimate Induction Cells installed. One of them has a max. capacity of 1.60 TFE like the getMaxEnergy() gets as output. I don't find a Method to get the actual Cell Type is installed only the amount of cells and providers. So the i think the only way to get the total capacity of the matrix is by multiplying them together. So in that case i have not all cells from the same tier the total amount of the matrix can't be calculated in the right way. It could be that i am totaly wrong but so far thats what i am getting out of this.

**Comment by NullPointerCollection** [comment]
the output is in Joules.  each ultimate cell holds 4TJ/1.6TFE.

**Comment by NullPointerCollection** [comment]
> the output is in Joules. each ultimate cell holds 4TJ/1.6TFE.

nice to get a thumbs down for the correct answer

**Comment by pupnewfster** [comment]
Old versions like 1.7.10 only output values using Joules which is what mekanism uses internally. Newer versions provide helper methods to convert between them, though that doesn't help you much as you are on such an old version. One potential reason for it only showing partial amounts is if it potentially overflows how much can actually be stored in the data type (I don't know offhand if this is what is going on). Unfortunately there isn't much you can do about this. Closing this as we are no longer developing for 1.7.10 and this isn't an issue in 1.20.4
