### ISSUE TITLE
CC modems can only connect if QIO redstone adapter is facing up or down

### ISSUE THREAD

**Issue by Sharparam** [mekanism/Mekanism#8064]
### Issue description

A CC: Tweaked modem is only able to be placed on a QIO Redstone Adapter if the adapter is facing up or down. On sideways facing adapters it's not possible to connect a modem.

![image](https://github.com/mekanism/Mekanism/assets/551094/f10d47dd-61ce-4586-9b36-3c90071bb4e9)

### Steps to reproduce

1. Place a QIO Redstone Adapter facing one of the cardinal directions.
2. Attempt to place a CC: Tweaked Wired Modem on it.

### Minecraft version

1.20.4 (Latest)

### NeoForge version

20.4.232

### Mekanism version

10.5.19 (Latest)

### Other relevant versions

CC: Tweaked version: 1.110.2

**Comment by pupnewfster** [comment]
I don't exactly get how this is a mekanism issue? Technically I would say it is a vanilla issue, as CC Tweaked is probably using the same method torches use in their `canSurvive` override. Which unfortunately doesn't work for certain cases. The way [we handle it](https://github.com/mekanism/Mekanism/blob/c53a41c10f0ef09ced86ce6cc384ed83c4ee2341/src/additions/java/mekanism/additions/common/block/BlockGlowPanel.java#L62-L65) in mekanism for things like the glow panel is by not directly calling the vanilla method

**Comment by Sharparam** [comment]
Right, so this is perhaps an issue for CC then.

Edit: For anyone arriving here by search: Using the full block version of the modem from CC works fine to attach adapters sideways. Not as neat maybe but it works.
