### ISSUE TITLE
Worldgen config keeps resetting itself on reload

### ISSUE THREAD

**Issue by The-Goat-HUN** [mekanism/Mekanism#8065]
### Issue description

Uranium's worldgen config keeps setting itself to "true" on reload.

### Steps to reproduce

1. In the config file (world.toml), at the uranium generation settings, set the "shouldGenerate" to "false".
2. Reload the game.
3. The config reloaded itself and it's now true again.

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

Forge 47.2.23

### Mekanism version

Older

### Other relevant versions

Mekanism version: 1.20.1-10.4.6.20

**Comment by The-Goat-HUN** [comment]
All worldgen, not just uranium.

**Comment by pupnewfster** [comment]
Are you editing the config while the game is open? And if so what text editor are you using? As I do know the file watcher for the config system forge uses has some issues when using things like notepad++ to edit a config while the game is open due to how N++ performs file saves.

**Comment by The-Goat-HUN** [comment]
> Are you editing the config while the game is open? And if so what text editor are you using? As I do know the file watcher for the config system forge uses has some issues when using things like notepad++ to edit a config while the game is open due to how N++ performs file saves.

Thanks, I already solved it, by using the stock Windows notepad and editing the configs while the game is closed.
