### ISSUE TITLE
Atomic Disassembler Glow [1.20.1]

### ISSUE THREAD

**Issue by Exokyhh** [mekanism/Mekanism#8066]
### Issue description

I don't know if it is intentional but the Atomic Disassembler, when using shaders, is very emissive/bright. Maybe it is supposed to glow but a bit less? Like the jetpack, for example.

![2024-04-25_00 52 50](https://github.com/mekanism/Mekanism/assets/90096585/767d0159-230e-4982-bc15-6b3e66384e9f)

![2024-04-25_00 53 01](https://github.com/mekanism/Mekanism/assets/90096585/e1b023f1-3939-4f31-9633-3e6aaaf516e7)

### Steps to reproduce

1. Install Mekanism and shaders (I used ComplementaryShaders_v4.7.1, even the r5.1.1 version is the same)
2. Hold the Atomic Disassembler, and admire its brightness

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

Forge - 47.2.20

### Mekanism version

Older

### Other relevant versions

I'm using:
Mekanism-1.20.1-10.4.6.20
oculus-mc1.20.1-1.6.15a

**Comment by thiakil** [comment]
That's something for your shader / shader mod, base Mekanism doesn't do anything for them

It does glow, but your shader is blowing it up drastically
