### ISSUE TITLE
Autominer in last version 1.18.2 don't drop when broke block

### ISSUE THREAD

**Issue by thomas260913** [mekanism/Mekanism#8069]
### Issue description

When I broke the auto miner it don't drop the autominer's item and I have to craft a new everytime it's boring (the server is magma 1.18.2 with the last version of forge and the modpack was securitycraft, all addon of mekanism, mekanism tweaker, create, cc: tweaker, securitycraft and botania. Every mods is in last version and if you want the jar there is in the modpack client is https://gamity-pvp.fr/modpack/modpack_mods_craftingmods.zip)

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

null

### Mekanism version

Older

### Other relevant versions

Version 10.2.5.465

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

null

**Comment by urmet** [comment]
> server is magma

pretty sure that these hybrid servers are 200% unsupported. so if anything, it's a magma bug, not mekanism bug
