### ISSUE TITLE
Pipe error after loading the World

### ISSUE THREAD

**Issue by Korasik011** [mekanism/Mekanism#8072]
### Issue description

I have a fairly large assembly of 271 mods, but most likely the problem is that after entering the world, all the pipes begin to live their lives.
![image](https://github.com/mekanism/Mekanism/assets/168999824/4c8df5c2-32d0-4708-8d9a-a793bf1e2981)
![image](https://github.com/mekanism/Mekanism/assets/168999824/92273a4a-096b-4646-b894-12ab02c256d9)
![image](https://github.com/mekanism/Mekanism/assets/168999824/d9ed747b-8911-4197-ac12-c5b418ad1860)

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

1.19.2

### Mekanism version

Older

**Comment by Korasik011** [comment]
Maybe it’s some kind of problem with textures, but I don’t have any shaders + pipes seem to perform their function in pumping liquid

**Comment by pupnewfster** [comment]
I believe we fixed this during the 1.20.4 lifecycle, so I am going to close this. If anyone can reproduce this on the last 1.20.4 build or in 1.21+ comment and I will reopen it.
