### ISSUE TITLE
Energy cube side Config with wrong facing bug 1.20.1

### ISSUE THREAD

**Issue by mystikKey** [mekanism/Mekanism#8074]
### Issue description

![Captura de ecrã 2024-05-08 224002](https://github.com/mekanism/Mekanism/assets/168667192/d7f0d5af-e035-49cf-a03e-6aa184d11bc7)
![Captura de ecrã 2024-05-08 224023](https://github.com/mekanism/Mekanism/assets/168667192/bf87fbf1-a258-4a79-a6e8-5ba6d09251ec)
![Captura de ecrã 2024-05-08 224032](https://github.com/mekanism/Mekanism/assets/168667192/4830f49b-c0c5-4fbf-adf4-39ffbf3307d6)
![Captura de ecrã 2024-05-08 224054](https://github.com/mekanism/Mekanism/assets/168667192/0d9b9f91-82bd-47a6-9e09-c2ce543c1104)

So far only detected this problem with energy cubes.

What it seems to be happening is that it's detecting the blocks and switching the front side with the back side. In other words, has it's presented in the images, the energy cube in front it's put in the back considering the block facing, even considering the world North facing is still wrong.

Mekanism 10.4.6

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

Forge 47.2.23 (Not NeoForge)

### Mekanism version

Older

**Comment by thiakil** [comment]
I don't quite understand what you mean here?
The facing property being north means that the block's front face is the north direction

**Comment by mystikKey** [comment]
I just point out the facing to show that the side config of the energy cube is showing at least 2 sides wrong (it's switching front and back side)

**Comment by thiakil** [comment]
So what direction are you facing in your screenshots?

**Comment by mystikKey** [comment]
In the screenshots i'm facing south

**Comment by thiakil** [comment]
Then south being the back face is correct, given the facing property is north

**Comment by mystikKey** [comment]
if you pay attention to the screenshots wether it's north or south the energy cube facing detection configs are still wrong

**Comment by thiakil** [comment]
Why is it wrong?
