### ISSUE TITLE
Ultimate Infusing Factory doesn't accept enriched obsidian

### ISSUE THREAD

**Issue by mystikKey** [mekanism/Mekanism#8075]
### Issue description

When trying to use the ultimate infusing factory to produce atomic alloy by using enriched obsidian and reinforced alloy, it does not accept the enriched obsidian

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

Forge 47.2.23 (Not NeoForge)

### Mekanism version

Older

**Comment by pupnewfster** [comment]
Sounds like this might be another case of #7831
