### ISSUE TITLE
Crash client when using cardboard box on Flawless budding Certus quartz

### ISSUE THREAD

**Issue by Thrystan01204** [mekanism/Mekanism#8078]
### Issue description

Hello,

I play on a private server where we installed Mekanism and AE2.
When trying to use a cardboard box on a Flawless budding Certus Quartz the client crash (only the client, not the server, the server is fine and saw nothing, just the player disconnecting).

### Steps to reproduce

1. craft a cardboard box
2. try to use it on a budding certus quartz

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

Forge 47.2.30

### Mekanism version

Older

### Other relevant versions

Applied Energistics 2 version 15.1.1

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Thrystan01204/92c3567719671e9cb8b1d479c87f99c4

**Comment by thiakil** [comment]
report to vortexmod

**Comment by Thrystan01204** [comment]
Sorry, thought it was from mekanism. I opened and issue on their curseforge page : https://legacy.curseforge.com/minecraft/mc-mods/the-time-vortex/issues/2
