### ISSUE TITLE
railcraft-reborn-1.20.1-1.1.1 Broke Mekanism

### ISSUE THREAD

**Issue by lmwood73** [mekanism/Mekanism#8080]
### Issue description

Playing on an FTB Direwolf20 1.20.1 server, updated Railcraft Reborn to the latest version and could no longer load any materials into enriching chamber, smelter, purifier etc. Updating to latest version of Mekanism did not solve the problem (went from 10.4.5.19 to 10.4.6.20). Reverting Railcraft Reborn to version 1.0.10 allowed all functions of Mekanism to work properly again. Additionally Mekanism JEI information was spotty, certain recipes didn't load. 

### Steps to reproduce

1. Have Mekanism v.10.4.5.19 or higher and Railcraft Reborn 1.0.10
2. Update Railcraft Reborn to v.1.1.1
3. Attempt to use a Mekanism machine like smelter or enrichment chamber

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

47.1.76

### Mekanism version

Older

### Other relevant versions

railcraft-reborn-1.20.1-1.1.1

**Comment by pupnewfster** [comment]
Can you please provide your latest log? This sounds like the railcraft update just broke recipe loading in general, but maybe there is some error that it is outputting in the log.
