### ISSUE TITLE
Chemical Tank doesn't have a dump mechanism

### ISSUE THREAD

**Issue by mystikKey** [mekanism/Mekanism#8081]
### Issue description

Chemical Tank doesn't have a dump mechanism has stated in the wiki. 

In fact only Eletrolytic Separator has it, besides the Metallurgic Infuser and it's upper tiers (dump mechanism).

![imagem](https://github.com/mekanism/Mekanism/assets/168667192/8fe705d4-3c4b-43ea-a871-58d09c7e5a9c)
![imagem](https://github.com/mekanism/Mekanism/assets/168667192/3a5c1adf-41cf-4f16-bb86-ce98092103ed)

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

Forge 47.2.23 (Not NeoForge)

### Mekanism version

Older

### Other relevant versions

Mekanism: 10.4.6
Minecraft: 1.20.1
Forge: 47.2.23

**Comment by thiakil** [comment]
Click the button next to the text that says `Idle`
