### ISSUE TITLE
Mekanism Energy Cube

### ISSUE THREAD

**Issue by HairyHarold369** [mekanism/Mekanism#8082]
### Issue description

The floating cube inside the energy cube keeps glitching out and going around my screen when i move my mouse around, however when i don’t move it also doesn’t move. This is in the latest All the Mods 9 so not sure on mekanism version or minecraft version.

### Minecraft version

1.20.4 (Latest)

### NeoForge version

Unsure

### Mekanism version

10.5.20 (Latest)

**Comment by pupnewfster** [comment]
I believe this is due to some rendering mod you have breaking the view and rendering the BERs without them being staticly placed.
