### ISSUE TITLE
Low TPS

### ISSUE THREAD

**Issue by vSKAH** [mekanism/Mekanism#8083]
### Issue description

![image](https://github.com/mekanism/Mekanism/assets/68877411/8900df56-147c-4e46-8eb2-0caaae20ca44)

### Steps to reproduce

i don't know just use some logistical transporter ? 

### Minecraft version

1.20.1 or earlier (No longer being developed)

### NeoForge version

Forge 47.2.30

### Mekanism version

Older

### Other relevant versions

Mekanism 10.4.6.20

**Comment by pupnewfster** [comment]
Can you please provide access to the spark profile? The important part is likely that it is interacting with another mod that has an item handler with poor performance, but as you only expanded as far as you did, it is hard to tell what is going on.
