### ISSUE TITLE
Atomic Disassembler losing cables

### ISSUE THREAD

**Issue by XlosVSM** [mekanism/Mekanism#8088]
### Issue description

Whenever you use the extended vein miner mode on the atomic disassembler on any of the cables (universal, mechanical), you only get one cable and lose the rest.

### Minecraft version

1.20.1 or earlier (No longer being developed)

### Forge version

14.23.5.2860

### Mekanism version

Older

**Comment by UnknownSerhan** [comment]
Old v9 bug, nothing you can do about it other than avoid breaking with vein mining. Do note the same happens with digital miner (it doesn’t drop)
