### ISSUE TITLE
Right-Clicking Unformed Multiblocks briefly opens the GUI

### ISSUE THREAD

**Issue by Drullkus** [mekanism/Mekanism#8089]
### Issue description

While attempting to build with Boiler Casing blocks in Minecraft 1.21, the right-clicking action is consumed to open the GUI instead of placing the block in hand. This happens in the process of constructing a multiblock, as the GUI is usually not shown until the multiblock is correctly formed.

Initially encountered whilst testing CTM with Mek installed.

### Steps to reproduce

Place Boiler Casing blocks in attempt to build a multiblock. In doing so, it's not possible to place a Boiler Casing block on a face of another Boiler Casing block without holding the Sneak key.

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.0-beta

### Mekanism version

10.6.0 (Latest)

**Comment by UnknownSerhan** [comment]
Can confirm as can be seen in the video:

https://github.com/mekanism/Mekanism/assets/69000972/fc50d2e7-1fb7-4534-8a86-6b20ef8bf63b




This can lead to certain dupes (I don't know how it even happened):


https://github.com/mekanism/Mekanism/assets/69000972/a5955cd2-ffa5-4689-b2f5-8fc4adc3a7aa
