### ISSUE TITLE
Creative Tab Search Bar is Missing for the Base Mod

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#8093]
### Issue description

Letting the image speak.

![image](https://github.com/mekanism/Mekanism/assets/69000972/82063de4-7f81-4cc5-bf6a-010af7d6b080)

### Steps to reproduce

1. Go to Creative Mode and check the search bar for the base mod.

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.4-beta

### Mekanism version

10.6.0 (Latest)

**Comment by pupnewfster** [comment]
https://github.com/neoforged/NeoForge/pull/1103
