### ISSUE TITLE
Advancement and Recipe Book Recipes Do Not Work/Exist

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#8096]
### Issue description

There is no trace of advancements existing in-game, even granting all does not help.

The recipe book does not also have any recipe related to mekanism, don't know if that's intended or not.

### Steps to reproduce

1. Try to get advancements and check for recipe book.
2. See that they do not exist.

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.4-beta

### Mekanism version

10.6.0 (Latest)

**Comment by pupnewfster** [comment]
The recipe book doesn't work because we don't have recipe advancements as at least historically it caused a lot longer world join times. The advancement part is definitely a bug though.
