### ISSUE TITLE
The F1 key does not hide the MekaSuite GUI

### ISSUE THREAD

**Issue by Lolothepro** [mekanism/Mekanism#8112]
### Issue description

The F1 key does not hide the MekaSuite GUI
![2024-06-15_18 35 40](https://github.com/mekanism/Mekanism/assets/68275908/42f71462-dcca-4044-a643-69f3eede9201)

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.6-beta

### Mekanism version

10.6.0 (Latest)

**Comment by UnknownSerhan** [comment]
It doesn't hide any of the elements in fact, probably not intended as I think it used to hide back in 1.20.
