### ISSUE TITLE
Digital Miner can't using tag to find glowstone in 1.20.1

### ISSUE THREAD

**Issue by FrozenFunny** [mekanism/Mekanism#8128]
### Issue description

![$PQS4B8}B 0)`SSQUW~48L](https://github.com/mekanism/Mekanism/assets/50235773/9de9d779-d79a-445c-bc46-61ffeef7c218)

### Steps to reproduce

1.Put Digital Miner on any block.
2.open tag filter,input:forge:storage_blocks/glowstone
3.No matching targets.

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

Forge47.3.1

### Mekanism version

Older

### Other relevant versions

Version:
Mekanism-1.20.1-10.4.8.43
Forge-47.3.1

**Comment by UnknownSerhan** [comment]
Are you sure glowstone actually has a tag? I checked on 1.21 and it has none.

Edit: Ok it actually has a tag in 1.20.1 NeoForge and it works on my game.

![image](https://github.com/mekanism/Mekanism/assets/69000972/2bff2dfe-8477-4234-9b62-281461f44aea)

**Comment by FrozenFunny** [comment]
> 你确定萤石真的有标签吗？我检查了一下，它没有。

![QQ图片20240623003838](https://github.com/mekanism/Mekanism/assets/50235773/cf77019a-6122-4961-95f8-20436400d8fd)
So this tag is from other mods?I can use it in ATM9sky.

**Comment by pupnewfster** [comment]
Just to confirm did you input `blocks/glowstone` or `forge:storage_blocks/glowstone`? It is a bit hard to tell from your initial picture.
