### ISSUE TITLE
Storage Blocks to  RawOre/Ingots shouldn't use Tags

### ISSUE THREAD

**Issue by Speiger** [mekanism/Mekanism#8130]
### Issue description

Basically, storage blocks to Ingots/Raw ore shouldn't use Tags, because we get the whole problem of recipe priority.
And if people want to choose what metal they want the Raw/Ingot items to Storage blocks lets you choose with the recipe already.
This is especially annoying if mekanism isn't the main ingot/raw target you want and then you try to craft to blocks and uncraft and you land in mekanism.
And if a mod adds raw ore and storage blocks they will include crafting/uncrafting recipes anyways.

(TL:DR its a bit overreaching)
We found this out when we setup a 1.19.2 pack.

It would be nice if that could be fixed.

### Minecraft version

1.21 (Latest)

### NeoForge version

Any

### Mekanism version

10.6.1 (Latest)

### Other relevant versions

Any range from 1.19.2-1.2x

**Comment by pupnewfster** [comment]
I believe I addressed all relevant ones in: https://github.com/mekanism/Mekanism/commit/2b5bef0503a3919ddb80fae0aefcae61979c3522, if I missed any feel free to let me know.

**Comment by Speiger** [comment]
@pupnewfster thank you for being so quick :)
I didn't even expect that ^^"
From what i see it is covering everything.

Thanks :)

Oh yeah one thing i realized but i forgot to ask.
Is it intended that the endgame SPUs are basically impossible if you have mekanism generators not installed?
We solved this on our end by adding IC2C Re-enriched uranium Cells as Oxidizion. But i wonder.
(That by the way is the fairest compat we could think of since you still need to run a reactor to obtain that)

**Comment by pupnewfster** [comment]
I don't know what SPU stands for, but yes I am aware that some late game recipes by default have no recipe unless you have mekanism generators, or the modpack decides to create recipes for them.

**Comment by Speiger** [comment]
Sorry i mean the SPS.

Ok that's good to know.
