### ISSUE TITLE
Scuba Mask makes head Dissapear

### ISSUE THREAD

**Issue by Kazuhiko-Gushiken** [mekanism/Mekanism#8133]
### Issue description

Wearing the Mekanism Scuba Mask makes your head disappear, both in the world and in viewing your inventory.

![image](https://github.com/mekanism/Mekanism/assets/132615999/e1418549-32d5-4544-a71f-997b0d3fe7ca)
![image](https://github.com/mekanism/Mekanism/assets/132615999/833f619a-3240-4a47-9d48-98b73b5e16a6)

### Steps to reproduce

put on scuba mask
look at head

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.25

### Mekanism version

10.6.1

### Other relevant versions

the version is actually 10.6.1.45, no idea if the extra `45` means anything special in this case.

**Comment by UnknownSerhan** [comment]
Can't reproduce, do you have any rendering mods in your pack?

**Comment by Kazuhiko-Gushiken** [comment]
Ah crap, maybe it's Embeddium?

**Comment by UnknownSerhan** [comment]
Well, try it and see

**Comment by Wizqok** [comment]
its  ImmediatelyFast Mod, already reported there
