### ISSUE TITLE
weird issue when crafting items. Crash/Disconnect 

### ISSUE THREAD

**Issue by ghost** [mekanism/Mekanism#8134]
### Issue description

few recipes are causing me to crash/disconnect while in Lan world, mostly the thermal evaporation stuff at moment. also sorry if not very well written. i am new to GitHub i hope logs attached help.

### Steps to reproduce

at moment using the crafting terminal for AE2 and crafting anything related to thermal evaporation plant. also, other items have caused same issue, but only once. also here are the debug files. 

[disconnect-2024-06-19_22.21.02-client.txt](https://github.com/user-attachments/files/15949549/disconnect-2024-06-19_22.21.02-client.txt)
[disconnect-2024-06-21_08.44.08-client.txt](https://github.com/user-attachments/files/15949550/disconnect-2024-06-21_08.44.08-client.txt)
[disconnect-2024-06-21_16.33.40-client.txt](https://github.com/user-attachments/files/15949551/disconnect-2024-06-21_16.33.40-client.txt)
[disconnect-2024-06-23_23.40.12-client.txt](https://github.com/user-attachments/files/15949552/disconnect-2024-06-23_23.40.12-client.txt)
[disconnect-2024-06-23_23.40.42-client.txt](https://github.com/user-attachments/files/15949553/disconnect-2024-06-23_23.40.42-client.txt)
[disconnect-2024-06-23_23.41.45-client.txt](https://github.com/user-attachments/files/15949554/disconnect-2024-06-23_23.41.45-client.txt)

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.28

### Mekanism version

10.6.2 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

not able paste whole recent log.

**Comment by pupnewfster** [comment]
It looks like all those crashes are related to AE2's facade recipe.

**Comment by trunksbomb** [comment]
@Hellzy87 That issue is fixed in the latest release of AE2.

**Comment by ghost** [comment]
just updated the mods before bed, i be trying again tmmrw. thanks
