### ISSUE TITLE
Newest Version Crash

### ISSUE THREAD

**Issue by Bazyliii** [mekanism/Mekanism#8136]
### Issue description

Mekanism-1.21-10.6.2.46 Crashes at start using NeoForge 21.0.37-beta.

Keep up with a good work anyway!

### Steps to reproduce

1. Install NeoForge
2. Add Mekanism
3. Run game

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.37-beta

### Mekanism version

10.6.2 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/UAv3bmJ3

**Comment by UnknownSerhan** [comment]
Be patient, neo versions above .30-beta is not supported yet due to neo making changes. You can compile the mod from github which has the fix, if you want to play.

**Comment by Fidulus** [comment]
> Be patient, neo versions above .30-beta is not supported yet due to neo making changes. You can compile the mod from github which has the fix, if you want to play.

I may sound stupid, but because i want to play it so bad i still gonna ask: can you tell me what i need to do with just a few more steps? Thank you very much

**Comment by UnknownSerhan** [comment]
You need to download the source code for 1.21.x and compile it through gradlew, IntelliJ or Eclipse. I use IntelliJ to compile mods. Do you know how to compile it?

**Comment by Fidulus** [comment]
> You need to download the source code for 1.21.x and compile it through gradlew, IntelliJ or Eclipse. I use IntelliJ to compile mods. Do you know how to compile it?

Ohhh i get it, thank you very much for taking the time
I am trying to compile it right now via windows console
I hope that works also

 :-) Have a great day
