### ISSUE TITLE
Robit skin not changing properly

### ISSUE THREAD

**Issue by marmot418** [mekanism/Mekanism#8138]
### Issue description

when I try to change the robit skin to default it changes to a random other skin

### Steps to reproduce

1. open robit skin change menu 2. select default

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

20.4.237

### Mekanism version

Older

### Other relevant versions

mekanism version 10.5.20.41 minecraft version 1.20.4

**Comment by pupnewfster** [comment]
This is intended behavior for the month of June. You can disable `holidays` in the `Mekanism/common.toml` config.

**Comment by pupnewfster** [comment]
While this is intended/a side effect of how things are implemented, it has been pointed out to me by others on the dev team that this isn't great UX. As such I am adding a thing that if you manually select the default skin after it has changed then it will persist that change and not change off of the default skin for various occasions.
