### ISSUE TITLE
Crash log for 1.21 - NeoForge 21.0.39 - Mekanism 10.6.3

### ISSUE THREAD

**Issue by Fidulus** [mekanism/Mekanism#8142]
### Issue description

Maybe my crash-log can help shed some light on any compatibility issues.
It´s running fine without mekanism (but i love the mod too much to play without it).
I guess it´s something between "architectury" and "mekanism" but ofc i am not sure...
I even tried to use a compiled version directly from the newest code but to no avail.

NeoForge: 21.0.39 (because 21.0.40 breaks architectury)

https://pastebin.com/DQs8iU1Q

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.39 beta

### Mekanism version

10.6.3 (Latest)

### Other relevant versions

older versions don´t seem to work either

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/DQs8iU1Q

**Comment by UnknownSerhan** [comment]
I launched on .40-beta with architectury and mekanism installed and it launched fine. Also that crash report only points to architectury, no mekanism at all.

**Comment by Fidulus** [comment]
> I launched on .40-beta with architectury and mekanism installed and it launched fine. Also that crash report only points to architectury, no mekanism at all.

Thank you very much for the kind reply and trying that out. so the culprit might be something else entirely.
I am gonna use the newest neoforge .40 and try again.

ps: After upgrading to .40 and all mods to the newest version everything works except for "jade" which shows some errors but thats not mekanism related at all.

As a sidenote: The latest update included "Collective". 

I am very sorry if I have posted something not related to mekanism but because of my trial and error it pointed that way imho.
