### ISSUE TITLE
PRC not accepting Plutonium gas

### ISSUE THREAD

**Issue by Nidaelie** [mekanism/Mekanism#8146]
### Issue description

PRC not accepting the plutonium gas from an isotopic centrifuge

### Steps to reproduce

process waste in an isotopic centrifuge...

use a press pipe or connect directly to a prc

prc not accepting the gas....

the recipe is the default one

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

1.20.1

### Mekanism version

Older

### Other relevant versions

mek 10.4.8 (Jun 3, 2024)

**Comment by UnknownSerhan** [comment]
Are you sure the gas sides are set correctly? This is very likely to be a simple issue

**Comment by Nidaelie** [comment]
Im very  sure, it is an Old issue closed and not fixed apparently

**Comment by UnknownSerhan** [comment]
This issue is fixed in the discord server, basically a duplicate of https://github.com/mekanism/Mekanism/issues/7831.

**Comment by Nidaelie** [comment]
fixed with discord help
