### ISSUE TITLE
Crash when using Farming Unit with Meka-tool

### ISSUE THREAD

**Issue by Fidulus** [mekanism/Mekanism#8147]
### Issue description

Trying to use the farming unit results in a crash.
I am very sorry if this is NOT actually caused by Mekanism but to me it seems that way.
If it is related i hope the provided crash log can help fixing.

### Steps to reproduce

1. Deactivate all conflicting units in Meka tool ui
2. Activating "farming unit" 
3. right click a dirt block

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.40 beta

### Mekanism version

10.6.3 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/cDctUsZc

**Comment by Fidulus** [comment]
Sorry, i think it´s related to glitch core... 
false alarm. I am just stupid

**Comment by UnknownSerhan** [comment]
Yeah just tested and it looks like a problem on GlitchCore's end.

**Comment by Fidulus** [comment]
> Yeah just tested and it looks like a problem on GlitchCore's end.

seems i am getting just a tiny bit better at discovering whats actually wrong.
Thank you very much again for the confirmation :-)
Maybe in the future i am able to understand exactly whats wrong and pinpoint it right away.
