### ISSUE TITLE
1 UO2 and 1 HF Gives 2 UF6

### ISSUE THREAD

**Issue by soopernovae** [mekanism/Mekanism#8148]
### Issue description

Not a bug or glitch, just a notice. In the creation of fissile fuel, one hydrofluoric acid and one uranium oxide gives 2 uranium hexafluoride. Given the realism of everything else, just wondering if this was an intentional thing to reduce resource strain, or if it might be something that might want to be considered.

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

47.4.20

### Mekanism version

Older

**Comment by UnknownSerhan** [comment]
Changing this would cause confusion and make things harder for players. So I guess making things easier was picked over making things super realistic

**Comment by YocyCraft** [comment]
mb is not proportional to mol

**Comment by kienerxyzzy** [comment]
> mb is not proportional to mol

it's in millibuckets, and depending on the density of the fluid, it can change.
so look up the density of those chemicals

**Comment by kienerxyzzy** [comment]
also the only way to do ratios would be to require a lot of fluid
Ex: a 120:121 ratio can only be achieved with 120mB of one and 121mB of the other, so you need more to even get started
