### ISSUE TITLE
Blocks Duplicate

### ISSUE THREAD

**Issue by MightyOwl3030** [mekanism/Mekanism#8151]
### Issue description

There is a Problem with the QIO Storage System, In the ATM10 , if you take Blocks Like Redstone, Iron, Gold etc. and convert them Back into ingots , it doesn´t take the Block out of the Inventory and just give out Like 9 Ingots 

### Steps to reproduce

1.Create a Block 2. Convert it Back 3. Endless Ingots  

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.24

### Mekanism version

10.6.3 (Latest)

**Comment by thiakil** [comment]
If you have multiple blocks in the system it will refill the crafting grid with another.

Are you sure that's not what's happening here?

**Comment by UnknownSerhan** [comment]
I am pretty sure this is a duping bug in vanilla itself. Try with a crafting table

**Comment by MightyOwl3030** [comment]
> If you have multiple blocks in the system it will refill the crafting grid with another.
> 
> Are you sure that's not what's happening here?

Nope It doesn´t take the Blocks out of the system 1 Block is enough to duplicate any amount

**Comment by MightyOwl3030** [comment]
> I am pretty sure this is a duping bug in vanilla itself. Try with a crafting table

I checked but the Crafting Table works fine

**Comment by pupnewfster** [comment]
Can you reproduce this with just Mekanism? I am not able to
