### ISSUE TITLE
HDPE Sheet enrichement chamber JEI recipe is wrong

### ISSUE THREAD

**Issue by MATMANOFFICIAL** [mekanism/Mekanism#8152]
### Issue description

![image](https://github.com/mekanism/Mekanism/assets/140093893/a4b71e57-3af9-4692-85f5-0dc2054d4707)
As you can see here it shows it's like that but in reality it's 3 hdpe pellets to one sheet

### Steps to reproduce

1. Open JEI
2. Check HDPE Sheet enriching recipe
3. Compare with reality
4. See how it's not the same

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.24-beta

### Mekanism version

10.6.1

**Comment by pupnewfster** [comment]
Update to EMI 1.1.9 or downgrade to EMI 1.1.7. Apparently this is a bug in EMI 1.1.8
