### ISSUE TITLE
- 21.0.68 SpawnPlacementRegisterEvent -> RegisterSpawnPlacementsEvent

### ISSUE THREAD

**Issue by ootwclyhe** [mekanism/Mekanism#8156]
### Issue description

neoforge changed

### Minecraft version

1.21 (Latest)

### NeoForge version

neoforge-21.0.76-beta

### Mekanism version

10.6.4 (Latest)

**Comment by UnknownSerhan** [comment]
Known issue, be patient and wait for the update. Neo is in a breaking-changes stage.
