### ISSUE TITLE
Mek Tank Fluid void

### ISSUE THREAD

**Issue by Callum4733** [mekanism/Mekanism#8161]
### Issue description

Shift right clicking a tank of any volume with any wrench gives you back an empty tank instead of the amount you had. 

### Steps to reproduce

1. Filling any tank with any liquid. 
2. Place Tank Down
3. Shift Right click with any Wrench

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

20.4.237

### Mekanism version

Older

### Other relevant versions

FTB Neotech 1.4.2

**Comment by pupnewfster** [comment]
I can't reproduce this issue in 1.21
