### ISSUE TITLE
Permission System supersedes level 4 OP rights. WTF?

### ISSUE THREAD

**Issue by Speiger** [mekanism/Mekanism#8162]
### Issue description

o/  That is kinda a bad thing. You literally should be able as a OP with lvl 4 op rights (SERVER OWNER) to access any machine even if it is security locked.
Even level 3 should be able to access it.
Level 2 is debatable since command blocks usually use these too.

But OP rights should in general work for breaking/maintaining blocks without having to get down to commands.

I checked the config its not a config option either.

### Steps to reproduce

- 1: Install mekanism
- 2: Make a machine and enable security
- 3: Make it so NOBODY can use it (3rd party)
- 4: Now try to move the machine without commands.
- 5: PROFIT!

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

Any

### Mekanism version

10.6.5 (Latest)

### Other relevant versions

1.19.2 version

This should be fixed accross all versions imo.

**Comment by thiakil** [comment]
![image](https://github.com/user-attachments/assets/028dee76-be00-4f16-b539-513755457c41)

This has been a thing since at least 1.7

**Comment by Speiger** [comment]
@thiakil ok that's my fault for overseeing this.
Sorry ^^"
And thank you!
