### ISSUE TITLE
Ore texture inconsistency 

### ISSUE THREAD

**Issue by JohnGoten** [mekanism/Mekanism#8169]
### Issue description

Tin ore uses a lighter gray stone texture that does not match that of the otherwise intended look.
As far as I can tell, this appears to be exclusive to tin.
![2024-07-25_02 06 41](https://github.com/user-attachments/assets/13f979cc-d7e1-4b7d-8daa-79eb9f20b774)

### Steps to reproduce

- Head into a cave or open up the creative inventory
- Look for "Tin Ore"
- Discover the problem at hand

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.133-beta

### Mekanism version

10.6.6 (Latest)

**Comment by pupnewfster** [comment]
Funnily enough this was meant to be fixed in 10.6.6, but I forgot to upload the fixed textures. Oops, thanks for the reminder.

**Comment by JohnGoten** [comment]
Decided it might be worthwhile mentioning it as I believe to have noticed a couple changes recently that really spice it up after all these years of seemingly untouched texture
Not just exclusive to Mekanism as e.g. AE2 received a major overhaul which caught me by surprise
but good work all around!
