### ISSUE TITLE
Each Ore does NOT give me 2 Dust to then create 2 Ingots.

### ISSUE THREAD

**Issue by SirTwsted** [mekanism/Mekanism#8170]
### Issue description

As the title says,
Each Ore does NOT give me 2 Dust to then create 2 Ingots.
When placing Ores in the Enrichment Chamber I DO NOT get 2 dust for every 1 Ore placed in the machine.
It wants me to place 3-Ores,  and only gives me back 4-dust, so where is the doubling?  🤷‍♀️

### Steps to reproduce

Use the Enrichment Chamber
Place Ore into Enrichment Chamber

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

20.4.237

### Mekanism version

Older

### Other relevant versions

I am placing MC-v1.20.4  because other many mods have yet to update to 1.21  🤷‍♀️

By the way I did try this on MC v1.21 self made custom mod pack that included Mekanism.
And it does the same thing.  🤷‍♀️

**Comment by UnknownSerhan** [comment]
Raw ores have a lower conversion ratio in ore processing than silked ores.

**Comment by SirTwsted** [comment]
> Raw ores have a lower conversion ratio in ore processing than silked ores.

Wow, that means I will be forced to find another mod that specifically does ore doubling.   🤦‍♂️
Because by the time I find an Enchanted Book for Silk Touch, I would have wasted so many ores building things.
It's not easy to find a Silk Touch book, as I am already 9 RL days playing and haven't found one yet. 🤷‍♀️
