### ISSUE TITLE
Factory ticks without anything inside

### ISSUE THREAD

**Issue by VoidTest** [mekanism/Mekanism#8179]
### Issue description

When a factory is empty it still ticks and tries to auto eject

### Steps to reproduce

1. Place a factory
2. Run a spark profiler
3. Check the profiler for factory ticking

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.146

### Mekanism version

10.6.7 (Latest)

**Comment by thiakil** [comment]
please provide your spark profile evidence

**Comment by UnknownSerhan** [comment]
This issue was talked on discord, pupnewsfter will fix it. This is just a reminder issue.
