### ISSUE TITLE
processing brine in a electrolytic separator breaks my world

### ISSUE THREAD

**Issue by Destral1** [mekanism/Mekanism#8180]
### Issue description

Whenever I put brine in an electrolytic separator the game errors, giving me this message:
![image](https://github.com/user-attachments/assets/efdf55cb-b49e-4877-a584-cd35b378a29a)
Processing water works just fine.
I set the electrolytic separator to "redstone detection: normal" and it was fine until I changed it.
I tried setting it in a different chunk, errored.
I tried to replicate the issue in a creative world, and the separator worked fine.
Whenever I try to load the world after, I get the same error and have to load a backup.

### Steps to reproduce

1. put brine in an active, powered electrolytic separator
2. error

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.146

### Mekanism version

10.6.7 (Latest)

### Other relevant versions

I'm playing on All the mods 10.

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

There's nothing in crash-reports from today.

**Comment by thiakil** [comment]
we'll need to see the debug log from the log folder

**Comment by Destral1** [comment]
[latest.log](https://github.com/user-attachments/files/16451734/latest.log)
I think this is it?

**Comment by Destral1** [comment]
I believe the issue was in laserio, not mekanism, and has since been resolved
