### ISSUE TITLE
FE - Joule Conversions Are Inconsistent After Energy is No Longer FloatingPoint

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#8182]
### Issue description

Inserting energy upgrades into the PRC one by one, some upgrades have literally no effect at all. This is the result with the biofuel -> substrate recipe:

https://github.com/user-attachments/assets/405b5ef6-1296-492a-a583-cdda4fc2aacd

### Steps to reproduce

1. Get a PRC and start inserting energy upgrades one by one.
2. See that the usage doesn't sometimes decrease at all, also see the 8 energy upgrade usage isn't correct either.

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.145

### Mekanism version

10.6.7 (Latest)

**Comment by thiakil** [comment]
IIRC when we mathed it out it was 'correct' but eventually this won't be a problem after power rebalance
