### ISSUE TITLE
Where's all energy generators?

### ISSUE THREAD

**Issue by Danya1771** [mekanism/Mekanism#8185]
### Issue description

I can't found any energy generators and I can't test it alpha, because it bug :(
![2024-08-03_12 29 12](https://github.com/user-attachments/assets/16240604-c450-49cf-9531-6d6920734f85)
![2024-08-03_12 29 55](https://github.com/user-attachments/assets/0d2de037-f876-414f-ba7a-ea864ce63e4b)
![2024-08-03_12 30 02](https://github.com/user-attachments/assets/828323e1-456c-4f35-8acd-78e3e61444f4)

### Steps to reproduce

1. Download latest version of Mekanism (10.6.7.54 for neoforge 1.21)
2. Launch Minecraft and go to any world
3. Search for any generators or try to craft!

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.143

### Mekanism version

10.6.7 (Latest)

**Comment by thiakil** [comment]
Mekanism: Generators has the generators
