### ISSUE TITLE
XP Dupe With Meka-Tool

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#8190]
### Issue description

Using the silk touch unit on the Meka-Tool and then mining blocks that drops XP causes a simple XP dupe where both XP and the blocks drop.

https://github.com/user-attachments/assets/5c559c86-1d23-4e9a-97ff-148edf498276

### Steps to reproduce

1. Get a Meka-Tool and install silk touch unit.
2. Break blocks that drops xp.
3. See that both xp and blocks are dropped.

### Minecraft version

1.21 (Latest)

### NeoForge version

21.0.148

### Mekanism version

10.6.7 (Latest)

**Comment by Kazuhiko-Gushiken** [comment]
yeah I got this too.

https://youtu.be/oYQUvpzKmlg

**Comment by UnknownSerhan** [comment]
Turns out, for some reason, Adorned (Curios) mod for 1.21 was the reason for this dupe. The same happens with silk touched pickaxes too, so not only mekatool. Curios got an update recently and fixed this on their end. In conclusion, this is not a mekanism issue.
