### ISSUE TITLE
Crash due to server Timing out

### ISSUE THREAD

**Issue by Flame1211** [mekanism/Mekanism#8194]
### Issue description

Issue has been occuring for a little over a week now. Server crashes due to spark: timed out waiting for world statistics. only happens after occasional world restarts, if it happens I usually have to roll back the server a few hours as whatever happens happens silently and bricks the backup files that have the issue. cant find anything in console related to it so its unknown if its broken until the restart. crashlog points to mekanism so thought id put a report in here. 

### Steps to reproduce

play server normally, everything seems fine, server restarts, timed out waiting for world statistic. server crashes due to watchdog. (ive tried making watchdog infinite, server never recovers)

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

Normal Forge. Client: 47.2.17 Server: 47.3.5

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/q5qih3iw

**Comment by thiakil** [comment]
That log just prints what was running at the time the watchdog had enough, not necessarily what caused it.

You'll need to run a profiler external to MC (e.g. VisualVM) on startup to find the true cause.

**Comment by Flame1211** [comment]
alright ill give it a shot and get back to you here if the issue still seems to be mekanism, if it isnt Ill close the report.

Edit, ive never used visualVM before, is there anything specific im looking for?

**Comment by thiakil** [comment]
Attach to a process, Click the Sampler tab and start a CPU sampling session, check the Total Time (CPU) column

**Comment by Flame1211** [comment]
alright these seem to be the highest and the only ones that continue to tick up after the timing out starts: 
![image](https://github.com/user-attachments/assets/bd66b16a-49e0-4e45-91cd-9c1b235c0c4e)

**Comment by thiakil** [comment]
You'll want to expand the server thread one and dig deeper (again, make sure to sort by CPU time not total time)

**Comment by Flame1211** [comment]
yeah realized it was sorted by total after i sent it
first image, sorted by total cpu:
![image](https://github.com/user-attachments/assets/7e0890d5-d311-4110-b7ae-4e881a65043c)

following total time down the chain in server thread, this is where it stopped:
![image](https://github.com/user-attachments/assets/8ed390ea-c161-4a8f-a333-02bdc012e3fc)

**Comment by thiakil** [comment]
Odd, it's trying to get a tile entity in an unloaded chunk, which shouldn't really be happening. I think that method is supposed to be checking that, but will have to check

**Comment by Flame1211** [comment]
Alright, sounds good. 

Is there an easy fix for this on my end?

**Comment by thiakil** [comment]
OK, that method does indeed check that the block is loaded. Your server is reporting that it is loaded, but is then trying to load it from disk.

You'll need to take that up with your modloader.
