### ISSUE TITLE
Electrolytic Separator won't separate water

### ISSUE THREAD

**Issue by SSolarite** [mekanism/Mekanism#8195]
### Issue description

This started happening a few days ago and i'm not sure why it's still happening. I have an ethylene generator that uses an Electrolytic Separator, it was separating water fine a few days ago but now it's not doing anything and i'm running out of power.
![image](https://github.com/user-attachments/assets/f89e9f47-5c33-4e12-85a4-9e29480e02fd)
I've even checked my side configuration and all the sides are set to Input (red) 
![image](https://github.com/user-attachments/assets/b4433148-e882-4607-9cc8-73a072337bc9)
I'm playing in multiplayer.

### Steps to reproduce

Unknown

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

forge 43.4.0

### Mekanism version

Older

### Other relevant versions

10.3.9

**Comment by SSolarite** [comment]
1.19.2

**Comment by thiakil** [comment]
Restart the server, or restart your client if single player. May require multiple restarts to fix it.
