### ISSUE TITLE
doesn't open the world having mekanism generators

### ISSUE THREAD

**Issue by Miguelanos32** [mekanism/Mekanism#8199]
### Issue description

crashes when i tried to play in a world

### Steps to reproduce

open minecraft
load a world
crash

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

1.19.2

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

-805306369

**Comment by thiakil** [comment]
need the crashlog, not just the useless error code

**Comment by Miguelanos32** [comment]
[crash-2024-08-16_18.08.15-server.txt](https://github.com/user-attachments/files/16642927/crash-2024-08-16_18.08.15-server.txt)

**Comment by Miguelanos32** [comment]
@thiakil 
I think it's one of the crashes, every time it happens, it tells me that to fix it I need to add more memory to the game and I'm playing with 32 GB of ram

**Comment by thiakil** [comment]
That error says your config file is corrupted. Delete `config/Mekanism/generator-storage.toml` 

Sorry I forgot about this issue.

**Comment by Miguelanos32** [comment]
Fixed!
