### ISSUE TITLE
The game crashed whilst rendering block entity Error: java.lang.NullPointerException: Cannot invoke "mekanism.api.SupportsColorMap.getRgbCode()" because "color" is null

### ISSUE THREAD

**Issue by wolfieboy09** [mekanism/Mekanism#8202]
### Issue description

![image](https://github.com/user-attachments/assets/ba93c906-05d2-49ea-8495-d7f3774b6ecc)

Placing a teleporter on an Eurika ship crashes MC, preventing world from being loaded with the mods listed below

![image](https://github.com/user-attachments/assets/6b935c39-bccf-4b8d-8903-2b416ee08634)

### Steps to reproduce

1. Make a Eurika! Ship
2. Assemble the very ship
3. Place a teleporter on it
4. Crashes from teleporter

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

47.3.5

### Mekanism version

10.6.7 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/X6zU6QFB

**Comment by pupnewfster** [comment]
I am going to just go with they probably don't sync all of the block entities data
