### ISSUE TITLE
render crash when creative tank appears in jei

### ISSUE THREAD

**Issue by rfields99** [mekanism/Mekanism#8212]
### Issue description

I am getting a crash when I start looking up something in jei, specifically the letters "me". The crash log points to the creative tank and this seemingly happened out of nowhere.

### Steps to reproduce

1.launch game
2. play the game normally
3. search "me" in jei
4. game crashes

### Minecraft version

1.21.0

### NeoForge version

1.21

### Mekanism version

10.6.7

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/uSxW6bXV

**Comment by thiakil** [comment]
That looks to be some sort of interaction between EMI and another mod patching into the renderItem method. Not directly related to Mekanism

**Comment by rfields99** [comment]
Thank you after much trial and error i found it was the mod stellaris causing this issue.
