### ISSUE TITLE
Game crashing with event handler error on Forge 1.20.1

### ISSUE THREAD

**Issue by BIPPY991** [mekanism/Mekanism#8213]
### Issue description

It seems to be an issue with this mod and Just Enough Items.
Whenever I use Just Enough Items to check a recipe, whenever I exit my inventory or crafting menu etc after checking a mekanism recipe the game crashes but the server does not.

### Steps to reproduce

1. Find a mekanism crafting recipe in just enough items.
2. Click that recipe
3. Exit inventory by pressing E or ESC
4. Game Crashes

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

Forge 47.3.5

### Mekanism version

Older

**Comment by Jorue23** [comment]
Provide your crash log please.

**Comment by BIPPY991** [comment]
> Provide your crash log please.

[crash-2024-08-22_10.45.52-client.txt](https://github.com/user-attachments/files/16708621/crash-2024-08-22_10.45.52-client.txt)

**Comment by Jorue23** [comment]
At the top of the crash log it recommends you to go and consult Sinytra or Lunar Pixel. I’d start with Lunar Pixel but this is not caused by Mekanism.

**Comment by thiakil** [comment]
yup, that's a fabric connector issue
