### ISSUE TITLE
Forge Microblocks can not cover any cables/pipes

### ISSUE THREAD

**Issue by cosmicdan** [mekanism/Mekanism#822]
Universal Cable nor Mechanical Pipes can not be covered with the (arguably) mod-universal Microblocks made with "Forge Essentials" saws, despite the visual assumption of it being possible.

Using Forge Microblocks over any other Microblocks mod (e.g. Immibi's, Project RED, etc.) would be the ideal only solution, since they can cut most blocks added by other mods and will also surround many other mod-added objects.

This would be a great feature obviously for aesthetic reasons, but is a minor request/priority.

**Comment by victoroos** [comment]
Is it stable now? Cause for me it still doesn't work and I'm on version 9.2.2.301

**Comment by thommy101** [comment]
You're replying to an almost 3.5 year old issue. ForgeMultipart support has dropped in favour of MCMultiPart for 1.10

**Comment by victoroos** [comment]
OOh, my mistake.
