### ISSUE TITLE
Memory Leak of Client Level

### ISSUE THREAD

**Issue by pietro-lopes** [mekanism/Mekanism#8221]
### Issue description

This is kinda of a soft leak, as it refreshes itself when you join another world.

![image](https://github.com/user-attachments/assets/eb2f19dc-e45d-4250-abe2-6fdf3e9bdc10)

Might want to add a cleanup strategy when single players exit world to clear MekanismClient.

### Steps to reproduce

1. Join world
2. Leave world
3. Check memory for leaked objects

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.23

### Mekanism version

10.6.7

**Comment by thiakil** [comment]
this should be fixed with https://github.com/mekanism/Mekanism/commit/59645a938d415495461c71b7b529ed546d5338ad

**Comment by pietro-lopes** [comment]
Does it cover Client player logout?

**Comment by thiakil** [comment]
It should always have been clearing at that point?

**Comment by pietro-lopes** [comment]
IIRC, Clone does not trigger at logout.
A good rule of thumb is that at main menu, there should be no client level/player, server, etc. instances alive.

**Comment by thiakil** [comment]
Indeed it would not fire, but the existing reset method should have been firing is what I meant
