### ISSUE TITLE
Digital Miner Fails to Scan The Area Correctly

### ISSUE THREAD

**Issue by UnknownSerhan** [mekanism/Mekanism#8222]
### Issue description

In singleplayer, when we set up some digital miners, install anchor ugprades to them, and if we leave the world and rejoin, we see that the digital miners' "to mine" number goes down. If we reset the miner and start it again, it scans the area correctly.

Here is a video of the issue:

https://github.com/user-attachments/assets/5eaf9a8f-b544-4dc0-86c4-6f34b8c617ab

### Steps to reproduce

1. Place digital miners around your world, configure them to max parameters, set them to mine something and install anchor upgrades.
2. Leave the world and join back.
3. See that the to mine number went down.

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.35

### Mekanism version

10.7.7 (Latest)

**Comment by Brizo24** [comment]
I've placed the digital miner where uraniums are at, yet it's being avoided to be mined by the digital miners, please fix.
