### ISSUE TITLE
Mekanism Sorter issue

### ISSUE THREAD

**Issue by PillowMan123456789** [mekanism/Mekanism#8224]
### Issue description

So i set up a system to send all my infusion mats (diamond,coal,obsidian,ect) through an enriching factory. then it goes straight to a sorter. to some chests for overflow and then out the chest into a logistical transporter to a infusion factory. However once the items get sorted and thrown into the overflow chest. The items will not then be pulled out the overflow chest into the infuser. Been trying to figure this out for a while. even posted in discord on multiple servers and all I get are people that dont know what they are talking about trying to tell me that Mekanism machines dont auto input only output. Yet when i put two chests with a logistical transporter in between the items will transfer without a sorter in between. So Yeah.

### Steps to reproduce

1 Make enrichment Factory
2 put a sorter on it with logistical pipes going to a chest just before the infuser. Make sure that there is a logistical pipe in between the infuser and chest for overflow.
3 Set your sorter up
4 Try and send diamonds or whatever through the enrichment factory to your chest then the infuser
5 realize they stopped in the chest and wont pull out.

### Minecraft version

1.21.1 (Latest)

### NeoForge version

N/a using Curseforge

### Mekanism version

10.7.7 (Latest)

**Comment by thiakil** [comment]
replied on discord
