### ISSUE TITLE
Mekanism Crash - java.lang.NoClassDefFoundError: mekanism/api/providers/IGasProvider

### ISSUE THREAD

**Issue by MrEizy** [mekanism/Mekanism#8226]
### Issue description

Just searching pipe in creative mode and it shows up with pipez gas pipe it causes a crash after a couple seconds

### Steps to reproduce

Pipez and Mekanism installed
Searching for Pipe in creative mode
Causes the game to crash

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.46

### Mekanism version

10.7.7 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/9Gs9r373

**Comment by thiakil** [comment]
That's a Pipez issue. try updating it
