### ISSUE TITLE
Bone meal dupe

### ISSUE THREAD

**Issue by Karotte128** [mekanism/Mekanism#8227]
### Issue description

It is possible to duplicate bone meal using the crusher

### Steps to reproduce

1. Craft bone block using 9 bone meal
2. Crush the bone block in the crusher -> 18 bone meal
3. Craft bone blocks with the new bone blocks
4. repeat duplicating bone meal

### Minecraft version

1.21.1 (Latest)

### NeoForge version

latest

### Mekanism version

10.7.7 (Latest)

**Comment by zperk13** [comment]
Relevant commit: bfad1d1748eebc58e552e8b4c4d170bece82c88c
