### ISSUE TITLE
Mekanism + Powah + Pipez

### ISSUE THREAD

**Issue by Pundah** [mekanism/Mekanism#8230]
### Issue description

**What happened?**
If you connect an energy Cell from Powah and the Magmator from Powah with an Energy Pipe from Pipez, and then use a pipewrench to set the pipe at the magmator to input, you get a crash "Ticking Block entity"

### Steps to reproduce

You connect an energy Cell from Powah and the Magmator from Powah with an Energy Pipe from Pipez. 

Use a pipe wrench to set the pipe at the magmator to input; you get a crash "Ticking Block entity."

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.55

### Mekanism version

10.7.7 (Latest)

### Other relevant versions

Issues noted as far back as neoforge 21.1.34.

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Pundah/d76c85063fb586f04b1b8d762b6cbf54

**Comment by thiakil** [comment]
Update pipez
