### ISSUE TITLE
Filling a bucket with a liquid on a dynamic tank causes the world to crash and be broken

### ISSUE THREAD

**Issue by Urlocalhuman** [mekanism/Mekanism#8231]
### Issue description

I was using a dynamic tank in my creative world, and tried to fill a bucket up with the liquid inside it. The game had a sudden lag spike (using MSI Afterburner's monitoring tool (RTSS v7.3.4.27560)), i tried to close the gui because nothing was happening, and the game said "the server has closed" or something along the lines of that. I tried to re-open the world, and I got this:
![image](https://github.com/user-attachments/assets/8a84b7ce-9740-4529-890b-5c7c19447e9d) I tried opening the world again. but it still happened.
Someone please tell me what happened because i had spent a lot of time into that world, building random contraptions and stuff.

### Steps to reproduce

I don't know if it applies to all liquids, but what happened was I put a bucket in the top slot of a dynamic tank in the gui while the tank had some Gasoline in it (mod is: "Create: The Factory Must Grow", Mod Id: createindustry)

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

I was using forge not neoforge, my forge version was 43.3.9

### Mekanism version

10.7.7 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/zteiDKeD

**Comment by thiakil** [comment]
Sounds like your saved data is corrupted or the Diesel bucket item doesn't have a fluid handler

You'll need to restore from backup or edit the tank multiblock saveddata
