### ISSUE TITLE
Crash when opening the inventory

### ISSUE THREAD

**Issue by 12Mosch** [mekanism/Mekanism#8234]
### Issue description

When opening the creative inventory tools & utilities, the game crashes.

### Steps to reproduce

1. Open the creative inventory tools & utilities
2. Scroll down
3. The game crashes

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.57

### Mekanism version

10.7.7 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/12Mosch/31921ab3bc24126993fd92fe28138473

**Comment by thiakil** [comment]
One of your mods has a badly registered fluid (no texture).

But we do need to add some checks to stop it crashing
