### ISSUE TITLE
problem atomic disassembler

### ISSUE THREAD

**Issue by Michel1344** [mekanism/Mekanism#8237]
### Issue description

when i hold the at in hand there is no problem but as soon as i switch to any other item andthen open  the inv all icons appear invisible! Only the names appear

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

idk

### Mekanism version

Older

**Comment by thiakil** [comment]
this sounds like another mod doing weird things, as this does not happen in bas mekanism.

As there is no version info, we can't help without more info.
