### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by SirTwsted** [mekanism/Mekanism#8238]
### Issue description

I was searching my inventory within+ a chest, next thing I know I crashed.

https://pastebin.com/uzHKJJtF

### Steps to reproduce

I was searching my inventory within+ a chest, next thing I know I crashed.

https://pastebin.com/uzHKJJtF

### Minecraft version

1.21.1 (Latest)

### NeoForge version

NeoForge v21.1.61

### Mekanism version

10.7.7 (Latest)

**Comment by thiakil** [comment]
Update pipez

**Comment by SirTwsted** [comment]
pipez was updated to the latest version that my launcher found.  I am using Curseforge launcher, and it didn't find
any other updated versions.  Just saying  🤷‍♀️

Anyways, thank you for your time.

**Comment by thiakil** [comment]
Well, go report to them. They need to update their usage of out api

**Comment by SirTwsted** [comment]
Why so angry?  🤷‍♀️
Anyways, have a beautiful week.  😉👍
