### ISSUE TITLE
Can't connect to ad astra cables / cable ducts, pipes / pipe ducts

### ISSUE THREAD

**Issue by Kevadroz** [mekanism/Mekanism#8239]
### Issue description

The title pretty much explains it, ad astra cables and pipes visually connect but mekanism cables and pipes don't, functionally the connection isn't there.

I know that mekanism 1.20.1 is no longer in development but if / when ad astra updates it's probable the issue will reappear unless something has changed. So I'll leave this issue here.

### Steps to reproduce

1. Place a filled energy cube.
2. connect a mekanism cable to that cube.
3. connect an ad astra cable to the previous cable.
4. Place an empty energy cube, notice it not getting filled.

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

47.1.106

### Mekanism version

Older

### Other relevant versions

Ad Astra 1.15.18

**Comment by thiakil** [comment]
That means their cable does not offer an energy capability.
The issue is on their side and given mixing cables is generally not advised, we won't add specific support
