### ISSUE TITLE
10.3.9 - Pipes/Cables leading to Out of Memory on server

### ISSUE THREAD

**Issue by Scharage** [mekanism/Mekanism#8242]
### Issue description

Heyha, my friends and me are playing a modpak on a server, which includes Mekanism 10.3.9 . After we have placed multiple Logistical Pipes/Energy Cables we noticed our server started to lag after a while, reaching a Out of Memory at the end.

We deduced it must be the Pipes after we have profiled the server with visual vm (and removed them afterwards). Below is a screenshot of the relevant classes which climb in counts.
 
![image](https://github.com/user-attachments/assets/be9e9663-02a7-4996-9e2c-b3ef1b72f8a7)
It reached about 1 millionen BasicCapabilityResolver objects in just 20 minutes runtime. And many mekanism classes also reach high levels. (We have only placed about 50 pipes in total)

Do you know how this could happen? Or pointers how we can fix that codewise? (As i understand you do not develop the earlier versions anymore, so we would try it ourselves.)

Thx for working on such a great mod :)

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

43.4.2

### Mekanism version

Older

**Comment by thiakil** [comment]
first of all, is that a heap dump view? If not I don't see the relevance to an out of memory error

second, you'd need to locate where things are being allocated - you could have some yo-yo chunkloading going on (loading and then unloading due to another poorly coded mod)

**Comment by Scharage** [comment]
Yep this is a heap dump view. 

I looked into allocation. And it is allocated via the blockenitity, so i guess it is like you said and someone forces a regeneration of the blocks and it just randomly hits the mekanism cables. Below a screenshot of the allocation stacktrace:
![image](https://github.com/user-attachments/assets/4d9d01c3-a93b-476b-8371-3135894a4d44)
I am not really versed in minecraft and its code, what method would be called to achieve such a yoyo chunkloading?

**Comment by Scharage** [comment]
Update: I noticed that the chunkloading reason may be coppled to compact maschinery and not mekanism itself.
I just noticed it through mekanism as the cables are used to connect to the tunnels of them. 

Will close this issue, thank you for giving the suggestion it may be something with chunkloading :)
