### ISSUE TITLE
Mechanical Pipe fluid extraction rate is insufficient for large-scale fission reactor setups

### ISSUE THREAD

**Issue by demiquartz** [mekanism/Mekanism#8243]
### Issue description

In a large-scale sodium-cooled fission reactor setup (7x7x7 fission reactor - 7x7x7 Thermoelectric Boiler - 7x7x12 Industrial Turbine), I encountered an issue where Dynamic Tank's extraction rate limits its usability as a buffer for water in high-demand setups. Specifically, the Dynamic Tank, combined with Ultimate Mechanical Pipes, is unable to meet the necessary water transfer rate to sustain the reactor’s full operation. The current extraction rate of 32,000mB/t provided by the Ultimate Mechanical Pipe is far below the required 1,040,000mB/t, despite having over 100,000,000mB of water stored in the tank.

### Setup Details:
- **Reactor Configuration:**
  - Sodium-cooled 7x7x7 fission reactor consuming fuel at 52mB/t.
  - 7x7x7 Thermoelectric Boiler connected to the reactor.
  - 7x7x12 Industrial Turbine converting steam to water at 1,040,000mB/t.
  - Approximately 24,000,000mB of water needs to be buffered to maintain operation.
  
- **Problem:**
  - The Dynamic Tank, while capable of holding large quantities of water (over 100,000,000mB), is bottlenecked by the Ultimate Mechanical Pipe's extraction rate of 32,000mB/t.
  - This limitation makes it impossible to maintain the required water transfer rate, even though there is ample water stored in the tank.

- **Workaround:**
  - A workaround is to use multiple Ultimate Mechanical Pipes and buffer water in the pipes themselves. However, this solution is aesthetically displeasing and inefficient in terms of design.

### Expected Behavior:
- The Dynamic Tank should be able to output water at a rate that matches the demand of high-capacity reactor setups when sufficient buffer is available.

### Proposed Solutions:
1. **Input/Output Ports for Dynamic Tanks:**
   - Similar to the fission reactor and Thermoelectric Boiler, Dynamic Tanks could benefit from configurable input/output ports to allow for higher throughput of fluids.

2. **Increased Ultimate Mechanical Pipe Output Rate:**
   - Allow the extraction rate of Ultimate Mechanical Pipes in "pull" mode to be configurable or significantly increased to better match the needs of large-scale reactor setups.

### Additional Information:
This issue impacts large-scale power generation setups using sodium-cooled reactors and makes the Dynamic Tank impractical as a fluid buffer in such setups without resorting to aesthetically unappealing workarounds.

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.61

### Mekanism version

10.7.7 (Latest)

**Comment by thiakil** [comment]
Adjusted the title to reflect your actual issue.

> Allow the extraction rate of Ultimate Mechanical Pipes in "pull" mode to be configurable or significantly increased to better match the needs of large-scale reactor setups.

Please have a look at your configs, they already **are** configurable.

The Tank itself has no limit. It's also not really necessary to use one in a fission setup.

> A workaround is to use multiple Ultimate Mechanical Pipes and buffer water in the pipes themselves. 

There are two things you need to consider
- The pull rate of a Mechanical Pipe
- The total buffer of the pipe _network_

Both can be increased by adding more pipes to the network (connected to a valve in pull mode for the 1st one). The total buffer of the pipe network determines the maximum amount that can be sent through the pipe net in 1 tick.
