### ISSUE TITLE
how do i disable this login message?

### ISSUE THREAD

**Issue by VaporeonScripts** [mekanism/Mekanism#8244]
### Issue description

![image](https://github.com/user-attachments/assets/9cdb5414-3da5-47f3-9b45-7d169872d74e)

### Steps to reproduce

install the mod
launch

### Minecraft version

1.21.1 (Latest)

### NeoForge version

.69

### Mekanism version

10.7.7 (Latest)

### Other relevant versions

any ig

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

no

**Comment by thiakil** [comment]
you don't. It's there to remind you that you're using a version that can break at any time.
