### ISSUE TITLE
Mekanism generators crashed the game upon creating/entering a world

### ISSUE THREAD

**Issue by Michepoli** [mekanism/Mekanism#8245]
### Issue description

Open pack.
Select world and open it / create a new one.
Wait for it to load.
Loading gets stuck  and console reports errors.

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

Forge 47.3.11

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/Michepoli/2b82b647d889fd51f17ec308d530316e

**Comment by thiakil** [comment]
delete the file it mentions, your config file is corrupt

**Comment by Michepoli** [comment]
ok fixed thanks
