### ISSUE TITLE
mekanism multiblock tank randomly voiding

### ISSUE THREAD

**Issue by emaulium** [mekanism/Mekanism#8251]
### Issue description

My dynamic tanks and fission reactors coolant tank content get sometimes voided when I break mekanism tube/pipe or CC:Tweaked networking cable connected to it or when I launch my solo world.

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

using Forge

### Mekanism version

Older

### Other relevant versions

Mekanism1.20.1-10.4.9.61
Forge 47.3.0
Minecraft Java 1.20.1

**Comment by thiakil** [comment]
This is likely actually the longstanding bug where if the chunk the multiblock was in otherwise did not change, the way the multiblocks shuffle their UUIDs was not saving the new UUID to the Block Entities, and so on reload would not be able to locate the saved data.
