### ISSUE TITLE
Fusion Reactor Controller has "Empty Tag: forge:glass_panes" in the crafting recipe.

### ISSUE THREAD

**Issue by MiloMiko** [mekanism/Mekanism#8253]
### Issue description

Hi, I installed Mekanism on my modpack and when going into the recipe for fusion reactor controller in JEI, it shows this:

![Zrzut ekranu 2024-11-09 154728](https://github.com/user-attachments/assets/426ee379-2c7b-4c51-bfd3-5f3c22c103a7)

As You see, there's an item labeled as missing tag.

### Steps to reproduce

1. Install Mekanism for forge 1.20.1 and JEI (Just Enough Items)
2. Launch the game
3. Open any world and go into the JEI menu
4. Search for Fusion Reactor Controller and click to show crafting recipe

Result: One of the items is shown as a barrier named 'Empty Tag: forge:glass_panes"

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

Forge 47.3.11

### Mekanism version

Older

**Comment by Jorue23** [comment]
If you added this to a modpack that didn’t have Mekanism previously. Another mod most likely changed something with the tag.
