### ISSUE TITLE
MC Instance Crashing when opening Creative Tabs 

### ISSUE THREAD

**Issue by InvokeUK** [mekanism/Mekanism#8254]
### Issue description

See crash report:
https://pastebin.com/aTXxs4Fx

As title says, when pressing "E" in creative mode, the MC instance crashes and disconnects from the server.
Using "E" to open Creative Tabs in Local Creative/Survival works fine, can scroll through tabs with no issues with Mekanism, only seems to be when run on server.

### Minecraft version

1.20.1

### NeoForge version

47.3.0

### Mekanism version

Older, 10.4.9.61

### Other relevant versions

Mekanism Additions 10.4.9.61

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://pastebin.com/aTXxs4Fx

**Comment by thiakil** [comment]
this looks a lot like one of your mods is straight up removing mekanism items from the registry

**Comment by InvokeUK** [comment]
Ah, my apologies, I managed to resolve it and completely forgot about this
issue ticket!

It sure was a case of meticulously switching things off and back on again
to see what conflicted. Sorry for raising the issue ticket, I was genuinely
so confused 😅
