### ISSUE TITLE
Game crashing when using Mekanism Logistical Transporter with Industrial Foregoing machines (Modpack used: All the mods 10)

### ISSUE THREAD

**Issue by tunes98** [mekanism/Mekanism#8255]
### Issue description

When you have an Industrial Foregoing (IF) machie, that is connected to any Inventory via a Logistical Transporter from Mekanism, the game freezes completeley, crashes and corrupts the chunk.
Sometimes while simply connecting and it freezes ALWAYS when breaking an active Transporter connection.

I tested this multiple times.
Connecting the IF machine via a Ender IO Item conduit works fine.
Mekanism Fluid Pipes also work.

The crash only happens from a IF machine to another inventory, when using the IF machines output setting "push"!

### Steps to reproduce

1. Place any Industrial Foregoing machine that produces an item.
2. Use a Logistical Transporter from Mekanism to connect the machine with any Inventory. (Chest, barrel etc.)
3. Set the Industrial Foregoign machine output to "push" and let the transporter transport Items.
4. Simply break one of the Logistical Transporter

!!! If the Industrial Foregoing machines output is already set to "push", the game might freeze as soon as you connect the machine to the inventory using the Mekanism Transporter. But this only happened once!

[crash-2024-11-12_21.53.27-server.txt](https://github.com/user-attachments/files/17734237/crash-2024-11-12_21.53.27-server.txt)

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.73

### Mekanism version

10.7.7 (Latest)

### Other relevant versions

Industrial Foregoing Version: 3.6.17

**Comment by thiakil** [comment]
we'll need a server profile from while this is happening - the crash is just where the watchdog had enough, not necessarily the point that the slowdown is actually occurring

**Comment by jstansel** [comment]
I tried with my homegrown pack (76 mods) and could not reproduce. I tried variations using the latex processing unit, resourceful furnace, basic logistical transporter, vanilla barrel, and basic bin. I did not have any crashes or other problems.

@tunes98 if you can still reproduce with the new version of ATM10 then I would suggest to report the issue to that team and reference this one.

NeoForge: 21.1.89
Mekanism: 10.7.7
Industrial Foregoing: 1.21-3.6.21
Titanium: 4.0.30
