### ISSUE TITLE
Server crash - getChunkForPos

### ISSUE THREAD

**Issue by MasterVitro** [mekanism/Mekanism#8257]
### Issue description

When a player loads a specific chunk, chunk dosn't load client by walking - chunks stop loading and entities stop moving.
Or logging in - times out on loading screen.
Server crashed due to single server tick taking too long.

Had the issue several times where I needed to use a editing tool to delete/reload chunks.
Only thing I've placed once was power cubes and energy pipes.
May be related to copy paste with WorldEdit but not sure.

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

Forge Version: 1.20.1- 47.3.0

### Mekanism version

Older

### Other relevant versions

Forge Version: 1.20.1- 47.3.0
Mekanism Version: 10.4.9

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/MasterVitro/a0ab61e9bb2b456fffd9dd2fb14ee616

**Comment by thiakil** [comment]
Looks like something is forcing a world load, which our helpers specifically try to avoid.
I suggest trying to remove some mods listed on line 22: 
`{re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:botania_xplat.mixins.json:LevelAccessor,pl:mixin:APP:adastra.mixins.json:common.multipart.LevelMixin,pl:mixin:APP:unsafe-world-random-access-detector.mixins.json:MixinWorld,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:citadel.mixins.json:LevelMixin,pl:mixin:APP:ars_controle.mixins.json:LevelGetEntitiesAccessor,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:gtceu.mixins.json:LevelMixin,pl:mixin:APP:neruina.mixins.json:catchers.WorldMixin,pl:mixin:APP:doespotatotick.mixins.json:WorldMixin,pl:mixin:A`
