### ISSUE TITLE
Missing recipes

### ISSUE THREAD

**Issue by BazZziliuS** [mekanism/Mekanism#8261]
### Issue description

Mekanism 10.4.9
Crafts in blocks from mekanism fall off completely randomly
I didn't find any logic in this, they just stop working immediately after the server starts or after some time
I tried to find a pattern for about a month, but I still haven't found it, I hope you can do something about it

![javaw_ncH7C8EIVN](https://github.com/user-attachments/assets/b340bc3e-40ae-45b8-8fb5-808ad5ddfb9c)

### Steps to reproduce

Start server
Wait

### Minecraft version

1.20.1

### NeoForge version

Forge: 47.3.10

### Mekanism version

Older

### Other relevant versions

I don't know, but I'll leave a list of mods just in case
https://paste.fuix.net/RPo3hte

**Comment by thiakil** [comment]
Its a weird forge bug, it doesnt load all the recipes. no known fix. #7831

Server needs to be restarted when it occurs

**Comment by bukowski912** [comment]
(Sorry for the necro).

@BazZziliuS , I went through your mods, and compared them to others in #7831. Here's what I found in common:

- `appleskin`
- `applied-mekanistics`
- `architectury`
- `balm`
- `betterf3`
- `cloth-config`
- `curios`
- `elevatorid`
- `framedblocks`
- `geckolib`
- `iceberg`
- `jei`
- `kubejs`
- `mekanism`
- `mekanism-generators`
- `mekanism-tools`
- `mousetweaks`
- `patchouli`
- `placebo`
- `rhino`
- `spark`

Would you be able to test your game again, using only the mods in that list, and see if you could reproduce the issue? It would be extremely helpful.

**Comment by BazZziliuS** [comment]
Sorry, but I'm running a server with active players and have no way to check.
