### ISSUE TITLE
JEI conflicting with the Mekanism mod

### ISSUE THREAD

**Issue by DotDotDotDashDashDashDotDotDot** [mekanism/Mekanism#8263]
### Issue description

I am new to the Mekanism mod and i was checking the recipes for the metallurgic infuser but after exiting, i crashed. 

### Steps to reproduce

Step 1: open the Metallurgic Infuser
Step 2: click on "Show Recipes"
Step 3: Exit out of the recipe screen
Step 4: crash

### Minecraft version

1.21.0

### NeoForge version

Forge - 47.3.11

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/DotDotDotDashDashDashDotDotDot/5f620134aa07359c48bd33fae1d8a8a5

**Comment by thiakil** [comment]
That's a fabric mod issue. Your modpack maker will be able to help you
