### ISSUE TITLE
Mechanism generators not not loading world

### ISSUE THREAD

**Issue by DUMPLINARCHIVE** [mekanism/Mekanism#8264]
### Issue description

When trying to enter a world after putting in the mechanism generators mode the world cannot loading and when I try to remove the mood still doesn't work I mean still does

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

0

### Mekanism version

Older

**Comment by thiakil** [comment]
There is not enough information to help you. Please provide some or the issue will be closed.

What are the symptoms of it "not working"?
