### ISSUE TITLE
Digital Miner Lagging

### ISSUE THREAD

**Issue by Imack92** [mekanism/Mekanism#8265]
### Issue description

When Approaching a Digital miner that was at Light Level Zero Frames dropped to 1FPS. Once broken frames returned when replaced in different chuck with light level zero same issue when torch was placed frames returned ATM10 

### Steps to reproduce

Place a Digital Miner with no light sources around in ATM 10 Latest Version 
![2024-12-01_20 31 42](https://github.com/user-attachments/assets/862e7ff3-22cf-4838-ab70-1e3117afd317)

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.81

### Mekanism version

10.7.7 (Latest)

**Comment by thiakil** [comment]
Can you reproduce in a world with just Mekanism? if not, please report to ATM instead
