### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.objects.ObjectArrayList.get(int)" because "this.wrapped" is null

### ISSUE THREAD

**Issue by kikuitimonnzi** [mekanism/Mekanism#8266]
### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

Not in use.

### Mekanism version

10.4.9.61 (1.20.1)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

[crash-2024-11-30_22.56.30-client.txt](https://github.com/user-attachments/files/17972204/crash-2024-11-30_22.56.30-client.txt)
[crash-2024-11-30_18.50.13-client.txt](https://github.com/user-attachments/files/17972205/crash-2024-11-30_18.50.13-client.txt)
[crash-2024-11-30_18.02.25-client.txt](https://github.com/user-attachments/files/17972206/crash-2024-11-30_18.02.25-client.txt)
[crash-2024-12-01_22.09.54-client.txt](https://github.com/user-attachments/files/17972207/crash-2024-12-01_22.09.54-client.txt)

**Comment by kikuitimonnzi** [comment]
This is the first time I've reported a crash report or problem, so I may be missing a lot of things.

**Comment by thiakil** [comment]
Looks like a possible thread race condition

**Comment by ghost** [comment]
This happens a lot to players of atm10 too
Steps to reproduce are usually place a lot of cables/pipes/tubes and it will happen eventually

**Comment by lupeduplemur** [comment]
Same error, happens whenever I'rm placing mekanism cables/pipes, has only happened to me when interacting with ae2 items with mekanism cables, but not sure if it's relevant.

[crash-2024-12-10_00.59.04-client.txt](https://github.com/user-attachments/files/18076975/crash-2024-12-10_00.59.04-client.txt)

**Comment by fare-SansUndertale** [comment]
The game crashes whenever I place mekanism mechanical pipe down connected to any machine
[https://mclo.gs/UzbdEXY](https://mclo.gs/UzbdEXY)

**Comment by thiakil** [comment]
@lupeduplemur @fare-SansUndertale nope, yours are different code paths, looks like a Sodium issue similar to #8269

**Comment by thiakil** [comment]
Fixed, hopefully

**Comment by pietro-lopes** [comment]
@thiakil Just to add, this is caused by Entity Culling 
* https://github.com/CaffeineMC/sodium/issues/2985
