### ISSUE TITLE
Crash when opening inventory on a server in creative

### ISSUE THREAD

**Issue by TomRachun** [mekanism/Mekanism#8267]
### Issue description

whenever i open cretive inventory my game crashes

### Steps to reproduce

Just load into minecraft server i use aternos and then open inventory in creative with the mods that are in the crash report

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

1.20.1

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/TomRachun/582e74afc25f8055e3d6f0ad413c84f5

**Comment by thiakil** [comment]
Quite likely you have another mod doing funny business.
Perhaps one of the fabric mods is doing things that don't work in a Forge environment
