### ISSUE TITLE
The game crashed whilst rendering block entity Error: java.lang.NullPointerException: Rendering Block Entity

### ISSUE THREAD

**Issue by YasirSantiago** [mekanism/Mekanism#8269]
### Issue description

Game Crash when I place a gas pipe in my Valkerien Skies Ship (with eureka). 

### Steps to reproduce

make a valkerien skies ship using the helm from eureka then place down a pressurized tube. 

### Minecraft version

1.20.x or earlier (No longer being developed)

### NeoForge version

N/A

### Mekanism version

Older

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/YasirSantiago/a6cfa545302ee687b5342a83d4cae98b

**Comment by thiakil** [comment]
That's not crashing in our code.

Try without sodium, if it still happens then report to VS

**Comment by YasirSantiago** [comment]
alright
