### ISSUE TITLE
The game crashed whilst rendering block entity Error: java.lang.NullPointerException: Cannot read field "lastChemical" because "network" is null

### ISSUE THREAD

**Issue by YasirSantiago** [mekanism/Mekanism#8270]
### Issue description

Game crashed when connecting gas pipes to each other in a valkerien skies ship 

### Minecraft version

1.20.x (Latest)

### NeoForge version

N/A

### Mekanism version

10.4.10.6

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://gist.github.com/YasirSantiago/be392598d825d51c51f64d6d6a0211a2

**Comment by thiakil** [comment]
Fixed
