### ISSUE TITLE
When using the mek tool for chain mining, the client crashed, but the server did not crash

### ISSUE THREAD

**Issue by 1-weibai-1** [mekanism/Mekanism#8271]
### Issue description

When using the mek tool for chain mining, the client crashed, but the server did not crash
[minecraft-exported-crash-info-2024-12-15T19-22-48.zip](https://github.com/user-attachments/files/18140239/minecraft-exported-crash-info-2024-12-15T19-22-48.zip)

### Steps to reproduce

我使用第2种连锁

### Minecraft version

1.21.1 (Latest)

### NeoForge version

21.1.7.3

### Mekanism version

10.7.7 (Latest)

**Comment by 1-weibai-1** [comment]
Fast mining chains also have this problem

**Comment by thiakil** [comment]
This is something wrong with `Subtle Effects`
