### ISSUE TITLE
Client crash on writing to client.toml during gameplay

### ISSUE THREAD

**Issue by ghost** [mekanism/Mekanism#8277]
### Issue description

Relaying issue from ATM discord, several users have reported these crashes to us over a period of several months now. Client will crash on writing to client.toml config file when moving gui positions in machine guis or doing HUD related actions
This is a known issue in nightconfig conflicting presumably with windows defender, reproduction can be hard, as it depends on windows defender doing things
Relevant neoforge issue https://github.com/neoforged/FancyModLoader/issues/194
Relevant nightconfig issue https://github.com/TheElectronWill/night-config/issues/183

Nightconfig has had a possible fix unreleased since august, so while they're waiting i'd appreciate any fix or workaround that doesn't crash our players, like only saving this when exiting the game, instead of every time a change is made.

### Steps to reproduce

Option 1: press HUD keybind
Option 2: move for example the upgrades gui in a mekanism machine

### Minecraft version

1.21.1 (Latest)

### NeoForge version

Range of several, most recently on 21.1.90

### Mekanism version

10.7.7 (Latest)

### If a (crash)log is relevant for this issue, link it here: (It's almost always relevant)

https://mclo.gs/jg3prsl https://mclo.gs/CS1rpWA https://mclo.gs/ZftcWWP

**Comment by thiakil** [comment]
I can't actually reproduce this, but the linked commit should alleviate it
