### ISSUE TITLE
Some Mekanism Items disappear on the inventory 

### ISSUE THREAD

**Issue by kendragster** [mekanism/Mekanism#8288]
### Issue description

Idk if is some compat issue with my optimization mods but, when i open the inventory, for example, Quantum Entangloporter doesn't work well, shows the item tag and name but not the icon, i mean, i can take the item an use it normally, and renders ok in my hand, but is bugged on the gui.
![image](https://github.com/user-attachments/assets/80648294-029d-44b2-b1f4-717569dfb2f3)

### Steps to reproduce

Just openin the inventory

### Minecraft version

1.21.0

### NeoForge version

Forge Version 51.0.33

### Mekanism version

10.7.7 (Latest)

### Other relevant versions

also bugs on 1.20.1 but i see is not longer developed

**Comment by thiakil** [comment]
Given the other functional blocks in the tab are also missing, I'd say another mod is to blame. You'll need to remove customisation mods until it fixes.
Perhaps the one making the background black with a rainbow border

**Comment by kendragster** [comment]
Hey dude, I finally fixed it; it was a mod named "Flerovium." [https://www.curseforge.com/minecraft/mc-mods/flerovium](url) After 7 hours removing and triying again with 256 different mods, I found it. Anyway, thanks. Also, the "Faithless" texture pack works well now.
