### ISSUE TITLE
Logistical transporters do not disconnect with redstone

### ISSUE THREAD

**Issue by taljaards** [mekanism/Mekanism#881]
Dev 176 and 177's (haven't tested the others) Logistical Transporters (and variants) do not disconnect when applying a redstone signal (regardless of their redstone configuration).
I don't know if this is intended or a bug, so reporting for safety's sake.

**Comment by stewbasic** [comment]
If this is intended, could you clarify what is the effect of toggling redstone sensitivity on a logistical transporter?
