### ISSUE TITLE
5.7.0.11: Console spam (Invalid tier identifier when retrieving with name.)

### ISSUE THREAD

**Issue by jalapeno777** [mekanism/Mekanism#984]
The server has started recently spouting a ton of console spam over and over.  Unfortunately I don't know the specific block that may be causing this.

Mekanism: Invalid tier identifier when retrieving with name.

Any advice on how to fix this or a method to suppress this error (assuming it can be safely ignored) would be much appreciated

**Comment by robhawkes** [comment]
I've been seeing this with 7.1.1 – it's easily replicatable and happens whenever I look at an energy cube with the rotating object inside of it. If the energy cube doesn't have the rotating object inside then the error message doesn't appear.

Let me know if I can provide more details.

**Comment by Rodg88** [comment]
I've been getting this too, with Mekanism-1.7.10-7.1.2.157 in Regrowth pack 0.6.5, whenever I'm looking directly at an energy cube.
